### ISSUE TITLE
Push to talk not working with Mac OS X Mavericks

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1003]
I am running Mumble 1.2.4 and installed Mac OSX Developer Preview 1. Mumble no longer recognizes my PTT keystroke. I cannot reset the stroke (though it will accept mouse button presses)

Checking Apple's side, Apple moved assistive devices to the Privacy Setting under Security and Privacy, yet Mumble doesn't seem to be registered.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1003/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/1003/attachment/Screen%20Shot%202013-06-24%20at%209.06.04%20PM.png*

**Comment by Avatat** [comment]
I checked it on MacOS 10.15.4 and Mumble 1.3.0 - buttons assignment works fine.
@Krzmbrzl, can we close the issue?

**Comment by Krzmbrzl** [comment]
yes. Thanks for testing! :)
