### ISSUE TITLE
Push to talk suddenly stops working

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1005]
I've been using Mumble close to a year and today my push to talk key stops working. I've tried rebinding it to other keys and eventually it stops working. If I leave the setting window up and hit APPLY push to talk works... but that's not really something I want to be doing when I'm in the middle of a game.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1005/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/1005/attachment/DxDiag.txt*

**Comment by Krzmbrzl** [comment]
Does this issue persist in 1.3?
