### ISSUE TITLE
Recording is mute after minute 43

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#1006]
I used the Mumble client 1.2.3 on Linux (Opensuse 12.3) to record a three hours long mumble session to a Flac file. All seemed to work well until I hit the "Stop" button to stop recording. The client froze, and I had to kill it manually. When I investigated the recorded file, it turned out that it was overly long (hundreds of hours) and only the first 43 minutes contained an actual recording. The rest was mute.

Another user in the same session made a similar experience, although I don't know which Mumble version and operating system he used.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1006/ ._

**Comment by llelectronics** [comment]
I can reproduce it with 1.3.0~425~g6f2552d. It is reproducable though it does not appear exactly after a couple of minutes. But on every record basically (not if it is a very short one though) 
It also happens with flac output format
