### ISSUE TITLE
Python scripts incompatible with ICE 3.5.0

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1007]
Starting with v3.5, the ICE Python wrappers have changed the API used in the Python scripts shipped with murmur (such as testdynamic.py) as well as the convenience mice.py script. It seems that the IcePy::Operation method now requires a tenth argument, indicating the format (defaulting to Ice::DefaultFormat when None is passed). However, this fix doesn't seem enough, since Python strangely segfaults when passing None as format parameter... Attached is the modified testdynamic script including the formatting parameter.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1007/ ._

_The following attachments were added on the original item:_
- _https://sourceforge.net/p/mumble/bugs/1007/attachment/testdynamic.py_

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you know the status of this in 1.3?

**Comment by davidebeatrici** [comment]
No changes:
https://github.com/mumble-voip/mumble/blob/78fefb4a2094bb22919598b87ca1628bb9eeda60/scripts/server/ice/testdynamic.py#L10

**Comment by ZeroAbility** [comment]
Was this resolved?

**Comment by Krzmbrzl** [comment]
Yeah, kinda - we removed the scripts from this repo ^^
