### ISSUE TITLE
Unable to turn Noise Supression Completely

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1009]
As topic says.

I noticed that i get less hiss no matter what i do with Mumble.
I thought, that maybe it was the encoding (opus), but that wasn´t the case.
And i tried changing Noise Suppression up and down (had it on off), but it didn´t change it.
Or well of course increasing made a change, but turning it On and Off didn´t make any change.

I also tried recording Mumble and Normal recording of the mic at the same time.
And as i thought, the normal recording was cleaner but had a bit more hiss.
But the mumble sound , not sure how to describe it, but not as clean and sharp.
Noise Suppression always makes sound like that more or less, it´s the drawback.

Can you please look into it.
I prefer to have it completely turned off, as i don´t have a extremely noisy mic, so Noise Suppression just makes it sound worse.

Thanks!

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1009/ ._

**Comment by mkrautz** [comment]
Noise suppression set to off does indeed remove noise suppression.

But it doesn't remove all preprocessing.

**Comment by davidebeatrici** [comment]
Closing in favor of #3323.
