### ISSUE TITLE
Incompatibility with Mumble/WoW (Mavericks)

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1010]
Mac OSX (Mavericks Developer Preview 2)
World of Warcraft Version 5.3.0 (17128) Release x64 Post Patch 7/2/2013
Mumble 1.2.4

When Mumble is running, now WoW quits. Here is Blizzard's diagnostic ID: 63A85162-5EDB-43DE-89CE-8D4F67676D18. I can't find any logs to provide details. Blizzard's error reporter only provided that reference number.

Mumble/WoW worked fine before the 7/2 rolling restarts. 

Reporting to WoW as well, but wanted to let you know. 

I do not know, yet, if this is a Mountain Lion issue or a Mavericks one.

Interesting note. If you launch WoW before Mumble, everything works fine. If you launch Mumble before WoW, WoW crashes.

*This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1010/ .*

**Comment by mkrautz** [comment]
This should be fixed in Git.  I will spin out a new snapshot as soon as possible.

**Comment by nrw2001** [comment]
building current git.  will test and report.

**Comment by mkrautz** [comment]
Yeah, seems like the build didn't go through -- sorry.  I will check on it later today.

**Comment by nrw2001** [comment]
perfect!  so happy to have this back!

**Comment by toborrow** [comment]
Does the last snapshot include the bug fix? I just tested out on 1.3.0~540~gedd5509~snapshot, still causing crashes on wow launch if overlay is activated...

**Comment by nrw2001** [comment]
Yes. The snapshot fixed the issue. If you are still having crashes. UN install the OVERLAY from within the mumble settings and then install the overlay from within mumble settings. The update does not auto update the overlay files. Hope that fixes it for you.

**Comment by toborrow** [comment]
Ok, I can confirm that enabling the overlay does not crash wow anymore. However, I have no overlay at all, despite resetting to default settings...

**Comment by mkrautz** [comment]
@toborrow See https://github.com/mumble-voip/mumble/issues/1561
