### ISSUE TITLE
"Move" privilege allows comment reset of other users

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1016]
In addition to the ability to move users into other channels, the "Move" privilege also allows any user with this privilege enabled to reset/erase the comments of other users.

This seems to be a bug, as there is no indication that this extra ability is granted with this privilege.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1016/ ._

**Comment by alexscorer** [comment]
I have submitted PR#4196 as a fix for this, using the change that @bontibon suggested. Although I feel this may be only be a temporary measure before something more robust is implemented, this is a quick way to close this issue that'll makes sense.

**Comment by Krzmbrzl** [comment]
Reading what has been written here I think that maybe the best idea would be to tie this permission to the `Ban` ACL. I do like the argument of Resetting comments and avatars should be granted to moderators but not other users. To me neither the `Move` nor the `Register` ACL seem to be exclusive for a moderator role. In fact I can see lots of situations in which one or the other is given to non-moderators for various reasons.
Banning on the other hand is something that I'd consider to be very moderator-specific so following this argument I think this might be the best choice here. What do you think?

**Comment by bendem** [comment]
Much better, I like that idea.

**Comment by streaps** [comment]
I don't think there is a one-size-fits-all solution (by moving it to another ACL), it really should be a separate permission/ACL.
