### ISSUE TITLE
WASAPI problems on MacBookPro with Bootcamp

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1021]
hte_ on IRC reports that using WASAPI on his MacBookPro using Bootcamp+Win8 makes his laptop lag:

21:51 < hte_> Hello people, i have a question. I'm running mumble in windows 8 (macbook pro with bootcamp), when i try to play something with 
              mumble on it makes the game and especially the mouse lag. I was told i have to change my sound driver/system from WASAPI -> 
              DirectSound but for some reason the selection is gray and does not let me do that. Even though DirectSound works fine with 
              Teamspeak. Can anyone help me out?

I suggested to try WinXP compatibility mode to use DirectSound, and that seemed to fix it:

22:14 < hte_> mkrautz: Win XP compatibility mode seemed to fix the problem. It's not entirely reliable result since this time we had much less 
              people on the channel.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1021/ ._

**Comment by mkrautz** [comment]
We should check whether this is the case on newer MacBooks.

Up for grabs.

**Comment by Krzmbrzl** [comment]
I guess that we can close this issue until someone encounters it again. Until then I'd consider it fixed/not too important
