### ISSUE TITLE
Balloon tip text not visible

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1023]
Notifications are displayed as empty yellow baloon tips; the text inside the popup is not visible.
OS: Xubuntu 13.04 (Xfce)
Mumble is installed from the Ubuntu repository.
Style is set to System default.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1023/ ._

**Comment by Hartmnt** [comment]
I am using Mumble and XFCE for the better part of a decade (including various versions of Ubuntu)
Never have I ever encountered Mumble spawning empty system notifications.

If in the future that happens to anyone again, please open a new issue.
