### ISSUE TITLE
"Next" button disabled when importing certificate (Linux)

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1025]
I am trying to import a certificate.  I have completed the "Import from" field and the "Password" field but the "Next" button remains disabled.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1025/ ._

**Comment by bontibon** [comment]
Cannot reproduce in ad1ed221148cf6e721529f8ff36af45ce4ec5fed.

This report was probably due to OP typing an incorrect password. There should probably be some feedback given to the user that the given password is incorrect.

**Comment by mkrautz** [comment]
Agreed.

It's not immediately obvious that your password isn't being acccepted.
