### ISSUE TITLE
Can't connect to any Server

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1026]
A while ago Mumble was rejecting me from accessing a Server, and it kept saying that either the password was wrong (it wasn't) or my Username was wrong (it wasn't). 

But now, even when I select a Mumble Server, it won't even let me connect. The button is greyed out like I can't click it. I'm trying to access the World Nobles Server from a game site, and have been unable to for months.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1026/ ._

**Comment by mkrautz** [comment]
The button being greyed out would typically mean that DNS hasn't been resolved yet.

Since this is mostly a support request, I'll close this. (It's also quite old...)
