### ISSUE TITLE
poor defaults lead to poor sound and bad initial experience

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1027]
Mummle 1.2.4, at least under Windows and Linux, has poor default settings which lead to crappy sound quality for Mumble noobs who won't know what the problems are or how to fix their sound without experimentation or help off an experienced Mumble user.

The main culprit here is the Amplification setting under Config -> Settings -> Audio Input which bizarrely defaults to 20x amp hence distortion is the default for most new Mumble users. This should be set to 1.0 by default.

The other poor default leading to unpleasant audio is the audio compression quality, which is too low by default. I keep it at 96K (max) and that brings good results. Maybe it need not be quite that high but it should be higher by default.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1027/ ._

**Comment by Krzmbrzl** [comment]
Now that Opus is the standard, I consider this issue as outdated. Please let me know, if this isn't the case
