### ISSUE TITLE
Mumble crash on startup with AMD Athlon XP 3200 (SSE)

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1028]
As reported in the forum https://sourceforge.net/apps/phpbb/mumble/viewtopic.php?p=4053#p4053
the Mumble client crashes on Windows XP with a AMD Athlon XP 3200.

The last version that does not have this issue is reported to be mumble-1.2.4-rc1-12-gdab8157.msi, which according to mkrautz is the last version from the old build system.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1028/ ._

**Comment by mkrautz** [comment]
I test 1.3.0 on Windows XP with older CPUs (SSE only) via QEMU regularly. The current build should work.

**Comment by davidebeatrici** [comment]
Latest snapshot working fine with a Pentium III emulated by QEMU.
