### ISSUE TITLE
Crash report on startup

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1030]
I have installed Mumble on my computer several times, uninstalled, cleaned the registry and reinstalled, and every time I try to launch the program, the crash report shows up without it even launching. I am running WINDOWS7 HOME PREMIUM 64, Inter(R) Core(TM) i5-3570k CPU @ 3.40GHz, 8GB of RAM. I have tried running it as adiministrator, and still achieve the same results.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1030/ ._

**Comment by bontibon** [comment]
Unless more information can be obtained about this issue, it should probably be closed.

**Comment by mkrautz** [comment]
I will close this. As @bontibon says, there is not enough information here to diagnose the problem.
However, if the reporter has sent in crash reports, perhaps something can be seen in them.
