### ISSUE TITLE
Mumble leaks DNS when using a proxy

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1033]
Mumble leaks DNS requests when the network settings have been configured to connect via a proxy or a SOCKS5 proxy. This has been tested with Wireshark on Debian Wheezy. 

What should happen is that DNS requests are resolved by the proxy network and are not sent to the host network at all. 

*This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1033/ .*

**Comment by ioerror** [comment]
I've just been bitten by this bug - would it be possible or welcome to add an option to refuse all DNS requests?
