### ISSUE TITLE
dd_meta_index_set: fd=1024 is not less then limit max_ifd=1024 or negative. Execution aborted.

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1034]
Hi,

When starting the static 1.2.4 linux binary file we're seeing:
murmur.x86-1.2.4: fd_meta_index_set: fd=1024 is not less then limit max_ifd=1024 or negative. Execution aborted.

We have a lot of virtual servers so we're expecting to need a lot of file descriptors.

Thanks!

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1034/ ._

**Comment by mkrautz** [comment]
Closing in favour of #2751.
