### ISSUE TITLE
Server suggests to choose nickname to registered user. 

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1036]
When you are connecting to a server which was announced via bonjour, it suggests you to choose a nickname, even if you are registered on this server. I think this is unnecessary, because the nickname will be replaced with the registered username anyway.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1036/ ._

**Comment by Krzmbrzl** [comment]
I suppose this can be closed. If someone still encounters this, please report here.
