### ISSUE TITLE
Connection to server dropped due to certificate issue, user not informed why

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1037]
I was unable to connect to any Mumble server (including my private team one). Every connection attempt was immediately dropped with "Server connection failed: The remote host closed the connection.".

DireFog suggested it may be a certificate issue. I generated a fresh one within Mumble and I could connect to servers.

I would consider it a bug that an issue with the client certificate is not told to the user for the reason that the connection failed. Having looked at the server log for my private team's server I found this:

> SSL Error: The root CA certificate is not trusted for this purpose

This should be relayed to the client.

My certificate in question is signed by my own CA, which would explain the trust issue with the server. I found this rather odd as it is signed by the same CA as defined in mumble-server.ini (sslCA).

I can attach the public certificates if needed.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1037/ ._

**Comment by Krzmbrzl** [comment]
Was anyone able to reproduce this issue with v1.3?
