### ISSUE TITLE
Text message flawed

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1042]
To Bohannas: Hi what up

> [11:56:02 PM] You were denied Text message privileges in The Tiki Bar (this is not a PG channel).

im sending a message to a user not the channel they just happen to be in that channel can you fix this  

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1042/ ._

**Comment by ZeroAbility** [comment]
Was this ever resolved? It also seems like a bug.

**Comment by Krzmbrzl** [comment]
From what is written here, it seems like intended behavior and so far no real arguments  were brought up to change it.
Thus far, I would say the arguments for "leave as it is" win :thinking:
