### ISSUE TITLE
Mumble freezes when I open the server browser

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1044]
When I open the server browser, or try to open Mumble without having the 'reconnect to last server on startup' option ticked, the program freezes. I can still talk to people if I'm connected to a server, but the only way I can do anything else is to force the program to close through Task Manager, and re-open it.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1044/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/1044/attachment/DxDiag.txt*

**Comment by Krzmbrzl** [comment]
I didn't experience anything like this with the latest version. Closing for now
