### ISSUE TITLE
Audio outputs to all Channels of Audio-Device

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1045]
Mac OS-X 10.7 (or higher)

i'm using a multi-channel Audio-Device (RME Fireface400 in this case).
Mumble (tested with 1.2.3 and 1.2.4) has a bug with such devices as it sends all audio out to ALL(!) Channels.

That means: in Case your Device has 10 audio-output channels, Voices are send to all 10 of them. So the sound is a) VERY loud (10 channels sums up) and b) it's impossible to record Microphone, Mumble-Audio and some other Inputs to separate channels with a recording software like reaper, garageband etc. 

Mumble should 
- either behave like every other software by sending out the output to channel 1 and 2 
- or, better(!), have an option where you could configure to which channels Mumble should output. This way you could let the microphone go out to channel 1 and Mumble to Channel 3 and 4 and maybe other Channels if you have Group-Chats and would like to have each member on a single Channel.

In it's current state, Mumble is unusable with Multi-Channel Devices as far as i know. If there are solutions/work-arounds i'm glad to try them

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1045/ ._

**Comment by RaspyAU** [comment]
Did anything ever happen with this issue? I've always had this problem with mumble outputting to all channels and its utterly ridiculous. I should be able to force Mumble to use 2.0 or just center speaker.

Even forcing Stereo via the Windows Sound panel doesn't get around it.

**Comment by mkrautz** [comment]
This isn't fixed yet.

But it's not a Windows issue. It's an OS X issue.

Are you sure this is the issue you're seeing?  If not, please file another bug on it, so we can track it. Thanks!

**Comment by RaspyAU** [comment]
Sorry, it's the exact same issue on Windows so I thought it'd be easier to keep it under the one issue thread. I'll make a new issue.

**Comment by RaspyAU** [comment]
Created a new Issue thread for Windows https://github.com/mumble-voip/mumble/issues/1555

**Comment by davidebeatrici** [comment]
Closing in favor of #1555.
