### ISSUE TITLE
Link Plugin v1.2.0 concurrency issues

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1050]
While making the [LinkAPI](https://github.com/zsawyer/mumble-LinkAPI) I stumbled upon a possible concurrency issue. After reviewing the code of the link-plugin to see how this is handled there I had to see that it is not being handled at all. 

Since the shared memory is freely available for read and write (as far as the OS permits) it is possible that - due to the frequent (per frame) updates - data might have changed during the consecutive reading of members in the struct. 

I am imagining a call chain of lm->xxx where the first call will get a result for dwcount 1 and the following lm->yyy will get the result for dwcount 2 - since there was an update in between. 

While this may actually be insignificant and possibly negligible it constitutes unexpected behavior. As one would expect all data collected "at the same time" (i.e. the [function fetch](https://github.com/mumble-voip/mumble/blob/master/plugins/link/link.cpp#L107) ) to be related to the same frame/dwcount, which is currently not guaranteed. 

The way to fix this imho is to use a semaphore. It might be best to use what ever the OS provides regarding semaphores or use dwcount to match data. So simply if there is a dwcount mismatch from before the first and after the last read then the whole data-group is invalid. 

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1050/ ._

**Comment by Krzmbrzl** [comment]
I don't think it's good practice to leave these possible race-conditions in there. Maybe we could add a secondary interface with locks in place. Then the user can chose if they want the safe version or the lock-free

**Comment by Krzmbrzl** [comment]
Having thought about it some more, I think that we need to be practical here. Given that no "real" issues seem to have been encountered due to these data races in 7 years, I don't think that this is something we have to worry about. In general of course this is an issue but we don't have the manpower to treat principle bugs that don't cause any trouble whatsoever.
