### ISSUE TITLE
Mumble does not stick to locked icon on the Ubuntu Launcher

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1052]
When the Mumble icon is locked on to the launcher, and then launched, it will simply generate a new icon on the launcher.

This is the only application to date I have exerpienced this with.

Ubuntu 13.10 Desktop 64-bit.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1052/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/1052/attachment/mumble-bugged-icons.png.png*

**Comment by eddie-dunn** [comment]
this is very annoying, is there a fix in progress?

**Comment by ubuntuaddicted** [comment]
I'm using Xubuntu 14.04 and I'm running mumble from a PPA. Sometimes the mumble icon disappears from my system tray and I have to click the application launcher again just to show it. Other times it will be there in the systray. Hopefully this is being addressed. Thanks for making such and awesome VOIP and messaging app. 
I would love it if I could control the audio of another user in my mumble server but that's another issue I suppose.

**Comment by Krzmbrzl** [comment]
My gut tells me that this could also be related to the used desktop environment.

Can anyone reproduce this with v1.3? And if so: which desktop environment are you using?
