### ISSUE TITLE
Protocol docs: make the use of protobuf more clear.

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1054]
Imisnew2 on IRC had a problem when trying to implement a Mumble client using the PDF protocol doc in the repo.

He receieved a Version message from the server and stared at the protobuf marshalled message's raw bytes trying to make sense of it. (It should be a uint32 signalling 1.2.4, but the protobuf encoding meant that he couldn't map it to anything that made sense.)

It seems the current protocol docs aren't clear enough about how protobuf is used in the protocol, and we should improve that:

17:06 < Imisnew2> mrkrautz: And marshall it as well ;) The documentation is VERY misleading about this, if you could pass it along.  It says it uses protobuf, but it looked like it was saying that the protobuf part was only the header (6bytes).  It even goes as far as how to break down the version portion (2bytes, 1byte, 1byte). I guess it's my fault for not googling protbuf after I saw it, heh.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1054/ ._

**Comment by bontibon** [comment]
Is this still an issue? The [protocol documentation](https://github.com/mumble-voip/mumble-protocol/blob/master/protocol_stack_tcp.rst) has:

> The prefix consists out of the two bytes defining the type of the packet in the payload and 4 bytes stating the length of the payload in bytes followed by the payload itself. The following packet types are available in the current protocol and all but UDPTunnel are simple protobuf messages.

Does more detail need to be added?
