### ISSUE TITLE
Mumble disconnects in a ghost fashion where it does not throw me off the server

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1055]
Using Mumble 1.2.3 that ships with Ubuntu 13.10 Desktop 64-bit, I am experiencing disconnects where Mumble does not reconnect until a good five or ten minutes pass.

I will remain in the channel. But I can not hear anyone, nor can I be heard. I already tried the forced TCP mode, but that did not change a thing.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1055/ ._

**Comment by InfernoZeus** [comment]
Same issue here, on Arch Linux with kernel 3.19.2-1-ARCH and Mumble package 1.2.8-3.

**Comment by Krzmbrzl** [comment]
I would have thought the regular ping should take care of things like this. Is this reproducible in Mumble 1.3?
