### ISSUE TITLE
[QT 5.x] ASIOInput.cpp compilation

### ISSUE THREAD

**Issue by Zuko** [mumble-voip/mumble#1064]
.\ASIOInput.cpp(205) : error C2664: 'IASIO::init' : cannot convert parameter 1 from 'WId' to 'void *'
        Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
.\ASIOInput.cpp(287) : error C2664: 'IASIO::init' : cannot convert parameter 1 from 'WId' to 'void *'
        Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast

**Comment by davidebeatrici** [comment]
These warnings have been fixed in 340c7b69fb80038c644d1d1b8aba5f1b0231d474.
