### ISSUE TITLE
Movable FPS and Time in overlay

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1068]
Currently the FPS display and Time are locked to the top left of the overlay.

I'm proposing a few things.

* Change the FPS display placement and time placement. In some games this covers information you may want to see. In Guild Wars 2 the Time covers up the Game Menu, Contacts and LFG, and Hero Panel.
* Change the format for the overlay clock (12h display option)

Being able to position these like you can with who's talking in the overlay would be very helpful.

**Comment by Kissaki** [comment]
Feature landed as 8bf9b0a1ed99d192946fed96cfbb206600f701dc for 1.3.0.
