### ISSUE TITLE
Mumble's "phone" PulseAudio role causes strange behavior

### ISSUE THREAD

**Issue by jpeddicord** [mumble-voip/mumble#1069]
Reviving http://sourceforge.net/p/mumble/bugs/831/

Because Mumble has a role of "phone" set on PulseAudio, this causes applications with a role of "music" or "video" to be muted when Mumble is active. As an example, if I open Banshee and play music, and then open Mumble, Banshee is muted (and paused). When I close Mumble, playback resumes. I can manually unmute the music stream myself, but any time I open another audio application or change the volume the streams will be re-muted again. This is due to module-role-cork in PulseAudio:

```
D: [pulseaudio] module-role-cork.c: Using role 'phone' as trigger role.
D: [pulseaudio] module-role-cork.c: Using roles 'music' and 'video' as cork roles.
```

Cork is designed to mute other streams when a phone role is active, presumably because it would be useful to mute/pause music when a phone call is received.

I would wager that the "phone" role was intended to be used for applications that have an active conversation going (such as Skype or a 1:1 VOIP call), and maybe not necessarily mass voice chat where there isn't constantly people talking.

See http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/ApplicationProperties/ PA_PROP_MEDIA_ROLE for available roles. I know it sounds less correct than "phone," but I would suggest a role of "game" or "production" as those don't have any side-effects.

I understand that this isn't necessarily a "bug" on your part (since the roles aren't very well-defined), but will cause issues on Linux and I feel you need to be made aware of this as more people upgrade to newer versions of Pulse that have this module enabled by default.

The "phone" is set as part of stream initialization: https://github.com/mumble-voip/mumble/blob/master/src/mumble/PulseAudio.cpp#L119

**Comment by morfikov** [comment]
According to [documentation](http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/ApplicationProperties/), which is:

    "music": for music streams from media players
    "game": for audio from games
    "event": for event sounds (i.e. button clicks, ...)
    "phone": for phone data (i.e. voip speech audio)
    "animation": for animations (i.e. Flash)
    "production": for audio production applications.
    "a11y": accessibility applications (i.e. screen readers, ...)`

The `media.role` should be set to `phone`, but instead it's set to `game`. 

I know that people don't know how to configure pulseaudio properly, but in the case of the ones that can do it right, there's a problem, because, for instance, I have the following setting:

    ### Cork music/video streams when a phone stream is active
    #load-module module-role-cork
    load-module module-role-ducking trigger_roles=phone ducking_roles=music,video,game volume=60%
 
Which lowers the volume of `music`, `video`, and `game` streams to 60% when `phone` stream appears.

**Comment by maxmati** [comment]
You are right but nature of group voice chat like mumble is different then typical VoIP. When you are connected to mumble server you can't assume that you are paying full attention to the talk.
In fact there is no good role setting for software like mumble.

**Comment by morfikov** [comment]
Why not? If people don't want this feature (auto mute), they can simply disable it in the pulseaudio config file, and that's the right way to do it.

**Comment by maxmati** [comment]
But they still can have some VoIP phone and may want auto mute. I don't know if there is possibility to turn on/off per program.

**Comment by morfikov** [comment]
There is an option:

    $ PULSE_PROP='media.role=phone' mumble

**Comment by maxmati** [comment]
So i think that we should set this role which will make more users happy.
