### ISSUE TITLE
EVE Online Rubicon and Mumble Overlay

### ISSUE THREAD

**Issue by Attoy** [mumble-voip/mumble#1072]
Rubicon was deployed today switching the client from DX9 to DX11, the mumble overlay doesn't work anymore if the Eve client starts in DX11 mode, it still works if forced to run in DX9 mode.

I'm running Windows 8.1 and the latest Mumble version available (1.2.4-183-g7f976ed)

**Comment by davidebeatrici** [comment]
Fixed via #1560.
