### ISSUE TITLE
1.2.4 install issue

### ISSUE THREAD

**Issue by jokerswild** [mumble-voip/mumble#1076]
Can't install 1.2.4 on my son's laptop. When I run it, I get some error about needing to locate mumble-1.2.4.blah blah.msi but it never finds it & searching the drive doesn't find it. 

Also have concerns that it wants to completely disable the antivirus software before it installs.

Any help would be appreciated
![mumble 02](https://f.cloud.github.com/assets/6026601/1610130/fbd11c7e-556c-11e3-805f-8b97a04d55b0.png)
![mumble 03](https://f.cloud.github.com/assets/6026601/1610131/fbd23b2c-556c-11e3-9250-ca14e5b34d4c.png)
![mumble error 01](https://f.cloud.github.com/assets/6026601/1610132/fbe8c8ce-556c-11e3-9150-e9aefb33296b.png)

**Comment by mkrautz** [comment]
Sorry for bumping this, but there is no such tool.

The easiest way to fix this would be to redownload the installer from http://mumble.info/snapshot/ and put it in the path expected by Windows (C:\Users\Jesse\Documents\mumble[...].msi).

That should fix it.
