### ISSUE TITLE
World of Tanks overlay does not display

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1079]
From #177 (also see http://mumble.sourceforge.net/Overlay#Incompatible%20games)

World of Tanks does not display an overlay.
D3D9 and DXGI is being injected, but not 10 or 11. The previous assumption (and report) that it uses D3D11 seems to be false.
Checking in procexp, loaded are:

* d3d8thk.dll “d3d8thk”
* d3d9.dll
* (D3DCompiler_43.dll)
* d3dx10_43 “Direct3D 10.1 Extensions”
* d3dx9_31.dll
* D3DX9_43.dll “Direct3D 9 Extensions”

Notably no dxgi.

So I guess it is using 10.1, and we are not compatible to it yet.
Would have to be investigated further.

**Comment by Kissaki** [comment]
No longer seems to be an issue.
The WorldOfTanks.exe process has d3d11.dll and d3d9.dll and d3dx9_43.dll loaded.
The overlay displays fine.

**Comment by mcfall-keystone** [comment]
The display no longer works with current version of WOT... i tried adding the d3d11.dll and tried the d3d9.dll the d3d9 makes it so the land is see thru
