### ISSUE TITLE
Emit specific compiler error when building without CELT 0.7.X

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble#1080]
Currently Mumble will fail to build when no CELT 0.7.X is available which is the intended behavior. However as the need for the specific CELT version isn't intuitive users will naturally try to get it to build with the newest version of CELT they can find (see e.g. #184 ). We should make the compiler output explicit errors in such occasions explaining the need for a specific version.

**Comment by Krzmbrzl** [comment]
@davidebeatrici are we even still supporting celt? :thinking:

**Comment by davidebeatrici** [comment]
Only CELT 0.7.0.

**Comment by ZeroAbility** [comment]
Since we appear to be removing CELT support, can we consider this closed?
