### ISSUE TITLE
Confusing user left/user disconnected message notification

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1086]
cc @frmimue, @Tarun80

The new functionality where we get both a "user left" and a "user disconnected" notification is confusing when used on Windows (implemented in https://github.com/mumble-voip/mumble/commit/5b3a406f36c17888cc75fb57dd831161fa5908cb)

I only get the "user left" notification bubble when on the desktop, so I don't immediately notice that a user has disconncted.

**Comment by mkrautz** [comment]
@bontibon proposed a change that simplifies the logic a bit:

#1577
f5affcd43bb6fe8dcd42bd046b8302e0a78ba624

I think this is better than what we've had for a while now.
Let us know what you think.

**Comment by Tarun80** [comment]
@mkrautz: Since this has been implemented, is it time for this issue to be closed?
