### ISSUE TITLE
Stop audio noise suppression while muted to reduce CPU load

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1089]
Our noise suppression needs to know the base-volume level (noise level) of the users surroundings compared to his voice to be able to effectively filter. This causes a constant CPU load.

While muted this seems unnecessary - it should be halted.
- This halting mechanism has to be implemented for all audio systems (PulseAudio, WASAPI, ASIO, potentially JACK).
- Test whether halting worsens the effectiveness or accuracy of the noise suppression algorithm.

PR #171 implements the halting for PulseAudio and may thus be a good starting point.

**Comment by Two-Tone** [comment]
This is still an issue, even on high end hardware like my i5-3470

**Comment by iluvkunena** [comment]
Hi, this may be the issue I'm also experiencing.  Whenever I give a constant whistle and any steady sound for more than 4 seconds, Mumble automatically mutes this.  I've tried several servers, and made sure the suppression settings we set not to attenuate, but it still does this.  This issue doesn't exist with Skye or other voip programs, it is only doing it with Mumble.  If this setting must be in place, could it be changed to 30 seconds instead of only 3 to 4 seconds?

**Comment by mkrautz** [comment]
@iluvkunena Do you mean that Mumble removes the sound you are making, or that Mumble is attenuating the volume of everything you say?

**Comment by mkrautz** [comment]
@Two-Tone I take it you are mostly having issues with this on Linux?

**Comment by Two-Tone** [comment]
Nope, I've had this issue on Linux and Windows.  No Mac here, so I can't say if it affects Mac users as well but I assume it does.

**Comment by iluvkunena** [comment]
It completely any constant sound longer than 4 seconds in length.  Sounds in variable tone (speech) reactivate it though.  It is almost like some type of DSP noise reduction filter kicks in, but it kicks in too soon.  I've turn off all the auto attenuate settings, it appears to be something built into the firmware.

**Comment by mkrautz** [comment]
@iluvkunena And just to make sure - you've tried to set Noise Suppression to "off"?

**Comment by iluvkunena** [comment]
Yep it's off..

**Comment by itsrachelfish** [comment]
Please merge a fix for this. Using 20-25% cpu in an empty channel where nobody is talking is completely absurd !

**Comment by Krzmbrzl** [comment]
This issue will now be tracked alongside others in #5408
