### ISSUE TITLE
Overlay still showing even when disabled in client settings

### ISSUE THREAD

**Issue by iggi-** [mumble-voip/mumble#1090]
The overlay is not disabling for me when I uncheck the option in the settings. I have rebooted the program affected by the overlay, but it still does not unload the overlay.

**Comment by davidebeatrici** [comment]
This probably have been fixed. If you still experience the problem, please create a new issue with details on which program are you using the overlay with.

**Comment by mkrautz** [comment]
No, I think this is still relevant.

**Comment by davidebeatrici** [comment]
Even after all the changes done to the overlay system?
