### ISSUE TITLE
Random Mumble Client Freezes

### ISSUE THREAD

**Issue by iggi-** [mumble-voip/mumble#1091]
In and out of games I'm getting a weird freezing of the mumble program. The program locks up and the window turns grey like it is not responding. The overlay locks in the position it was when the program freezes. I can still hear others in the room normally, but the overlay does not light up their name. If I am talking when the program freezes, my mic is still open and everyone can hear what I am saying while the program is frozen and it does not release my mic until the program comes back from it's frozen state. This happens in and out of games, I can seem to find a correlation.

Windows dump file is located here (it was too large for github):
http://www.mediafire.com/download/3cu2vr5ab04cv93/mumble.zip

The password was given to dD0T in IRC.

**Comment by sandersaares** [comment]
I can confirm that adding Spotify to blacklist seems to have fixed the problem for me. It was occurring exclusively when Spotify was running.

**Comment by JoelTroch** [comment]
I'm not 100% sure about this, this issue could be connected to #1527, need more investigation.

**Comment by DanielMarquard** [comment]
This has been happening to me for months on Windows 8.1 whether or not a game is open. Interesting to see that Spotify could be causing this, which I have open all the time. Testing that theory now.

**Comment by Tarun80** [comment]
Just to add information, Spotify is not installed on my machine.

**Comment by DanielMarquard** [comment]
Terminating Spotify seems to have fixed it for me. Hope you can get yours fixed, @Tarun80.

**Comment by Tarun80** [comment]
I had my entire computer lock up after a few days. Once I disabled the overlay the problem stopped completely.

**Comment by Kissaki** [comment]
Before someone else checks:
Spotify was added to the default overlay blacklist in e5b6dac26dd317ca5115f78ef3ebc84aa7ca0a7b

**Comment by niwinz** [comment]
The same happens on linux version (1.2.19)

**Comment by trqx** [comment]
same here,
random freezes, linux amd64 mumble 1.2.19, no overlay, no desktop environment.

**Comment by 320x200** [comment]
same here.

random freezes of the GUI, Debian Sid, Mumble 1.3.0~git20190125.440b173+dfsg-2, no overlay, just evilwm, gajim and firefox running.

**Comment by ZeroAbility** [comment]
Since moving from Qt 4 to Qt 5, is this an issue anymore?

**Comment by 320x200** [comment]
following up my last comment (from 2019), I haven't experienced a problem in a long while (mumble is now 1.3.4 on sid). So I guess something at some point got fixed somewhere, and I'm very grateful for it :)

**Comment by Krzmbrzl** [comment]
Great! Thanks for letting us know :)
