### ISSUE TITLE
Audio issues on TCP clients connecting to murmurd running on armel

### ISSUE THREAD

**Issue by Uragon** [mumble-voip/mumble#1093]
Running a mumble-server in a SheevaPlug ARM SoC, I have noticed that some users are unable to hear anybody else, including themselves in server loopback mode. I was able to reproduce this by selecting the option to force tcp in the mumble client. Audio reception immediately broke for this client, while sending would still work. Disabling force TCP and going back to UDP connection would immediately fix the problems.

My assumption is that this is some kind of endianness issue in the server software. A bit of more detailed information about the server below:

$ uname -a
Linux plug 3.2.0-4-kirkwood #1 Debian 3.2.51-1 armv5tel GNU/Linux
$ /usr/sbin/murmurd -version
<F>2013-12-12 09:51:46.957 /usr/sbin/murmurd -- 1.2.4-0.2+0coredump2+wheezy
$ cat /etc/debian_version
7.2

**Comment by Krzmbrzl** [comment]
Can this problem be reproduced with the latest 1.3 version?
