### ISSUE TITLE
User Properties - Opus

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1098]
Would it be possible (and worthwhile) to return what version of Opus is in use instead of (or in addition to) Opus: Supported?

Perhaps something like:
**Opus**: 1.1 (Supported)

Side question, but shouldn't things such as OS, Version, etc. all have a colon after them?

**Comment by bontibon** [comment]
Do you think this is still worth doing, @Tarun80? This would require adding a string field in the `Authenticate` message to hold the return value of `opus_get_version_string()`.

/cc @mkrautz

**Comment by Tarun80** [comment]
Yeah, I do think this would still be worthwhile since Opus: Supported is reported. A little extra info shouldn't hurt.

**Comment by Krzmbrzl** [comment]
What would that information be needed for?

**Comment by Tarun80** [comment]
Considering this was opened almost eight years ago and last touched on over six years ago, far too much time has passed to touch on this again.

I can only assume it was like I said in my original post - report the version number and extra bits like that.

I unfortunately had to move on to Discord for my guild's needs.

**Comment by Krzmbrzl** [comment]
Roger that. 

Without an actual usecase for this kind of information, I will close this issue. If someone requires this kind of info, comment here and share what you need it for and we can reconsider.
