### ISSUE TITLE
Razer Tartarus causes mumble to hang up whenever plugged in

### ISSUE THREAD

**Issue by Killomatic** [mumble-voip/mumble#1101]
So I just got a new Razer Tarturus (Keypad for left hand) for christmas and I found out that whenever it is plugged in, Mumble will freeze (I can't click on anything but i can hear and interact with people). Whenever I remove it, it unfreezes.

**Comment by Krzmbrzl** [comment]
Do you happen to be able to reproduce this with version 1.3?
