### ISSUE TITLE
Mumble deadlock on launch (Ubuntu raring)

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1107]
Steps to reproduce:
1. Launch raring VM with a single CPU core allocated to it.
2. Run mumble:

`mkrautz@mkrautz-raring ~/mumble/release $ ./mumble
 [hang...]`

This version of Mumble is built with the following qmake flags:
`qmake-qt4 -recursive main.pro CONFIG+="release no-speechd no-embed-qt-translations"`

Stack trace at https://gist.github.com/mkrautz/8326961

**Comment by Krzmbrzl** [comment]
Dies this also apply to Mumble 1.3?

**Comment by Avatat** [comment]
I ran Ubuntu 18.04 VM, added Mumble's PPA, installed Mumble 1.3.0, and it worked OK.
@Krzmbrzl, can we close the issue?

**Comment by Krzmbrzl** [comment]
I guess so, yes :)
