### ISSUE TITLE
Overlay does not display in Chivalry: Medieval Warfare

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1111]
Chivalry loads both d3d9 and d3d11, but the overlay does not display with a recent 213-g1eefaab snapshot.

Check why the overlay does not display.

Analysing the debug text log:
When starting chivalry, a lot of processes seem to spawn that hookes get injected to.
The UDK.exe process ID does not seem to receive hooks at all.

**Comment by Krzmbrzl** [comment]
Does this still apply to version 1.3?
