### ISSUE TITLE
OSInfo: getDisplayableVersion does not detect Pro vs. non-Pro for Windows 8 and 8.1.

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1114]
When running on Windows 8 or Windows 8.1, the new 'displayable version' code in OSInfo does not detect "Pro" editions correctly.

**Comment by ZeroAbility** [comment]
Support for Windows 8/8.1/2012/2012R2 has ended:

https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93

It appears we addressed this for Windows 10 (which should have worked for 8):

https://github.com/mumble-voip/mumble/pull/2447

**Comment by Krzmbrzl** [comment]
Given  the linked PR, I'll close this as completed.
