### ISSUE TITLE
DX11 Overlay Hangs EVE Online - Memory Leak

### ISSUE THREAD

**Issue by Prodigalhacker** [mumble-voip/mumble#1123]
Since the overlay appears to have been updated to support DX11 in release 1.2.4-213-g1eefaab, EVE Online hangs shortly after logging into the game. Game does not hang when the overlay is disabled. Happening on Win7 x64 on two different computers consistently, both of which had the overlay working without issue when the game was using DX9.

EVE Hangs rather than crashes, i.e. Windows comes up and says that it's not responding, asks if you want to wait or close it. The mumble overlay itself does work, at least until the game hangs.

Debug logs here: http://sourceforge.net/apps/phpbb/mumble/viewtopic.php?f=4&t=1234

**Comment by hnsr** [comment]
Ran into this issue today with 1.3.0~567~g3223c8a~snapshot running on Win 8.1 x64. What appeared to be happening was if I started EVE with Mumble running (but not connected to anything), EVE's memory usage would slowly grow up to ~4GB at which point it froze and I got the dreaded 'application has stopped responding' message. I guess that makes sense with EVE being 32bit.

Starting EVE without Mumble running was fine. However! ..starting EVE with mumble running but *also* connected to a server made it work fine as well, no more memory leakage. So it seems to only happen if Mumble is active but no connected (and so no overlay is actually being drawn). So for me that is a suitable workaround for now; it let me play EVE for hours without any issues last night, having mumble connected at all times.

**Comment by AxMi-24** [comment]
I just tried it on fully patched win 7 64 bit, Mumble 1.3.0~g3223c8a~snapshot and EVE running in DX11 move and the memory leak is there crashing the client in less than a minute. (mumble started and connected before I started the eve client).

However, I did notice that if I spam the speak button (thus making the overlay show up) the memory use goes back down. So if it's activated every 10-30 sec you could be fine for quite a while. Client was using 2 GB Memory (private) and single click on push-to-talk moved it back to 600 MB. This happens no matter who it is that is speaking.

**Comment by Prodigalhacker** [comment]
I can confirm the behavior in the previous 2 posts, I was just able to replicate it myself.

I tested with Mumble 1.3.0~567~g3223c8a with EVE in DX11 mode on Windows 8.1 x64, while running the task manager on a different monitor and watching the EVE client's memory use.

Memory use starts at around 600MB and rapidly climbs whenever there is silence on mumble. Just as AxMi-24 mentioned, tapping the PTS key resets EVE's memory usage to <700MB. Other people talking in the same channel on mumble (causing the overlay to display) does the same. EVE is stable and runs without issue until its memory use gets to about 3.6GB, at which point it hangs (my system has 16GB of RAM if that's at all relevant).

In retrospect, I think this also explains why when I was attempting to reproduce this issue last year the crash would sometimes take an hour and sometimes only take a couple of minutes...it's directly dependent on the amount of comms chatter going on.

**Comment by hnsr** [comment]
Ah, that explains why my workaround works. I have the overlay configured to always show when I'm connected (shows only myself and anyone currently keying up)

**Comment by Prodigalhacker** [comment]
The overlay has stopped showing up entirely in DX11 EVE for the last couple of snapshots. I'm currently on 1.3.0~598~g0128e7d.

Until yesterday or thereabouts it was working great as long as I set it to always display me when connected (as described above) but now it's not showing up at all.

**Comment by mkrautz** [comment]
We've switched to a new method of doing overlay injection.  Now, the builds ship with both an x86 and an x64 overlay.

When Mumble is running, do you see 'mumble_ol.exe' and 'mumble_ol_x64.exe' in your task manager? (Use the 'Details' view if you're on Windows 8+).

**Comment by Prodigalhacker** [comment]
I'm not on the computer with EVE & Mumble on it currently, though I'll check when I get home from work tonight.

I'm running the x86 Mumble client on Win8.1 x64, as the overlay never seemed to work with EVE if I used the x64 Mumble client. I'm assuming this is because EVE is a 32-bit application. Do I need to install the x64 Mumble client if I'm running a 64-bit OS?

**Comment by mkrautz** [comment]
No.  You can run either client.  Both should work.

**Comment by Prodigalhacker** [comment]
A third reboot appears to have fixed it (and I do indeed see both exe's in the task manager), though it appears to sporadically freeze both the mumble window and the overlay for the first several minutes after logging into the game. Audio send/receive still works throughout, and after several minutes everything appears to go back to working properly.

**Comment by AxMi-24** [comment]
1.3.0~598~g0128e72

Is still exhibiting above mentioned memory leak behaviour (leaking like crazy until overlay activates due to talking in channel at which point memory use resets to normal and starts leaking again)..

**Comment by leit512** [comment]
I am using 1.3.0~658~g3s46634 and i have the same problem. The eve client starts using more and more memory and crashed after 1 - 5 minutes.

I noticed that the problem only occurs when the overlay is hidden. What i active the option "always show myself"(and the overlay is therefore always-on) the eve client and mumble run stable for hours.

**Comment by Kissaki** [comment]
That this is only an issue when the overlay shows *nothing*, as in only talking users are displayed and nobody talks, is crucial here. Then indeed the memory use increases rapidly.
This is not an issue for a test program I just tried out, so it is something about how Eve 
I will analyse further later.

**Comment by mkrautz** [comment]
Update: still reasily reproducible...

**Comment by mkrautz** [comment]
Not present in D3D9.

**Comment by mkrautz** [comment]
When looking at Private Data for evefile.exe it grows tons of 4MB sections in Private Data at every refresh.

**Comment by mkrautz** [comment]
My first thought was the trampoline allocation in HardHook_x86, but that memory is allocated with PAGE_EXECUTE_READWRITE, where as the memory shows Read/write/WriteCombine in VMMap.

**Comment by mkrautz** [comment]
The memory size stays 4MB even if I only run EVE at 1024x768.

**Comment by mkrautz** [comment]
Once the overlay is re-enabled, the memory is *freed*. Hmh.

**Comment by mkrautz** [comment]
PR at https://github.com/mumble-voip/mumble/pull/2364 works around this issue.
