### ISSUE TITLE
OSX user menu, key shortcut

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#1134]
Hello,

I'd like to report bug (i think :)). On the OSX 10.9 while right-clicking on username no menu shows up. Right-clicking on room name works fine tho.

I have one more problem, with shortcuts. I cannot assign key other than fn, cmd, alt, shift and so on. I cannot assign any letters, digits or symbols.

Those where tested on stable (1.2.4) and 1.2.4-209-g00b3686. Beside that on testing version i cannot roll down function menu in shortcuts key assignment.

**Comment by Krzmbrzl** [comment]
Is this problem reproducible with version 1.3?

**Comment by Avatat** [comment]
I checked it on MacOS 10.15.4 and Mumble 1.3.0 - menu shows up for every right-click.
I can assign any key to a shortcut.
@Krzmbrzl, can we close the issue?

**Comment by Krzmbrzl** [comment]
Yes, thanks! :)
