### ISSUE TITLE
AudioWizard hangs at startup on OpenBSD (plus patch)

### ISSUE THREAD

**Issue by dcoppa** [mumble-voip/mumble#1138]
Hi,

I've ported mumble to OpenBSD, and we're using the PortAudio backend.

During my tests, I've found a convoluted threading issue that makes mumble hang at startup. This is 100% reproducible, at least on OpenBSD.

In PAAudio.cpp, around line 338, it will get caught in an infinite loop.
It relies on the PortAudioInput object being destroyed in another thread, thereby setting bRunning to false and telling it to exit the loop, which will never happen. Luckily, this bug is only exposed by the AudioWizard configuration stuff.

Skipping the call to restartAudio() from on_qsOutputDelay_valueChanged() while
the AudioWizard is starting up fixes this issue for me:

```
--- a/src/mumble/AudioWizard.cpp
+++ b/src/mumble/AudioWizard.cpp
@@ -308,7 +308,8 @@ void AudioWizard::on_qcbOutputDevice_activated(int) {
 void AudioWizard::on_qsOutputDelay_valueChanged(int v) {
        qlOutputDelay->setText(tr("%1 ms").arg(v*10));
        g.s.iOutputDelay = v;
-       restartAudio();
+       if (! bInit)
+               restartAudio();
 }

 void AudioWizard::on_qsMaxAmp_valueChanged(int v) {
```

Ciao,
David

**Comment by ZeroAbility** [comment]
Does this still occur on newer versions of OpenBSD and Mumble?

**Comment by klemensn** [comment]
> Does this still occur on newer versions of OpenBSD and Mumble?

Hi, I am currently maintaining OpenBSD's audio/mumble port.
The crash is no longer reproducible with Mumble 1.4.287 on OpenBSD/amd64 7.3-beta and this PR *not applied*,
but we still carry it as local patch.

I'll probably just drop it, the intial report certainly no longer holds true:

> During my tests, I've found a convoluted threading issue that makes mumble hang at startup. This is 100% reproducible, at least on OpenBSD.

The audio wizard completes fine, I can hear my own voice (and echo), the speex example is audible, just as expected.

**Comment by Krzmbrzl** [comment]
Thanks for letting us know!
