### ISSUE TITLE
Mumble freezes on selfmute when playback device is not available

### ISSUE THREAD

**Issue by obry** [mumble-voip/mumble#1143]
I use an external soundcard that is not always plugged in.
Say this soundcard was used in a session.
In the following session the soundcard is not plugged in.
I open mumble, press mute self (this should play a sound), and mumble will freeze.

It will also freeze on muting myself, if I change to the soundcard that should be actually used.

It will work without crash/freeze, when i choose the right soundcard and restart mumble.

Using mumble 1.2.4-0.1 on linux.
Regards + keep up the great work :)

**Comment by bontibon** [comment]
Confirming that this happens to me on Linux (Mumble 1.2.8 and [HEAD](https://github.com/mumble-voip/mumble/commit/bdcd5927d6424d7f2fc91ab3cb598dcbc676c430)).

**Comment by Krzmbrzl** [comment]
Closing this issue in favor of #1672. It seems to address the same issue, but provides mor input / activity.
