### ISSUE TITLE
GlobalShortcutX: no keys are caught when a Yubikey is plugged in

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1145]
sdaugherty reports on IRC that Mumble does not see global shortcut keypresses when a Yubikey is plugged in.

After discussing it for a bit, it seems like the Yubikey's /dev/input node is readable by the regular/console user, but no *regular* keyboards *are*. Mumble then happily treats the Yubikey it found as a valid keyboard, and doesn't fall back to any other input mechanisms, such as XI2.

12:49 < sdaugherty> I still can't bind keys in mumble, running 1.2.3 from packages on kubuntu 13.10 -I click to bind a key, see the "Press shortcut key" message, and then no keypresses are recognized to set the keybind.
13:21 <@mkrautz> sdaugherty: what does the lines prefixed with 'GlobalShortcutX:' in mumble's stdout output say when you launch mumble?
13:41 < sdaugherty> oh, that might explain things GlobalShortcutX: /dev/input/event6: Yubico Yubikey NEO OTP+CCID
13:42 <@mkrautz> cute. does it work if you unplug the yubikey? :)
13:43 < sdaugherty> GlobalShortcutX: Unable to open any keyboard input devices under /dev/input, falling back to XInput
13:43 < sdaugherty> GlobalShortcutX: Using XI2 2.0
13:43 < sdaugherty> and yes
13:44 <@mkrautz> hmmmm
13:44 <@mkrautz> so the XI2 path works if you unplug the yubikey?
13:44 < sdaugherty> I was able to bind my left shift key to PTT with no problem once I unplugged the yubikey
13:46 < sdaugherty> (in case you aren't familiar the yubikey shows itself as a keyboard in order to send passwords as keystrokes)
13:46 <@mkrautz> does it use XI2 when it's unplugged as well?
13:46 < sdaugherty> yeah, that was with it unplugged
13:46 <@mkrautz> ah ok
13:46 <@mkrautz> hmm.
13:49 <@mkrautz> sdaugherty: I suppose it also falls back to XI2 when it *is* plugged in? Or does it use /dev/input?
13:49 < sdaugherty> and plugging it in after starting mumble doesn't break anything
13:49 < sdaugherty> it uses /dev/input with the yubikey plugged in
13:49 <@mkrautz> ah
13:50 <@mkrautz> presumably, the Yubikey /dev/input node is readable by your regular user, but your keyboard isn't
13:50 <@mkrautz> which means the only keyboard it finds is the Yubikey
13:51 < sdaugherty> It would seem so, yeah - there's udev rules that make it readable and writiable by the console user for the config tool to work.
13:51 <@mkrautz> we should probably try to detect that... *sigh* blacklisting.
13:53 < sdaugherty> Might want to make sure you get the USB iDs for the other versions of the Yubikey if you do that, there's at least 2 other variations.
13:57 < sdaugherty> regular Yubikey and Yubikey Nano are just OTP tokens, and Yubikey Neo is both an OTP token and a smartcard.

**Comment by skobkin** [comment]
Seems to my problem with hotkeys is fixed now too.
