### ISSUE TITLE
Mumble 1.2.5 (Windows) hangs when launching - Black Magic Intensity Pro (internal)

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1151]
itaku reports on IRC that Mumble 1.2.5 on Windows 7 hangs when launching.

The computer has a Black Magic Intensity Pro (internal) card in it: http://www.blackmagicdesign.com/products/intensity/

Other people with the same card confirm the hangs (via itaku).

**Comment by Krzmbrzl** [comment]
Did anyone experience this issue with the current 1.3 version?

**Comment by ZeroAbility** [comment]
This needs tested with 1.4

**Comment by Krzmbrzl** [comment]
Better: This will be closed until someone reports that this is still an issue.
