### ISSUE TITLE
Use explicit OS in the auto-download SF.net URL in "New update available" log message

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1153]
User 'anonymous' reported on the blog that the 1.2.5 release's auto download link gave him the mumble-1.2.5.tar.gz file instead of mumble-1.2.5.msi. This was found to be because the machine's browser had a custom User-Agent set.

For now, I have updated mumble-1.2.5.msi to be the default download for 'Others' (SF.net's default for OS'es when it cannot sniff the UA). I feel this is generally fine, since it's our most downloaded product, and people who really _are_ on other OS'es can probably figure out what to do.

(Note: 'Others' does not include Linux, BSD and Solaris -- at least not as long as they make themselves known via their UA. The *nixes are served the mumble-1.2.5.tar.gz tarball by default)

The real fix for this would be to ensure that the SF.net auto-download link knows which OS we're really on. I'm not sure this is possible.

We could potentially also do a redirect on mumble.info.

**Comment by bontibon** [comment]
Is this still applicable, @mkrautz?

**Comment by hacst** [comment]
It's probably still applicable but imho no longer relevant. Close?
