### ISSUE TITLE
Mumble overlay crashes Firefox on Mac OS X

### ISSUE THREAD

**Issue by iay** [mumble-voip/mumble#1157]
As title: Firefox 27 crashes on startup under Mac OS X 10.9.1 if you have Mumble 1.2.5 already running with the overlay enabled.

Workround: Adding Firefox to the overlay blacklist alleviates the problem.

**Comment by davidebeatrici** [comment]
I'm closing this, as **firefox.exe** is in the blacklist by default and the overlay system heavily changed.

**Comment by mkrautz** [comment]
The blacklist changes haven't affected macOS yet. So I think the most sane thing is to keep this open for now.

**Comment by davidebeatrici** [comment]
Sorry, my fault. Even if I read that the user was on Mac OS X, I immediately associated overlay with Windows.

**Comment by Krzmbrzl** [comment]
I assume the blacklist has now arrived on MacOS as well? Thus I'll close this issue...
