### ISSUE TITLE
Razer Synapse audio plugin crashes Mumble on OS X

### ISSUE THREAD

**Issue by baurpowr** [mumble-voip/mumble#1158]
I've used mumble for a good year or so now but recently, starting about a week before 1.2.5 was released mumble has been crashing at launch. The main window shows up as if it's about to open the server connection list but before that happens it crashed completely. Occasionally I'll try to open it and everything will be working perfectly fine. However about 98% of the time this is not the case. Currently running Mac OS 10.9. The issue never happened in older versions, nor did it start happening once I upgraded to maverick. Only just recently.

**Comment by Krzmbrzl** [comment]
Can this be reproduced with mumble v1.3?
