### ISSUE TITLE
Update license display in about box

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble#1159]
Make sure to update the copyright date ranges in the license list before the 1.3.0 release. Also we should think about how to handle the license display in the "About Mumble" tab of the dialog. It correctly displays Thorvald's last contribution as 2012 but that's not very helpful there.

The options I see is to ditch that line alltogether, to change it into a range for the whole project with (maybe attributing to "The Mumble team"? IANAL. Would this be problematic?) or to put something completely different there.

**Comment by mkrautz** [comment]
Fixed.
