### ISSUE TITLE
Temporary channels can't be moved at all

### ISSUE THREAD

**Issue by lavoiesl** [mumble-voip/mumble#1162]
Currently, you can move channels and create temporary channels, but you cannot move a temporary channel in a channel where you cannot create channels even if you can create temporary channel.

If that seems rubbish, here is an example:

```
- Root
  \- Channel A  <- Temporary channels allowed
    \- My temporary channel 
  \- Channel B  <- Temporary channels allowed
    \- *I want to move my channel here*
```

Would that be hard to do ? Something like if a channel was created temporary, it can be moved to a channel where temporary channels are allowed.

**Comment by ZeroAbility** [comment]
Since the PR for this request was closed by the contributor, should we also close this? It seems to defeat the concept of a "temporary" channel to treat it like a permanent one.

**Comment by Hartmnt** [comment]
> t seems to defeat the concept of a "temporary" channel to treat it like a permanent one.

I do not think so. Moving temporary channels to other parent channels where you are allowed by ACL to create temporary channels seems like a valid use case to me. I might even consider this more of a bug or unwanted behavior, but that is up for debate.
Anyway, if there is no objection to the general concept, I will refurbish OPs original merge request myself.

**Comment by Krzmbrzl** [comment]
>  Anyway, if there is no objection to the general concept, I will refurbish OPs original merge request myself.

Sure, please go ahead :+1:
