### ISSUE TITLE
Client crash on launch

### ISSUE THREAD

**Issue by DavidVentura** [mumble-voip/mumble#1168]
I'm running debian testing, with mesa from git (oibaf ppa).
Upon running mumble as a regular user, it crashes (no window displayed): this is the (gdb) log http://pastebin.com/DwSmyg77
This is a config issue, running mumble as root works.

The same thing happened upon compiling master from git. If there's another log I can post to help, I'll gladly do so.

**Comment by Krzmbrzl** [comment]
I didn't encounter this problem with 1.3. Did you? If so, please let me also know, which OS you are testing this on.

I'll close this issue for now in the hope that this issue has been fixed by now. If that's not the case, please reopen it :)
