### ISSUE TITLE
Drop in-game GUI code

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble#1172]
We should drop the in-game GUI overlay code that can show the Mumble GUI in games. With the current way it is implemented it is unlikely to ever work in a fully consistent, bug-free way and the code used to enable it is very invasive, hard to maintain and rotting at this point.

The feature itself is a good idea and should be revisited in the form of specialized in-game GUIs.

**Comment by davidebeatrici** [comment]
Superseded by #3484.
