### ISSUE TITLE
Failed to load mumble_ol.dll in 248-g640b532 snapshot on Windows

### ISSUE THREAD

**Issue by bill-long** [mumble-voip/mumble#1176]
After updating to the 248-g640b532 snapshot, I'm getting the error indicating that mumble_ol.dll couldn't load:

!["Error dialog"](http://gyazo.com/aa2dfb16e6120c31175c538da1ef2936.png)

Process Monitor shows that it does open the mumble_ol.dll, but after that it starts looking for mumble_ol.dll.dll for some reason (notice the extra .dll).

This behavior does not occur if I uninstall the snapshot and run 1.2.5 - neither the error dialog, nor the looking for mumble_ol.dll.dll is observed in that version.

I'm not entirely sure what build this started with, as I hadn't updated my snapshot in some time.

**Comment by hacst** [comment]
Tested on a clean system. Seems to work.
