### ISSUE TITLE
Media-Keys don't work when mumble window is active

### ISSUE THREAD

**Issue by SvenNus** [mumble-voip/mumble#1177]
Media-Keys don't work when mumble window is active.

Using Roccat Ryos driver version: 1.32 Firmware version: 1.24
Mumble version: 1.2.5-248-g640b532
OS: Windows 8.1

**Comment by Krzmbrzl** [comment]
Aren't they working inside Mumble or aren't they working in another program as long as Mumble is running?
Does this problem even persist with the new 1.3 version?
