### ISSUE TITLE
Separate mute and unmute sounds

### ISSUE THREAD

**Issue by git-commit** [mumble-voip/mumble#1179]
It would be nice to have separate sounds (and therefore states in the config menu) for muting and unmuting the microphone.
If I'm allowed I'd reverse the sound of the muted state (not sure about the license of the sound files) and try to create a pull request.

Why you would want this was described a while back on sourceforge see: http://sourceforge.net/p/mumble/feature-requests/500/

**Comment by davidebeatrici** [comment]
Feature added in #142.
