### ISSUE TITLE
Mumble incorrectly attenuating

### ISSUE THREAD

**Issue by Krisiries** [mumble-voip/mumble#1183]
Mumble will permanently attenuate the active application periodically until its next attenuation cue. This happens while no users are talking and at a frequency of approximately once per minute

It seems that the attenuation being applied periodically (and fixed via the mumble attenuation process) is the windows communication attenuation - which i was under the impression mumble ignored.

**Comment by Krzmbrzl** [comment]
Does this also happen in Mumble 1.3?

I'll close this for now as you said it turned out to be Steam's fault. Feel free to reopen if you disagree and the problem also exists in 1.3 :)
