### ISSUE TITLE
Mumble plugin l4d2 outdated (with fix)

### ISSUE THREAD

**Issue by Ophidiophobia** [mumble-voip/mumble#1184]
I have tried to use positional audio in Left 4 Dead 2 but I noticed that it didn't work.

I learned that the plugin for Build 4440 is outdated and even the newest source code version is from 8 months ago. And I know the game was updated around christmas.

I updated the pointer offsets.
In testing position and distance worked.

The code can be found here:
http://pastebin.com/Kzj32fHU

There are three changes:
1. The pointer offsets are changed
2. I added some maybe helpful comments for the next time those values have to be updated.
3. The text description is updated. I do not know where the build number of Left 4 Dead 2 can be found. I used the version number I found in one of the steam files.

**Comment by AlonTavor** [comment]
Could anyone update the dll again? Current up to date plugin in the 1.3.0 snapshot doesn't work. I'm a bit scared of VAC to find the values myself.
