### ISSUE TITLE
Window size and position not remembered

### ISSUE THREAD

**Issue by dallenwilson** [mumble-voip/mumble#1185]
On Linux Mint 14, using mumble v1.2.5 provided by the mumble-snapshot ppa on Launchpad.net (exact package is 1.2.5-245-g221a5d7-1~ppa1~quantal1), I've found two minor bugs with the main window's size and position. They are consistently reproducible on my system, but I have not tried on any other platforms.

Every time I close mumble and re-open it later, the window is sometimes wider and taller (It seems to want to reset to a minimum value, if I leave it under that value. If it is over, it does not resize), and positioned slightly up and to the left from where I left it. It doesn't matter where I move the window before closing it, it will always reposition slightly up and left from where it was when it was closed. Ten pixels or so, roughly.

The second issue, which may not be related, is that every time I open Configure -> Settings, and then click 'Ok' without making any changes, the main window resizes itself. It will keep the same aspect ratio, and simply get a little bit bigger. If I repeat these steps, it will continue growing until it's height matches my screen height, and then it will stop expanding.

**Comment by Krzmbrzl** [comment]
The linked issue appears to have been fixed and I assume that this fix also applies for this issue here. If not, please let me know and reopen this issue :)
