### ISSUE TITLE
People auto-reconnecting after kick

### ISSUE THREAD

**Issue by nicolasjoly** [mumble-voip/mumble#1189]
Since update 1.2.5, whenever I kick someone from my server, they will automatically reconnect after 10 seconds (the same time as the auto-reconnect feature). Obviously when I ban them they cannot reconnect, but as soon as I remove them from the ban list they will reconnect. Same thing happens on the latest snapshot (1.2.5-248-g640b532). Everything is perfect with mumble 1.2.4 (I reverted back my client to 1.2.4 and I don't auto-reconnect anymore).

Here are some info that might help:
- Server version 1.2.4 on FreeBSD
- Clients are all Windows machines running either Win7 or Win8.1
- Clients are all running mumble 1.2.5 or the latest 1.3.0 snapshot (1.2.5-248-g640b532)

Here's what happens when I get kicked:
[4:13:16 PM] You were kicked from the server by SuperUser: Test.
[4:13:16 PM] Server connection failed: The TLS/SSL connection has been closed.
[4:13:26 PM] Reconnecting.

**Comment by nicolasjoly** [comment]
Still not there :)

**Comment by mkrautz** [comment]
OK. I lied. Sorry!

**Comment by steelphase** [comment]
I understand a fix for this has been committed, but should this issue be closed if the commit is not included in release?
