### ISSUE TITLE
Root Channel Name Won't Change on Ubuntu Server 14.04

### ISSUE THREAD

**Issue by InfinityDrop** [mumble-voip/mumble#1191]
Root channel name doesn't change with "registerName=" set in the .ini file. There are no significant events in the logs. The server is brand new, running only Murmur (1.2.4), every other setting change in the .ini file I've made works (greeting, bandwidth, allowed characters, etc etc). Must be a bug with the 14.04 setup on Murmur. New channels can be created with any name. Users can connect and use the server.

Orignal support thread: https://sourceforge.net/apps/phpbb/mumble/viewtopic.php?f=4&t=1285

**Comment by Krzmbrzl** [comment]
Does this still happen with version 1.3?

**Comment by lunyav** [comment]
I stumbled upon this issue, because I have this issue on FreeBSD 14.3 with version 1.3.4_11 of murmur.

**Comment by Krzmbrzl** [comment]
@lunyav please check again with a recent version of Mumble (1.5) - it's pretty hard to reason about the state of the code from that long ago 👀 
You can install it via Docker, if you don't want to self-compile and your packaging system doesn't ship a more recent version. See github.com/mumble-voip/mumble-docker

**Comment by lunyav** [comment]
On version 1.5 it doesnt seem to occur to me, then Ill just wait for a newer version.
EDIT: my default .ini contained the key RegisterName instead of registerName.
