### ISSUE TITLE
My browser doesn't open when i click on a link  in the chat.

### ISSUE THREAD

**Issue by Sivolcus** [mumble-voip/mumble#1193]
Using W8.1
Latest update installed
Using Chrome

**Comment by Soni93200** [comment]
Still not resolved :/

**Comment by mkrautz** [comment]
This is not an issue that everyone is able to reproduce.

One thing to try is to set IE or Firefox as your default browser.  You will note that clicking links with either of those two does work.  However, if Chrome is used, it will not.

One thing that has worked for orker people is to reinstall Chrome.  Onde thing to note here is that there are multiple variants of Chrome installations.

One kind of install lives in the user's APPDATA folder.  The other kind as a traditional program in program files.

In my case, the installation in APPDATA does work, and I believe an installation in Program Files have been reported to not work in a previous case...

It would be nice to get to the bottom of this.

**Comment by Soni93200** [comment]
I'm using Chromium and I've already set Chromium as default web browser ><

**Comment by mkrautz** [comment]
The point is that we're using the bog-standard Win32 API to open URL's. But for some reason, it doesn't work for sæl Chrome/Chromium installations.

Could you check where Chromium is installed om your system? That's the only lead er have to follow, for now...

**Comment by mkrautz** [comment]
I just installed the latest Chromium build via the mini installer.

After installing, it is in APPDATA, and I cannot open links in Mumble anymore.

My guess is that Windows 8 doesn't like default browsers to live in %APPDATA%?  My standard Chrome install is *not* in APPDATA, but Program Files -- when it's there, it works.

**Comment by mkrautz** [comment]
I will investigate now that we have a lead...

**Comment by mkrautz** [comment]
Here's the corresponding Chrome bug:

https://code.google.com/p/chromium/issues/detail?id=156400

**Comment by mkrautz** [comment]
We will try to give a better error message when opening the browser fails.

**Comment by mkrautz** [comment]
This is a new behavior in Windows 8 that disallows elevated applications.

Mumble runs elevated in its default configuration, with uiAccess=true to be able to grab global keypresses from elevated software such as MMOs and other games that has (or had) a tendency to run elevated.

To make this work in the general case, you need a Chrome/Chromium install that lives in Program Files, and not the default %APPDATA% location.

Official Chrome installers have installed to Program Files on Windows 8 for a long time now.  The Chromium installer I found when testing this, the mini_installer.exe (Win-330553-mini_installer.exe), still installs to APPDATA.

Unfortunately, when it's installed there, we cannot open links with that browser.  I recommend that you find an installer that installs to Program Files.

I have updated our Qt source tree to print an error when this fails. It's Windows's own error. So it's not very descriptive. But it gives users a string to Google for, and we can put it in our FAQ.

You can try to reproduce this yourself in an elevated Command Prompt:

Ctrl-X + A

and type:

    start http://mumble.info/

while Chromium in APPDATA is set as your default browser.

What you will get is an error stating:

    http://www.google.com
    Class not registered

like these: https://www.google.dk/search?q=class+not+registered&tbm=isch

This dialog will automatically show itself when you use the ShellExecuteEx API to open URLs.
We cannot hide it.  With the old ShellExecute, it would just fail silently.

So I will close this.  The new behavior should hit snapshots soon.

We will add this to the FAQ.
