### ISSUE TITLE
Dear Mumble, your RPC sucks

### ISSUE THREAD

**Issue by sebi** [mumble-voip/mumble#1196]
I blogged about this issue some time ago and I'm placing the link to my post here, so it can be discussed.

http://badgateway.net/2013/12/dear-mumble-your-rpc-middleware-sucks/

**Comment by bontibon** [comment]
This is being worked on over the next few months: https://www.google-melange.com/gsoc/project/details/google/gsoc2015/timcooper/5649050225344512

**Comment by mkrautz** [comment]
Excellent! Thanks Tim!

**Comment by coder4life** [comment]
What is the status of this. Curious because it can be a huge quality of life improvement for developers. Looks like the last code submission on the link above was at the end of August.

**Comment by bontibon** [comment]
Can this be closed now that grpc has been merged in? New tickets should be created for any specific issues around the new functionality.

**Comment by hacst** [comment]
I guess so. Closed.
