### ISSUE TITLE
Allow at least the space character in the default username variable

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#1202]
This is often the first setting an admin tries to change on a new server from my pov. Space characters are allowed in channels, but not in usernames.

I think most users try nicknames like "name tag" and not "name_tag".

**Comment by Krzmbrzl** [comment]
I'd always trim the attempted username. Thus leading and trailing WS is removed. Afterwards one could check if the name is empty and if it is, emit an error. Seems pretty straight forward to me :thinking:

**Comment by JonasOlson** [comment]
Why is there a restriction in the first place?

**Comment by Krzmbrzl** [comment]
Because you can create all kinds of shenanigans if the character set is not restricted.
