### ISSUE TITLE
mumble-overlay library fails to load for i386 windows games

### ISSUE THREAD

**Issue by foresto** [mumble-voip/mumble#1204]
I'm trying to get mumble-overlay to work with games in wine, but it fails, producing this error on the console:

```
ERROR: ld.so: object '/usr/lib/mumble/libmumble.so.1' from LD_PRELOAD cannot be preloaded: ignored.
```

Since I am on an multiarch/amd64 build of ubuntu (saucy) and the game (Guild Wars 2) and wine are 32-bit windows binaries, I tried it again using the mumble:i386 package instead of the amd64 package, but got the same error.

ld doesn't explain why the library cannot be preloaded, so I don't know what to do next.

**Comment by ZeroAbility** [comment]
Ubuntu 13.10 (Saucy) has reached End of Life:

https://fridge.ubuntu.com/2014/07/17/ubuntu-13-10-saucy-salamander-end-of-life-reached-on-july-17-2014/

If this can't be reproduced on current supported Ubuntu versions, this can probably be closed.
