### ISSUE TITLE
Mumble snapshots locking up with Guild Wars 2

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1205]
For a while now I've been noticing that Mumble will lock up (Not Responding) when Guild Wars 2 is open. This issue seems to be easy to reproduce when you first open Guild Wars 2.

This can also occur when alt-tabbed from the game. I have previously reported the issue on the [sourceforge forums](https://sourceforge.net/apps/phpbb/mumble/viewtopic.php?f=4&t=1140).

An earlier reported issue sounded very similar to this, also. However it has been occurring for quite some time prior to [this report](https://github.com/mumble-voip/mumble/issues/1091).

I've also noticed it's reproducable at a higher rate by running two fullscreen games at once. Usually Guild Wars 2 and then something like Team Fortress 2.

This problem originally appeared around the time of Aug 24, 2013. So between the 1.2.4 release and the snapshot of [1.2.4-139-g7c2d1a3](http://mumble.info/snapshot/mumble-1.2.4-139-g7c2d1a3.msi) is when this issue may have truly started. I recall that in Guild Wars 2 the overlay didn't work in 1.2.4 and I've been using snapshots since.

Hope this helps.

**Comment by Tarun80** [comment]
I believe this issue has been resolved, however one that has been ongoing and is somewhat related still exists. If you alt-tab out of GW2 (or any full-screen game for that matter) but keep talking on Mumble. Over time Mumble will go into a Not Responding state and lock up briefly.

To unlock it you either wait or go back into the full screen game.

**Comment by mkrautz** [comment]
I think that is the same issue that @Kissaki found.  It happens in other scenarios as well, not just GW.

It might not be an upstream Qt issue, BTW.

We patch Qt's LocalSocket implementation to add a buffer:
https://qt.gitorious.org/qt/mumble-developers-qt/commit/50c7e47c2ac423b012627c60cad2f486c64a232a

But it doesn't seem to necessarily be what's going wrong in the stack trace by @Kissaki

**Comment by mkrautz** [comment]
Oh, and that's the server...

**Comment by mkrautz** [comment]
The wait was increased from 100 ms to 30 seconds in Qt 4.8:
https://bugreports.qt.io/browse/QTBUG-4425

**Comment by mkrautz** [comment]
I wonder if we can create a D3D app that can consistently reproduce this easily.

**Comment by Tarun80** [comment]
I can reproduce it with any fullscreen game. Moreso when I run two or games fullscreen at once.

**Comment by Tarun80** [comment]
Any progress on this issue?

**Comment by hacst** [comment]
ad1ed221148cf6e721529f8ff36af45ce4ec5fed should at least give us back the old behavior (with 1s instead of a 30s timeout).

**Comment by Tarun80** [comment]
Looking forward to testing this. I wonder if a part of the hangups are related to #1637 and #1641 as you referenced. Hopefully the Qt 5.4.1 issue with Drag and Drop problems with caused #1610 to crop up will get fixed soon too. 5.4.2 and 5.5 are slated to have it fixed too.

**Comment by Kissaki** [comment]
So, this was an issue with Guild Wars 2s launcher, which was fixed/changed on their side.

According to the logging the Overlay still injects into D3D9 in the launcher (createdevice functions), but no Overlay is visible.
When launching the game, we inject into DXGI+D3D11 (Present, ResideBuffers, Device add/remove). The Overlay displays fine, no Mumble client lockup, no "Dead Overlay client detected" message in the debug logging.

Supposedly, the `QWindowsPipeWriter` is no longer using a thread, and should thus not cause hungups for us after Qt Version 5.6.0. ([change](https://codereview.qt-project.org/#/c/152304/), [qt ticket](https://bugreports.qt.io/browse/QTBUG-38185).

As the GW2 issue does no longer exist, I suggest we close this ticket.
For the other issue, we should create a separate ticket - I’m not sure what to make of it right now/yet though. What does still occur, when does it occur? @Tarun80 @mkrautz

**Comment by Kissaki** [comment]
We already have that as #1641. Closing this then.

**Comment by Kissaki** [comment]
I also tried fullscreening GW2 and tabbing out. Mumble 1.3.0~1937 does not lock up.

**Comment by mkrautz** [comment]
I tried GW2 a while back (after Qt 5.6) and I was still able to lock it up :-(

**Comment by mkrautz** [comment]
I don't recall how to do it, exactly... Maybe it was when I closed the game?

**Comment by Kissaki** [comment]
Do you want to reopen and assign to yourself to test again?

@Tarun80 said it was fixed for him [above](https://github.com/mumble-voip/mumble/issues/1205#issuecomment-55183418), so we don't have anybody else to reproduce despite you?

**Comment by Tarun80** [comment]
It's been a while since I used the Mumble overlay since I have Mumble on a second monitor now. However I'll try to test this out over the next few weeks. Alt-tabbing was an issue that would write to the console with errors, though I forget what they were.

Regardless, I'll enable the overlay and keep an eye on things. I say over the next few weeks as life has been rather busy lately.

**Comment by Tarun80** [comment]
While it's not Guild Wars 2, this is an issue in World of Warcraft that happened on the loading screens. Turning off the overlay stopped the issue. https://i.imgur.com/KTkLmYp.jpg

**Comment by mkrautz** [comment]
@Tarun80: Yes, that's a WoW-specific bug. Only affects loading screens AFAIK
