### ISSUE TITLE
Limited Push to talk keys

### ISSUE THREAD

**Issue by jenovi** [mumble-voip/mumble#1206]
When running Mumble on my mac, I have limited push to talk key choices. 
The only button's I can use are
- Caps Lock
- Shift
- Alt/Option
- Control 
- Mouse button 1 and 2 
- Command 
- Fn

This happened when I updated to version 1.2.4
I was using the ~ key as my push to talk before, and can no longer set it. 
If I try entering a new shortcut, nothing happens unless I press one of the above mentioned keys. 
I'm currently running OSx version 10.9.2
Mumble version 1.2.5

Thanks
-Jenovi

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you know of any changes in 1.3 regarding this issue?

**Comment by davidebeatrici** [comment]
Only #3603.

**Comment by Krzmbrzl** [comment]
Alright

From @mkrautz comment, I take it that this appears to be a problem with the OS not being configured properly anyways. Thus - until proven otherwise - I'll close this issue for now...
