### ISSUE TITLE
Mumble - Unresponsive/Frozen when playing League of Legends

### ISSUE THREAD

**Issue by MonkRX** [mumble-voip/mumble#1209]
Issue started: On release of 1.2.4 Final, reproduced with most snapshots since then, including latest.
Replicated on: Windows 7, 8, 8.1 - 64 bit
Hardware: Varies. About 5-6 machines/people in my mumble experience this issue. Laptops, desktops, integrated audio, dedicated Creative sound card. Probably 1/3rd or close to half the people probably experience this in my mumble.

How to replicate: 
1. Launch Mumble, Join Server
2. Start Game on League of Legends
3. Initiate an action on Mumble. Freezing won't occur until you perform an action (such as sending a message or pushing push to talk). It won't occur on the first action, but maybe a few actions in.
4. Mumble will stop taking user input. If PTT was transmitting during this time, it will stay stuck. If it was not, it will stay off. Mumble's screen will go to faded white (standard Windows behavior when an app stops responding). You will not be able to message, click and drag, or do anything within Mumble's app for about 2 minutes. Screen updates on Mumble and overlay won't occur. (Messages sent to chat won't appear, updates to the overlay, such as when someone joins the channel or begins talking won't update).
Mumble will continue to receive voice transmissions, with no apparent delay or lag. If you pull up a frozen's user's ping statistics, it will appear normal. 

Troubleshooting performed:
Updating to snapshots.
Disabling overlay. 
Another Mumble server.
Opus versus Celt (when my server falls back when someone with an older client joins).

If anyone has a workaround, I would greatly appreciate it. I can also provide further testing and troubleshooting. If you need system specific information, let me know (or any information at all).

**Comment by Kissaki** [comment]
Is this still an issue?
I ran a LOL tutorial game, spammed the PTT and mute in Mumble, in Mumble 1.3.0~1291 (x86), with no issues.
If this is still an issue, plz reopen with info.

**Comment by MonkRX** [comment]
I'll retest this with the latest snapshot, but our group narrowed it down
to the Overlay. We shut ours off and we don't have any issues anymore.
