### ISSUE TITLE
Windows 8.1 Mumble does not allow audio to be heard,

### ISSUE THREAD

**Issue by blake1383** [mumble-voip/mumble#1225]
I installed Mumble 1.25 on my windows 8.1 machine. My friends can hear me without any issue but i hear nothing from them. The audio wizard has no sounds as well. All other apps work fine with my afterglow prizmatic headset. Ive tried all the suggestions i found when googling the issue but no resolve.

**Comment by nate191** [comment]
Having the same issues, and tried much of the above.  No solutions yet?

**Comment by Kissaki** [comment]
The message

> "This audio device is already in use"

can only really occur when Mumble *exclusively* uses the output device. This is only the case if the output device is set to allow exclusive mode in the system/driver settings, *and* Mumble is configured to use exclusive mode. Are you sure that is not enabled?

**Comment by Krzmbrzl** [comment]
Anything new on this issue? Is it still in the 1.3 version?
Also it would be nice if you could answer Kissaki's question...
