### ISSUE TITLE
Freezes after connection attempt

### ISSUE THREAD

**Issue by valdr** [mumble-voip/mumble#1227]
Hello

I am running Debian Linux Wheezy 7.4 with LXDE on a 1-core, 2GB eMachines laptop.
I am attempting to use the latest Mumble (1.2.5-245-g221a5d7-1).

When I start, I get the "mumble server connect" window, where I have a bookmarked server.
I click "connect", and... nothing.
It is not connecting;
I cannot choose anything in the menu;
When I take the focus away, the window goes gray.
Looking at running processes with top, I see mumble using 90-95% of the CPU...

**Comment by bendem** [comment]
This problem still happens on latest available build for Fedora (1.2.6). Is there anything I can do to help finding a solution?
Client is stuck on "Connecting to *hostname*" but I'm actually connected on the server (and I don't timeout).

**Comment by ngollan** [comment]
You could try removing (or at least temporarily renaming) the client database. On Linux, you should find it under `${HOME}/.local/share/data/Mumble/Mumble/.mumble.sqlite`.

**Comment by bendem** [comment]
Yep, that fixed it, thanks

**Comment by taibhse** [comment]
Have been experiencing this issue for a while. Have to just keep trying until I get into the server.
running Ubuntu 14.04 and deleting the client database does not solve the issue.

**Comment by Krzmbrzl** [comment]
Does this still happen in Mumble 1.3?
