### ISSUE TITLE
Better mumble usabillity for servers with 100+ channels or high traffic

### ISSUE THREAD

**Issue by a1668753** [mumble-voip/mumble#1229]
Mumble client works great for single channel or low traffic chats (30 people and less). However, when you have more than 1000 people who constantly join and leave channels it becomes near impossible to watch room from mumble client. Constant scrolling happens all the time.

There several ways to solve this issue:
1. Best option will be lock scrollbar so deepest sub channel is sticked to top of scrolling window and make this behavior optional (mumble setting) and enabled by default.
2. Simpler way but less usable. Since we have filters already we can just add right click menu item to channel "show only this sub-channel tree".

**Comment by ZeroAbility** [comment]
Has this been implemented by some other feature, or mitigated in some way using groups and ACL's?

**Comment by Hartmnt** [comment]
Yup 2) should now be possible with "Pin channel when filtering" #5923

**Comment by ZeroAbility** [comment]
> Yup 2) should now be possible with "Pin channel when filtering" #5923

Please confirm and close this @Hartmnt.

Thank you

**Comment by Hartmnt** [comment]
So, Mumble implemented a feature to "Limit notifications when there are more than N users on the server" and the channel filter system now has "pinned channels". This makes the general usability in large servers much better, but I suppose the problem OP has cannot be conveniently solved yet.

"pin channel" can only be used to solve that problem, if you are able to hide all non-empty channels manually. This is only reasonably possible, if channels are not constantly created and removed by other users.

So despite all the improvements the original problem - albeit a very edge-casey problem - would still exist on certain servers.

**Comment by Krzmbrzl** [comment]
I don't think I have ever observed scrolling due to other users moving on the server :thinking: 
Has any of you?

**Comment by Hartmnt** [comment]
> Has any of you?

I can not tell, because I do not visit servers with so many users that this might become an issue.

**Comment by Krzmbrzl** [comment]
Me neither but the general behavior can't depend on the oder count. If people moving channels can cause the scrolling to change, then this should be reproducible with less users as well :thinking:
