### ISSUE TITLE
Mumble overlay not working with SweetFX Shader Suite

### ISSUE THREAD

**Issue by thng2** [mumble-voip/mumble#1232]
I am using mumble 1.25 and my mumble overlay isn't working in hardly any game.
I have it enabled in options, i have checked my blacklist and it just doesnt make sense.
Out of all the games i tried the only game where the overlay seems to work is TF2, i've tried many other games (Dota 2, Counter strike Source, Counter strike Global Offensive etc.) and i just can't get it to work and i don't understand why!

**Comment by Kissaki** [comment]
[SweetFX Shader Suite](http://www.guru3d.com/files-details/sweetfx-shader-suite-download.html) injects itself into the program/shaders to make changes to shaders (allow antialiasing and various other shader tech).

In the compatibility section it says:

> It does not work well with most programs that overlay an image onto the game. It has a workaround for the Steam overlay so that will work, and you can make overlays based on Rivatuner OSD work as well with a compability setting in those overlays , but other overlays may prevent SweetFX from making changes to the image or outright crash the game - turn those off.

There does not seem to be source code available, and no further description about how it injects itself. As they made Steam Overlay work, I guess they could also make other Overlays work. As I don’t know what they do or how they break our Overlay I don’t think it’s worth to pursue on our side (also given with how many other Overlays we are compatible with - I’d like to blame it on them).

---

Looking at that huge log (makes it hard to see what is important)

```[4164] M:HardHook: Setup: Asked to replace 76C1ED12 with 5527CE00 
[4164] M:HardHook: CloneCode failed; Unknown opcode b8 at 0: b8 14 10 00 00 b9 00 00 00 00 8d 54 
[4164] M:HardHook: Setup: Asked to replace 76C1F170 with 5527CE90 
[4164] M:HardHook: trampoline creation successful at 001A0000 ```

it probably is an unhandled opcode on our side.

[b8 seems to be a MOV operation](http://ref.x86asm.net/coder32.html#xB8). So should be possible to fix.

**Comment by Krzmbrzl** [comment]
I'd say this is not in Mumble's scope to fix this => Closing the issue
