### ISSUE TITLE
Can't restore from tray icon in Fluxbox with "Hide in tray when minimized"

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#1233]
If "Hide in tray when minimized" is enabled and I manually minimize Mumble I can't restore it by clicking on the tray icon, tested in Fluxbox 1.3.5, works in LXDE though.

If Im asked whether to quit or not while Im connected and I click "Minimize" it works just fine and is restorable.

Mumble version is 1.2.3-349-g315b5f5-2.2ubuntu1 (on Lubuntu 13.10)

**Comment by ubuntuaddicted** [comment]
I'm running XFCE 4.12 with Xubuntu 14.04 and whenever I minimize mumble it doesn't go to my systray at all. I have to reopen mumble using my start menu just to get it to reappear. I'm using version 1.2.8.1~ppa~trusty1

**Comment by Strit** [comment]
I can confirm this issue happens with 1.3.0 on Manjaro KDE as well. Can't restore the app from the system tray, but if I uncheck the hide in systemtray option, the application panel icon works as it should.

**Comment by mkrautz** [comment]
Probably related to https://github.com/mumble-voip/mumble/pull/2685

Anyone building from source?

What happens if you comment of these lines:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/MainWindow.cpp#L514-L517

?

**Comment by mkrautz** [comment]
Actually, ignore my comment. This is not related to the restore-from-tray bug on X11.

**Comment by abbradar** [comment]
@mkrautz Just in case I've tried your solution. Mumble stopped to minimize on window close button (when I choose Minimize, nothing happens). However "Hide Mumble" option from the main menu works, and then I can restore Mumble from tray!

**Comment by ZeroAbility** [comment]
Does this still occur with newer versions of Fluxbox and Mumble?
