### ISSUE TITLE
Mumble becomes unresponsive

### ISSUE THREAD

**Issue by tenjoname** [mumble-voip/mumble#1234]
After an indeterminate amount of time (sometimes a few minutes sometimes longer) my mumble slows up and becomes unresponsive - preventing my transmitting. Reapplying the settings seems to fix this. Occasionally the entire program just freezes up and I have to restart the client.

I've tried installing the latest. All my sound drivers are up to date, I've enforced TCP, running administrator, my firewall is not preventing udp or tcp. I'm at a loss how to fix this.

Windows 7 64.
Mumble 1.2.5

**Comment by Krzmbrzl** [comment]
Does the freeze still happen in version 1.3?
