### ISSUE TITLE
mumble-overlay doesn't work with Ryzom

### ISSUE THREAD

**Issue by shackra** [mumble-voip/mumble#1239]
Hello!

I ran `mumble-overlay ryzom_client` but the overlay doesn't work for the game under GNU/Linux. However, this is not true for the same game but running on Windows (according to a friend).

**Comment by ZeroAbility** [comment]
Can you let us know if you are still playing this and are having this issue? Apologies for the extremely long wait.

**Comment by shackra** [comment]
Not playing currently, and nowadays, I use Discord for everything gaming related, so...

**Comment by Krzmbrzl** [comment]
Closing this then
