### ISSUE TITLE
Add DNS SRV record support

### ISSUE THREAD

**Issue by flussence** [mumble-voip/mumble#1242]
It'd be nice to have on shared-IP hosting setups, and for symmetry with the existing mDNS support.

Qt5 has a new QDnsLookup class that looks like it'd make this trivial: http://qt-project.org/doc/qt-5/qdnslookup.html

**Comment by navarr** [comment]
Would also be nice for those of us that use Cloudflare for the website and want to use the same address for mumble.

**Comment by DamonGant** [comment]
:+1: for this issue. This should be a trivial thing.

**Comment by FilipPyrek** [comment]
:+1:  for this issue. I don't understand why it hasn't been implemented yet.

**Comment by Ant59** [comment]
:+1:

**Comment by kevincox** [comment]
This would be a great feature, avoiding set port numbers where possible is always good.

**Comment by robingroppe** [comment]
+1
We need that. 
Teamspeak got it too, and it makes sense.

**Comment by duxet** [comment]
What's the status of #1306?

**Comment by navarr** [comment]
@duxet They said they plan to have it in 1.3 - which is still "in dev"

**Comment by mkrautz** [comment]
SRV support is now in 1.3.x.
