### ISSUE TITLE
Problem with the voices of some users when they start speaking (Mumble 1.2.5)

### ISSUE THREAD

**Issue by zudkas** [mumble-voip/mumble#1247]
When some users on my  Mumble start talking the volume of their voice becomes very high, and it seems they speak as monsters for a few seconds. This bug occurs with several people on my mumble but it is always the same people who have this problem. As a user bug all other players in the channel didn't hear them strangely but this happens in a random order. 

So I think this problem is not from the user and I doubt that my webhost (verygames.net) is the author of the problem. 

If anyone has a solution let me know. 

Zudkas

**Comment by Krzmbrzl** [comment]
Does this problem persist in Mumble 1.3?
