### ISSUE TITLE
Mumble:// links still display wrong behaviour when mumble is already running

### ISSUE THREAD

**Issue by ZakMcRofl** [mumble-voip/mumble#1256]
I could not reopen #1190 so I created this new ticket.

Using build 1.2.5-294-gd9ff1e9 for Windows which should include the fixes for #1190 , I observe the following behaviour:

Test URL:
mumble://someusername123@mumble.tf2center.com/%23105050?version=1.2.0

Case: Mumble is completely shut down when the link is clicked
Expected behaviour: Mumble launches and connects you to the intended channel. 
Actual behaviour: as expected

Case: Mumble is open and not connected to anything (#1190 says this also happens if mumble is open and connected to another server)
Expected behaviour: Mumble connects to the intended server and puts you into the channel of the URL
Actual behaviour: Mumble connects to the intended server but puts you into the root channel.

Case: Mumble is connected to the current server but in another channel: 
Expected behaviour: switches to the channel in the URL
Actual behaviour: Mumble claims to open the URL but remains in the other channel 

I also often got a certificate error in the past when Mumble was already open but I have not been able to reproduce this so far.

Some meta info:
An update with this fix would have a great impact on the usability of Mumble for the TF2center use case. It is a matchmaking website for TF2 matches in competitive format which generates mumble links so the team can communicate much better with each other than the ingame chat. Currently people have to close down mumble if they switch from one team/match to the next. So fixing this would have a great impact on our ever growing community.

**Comment by Janhouse** [comment]
Still not fixed in 1.3 :disappointed:

**Comment by Janhouse** [comment]
Seems to be fixed in the latest OSX snapshot. :smiley:
