### ISSUE TITLE
Mumble memory leak -> Crash

### ISSUE THREAD

**Issue by ssateneth** [mumble-voip/mumble#1259]
This is on Windows 7 x64 Ultimate, used to have 1.2.5 installed, had this problem, fully uninstalled, reinstalled 1.2.6, same thing. Allow me to go into detail here.

I use UltraVNC to remotely access a PC. The UltraVNC viewer client has an option to make the window use DirectX, which stretches the remote PC's screen to cover the shape of the viewer client window instead of being restricted to display pixels 1 to 1. If I have this DirectX feature disabled, Mumble behaves normally. But if the feature is enabled in the UltraVNC Viewer Client and the viewer window is visible (not minimized), Mumble CPU usage pegs a single CPU core to 100% and memory usage skyrockets, up to about 1.6GB where it eventually says "Mumble ... has stopped working" and I need to close it and reopen it.

Here is the Console.txt log found in the %appdata%/Mumble/ directory. Maybe you cna get some use out of it. I can't figure out how to attach log files here.

https://dl.dropboxusercontent.com/u/9768004/console.txt

**Comment by davidebeatrici** [comment]
Is the problem still present with the latest snapshot?
