### ISSUE TITLE
Mumble snapshot on Windows titlebar issue?

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1260]
The titlebar of the snapshot builds on Windows says 1.2.5. Shouldn't this read 1.3.0?

**Comment by Tarun80** [comment]
Bringing this up again with how the x64 builds are coming out on a more consistent basis.

Would it be worth having x64 or x86 somewhere in the titlebar and/or about section? Speaking of the about section, the Mumble copyright says 2005-2014.

**Comment by Tarun80** [comment]
@mkrautz: Any thoughts about adding in the ~x64~ I mentioned above for 64-bit builds?

**Comment by Tarun80** [comment]
Any chance for having the x64 in the titlebar?

**Comment by Kissaki** [comment]
Adding x64 to the titlebar may be viable. Why do we have a version in the titlebar? To easily see the version on issues? Do we expect issues on x64 that are not on x86?

Probably not. The length is already pretty long. Maybe this is more viable on stable releases. But we haven't had this missing as information AFAIK before. So I don't think we need it.

This ticket requests that 1.3.0 snapshots be titled 1.3.0, which they are. Closing this.
