### ISSUE TITLE
ACLs and Groups wiki page out of date

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1265]
07:16 < DGMurdockIII> please update this http://mumble.sourceforge.net/ACL_and_Groups
07:16 < DGMurdockIII> for newer verson of mumble

**Comment by Krzmbrzl** [comment]
As a lot of changes have occurred on these docs, I consider them to be roughly up-to-date for now. They should at least contain a lot more up-to-date information in contrast to when this issue has been created. Therefore I'll close this issue.
