### ISSUE TITLE
Mumble's overlay does not support Watch_Dogs

### ISSUE THREAD

**Issue by lhyco2** [mumble-voip/mumble#1268]
We download the Mumble and test the overlay on watch dog game which from ubisoft and find mumble cannot show fps on this game. Is there a way to support it.

**Comment by Kissaki** [comment]
This should work now. We ship x64 overlay with our development snapshots. Can anyone confirm it works?

**Comment by mkrautz** [comment]
I'm installing Watch_Dogs to check.

**Comment by mkrautz** [comment]
Works in 1.3.0.
