### ISSUE TITLE
ServerDB.cpp assumes that not sqlite is MySQL

### ISSUE THREAD

**Issue by singpolyma** [mumble-voip/mumble#1269]
It should at least check if MySQL and then error if not, since right now it happily connects to Postgres and then sends invalid SQL to it, which can be confusing.

**Comment by mkrautz** [comment]
The top of ServerDB::ServerDB() should probably just check:

    if (Meta::mp.qsDBDriver != QLatin1String("QMYSQL") && Meta::mp.qsDBDriver != QLatin1String("QSQLITE")) {
        qFatal("ServerDB: invalid DB driver specified: '%s'. Murmur only support QSQLITE and QMYSQL.");
    }

**Comment by mkrautz** [comment]
Fixed by https://github.com/mumble-voip/mumble/pull/3039.
