### ISSUE TITLE
Skins cannot bypass OSX native look

### ISSUE THREAD

**Issue by xPoke** [mumble-voip/mumble#1272]
Hey guys,
Please see this issue posted on my skin project
https://github.com/xPoke/MetroMumble/issues/4

Basically, QT's OSX native menubar look screws up skins.
I suggested there that you could probably add a checkbox to the UI panel which would let you choose between native OSX menubars and QT native toolbars, since this is impossible to solve with QSS alone without redesigning the skin for OSX.
The native menubar also lacks the feature of being drag-able and positionable, so that's another reason why a regular user might prefer this as an option.

**Comment by mkrautz** [comment]
At this point, this is fixed:

https://github.com/mumble-voip/mumble/blob/master/src/mumble/MainWindow.cpp#L2260
