### ISSUE TITLE
UTF-8 character in Murmur_User->context causes CVP viewers to fail

### ISSUE THREAD

**Issue by usefulz** [mumble-voip/mumble#1277]
Recently, a support request came in, saying that CVP was throwing a json_encode() utf-8 error, and upon debugging the json output, it looks like the user->context has some weird utf8 characters in there that weren't before.  Specifically an issue with Guild Wars 2, and it happened after an update yesterday.  Can anyone shed some light on this?

Using commit f91386b36463cf99d1e431d3487c9e4f6444f977

Thanks!

**Comment by Krzmbrzl** [comment]
Until steps to reproduce are provided, I'm afraid we can't really help here. Also the issue might have been fixed in the meantime, so I'll close this issue for now.

If you still experience this bug, please reopen this issue
