### ISSUE TITLE
Stable Mumble releases don't prompt for update like snapshots?

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1286]
I feel like this is a bug or unintended behavior at least.

I've noticed that the snapshots just tell you there's a new version but don't have the similar behavior that snapshots do.

I believe this would help users stay up-to-date by prompting in a more noticeable manner than just saying there's an update in the log.

An auto-update would also be very helpful/useful.

**Comment by Krzmbrzl** [comment]
I don't think there is enough incentive to change the update notification in the client. Therefore, I am closing this

**Comment by Tarun80** [comment]
@Krzmbrzl I think you're about _eight years_ too late... I unfortunately had to migrate to Discord, as Mumble seemed to be lagging behind and didn't keep up with the solutions gamers needed.

**Comment by Krzmbrzl** [comment]
Closing this as reslved, then
