### ISSUE TITLE
Overlay for Wildstar (64 bit)

### ISSUE THREAD

**Issue by markuznw** [mumble-voip/mumble#1290]
Tried everything possible to make it work (adding wildstar64.exe to whitelist, switching game to -dx9 flag, using last dev version of mumble etc) but nothing seems to work.
It just doesn't appear :_(
Anything I can do to make it work? Win7 64

**Comment by Kissaki** [comment]
The x64 Overlay has been implemented quite some time ago.
 Wildstar is EOL as well since 2018.
