### ISSUE TITLE
Mumble is unable to open URLs when Chrome is set as the default browser

### ISSUE THREAD

**Issue by Iraos** [mumble-voip/mumble#1294]
Mumble doesn't want to open any links in Chrome Canary (set to default browser via registry edit). How does mumble handle opening URLs?
Windows 8.1
Mumble 1.2.7
Chrome Canary 37.0.2062.0

**Comment by bontibon** [comment]
Possibly related issue: #1193

**Comment by mkrautz** [comment]
Closed via #1193.
