### ISSUE TITLE
Mumble randomly goes silent on continuous transmit broadcast

### ISSUE THREAD

**Issue by marcetcheverry** [mumble-voip/mumble#1295]
Server/Broadcaster:

Windows 7 running Mumble 1.2.6 & Murmur, broadcasting audio continuously from line-in input. Lips on UI show red continuously.

Quality: 72.0kbps
Audio Per Packet: 10ms
Noise Suppression: Off
Max Implication: 1.00
Echo: Disabled
Transmit: Continuous

Murmur.ini bandwidth upped to 150000 from default. Otherwise settings are default.

Clients:

Both the iOS app and the Mac app, sometimes when moving around (maybe a connectivity issue), the broadcasting client goes completely silent, no red mouth icon. If I disconnect and reconnect I get the audio again.

Clients are always muted or on push to talk.

Sometimes this happen even when connecting for the first time. The server is never restarted, but the clients are and the problem is resolved.

This setup is intended to get a high quality extremely low latency relay from a TV output.

How can I provide more information to debug this issue?

**Comment by Krzmbrzl** [comment]
Does this still happen in Mumble 1.3?
