### ISSUE TITLE
mumble deadlock on connect on debian sid

### ISSUE THREAD

**Issue by jakob-ledermann** [mumble-voip/mumble#1297]
the mumble client stops reacting to any input at connect to any server.
Happened with debian sid package mumble Version 1.2.6-1, the stable package `1.2.3-349-g315b5f5-2.2+deb7u1` and a build based on the latest git sources.

Output of last compiled build:

> CELT bitstream 8000000b from /home/jakob/workspace/mumble/release/libcelt0.so.0.7.0
> CELT bitstream 80000010 from /home/jakob/workspace/mumble/release/libcelt0.so.0.11.0
> Locale is "de_DE" (System: "de_DE")
> Database SQLite: "3.8.4.3" 
> Overlay: Listening on "/home/jakob/.MumbleOverlayPipe" 
> GlobalShortcutX: Unable to open any keyboard input devices under /dev/input, falling back to XInput
> GlobalShortcutX: Using XI2 2.0
> AudioInput: 40000 bits/s, 48000 hz, 480 sample
> PulseAudio: Starting input alsa_input.usb-Sennheiser_Sennheiser_3D_G4ME1-00-G4ME1.analog-stereo
> PulseAudio: Starting output: alsa_output.usb-Sennheiser_Sennheiser_3D_G4ME1-00-G4ME1.analog-stereo
> PulseAudio: Stream error: Entität nicht vorhanden
> AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
> warning: The VAD has been replaced by a hack pending a complete rewrite
> OpenSSL Support: 1 (OpenSSL 1.0.1i-dev xx XXX xxxx)

Options of the build: `qmake CONFIG+=no-server -recursive & make & make release`

Probably an issue sourcing in an other package. 1.2.6 Worked until yesterday so i guess i installed some updates which broke mumble. Unfortunately I can't remember which packages i upgraded.

Can anyone give some hints where problem may lay, or how i can get it back working?

**Comment by Krzmbrzl** [comment]
Given how old this issue is, I will assume that this has been fixed in the meantime. If not, please let me know
