### ISSUE TITLE
Mumble 1.2.7 memory leaks

### ISSUE THREAD

**Issue by Rulfy** [mumble-voip/mumble#1304]
After idling about 4-6 hours, I noticed a very high memory usage.

After a fresh start, the client usually uses about 15 MB RAM.
In my case it used 1.6GB RAM.

I was just sitting in a channel with a muted mic+sound.
Using Windows 7 x64 and Mumble Client 1.2.7.

![mumble memory leak](https://cloud.githubusercontent.com/assets/5162032/3474419/b51580fc-02e3-11e4-801f-3c86208bf947.png)

**Comment by Kissaki** [comment]
No further input was provided.
Closing in favor of #1497
