### ISSUE TITLE
Channel File Transfer/Browser

### ISSUE THREAD

**Issue by Xylemon** [mumble-voip/mumble#1307]
It would be great if Mumble supported a channel based file browser that users could upload to and download from. Many alternatives feature this and its main use could be for those who need to share something quick with other players/users or downloads for servers.

**Comment by devcline** [comment]
1. people use mumble for 2 reasons, opensource CRYPTED VOIP and for games.
2. The services like dropbox and stuff , isnt secure, so its not a solution for crypted voip
3. I was using teamspeak and i moved to mumble, but im upset , that there is no filetranfer plugin or something like this.

**Comment by bontibon** [comment]
That's a good point you make, @devcline.

If this were to be implemented, there are at least a couple implementations to consider:

1. Like @Xylemon suggested, having per-channel file browsers, where users with particular ACL permissions can upload and download files for a channel, and
2. Allowing users to send files directly to others, where the transfer is still done via the encrypted server connection. This would allow users to share large files with others, without requiring the file to be uploaded to the server first.

**Comment by hacst** [comment]
File transfers would - depending on how cleanly you want to integrate it - be a lot of work the way our protocol currently is setup (no stream multiplexing on the control channel). Sure you can always bolt on something extra very quickly (e.g. out of band transfers negotiated via the control channel) but doing that in the core would be asking for trouble in all kind of ways. I'd much rather see us push for an extension system so ppl. can do stuff like that themselves.

**Comment by Xylemon** [comment]
@hacst Whether it's officially in the client of an advanced extension, I wouldn't mind as long it's there. Especially considering this is one of the things that is stopping most of my friends from moving over.

**Comment by amki** [comment]
I can't see why this would be "a lot of work". File uploads are basically the same thing setUserTexture already does, the only difference is that setUserTexture uploads a picture that is then added to the user and a file upload would upload a file to a channel.

**Comment by hunter688** [comment]
File transfers and file storage on the server like TeamSpeak will be very useful feature. I would like leave TeamSpeak and use Mumble for my gaming comunity, but we need this feature.

**Comment by Nextnx** [comment]
I would love a direct file transfer (hole-punching most likely), so I can scrap skype. With that I would only need mumble for all my communicative activities.

**Comment by katamari1992** [comment]
This would be an awesome feature for mumble to tote around. If anyone knows of a plugin that does this I'd love to have it in the meantime.

**Comment by reklrekl** [comment]
This is the only feature missing IMHO.
Would be awesome!

**Comment by alex9099** [comment]
This would be a pretty good feature

**Comment by davidebeatrici** [comment]
Closing in favor of #3324.
