### ISSUE TITLE
Find a solution for feature request - new tracker

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1310]
Within the team we seem to agree that we want to move away from the [sourceforce feature tracker](https://sourceforge.net/p/mumble/feature-requests/), and also that this github tracker is not quite fitting for feature requests either.

Because people post FRs here anyway, we already have a [flag feature-request](https://github.com/mumble-voip/mumble/issues?labels=feature-request&page=1&state=open). This also lead to previously closed issues [being asked to be re-opened](https://github.com/mumble-voip/mumble/issues/1257#issuecomment-48555514).

We should find an adequate solution. Probably a separate tracker (hoster/software). We should also discuss migration -  I guess we want to move the old tracker data into the new one? Or take a fresh start?

**Comment by jundis** [comment]
http://feathub.com/

This appears to be a fairly decent feature tracker. No registration required outside of a github account.

**Comment by Kissaki** [comment]
Looks pretty cool;
it’s simple, and uses github accounts. It has up and downvotes for existing, and you can suggest new items.
It is free for open source projects.
It does not seem to have any admin/project maintainer controls though in terms of being able to accept, close or comment on feature requests - at least no such thing is documented.

**Comment by bontibon** [comment]
Is this still an issue now that GH's issue tracker has "reactions"?

![image](https://cloud.githubusercontent.com/assets/110883/14936558/2ebe644c-0ec6-11e6-9f50-e7e342ea176f.png)

**Comment by mkrautz** [comment]
No, I personally think GitHub's good enough now.  We just need to document that we prioritize feature requests that have the most +1s.

**Comment by Kissaki** [comment]
I previously looked at querying the Github API for an ordered / prioritized list we could display, but the API does not provide "reaction" data yet…
Asking support, they added my "+1" to their feature request or sth, so I feel like it's not coming all too soon, sadly.

**Comment by Kissaki** [comment]
We can't really move away from Github, and this is an OK solution. Being able to query/order by votes is pretty important, but not having it does not really warrant moving away.
So yeah, I guess we stay…

Also, how come we didn't mention [GitLab](https://about.gitlab.com/gitlab-com/) yet?
Pretty much all that github provides except userbase, unlimited free repos, hosted service based on FOSS, free "buildserver" runners, …
And most importantly, [ordering issues by popularity](https://gitlab.com/gitlab-org/gitlab-ce/issues?assignee_id=&author_id=&milestone_title=&scope=all&sort=upvotes_desc&state=opened).

**Comment by mkrautz** [comment]
@Kissaki Are you aware you can order issues by +1 via the web interface, as @bontibon pointed out?

Or are you just pointing out that it's not possible via the API?

For example, sorting by +1 via the web interface:
https://github.com/mumble-voip/mumble/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

It's not visualized very well in that you can't see the number of +1s in the list, but it at least gives an idea of the prioritization.

**Comment by hacst** [comment]
Not as user-friendly as I would like (still would have to manually filter and sort to figure out what FRs are already there to support as a user) but good enough to not bother with another tool I think.

Can we somehow make the filtered and sorted list available as a separate page?

**Comment by Kissaki** [comment]
Ah, that is something at least. No numbers though, and hearts also do not count towards the thumbs up. So if someone hearts something, that does not count.

I thought about parsing it from the website as long as its not available on the API as well...
It's an unnecessary hassle though. And as soon as its added to the API, obsolete.

**Comment by Kissaki** [comment]
So, I guess we’re effectively using this issue tracker for feature requests as well - even as our main/only tool by now. As no progress has been made or discussion had, I will close this for now.

**Comment by Krzmbrzl** [comment]
Note that reactions can now be queried via the API (even though this is still considered to be in a "preview" state.

In order to query the reactions for a given issue, use e.g.
```bash
curl   -H "Accept: application/vnd.github.squirrel-girl-preview"   https://api.github.com/repos/mumble-voip/mumble/issues/3743/reactions
```

@Kissaki how har ddo you think would creating a sorted list of feature requests on our website be (making use of this)? :thinking:

**Comment by Kissaki** [comment]
I presume we have to set up an API auth key for that, and secure that server side, so we need a server side component?

**Comment by Krzmbrzl** [comment]
No authentication required in order to access this API. At least I was able to paste above command in my terminal and execute it without having to put in any credentials.
