### ISSUE TITLE
Obfuscated IPs are not match-able across server restarts

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1311]
The IP obfuscation hashes the IP. Salt is added, which is a random number, assigned each start of the server anew.

Thus, obfuscated IPs are match-able during the runtime of a server instance, but not with another lifetime.

On the other hand, this makes it more secure, one is not able to track users via IP across server sessions - this does require a server restart though to take effect.

@dD0T @mkrautz 
Shouldn't we just use a persistent salt? Or is there a reason not to?

**Comment by Krzmbrzl** [comment]
What are IPs obfuscated for?

**Comment by Kissaki** [comment]
User anonymization, user privacy.

**Comment by Krzmbrzl** [comment]
Given that this issue is from 2014 and hasn't received any attention whatsoever, I don't think that this actually poses a problem for running mumble servers.

Therefore I'll close this issue for now.
