### ISSUE TITLE
Mumble issue while running another program

### ISSUE THREAD

**Issue by Smellynoob** [mumble-voip/mumble#1312]
Hi, I really hope this is the right place for this, but I have been trying to fix this issue for over a week. Whenever I have mumble running along with one of my computer games, I cannot use the ALT key in my game. Though this is not my push to talk key it does have a significant role in the computer game I play. I only have this issue while Mumble is open. I have tried running both programs as admin and still get this bug. Please help :(

**Comment by Kissaki** [comment]
Do you use a keyboard driver or other program for macro keys that bins macro keys or other keys (specifically ALT) to different logic depending on the program you are running?
![2015-01-06 02_06_44-microsoft mouse and keyboard center](https://cloud.githubusercontent.com/assets/93181/5622755/b6aa1a5c-9548-11e4-97e7-a9ba64a61397.png)
