### ISSUE TITLE
"Jail" channel

### ISSUE THREAD

**Issue by ExeArco** [mumble-voip/mumble#1315]
An ACL permission that would allow an Admin to put a user into a "jail" or "time-out" channel  where the user inside can't leave.

**Comment by ZeroAbility** [comment]
You should be able to accomplish this by creating a channel, group, and ACL for this purpose. You would just remove the user from the rest of the groups and put the user only in the "time-out" group. Then have someone in the admin group move the user to that channel. Don't forget, ACL permissions are applied top down. Let us know if this is sufficient.
