### ISSUE TITLE
Mumble x64 installer does not install to Program Files

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1318]
This may be due to running previous versions, but it wants to install to Program Files (x86) instead of Program Files.

Also, the titlebar doesn't reflect that it's an x64 snapshot. Not sure if it should but felt this was worth mentioning.

**Comment by mkrautz** [comment]
Right now the behavior is inconsistent.

If you update from an x86 to an x64 build, the x64 build will live in Program Files (x86).

If you update from an x64 build to an x86 build, the x86 build will live in Program Files.

While it is a little ugly, the easy fix is to simply ALWAYS use Program Files (x86) -- for both x86 and x64.

That would also make the install path consistent, no matter which arch you installed. (And keep compatibility with scripts people may have.)

I think this should be our workaround for this inconsistency.  Thoughts?  Does it matter much that the x64 build also lives in Program Files (x86)?

**Comment by Tarun80** [comment]
I believe the installer should have proper detection for this. Perhaps offer to uninstall from Program Files x86 and say that settings will be preserved. Then install to Program Files itself. I believe standards and consistency are beneficial.

**Comment by JoelTroch** [comment]
AFAIK, there are no differences between a x64 app running on "Program Files" and "Program Files (x86)", the reason of why there are 2 "Program Files" folders is to seperate x86 and x64 apps.

**Comment by Tarun80** [comment]
As far as the files themselves, there is no difference. However it's best to keep x86 and x64 apps in their respective folders.

Also a good read: http://www.howtogeek.com/129178/why-does-64-bit-windows-need-a-separate-program-files-x86-folder/

**Comment by felix91gr** [comment]
Is this issue still happening?

**Comment by Krzmbrzl** [comment]
I am rather sure that at least for 1.4.0 Mumble is installed into the Program Files directory. In fact you can't even choose anymore xD
See #4702

@felix91gr thanks for drawing attention to this old issue :ok_hand:

**Comment by mirh** [comment]
Yup, now it always installs on program files.
