### ISSUE TITLE
Push to Talk Sticking On / Ubuntu 14.04

### ISSUE THREAD

**Issue by geudrik** [mumble-voip/mumble#1319]
### The Issue
Push to Talk stays active when I activate PTT and my mouse *is* active within my primary display (my middle display - I have three total)

### Notes
PTT works as expected when my mouse is active within either my left or right hand monitors. The left hand display is secondary, the right hand is tertiary.

As soon as my mouse is active within my primary display (the middle), I *can* activate PTT to speak, but when I release my bound key, I continue to transmit. I am unable to toggle the PTT once activated from my primary display. 

To fix the the above "stuck" scenerio, I have to move my mouse either to my left or right hand monitors and press my PTT key again. This does fix the issue. However, it clearly is having a hiccup along the way somewhere.

### Additional Information
* Ubuntu 14.04 x64 3.13.0-29-generic Unity (Fresh Install)
* Pulse Audio, G930 Headset, G500 Mouse using MButton 5 as PTT Key
* Encrypted boot and homes
* I have "Launcher Placement" in Settings->Displays set to my middle display (not the default of "All Displays")
* DoublePush Time is set to "Off"

**Comment by pixel5** [comment]
I know this isn't exactly a fresh issue, but I had this same problem on Ubuntu 14.04 and `sudo chmod a+r /dev/input/event*` then restarting mumble fixed it. Just wanted to confirm, thanks guys!

**Comment by dwightjl** [comment]
The `sudo chmod a+r /dev/input/event*` command no longer fixes this issue in the newer versions of mumble.

OS: Linux Mint 17.2, but I first encountered this issue on Arch.

Mumble versions tested:
+ Mumble 1.2.10-1 from the ppa:mumble/release repository.
+ Mumble 1.3.x from the ppa:mumble/snapshot repository.

The command still works to fix Mumble 1.2.4-0.2 from the default Ubuntu repository. It's also strange to see that 1.2.4-0.2 recognizes one of my mouse buttons as "Mouse 4", while versions 1.2.10-1 and 1.3.x see that same button as "Mouse 8". Something must have changed significantly in the way Mumble identifies mouse button events.

**Comment by jocelynthode** [comment]
@geudrik yeah problem is present on arch with gnome and chromium even applying the fix doesn't work anymore.

**Comment by vith** [comment]
The workaround is no longer effective for me either. I see `GlobalShortcutX: Using XI2 2.0` at startup now instead of any `/dev/input/event*` devices. Can we re-open this issue?

**Comment by tazjin** [comment]
Note that you also need to enable kernel input devices, as per [this comment](https://github.com/mumble-voip/mumble/issues/1726#issuecomment-115885189).

**Comment by mkrautz** [comment]
Note that because of a bug in the 1.2.10 release, you'll have to use the following instead:

https://github.com/mumble-voip/mumble/issues/1726#issuecomment-133029289

**Comment by FilipPyrek** [comment]
I've been browsing these issues for a while. I've downgraded, upgraded (even snapshots) and tried these solutions. Noting works permanently (after system restart). So can somebody tell me, if there really is some solution or atleast where is the problem? I (and IMHO all Linux users) would really appreciate it. Thanks. :+1: 

My OS: Ubuntu 14.04, tested versions: 1.2.4-0.2ubuntu1.1, 1.2.10-1~ppa5~trusty1, 1.3.0~797~g74d19f4~snapshot-1~ppa1~trusty1

**Comment by patoupatou** [comment]
Can confirm the problem is still there (1.2.10) and the workaround is not working anymore (even with the .conf modification).

**Comment by mkrautz** [comment]
This should not have been closed.

**Comment by mkrautz** [comment]
Workaround is at https://github.com/mumble-voip/mumble/issues/1726 (re-enable evdev)

**Comment by geudrik** [comment]
Confirming that workaround for some, caused by 6edf2c6008805fce41d20e1fe929a178cca417cd at #1726, works. Thanks @mkrautz :+1:

**Comment by mkrautz** [comment]
@geudrik FYI, there is a fix in git master.  If it works for people, we will backport into 1.2.x and do a 1.2.11 release eventually.

**Comment by vith** [comment]
@mkrautz I can confirm I no longer need any workarounds when using a build from master.

**Comment by Barthalion** [comment]
I just want to make a little anecdote about this bug fix – I actually used the described behaviour to have microphone always on when I needed to move away from laptop on which I use push-to-talk. [This XKCD](https://xkcd.com/1172/) became really relevant to me now.

But really, thanks for the fix, it was really annoying at first.

**Comment by hacst** [comment]
@Barthalion But we have a real feature for that ;) If you go into the PTT configuration you can set a "Double push" time. If you press PTT twice in below the time you configured there it'll stick.
