### ISSUE TITLE
Timer on the server to simultaneously enter the network lobby.

### ISSUE THREAD

**Issue by sem174** [mumble-voip/mumble#1321]
Good day! I think not only me, but many other players interested in the request. Is it possible to add a timing function to the server, with the conclusion of the client window in the overlay + digits of reference? such as 1 - 2 - 3 or vice versa can be forced 3 - 2 - 1. desirable accompaniment reference sound - "beep" or something like that. Well, the countdown for each room separately desirable. Running reference any signed-in users on any hotkey.
![countdown](https://cloud.githubusercontent.com/assets/8233588/3656166/52b0b16c-1183-11e4-9d4e-d3a5e3388e30.gif)
Sorry for my English, use Google translator

**Comment by Kissaki** [comment]
Unclear use case. Countdown can be implemented via serverside scripts. I don't think a niche countdown only useful for very few users (I don’t know what this would be used for) warrants server side code. With our low voice delay, counting down with voice should be good enough.
