### ISSUE TITLE
I cannot alt tab when mumble is running

### ISSUE THREAD

**Issue by zoomdude44** [mumble-voip/mumble#1327]
So I recently reformatted my computer, before I did this I could alt tab while mumble was running with no problems, now when I have it running when I try to alt tab it looks classic (I re-checked aero in properties and still does this) and the alt tab box will just sit there and not actually switch to that tab and when I click it just goes away. ive tried restarting the computer aswell, I use mumble often so not using it is not an option, what can I do to troubleshoot this?

**Comment by Kissaki** [comment]
So does windows simply disable aero and display the non-aero alt-tab dialog?
You can still use *that* though?
Could you provide a screenshot?
