### ISSUE TITLE
The clearlook theme has disappeared - 1.3.0~342~g340c7b6~snapshot

### ISSUE THREAD

**Issue by Venopsis** [mumble-voip/mumble#1329]
Hello,

As told in the title, since I update to 1.3.0~342~g340c7b6~snapshot, the cleanlook theme has disappeared. I can't choose it but I really don't like the others theme.

Could you go it back please?

Cordially, Venopsis.

**Comment by hacst** [comment]
With #1459 I was planning to completely ditch the option for a user selectable qt style. Their nature makes them incompatible with themes (though I was thinking about whether themes should be allowed to set them if they want to). In any case I don't think we should start shipping non-standard ones.

**Comment by mkrautz** [comment]
Qt themes are unavailable due to the implementation of Mumble's new theming system.
