### ISSUE TITLE
Murmur doesn't open UDP Port since mumble-1.3.0~342~g340c7b6~snapshot (Windows)

### ISSUE THREAD

**Issue by MiskyWhixer** [mumble-voip/mumble#1343]
As already said in the issue title, murmur does not open an UDP Port since the mumble-1.3.0~342~g340c7b6~snapshot version under Windows Server 2008 R2.
As result it looks like it's offline in the favorite serverlist and the server is not listed in public server list.
Instead it opens an TCP und UDP port for IPv6 wich I do not use on my server.

**Comment by hacst** [comment]
Should be fixed by #1689 . Please verify with the coming snapshots 1.3.0-650 .
