### ISSUE TITLE
Current Left 4 Dead 2 release breaks positional audio support.

### ISSUE THREAD

**Issue by PianoRoKR** [mumble-voip/mumble#1344]
Newest L4D2 release 2.1.3.6 breaks the positional audio support. Probably another change in offsets with the minor release.

**Comment by Fablock** [comment]
Any update on this issue? Tried to compile it myself but i have no knowledge of C++.So in the end mumble didn't recognize the plugin.

**Comment by Ophidiophobia** [comment]
Have you read http://wiki.mumble.info/wiki/Pluginguide#Compile_the_Plugin ? 
If you compiled the plugin successfully then maybe it could be this bug https://github.com/mumble-voip/mumble/issues/1529 ?

**Comment by mkrautz** [comment]
The L4D2 has been updated since. (Thanks @davidebeatrici)
