### ISSUE TITLE
Feature Request: Listen Permission

### ISSUE THREAD

**Issue by nocmonkey** [mumble-voip/mumble#1352]
Add a listen permission in order to allow admins the ability to control deafening via ACLs.

**Comment by ZeroAbility** [comment]
Does this provide the requested feature?

https://wiki.mumble.info/wiki/ACL_and_Groups/English#Mute_.2F_Deafen

**Comment by Hartmnt** [comment]
> Does this provide the requested feature?
> 
> https://wiki.mumble.info/wiki/ACL_and_Groups/English#Mute_.2F_Deafen

No, I think this is more or less a duplicate of #1257

**Comment by Krzmbrzl** [comment]
I agree. Let's close this as a duplicate
