### ISSUE TITLE
Pause key and NumLock key bug

### ISSUE THREAD

**Issue by jklphe00** [mumble-voip/mumble#1353]
This is confirmed to happen in DotA 2, Guild Wars 2, and ArcheAge. A friend of mine has the same problem. I have not tested other apps/games. This bug may occur in other apps/games.

The bug:

First, I have the Pause/Break key set up as the toggle "Deafen Self" shortcut. Everything works as it should at first. However, when I am playing DotA 2, Guild Wars 2, or ArcheAge in fullscreen and I press NumLock, I am deafened and muted as if I had pressed the Pause key. This is very odd so I thought that maybe Pause and NumLock were tied to each other. To confirm my suspicion I changed NumLock to the shortcut for toggling "Deafen Self". NumLock works to toggle deafen and mute on Mumble when I'm in-game as it should. But, when I pressed the Pause key in-game, I became deafened and muted as if NumLock was pressed. Now, if I change the toggle "Deafen Self" shortcut to something other than Pause or NumLock such as left Control, pressing Pause or NumLock in-game does not trigger the toggle. This leads me to believe that Pause and NumLock are linked in some way with Mumble in games. I am not aware of any other keys that cause a similar issue to occur. Changing the game to windowed mode makes no difference compared to fullscreen mode.

A friend of mine who uses the same shortcut hotkeys has the same issue.

Possible Solution:

After Googling a bit on Pause/Break and NumLock relationships, I discovered this information on the Wikipedia page for "Break key":
Pressing the dedicated Pause key on 101/102-key keyboards sends the same scancodes as pressing Ctrl, then NumLock, then releasing them in the reverse order would do; additionally, an E1_hex prefix is sent which enables 101/102-key aware software to discern the two situations, while older software usually just ignores the prefix.
Source: http://en.wikipedia.org/wiki/Break_key

It seems to me that Mumble just needs to discern the difference between the Pause/Break key and the NumLock key using the E1_hex prefix.

I hope this issue will get resolved in a near future release. Thank you and keep up the good work on Mumble.

EDIT: It just became apparent to me that the games could possibly be the ones to report the key presses to Mumble rather than Mumble capturing the key presses since Pause and NumLock work fine outside of games to toggle Deafen Self. If this is the case then it would be up to the games to issue a fix and Mumble has nothing to do with the problem at all. I have no idea how Mumble works with games though so maybe I'm talking out of my ass. Hopefully this is something that can be worked on within Mumble. Thanks again.

**Comment by danielocdh** [comment]
The issue is not present on Pause hotkey on teamspeak and ventrilo, it might be something more DX related, but still Mumble's issue.

**Comment by timvisee** [comment]
I'm experiencing the same issue.

When assigning shortcuts in the settings window, the <kbd>NumLock</kbd> and <kbd>Pause</kbd> key are both recognized when either of them is pressed.

I'm using Mumble 1.2.13 on a Windows 7 Home Premium 64-bit machine.

**Comment by phage80** [comment]
Even in the most recent 1.3.0 snapshot this is still an issue.
![ptt](https://cloud.githubusercontent.com/assets/2360654/20269627/fa149572-aa51-11e6-9d1c-b9f3ef2b917b.jpg)

**Comment by mkrautz** [comment]
Only happens with WinHooks enabled.
The scancode code in GlobalShortcut_win needs to consider the scancode with the E1 prefix as mentioned by @jklphe00.

**Comment by mkrautz** [comment]
I have a fix pending in #2641

**Comment by timvisee** [comment]
Awesome! 

I'll give the fixing commit a try when I get home.

**Comment by mkrautz** [comment]
Note that I was never able to reproduce a case where both keys were shown at the same time in the shortcut settings.

What I saw was the same as @jklphe00 reported: when binding the keys, everything worked as it should. But when in another program, both keys would trigger one another.

That's what my PR fixes.

I'm curious if it fixes the problems both you and @phage80 were seeing.

**Comment by timvisee** [comment]
Can you supply a binary for me with PR #2641 in it, so I can test it out?

I currently haven't set up a building environment for Mumble, and I honestly don't want to go through the hassle of doing it as I'm quite busy at the moment.

**Comment by mkrautz** [comment]
Sorry, we'll have to wait for someone to review it before we can distribute a snapshot.

**Comment by mkrautz** [comment]
@timvisee A snapshot with the change is now available.

**Comment by timvisee** [comment]
I can confirm that the issue doesn't persist after the update to the latest 1.3.0 snapshot available on Mumble's Wiki.

![Mumble configuration screenshot](http://i.imgur.com/v0k2zLe.png)

Thanks a bunch!
