### ISSUE TITLE
Overlay causes FPS drops ingame

### ISSUE THREAD

**Issue by AL-97** [mumble-voip/mumble#1359]
Hello. When I use overlay in Mumble it causes the game to skip some frames. I have tested it DayZ, Portal 2 and Spelunky. And in all of those games when I enable overlay the game starts to skip some frames. I've noticed this issue since version 1.2.8, while previous version 1.2.7 was fine. I've tried unistalling 1.2.8 and installing 1.2.7 back again, but the issue persists. Please help.
Thanks.

**Comment by Kissaki** [comment]
Given that this issue is still open, I would like to come back to it. Is this still an issue for you?

Can you describe more detailed how you determine skipped frames or fps drops? Purely a "feel" from looking at the game? Is it noticeable stuttering?
