### ISSUE TITLE
Move registry config keys into an appropiate config file within appadata

### ISSUE THREAD

**Issue by ranomier** [mumble-voip/mumble#1360]
It is a common practice for software on windows (since winXP) to store their configuration data in %appdata% instead of the registry. Saving and restoring the configuration after fatal system crashes is much easier this way. Configurations of user space software does not belong in the registry, anymore.

**Comment by ranomier** [comment]
Just use the same config code as Linux. I think that would be less code :)

**Comment by davidebeatrici** [comment]
Superseded by #1940.
