### ISSUE TITLE
Positional Audio plugins missing from list and will not update

### ISSUE THREAD

**Issue by EbuVitae** [mumble-voip/mumble#1371]
![screen shot 2014-08-24 at 4 58 23 pm](https://cloud.githubusercontent.com/assets/8539770/4024805/d4891952-2bd9-11e4-941e-3f5a6558df33.png)
Screenshot says it all. Running on OS X Mavericks. Have tried all sorts of versions (non-universal, universal.) What version do I need to use to re-get the plugins, or, where can I download them?

**Comment by Hiradur** [comment]
According to http://wiki.mumble.info/wiki/Games there are no plugins for OS X available, is that correct?

**Comment by mkrautz** [comment]
There are no positional audio plugins for OS X, correct.

**Comment by mkrautz** [comment]
@EbuVitae Anything specific you were interested in?

**Comment by EbuVitae** [comment]
Thanks for the help anyway. I figured that the plugins were just incompatible, but I couldn't find any definitive answer.

**Comment by Hiradur** [comment]
@EbuVitae You should still get positional audio in games with native support which are marked with a blue background in the list linked above.
