### ISSUE TITLE
[BUG/SECURITY] (Possible IP Address Leak)

### ISSUE THREAD

**Issue by CanadianJeff** [mumble-voip/mumble#1388]
I was told if you go into mumble's config (network -> advanced -> misc) you can disable image download. This setting should be visable by default.

how to leak a users IP and user agent

1: right click send message to a channel or user
2: click on source text
2a: send an image using img src="http://somesite.tld/someimage.jpg"
2b: press ok/send without going into back preview mode
3: check log files on the web server that hosts the image

**Comment by Kissaki** [comment]
> It's not an important enough feature.

For *you*.

**Comment by skobkin** [comment]
> is easy update of banners

Yes. We are using external images for server banner.

I think it may be option in client that can disable fetching external images. Or it can be server option that restricts HTML images in messages from non-privileged users.

**Comment by SteffanLong** [comment]
This would be best resolved as an option in the server .ini configuration file.

**Comment by Vash63** [comment]
I'd also like a server side option on this. I'm running a murmur server and one of the people on it is a streamer, pretty worried with all the DDOSing for streamers and pros that if someone else on the server sends a general chat message or something it could leak his IP.

**Comment by mkrautz** [comment]
It's worth noting that it's already achievable by disabling HTML with allowhtml=false.

I assume that is not enough?

We could pretty easily add an allowexternalimages=false option that only strips external (non-data URL images).

**Comment by Vash63** [comment]
allowhtml should work for now, I'd definitely make use of a flag to disable
externally hosted images though.

**Comment by CanadianJeff** [comment]
closing due to old age this should have been solved by now

**Comment by CanadianJeff** [comment]
any reason for reopening this issue?

**Comment by CanadianJeff** [comment]
should this issue remain open?

**Comment by Vash63** [comment]
I personally would still like to see a feature that filtered out any img= links that went to external domains (maybe offer a whitelist in the .conf of allowed domains?). I'm not sure this is really within the 'BUG' tag as it feels more like a feature request at this point though. The 'allowhtml' setting has sufficed as far as security is concerned, this would just be helpful functionality to allow HTML while still providing similar security.

**Comment by pasimko** [comment]
Bumping this. Is this still an issue?

**Comment by davidebeatrici** [comment]
We can't enable the option by default, as there's a problem with it: it replaces the entire message with `[[ No valid image ]]`, meaning that if someone sends a message with an external image and some text, you wouldn't see any of the two.

Also, the external image should be replaced with its URL, so that you can see it outside of Mumble or save the link.

I think it's safe to enable the option once we have fixed these two things.

**Comment by bontibon** [comment]
Fixed with #3168.
