### ISSUE TITLE
Do not auto reconnect when connecting from another client

### ISSUE THREAD

**Issue by Gunni** [mumble-voip/mumble#1395]
The Mumble client should not reconnect when it is booted off a server because the same user has connected from somewhere else.

Currently, this happens:
> [XX:XX] Gunni connected.
> [XX:XX] Gunni disconnected.
> [XX:XX] Gunni connected.
> [XX:XX] Gunni disconnected.
> [XX:XX] Gunni connected.
> [XX:XX] Gunni disconnected.
> [XX:XX] Gunni connected.
> [XX:XX] Gunni disconnected.
> [XX:XX] Gunni connected.
> [XX:XX] Gunni disconnected.
> ...

**Comment by bontibon** [comment]
This issue was fixed with #1576.
