### ISSUE TITLE
Redirection feature

### ISSUE THREAD

**Issue by HarpyWar** [mumble-voip/mumble#1401]
Hello,.
A lot of hosters experiencing DDoS attacks on their servers and it occurs very often at the last time. In most cases a datacenter simply null-routed a server IP that was DDoSed for 24 hours, but the server is still available from other IP addresses (if binded).  
I have an elegant suggestion how to solve this for Mumble servers. It should be easy to implement and saves a lot of nerves for hosters and end users :). 
1. When user connecting to a Mumble server he should receive a first packet from the server with IP address list which Murmur is bind (`host` option from `murmur.ini`, or even a new option `failoverhost` that can have IPs from other physical servers).
2. These IPs should be saved into a client connection settings for that server (and updated for each next connection to keep up to date).
3. If a connection lost to the main server IP a Mumble client should check next IP from the list for availability and auto-reconnect to the server.

Thus, we have a simple and effective fail-over system. I hope it can be done in next Mumble release.
What are you thinking about it?

---

P.S. It will not work for new users who didn't connect to a server yet (because they didn't received a list with reserved IPs). But this should not be a problem, because there are mostly regular visitors for a single Mumble server, and above feature will allow teams save a voice communication during important events if their server is unreachable due to a DDoS.
Also the problem can be solved by informing each user about reserved IP. But actually this is not a solution and very uncomfortable. Most users will not add a reserved address to their Mumble clients until a first accident

**Comment by ZeroAbility** [comment]
It sounds like what is being proposed is to make Mumble server act like DHCP with DNSSEC. I don't think that Mumble server should supplement attacks of these types by storing extra information that could fall out of date without proper purging. It would also be subject to the same types of cache poisoning attacks which means the Mumble server attack surface would increase.

**Comment by Krzmbrzl** [comment]
From what I have read in here it seems that the core functionality of this request is already available through SRV records. The arguments for why those are inappropriate, I couldn't quite follow (though I'm not too versed in DNS records to begin with - that might be the culprit).
Could someone summarize why we require an extension of what is available through SRV records? :thinking:

**Comment by HarpyWar** [comment]
@Krzmbrzl
The primary reason for utilizing an external service to redirect connection requests, instead of default DNS, is the inherent delay in DNS record propagation up to 48 hours (or even more if DNS server uses invalid cache), which makes rapid IP address changes unfeasible. With external service, this limitation is overcome, allowing for swift updates to IP addresses without the usual waiting period.

**Comment by Gunni** [comment]
Just decrease the TTL and your problem is solved.

**Comment by Gunni** [comment]
> In fact, it does not work. ISP policy cache for DNS and user's local cache, leading to some users still resolving to the old IP address.
> 
> How wildcard DNS may help in this case?

Just assume all deployments respect TTL, if they serve stale data non-standard and violating RFCs anyway, just ignore them, and if the users complain, tell them that.

Sorry, not wildcard dns, but maybe you could use CNAME records for it, `a.example.com`, `b.example.com` both point to `srv.example.com` and you put the srv records on that name.
