### ISSUE TITLE
attenuation permanently drops Adobe Flash volume in mixer

### ISSUE THREAD

**Issue by rohku** [mumble-voip/mumble#1402]
When I use attentuation in mumble while using Adoble Flash Player (11.8 r800), the volume of Flash will sometimes get stuck on the attenuated level.  I have to manually open up my sound mixer and raise it back up to full volume.

Adobe Flash Player is being used to youtube, primarily.

I'm using Windows 8.1 64 bit.

**Comment by skobkin** [comment]
Same problem on Gentoo with PulseAudio. Not only with Flash. Mumble sometime behaves strangely with Clementine.

**Comment by ZeroAbility** [comment]
This occurred with Left 4 Dead 2 when attenuating on the output when others are speaking. All other volumes were at the correct level except for the game. It never reverted back to its original volume. This was noticed in the audio settings under KDE 5 in latest Manjaro.

**Comment by ZeroAbility** [comment]
Adobe Flash Player is no longer supported by Adobe.

https://www.adobe.com/products/flashplayer/end-of-life-alternative.html

This could probably be closed.

**Comment by Krzmbrzl** [comment]
Yep, closing this.
