### ISSUE TITLE
Port overlay_gl fixes from PR 1431 to OS X and Windows

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1432]
PR #1431 implemented a bug fix for overlay_gl. (Landed as https://github.com/mumble-voip/mumble/commit/6e9a7e7cb1b1fa9468bba965f34bed0f24017805)

We should port this to the two other OpenGL overlays: Windows and OS X.

**Comment by Kissaki** [comment]
How can I test this on windows? Do we actually know any games that use OpenGL and have this issue?

**Comment by Kissaki** [comment]
The OpenGL overlay code is quite different between win and nix. The drawing happens at two pretty different times.
An effort has been made to improve the win opengl overlay code; to make it more readable.
It may be wise to first further analyse the differences between the two, and to converge them.

**Comment by ZeroAbility** [comment]
This appears to have been resolved according to the following:

https://github.com/mumble-voip/mumble/pull/1520#issuecomment-70384021
