### ISSUE TITLE
1.3 snapshot - Deafening and muting yourself, causes delay for the rest of the conversation

### ISSUE THREAD

**Issue by mumbledenoise** [mumble-voip/mumble#1446]
Using the latest 1.3 snapshots, when I deafen and mute myself for a while, then turn it off so I can talk and hear again, there is about a second delay in the conversation.  I was able to repeat this multiple times.  Disconnecting and reconnecting to the Mumble server fixes the delay.

**Comment by Kissaki** [comment]
>  This lag was immediately removed after I disconnected and reconnected.

Does it persist if you do *not* reconnect?
Like, is it still there 2 minutes later?
