### ISSUE TITLE
Random Qt Crashes with 1.3 snapshot (OS X 10.10)

### ISSUE THREAD

**Issue by zorgiepoo** [mumble-voip/mumble#1448]
Mumble version: 1.3.0~425~g6f2552d~snapshot

Mumble seems to crash on OS X 10.10 at random points when bringing up or dismissing a window (e.g., bringing up preferences window, hitting cancel on connections window, trying to join a server). I suspect the problem is with Qt; it's not 100% reproducible. I didn't encounter the problem with 1.2.8 though.

Crash logs were submitted under an email containing this username.

**Comment by zorgiepoo** [comment]
I have no idea (don't use Mumble these days) and I don't recall what crashlog I sent back then was.

**Comment by Krzmbrzl** [comment]
Okay - thanks for the update nonetheless :)
In that case I'll close this issue though
