### ISSUE TITLE
Annoying problem with tray icon functionality on Windows

### ISSUE THREAD

**Issue by Zuko** [mumble-voip/mumble#1452]
After https://github.com/mumble-voip/mumble/commit/06d9f7e6d0ab6081393d4169a10de7ad84010cc3 if you click twice on mumble tray icon mumble window does not show again on next click (if its under other window). Only "fast" doubleclick causes this. We talk about it on IRC right after your @hacst commit.

Previous change was a lot worse. But this needs to be fixed.

**Comment by davidebeatrici** [comment]
Fixed in 90bef53571313c56493a0ed1efc8599f2b5b9908.
