### ISSUE TITLE
QWhatsThis dotted border around shadow

### ISSUE THREAD

**Issue by xPoke** [mumble-voip/mumble#1457]
The QT QWhatsThis widget (which also cannot be styled with QSS) draws a dotted border near it's shadows instead of a solid border. The border and/or shadow cannot be removed (even on styles without shadows such as GTK+).
This affects channel comment popups, as well as the usual What's This popups.

![3lc4r9h](https://cloud.githubusercontent.com/assets/2204968/4872102/1a548c48-61d9-11e4-8b2d-f1ffb7d92f19.png)

This is an existing QT bug - https://bugreports.qt.io/browse/QTBUG-1203

Possible solutions:
- Inherit or re-implement QWhatsThis with correct drawing.
- Inherit or re-implement from a different class and reduce use of QWhatsThis (for example QToolTip or QPopupMenu). This will solve other skinning issues.
- Wait for upstream fix

**Comment by davidebeatrici** [comment]
Resolution is marked as "out of scope" on Qt's Bug Tracker: https://bugreports.qt.io/browse/QTBUG-1203

**Comment by davidebeatrici** [comment]
The bug is not present anymore.
