### ISSUE TITLE
Same frequencies, different response

### ISSUE THREAD

**Issue by mirh** [mumble-voip/mumble#1458]
I have a cheap USB webcam with built-in microphone. 
Today I installed mumble and I noticed it couldn't hear me. 

After half an hour of messing, I changed format from 16bit, 32000 Hz to 16bit, 32000 Hz (FM Radio quality).. and it worked

**Comment by Kissaki** [comment]
Is it still reproducible after changing it back and forth?
FM Radio works, the other does not?

Where did you change that setting?
In windows? Or a driver specific configuration?

Can you name the webcam model/product?

**Comment by mirhl** [comment]
The webcam is an [Emtec W100](http://web.archive.org/web/20071010121157/http://www.emtec-international.com/en/produit.php?categorie=AVNOM&gamme=AV%20WEBCAMS&ss_gamme=W100). As I said is old as hell (and I couldn't even find it atm to test with latest nightly)

Anyway, yes it was reproducible. 100% of times. FM Radio was the one working correct. 
And I just adjusted it in [windows](http://www.walkernews.net/wp-content/uploads/2010/02/Disable-Exclusive-Control-Of-Sound-Devices-In-Windows-7.jpg) (random photo taken from the net)

**Comment by Krzmbrzl** [comment]
Did the webcam work in other applications if not set to FM Radio? If not, then I'm pretty confident that it's probably not Mumble's fault.

If other applications worked, it's pretty clear that it is indeed Mumble's fault. However we'd need a way to reproduce this. Thus in this case, it would be important to know, if you still have that webcam available for testing purposes (From your comment above I assume that you don't)...
