### ISSUE TITLE
Auto update check freezes the client

### ISSUE THREAD

**Issue by fletchowns** [mumble-voip/mumble#1466]
When I start mumble it always seems to hang for a sec and Windows will put (Not Responding) in the title bar. After 10-20 seconds it will become responsive again and the new version notification pops up. Any way to move the auto update check to a background thread or something so it doesn't hang the UI?

**Comment by Kissaki** [comment]
I also experienced this multiple times for a long time.
On the previous previous snapshot update as well.
I also guessed it was maybe the download of the installation file itself that made it become unresponsive.

**Comment by Tarun80** [comment]
I question a bit of the update logic. Such as, if there's a new build (snapshot or stable release); why download both the installer and the .dll plugins? If a new build is available, I would skip downloading the plugins since they're more than likely going to be in the new build install.

**Comment by Gunni** [comment]
I have this happen for every update, even the one i installed yesterday....

Always thought it just happens because the update is being downloaded by the main/UI thread...

**Comment by Krzmbrzl** [comment]
I assume this is still the case for the latest version?

**Comment by Krzmbrzl** [comment]
#3987 will move the preparation of the VersionCheck to another thread as well (the network request should be on another thread already) and with that I experienced no such micro-freezes anymore.
