### ISSUE TITLE
ASIO doesn't detect output line

### ISSUE THREAD

**Issue by mirhl** [mumble-voip/mumble#1472]
When I query the asio device (in my case cmasiopPCIX, on an asus xonar DX) mumble can only detect IN-00 and IN-01 (respectively microphone left and right channels)

I'm sure it's not driver's fault because both ASIO input and output work with [audacity special compiled ASIO-enabled](http://error420.com/audacity/) version

**Comment by Kissaki** [comment]
![2015-01-06 01_39_42-mumble configuration](https://cloud.githubusercontent.com/assets/93181/5622521/1451db08-9545-11e4-9dc0-6563bb68a409.png)
This is what you see as well?
And you would expect to also see OUT channels?
How does it look on audacity?

**Comment by mirhl** [comment]
In audacity I can just select: ASUS Xonar ASIO driver and it works. 
Anyway it [seems](http://ixbtlabs.com/articles3/multimedia/asus-d2.html) there should be **8** channels. 

And his is just a screenshot from foobar2000 with relative plugin. 
![0000](https://cloud.githubusercontent.com/assets/9366725/5652437/f36ba280-96b0-11e4-9d3c-8dbe58641200.PNG)

Btw would it be possible to include ASIO support even for 64bit mumble version?

**Comment by mkrautz** [comment]
@mirhl I've created a bug for x64 ASIO: https://github.com/mumble-voip/mumble/issues/1518
Thanks for reminding me.

**Comment by AforAnonymous** [comment]
Same exact issue here, Xonar U7 Echelon. I first thought it was Asus at fault, but it seems to be a Mumble issue.

**Comment by mirhl** [comment]
I think this may be considered a duplicate of #1113

**Comment by mkrautz** [comment]
Close as duplicate per @mirhl's correct suggestion.

Please move discussion there.

**Comment by mirhl** [comment]
Doh, I'm dumb .-.
I actually meant *that* to be a duplicate of this, given this seemed more.. followed... but whatever.

**Comment by mkrautz** [comment]
Don't worry, the other issue was older, so technically this is the duplicate. :-)
