### ISSUE TITLE
Bountysource Integration

### ISSUE THREAD

**Issue by meZee** [mumble-voip/mumble#1477]
copy&pasted from an issue I've submitted on a different project. I think it is also relevant for this project, I think it may warrant a discussion label.

[Bountysource](https://www.bountysource.com) is a Issue/Feature bounty service, it does not require GitHub integration, however this project can benefit from the features highlighted in the picture below.
![Bountysource Integration Overview](https://d2bbtvgnhux6eq.cloudfront.net/assets/github-plugin-fd1985c4382e1a4e395fcc254e3dafac.png)

Bountysource is similar to [ChangeTip](https://changetip.com), and [tip4commit](https://tip4commit.com). However, unlike the aforementioned it allows support of specific Issues & feature requests. This allows those who tackle the task to claim any said bounties when the relevant issue/feature-request is resolved or merged. As opposed to tipping a specific committee regardless of whether or not that specific Pull-Request is implemented.

Bountysource is used by big companies like Facebook, Github, and IBM, as well as prominent Open-Source projects like ZNC & OpenRA to name a couple. 

There are no fees except during withdrawal, upon which they assess 10% fee.They allow bounties to be placed using Paypal, Google Wallet, & Bitcoin, and to be withdrawn using whatever is preferred.

To add Bountysource integration you need to be a public member of the repo's GitHub Organization, and navigate to https://www.bountysource.com/tools, preferably after creating a new team https://www.bountysource.com/teams/new.

**Comment by bontibon** [comment]
We're not going to add this.
