### ISSUE TITLE
Mumble's (x64?) opus.dll crashes when encoding audio when built with MSVC 2013.3 / 2013.4

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1480]
See latest standalone reproducible case here:

https://gist.github.com/mkrautz/a122c52f3033da12cc57

**Comment by hacst** [comment]
According to MS the issue will be fixed for VS2015.

Their suggested workaround for the meantime:
> If you need a source code workaround, please disable optimization of the affected functions using #pragma optimize ("", off). The affected functions typically have a sequence of square root caculation.

Will keep this issue open until we transitioned to VS2015 and removed the opus workarounds

**Comment by hacst** [comment]
Verified that our minimal test case no longer crashes with VS 2015 RC. Seems like they fixed it.

**Comment by mkrautz** [comment]
Microsoft fixed this in MSVC2015, and we've added a workaround to our Opus.
Closing.
