### ISSUE TITLE
OS X Client Uses System-Only Certificate Authority

### ISSUE THREAD

**Issue by emperor06** [mumble-voip/mumble#1483]
On OS X Mumble client (1.2.8) when the server prompts its ssl certificate, it is verified using the system keychain only.
OS X has actually 3 default keychains that hold our certificates: the user keychain (in ~/Library), a "custom system keychain" or computer keychain located in /Library, and an OS X System keychain in /System.
The user certificates go into the first one. The certificate authorities we want to add and trust go into the second one and are used globally (for all user, hence "system-wide". The last keychain simply cannot be changed (and should not) as it is provided and maintained by Apple (users should never alter /System).
A quick trace of the Mumble client shows that the only files checked are /System/Library/Keychains/SystemTrustSettings.plist and /System/Library/Keychains/SystemRootCertificates.keychain, which are basically that last system keychain we cannot alter.
As a result, when using our own certificate authority (which is correctly registered in the /Library system keychain) Mumble fails to verify the identity of the server since it cannot access the root certificate.

Affected OS:
Mac OS X (probably all versions). The Windows client correctly uses the system certificate store where the users can trust their own certificate authorities.

Expected Result:
Since my own CA is registered on all my computers, I do expect Mumble to connect my own server without any warning, which is actually the case on my Windows computer.

Actual Result:
The OS X client prompts me with the following warning:
Sever presented a certificate which failed verification..
The specific errors with this certificate are: 
The root certificate of the certificate chain is self-signed, and untrusted
Do you wish to accept this certificate anyway?
(It will also be stored so you won't be asked this again.)

Possible Workaround:
1. I can manually review the server certificate from the warning popup and tell Mumble to accept the certificate anyway, which will tell Mumble to trust my own CA. But that defeats the purpose of trusting that CA system-wide. My own CA is already trusted on my Mac and I'd like Mumble to know about it (by looking into the correct keychain)
2. Install my CA into Apple's keychain in /System. This is a very bad idea. It will be reset on OS X update and I would have to hack the system keychain to do that (provided it's even feasible)
3. Use a certificate issued by CA already present in the Apple's trusted CA list which I won't do anyway since I do not trust what Apple trusts (yes, I do trust myself more than Apple :p)

**Comment by guruz** [comment]
Hey guys, we're having the same issue for OS X in the ownCloud client. 
@mkrautz Did you have something in gerrit already? Else I can attempt..

**Comment by mkrautz** [comment]
@guruz We haven't patched this yet. Please go ahead :-)  Once it's in gerrit or you a patch, please ping me, we'd like to add it as a patch ot our Qt 5 build for snapshot releases. :-)

**Comment by mkrautz** [comment]
@guruz Did anyone end up working on this? I am hacking on various QSsl things right now, so I can submit this to Gerrit soon, if no one else has done the work.

**Comment by guruz** [comment]
@mkrautz Sorry no :) Just had the look at the code in https://github.com/owncloud/client/issues/2964#issuecomment-93400280 and did not find time to do anything. Please go on....

FYI @richmoore @peter-ha

**Comment by guruz** [comment]
@mkrautz Just checking in :) Did you have any success? Could go into 5.5.1 then..

**Comment by mkrautz** [comment]
No, sorry, haven't gotten to it yet. Currently working on getting settable Diffie-Hellman parameters in for 5.6.

**Comment by ontheroadagain** [comment]
El Capitan will prevent users with admin privileges from altering /System because of System Integrity Protection, so it seems like OP's workaround #2 goes out the window. :)

**Comment by mkrautz** [comment]
Well, it's not like it's a particularly hard issue to solve, it just needs someone to do it. :-)

**Comment by guruz** [comment]
Do you guys want to test https://codereview.qt-project.org/#/c/140966/2

FYI @danimo

**Comment by danimo** [comment]
Rather more generally https://codereview.qt-project.org/#/c/140966. There have been a few revisions on top.

**Comment by mkrautz** [comment]
Thanks, patches are now merged into our Qt 5.5.1 build:
