### ISSUE TITLE
Mic stays on if push to talk button is pressed when minimized

### ISSUE THREAD

**Issue by Amusingdock25** [mumble-voip/mumble#1485]
Using Lubuntu 13.10 and if I press my mic button while the mumble window isn't "active" it stays on. It doesn't do the same thing if I have it set to voice activity and it works in windows

**Comment by dwightjl** [comment]
Is this issue related to the following issue?
https://github.com/mumble-voip/mumble/issues/1319

That solution might work for you on Mumble 1.2.4. However, I have been unable to find a fix for versions 1.2.10 and newer. Anybody have an answer for this issue on newer versions of Mumble?

**Comment by odielag** [comment]
This also happens to me also.
I'm using Ubuntu 14.04 as my operating system and when I use my push to talk key when another app besides mumble is focused mumble keeps transmitting even though I've let go of the press to talk button.

**Comment by Krzmbrzl** [comment]
Is this behaviour still present in the latest version?

**Comment by odielag** [comment]
No but I'm on a different setup. Debian 10 with another sound card.

**Comment by Krzmbrzl** [comment]
Okay. Let's hope the best and close this issue as resolved nonetheless. If it resurfaces, we can reopen this issue or create a new one :)
