### ISSUE TITLE
username regex doesn't support quantifiers

### ISSUE THREAD

**Issue by olaulau** [mumble-voip/mumble#1487]
when trying to limit username length via `mumble-server.ini` config file, I tried to use things like that : 
```
username=[\\-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]{3,32}
```
I also tried adding backslashed, and escaped backslashes before  { , }
but it fails with this in log file :
```
Configuration variable "username" is of invalid format. Set to default value of "[-=\w\[\]\{\}\(\)\@\|\.]+" .
```

config : `murmurd -- 1.2.8~7~g76f6870-2` (ubuntu 14.10 amd64)

**Comment by Kissaki** [comment]
We are using the [Qt QRegExp class](http://qt-project.org/doc/qt-4.8/qregexp.html), AFAIR,
which explicitly talks about quantifiers. So they should work.

**Comment by olaulau** [comment]
I still don't manage to create a username length limitation.
I've also tried to add parenthesis before the quantifier, with no success : 
```
username=([\\-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.])\\{3\\,32\\}
```
could you provide an example of qorking quantifier use inside mumble-server config file ?

**Comment by Natenom** [comment]
You need to use quotes because of the comma in the expression ...
The expression `username="[\\-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]{3,32}"` works on my testserver.

**Comment by olaulau** [comment]
seems to work great ...
thanks !
