### ISSUE TITLE
Mumble crashes on startup.

### ISSUE THREAD

**Issue by KingJulien2G** [mumble-voip/mumble#1490]
Hi, hope I can get this fixed here,

Recently downloaded mumble and when I launched it it crashed with the message "Mumble has crashed would you like to send a crash report" or some thing like that. No error code given.
I then tried to install it without the mumbleSkin, same thing happened.

2 uninstalls down the road I tried the manual install option via zipfile. Same. Thing. I don't know what to do by now basicly. I've tried everything from tips on shady forums to the customer support guides mumble provides and nothing's worked sofar.

Hope someone knows what's up thanks in advance.

**Comment by dae-eliador** [comment]
Hi
Same issue since today, even after fresh install of v 1.2.19 (after full and complete uninstall and manually deleting local appdata and register entries, rebooting, uninstalling and rebooting, using fresh downloads of client installer).

Thanks for your help.

**Comment by davidebeatrici** [comment]
Hi,

Have you tried installing a development snapshot?

**Comment by dae-eliador** [comment]
Hi,

I just tried latest 1.3.0 snapshot and it works.

Thanks.

2018-03-03 18:48 GMT+01:00 Davide Beatrici <notifications@github.com>:

**Comment by Krzmbrzl** [comment]
> I just tried latest 1.3.0 snapshot and it works.

Then I'll assume this issue to be fixed
