### ISSUE TITLE
Volume issues

### ISSUE THREAD

**Issue by haasn** [mumble-voip/mumble#1491]
OS: Windows 7
Mumble version: 1.2.8
Microphone: Blue Yeti
Issue: Mumble's concept of volume seems to require some amount of adjustment.

I ran the audio setup wizard and did my best to follow the instructions as accurately as possible - adjusting both the gain slider on the microphone and the volume slider in the Windows microphone settings to make the levels hit the blue, green and yellow parts of the displayed loudness spectrum as appropriate. The result had my microphone's gain knob at something near 50%, and the Windows slider at 30/100.

The result, however, was that I was unbearably, ear-shatteringly loud - I listened to it myself, it felt like I had to whisper or risk shattering my own eardrums. Something as simple as clicking my mouse sounded like a large object falling.

I then went ahead and ear-adjusted the volume settings until they were comfortable - the result was that my Windows settings were at 2/100, and my microphone gain knob was at like 30%, and the results were reasonable, but volume swayed greatly depending on my posture and orientation relative to the microphone.

After digging through the settings a bit looking for something similar to TeamSpeak 3's automatic voice gain control (I later found out that Mumble was supposed to have it integrated by default), I saw a slider labeled “Max amplification”, at the default setting of 20.00. After reducing this to 1.00, I could go back up a bit (to 4/100 in the Windows settings and 50% on the microphone knob) but volume still swayed greatly depending on my orientation - which is undesirable.

A short comparison to TeamSpeak 3: In TS3, I just enabled the “Automatic voice gain control” option, which had the result that my voice is automatically adjusted to a comfortable level, no matter how close or far I am from my microphone, nor how loud or quiet I'm talking. After enabling this option, I've no longer gotten any complaints about being too loud or too quiet.

It seems like Mumble should be doing the same thing in theory, but in practice I observed no such effect. In addition, the Audio Wizard misled me into nearly deafening my friends. I don't really know what to make of this, but until it is fixed I cannot possibly switch to or recommend Mumble.

**Comment by Kissaki** [comment]
> In TS3, I just enabled the “Automatic voice gain control” option, which had the result that my voice is automatically adjusted to a comfortable level

Does it lower your volume?

> the Audio Wizard misled me into nearly deafening my friends

Shouldn’t everyone be talking at a volume level of about 80 %, so going to 100 % would be loud, but not *that* bad?

I really don’t know what to make of this. Is the microphone / sound driver magnitudes too sensitive then?

**Comment by haasn** [comment]
> Does it lower your volume?

I'm not sure. It certainly affects the volume in some way, though, yes.

> Shouldn’t everyone be talking at a volume level of about 80 %, so going to 100 % would be loud, but not that bad?

In theory, yes. That's how we have it set up for teamspeak, at least - I run teamspeak at 100% software volume and it maps to a fairly comfortable volume range.

> I really don’t know what to make of this. Is the microphone / sound driver magnitudes too sensitive then?

Perhaps. I'm not sure how to debug this any further, all I know is that after following the audio adjustment wizard it was perceived as *way* too loud. Perhaps it was clipping / compressed like crazy?

**Comment by Krzmbrzl** [comment]
Were you able to reproduce this with Mumble 1.3?
