### ISSUE TITLE
Client using between 2 and 3Gb of ram after using for a while.

### ISSUE THREAD

**Issue by killawat** [mumble-voip/mumble#1497]
Mumble 1.2.8
Windows 8 Pro
Lenovo Y500

Sometimes it is less like 1.5 Gb after about an hours use, but it has been as high as 3Gb.
If you need anymore information I will be glad to provide it.

**Comment by skobkin** [comment]
I experienced same problem a long time. Mumble using 2-3 GB of RAM after one or two days of usage and then crashes. May crash is caused by 32-bit build. But memory leak is source cause of this problem.

**Comment by ColtonDRG** [comment]
I noticed the same issue on a x86_64 Linux build. It doesn't crash, because it's x86_64, but it does use an insane amount of memory. I am still looking into specific details about what is causing it, so I will submit a proper bug report whenever possible.

**Comment by Krzmbrzl** [comment]
This appears to be some sort of memory leak. Did anyone encounter this with the newer 1.3 version?
