### ISSUE TITLE
Duplicate username SQL error

### ISSUE THREAD

**Issue by usefulz** [mumble-voip/mumble#1500]
/usr/sbin/murmurd: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0xc7a4cf124879395ae2a984b7c8def5d68f80aae6, stripped
# sqlite3 -version

3.7.13 2012-06-11 02:05:22 f5b5a13f7394dc143aa136f1d4faba6839eaa6dc

```
2014-12-19 01:02:19.557 SQL Error [UPDATE `users` SET `name`=? WHERE `server_id` = ? AND `user_id`=?]: columns server_id, name are not unique Unable to fetch row
```

```
sqlite> .schema users
CREATE TABLE `users` (`server_id` INTEGER NOT NULL, `user_id` INTEGER NOT NULL, `name` TEXT NOT NULL, `pw` TEXT, `lastchannel` INTEGER, `texture` BLOB, `last_active` DATE);
CREATE UNIQUE INDEX `users_id` ON `users` (`server_id`, `user_id`);
CREATE UNIQUE INDEX `users_name` ON `users` (`server_id`,`name`);
```

A user fessed up, and said he tried to create 2 users with the same username.  This stopped the daemon, so I would like to prevent this from reoccurring in the future.

**Comment by Kissaki** [comment]
Did you fix the issue by removing one of the accounts manually?

Can you reproduce the issue (creating two accounts on the same server with the same name)?

**Comment by skobkin** [comment]
I think I saw this error once using MySQL. Server gone online unexpectedly and I found similar (not fully shure) error in the log.
