### ISSUE TITLE
Recording files not saving in Mumble

### ISSUE THREAD

**Issue by rudiger650** [mumble-voip/mumble#1501]
Recording files are not saving in Mumble 1.2.8 on my Desktop (Windows 7). It works fine on my Laptop (also Windows 7.)

Things I've tried:

-Changing the directory, file type, file name, drive-where-saved.
-Searching for the file in windows search.
-Checking the default folder.
-Restarting Mumble.
-Restarting computer.
-Re-installing Mumble
-Made sure Mumble was opened as administrator.
-Made sure Mumble was completely allowed by firewall.
-Deleting the user info in the registry.
-Installing and using the the 1.3.0~499 "Snapshot."
-Uploading log data (no errors found.)

**Comment by rudiger650** [comment]
Sorry for the delay, holidays and all that.

I finally downloaded 1.3.0~499, unfortunately the problem remains unchanged.

**Comment by Strit** [comment]
I actually have the same problem on my laptop, running Linux.
I'm using the AUR package mumble-git, installed/updated about a month ago now.
Mumble version: 1.3.0 (according to the "About" section).

**Comment by KatSick** [comment]
**No recorded files** for me on 1.4.0 snapshot 6 and 1.3.3 on macOS Big Sur 11.4 (Intel)

**Comment by Krzmbrzl** [comment]
@KatSick could you give me the output of the [Developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) when this happens, please?

**Comment by Kissaki** [comment]
Note that Mumble does not create files until there is audio that is to be saved.

But I assume you did hear or produce audio?

I just tested it on the 1.4 snapshot, and it works fine for me. Both downmix and multichannel produce files when I use push to talk.
