### ISSUE TITLE
Skype does not show up when overlay is activated

### ISSUE THREAD

**Issue by neuron303** [mumble-voip/mumble#1503]
When you try to start Skype and Mumble is running with overlay activated Skype seems to hang during startup.
Quick fix is to add it to the black-list.

I guess you hook opengl/directx calls so this is a rather invasive feature.
In my opinion a switch to white-list per default would be more appropriate even if it's more inconvenient.
I realize that these options are hidden in the advanced section for that reason and that it would need to be changed in that case.

**Comment by Kissaki** [comment]
For me, starting Skype 7.0.0.102 works fine.
Calling the echo test service, the Mumble overlay displays fine in the Skype window.
Mumble 1.3.0~488 Snapshot. Win7 x64.
Could you try using the Snapshot release?
Otherwise, it's probably something else!?

**Comment by neuron303** [comment]
I could not reproduce it with x64 because I got no option for using overlay there.
Still happens with x86 snapshot 488

**Comment by Kissaki** [comment]
Did you reboot your PC?
Does the order in which you start the applications matter? (Launching Skype first works?)

**Comment by neuron303** [comment]
if mumble is running (with default configuration) when i start skype a skype process is appearing but no window will show up.
if i try it a second time a second skype process is started and will also stay in the task list. likely due to the mutex check happening later.

if mumble is not running skype will start and the main window shows up .. if i try to start it a second time a second process starts up and immediatly shuts down.

if i blacklist skype.exe same behaviour is observed.

to me there is no doubt this is correlated.

i will verify if skype is a 64 bit process. should overlay of 32 bit mumble work with 64 bit processes?

**Comment by Kissaki** [comment]
> i will verify if skype is a 64 bit process. should overlay of 32 bit mumble work with 64 bit processes?
No.

Could you run [DebugView](http://technet.microsoft.com/en-us/sysinternals/bb896647.aspx) alongside, and post the log?
With Skype blacklisted, I do not get any log messages from the Mumble overlay.

And with a file named `debugoverlay` next to Skype.exe

For me, the logs are https://gist.github.com/Kissaki/f2530467e490aa68ea9f

**Comment by neuron303** [comment]
https://gist.github.com/neuron303/70d8eaa9bc3e40c69a9a
I cleared debugview everytime before starting skype, so the prologue of mumble starting up is missing

**Comment by Kissaki** [comment]
Hello. Given that this is a year old, is this still an issue?

The CloneCode failed line indicates that the trampoline hook did not succeed. As you have an unknown opcode, while I do not, we seem to have differing D3D9 versions that Skype uses. I am not sure what could cause this. Is your Skype up to date? And the official Full Desktop App?

After the trampoline hook creation failed we still inject and upon calling try to restore the original code. As far as I can see we do not actually output or check for a failure case here, and on initial decision branch for this alternative method warn that this needs to work or we jump recursively. We do however make the code area writeable for the initial code replacement. So that would mean initially we can do that, but once it is being called, we can no longer do that.

**Comment by neuron303** [comment]
I have not used mumble in a while, but i will see if this still is an issue. Thanks for digging it up ;)

**Comment by neuron303** [comment]
So I had Mumble version 1.3.0~702~g4c16f25 still installed and a next to current Skype installation and it seems to work now. Overlay is displayed during the Test call. I guess some update to Skype or D3D has fixed it. Some CloneCode still failed though:
https://gist.github.com/neuron303/b852b49ce109ede7019249a3de0f81e6
This is also present in the latest snapshot.
If you want to look into this I will happily assist you. Otherwise feel free to close this :)
Thanks for your support!

**Comment by Krzmbrzl** [comment]
Then I assume this bug to be fixed
