### ISSUE TITLE
TLS 1.2 for Mumble 1.3.x

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1508]
My initial approach failed horribly because I can't read:

https://github.com/mumble-voip/mumble/commit/75843b62a7c2514d272734c711b96ab665984b76
https://github.com/mumble-voip/mumble/commit/c5e427d6071b1b3bf5f22d86a41868c542563b24

We've suggested ways to accomplish our goal of TLS 1.0 + TLS 1.2 to the Qt folks at
http://lists.qt-project.org/pipermail/development/2014-December/019550.html

Hopefully we'll get something that works for us.

**Comment by hacst** [comment]
The ML thread seems to be stalled. Any news?

**Comment by mkrautz** [comment]
This is done.
