### ISSUE TITLE
Weird display on start with Windows x64 and Snapshot version

### ISSUE THREAD

**Issue by JoelTroch** [mumble-voip/mumble#1510]
When I start Mumble, it appears sometimes like this :

![mumble_bug](https://cloud.githubusercontent.com/assets/4483707/5578562/3e0dd994-902a-11e4-8fc4-436048e39ffe.jpg)

The workaround is to play with the "Maximize" button to kinda refresh the display and fix it.
I am running Windows 7 x64 Pro SP1 with Mumble 1.3.0~489~g6a07cbd (64 bits) and this issue started to appear since 2 or 3 Mumble's updates.

**Comment by mkrautz** [comment]
Easy to reproduce in Windows 8 as well.

1) Maximize Mumble.
2) Exit Mumble
3) Re-launch Mumble

**Comment by mkrautz** [comment]
I believe this is actually fixed in the newer Qt version we're using now.

Is that true @JoelTroch?

**Comment by mkrautz** [comment]
Closing, as my testing suggests that it is indeed fixed.

If this is wrong, please inform me. Thanks!

**Comment by JoelTroch** [comment]
Confirmed it is fixed on Windows 10 Pro x64 November Update with 1.3.0~883~g2a31708~snapshot

Are you sure this issue is fixed on Seven ? Because I reported this issue with it.

**Comment by mkrautz** [comment]
It was bad for me initially on 8. It is fixed now. I assume it is fixed in 7 as well.
