### ISSUE TITLE
Use of "Mumble team" as the collective copyright holder

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1513]
I don't like our use of "Mumble team" as the copyright holder.

It implies there is a "team". Which I suppose is true.
We've also used the term in things such as blog posts, or formal posts to
with security advisories for things such as oss-security.

But it also implies that everyone who hold the copyright to pieces of Mumble
are part of the team. Not that I am against that, but it does seem a bit confusing to me.

Instead, I think we should the term "Mumble Developers" instead.
That's also what Bitcoin does, for example:
https://github.com/bitcoin/bitcoin/blob/master/COPYING

We also already use the term "Mumble Developers" in the LICENSE
file of Mumble to refer to the collective copyright holders:
https://github.com/mumble-voip/mumble/blob/93ad74b467980a45537141e14d385cd8a75956b3/LICENSE#L24

I also think it's more formal, and I feel that it is more inclusive (from a FOSS perspective)
to use "Copyright (C) 2005-2015 Mumble Developers" instead of the current "Mumble team" term.

Thoughts?

**Comment by hacst** [comment]
Fine with me I guess ;) Not particularly attached to any of the terms.

**Comment by Streusel** [comment]
Additionally an Authors file would be neat.

**Comment by Kissaki** [comment]
I agree (to the OP)

**Comment by Geraner** [comment]
This will also effect the Mumble Transifex translation string 132.
Needs to be updated for each langueage. Right?

**Comment by mkrautz** [comment]
Strings updated at https://github.com/mumble-voip/mumble/commit/2857d71e8ef25adcd92d681ead2e7912ac45d7ce

**Comment by Kissaki** [comment]
Pretty cool: https://cla-assistant.io/

Allows you to integrate into Github. When someone opens a PR, he is asked to accept the CLA. When he does, the bot adds an info that he did.

This could allow us to reasonably make contributors read and accept a CLA / allow our team to handle the code as we see fit.

**Comment by hacst** [comment]
Imho that gives the incorrect (and given the license we are coming from not really very meaningful) impression that we might want to plan to make Mumble closed-source / dual-licensed in the future. Many OSS contributors don't like CLAs very much and it would be yet another bit of friction for a contribution. I think we should be able to do without. I don't really see us relicensing anytime soon and what we are doing now should be a one-time thing.

**Comment by mkrautz** [comment]
Fixed.
