### ISSUE TITLE
Add shortcuts to send predefined messages

### ISSUE THREAD

**Issue by neckcen** [mumble-voip/mumble#1515]
Would love to have the ability to set shortcuts to send a predefined message to a channel/user.

Use case: a bot which responds to chat commands, would be helpful to send them without going back to mumble interface.

**Comment by ubuntuaddicted** [comment]
this would be grand!

**Comment by mkrautz** [comment]
@bontibon has implemented this in #1578, which I've just landed as dede31785ffcf701c0b568790bd940b0f1d2562e.

I think we should aim to have a more advanced version of this in the future -- but at now we have *something*, at least.

**Comment by tixtixti** [comment]
Hello! I know this is old issue, but I am in need of this kind of feature. I have latest mumble Installed, but I can't find it anywhere. So is this feature live in 1.2.15 and how do I use it? Or is this to be coming ?

**Comment by bontibon** [comment]
@tixtixti This feature is only available in 1.3.0, which is not stable yet. Install the Development Snapshot version from [mumble.info](https://wiki.mumble.info/wiki/Main_Page).
