### ISSUE TITLE
Impossible to listen on port 443 on Linux

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1521]
Even if running as root, we'll set up our capabilities such that listening on a privileged port is impossible.

Reported by cts on IRC.

**Comment by ZeroAbility** [comment]
This seems confusing. Is the goal to make listening on 443 impossible (good idea) or that the Mumble server should use port 443 (potentially bad idea depending on the services used on the network)?

**Comment by Krzmbrzl** [comment]
This issue seems to be about being able to bind to those privileged ports, which apparently is currently not possible.

I don't see a need for having this possibility though, so let's close this.
