### ISSUE TITLE
Mumble 1.3.0~507 and Multimedia hotkeys

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1523]
Using a Logitech G510s I've noticed the multimedia keys at the top right of the keyboard do not function as intended when Mumble has focus.

I've tested this with foobar2000 and Windows Media Player. Same thing happens.

When Mumble does not have focus the keys work just fine.

**Comment by mkrautz** [comment]
Does it work when GlobalShortcutWin doesn't hook the keyboard/mouse funcs?

Could you try:

Regedit to HKEY_CURRENT_USER\Software\Mumble\Mumble.
Add a string value named "winhooks" and set value its to "false".

Re-launch Mumble.

**Comment by Tarun80** [comment]
Added the registry key and tried it. No change.

Copy of the reg export for that part:

	[HKEY_CURRENT_USER\Software\Mumble\Mumble]
	"crashemail"=""
	"lastupdate"=dword:00000002
	"winhooks"="false"

**Comment by Kissaki** [comment]
I can verify with my Microsoft keyboard.
Media key starts/stops media playback from various windows, but not from Mumbles window.

**Comment by mkrautz** [comment]
(I didn't attempt to verify earlier).

I can also reproduce.

**Comment by Tarun80** [comment]
Resolved in build 3d4663465ea1e528a299f1939237c31a4188775 (possibly earlier).
