### ISSUE TITLE
wrong rendering after restart in Win7

### ISSUE THREAD

**Issue by dafoxia** [mumble-voip/mumble#1534]
When Mumble closed in Fullscreen Mode, then opened again (next day or a minute lader), Rendering of UI goes wrong.
Occured 1.3.0~511~ge469bd6~snapshot.
![screen1](http://soa.chickenkiller.com/daten/dafoxia_Screen1.png)
When opened Menue
![screen3](http://soa.chickenkiller.com/daten/dafoxia_Screen2.png)

**Comment by mkrautz** [comment]
Thanks for the report. But it's a duplicate of #1510.  Closing.
