### ISSUE TITLE
Push-to-Talk button (Mouse 7) release doesn't stop sending voice when Chromium has focus

### ISSUE THREAD

**Issue by dennisschagt** [mumble-voip/mumble#1536]
I just started using Mumble on Ubuntu. I created a push-to-talk shortcut with the `Mouse 7`-button. This works fine with all the applications I tested, except for Chromium. When Chromium has the focus pressing the `Mouse 7`-button correctly enables sending my voice but releasing the button does not disable this. Other mouse buttons fail in the same way. The push-to-talk shortcut works fine when using keyboard keys.

I'm using Xubuntu (Ubuntu+Xfce) with `Chromium version 39.0.2171.65` and `Mumble 1.2.4.0.2ubuntu1.1`.

**Comment by Kissaki** [comment]
It’s only an issue when Chromium has focus?
With other apps in focus, it works as expected?

**Comment by dennisschagt** [comment]
Yes, Chromium seems to be the only program which gives this issue.
I've now tested with more then 10 programs, with all of them it works as expected.

**Comment by dennisschagt** [comment]
The last message on [Chromium issue 416249](http://code.google.com/p/chromium/issues/detail?id=416249) contains a solution, which is running `sudo chmod a+r /dev/input/event*`

At the moment I can't test with my regular mouse but it works with the buttons around my touch-pad.

**Comment by dennisschagt** [comment]
Related/duplicate of #1319, which contains some other programs that eat up the mouse-release events.
