### ISSUE TITLE
newServer issue when both icesecretread and icesecretwrite are enable (ice 3.4)

### ISSUE THREAD

**Issue by H4wKs** [mumble-voip/mumble#1538]
Hi,
When both icesecretread and icesecretwrite are unable in murmur, the use of newServer give an ice exception: ::Murmur::InvalidSecretException
However, the new server is created, but newServer return an exception instead of the created server ID.
This only affect the newServer function, anything else like stop, start, delete, update, ... is working.

If I comment icesecretread in murmur.ini, and only use the icesecretwrite, everything is working fine.

This have been tested on several different murmur build including the last one. Also tested with ice 3.4.2 and ice 3.5.1
Using the same, or different password for icesecretread and icesecretwrite do not change anything.

**Comment by Krzmbrzl** [comment]
What do you mean by `both icesecretread and icesecretwrite are unable in murmur`?

Have you tested whether the issue is still in Mumble 1.3 as well?
