### ISSUE TITLE
Replace OCB-AES128 encryption with free alternative

### ISSUE THREAD

**Issue by bontibon** [mumble-voip/mumble#1539]
Mumble currently uses the [OCB](http://web.cs.ucdavis.edu/~rogaway/ocb/) algorithm for the encryption of UDP. Unfortunately, this algorithm is patented in the United States and requires a [license](http://web.cs.ucdavis.edu/~rogaway/ocb/license.htm) when used in commercial software.

The licensing does not pose a problem to Mumble directly, but rather to those who implement the Mumble protocol. The restriction means Mumble-related software cannot (a) be compatible with the official Mumble server software and implement UDP audio, and (b) be sold inside the U.S. without purchasing an OCB license.

I propose that an algorithm that does not have these restrictions be used (or at least be supported by murmur) for UDP encryption. While I have not researched such an algorithm, this link contains the names of several alternatives: [Why is OCB-AES mode not becoming a standard for authenticated encryption?](https://crypto.stackexchange.com/questions/5639/why-is-ocb-aes-mode-not-becoming-a-standard-for-authenticated-encryption)

I can appreciate that this issue will probably only be solved by someone developing 3rd-party Mumble clients, but I thought I would bring it to attention anyway.

Any thoughts on this?

**Comment by mkrautz** [comment]
The OCB license was actually made quite a bit less strict a couple of years ago, so it is not as bad as you portray.

However, I agree with the sentiment.

Some time ago, I implemented XSalsa20-Poly1305 support in Grumble (the server, not your Grumble!)

See https://github.com/mumble-voip/grumble/tree/master/pkg/cryptstate

It also includes some negotiation logic for selecting the supported crypto modes.

I know @hacst is not fond of implementing an additional mode.  I've previously voiced my support of doing it, though.

**Comment by mkrautz** [comment]
Actually, I take my comment back.  I see that the #2 OCB license actually does not allow commercial use.

**Comment by bontibon** [comment]
> <strike>Actually, I take my comment back. I see that the #2 OCB license does not allow commercial use.</strike>

I'm glad I wasn't the only one who misread the license wording.

> Software implementations are free to use OCB in any way they wish (as long as they're not military).

That's probably permissive enough not to change the implementation.
