### ISSUE TITLE
Mumble Freezes with DAC (not ASIO Freeze)

### ISSUE THREAD

**Issue by Boxx1e** [mumble-voip/mumble#1546]
Assuming that the 32bit ASIO sdk from steinberg was causing freeze with my Sabre u2 Dac, I tried to switch over to the 64 bit snapshots without ASIO. It still freezes / lags the mouse and kb  with the DAC plugged in but not when I take the Dac out. Pulling my hair out trying to solve the issue and the last resort is to re-image my windows 8.1ent.

Output from Console.txt:

<W>2015-01-25 18:06:23.939 DirectSound: Disabled as WASAPI is available
<W>2015-01-25 18:06:23.940 CELT bitstream 8000000b from C:/Program Files/Mumble/celt0.0.7.0.dll
<W>2015-01-25 18:06:23.941 CELT bitstream 80000010 from C:/Program Files/Mumble/celt0.0.11.0.dll
<W>2015-01-25 18:06:23.941 Locale is "en_US" (System: "en_US")
<W>2015-01-25 18:06:24.006 Database SQLite: "3.8.6"
<W>2015-01-25 18:06:25.008 Overlay: Listening on "\.\pipe\MumbleOverlayPipe"
<W>2015-01-25 18:06:25.009 Updating application palette
<W>2015-01-25 18:06:25.045 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2015-01-25 18:06:25.090 AudioInput: 96000 bits/s, 48000 hz, 480 sample
<W>2015-01-25 18:06:25.091 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-01-25 18:06:25.093 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-01-25 18:06:25.093 WASAPIOutput: Driver says no to 2 channel output. Closest format: 8 channels @ 96000 kHz
<W>2015-01-25 18:06:25.097 WASAPIInput: Stream Latency 58050 (882)
<W>2015-01-25 18:06:25.097 AudioInput: Initialized mixer for 2 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2015-01-25 18:06:25.098 WASAPIOutput: Stream Latency 106666 (10560)
<W>2015-01-25 18:06:25.098 WASAPIOutput: Periods 10000us 3000us (latency 10666us)
<W>2015-01-25 18:06:25.098 WASAPIOutput: Buffer is 20521us (10)
<W>2015-01-25 18:06:25.098 AudioOutput: Initialized 8 channel 96000 hz mixer
<W>2015-01-25 18:06:25.112 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Mouse Mouse:8
<W>2015-01-25 18:06:25.112 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Keyboard Keyboard:109
<W>2015-01-25 18:06:25.121 Adding device {4669a280-8b75-11e4-8001-444553540000} USB Keyboard USB Keyboard:42
<W>2015-01-25 18:06:25.129 Adding device {4669c990-8b75-11e4-8002-444553540000} USB Keyboard USB Keyboard:3
<W>2015-01-25 18:06:25.134 Adding device {46736680-8b75-11e4-8008-444553540000} Microsoft eHome Infrared Transceiver Microsoft eHome Infrared Transceiver:573
<W>2015-01-25 18:06:25.136 Adding device {46738d90-8b75-11e4-800c-444553540000} Microsoft eHome Infrared Transceiver Microsoft eHome Infrared Transceiver:256
<W>2015-01-25 18:06:35.143 Adding device {7f0cdfc0-a3d1-11e4-8001-444553540000} HID-compliant consumer control device HID-compliant consumer control device:8
<W>2015-01-25 18:06:35.144 QObject::killTimer: Timers cannot be stopped from another thread
<W>2015-01-25 18:06:35.144 QObject::~QObject: Timers cannot be stopped from another thread

**Comment by metalmakkusu** [comment]
its happening to me with my Objective2 amp/dac.  Did you get it fix some how ?

**Comment by mkrautz** [comment]
Please see this thread:

https://github.com/mumble-voip/mumble/issues/1880

Is this the issue you are seeing?

**Comment by mkrautz** [comment]
In particular https://github.com/mumble-voip/mumble/issues/1880#issuecomment-156945302
