### ISSUE TITLE
Make two distinct audio notifications for microfone mute/unmute

### ISSUE THREAD

**Issue by Revertron** [mumble-voip/mumble#1547]
In TeamSpeak there are two distinct audio notifications: "Microphone muted" and "Microphone activated".
When user pushes key combination to mute/unmute he/she is certain what the mode of microphone is.

Please, make this change in Mumble, it will be much appreciated.

**Comment by bontibon** [comment]
Duplicate of #1179.

**Comment by bontibon** [comment]
This issue can be closed as a duplicate, @hacst.
