### ISSUE TITLE
Hotkey to whisper selected user

### ISSUE THREAD

**Issue by NullEntity** [mumble-voip/mumble#1548]
I believe whispering would be a lot more useful if you could highlight a user and hold a hotkey to whisper them. Selecting User 2 and repressing and holding the whisper hotkey would whisper to User 2. Maybe even being able to hold control to select multiple users and whisper a group. I like the idea of whispering, but I don't feel it's terribly useful right now.

**Comment by Benguin** [comment]
I'd also like this feature.

**Comment by dstensnes** [comment]
Can this be implemented? I believe you have to bind individual shortcuts to whisper to different persons, meaning the shortcut list can potentially grow to a very long list. Maybe an alternative could be to make it so a whisper shortcut without any targets set, will pick target from currently selected user, somewhat like "Use selected item as the chat bar target" (under "Settings" -> "UserInterface") functionality?

**Comment by dstensnes** [comment]
I mean, I had to look up how to use the whisper functionality, because I didn't know you had to set a target in the data-field of the shortcut. Without that I assume the whisper functionality is useless, so I think that would make for a better default/fallback at the very least

**Comment by Krzmbrzl** [comment]
> Can this be implemented?

Pretty sure it can be done. I am also relatively confident that this should be doable with not too much work that has to be done...

> I mean, I had to look up how to use the whisper functionality, because I didn't know you had to set a target in the data-field of the shortcut.

I didn't know that until now xD This indeed does seem pretty annoying and in my oponion it is only useful, if one wants to whisper to the same person over multiple sessions.

Thus I agree that a shortcut for whispering to selected user will be beneficial for the system.

As far as whispering to multiple users is concerned, I'm not sure about this. Haven't looked into how whispering is implemented and depending on the point of view this might even defeat the point of whispering. But as I said I haven't looked into this.

The one thing that immediately comes to my mind when talking about such a feature is: What should be done, if the user has a channel (or nothing) selected?
What does the current implementation if I have configured a shortcut to whisper to a specific person, but that person is not on the server when I press that shortcut? Whatever that does, I'd say the new shortcut should do the same or at least something close to it in abovementioned scenario...

**Comment by dstensnes** [comment]
I'd say, if a channel is selected, then shout to the channel. If a user is selected, whisper to that user. If nothing is selected then do nothing. I think that is acceptable behavior for the following reasons:
  * It is kind of like talking in a channel where you are currently the only member. You get no indication that no one is listening, and it is pretty intuitive when you think about it, leading somewhat into the next point:
  * There is no default shortcut for whispering of any kind, so people who want to use the functionality will have to define a shortcut to this suggested action (maybe "Whisper to selected target") and map a key to it them selves. Having a reasonable name for the shortcut action, implies that with no selected target, no one will hear you.

**Comment by dstensnes** [comment]
I thought I could make some notes about the current system too, just to ensure the good aspects of the current features are preserved. I can definitively see use cases for the current system, and it looks pretty solid as is, UI and all:
  1) Whisper a message to a dungeons and dragons game master without everyone else hearing the message (Usually the same person throughout a campaign?)
  2) For a moderator to whisper a message to streamer who is in a separate channel (can be controlled via ACL. Also usually the same person every time)
  3) Deliver a message to someone far away in a game that has positional audio enabled (using the "Ignore positional audio" modifier checkbox)
  4) For a moderator on a streamers server to deliver a message to all online moderators across the server (using a list of users defined in the shortcut)

Point 3 could probably use a separate shortcut for "Ignore positional audio" for talking to everyone in the channel without being affected by positional audio. It can be done using the current whisper shortcut but you will have to update the shortcut to point to the current channel, so a "Ignore positional audio" shortcut would be an easier solution in this regard. That should however be tracked in a separate issue, if that is a wanted feature.

**Comment by bendem** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahhhhhhhhhhhh!!!
This is awesome, thanks!

**Comment by Krzmbrzl** [comment]
You're welcome :)

Let me know if it misbehaves, but it should just work (at least from my tests) :innocent:

**Comment by dstensnes** [comment]
Nice! Thanks!

**Comment by Krzmbrzl** [comment]
"I will even disguise myself as a 13 year old, by giving you a heart emoticon!" he said and gave the heart emoticon to himself :joy:

**Comment by dstensnes** [comment]
Heh, well, I don't mind sharing it :)
