### ISSUE TITLE
"Recording Devices"-panel crashes when closing Mumble

### ISSUE THREAD

**Issue by dennisschagt** [mumble-voip/mumble#1554]
I just did a clean install of `mumble-1.3.0~511~ge469bd6~snapshot.winx64.msi`. After walking through the audio wizard I left the panel with recording devices open. When I closed Mumble, the panel crashed. This still crashes after I restarted Windows, Mumble, and the recording devices panel. Following is a recording of the crash:
![recordingdevices-crash](https://cloud.githubusercontent.com/assets/4629607/6070771/b5bae09a-ad8f-11e4-9c03-5cd2a3d56282.gif)

I'm working on Windows 7 64-bit. This is the first time that I installed Mumble on this machine. Let me know if you need anymore information or if you want me to try another snapshot or a stable release. Now I don't have time but I can probably try tomorrow.

**Comment by dennisschagt** [comment]
Some more information, I looked up the error in the Windows event viewer. In `Details->XML View` it shows:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" /> 
        <EventID Qualifiers="0">1000</EventID> 
        <Level>2</Level> 
        <Task>100</Task> 
        <Keywords>0x80000000000000</Keywords> 
        <TimeCreated SystemTime="2015-02-06T20:25:36.000000000Z" /> 
        <EventRecordID>55267</EventRecordID> 
        <Channel>Application</Channel> 
        <Computer>dennis-PC</Computer> 
        <Security /> 
    </System>
    <EventData>
        <Data>rundll32.exe_Shell32.dll</Data> 
        <Data>6.1.7600.16385</Data> 
        <Data>4a5bc9e0</Data> 
        <Data>mumble_ol.dll_unloaded</Data> 
        <Data>0.0.0.0</Data> 
        <Data>54b7efc8</Data> 
        <Data>c0000005</Data> 
        <Data>000007fed2e62e35</Data> 
        <Data>6e4</Data> 
        <Data>01d0424b0dbf250c</Data> 
        <Data>C:\Windows\system32\rundll32.exe</Data> 
        <Data>mumble_ol.dll</Data> 
        <Data>4e83fc5b-ae3e-11e4-a480-406186c3f879</Data> 
    </EventData>
</Event>
```
I just installed the stable release (32-bit version 1.2.8) which did not give the crash on closing.

I'm now going to install a new SSD and reinstall Windows, I can't guarantee that I will be able to recreate this specific system configuration afterwards.

**Comment by dennisschagt** [comment]
I just tried again on my clean Windows 7 64-bit install and `mumble-1.3.0~511~ge469bd6~snapshot.winx64.msi` still has the crashing `Recording Devices` on close.

**Comment by hacst** [comment]
Interesting. Does this happen with a 32bit snapshot too? 64bit is relatively new and maybe this is a regression we haven't noticed before.

**Comment by dennisschagt** [comment]
I uninstalled the 64-bit snapshot and installed the 32-bit snapshot `mumble-1.3.0~511~ge469bd6~snapshot.msi`. This time closing Mumble did not cause a crash.

**Comment by hacst** [comment]
@mkrautz might know what to look for in that case

**Comment by mkrautz** [comment]
The 32-bit overlay doesn't inject into 64-bit programs, so that's probably why we haven't seen the crash before.

**Comment by Kissaki** [comment]
Does not crash for me on current snapshot `1.3.0~1937~g289d0d4`.

**Comment by tatokis** [comment]
This no longer seems to be reproducible on `1.3.0~2569~gd196a4b~snapshot` under Win7 x64.

**Comment by dennisschagt** [comment]
Closing this issue as I don't have a Windows 7 system anymore and others are reporting that it is not reproducable. If someone else can reproduce this issue with the newest snapshot, they can reopen it.
