### ISSUE TITLE
Overlay for Elder Scrolls is WORKING!!!!!!!!!!! 8) 8) 8)

### ISSUE THREAD

**Issue by HeroOfEvbof** [mumble-voip/mumble#1563]
I have downloaded and fired up the 64 bit snapshot dated feb 8 (build 537)
I am running Elder Scrolls Online on a Win 7 64 bit in DX11 Mode.
THE OVERLAY WORKS!!!!!!

I'm not sure how to express my joy at this.  You need to know that you are now ahead of Project Kryptonite and their efforts to get an overlay for TS3 to work with Elder Scrolls in this mode.

**Comment by Tarun80** [comment]
Unfortunately the x64 build's overlay is not working yet for GW2.

**Comment by HeroOfEvbof** [comment]
OK - Prepare for the the totally bizarre.
The Overlay is gone for my Elder Scrolls Online.
I did not update Mumble, I did not update Elder Scrolls and I am pretty sure I did not update Windows.  I did turn the Overlay in Mumble off and while it was off I did power down.
I cannot seem to get the Overlay back.

**Comment by HeroOfEvbof** [comment]
All-righty-then.
I ran the 32-bit mumble build 537 and the overlay came up in elder scrolls ok.
i closed it and ran the 64-bit mumble build 537 - and there be the overlay!!!!

**Comment by mkrautz** [comment]
Is ESO a 32-bit game?  The current 64-bit Mumble client only has a 64-bit overlay (but will gladly service a 32-bit overlay if it has been injected by the 32-bit client).

We're working on merging the ability to have both a 32-bit and a 64-bit overlay active at the same time:

https://github.com/mumble-voip/mumble/pull/1540

**Comment by HeroOfEvbof** [comment]
Wow - Yes, TESO is currently a 32-bit client.  I am not sure why I thought it was 64-bit since it is clearly in my x86 folder.

**Comment by TurBoss** [comment]
Version 1.3.0-939 overlay crashes the game when launching

**Comment by Kissaki** [comment]
I’m not sure what this issue is about any more?
For ESO crash we have #1600. GW2 works for me. Appreciation is very welcome, but we don’t need an open issue ticket for that. If there’s still something open, please create an issue specific to that.
