### ISSUE TITLE
Issue with window size

### ISSUE THREAD

**Issue by markuznw** [mumble-voip/mumble#1565]
This is happening to me since few builds (don't remember which one started it since I tought it was a temporary error)
It fixes if I minimize/maximize the mumble window but still a very annoying issue since it does each time on open and on every computer I am using :(
They are all on win7 64bit

http://i.imgur.com/Zb52p5Z.png

**Comment by Kissaki** [comment]
When does it occur?
Do you start Mumble maximized?
Or are you maximizing it, and it occurs then?
Or do you keep it maximized, which works fine at first, and at some point it ends up like that?

**Comment by markuznw** [comment]
As long as use it maximized, every time you open the client it shows in that way, directly on the "choose a server" list.
Obviously every menu on right click is off position too, so need to minimize and maximize again to fix it.

**Comment by markuznw** [comment]
Attaching yet another screen that i just took, as said it happens 100% of the times :p
![image](https://cloud.githubusercontent.com/assets/779743/6423053/a2d3a158-bee0-11e4-9bf7-89a383160774.png)

**Comment by markuznw** [comment]
Any update on this? Cosmetic but really annoying for users that use maximized mumble window ç_ç

**Comment by JoelTroch** [comment]
Related to #1510 ?

**Comment by markuznw** [comment]
Fixed in 1.3.0.658 thanks!
