### ISSUE TITLE
Welcome message changes require server restart

### ISSUE THREAD

**Issue by encg** [mumble-voip/mumble#1568]
I was told that a new welcome message should be seen instantly by new clients. However, changes to my server's welcome message do not come into effect until I restart the server. I'm running Murmur on Ubuntu 14.04 via DigitalOcean.

**Comment by Natenom** [comment]
That depends on how you set the welcometext...

When using Ice it changes instantly, when using the murmur.ini or mumble-server.ini, you must restart the Mumble server.

**Comment by encg** [comment]
@Natenom Thanks for the clarification. I'll do some research on how to use Ice.
