### ISSUE TITLE
Mumble causes entire computer to stop functioning properly

### ISSUE THREAD

**Issue by exgladous** [mumble-voip/mumble#1569]
When mumble is opened, everything works fine for about a minute. Then depending on whether I am talking or not my channel will get stuck open or closed but nobody can hear me, I can still send text messages and hear everyone however. Then after about 10 seconds of that my messages will not get sent although I see them as being sent. Also all programs on my computer will stop functioning properly in some way and I cannot open anything new. All programs that use the internet will not be able to make connections either even though Windows says I have an internet connection. The only way for me to fix this is to force power down my computer because this renders my reboot button in the start menu useless.

**Comment by Kissaki** [comment]
I suspect a serious driver issue then.
Mumble itself can not possibly prevent other programs from launching like you describe.
