### ISSUE TITLE
Mumble Overlay stops appearing (snapshot 537)

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1571]
I first noticed this issue starting with snapshot 535 (for certain) and this issue happens with 537 as well. I've been trying to reproduce it but I have not had much success. When it happens next I will try to roll the snapshots back. Hopefully I can isolate it.

The only fix I have found is restarting the computer.

I will notice that the overlay does not appear in any games when before it did. No settings have been changed. I have tried closing the mumble_ol.exe process, restarting Mumble and then reloading the games. The reboot is the only thing that seems to successfully bring the overlay back.

I suspect that it may have started when the overlay was split to it's own executable. But I'm not sure. -- https://github.com/mumble-voip/mumble/commit/9f1e60507b06ab17e7dea22d4d5e83dc4bbc0e7b

**Comment by Toshar** [comment]
I am also having a similar problem with my snapshot 535. I have tried resetting mumble and my game to fix the overlay but still no luck. It looks like restarting my computer is the only way to fix it and even that is a flip of a coin.

**Comment by mkrautz** [comment]
There are currently a few known problems with the exe-driven overlay.

Next time it doesn't show in a game, try to close Mumble. Then, look for any running mumble_ol.exe / mumble_ol_x64.exe that is also running, and terminate it if there is. (On Windows 8, you need to go to 'Details' in the Task Manager to see the individual processes...).

Thanks.

**Comment by Tarun80** [comment]
I believe I have tried this already. If I recall correctly, the mumble_ol.exe will close properly when mumble.exe is closed.

I failed to mention, this is the 32 bit version.

**Comment by Tarun80** [comment]
Just had it happen again. Tried as suggested. When I closed Mumble it appears that there was no mumble_ol.exe and that it closed cleanly. Nothing was listed in Task Manager or Process Explorer.

**Comment by Kissaki** [comment]
To clarify:
You can start games fine and the overlay displays fine.
You then exit the games.
At some point, you start another game, but the overlay does not display.
Restarting Mumble does not help.
You restart your PC, and the overlay displays again.

Is this description correct?

**Comment by Tarun80** [comment]
That is correct.  Worth noting that I leave my computer on at all times and only restart to update drivers and Windows.

Not really sure what causes this. Next time it occurs I'll check the console.txt to see if there's something useful in there.

**Comment by Tarun80** [comment]
Had this problem occur again last night. I looked through the console log and noticed tons of repeated lines being spammed.

QBuffer::seek: Invalid pos: -897575107

Looking back through the log the first instance of this was this entry:
<W>2015-02-15 14:28:44.354 QBuffer::seek: Invalid pos: -897575107

**Comment by Toshar** [comment]
I had this problem again, exited both game and mumble, made sure they were not running in task manager, then started mumble and the game (Guild Wars 2 for reference) but the overlay still did not appear.

**Comment by Kissaki** [comment]
> QBuffer::seek: Invalid pos: -897575107

Well, that’s interesting.
Indicates we got some invalid data there. I could not check yet. A stacktrace or something would be helpful though, which QBuffer that is, and at which seek call this occurs.

@Tarun80 and at which point of launching and playing eve was that? On startup?

@Toshar can you check if you get the same error in the log?

**Comment by Tarun80** [comment]
@Kissaki This was from playing Guild Wars 2.

Here's a copy of my console.txt from February 14th, 2015 through to today (March 3rd). I've also cleared my console.txt to create a new one.

http://pastebin.com/kR02q2xz

**Comment by Toshar** [comment]
@Kissaki  The first occurrence of that on my system was February 17th 2015  and i have been getting the same error consistently

**Comment by Tarun80** [comment]
When this problem occurred again today, I rolled back to snapshot 532 and the overlay worked without a reboot being necessary. I'll keep this build and see if it happens, then go back to 511 if it does continue to occur.

**Comment by Tarun80** [comment]
Tried build 549, issue persists. Rolled back to 532, still no overlay (did not reboot yet).

Also noticed this when the overlay starts to hiccup:
<W>2015-03-16 14:53:19.312 Overlay: Dead client detected. PID 4780 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-03-16 20:52:09.334 Overlay: Dead client detected. PID 5988 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-03-16 21:12:20.691 Overlay: Dead client detected. PID 5988 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-03-16 21:33:41.698 Overlay: Dead client detected. PID 5988 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-03-16 22:59:02.631 Overlay: Dead client detected. PID 6620 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-03-16 22:59:26.317 Overlay: Dead client detected. PID 2692 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-03-17 00:23:21.765 Overlay: Dead client detected. PID 2692 "C:\Windows\SysWOW64\DllHost.exe"

Tried adding dllhost.exe to the blacklist, still no overlay showing.

Might have to try rolling snapshots back further.

**Comment by Tarun80** [comment]
Additional information:
This morning I rolled back to 511 and the overlay now appeared. Went back to 532 and the overlay is there now? Not sure what's going on but I believe that bug where the overlay locks up when you're alt-tabbed might have something to attribute to this.

**Comment by Tarun80** [comment]
Had this issue crop up again. Rolling back to snapshot 511 once more and the overlay did not appear. No idea what's causing this, but it definitely happens when alt-tabbed out of a game and the Mumble client locks up briefly.

**Comment by AzoHarper** [comment]
I am currently using 511 and the only way the overlay works, is buy first starting mumble when I turn on my pc. If I close mumble at any point after that, the overlay only shows up by restarting my computer.

**Comment by Tarun80** [comment]
Noticed earlier today that there were multiple instances of mumble_ol.exe, roughly three while Mumble was open. Killed them off (End Process) and when I relaunched Mumble and the game I was playing, there was no overlay.

I wonder what's going on with this.

**Comment by Tarun80** [comment]
Noticing something recurring here. Once again on x86 - 532 and had the overlay disappear... A common occurrence here. DllHost.exe also appears as a problem.

```
<W>2015-05-01 11:03:11.124 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 11:05:56.310 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 11:28:44.879 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 11:36:18.541 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 12:14:19.520 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 12:19:49.805 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 12:40:44.500 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 12:51:26.996 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 13:05:34.441 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 13:06:33.801 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 13:13:59.363 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 13:28:02.191 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 14:10:49.270 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 14:15:21.730 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 14:45:04.981 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 15:37:00.100 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 15:42:26.789 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 16:36:59.812 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 16:40:34.944 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 17:03:11.430 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 17:32:14.602 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 17:33:00.513 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 17:45:02.973 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:06:31.064 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:07:10.159 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 18:13:49.294 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:14:19.313 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 18:15:26.820 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:15:56.839 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 18:17:23.806 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 18:17:23.810 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:18:24.188 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:19:50.494 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 18:19:50.497 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:21:31.939 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:22:01.959 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 18:41:49.271 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 18:42:19.292 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 19:11:54.153 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 19:12:24.176 Overlay: Dead client detected. PID 8316 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 20:53:09.430 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:09:03.875 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:09:36.891 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 21:14:59.412 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:15:29.443 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 21:24:08.416 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:24:38.448 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 21:28:14.060 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:33:29.569 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:34:12.368 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 21:36:41.333 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:37:16.763 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 21:39:19.040 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:39:49.076 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 21:41:15.688 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:41:45.725 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 21:45:40.001 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 21:46:10.041 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 22:00:21.957 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:00:51.993 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 22:06:37.744 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:10:55.352 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:11:25.401 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 22:16:02.344 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:16:32.393 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 22:23:02.950 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:24:01.515 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:26:26.351 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:26:56.368 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 22:29:44.273 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:30:47.855 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:32:29.852 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:32:39.473 Overlay: Dead client detected. PID 11512 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<W>2015-05-01 22:34:02.783 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:36:31.295 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:37:36.696 Overlay: Dead client detected. PID 11024 "C:\Windows\SysWOW64\DllHost.exe"
<W>2015-05-01 22:38:08.274 ServerHandler: Failed to remove UDP from QoS
<W>2015-05-01 22:38:08.286 QObject::killTimer: Timers cannot be stopped from another thread
<W>2015-05-01 22:38:08.286 QObject::~QObject: Timers cannot be stopped from another thread
<W>2015-05-01 22:38:08.368 QProcess: Destroyed while process ("C:\Program Files (x86)\Mumble\mumble_ol.exe") is still running.
```

**Comment by davidebeatrici** [comment]
Is the issue still present with the latest snapshot?
