### ISSUE TITLE
Donate Button broken

### ISSUE THREAD

**Issue by EvilScientist** [mumble-voip/mumble#1583]
Paypal link on on http://wiki.mumble.info/wiki/Donate not working for donation is broken. Clicking the button leads to http://sourceforge.net/donate/index.php?group_id=147372|Donate wich displays a 404 message.

Please update your donation link, so we can support your project.

Best regards

**Comment by Saladien** [comment]
same here, im going to us my 50 usd else-were now ;)

**Comment by hacst** [comment]
Hi. Seems like SF changed their linking scheme. Should be fixed now. Thanks for the information.

**Comment by EvilScientist** [comment]
Wow that was fast! Thanks, also file transfer please :)

**Comment by Saladien** [comment]
faster than light :) *push for file transfer

**Comment by hacst** [comment]
Was just checking my mail when this popped up and editing a wiki link isn't exactly rocket surgery ;)

#1307 is a request for file transfers. That would - depending on how cleanly you want to integrate it - a lot of work which the way our protocol currently is setup. Sure you can always bolt on something extra very quickly (e.g. out of band transfers negotiated via the control channel) but doing that in the core would be asking for trouble in all kind of ways. I'd much rather see us push for an extension system so ppl. can do stuff like that themselves. But that discussion belongs in the other issue(s?) ;)

I'll close this one.
