### ISSUE TITLE
OS X 10.10: overlay doesn't work

### ISSUE THREAD

**Issue by backerman** [mumble-voip/mumble#1584]
I'm using the current OS X snapshot edd5509 (64-bit), and the overlay does not work.

Behavior observed:
- Using the blacklist, the overlay doesn't appear at all that I've seen.
- Using the whitelist, it can appear... weird. 

How it should look: (in the upper-right corner of the screen)
![screenshot 2015-02-26 19 18 09](https://cloud.githubusercontent.com/assets/115895/6404995/42fda94e-bdec-11e4-9413-14c4b1f7f42a.png)

How it does look: (tiny, in the middle of the screen)
![screenshot 2015-02-26 19 19 03](https://cloud.githubusercontent.com/assets/115895/6405002/5eac02bc-bdec-11e4-8c40-87ed0aa02d4c.png)

I'm on OS X 10.10.2 and reinstalled the overlay (ver 19).

Possible clue—this message appears in my logs:

```
Mumble[56331]: AppleEvents: Send port for process has no send right, po
rt=( port:70423/0x11317 rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
```

**Comment by mkrautz** [comment]
It shows in Safari for you?

It's only supposed to show in games.

**Comment by backerman** [comment]
The overlay shows up in Firefox when in whitelist mode.

I haven't been able to get it to show up in games (tried EVE Online, Portal 2) in either blacklist or whitelist mode.

**Comment by mkrautz** [comment]
OK.

What kind of hardware are you running? What kind of GPU?

**Comment by backerman** [comment]
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	16 GB
  Boot ROM Version:	MBP111.0138.B14
  SMC Version (system):	2.16f68

Intel Iris:

  Chipset Model:	Intel Iris
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0a2e
  Revision ID:	0x0009
  Displays:
Color LCD:
  Display Type:	Retina LCD
  Resolution:	2560 x 1600 Retina
  Retina:	Yes
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Built-In:	Yes

**Comment by Krzmbrzl** [comment]
I assume this behavior is still encountered in Mumble 1.3?
