### ISSUE TITLE
Strange latency and network spike issues in other applications (snapshot/OS X 10.10)

### ISSUE THREAD

**Issue by NitroPye** [mumble-voip/mumble#1585]
When using the latest snapshot games that depend highly on network latency being low start spiking left and right. This does not happen with 1.2.8. I'm having a tough time figuring out where the issue is coming from but it certainly is Mumble client related.

For example, if I am playing Heroes of the Storm with the network debug txt turned on and I launch the mumble snapshot it starts reading anywhere from 15-30 network spikes a minute. I've tried turning mumble's QOS on and off, forcing TCP mode, etc to no avail. As soon as I quit the mumble snapshot client no more network spikes.

I do not experience this behavior with 1.2.8 running.

I'm not great with networking so let me know what debugging information on my end would be helpful.

Edit: mumble-overlay turned off for all this testing. That doesn't appear to be causing the issue.

**Comment by NitroPye** [comment]
I'm not sure how scientific this is but I ran a few tests. 

 * Connecting to a mumble server, no users, no one transmitting. Computer idling.
 * Run three tests, no mumble client, 1.2.8 and snapshot
 * Ping 50 times to my gateway.

First test: No mumble client running at all
```
50 packets transmitted, 49 packets received, 2.0% packet loss
round-trip min/avg/max/stddev = 0.567/2.507/4.705/1.391 ms
```

Second test: Mumble 1.2.8 client running
```
50 packets transmitted, 49 packets received, 2.0% packet loss
round-trip min/avg/max/stddev = 0.539/1.833/4.934/1.436 ms
```

Third test: Mumble 1.3 snapshot running
```
50 packets transmitted, 50 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.567/12.066/112.900/26.683 ms
```

Not the average, max and stddev are quite different. 

This is the full output for the third test
```
PING 10.0.1.1 (10.0.1.1): 56 data bytes
64 bytes from 10.0.1.1: icmp_seq=0 ttl=255 time=0.820 ms
64 bytes from 10.0.1.1: icmp_seq=1 ttl=255 time=0.690 ms
64 bytes from 10.0.1.1: icmp_seq=2 ttl=255 time=0.625 ms
64 bytes from 10.0.1.1: icmp_seq=3 ttl=255 time=13.366 ms
64 bytes from 10.0.1.1: icmp_seq=4 ttl=255 time=21.205 ms
64 bytes from 10.0.1.1: icmp_seq=5 ttl=255 time=111.370 ms
64 bytes from 10.0.1.1: icmp_seq=6 ttl=255 time=0.684 ms
64 bytes from 10.0.1.1: icmp_seq=7 ttl=255 time=3.157 ms
64 bytes from 10.0.1.1: icmp_seq=8 ttl=255 time=3.176 ms
64 bytes from 10.0.1.1: icmp_seq=9 ttl=255 time=4.701 ms
64 bytes from 10.0.1.1: icmp_seq=10 ttl=255 time=0.705 ms
64 bytes from 10.0.1.1: icmp_seq=11 ttl=255 time=4.214 ms
64 bytes from 10.0.1.1: icmp_seq=12 ttl=255 time=3.504 ms
64 bytes from 10.0.1.1: icmp_seq=13 ttl=255 time=4.029 ms
64 bytes from 10.0.1.1: icmp_seq=14 ttl=255 time=0.629 ms
64 bytes from 10.0.1.1: icmp_seq=15 ttl=255 time=0.908 ms
64 bytes from 10.0.1.1: icmp_seq=16 ttl=255 time=0.688 ms
64 bytes from 10.0.1.1: icmp_seq=17 ttl=255 time=0.775 ms
64 bytes from 10.0.1.1: icmp_seq=18 ttl=255 time=55.116 ms
64 bytes from 10.0.1.1: icmp_seq=19 ttl=255 time=0.726 ms
64 bytes from 10.0.1.1: icmp_seq=20 ttl=255 time=0.645 ms
64 bytes from 10.0.1.1: icmp_seq=21 ttl=255 time=3.410 ms
64 bytes from 10.0.1.1: icmp_seq=22 ttl=255 time=0.760 ms
64 bytes from 10.0.1.1: icmp_seq=23 ttl=255 time=0.714 ms
64 bytes from 10.0.1.1: icmp_seq=24 ttl=255 time=0.732 ms
64 bytes from 10.0.1.1: icmp_seq=25 ttl=255 time=0.657 ms
64 bytes from 10.0.1.1: icmp_seq=26 ttl=255 time=3.422 ms
64 bytes from 10.0.1.1: icmp_seq=27 ttl=255 time=0.669 ms
64 bytes from 10.0.1.1: icmp_seq=28 ttl=255 time=3.478 ms
64 bytes from 10.0.1.1: icmp_seq=29 ttl=255 time=112.900 ms
64 bytes from 10.0.1.1: icmp_seq=30 ttl=255 time=82.761 ms
64 bytes from 10.0.1.1: icmp_seq=31 ttl=255 time=9.882 ms
64 bytes from 10.0.1.1: icmp_seq=32 ttl=255 time=0.567 ms
64 bytes from 10.0.1.1: icmp_seq=33 ttl=255 time=3.533 ms
64 bytes from 10.0.1.1: icmp_seq=34 ttl=255 time=3.270 ms
64 bytes from 10.0.1.1: icmp_seq=35 ttl=255 time=0.689 ms
64 bytes from 10.0.1.1: icmp_seq=36 ttl=255 time=3.158 ms
64 bytes from 10.0.1.1: icmp_seq=37 ttl=255 time=3.689 ms
64 bytes from 10.0.1.1: icmp_seq=38 ttl=255 time=3.429 ms
64 bytes from 10.0.1.1: icmp_seq=39 ttl=255 time=3.209 ms
64 bytes from 10.0.1.1: icmp_seq=40 ttl=255 time=1.015 ms
64 bytes from 10.0.1.1: icmp_seq=41 ttl=255 time=0.573 ms
64 bytes from 10.0.1.1: icmp_seq=42 ttl=255 time=72.277 ms
64 bytes from 10.0.1.1: icmp_seq=43 ttl=255 time=40.367 ms
64 bytes from 10.0.1.1: icmp_seq=44 ttl=255 time=0.728 ms
64 bytes from 10.0.1.1: icmp_seq=45 ttl=255 time=0.624 ms
64 bytes from 10.0.1.1: icmp_seq=46 ttl=255 time=4.014 ms
64 bytes from 10.0.1.1: icmp_seq=47 ttl=255 time=3.316 ms
64 bytes from 10.0.1.1: icmp_seq=48 ttl=255 time=3.243 ms
64 bytes from 10.0.1.1: icmp_seq=49 ttl=255 time=4.463 ms

--- 10.0.1.1 ping statistics ---
50 packets transmitted, 50 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.567/12.066/112.900/26.683 ms
```

Note it spikes every couple of seconds. This only happens with 1.3 snapshot running.

**Comment by mkrautz** [comment]
Just thinking aloud here...

One obvious contender would be SSL changes in Qt 5...

**Comment by NitroPye** [comment]
Probably a good guess. It appears to be happening to other folks using QNetworkAccessManager.

http://stackoverflow.com/questions/24644732/qnetworkaccessmanager-causes-network-traffic-spike-every-5-seconds-in-wireless-n
http://qt-project.org/forums/viewthread/44771

Going back to last year.

**Comment by mkrautz** [comment]
Interesting... You're on WiFi, like people in the issue are, I take it?

**Comment by NitroPye** [comment]
Yep. Have another friend experiencing the same issue on wifi. It also appears to not be limited to OS X.

I'm attempting to build the Qt and the entire mumble-env with the flag mentioned in the link but its taking me a little time to get up to speed on the whole thing.

```
-D QT_NO_BEARERMANAGEMENT
```

**Comment by NitroPye** [comment]
Okay I'm unable to build the env (Qt fails miserably with or without any options)

From the looks of it adding this to qt5.build should fix it but I cannot confirm.

```
-no-feature-bearermanagement
```

Want a PR for this?

**Comment by NitroPye** [comment]
PR submitted to mumble-releng: 

https://github.com/mumble-voip/mumble-releng/pull/8

**Comment by NitroPye** [comment]
Any thoughts on merging that PR? Builds and appears to fix things on my end. It could also be applied to the Win & Linux builds.

**Comment by mkrautz** [comment]
Yes, I plan to merge it. Haven't had the time to sit down and play with it and test it...

**Comment by NitroPye** [comment]
Merge on the releng project seems to have fixed it. Tried the snapshot build on a fresh computer over wifi and am not seeing any latency spikes.
