### ISSUE TITLE
Mumble creates corrupt flac files

### ISSUE THREAD

**Issue by flyser** [mumble-voip/mumble#1587]
I noticed that the multi-track recording feature of mumble version bf1667fa9845dfb68ae24fef1534bc2c74894867 creates flac files that are decoded differently by different applications, which lets me think that these are not valid flac files.

See the following screenshot, which shows the problem: http://i59.tinypic.com/wrgd1w.png
The first track is the unchanged mumble recording opened in audacity.
The second track is the same flac file transcoded to wav by the flac commandline utility and then opened in audacity.
The third track is a recording of the raw microphone input.
You can find the flac file here: http://flyser.medienzuflucht.de/mumble/short.flac
Note that I had to cut the file on the byte level, so the end of the file is corrupted.

This is a issue I originally mentioned in https://github.com/mumble-voip/mumble/issues/971#issuecomment-76063237 but I think it deserves a different bug report as it seems to be independent from the inverted clipping issue. Correct me if I am wrong.

**Comment by hacst** [comment]
Wouldn't be surprised if the Xiph guys have a FLAC validator out there we might be able to use to see if the file actually is invalid.

We use libsndfile for encoding and writing the flac file. Will have to check whether we violate some API contract or sth. .

**Comment by Kissaki** [comment]
The command line tool [provides the `--test` parameter](https://xiph.org/flac/documentation_tools_flac.html#general_options) to decode the file and possibly print warnings or errors.
There is also `--analyze` which writes an analysis file.

For the file provided:

```
>flac --test short.flac
[…]
short.flac: testing, 0% complete
short.flac: ERROR while decoding data
            state = FLAC__STREAM_DECODER_END_OF_STREAM
```

What do you mean you had to cut the file, corrupting it?
How is it still a valid sample file then?

I did a short multi-channel flag recording of myself, which resulted in a `OK` result with `--test`.

**Comment by flyser** [comment]
I had to truncate the file, because it was a two hour recording. the few seconds I provided are sufficent to visualize the problem in audacity.
Running flac --test on the whole file returns "ok".

**Comment by Krzmbrzl** [comment]
1. Is this still the case in 1.3?
2. If the test on the created file turns out to be okay, why would you be so sure, that it isn't the fault of one of the applications you are using? :thinking:
