### ISSUE TITLE
WASAPIOutput does not correctly check for IEEE floating point support

### ISSUE THREAD

**Issue by gibbed** [mumble-voip/mumble#1589]
https://github.com/mumble-voip/mumble/blob/master/src/mumble/WASAPI.cpp#L872

This code is currently assuming that ::GetMixFormat always returns a pointer to a WAVEFORMATEXTENSIBLE, when it can return a pointer to a regular WAVEFORMATEX.

It needs to check wFormatTag is WAVE_FORMAT_IEEE_FLOAT or wFormatTag is WAVE_FORMAT_EXTENSIBLE and SubFormat is KSDATAFORMAT_SUBTYPE_IEEE_FLOAT as well as further changes to any code that makes use of the extended fields.

This problem was uncovered after some discussion on IRC between myself (Rick) and @hacst shortly before I submitted this issue.

Related documentation:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd370872(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/dd390970(v=vs.85).aspx

Possibly related to this issue: #1573

**Comment by hacst** [comment]
Note: There are some other locations in WASAPI.cpp that also rely on this invalid assumption that have to be checked and fixed.
