### ISSUE TITLE
Remove border from multi-line TextChat-messages

### ISSUE THREAD

**Issue by devonzara** [mumble-voip/mumble#1590]
Is there a way to override the border that is currently [ [hard-coded](https://github.com/mumble-voip/mumble/blob/master/src/mumble/Log.cpp#L485) ] on messages containing line-breaks?

I'm not very familiar with Qt and was unable to figure out how to descend the node tree using CSS. If there isn't a way, I think it should be addressed seeing as users can user <kbd>Shift + Enter</kbd> to enter their own line breaks and essentially spam/outline their messages.

I suppose this is a 2-part question/suggestion.
- Add a way to remove the border in skins. (Assuming I'm not over-looking something)
- Address the issue where users can spam/take advantage of this automatic parsing.

**Comment by Krzmbrzl** [comment]
Please create separate issues for separate concerns. Also the provided link is no longer correct (I assume). In the future, please only use permalinks (available via GitHub, when selecting a line).

I'll take the liberty of modifying your issue to deal with the border around multi-line messages...

**Comment by Krzmbrzl** [comment]
Here's an example showing the problem in 1.3:
![Mumble_BorderAroundMessagesWithLineBreak](https://user-images.githubusercontent.com/12751591/72922330-2aea5d80-3d4d-11ea-9382-237d24bffa6e.png)

Note that the border is only drawn, if the message contains an explicit linebreak

**Comment by Krzmbrzl** [comment]
@davidebeatrici are you handling this in your PR for the tabbed logging area?

**Comment by devonzara** [comment]
Sorry, I've not used Mumble in nearly 4 years... looking through the file history I was able to obtain a link to the [ [line of code](https://github.com/mumble-voip/mumble/blob/491789c202934a52b5a3b2064615126018d12ac3/src/mumble/Log.cpp#L485) ] in question.

**Comment by Krzmbrzl** [comment]
If you copy a permalink and simply add it to your message here, it'll give a nice preview of that line ;)
https://github.com/mumble-voip/mumble/blob/491789c202934a52b5a3b2064615126018d12ac3/src/mumble/Log.cpp#L485
See https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet for details.

Anyways: Thanks for providing the new link :+1:

**Comment by Krzmbrzl** [comment]
From the code-block, I'd deduce that either qt always uses `\r\n` for line breaks, or this whole border-thing exclusively happens on Windows, as it is hard-coded to look for CRLF only:
https://github.com/mumble-voip/mumble/blob/491789c202934a52b5a3b2064615126018d12ac3/src/mumble/Log.cpp#L483-L490

Will have to investigate that...

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you know the/a reason for drawing this border around multi-line messages? I don't really see an advantage in doing so, but before removing this, I'd like to know that this doesn't fulfill some "hidden" purpose :)
