### ISSUE TITLE
Sound for self-deafening is useless

### ISSUE THREAD

**Issue by Sildra** [mumble-voip/mumble#1593]
`(un)mute yourself` represents the button that looks like a mic in the Windows GUI.
`(un)deafen yourself` represents the button that looks like an headset in the Windows GUI.

In Configure -> Settings -> Advanced ticked -> Messages
The sound (soundfile box ticked) labeled `You self-muted/deafened` is played when :
- `mute yourself`
- `unmute yourself`
- `undeafen yourself` (both previously muted or unmuted)
  But is not played when :
- deafen yourself (both previously muted or unmuted, but cause mute)

There is a non consistency between the fact that the sound is played when `mute yourself`and not played when `deafen yourself`.

Version is Windows 1.2.8, OS is Windows 7

**Comment by Krzmbrzl** [comment]
If I understood this correctly, the weird part is that you can configure a sound for self-deafening but it won't be played, right?

**Comment by Hartmnt** [comment]
This seems to have been fixed in the last 9 years. I am able to hear my configured self-deafen sound.
