### ISSUE TITLE
No Client RPC support for Push-to-Talk?

### ISSUE THREAD

**Issue by Dessix** [mumble-voip/mumble#1594]
Coming from TeamSpeak, I've used several addons that let games or the operating system handle push-to-talk, from media keys to G15 bindings with no intermediate key combination to disrupt interaction with the running games or applications.
The closest method I can find for being able to do this with Mumble seems to be calling the executable with `mumble rpc mute/unmute`, but this spams people in the channel with messages about my microphone state too much to be viable for a push-to-talk replacement. Are there any plans to implement a pluggable input system or improved clientside remoting capabilities?

**Comment by Dessix** [comment]
If anyone wants, I've written a C#-based daemon that can inject PTT RPCs into a running Mumble client, but sooner or later it will break as that area of the code is changed- I'd like to see an official solution.

**Comment by mkrautz** [comment]
There should be a ptt RPC option in the client itself...  Not sure of the design, though. Maybe something like

    ptt [<action>] (by default, ptt toggles the current ptt state)
      ptt on
      ptt off
      ptt toggle

**Comment by Dessix** [comment]
That'd be a nice addition to the program.

**Comment by Dessix** [comment]
Four years later, I'm still trying to solve this problem. Any ideas, @mkrautz?

**Comment by Krzmbrzl** [comment]
You'll be able to write a plugin for this as soon as #3743 gets finished and merged :)
