### ISSUE TITLE
Suppressed keys sometimes get stuck pressed down

### ISSUE THREAD

**Issue by Gunni** [mumble-voip/mumble#1597]
I have the right control button on my keyboard set as one of my push to talk keys. Mumble is set to "suppress" it.

![right control suppress](http://i.imgur.com/E0o2LOF.png)

Randomly though, it seems like the keyDown event actually gets through, but _not_ the keyUp event, meaning, any action in any program I am using that uses control to modify it, happens as if control is pressed.

In browsers, pages zoom out or in if I scroll with the mouse, r reloads the page, t opens a new tab.

As you can probably guess, this is really annoying.

My suggestion is: only suppress keyUp events if the matching keyDown event was successfully suppressed previously.

Hardware/software:
- OS: Windows 7 Pro x64
- Keyboard: Logitech UltraX Premium Keyboard

**Comment by Gunni** [comment]
Abandoning ticket.

**Comment by davidebeatrici** [comment]
Is this problem still present?

**Comment by Gunni** [comment]
@davidebeatrici i don't know, i stopped using mumble over a year ago.
