### ISSUE TITLE
Mumble crashes Elder Scrolls Online

### ISSUE THREAD

**Issue by CarterDC** [mumble-voip/mumble#1600]
The 32 bit snapshot is still to date the only way to get the overlay on ESO.
However i got reports from players that the latest snapshot 1.30-547 causes crashes with ESO.

It is to be noted that any version of mumble still crashes the game (every time) when mumble is running without being connected to a server.

**Comment by Kissaki** [comment]
You received reports? Does it not crash for you?

Disabling the overlay makes it not crash? No matter if you're connected or not?

**Comment by Kissaki** [comment]
Closing this as no further input or confirmations from others.

As I don’t own the game I can’t test it either.
