### ISSUE TITLE
Overlay doesn't work when Plantronics Gamecom is being used

### ISSUE THREAD

**Issue by jammasterj** [mumble-voip/mumble#1606]
I use Windows 8.1 64bit and play Eve Online with Mumble.  One problem has always been getting the overlay to work in Eve -- I haven't tried it with other games.   I've added the -nod3d9ex switch to Mumble and ran Eve in DX9 mode, and white listed Eve.

Today I noticed that when I ran Mumble with Eve, while using my PC speakers, the overlay worked fine.  I connected my Plantronics Gamecom 780, and the overlay stopped working.  This happened regardless of what version of Mumble I was using -- the latest 1.3.0 snapshot or 1.2.8.   When I disconnected my headset, the overlay started working again.

So it appears that something with the Gamecom interferes with the overlay.  The only thing I can think of, is that the Gamecom does show an on-screen popup indicator when the volume is changed on the headset.

**Comment by Venopsis** [comment]
Hello,

I have also a 780 but I never had this problem with all versions. I don't like overlay it's why I like dual screen :D

**Comment by Kissaki** [comment]
The [product page for the Plantronics Gamecom 780](http://www.plantronics.com/us/product/gamecom-780) seems to be dead.

Unfortunately, if Plantronics indeed injects itself as well, but in a manner that breaks our injection, we probably can’t do much. We would first have to check what breaks though.

Do other Overlays work? Steam, Discord, Twitch App, whatever else you can try.

When you place a file named `debugoverlay` (no file extension) next to the exe, and run [DebugView](http://technet.microsoft.com/en-us/sysinternals/bb896647.aspx) ([description](https://wiki.mumble.info/wiki/Debugging#Getting_a_Console_Log)). The log could be interesting.
