### ISSUE TITLE
Crash due to invalid instruction vmovd in sin function on some non AVX2 systems

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble#1615]
"2015-03-23T01:41 1.3.0 1.3.0~567~g3223c8a~snapshot Unknown.html" reports a crash on startup due to an illegal instruction. Dump shows it crashing on a vmovd AVX instruction in the sin function called by celt.

While the user has a [i7-4790 CPU](http://ark.intel.com/products/80807/Intel-Core-i7-4790K-Processor-8M-Cache-up-to-4_40-GHz) with AVX support he is running Windows 7 Professional 64-bit (6.1, Build 7600) (7600.win7_rtm.090713-1255) which [doesn't support AVX which was only added in SP1](https://msdn.microsoft.com/en-us/library/windows/desktop/ff919571%28v=vs.85%29.aspx).

Apparently this is a bug with the VS2013 runtime (msvcrt12.dll) reported as [Visual Studio 2013 RTM: C++ x64 code generation bug for AVX2 instructions](https://connect.microsoft.com/VisualStudio/feedback/details/811093/visual-studio-2013-rtm-c-x64-code-generation-bug-for-avx2-instructions).

It is supposedly fixed in VS14 so I guess we'll fix this by switching as soon as it is released. This issue should be kept open until then so we can refer to it.

**Comment by mkrautz** [comment]
Should be in Known Issues for 1.3.0.

**Comment by mkrautz** [comment]
@hacst Where during startup?

Perhaps we should simply add the workaround stated in the MS bug report:

    _set_FMA3_enable(0)

preprocessor if'd to only MSVC2013.

**Comment by hacst** [comment]
Don't remember exactly. Likely the first time it starts to process audio ;) Check the dump I linked for the exact spot.

I'm not sure this issue is worth switching off FMA for everyone. It's kinda of a big part of SIMD. We should restrict it to affected systems if we decide to invest the time to work-around this.

Imho the easiest would be the simply upgrade to the new Visual Studio 2015. It would also resolve #1615 for good. Our current workaround is kinda brittle if you ask me. The current 2015 RC comes with a go-live license so if we are eager we can switch right now without feeling too bad. Otherwise the release likely won't be too far off.

**Comment by mkrautz** [comment]
I really don't think we should switch compilers at this point.

**Comment by mkrautz** [comment]
I'm also not suggesting turning it off for everybody. Only for < Win 8 or whatever the cutoff is.

**Comment by hacst** [comment]
Apart from plugins I expect less breakage from such a compiler change than a Qt update to be honest ;)

**Comment by mkrautz** [comment]
Also, we might need the updated SDK for good Windows 10 compatibility. So maybe it's just better to bite the bullet and do it now...

**Comment by mkrautz** [comment]
It seems to me the safest way to work around this for MSVC 2013 is to conditionally call `_set_FMA3_enable(0);` for Windows < 8.

There seems to distinct issues here:

If your CPU indicates AVX2, and you run an OS without AVX2 support, it will crash.

If your CPU does not support AVX2, and you run an os with AVX2 support (well, Windows 7 SP1), it will crash.

So I suggest we add the following in os_win.cpp:

    #if _MSC_VER == 1800 && defined(_M_X64)
        // Disable MSVC 2013's FMA-optimized math routines on Windows
        // versions earlier than Windows 8 (6.2).
        // There are various issues on OSes that do not support the newer
        // instructions.
        // See issue mumble-voip/mumble#1615.
        {
	    OSVERSIONINFOEXW ovi;
            memset(&ovi, 0, sizeof(ovi));

	    ovi.dwOSVersionInfoSize=sizeof(ovi);
	    if (GetVersionEx(reinterpret_cast<OSVERSIONINFOW *>(&ovi))) {
                if (ovi.dwMajorVersion < 5 || (ovi.dwMajorVersion == 6 && ovi.dwMinorVersion <= 1)) {
                    _set_FMA3_enable(0);
                }
	    }
        }
    #endif

**Comment by hacst** [comment]
LGTM. I guess that means we won't be upgrading to 2015 before the next release? ;)

**Comment by mkrautz** [comment]
No, I am not ruling it out. It depends on whether we want to make use of the new Windows 10 SDK features, mainly D3D12.

I am not even sure if the NDA has been lifted on D3D12 yet.

Landing this doesn't change anything in that regard, it just makes our current builds on VS2013 more stable for some.

**Comment by mirh** [comment]
So.. I hope nobody get offended by necroposting, but switching to vs2015 doesn't oblige you in anyway to use W10 sdk. PCSX2 still relies on dx sdk, for example. 

Considering you can still even target XP with v140_xp toolset and that you would fix both #1480 and #1705, I really don't see what's the matter.

**Comment by mkrautz** [comment]
There is a LTCG bug that's blocking our switch. I haven't had time to investigate...

https://github.com/mkrautz/mumble-msvc2015-ltcg-crash-repro

That crashes when built in a default mumble buildenv with a MSVC2015 buildenv (win32-static or win64-static with VSVER=14.0 in prep.cmd)

**Comment by mkrautz** [comment]
So, it's not really because we don't want to switch. :-(

**Comment by mirh** [comment]
Update 3 I suppose?

**Comment by mkrautz** [comment]
@mirh Yep... Also happened with an earlier update (or maybe even stock 2015?).

**Comment by mirh** [comment]
Might be [this](https://connect.microsoft.com/VisualStudio/feedback/details/3102400) or [this](https://connect.microsoft.com/VisualStudio/Feedback/Details/3107570). 
(and it's not like one couldn't disable LTCG then)

**Comment by mirh** [comment]
[Soo](https://github.com/mumble-voip/mumble/pull/2775).. Did you solve?

**Comment by mkrautz** [comment]
@mirh Yes, I believe it's a compiler bug: https://bugreports.qt.io/browse/QTBUG-58318

**Comment by mirh** [comment]
Wow, nice effort you put there.

**Comment by mkrautz** [comment]
Thanks! We've been very unlucky. For the last two MSVC updates (2013 and 2015), we've hit obscure compiler bugs. Ouch.

**Comment by mirh** [comment]
Guess we should switch to gcc/clang 😛

**Comment by mirh** [comment]
You might or might have not noticed the "alternative solution" reply about `-Zc:threadSafeInit-` switch (which funnily is the same that gets Wx to work in XP too, but that's another matter)
