### ISSUE TITLE
Whispering to a user causes other users to hear the last little sliver of audio upon releasing the key.

### ISSUE THREAD

**Issue by Benguin** [mumble-voip/mumble#1616]
If two people on my server are whispering, I can tell, because every time one of them lets go of the whisper key, I hear a very short sample of sound from what they were saying as they released the key. This also triggers the attenuation. It's pretty irritating to other users, and happens on both windows and linux.

It only does it /some/ of the time, but it's pretty easy to reproduce.

**Comment by pprince** [comment]
+1, everyone in my WildStar guild is noticing, and telling me that I got "cut off" when I wasn't even talking in-channel :)

**Comment by Krzmbrzl** [comment]
This seems to be related to #1754

**Comment by Krzmbrzl** [comment]
I assume a fix for this would be to keep the whispering activated for just a little bit longer than the key is actually pressed. What do you think about this?

**Comment by dstensnes** [comment]
Could incorrectly routed audio streams like this be related to occasional garbled sound, eg. because receiving mumble client does not receive the beginning of an audio stream or something like that?

**Comment by Krzmbrzl** [comment]
I don't really see why an artifact from whispering that (accidentally) gets transmitted to all clients instead of just the whisper target would increase the likelyhood of Mumble missing the beginning of an audio stream... The latter I'd suspect to be mostly network-dependent.
That of course doesn't mean that there can't be some weird correlation between the two. I just don't think that this is likely :thinking: 

How did you come to that suspicion?

**Comment by dstensnes** [comment]
Nah, just curious if some of the garbled sounds some people have complained about in the past could be a result of two audio streams mashed together or something like that. It was just a thought, so pay no attention if it is wrong :)

**Comment by dstensnes** [comment]
My logic was simply that if this was the result of an uncleared buffer or invalid buffer size value, then some of the noises people might have complained about could be because some other sample or left over sample might be played back at a completely wrong bitrate or something like that

**Comment by Krzmbrzl** [comment]
I just fixed a bug in #4051 and I think that this issue is the due to that very same bug. Thus I tagged the PR to close this issue once it's merged.
