### ISSUE TITLE
Enable G15Helper for Windows x64 builds

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1618]
We should enable G15Helper for Windows x64 builds.

Blocked on https://github.com/mumble-voip/mumble/pull/1540 as it needs to use an x86 toolchain.

**Comment by Kissaki** [comment]
“blocked on”? I don’t see the correlation …

**Comment by mkrautz** [comment]
https://github.com/mkrautz/mumble/commit/374f8ea00abbb44ca40fa6048fca4be6206a2777
https://github.com/mkrautz/mumble/commit/a60c5153a433fd83de31c50b3615ade3ee696c28

**Comment by mkrautz** [comment]
BTW, I implemented this in master.

But the Windows build envs are broken at the moment, so I won't mark it as closed until it's in snapshots.

**Comment by mkrautz** [comment]
It's in snapshots.
