### ISSUE TITLE
Overlay and Fresh Win 8.1 Install

### ISSUE THREAD

**Issue by knight2142** [mumble-voip/mumble#1620]
With Mumble 1.3.0 on my Win 8.1 install I can't get the overlay to work on anything. 

Primary applications being Mass Effect 3, Star Wars: The Old Republic, and Minecraft (Feed The Beast)

**Comment by mkrautz** [comment]
Note that with current snapshots, the x64 snapshots can only present the x64 overlay, and the x86 snapshots can only present the x86 overlay. So perhaps that's what you're seeing.

**Comment by knight2142** [comment]
Minecraft is running on a Java 64bit and still not working. Also tried both standard and x64 installs. Neither work on any of the applications. (thought 1.2.8 does work with SWTOR and ME3 and not FTB)

**Comment by Attoy** [comment]
knight2142 are you running Mumble before the games and with administrator rights? This fixed my overlay issue the last time.

**Comment by knight2142** [comment]
I know for sure I was running Mumble prior to the game. I can't confirm admin mode though. I'll test that.

**Comment by Attoy** [comment]
I'm pretty sure running mumble with admin rights will solve your issue ;)

**Comment by knight2142** [comment]
Worked with SWTOR, but not working on Minecraft still.

Thanks

**Comment by Attoy** [comment]
SWTOR it's ok , Minecraft, never used it, but I know it's running over JRE. Perhaps you should check to have Java whitelisted on your Overlay configuration or not blacklisted. It depends if your overlay check the whitelist or the blacklist.

**Comment by knight2142** [comment]
Got all the minecraft stuff into the whitelist...no go.

**Comment by JoelTroch** [comment]
@knight2142 : Have you whitelisted the JAR itself or the JRE (Java Runtime Environment) ? Whitelisting the JAR won't do any good, you need to whitelist the JRE itself. Because any Java application start this way :
java.exe (or javaw.exe) -jar minecraft.jar [Others JVM options here]

By default, you can find the JRE (64 bits) here :
C:\Program Files\Java\jre\bin\java.exe
C:\Program Files\Java\jre\bin\javaw.exe

If you have both the 32 bits and 64 bits of the JRE, I suggest you whitelist both of them.

**Comment by knight2142** [comment]
![image](https://cloud.githubusercontent.com/assets/8713175/7462687/80d6d32a-f281-11e4-8380-6060847c4b09.png)

**Comment by Attoy** [comment]
@knight2142 to be sure add also the 32bit version , it should be under Program Files (x86) folder.

Does it work now?

**Comment by knight2142** [comment]
I don't have a 32bit java installed and i've had the overlay exceptions in place for a while now. It does not work.

**Comment by Krzmbrzl** [comment]
I'll close this as outdated. If you are still having trouoble with this, please let me know
