### ISSUE TITLE
Mumble Protocol Clarification - varint?

### ISSUE THREAD

**Issue by dylanetaft** [mumble-voip/mumble#1622]
More just a documentation issue\my understanding.  Appreciate any insight or explanation.

http://mumble-protocol.readthedocs.org/en/latest/voice_data.html
https://github.com/mumble-voip/mumble/blob/master/src/PacketDataStream.h

Having a bit of trouble understanding this.

I'm writing a Java mumble library.  Actually pretty close, it can do many text operations.  Log in, message people, listen to chat, set channel name, etc.

I'm working on voice capability now, listening first.  It's actually working, I was able to read the OPUS header and write the output to a file to a format opus_demo supports.  ./opus_demo -d 48000 1 filename Works great.

I think I am also "just lucky" that it works, since most varints that come through are small.

Prefixes:
0xxxxxxx	1 byte with 7 \cdot 8 + 1 leading zeroes
10xxxxxx + 1 byte	2 bytes with 6 \cdot 8 + 2 leading zeroes
110xxxxx + 2 bytes	3 bytes with 5 \cdot 8 + 3 leading zeroes
1110xxxx + 3 bytes	4 bytes with 4 \cdot 8 + 4 leading zeroes
111100__ + int (4 bytes)	32-bit positive number
111101__ + long (8 bytes)	64-bit number
111110__ + varint	Negative varint
111111xx	Byte-inverted negative two byte number (~xx)

The first 4 prefixes are easy to understand.

Which prefixes here should always be treated as unsigned(aka always positive?)  All of them unless it follows 111110__?

111100__ - does __ mean throw those two bits away(actually the whole byte) and the next 4 bytes are considered a _positive_ 32 bit integer?
Same with 111101__, except 64 bit - positive 64 bit?

111110__ - throw the two bits away(actually the whole byte), re-parse the next bytes as a negative varint via the same process?

111111xx - Not following what this is saying.  111111__ + (2 bytes) ?  Treat it as a byte inverted negative 16 bit integer?  Why is the byte inversion significant, what would I do with it?  Do I need to invert again?  Or does XX mean two bit?

**Comment by dylanetaft** [comment]
Out of curiosity, also, is this just a micro optimization that is really hard to remove because of backwards compatibility?  If it was me..I'd probably just include an extra full byte anywhere a varint would be used.  The first half of the byte could be used for flags, treat it as positive\negative\etc.  The second half is how many bytes follow to make up a varint.  Most varints seem to fall in the 1-2 byte range, so I can see not wanting to use 64 or 128 bits of data every time.  Adding an extra 8 bits and keeping the code really simple though...would be nice.   But it's something you write once and never look at again, probably. :)

**Comment by bontibon** [comment]
> Which prefixes here should always be treated as unsigned(aka always positive?) All of them unless it follows 111110__?

Almost; `111111xx` will also result in a negative number.

> 111100__ - does __ mean throw those two bits away(actually the whole byte) and the next 4 bytes are considered a positive 32 bit integer?

Yes.

> Same with 111101__, except 64 bit - positive 64 bit?

Yes.

> 111110__ - throw the two bits away(actually the whole byte), re-parse the next bytes as a negative varint via the same process?

Yes (though, technically, it reads a varint **then** negates it).

> 111111xx - Not following what this is saying. 111111__ + (2 bytes) ? Treat it as a byte inverted negative 16 bit integer? Why is the byte inversion significant, what would I do with it? Do I need to invert again? Or does XX mean two bit?

Yes, this is a typo; it should be two bit. This allows the values -1, -2, -3, and -4 to be encoded as a single byte.

The byte inversion is necessary. Here is what the conversions should look like:

    11111111    -4
    11111110    -3
    11111101    -2
    11111100    -1

**Comment by dylanetaft** [comment]
Thanks!!
