### ISSUE TITLE
Username doesn't get decoded on OS X (1.2.8)

### ISSUE THREAD

**Issue by moorscode** [mumble-voip/mumble#1627]
When using a mumble://MEDIC%3A%20U%20Be%20R%20Eddy@mumble.tf2center.com/?version=1.2.0 my username in Mumble still has the %3A instead of the ':'

**Comment by bontibon** [comment]
Possibly related issue: #1275

**Comment by Kissaki** [comment]
Verified that it works in 1.3.0~598, on Win7x64.

Yeah, looks like a duplicate.

**Comment by mkrautz** [comment]
Closed as duplicate.
