### ISSUE TITLE
murmur fails to listen on a default IP when started via systemd and upstart

### ISSUE THREAD

**Issue by crknadle** [mumble-voip/mumble#1629]
When using a default setting of "host=" (i.e. empty) or #host= (i.e. commented out), murmur tries to listen on "Any" interface, either via QHostAddress::AnyIPv6 or QHostAddress::Any, which should enumerate to "::" for IPv6/IPv4 or "0.0.0.0" for IPv4 only:

   http://doc.qt.io/qt-4.8/qhostaddress.html#SpecialAddress-enum

These "default IPs" should be "unconditionally available" and always work regardless of whether the local network is configured or not.  For some reason when running murmur under systemd or upstart, murmurd is started yet ends up **not** listening. 

However, using a **manual** setting of "host=::" or "host=0.0.0.0" both work fine.
?!?
So there must be some subtlety in the network initialization for murmur that differs depending on whether the host= setting has been specified or not.  [I've been looking at src/murmur/Meta.cpp] 

A service file for systemd for murmur doesn't help, BTW.  Before finding that setting "host=::" manually gets around this bug, I went through the effort of creating one (and reading lots of documentation to do so) to depend on network-online.target to get systemd to start murmur _after_ the network is "up", but that doesn't seem to help.

Debian bug (Jessie, systemd):
   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780300

Ubutnu bug (14.04, upstart):
   https://bugs.launchpad.net/ubuntu/+source/mumble/+bug/1346431

Thanks
-- Chris

**Comment by mkrautz** [comment]
Ticking bomb :-)

Jessie release date: 2015-04-25
Vivid release date: 2015-04-23

@crknadle, I have nothing to add right now, unfortunately. (Haven't had time to check up on what's actually going on...).  I hope to do so soon.

**Comment by crknadle** [comment]
@mkrautz:  Since this issue isn't security related, even if I had a fix right now I wouldn't be able to include it in Debian Jessie until the next _point_ release, the first of which will happen about three months after the official release.  I don't know but I would imagine that Ubuntu is similar in this regard.

I need to do some more testing but I suspect this issue may be related to network-manager.  Interfaces specified for auto-negotiation in /etc/network/interfaces will use ifupdown (which hopefully doesn't show this issue), but for interfaces not specified they're likely outside of systemd's considerations, so systemd won't wait for network-manager to start them before starting services dependant on the network.

There's a "NetworkManager-wait-online.service" discusseed here:

   http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

which at least from the description should work around this issue for when network-manager is used, similarly one for systemd-networkd.  However there's also a 'wicd-daemon' available and it may be that neither of these workarounds will work for that case.

I think all of this is brought about because there's no universal way on Debian (and likely Ubuntu) to know whether the network is "fully up".

**Comment by crknadle** [comment]
Mikkel Krautz:
> Closed #1629 via #2908.
> https://github.com/mumble-voip/mumble/issues/1629#event-986919502

I had a look at the commit, seems logical and should work.

I also had a quick peek at the murmur.service file linked to in #2908,
which I think looks fine AFAICT.  Just for quick comparison the one I
had created/tried is below, which used After=network-online-target, but
even then systemd doesn't wait for the network to actually be up. :-P


https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=780300;filename=mumble-server.service;msg=49

Thanks much.

   -- Chris

-- 
Chris Knadle
Chris.Knadle@coredump.us
