### ISSUE TITLE
OS X client deadlocks when stopping a multichannel FLAC recording after 3-4 hours

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1633]
andi-muc reports on IRC:

`23:05 < andi-muc> hi`
`23:06 < andi-muc> the mac osx client deadlocks when stopping a multichannel flac recording  after 3-4 hours`
`23:06 < andi-muc> http://paste.debian.net/hidden/f3985db0/`
`23:26 < andi-muc> and the local recorder file (my own voice) is still increasing`
`23:26 < andi-muc> currently it's about 2,7 GB`
`23:26 < andi-muc> 2708967763 21 Apr 01:21 Mumble-21-04-00-Recorder.flac`

See http://paste.debian.net/hidden/f3985db0/

**Comment by mkrautz** [comment]
Mirror of the paste, in case it disappears:
https://gist.github.com/mkrautz/91958eec86aed5de7371

**Comment by saerdnaer** [comment]
I can also provide the Mumble-21-04-00-Recorder.flac, if needed.

**Comment by hacst** [comment]
That bug should already be addressed by  ed424afa9414ea5bff7b37d6feb402e533e01dc6 and no longer occur in current snapshots. Unfortunately the latest stable 1.2.8 doesn't have this fix.
