### ISSUE TITLE
Build 597 mumble_ol_x64.exe missing D3DCOMPILER_47.dll

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1635]
When running this build (on my laptop) I see this error:

"The program can't start because D3DCOMPILER_47.dll is missing from your computer. Try reinstalling the program to fix the problem."

https://i.imgur.com/NDVWQbk.png

**Comment by mkrautz** [comment]
Ah, we only include one or the other. Will fix.

**Comment by mkrautz** [comment]
Fixed in 0128e7ddab68ab1792a6c2d98a2b0a40932d7ab9.

**Comment by mkrautz** [comment]
Will build a new snapshot.

**Comment by Tarun80** [comment]
That was fast. Thanks!

**Comment by Kissaki** [comment]
Experienced the same.
Works for me now with ~598.
