### ISSUE TITLE
Quitting Mumble 1.3.0 snapshot causes other programs to crash

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1637]
See for example:
http://abload.de/img/2015-04-2322_57_49-prd2s9r.png

There seems to be an issue with the new overlay helper process mechanism.

Maybe it's only related to the x64 overlay.  Now that the build ships with both overlays at the same time, many users are going to experience the overlay in 64-bit processes for the first time.

**Comment by Kissaki** [comment]
The linked screenshot is from me. The windows volume mixer, which was still running in the background, crashes as well.
All x64 programs.

I had updated the Mumble client once, and then another time (for the DLL fix).
The second time, it notified me of adobe flash, which it could not close, which I think I did then though, and a second notification did not appear.
I was able to use fine, and had an overlay playing Smite x86 DX9. I used my makro key there; which is probably why the MS keyboard center got active.

All was fine until I closed Mumble, some time after playing.

I am able to reproduce by running Mumble 1.3.0~598, going into a game of Smite x86 DX9, and using my MS keyboard Makro key. I then close Smite, and then Mumble -> Crash occurs on the MS keyboard center, and the volume mixer thingy I left open. (Not Hexchat this time.)

**Comment by JoelTroch** [comment]
Duplicate/Related to #1527

**Comment by mkrautz** [comment]
Thanks @JoelTroch . :-)

**Comment by Kissaki** [comment]
I don’t even need Smite to crash MS Mouse and Keyboard Center. After having set up a makro key,

* Start Mumble
* Press makro key
* exit Mumble

=> stuff crashes; specifically itype.exe

**Comment by Kissaki** [comment]
Checking the minidumps, none of the applications have a mumble_ol module injected still.

**Comment by Kissaki** [comment]
It seems like every x64 program is vulnerable to being crashed.
![2015-04-24 18_18_49-dumps](https://cloud.githubusercontent.com/assets/93181/7323377/661a445c-eaae-11e4-8011-6e28bac87df3.png)

It also crashed Keepass at one point, but using that alone, I can not reproduce.

**Comment by Kissaki** [comment]
Wow, Visual Studio is useless. WinDbg shows so much more …

> (1b28.1a18): Unknown exception - code c000041d (first/second chance not available)
<Unloaded_mumble_ol_x64.dll>+0x22e55:
000007fe`e3c62e55 ??              ???

> .  7  Id: 1b28.1a18 Suspend: 0 Teb: 000007ff`fffac000 Unfrozen
      Start: procexp64+0x97804 (00000001`3f6e7804) 
      Priority: 0  Priority class: 128  Affinity: f
Child-SP          RetAddr           Call Site
00000000`0528fd20 000007fe`e3c8bc08 <Unloaded_mumble_ol_x64.dll>+0x22e55
00000000`0528fd28 00000000`00000000 <Unloaded_mumble_ol_x64.dll>+0x4bc08

**Comment by Tarun80** [comment]
I can confirm this issue too. x64 Mumble was locking up my x64 Firefox and x64 Filezilla. I had to roll back.

It also locks up when you alt-tab out of a full screen game (GW2.exe 32 bit) a LOT more.

**Comment by Kissaki** [comment]
Can’t build right now …

**Comment by Kissaki** [comment]
No crashes have been reported to occur on Windows 8.
If anyone experienced otherwise, please say so.

**Comment by mkrautz** [comment]
Haven't seen crashes on Windows 8.1

**Comment by Mumpitz23** [comment]
Other Programs like ESET Smart Security, Total Commander, EVGA Precision X and TaskHost are also crashing when I shut down Mumble. The first 3 can be placed on the Blacklist which prevents crashing, but you can't place taskhost.exe on it.

http://i.imgur.com/VzzQXhb.png

**Comment by Kissaki** [comment]
As a workaround I suggest using the Whitelist rather than blacklist, until this issue is fixed.

**Comment by mkrautz** [comment]
Installed a Windows 7 VM, and I'm able to reproduce immediately.

**Comment by mkrautz** [comment]
We need a snapshot with https://github.com/mumble-voip/mumble/commit/57740e7e1b2f9f5a0f3e595bdfa134bab8e5d7a8 in it to get proper symbols for the crashes.

I will check back tomorrow. Just started a snapshot for that commit.

**Comment by mkrautz** [comment]
Symbolicated crash:

https://gist.github.com/mkrautz/66a29af8d2b4c0d3015c
