### ISSUE TITLE
The 1.3.0 release should target Qt 5.5 for our own binaries

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1638]
...and stabilize on that version.

**Comment by hacst** [comment]
:+1: for the stabilization part. For my taste we are seeing to much breakage from tracking upstream so closely. I think that version should have all the features we wanted from Qt 5.

**Comment by mkrautz** [comment]
This is not strictly necessary. Maybe we should just stabilize on 5.4.
