### ISSUE TITLE
Mumble client (1.2.8 to 1.3.0~598) causing fps drops even without overlay

### ISSUE THREAD

**Issue by Schroedingers-Cat** [mumble-voip/mumble#1640]
When I start Don't Starve Together (http://store.steampowered.com/app/322330) with the mumble client active, fps varies between 30-50, often somewhat locking at 45fps. The moment I close mumble, fps stays at 60 perfectly. As soon as I start mumble again, fps drops to 30-45fps.

What does not help:
* deactivating the overlay (side note: with the overlay activated I do not see the overlay in-game anyway)
* not having plugged in a microphone
* not even connecting to a server
* lowest bitrates
* using a native x64 client (x64, 1.3.0~598)
* using a stable client (x86, 1.2.8)
* lowering process priority of mumble and/or increasing process priority of the game
* forcing mumble to run on a different cpu core than the game does

Monitoring cpu usage in the task manager, mumble uses around 1-4% cpu and the game like 7%. 

What else can I try so mumble won't affect the game's fps?

Win7x64, latest steam and game client, 32GB ram, i7-3770, GTX770 (2GB).

**Comment by Kissaki** [comment]
After disabling the overlay, did you restart the game?

Did you try starting the game before Mumble?

**Comment by Schroedingers-Cat** [comment]
I thought restarting Mumble would be sufficient. Turns out, restarting the game after deactivating the overlay was the missing step. Thank you!
