### ISSUE TITLE
Wav recording is HUGE

### ISSUE THREAD

**Issue by bhardin** [mumble-voip/mumble#1642]
I recently recorded a mixdown wav audio of a 2 hour chat with just two people. The file came out to 785G.

I am blown away by this and it makes no sense to me. Is this normal?

**Comment by bhardin** [comment]
So. It looks like what happened was that the file just kept writing "blank" audio. Although our recording was only 2 hours long. The resulting file had about 72 hours of recorded audio. (All of the audio at the end was blank) even though we stopped the recording at the end of the 2 hours.

Potential issue with recording audio in mumble?

**Comment by hacst** [comment]
Haven't heard about that one before. A two hour stereo wav recording is suspiciously close to 2GiB. Maybe we are overflowing some intermediary variable. Could even be in libsndfile itself. Is it reproducible?

**Comment by bhardin** [comment]
I don't know if I can reproduce or not. But wanted to document the issue. I have read some other uses about getting a longer recording (usually with drift) than they had.

The next time we record, I will test the theory and see if I can reproduce.

**Comment by Krzmbrzl** [comment]
Is this reproducable in Mumble 1.3?
