### ISSUE TITLE
mumble starts and quits instantly

### ISSUE THREAD

**Issue by l29ah** [mumble-voip/mumble#1644]
I'm at ad1ed221148cf6e721529f8ff36af45ce4ec5fed on Gentoo linux. 
‰ strace mumble 2>&1 | dumpcheese 
https://dump.bitcheese.net/files/ywurysa/fileyWLBGP

**Comment by mkrautz** [comment]
Mumble seems to think another Mumble instance is running, and tries to bring that instance to the front using a focus RPC.

**Comment by l29ah** [comment]
Thanks: i had a strange mumble process hanging, killing it fixed stuff.

**Comment by mkrautz** [comment]
Hmmm. Maybe the semantics of QLocalSocket is making it do funny things, and exit early.

The intention of the code path at https://github.com/mumble-voip/mumble/blob/master/src/mumble/main.cpp#L285 is for Mumble only to exit if the message is received by the other client.

Are you sure there aren't multiple clients running?

If there aren't, we should add a more robust check for 'already running' on Linux.

In that case, you should be able to work around it by building with DBus support, or by removing the 'return 0'.

**Comment by mkrautz** [comment]
Ah, didn't see your message. All good.
