### ISSUE TITLE
[Murmur] Windows 10 is not detected

### ISSUE THREAD

**Issue by JoelTroch** [mumble-voip/mumble#1650]
Using Mumble's latest snapshot on a Windows 10 VM, Murmur still show Windows 8 instead of Windows 10.

UPDATE : Fixed a mistake, it shows as Windows 8, not 8.1

**Comment by mkrautz** [comment]
Murmur needs to grow its own https://github.com/mumble-voip/mumble/blob/master/src/mumble/mumble.appcompat.manifest

Any takers? :-)  If not, I'll pick it up eventually.

**Comment by mkrautz** [comment]
...Or just refer to Mumble's file.

**Comment by hacst** [comment]
Fixed by #1653 .
