### ISSUE TITLE
Custom client - how to start?

### ISSUE THREAD

**Issue by michail-nikolaev** [mumble-voip/mumble#1656]
Hello.

I want to implement custom client for Mumble for mod (Task Force Arrowhead Radio http://radio.task-force.ru/en) for Arma 3.

So, I want to connect to servers, process audio with custom DSP, list channels and users, also some support for messaging (for application purposes) is required.

But I am not sure if some kind of API (SDK?) is availble to implement it? Or it is required to dive into mumble client application and change it....

**Comment by hacst** [comment]
I think the most complete implementation of a client library is probably https://github.com/mumble-voip/mumblekit which is used in the iOS client. There's also https://github.com/mumble-voip/libmumble but afaik that's very limited in what it will do at this point. Of course you can always change the client. Can't say it was meant to be easily customized though (we don't have a plugin interface yet) so you would have to directly dig into the source. We also have some protocol documentation on http://mumble-protocol.readthedocs.org/en/latest/ and can answer questions on IRC if someone wants to put in the work of making such integration easier. Unfortunately we are pretty bogged down by client work :(

**Comment by hacst** [comment]
I'll close this as it's not really a bug or feature request. If you have further questions check out our forums on http://forums.mumble.info or hit us up on IRC in #mumble on freenode.

**Comment by michail-nikolaev** [comment]
Thanks a lot!
