### ISSUE TITLE
Connection refused since snapshot 1.3.0~624~g8f4b071~snapshot

### ISSUE THREAD

**Issue by nicolasjoly** [mumble-voip/mumble#1668]
Hi!

I updated my linux server to the latest snapshot (I'm always at the latest) and now it's blocking everyone from connecting. I have people on the latest stable and me on the latest snapshot and we all get a Connection Refused. There's literally nothing in the log post the server reboot.

**Comment by mkrautz** [comment]
Static or PPA?

**Comment by nicolasjoly** [comment]
PPA trusty : 1.3.0~624~g8f4b071~snapshot-1~ppa1~trusty1

**Comment by mkrautz** [comment]
The PPAs recently switched over to Qt 5.

Probably this issue? https://github.com/mumble-voip/mumble/issues/1343

Maybe it's the init script?  https://github.com/mumble-voip/mumble/issues/1629

**Comment by nicolasjoly** [comment]
Not really sure, I reverted back to a "stable" snapshot. The mumble client was showing the ping, but I guess this isn't a ping to the application mumble-server but just to the machine. If you need some testing I can boot up a 2nd VPS and install the PPA snapshot

**Comment by funkydude** [comment]
The "fix" for now is to set the following in your .ini
> host=0.0.0.0

As referenced here: https://github.com/mumble-voip/mumble/issues/1343

**Comment by nicolasjoly** [comment]
I have the same problem in 628. I've done the "fix" for now, but I don't know how people with IPv6 will react. IIRC, I have some users that have IPv6 when I checked their "Information" via the mumble client.
