### ISSUE TITLE
Audio cue should stop when PTT is released

### ISSUE THREAD

**Issue by 9001** [mumble-voip/mumble#1671]
I would like to use [this .ogg file](https://clyp.it/ddmnp0jm) as my "On" Audio Cue, giving audible feedback when the microphone is live. However, the .ogg will keep playing even after releasing the PTT button. When ending transmission, the "Off" Cue should play (like it currently does) but the "On" Cue should also be stopped.

**Comment by hacst** [comment]
If you want to tackle this you'll want to take a look at AudioOutputSample (https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutputSample.h) which we use to play the samples. Also void AudioInput::encodeAudioFrame in AudioInput.cpp is where the cues are triggered. More specifically https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioInput.cpp#L816 .

**Comment by Kissaki** [comment]
To document:
The linked .ogg file is 2 minutes long.
So the use case is using an audio cue *while* you are talking (keeping the PTT key pressed).
