### ISSUE TITLE
Stats should be sent over TLS

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#1674]
Any form of stats be it usage info, OS info, crash info, etc. should be sent securely over TLS.

**Comment by funkydude** [comment]
It would be nice to see this set for v1.3 as it can be considered a security issue.

**Comment by bontibon** [comment]
The offending lines:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/Usage.cpp#L95
https://github.com/mumble-voip/mumble/blob/master/src/mumble/Usage.cpp#L112

**Comment by hacst** [comment]
Jitter reporting isn't used anymore. For the other we'll like want to solve this in the scope of #1416 . While we won't be able to cache this part it still shouldn't directly hit mumble.info as that leaves us little options when slicing/dicing our services. Currently we only have a valid cert for the mumble.hive.no domain so we can't just append an "s" there and be done with it. It's a bit tricky to have proper SSL as soon as you are behind a CDN :(

**Comment by funkydude** [comment]
Could it not just be moved to mumble.hive.no so at least this specific issue is resolved? It seems odd having it depend on another ticket unrelated to security.

**Comment by hacst** [comment]
We could do that. I'd rather not though. We really need to move from mumble.hive.no as we do not have full control over that domain (it ultimately belongs to a university) or the server behind it (we have root but no clear way to handle hardware issues). I'll try to figure out if we can get a cert for (www.)mumble.info short-term...

**Comment by funkydude** [comment]
StartSSL? Letsencrypt?

**Comment by hacst** [comment]
It looks like thanks to @actown we'll soon have a wildcard certificate for our CDN which was our preferred solution from the beginning. That way we can secure all our *.mumble.info domains.

**Comment by funkydude** [comment]
Lets Encrypt is now in open beta.
