### ISSUE TITLE
Mumble tray icon appears top left in Ubuntu 14.04

### ISSUE THREAD

**Issue by mikesulsenti** [mumble-voip/mumble#1678]
Mumble version is on 1.3.0~628~gfcb908b~snapshot-1~ppa1~trusty1
Ubuntu 14.04.2

It'd also be nice to have a no tray icon option btw.

I found a possible reason here: https://github.com/zealdocs/zeal/issues/148

Related issue: http://askubuntu.com/questions/562259/dropbox-icon-in-the-wrong-place

Related issue, possibly not a true fix: http://askubuntu.com/questions/481614/viber-notification-is-not-in-the-right-position

Screenshots:

![screenshot from 2015-05-22 01 35 49](https://cloud.githubusercontent.com/assets/8174608/7766638/42c89fd0-0039-11e5-8267-bd97ff13464c.png)

![screenshot from 2015-05-22 04 16 37](https://cloud.githubusercontent.com/assets/8174608/7766647/5c42a6fe-0039-11e5-9db4-5e5216dce75f.png)

Even shows up in fullscreen applications
![screenshot from 2015-05-22 01 47 25](https://cloud.githubusercontent.com/assets/8174608/7766640/45d072de-0039-11e5-94e7-aeb6ec3a1ae7.png)

**Comment by mkrautz** [comment]
I thought there was an option to disable tray icon, but I suppose there isn't. Sorry.

**Comment by MPW1412** [comment]
Any news on this? Still an issue here on ubuntu 14.04 with the snapshot version of Mumble 1.3.

**Comment by ViBENo1** [comment]
this bug also cause flickering in some fullscreen applications on mx Ubuntu 14.04.

**Comment by akima-io** [comment]
I think this issue should be closed as Ubuntu 14.04 goes out of support next month. See [here](https://en.wikipedia.org/wiki/Ubuntu_operating_system#Releases).
