### ISSUE TITLE
Some users cannot load custom SVG files in skins

### ISSUE THREAD

**Issue by xPoke** [mumble-voip/mumble#1691]
Hey, here are some issues I received on my theme, but the issue appears to be global
https://github.com/xPoke/MetroMumble/issues/2
https://github.com/xPoke/MetroMumble/issues/11

It basically prevent some users from loading custom SVGs (loaded through QSS), with various success in solving via reinstalling and restarting. It was reported on both Win 7 and Mac OS.

Any idea what could be the cause of this?

**Comment by mkrautz** [comment]
You don't use SVGs that link to external images, do you? We've disabled the Qt functionality for that...

It's highly doubtful that that is indeed the problem, because a reinstall seems to fix it, though.

Other than that, I have no idea at present.

**Comment by xPoke** [comment]
I'm not sure if it counts as external - the resource is local and relative to the skin file, referenced via ``` image: url(skin:...)```
See [usage](https://github.com/xPoke/MetroMumble/blob/master/MetroLite.qss#L743) here.

The latest issue is one where re-installing and restarting apparently didn't help.

It could be an issue with the parsing of the url(skin:) lines, though I have no idea why it affects so few users and then gets fixed unexpectedly.

**Comment by mkrautz** [comment]
Relative paths in .qss should be fine.  What I am talking about above is using external files *from* the SVG.

**Comment by mkrautz** [comment]
@xPoke Just to make sure - the issue you are referring to as not working after a restart is the Mac issue -- correct?

**Comment by xPoke** [comment]
@mkrautz Indeed, that's the one I meant
https://github.com/xPoke/MetroMumble/issues/11

**Comment by mkrautz** [comment]
@xPoke Do you think this might be https://github.com/mkrautz/mumble-theme/commit/c8a325d69161c208ea2a91a99baf2e68b3c255aa?

**Comment by xPoke** [comment]
Currently abroad and via crappy european hotel wifi, will look in two days
when i'm back home :)

**Comment by xPoke** [comment]
@mkrautz Even though I had the OSX source in a different folder, I would compile it into the main theme folder - the same folder the regular QSS file was located. The non-OSX source was in it's own folder as well, to reduce user confusion when choosing the theme file. 
It also only affected files referenced via image: url(), but "standard" mumble svgs would load properly, which wouldn't happen if the QSS file was located in the wrong location.

So I don't think it has anything to do with it. That said, it has been a while since it was reported, and I don't think it was reported in the dev build, so I think it might have to do with user error or weird QT edge cases.

**Comment by xPoke** [comment]
Closing this for now until we get a report relevant to this repo.
