### ISSUE TITLE
G15 error on startup - 1.3.0-652-g441ae3f Client

### ISSUE THREAD

**Issue by nicolasjoly** [mumble-voip/mumble#1692]
Whenever I start the client I get this error : http://i.imgur.com/SZxYcF3.png I can close it and everything is fine. I don't have a G15 keyboard, but I do have a G502 mouse (both from logitech)

**Comment by mkrautz** [comment]
Is this a new error?

**Comment by mkrautz** [comment]
Also, x86 or x64 Mumble client?

**Comment by nicolasjoly** [comment]
Yes sorry. Windows 8.1 x64, x64 mumble client, never happened before. I'm always on the latest snapshot. I will try tonight on my laptop to see if I get the same error.

**Comment by mkrautz** [comment]
FWFW, can't reproduce using the x64 client here.

**Comment by nicolasjoly** [comment]
Same problem with the latest snapshot. I was able to "fix" it by removing "mumble-g15-helper.exe" from the mumble directory. I tried uninstalling mumble and renaming the sqlite, but I had the same problem.

BTW where are the settings located ? I thought the were all in the sqlite but it seems like it's only the saved servers.

**Comment by mkrautz** [comment]
The issue here is that mumble-g15-helper.exe is a 32-bit x86 executable.
It is dynamically linked against msvcr120.dll. We only ship the x64 msvcr120.dll on x64.

So, this works on systems that have msvcr120.dll in syswow64 from another source. But on more "pristine" Windows installations, it fails.

We should probably statically link mumble-g15-helper on x64.

**Comment by StrangerDanger** [comment]
I also get this Error when I start mumble. I am running a fresh install of Windows 10 build 10130.

**Comment by FrankVanVuuren** [comment]
I got the same issue on a fresh 64 bit Windows 10 Pro with `1.3.0~704~g6fe5547~snapshot`

**Comment by sephtin** [comment]
Google search brought me here regarding the same error.  Discussion above about fixing by changing code to statically link to mumble-g15-helper to x64.. but no easy fix for the ongoing issue.

Summary of the issue.  
--mumble-g15-helper.exe
--The application was unable to start correctly (0xc000007b).  Click OK to close the application.

Fix for existing versions:
--Download and install "vcredist_x86.exe" from Microsoft, here:  https://www.microsoft.com/en-us/download/details.aspx?id=40784

Hope this helps others.
