### ISSUE TITLE
connecting to VPN causes issues

### ISSUE THREAD

**Issue by meZee** [mumble-voip/mumble#1697]
Issue similar to #1696, and was made in response to a self-closed duplicate issue #1541.

When connecting to a VPN whilst already connected in mumble you can no longer hear anyone, or speak to anybody, but still appear connected. The microphone still lights up when attempting to speak, However you cannot move around, or otherwise interact with the server. It doesn't seem to timeout for quite awhile(30mins or so) for whatever reason, and does not continue to be an issue after.

**Comment by davidebeatrici** [comment]
Related to #2109?

**Comment by Krzmbrzl** [comment]
Does this still apply to Mumble 1.3?

**Comment by meZee** [comment]
Yes, I'm fairly certain it does.

**Comment by Reikion** [comment]
I'll tried to reproduce your problem and it works correctly. Mumble client disconnects after 2 seconds and reconnects.
OS: Linux
Mumble: 1.3.0
QT version: 5.14.1

**Comment by Krzmbrzl** [comment]
@Reikion thank you very much for testing this out :+1:

@meZee from the wording of your comment I take it that you didn't actually try it for yourself?

**Comment by Reikion** [comment]
It may be Windows specific thing, I'll check it out in a moment.

**Comment by Reikion** [comment]
On Windows it's even better. It doesn't disconnect. And still I can talk with my friend.
