### ISSUE TITLE
Murmur - Murmur.ini vanished

### ISSUE THREAD

**Issue by Kretol** [mumble-voip/mumble#1700]
Hello!

I recently updated the Murmur snapshot from 657 to 658 (specifically, 1.3.0~658~g3d46634~snapshot on WinX64), and it seems that the upgrade removed the murmur.ini file.  I tried searching the whole computer to no avail, and the log states that it is "Initializing settings from C:/Users/Administrator/AppData/Local/Mumble/Murmur/murmur.ini (basepath C:/Users/Administrator/AppData/Local/Mumble/Murmur)".  However, that location does not exist (the Mumble subfolder in the Local AppData path does not exist).

Should I just create that location and make a new murmur.ini file?

**Comment by nicolasjoly** [comment]
Are you sure it's not in your own account AppData (unless your account is called Administrator). You can go by typing this in the explorer %appdata%

It's pretty much impossible that AppData doesn't contain a Mumble directory since the client stores some of it's config in there.

**Comment by Kretol** [comment]
Aye, Administrator is the name of the account.  Once I created the subfolder and moved an old version of my mumble.ini in there (thank goodness I had a copy of it in the recycle bin from a few months back! ;) ), it ended up working fine.  Of course, I also ended up having to move the certificates in there as well.

**Comment by nicolasjoly** [comment]
Well thats some weird stuff. Everything was fine on Ubuntu when I did the upgrade.

**Comment by mkrautz** [comment]
Our new uninstaller behavior might have caused this...

Is it totally gone?  It's odd, because, in any case, one would think that the installer would replace the Murmur.ini with user modifications with the stock one...

**Comment by mkrautz** [comment]
I can see it on my own system, too. Investigating...

**Comment by mkrautz** [comment]
I guess what's going on is:

 - We changed the installer to uninstall completely before doing an installation. This is due to a new directory hierarchy, intended to improve user experience when upgrading an installation that uses the overlay.
 - The murmur.ini file is tagged with "NoOverwrite", presumably meaning it will only ever be installed on *clean* installs.
- Since we now remove the old installation beforehand, the Murmur.ini will vanish after doing an upgrade.

Not good. :-(

**Comment by Kissaki** [comment]
We probably want to fix this before 1.3.0, to prevent users from using their configs. @mkrautz agree?

**Comment by mkrautz** [comment]
Yes. We have a ticket for the installer thing.

**Comment by Kissaki** [comment]
#2901

**Comment by mkrautz** [comment]
This should be fixed in the latest snapshot: mumble-1.3.0\~2505\~g346702f.

If it isn't, please let us know! Thanks.
