### ISSUE TITLE
Git Submodules not accessible anymore

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#1701]
The submodules for speex and celt are not accessible anymore with the git protocol.
I suggest replacing it with https in `.gitmodules` which still works.

`git clone git://git.xiph.org/celt.git`
`Cloning into 'celt'...`
`fatal: read error: Connection reset by peer`

**Comment by Frogging101** [comment]
It doesn't look like this is the first time this has happened http://lists.xiph.org/pipermail/opus/2014-March/002574.html

I think it fixed itself last time though? I don't know. I'll try and find someone to poke over at Xiph.

**Comment by Frogging101** [comment]
It's fixed now.

**Comment by radioactiveman** [comment]
All right, closing this issue.
