### ISSUE TITLE
Configuration not being migrated from Mumble 1.2.x to 1.3.x

### ISSUE THREAD

**Issue by synapse84** [mumble-voip/mumble#1702]
I've only experienced this on Linux. I doubt it effects Windows, but may effect Mac builds as well.

After upgrading mumble from a Qt4 to Qt5 build, the server list is empty. This is likely related to the change to Qt's DataLocation.

Qt4: QDesktopServices::DataLocation => ~/.local/share/data/<APPNAME>
Qt5: QStandardPaths::DataLocation => ~/.local/share/<APPNAME>

I recorded a video of it:
https://www.youtube.com/watch?v=15bNOtTrhpo

explanation:
I installed mumble snapshot 657 compiled with Qt4.
ran mumble and added a server. (this created the directory ~/.local/share/data/Mumble/Mumble)
reran mumble to show the server is still in the server list.
I then installed mumble snapshot 657 compiled with Qt5.
ran mumble and the server list was empty. (this created the directory ~/.local/share/Mumble/Mumble)

**Comment by synapse84** [comment]
fixed in f6b746e. closing

**Comment by anarcat** [comment]
i've just had the same problem upgrading from 1.2.19-3 to 1.3.0~git20190114.9fcc588+dfsg-1: the directory changed but was not migrated over, so I doubt this is fixed.

**Comment by davidebeatrici** [comment]
Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920237
