### ISSUE TITLE
Toolchain files need to check for presence of x64 MSVC files

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1705]
See
https://github.com/mumble-voip/mumble/blob/master/toolchain/win32-msvc2013/x64.toolchain#L10-L14

If people use MSVC Express, they won't have the native amd64 compiler, but an x86 cross compiler that lives at a different path (x86_amd64 instead of amd64, I believe).

**Comment by hacst** [comment]
Is this still true for the Visual Studio Community edition? https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx says:
```
Q: How does Visual Studio Community 2013 compare to other Visual Studio editions? 
A: Visual Studio Community 2013 includes all the great functionality of Visual Studio Professional 2013, designed and optimized for individual developers, students, open source contributors, and small teams.
```
Community edition isn't exactly a drop-in replacement of express licensing wise - I think commercial users can use express but not community - it's probably good enough for our contributor base to not have to worry too much about it. All assuming it actually has the compiler ofc ;)

**Comment by mkrautz** [comment]
I know, I would love to recommend people to use Community.

But it's a small fix, and it doesn't hurt, so I think we should accommodate it.

FWIW, you can still get Express with Update 4, so it is still maintained.

**Comment by mkrautz** [comment]
And to answer your question: no, it's not the case for Community.

**Comment by austinliou** [comment]
VS Community does not have the native 64-bit x64 compilers, but it does have the 32-bit x64 cross-compiler, see here:
https://msdn.microsoft.com/en-us/library/hs24szh9%28v=vs.120%29.aspx

That being said, I managed to compile both a 32-bit and 64-bit build of Mumble on Win10 x64, with VS2013 Community, by simply changing references to 'amd64' to 'x86_amd64' in the following lines:
https://github.com/mumble-voip/mumble/blob/master/toolchain/win32-msvc2013/x64.toolchain#L10-L13

The other references were okay, although I was missing the atlmfc directory toward the bottom.  My guess is that component was not actually installed (and I forgot if you can even include that in your VS Community installation).

**Comment by mkrautz** [comment]
The page you linked to does not mention community, only Express. Community is supposed to be equivalent to Pro in 2013, so I believe it should have the correct compilers.

I just checked, and we use Community on our builder box, and it builds just fine with the current config (without falling back to the 32-bit cross compiler)... But it was an upgrade (well, downgrade) from Pro -> Community...

Are you sure Community doesn't have the native x64 compilers?

**Comment by austinliou** [comment]
I may have a faulty memory...I thought that Express was part of the Community installation.  I'll perform a full reinstall later today to check and get back to you, but in my specific case, I'm missing the amd64 toolchain.

**Comment by mkrautz** [comment]
No need to reinstall to confirm, if it's only for this bug. :-)

We just need to check for the existence of the native x64, and fall back, that's all... Someone just needs to update the .pro file. :-)

**Comment by mkrautz** [comment]
And just to confirm, the missing atlmfc directory didn't cause any issues, did it?

**Comment by austinliou** [comment]
Huh.  I must have installed the two separately without knowing; VS Community does indeed install the other toolchains.  My bad!  But you're right, I think there does should be a case for the win32 to win64 cross-compiler.

To answer your question, I was able to compile just fine without the atlmfc directory using VS Express, although I only compiled the Mumble client (no Murmur).

**Comment by forivall** [comment]
Just a quick FYI: Microsoft will be finally making the built tools available without VS: https://www.microsoft.com/en-us/download/details.aspx?id=49512 _(via http://nodeup.com/ninetyfive)_

**Comment by mirh** [comment]
> https://www.microsoft.com/en-us/download/details.aspx?id=49512

[Actually working link](http://landinghub.visualstudio.com/visual-cpp-build-tools).
