### ISSUE TITLE
Change log for 1.2.9?

### ISSUE THREAD

**Issue by godofgrunts** [mumble-voip/mumble#1707]
mumble.info doesn't seem to have one, and the change log in the github repo doesn't seem to be updated either. Can we get a change log for 1.2.9?

**Comment by bendem** [comment]
[This](https://github.com/mumble-voip/mumble/blob/1.2.x/CHANGES)? ([git history](https://github.com/mumble-voip/mumble/compare/1.2.8...1.2.9))

**Comment by godofgrunts** [comment]
Ah yes. I was in master. Silly me. Why isn't 1.2.x branch the master?

**Comment by mkrautz** [comment]
The master is what will become 1.3.0, 1.3.1, etc. So master == "1.3.x".

**Comment by bontibon** [comment]
The changelog is now up at http://wiki.mumble.info/wiki/1.2.9.
