### ISSUE TITLE
Attenuation or Volume Adjustment happening while disabled.

### ISSUE THREAD

**Issue by daryltucker** [mumble-voip/mumble#1710]
Under Mumble Configuration (Advanced) -> Audio Output, I have disabled both _while other users talk_ and _while you talk_ under Audio Output.

Unfortunately, I still see this happening, while not every time somebody talks, but most of the times they talk.

I was able to reduce this dramatically by editing `/etc/pulse/daemon.conf` (and then rebooting) to have:

```
default-sample-format = s16le
default-sample-rate = 44100
```

While I'm glad to have reduced the issue, it is still happening, and now I am not sure it's caused by Mumble.  I've started `mumble` in a console, as well as told `pulseaudio` to log to `/var/log/syslog`, but neither report **anything** as this happens.

Any suggestions?

**Comment by GizmoRA2** [comment]
Mumble 1.3.0~941~gcffa565~snapshot

I have the same problem in windows 10, I have it all unticked however it still attenuates when others speak

**Comment by Krzmbrzl** [comment]
Does this also happen with the stable 1.3 release?
