### ISSUE TITLE
murmur not in application bundle on OS X

### ISSUE THREAD

**Issue by robcee** [mumble-voip/mumble#1717]
Readme refers to launching murmur via Mumble.app/Contents/MacOS/murmur, but server is no longer there.

Suggest either updating the Readme to reflect reality or reincluding the server in the application bundle.

**Comment by mkrautz** [comment]
Needs a doc update. Murmur is now distributed separately, as "Static OS X Server": http://wiki.mumble.info/wiki/Main_Page

**Comment by alexkrishnan** [comment]
I have updated the OS X section of the README. PR is at https://github.com/mumble-voip/mumble/pull/1723

**Comment by mkrautz** [comment]
PR was landed a while ago. Thanks!
