### ISSUE TITLE
-bash: ./murmur.x86: cannot execute binary file

### ISSUE THREAD

**Issue by timelf123** [mumble-voip/mumble#1720]
```
[~] uname -a; lsb_release -a
Linux 3.19.5 #1 SMP x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
```

Any ideas? Tried on 1.2.9 and 1.2.8.

PS I don't have admin privileges on the box in question

**Comment by mkrautz** [comment]
Your kernel is built without support for running x86 binaries. We don't currently provide x86_64 builds because the vast majority of x86_64 systems do support x86 binaries.

I'd guess your best bet would be to use murmur from the Debian repositories instead.

**Comment by timelf123** [comment]
Thank you for the prompt response. I'll check out the Debian repo instead

**Comment by dstensnes** [comment]
You can check this by running "file" on the binary like so:
'''
$ file /usr/sbin/murmurd
/usr/sbin/murmurd: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0xc45b93026cd186c80c17c3e0856ab3b6b92d761d, stripped
$ 
'''
This is how it is reported with the debian version. It says "ELF 64-bit"

**Comment by timelf123** [comment]
Are there any instructions to build a static binary on a local machine? I'd like to get a 64bit only build

**Comment by hacst** [comment]
Why bother with a static if you plan to self-compile anyways? Building murmur from source on linux isn't that bad (and building a static is harder). There is http://wiki.mumble.info/wiki/BuildingLinux#Install_the_dependencies though you have to take care about not doing to much if you only want the server.

**Comment by timelf123** [comment]
Sorry, I should have clarified. I wish to build static because I am
compiling on a local machine, and pushing up to a server where I do not
have root access, nor the ability to install deps. I tried the --static
option but got all sorts of glibc errors

**Comment by hacst** [comment]
Our static build setup is pretty involved. You can find the scripts on https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.3.x/centos-ermine and https://github.com/mumble-voip/mumble-releng/blob/master/buildscripts/1.3.x/murmur-centos-ermine.bash (maybe others too) though I'm not sure how useful they are out of context. As the name says we build the statics using magic ermine on an old redhat to get maximum compatibility. I didn't set up this build so I don't really know how much easier it can be if you can disregard the backwards compatibility considerations. Iirc those created most of the trouble we had and is why we have to use extra tooling like ermine.

**Comment by dstensnes** [comment]
I suppose you could just upload the libraries used, to a folder and start the server with LD_LIBRARY_PATH environment variable pointing to that directory, but then you will have to update that directory manually for security updates and such. You should be able to build murmur on another machine, then use "ldd" on the binary to figure out which files needs uploading to the library directory defined.

**Comment by timelf123** [comment]
Thank you for all of the direction here! @hacst @dstensnes 

I'll try the contents of the PPA first. If it doesn't work, I'll likely call it quits on trying to get that working on this server.

**Comment by mkrautz** [comment]
Resolved support request. Closing.
