### ISSUE TITLE
[Feature Request] Logitech G-Keys

### ISSUE THREAD

**Issue by forivall** [mumble-voip/mumble#1721]
I'd like to write a PR for this! Would you accept adding this, esp. since the LCD plugin is already there? Who do I have to contact to get help, especially with modifying the windows build process (releng?) to include logitech's library?

FYI, for some reason, the current version of the g-key library available on [logitech's site](http://gaming.logitech.com/developers) ([GkeySDK_8.57.148.zip](http://www.logitech.com/pub/techsupport/SDK/GkeySDK_8.57.148.zip)) doesn't seem to work with my g710 with version 8.50.281 of logitech's desktop software (their current version is 8.58.183). However, it does work with the older [1.02.004 g-key library](https://github.com/noorus/nil/tree/master/external/LogitechGkeySDK_1.02.004) . I'll probably test upgrading my logitech software to see if it works with the new version then.

I'm currently working on [a tray app to talk to a teamspeak plugin](https://github.com/forivall/niftykb) to enable push to talk for keys that only directinput seems to pick up, where I basically ripped out mumble's keybinding code (so I've got a decent understanding of how do implement this). I also wanted to use it to allow mumble to detect g-key events, but I just realized that your plugin system doesn't do that kind of thing, so I'm submitting this PR. Alternatively, adding more features to the plugin system could be added, but I don't have the expertise needed for that.

**Comment by mkrautz** [comment]
Seems fine. How big of a diff to the current code is it? That's what I'm most worried about.

Regarding releng integration: what you could do to start off with is to gate the feature behind a qmake CONFIG flag, such as "gkeys", such that the default build won't break without the G-keys SDK in mumble-releng. Then I can add the G-key SDK to releng after the change has been landed.
Then, once the G-key SDK is available in mumble-releng, we can change the "gkeys" CONFIG option to be on by default, and require "no-gkeys" to disable it.

Now to the technical side:

How does it work in practice? Do we *have* to link against the .lib in order to use the SDK? Or can we dlopen/dlsym the functions at runtime from the .dll? The API surface looks very managable:  https://github.com/noorus/nil/blob/master/external/LogitechGkeySDK_1.02.004/Include/LogitechGkey.h

If possible, I'd like to avoid depending on a static library, and just have the feature depend on being able to load the LogitechGkey.dll at runtime (presumably directly from the Logitech Gaming Software  dir in Program Files or whatever?)...

**Comment by mkrautz** [comment]
Seems like nil loads the G-keys DLL -- neat. In that case, I have no technical qualms about the feature. Full steam ahead.

(I suppose we don't have to distribute the DLL ourselves? Surely it must be included with Logitech Gaming Software?!)

**Comment by mkrautz** [comment]
BTW, please simply use QLibrary to implement the runtime DLL load/call mechanism. (As opposed to Win32).

**Comment by forivall** [comment]
Ok, so, after some quick investigation, it looks like the newer versions of the logitech gaming software does include the dll, and the newest version of the sdk works with it as well. The docs of the current sdk version says "The lib file loads the dll LogitechGkey.dll that ships
with Logitech Gaming Software 8.55+". I'll also use the non-callback/polling interface, since we're already polling for dinput keys. Finally, I'll not use logitech's lib file to load the dll, but see how the mumble-g15-helper loads the lcd api, and see how to take the same approach, using qlibrary as you mentioned. It's looking like everything is as you expected, and I'll be moving forward!

**Comment by forivall** [comment]
nix that on mumble-g15-helper, it looks like it uses the lib. I'll still need some help to figure out how to lookup the dll to open it properly. from some digging, it looks like the location of the installed dll is stored in a registry key that the logitech lib looks up, then loads, and returns the appropriate error if it can't find it. this is probably the same mechanism used as the logitech lcd library. hrm...

I'll use qlibrary and, while developing, hardcode the location of the dll. The solutions i can think of are (1) set up a separate gkeyhelper, just like g15helper, communicating over stdio, (2) put an option in settings to ask the user where they installed the logitech gaming software, or (3) lookup the location in the registry ourselves...

**Comment by forivall** [comment]
Yup, it looks like it's stored in 
```
HKEY_CLASSES_ROOT\CLSID\{7bded654-f278-4977-a20f-6e72a0d07859}\ServerBinary
HKEY_CLASSES_ROOT\Wow6432Node\CLSID\{7bded654-f278-4977-a20f-6e72a0d07859}\ServerBinary
```
I would combine my (2) and (3) options, and load the location from the registry, but also include an advanced setting to be able to override it, in case logitech changes this. I'm looking at the lib in a hex editor to investigate further...

**Comment by forivall** [comment]
Yup, there it is, hard coded in the lib. I doubt they'd change it, but I'd still include a hidden setting.
```
0004:2B60 | 01 00 00 01  04 08 00 07  00 32 81 01  00 00 02 33  81 01 00 00  08 07 00 33  81 01 00 00  03 80 96 00 | .........2.....3.......3........
0004:2B80 | 53 00 4F 00  46 00 54 00  57 00 41 00  52 00 45 00  5C 00 43 00  6C 00 61 00  73 00 73 00  65 00 73 00 | S.O.F.T.W.A.R.E.\.C.l.a.s.s.e.s.
0004:2BA0 | 5C 00 43 00  4C 00 53 00  49 00 44 00  5C 00 7B 00  37 00 42 00  44 00 45 00  44 00 36 00  35 00 34 00 | \.C.L.S.I.D.\.{.7.B.D.E.D.6.5.4.
0004:2BC0 | 2D 00 46 00  32 00 37 00  38 00 2D 00  34 00 39 00  37 00 37 00  2D 00 41 00  32 00 30 00  46 00 2D 00 | -.F.2.7.8.-.4.9.7.7.-.A.2.0.F.-.
0004:2BE0 | 36 00 45 00  37 00 32 00  41 00 30 00  44 00 30 00  37 00 38 00  35 00 39 00  7D 00 5C 00  53 00 65 00 | 6.E.7.2.A.0.D.0.7.8.5.9.}.\.S.e.
0004:2C00 | 72 00 76 00  65 00 72 00  42 00 69 00  6E 00 61 00  72 00 79 00  00 00 07 00  41 81 01 00  00 03 0D 4C | r.v.e.r.B.i.n.a.r.y.....A......L
0004:2C20 | 6F 67 69 47  6B 65 79 49  6E 69 74 00  07 00 43 81  01 00 00 03  1C 4C 6F 67  69 47 6B 65  79 49 6E 69 | ogiGkeyInit...C......LogiGkeyIni
```

**Comment by mkrautz** [comment]
For an example of a library that's dynamically loaded and resovled via QLibrary, see https://github.com/mumble-voip/mumble/blob/master/src/mumble/CELTCodec.cpp

**Comment by mkrautz** [comment]
And its corresponding header: https://github.com/mumble-voip/mumble/blob/master/src/mumble/CELTCodec.h

**Comment by forivall** [comment]
Yup, I got the dll loading. https://github.com/forivall/mumble/blob/feature/gkeys/src/mumble/GlobalShortcut_win_gkey.cpp
The main question is to decide what mechanism should be used to find the dll, since the only purpose of the logitech gkey lib is to find the dll installed with the logitech gaming software, then load it. Right now it's hard coded, but I'll look up the registry and add a config setting. Because of how the gaming software responds to use of the api, I'd also like to make this feature togglable from the ui (of course, only if the logitech software is detected in the first place).
And, note to self: the logitech gaming software creates a profile for mumble, and the user will need to set the mumble profile to default or persistent in order to use the keys while mumble is not the active window (because the api is designed to be used with a game).

**Comment by mkrautz** [comment]
I'm curious what part of that file this relates to:

    // portions of this code are
    // Copyright (C) 2011-2014 Logitech. All rights reserved.
    // Author: Tiziano Pigliucci
    // Email: tpigliucci@logitech.com
    // http://gaming.logitech.com/en-us/developers

If you really based this on existing Logitech code, as opposed to using the Logitech code as an example, we'll need to fix any potential licensing issues.

**Comment by forivall** [comment]
```
#define LOGITECH_MAX_MOUSE_BUTTONS 20
#define LOGITECH_MAX_GKEYS 29
#define LOGITECH_MAX_M_STATES 3
```
And portions of the header for the API.

That's all. I guess I can remove the notice. (oracle v google, i can use the api, yada yada yada)

**Comment by forivall** [comment]
Yup, it (the logitech notice) was definitely only meant to go in the header file, since that's what nil does.

**Comment by mkrautz** [comment]
In any case, please don't outright copy them from the Logitech header.

I have written a small spec if someone wishes to implement this interface themselves in the future:

The G-keys DLL lives in "C:\Program Files\Logitech Gaming Software\SDK\G-key\x64\LogitechGkey.dll" for x64 and "C:\Program Files\Logitech Gaming Software\SDK\G-key\x86\LogitechGkey.dll" for x86.

Its location can also be read from the registry, using the following keys:

x86
    "HKEY_CLASSES_ROOT\\CLSID\\{7bded654-f278-4977-a20f-6e72a0d07859}\\ServerBinary"

x64:
    "HKEY_CLASSES_ROOT\\Wow6432Node\\CLSID\\{7bded654-f278-4977-a20f-6e72a0d07859}\\ServerBinary"

The registry keys are needed if a user installed the Logitech Gaming Software in a non-standard location.

The DLL has an init function, it's called "LogiGkeyInit". It takes a pointer, but the parameter must always be NULL. The function returns a BOOL as a status code.

The DLL also has a shutdown function, called "LogiGkeyShutdown". It takes no parameters and does not return anything.

You can poll for button states with the DLL using the functions "LogiGkeyIsMouseButtonPressed" and "LogiGkeyIsKeyboardGkeyPressed".

The function "LogiGkeyIsMouseButtonPressed" takes a single int parameter, a button number. Mouse button numbers run from 6 up to and including 20. The function returns a BOOL that is true if the button is pressed, and false if not.

The function "LogiGkeyIsKeyboardGkeyPressed" takes two int parameters, a button number and a mode number. Keyboard button numbers run from 1 up to and including 29. The mode number can 1, 2 or 3. The mode checks the button state in a specific mode. Typically, one queries all buttons for all modes, so one ends up with 29*3 calls to the function. The function returns a BOOL that is true if the button in the given mode is pressed, and false if not.

There are also two functions, "LogiGkeyGetMouseButtonString" and "LogiGkeyGetKeyboardGkeyString". They take the same parameters as the polling functions above, but do not check whether the button is pressed or not. Instead, they return the name of the button being queried as a pointer to a NUL-terminated array of wchar_t's. Presumably, the pointer will be NULL if the name cannot be retrieved or translated.

Also, @forivall, feel free to implement the DLL interaction using the above spec instead.

**Comment by forivall** [comment]
OK, I'll be rewriting the feature change from scratch based purely on the above spec, base on commit 8872ec2 at https://github.com/forivall/mumble/tree/feature/gkeys-clean.

**Comment by forivall** [comment]
nvm, it won't be based on that commit, I'll be switching to the pattern that CELTCodec uses, so it'll be quite different. and better :smile:

**Comment by forivall** [comment]
(waiting for code to compile) Yeah, thanks for calling me out on that. I am acutely aware of copyright issues, but, since I really didn't know how to go back and fix my mistake, i kinda wanted to plead ignorance and just ignore that I did that.

The code that I'm writing now is way cleaner than what I had before.

**Comment by mkrautz** [comment]
I will close this as well.  Thanks a lot of the addition. :-)
