### ISSUE TITLE
Mumble Asus Xonar u7 + USB Microphone driver conflict/problem(?).

### ISSUE THREAD

**Issue by gilthas** [mumble-voip/mumble#1722]
Couple of days ago i bought Asus Xonar u7 installed it and got a problem. My USB microphone(Blue Snowball) refuses to work if Xonar chosen as default device for incoming sound. If i chose onboard sound or other USB card in windows or mumble settings it works perfectly well. Other VoIP i have installed have no problems with Xonar too. I'll appreciate any possible help with this issue.

**Comment by mkrautz** [comment]
Hi,

This report is missing some useful information, such as which OS you are using, which Mumble version you are using, and so on.

Are you saying that when you configure Mumble to use the following device combo:

Audio Output: Xonar u7
Audio Input: Snowball

you cannot send audio in Mumble?

Or are you saying that when you use:

Audio Output: Xonar u7
Audio Input: Xonar u7

The Snowball doesn't work anywhere?  It's unclear to me what you actually mean.

**Comment by gilthas** [comment]
No the first suggestion is right, it affects only mumble, i can use it in other VoIP apps like Skype or Team Speak.

**Comment by mkrautz** [comment]
So the problem is that when you use this combo:

Audio Output: Xonar u7
Audio Input: Snowball

You cannot transmit audio to other users?

If so, it would be helpful for us to look at a Mumble log for a session where you start the client, configure it to use this combo, and maybe try to transmit audio.

The log file is automatically written to by Mumble, and you can get it at %APPDATA%\Mumble\Console.txt if you're on Windows.  We only need the parts related to the session you used for testing, so feel free to give us only that part of the log, and feel free to censor anything you'd not like us to see. Thanks!

**Comment by gilthas** [comment]
<W>2015-06-28 13:59:28.229 Database SQLite: "3.7.7.1" 
<W>2015-06-28 13:59:28.380 Overlay: Listening on "\\.\pipe\MumbleOverlayPipe" 
<W>2015-06-28 13:59:28.582 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2015-06-28 13:59:28.746 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} ???? ????:8
<W>2015-06-28 13:59:28.776 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} ?????????? ??????????:127
<W>2015-06-28 13:59:29.006 Adding device {ed3d5bd0-e602-11e1-8001-444553540000} XUSB Gamepad (Controller) XUSB Gamepad (Controller):10
<W>2015-06-28 13:59:29.041 Adding device {c6de6f30-fd64-11e3-8003-444553540000} G500s Laser Gaming Mouse G500s Laser Gaming Mouse:652
<W>2015-06-28 13:59:29.140 Adding device {ddd05a50-d866-11e3-8001-444553540000} USB Receiver USB Receiver:652
<W>2015-06-28 13:59:29.224 AudioInput: 83943 bits/s, 48000 hz, 480 sample
<W>2015-06-28 13:59:29.228 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:29.229 Adding device {d4437900-1b30-11e5-8001-444553540000} Xonar U7 Xonar U7:5
<W>2015-06-28 13:59:29.231 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:29.233 Adding device {e9c30e40-a1b2-11e0-8006-444553540000} Razer BlackWidow Razer BlackWidow:3
<W>2015-06-28 13:59:29.237 WASAPIInput: Stream Latency 58050 (882)
<W>2015-06-28 13:59:29.238 WASAPIInput: Echo Initialize failed: hr=0x88890008
<W>2015-06-28 13:59:29.246 Adding device {e9c33550-a1b2-11e0-8007-444553540000} Razer BlackWidow Razer BlackWidow:573
<W>2015-06-28 13:59:29.287 WASAPIOutput: Stream Latency 106666 (2880)
<W>2015-06-28 13:59:29.287 WASAPIOutput: Periods 10000us 3000us (latency 10666us)
<W>2015-06-28 13:59:29.287 WASAPIOutput: Buffer is 60000us (5)
<W>2015-06-28 13:59:29.293 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2015-06-28 13:59:31.479 OpenSSL Support: 1 (OpenSSL 1.0.1n 11 Jun 2015)
<W>2015-06-28 13:59:31.499 SSL: CA certificate filter applied. Filtered size: 104, original size: 106
<W>2015-06-28 13:59:31.499 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
<W>2015-06-28 13:59:31.519 ServerHandler: QOS2 loaded
<W>2015-06-28 13:59:34.533 "Text "Говорит" did not fit (+8/-1): (+5.13298/-1.42027). Scaling to 0.70409." 
<W>2015-06-28 13:59:34.537 "Text "Крик" did not fit (+8/-1): (+5.13298/-1.42027). Scaling to 0.70409." 
<W>2015-06-28 13:59:34.539 "Text "[Tau]Giltt" did not fit (+8/-1): (+5.36395/-1.35133). Scaling to 0.740013." 
<W>2015-06-28 13:59:39.464 AudioInput: 83943 bits/s, 48000 hz, 480 sample
<W>2015-06-28 13:59:39.469 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:39.472 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:39.487 WASAPIInput: Stream Latency 58050 (882)
<W>2015-06-28 13:59:39.488 WASAPIInput: Echo Initialize failed: hr=0x88890008
<W>2015-06-28 13:59:39.533 WASAPIOutput: Stream Latency 106666 (2880)
<W>2015-06-28 13:59:39.533 WASAPIOutput: Periods 10000us 3000us (latency 10666us)
<W>2015-06-28 13:59:39.533 WASAPIOutput: Buffer is 60000us (5)
<W>2015-06-28 13:59:39.533 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2015-06-28 13:59:44.747 AudioInput: 83943 bits/s, 48000 hz, 480 sample
<W>2015-06-28 13:59:44.751 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:44.754 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:44.764 WASAPIInput: Stream Latency 58050 (882)
<W>2015-06-28 13:59:44.766 WASAPIInput: Echo Initialize failed: hr=0x88890008
<W>2015-06-28 13:59:44.813 WASAPIOutput: Stream Latency 106666 (2880)
<W>2015-06-28 13:59:44.813 WASAPIOutput: Periods 10000us 3000us (latency 10666us)
<W>2015-06-28 13:59:44.813 WASAPIOutput: Buffer is 60000us (5)
<W>2015-06-28 13:59:44.813 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2015-06-28 13:59:45.372 AudioInput: 83943 bits/s, 48000 hz, 480 sample
<W>2015-06-28 13:59:45.375 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:45.379 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-06-28 13:59:45.396 WASAPIInput: Stream Latency 58050 (882)
<W>2015-06-28 13:59:45.399 WASAPIInput: Echo Initialize failed: hr=0x88890008
<W>2015-06-28 13:59:45.443 WASAPIOutput: Stream Latency 106666 (2880)
<W>2015-06-28 13:59:45.443 WASAPIOutput: Periods 10000us 3000us (latency 10666us)
<W>2015-06-28 13:59:45.443 WASAPIOutput: Buffer is 60000us (5)
<W>2015-06-28 13:59:45.443 AudioOutput: Initialized 2 channel 48000 hz mixer

**Comment by mkrautz** [comment]
Seems like WASAPIInput is exiting early because it can't initialize echo cancellation.

You can't use Echo Cancellation across devices (it has to be the same device for both input and output). I would have thought the client was smart enough to disable echo cancellation if the devices do not match -- but that does not seem to be the case.

Can you try to disable Echo Cancellation? In Audio Input, set the Echo combo box to "None", and hit apply.

If that works, we should fix it so that WASAPI only tries to enable Echo Cancellation if the devices match -- and maybe fix up the UI if we can do it in a way that makes sense.

**Comment by gilthas** [comment]
Yea i tried it and it seems to work.

**Comment by mkrautz** [comment]
Excellent. Now tracking the problem in the issue referenced above.
