### ISSUE TITLE
murmur.ini references old site

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1727]
#registerUrl=http://mumble.sourceforge.net/

Shouldn't this be updated to the new mumble.info? Noticed this made it's way into 1.2.9's ini.

**Comment by mkrautz** [comment]
Yes!

**Comment by bendem** [comment]
There is actually [quite a lot of references to sourceforge](https://github.com/mumble-voip/mumble/search?utf8=%E2%9C%93&q=sourceforge) scattered throughout the mumble codebase.

**Comment by mkrautz** [comment]
Most of them cannot be changed as they are reverse-DNS-notation names that are part of APIs (DBus in particular), app bundle identifiers, and such.

The user-facing ones should be changed, though!

**Comment by Tarun80** [comment]
Solved as per the above #1736.
