### ISSUE TITLE
Separate 'user renamed' message options

### ISSUE THREAD

**Issue by nfug** [mumble-voip/mumble#1728]
Currently, "x renamed to y" messages are handled by the "Information" options. MOTD is also affected by the same option.

I have a number of minigames implemented with Ice which display dynamic data (e.g. score) as a name postfix. You can imagine the amount of spammed rename messages in the chat with lots of people.

The workaround is to disable the entire "Information" category but that, as I already mentioned, disables the MOTD as well and maybe something else I am not aware of.

I suggest simply adding another set of checkboxes specifically for the rename messages much like there already is one for every possible mute/deafen interaction.

**Comment by mkrautz** [comment]
Seems fine, will put this up-for-grabs.

**Comment by bheart** [comment]
Text, audio files and TTS works, I haven't tested the notifications/balloons.

**Comment by bontibon** [comment]
@bheart You should rebase to include d19e266f5dd06732905722e3b33a8810a299ebf5.

**Comment by mkrautz** [comment]
I hope the change was actually ready for primetime. It looked like it! :-)

**Comment by bheart** [comment]
I believe so, I didn't test the balloon notifications though.
