### ISSUE TITLE
[Feature Request] Mixer within the software

### ISSUE THREAD

**Issue by biboon** [mumble-voip/mumble#1729]
I think that would be a cool feature to tune the volume of each speaker in a server. Sometimes the sound can be not equalized and this would allow us to solve this problem

**Comment by bheart** [comment]
Per-user volume adjustment is scheduled for 1.3.0 (see #1156)

**Comment by biboon** [comment]
Yes indeed that is exactly what i was thinking. Thanks for the fast reply !
