### ISSUE TITLE
Overlay Steam?

### ISSUE THREAD

**Issue by mememe528** [mumble-voip/mumble#1738]
So, when Mumble is running, no overlay on Steam, uh?
Sorry but the overlay Steam is better than your dumb software... TeamSpeak, Skype and a lot of other shit do the work better WITH the overlay on...
Find a way...

**Comment by bheart** [comment]
Could you perhaps elaborate? The Steam overlay works fine with the Mumble running on my system, maybe if you shared some more details we'd have a chance at figuring out your issue.

**Comment by hacst** [comment]
Nope he can't. closed and locked.
