### ISSUE TITLE
Overlay issues

### ISSUE THREAD

**Issue by Unopposedcomet** [mumble-voip/mumble#1739]
I currently have the latest snapshot of mumble and have only gotten the overlay to work once, I also primarily use it on planetside 2.

**Comment by chrisbarmonde** [comment]
FWIW, I've found you need to have mumble open *before* launching the game in order for the Overlay to work. Whether this is intentional or not, I don't know.

**Comment by Kissaki** [comment]
Closing as no reply to previous suggestion / clarification.
If you feel like that’s your issue, please reply back / open a new, more specific issue.
