### ISSUE TITLE
Mumble 664 overlay causing black screen and lockups

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1740]
Snapshot 664 (x64) has been causing lockups on my computer. I'll notice it will suddenly become very sluggish, typing and all. Then lock up. Ctrl+Alt+Delete doesn't help because the desktop will no longer render.

I've recently run with the overlay disabled through Mumble and it will work just fine. This problem seems to occur after a few days usage. Nothing shows up in the Mumble log about the crash. I will notice that Mumble does crash when this occurs because the PTT audio cue no longer works.

**Comment by Kissaki** [comment]
I’m not sure how to debug this?
Anything to isolate this issue or when it occurs?

**Comment by Tarun80** [comment]
Unfortunately no. It happened generally after a few days. System would crawl, then lock up. I disabled the overlay back when I was having this issue and have not reenabled it since then.

That is, I'd boot up, run it for a few days until I got the system lockup which would force a restart. All I was doing was playing GW2 using the Steam overlay (as always).

**Comment by Tarun80** [comment]
I recently tried enabling the overlay and had it lock up the overlay (and my computer briefly).

From console.txt:
```
<W>2015-10-12 04:30:10.870 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2015-10-12 04:30:10.870 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
<W>2015-10-12 14:39:03.970 Overlay: Dead client detected. PID 7224 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<D>2015-10-12 14:39:04.965 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
<W>2015-10-12 17:07:29.945 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2015-10-12 17:07:29.945 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
<W>2015-10-12 19:47:55.984 Overlay: Dead client detected. PID 2160 "C:\Program Files (x86)\Guild Wars 2\Gw2.exe"
<D>2015-10-12 19:47:56.988 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
<W>2015-10-12 20:00:05.358 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2015-10-12 20:00:05.358 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
<W>2015-10-12 20:00:08.700 class QPixmap __cdecl QPixmap::grabWindow(unsigned __int64,int,int,int,int) is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
```

**Comment by Krzmbrzl** [comment]
I assume this still happens in the stable Mumble 1.3?
