### ISSUE TITLE
Mumble Wiki Main Page needs updates

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1742]
There are several sections on the main page that need minor edits to update things, unfortunately it's locked down and there's no editable draft page available. What could be updated are things such as how it's pointing to sourceforce, a more correct link to the iPhone app, what's new points to 1.2.8.

These are things I noticed just glancing over it initially.

**Comment by trustable-code** [comment]
Please see also the points I mentioned on the talk page http://wiki.mumble.info/wiki/Talk:Main_Page

**Comment by mkrautz** [comment]
I'm curious what you think a more correct link to the iOS app would be?

**Comment by trustable-code** [comment]
The link could be more clean: https://itunes.apple.com/us/app/mumble/id443472808

**Comment by Tarun80** [comment]
The above posted link by @trustable-code will not work, because it's region specific. When I looked into this last I saw that the following link would work just fine. The region should properly autodetect and work no matter where in the world they view it.

https://itunes.apple.com/app/mumblefy/id858752232?mt=8

**Comment by mkrautz** [comment]
That is not the Mumble app. It's Mumblefy.

**Comment by mkrautz** [comment]
But yeah, the link structure is probably what you mean. Sorry for the nitpick.

**Comment by Tarun80** [comment]
@mkrautz, no problem at all. I should have been clearer myself.

**Comment by Tarun80** [comment]
Adding on, I think a link to the snapshot directory would be a nice addition as well.

**Comment by Kissaki** [comment]
Apart from debugging errors, the snapshot directory is not really meant to be (that) public.
There is no reason to use outdated versions, which is why links to the most recent version per version line should be sufficient.

**Comment by Kissaki** [comment]
Apart from the iOS link all suggestions seem to have been applied.
So, @mkrautz do we want to adjust the link to the iOS app?

**Comment by Tarun80** [comment]
It looks like everything has been fixed/etc.
