### ISSUE TITLE
Closing Mumble leaves Mumble.exe running.

### ISSUE THREAD

**Issue by rsheffield** [mumble-voip/mumble#1745]
Each time Mumble is opened, a new mumble.exe process is spawned & not closed when the application is closed, resulting in multiple orphaned processes viewable in TaskMgr.

Observed using 1.2.10
![mumble_orphanedprocesses_2](https://cloud.githubusercontent.com/assets/13107640/8634867/12af9eac-27d0-11e5-98be-c13ec7fc613a.jpg)

**Comment by hacst** [comment]
Did you observe this behavior in 1.2.9? Is it a 64bit or 32bit mumble. Also which version of Windows are you using?

**Comment by rsheffield** [comment]
I did not check 1.2.9, but I noticed it just prior to updating to 1.2.10 from 1.2.8, so 1.2.8 was also affected.

Install is from the STABLE branch, so that should be 32bit, no?  However, it is installing to a 64bit machine, so if the installer is sorting out which version to install, then it would be 64bit.  Install was downloaded from the 1.2.10 STABLE link on mumble.info.

OS is W8.1 Pro.

**Comment by mkrautz** [comment]
Clearing the milestone. Unable to reproduce.

@rsheffield Do you still experience this?

**Comment by mkrautz** [comment]
No response. Unable to reproduce. Closing.
