### ISSUE TITLE
Mumble fails to restart itself on Windows 7 and later

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble#1747]
Mumble fails to restart itself when asked to do so from the configuration menu. This failure is handled correctly and the shutdown in general is clean.

This is because we run with ```uiaccess=true``` resulting in the normal ```QProcess::startDetached``` failing with the following in the windows error log: ```"The process failed to handle ERROR_ELEVATION_REQUIRED during the creation of a child process."```

There's a long standing bug report for running applications requiring elevation with QProcess https://bugreports.qt.io/browse/QTBUG-7645 . This is likely the cause.

Possible workarounds might be:

- Using http://doc.qt.io/qt-4.8/qdesktopservices.html#openUrl to launch the .exe in the hopes that the OS does whatever is required to do so.
- Implement a platform specific workaround as described  in http://codeblog.vurdalakov.net/2010/09/solution-qprocessstartdetached-cannot.html . Apparently we have to watch out for behavioral differences between XP and later though.

In general it's a bit unclear on what we have to expect here. Does our process have enough rights to re-launch itself without an UAC prompt appearing? Will we actually launch with the same permissions as if a user had started mumble manually?

Unfortunately this cannot be reproduced locally without signing the binaries and placing them in the right location which is how it slipped by testing :(

**Comment by funkydude** [comment]
Just pitching in what I said on IRC that I think it should just display a window with a generic "please relaunch mumble" and exits when you click ok. KISS etc. I don't think implementing what appears to be a hack is worth it for what I assume is solely the skin change functionality. There is nothing unfriendly about asking the user to launch the application again.

**Comment by mkrautz** [comment]
You should be able to use openUrl. It will use the same ShellExecuteEx mechanism as described in the blog post in our Qt fork.

**Comment by mkrautz** [comment]
...But opening by URL might only work on Windows.

**Comment by JoelTroch** [comment]
Just had this issue around 5 minutes ago (I left my name in the crash report so you will recognize it) when trying the themes.

**Comment by hacst** [comment]
@mkrautz OpenUrl unfortunately also doesn't allow us to pass parameters which breaks the "restore state as good as possible" functionality I intended the feature to have (though I would let that go if it makes for a cleaner overall solution).

**Comment by hacst** [comment]
@JoelTroch If you experience a crash on restart that is an issue unrelated to this one. Please report it separately and I'll try to see whether the crash-dump you uploaded is enough to diagnose the issue.

**Comment by hacst** [comment]
This should hopefully fix it. Will know with the next snapshot (can't really test this locally as I can't sign my executable at the moment). If you still experience crashes please open a separate issue as that is an unrelated issue.
