### ISSUE TITLE
Remove background on dev build notification

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#1748]
With the new theme, the background color makes the text extremely difficult to read. To be honest, the background seems entirely pointless, and should just be white.

![screenshot](http://abload.de/img/bgomyvw.png)

**Comment by mkrautz** [comment]
@xPoke I just had a look at the HTML, and we actually do set the color for the HTML snippet we show here. (See http://mumble.info/focus.php)

That means the theme is overriding colors of HTML messages, which it should not, AFAICS.

Do you agree?

**Comment by xPoke** [comment]
This is a QT issue - QT allows QSS to override text colors in general, but specifically doesn't allow it for links.
More strangely, things that get shown later (like server motd) don't seem to be affected by this.
So HTML messages are generally okay - 
![untitled](https://cloud.githubusercontent.com/assets/2204968/8642822/31b302ee-2933-11e5-8877-a368ef1c18e6.png)

**Comment by Tarun80** [comment]
What happens if you remove the style section from the table? It should appear just fine?

``` style="background: #123456; color: #ffffe0;" ```

**Comment by hacst** [comment]
It's less about how to fix the message and more about why it is getting screwed up in the first place. Unless I'm mistaken we set background AND text color for the focus message so for me it's a bit of a mystery why it would break that way.

@xPoke Are you sure? I thought the links and the background were the only things actually getting the colors configured for the snippet. See http://mumble.info/focus.php

**Comment by xPoke** [comment]
Could it be that the qss or qpalette get loaded after the message gets written to the log?

It's possible that the theme is overriding the color set by the table.

It's either that or qpalette just takes priority of the subelements for some obscure qt reason.

**Comment by hacst** [comment]
I would find it unlikely that the palette overrides what's already in the table as it does a network query to fetch that message and happens quite a bit after we apply the theme. Should be much to slow to race anything the palette is doing. It's applied quite early in the code. It's imho likelier we are hitting some strange Qt behavior. Should try to create a simple repro test-case. Maybe it can be fixed/worked around.

**Comment by DGMurdockIII** [comment]
will this be fixed in next snapshot build

**Comment by mkrautz** [comment]
@DGMurdockIII No, it has not been fixed yet. Someone needs to figure out what is wrong.

**Comment by DGMurdockIII** [comment]
aslo it did not start happening till u started using the new skin based off metro mumble

**Comment by Tarun80** [comment]
@mkrautz, did my potential solution not get attempted or work?

**Comment by mkrautz** [comment]
It would probably work. But I worry what the effect of this is on user messages. If the stylesheet overrides our own HTML, what does it do to user's messages?

**Comment by mkrautz** [comment]
OK, @xPoke states that later HTML messages are fine....

**Comment by mkrautz** [comment]
Put up a "fix". The fix seems correct to me, but breaks styling of the log. It seems that the ability to style the log was "accidental" this whole time.

**Comment by mkrautz** [comment]
Fixed by https://github.com/mumble-voip/mumble-theme/commit/a100f09f519de971c39db32e4b857c640052a04e.
