### ISSUE TITLE
Ubuntu 15.04 PPA support

### ISSUE THREAD

**Issue by Hannobal** [mumble-voip/mumble#1761]
Please add PPA support for Ubuntu Vivid (15.04)

**Comment by mkrautz** [comment]
I've done a new upload of the stable PPA, now with vivid and willy included. Thanks for the heads up.

**Comment by Hannobal** [comment]
Thanks a lot :) But I don't get any mumble updates.

According to this site there were build failures. https://launchpad.net/~mumble/+archive/ubuntu/release/+packages
