### ISSUE TITLE
Ubuntu 15.04 PPA build failures

### ISSUE THREAD

**Issue by Hannobal** [mumble-voip/mumble#1762]
I don't get any mumble updates for Ubuntu Vivid (15.04).

According to this site there were build failures. https://launchpad.net/~mumble/+archive/ubuntu/release/+packages

Seems that it is missing some dependencies https://launchpad.net/~mumble/+archive/ubuntu/release/+build/7714317

**Comment by mkrautz** [comment]
Sorry for earlier, I thought the base package was ready for newer releases, but instead we rewrite it for newer distros via "backports"...

Anyway, I've added support for vivid now, let's see if it builds before I close, this time. :-)

**Comment by mkrautz** [comment]
It built 👍
