### ISSUE TITLE
Update to Qt 5.5 (and OpenSSL 1.0.2)

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#1764]
Since 5.5.1 [isn't due until September](https://wiki.qt.io/Qt-5.5-release) I think we can safely update to Qt 5.5 now, which in turns enables us to update to OpenSSL 1.0.2.

**Comment by funkydude** [comment]
Halfway through October.
http://blog.qt.io/blog/2015/10/15/qt-5-5-1-released/

**Comment by mkrautz** [comment]
While this has taken longer than I had hoped, I wasn't actually waiting for 5.5.1 to release before bumping us to 5.5.1. The Windows buildenv was updated a while ago with Qt 5.5: https://github.com/mumble-voip/mumble-releng/commit/a9cbd32e733b7fe6f2a570abf91cfd7e45fbf668

Still hoping to get the rest of the environments up to speed with 5.5.1 and OpenSSL 1.0.2 ASAP.
