### ISSUE TITLE
'User Joined/Left Your Channel' notification

### ISSUE THREAD

**Issue by Rawi666** [mumble-voip/mumble#1766]
It would be really great if Mumble had new type of notification when a user joins/lefts YOUR channel instead of notifying when someone joins/lefts ANY channel.

As a user I'm less interested when someone joins other channels but I'd like to know when someone joins exactly the channel where I'm in

**Comment by Tarun80** [comment]
Not sure what you're talking about. Mumble only tells you when a user joins/leaves the channel you're currently in.

**Comment by Rawi666** [comment]
Ok looks like my mumble was corrupted. After reinstalling everything works fine

**Comment by Tarun80** [comment]
Glad to hear you got it fixed. :)
