### ISSUE TITLE
Mumble crash on "Add new..."

### ISSUE THREAD

**Issue by ManDude** [mumble-voip/mumble#1767]
Just installed Windows Mumble from the website, but whenever I click "Add New..." on Connect it crashes (and strts using all the RAM possible).

Windows 7 32-bit

**Comment by hacst** [comment]
Hi. Were you able to submit a crashreport (mumble should ask when restarting after the crash). If so what did you put into the description (or the email field).

**Comment by ManDude** [comment]
I don't remember but I think I put that it crashed when I clicked add new. I can't recall if I filled the e-mail box though.

Using the version that was on the download page in the website 4 days ago.

**Comment by Krzmbrzl** [comment]
Seems to be fixed in 1.3
