### ISSUE TITLE
Fix QPixmap::grabWindow

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#1769]
Regarding this log event:
class QPixmap __cdecl QPixmap::grabWindow(unsigned __int64,int,int,int,int) is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.

**Comment by funkydude** [comment]
Fixed by https://github.com/mumble-voip/mumble/commit/495dfdc099df57470b2985d8aad1014791cbb23f ?

**Comment by mkrautz** [comment]
Yes, it should be.
