### ISSUE TITLE
Can't connect to any server: Hangs on connect. (Windows 10 and Windows 7)

### ISSUE THREAD

**Issue by BananasGoMoo** [mumble-voip/mumble#1774]
Whenever I try to connect to ANY server, after I press the connect button, Mumble hangs indefinitely. When I was on windows 7, it would hang for about a minute until it finally connected, but now on Windows 10 it hangs and doesn't seem to ever get past that.

I thought it was a problem with my old Windows 7 install, but I've done a clean install on Windows 10, and then I reinstalled using the snapshot, as well. Both 1.2.10 and 1.3.0 snapshot have the same problem.

Using Windows 10 Pro x64 (was previously on Windows 7 Ultimate x64).

EDIT: The latest snapshot fixed my problem.

**Comment by BananasGoMoo** [comment]
Started happening again after restart. I can connect maybe once a day to a server. The rest of the time it just hangs on connect.

**Comment by BananasGoMoo** [comment]
Fixed: It turns out that a modification I did to Windows Explorer was causing the problem. When I disabled it, everything works.

**Comment by JoelTroch** [comment]
@BananasGoMoo I think it would be nice to tell which option in Windows Explorer caused this issue in case other people have it and that you close this issue itself ^^

**Comment by BananasGoMoo** [comment]
Its not an option in Windows Explorer. It's a modification called "OldNewExplorer" Which modifies Windows Explorer.
