### ISSUE TITLE
Remove "Welcome to Mumble" print on launch

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#1776]
The first thing printed into the chat log when launching Mumble is "Welcome to Mumble". There is no need for this "MOTD" of sorts. I know I'm in Mumble, I just launched the thing. When freshly connecting to a server, it just serves as extra spam.

**Comment by funkydude** [comment]
Removal of line 398 in main.cpp seems to be the solution to this?

**Comment by Eriner** [comment]
This is a non-issue. You should close this issue.

**Comment by funkydude** [comment]
I respectfully disagree

**Comment by nshopik** [comment]
isn't that same as #1781? if so that was fixed in 2612b67de1603aca32d0fc047997a62273aa94be

**Comment by funkydude** [comment]
No, it isn't the same. I said when launching the client, not when connecting to a server.

**Comment by aschereT** [comment]
I'm thinking of tackling this. I've added a checkbox to the Settings screen:
![screenshot_20180621_182649](https://user-images.githubusercontent.com/12742227/41753209-cdbc06f8-7580-11e8-999a-f26fc333490f.png)
But I'm not sure how to invoke isChecked() from main, nor to save the state of the checkbox to configurations (or loading it).

Sorry if my questions are noobish!

**Comment by davidebeatrici** [comment]
Load:
https://github.com/mumble-voip/mumble/blob/6195761d290fd3ba4296215e525da8008ddf86d2/src/mumble/Settings.cpp#L588

Save:
https://github.com/mumble-voip/mumble/blob/6195761d290fd3ba4296215e525da8008ddf86d2/src/mumble/Settings.cpp#L921

**Comment by Krzmbrzl** [comment]
I consider making this a checkox is an overkill. We should either decide to remove it or leave it. I don't think a setting is necessary...

In my opinion having this message doesn't hurt though and if you don't read it, then so be it. There might be users though that think it is a nice gesture.

I'll close this issue for now. If there's more to be debated about this, please let me know and I'll re-open it
