### ISSUE TITLE
[Windows 10] No notifications in "Notifications Center"

### ISSUE THREAD

**Issue by JoelTroch** [mumble-voip/mumble#1777]
OS: Windows 10 Pro x64 (final release with all the updates).
Mumble version: Snapshot 1.3.0~704~g6fe5547.

When there is an "event" in Mumble (someone connecting, someone being kicked, someone joining your channel...), there will be no notifications in the "Notifications Center" even if in Mumble's settings they are set to display them.

I didn't had that issue with "Technical Preview"/"Insider Preview" versions of Windows 10.

Things I tried and it didn't worked:
* Add a registry key in ```HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Current\Microsoft.Explorer.Notification.{6FECDCF1-3D54-462A-AE56-6698CA5A0733}``` (```{6FECDCF1-3D54-462A-AE56-6698CA5A0733}``` being Mumble's GUID) and reboot.
* Run as administrator.

Something worth a note: if you open Windows 10's "Parameters" app, go to the "System" category and the "Notifications and actions" sub-category, Mumble is not present in that list (see the following screenshot):
![mumble](https://cloud.githubusercontent.com/assets/4483707/9062740/8dc71438-3ac4-11e5-947e-037a43cf4166.png)

UPDATE: The following are random thoughts that need to be investigated and may be wrong:
* Qt's support for Windows 10 isn't complete yet so Mumble isn't the only application affected?
* An upgrade to Windows 10 SDK and/or Visual Studio 2015 is (are) required?
* Manifest need tweaking?

**Comment by falkreon** [comment]
Can confirm in Windows 10 Home x64 and Mumble 1.2.10, just to expand the net a bit. I can't find any issues in the Qt project tracker, but it's still pretty early, they might not have caught it yet.

**Comment by mkrautz** [comment]
We use Win32 notifications.  Maybe that's it? Only modern-style notifications work?

It worked in TP though?

**Comment by JoelTroch** [comment]
@mkrautz It worked in TP. I don't think it's related to Win32 notifications because the "Qt system tray" example in Qt 5.5.0 works fine.
![mumble](https://cloud.githubusercontent.com/assets/4483707/9109445/08405626-3c36-11e5-8644-4706b77aa75b.png)
Funny thing is that "systray.exe" (the Qt example below) was automatically added to the "allowed applications to display notifications", so I suspect it's because Mumble is NOT on that list that notifications aren't displayed. Theorically, we find the way to add Mumble to that list, notifications should work again.

**Comment by mkrautz** [comment]
We patch Qt to disable queueing of notifications behind fullscreen windows... Mayer that's to blame...

**Comment by mkrautz** [comment]
https://github.com/mumble-voip/mumble-releng/blob/master/buildenv/1.3.x/win32-static/patches/qt5-add-realtime-flag-for-systray-messages.patch

**Comment by mkrautz** [comment]
I'd guess that's probably it, actually...

Since it's realtime, it make sense not to show it in the notification center...

**Comment by GriefSeeds** [comment]
Hey guys, I got the newest snapshot of mumble (1.3.0.713) and it still doesn't show up in the notifications center. Any other possibilities?

**Comment by JoelTroch** [comment]
I think upgrading Mumble to Qt 5.5 will fix this issue, Mumble is actually using Qt 5.4.2 (which is released a month before Win10 was released to the public).

But I think that upgrading Qt results in more bugs to fix?

**Comment by Flyflo** [comment]
FYI the Windows 10 Fall Update fixed the problem for me.

**Comment by mkrautz** [comment]
That was also the response we got from people when this first showed up. Insider builds were not affected.

If this is still a problem for some, please re-open!

**Comment by CWTagpro** [comment]
Oh awesome!
