### ISSUE TITLE
if ((! supw.isEmpty()) && supw.isEmpty())   qFatal("Superuser password can not be empty");

### ISSUE THREAD

**Issue by 9x6** [mumble-voip/mumble#1778]
src/murmur/main.cpp line 408-413:
```cpp
if (! supw.isEmpty()) {
    if (supw.isEmpty())
        qFatal("Superuser password can not be empty");
    ServerDB::setSUPW(sunum, supw);
    qFatal("Superuser password set on server %d", sunum);
}
```

I don't know what you meant to do here but
````
qFatal("Superuser password can not be empty");
````
is most likely never executed.

Maybe you meant
````cpp
if (! supw.isEmpty()) {
    ServerDB::setSUPW(sunum, supw);
    qFatal("Superuser password set on server %d", sunum);
}
else
    qFatal("Superuser password can not be empty");
````

**Comment by hacst** [comment]
Thanks a lot for reporting this. Seems like the original intent was to check if anything had been assigned to the string which is done with ```!supw.isNull()```. Luckily this only resulted in the request to set the password being ignored instead of actually setting an empty password. Should be fixed now.
