### ISSUE TITLE
IP address leak

### ISSUE THREAD

**Issue by simonsmiley** [mumble-voip/mumble#1780]
I don't understand how the "information" (connection information, ...) are shown or hidden.
Using my own server, a client that is not registered but in any subchannel from root can see all the information including the ip address of other clients connected. 
I know the documentation mentions "obfuscate" but I do want the logs and admins being able to see everything. What am I doing wrong or is this a bug?

**Comment by mkrautz** [comment]
You should only be able to see IP addresses ud you're an admin (you have the 'write' permission)

**Comment by trustable-code** [comment]
I think that the client IP address should now be shown to normal users, because some users don't want to reveal they IP address. The informations should be available for admins only.

How is the permission 'write' called in the GUI? Is it 'Make channel'?

**Comment by mkrautz** [comment]
It's called "Write".

**Comment by mkrautz** [comment]
And it is only available to admins (people with the write permission), unless there's a bug somewhere.

**Comment by trustable-code** [comment]
@mkrautz, please explain how where this permission comes from or how I can disable it. 
On my Mumble server, every registered user can see other users' IP addresses.
This is not good.

**Comment by mkrautz** [comment]
The permission is called "Write". By default, only people in the admin group will have the Write permission.

It seems like Write is allowed for the "auth" (registered users) group on your server or channel tree. Perhaps a channel has that configured, and other channels inherit it.

**Comment by trustable-code** [comment]
In the list of permissions I don't have "Write". Is it "Write ACL"?

**Comment by trustable-code** [comment]
According to my test, the permission "Register User" is used to allow/disallow viewing the IP address.

**Comment by mkrautz** [comment]
Ah, you're right. The "write" ACL is more of a catch-all. The register permission is what gives access to the extended user list.
