### ISSUE TITLE
Finish implementation of registerLocation

### ISSUE THREAD

**Issue by klausenbusk** [mumble-voip/mumble#1784]
At the moment is not implemented on the master server.

Use-case: Server hosted in France, users is in Denmark.

I also proposal the following change.
If either 2 of this is true, the location change should be allowed:
* `registerHostname` country code match `registerLocation`.
* The certificate is verified and country match `registerLocation`

**Comment by hacst** [comment]
Looking at the handler script it will only match uppercase country codes. I adjusted the error message accordingly (it being perl I don't trust myself making it convert it to uppercase right now ;) ).

Unfortunately unless I'm mistaken only the "check and store preference" part is implemented. The script generating the list does not make use of that information (yet).

**Comment by klausenbusk** [comment]
Any update on this?

**Comment by hacst** [comment]
Iirc I have an implementation but wasn't sure how to test it properly. I'm not that familiar with development and testing in Perl. I'll try to take another look this weekend. Sorry for letting this linger so long.

**Comment by klausenbusk** [comment]
@hacst Any update? :)

**Comment by hacst** [comment]
The code is still pending internal review. Not feeling comfortable pushing that out without someone else taking a good look first. As I mentioned Perl isn't exactly my forte. Will update this issue once I've got something new.

**Comment by hacst** [comment]
Ok. The new code is deployed. registerLocation should now either accept your valid certificate location or alternatively the location matching your host names TLD. Could you please try it an report back (ideally with your server data if it doesn't work). Thanks.

**Comment by klausenbusk** [comment]
Just removed my home generated certificates, as I have been getting `Registration failed: SSL handshake failed` (not sure why) for some time now.
Now the log says `Registration: New registration successfull [Location set to DK]`
But can't find the server on http://mumble.hive.no/list2.cgi .
```
registerName=FancyGaming.dk
registerPassword=<some-password>
registerUrl=http://fancygaming.dk
registerHostname=m.fancygaming.dk
registerLocation=dk
```

**Comment by hacst** [comment]
Did it show up? The edit is confusing me ;)

If not could you provide me with the registerName and registerHostname? Feel free to mail them to me at dd0t@users.sourceforge.net if you don't feel comfortable putting them in this issue.

**Comment by klausenbusk** [comment]
> Did it show up? The edit is confusing me ;)

I removed my self-signed certificate (then "SSL handshake failed" was gone). But it didn't show up (waited 5-10 min) and went to sleep. The next day it was in the list.
Maybe I was impatient :)

**Comment by hacst** [comment]
The public list is heavily cached for performance reasons. It can take 30 minutes or more for it to pick up changes.

Did you server appear in the region you set with registerLocation?

**Comment by klausenbusk** [comment]
> Did you server appear in the region you set with registerLocation?

Yes, working perfect.

I'm closing this issue. Thanks again!

**Comment by klausenbusk** [comment]
But not sure why I was getting "Registration failed: SSL handshake failed" with my self generated certificate, if I remember correct, it was working when I first switched.. Not sure through.. Hmm

**Comment by hacst** [comment]
Maybe the cert is no longer valid? Feel free to open a separate issue if you think there's a bug on our end.

**Comment by klausenbusk** [comment]
> Maybe the cert is no longer valid?

Just checked, you correct :)
