### ISSUE TITLE
UserListModel.cpp: if (index.row() < 0 && index.row() >= m_userList.size()) is never true

### ISSUE THREAD

**Issue by 9x6** [mumble-voip/mumble#1786]
In UserListModel.cpp line 97 tries to catch invalid input:
````c++
if (index.row() < 0 && index.row() >= m_userList.size())
    return QVariant();
````
m_userList.size() is always >= 0 because it is a QList. So it should probably be:
````c++
if (index.row() < 0 || index.row() >= m_userList.size()) {
    return QVariant();
}
````

**Comment by hacst** [comment]
Oops. Yeah. That definitely should've been a ```||``` there. Thanks for reporting.

**Comment by nxtreaming** [comment]
@9x6 :+1:
