### ISSUE TITLE
Problem with microphone config wizzard

### ISSUE THREAD

**Issue by JavierZenko** [mumble-voip/mumble#1789]
the audio wizard setup doesn't work properly. When I speak the sound bar decreases and when I shut up the sound bar increases. In this way following the instructions become impossible. 

Version 1.2.10
OS: Windows 7, Ubuntu 15.04, Linux Mint 17.2 all of them just out of the box. Same problem
Hardware: Lenovo B50-80 Laptop

By the way I also tried the version 1.2.4 in Ubuntu 14.04 in a PC and it worked just fine.

**Comment by JavierZenko** [comment]
Aparently the microphone is badly wired with the polarity inverted so it seems to be a hardware problem of the laptop. Feel free to close the Issue.

**Comment by davidebeatrici** [comment]
Does it happen with other programs, such as Sound Recorder in Windows?

**Comment by mkrautz** [comment]
@davidebeatrici He is running Linux.

Closing the issue as requested.
