### ISSUE TITLE
Mumble not picking up headset PTT

### ISSUE THREAD

**Issue by Veight** [mumble-voip/mumble#1793]
I know this is really a specific issue and it might be hard to replicate but figured i'd let you guys know. Currently on Windows 10 with both 1.3.0~704~g6fe5547 and 1.2.10. Logitech G930 Headset on drivers 1.00.358.  I made sure that my buttons work properly. (Bound to key and it works in everything else in Windows 10). It used to work fine when I was on Windows 7.

**Comment by Krzmbrzl** [comment]
What is a "headset PTT"? Are you using one of the G-buttons on your headsets as a PTT-key?

Is this still the case in the released version of Mumble 1.3?
