### ISSUE TITLE
Hearing other user's push-to-talk audio cue

### ISSUE THREAD

**Issue by evnhali** [mumble-voip/mumble#1794]
When another user has Push-to-Talk audio cues enabled on his client, I can hear them on my client. Not sure if relevant, but the affected user and I are on the same LAN.

**Comment by Krzmbrzl** [comment]
I assume that the user in question is outputting audio via regular speakers whose output will then be captured by the microphone and sent to you.

If this is not the case, please let me know and I'll re-open this issue
