### ISSUE TITLE
Starting Mumble twice clears all Whisper/Shout shortcuts

### ISSUE THREAD

**Issue by thommcgrath** [mumble-voip/mumble#1797]
All my clanmates report this same issue. Sometimes we notice our whisper shortcuts are missing. The pattern we've found is that if the mumble client is started twice - by accident, of course - they disappear completely.

We're setup so that our PTT keys talk to our immediate channel, and we have a Shout to talk to the root channel and subchannels. This allows us to setup two-team communication, so we can talk to either only our team or everybody. When even one person's shout breaks, it causes us gameplay headaches.

**Comment by jagodragon** [comment]
i've noticed that this seams to be a windows issue.. when you try to open the second client of mumble, windows tries to rewrite the configs since the existing ones are in use. 

can i ask why you need to have two clients running? do you have a bot system that uses the second client? if it is a bot system there are alternatives to the mumble client it's self that you can get on the wiki. there is even a headless client that you could point your bot at instead of the standard client.

**Comment by thommcgrath** [comment]
I have absolutely no reason to run it twice. But sometimes the launch is delayed by I/O or cpu load, so we try to launch the shortcut again. It's entirely user-fault, but should also be avoidable.

For example, I have the shortcut bound to my M1 key on my BlackWidow keyboard. I can press the button and if nothing happens, maybe Razer Synapse missed the press or who know what. So pressing again is a natural response. Or even under normal circumstances, the button could b pushed by a child or cat.

Could a mutex be employed to prevent the double-launch? Is there ever a use-case for multiple copies.

**Comment by thommcgrath** [comment]
Can I get a bump on this? It looks like there is already code to prevent multiple copies. However, that code isn't given a chance to trigger if the second copy is launched before the first is loaded. To be clear, I am not asking for multiple copies, and my shortcuts do not use the "-m" modifier to allow it.

If we can't fix the multiple copies issue, can we fix the settings nuking?

**Comment by mkrautz** [comment]
We should use a Windows mutex to ensure only a single client is able to start.

The current RPC-based method is evidently racy.

**Comment by mkrautz** [comment]
We should also fix the settings nuking issue.

**Comment by thommcgrath** [comment]
Thanks Mike. I'd love submit a pull request myself, but C++ is not very much not my specialty.

**Comment by mkrautz** [comment]
PR at https://github.com/mumble-voip/mumble/pull/2037
