### ISSUE TITLE
Ubuntu "taskbar" icon screwed in dev

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#1800]
Appears to be showing up on top of the menu bar in Ubuntu 14.04.3
![screenshot](http://abload.de/img/screenshotfrom2015-09ffri5.png)

**Comment by funkydude** [comment]
It's still showing over the full screen game "Terraria" as if it's part of the overlay, but I have the overlay disabled.

**Comment by hacst** [comment]
Looks like a Ubuntu bug to me.
