### ISSUE TITLE
VF0800 Mic not working in win 8.1 Pro

### ISSUE THREAD

**Issue by J-Fricke** [mumble-voip/mumble#1801]
So I have an F800 RealSense camera with built in microphone array. I was using this just fine with windows 7 + Mumble and then I upgraded to windows 8.1 Pro and now it simply does not work. 

I can get my Realtek line in mic to work fine.

Also the RealSense one works fine in Sounds, Sound Recorder, etc. so it's confirmed to be functional in win 8.1 Pro.

**Comment by mkrautz** [comment]
The best way to troubleshoot this is to upload a snippet of your Mumble log to a pastebin or gist.github.com.

1. Start Mumble
2. Open Settings
3. Check if the F800 RealSense is picked as the audio input device. If not, ensure it's selected. Click Apply.
4. Close Mumble.
5. The log is found at %APPDATA%\Mumble\Console.txt. Open it and copy the log for the session you just had into your clipboard, and paste it into a pastebin. Link it here.

Feel free to censor the log before pasting it, if there is something in it you don't want to share publicly.

Thanks!

**Comment by J-Fricke** [comment]
This is what I got: https://gist.github.com/J-Fricke/1d0c5e8c36d7b4c1fb00
