### ISSUE TITLE
Mouse cursor reset at center of the screen

### ISSUE THREAD

**Issue by Skefrep** [mumble-voip/mumble#1803]
When I launch mumble, my mouse cursor keeps being reset to the center of the screen.
- OS: Windows 10 (x64)
- Overlay: Disabled
- Mumble version: 1.2.4/1.2.9/1.2.10/1.3.0~704~g6fe5547~snapshot
- Happens in-game and out of game
- Connected to a server or not.

**Comment by Krzmbrzl** [comment]
I don't have this in the released version of Mumble 1.3
Do you?
