### ISSUE TITLE
Freeze Upon Unmute/Undeafen

### ISSUE THREAD

**Issue by weaponizedketchup** [mumble-voip/mumble#1808]
Apparently the last time I logged off of Mumble I was muted and deafened. Now when I log into mumble, I can see everything just fine, move between channels just fine, but if I try to unmute or undeafen, it instantly and permanently freezes.

**Comment by byteturtle** [comment]
I get this too, i'm on Mumble 1.2.4-0.2ubuntu1.1 on Ubuntu 14.04 x64.

**Comment by nilsding** [comment]
What sound system are you using?  I experienced this problem on Linux with PulseAudio enabled.  Whenever PulseAudio forgot about my devices, I had to change the audio settings in Mumble to pick up the correct devices again.

I'm currently on FreeBSD 10.2 with OSS and I've never experienced this problem on on platform yet.

**Comment by byteturtle** [comment]
In my case using the snapshot PPA helped fixing this.

sudo add-apt-repository ppa:mumble/snapshot
sudo apt-get update
sudo apt-get dist-upgrade

**Comment by Krzmbrzl** [comment]
Then I assume this to be fixed in 1.3 as I never encountered that issue there
