### ISSUE TITLE
Audiowizard freeze 

### ISSUE THREAD

**Issue by fulup-bzh** [mumble-voip/mumble#1819]
When changing headphone model under pulse, Mumble freeze on audio-wizard. The only solution is to delete ~/.config/Mumble/Mumble.conf Look like Mumble tries forever to open the old headset.

Bug does not look new as something equivalent was already described in 2008 at https://sourceforge.net/p/mumble/bugs/587/

**Comment by mkrautz** [comment]
I don't know enough of Pulse to fix this at present.  But if no-one else gets to this, I'll get to it eventually.

If someone can chime in with a simple patch that simply checks the availability of a device before opening it, that'd be neat.

Thanks.

**Comment by gsauthof** [comment]
Actually, you don't have to delete the complete configuration file to work around this issue. It is sufficient to delete the `[pulseaudio]` and `[audio]` sections in the `~/.config/Mumble/Mumble.conf` configuration file.

Tested it on Fedora 25/mumble 1.2.11. Probably one just needs to remove the `[pulseaudio]` section.

Btw, with pulseaudio, I can also reproduce this issue when I explicitly select the new currently connected headset in the first step of the wizard (in contrast to just selecting the 'default'). I don't see why the wizard then even tries to open the old device.

The corresponding ubuntu bug report: https://bugs.launchpad.net/fedora/+source/mumble/+bug/1268419

**Comment by mkrautz** [comment]
This bug should be fixed in more recent 1.2.x builds.

**Comment by mkrautz** [comment]
Fixed via https://github.com/mumble-voip/mumble/commit/6d671c6a23a305dad7818ce70f3d603ada915316.
