### ISSUE TITLE
Placeholder texts shouldn't word wrap

### ISSUE THREAD

**Issue by gyvess** [mumble-voip/mumble#1823]
**1.  Checkbox option to remove/disable "Type message to channel '%channelname%' here" string.**
*The combination of a stacked Mumble client with a small width and long channel name can cause a minor annoyance.  The text box is expanded horizontally to accommodate the entirety of the "type message" string.  When you select the text box, the "type message" string disappears causing the box to shrink once again.  Afterward, deslecting the text box makes it expand again and the chat box will automatically scroll a little bit.

The above option would avoid this annoyance.
![](http://img.ctrlv.in/img/15/09/23/5603249f0d41a.png) ![](http://img.ctrlv.in/img/15/09/23/560324a63db6c.png) ![](http://img.ctrlv.in/img/15/09/23/560324b781ddf.png)

**2.  Input box behavior should mimic "Send Message" option.**
*Right now, entering HTML into the formal input box only outputs the equivalent of source text.  Allowing the same behavior would be a much shorter process for chat when compared to the right click channel, select "Send Message", enter and format text, and click OK process that is required now.

**Comment by ZeroAbility** [comment]
Was this UI sizing issue ever fixed?

**Comment by Krzmbrzl** [comment]
2) Is no longer valid as the default message box now uses Markdown syntax

1) is still present though
