### ISSUE TITLE
UI allows any mouse button for interaction

### ISSUE THREAD

**Issue by gibbed** [mumble-voip/mumble#1827]
Mumble allows any mouse button to do things such as drag & drop items, and click on UI elements (including double-clicking). This appears to affect all windows and dialogs, though it's only a real problem on the main window.

I sometimes use Push-to-Talk with a shortcut bound to either M:Button 3 or M:Button 5 without the the Suppress option enabled (as I also use those shortcuts for Push-to-Talk in say, OBS). If I am currently using PTT and tab into the Mumble window, it is very likely that Mumble will start treating the mouse input as a click&drag option in inadvertently doing things I didn't intend to (such as moving a user to another channel).

Tested with 1.3.0~713~g4d2d72e~snapshot on Windows 8.1.

**Comment by mkrautz** [comment]
Just curious: what mouse, and do your have vendor drivers installed for it?

**Comment by gibbed** [comment]
I'm using a Logitech G502, with Logitech Gaming Software installed.

**Comment by Tarun80** [comment]
@gibbed - What version of LGS are you using? Also, is the Mumble profile (Why is there even a Mumble profile in the Logitech Gaming Software... I do not know.) perhaps contributing to this?

**Comment by gibbed** [comment]
LGS version 8.55.137, firmware for the mouse is 88.2.16 (latest). Not actively using software profiles, only on-board profiles (though switching to software profiles doesn't help).

**Comment by Tarun80** [comment]
Doubt it's related, but it could be. Try updating your LGS software to the latest (8.74.80) as of this post.

I say this because I had an issue where I couldn't use some buttons on my mouse with Mumble due to LGS.

**Comment by gibbed** [comment]
No change after upgrading.

**Comment by tjhorner** [comment]
Can repro, MOUSE4 and MOUSE3 trigger UI.

**Comment by ZeroAbility** [comment]
Is this still an issue in 1.4?

**Comment by Hartmnt** [comment]
I can use Mouse3, Mouse4, and Mouse5 to drag channels and users in the tree with 1.5 RC, so yes.

**Comment by ZeroAbility** [comment]
> I can use Mouse3, Mouse4, and Mouse5 to drag channels and users in the tree with 1.5 RC, so yes.

What software are you using for the mouse?

**Comment by Krzmbrzl** [comment]
It may be argues though that this is likely a Qt thing as I don't recall any code where we would set this kind of behavior. Does it also happen with other Qt applications or only Mumble?

**Comment by Hartmnt** [comment]
> What software are you using for the mouse?

Nothing specific. Whatever the Linux kernel is providing...



> Does it also happen with other Qt applications or only Mumble?

Yup, tested it with the VLC player playlist. This is probably an upstream thing.



> I don't recall any code where we would set this kind of behavior

We could investigate, if it is possible to _prevent_ this presumed Qt default behavior.

**Comment by Krzmbrzl** [comment]
> Yup, tested it with the VLC player playlist. This is probably an upstream thing.

Thanks for testing :+1: 
If this i Qt behavior, then we can close this issue. Any report about this should go to Qt and trying to work around that on our end is needless work with little chance of proper, long term success.
