### ISSUE TITLE
Show channel when filtering

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#1830]
The automatic channel filter in 1.3 is great, but there is one drawback: You can hide a channel when filtering, but you can't always show a channel when filtering.

Use case: We have a support channel on our server where the admins can move people to, but the channel is usually empty. When you have the filter active you can't see this channel. It would be nice if you could "pin" this channel to be always visible.

**Comment by Xylemon** [comment]
+1

**Comment by hacst** [comment]
I think I have most of the implementation together but other shiny things took away my attention. Will see if I can get it to a PR ready state this weekend if nothing more pressing comes up.
