### ISSUE TITLE
Allow multiple login with the same certificate, but several different devices / resources

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#1832]
Currently if you want to be logged in to the same server several times with different devices, you have to have different certificates and usernames for all of the devices.

This leads to people having user names like "Promi-Kitchen", "Promi-LivingRoom", "Promi-Mobile", etc.

I don't think that this solution is optimal, because it adds registration overhead and the "friend" function also doesn't work where the same person has multiple certs.

I propose a solution like XMPP resources. Let users login with the same certificate multiple times as long as they send a unique resource name on every login.

For example in XMPP I am allowed to have (all logged in at the same time):
- promi@myserver/Kitchen
- promi@myserver/LivingRoom
- promi@myserver/Mobile

http://wiki.xmpp.org/web/Jabber_Resources

**Comment by mkrautz** [comment]
I agree, we need a better way to handle people that use multiple devices.

**Comment by Krzmbrzl** [comment]
We'll track this in #6065
