### ISSUE TITLE
Issue on olinuxino

### ISSUE THREAD

**Issue by otyugh** [mumble-voip/mumble#1834]
Hey there,
I'm trying to use the mumble client on a olinuxino-A20-micro (arm device), everything run smoothly but the fact that input or output sound just does not work and a big spam of
 "

warning: Unknown speex_preprocess_ctl request:  26
warning: Unknown speex_preprocess_ctl request:  35
warning: Unknown speex_preprocess_ctl request:  26
warning: Unknown speex_preprocess_ctl request:  35
warning: Unknown speex_preprocess_ctl request:  26
warning: Unknown speex_preprocess_ctl request:  35
warning: Unknown speex_preprocess_ctl request:  26
warning: Unknown speex_preprocess_ctl request:  35
warning: Unknown speex_preprocess_ctl request:  26
warning: Unknown speex_preprocess_ctl request:  35
warning: Unknown speex_preprocess_ctl request:  26
warning: Unknown speex_preprocess_ctl request:  35
warning: Unknown speex_preprocess_ctl request:  26
"
happens while running.

Is there a way to fix this or a workaround ? Or is there a kernel module to install ? I'm using debian.

**Comment by otyugh** [comment]
I may add that audacity input/output works great. I'm also using pulseaudio, but had similar issues using directly alsa.

**Comment by mkrautz** [comment]
Your libspeex or libspeexdsp libraries are built with fixed point instead of floating point.

Did you build Mumble yourself? If so, you should build with CONFIG+="bundled-speex" to use the bundled libspeex instead of your distro's version.

**Comment by mkrautz** [comment]
Fixed by rebuilding Mumble from source with the given config option:

    22:26 < gryf> mkrautz: It works ! Thanks you very much for the help !!
    22:28 <@mkrautz> gryf: excellent.

**Comment by Chris2000SP** [comment]
Thx for this. That helped me on the Raspberry Pi 400 with Raspbian.

I Created a issue here:
https://salsa.debian.org/salsa/support/-/issues/262
