### ISSUE TITLE
Mumble hangs on linux mint (ubuntu) when connecting to a server

### ISSUE THREAD

**Issue by jar349** [mumble-voip/mumble#1837]
Linux Mint 17.2 Cinnamon Desktop
Package: mumble 1.2.10-1~ppa3-trusty1 (from the mumble PPA)

All goes well until you attempt to connect to a server, whereupon the application hangs forever.  One can move the mumble window about, but no other UI elements are responsive.  Eventually, the application must be killed.

Here's the console log:

```
jar349@themachine ~ $ mumble
G15LCDEngineUnix: Unable to connect to G15Daemon.
CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
CELT bitstream 80000010 from /usr/lib/mumble/libcelt0.so.0.11.0
Locale is "en_US" (System: "en_US")
Database SQLite: "3.8.2" 
Overlay: Removing old socket on "/home/jar349/.MumbleOverlayPipe" 
Overlay: Listening on "/home/jar349/.MumbleOverlayPipe" 
GlobalShortcutX: Using XI2 2.0
"sni-qt/20426" WARN  21:43:31.763 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
SocketRPC: Removing old socket on "/home/jar349/.MumbleSocket" 
AudioInput: 40000 bits/s, 48000 hz, 480 sample
PulseAudio: Starting input alsa_input.usb-Logitech_Logitech_USB_Headset-00-Headset.analog-mono
PulseAudio: Starting output: alsa_output.usb-Logitech_Logitech_USB_Headset-00-Headset.analog-stereo
PulseAudio: Stream error: No such entity
PulseAudio: Stream error: No such entity
OpenSSL Support: 1 (OpenSSL 1.0.1f 6 Jan 2014)
ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
^C
jar349@themachine ~ $
```

One thing worth noting is the PulseAudio log entry that talks about a Logitech usb headset?  There's no such device connected to the laptop.  There used to be, long ago.  Here's what PulseAudio reports is on the laptop:

```
jar349@themachine ~ $ pactl list | grep -A2 'Source' | grep 'Name: '
    Name: alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor
    Name: alsa_input.usb-046d_HD_Pro_Webcam_C920_5311BA9F-02-C920.analog-stereo
    Name: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
    Name: alsa_input.pci-0000_00_1b.0.analog-stereo
```

**Comment by Querschlag** [comment]
Thanks for pointing that out. Had the same problem on Arch and reverting bck to default input fixed the issue for me.

**Comment by jar349** [comment]
I completely uninstalled (purged) and re-installed and it correctly detected the new set of audio devices available and worked correctly thereafter.  So the dev team may want to investigate what's causing the hang in such cases.

**Comment by jar349** [comment]
This happened to me again when my headset hardware changed.  I discovered that you can just delete the lines referencing the headset hardware in `~/.config/Mumble/Mumble.conf`.

**Comment by mkrautz** [comment]
This was fixed in 1.3.x some time ago:

**Comment by jar349** [comment]
Apologies: The 1.3.x line isn't yet available on ubuntu: https://launchpad.net/~mumble/+archive/ubuntu/release.  So I didn't know.  Please feel free to close this issue.

**Comment by mkrautz** [comment]
No need to apologize! 1.3.0 has not yet been released.

I simply wanted to add a note for myself to get the patch into the next 1.2.x point release!

**Comment by DavidVentura** [comment]
This is still affecting `1.2.12-1ubuntu1`

**Comment by mkrautz** [comment]
We have backported this to our stable 1.2.x branch and cut a release that includes the fix.

Please ask Ubuntu to include the patch in their package. We don't package Mumble for Ubuntu ourselves, so there isn't much we can do, sorry!

**Comment by mkrautz** [comment]
Alternatively, you can used our updated PPA repo, which includes the fixes:
https://launchpad.net/~mumble/+archive/ubuntu/release
