### ISSUE TITLE
CTRL+Enter to send direct chat messages

### ISSUE THREAD

**Issue by TheRadialActive** [mumble-voip/mumble#1839]
In any good mailprogram you have the key shortcut CTRL (or sometimes SHIFT) and Enter to send a message (on Github, too). I would like to see that in Mumble. In both chat inputs: direct chat message to a user/channel.

**Comment by bendem** [comment]
<kbd>ctrl+enter</kbd> already sends the message (same as <kbd>enter</kbd>). <kbd>shift+enter</kbd> allows you to insert a new line instead of sending the message.

**Comment by TheRadialActive** [comment]
I checked again. Yes, in the main chat frame, I can send it with the shortcut. But when I want to send something directly to another user or channel (through a new small chat window open [when I double click on a user/channel]), then it doesn't send the message.

**Comment by bendem** [comment]
Ah, I see what you mean now.

**Comment by Krzmbrzl** [comment]
I assume this to be fixed in #3465 as this will basically turn these kind of chats into "normal" chats as well and thus I suspect that it will behave like it as well.

**Comment by Hartmnt** [comment]
If I press ``CTRL+Enter`` in the ``Send Message`` dialog (as in the window that pops up), the direct message to the user/channel is sent.

That suggests to me that this issue has been fixed at some point. Or am I missing something?
