### ISSUE TITLE
Compile static murmur 1.2.10

### ISSUE THREAD

**Issue by lexesv** [mumble-voip/mumble#1846]
OS Debian 6 32 bit
Ice-3.3.1 with static libraries, like libIce.a libIceUtil.a
QT 4.6.3 with static libraries, like libQtDbus.a, libQtCore.a 
gcc/g++ version 4.4.5

Build config:
qmake CONFIG+=no-client CONFIG+=static CONFIG+=no-bonjour -recursive main.pro

> /usr/lib/libQtCore.a(qeventdispatcher_glib.o): In function `QEventDispatcherGlib::~QEventDispatcherGlib()':
> qeventdispatcher_glib.cpp:(.text+0x9b0): undefined reference to`g_source_destroy'
> qeventdispatcher_glib.cpp:(.text+0x9bb): undefined reference to `g_source_unref'
> qeventdispatcher_glib.cpp:(.text+0x9cd): undefined reference to`g_source_destroy'
> qeventdispatcher_glib.cpp:(.text+0x9d8): undefined reference to `g_source_unref'
> qeventdispatcher_glib.cpp:(.text+0xa21): undefined reference to`g_source_remove_poll'
> qeventdispatcher_glib.cpp:(.text+0xa5a): undefined reference to `g_source_destroy'
> qeventdispatcher_glib.cpp:(.text+0xa65): undefined reference to`g_source_unref'
> qeventdispatcher_glib.cpp:(.text+0xa77): undefined reference to `g_source_destroy'
> qeventdispatcher_glib.cpp:(.text+0xa82): undefined reference to`g_source_unref'
> qeventdispatcher_glib.cpp:(.text+0xa94): undefined reference to `g_main_context_unref'
> /usr/lib/libQtCore.a(qeventdispatcher_glib.o): In function`QEventDispatcherGlib::registerSocketNotifier(QSocketNotifier_)':
> qeventdispatcher_glib.cpp:(.text+0xbb1): undefined reference to `g_source_add_poll'
> /usr/lib/libQtCore.a(qeventdispatcher_glib.o): In function`QEventDispatcherGlib::unregisterSocketNotifier(QSocketNotifier_)':
> qeventdispatcher_glib.cpp:(.text+0xc58): undefined reference to `g_source_remove_poll'
> qeventdispatcher_glib.cpp:(.text+0xcac): undefined reference to`g_source_remove_poll'
> /usr/lib/libQtCore.a(qeventdispatcher_unix.o): In function `QEventDispatcherUNIX::unregisterSocketNotifier(QSocketNotifier*)':
> qeventdispatcher_unix.cpp:(.text+0x1da): undefined reference to`__fdelt_chk'
> qeventdispatcher_unix.cpp:(.text+0x209): undefined reference to `__fdelt_chk'
> /usr/lib/libQtCore.a(qeventdispatcher_unix.o): In function`QEventDispatcherUNIX::setSocketNotifierPending(QSocketNotifier_)':
> qeventdispatcher_unix.cpp:(.text+0x106f): undefined reference to `__fdelt_chk'
> qeventdispatcher_unix.cpp:(.text+0x10c9): undefined reference to`__fdelt_chk'
> /usr/lib/libQtCore.a(qeventdispatcher_unix.o): In function `QEventDispatcherUNIX::registerSocketNotifier(QSocketNotifier_)':
> qeventdispatcher_unix.cpp:(.text+0x131c): undefined reference to `__fdelt_chk'
> /usr/lib/libQtCore.a(qeventdispatcher_unix.o):qeventdispatcher_unix.cpp:(.text+0x1b3f): more undefined references to`__fdelt_chk' follow
> /usr/lib/libc.a(assert.o): In function `__assert_fail':
> (.text+0x2): undefined reference to`pthread_setcancelstate'
> /usr/lib/libc.a(assert.o): In function `__assert_fail':
> (.text+0x25): undefined reference to`pthread_setcancelstate'
> collect2: ld returned 1 exit status
> make[2]: **\* [../../release/murmurd] Error 1
> make[2]: Leaving directory `/home/build/mumble-1.2.10/src/murmur'
> make[1]: *** [release] Error 2
> make[1]: Leaving directory`/home/build/mumble-1.2.10/src/murmur'
> make: **\* [sub-src-murmur-make_default-ordered] Error 2

How to solve the problem?
Please help.

**Comment by mkrautz** [comment]
Can you give some more information on what you're trying to achieve?

Our "static" builds distributed on the front page of the wiki aren't really static, but they're wrapped with Magic Ermine. You can see how we build the environment at:

https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.2.x/centos-ermine

And this is how the build is packaged in the end:
https://github.com/mumble-voip/mumble-releng/blob/master/buildscripts/1.2.x/murmur-centos-ermine.bash

Anyway. It seems like you're trying to build a fully static binary. This is not a setup we truly support, but we can try to help you out.

First of all, it seems like your glib library is dynamic, and not static. So you'll have to acquire a static version somehow. It seems to me that glib might be pulled in silently by Qt's glib event dispatcher. So you may have to add the -lglib entry yourself.

I am unsure why you are getting the __fdelt_chk errors. Presumably, your static libc would have that defined?

Did you build your static Qt yourself? Or was it provided by your distro? Is it built against the same glibc that your system uses? If not, that might be why you get the __fdelt_chk errors. (And __assert_fail as well?).

**Comment by lexesv** [comment]
Thanks for your reply!

I apologize in advance for my bad English. I'm from Ukraine.

>Can you give some more information on what you're trying to achieve?

I'm trying to build a static server Murmur with a value larger than 1024 file descriptors (need to open > 8000 descriptors and 1000 threads). 
And my employers require that the server Murmur run on different operating systems Linux,  without additional settings and install packages.


>Did you build your static Qt yourself?

Yes. 
QT 4.6.3
./configure -opensource -static -fast -no-accessibility -no-opengl -nomake examples -nomake demos -nomake docs -no-webkit -dbus -no-script -no-scripttools -no-phonon 
In the directory /usr/lib there are library:
libanl.a
libasound.a
libasprintf.a
libavahi-client.a
libavahi-common.a
libboost_python.a
libboost_python-mt-py25.a
libboost_python-mt-py26.a
libboost_python-py25.a
libboost_python-py26.a
libBrokenLocale.a
libbsd.a
libbsd-compat.a
libbz2.a
libc.a
libcelt0.a
libc_nonshared.a
libcrypt.a
libcrypto.a
libdb-4.8.a
libdb.a
libdb_cxx-4.8.a
libdb_cxx.a
libdbus-1.a
libdl.a
libdns_sd.a
libexpat.a
libexpatw.a
libffi.a
libffi_pic.a
libFLAC.a
libg15daemon_client.a
libg.a
libgettextpo.a
libgio-2.0.a
**libglib-2.0.a**
libGLU.a
libgmodule-2.0.a
libgmp.a
libgmpxx.a
libgobject-2.0.a
libgthread-2.0.a
libICE.a
libieee.a
libm.a
libmcheck.a
libmcpp.a
libmp.a
libnsl.a
libogg.a
libprotobuf.a
libprotobuf-lite.a
libpthread.a
libpthread_nonshared.a
libpython2.6.a
libQtCore.a
libQtDBus.a
libQtNetwork.a
libQtSql.a
libQtUiTools.a
libQtXml.a
libresolv.a
librpcsvc.a
librt.a
libSM.a
libsndfile.a
libspeechd.a
libspeex.a
libspeexdsp.a
libssl.a
libsupp.a
libutil.a
libvorbis.a
libvorbisenc.a
libvorbisfile.a
libX11.a
libXau.a
libxcb.a
libXdmcp.a
libXext.a
libXi.a
libXt.a
libz.a

Ice-3.3.1 
in /config/Make.rules (for cpp) 
I set the value of the variable STATICLIBS = yes
After compiling I get libIce.a and libIceUtil.a
/opt/Ice-3.3/lib# ls | grep ".*\.a$"
libIce.a
libIceUtil.a


With many thanks, Alex

**Comment by mkrautz** [comment]
Are you sure that the static binaries we ship don't work with > 1024 FDs?

If they don't, we consider that a bug, and we will fix that promptly.

Have you tried the "murmur-static" package? https://github.com/mumble-voip/mumble/releases/download/1.2.10/murmur-static_x86-1.2.10.tar.bz2

**Comment by mkrautz** [comment]
Though I do admit that it's an i386 binary, so you might run into issues there...

**Comment by lexesv** [comment]
>Are you sure that the static binaries we ship don't work with > 1024 FDs?

Yes, I am sure.

cat /etc/security/limits.conf
 \*       hard    nofile  8192
 \*       soft    nofile  8192
root       hard    nofile  8192
root       soft    nofile  8192

wget https://github.com/mumble-voip/mumble/releases/download/1.2.10/murmur-static_x86-1.2.10.tar.bz2

tar xf murmur-static_x86-1.2.10.tar.bz2

cd murmur-static_x86-1.2.10

./murmur.x86 -limits
<W>2015-10-17 07:27:04.321 Initializing settings from /home/test/murmur-static_x86-1.2.10/murmur.ini (basepath /home/test/murmur-static_x86-1.2.10)
<W>2015-10-17 07:27:04.325 Meta: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
<W>2015-10-17 07:27:04.325 OpenSSL: OpenSSL 1.0.1p 9 Jul 2015
<C>2015-10-17 07:27:04.325 WARNING: You are running murmurd as root, without setting a uname in the ini file. This might be a security risk.
<W>2015-10-17 07:27:04.325 Resource limits were 0 0
<W>2015-10-17 07:27:04.325 Successfully dropped capabilities
<W>2015-10-17 07:27:04.325 Running descriptor test.
<W>2015-10-17 07:27:04.325 0 descriptors...
<C>2015-10-17 07:27:04.336 Managed to open 1012 descriptors
<W>2015-10-17 07:27:04.338 0 threads...
<F>2015-10-17 07:27:04.390 Managed to spawn 126 threads

**Comment by lexesv** [comment]
I have installed environment by using this
https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.2.x/centos-ermine

But, as I understand it, compile standard methods is not possible.
Need to use a only the paid version ermine?

**Comment by mkrautz** [comment]
I just tested this, and it does work:

	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ulimit -n 4000
	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ./murmur.x86 -limits
	<W>2015-10-04 00:40:38.052 Initializing settings from /home/mkrautz/Downloads/murmur-static_x86-1.2.10/murmur.ini (basepath /home/mkrautz/Downloads/murmur-static_x86-1.2.10)
	<W>2015-10-04 00:40:38.054 Meta: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
	<W>2015-10-04 00:40:38.054 OpenSSL: OpenSSL 1.0.1p 9 Jul 2015
	<C>2015-10-04 00:40:38.054 Successfully switched to uid 116
	<W>2015-10-04 00:40:38.054 Resource limits were 0 0
	<W>2015-10-04 00:40:38.054 Successfully dropped capabilities
	<W>2015-10-04 00:40:38.055 Running descriptor test.
	<W>2015-10-04 00:40:38.055 0 descriptors...
	<W>2015-10-04 00:40:38.061 1024 descriptors...
	<W>2015-10-04 00:40:38.066 2048 descriptors...
	<W>2015-10-04 00:40:38.071 3072 descriptors...
	<C>2015-10-04 00:40:38.080 Managed to open 3989 descriptors
	<W>2015-10-04 00:40:38.080 0 threads...
	<F>2015-10-04 00:40:38.171 Managed to spawn 498 threads

...However, there is a bug somewhere. Once I go a bit over 4000 FDs, I get no output.

**Comment by mkrautz** [comment]
@lexesv Maybe the free version works, I actually don't know. We do use the paid version, which was provided to us for free from Magic Ermine because we're FOSS.

**Comment by mkrautz** [comment]
(Running it with ./murmur.x86 -v -fg -limits gives better results)

**Comment by mkrautz** [comment]
OK, it does work:

	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ulimit -n 8196
	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ulimit -s 256
	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ulimit -s 256^C
	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ./murmur.x86 -v -fg -limits
	<W>2015-10-04 01:07:27.763 Initializing settings from /home/mkrautz/Downloads/murmur-static_x86-1.2.10/murmur.ini (basepath /home/mkrautz/Downloads/murmur-static_x86-1.2.10)
	<W>2015-10-04 01:07:27.766 Meta: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
	<W>2015-10-04 01:07:27.766 OpenSSL: OpenSSL 1.0.1p 9 Jul 2015
	<C>2015-10-04 01:07:27.766 Successfully switched to uid 116
	<W>2015-10-04 01:07:27.766 Resource limits were 0 0
	<W>2015-10-04 01:07:27.766 Successfully dropped capabilities
	<W>2015-10-04 01:07:27.766 Running descriptor test.
	<W>2015-10-04 01:07:27.766 0 descriptors...
	<W>2015-10-04 01:07:27.772 1024 descriptors...
	<W>2015-10-04 01:07:27.777 2048 descriptors...
	<W>2015-10-04 01:07:27.782 3072 descriptors...
	<W>2015-10-04 01:07:27.788 4096 descriptors...
	<W>2015-10-04 01:07:27.793 5120 descriptors...
	<W>2015-10-04 01:07:27.799 6144 descriptors...
	<W>2015-10-04 01:07:27.805 7168 descriptors...
	murmur.x86: fd_meta_index_set: fd=8192 is not less then limit max_ifd=8192 or negative. Execution aborted.
	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ulimit -n 8190
	root@ubuntu:/home/mkrautz/Downloads/murmur-static_x86-1.2.10# ./murmur.x86 -v -fg -limits
	<W>2015-10-04 01:07:39.230 Initializing settings from /home/mkrautz/Downloads/murmur-static_x86-1.2.10/murmur.ini (basepath /home/mkrautz/Downloads/murmur-static_x86-1.2.10)
	<W>2015-10-04 01:07:39.231 Meta: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
	<W>2015-10-04 01:07:39.231 OpenSSL: OpenSSL 1.0.1p 9 Jul 2015
	<C>2015-10-04 01:07:39.231 Successfully switched to uid 116
	<W>2015-10-04 01:07:39.231 Resource limits were 0 0
	<W>2015-10-04 01:07:39.231 Successfully dropped capabilities
	<W>2015-10-04 01:07:39.231 Running descriptor test.
	<W>2015-10-04 01:07:39.231 0 descriptors...
	<W>2015-10-04 01:07:39.236 1024 descriptors...
	<W>2015-10-04 01:07:39.241 2048 descriptors...
	<W>2015-10-04 01:07:39.248 3072 descriptors...
	<W>2015-10-04 01:07:39.253 4096 descriptors...
	<W>2015-10-04 01:07:39.258 5120 descriptors...
	<W>2015-10-04 01:07:39.264 6144 descriptors...
	<W>2015-10-04 01:07:39.269 7168 descriptors...
	<C>2015-10-04 01:07:39.286 Managed to open 8179 descriptors
	<W>2015-10-04 01:07:39.287 0 threads...
	<W>2015-10-04 01:07:39.357 512 threads...
	<F>2015-10-04 01:07:39.506 Managed to spawn 1022 threads

(Note that our Ermine config the FD limit hardcoded to 8192, so that's why I use a number just below that).

But note that our static binaries are i386 only at the moment, so you might run into problems if you run with that many threads and sockets in production!

**Comment by lexesv** [comment]
Thank you very much for your help.
At me it turned to create a static build Murmur using statifier
>qmake CONFIG+=no-client -recursive main.pro
make
statifier -v murmurd murmur.x86

But when you run on a different computer error "segmentation fault".
This problem is solved with:
>echo -n 0 >| /proc/sys/kernel/randomize_va_space

Maybe there is another version of the solution, but has not yet found.

**Comment by mkrautz** [comment]
Closing in favour of #2751.
