### ISSUE TITLE
audio device output and input attribution issue 

### ISSUE THREAD

**Issue by alamata** [mumble-voip/mumble#1852]
Hey ,...

i work in Win 10 Pro 64 with Virtual Audio Cable and the mumble-1.3.0~733~g664d5bc~snapshot.winx64.msi

here is the situation :  when i put in mumble 

for the input : VAC 9  
for the output : VAC 10 

in  window only the VAC 10 in output and input  react

if i put in mumble 

for the input : VAC 10
for the output : VAC 9

in  window only the VAC 9 in output and input  react

ii cant have in windows input and output with different VAC
it s always the VAC who is indicate as output in mumble who react under windows as input or output

any ideas,...
....

**Comment by mkrautz** [comment]
Anything in the Mumble log at %APPDATA\Mumble\Console.txt?

**Comment by alamata** [comment]
hey ,...

thx in advance for your intervention,...

here the console?txt

""
<W>2015-10-19 12:06:41.901 DirectSound: Disabled as WASAPI is available
<W>2015-10-19 12:06:41.932 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<W>2015-10-19 12:06:41.935 CELT bitstream 8000000b from C:/Program Files (x86)/Mumble/Versions/1.3.0~733~g664d5bc~snapshot/celt0.0.7.0.dll
<W>2015-10-19 12:06:41.937 CELT bitstream 80000010 from C:/Program Files (x86)/Mumble/Versions/1.3.0~733~g664d5bc~snapshot/celt0.0.11.0.dll
<W>2015-10-19 12:06:41.938 Theme: "Mumble"
<W>2015-10-19 12:06:41.938 Style: "Lite"
<W>2015-10-19 12:06:41.938 --> qss: ":builtin/themes/Mumble/Lite.qss"
<W>2015-10-19 12:06:41.938 Locale is "fr_FR" (System: "fr_FR")
<W>2015-10-19 12:06:42.278 Database SQLite: "3.8.6"
<W>2015-10-19 12:06:42.344 Overlay: Listening on "\\.\pipe\MumbleOverlayPipe"
<W>2015-10-19 12:06:42.351 OverlayPrivateWin: overlay helper process 'C:\Program Files (x86)\Mumble\Versions\1.3.0~733~g664d5bc~snapshot/mumble_ol_helper.exe' started with PID 208.
<W>2015-10-19 12:06:42.353 OverlayPrivateWin: overlay helper process 'C:\Program Files (x86)\Mumble\Versions\1.3.0~733~g664d5bc~snapshot/mumble_ol_helper_x64.exe' started with PID 8892.
<W>2015-10-19 12:06:42.355 Updating application palette
<W>2015-10-19 12:06:42.568 AudioInput: 72000 bits/s, 48000 hz, 480 sample
<W>2015-10-19 12:06:42.572 WASAPIInput: Latencies 100000 100000 => 100000
<W>2015-10-19 12:06:42.584 OpenSSL Support: 1 (OpenSSL 1.0.1p 9 Jul 2015)
<W>2015-10-19 12:06:42.587 WASAPIOutput: Latencies 100000 100000 => 100000
<W>2015-10-19 12:06:42.593 SSL: CA certificate filter applied. Filtered size: 72, original size: 72
<W>2015-10-19 12:06:42.593 ServerHandler: TLS cipher preference is 
SHA:AES128-SHA"
<W>2015-10-19 12:06:42.595 ServerHandler: QOS2 loaded
<W>2015-10-19 12:06:42.600 WASAPIInput: Mic Stream format 1
<W>2015-10-19 12:06:42.600 WASAPIInput: Stream Latency 0 (970)
<W>2015-10-19 12:06:42.680 WASAPIOutput: Output stream format 1
<W>2015-10-19 12:06:42.680 WASAPIOutput: Stream Latency 0 (970)
<W>2015-10-19 12:06:42.680 WASAPIOutput: Periods 10000us 10000us (latency 0us)
<W>2015-10-19 12:06:42.680 WASAPIOutput: Buffer is 21995us (1)
<W>2015-10-19 12:06:42.681 WASAPIInput: Echo Stream format 1
<W>2015-10-19 12:06:42.681 AudioInput: Initialized mixer for 2 channel 44100 hz mic and 2 channel 44100 hz echo
<W>2015-10-19 12:06:42.681 AudioInput: ECHO CANCELLER ACTIVE
<W>2015-10-19 12:06:42.692 AudioOutput: Initialized 2 channel 44100 hz mixer
<W>2015-10-19 12:06:42.808 Connection: Failed to add flow to QOS
<W>2015-10-19 12:06:42.809 ServerHandler: Failed to add UDP to QOS
<W>2015-10-19 12:06:43.148 libpng warning: iCCP: known incorrect sRGB profile
<W>2015-10-19 12:06:44.711 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2015-10-19 12:06:44.712 GlobalShortcutWin: GKeys initialized, isValid: 0
<W>2015-10-19 12:06:44.795 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Souris Souris:3
<W>2015-10-19 12:06:44.796 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Clavier Clavier:109
<W>2015-10-19 12:06:44.798 Adding device {f521fd30-b0ed-11e3-8002-444553540000} Wireless KB/Touch Pad Wireless KB/Touch Pad:8
<W>2015-10-19 12:06:44.823 Adding device {c6ae1160-10e1-11e4-8006-444553540000} Transmetteur infrarouge Microsoft eHome Transmetteur infrarouge Microsoft eHome:573
<W>2015-10-19 12:06:44.844 Adding device {c6ae5f80-10e1-11e4-800a-444553540000} Transmetteur infrarouge Microsoft eHome Transmetteur infrarouge Microsoft eHome:256
""

**Comment by alamata** [comment]
here is a print screen  of the situation,....

![mumble issue](https://cloud.githubusercontent.com/assets/554318/10593513/b78e3b52-76c4-11e5-9672-1cebfd357411.jpg)


on this print screen you can see that i have several "salon" with specific output input system settings for each of them,...

but  here i have one " salon "  called "Tablet" with VAC 10  for output and VAC 9 for input but in windows i have only the VAC 10 who react as input or output ....

**Comment by alamata** [comment]
... What i'm doing wrong...?

...Anyone to resolve this situation...?

**Comment by mkrautz** [comment]
I can't see anything wrong with the log you posted, and I am not very familiar with Virtual Audio Cable.

Have you tried to disable Echo Cancellation? Just something to try.

If nothing else works, you could try to re-enable DirectSound support in Mumble.

You can do this by forcing the program to run in Windows XP compatibility mode.

**Comment by alamata** [comment]
hey,...

i have followed these instructions with no succes,... 
But
i m nearly sur that sorts of mumble's configurations are possible 
perhaps with win 8.1 or win 7 ,...

**Comment by alamata** [comment]
these configurations are working  on win 7 !!
apparently not with upper version of windows

can you tell me if
there are possibilities that situation will be resolved by further developpement .... 

thx for your comprehension,....

**Comment by Krzmbrzl** [comment]
Does this issue still exist in the released 1.3 version?
