### ISSUE TITLE
Mac OS 10.11: App Nap

### ISSUE THREAD

**Issue by DairyDTP** [mumble-voip/mumble#1863]
Having issues when Mumble goes into the background on El Capitan. This is both on 1.2.10 and 1.3.x

About 0.5s of audio get sent out repeatedly. I can hear the other side, but they only hear the same buffer over and over. 

Suspecting App Nap to be a possible culprit. Independently of my issue, consider disabling App Nap when a connection is active, as in El Capitan the checkbox on the Get Info pane in Finder is gone for users to easily disable it themselves.

**Comment by DairyDTP** [comment]
Confirmed to be an App Nap problem. Setting LSUIElement = true in Info.plist opts Mumble out of App Nap and the problem goes away. No feasible workaround though, as this key disables the Dock Icon as well.

**Comment by olzzon** [comment]
There´s still an issue when running multiple instances of Mumble on OSX Sierra.
It keeps toggling between AppNap On/off (Pics from Danish OSX ja=yes, nej=no) 
Causing multiple reconnections of all background Clients. (Kind of a AppNap background loop)

Workaround is to completely disable AppNap:
defaults write NSGlobalDomain NSAppSleepDisabled -bool YES
Enable again by deleting: defaults delete NSGlobalDomain NSAppSleepDisabled

<img width="298" alt="skaermbillede 2018-03-19 kl 10 20 51" src="https://user-images.githubusercontent.com/29782499/37587307-3ed94ac4-2b5f-11e8-99db-d296806a3e8d.png">
<img width="280" alt="skaermbillede 2018-03-19 kl 10 20 45" src="https://user-images.githubusercontent.com/29782499/37587308-3ef76bf8-2b5f-11e8-949e-2f76e91dcd7e.png">
