### ISSUE TITLE
[1.3.0] Can't compile 32-bit overlay library

### ISSUE THREAD

**Issue by Xylemon** [mumble-voip/mumble#1866]
Using the latest Git, I am unable to compile a 32-bit overlay library that compliments the 64-bit one. It fails with this error:

 gcc -c -m32 -O2 -march=i486 -mtune=i686 -fvisibility=hidden -Wall -Wextra -Werror  -O2 -Wall -W -fPIC -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DTARGET_UNIX -I/usr/lib64/qt/mkspecs/linux-g++ -I. -o release/overlay.o overlay.c
overlay.c: In function 'drawOverlay':
overlay.c:348:5: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'ssize_t' [-Werror=format=]
     ods("Short overlay message read %x %ld/%d", ctx->omMsg.omh.uiType, length, ctx->omMsg.omh.iLength);
     ^
overlay.c:366:25: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         if (buf.st_size >= ctx->uiWidth * ctx->uiHeight * 4
                         ^
cc1: all warnings being treated as errors
make[1]: *** [release/overlay.o] Error 1
make[1]: Leaving directory `/tmp/SBo/mumble-1.3.0/overlay_gl'
make: *** [release] Error 2

Any ideas?

**Comment by mkrautz** [comment]
Try changing %ld to %zd.

**Comment by Xylemon** [comment]
Led to this compile error:

gcc -c -m32 -O2 -march=i486 -mtune=i686 -fvisibility=hidden -Wall -Wextra -Werror  -O2 -Wall -W -fPIC -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DTARGET_UNIX -I/usr/lib64/qt/mkspecs/linux-g++ -I. -o release/overlay.o overlay.c
overlay.c: In function 'drawOverlay':
overlay.c:366:25: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         if (buf.st_size >= ctx->uiWidth * ctx->uiHeight * 4
                         ^
cc1: all warnings being treated as errors
make[1]: *** [release/overlay.o] Error 1
make[1]: Leaving directory `/tmp/SBo/mumble-1.3.0/overlay_gl'
make: *** [release] Error 2

**Comment by mkrautz** [comment]
Could work if you replace buf.st_size with static_cast<unsigned int>(buf.st_size) in both parts of the if statement.

Not sure if there are other errors... In any case, I will take a look later.

**Comment by Xylemon** [comment]
I think that actually got it to compile however this happened after leaving the overlay_gl folder in the compile process:

                 from mumble_pch.hpp:56:
/usr/include/boost/type_traits/is_member_function_pointer.hpp: In instantiation of 'struct boost::is_member_function_pointer<long unsigned int>':
/usr/include/boost/type_traits/is_member_pointer.hpp:50:1:   required from 'struct boost::is_member_pointer<long unsigned int>'
/usr/include/boost/type_traits/is_pointer.hpp:61:5:   required from 'const bool boost::detail::is_pointer_impl<long unsigned int>::value'
/usr/include/boost/type_traits/is_pointer.hpp:73:1:   required from 'struct boost::is_pointer<long unsigned int>'
/usr/include/boost/type_traits/is_scalar.hpp:29:4:   required from 'const bool boost::detail::is_scalar_impl<long unsigned int>::value'
/usr/include/boost/type_traits/is_scalar.hpp:49:1:   required from 'struct boost::is_scalar<long unsigned int>'
/usr/include/boost/type_traits/is_pod.hpp:39:5:   [ skipping 12 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/iterator/iterator_adaptor.hpp:251:9:   required from 'class boost::iterators::iterator_adaptor<boost::iterators::counting_iterator<long unsigned int>, long unsigned int, long unsigned int, boost::iterators::random_access_traversal_tag, const long unsigned int&, long int>'
/usr/include/boost/iterator/counting_iterator.hpp:150:7:   required from 'class boost::iterators::counting_iterator<long unsigned int>'
/usr/include/c++/4.9.3/bits/stl_iterator_base_types.h:165:53:   required from 'struct std::iterator_traits<boost::iterators::counting_iterator<long unsigned int> >'
/usr/include/boost/iterator/transform_iterator.hpp:51:17:   required from 'struct boost::iterators::detail::transform_iterator_base<std::binder1st<std::multiplies<long unsigned int> >, boost::iterators::counting_iterator<long unsigned int>, boost::iterators::use_default, boost::iterators::use_default>'
/usr/include/boost/iterator/transform_iterator.hpp:75:9:   required from 'class boost::iterators::transform_iterator<std::binder1st<std::multiplies<long unsigned int> >, boost::iterators::counting_iterator<long unsigned int> >'
/usr/include/boost/accumulators/statistics/times2_iterator.hpp:30:62:   required from here
/usr/include/boost/type_traits/is_member_function_pointer.hpp:43:1: internal compiler error: Bus error
 BOOST_TT_AUX_BOOL_TRAIT_DEF1(
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [release/mumble.gch/c++] Error 1
make[2]: Leaving directory `/tmp/SBo/mumble-1.3.0/src/mumble'
make[1]: *** [release] Error 2
make[1]: Leaving directory `/tmp/SBo/mumble-1.3.0/src/mumble'
make: *** [sub-src-mumble-release_ordered] Error 2

I'm not really sure what information to give here.

**Comment by tjhorner** [comment]
@Xylemon

Here's a tip, to make those compile logs properly formatted, use do a ``` at the start of it and at the end.

```
             from mumble_pch.hpp:56:
/usr/include/boost/type_traits/is_member_function_pointer.hpp: In instantiation of 'struct boost::is_member_function_pointer':
/usr/include/boost/type_traits/is_member_pointer.hpp:50:1: required from 'struct boost::is_member_pointer'
/usr/include/boost/type_traits/is_pointer.hpp:61:5: required from 'const bool boost::detail::is_pointer_impl::value'
/usr/include/boost/type_traits/is_pointer.hpp:73:1: required from 'struct boost::is_pointer'
/usr/include/boost/type_traits/is_scalar.hpp:29:4: required from 'const bool boost::detail::is_scalar_impl::value'
/usr/include/boost/type_traits/is_scalar.hpp:49:1: required from 'struct boost::is_scalar'
/usr/include/boost/type_traits/is_pod.hpp:39:5: [ skipping 12 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/iterator/iterator_adaptor.hpp:251:9: required from 'class boost::iterators::iterator_adaptor, long unsigned int, long unsigned int, boost::iterators::random_access_traversal_tag, const long unsigned int&, long int>'
/usr/include/boost/iterator/counting_iterator.hpp:150:7: required from 'class boost::iterators::counting_iterator'
/usr/include/c++/4.9.3/bits/stl_iterator_base_types.h:165:53: required from 'struct std::iterator_traits >'
/usr/include/boost/iterator/transform_iterator.hpp:51:17: required from 'struct boost::iterators::detail::transform_iterator_base >, boost::iterators::counting_iterator, boost::iterators::use_default, boost::iterators::use_default>'
/usr/include/boost/iterator/transform_iterator.hpp:75:9: required from 'class boost::iterators::transform_iterator >, boost::iterators::counting_iterator >'
/usr/include/boost/accumulators/statistics/times2_iterator.hpp:30:62: required from here
/usr/include/boost/type_traits/is_member_function_pointer.hpp:43:1: internal compiler error: Bus error
BOOST_TT_AUX_BOOL_TRAIT_DEF1(
^
Please submit a full bug report,
with preprocessed source if appropriate.
See http://gcc.gnu.org/bugs.html for instructions.
make[2]: *** [release/mumble.gch/c++] Error 1
make[2]: Leaving directory /tmp/SBo/mumble-1.3.0/src/mumble' make[1]: *** [release] Error 2 make[1]: Leaving directory/tmp/SBo/mumble-1.3.0/src/mumble'
make: *** [sub-src-mumble-release_ordered] Error 2
```

See, that looks much better.

**Comment by Xylemon** [comment]
Tested the PR earlier and it worked and now it's committed so closing as a result.
