### ISSUE TITLE
[1.3.0] Feature Request: Always show channel

### ISSUE THREAD

**Issue by Xylemon** [mumble-voip/mumble#1867]
Can there be a filter option to always show certain channels? There's two on my server I would want to always be visible with the dynamic channel filter on, users in it or not.

**Comment by Brottweiler** [comment]
The other day I was going to suggest this feature myself, but I searched before I made an issue, and found https://github.com/mumble-voip/mumble/issues/1830

**Comment by Xylemon** [comment]
Ah I see, closing a dupe issue then.
