### ISSUE TITLE
Unable to alter Priority Speaker status in Temporary channels

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1877]
As the title says, I've found I am unable to alter Priority Speaker status - including on myself - in a temporary channel when I (server admin) am in the temporary channel.

Denied: Operation not permitted in temporary channel.

**Comment by bontibon** [comment]
It appears that muting and deafening someone while you are inside of a temporary channel are also disallowed. The commit that made this change was 52e27ef37f452e13e2ef15b2763942c8a8dfd54e by @pcgod. Its comment:

> Murmur: Disallow mute/deafen status changes in temporary channels

If no one can argue that this change was a good idea, it should probably be reverted.

**Comment by Tarun80** [comment]
The way I noticed this was when running guild missions with my guild, we had to do PvP based missions. We had team captains who needed to have Priority Speaker. I could set them in the other temp channels, but not the one I was in. I had to hop channels, set the Priority, then hop back.

Hope this helps.
