### ISSUE TITLE
No more overlay since patch 1.3.0-781 in armored warfare

### ISSUE THREAD

**Issue by dcpc007** [mumble-voip/mumble#1878]
I used 1.3.0 with overlay ok (mumble-1.3.0-745-g10c902f-snapshot.winx64)

I just let the client auto-update today (1.3.0-781) and no more overlay in the game Armored warfare.

**Comment by Kissaki** [comment]
Is this still an issue after restarting the PC and then starting Mumble before Armed Warfare?

**Comment by Kissaki** [comment]
Closing this as no more input and no other people reporting this.
