### ISSUE TITLE
Suggestion: Option to set user limit on channels

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#1882]
An option that I would like to see added would be setting a limit to the number of users in a certain channel. This would be beneficial in helping MMOs (dungeons, raids, teams, etc) and FPS games (scrim teams, etc) keep their teams to just the teams in channels and prevent others from just hopping in. Passwords are an option, as are setting up groups/permissions in the ACP. However, due to how often these team of group setups change, it would be troublesome to change the groups in the ACP.

An option when you create/edit a channel of limiting the channel to a set number of users would really help.

**Comment by FilipPyrek** [comment]
:+1:

**Comment by HarpyWar** [comment]
https://github.com/mumble-voip/mumble/issues/1619

**Comment by mkrautz** [comment]
Fixed by mumble-voip/mumble#1889.

Thanks @bontibon!
