### ISSUE TITLE
Mumble DotA2 Overlay

### ISSUE THREAD

**Issue by HGNTorres** [mumble-voip/mumble#1885]
Mumble overlay doesn't work on the DotA2 Reborn, I tried it on Windows 8, Windows 8.1 and W10, not even in Borderless Window or Window mode.

Using 1.2.9 version of Mumble.

**Comment by mkrautz** [comment]
To use a 64-bit DX11 overlay, you need to use our snapshot builds, available on the front page of mumble.info.

They're listed under "Development Snapshot", and have the version "1.3.0".

If it works, please report back!

**Comment by HGNTorres** [comment]
Worked with 1.3.0~797~g74d19f4~snapshot W x64
