### ISSUE TITLE
Annoying notifications on Windows 10

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1893]
From IRC:

11:19 [Funkeh] did you change something in the latest mumble builds or was it the new windows 10 build that now makes a notification appear in the notification center when someone joins the channel
11:19 [Funkeh] really annoying
11:21 [mkrautz] microsoft fixed a bug that prevented notifications from appearing :)
11:22 [Funkeh] can we disable it by default on win 10
11:45 [mkrautz] I don't feel strongly either way, but if the notifications are listed in the notification center, that would align the functionality with that of our notifcations on OS X.
11:45 [mkrautz] it also seems to me from reading other people's posts on the issue, that some people do want this...
11:45 [Funkeh] we want notifications for certain things
11:45 [Funkeh] certainly not users joining and leaving the channel
11:45 [Funkeh] it was fine when it was a windows xp bubble you could ignore
11:45 [Funkeh] now it's an intrusive popup with a loud sound
11:46 [mkrautz] aha
11:46 [Funkeh] which conflicts with the TTS anyway
11:48 [Funkeh] looking at what has notifications enabled, it would be faster telling you to disable everything and leave the following enabled: critical, warning, permission, text
11:49 [Funkeh] infact text might also be annoying since tts is on

Please discuss.

**Comment by mkrautz** [comment]
See also https://github.com/mumble-voip/mumble/issues/1777

**Comment by hacst** [comment]
:+1: We'll need to change the defaults for Windows 10. I guess I could live with the popup but the sound is really jarring.

**Comment by JoelTroch** [comment]
A dirty and hacky workaround would be for the user to remove the notification sound in the sound theme settings.

**Comment by JoelTroch** [comment]
Or build a custom notification app (yeah it's a hardcore solution)

**Comment by hacst** [comment]
Now that's unfortunate. Settings ```NIIF_NOSOUND``` (https://msdn.microsoft.com/en-us/library/bb773352(VS.85).aspx) on the notification seems like exactly what we want. Unfortunately Qt doesn't provide us with any way to do so while still using their API :( I guess we might have to duplicate that functionality (it's not like we don't do so already for the other platforms...).

**Comment by mkrautz** [comment]
Have you tested that it actually works? It's an XP+ setting...

**Comment by mkrautz** [comment]
Also, some people were annoyed of all the entries in the notification center.

Though that is also an issue on OS X.

**Comment by hacst** [comment]
I guess ```NIF_REALTIME``` would get rid of those entries. Not sure that makes sense to set generically though. At least for text messages, errors and so on I don't think that's a good idea.

**Comment by mkrautz** [comment]
We already use NIF_REALTIME:

https://github.com/mumble-voip/mumble-releng/blob/master/buildenv/1.3.x/win32-static/patches/qt5-add-realtime-flag-for-systray-messages.patch

**Comment by mkrautz** [comment]
We could also easily add NIF_NOSOUND to that list...

**Comment by JoelTroch** [comment]
@mkrautz I think this could be the solution, I've found something about suppressing Toast notifications but it's for Universal Windows 10 applications, not Win32 ones.

**Comment by hacst** [comment]
Oh. I remembered us using that but didn't realize we patched it into Qt. Can't say I would've set it for all notifications when re-implementing the logic but it is definitely better than not using it at all.

@mkrautz Let's add NIF_NOSOUND too then. We do our own audio so I don't think there's a strong reason not to do so (someone will always complain ;) ). Windows XP doesn't care if it sees those flags?

**Comment by funkydude** [comment]
It's time to stop thinking about XP at this point. Qt 5.6 (now in beta) will supposedly also be dropping support for it and Vista.

**Comment by hacst** [comment]
@funkydude Hm. Do you have a good source about Qt 5.6 dropping XP and Vista?

Last month we had ~10k users reporting in from those platforms (as a reference all Linux distributions combined were around 8.7k). The majority of those were still using XP. I see no reason to purposely break compatibility with those platforms if we can help it.

**Comment by JoelTroch** [comment]
[Qt 5.6.0 Known issues](https://wiki.qt.io/Qt_5.6.0_Known_Issues) doesn't mention any drop of Windows XP support at the time I'm writing this and the [list of compatible OSes for Qt 5.6](http://doc.qt.io/QtSupportedPlatforms/index.html) isn't available yet.

**Comment by funkydude** [comment]
Why would the removal of an OS be listed under an issue? :D

It was discussed back during the Qt summit. A quick Google brought up [this](https://www.phoronix.com/scan.php?page=news_item&px=Qt-5.6-LTS-Gauge) though it doesn't specifically call out XP, it calls out Vista. It may well be pushed back to 5.7 or just not documented yet.

**Comment by hacst** [comment]
Fixed in current snapshots (e.g. 1.3.0~953). Thanks to ```NIIF_NOSOUND``` we no longer make any noises on Windows 10. Having the notifications appear in the notification center as well as them showing up in general seems acceptable. If not please open another issue.

**Comment by funkydude** [comment]
When you go to `settings > system > notifications & actions` on Windows 10, Mumble is listed as "On: Banners, Sounds".

It actually gives you the ability to disable banners and sounds on a per app basis, manually. It makes me wonder if there is API on Windows 10 to "register" your app as not having sounds?
