### ISSUE TITLE
murmur FreeBSD 10.1 build failure due to -pie

### ISSUE THREAD

**Issue by feld** [mumble-voip/mumble#1894]
c++ -O2 -pipe -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Werror -isystem /usr/local/include -fPIE -pie 
	-isystem ../mumble_proto -Wall -W -pthread -D_THREAD_SAFE -fPIE -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DSNAPSHOT_BUILD 
	-DMUMBLE_VERSION_STRING=1.3.0 -DMURMUR -DUSE_BONJOUR -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../src 
	-I. -I../mumble_proto -I../bonjour -isystem /usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtNetwork -isystem 
	/usr/local/include/qt5/QtSql -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/qt5/QtCore -Idebug 
	-I/usr/local/lib/qt5/mkspecs/freebsd-clang -x c++-header -c murmur_pch.h -o debug/murmurd/c++.pch
    c++: error: argument unused during compilation: '-pie'

If I remove -pie from the flags in compiler.pri the entire build is successful.

    # cc --version
    FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
    Target: x86_64-unknown-freebsd10.1
    Thread model: posix

**Comment by feld** [comment]
Same error in FreeBSD HEAD, but newer clang

    # cc --version
    FreeBSD clang version 3.7.0 (tags/RELEASE_370/final 246257) 20150906
    Target: x86_64-unknown-freebsd11.0
    Thread model: posix

FreeBSD 9.3 does not have this error, but it uses GCC and ends up erroring elsewhere.

**Comment by mkrautz** [comment]
FWIW, this option is (currently) only being triggered for *debug* builds.

Is this from a build from source manually, or from a ports build? Rather not have the ports build be a debug build. :-)

Anyway, working on a fix...

**Comment by mkrautz** [comment]
Fixed by 0214948de478047392ab84ae5840d0df04e75dda.
