### ISSUE TITLE
murmur FreeBSD 9.3 build error

### ISSUE THREAD

**Issue by feld** [mumble-voip/mumble#1895]
c++ -c -O2 -pipe -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Werror -fPIE -pie -isystem ../mumble_proto -Wall -W -pthread -D_THREAD_SAFE -fPIE -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DSNAPSHOT_BUILD -DMUMBLE_VERSION_STRING=1.3.0 -DMURMUR -DUSE_BONJOUR -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../bonjour -isystem /usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtSql -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/qt5/QtCore -Idebug -I/usr/local/lib/qt5/mkspecs/freebsd-g++ -o debug/Server.o Server.cpp
    c++ -c -O2 -pipe -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Werror -isystem ../mumble_proto -Wall -W -pthread -D_THREAD_SAFE -fPIE -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DMUMBLE_VERSION_STRING=1.3.0 -DMURMUR -DUSE_BONJOUR -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../bonjour -isystem /usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtSql -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/qt5/QtCore -Irelease -I/usr/local/lib/qt5/mkspecs/freebsd-g++ -o release/Server.o Server.cpp
    c++ -c -O2 -pipe -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Werror -fPIE -pie -isystem ../mumble_proto -Wall -W -pthread -D_THREAD_SAFE -fPIE -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DSNAPSHOT_BUILD -DMUMBLE_VERSION_STRING=1.3.0 -DMURMUR -DUSE_BONJOUR -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../bonjour -isystem /usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtSql -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/qt5/QtCore -Idebug -I/usr/local/lib/qt5/mkspecs/freebsd-g++ -o debug/ServerUser.o ServerUser.cpp
    ../CryptState.cpp: In function 'void S2(subblock*)':
    ../CryptState.cpp:215: error: '__builtin_bswap64' was not declared in this scope
    ../CryptState.cpp: In function 'void S3(subblock*)':
    ../CryptState.cpp:222: error: '__builtin_bswap64' was not declared in this scope
    ../CryptState.cpp: In member function 'void CryptState::ocb_encrypt(const unsigned char*, unsigned char*, unsigned int, const unsigned char*, unsigned char*)':
    ../CryptState.cpp:256: error: '__builtin_bswap64' was not declared in this scope
    ../CryptState.cpp: In member function 'void CryptState::ocb_decrypt(const unsigned char*, unsigned char*, unsigned int, const unsigned char*, unsigned char*)':
    ../CryptState.cpp:290: error: '__builtin_bswap64' was not declared in this scope
    *** [release/CryptState.o] Error code 1
    ../CryptState.cpp: In function 'void S2(subblock*)':
    ../CryptState.cpp:215: error: '__builtin_bswap64' was not declared in this scope
    ../CryptState.cpp: In function 'void S3(subblock*)':
    ../CryptState.cpp:222: error: '__builtin_bswap64' was not declared in this scope
    ../CryptState.cpp: In member function 'void CryptState::ocb_encrypt(const unsigned char*, unsigned char*, unsigned int, const unsigned char*, unsigned char*)':
    ../CryptState.cpp:256: error: '__builtin_bswap64' was not declared in this scope
    ../CryptState.cpp: In member function 'void CryptState::ocb_decrypt(const unsigned char*, unsigned char*, unsigned int, const unsigned char*, unsigned char*)':
    ../CryptState.cpp:290: error: '__builtin_bswap64' was not declared in this scope
    *** [debug/CryptState.o] Error code 1
    c++ -c -O2 -pipe -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Werror -fPIE -pie -isystem ../mumble_proto -Wall -W -pthread -D_THREAD_SAFE -fPIE -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DSNAPSHOT_BUILD -DMUMBLE_VERSION_STRING=1.3.0 -DMURMUR -DUSE_BONJOUR -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../bonjour -isystem /usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtSql -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/qt5/QtCore -Idebug -I/usr/local/lib/qt5/mkspecs/freebsd-g++ -o debug/ServerDB.o ServerDB.cpp
    ../Net.cpp: In member function 'bool HostAddress::match(const HostAddress&, int) const':
    ../Net.cpp:101: error: '__builtin_bswap64' was not declared in this scope
    ../Net.cpp:103: error: '__builtin_bswap64' was not declared in this scope
    *** [release/Net.o] Error code 1
    ../Net.cpp: In member function 'bool HostAddress::match(const HostAddress&, int) const':
    ../Net.cpp:101: error: '__builtin_bswap64' was not declared in this scope
    ../Net.cpp:103: error: '__builtin_bswap64' was not declared in this scope
    *** [debug/Net.o] Error code 1
    2 errors
    *** [release-all] Error code 2
    2 errors
    *** [debug-all] Error code 2
    2 errors
    *** [sub-src-murmur-all-ordered] Error code 2
    1 error
    ===> Compilation failed unexpectedly.

This might be due to the old GCC base compiler in FreeBSD 9.3. I can force a different compiler if this is not something you want to chase.

    # cc --version
    cc (GCC) 4.2.1 20070831 patched [FreeBSD]
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by feld** [comment]
confirmed this goes away if i force it to build with the system clang compiler.

    # clang --version
    FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
    Target: x86_64-unknown-freebsd9.3
    Thread model: posix

**Comment by mkrautz** [comment]
We probably need to fix this anyway, for the legacy OSX universal build. It also user's GCC 4.2.

**Comment by mkrautz** [comment]
Universal OS X does not seem to be affected. Probably because it's strictly ppc/i386.

It seems to me from Googling that GCC 4.2 should include __builtin_bswap64. I am not sure why it doesn't work on FreeBSD.

I need to check on FreeBSD 9 to determine how to proceed.

**Comment by mkrautz** [comment]
Fixed in 5dac7e81a4cf21dca6ab30d8b916c140dd801533.
