### ISSUE TITLE
FreeBSD 10.1 "unused parameter" build error

### ISSUE THREAD

**Issue by feld** [mumble-voip/mumble#1896]
c++ -c -Xclang -include-pch -Xclang release/mumble/c++.pch -O2 -pipe -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Werror -isystem ../mumble_proto -isystem ../../3rdparty/celt-0.7.0-src/libcelt -Wall -W -pthread -D_THREAD_SAFE -fPIE -DRESTRICT=__restrict__ -D_FORTIFY_SOURCE=2 -DMUMBLE_VERSION_STRING=1.3.0 -DMUMBLE -DNO_CRASH_REPORT -DUSE_OPUS -DUSE_NO_TTS -DUSE_OSS -DUSE_DBUS -DNO_UPDATE_CHECK -D_THREAD_SAFE -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../bonjour -I../../3rdparty/celt-0.7.0-src/libcelt -I/usr/lib/oss/include -isystem /usr/local/include -isystem /usr/local/include/opus -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtSvg -isystem /usr/local/include/qt5/QtWidgets -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtSql -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/qt5/QtDBus -isystem /usr/local/include/qt5/QtCore -Irelease -I. -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o release/GlobalShortcut_unix.o GlobalShortcut_unix.cpp
    GlobalShortcut_unix.cpp:303:55: error: unused parameter 'dir' [-Werror,-Wunused-parameter]
    void GlobalShortcutX::directoryChanged(const QString &dir) {
                                                          ^
    1 error generated.
    Makefile.Release:3242: recipe for target 'release/GlobalShortcut_unix.o' failed
    gmake[3]: *** [release/GlobalShortcut_unix.o] Error 1
    gmake[3]: Leaving directory '/wrkdirs/usr/ports/audio/mumble/work/mumble-82561a4/src/mumble'
    Makefile:42: recipe for target 'release-all' failed
    gmake[2]: *** [release-all] Error 2
    gmake[2]: Leaving directory '/wrkdirs/usr/ports/audio/mumble/work/mumble-82561a4/src/mumble'
    Makefile:182: recipe for target 'sub-src-mumble-all-ordered' failed
    gmake[1]: *** [sub-src-mumble-all-ordered] Error 2
    gmake[1]: Leaving directory '/wrkdirs/usr/ports/audio/mumble/work/mumble-82561a4'
    *** Error code 1

**Comment by feld** [comment]
This resolved the build error for me. If this looks legit let me know and I'll wrangle together a pull request.

    --- src/mumble/GlobalShortcut_unix.cpp.orig     2015-11-17 20:19:01 UTC
    +++ src/mumble/GlobalShortcut_unix.cpp
    @@ -300,7 +300,7 @@ void GlobalShortcutX::inputReadyRead(int
     #define test_bit(bit, array)    (array[bit/8] & (1<<(bit%8)))
    
     // The /dev/input directory changed
    -void GlobalShortcutX::directoryChanged(const QString &dir) {
    +void GlobalShortcutX::directoryChanged(const QString &) {
     #ifdef Q_OS_LINUX
            if (!g.s.bEnableEvdev) {
                    return;

**Comment by mkrautz** [comment]
FWIW, fixed in80e0f9611c3052581c09a1b1e7458f6876c5772e.
