### ISSUE TITLE
Freenas 9.3 updated murmur now complains about segmentation fault

### ISSUE THREAD

**Issue by Grasfer** [mumble-voip/mumble#1901]
Hi, updated murmur from murmur: 1.2.8_1 -> 1.2.10 and now when i try to start it it complains about segmentation fault. Sorry if this report breaks all the rules about posting bug report.

root@server:/ # service murmur start
Starting murmur.
Segmentation fault
/usr/local/etc/rc.d/murmur: WARNING: failed to start murmur

>The following 2 package(s) will be affected (of 0 checked):

>New packages to be INSTALLED:
        openssl: 1.0.2_4

>Installed packages to be UPGRADED:
        murmur: 1.2.8_1 -> 1.2.10

>The process will require 11 MiB more space.
3 MiB to be downloaded.

>Proceed with this action? [y/N]: n
root@server:/ # service mumble stop
mumble does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d)
root@server:/ # cat /etc/rc.conf
portmap_enable="NO"
sshd_enable="NO"
sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"
hostname="server"
devfs_enable="YES"
devfs_system_ruleset="devfsrules_common"
inet6_enable="YES"
ip6addrctl_enable="YES"
murmur_enable="YES"
znc_user="znc-admin"
znc_enable="yes"
znc_conf_dir="/usr/home/znc-admin/.znc"
nginx_enable="YES"
php_fpm_enable="NO"
mysql_enable="NO"
syslogd_enable="NO"
syslogd_program="/usr/sbin/syslogd"
syslogd_flags="-ss"
root@server:/ # service murmur stop
Stopping murmur.
Waiting for PIDS: 7737.
root@server:/ # pkg upgrade
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Checking for upgrades (2 candidates): 100%
Processing candidates (2 candidates): 100%
The following 2 package(s) will be affected (of 0 checked):

>New packages to be INSTALLED:
        openssl: 1.0.2_4

>Installed packages to be UPGRADED:
        murmur: 1.2.8_1 -> 1.2.10

>The process will require 11 MiB more space.
3 MiB to be downloaded.

>Proceed with this action? [y/N]: y
[server] Fetching murmur-1.2.10.txz: 100%  390 KiB 400.2kB/s    00:01
[server] Fetching openssl-1.0.2_4.txz: 100%    2 MiB   1.4MB/s    00:02
Checking integrity... done (0 conflicting)
[server] [1/2] Installing openssl-1.0.2_4...
[server] [1/2] Extracting openssl-1.0.2_4: 100%
[server] [2/2] Upgrading murmur from 1.2.8_1 to 1.2.10...
You may need to manually remove /usr/local/etc/murmur.ini if it's no longer needed.
==> You should manually remove the "murmur" user.
===> Creating users and/or groups.
Using existing group 'murmur'.
Using existing user 'murmur'.
[server] [2/2] Extracting murmur-1.2.10: 100%
Message from openssl-1.0.2_4:
Copy /usr/local/openssl/openssl.cnf.sample to /usr/local/openssl/openssl.cnf
and edit it to fit your needs.
root@server:/ # service murmur start
Starting murmur.
Segmentation fault
/usr/local/etc/rc.d/murmur: WARNING: failed to start murmur
root@server:/ # cat /etc/rc.conf
portmap_enable="NO"
sshd_enable="NO"
sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"
hostname="server"
devfs_enable="YES"
devfs_system_ruleset="devfsrules_common"
inet6_enable="YES"
ip6addrctl_enable="YES"
murmur_enable="YES"
znc_user="znc-admin"
znc_enable="yes"
znc_conf_dir="/usr/home/znc-admin/.znc"
nginx_enable="YES"
php_fpm_enable="NO"
mysql_enable="NO"
syslogd_enable="NO"
syslogd_program="/usr/sbin/syslogd"
syslogd_flags="-ss"
root@server:/ # updatedb
>>> WARNING
>>> Executing updatedb as root.  This WILL reveal all filenames
>>> on your machine to all login users, which is a security risk.
root@server:/ # locate murmur.ini
/usr/local/etc/murmur.ini
/usr/local/etc/murmur.ini.sample
root@server:/ # service murmur start
Starting murmur.
Segmentation fault
/usr/local/etc/rc.d/murmur: WARNING: failed to start murmur
root@server:/ # service murmur start
Starting murmur.
Segmentation fault
/usr/local/etc/rc.d/murmur: WARNING: failed to start murmur
root@server:/ # pkg remove murmur
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

>Installed packages to be REMOVED:
        murmur-1.2.10

>The operation will free 1 MiB.

>Proceed with deinstalling packages? [y/N]: y
[server] [1/1] Deinstalling murmur-1.2.10...
You may need to manually remove /usr/local/etc/murmur.ini if it is no longer needed.
==> You should manually remove the "murmur" user.
[server] [1/1] Deleting files for murmur-1.2.10: 100%
root@server:/ # pkg install murmur
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

>New packages to be INSTALLED:
        murmur: 1.2.10

>The process will require 1 MiB more space.

>Proceed with this action? [y/N]: y
[server] [1/1] Installing murmur-1.2.10...
===> Creating users and/or groups.
Using existing group 'murmur'.
Using existing user 'murmur'.
[server] [1/1] Extracting murmur-1.2.10: 100%
root@server:/ # service murmur start
Starting murmur.
Segmentation fault
/usr/local/etc/rc.d/murmur: WARNING: failed to start murmur

**Comment by mkrautz** [comment]
We do not create those packages. I assume FreeNAS simply uses the same binary packages that FreeBSD does? /cc @feld 

Maybe file a bug against that?

I can take a look at this, but I need to know how to reproduce. Do I need to install FreeNAS? Can I use FreeBSD? Which version of FreeNAS? Which version of FreeBSD?

It would also help tremendously if you could attach a debugger and try to get a stack trace from the place where the segfault happens. Then we should be able to easily diagnose and fix the problem.

**Comment by Grasfer** [comment]
Thanks for the answer, got a comment on freenas forum it might be a bad build. i'll search around some more.

**Comment by mkrautz** [comment]
Ah sorry, didnt' see the "9.3" in the subject, only read the message content. So, version 9.3. :-)

**Comment by feld** [comment]
I might have tracked this down, but I haven't reproduced the segfault myself. FreeBSD 9.3 is very fussy.

**Comment by feld** [comment]
Found the problem. We were pulling in OpenSSL from ports and QT was pulling in OpenSSL from base. As a result, it was trying to load two different OpenSSLs into murmur and that was causing it to blow up. I wasn't aware QT was also pulling in OpenSSL so now this has thrown a wrench into my plans.

**Comment by feld** [comment]
Would you mind testing this package? It's built for FreeBSD 9.3 amd64 so should be correct for FreeNAS.

https://feld.me/freebsd/murmur-1.2.10_1.txz

**Comment by Grasfer** [comment]
Tried it, installing without a error and everything seems to work. Atleast with 5 users connected.

**Comment by mkrautz** [comment]
@feld Will you close this, or tell me to, once you feel this is properly fixed?

**Comment by feld** [comment]
as far as I can tell, this is fixed. It has also hit the official FreeBSD package mirrors.

**Comment by mkrautz** [comment]
Thanks!
