### ISSUE TITLE
rcc.pri should use system_quote() instead of $$escape_expand(\") once we don't support Qt 4 anymore

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1912]
As the subject says...

**Comment by Krzmbrzl** [comment]
So all of this: https://github.com/mumble-voip/mumble/search?q=escape_expand%28%5C%22%29&unscoped_q=escape_expand%28%5C%22%29 ?

**Comment by ZeroAbility** [comment]
> So all of this: https://github.com/mumble-voip/mumble/search?q=escape_expand%28%5C%22%29&unscoped_q=escape_expand%28%5C%22%29 ?

The search link is dead, so that probably means this was resolved?

**Comment by Krzmbrzl** [comment]
I don't even understand what this issue really is about xD
So let's close it.
