### ISSUE TITLE
Include full Windows 10 build number in OSInfo

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1916]
@funkydude says:

08:56 <Funkeh`> can we not have the entire windows 10 build number show up in the info pane? going forward that's going to be the main distinction of versions

**Comment by mkrautz** [comment]
I would have thought we did this already, but seemingly not...

We should look into this.

**Comment by JoelTroch** [comment]
I don't understand too, because everything seems to work on my end:
![mumble](https://cloud.githubusercontent.com/assets/4483707/11402928/7680ba5c-939a-11e5-81c5-f2b7a65ed03a.png)

**Comment by mkrautz** [comment]
@funkydude - was this not what you meant?

**Comment by funkydude** [comment]
Windows version is in the format X.X.X.X, however, mumble prints X.X.X
![Screenshot](http://abload.de/img/verqxuai.png)

I'm not sure how much of a big deal this truly is though.

**Comment by mkrautz** [comment]
Can someone try to run

    reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion"

on Windows 10 to and see if it produces something useful? (Look at the top -- the bottom part is keys under CurrentVersion, but we want the values at the top...)

**Comment by mkrautz** [comment]
For example, on Windows 8.1 I get:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    SystemRoot    REG_SZ    C:\WINDOWS
    SoftwareType    REG_SZ    System
    InstallDate    REG_DWORD    0x52601484
    CurrentVersion    REG_SZ    6.3
    CurrentBuild    REG_SZ    9600
    RegisteredOrganization    REG_SZ
    CurrentType    REG_SZ    Multiprocessor Free
    InstallationType    REG_SZ    Client
    EditionID    REG_SZ    ProfessionalWMC
    ProductName    REG_SZ    Windows 8.1 Pro with Media Center
    ProductId    REG_SZ    XXXX
    DigitalProductId    REG_BINARY    XXXX
    CurrentBuildNumber    REG_SZ    9600
    BuildLab    REG_SZ    9600.winblue_ltsb.151014-0600
    BuildLabEx    REG_SZ    9600.18090.amd64fre.winblue_ltsb.151014-0600
    BuildGUID    REG_SZ    ffffffff-ffff-ffff-ffff-ffffffffffff
    PathName    REG_SZ    C:\WINDOWS
    RegisteredOwner    REG_SZ    mkrautz

**Comment by JoelTroch** [comment]
Here is a sample on my outdated Windows 10 (for some reason the November/Fall update don't want to install itself) :


HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    SystemRoot    REG_SZ    C:\Windows
    BuildBranch    REG_SZ    th1
    CurrentBuild    REG_SZ    10240
    CurrentMajorVersionNumber    REG_DWORD    0xa
    CurrentMinorVersionNumber    REG_DWORD    0x0
    CurrentType    REG_SZ    Multiprocessor Free
    CurrentVersion    REG_SZ    6.3
    EditionID    REG_SZ    Professional
    InstallationType    REG_SZ    Client
    InstallDate    REG_DWORD    0x55fc2969
    ProductName    REG_SZ    Windows 10 Pro
    RegisteredOrganization    REG_SZ    
    RegisteredOwner    REG_SZ    Shepard
    SoftwareType    REG_SZ    System
    UBR    REG_DWORD    0x40ce
    PathName    REG_SZ    C:\Windows
    ProductId    REG_SZ    00331-10000-00001-AA418
    CurrentBuildNumber    REG_SZ    10240
    BuildLab    REG_SZ    10240.th1_st1.151104-1714
    BuildLabEx    REG_SZ    10240.16590.amd64fre.th1_st1.151104-1714
    BuildGUID    REG_SZ    ffffffff-ffff-ffff-ffff-ffffffffffff
    InstallTime    REG_QWORD    0x1d0f2242a5bf501
    Customizations    REG_SZ    ModernApps

**Comment by hacst** [comment]
Windows 10 pro with november update (the retracted one).
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    SystemRoot    REG_SZ    C:\WINDOWS
    BuildBranch    REG_SZ    th2_release
    CurrentBuild    REG_SZ    10586
    CurrentMajorVersionNumber    REG_DWORD    0xa
    CurrentMinorVersionNumber    REG_DWORD    0x0
    CurrentType    REG_SZ    Multiprocessor Free
    CurrentVersion    REG_SZ    6.3
    EditionID    REG_SZ    Professional
    InstallationType    REG_SZ    Client
    InstallDate    REG_DWORD    0x5647a39e
    ProductName    REG_SZ    Windows 10 Pro
    ReleaseId    REG_SZ    1511
    SoftwareType    REG_SZ    System
    UBR    REG_DWORD    0x3
    PathName    REG_SZ    C:\WINDOWS
    Customizations    REG_SZ    ModernApps
    BuildLabEx    REG_SZ    10586.3.amd64fre.th2_release_sec.151104-1948
    BuildLab    REG_SZ    10586.th2_release_sec.151104-1948
    ProductId    REG_SZ    00330-80000-00000-AA169
...
```

**Comment by funkydude** [comment]
So BuildLabEx or?

**Comment by mkrautz** [comment]
I think we should show the following:

     WinX64 (Windows 10 Professional x64 - version 1511 build 10586.164)

...Perhaps shorened to V1511 B10586 or v1511 b10586 so?

Version is "ReleaseId". The version is encoded as YYMM, so version 1511 is clearly the November update (November 2015).

The build number is "CurrentBuild". Can also be queried via `GetVersionEx()`. The last part of the build number, I am not sure how we query -- or if it is even necessary.

The values proposed are the same as the ones shown in the about dialog for System (Windows + Pause):

![image](https://cloud.githubusercontent.com/assets/36527/14294608/424e4a70-fb72-11e5-968d-8bf8ab049bbe.png)

We should also simplify the edition detection. Right now, Win 10 Pro is detected as "Professional". That's not really the name of the SKU, and using Pro saves some characters, allowing us to show both the version and the build number more easily...

**Comment by mkrautz** [comment]
The ".164" part is UBR:

    UBR    REG_DWORD    0xa4

**Comment by hacst** [comment]
SGTM. Displaying what is in the about windows dialog seems like the right way to go. I wouldn't bother displaying anything else unless we have to work to take it out. So how do we get that programatically with the least amount of baggage?

**Comment by mkrautz** [comment]
In pseudocode:

    var key = "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion";
    var version = getRegString(key + "\ReleaseId");
    var build = getRegString(key + "\CurrentBuild");
    var ubr = getRegDword(key + "\UBR");
    var win10relinfo =  sprintf("version %s build %s.%u", version, build, ubr); 


Then replace the following lines of OSInfo.cpp:

	QString osv;
	osv.sprintf(" - %d.%d.%d", ovi.dwMajorVersion, ovi.dwMinorVersion, ovi.dwBuildNumber);
	osdispver.append(osv);
   
with:

        QString osv;
        if (win10) {
            osv.sprintf("%s", win10relinfo);
        } else {
            osv.sprintf(" - %d.%d.%d", ovi.dwMajorVersion, ovi.dwMinorVersion, ovi.dwBuildNumber);
        }
        osdispver.append(osv);

**Comment by hacst** [comment]
Did Microsoft document that somewhere or will this come crashing down on us with their next update? ;)

**Comment by mkrautz** [comment]
I don't think it's documented anywhere.

Nor is it likely to be.

They don't want you querying the OS version anymore.

I think this will be fine as long as we can reasonably fall back to something (GetVersionEx()?) output if we detect any anomalies.

**Comment by hacst** [comment]
ok. Why not.
