### ISSUE TITLE
Fix uninstall behavior for Windows installer

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1917]
Via @funkydude

21:02 <Funkeh`> something is wrong with the windows updates the past few month(s), every time there's an update, the pinned icon on the taskbar is removed, and I have to unpin and pin it again

**Comment by mkrautz** [comment]
This is because of our new behavior where we uninstall fully.

We changed our installer to do a full uninstall when installing on top ("upgrading") an existing installation.

We did this because the installer would not properly remove old files and versions of Mumble.

We'll have to figure out what to do from here.

**Comment by JoelTroch** [comment]
[This might help](http://www.codeproject.com/Articles/43768/Windows-Taskbar-Check-if-a-program-or-window-is)

**Comment by JoelTroch** [comment]
Something that could be worth testing:

After update, remove the symlink to Mumble, remake it, restart "explorer.exe"

**Comment by Kissaki** [comment]
I have Mumble pinned to start on my Windows 10. Upgrading the snapshots and opening the start menu, I can see the Mumble icon briefly disappear and appear again.
So at least for me, it works fine.

**Comment by mkrautz** [comment]
This should be fixed in the latest snapshot: mumble-1.3.0\~2505\~g346702f.
