### ISSUE TITLE
Username isn't being shown in server console

### ISSUE THREAD

**Issue by TheJamesD** [mumble-voip/mumble#1918]
I am using "Murmur 1.2.8 (1.2.8) running on X11: Ubuntu 14.04.3 LTS: Booting servers". When a user connects, it will show their username as a number. Here is the console output: http://pastebin.com/pFTSSNY3

Why doesn't it show the username of the user connecting?

Thank you for your help.

**Comment by mkrautz** [comment]
Thanks for reporting this. This looks odd. We will look into it.

**Comment by TheJamesD** [comment]
A few other things to note:

1. I have tried connecting with Client 1.2.8 and Server 1.2.8.
2. I have tried connecting with Client 1.2.10 and Server 1.2.8.
3. I have tried connecting with Client 1.2.10 and Server 1.2.10.
4. I have reinstalled the server and client.
5. I am running the server on docker 1.4.1.

Thanks for looking into this. If I could get an update ASAP, that would be great because I am midway through building a web application for Mumble. If you need any more info, I would be happy to provide.

**Comment by TheJamesD** [comment]
Hi mkrautz,

Have you looked into this?

Thanks for your help.

**Comment by TheJamesD** [comment]
It appears the issue was when transferring Murmur output via XML-RPC. After HTML encoding output, it then transfers correctly.

**Comment by mkrautz** [comment]
Thanks for confirming.  Sorry for not looking into this.  I was in fact going to this weekend, as we're preparing to release 1.2.12, but I hadn't gotten to it yet.

Glad you found the culprit!
