### ISSUE TITLE
Logitech G15 LCD display helper not loading

### ISSUE THREAD

**Issue by dekeonus** [mumble-voip/mumble#1927]
Neither
mumble-1.3.0~826~g0e4070c~snapshot.winx64.msi
nor
mumble-1.3.0~841~gee43279~snapshot.winx64.msi
load the LCD display
Last snapshot with working G15 LCD display is:
mumble-1.3.0~809~gb0d53e1~snapshot.winx64.msi

The LCD options category is missing from the config UI. The mumble-g15-helper.exe is present in [install_dir]/Versions/[snapshot_version] it just doesn't load. I can't find any reference in the console log about the helper not loading (or in the case of b0d53e1 actually loading)

**Comment by mkrautz** [comment]
You don't see
    <W>2015-11-26 16:59:42.625 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
in your log?

**Comment by mkrautz** [comment]
Is this the error you see?
https://github.com/mumble-voip/mumble/issues/1692

**Comment by mkrautz** [comment]
Sorry, I have to clarify:

If you try to start mumble-g15-helper.exe, do you get the error from the #1692 issue?

You should get that, or it'll how you that the .exe should only be run by Mumble.

**Comment by dekeonus** [comment]
I've examined logs (fresh mumble install) from 1.3.0~809~gb0d53e1 and 1.3.0~841~gee43279 neither have any reference to G15LCDEngine_lglcd (neither succeeding to load nor failing to load)

If I execute mumble-g15-helper.exe by hand I see the message box
Title: Nothing to see here move along
msg: This program is run by Mumble, and should not be started separately.
this is the same message box for both versions (1.3.0~809~gb0d53e1 and 1.3.0~841~gee43279).

**Comment by mkrautz** [comment]
I can reproduce. With 841, I see no G15 message in the log. How odd.

**Comment by dekeonus** [comment]
Just tested with the mumble-1.3.0~841~gee43279~snapshot.msi (ie the 32 bit version instead of the 64bit) it exhibits the same issue: the mumble-g15-helper.exe is not running* the G13 gamepad has no mumble applet and the LCD sub-options are missing from the configuration settings.

*that is the child process mumble-g15-helper.exe is not present in the process monitor I use (Process Hacker http://processhacker.sourceforge.net/)

I should have mentioned in my opening ticket I'm using Win7pro 64bit.

**Comment by mkrautz** [comment]
Ah, OK. I probably screwed up a conditional in the qmake file when I "fixed" G15 for FreeBSD...

**Comment by dekeonus** [comment]
I did wonder if that was related
