### ISSUE TITLE
User limitation is ignored on reconnect.

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#1930]
For example user1 and user2 are in a channel limited to 2 users.
User1 disconnects, user3 enters the limited channel and user1 reconnects.

Result: 3 users in a 2-user-limited channel.

**Comment by mkrautz** [comment]
Logic should probably be:

On connect, if the channel is full, try to join root instead. If unable to join root (full/permission error), recurse through the channel tree until a working channel is found, and join it.

**Comment by mkrautz** [comment]
If nothing works, disconnect with an error message.

**Comment by bontibon** [comment]
On it.

**Comment by Natenom** [comment]
Wow, that was fast. Works. Thank you :)
