### ISSUE TITLE
mumble mutes spotify app on linux

### ISSUE THREAD

**Issue by IlikePepsi** [mumble-voip/mumble#1934]
Everytime I mess around with the systems volume control Spotify get's muted completely. As you can see in the attached picture other players are not affected, e.g. Clementine or any webplayer in the browser.

I'm using Arch Linux (64bit) and the gnome desktop environment. 

How can I track down the reason for this behavior? I thought this might relate to the adaptive volume reduction when somebody is talking but the problem remains even when that mumble feature is deactivated.

![gnome volume control](https://cloud.githubusercontent.com/assets/9033437/11452975/ce2d3a12-95f9-11e5-99f6-27a3a78baf18.png)

**Comment by mkrautz** [comment]
Your description is not clear on this, but I assume this only happens when Mumble is running?

**Comment by mkrautz** [comment]
Also, what version of Mumble are you using?

If you are using the 1.2 series, Mumble is set as a "phone" to Pulse.

That may be why it is muting Spotify.

In 1.3, we're set as "game", and that doesn't try to mute music apps when a call is active:
https://github.com/mumble-voip/mumble/commit/76475381dfff4079de73113676acf1dec3729263

**Comment by IlikePepsi** [comment]
Yes, it only happens when mumble is running and my current version is 1.2.10. So I'll wait for the next version. Thank you.

**Comment by mkrautz** [comment]
FWIW, there is a package that builds the latest development snapshot in AUR:
https://aur.archlinux.org/packages/mumble-git/

It would be nice if you could confirm that this fixes the issue you are seeing. Thanks!

**Comment by mkrautz** [comment]
Please re-open if it is still an issue in 1.3.0. Thanks!

**Comment by Soundtoxin** [comment]
When I open mumble with `mpd` playing music, `mpd` gets muted. I can unmute in `pavucontrol`, but if I quit and restart mumble it happens again. Can I disable this somehow? Seems related to this issue. I'm on GuixSD running mumble 1.2.19. I guess I'll see if my distro will update to 1.3.
