### ISSUE TITLE
Client configuration storage should not be platform-specific

### ISSUE THREAD

**Issue by RomanHargrave** [mumble-voip/mumble#1940]
Currently, mumble stores client data, including certificates, as follows:
- On Windows, the mumble configuration lives entirely in binary storage hell - NTUSER.DAT (HKCU)
- On OSX, the configuration is stored in a plist file, and I'm not sure what that looks like
- On Linux, the configuration is stored in some manner of INI file, Mumble.conf

I propose that mumble either move settings and certificate storage in to an SQLite database, or
that it uses the `Mumble.conf` approach for all platforms. There appears to be no reason to keep this data in such manners, and it has only caused me frustration.

I was trying to help someone recover their key from windows. I got as far as extracting the REG_BINARY cert value, and gave up, because converting that to a Mumble.conf-friendly value is simply no small task.

In the end, I would have to:
- Export a registry snapshot of Software\Mumble
- Attempt to get mumble to run in WINE or use a VM
- Export the certificate there.

Realistically, I should be able to extract a mumble client profile on one platform and have it work on any other supported platform simply by placing it in the configuration folder.

**Comment by mkrautz** [comment]
In my opinion, this is something we should work towards.

However, regarding certificate management, the proper place to store them would be in the user's certificate store, or Keychain on OS X. But I'm afraid that would possibly make certificate extraction in case of emergency even harder...

**Comment by hacst** [comment]
:+1: for storing certs in the cert store. Maybe we should take a look at the KDE Framework stuff. Would be surprised if they hadn't already solved proper access to the system specific store.

Using the same configuration format on all platforms would be ok I guess. However for example using the registry on Windows has been pretty helpful in the past (e.g. we can simply distribute .reg files for experimental configuration).

I'm against moving the config into the SQLite unless we have other strong reasons to do so then unification. It's extra work to migrate from QSettings and more importantly users will no longer be able to edit/inspect the configuration by hand. Sure we could extend our commandline interface with a way to edit the configuration (e.g. set k,v pairs) or add special UI but that's not something users are used to.

**Comment by RomanHargrave** [comment]
@mkrautz If we stored the cert in the cert store it would still be easier to extract ICE due to the availability of forensics/data recovery software to analyze the cert store / keychain.

The downside to using the keychain on OSX, if I recall, would be needing to prompt the user for their password every time the cert is needed.

@hacst RE: SQLite

I would prefer to use plaintext storage instead. WRT to distributing registry files, you could simply replicate that functionality with an "Import / Export Configuration" menu item or wizard in the same manner as the "Import / Export Certificate" wizard.

**Comment by mkrautz** [comment]
@RomanHargrave As long as you've granted access once, and your app is properly signed, Keychain shouldn't prompt again, AFAIK.

**Comment by RomanHargrave** [comment]
@mkrautz I just updated my previous comment with some concerns about keychain usage on Linux.
