### ISSUE TITLE
Local Volume for Different Users

### ISSUE THREAD

**Issue by mattconsto** [mumble-voip/mumble#1952]
Currently you can Local Mute any user on whatever server you are connected too. Being able to change the volume of an individual user would be useful in-case they are significantly louder/quieter than everyone who is already connected. Currently the only options are muting them or asking them to turn down their transmit volume.

I know both TeamSpeak and Curse Voice support this feature, and I'm pretty sure they are not the only voice chat clients with this feature.

Feature Request

**Comment by Natenom** [comment]
This is already implemented in the 1.3 snapshots (15f47f4f).
