### ISSUE TITLE
Implement simple game detection logic as an alternative to the overlay whitelist/blacklist

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1954]
Builds upon #1953

It seems to me it would be handy to have a very simple game detection feature as an alternative to the current overlay whitelist/blacklist system.

We should be able to glob all Steam programs using something like:

```
*steamapps*
```

Other services like Origin do not require a structure like Steam's, but the library paths could be queried from the configuration. For Origin there's a local.xml containing the path to your library.

I have not tested other services.

If we do read configs, we're prone to break with updates. Ideally, something like that should be fixable by a point release.

**Comment by mkrautz** [comment]
Another mechanism that at least works for Steam:

Check if Steam is parent of the process.

That'd work for non-Steam games added to the Steam list of games as well.

**Comment by mkrautz** [comment]
The same works for Origin, where programs are launched by EALaunchHelper.exe.

**Comment by mkrautz** [comment]
The same works for the Battle.net launcher, where the parent would be Battle.net.exe.

**Comment by mkrautz** [comment]
The same works for GOG Galaxy, where the parent would be GalaxyClient.exe.

**Comment by hacst** [comment]
So basically switch over to whitelist only and provide some preconfigured glob entries? We would have to revamp the complete mechanism though (not that it would be that hard). At the moment it is either a whitelist xor a blacklist and we still need blacklisting. Also whitelisting would have to be simple and obvious as we'll never have a sufficient whitelist.

**Comment by mkrautz** [comment]
In the later comments, I figured it would be easier just to check the parent's process name.

I am not exactly sure how it would be presented in the UI.

Perhaps a separate mode next to the existing whitelist/blacklist.

Or perhaps allow the whitelist to match parent processes, and pre-populate it with various launchers.

**Comment by Kissaki** [comment]
Implemented by #2920. @mkrautz so we can close this, right?
