### ISSUE TITLE
User info shows invalid Windows version.

### ISSUE THREAD

**Issue by artur9010** [mumble-voip/mumble#1956]
![zbaktpnajqiwbruwfjusscyoatxwhruucbhirlaphqonnxiwthfdniqwdmkarrtsvntzjmetjflcokbckbdzlrguklffbzxpwwrz](https://cloud.githubusercontent.com/assets/4835677/11610411/c566705c-9ba2-11e5-849e-1c96da2cceed.jpg)
Mumble 1.2.10 on Windows 10

**Comment by mkrautz** [comment]
This is expected. Mumble 1.2.10 is not built with the updated manifest.

This is fixed in the tree, and will be in 1.3.0.
