### ISSUE TITLE
Configure button does nothing...

### ISSUE THREAD

**Issue by kombat601** [mumble-voip/mumble#1957]
Whenever i click the "Configure" button in mumble, nothing happens, at that point, all i can do on mumble is talk, nothing else can be done, every time i click a button on the mouse in any part of the mumble window, all i get is a windows alert sound. Only way to end this is to force close mumble.
Here's a debug: http://pastebin.com/THaQfgP4
(The issue is at line 186)

Mumble version: 1.2.10
Windows 10

**Comment by mkrautz** [comment]
Turned out to be a bad configuration.

Wipe of Mumble-related registry entries fixed it.
