### ISSUE TITLE
PBKDF2 fallback for OpenSSL 0.9.9 too broad

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1959]
Static snapshots don't work because of it...

**Comment by funkydude** [comment]
>Support for version 0.9.8 will cease on 2015-12-31. No further releases of 0.9.8 will be made after that date. Security fixes only will be applied to 0.9.8 until then.
>Support for version 1.0.0 will cease on 2015-12-31. No further releases of 1.0.0 will be made after that date. Security fixes only will be applied to 1.0.0 until then.

https://www.openssl.org/policies/releasestrat.html

**Comment by mkrautz** [comment]
FreeBSD is still supporting 0.9.8 in their 9 series.

Not us.

**Comment by mkrautz** [comment]
/cc @feld 

Will Qt transition to -openssl-linked against the ports copy of OpenSSL?

Or should we continue to link against the base system version?

**Comment by funkydude** [comment]
Supporting in what way, they are taking over maintaining it themselves?

**Comment by hacst** [comment]
Not sure I understand the problem from the description. Could you elaborate a bit on what's broken?

**Comment by mkrautz** [comment]
@hacst I added some code to forcefully disable PBKDF2 for older OpenSSL's, such as the one used in FreeBSD 9 base. We link against the base system's OpenSSL because Qt in FreeBSD 9's ports uses dlopen() and prefers /usr/lib to /usr/local/lib.

Unfortunately, I typo'd the preprocessor identifiers OPENSSL_VERSION vs OPENSSL_VERSION_STRING, so it is broken.

@feld Do you know whether FreeBSD 9 will stay on 0.9.8? Could the Qt port be migrated to use -openssl-linked against the ports copy, so we could require OpenSSL 1.0.1 or newer for Mumble 1.3.0. And last but not least, will Mumble 1.3.0 even be available in FreeBSD 9's ports tree once it's released?

**Comment by hacst** [comment]
So this does affect the statics we released for 1.2.11 too? Or only FreeBSD?

**Comment by mkrautz** [comment]
Only snapshots.

**Comment by hacst** [comment]
/me failed at reading. Just noticed you wrote that right in the beginning. Sorry.

**Comment by feld** [comment]
FreeBSD 9 has to stay on 0.98 until it is EoL (December 31, 2016). Any security issues that affect OpenSSL 0.98 will be backported by our developers or we will collaborate with Red Hat, etc who are also stuck in this situation.

QT will not be forced to link against OpenSSL in ports. There are just too many potential edge cases. I anxiously await FreeBSD 11 which will require *everything* to come from ports/packages and base-system things that need OpenSSL, for example, will use a private copy that other software can't link to.

If you need to kill support for OpenSSL 0.98 that's fine. We will just mark it as broken on FreeBSD 9.

**Comment by hacst** [comment]
I really don't like these additional legacy crap workaround code-paths in security critical code :( Stupid distribution model....
