### ISSUE TITLE
Mumble Doesn't Work With Steam Controller

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#1964]
Every time the mumble window is focused by the steam controller (which emulates a mouse), I am unable to move the mouse anymore. With other applications it's no problem using the controller as a mouse.

**Comment by Kissaki** [comment]
I have a Steam controller myself, and just tried it out.
0 problems.

Mumble was running,
I connected the Steam controller,
focused the Mumble window with the mouse, was able to move the cursor, select stuff, switch channels, move and resize the window, scroll, no problem.

Are you sure this is not related to something else on your end?

**Comment by mkrautz** [comment]
@Kissaki Running Steam Beta or regular releases?

**Comment by Kissaki** [comment]
@mkrautz regular

**Comment by mkrautz** [comment]
@stc1103 Are you running with Steam betas, or the regular Steam client?

**Comment by Kissaki** [comment]
@mkrautz same for the Steam client beta I just installed.
While the Steam client was updating, the steam controller mouse input became *very* unresponsive.
Maybe they simply have some issues still in that regard.

**Comment by mkrautz** [comment]
Also, it's worth noting (I don't know if you know already), but the Steam controller without updated firmware (that is, if you don't have Steam running -- and Steam therefore has not been able to update the firmware of the controller, which happens on the fly, and is seemingly not stored on the controller) doesn't function nearly as good as when running the latest firmware.

At least, this was the case with the October units. I don't know if the situation is better now.

Anyway, if you're running Steam as well, this shouldn't be a problem.

**Comment by stc1103** [comment]
@mkrautz Beta. Didn't make a difference with Steam being on or off.

**Comment by Kissaki** [comment]
Closing Steam, the controller stops working as a mouse.
Reconnecting the controller without Steam running behaves fine as a mouse input even with the Mumble window (it receiving and with it having focus).

As soon as I launch steam, most of the "haptic feedback" (rumble on swipe) disappears, and the issue occurs again.

**Comment by mkrautz** [comment]
We have determined that the Steam Controller seems to work when Mumble is running without uiAccess.

If you try to copy your Mumble installation from Program Files to your desktop, and try to run it from there -- it should work better. (This will force uiAccess to be disabled.)

If this works for you, we will consider making this process an easier thing to do for 1.3.0.

Please report back!

Thanks.

**Comment by stc1103** [comment]
@mkrautz It works.

**Comment by shadowbottle** [comment]
Could someone elaborate on this issue? It's still present. I can launch and then kill focus on 1.3 snapshot and controls will work again, but nothing in the Mumble window can be accessed or utilized using the steam controller. By "copying the mumble installation" do you mean move out the binary or the entire folder?

In any case, glad this was already open as it was quite mystifying to troubleshoot lol

Thanks!

**Comment by mkrautz** [comment]
@shadowbottle Mumble uses a Windows feature that marks Mumble as an accessibility program. (uiAccess=true).

This causes Mumble run run with slightly higher privileges than what the Steam controller expects.

There are a few workarounds:

 - The uiAccess=true feature only works if Mumble is installed in C:\Program Files\ or C:\Program Files (x86), so if you you install Mumble somewhere else -- or simply copy your Mumble folder to your desktop and run it from there, your Steam controller should work.

 - Alternatively, you can set the environment variable __COMPAT_LAYER=RunAsInvoker before running Mumble. This will also disable uiAccess=true. You can do this with a bat file:

    set __COMPAT_LAYER=RunAsInvoker
    C:\Program Files (x86)\Mumble\mumble.exe

**Comment by hacst** [comment]
You forgot the other alternative:

* Get Valve to actually make their controller act like a proper input device....

**Comment by mkrautz** [comment]
That's not a workaround. That's a fix.
