### ISSUE TITLE
New messages bring the scroll bar down to the latest message

### ISSUE THREAD

**Issue by vCarbonnn** [mumble-voip/mumble#1969]
I have just upgraded from version 1.2.10 to 1.2.11, and now when I am looking at old chat (scrolled up), any new messages brings the scroll bar down to the latest message, meaning I can't read old messages easily.

I have asked a few others who have upgraded to the same version, and they are also reporting the same issue.

**Comment by mkrautz** [comment]
It seems like our fix for https://github.com/mumble-voip/mumble/issues/1258 was too agressive...

**Comment by mkrautz** [comment]
I have landed a commit that I believe fixes the issue to the 1.2.x branch:
https://github.com/mumble-voip/mumble/commit/1a4ae8deddc9c833ee276cbbb08bd19940e2840c

I am currently building a 1.2.x snapshot for you to test.

I will update this with a link as soon as I can, but if nothing else, the snapshot should show up in http://mumble.info/snapshot/ (called mumble-1.2.12~[something].msi)...

**Comment by mkrautz** [comment]
Here is the snapshot: http://mumble.info:8080/snapshot/mumble-1.2.12~3~g1e4e1e1~snapshot.msi

GPG sig if you're into that: http://mumble.info:8080/snapshot/mumble-1.2.12~3~g1e4e1e1~snapshot.msi.sig

(Note: the snapshot will probably prompt you to update a 1.3.0 snapshot... Just ignore that message in the log -- it just thinks that the 1.3.0 snapshot is newer than the 1.2.12 snapshot that you're testing ... which is technically true ... but worthless for us.)

Please report back if this works for you.  If it does, please report back.

Then, if possible please give it good test drive for some days, if you can.

If everything works, we'll try to release a version 1.2.12 this weekend.

**Comment by vCarbonnn** [comment]
Initial testing shows that 1.2.12~3~g1e4e1e1 works perfectly! 
It also works alongside the #1258 fix for images.

I will continue to test it in the next day or so and report back again, but other than that, thank you!

**Comment by mkrautz** [comment]
@vCarbonnn Any good/bad news regarding the change? :-)

**Comment by vCarbonnn** [comment]
@mkrautz All working great! I've confirmed with a few others who upgraded to 1.2.11 that the 1.2.12 snapshot above resolves the issue for them too.

**Comment by mkrautz** [comment]
1.2.12 is now released. Thanks very much for the help!
