### ISSUE TITLE
Logging to syslog doesn't seem to work?

### ISSUE THREAD

**Issue by simmel** [mumble-voip/mumble#1973]
I have no idea if I misinterpret #1313 but doing:
```
logfile=syslog
```
in `murmur.ini` doesn't make murmurd syslog, it just says:
```
murmurd: failed to open logfile syslog: no logging will be done
```

This is on version `1.2.10-1~ppa5~trusty1`.

**Comment by mkrautz** [comment]
That change is not in that version. The change is in the master branch in git, which will become 1.3.0. That is, our snapshot builds on the Mumble website.

There are also snapshot PPAs available, FWIW.

If it still doesn't work there, please file a bug!
