### ISSUE TITLE
Create a Steam curator for games with positional audio?

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1974]
The Steam curator system allows individuals and organizations (groups) to comment and recommend games.
This system meant for recommendations has already been (creatively mis)used to label games with whether their FPS are locked or not, and to which frame rate ([The Framerate Police](http://store.steampowered.com/curator/9393382/).

Although it only shows up after you have 10 games listed,
what do you generally think about making our Steam Mumble group curate games that provide PA either natively or via plugins?

*poke* @mkrautz @hacst @Natenom

**Comment by mkrautz** [comment]
SGTM

**Comment by hacst** [comment]
Sure.

**Comment by Kissaki** [comment]
Ok, I set it up according to our PA games list in the wiki
http://wiki.mumble.info/wiki/Games#Supported_Games

http://store.steampowered.com/curator/1183851/
https://steamcommunity.com/groups/mumble_voip#curation

(this makes me really want to continue/finish what I began for not-having-to-compile-dlls - most of these plugins are probably outdated…)

**Comment by Hiradur** [comment]
@Kissaki I believe the Tesseract game on your list is the wrong one since it seems be a single player game. This is the Tesseract game which has PA support: http://tesseract.gg/ (not on Steam).

**Comment by Kissaki** [comment]
@Hiradur thank you, I removed it
