### ISSUE TITLE
Where's stable Windows x64 build?

### ISSUE THREAD

**Issue by mirhl** [mumble-voip/mumble#1980]
Missing on both pages. 
http://wiki.mumble.info/wiki/Main_Page
https://github.com/mumble-voip/mumble/releases/

Development snapshots are fine though.

**Comment by Kissaki** [comment]
I can see it on the mainpage - although I am confused by that, as x64 is fairly new.
From what I knew up to now, its a new thing with out 1.3.0 builds.

So, as its not well tested, and definitely not a bugfix release, I would expect there to not be a x64 1.2 version.

**Comment by hacst** [comment]
There is no x64 build for 1.2.X stable. The link on the front page intentionally goes to the x86 version. Only with the 1.3 release will there be an actual x64 stable version.

**Comment by mirhl** [comment]
Oh, sorry. Thanks for answering.
