### ISSUE TITLE
1.3.0 Windows Murmur builds are missing correct openssl

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1981]
![2015-12-10 23_55_54-murmur-openssl](https://cloud.githubusercontent.com/assets/93181/11731156/a4c9bb7e-9f99-11e5-8e1a-8367ce8edd86.png)

qFatal from PBKDF2.cpp:89 after check for `OPENSSL_VERSION_NUMBER >= 0x00090900fL`

Works with an older, existing (legacy) DB, as that does not use PBKDF2.
(`ServerDB.cpp:78 if (!Meta::mp.legacyPasswordHash) {`)

**Comment by Kissaki** [comment]
Actually, same for our x86 build.

**Comment by hacst** [comment]
So. Uh. What exactly are you running to get that? Snapshot? Stable? Self-compiled?

**Comment by YujiSaeki** [comment]
1.3 snapshot, 868 only build I tested, but both x86 and x64.

**Comment by Kissaki** [comment]
sorry …

**Comment by Kissaki** [comment]
Seems to work fine with my self-compile with a recent `mumble-releng` `win32-static-no-ltcg-1.3.x-2015-12-05-0ee371c-581`.

**Comment by hacst** [comment]
Sounds like either the fix for https://github.com/mumble-voip/mumble/issues/1959 introduced this issue or our build for some reason fell back to an old OpenSSL on Windows. I think @mkrautz has to take a look.

**Comment by mkrautz** [comment]
Should already be fixed by https://github.com/mumble-voip/mumble/commit/ba49ba5e34ffa5b7e7dcb1ea89943854255f3071

**Comment by hacst** [comment]
I see. I read Kissaki's code snippet and assumed ```OPENSSL_VERSION_NUMBER``` was what was already checked against in the snap (and hence the bug would be present with the patch from the linked issue). I guess that simply means we don't have a new snap out yet.

**Comment by Kissaki** [comment]
ah, sorry,
I didn’t think about that either

**Comment by mkrautz** [comment]
Confirmed that self-built Murmur works (Windows x64).

Closing this, as it'll be fixed in the upcoming snapshot.
