### ISSUE TITLE
mumble consumes 100% cpu if the network is not available

### ISSUE THREAD

**Issue by l29ah** [mumble-voip/mumble#1983]
To reproduce, connect to a server and then shut down the internet access.

**Comment by mkrautz** [comment]
I am not saying it is not true for all OSes, but what OS/distro and what version of Mumble? (And what version of Qt?)

Thanks.

**Comment by l29ah** [comment]
On Fri, Dec 11, 2015 at 09:20:28AM -0800, Mikkel Krautz wrote:
> I am not saying it is not true for all OSes, but what OS/distro and what version of Mumble? (And what version of Qt?)

Gentoo Linux amd64, mumble-1.2.10, qt-4.8.7.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by actown** [comment]
Marked Linux for now.

**Comment by fcsonline** [comment]
Confirmed in Ubuntu too. mumble-1.2.12

**Comment by davidebeatrici** [comment]
Closing in favor of #2109.
