### ISSUE TITLE
Linux static server snapshot doesn't run

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#1994]
I currently run murmur-static_x86-1.3.0~658~g3d46634 on my server. Debian 8.2 on custom compiled linux 4.2.5 with grsecurity without any problems.

Now I tried running  version 1.3.0~874~gba49ba5 and 1.3.0~883~g2a31708 and here I get. 

 ./murmur.x86 murmur.x86: can't find internal filesystem in '/home/c/murmur-static_x86-1.3.0~883~g2a31708~snapshot/murmur.x86'

also here is a strace output 

execve("./murmur.x86", ["./murmur.x86"], [/\* 17 vars */]) = 0
[ Process PID=30074 runs in 32 bit mode. ]
readlink("/proc/self/exe", "/home/c/murmur-static_x86-"..., 4096) = 70
stat64("/home/c/murmur-static_x86-1.3.0~883~g2a31708~snapshot/murmur.x86", {st_mode=S_IFREG|0755, st_size=37659820, ...}) = 0
uname({sys="Linux", node="pandabaer.org", ...}) = 0
open("/home/c/murmur-static_x86-1.3.0~883~g2a31708~snapshot/murmur.x86", O_RDONLY) = 3
fstat64(3, {st_mode=S_IFREG|0755, st_size=37659820, ...}) = 0
old_mmap(0x1003b000, 53248, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x10000) = 0x1003b000
write(2, "murmur.x86: can't find internal "..., 119murmur.x86: can't find internal filesystem in '/home/c/murmur-static_x86-1.3.0~883~g2a31708~snapshot/murmur.x86'
) = 119
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by davidebeatrici** [comment]
Have you tried moving the server to another path?
