### ISSUE TITLE
Support XBox 360 Guide button as a key binding

### ISSUE THREAD

**Issue by WydD** [mumble-voip/mumble#1995]
I use an arcade stick on windows and I usually use the "home" (or "guide") button functionality as a push-to-talk. Unfortunately, it is not possible to bind this button with an XBox 360-like controller at least in windows.

Some people have made small programs to detect this exact input and bind it to a keyboard action but it is not recognized by mumble.
The reddit thread in question: https://www.reddit.com/r/emulation/comments/1goval/any_way_to_map_the_middle_xbox_360_button/camujj7

This feature would be really awesome.

Thanks.

**Comment by mkrautz** [comment]
We want to provide a better Mumble experience for controllers, including fight sticks.

We would definitely like to do this.

**Comment by WydD** [comment]
Great :) !

If that helps, actually it seems that no other buttons works on an xbox 360 pad (even though other buttons are usually bound to something ^^)

**Comment by mkrautz** [comment]
I have added a proposed implementation of this at:
https://github.com/mumble-voip/mumble/pull/2013

Currently pending code review. Should hopefully show up in a snapshot soon!

**Comment by WydD** [comment]
Wooooh that was quick ! Let me know when a snapshot is ready :)

**Comment by mkrautz** [comment]
This should be in the upcoming snapshot 1.3.0~894~gabdb500~snapshot.

Right now, we do not disable Xbox controllers from DirectInput. So when you click a button, you'll get *both* clicks.

In practice, that shouldn't matter. But in the shortcut config dialog, you'll notice that for some buttons, it'll be bound for both XInput and DirectInput.

We plan to fix that in the future -- but for now, we haven't observed any ill effects of it. It should just work.

Let us know if the new XInput support works well! Thanks!

**Comment by mkrautz** [comment]
Update:

We've had to disable XboxInput for now in the snapshots, as it crashes on x86.

Our x64 snapshots are reportedly fine, though.

Snapshot 894 still has it enabled by default. You can also create a string value "enable"="true" in the registry at HKCU\Software\Mumble\Mumble\shortcut\windows\xbox to enable it again.

I'll dig deeper once my christmas schedule allows. :-)

**Comment by mkrautz** [comment]
Here's a quick reg file to enable it for snapshots newer than 894:
http://mumble.info/~mkrautz/mumble-enable-xboxinput.reg

**Comment by WydD** [comment]
It seems to work alright!
You don't know but you actually changed my daily life (a bit) :)

Thanks again!
