### ISSUE TITLE
On Linux, Mumble doesn't use the default device (e.g., Jack)

### ISSUE THREAD

**Issue by buckwangs** [mumble-voip/mumble#1997]
I'm currently on Fedora 22. I use both Pulseaudio and Jack sound servers and Mumble works great with either. In Phonon, I've selected Jack as the default device (if it's running) and when Jack is running, all applications know to use it _but_ Mumble never uses it.

In Mumble, I can select system = Pulseaudio and I have 3 devices listed. Default, Built-in Audio, Jack.  I was hoping choosing "Default" would help Mumble go through Jack when it's running but it still insist on using Built-in Audio every time. I can select Jack as the input/output in pavucontrol and Mumble will work with Jack.

Mumble I don't believe is honoring the default device :(

**Comment by Natenom** [comment]
Mumble doesn't have support for Jack and Phonon. Regarding Jack support there is an open PullRequest, see https://github.com/mumble-voip/mumble/pull/137.

**Comment by buckwangs** [comment]
I'm sorry, I don't understand how Mumble doesn't have support for Jack. If Jack is running, Mumble offers me an option to use it. If I were to choose Jack, Mumble will work with it. If I didn't choose Jack from Mumble but left it at "pulseaudio = default" and changed the input/output for Mumble from pavucontrol to Jack, Mumble will work just fine with it.

From a users pov, Mumble works with Jack no problem. The only issue I've noticed is Mumble doesn't automatically use Jack when it's the default device (every other app does). I can manually make it work in a heartbeat but I'd rather skip that beat, it's a pain :(

**Comment by mkrautz** [comment]
@buckwangs Just to confirm, you're using the PulseAudio audio system in Mumble? If that is the case, setting the default Pulse device would make Mumble honor that.

As @Natenom says, Mumble doesn't have native Jack support. But there is an open PR.

**Comment by Krzmbrzl** [comment]
Mumble has added support for JackAudio in the meantime so I assume this issue to be fixed by now...
