### ISSUE TITLE
Support Wanted

### ISSUE THREAD

**Issue by Dsranieri** [mumble-voip/mumble#2014]
I have an unlimited mumble service paid in full for one year. I can not get open tickets supported.
I can not use the viewer 
I can not use the restart function
I can not edit my title
I can not download invoice.
Have been asking for help for weeks, no answer.
I get messages that the price is going in in 2016 but not to worry it won't affect free mumble users.

Now do I have to file a complaint with my federal credit union to get support?

**Comment by nicolasjoly** [comment]
Sadly for you, this is a free and open source software as stated on the top left of this page : http://wiki.mumble.info/wiki/Main_Page

You will have to contact the hoster you paid to get service. Issues here are for problems with source code and not hosters, you're really not at the right place. If you don't like your hoster, you can simply download the server from the main page and install it on your computer. This program is literally free. What logic led you to complain here and not the place where you paid for a service?

**Comment by Dsranieri** [comment]
I was thinking this was for the service named gotmumble.com I am sorry 
for the misunderstanding

**Comment by mkrautz** [comment]
Sorry for the trouble you're seeing. Hope you can resolve it with your provider.

I will close this for now, as it is not related to the Mumble open source project.

Happy holidays from the Mumble team.
