### ISSUE TITLE
Mumble client crashing on startup with version 1.3.894

### ISSUE THREAD

**Issue by Geraner** [mumble-voip/mumble#2016]
When using version 1.3.894, the mumble client is crashing on startup.
Error message: Mumble - Low-latency VoIP client has stopped working.

Windows 7, 64 bit.
Using client package "mumble-1.3.0~894~gabdb500~snapshot.msi".

I have no issues when using Windows x64 version for Mumble instead. (mumble-1.3.0-894-gabdb500-snapshot.winx64.msi) Mumble is starting without any problems.
Looks like this issue applies only on the 32bit version of Mumble 1.3.894.

Logfile from UserProfile/AppData/Roaming/Mumble added to issue.
[Console.txt](https://github.com/mumble-voip/mumble/files/71523/Console.txt)

**Comment by Geraner** [comment]
No issues when using Windows x64 version for Mumble instead. (mumble-1.3.0-894-gabdb500-snapshot.winx64.msi) Mumble is starting without any problems.
Looks like this issue applies only on the 32bit version of Mumble 1.3.894.

**Comment by Geraner** [comment]
[Console.txt](https://github.com/mumble-voip/mumble/files/71501/Console.txt)
Logfile from UserProfile/AppData/Roaming/Mumble added to issue.

**Comment by Geraner** [comment]
Work-Around for users of Win32bit installer version, has been posted:
http://www.mumblesverige.se/client-crashing-in-snapshot-version-894/

**Comment by mkrautz** [comment]
Sorry. Looking into this.

**Comment by mkrautz** [comment]
We're doing a new snasphot with https://github.com/mumble-voip/mumble/commit/fe81316f383b329a10e131d7bea3fc6be9eda464 included, disabling XboxInput by default.

Until then, you can use the following registry fix to disable XboxInput on affected versions:
http://mumble.info/~mkrautz/mumble-disable-xboxinput.reg

Thanks...

**Comment by hacst** [comment]
Not resolved yet unfortunately

**Comment by Geraner** [comment]
Uninstalling Mumble Client from computer.
Installing Client version .895 32 bit version.
After client start, the Mumble Crashreport Window comes up.
Same problem when using installer for .895 64 bit version.
When instead using installer .894 64 bit version, and updating after first start to version .895, Mumble is starting normally.
Console.txt and Mumble Dump file added to post.
[Mumble895.zip](https://github.com/mumble-voip/mumble/files/71939/Mumble895.zip)

**Comment by hacst** [comment]
@Geraner  The crashreport window is supposed to come up when the client crashed in the last run. It shouldn't reappear after a successful run.
