### ISSUE TITLE
Linux (PulseAudio/ALSA) - 905 - Loss of output audio after a while

### ISSUE THREAD

**Issue by JoelTroch** [mumble-voip/mumble#2040]
Fresh install of Ubuntu MATE 15.10 Wily Werewolf AMD64.
Client is using latest snapshot version (1.3.0~905~)
Server is using 1.2.10 hosted by an Ubuntu Server 13.10, can't update any of them because my server is hosted by a MSP (Mumble Server Provider).

Terminal output:
```
G15LCDEngineUnix: Unable to connect to G15Daemon.
CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
CELT bitstream 80000010 from /usr/lib/mumble/libcelt0.so.0.11.0
Theme: "Mumble"
Style: "Dark"
--> qss: ":builtin/themes/Mumble/Dark.qss"
Locale is "fr_FR" (System: "fr_FR")
Database SQLite: "3.8.11.1"
Overlay: Listening on "/home/joeltroch/.MumbleOverlayPipe"
Updating application palette
GlobalShortcutX: Using XI2 2.3
AudioInput: 27160 bits/s, 48000 hz, 480 sample
PulseAudio: Starting input alsa_input.usb-046d_081d_113B4B90-00.analog-mono
PulseAudio: Starting output: alsa_output.pci-0000_00_1b.0.analog-stereo
AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
AudioOutput: Initialized 1 channel 44100 hz mixer
warning: The VAD has been replaced by a hack pending a complete rewrite
```

Nothing interesting in log window.

This happen with both PulseAudio and ALSA, the sound/mic settings in Ubuntu are correct and aren't changed.

The issue is that after 5-10-15 minutes, I can't hear anyone anymore, their icon don't switch to the green face when they are talking, they can still hear me if I talk but if I want to hear them again, I need to restart Mumble (on rare occasions, I have to open the MATE System Monitor and close the mumble process because it doesn't close entirely).

UPDATE: After I reported this issue, my Mumble configuration isn't saved when I start it normally, forcing me to run it as superuser with ``sudo``.

**Comment by hacst** [comment]
#2007 and #1968 might be related. Try forcing TCP to verify.

**Comment by JoelTroch** [comment]
Confirming that forcing TCP seems to solve this issue.

**Comment by JoelTroch** [comment]
Closing this issue because I'm on KDE instead of MATE. If anyone has this issue with a Linux distro with the MATE desktop, feel free to re-open.

**Comment by JoelTroch** [comment]
Please ignore my statement about MATE, the issue also appeared on KDE, LXDE (but I had to wait like hours for it to happen)
