### ISSUE TITLE
Windows: UI becomes unresponsive after using menus or preferences dialog

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#2041]
Since 1.2.12, the Mumble UI has started behaving in a laggy manner. Every time you use a menu, the preferences dialog, or another dialog pops up, the UI becomes unresponsive and UI elements take their sweet time to render. I can replicate this in the daily snapshot builds as well. 1.2.11, however, doesn't have this problem at all which makes it the only build I can use at the moment.

My hardware is an Intel/Nvidia combo. I'm running Windows 10 Pro 64-bit.

**Comment by Hautausurakoitsija** [comment]
Aaaand this is seems to be linked to Windows element scaling, if the element scale value is set to something else than 100 %, 125 %, 150 % etc.

**Comment by Hautausurakoitsija** [comment]
Scratch that, the interface seems to hang regardless of element scaling.

**Comment by fwaggle** [comment]
I was about to say, I can't get my Mumble to behave this way regardless of element scaling - Windows 10 Pro 64-bit, just installed 1.2.12, Intel/Nvidia as well.

**Comment by mkrautz** [comment]
1.2.11 and 1.2.12 use the same buidlenv on windows, so no underlying deps changed.

So the culprit should be in https://github.com/mumble-voip/mumble/compare/1.2.11...1.2.12

@Hautausurakoitsija Does it perhaps only slow down when there is a lot of "log spam" - lots of text messages, user state changes, etc?

Then it could perhaps be https://github.com/mumble-voip/mumble/commit/1a4ae8deddc9c833ee276cbbb08bd19940e2840c

**Comment by mkrautz** [comment]
But that commit is *not* in 1.3.0. So I am not sure what is going on...

**Comment by mkrautz** [comment]
@Hautausurakoitsija Are you still experiencing these problems? And it only happens on 1.2.12 and 1.3.0 -- not 1.2.11?

I have a hard time reproducing this.  Would it be possible to record this sluggish UI with a screen recorder?  I'd like to see how it looks, maybe that can give us more hints.

**Comment by Krzmbrzl** [comment]
I didn't see this happening with 1.3
