### ISSUE TITLE
Launchpad mumble build failed

### ISSUE THREAD

**Issue by Hannobal** [mumble-voip/mumble#2047]
Hi,

seems that building Mumble under Ubuntu 15.10 (Wily) failed in Launchpad, because the package g++-4.6 is no more available under 15.10.

Build log: https://launchpad.net/~mumble/+archive/ubuntu/release/+build/8743347

**Comment by mkrautz** [comment]
Should be fixed by https://github.com/mumble-voip/mumble-ubuntu-ppa/commit/6158b11b92b6f7a103bc88b41450541c9137c3c6, I hope.

Waiting to see if it builds...

**Comment by mkrautz** [comment]
New failure:

https://launchpadlibrarian.net/232167985/buildlog_ubuntu-wily-amd64.mumble_1.2.12-1~ppa2~wily1_BUILDING.txt.gz

libspeechd package b0rked?

**Comment by mkrautz** [comment]
Now fixed:
https://launchpad.net/~mumble/+archive/ubuntu/release/+build/8767829
