### ISSUE TITLE
Small Notification number in tray icon symbol

### ISSUE THREAD

**Issue by dede321** [mumble-voip/mumble#2050]
Hey, 

First of all, great project! I would like to replace Skype by Mumble for text messages as well as for voice chat. Is it possible that you include a small notification number in the tray icon symbol?

I use Win10, if someone writes a text message in Mumble, a notification window popups for a very short time. Suppose you are AFK and your friend writes: You return after a few minutes (friend gone afk in the meanwhile as well) and since there is no indication (no tray icon symbol change or persistant notification popup) you won't notice that there is message until you manually check the notification center.

Is there maybe a workaround for this?

With best regards,
dede123

**Comment by mkrautz** [comment]
I think old notifications may still appear in the notification center in Windows 10?

**Comment by dede321** [comment]
And this is exactly what one needs to manually open/check. Hence one may not notice that there is a new message.

**Comment by mkrautz** [comment]
How would this "notification badge" work. I get that if you get a notification while your computer is idle, it will count up.

How will you clear it?

**Comment by dede321** [comment]
If I were able to, I would count it up as soon as Mumble is not the active Window.
Once you activate the Mumble window, the counter could be cleared. Similar like it is the case in Skype

**Comment by JoelTroch** [comment]
:+1: for this, the counter isn't a big deal IMHO, it would be just "bonus"

**Comment by davidebeatrici** [comment]
Related: #3283

**Comment by Krzmbrzl** [comment]
Imo #3283 (which has been integrated in the meantime) is enough for the main purpose of this issue. Thus I'll close this issue. If someone considers the actual counter to be essential, let me know
