### ISSUE TITLE
Missing RPC functionality

### ISSUE THREAD

**Issue by lmoe** [mumble-voip/mumble#2051]
I was thinking about implementing Mumble into an application I'm currently writing on.
The basic idea is to control and gather data from Teamspeak and Mumble via RPC.

I want to display a list of channels, the connected clients and display their talking status. I want to react on a new server connection, maybe connect to a new server remotely, mute or deaf the client and switch to other channels.

With Teamspeak this is pretty straightforward. There is a plugin SDK which gives you everything you need. You can grab the SDK here: https://www.teamspeak.com/downloads

The SDK offers a lot of features including controlling of the local client and events you can listen on. Example events are:
- Connecting to a server which returns the IP and port. 
- Switching to another channel
- Changing talking status of each client

and so on.

This allows a third party developer to do a lot of neat things and makes it very easy too! In this case you have to write the RPC code on your own as the plugin SDK only offers access to the functions of Teamspeak.

Sadly there is no functionality for this use case for Mumble which makes it hard to do what I want to do. 

Basic RPC functionality is already implemented in the SocketRPC class and offers some of the features I would require. I think this should be extended further - maybe as a JSON RPC ? - so third party developers can integrate and control mumble from their applications too. 

I believe this could also help making Mumble more wide spread as other developers can adapt the functionality in an easy way.

I don't think this idea is too hard to implement. I would even offer to help if there is any need.

**Comment by mkrautz** [comment]
Sorry for not responding earlier.

This is something I would very much like Mumble to have.

We need to figure out a suitable transport to use. Something that potential users can integrate with without too much trouble...

**Comment by lmoe** [comment]
All good.

The problem I see, is that you can start mumble multiple times. That prevent us from opening one simple port everyone could listen to - except we have some kind of shared server which manages all instances on one port.

We could use socket files, but this would bring some trouble to the adaptors. 

On the other hand we could configure to use a specific port range, or set the port as a command line arg. But then everyone would have to manage the ports by themselfes which is not really that great either.

I think choosing the right transport method is one of the trickiest parts, as a stateless JSON RPC is not really that hard to implement, and all languages would be able to support it. 

Does mumble have a shared space between multiple instances already?

**Comment by mkrautz** [comment]
I wouldn't worry about that.

Running multiple clients is not a supported configuration, and has all sorts of race conditions already.
(Configurations being potentially overwritten, overlay not working, etc.).

The overlay and SocketRPC are the best examples. They also break when multiple instances are running.

> Does mumble have a shared space between multiple instances already?
Nope.

**Comment by lmoe** [comment]
I don't see any reason to run multiple connections though, just wanted to keep that in mind.

So at the end we could simply open a port, and make it available for everyone. 

- Should we define internal API keys to make it more secure?
- Should the API also include streaming output/input data?
- JSON, XML, both? -> Would use JSON as it's easier to manage.
- Keep-Alive connection, or call per request? -> Would use a Keep-Alive connection to receive events

**Comment by mkrautz** [comment]
For any onlookers: we discussed this a bit on IRC... Discussion hasn't stalled...

**Comment by Krzmbrzl** [comment]
I would also be interested in whether this is still being worked on.

Also if one starts implementing this kind of thing, would it be a good idea to try to overtake the TeamSpeak API as a whole? I could imagine that this would make it very attractive for TeamSpeak developers to (also) port their code to mumble which I'd count as a clear win.
But I don't know whether that is even feasable...

**Comment by Krzmbrzl** [comment]
Also is the whole gRPC-thing related to this? It seems like it to me, but I'm not quite sure.

The issues I found on this:
- https://github.com/mumble-voip/mumble/issues/1196
- https://github.com/mumble-voip/mumble/issues/3429

And this is the associated (still open at the time of writing this) PR:
- https://github.com/mumble-voip/mumble/pull/3480

**Comment by Krzmbrzl** [comment]
Referencing this to #3743
