### ISSUE TITLE
Push-to-talk doesn't work on keyboard MAC OSX

### ISSUE THREAD

**Issue by LushBushs** [mumble-voip/mumble#2057]
Yea,  it doesn't work when I try to set it on my keyboard.

**Comment by mkrautz** [comment]
What version of Mumble are you on? What version of OS X?

On 1.2.12 and later (but not yet snapshots, that is, 1.3.0) should show the following message when you visit the Shortcuts section of the config dialog. However, it may only show when you have turned "advanced mode" on -- or you may have dismissed the text by clicking "skip".

Here's what to do to fix your issue:

---BEGIN QUOTE---

Mumble can currently only use mouse buttons and keyboard modifier keys (Alt, Ctrl, Cmd, etc.) for global shortcuts.

If you want more flexibility, you can add Mumble as a trusted accessibility program in the Security & Privacy section of your Mac's System Preferences.

In the Security & Privacy preference pane, change to the Privacy tab. Then choose Accessibility (near the bottom) in the list to the left. Finally, add Mumble to the list of trusted accessibility programs.

---END QUOTE---

Hope it helps.

**Comment by mkrautz** [comment]
No response. Closing this.

If the problem persists, please reopen! Thanks!
