### ISSUE TITLE
Images crash and freeze linux

### ISSUE THREAD

**Issue by ogbaba** [mumble-voip/mumble#2058]
Hello, I'm running fedora 23 and Mumble version 1.2.11 and when someone messages an image, it freezes my whole computer and I have to restart. I haven't managed to see the log.

**Comment by fedpop** [comment]
I'll take a look on vacation for a few more days though.

**Comment by baptistepouget** [comment]
It seems its not everytime someone sends an image, only when the image is big (i'm not 100% sure)

**Comment by fedpop** [comment]
You are using it from the fedora repository, i.e. dnf install mumble, right?

**Comment by baptistepouget** [comment]
Yes

**Comment by baptistepouget** [comment]
Here is something I grabbed from the terminal, a freeze occured and I managed to recover clicking the notification ant alt+f4ing many times
[mumbleLog2.txt](https://github.com/mumble-voip/mumble/files/77170/mumbleLog2.txt)

**Comment by fedpop** [comment]
Can you post the image that causes the crash, the client version and OS that the sender is using, and the version of the server?

I can't replicate this using only Fedora.

**Comment by baptistepouget** [comment]
I don't know the server version neither the client version the senders are using but they are on windows 7 and 10 so i would say they use the latest mumble version. By the way I haven't had this bug since i disabled notifications in mumble settings :octopus:

**Comment by mherweg** [comment]
I have the same bug on Linux Mint "rafaela" with cinnamon desktop.

**Comment by Krzmbrzl** [comment]
Does this still happen with Mumble 1.3?
