### ISSUE TITLE
Some Mumble build environment paths exceed MAX_PATH

### ISSUE THREAD

**Issue by NoAglets** [mumble-voip/mumble#2061]
Lengths of Windows pathnames are expected to be less than _MAX_PATH (260) bytes allowing for the trailing terminating zero byte.

Four pathnames are too long:

263 bytes:
C:\MumbleBuild\win32-static-debug-1.3.x-2015-12-30-1ca3f3d-587.build\qt-everywhere-opensource-src-5.5.1\qtwebengine\src\3rdparty\chromium\third_
party\WebKit\Tools\Scripts\webkitruby\check-for-inappropriate-macros-in-external-headers-tests\resources\Fake.framework

267 bytes:
C:\MumbleBuild\win32-static-debug-1.3.x-2015-12-30-1ca3f3d-587.build\qt-everywhere-opensource-src-5.5.1\qtwebengine\src\3rdparty\chromium\third_
party\skia\experimental\expectations\skp\Test-Mac10.8-MacMini4.1-GeForce320M-x86_64-Debug\renderskp-deferImageDecoding.json

269 bytes:
C:\MumbleBuild\win32-static-debug-1.3.x-2015-12-30-1ca3f3d-587.build\qt-everywhere-opensource-src-5.5.1\qtwebengine\src\3rdparty\chromium\third_
party\WebKit\Tools\Scripts\webkitruby\check-for-inappropriate-macros-in-external-headers-tests\fake-data-failing-expected.txt

276 bytes:
C:\MumbleBuild\win32-static-debug-1.3.x-2015-12-30-1ca3f3d-587.build\boost_1_59_0\libs\geometry\doc\html\geometry\reference\spatial_indexes\boos
t__geometry__index__rtree\rtree_parameters_type_const____indexable_getter_const____value_equal_const____allocator_type_const___.html

**Comment by mkrautz** [comment]
Can you explain how this affects you? Other than it being obviously bad.

I see no ill effects in my builds.

**Comment by NoAglets** [comment]
I cannot tell if it poses a direct problem within Mumble but a real issue is a possible buffer overrun in any application that tries to use these pathnames. Also, it would be very difficult to access these files from the command line.

**Comment by hacst** [comment]
Those files aren't actually used by us during the build though so I don't think we have to do anything about it. ```MAX_PATH``` is the epitome of legacy cruft and I'm for ignoring it where one can get away with it ;)

**Comment by Krzmbrzl** [comment]
Given that there aren't any noticeable effects and in the hope that Windows has removed that silly restriction at some point, I'll close this issue
