### ISSUE TITLE
Current snapshot authenticode signature not valid on XP

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2065]
When checking out

https://github.com/mumble-voip/mumble/issues/1330

I stumbled upon the fact that (on Windows XP SP 3):

1. When running the .MSI, it told me it was by "Unknown Publisher" (i.e., the signature was bad)
2. When checking the installed files, it says the signature is invalid. (Cert chain is good, though!)

This happens now because we've done away with nested signing SHA1 and SHA256 certs and signatures. (Our SHA1 cert expired on 31 Dec, and SHA1 code signing was deprecated on Jan 1 2016.)

Our certificate is SHA256, but the hash we sign is also SHA256. Perhaps XP does not like that.

I will try an experiment:

Re-introduce nested signatures.

The initial signature will now be:
SHA256 certificate, but the signature will be a signed SHA1 digest.
Nested signature will be:
SHA256 certificate, but the signature will be a signed SHA256 digest.

Perhaps this works better on the older OSes.

Now, some might read this and think "XP, really"? But we have quite some users on XP still, and this issue is presumably not restricted to XP -- it's likely that Vista is also affected. Who knows.

I will try the aforementioned experiment and update this issue with the results once we know more...

**Comment by funkydude** [comment]
Vista is not affected by this. Even if it was, it's dead, and is less of a consideration than XP is (stats everywhere support this).

Is there actually a downside to using nested signatures? The hard deadline for SHA1 is 2017, so might as well do it for another year before calling it a day. Hopefully by then XP will have reduced more.

**Comment by mkrautz** [comment]
SHA1 is deprecated for Authenticode. As the start of the year:
http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx#H1_A

**Comment by mkrautz** [comment]
Works.
