### ISSUE TITLE
Which is the correct license?

### ISSUE THREAD

**Issue by darklie** [mumble-voip/mumble#2071]
In https://github.com/mumble-voip/mumble/blob/master/LICENSE , the license of mumble looks like new BSD license, but the installer shows GPLv2 as the Mumble's EULA.Which is the correct license?
![mumble](https://cloud.githubusercontent.com/assets/12250058/12384849/c00ad728-bdf9-11e5-9473-52d650d0dd55.png)

**Comment by mkrautz** [comment]
The GPL in the installer is from when Qt was licensed under GPLv2 - so the combination of Mumble and Qt would have to be GPL licensed.

Now, Qt is under LGPL 2.1/3.

For other GPL'd software, we have a license exception (I.e. ZeroC Ice)

We should be able to ship Mumble's BSD license along with a trail of all third party licensing to make the licensing situation as seen through the installer a bit less confusing.

So: Mumble's source is under a BSD license. I don't believe we have GPL'd dependencies that force the final Mumble distribution to be distributed under the terms of the GPL anymore.

**Comment by hacst** [comment]
@mkrautz We should drop that page from the installer in any case. The GPL doesn't require it and it might scare people off even when with mumble the restrictions of the GPL on the installer are pretty much meaningless (we'll still have to put a license somewhere obviously).

That being said it makes my brain hurt even trying to figure out what the binary distribution is licensed under.
* ZeroC is GPL but we have a license exception.
* The mysql client stuff is GPL but we use it through Qt and should additionally fit their Open Source license exception
* We statically link with Qt which is LGPL but that shouldn't really mean anything as the user can "relink" (read self-compile) removing the need for us to also be LGPL
* ...

**Comment by mkrautz** [comment]
> For other GPL'd software, we have a license exception (I.e. ZeroC Ice)

Update: We don't have a license exception for Ice. I took a closer look at the license.
The combination of Murmur + Ice is still GPL'd.

**Comment by davidebeatrici** [comment]
I agree with @hacst, we should drop the license page from the installer.

**Comment by hacst** [comment]
Is this actually a blocker? What's our todo here? Just remove the page? Looking at the installer I see it installing license files for speex etc. which have not been touched in a while. Is this redundant with our license dialog or actually required and must be updated?
