### ISSUE TITLE
Using an external IP from within the network causes extreme latency

### ISSUE THREAD

**Issue by PiercingGoblin** [mumble-voip/mumble#2075]
I have a murmur server hosted on 192.168.1.202, and a client running on 192.168.1.201. When I attempt to connect to the server (.202) using it's internal address, it connects and all is well. However, if I either use the domain name that points to my external IP, or I use the external IP itself, I am able to connect, but all other connections on the CLIENT drop / slow to a halt. Mumble must be doing something strange with how it attempts to resolve the IP.

Steps to reproduce:
1) Have a client / server on the same local network
2) Have a router that supports NAT Loopback (so you can reference your external IP from within the network)
3) Attempt to connect to the local server using the external IP (port forwarding necessary)
4) Observe that the client machine cannot access web pages / the audio quality in mumble is incredibly low.

**Comment by davidebeatrici** [comment]
With #2928, this shouldn't be an issue anymore.
