### ISSUE TITLE
SSL Version Mismatch

### ISSUE THREAD

**Issue by bddenhartog** [mumble-voip/mumble#2076]
Running into an issue using murmurd inside a docker container. Upon connecting, I receive an **SSL Version Mismatch** dialog window, and I'm having trouble resolving it.

![2016-01-19__20 15 27](https://cloud.githubusercontent.com/assets/3893293/12439820/2c003f18-beea-11e5-9b4d-e7df71e286dd.png)

The OS inside of the docker container is `Alpine Linux 3.3`. The repo for the container is here: [bddenhartog/docker-murmur][1].

My local machine is running `Ubuntu 14.04` (same as the remote server); the latest available version of the Mumble client is `1.2.12-1~ppa3~trusty1` from `http://ppa.launchpad.net/mumble/release/ubuntu/ trusty/main`, which I have installed. The version of `murmurd` running inside of the remote container is `1.2.10`. The remote host is using NGiNX to `proxy_pass` a port to the container, and that looks to be working without issue, as I can attempt to connect successfully -- I just receive this **SSL Version Mismatch** error.

**NOTE**: If I run the container on my local machine, I can connect without issue. The local and remote machine is effectively the same; the container OS is the same in both instances. That is why this is so puzzling for me.

I've looked around the web in order to attempt to resolve this to no avail. I'd appreciate any input you can provide.

[1]: https://github.com/bddenhartog/docker-murmur

**Comment by mkrautz** [comment]
This is in fact just the error the client presents when a SSL handshake error occurs:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/MainWindow.cpp#L2840-L2841

Have you looked at the Murmur log?

I am not sure what you're doing with nginx's proxy_pass. Are you using that with Murmur? Looking at the nginx docs, proxy_pass only works with http or https. Murmur isn't http based, so if you're using it with Murmur, that will probably be troublesome.

**Comment by bddenhartog** [comment]
@mkrautz Thank you for your insight. What a silly mistake! I can successfully connect to `ip-address:64738`.

Here's what I'm trying to accomplish:

- Run murmur in a docker container on the host, using the `-p A:64738` option to forward "port A" from the host to port 64738 inside of the container, which is what murmur is running on.
- Use nginx to assign a hostname for that container, and forward `Port X` to `Port A`, allowing users to connect to `somedomain.com:X` in the Mumble client, when in reality they are being sent to `somedomain.com:A`.
- The end goal is to be able to use a variety of psuedo ports with the same hostname while forwarding the requests to the proper docker container.

Below is a simplified version of my nginx server block file. Remember that at this point, I have a docker container running murmur, and the host's port `1234` is mapped to the container's port `64738`. I can connect successfully to `ip-address:1234`, but I want to be able to connect to `somedomain.com:1337`.

```
server {
    listen 1337;
    server_name somedomain.com
   
    location / {
        proxy_pass 127.0.0.1:1234
    }
}
```

I realize that this is a bit out of the domain of this project, but I'm confident you understand how to best accomplish this goal much better than I.
