### ISSUE TITLE
Overlay doesn't work in Lineage II

### ISSUE THREAD

**Issue by Tacejibxob** [mumble-voip/mumble#2078]
We use a voice server mumble for playing Lineage II , a very handy thing. But there is a problem with the configuration of the substitution. My friends are no problems with the replacement on the server which we play.
When exposed replacement knocks Crete. 
![image](https://cloud.githubusercontent.com/assets/16819441/12483079/13229a60-c064-11e5-9954-8c0cdee18a28.png)

I use Windows 10x64, SonyVaio laptop video card AMD Radeon HD 7500М/7600M Series 
![image](https://cloud.githubusercontent.com/assets/16819441/12483063/ffe431b6-c063-11e5-8c21-780414a91fca.png)

 A lot of advice from the Internet I tried. And changed the driver for the graphics card and tried to put DirectX. (Windows automatically updates itself) .
![image](https://cloud.githubusercontent.com/assets/16819441/12483097/1f9082a8-c064-11e5-8514-5ee0a9600180.png)

 And were running everything from the administrator. And disable DEP.Had disabled antivirus. Also tried to make the game too slow using using OpenGl not DirectX (really don't know how but there was a Board on the Internet) . Change client version from 1.2.2 to 1.2.13. Only happened once to start with replacement of the game on the client Mumble 1.2.6 played a day then the PC stopped responding, everything is reset again and the problems started. Repeated again similar, but the effect no longer occurred.

**Comment by mkrautz** [comment]
Try disabling the overlay in Mumble.

Settings -> Overlay -> Uncheck "Enable Overlay" and log out of your user, and log in again -- or restart the computer.

**Comment by Tacejibxob** [comment]
Yeah after that the game starts to work. But the function of substitution the right thing for me, so I described this problem to you.

**Comment by mkrautz** [comment]
@Tacejibxob I assume "substitution" means "overlay"? :-) I have updated the title to reflect that.

**Comment by Tacejibxob** [comment]
Yes, all right. I'm terrible with English and therefore use interpreters.

**Comment by Tacejibxob** [comment]
I hope you have not forgotten me?

**Comment by Tacejibxob** [comment]
I noticed a trend, if mumble does not run from the administrator , on servers with poor protection all starts to work (run the game from the administrator) on the server with a good protective stops. But my friends, such changes do not occur and everything works fine. The only changes that I noticed between us is build PC.

**Comment by mkrautz** [comment]
Yes, currently, the overlay only works if you don't run Mumble as administrator.
The reason is, if Mumble is run as administrator, the shared memory segment it creates will be owned by the administrator, and the game, running as a regular user, can't access it.

**Comment by ZeroAbility** [comment]
Is this still occurring? The first screenshot you posted looks like it didn't find the Direct3D render device on your system. It also detected your OS as Vista when you stated you were running Windows 10. It also didn't seem to detect your video card. This sounds like an issue with the application that gave you the error.
