### ISSUE TITLE
Make channel description editor display raw HTML

### ISSUE THREAD

**Issue by ReekyMarko** [mumble-voip/mumble#2080]
I don't know if this is a bug but it certainly feels like one!

I just wasted 10mins of my life because I assumed the "source code" tab in channel description editor was supposed to be about being able to write the description the way you want using HTML. After I submitted my code there and pressed OK, it removed all the headers and CSS styling I had written and replaced all of the elements with `<span>` tags.

This would be managable but when I tried to edit the <span> tags with extra styling (e.g. text-alignment:center;) it just ignored the values and deleted them >:(  (and they were written right, tried multiple times)

**Comment by ReekyMarko** [comment]
And by the way I'm running the 1.3.0 snapshot if that matters

**Comment by mkrautz** [comment]
@ReekyMarko Mumble doesn't support full HTML for messages, but you should be able to use some things.

But I believe what you're saying is that Mumble mangles or rewrites the HTML you give it, puts extra style attributes on the tags, and so on. Is that correct?

**Comment by ReekyMarko** [comment]
Sorry if the post was unclear, github removed span tags in brackets :P 

Didn't know that it doesn't support full HTML o.0
But the server supports it in welcome text. In mumble-server.ini I wrote a full HTML page and it displayed just fine on my Mumble client.

And yes, it does rewrite my html. For example if the "Source Text" tab displays span style="color:#ff0000;" and I change it to span style="color:#ff0000;text-alignment:center;" it just ignores the modification and removes it...
