### ISSUE TITLE
[Linux] Display issues with Enlightenment 20

### ISSUE THREAD

**Issue by JoelTroch** [mumble-voip/mumble#2081]
When you start Mumble, Enlightenment 20's task bar start flashing very quickly (imagine that you have an application that open and closes every 0,01 second infinitely). It also take a lot of time to show the connect dialog (like 5 minutes) and not the main window. According to `htop`, there is a heavy CPU usage during the startup process. 
Sometimes, it can cause a segmentation fault in Enlightenment 20.

First setup used to have this bug :
- Fresh minimal install of Ubuntu 15.10 Wily Werewolf AMD64 in UEFI.
- Enlightenment 20 installed from this [PPA](https://launchpad.net/~niko2040/+archive/ubuntu/e19).
- Latest snapshot version of Mumble.

Second setup used to have this bug :
- Fresh install of Arch Linux (1st January 2016) x86_64 in UEFI.
- Enlightenment 20 installed from Arch's official repository.
- Latest snapshot version of Mumble.

To reproduce :
- Install Enlightenment 20 on any Linux distro.
- Start Enlightenment 20.
- Install and start Mumble.
- Enjoy the bug.

Notes :
I have disabled everything related to compositor effects and I'm using Software rendering in Enlightenment (instead of OpenGL).

Workaround :
Kill `enlightenment_start` with the SIGSEVG (code = 11, Segmentation fault) signal when starting Mumble, when the X server show the little window that Enlightement 20 had a problem and you have the choice between "Recover (F1)" and "Logout (F12)", select "Recover (F1)".

**Comment by TurBoss** [comment]
same here, restart enlightenment leaves the client open

**Comment by Teteros** [comment]
Still occurs if anyone's wondering.
However [forostm's patch](https://gist.github.com/forostm/79967fd973ae833bfc2ae2886d2947d2) in #2192 fixes this completely so it's not a big deal.

Linux 4.7.1-1-ARCH
E21.99 (efl-git, enlightenment-git)

**Comment by davidebeatrici** [comment]
Fixed by #2552.
