### ISSUE TITLE
How can I edit the default Mumble - Dark theme?

### ISSUE THREAD

**Issue by bamtan** [mumble-voip/mumble#2083]
I can seem to find the dark.qss file, where is it located?

Thanks again:-)
bamtan

EDIT: Managed to edit MetroDark.qss and move it into the new "Themes" folder, everything seems to be working now.

**Comment by mkrautz** [comment]
In case anyone else is looking for the answer to this:

The source code to the themes is available here:
https://github.com/mumble-voip/mumble-theme
