### ISSUE TITLE
No audio output to headset in Windows 10

### ISSUE THREAD

**Issue by craxal** [mumble-voip/mumble#2084]
I've tried countless attempts in Windows 10 to get Mumble 1.2.13 to work with several pairs of headphones (one with a standard audio jack, the other a wireless USB headset). The microphone works perfectly.

The only workaround that seemed to work was to run Mumble in Windows XP SP3 Compatibility Mode and switching off positional audio. The forums are littered with people complaining about the same problem. I hope someone plans on investigating this issue.

**Comment by mkrautz** [comment]
I believe this is already fixed if you try our snapshot builds. The bug is, that the 1.2.x series only support the WASAPI audio engine with float samples, yet many USB devices want to use signed 16-bit samples.

Please try a snapshot build and report back if it works, thanks!

Snapshots are available at https://www.mumble.info (Development Snapshots, 1.3.0)

**Comment by mkrautz** [comment]
I realize your issue also mentions headphones that use regular audio jacks -- so the issue might not be the above.

Can you point me to forum posts that mention this issue? The forum issues I have seen recently have all been about USB headsets, which would be the aforementioned bug.

**Comment by ElPumpo** [comment]
I swear people who open a issue and don't responde. I say close the issue. Works for all my friends and me running W10 with both usb and jack drivers

**Comment by craxal** [comment]
I apologize. I'm fine with the issue being closed for now. I haven't been experiencing problems lately. Audio in general seems to be a very difficult thing to get to "just work" on Windows.

**Comment by mkrautz** [comment]
FWIW, the aforementioned float/WASAPI issue has been fixed in more recent 1.2.x builds, so I don't think this should be an issue any longer.

If you have new problems, please file a new issue. Thanks! :-)

**Comment by ElPumpo** [comment]
well this is only the beginning, there's a lot of old issues. I do not think that all 510 issues are active.
