### ISSUE TITLE
Logitech C270 Webcam microphone does not work at first Mumble start

### ISSUE THREAD

**Issue by makedir** [mumble-voip/mumble#2085]
Logitech C270 Webcam microphone does not work at first Mumble start. You always have to close and re-open Mumble after a cold Windows reboot.

Windows 10 64bit
Newest trunk Mumble (never worked in older Mumble versions)

**Comment by mkrautz** [comment]
Could you provide us with a log file of a session where the microphone doesn't work?

Run Mumble (in the scenario where it does not work)
Open %APPDATA%\Mumble\Console.txt
Upload the section of the log that represents the session you just had (use the timestamps)

Thanks!

**Comment by mkrautz** [comment]
Oh, it might make sense for us to get both a non-working session, *and* one that works. If possible. Thanks!

**Comment by makedir** [comment]
Not working:
[Console.txt](https://github.com/mumble-voip/mumble/files/102343/Console.txt)

Working:
[Console2.txt](https://github.com/mumble-voip/mumble/files/102345/Console2.txt)

**Comment by makedir** [comment]
Anything new on this?

**Comment by Krzmbrzl** [comment]
Does this still happen with Mumble 1.3?

**Comment by ellegance** [comment]
Is it possible to reopen this ticket? I confirm, on first boot, and on waking from sleep, Mumble cannot use microphone of Logitech C270, only relaunch fixes it.
