### ISSUE TITLE
Can you route notifications and text-to-speech sound to a different output?

### ISSUE THREAD

**Issue by ReekyMarko** [mumble-voip/mumble#2086]
As the title says

**Comment by mkrautz** [comment]
Not currently, no.

Text-to-Speech is not handled by Mumble itself -- it's delegated to OS APIs, or, for Unix-like systems, speech-dispatcher.

Mostly, these APIs will output to the default device of the system, but I suppose it's possible in some cases to direct them to other devices.

Notification sounds are (if we're talking about the sounds from Mumble's own notifications, not any sounds the OS plays when a "native" notification appears) handled by Mumble itself, and are output to the device you've specified in Mumble.

This could also be fixed, but it would require Mumble to open more than one audio device at a time.

**Comment by ReekyMarko** [comment]
Ok, thanks for the quick response :)
