### ISSUE TITLE
can't stop the server via init scripts 1.3.0-935 linux

### ISSUE THREAD

**Issue by TurBoss** [mumble-voip/mumble#2089]
hi,
if I issue "# service mumble-server stop" nothing happends
I'm on ubuntu 14.04 lts
i have to kill all the murmurd instances by hand and then i'm able to start the server "# service mumble-server start"

thx

**Comment by mkrautz** [comment]
Just to confirm, this is with the packages from the PPA, correct?

**Comment by TurBoss** [comment]
ppa snapshots

**Comment by Natenom** [comment]
"kill -14" does the job.

**Comment by Kissaki** [comment]
I never noticed this on my server, and I definitely used `service stop/start` in the last two weeks on both Ubuntu 14.04 and 16.04, with our PPA packages.
