### ISSUE TITLE
I can't see channels in 1.3.0~941~gcffa565

### ISSUE THREAD

**Issue by tiggger** [mumble-voip/mumble#2093]
I can see the channel that I'm in, and if someone is in a channel I can see them, but only the channel.
http://puu.sh/mOETP.png here's all of us in the root. No channels are visible.
http://puu.sh/mOEXh.png here's all of us in a different channel. You can see the full tree of channels down to the root.
Same goes for anyone in any channel. Here's another example: http://puu.sh/mOF1Q.png

**Comment by mkrautz** [comment]
Are you sure you haven't enabled the channel filter? (In the toolbar)

**Comment by tiggger** [comment]
jesus christ im an idiot

**Comment by hacst** [comment]
Sounds like the issue is resolved ;)
