### ISSUE TITLE
Documentation on how to report security concerns

### ISSUE THREAD

**Issue by jmariondev** [mumble-voip/mumble#2099]
In the process of recently reporting a security concern to Mumble, I found that there isn't any published information on how or who to report security concerns to. I feel it would be beneficial to at least have a wiki page on [wiki.mumble.info](http://wiki.mumble.info/) explaining how the Mumble developers would prefer to be notified of concerns (who to email, GPG keys, expectations, etc).

**Comment by hacst** [comment]
We were just discussing this a few days ago. Good timing ;) Steps we have already taken:
* Create a security@mumble.info and ensure that we notice when it stops working

Steps we plan on taking:
* Create a shared private GPG key for security@mumble.info
* Extend https://www.mumble.info/security/ to explain the process of reporting issues including the new contact point
* Link to it from the landing page and the README

@mkrautz

**Comment by Krzmbrzl** [comment]
@davidebeatrici @Kissaki has this been done and documented yet?

**Comment by Kissaki** [comment]
I’ll assign this to myself with regard to the website content and documentation which I am working on.

I am not working on it atm though as my Mumble buildenv is more important to set up for other issues.

**Comment by Kissaki** [comment]
I added a SECURITY.md to this repository. This is also used in the Security tab of the project/repository on GitHub.

The website part is already tracked in https://github.com/mumble-voip/mumble-www/issues/28 so I will close this ticket in favor of that one. I will add the information there.
