### ISSUE TITLE
Text-to-speech doesn't work on 64-bit version of win7 1.3.0~941~gcffa565~snapshot 

### ISSUE THREAD

**Issue by trynoval** [mumble-voip/mumble#2106]
My OS is Win7 SP1 x64, text-to-speech worked on 1.2.10
I installed snapshot over stable version. All configs sucessfully migrated from stable.
Will provide any info if needed.
It seems not so important now - maybe problem is, that text-to-speech or voice pack is 32bit on my win7.

**Comment by Tarun80** [comment]
I too have noticed that sometimes, TTS does not trigger. I think it's happening when people leave/disconnect. Not 100% certain though.

**Comment by trynoval** [comment]
No, it doesn't work at all.

**Comment by Kissaki** [comment]
Can you verify its still enabled in your system audio settings, Mumble audio settings, and Mumble notification settings?

**Comment by trynoval** [comment]
Yes, it was enabled when I reported.
If you need I can install again, check and provide any additional info.

**Comment by Krzmbrzl** [comment]
Is this still the case with the released 1.3 version?
