### ISSUE TITLE
Overlay not showing (1.3.0~941~gcffa565~snapshot)

### ISSUE THREAD

**Issue by Toludin** [mumble-voip/mumble#2111]
I've not been able to get the overlay to show in any of my games so far (just recently installed the snapshot, as I know the overlay in 1.2.x doesn't work in Directx11 games).

I'm making sure to do start Mumble first, running as administrator, before launching the game. I've also rebooted my computer after installing Mumble 1.3.0.

I've tried WoW and FFXIV so far, and will try some more. Both are running in DX11. I've tried both Fullscreen and Windowed modes, and I've also tried using both the blacklist and whitelist in the overlay settings.

I also set WoW back to 32-bit and DX9, and the overlay still didn't show.

If there are any more troubleshooting or diagnostic steps I should take, please let me know! Thanks!

**Comment by mkrautz** [comment]
If you run Mumble as admin, I am not sure the games themselves will be able to communicate with the overlay. Why do you run Mumble as admin?

**Comment by Toludin** [comment]
That indeed was the problem, thanks!

Looking back, I'm not really sure exactly where I got it in my head that running as Admin was important here. I was trying to get the overlay to work several months ago (using 1.2.x) and I think somebody had suggested admin, but I can't retrace my steps to any specific suggestion now.

Thanks again!
