### ISSUE TITLE
Releases PPA one version behind

### ISSUE THREAD

**Issue by StrvnMrvn** [mumble-voip/mumble#2112]
Just an FYI, the Releases PPA is currently at 1.2.12 dated 10/28/2015

Is there a reason it hasn't been bumped to 1.2.13 or did the buildbot just take a nap?

**Comment by mkrautz** [comment]
Hi,

I believe we neglected to update the PGP keys for the PPA bot that does the uploads. Since the key is expired, the attempted uploads were rejected.

Let me fix this...

**Comment by Slyvester1** [comment]
any chance on when this well get updated? we are 3 versions behind now.

**Comment by leonmaxx** [comment]
Any news on this?

**Comment by mkrautz** [comment]
Fixed.
