### ISSUE TITLE
Murmur does not gracefully shut down when receiving SIGTERM

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#2114]
Tested on two different servers, one is Debian 7.9 and one is Debian 8.3 with the current 1.3 snapshots.

On the Debian 7.9 this happens always, on 8.3 only sometimes.

From the log:
Feb 13 23:14:29 domain.bla.com murmurd[1226]: Caught SIGTERM, exiting
Feb 13 23:14:29 domain.bla.com murmurd[1226]: Killing running servers
Feb 13 23:14:29 domain.bla.com murmurd[1226]: 3 => Removed all Ice ServerCallbacks
Feb 13 23:14:29 domain.bla.com murmurd[1226]: 3 => Stopped
Feb 13 23:14:29 domain.bla.com murmurd[1226]: 5 => Removed all Ice ServerCallbacks
Feb 13 23:14:29 domain.bla.com murmurd[1226]: 5 => Stopped
Feb 13 23:14:29 domain.bla.com murmurd[1226]: 1 => Removed all Ice ServerCallbacks
Feb 13 23:14:29 domain.bla.com murmurd[1226]: 1 => Ending voice thread
Feb 13 23:14:29 domain.bla.com murmurd[1226]: 1 => Stopped
Feb 13 23:14:29 domain.bla.com murmurd[1226]: Shutting down

Then it hangs.

**Comment by mkrautz** [comment]
cc https://github.com/mumble-voip/mumble/issues/2089

**Comment by mkrautz** [comment]
Closing this in favor of #2089
