### ISSUE TITLE
Mumble on Qt 5 on Linux crashes when using a proxy

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2115]
...but it works OK, on, for example, Windows.

**Comment by bontibon** [comment]
Tested with aa90739bfd019a5f1f34e9f2d172a477ed8da4df and Qt5 5.10.0

HTTP proxy works without crash.
SOCKS5 proxy works without crash.

**Comment by mkrautz** [comment]
Thanks. I guess they fixed it upstream.
Did you get any Qt errors/warnings because of things running on the wrong thread? I think I had that when the crash occurred.

**Comment by bontibon** [comment]
> Did you get any Qt errors/warnings because of things running on the wrong thread?

negative

**Comment by mkrautz** [comment]
Cool. Closing. :-)
