### ISSUE TITLE
Fix overlay for OpenGL on windows x64

### ISSUE THREAD

**Issue by Lou363** [mumble-voip/mumble#2117]
As I said in the title fix overlay for Windows 64bit because it is annoying as I keep advertising mumnle to my friends because the overlay and everything but they have a 64bit so it does not work :-(

**Comment by mkrautz** [comment]
Note that only our 1.3.x development snapshots (labelled "Development Snapshots" on https://www.mumble.info) have x64 support.

Can you confirm whether using those work for your use-case?  I just tried to run minecraft.exe from the Mojang site. It downloaded the x64 Java runtime, and I am running Minecraft (x64) on Windows 10 with  Mumble 1.3.0~941~gcffa565~snapshot, and the overlay works.

I am sorry you have to use snapshots to get this functionality. We hope to release 1.3.0 soon.

**Comment by mkrautz** [comment]
If this continues to be a problem, please respond to this ticket or re-open a new one.

I am going to assume my suggestion fixed your issue.
