### ISSUE TITLE
feature request: show clients sending voice which are local muted

### ISSUE THREAD

**Issue by treaki** [mumble-voip/mumble#2119]
if you mute some client locally you are unable to determine if it is sending voice or not anymore. Maybe you have muted some music bot (or other client) for once and than forget to unmute them. So it would be nice if the ui would clients sending voice which are locally muted also with the red mouth.

Thanks

**Comment by Tarun80** [comment]
I agree with showing if a muted client is transmitting audio. Though I believe it should be another color. In the new UI/theme they have, red is no transmission, green is open comms.

**Comment by Kissaki** [comment]
I don’t see the use case yet.

You mentioned muting a music bot; if I mute a music bot, I know he will be transmitting audio.
If I miss the music, I will unmute. If I don’t, nothing was missed not unmuting it.

If I mute a person, I probably had a reason. If I occasionally check the (full) user list, or when said user connects/changes channels, I will see the muted icon.

I strongly disagree with using the same indication as unmuted talking.
Adding yet more talking states (besides priority speaker, linked channels, and whispering) is also very questionable to me, as it increases complexity (and thus the likelyhood of confusion) even more.

A "recently active" information may be a viable alternative.

**Comment by jagodragon** [comment]
the use case is that you won't talk over some one who you have local mute on.

it will cut down on confusion during a conversation and preserve good relations in the group by keeping it from being obvious that you have some one muted.

**Comment by Natenom** [comment]
As a temporary "solution" you can use the current snapshots and locally lower the volume of a person to -60db instead of muting him locally.

**Comment by Krzmbrzl** [comment]
> the use case is that you won't talk over some one who you have local mute on.

Well if you're all in the same discussion, you shouldn't be muting people in the first place...

Besides: I think that #3973 is a very senseful thing to implement but this would (more or less) make this feature-request impossible.
Thus the question: Do you agree with me or do you think that this feature-request is more important?

/cc @davidebeatrici @Kissaki
