### ISSUE TITLE
Client feature request: emit a host header (similar to HTTP)

### ISSUE THREAD

**Issue by eligrey** [mumble-voip/mumble#2139]
**Edit**: Simplifying the feature request to the bare necessity: emitting a host header in the client. The rest of this message is just a hypothetical scripting scenario making use of said header.

It would be neat if I could specify a special value in registerName called $hostname, and when registerName is set to this value, the root channel would have a variable name based on the hostname being connected to by the user. (I'm assuming the mumble protocol has something like HTTP's Host header)

e.g. Suppose the same mumble server is available at both mumble-1.example and mumble-2.example. If `registerName=$hostname`, then when a user connects to mumble-1.example, the root channel's name would be reported as "mumble-1.example". When a user connects to mumble-2.example, the root channels name would be reported as "mumble-2.example". When a user connects by directly entering the IP address, the root channel name would be reported as the IP address entered.

**Comment by hacst** [comment]
The protocol doesn't really care about hostnames at all. The user connects to an ip and port which uniquely identify the server (at list that's how it works now. See #1306).

I'm not sure what the use-case would be for that feature anyways. Is there a specific reason why you would want to have root channel names not bound to the specific virtual server?

**Comment by eligrey** [comment]
My use case is so that I can give people `mumble://[personal website]` on my personal website, and `mumble://[some group I run]` on some group I run, and have them both be the same mumble but display a different root without having one "official" root name. Individually, both URLs get very few users and would share the same internal channel structure and permissions anyways, so I'd rather not make two separate mumble vhosts and split up the groups.

**Comment by Kissaki** [comment]
I don’t see the usefulness.
If the two user groups are so different that you want to display a different server name, either the server is where you would split them or the channel level below that, where you split the two.
For the latter however, using separate server names does not make sense, as the "other group" will always be under that root channel as well.

If they are so close that they run on the same (virtual) server, one hosting the other is likely, in which case the server name is clear, or it does not really matter whichs name is used.

**Comment by eligrey** [comment]
Another feature that becomes possible if the Mumble client emits host headers would be automatically placing users in certain channels (though unrelated to this specific feature request, it's something that becomes possible for scripters if this feature's prerequisites are ever implemented).

I have a third group of people who use this channel, and they always go to a channel called `corp.[group I run]`. Imagine if they connected to `corp.[group I run]` and were automatically placed there. A very very small feature, but it's neat to think about.

**Comment by Kissaki** [comment]
Links can already point to specific subchannels.
We already allow moving users to specific channels on connect via Ice.

So you could add a server callback script that on user connect check which group he belongs to and places him in a channel.
Then again, if he is registered, he is already being placed into his last channel automatically - so I don’t see the usefulness there either.
And if you want to send him to that channel via a link, you can already do that as well.

**Comment by hacst** [comment]
Considering your use-case I still think the root channel name should stay a fixed part of server identity. As such I don't support adding connection dependent variables to it.

Seems like the FR isn't about that anymore anyways. Transmitting the host-name might be interesting for the scenario you mentioned where you have one virtual server but several topic channels you want users to join into. As Kissaki mentioned that would conflict a bit with the "rejoin last channel" logic we currently use. Also it is partially redundant (though not fully equivalent) to mumble URLs with a channel specified (redundant as in those allowing you to join a specific channel, not fully equivalent in that if you save a server as your favorite such channel information isn't preserved as you simply join the last channel you were in when you left).

I think transmitting the hostname and leaving it up to server-side scripting what to do with isn't unreasonable. However I don't think it's useful information outside of an authenticator. Also not sure how much it would actually be used ;)

**Comment by mkrautz** [comment]
We have a host header (SNI), but we just need to expose it, if we wish to.

**Comment by eligrey** [comment]
I'm closing this due to unnecessary complexity it would introduce, and using mumble URLs linking to specific channels is probably sufficient for more people (although this feature would be neat to have, it's probably just not worth it).

If anyone else other than me actually wants this, you are free to re-open the issue.
