### ISSUE TITLE
Certificate chain shows up twice in the certificate viewer

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2141]
Via @janschejbal in mumble-voip/mumble#1949:

> [...]
> The chain in the client UI will show the server cert twice, once on top and once on the bottom, but this seems to be normal (haven't seen a server where this doesn't happen nor could I find a config that > would not make it happen) and it will work without issue.

**Comment by mkrautz** [comment]
I believe this is because we did some "certificate chain shuffling" to work around a bug.
I don't know if that code can be removed safely, or even where it is. This is just a brian dump. :)

**Comment by Krzmbrzl** [comment]
Appears to be fixed with #3590
