### ISSUE TITLE
Feature Request: Local Channel linking and PTT to target

### ISSUE THREAD

**Issue by jagodragon** [mumble-voip/mumble#2142]
I am an officer in my guild. there are times that i have to talk to people privately and there are also times that i need to e part of several conversation in multiple channels. it would there for be great we could have a local channel linking feature that would allow the user to listen to multiple channels and with out having the PTT transmit to both and with out linking them for every one on the server. this coupled with a PTT to target would allow for people to move them selves to another channel and chat with the officer in private with out the officer having to leave the group. and with the targeted PTT you could easily send a private praise or reprimand to any one with out having to set multiple whisper/shout buttons.

these two features would be very handy in several other instances as well.

**Comment by Kissaki** [comment]
From what I would expect we can already do this.
Link the two channels, via ACL deny speak for people outside of the channel, and deny hearing for everyone not an officer, and use the shout functionality to speak/shout to the other room, or use whisper to praise a single person.

Were you aware of these features?
Were you looking for something different?

**Comment by jagodragon** [comment]
I am asking for the ability to link on client side only

and to whisper/shout to target target.

**Comment by Kissaki** [comment]
Are these two separate feature requests?
Could you separate them?

What is your use case for local linking?
Because I can’t think of one that whisper/shout would not be sufficient for.

What do you mean by “target target”?
