### ISSUE TITLE
mumble crashes trying to use wrong protobuf version

### ISSUE THREAD

**Issue by rathsky** [mumble-voip/mumble#2143]
I'm on Arch Linux. [Here's one](https://bbs.archlinux.org/viewtopic.php?id=192984) other report of another users experiencing the same, and [a similar one](https://bugs.archlinux.org/task/28729) from ParaView.

> [libprotobuf FATAL google/protobuf/stubs/common.cc:78] This program was compiled against version 2.5.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.0.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "gen/proto_out/ipc/ipc.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
>  what():  This program was compiled against version 2.5.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.0.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "gen/proto_out/ipc/ipc.pb.cc".)
>zsh: abort (core dumped)  mumble

Happens with both repo versions of mumble and protobuf and the packages I self-compiled a minute ago (protobuf before mumble, ofc).

There is no version other than 3.0.0 installed on my system. With the repo packages (2.6.1/1.2.13) the number changes to 2.6.1, the "compiled against" stays at 2.5.1.

I tried removing my ~/.config/Mumble, no change.

**Comment by mkrautz** [comment]
Did you do a clean compile of Mumble? No stale Mumble.pb.c/Mumble.pb.h files?

Have you checked your protobuf headers? Do they match the 3.0 release? Or are they from a prior release?

Where did you get your Protobuf 3.0 package from? It doesn't seem like it's in the main Arch repos.
The 3.0 library is (evidently, per the fatal error) incompatible with binaries built against earlier versions, so it's not surprising that the Arch prebuilt Mumble isn't compatible with 3.0.

**Comment by rathsky** [comment]
> Did you do a clean compile of Mumble? No stale Mumble.pb.c/Mumble.pb.h files?

It's built from a repo cloned freshly into /tmp, using [this build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mumble-git). So if those Mumble.pb.c/Mumble.pb.h files are in the repo: Yes, no stale ones.

What the Arch maintainer used I can't tell, ofc – but I'm still getting the bug with mumble/protobuf repo packages and his mumble package is described as a rebuild for protobuf 2.6.1.

> Have you checked your protobuf headers? Do they match the 3.0 release? Or are they from a prior release?

Dunno which you mean exactly, but there's nothing related to protobuf in my /usr other than what's in the protobuf 3.0 package, and those files set their version macros to 3000000 everywhere.

> Where did you get your Protobuf 3.0 package from?

Using the Arch repo scripts, just changing them to use a git clone of the protobuf repo instead. I tried that because mumble wouldn't work with Arch's 2.6.1 either, and from my understanding protobuf 3.0 has a fallback to/compatibility with 2.x semantics (at least that's what it prints during compile).

**Comment by rathsky** [comment]
Also, ldd shows the same mumble binary that crashes is properly linked to /usr/lib/libprotobuf.so.10 (hence it crashes with file not found when downgraded to 2.6.1/libprotobuf.so.9).

**Comment by rathsky** [comment]
Alright, finally! Wasn't mumble at all, sorry about all the noise.

> strace -f -t -e trace=file mumble &> file

showed me it was failing upon opening an [uim](https://en.wikipedia.org/wiki/Uim) library. Turns it was the actual cause as the Arch maintainer hasn't rebuilt it in a while. (The package also states no dependency on protobuf.)
