### ISSUE TITLE
Mumble 1.2.14 notifies to update to 1.2.13

### ISSUE THREAD

**Issue by lbernd** [mumble-voip/mumble#2145]
Just a FYI, Mumble 1.2.14 notifies to update to 1.2.13. Maybe that's just because I updated already to 1.2.14 before the update was recommended in the program.

Windows 7 64bit
Install file used:
https://github.com/mumble-voip/mumble/releases/download/1.2.14/mumble-1.2.14.msi

**Comment by barbuslex** [comment]
Same issue for me...

**Comment by mkrautz** [comment]
Fixed!

Sorry, the problem was that we initially had released a bad Windows binary that didn't launch correctly due to a code signing issue.

We retracted the binaries.

Then, when we released them again, I forgot to update the version in the version checker.

Done.
