### ISSUE TITLE
Opus 1.1.3 released

### ISSUE THREAD

**Issue by w4** [mumble-voip/mumble#2146]
Are there any plans to upgrade the Opus codec in Mumble? In the mumble-voip/opus repo it seems as if it was last updated 3 years ago. There have been a few releases since the last pull from the upstream repo.

**Comment by mkrautz** [comment]
Yep, we'll upgrade to 1.1.2.

And to the 3 years ago thing: no, we're on 1.1.1 in 1.3.x:
https://github.com/mumble-voip/opus/commits/1.1.1%2Bmsvc2013.3-alignment

**Comment by w4** [comment]
Ooops yeah, sorry. I saw "Last commit Dec 29, 2014"

**Comment by mkrautz** [comment]
Not done yet.

**Comment by j0bb13** [comment]
Opus 1.1.3 is the latest since July 15, 2016.
