### ISSUE TITLE
Qt format string mistake in Plugins.cpp

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2148]
<W>2016-03-03 10:19:28.417 Plugins: Failed to load sr.dll: Cannot load library C:/Users/mkrautz/AppData/Roaming/Mumble/Plugins/sr.dll: %1 is not a valid Win32 application.

**Comment by mkrautz** [comment]
This was in 1.3.x, btw.

**Comment by davidebeatrici** [comment]
Can you explain more about this problem?

**Comment by mkrautz** [comment]
The code output "%1"... So the format string used in Plugins.cpp must not be correct.

**Comment by davidebeatrici** [comment]
When does it happen?

I have seen this only one time, when Mumble/MumblePAHelper and the plugin were built with different compilers.

**Comment by mkrautz** [comment]
https://github.com/mumble-voip/mumble/blob/1017830/src/mumble/Plugins.cpp#L334

Seems like the offending string is actually from QLibrary::errorString(), so it's a Qt bug rather than a Mumble bug.

**Comment by davidebeatrici** [comment]
Why are we using `qPrintable()` if `QLibrary::errorString()` is a QString?

**Comment by mkrautz** [comment]
Because that's what qPrintable is for: converting a QString to a const char * for printing.

**Comment by davidebeatrici** [comment]
Oh, I didn't notice that it is `QWarning(<message>)` and not `QWarning() << <message>`.

**Comment by davidebeatrici** [comment]
[qUtf8Printable()](http://doc.qt.io/qt-5/qtglobal.html#qUtf8Printable) should fix the problem.

**Comment by mkrautz** [comment]
???

How so?

**Comment by davidebeatrici** [comment]
`qWarning()` expects the arguments to be UTF-8 encoded.

**Comment by mkrautz** [comment]
What gives you that idea? According to the docs, it should be Latin1. And how is this even related to the bug in question?

**Comment by davidebeatrici** [comment]
Well... `QWarning()` isn't able to print the argument correctly. Isn't that the problem?

**Comment by mkrautz** [comment]
Why do you think it is related to an encoding problem? The problem is a stray format string.

**Comment by Krzmbrzl** [comment]
I think this issue can be closed with #3743 the framework has been rewritten in it.
If the error comes up again, we can have a new issue. 

And as I see it, you didn't find out, what the actual cause of that error was, right? If you did, I could try to make sure to not make the same mistake in the new framework...
