### ISSUE TITLE
Fix https://www.mumble.info/AUTHORS and https://www.mumble.info/LICENSE URLs

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2153]
Right now, they aren't active.

**Comment by hacst** [comment]
Hm. Should those be the ones from the current repo head? If so how do we keep them updated?

**Comment by mkrautz** [comment]
I have a cronjob set up for mumble-releng on mumble.hive.no, we can do the same here.
Or we could set up a redirect to github from fastly?

I.e., redirect to https://github.com/mumble-voip/mumble/blob/master/AUTHORS and https://github.com/mumble-voip/mumble/blob/master/LICENSE

**Comment by hacst** [comment]
If you upload them into the www-mumble-info bucket we can make it retrieve them from there. We could also do a real redirect to github. Directly retrieving them from github is another option however that would require us to have multiple backends and drop the shield host configuration.

**Comment by hacst** [comment]
Now served from the www-mumble-info bucket. See:
* https://www.mumble.info/AUTHORS
* https://www.mumble.info/LICENSE

**Comment by mkrautz** [comment]
We need to auto-sync. I will need to think it over...

**Comment by davidebeatrici** [comment]
Issue fixed some time ago, probably when we were working on the new website.
