### ISSUE TITLE
Latest Mumble 1.3.0 doesn't allow loopback connection

### ISSUE THREAD

**Issue by ReekyMarko** [mumble-voip/mumble#2157]
I updated my Mumble 1.3.0 snapshot to the latest version, actually several times yesterday because the client requested it.

After the first update I wasn't able to connect to my server from the same network using my domain name. Then another update rolled in almost immediately and I thought it would fix the problem, which it didn't. I resorted to connecting to my server with the local ip of the server and everything else is working fine. Today, another update rolled in and it still didn't fix the problem. Just wanted you to know that this kind of a problem was probably caused by the latest update(s).

**Comment by mkrautz** [comment]
Which OS are you seeing this on?

**Comment by ReekyMarko** [comment]
Windows 10 Pro 64bit, the latest insider preview

**Comment by mkrautz** [comment]
I haven't had time to check this yet, but I assume this is a regression in the latest insider preview.

**Comment by ReekyMarko** [comment]
Ok, I was thinking about that too :/ But I had to reinstall windows anyways, so now it is working fine without the preview. Thanks for your input!

______________________________________ 
Best regards / Ystävällisin terveisin 

Marko Korhonen 
Piiluvankatu 35 A10 
53950 Lappeenranta, Finland 
Mobile: +358407658800 
Tel:        +358923161993

**Comment by mkrautz** [comment]
@ReekyMarko As I said, I haven't tried to verify on a non-Insider build yet! Could be that I'm wrong. I just wanted to update with my thoughts. :-)

**Comment by mkrautz** [comment]
@ReekyMarko 

This works for me on the released version of Windows 10.

I can connect to my server via Bonjour.
Via localhost.
Via 127.0.0.1.

**Comment by LuaMilkshake** [comment]
To clarify, it sounds like you're on the same LAN as the Murmur host system but you're using a domain pointed to your public IP address to connect to it? If so, this could be an issue with going out and back in through NAT.

**Comment by ReekyMarko** [comment]
It worked that way before, using the same configuration (no changes in the router). The problem only arose immediately after an update to the Mumble snapshot. Now, I'm running a fresh install of regular Win10 and it's working again. So probably a conflict of some kind with the preview + current version of Mumble.

This problem probably affects a very small group of people but I thought to let you guys know ;)

______________________________________ 
Best regards / Ystävällisin terveisin 

Marko Korhonen 
Piiluvankatu 35 A10 
53950 Lappeenranta, Finland 
Mobile: +358407658800 
Tel:        +358923161993
