### ISSUE TITLE
Wiki homepage links to outdated GPG information

### ISSUE THREAD

**Issue by LuaMilkshake** [mumble-voip/mumble#2163]
On the wiki homepage, there is a link to "GPG signatures" under "Download Mumble". This links to http://mumble.info/gpg/gpg.txt which is outdated information from 2015. Perhaps this should link to the [mumble-voip/mumble-gpg-signatures](https://github.com/mumble-voip/mumble-gpg-signatures) repo, or the raw [gpg.txt](https://raw.githubusercontent.com/mumble-voip/mumble-gpg-signatures/master/gpg.txt) within that repo?

**Comment by mkrautz** [comment]
Thanks, fixed!

The GPG link now points to GitHub -- more specifically, the gpg.txt file in the repo.
