### ISSUE TITLE
Checkbox checks don't appear

### ISSUE THREAD

**Issue by LOZORD** [mumble-voip/mumble#2165]
On Windows 10 (Education), checkboxes (or specifically their checks) don't show up.

Just did a fresh re-install with version 1.2.13 and it still doesn't work.

![broken_mumble](https://cloud.githubusercontent.com/assets/3687761/13591070/f318e6f0-e4aa-11e5-9049-8aba1f232b90.PNG)

**Comment by mkrautz** [comment]
Seems like a potential Qt 4 issue...

**Comment by mkrautz** [comment]
Nope, works for me with 1.2.15 on Windows 10 Pro, so presumably not a Qt 4 issue...

**Comment by mkrautz** [comment]
This doesn't make sense. Are you using a custom Mumble theme?
A custom Windows theme?

The look of your screenshot doesn't add up with any of mine:

The "group box" around "Input Device" and "Output Device" is blue for you.
The checkboxes are also blue.

That's not the case for me.

**Comment by mkrautz** [comment]
FWIW, this is my Audio Wizard in 1.2.15, on Windows 10 Pro:

![image](https://cloud.githubusercontent.com/assets/36527/13676753/582b39e2-e6e7-11e5-80e5-a4ffed332d13.png)

**Comment by mkrautz** [comment]
@LOZORD Any idea why the checkboxes and frames in the window look like they do? They don't match my default Windows 10 theme.

**Comment by LOZORD** [comment]
Ok, after some tinkering around, I restored the default Mumble configuration via `Configure > Settings > User Interface > Restore Defaults`. Now the checkmarks are back :smile:  It must have been the Mumble skin/theme I was using. However, I'm pretty sure I got it from the [download page](http://www.mumble.com/mumble-download.php). I was using the "official Mumble.com" skin.

**Comment by mkrautz** [comment]
That's not our download page. That's the download page of Mumble.com, a Mumble hosting company.

The website and download page for Mumble is https://www.mumble.info/.

Glad you solved your problem!
