### ISSUE TITLE
segfaults when displays are turned on or off

### ISSUE THREAD

**Issue by NoEffex** [mumble-voip/mumble#2170]
Not sure exactly when it segfaults but if I have Mumble open when I turn off my screens it will often segfault by the time they're back on. I'm not certain if it's within Mumble or within Qt.

Stacktrace: [https://gist.github.com/NoEffex/070c1da63fe24ca4876a](https://gist.github.com/NoEffex/070c1da63fe24ca4876a)

**Comment by mkrautz** [comment]
Looks to me like a Qt bug. Maybe Qt doesn't anticipate working with no screens?

**Comment by NoEffex** [comment]
Indeed so. I'll report it there.

**Comment by mkrautz** [comment]
@NoEffex Can you cross-link the Qt bug report here? We'd like to track it, too!

**Comment by mkrautz** [comment]
Also, from IRC:

20:41:47 <Natenom> mkrautz: Regarding https://github.com/mumble-voip/mumble/issues/2170. 1. Mumble crashes also on my Plasma5 Desktop when my laptop monitor goes off and the external one becomes the main screen.

**Comment by NoEffex** [comment]
https://bugreports.qt.io/browse/QTBUG-51831

**Comment by mkrautz** [comment]
FWIW, I saw that a similar issue was fixed in the 5.6 release of Qt. I don't have a reference at hand right now though!

**Comment by davidebeatrici** [comment]
The bug has been fixed in Qt 5.6.1.
