### ISSUE TITLE
Potential issue with tray icon updates not working on Ubuntu 15.10

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2172]
```
03:56:44 <peekdino> Does the talk status tray icon not generally work in Ubuntu Unity, or is this a new bug?

03:56:50 <peekdino> Running HEAD on 15.10

04:53:43 <peekdino> Regarding that icon, strangely restarting Mumble a couple times made it work *shrug*
```

**Comment by LuaMilkshake** [comment]
As additional information, I believe I built this from d3929c6. Running Ubuntu 15.10 amd64 with the latest patches as of yesterday. The icon in the tray was remaining green while I was talking (when it should have been blue with additional lines emanating from the icon's head).

**Comment by LuaMilkshake** [comment]
I've found that the icon updates work fine until you open the Mumble configuration window. Even opening the window and hitting "Cancel" prevents the icon from updating.

**Comment by Krzmbrzl** [comment]
Is this still present in Mumble 1.3?

I wasn't able to reproduce this on KDE Neon 18.2
