### ISSUE TITLE
Mumble chat won't appear?

### ISSUE THREAD

**Issue by CyrusXL** [mumble-voip/mumble#2174]
For some reason, the only logs that will appear in the chat are disconnect/reconnect and failure logs. No other kind of chat appears, and when I send a message it dissapears from the typing box but doesn't show up in chat.

**Comment by mkrautz** [comment]
Please check that you haven't disabled logging to the "Console" in Settings -> Messages.

The Console is Mumble's log view.

**Comment by mkrautz** [comment]
@CyrusXL Can you confirm or deny whether my suggestion worked? :-)

Thanks.

**Comment by CyrusXL** [comment]
@mkrautz Oh sorry! It worked, so I forgot to reply. Was a little mixed up on what the chat actually logged. Thanks :)

**Comment by mkrautz** [comment]
No worries! Thanks for the confirmation.
