### ISSUE TITLE
Visual Studio display bug with mumble overlay

### ISSUE THREAD

**Issue by barbuslex** [mumble-voip/mumble#2178]
Hi,

When i launch Visual Studio with mumble already launched (in tray) the Visual Studio's display (home page, menu etc...) does not appears.

Tested with Visual Studio 2013.

The mumble overlay is probably the cause.

Thanks to solve it.

++

**Comment by mkrautz** [comment]
What version of Mumble? devenv.exe is blacklisted in 1.3.0.

**Comment by barbuslex** [comment]
I'm using Mumble version 1.2.15

**Comment by Kissaki** [comment]
Can not reproduce.

Could you check that devenv.exe is in your overlay blacklist?

Could you run Debug View alongside to see if any issues are logged - Mumble Overlay or VS wise.

**Comment by barbuslex** [comment]
The Devenv.exe process was not in the blacklist.
Maybe because my Visual Studio is installed on another hard disk than C:\ (P:\ for me).

No issue with devenv.exe in the blacklist.

**Comment by mkrautz** [comment]
Yep, that's correct. It's not there in 1.2.x yet (which is why I targetted this at 1.2.16).

We should add it to 1.2.x.

**Comment by mkrautz** [comment]
Fixed in 1.2.16.
