### ISSUE TITLE
Update to Qt 5.6

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#2181]
https://blog.qt.io/blog/2016/03/16/qt-5-6-released/
@mkrautz @hacst 

Since this is an LTS, it would make the most sense to stabilize on this regarding https://github.com/mumble-voip/mumble/issues/1638

**Comment by mkrautz** [comment]
This aligns pretty well with our goals of 1.3.0:

We still want to run on XP.
We still want to run on at least OS X 10.7.

Qt 5.6 can still do that, so I think it makes sense.

1.4.0 will drop most legacy compatibility, and will require Win 7+ and a modern OS X (10.10? maybe 10.11 depending on the schedule for Mumble 1.4.0)

**Comment by funkydude** [comment]
If you're referring to me when I was talking about the dropping of old OS's, I believe that was pushed to 5.7 due to 5.6 being LTS.

From that link:
> With Qt 5.6 being supported for a long period of time, we at the same time gain some more freedom in the upcoming versions of Qt. As such, Qt 5.6 will also be the last release that will work without requiring a C++11 compliant compiler. **With Qt 5.7, we will also be dropping support for some older platforms**.

**Comment by mkrautz** [comment]
No, I wasn't referring to anyone in particular. I just meant that we want 1.3.0 to run on those OSes, and we can still achieve that with 5.6, so I think it's worth it.

**Comment by hacst** [comment]
Anything specific we want of Qt 5.6 right now (feature or bugfix wise)?

**Comment by mkrautz** [comment]
HiDPI for Windows

**Comment by hacst** [comment]
That does kinda sound useful.

**Comment by Kissaki** [comment]
I agree with the arguments presented.

**Comment by mkrautz** [comment]
Status:

 - [x] Windows
 - [ ] OS X
 - [ ] CentOS/Ermine
