### ISSUE TITLE
[1.3.0] 32-bit Overlay failing to start

### ISSUE THREAD

**Issue by Xylemon** [mumble-voip/mumble#2182]
I'm not really sure what triggered this, whether it was me upgrading Mumble to the latest git (though it seemed fine the other day) or going back to the nVidia drivers, but I seem to be unable to use the overlay with 32-bit games resulting in the game crashing. The output in terminal shows this error:

symbol lookup error: /usr/lib/libmumble.so: undefined symbol: shm_open

Tested it with Wine and a Source game. Even more strange, 64-bit games work fine and the 32-bit version of glxgears works fine with the overlay too. Any ideas?

**Comment by mkrautz** [comment]
What does `ldd /usr/lib/libmumble.so` say? Is it linked with "librt.so"?

**Comment by Xylemon** [comment]
Doesn't seem to, the 64-bit library does. Output of the ldd:
```
ldd /usr/lib/libmumble.so  
	linux-gate.so.1 (0xf7741000)
	libc.so.6 => /lib/libc.so.6 (0xf7563000)
	/lib/ld-linux.so.2 (0x56601000)
```

**Comment by mkrautz** [comment]
Then it will only work if it injects into processes that *do* link against librt.so.
We should probably add a -lrt linker flag...

**Comment by mkrautz** [comment]
Hmm. Seems like we do:
https://github.com/mumble-voip/mumble/blob/master/overlay_gl/overlay_gl.pro#L19

Maybe -z lazy makes it not actually link:
https://github.com/mumble-voip/mumble/blob/master/overlay_gl/overlay_gl.pro#L26

**Comment by Xylemon** [comment]
I am compiling with Qt 5.5.1 and GCC 5.3.0 if that makes any difference or is causing the problem.

**Comment by mkrautz** [comment]
That shouldn't make a difference.

How are you building both the 32-bit and the 64-bit overlay libraries? Using qmake?

**Comment by Xylemon** [comment]
I am using the qt5 version of qmake.

**Comment by mkrautz** [comment]
But how are you building both the 32-bit version of the overlay, and the 64-bit version?

**Comment by Xylemon** [comment]
I'm on Slackware and I use a modified Mumble SlackBuild. The source tarball it uses is just a copy of the git repo with the submodules. You can view it here: https://raw.githubusercontent.com/Xylemon/slackbuilds/master/Mods/mumble-1.3.0/mumble.SlackBuild

I run it with OSS=yes OVERLAY=yes COMPAT32=yes. The 64-bit build process begins here: https://github.com/Xylemon/slackbuilds/blob/master/Mods/mumble-1.3.0/mumble.SlackBuild#L110 and the 32-bit overlay library is built here: https://github.com/Xylemon/slackbuilds/blob/master/Mods/mumble-1.3.0/mumble.SlackBuild#L171

I'm gonna double check my glibc packages again when I get the time later today, just in case that is the problem.

**Comment by Xylemon** [comment]
After ditching the nVidia drivers again, this issue is no longer present. Don't know why it happened with the proprietary drivers at seemingly random, but nonetheless, I'm closing this issue since it's resolved for me.
