### ISSUE TITLE
Support PostgreSQL with QPSQL

### ISSUE THREAD

**Issue by svenstaro** [mumble-voip/mumble#2187]
Mumble/murmur currently only support SQLite and MySQL but not PostgreSQL. It should support PostgreSQL. There is a patch here that actually applies cleanly: https://sourceforge.net/p/mumble/patches/368/

Doesn't look like too much work.

**Comment by Kissaki** [comment]
Do we support MySQL?
AFAIK it’s a best-effort support. It’s not our primary focus, and we recommend not to use MySQL, but if issues arise, we fix them.

I guess we would need someone to commit to maintaining PostgreSQL, and someone to continuously use it. If we supposedly support it, and after half a year noticed its broken, that would not be so great.

**Comment by Nuc1eoN** [comment]
#2541 implemented this feature. Can be closed?

**Comment by Kissaki** [comment]
Thank you for pointing it out
