### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by Slyvester1** [mumble-voip/mumble#2189]
Sometimes when trying to post messages, the whole chat line where you type a message is grayed out. To get it to show up again I have to close the whole client out and reopen the client. Also, several people in my gaming community have issues with trying to talk and or hearing people after they are in the channel for awhile. I do know that one specific person is using version 1.2.13 that is having the sound problem, but the other person I'm not sure of. If you need anything that might be useful, I will see what i can dig up. 

**Specifications:**
**Ubuntu Version:** 14.04.4 LTS (Trusty Tahr)
**Mumble Server Version:** 1.2.12
**Client Version:** 1.2.15
**Windows 10 Home**

Thanks, Slyvester

**Comment by Kissaki** [comment]
For future support requests, please separate separate issues into separate issue tickets - unless you are not sure they are not related of course.

For your missing audio issue, please check the connection statistics for packet loss, specifically on the users that are missing or losing audio.
