### ISSUE TITLE
Virtualbox Overlay won't disable.

### ISSUE THREAD

**Issue by AppliedEllipsis** [mumble-voip/mumble#2191]
With W64, 1.3.0~970~g888a459~snapshot,
The in game overlay shows in VirtualBox virtualmachines.
Adding every exe in C:\Program Files\Oracle\VirtualBox to exception list does not disable it.
Setting to white-list only does not disable it.
Unchecking show overlay does not disable it.
Restarting the app, does not change it. 
Once connected to a server and clicking in the VM, the overlay comes up.

**Comment by Kissaki** [comment]
After changing the overlay display settings, did you restart your VirtualBox VM?

I just launched an Ubuntu VM and see no 

When installing VirtualBox, did you install the (experimental) Direct3D support?
If you installed it, is there a setting to en-/disable this in the virtual machine settings?

In the virtual machine settings, do you have 3D acceleration and/or 2D Video Acceleration enabled?
