### ISSUE TITLE
MainWindow doens't appear on Linux/Qt 5

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2192]
From IRC:

	20:52:26 <unascribed> I just updated Mumble to the latest Git master (via the AUR package mumble-git) and now whenever I start Mumble, I get the Server Connect dialog but the main window never appears.
	20:52:36 <unascribed> The PKGBUILD for mumble-git, as I can't get it to build manually: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mumble-git
	20:52:42 <unascribed> log: https://gist.github.com/unascribed/2129043722628886d280077bfedc803b
	20:52:54 <unascribed> if I downgrade to 1.2.15 the main window does appear
	20:54:20 <unascribed> going to keep trying to get it to build manually
	21:01:19 <unascribed> got it to build, and it has the same problem
	21:19:38 <@mkrautz> unascribed: tried moving your ~/.config/Mumble folder? sounds to me like the saved geometry is bad in some way
	21:19:47 <unascribed> oh, I meant to mention that
	21:19:49 <unascribed> yes, I did try that
	21:19:57 <unascribed> also tried moving Mumblerc and ~/.local/share/Mumble
	21:20:14 <unascribed> I also tried going through the Mumble config and removing all the geometry lines
	21:21:26 <unascribed> the window simply doesn't exist
	21:21:31 <unascribed> doesn't show up in the pager, xprop can't find it
	21:23:13 <unascribed> clicking on Mumble in the system tray also doesn't do anything
	21:23:47 <@mkrautz> what WM/DE are you using?
	21:23:54 <unascribed> KDE Plasma 5.6
	21:23:55 <unascribed> kwin
	21:24:09 <@mkrautz> OK. I would expect a Qt program to work in that case ;)
	21:24:30 <unascribed> trying to find a good commit without the issue to try a bisect
	21:24:33 <unascribed> not having much luck
	21:24:36 <unascribed> aaand my panel just disappeared
	21:24:37 <unascribed> ??
	21:24:42 <unascribed> maybe I should reboot...
	21:24:50 <@mkrautz> I don't really know what's going on. There have been other reports of the MainWindow not showing up after being minimized to the notification area
	21:25:20 <@mkrautz> unascribed: I don't think you can bisect. Nothing has changed in the Mumble tree regarding that particular issue in a looong time.
	21:25:29 <unascribed> okay
	21:25:33 <unascribed> but as said 1.2.15 works fine
	21:25:47 <@mkrautz> yep. 1.2 uses Qt 4, git master uses Qt 5 :)
	21:25:57 <unascribed> hm, that's a good point
	21:25:59 <@mkrautz> I assume it's an incompatibility with Qt 5, somehow.
	21:26:08 <unascribed> I'll try building master on qt4, assuming that's still possible
	21:26:14 <@mkrautz> it is
	21:26:46 <@mkrautz> but you need to pass CONFIG+=qt4-legacy-compat
	21:26:49 <unascribed> it printed the deprecation warning ten times
	21:26:49 <unascribed> lol
	21:26:55 <@mkrautz> uh, yeah...
	21:27:06 <@mkrautz> we're ... not really optimizing the UX of "qmake" :)
	21:27:09 <unascribed> -j24 wouldn't cause issues, would it?
	21:27:16 <unascribed> (on make)
	21:27:20 <@mkrautz> unascribed: it shouldn't
	21:28:47 <unascribed> yep, works fine on qt4
	21:29:02 <unascribed> so weird
	21:29:07 <unascribed> any suggestions for debugging this?
	21:30:12 <@mkrautz> I would look into the setupView method of MainWindow... I suspect it's something in there
	21:30:30 <@mkrautz> or its callees
	21:30:56 <unascribed> is it supposed to be called twice on non-OSX?
	21:31:02 <@mkrautz> perhaps MainWindow::setupGui()
	21:31:30 <@mkrautz> unascribed: I think so, but... who knows if it's applicable for Qt 4
	21:31:31 <@mkrautz> 5.
	21:31:33 <@mkrautz> not 4.
	21:32:03 <unascribed> well, I'm going to try changing random seemingly related things
	21:32:10 <unascribed> I'm not a C++ dev nor am I familiar with the Mumble codebase
	21:32:16 <unascribed> worked for OBS, maybe it'll work here :P
	21:33:39 <@mkrautz> sounds good to me :) since we don't know the culprit, that's what can give us clues...
	21:35:26 <unascribed> yep
	21:35:33 <unascribed> commenting out the redundant setupView makes it work fine
	21:35:51 <unascribed> no idea if it works on Windows
	21:35:54 <unascribed> evidently it didn't work on Mac
	21:36:50 <unascribed> not going to PR as this is a trivial change that has side-effects on other OSes that I can't test
	21:37:09 <unascribed> https://github.com/mumble-voip/mumble/blob/master/src/mumble/MainWindow.cpp#L359
	21:37:13 <unascribed> commenting out this line makes it work
	21:37:54 <unascribed> my guess is you were right on the incorrect geometry
	21:37:59 <unascribed> because this is called before geometry is restored
	21:38:13 <unascribed> so maybe the second one doesn't actually do anything? not sure
	21:38:32 <unascribed> maybe that should check if the qt4 legacy flag is set and it's not mac
	21:38:40 <unascribed> no idea how to write a preprocessor directive that does that
	21:38:52 <unascribed> short of two ifdefs
	21:38:57 <unascribed> but that doesn't seem right :P
	21:40:46 <unascribed> and I did test uncommenting it again, to make sure it wasn't a config change
	21:40:57 <unascribed> if I uncomment the line I get the original issue again
	21:41:08 <unascribed> I can comment/uncomment (presumably) as many times as I want and the behavior will be the same
	21:41:14 <unascribed> I only did it twicew
	21:41:16 <unascribed> twice*

**Comment by mkrautz** [comment]
We should test whether removing the first setupView() calls breaks other OSes on Qt 5.

If not, it should be wrapped in `#if QT_VERSION < 0x050000`...

**Comment by JoelTroch** [comment]
Probably related to #2081

**Comment by NiLuJe** [comment]
And a quick comment to confirm that this indeed fixes the issues on Linux w/ KWin 5 & Qt 5.5.x :).

**Comment by msva** [comment]
And my 5 cents that patch from highlight (@KaOSx/apps#58) is working like a charm: https://gist.github.com/forostm/79967fd973ae833bfc2ae2886d2947d2

// although, it is still broken tray icon

**Comment by EmperorArthur** [comment]
Can confirm this is still an issue.  The patch msva linked fixed it.

Tray icon is still broken here too.

OS:  Debian staging

**Comment by msva** [comment]
ping any devs? Patch is pretty simple, can you, plase apply it?

**Comment by mkrautz** [comment]
Patch is very simple. However, it's removing code that's currently working fine on Qt 4.

It seems like no-one has had the time to test that this doesn't break anything across various Qt 4 and 5 versions, and across other OSes than Linux. (Mumble 1.3.0 targets both Qt 4 and 5.)

Sorry.

**Comment by msva** [comment]
so, then it can be solved by something like:
```cpp
#if (QT_VERSION >= QT_VERSION_CHECK(5, 0, 0))
#if !defined(Q_OS_MAC) && !defined(Q_OS_LINUX)`
setupView(false);
#endif
#endif
```

Then it will keep status-quo on non-Linux (and non MacOS, like before too) and on Qt4, but will fix for Qt5@Linux. :)

**Comment by Grandpa-G** [comment]
I have added the above code to an earlier version of 1.3 on a Raspberry Pi and with a few limited trials, 100% have stayed full screen with the hidetray=false option in the config file.

**Comment by mkrautz** [comment]
PR at https://github.com/mumble-voip/mumble/pull/2552
