### ISSUE TITLE
Remote host closed the connection???

### ISSUE THREAD

**Issue by GreenCare** [mumble-voip/mumble#2200]
Have Murmur running on Win XP. Mumble on the server PC connects just fine until the 2nd Mumble client tries to connect then they alternate back and forth. Both machines are on a IPSEC VPN between the house and the office. 
The error message at either the server pc or the client pc is...
"Server connection failed: The remote host closed the connection."
Any thoughts on how to correct this??? Mumble or network issue???
Tom

**Comment by Kissaki** [comment]
Where is the second client connecting from?
Are both clients using the same user certificate?
The same username?
The same IP address to connect from?

Checking the server log may also provide more details on why you get disconnected (I guess because the server identifies the new client as a replacement of the old - disconnecting the old, presumably dead client).

**Comment by GreenCare** [comment]
Second client is connecting from the office over a vpn.
Yes, both are using the same certificate.
Different username at each client as they are generating different audio to each other.
Server is at the house with static IP.

Sample of log...where one client connects and then the other...
<W>2016-04-11 11:16:19.352 1 => <155:(-1)> New connection: 192.168.205.57:3216
<W>2016-04-11 11:16:19.555 1 => <155:(-1)> Client version 1.2.15 (Win: 1.2.15)
<W>2016-04-11 11:16:19.789 1 => <155:ts590(3)> Disconnecting ghost
<W>2016-04-11 11:16:19.930 1 => <154:ts590(3)> Connection closed:  [-1]
<W>2016-04-11 11:16:20.211 1 => <155:ts590(3)> Authenticated
<W>2016-04-11 11:16:30.008 1 => <156:(-1)> New connection: 10.10.171.20:54715
<W>2016-04-11 11:16:30.258 1 => <156:(-1)> Client version 1.3.0 (WinX64: 1.3.0~982~gef72e3e~snapshot)
<W>2016-04-11 11:16:30.524 1 => <156:ts590(3)> Disconnecting ghost
<W>2016-04-11 11:16:30.711 1 => <155:ts590(3)> Connection closed:  [-1]
<W>2016-04-11 11:16:30.977 1 => <156:ts590(3)> Authenticated
<W>2016-04-11 11:16:40.711 1 => <157:(-1)> New connection: 192.168.205.57:3218
<W>2016-04-11 11:16:40.914 1 => <157:(-1)> Client version 1.2.15 (Win: 1.2.15)
<W>2016-04-11 11:16:41.227 1 => <157:ts590(3)> Disconnecting ghost
<W>2016-04-11 11:16:41.367 1 => <156:ts590(3)> Connection closed:  [-1]
<W>2016-04-11 11:16:41.649 1 => <157:ts590(3)> Authenticated
<W>2016-04-11 11:16:51.414 1 => <158:(-1)> New connection: 10.10.171.20:54716
<W>2016-04-11 11:16:51.649 1 => <158:(-1)> Client version 1.3.0 (WinX64: 1.3.0~982~gef72e3e~snapshot)
<W>2016-04-11 11:16:51.914 1 => <158:ts590(3)> Disconnecting ghost
<W>2016-04-11 11:16:52.071 1 => <157:ts590(3)> Connection closed:  [-1]
<W>2016-04-11 11:16:52.352 1 => <158:ts590(3)> Authenticated
<W>2016-04-11 11:17:02.055 1 => <159:(-1)> New connection: 192.168.205.57:3220
<W>2016-04-11 11:17:02.274 1 => <159:(-1)> Client version 1.2.15 (Win: 1.2.15)
<W>2016-04-11 11:17:02.555 1 => <159:ts590(3)> Disconnecting ghost
<W>2016-04-11 11:17:02.680 1 => <158:ts590(3)> Connection closed:  [-1]
<W>2016-04-11 11:17:02.946 1 => <159:ts590(3)> Authenticated
<W>2016-04-11 18:39:44.086 1 => <159:ts590(3)> Connection closed: The remote host closed the connection [1]

**Comment by Kissaki** [comment]
A user certificate is meant to identify a single user, so that behaviour is expected.
If a single persona gets disconnected and reconnects, the previous "him" is dropped.

Would using two user certificates work for you?
Otherwise, what is your use case?

**Comment by GreenCare** [comment]
I thought the idea was to have a certificate on the server that got handed out to clients as a confirmation/password. Willing to learn how to add multiple certificates??? Can you point me in the right direction??? Using Mumble to pass audio on a amateur remote base to a client and then replies back to the server/remote base.
Tom

**Comment by Kissaki** [comment]
The server provides a certificate to identify itself,
and every user has his own user certificate, to identify himself.
As you have two separate client installs, on one, you should use the certificate wizard to create a new user certificate. In the menu, Configure -> Certificate Wizard.

**Comment by GreenCare** [comment]
I will upgrade the certificates...Thanks for the advice.
Tom
