### ISSUE TITLE
Listview overflow in ASIO configuration

### ISSUE THREAD

**Issue by Zylann** [mumble-voip/mumble#2201]
Platform: Windows 7 64 bits
In version 1.2.4, there were sliders to see the names of the items in the list.
I upgraded to 1.2.15 and now they are gone, making it impossible to read the items in my situation:
![screenshot](http://zylannprods.fr/images/screen/mumble_asio_overflow.png)

**Comment by Kissaki** [comment]
I would not expect UI changes in these bug fix releases.

If you are willing to test, knowing the exact version that introduced this change would be helpful.

**Comment by Kissaki** [comment]
I guess this is also an issue for 1.3.0. Sadly, I can’t list devices there / the virtual devices I have are not long enough in text.

**Comment by mkrautz** [comment]
We upgraded Qt between those versions. I am not sure how much, but I am sure we did it. 1.2.4 is quite old by now!

**Comment by Krzmbrzl** [comment]
Assuming this has been fixed in the meantime, I'll close this issue now
