### ISSUE TITLE
Find sane default for Murmur DH params before 1.3.0 release

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2204]
Currently, Murmur generates new DH params for virtual servers unless there's a global sslDHParams= set in the .ini file.

This makes `server.start()` via RPC very slow.

We should probably move to a scenario where we generate global DH params on first launch of Murmur, and then use those DH params for all virtual servers...

**Comment by fwaggle** [comment]
As a temporary workaround, suggested by @mkrautz:

 openssl dhparam -out dhparams.pem -5 2048
 echo 'sslDHParams=dhparams.pem' >> murmur.ini

causes each virtual server to use the same DH parameters, so server.start() returns almost immediately again.

**Comment by mkrautz** [comment]
Option 1:

No DH params by default. (ECDHE is always on, though!)
Require users to generate DH params themselves if they want to use EDH cipher suites.
Remove auto-generation per-vserver. However, DH params *can* be set per-vserver.

Option 2:

Ship a default DH group.
Disable auto-generation per-vserver.
Users can override either in Meta (global) or Server (per-vserver) if they want to customize.

Option 3:

Ship built-in named groups.
Disable auto-generation per-vserver.
Allow for either a named group or for a DH params .pem file/string to be used.

For example, we could support allowing the use of the named curves  from https://tools.ietf.org/html/draft-ietf-tls-negotiated-ff-dhe-10 (also a part of TLS 1.3 draft).

This would allow people to specify `ffdhe2048`, `ffdhe3072`, `ffdhe4096`, `ffdhe6144`, `ffdhe8192` as the `sslDHParams` option, with one of them being the default.

This would allow sslDHParams to be either a filename, or one of the above entries. Perhaps we need a prefix on the names to signal that they are not filenames. "@ffdhe2048" for example.

The default could then be:

`sslDHParams=@ffdhe2048`

**Comment by hacst** [comment]
Option 5: Generate a default group on first start and use it like Option 2.

Imho that would be a decent compromise. Imho speaking purely from a crypto perspective my understanding is that option two with a reasonably chosen group alone would be safe enough. We can safely assume that even if the pre-calculation for our group was feasibly we are nowhere near attractive enough to make mass cracking mumble connections worth it. However I think - unless generation really takes ages - we can accept a very first launch time hit to proove we developers "have nothing up our sleve" or choosen the params in some wonky way.

Option 1 I don't think we have to accept. Imho EDH (or comparable) is a out-of-the-box must have these days. 3 imho is overkill and nowhere worth the effort and 4 is undesirable as we want launching vservers to be cheap and fast.

**Comment by mkrautz** [comment]
We can ship built-in named groups (from option 3) separately from auto-generation.
I quite like the ability to specify groups by name, and I think I'll submit a PR to do so.

Then we can re-visit if it's worth it to auto-generate or not. If nothing else, we can ship
the default .ini with a named group.

**Comment by mkrautz** [comment]
My plan is to allow the DHE groups from https://tools.ietf.org/html/rfc7919 to be used for  dhParams (say `dhParams=@ffdhe2048`).

We should also update the dhParams doc to specify that it is used for configuring the non-negotiated default dhParams for the server/meta.

**Comment by hacst** [comment]
Is there any cryptographic advantage to using one of the named groups? Seems like that would just again make us use something that can be pre-computed against. Or am I missing something here?

**Comment by mkrautz** [comment]
My thinking was that with the negotiated EDH params of RFC 7919 being part of TLS 1.3 (and as an extension in earlier TLS versions?), it would make sense to have them selectable even in non-negotiated EDH mode with my proposed "@ffdhe2048" notitation.

It would also save us from auto-generating a unique group on startup.

With that said, I agree with your analysis about pre-computation and weakdh.org. It is somewhat mentioned in RFC 7919 (see 8.5. Choice of Groups). However, given the ubiquity of TLS, the best solution would probably be to auto-generate.

Most of all, it was to have a shippable solution for enabling EDH by default in 1.3.0, allowing older 1.2.x clients to get forward secrecy.

Shipping with a default of dhParams=@ffdhe2048 and ripping out the current per-vserver auto-generation code is an easier goal than moving the auto-generation code to work on the Meta instance. (At least conceptually, in my mind... Maybe I'm crazy.).

Then, if we have time, we can do the auto-generation.

But if we don't find the time, at least we have something we can ship, to avoid having 1.3.x slip any further.

**Comment by hacst** [comment]
Ok. I assumed it would be simpler to go from generation per vserver on creation to once in meta on first launch than adding that default group handling. Thought that would just be moving some code we already have. From that POV adding something else that is arguably redundant/less secure seemed strange. If you think the named group solution is faster to implement then that's surely true and I'm totally fine with taking that tradeoff.

**Comment by mkrautz** [comment]
First part is here:
https://github.com/mumble-voip/mumble/pull/3183
