### ISSUE TITLE
Overlay not working at all

### ISSUE THREAD

**Issue by Enigma0** [mumble-voip/mumble#2206]
I've been at it for several hours uninstalling/reinstalling with no luck.

- Running latest winx64 1.3.0 snapshot. (Couldn't get it working on 1.2.x either)
- System is Win10 x64 latest updates/drivers
- All .exe's in mumble are set for all users to run as administrator

Steam overlay works perfectly and other overlays as well (AMD Gaming Evolved - even simultaneously with Steam overlay). All other overlays are currently disabled.

Are there any logs anywhere that might be relevant?

Could a skin interfere with it functioning?

**Comment by mkrautz** [comment]
You can turn on debug logging for the overlay:
https://wiki.mumble.info/wiki/Debugging#Enabling_More_Verbose_Logging_in_the_Overlay

What are you running Mumble as? In general, you should run Mumble as your regular user, and your games as your regular user as well.

Mumble uses ICP such as shared memory and Windows pipes for communicating between Mumble and the overlay. If the game is running as another user than Mumble itself, you might get into a situation where the overlay in the game can't communicate with Mumble. (That's a bug in itself, should probably be trakced!).

So, please try to run Mumble as your regular user, and the game as a regular user.

If that, too, fails, please report back here with the name of the game -- and I can try it on my end as well.

Thanks!

**Comment by Enigma0** [comment]
I'm running mumble and the games in my regular user account but I escalated all the mumble .exe's to run as administrator and also clicked the "Change setting for all users" box to enable run as admin for every user (there is only one so that was probably unnecessary).

The overlay was not working when it was left default (no "run as admin" boxes checked).

I've been testing primarily with Rocket League, Starbound, and ARK Survival but I have plenty others to test with as well. Starbound seems like a good test case as I can easily launch DX/DX64/OGL/OGL64.

**Comment by mkrautz** [comment]
You should never manually elevate Mumble with "Run as Administrator" -- we don't test that configuration.

I am also confused: You state that the overlay didn't work *until* you set it to "Run as Administrator" for all users. But in your ticket, you state that even then, the overlay doesn't work.

Did it ever work for you?

**Comment by Enigma0** [comment]
Sorry. It hasn't worked _ever_ in any configuration.

**Comment by Tarun80** [comment]
I've seen this issue before. If I remember right you have to run Mumble normally and run the games/Steam/Origin/etc as Admin.

**Comment by mkrautz** [comment]
FWIW, that shouldn't ever be necessary. It's not a configuration we recommend using.

**Comment by mkrautz** [comment]
@Enigma0 

You can use the following trick to get logging from the overlay:
https://wiki.mumble.info/wiki/Debugging#Enabling_More_Verbose_Logging_in_the_Overlay

**Comment by Enigma0** [comment]
So I got it working by undoing the "run as admin" stuff. This alone wasn't enough though. I think I needed to also be running the winx64 version of mumble for it to work at all which I wasn't until recently.

**Comment by mkrautz** [comment]
FWIW, both x86 and x64 snapshot builds should support showing the overlay in x86 and x64 games.
