### ISSUE TITLE
[BUG] Volume slider in "Audio Output" turns down your voice as heard by others

### ISSUE THREAD

**Issue by Enigma0** [mumble-voip/mumble#2209]
Not sure if this is intentional or not but it's a rather aggravating mechanic.

Say someone wants to reduce their local Mumble voice volume globally. Every other person then needs to manually increase that persons local volume in order for them to be heard at your/their relative level.

Is there perhaps some other global mumble volume slider that is meant to turn down only your local mumble volume level?

**Comment by mkrautz** [comment]
That shouldn't be the case.

Can you please provide more information?

What OS? (Version, build?)
What version of Mumble?
What sound system are you using?
What audio device?
etc.

**Comment by Enigma0** [comment]
User using the slider:
Win7 x64 (latest)
Latest from sites front page (1.2.5 I think)

Myself:
Win10 x64 (latest)
Latest x64 snapshot (1.3.x)

I was using an ASTRO A50 wireless headset. (connected over USB)

I had to adjust the Win7 guy +10dB to be about the same as he was before using the volume slider.

**Comment by Krzmbrzl** [comment]
To me this seems perfectly senseful: If you turn down your voice loudness then it makes sense that others will indeed hear your voice more silently than before. Or did I misunderstand the problem?
