### ISSUE TITLE
Total Control application by RPC

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2220]
[From @Oliveur, via mumble-voip/mumble#21939]

Hi,

It's juste a suggestion but can you add RPC control off all the client application parameter and command for send and receive.

Because mumble client works well on raspberry pi, its application areas beyond simple TOIP client.

So if we can control the client through anything other than the AC GUI would be perfect.

We can imagining a free interface mode like daemon mode.

Thanks in advance :+1:

**Comment by bontibon** [comment]
Duplicate #2051

**Comment by mkrautz** [comment]
Closing as duplicate.
