### ISSUE TITLE
OS X: Qt's own built-in ICNS reader doesn't handle alpha for Mumble.icns

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2234]
This is really a Qt bug, but it's a regression.

In 1.2.x, we used to have our own ICNS reader plugin for Qt that I wrote.
I was contacted by Jake Petroules about upstreaming the work. In the mean time, other contributors took over and implemented an ICNS reader in qtimageformats for Qt 5.

Unfortunately, Qt's own ICNS reader doesn't handle our Mumble.icns very well.

![screen shot 2016-04-30 at 20 05 50](https://cloud.githubusercontent.com/assets/36527/14937669/364d3424-0f0f-11e6-9d5a-876a716ee441.png)

**Comment by mkrautz** [comment]
Not yet reported upstream.

**Comment by mkrautz** [comment]
This works OK if we don't include JP2 (JPEG2000) support...

I think that's an OK compromise, since that's also what we do for 1.2.x at the moment... Removing 1.3.0 milestone....

**Comment by Krzmbrzl** [comment]
As this appears to be an upstream bug, I'll close this issue
