### ISSUE TITLE
DirectX11 support for Overlay

### ISSUE THREAD

**Issue by jammet** [mumble-voip/mumble#2239]
I've read that it's not supported yet - and also wondered why I never seem to see the Overlay in any games other than DayZ.

Now -- DayZ is going to discard DX9 very soon, and become a DX11 game. At that point I won't see the useful overlay anymore. So I'm opening this as a feature request. Hopefully it's not a duplicate, I tried to find others, but didn't.

**Comment by mkrautz** [comment]
Mumble 1.3.0 snapshots have DX11 support. If any of your games do not work, feel free to open issues regarding those!

Snaphots are available from mumble.info.

**Comment by jammet** [comment]
Thanks for the information. I wish this were pushed to stable, however -
then I'll go to 1.3.x for now.
