### ISSUE TITLE
[Request] Murmur server compatible with Raspberry Pi running CentOS 

### ISSUE THREAD

**Issue by Coxis** [mumble-voip/mumble#2240]
Hello,

CentOS has officially launched for Raspberry Pi. I was running a Murmur server on Raspbian with no problem, but I haven't found a version compatible with CentOS. How feasible would be to convert the package to CentOS flavor?

**Comment by hacst** [comment]
As it's the same architecture a maintainer shouldn't have much trouble porting the packages over. Afaik we do not plan on providing any CentOS packages ourselves at this point though. Sorry. We have some CentOS build guides (e.g. https://wiki.mumble.info/wiki/Install_CentOS7) in our wiki though I don't know how usable those are. Ideally someone from the CentOS community would pick up our upstream release (like it happens for some other distributions) and put them into the official repositories but so far noone did so :( It's the bane of the Linux distribution model to have to duplicate this work over and over again.
