### ISSUE TITLE
Service host "publist-registration.mumble.info" does not exist yet.

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2242]
The service host "publist-registration.mumble.info " does not exist yet.

We need this to be there for 1.3.0.

**Comment by mkrautz** [comment]
@hacst Why isn't it there? Because we lack service slots on Fastly?

**Comment by hacst** [comment]
I think that was a concious decision. For one I wasn't sure if putting it behind fastly wouldn't break it, on the other hand I couldn't think of what it would gain us to put it behind fastly as it isn't cacheable and the server needs to "call back" anyways.

**Comment by hacst** [comment]
That still leaves the "rewrite to new format" issue though. If we point directly at the host we have to do local rewriting. I could of course do that in fastly like for our other services (we even have the configuration slot left over to do so) if you prefer that. We would have to make sure it gets all the client information it requires even when passed through fastly.

**Comment by mkrautz** [comment]
The other reason: we can't do client certs with Fastly.

**Comment by mkrautz** [comment]
up-for-grabs TODO:
- [ ] Add mod_rewrite rule to mumble.info's Apache config (for mumble-info-ssl), the new service endpoint should only be available via SSL (as it was for mumble.hive.no)
- [ ] Fix Murmur's code to use the new endpoint.

mkrautz TODO:
- [ ] Ensure mumble.info's updated scripts and configs are in version control.

**Comment by mkrautz** [comment]
@hacst Weren't you doing the up-for-grabs ones? Or didn't you get far?

**Comment by hacst** [comment]
I setup a new vhost for publist-regstration and configured it to use the registration script for the endpoint url (no mod_rewrite). I also partially checked in the apache configuration.

**Comment by hacst** [comment]
With #3570 we now use the new domain and API endpoint.
