### ISSUE TITLE
I Hear Myself When Talking

### ISSUE THREAD

**Issue by iluvkunena** [mumble-voip/mumble#2251]
I've tried this on 5 different computers.. I've played with the volume controls, muted all loopback, echo, and made sure the listening option isn't check in my speaker settings.  Tried several headphones, and also tried both onboard and upgraded soundcards, and cannot get Mumble to stop playing my own voice back, while I'm talking.  Reducing the volume and mic gain helps a bit, but it's still there and worse I have to yell to compensate..

**Comment by Enigma0** [comment]
Have you tried a different headset/mic? Could be a hardware or internal feedback issue.
