### ISSUE TITLE
Request: ini variable for phonetic variant of the server name (for the root channel)

### ISSUE THREAD

**Issue by eligrey** [mumble-voip/mumble#2254]
I'd like to have a verbose server list name and a short/abbreviated root channel name, so my users don't get annoyed by "so and so moved in from [very long root name] by the server" TTS messages.

An ini variable like `registerPublicName` or `registerServerListName` for this purpose would be much appreciated. `registerName` could continue to be the variable used for setting the root channel name.

**Comment by mkrautz** [comment]
Is your use-case just having a shorter name for the root channel, and nothing else?

In that case, would something like

	; registerName is the name of the server shown in the public server list.
	; When set, this name will also be used as the name for the root channel.
	; If the other register* options are not set, this option will only be used as
	; the name of the root channel.
	registerName=eligrey's server - 100% uptime, always online, greatest server ever, no spam, no swearing, 

	; registerShortName is a shorter form of registerName.
	; If this is set, it will be used as the name for the root channel.
	; This allows you to have a longer registerName for the public
	; server list, and a shorter name for the root channel.
	; For registerShortName to be used, it MUST match the beginning
	; of registerName. If it does not, registerName will be used instead.
	registerShortName="eligrey's server"

This solves my biggest problem with this proposal: confusion. If you can set the root channel name to something arbitrary, and the long-form name is different from the root channel, how is the user to know that he/she has connected to the right server? Not everyone is savvy enough to check the IP/hostname.

What do you think?

**Comment by eligrey** [comment]
My shorter name would be an abbreviation, so it wouldn't exactly match up in this case. I see your concerns though. Maybe we need something like registerPhoneticName so that users can visually see the same root channel name and server list name, but TTS reads out something different.

**Comment by ngollan** [comment]
The split of short name vs. long name in @mkrautz's example above would IMAO be better served with a server name and an abstract, like:

```
registerName = eligrey's server

; registerAbstract sets additional text that a client can show in addition to the registerName.
registerAbstract = 100% uptime, always online, greatest server ever, no spam, no swearing, etc. etc. etc.
```

and TTS would only read out the `registerName`. The root channel name could be generated like `"{registerName} — {registerAbstract}"`.

**Comment by eligrey** [comment]
@ngollan The root channel name/server list name I want to use isn't really like @mkrautz's example. The main problem is that it uses a lot of non-English characters and formatting that the TTS takes forever to say. I'd simply like more control over the TTS by providing an alternate name that I know the TTS can say quickly.

Currently I just use an abbreviation with English characters as my root channel name that my users prefer for the TTS.

**Comment by mkrautz** [comment]
I suppose if we implemented phonetic nicknames (https://github.com/mumble-voip/mumble/issues/2210) we would implement a phonetic serve name as well.
Also phonetic channel names?

**Comment by eligrey** [comment]
@mkrautz Yeah, that all sounds good to me.

**Comment by bontibon** [comment]
Merging with #2210.
