### ISSUE TITLE
"Check for updates" references SVN

### ISSUE THREAD

**Issue by bontibon** [mumble-voip/mumble#2263]
When running a self-compiled version of Mumble, running checking for updates shows the following message:

> You are running a self-compiled SVN version on a platform without offical snapshots, and we're unable to determine if a new version is out.

SVN is no longer used.

**Comment by Enigma0** [comment]
Not necessarily relevant but you can still use SVN with Github repos.

**Comment by mkrautz** [comment]
Did `s/SVN/Git/g`. I wanted to remove the VCS from the message, but there were translations for various langauges -- so I just did the rename for now.
