### ISSUE TITLE
Chatlog section of UI separated from main window.

### ISSUE THREAD

**Issue by ionstorm66** [mumble-voip/mumble#2271]
Some how I separated the chatlog from the rest of the UI. I can't move the chatlog, but i can resize it. Changing the layout in settings won't reattach it, restore defaults won't either

[Imgur](http://i.imgur.com/mVz7tlJ.png)
[Imgur](http://i.imgur.com/MuGflpl.png)

**Comment by mkrautz** [comment]
I have had this happen to me before as well, but it was temporary...

Can you try running this reg file?

https://mumble.info/reg/mumble-full-ui-reset.reg

**Comment by ionstorm66** [comment]
Thanks that worked great. An odd problem to have lol.
