### ISSUE TITLE
Request: api for interacting locally with the client

### ISSUE THREAD

**Issue by PmmaGit** [mumble-voip/mumble#2278]
An api to interact locally with the client would be great, it opens the possibility to create and extend new ways to work with mumble from external applications.

for the time being, some of the things i can notably think of that would fit the api well are:

**\- Chat input/output manipulation (Text, Voice)**

Text output/input would allow things such as an external, more dynamic text chat interface.
Audio output, would allow to filter it more easily, removing the use of applications such as Virtual Audio Cable.

Regarding the input ones, the existance of a server-side setting allowing (or not) the usage of them could be beneficial, to prevent potential spam abuse.

**\- Mute/Deafen Control**

This one would allow external applications to make mumble react appropriately to them,
for example you could configure a video player to deafen mumble automatically when you start playing a video.

**\- Channel/User Lists**

A game could possible explore this to sort 'teams' of players through channels (when used under the control of a moderator) without the need of a server side implementation/access.

**Comment by mkrautz** [comment]
Some of these are duplicates of https://github.com/mumble-voip/mumble/issues/2051
but some obviously require tighter integration than is possible via RPC (i.e. audio plugins).
