### ISSUE TITLE
[Feature request] Opt out of speech dispatcher / tts at compile time

### ISSUE THREAD

**Issue by source83** [mumble-voip/mumble#2283]
Speech dispatcher blocks pulse/alsa for multichannel playback, and I don't use it to begin with.
I'd very much like to opt out of having the feature compiled at all as an option since speech dispatcher  libraries are required at compile time.
"TextToSpeech_unix.cpp:14:26: fatal error: libspeechd.h: No such file or directory"

**Comment by source83** [comment]
Okay, scratch that...
found the -DUSE_SPEECHD and -lspeechd in the Makefile.Release file.
It would be very beneficial with a configure script to be able to opt features in/out.

**Comment by mkrautz** [comment]
See INSTALL.

You can pass no-speechd to qmake, AFAIK.

**Comment by source83** [comment]
crap, sorry, you are correct.
Thanks :)
