### ISSUE TITLE
Feature request: Integration of new low bandwitdth codec "Codec2"

### ISSUE THREAD

**Issue by BuddyButterfly** [mumble-voip/mumble#2295]
Hi,

I want to request integration of a new open source low bandwidth codec named "Codec2" with the possibility to have configurable bandwidth. Such a codec would be of special interest when using mumble with low bandwidth via smart phones or even radio stations/handhelds. Please find the background of the codec below:

- Developer page Codec2: [http://www.rowetel.com/blog/?page_id=452](http://www.rowetel.com/blog/?page_id=452)
- Implementation example in FreeDV: [http://freedv.org/tiki-index.php](http://freedv.org/tiki-index.php)

Videos:
- FreeDV: [http://freedv.org/tiki-index.php?page=video](http://freedv.org/tiki-index.php?page=video)
- Codec2 mit Hardware-Modem: [http://www.rowetel.com/blog/?page_id=3902](http://www.rowetel.com/blog/?page_id=3902)

Tnx and keep on good work.

**Comment by hacst** [comment]
Hi. Currently we do not plan on supporting any new codecs. We only support Speex and CELT for legacy reasons these days. Our primary codec is Opus and once we get the next chance to break backwards compatibility it will likely become our only codec as that simplifies our life a lot.

Opus gives a excellent compromise over a big range of bandwith/latency ranges. Also it is an IETF standard and mandatory to implement for WebRTC support wich makes for robust and efficient implementations and easier interoperation where it is needed.

Thanks for the suggestion though. codec2 is definitely great at what it is doing.

(For reference: This was already asked in the (far) past https://sourceforge.net/p/mumble/feature-requests/795/)
