### ISSUE TITLE
Empty dbus folder in server snapshots

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#2296]
Upon updating the Linux server snapshot today I noticed that the dbus folder was empty. Since it's empty, if this is indeed intentional shouldn't the folder itself be removed from the snapshots as well?

**Comment by mkrautz** [comment]
Not intended.

**Comment by Krzmbrzl** [comment]
Did this happen again with a newer version? Specifically: Does this happen with the most recent version?
