### ISSUE TITLE
Mumble release key not signed

### ISSUE THREAD

**Issue by jonathancross** [mumble-voip/mumble#2302]
Would be great if the "Mumble Automatic Build Infrastructure 2016" key `0x5A2BE0C1` could be signed by the developers.  This would help users to verify that the binaries are "official" and not signed by some arbitrary key.   Thanks.

**Comment by mkrautz** [comment]
I agree with your point.

However, it is "out-of-band"-signed by my signature:
https://github.com/mumble-voip/mumble-gpg-signatures/blob/master/gpg.txt

(The whole document is clearsigned.)

**Comment by jonathancross** [comment]
Thanks, that helps.
A signature on the key itself would be easier for users to verify, but at least this signed message ties the build key to you  :-)
