### ISSUE TITLE
'Dynamic' build of mumble 1.3.x

### ISSUE THREAD

**Issue by DofuUZ** [mumble-voip/mumble#2305]
I'm trying to build win32-dynamic build of mumble.
That's for 2 reasons. I want to build custom mumble client without opening source. And I need to use QtWebEngine which cannot built with static configuration.

I built '.dll' version of Qt5, and tried to link with mumble but it was not enough I think. It faild.

I request the 'dynamic' build of windows version of mumble.
Or is there any guidance or ongoing work with this?

Thank you.

**Comment by mkrautz** [comment]
We don't officially support a dynamic build of 1.3.x on Windows.

You should however be able to either modify the win32-static buildenv to build all dependencies as dynamic. (Or perhaps just the ones that are under the L/GPL.)

Note that ZeroC Ice for the server is under the GPL. But 1.3.x now includes experimental support for gRPC, which is Apache licensed.

One thing you could do as a start is to build the buildenv/1.2.x/win32 environment.

That thing *should* be able to build Mumble 1.3.x.
But it uses Qt 4 by default. But, Mumble 1.3.x still supports Qt (with a CONFIG option).

Once you know you can build a dynamic Mumble with that build environment, you could move the qt5.build recipe into that environment and build it. (And change Mumble to use that.)

...Alternatively, you can also:

Use the win32-static environment, but with a dynamic Qt build from qt.io.

Or, provide all dependencies yourself.

If you want to build it yourself, you can have a look at this historic version of the BuildingWindows page from the Mumble wiki:
https://wiki.mumble.info/index.php?title=BuildingWindows&oldid=8849
It contains the instructions we used before we had the automatic build environments.

Hope it helps.

**Comment by mkrautz** [comment]
I closed this because it isn't really something we're going to fix. (The build is intended to be static.)

But if you're interested in maintaining a win32-dynamic build environment in mumble-releng -- and if the delta is quite small -- maybe that's an idea we should pursue.

**Comment by mkrautz** [comment]
Feel free to still ask questions in here though. I'll be happy to take a look and answer if I can.

**Comment by DofuUZ** [comment]
Thanks for answer. I'll give a try.
