### ISSUE TITLE
Awful text rendering on OS X

### ISSUE THREAD

**Issue by w4** [mumble-voip/mumble#2306]
(Click the images)

![](http://xn--83h.ws/69idfkrORL.png)

Compared to other applications:

![](http://xn--83h.ws/WRSiRNzZjo.png)

**Comment by w4** [comment]
![](http://xn--83h.ws/48VCB0I0gJ.png)

**Comment by mkrautz** [comment]
Mumble 1.3.0 (snapshots) has retina support, please use that instead!

**Comment by w4** [comment]
That fixed it, thanks mate.
