### ISSUE TITLE
Mumble 1.2.16 for Windows Uses Lots of Memory and Crashes

### ISSUE THREAD

**Issue by Vocylis** [mumble-voip/mumble#2311]
Hello,

After updating to the stable release of Mumble 1.2.16 for Windows, I noticed that after around 20 minutes or so of being connected, mumble uses a high amount of memory, other people's voices start cutting out, and upon opening the Mumble application from the system tray, it crashes. I have tried a reinstall, but that has not fixed anything. My operating system is Windows 10 (64-bit).

**Comment by Kissaki** [comment]
Which version did you upgrade from?
Is that with voice, channel and server activity?
With overlay in use? Hotkeys?
Is this also an issue with no voice activity - e.g. in an empty channel?

**Comment by Vocylis** [comment]
I apologize for the late reply.

1. I am not sure what version I upgraded from, sorry.
2. In my experience, it happened whenever talking.
3. I do not think the overlay was in use. I have hotkeys for muting and muting and deafening myself.
4. I think it is only with voice activity.

**Comment by Krzmbrzl** [comment]
Did you encounter the same problem with Mumble 1.3?

**Comment by Vocylis** [comment]
Thank you for your reply, @Krzmbrzl. This issue is over 3 years old though and I have since moved away from using Mumble. I will close the issue now due to the timeframe.
