### ISSUE TITLE
Mumble server information window exceeds screen resolution

### ISSUE THREAD

**Issue by jtl999** [mumble-voip/mumble#2312]
Using Mumble 1.3.0~970-g88a459 on OS X 10.11.5

Macbook Pro Retina running at 1280x800 HIDPI resolution

Screenshot should be pretty self explanatory.

![](https://i.imgur.com/tOrtvgA.png)

**Comment by Hartmnt** [comment]
This was fixed with #4891 (Dup #3263)

**Comment by Krzmbrzl** [comment]
From now on legends shall refer to you as "duplicate issue master detective" :D
Thanks!
