### ISSUE TITLE
SyntaxHighlight extension for wiki.mumble.info

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2316]
Friday, May 27th, 2016
	18:42:51 <davidebeatrici> Hi
	18:43:15 <davidebeatrici> I see that by default MediaWiki doesn't have a code highlight feature
	18:43:20 <davidebeatrici> I found this plugin: https://www.mediawiki.org/wiki/Extension:SyntaxHighlight
	18:43:36 <davidebeatrici> Could you install it on Mumble's Wiki? I think that the code will be much more clear with it :)
	Sunday, May 29th, 2016
	13:30:30 <davidebeatrici> https://wiki.mumble.info/wiki/Games
	13:30:39 <davidebeatrici> I updated the Wiki page :)
	13:34:32 <davidebeatrici> What do you think about the Syntax Highlight? :)
	15:26:36 <mkrautz> sounds good to me, but I'm not the one taking care of the wiki
	15:26:51 <mkrautz> maybe open an issue?

**Comment by hacst** [comment]
Fine with me too. As long as there's something reasonably stable/secure out there we can use. Every kind of extensions/option always carries some additional risk these days ;)

**Comment by davidebeatrici** [comment]
I think that it's safe to use, because it's constantly updated and used by almost every Wiki, [including Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Syntax_highlighting).

This is the latest stable release: https://extdist.wmflabs.org/dist/extensions/SyntaxHighlight_GeSHi-REL1_26-a15f02e.tar.gz :wink:

**Comment by Natenom** [comment]
According to https://www.mediawiki.org/wiki/Extension:SyntaxHighlight this extension is already bundled with the used MediaWiki version on wiki.mumble.info. One needs to enable it.

**Comment by davidebeatrici** [comment]
@actown @hacst: Could you take a look at this pull request, please? :wink:

**Comment by mkrautz** [comment]
We're all in agreement that it should be enabled.

Who can actually do it, though? I don't have SSH access to the wiki host.

**Comment by hacst** [comment]
I'll take a look.

**Comment by hacst** [comment]
Really did just work out of the box. Updated https://wiki.mumble.info/wiki/Link to show it in action.
