### ISSUE TITLE
a11y: Ability to move users with keyboard

### ISSUE THREAD

**Issue by jcsteh** [mumble-voip/mumble#2322]
As far as I've been able to discover, the only way to move users into other channels is by dragging and dropping with the mouse. Screen readers do have some functionality to do this, but it's inelegant at best and I can't seem to get it to work in Mumble at all. It'd be great if there were some way to do this via the keyboard. I can think of two possible solutions, but there may be better ones:
1. Emulate cut/paste. You first select the user(s) to move in the tree and press control+x to "cut" the user(s) to be moved. You then select the target channel in the tree and press control+v to "paste" the user(s) into that channel. Note that "cutting" doesn't actually remove them from the tree; it just marks them. This is similar to how cut/paste works in Windows File Explorer.
2. Dialog/pop up menu. You select the user(s) to move in the tree and then activate a command (e.g. from the context menu). This command presents a dialog or pop up menu from which you can select the target channel.

I prefer option 1, since it keeps everything within the same tree and is natural for keyboard users who already do this elsewhere (e.g. Windows File Explorer).

**Comment by lilmike** [comment]
100% +1. I really need this feature for some users who often talk on tablets and have trouble with the touch screen at best. Any plans?
-Michael.

**Comment by stormdragon2976** [comment]
I was really surprised this was an issue. Mumble does so good with a11y on most things, but I went to move a user, and no dice. I could really use this functionality.

Thanks

**Comment by jticket1024** [comment]
I too could really use this functionality. I have been using mumble for some time now, and this can really come in handy.

**Comment by Krzmbrzl** [comment]
Closing in favor of #4642 (same issue, but with more votes)
