### ISSUE TITLE
Add hide/show mumble window option to keybindings dropdown

### ISSUE THREAD

**Issue by danthedaniel** [mumble-voip/mumble#2328]
Personally I would find it pretty useful to be able to bind a key to toggle hiding mumble.

**Comment by terenc3** [comment]
@Krzmbrzl Why is this issue still open? It got merged and is available in the latest 1.4 version

**Comment by Krzmbrzl** [comment]
Because GitHub doesn't use `Implements` as one of those magic keywords that automatically link PRs and issues (as is the case for e.g. `Fixes`) and it appears we forgot to close this manually.
Thanks for pointing this out though :+1:

Fixed via #4562
