### ISSUE TITLE
Auto normalize 

### ISSUE THREAD

**Issue by BenjaminArgentine** [mumble-voip/mumble#2330]
Murmur: please add an 'automaticGainControl' option in the conf file to toggle automatic normalization of the volume of each input.

**Comment by Kissaki** [comment]
![2016-06-08 00_21_43-clipboard](https://cloud.githubusercontent.com/assets/93181/15876666/01d2e25c-2d0f-11e6-941b-c3ff09fdd0ca.png)

We have a noise suppression and max amplification setting that may fit your description?

It is only visible after enabling advanced in the settings dialog.

**Comment by mkrautz** [comment]
What's the use case?

We're unlikely to add this to Murmur, but I'm fine with adding a (hidden) config option.
