### ISSUE TITLE
Mumble "paste and send" appends infotext

### ISSUE THREAD

**Issue by ranzpirat** [mumble-voip/mumble#2331]
When directly right-clicking on the chatbar in an unfocused window and using "paste and send" the "Type message to channel 'NAME' here" gets appended to whatever gets send.

Running Mumble 1.2.16 on GNU/Linux 4.5.4-1-ARCH with qt 4.8.7.

**Comment by Kissaki** [comment]
Not a problem for me on Windows, with 1.3.0. Right click will focus the window (which may hide the otherwise existing issue).

**Comment by ranzpirat** [comment]
I can confirm that this does not affect me on my windows installation, but I can reproduce the behaviour on a ubuntu 14.04 installation at work with mumble 1.2.4 and qt 4.8.5

Both this machine and my desktop at home are running xfce/xfwm as windowmanager.

**Comment by elouin** [comment]
Also not a problem running mate on arch. Same as with windows the window gets focused.

**Comment by ranzpirat** [comment]
This still affects me on all machines running xfce/xfwm (which is ubuntu, arch linux and fedora) ranging from xfce versions 4.10 to 4.12 and all mumble versions distributed by the os-vendor. I'm happy to provide additional info if it helps.

**Comment by ranzpirat** [comment]
Doesn't happen anymore using ubuntu 1804 with xfwm4 4.12.5 and mumble 1.2.19
