### ISSUE TITLE
feature req: Use of up and down arrow keys in message edit box

### ISSUE THREAD

**Issue by hamilton5** [mumble-voip/mumble#2332]
Several irc clients have this ability to hit the up arrow key to bring up past sent text messages. Another FQ would be the ability to throttle chat so it is not flooded / spammed.

**Comment by bontibon** [comment]
> hit the up arrow key to bring up past sent text messages.

In Mumble it's Ctrl+Up, Ctrl+Down

**Comment by Kissaki** [comment]
Contrary to IRC clients, you can do multiline text in Mumble. SHIFT+Enter will insert a line break.

In a multiline message, up and down will move the text cursor up and down as one would expect.

**Comment by hamilton5** [comment]
very nice, thanks bontibon and kissaki! Any where to check out the other not so obvious shortcuts?

**Comment by Kissaki** [comment]
No, I don’t think so. :)
