### ISSUE TITLE
Certificate crashes murmur

### ISSUE THREAD

**Issue by Skippidar** [mumble-voip/mumble#2334]
When i try to connect to server with COMODO signed sertificate - server crashes. When i use private sertificate, generated by Mumble - i successfully connect to server.

P.S.: Static Linux Server - 1.3.0~1307~g3e1d7ed~snapshot (Fedora 23, Linux-4.4.9-300.fc23.x86_64)

**Comment by Skippidar** [comment]
I've just checked some 1.3.0 servers. Some of them crash, some of them not (or they have auto-restart, but untill i stop auto-reconnecting, they continue crashing every 2 sec).

**Comment by schlarpc** [comment]
Is this you? My server just started crashing about 30 minutes ago.

`<W>2016-06-06 23:56:33.051 1 => <7:(-1)> New connection: 82.179.72.68:50968
<W>2016-06-06 23:56:33.183 1 => <7:(-1)> SSL Error: The root CA certificate is not trusted for this purpose
<W>2016-06-06 23:56:33.189 1 => <7:(-1)> SSL Error: No certificates could be verified
<W>2016-06-06 23:56:33.195 1 => <7:(-1)> Connection closed:  [-1]
`

**Comment by mkrautz** [comment]
I believe there is a problem in 1.3.0 where if you try to connect without a full certificate chain, this will happen.

**Comment by Skippidar** [comment]
@schlarpc Yep, ip looks like mine. Sorry for this, i was trying to connect to any server, but forgot about auto-reconnecting.

**Comment by mkrautz** [comment]
Workaround in https://github.com/mumble-voip/mumble/pull/2335

I believe the bug is a regression introduced in Qt 5.
Working on submitting a patch upstream to fix it 'properly'.

**Comment by mkrautz** [comment]
FWIW, Qt bug is https://bugreports.qt.io/browse/QTBUG-53906.

**Comment by Skippidar** [comment]
And what about connecting to 1.2.X servers? They don't allow me to connect with COMODO sertificate.

**Comment by mkrautz** [comment]
@Skippidar The problem is that you haven't imported all needed intermediate certificates into Mumble.

It is disconnecting you, because the server can't verify your certificate chain.

You can fix it by including all intermediates in Mumble.

There's a pending pull request to allow you *in* without a full chain (https://github.com/mumble-voip/mumble/pull/2336) -- but in that case, the certificate would not be deemed **strong** (just like a self-signed certificate wouldn't).

**Comment by Skippidar** [comment]
Yep, problem with crashes solved.

But i did everything as said here https://wiki.mumble.info/wiki/Obtaining_a_Comodo_Certificate 
And i use Firefox, not Chrome for exporting certificate. But i can't connect anyway.
