### ISSUE TITLE
design update 

### ISSUE THREAD

**Issue by Announcement** [mumble-voip/mumble#2337]
may i request a refresh / design update?
yanno something that doesn't look like it's from the sixties, so I can convince my friends to use it...
oh and video calling.
I'd much rather use open source than skype.

**Comment by bontibon** [comment]
Mumble 1.3.0 uses a [new theme](https://github.com/mumble-voip/mumble-theme), previously known as "MetroMumble":

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323230343936382f313937353632392f36333938303632302d383337662d313165332d396630622d3538303364646562363430332e706e67](https://cloud.githubusercontent.com/assets/110883/15891910/3f54f8e8-2d4d-11e6-8c48-ddb6dbbd2127.png)

**Comment by Brottweiler** [comment]
Go into the mumble settings, then "User Interface" to enable above theme.

**Comment by mkrautz** [comment]
> Go into the mumble settings, then "User Interface" to enable above theme.

But note that it is only availalbe in 1.3.0.

**Comment by Tarun80** [comment]
Interesting. I'm on the snapshots (1.3.0~1318) and my comment button is purple for the Lite theme?

**Comment by Brottweiler** [comment]
The bundled mumble theme is slightly tweaked version of Metro Mumble.

**Comment by Tarun80** [comment]
Thanks for that, Brottweiler.

**Comment by Kissaki** [comment]
@Announcement Would that resolve your request? Or were you aware of the 1.3.0 skins?

If so, could you provide some suggestions for improvements, and point out specific issues you have with the design?
