### ISSUE TITLE
Import external rooms of mumblers with full arborescence

### ISSUE THREAD

**Issue by BenjaminArgentine** [mumble-voip/mumble#2338]
Actually, a symbolic link to a room of another mumble allow to listen to its mumblers but show it as a unique, agregated mumbler. 

The request is to allow to show the full arborescence of the room (check for loops!), in order to build a resilient, forkable and duplicatable web of nodes.

**Comment by Kissaki** [comment]
What? Are you asking for two things here? Importing a channel tree (configuration), and symbolic link channels redirecting transparently to another channel?

**Comment by Krzmbrzl** [comment]
Could you please elaborate on what you want? I can't seem to grasp it either...
