### ISSUE TITLE
Give an option not to create a desktop shortcut

### ISSUE THREAD

**Issue by TBotV63** [mumble-voip/mumble#2346]
I only have shortcuts for very few programs on my desktop. It would be nice if there was an option not to create a new Desktop shortcut every time Mumble updates.

**Comment by mkrautz** [comment]
Might be related to https://github.com/mumble-voip/mumble/issues/1845

Since we do a full uninstall, then a reinstall, the installer probably puts the shortcut there again.
If we used the default MSI/WiX behavior, it might not have done it.

**Comment by davidebeatrici** [comment]
There's already the option in the installer to not create a desktop shortcut. :wink: 
![shortcut](https://cloud.githubusercontent.com/assets/5897523/17444616/3d2449c6-5b41-11e6-8925-9408732e55c2.PNG)

**Comment by TBotV63** [comment]
Well yes, the development version has. And I believe it was a semi-recent addition to the dev version too. I'm not that blind (I hope?). However the release version has yet to see that change. As of now this issue no longer occurs on my end, using the development snapshot "1.3.0~1500~g8bdfd7d~snapshot".
