### ISSUE TITLE
Positional and Stereo backwards

### ISSUE THREAD

**Issue by archrin** [mumble-voip/mumble#2352]
I'm using Logitech G430 gaming headset, plugged into the USB dongle. The surround works fine in games. Most recently Overwatch. However when I'm running Mumble with positional audio set, all the sound positions are backwards, including front to back. It's even evident in the wizard. The little green dot is exactly opposite of the apparent sound. When I turn off positional audio, it goes back to stereo, and I lose the surround in the game.

**Comment by davidebeatrici** [comment]
It seems like a lot of people is having this type of problem with your same headset; you can find a lot of results correlated by searching "Logitech G430 backwards" on Google.
I don't think this is a problem of Mumble :wink:
