### ISSUE TITLE
Every update breaks the taskbar icon/pin in Windows

### ISSUE THREAD

**Issue by Enigma0** [mumble-voip/mumble#2357]
After installing the update, the taskbar app pin is broken. Has to be removed and re-added.

OS: Windows 10 (latest)
Mumble: 1.3.0 snapshot

https://i.imgur.com/zYpGceV.png

**Comment by davidebeatrici** [comment]
The installation path is like this: `C:\Program Files\Mumble\Versions\1.3.0~1326~gf4ca0cf~snapshot`.
The folder "1.3.0~1326~gf4ca0cf~snapshot" is the version name and changes every update, this is why the taskbar app pin breaks :wink:

**Comment by mkrautz** [comment]
No it isn't -- or at least, shouldn't be.

`mumble.exe` is not inside the versioned path.

The reason is breaks is because the installer removes the shortcut, because we changed the installer to do a full uninstall because of other bugs...

**Comment by mkrautz** [comment]
Duplicate of #1845.

**Comment by davidebeatrici** [comment]
You're right, I got confused, sorry.
@Enigma0 To fix that you should probably pin `mumble.exe` to the taskbar and not the shortcut :wink:

**Comment by Enigma0** [comment]
@davidebeatrici , @mkrautz 
Hey so I pinned the exe itself but the issue still remains. This isn't fixed and needs to be re-opened.

Path is: `"C:\Program Files\Mumble\mumble.exe"`

**Comment by Enigma0** [comment]
@davidebeatrici Unfortunately that doesn't fix it.
