### ISSUE TITLE
Usability issue with "sub" group

### ISSUE THREAD

**Issue by fwaggle** [mumble-voip/mumble#2359]
A user on Reddit and I collectively discovered that the "sub" group is a special case: all other groups update the ACL when the group box loses focus, so you can type the group name and press "OK" and the changes are saved.

"Sub" behaves differently - if you type out sub, it changes immediately when the box loses focus, but the parameters for constraining depth don't seem to save unless you press enter on the box. So if you type out say "sub,1,2,3" in the group box then click "OK", only "sub" is saved.

Is this for a specific reason, or is there a bug because it takes arguments? Is it possibly related to the fix for #1199?

If no one else picks this up I'll check into it when I have more free time.

**Comment by mkrautz** [comment]
Hmmmm...

It only works in the way you describe because of completion (I guess).

For example, the text field losing focus doesn't auto update the group name if you type in "custom", fore example.
