### ISSUE TITLE
Better distinguish private messages

### ISSUE THREAD

**Issue by schmatzler** [mumble-voip/mumble#2362]
The only difference between private and public messages is the string "(Channel)" in front of them.

This isn't very userfriendly and leads to confusion, i.e. users referring to messages others shouldn't have seen by mistake.

An option to have them highlighted with a background color would be a good fix, imho.

**Comment by Natenom** [comment]
What do you think about this instead of an option for highlighting?
* (Private) for private messages...
* (Channel) for channel messages...

**Comment by schmatzler** [comment]
Thanks! :)
