### ISSUE TITLE
Audio not working after a while

### ISSUE THREAD

**Issue by janniklorenz** [mumble-voip/mumble#2368]
After a while being muted, audio output (sounds and other people) and input is buggy. The talking lights also don't light up from other people, and my light behaves just normal. Reconnecting solves the issue.

It's quite hard to reproduce, but it happens to me and other people at least once a day, after being muted for about one hour. Are there other people having this Problem?

We've tested it on OS X 10.11 with 1.2.15/.16 and 1.3.0 and debian 1.2.8-2 (repo, qt 4.8.6) with murmur 1.2.15/.16.

**Comment by mkrautz** [comment]
Some things to test when this happens:

If you open the Audio Statistics dialog (Self -> Audio Statistics), does Mumble still register your Mic?

If it does, then perhaps the UDP connection is not doing well.
Try talking, and look at your number of packets transmitted (UDP Network Statistics in User Info, "From Client"). Does it increase as expected?

Could be that the UDP connection is flakey and doesn't really work anymore.
Could also by that our encryption layer is not working, i.e., there's a mismatch between server and client, and the server can't decrypt the packets it's receiving. To test this, you could temporarily try to switch to TCP mode. Does transmitting work then?

**Comment by janniklorenz** [comment]
Thanks for the quick reply, just happened again.

Yes, the mic is still working well. The number of UDP packets "From Client" isn't increasing, while "To Client" is, when someone else talks.

To enable forcing TCP Mode fixes it, but is it a bug in mumble or networking problem with my server?

**Comment by Kissaki** [comment]
It is unlikely to be the on the server (provider) end. Do other users on the server experience the same issue?

So it seems to be limited to UDP. It may be your router or internet service provider. It seems that upon not transmitting for some time, some networking node drops/ignores future packets/closes the connection.

Can you check your router or firewall (if you have one) for any such security or flood protection settings?

**Comment by janniklorenz** [comment]
It happens to other people I know as well, which are using a different ISP and different Hardware. Everything run well the last 1/1,5 years.

I've got enabled the force TCP mode awhile, and I noticed some disconnects followed by auto reconnect. Maybe this happens to the UDP connection as well, but didn't get noticed?

I can ask, if the server has any flood protection enabled. The firewall is open for TCP/ UDP.

**Comment by mkrautz** [comment]
I have seen people with this issue before. It's a long-standing issue. I do not know whether it's a networking issue, or a Mumble issue though.

Possibly related to https://github.com/mumble-voip/mumble/issues/1968

**Comment by sandervg** [comment]
Look like we have the same issue. We use the application for broadcasting an intercom. We put all the clients op talk continuously and we noticed that some clients at random times stop to broadcast. Lip icon is gray for all other user except themselves. Opening settings and reselect  continuously seems to solve it temporarily. We will test it with **Forced TCP** mode on now. Can anybody tell me what the negative side effects are by using TCP packages?

**Comment by Krzmbrzl** [comment]
Does this also happen with Mumble 1.3?
@sandervg which version of Mumble did you experience that with?

**Comment by sandervg** [comment]
Hi @Krzmbrzl we currently stoped using mumble for this purpose. So I can't recall if this is fixed on version 1.3. Thanks for following up.
