### ISSUE TITLE
Pulseaudio input is not saved

### ISSUE THREAD

**Issue by Brottweiler** [mumble-voip/mumble#2369]
Using mumble `1.3.0~1372~gd21de05~snapshot` and Pulseaudio 8, each start of mumble will have "Built-in Audio Analog Sterio" selected as input, rather than my microphone. So every start of mumble, I need to open `pavucontrol` and switch the input.

After starting mumble:
![](https://i.imgur.com/74BMUX3.png)

After fixing the input to the proper one:
![](https://i.imgur.com/bUNKiaP.png)

**Comment by mkrautz** [comment]
Possibly broken by https://github.com/mumble-voip/mumble/commit/a50a120b2c398afe41801ae7d14c805ceac73110

**Comment by Brottweiler** [comment]
As I just made this issue, I realised that in the option menu of the `pasystray`, I can select "Default Source", and it seemed to have been set to `Built-in Audio Analog Sterio`, rather than my microphone.

Now, I've never changed this before, so I think as you say this is a mumble bug anyway, that it won't save it?

**Comment by mkrautz** [comment]
I am not sure if it is a Mumble bug.

The commit I referenced will revert back to the default device if the device Mumble was last set to is no longer present.

What I meant by "possibly broken" is that it is possible the patch doesn't work as intended -- for example, if there is a race in the code, such that `outputDevice()` or `inputDevice()` are called and used before PulseAudio has returned the correct list of devices to us.

**Comment by Brottweiler** [comment]
Then it's possible it might have been caused by me in the first place, that I somehow made the microphone not be default. It's possible, since the other day I was experimenting with JACK, and using that with pulse it adds it's own sinks, so it might have resetted it.

**Comment by mkrautz** [comment]
If it has an actual PulseAudio sound device, and not Mumble's "Default device" selected, then I think it's because you changed your default device by accident.

Please re-open if you think otherwise.
