### ISSUE TITLE
Only One Person Can Hear Me?

### ISSUE THREAD

**Issue by Kraftec** [mumble-voip/mumble#2379]
So I recently got a new microphone because my old one didn't work at all with Mumble, but for some reason only one person can hear me?

I'm using Windows 10

**Comment by Kissaki** [comment]
That probably has nothing to do with your microphone.

Can you hear yourself in the audio wizard?

Did you try on a different server with other people? How many people did you test with?

**Comment by Kraftec** [comment]
I can hear myself and I tested it with 8 people on the server.

**Comment by Kissaki** [comment]
You can hear everyone? Everyone else can hear each other?

Are you sure you’re not whispering to a single person (keybind) rather than using push-to-talk?

**Comment by DGMurdockIII** [comment]
i thnk there right you need to do the audio wizzard and read it closely and do what it says
