### ISSUE TITLE
QStyleOptionViewItemV4 is deprecated as of Qt 5.7

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2381]
`UserView.cpp:33:25: warning: ‘QStyleOptionViewItemV4’ is deprecated [-Wdeprecated-declarations]`

Introduced in https://github.com/mumble-voip/mumble/commit/b39f73be

Seems like the fix should be simple?
https://git.reviewboard.kde.org/r/128208/diff/1#index_header

**Comment by mkrautz** [comment]
cc @pcgod - in case you have any insight (you wrote the code initially)

**Comment by hacst** [comment]
So. Uh. Does it still compile and not break anything obvious visually? ;) If so I guess we can just do what they did in the patch you linked.

**Comment by mkrautz** [comment]
I haven't tried it yet. :-)
