### ISSUE TITLE
G Data anti virus reports http://de.mumble.info/plugins/gtaiv.dll is a virus

### ISSUE THREAD

**Issue by UdoKifferbrehl** [mumble-voip/mumble#2385]
Hi,
when I start Mumble on Windows 10 I get a warning from G Data: 
http://de.mumble.info/plugins/gtaiv.dll is a virus?
Do you know anything about that?
Thanks.

**Comment by mkrautz** [comment]
I'm pretty sure it's a false positive.

Take a loot at a scan of the file here:
https://www.virustotal.com/en/file/0ade9891a2e23fbccb9af2ec1c43dd4b4586c57fb85648ad797630bb92a82c33/analysis/

Also, it's worth noting that while the file is downloaded from an HTTP URL in Mumble 1.2.x, Mumble will verify its Authenticode signature before making use of the file.

You can for example try to download the file from that URL, and upload it yourself to Virustotal:
https://www.virustotal.com.  If you get the same URL as I do above, you'll know that we have the same file, and I have vouched for that one.

If G Data is reporting that file as a virus, then I would suggest that you submit that to G Data as a false positive, and see what they say. According to http://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm, you can submit false positives to G Data using the following form:

https://su.gdatasoftware.com/us/sample-submission/

Thanks,
Mikkel

**Comment by UdoKifferbrehl** [comment]
Yes, I think that it is a false positive too and have informed G Data. I also uploaded the file to virustotal and got the same result. Thanks @mkrautz

**Comment by mkrautz** [comment]
Excellent, thanks!

Please update this thread once you hear back from G Data.

**Comment by mkrautz** [comment]
With the assumption that this was indeed a false positive, I'll close this thread.

If anything comes up, and G Data responds that they fell that it is not, feel free to respond, and we can re-open it.

Thanks!
