### ISSUE TITLE
Mumble 1.3.0~1383~g4f4e5ac G15 LCD applet blank

### ISSUE THREAD

**Issue by dekeonus** [mumble-voip/mumble#2386]
With the 1.3.0~1383~g4f4e5ac snapshot the Logitech G15 LCD applet does not display anything on a Logitech G13 keypad.
The plugin appears to load (mumble-g15-helper.exe is running and is selectable within the G13 keypads controls) but the LCD display is blank.
This is for the mumble-1.3.0~1383~g4f4e5ac~snapshot.winx64.msi the 32bit win client was not tested.
The mumble-1.3.0~1372~gd21de05~snapshot.winx64.msi G15 applet is working 

edit: updated with info about last snapshot with working G15 applet

**Comment by mkrautz** [comment]
Hm, very odd. We haven't touched anything related to G15...

**Comment by mkrautz** [comment]
Hi @dekeonus, @StupidGenius,

Does this still happen for you with the latest snapshot, 1.3.0~1434~g6a78217~snapshot?

x86: https://dl.mumble.info/snapshot/mumble-1.3.0~1434~g6a78217~snapshot.msi
x64: https://dl.mumble.info/snapshot/mumble-1.3.0~1432~gf241782~snapshot.winx64.msi

Thanks.

**Comment by dekeonus** [comment]
Yes the LCD is still blank with mumble-1.3.0~1434~g6a78217~snapshot.winx64 (I have not tested the 32bit builds and will not be able to for at least a few days possibly more)

**Comment by mkrautz** [comment]
OK, thanks.

Perhaps it's a drawing when drawing 1-bit on new-ish Qt versions... I'll try to check that.

**Comment by mkrautz** [comment]
Haven't had time to check it out yet.

I'm imagining we'd need a simple "emulator" version of g15helper that, instead of communicating with the G15 library, simply displays the received images on the screen/terminal....

**Comment by InteliWasp** [comment]
I have noticed this bug as well on my G15 keyboard for the last 2 snapshots. If it helps i noticed that the mumble logo that apears when mumble is not connected to a server is also missing parts.  [picture](https://goo.gl/photos/yGzvzk97QRrBriUK9)  I hope this helps as i do enjoy using the LCD screen

**Comment by mkrautz** [comment]
OK.

This seems to be caused by the upgrade to Qt 5.6.

I just tried the emulator I implemented in https://github.com/mumble-voip/mumble/pull/2428 on the snapshot 1.3.0~969~gbc12e8e, and there, the G15 widget renders just fine.

In Qt 5.6-based Mumble snapshots, it is just totally black.

**Comment by mkrautz** [comment]
Also, the G15 widget is usually black. It is in the Qt 5.5-based snapshot:

![image](https://cloud.githubusercontent.com/assets/36527/16887236/116a9b46-4ad9-11e6-8dd0-8d9434d1ae22.png)

...It's probably a text rendering issue.

**Comment by mkrautz** [comment]
Workaround at https://github.com/mumble-voip/mumble/pull/2430

**Comment by mkrautz** [comment]
Hi,

I've included the workaround in https://dl.mumble.info/mumble-1.3.0~1471~gac134d3~snapshot.winx64.msi

Can you please test if this works better for you?

Thanks.

**Comment by StupidGenius** [comment]
@mkrautz Yep, it is working. I used the (32 bit) binary here https://dl.mumble.info/mumble-1.3.0~1471~gac134d3~snapshot.msi (x86) instead of the 64-bit you linked, and I can confirm the Mumble app/interface is working on my G15's Display on Windows 10. Thanks!

**Comment by mkrautz** [comment]
Excellent -- it looks 100% correct?

**Comment by dekeonus** [comment]
Looks good here on a G13 with the 64bit build on win7pro x64

**Comment by mkrautz** [comment]
Excellent! Thanks for reporting this.

**Comment by StupidGenius** [comment]
@mkrautz Yeah, looks correct as far as I can tell, here is a picture: http://imgur.com/ErcXakX.jpg
