### ISSUE TITLE
Question marks instead of symbols in welcome message

### ISSUE THREAD

**Issue by edo44** [mumble-voip/mumble#2389]
In my Raspberry Pi server's welcome message I have question marks instead of symbols like ">>" and "è"

![mumble_2016-07-03_17-40-08](https://cloud.githubusercontent.com/assets/13797216/16546394/0c2334fc-4149-11e6-8920-3f8f5f603b59.png)

Why is that? I've been having this problem ever since I reinstalled the OS.

**Comment by mkrautz** [comment]
If this was set in murmur.ini, please ensure that your text is UTF-8 encoded. Murmur expects an UTF-8 encoded murmur.ini.

**Comment by edo44** [comment]
> If this was set in murmur.ini, please ensure that your text is UTF-8 encoded. Murmur expects an UTF-8 encoded murmur.ini.

It was placed in mumble-server.ini actually.

**Comment by mkrautz** [comment]
That's what Debian-based distros call murmur.ini.

**Comment by edo44** [comment]
> That's what Debian-based distros call murmur.ini.

I see. I put `<head><meta charset="utf-8"/></head>` but it doesn't work.

**Comment by mkrautz** [comment]
Just make sure the file itself is saved as UTF-8 in your editor, I believe that should be enough. :-)

If your editor is unwilling, you could also escape the characters, such as:

è -> `&#xe8`

etc. (http://www.codetable.net/unicodecharacters)

**Comment by edo44** [comment]
> Just make sure the file itself is saved as UTF-8 in your editor, I believe that should be enough. :-)

Oh, it was so simple, thank you!

**Comment by mkrautz** [comment]
Excellent. Closing as resolved.

If you have any further issues, feel free to comment here -- and I can re-open the issue if necessary.
