### ISSUE TITLE
Overlay blacklist updates for 1.3.0

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#2422]
The Radeon Settings application (included in the AMD GPU driver catalyst) shows the Mumble overlay.

Unfortunately, when I added `RadeonSettings.exe` to the default blacklist, it did not seem to work for me. I wonder if it draws from/in a different process? :confused: 
Maybe I’ll(/someone) just have to try again…

**Comment by mkrautz** [comment]
My semi-recent change that introduced better support for the overlay in Windows games, .e.g EVE, has caused the overlay to appear in a lot of new places. Also appears in iTunes...

**Comment by mkrautz** [comment]
Which is also why progress on https://github.com/mumble-voip/mumble/pull/2371 is semi-important.

I believe it's blocked on me fixing issues as pointed out by @hacst. Any other issues people see with it?

**Comment by mkrautz** [comment]
@Kissaki 

It should work if you simply add it to the default blacklist.

Make sure it shows up in Mumble's blacklist in the client. The default entries are non-removable and are in a "disabled" state in the list.

If it shows up correctly there, then I suggest you investigate using Process Explorer.

Open Process Explorer.
Open Mumble.
Open the Radeon Settings program. Ensure the overlay is shown.

To find potential processes that could be doing the drawing,  switch to Process Explorer.
Type Ctrl-F to bring up its Handle/DLL search feature.
Type "mumble_ol". (Without the quotes!)
You'll be presented with a list of all processes with the overlay injected into them.

You might be able to figure out which process it is by looking at that list?

**Comment by mkrautz** [comment]
Also happens in Remote Desktop Connection (mstsc.exe)

**Comment by mkrautz** [comment]
On Windows 10:

sihost.exe
ApplicationFrameHost.exe

**Comment by mkrautz** [comment]
iCloudServices.exe

**Comment by mkrautz** [comment]
BethesdaNetLauncher.exe

**Comment by Kissaki** [comment]
`BITRAY2.exe` (launched from Steam) fails to draw with Mumble Overlay enabled.

**Comment by Kissaki** [comment]
`TrueOrFalse.exe` same. Seems to be an issue with a specific configuration/version of the Unity engine. Other games work fine.

**Comment by Nuc1eoN** [comment]
To fix issue #2738 add: C:\Windows\System32\dllhost.exe
Some info about this file:
https://www.groovypost.com/reviews/dllhost-windows-process-explained/

**Comment by Nuc1eoN** [comment]
Btw blacklisting RadeonSettings.exe doesn't work for me either :/
![mumbleradeon](https://cloud.githubusercontent.com/assets/2538022/22046409/b87be654-dd20-11e6-84de-23a054efb3d9.PNG)
