### ISSUE TITLE
detect loudest/correct mic when skipping wizard

### ISSUE THREAD

**Issue by magicrub** [mumble-voip/mumble#2427]
I'm often in a mumble server where new users join for the first time (fresh install) and they _always_ have audio issues (and can't figure out PTT, but thats another issue). Is there a way that if they start using the app, but don't run the wizard, that it can try to make a guess at which audio source to use? Loudest seems like an easy check. If the data is zero-ish then don't use that one.

**Comment by Kissaki** [comment]
I don’t think we should overwrite the system default mic choice by guessing about a loudest mic.

We could on skipped wizard check and make a yes/no suggestion. But the system default mic is probably a default mic for a reason (or at least intended as such).

**Comment by hacst** [comment]
Definitely against this heuristic. That would just pick whichever mic is currently the noisiest (e.g. on my Laptop the background noise on the built-in mic is pretty obnoxious. My attached headset is much quieter). That will mostly stay true even if you tell the user to speak (especially as loudness is a freely configurable device setting).

While one can think up more robust heuristics to try to overcome that the notion of a "default system device" (and on windows even a specific communication input device)  is provided by the OS to remove such guesswork. Imho we should keep using it.

That being said the wizard could definitely be smarter and more user friendly....

**Comment by Krzmbrzl** [comment]
I don't think this is a good idea either. If someone actively avoids the audio wizard (after all it pops up on first start), then it's their problem :man_shrugging:
