### ISSUE TITLE
Typos in new ManualPlugin code

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2433]
Muble: https://github.com/mumble-voip/mumble/blob/6e2f710221d3ea56d43fc5a72775148fb8600b29/src/mumble/ManualPlugin.cpp#L283

MMUBLE: https://github.com/mumble-voip/mumble/blob/6e2f710221d3ea56d43fc5a72775148fb8600b29/plugins/mumble_plugin.h#L21

**Comment by davidebeatrici** [comment]
The second typo has been fixed in d818a8d3623605bb2251e823c24a62cfd9e6615b, the first is still there.

**Comment by davidebeatrici** [comment]
Fixed by #3272.
