### ISSUE TITLE
MumbleTheme: bottom of Audio Wizard is white on Windows 10

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2436]
![image](https://cloud.githubusercontent.com/assets/36527/16902779/f295b3c2-4c68-11e6-9bc2-fa4c84129cfa.png)

**Comment by Kissaki** [comment]
It’s white for me bottom /and/ top. I guess white is my theme color then?

**Comment by mkrautz** [comment]
Yep

**Comment by mkrautz** [comment]
Tried setting the QWizard to use Classic style.

Result:

![image](https://cloud.githubusercontent.com/assets/36527/16928753/a4911046-4d34-11e6-9820-b4180f13f543.png)

**Comment by mkrautz** [comment]
![image](https://cloud.githubusercontent.com/assets/36527/16928772/c164390a-4d34-11e6-854e-9da5410e74fc.png)

**Comment by mkrautz** [comment]
![image](https://cloud.githubusercontent.com/assets/36527/16928781/cb7dacfa-4d34-11e6-8caa-a2a27f33789a.png)

**Comment by mkrautz** [comment]
I think it looks better that way.

Will send a PR.

**Comment by Kissaki** [comment]
Alright. Looks like a reasonable fix.
