### ISSUE TITLE
Feature request: "Audio cue" volume slider

### ISSUE THREAD

**Issue by ibex-are-goats** [mumble-voip/mumble#2452]
Context: I turned on "Audio cue", but the sound is too loud for me. It hurts my ears! And I don't know how to adjust it :(

Feature: A volume knob for "Audio cue" in the Audio Input settings. :)

**Comment by Tarun80** [comment]
I'm for this. I used to use Audacity to lower the overall volume of the audio cue.

**Comment by trustable-code** [comment]
Do you mean the notification sounds?

**Comment by ibex-are-goats** [comment]
@trustable-code in the settings the feature is named "audio cue", and it is the sound that plays when you press or release the "press to talk" button. So it "notifies" you when transmission begins and ends :)

**Comment by hacst** [comment]
If it's a common problem that it's to loud we could just lower the volume of what we ship. I think we should be able to find something between "blows you ears" and "too easy to miss" without having to offer full customizability.

**Comment by Bigcheese** [comment]
Any update on this?  The sound is physically painful.

**Comment by Krzmbrzl** [comment]
Closing this one in favor of the more general #3963.
