### ISSUE TITLE
Manual placement plugin: "Unhinge" button is disabled

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#2456]
![manual_placement_plugin](https://cloud.githubusercontent.com/assets/5897523/16949864/6cb3298c-4dbd-11e6-9da2-833fda1e2f69.PNG)

**Comment by mkrautz** [comment]
It was disabled when using Qt 5 when the plugin wasn't built in. Someone should check whether disabling the QT_VERSION if's in ManualPlugin.cpp makes it work correctly now.

**Comment by davidebeatrici** [comment]
Tested, works flawlessly :wink:
