### ISSUE TITLE
Detect the current audio status and apply the corresponding status

### ISSUE THREAD

**Issue by Zilor** [mumble-voip/mumble#2458]
I tought it might be neat addition for Mumble to pull the current speaker/microphone status (mute/active) from the system/OS and then apply the correspondig status automatically onto the client.

**Comment by Kissaki** [comment]
Which client status are you talking about?

**Comment by mkrautz** [comment]
I believe the issue refers to auto-deafening, if the system's audio device is muted. Perhaps the same for the mic.

**Comment by Zilor** [comment]
@mkrautz Exactly!

**Comment by Krzmbrzl** [comment]
The problem with this would probably be that the user then tries to unmute themselves inside Mumble which hasn't control over system wide settings (I think) and thus can't actually unmute the mic. This could lead to frustration as users will think it's Mumble's fault...

How would you address that problem?
