### ISSUE TITLE
"Reset to 0 dB" button in local volume adjustment menu

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#2461]
The current "Reset" button sets the volume to the value when the dialog was entered.

It would be nice if there was a button to reset to normal volume (0 dB) as well.

**Comment by mkrautz** [comment]
Seems to me like that's what the reset button should do.

If you want to go back to the original value, you just close the dialog (or click "Cancel") and re-open it.

**Comment by mkrautz** [comment]
Fixed by @while-loop in PR #2518. Thanks!
