### ISSUE TITLE
Mumble disables side mouse buttons

### ISSUE THREAD

**Issue by Koan12** [mumble-voip/mumble#2464]
So I just bought a new Razer Naga Chroma, this is the mouse that has buttons 1-12 on the side of it. Whenever mumble is running, those buttons are completely disabled. As soon as I close mumble, those buttons work immediately. 

I've tried it with Razer Synapse running and not running as I saw that was an issue in the past. I have tried the stable version of mumble and the development version(1.2.16 and 1.3 respectfully) and still the problem. Mumble doesn't need to be connected to a server, just running.  I've tried completely uninstalling it and reinstalling, making sure to delete any config files and reg keys left behind. 

Wasn't disabling my side buttons on a previous mouse, but that only had the standard buttons. 

Any ideas on a solution? 

OS: Windows 10
Mumble version: 1.2.16 and 1.3
Latest version of Naga drivers as well.

**Comment by mkrautz** [comment]
Does it help if you disable Mumble's winhooks backend?

You can disable it with https://mumble.info/reg/disable-winhooks.reg
Re-enable with https://mumble.info/reg/enable-winhooks.reg
(You need to restart Mumble for this to have any effect...)

**Comment by mkrautz** [comment]
It could also be Mumble's use of Windows UI Automation to get global keypresses.

Try to copy your Mumble directory from `C:\Program Files\Mumble` or `C:\Program Files (x86)\Mumble` to your desktop.

Then try running Mumble from there.  Does it change the behavior of the mouse buttons?

**Comment by Koan12** [comment]
@mkrautz Thanks for the response.

So I tried the reg key above and no change. 

I tried moving the install earlier after reading the steam controller thread and that didn't help either. I just tried again to be sure. 

I did notice this however, the side buttons on the mouse default to the keys on the keyboard on a 1 for 1, so mouse 1 = 1 on the keyboard(not numpad) and mouse button 10 = 0, 11 = - and 12 = '='. That might be to much info but if I click 1 on the mouse it should enter 1 on any input field(like notepad.) If I spammed the 1 key on the mouse while mumble was running but with notepad in the forefront, switch to mumble and immediately exited out a 1 (just 1 number no matter how much I spammed it) would pop up in the notepad or whatever field I was spamming. This would happen with both the regkey enabled an disabled and in either install location.

**Comment by mkrautz** [comment]
Ah, OK. I just took a look at the Naga Chroma, and now I understand the issue a little better. :-)

Just to be clear:

If you disable winhooks and run Mumble from your desktop -- this still happens?
That is, you're unable to use your Naga Chroma's 1-10 keys to type "1", "2", ... "=", "-", etc. in Notepad?
That would be very surprising, because Mumble shouldn't be able to affect other programs when running in this mode. Mumble is *only* querying the mouse and keyboard for button presses via DirectInput, like a game would.

Could I perhaps get you to post the output of a Mumble log when you run Mumble 1.3.x with the Naga Chroma plugged in?

Just start Mumble, wait until it has launched.
Then close it.
Open %APPDATA%\Mumble\Console.txt, and copy/paste the lines corresponding to your session (you should be able to determine that via the timestamp), and upload it as a Gist (gist.github.com), or pastebin it somewhere. Feel free to remove any lines that contain personal information, if any.

Other than that, I'll have to think about this for a bit. It's getting late here...

**Comment by Koan12** [comment]
Hey @mkrautz sorry if the last bit was rambling I just woke up from a nap! Late afternoon here :)

Yes, with the winhooks disabled, I was unable to get the side keys(razer calls it a thumbgrid) to work within any application. 

Really appreciate you taking the time to troubleshoot with me =)

I cleared out console.txt, ran mumble and closed it so this should be everything from that session:

<W>2016-07-23 19:22:53.718 DirectSound: Disabled as WASAPI is available
<W>2016-07-23 19:22:53.718 ASIO: No valid devices found, disabling
<W>2016-07-23 19:22:53.728 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<W>2016-07-23 19:22:53.730 CELT bitstream 8000000b from C:/Program Files (x86)/Mumble/Versions/1.3.0~1492~g2f88605~snapshot/celt0.0.7.0.dll
<W>2016-07-23 19:22:53.731 CELT bitstream 80000010 from C:/Program Files (x86)/Mumble/Versions/1.3.0~1492~g2f88605~snapshot/celt0.0.11.0.dll
<W>2016-07-23 19:22:53.732 Theme: "Mumble"
<W>2016-07-23 19:22:53.732 Style: "Dark"
<W>2016-07-23 19:22:53.732 --> qss: ":builtin/themes/Mumble/Dark.qss"
<W>2016-07-23 19:22:53.732 Locale is "en_US" (System: "en_US")
<W>2016-07-23 19:22:53.785 Database SQLite: "3.9.2"
<W>2016-07-23 19:22:53.785 Bonjour: Failed to load dnssd.dll
<W>2016-07-23 19:22:53.785 Overlay: Listening on "\\\\.\\pipe\\MumbleOverlayPipe"
<W>2016-07-23 19:22:53.790 OverlayPrivateWin: overlay helper process 'C:\Program Files (x86)\Mumble\Versions\1.3.0~1492~g2f88605~snapshot/mumble_ol_helper.exe' started with PID 7080.
<W>2016-07-23 19:22:53.791 OverlayPrivateWin: overlay helper process 'C:\Program Files (x86)\Mumble\Versions\1.3.0~1492~g2f88605~snapshot/mumble_ol_helper_x64.exe' started with PID 3628.
<W>2016-07-23 19:22:53.793 Updating application palette
<W>2016-07-23 19:22:53.845 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2016-07-23 19:22:53.882 GlobalShortcutWin: GKeys initialized, isValid: 0
<W>2016-07-23 19:22:53.883 XboxInput: using XInput DLL 'XInput1_4.dll'
<W>2016-07-23 19:22:53.883 XboxInput: using XInputGetStateEx() as querying function.
<W>2016-07-23 19:22:53.883 GlobalShortcutWin: XboxInput initialized, isValid: 1
<W>2016-07-23 19:22:53.895 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2016-07-23 19:22:53.898 WASAPIInput: Latencies 100000 30000 => 100000
<W>2016-07-23 19:22:53.899 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2016-07-23 19:22:53.904 WASAPIInput: Mic Stream format 1
<W>2016-07-23 19:22:53.904 WASAPIInput: Stream Latency 0 (970)
<W>2016-07-23 19:22:53.906 AudioInput: Initialized mixer for 2 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2016-07-23 19:22:53.907 WASAPIOutput: Output stream format 1
<W>2016-07-23 19:22:53.907 WASAPIOutput: Stream Latency 0 (2646)
<W>2016-07-23 19:22:53.907 WASAPIOutput: Periods 10000us 3000us (latency 0us)
<W>2016-07-23 19:22:53.907 WASAPIOutput: Buffer is 60000us (5)
<W>2016-07-23 19:22:53.908 AudioOutput: Initialized 2 channel 44100 hz mixer
<W>2016-07-23 19:22:53.917 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Mouse Mouse:5 type 0x00000112
<W>2016-07-23 19:22:53.918 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Keyboard Keyboard:127 type 0x00000413
<W>2016-07-23 19:22:54.007 Adding device {b3689300-1972-11e6-800a-444553540000} ndPoint1 Inte ndPoint1 Inte:6 type 0x00010011
<W>2016-07-23 19:22:54.014 Adding device {66254f00-5047-11e6-8001-444553540000} Razer Naga Chroma Razer Naga Chroma:573 type 0x00010011
<W>2016-07-23 19:22:54.015 Adding device {66259d20-5047-11e6-8002-444553540000} Razer Naga Chroma Razer Naga Chroma:3 type 0x00010011
<W>2016-07-23 19:22:54.016 Adding device {6625c430-5047-11e6-8003-444553540000} Razer Naga Chroma Razer Naga Chroma:1 type 0x00010011
<W>2016-07-23 19:22:54.017 Adding device {6625c430-5047-11e6-8004-444553540000} Razer Naga Chroma Razer Naga Chroma:1 type 0x00010011
<W>2016-07-23 19:22:54.022 GlobalShortcutWin: excluded XInput device 'Controller (XBOX 360 For Windows)' ({b3689300-1972-11e6-8008-444553540000}) from DirectInput
<W>2016-07-23 19:22:54.026 Adding device {b3689300-1972-11e6-800b-444553540000} ndPoint1 Inte ndPoint1 Inte:3 type 0x00010011
<W>2016-07-23 19:22:54.067 Adding device {b3689300-1972-11e6-8009-444553540000} HyperX 7.1 Audio HyperX 7.1 Audio:3 type 0x00010011
<W>2016-07-23 19:22:54.138 libpng warning: iCCP: known incorrect sRGB profile
<W>2016-07-23 19:22:58.305 QObject::killTimer: Timers cannot be stopped from another thread
<W>2016-07-23 19:22:58.305 QObject::~QObject: Timers cannot be stopped from another thread
<W>2016-07-23 19:22:58.331 QProcess: Destroyed while process ("C:\\Program Files (x86)\\Mumble\\Versions\\1.3.0~1492~g2f88605~snapshot\\mumble_ol_helper.exe") is still running.
<W>2016-07-23 19:22:58.333 QProcess: Destroyed while process ("C:\\Program Files (x86)\\Mumble\\Versions\\1.3.0~1492~g2f88605~snapshot\\mumble_ol_helper_x64.exe") is still running.

**Comment by Krzmbrzl** [comment]
Does this also happen with Mumble 1.3?
