### ISSUE TITLE
JSON won't parse, "\0" in osversion value

### ISSUE THREAD

**Issue by nomad5** [mumble-voip/mumble#2469]
I run a program that checks who's in Mumble by parsing JSON provided by Typefrag. When client updates to `1.3.0~1492~g2f88605~snapshot` the osversion value turns into `Windows 10 Pro\0 x64 1511\0 10586\0.218`. I believe that "\0" stops JSON parsers.

`1.3.0~1432~gf241782~snapshot` provides `Windows 10 Professional x64 - 10.0.10586`
`1.3.0~1492~g2f88605~snapshot` provides `Windows 10 Pro\0 x64 1511\0 10586\0.218`

Full JSON - 

`{"id": 79,"name": "Server Name","root": {"description": "","id": 0,"links": [],"name": "Root","parent": -1,"users": [],"position": 0,"channels": [{"description": "","id": 1,"links": [],"name": "Ascalon City","parent": 0,"users": [],"position": 0,"channels": [],"temporary": false,"x_connecturl": ""}, {"description": "","id": 2,"links": [],"name": "Citadel","parent": 0,"users": [],"position": 0,"channels": [],"temporary": false,"x_connecturl": ""}, {"description": "","id": 3,"links": [],"name": "Underground","parent": 0,"users": [{"channel": 3,"deaf": false,"mute": false,"name": "Nomad5","selfDeaf": true,"selfMute": true,"session": 1,"suppress": false,"userid": 2,"address": [0],"x_addrstring": "ip","recording": false,"bytespersec": 0,"comment": "","context": "System.Runtime.Serialization.StreamingContext","identity": "","idlesecs": 580,"onlinesecs": 581,"os": "WinX64","osversion": "Windows 10 Pro\0 x64 1511\0 10586\0.218","prioritySpeaker": false,"release": "1.3.0~1492~g2f88605~snapshot","tcponly": false,"x_texture": "","version": 66304}],"position": 0,"channels": [],"temporary": false,"x_connecturl": ""}],"temporary": false,"x_connecturl": ""},"x_connecturl": "","x_uptime": 2876149}`

**Comment by davidebeatrici** [comment]
@mkrautz Perhaps it is related to https://github.com/mumble-voip/mumble/pull/2447?

**Comment by mkrautz** [comment]
Thanks! This was an oversight.
