### ISSUE TITLE
Null characters in OS string

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#2473]
While it displays fine, trying to copy paste this information cuts out due to the null characters.

On Windows 10:
![OS String](https://i.imgur.com/SNBOEBq.png)

Seen from Arch Linux:
![OS String](https://i.imgur.com/Y7tkmex.png)

As you can see, the rectangle dotted line shapes are where the null characters are.

**Comment by mkrautz** [comment]
Duplicate of https://github.com/mumble-voip/mumble/issues/2473.

**Comment by Tarun80** [comment]
This is a duplicate of my own issue?

**Comment by mkrautz** [comment]
That too :-)

But mostly a duplicate of mumble-voip/mumble#2469.

Sorry!
