### ISSUE TITLE
Ban reason has overlapping text in content menu

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#2474]
Noticed this earlier when I went to edit a ban reason.

![Content menu for ban reason](https://i.imgur.com/ZZ6hDDC.png)

Client and Server are both 1494. Happens on both Windows and Linux.

**Comment by synapse84** [comment]
This is caused by the `Qt::RightToLeft` property being applied to `qleReason` in https://github.com/mumble-voip/mumble/blob/2f886052e4232905ea3c2cb5c027cac8a3ba72c2/src/mumble/BanEditor.ui#L155

**Comment by mkrautz** [comment]
Fixed by the merge of PR #2475.
