### ISSUE TITLE
ChatbarTextEdit should subclass RichTextEdit

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2476]
That way, one would be able to paste images in the chat bar.

I tried to subclass RichTextEdit and it mostly worked, but some of the internal of ChabarTextEdit expects its content to be plain text -- so sending the actual message doesn't work.

Someone should look into what it'd take to refactor ChatbarTextEdit to support HTML messages like this.

**Comment by Krzmbrzl** [comment]
Implemented via #4265
