### ISSUE TITLE
Make the History inaccessible

### ISSUE THREAD

**Issue by SuperNascher** [mumble-voip/mumble#2477]
It is possible to “kill” the Chat history, if somebody posts an image with a very big width and height value. The user can not see the chat log anymore. Here an example:

`<img src="https://wiki.mumble.info/logo.png" height="50000000000" width="50000000000" />`

The only way to see the history, is to copy the content of the history and see it in HTML source code. To make the chat log usable again, the user can right click on the chat log and choose ”Clear” to remove the large image.

It even affects the users, that have enabled the “Disable image download” checkbox in Mumble. It affects Mumble 1.2.16 and the Snapshot version.

![Screenshot](https://cloud.githubusercontent.com/assets/655858/17276342/0aa3fd70-5727-11e6-8405-db5ef9303baa.png)

**Comment by Natenom** [comment]
![mumble_history_killer](https://cloud.githubusercontent.com/assets/385995/17276360/9dbf7044-5727-11e6-9b77-7174664c009f.png)

**Comment by mkrautz** [comment]
Hmmm. Odd.

If I insert a reasonable-but-big image, i.e. `<img src="https://wiki.mumble.info/logo.png" height="65535" width="65535" />` Mumble shows the HTML, like I expect.

I wonder what's going wrong.

**Comment by mkrautz** [comment]
Interesting! I tried to use 2**10-1, 1048575.
This turned into the following source HTML,
after being shown in the log as HTML:

`<img src="https://wiki.mumble.info/logo.png" width="1.04858e+06" height="1.04858e+06"/>`

**Comment by mkrautz** [comment]
Note that the width and height are floats.
