### ISSUE TITLE
Jack Audio Support

### ISSUE THREAD

**Issue by Reaper10** [mumble-voip/mumble#2479]
Mumble could use Jack Audio Support for connecting to a Jack Audio Support daw for recording on Esprit tracks.

http://jackaudio.org/
https://github.com/jackaudio

**Comment by Natenom** [comment]
Code is already there ... https://github.com/mkrautz/mumble/commit/16c8ff512c2e7b4e1d32410d8bd576d1a5c5dfba

(based on?) https://sourceforge.net/p/mumble/patches/324/.

**Comment by mkrautz** [comment]
@Natenom Well, it's not fully ready to merge yet. But yeah, it's there in an early state.

**Comment by Natenom** [comment]
There it is: https://github.com/mumble-voip/mumble/pull/137

**Comment by Reaper10** [comment]
what about connecting isdn and sound strike and ipdtl and audio tx source-connect for those who do voice over for a living

**Comment by Reaper10** [comment]
what about connecting isdn and sound strike and ipdtl and audio tx source-connect for those who do voice over for a living

**Comment by ranomier** [comment]
+1

**Comment by davidebeatrici** [comment]
Support added via #3396.
