### ISSUE TITLE
[Q] Is somebody even aware Windows has a shim for mumble?

### ISSUE THREAD

**Issue by mirh** [mumble-voip/mumble#2487]
![mumble](https://cloud.githubusercontent.com/assets/9366725/17421977/34e82b94-5aae-11e6-8fd0-c65b21c5fbde.PNG)

What's the point?

**Comment by mkrautz** [comment]
Interesting... No, I don't think anyone was aware.

**Comment by mkrautz** [comment]
My guess is that a lot of people are stuck on 1.2.3 for whatever reason, and because that version is quite old, they had to force it to run in Win7 compatibility mode on Windows 8/8.1/10.

**Comment by mirh** [comment]
Mhh, nope. 
That's *Win7RTMVersionLie*, which is not the same of *Win7RTM compatibility mode* (that includes the former plus another 18-19 shims). 
This is only about telling mumble "Hey, you are under 7", stop. 

Which totally doesn't make sense considering I'm not expecting Mumble to be a shitty application programmed in the first 2000.

**Comment by mirh** [comment]
I wonder if it *mightn't* have something to do with the [manifest](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191.aspx#supportedOS) mumble has?

For some reason, even latest 1.2.16 release is using a very [old one](https://github.com/mumble-voip/mumble/blob/ab940f1948aa5d5b4efc723e48c3ff7827c7c947/src/mumble/mumble.appcompat.manifest).

**Comment by davidebeatrici** [comment]
This should already be fixed in the master branch: https://github.com/mumble-voip/mumble/blob/master/src/mumble/mumble.appcompat.manifest

**Comment by mirh** [comment]
Actually.. That was already a thing 2 years before I posted this (wtf did I do?)
Gg then?

**Comment by mkrautz** [comment]
@mirh I believe the problem is that 1.2.x doesn't have an updated manifest.

**Comment by mirh** [comment]
I believe that never was an *actual* problem to begin with (and anyway, only < 1.2.9 didn't have it, according to commit dates). I mean, I don't see which code of yours would simply fail/change if version is 7 instead of 8. 

The most simple explanation I have atm, is some dumb microsoft engineer scanning his computer for "stuff I could potentially shim" and calling it a day.

**Comment by mkrautz** [comment]
Quite possibly... :-)
