### ISSUE TITLE
Mumble should set a specific -std=c++XX instead of relying on the compiler default

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2494]
See also:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831184

**Comment by mkrautz** [comment]
Needs a 1.2.17 backport as well.

**Comment by davidebeatrici** [comment]
In [MumblePAHelper](https://github.com/mumble-voip/mumble-pahelper/blob/master/MumblePAHelper.pro) I added `CONFIG += c++11` in the project file.

**Comment by hacst** [comment]
So uh. Can we actually do ```c++11``` for 1.3 now? I mean it has been quite a few years so maybe Linux isn't holding us back from that anymore. I think last time I checked we should be ok to do so on paper but I'm not sure if those compiler versions _actually_ support C++11 in a non-broken way. I remember the first gcc versions saying they have "full support" shipping with quite broken library implementations....

**Comment by hacst** [comment]
I guess this would be resolved with #2582 ?

**Comment by mkrautz** [comment]
Yes
