### ISSUE TITLE
[Feature Request] Paste and Send from Clipboard Shortcut

### ISSUE THREAD

**Issue by gyvess** [mumble-voip/mumble#2501]
**Problem**:  Mumble chat is frequently used to exchange hyperlinks.  If there is something I want to share that often entails bringing the Mumble window into focus, right clicking the message box, and pressing the 'S' key to paste and send the copied URL  Cumbersome for something much used.

**Solution**:  Add "Paste and Send" to the function dropdown within the Shortcut menu of Mumble Configuration.  "Paste and Send" would allow users to set a global hotkey of their choosing which posts text from their clipboard directly into Mumble chat, greatly reducing the steps need to do so now.

**Comment by mkrautz** [comment]
Seems like a neat idea!

**Comment by Tarun80** [comment]
Why is this even needed? Paste and Send already exists in the context menu for the chat log, and Ctrl+V and Enter works very well. Plus it gives them the option to backpedal if it was data they did not want to send (ie where Ctrl+C did not copy the data properly) becomes visible.

A problem is that people could hit this "global hotkey" and paste things that they did not want to send. Accidental keypresses and poor hotkey choices. I've seen people copy usernames, passwords/passphrases, account numbers, remote desktops tend to copy/share clipboard data, and many other things. This could elevate a security risk and no one really wants that.

At least with the context menu option (which already exists) they have to consciously make the choice of sending their clipboard data.

**Comment by gyvess** [comment]
The hotkey is needed because the steps for something oft used causes an annoyance.

The global hotkey would have to be set by every user individually, just as every shortcut within the menu is set within the program.  It wouldn't be activated otherwise.  In addition, the shortcut can be set to any three key combination of your choice allowing users to select a shortcut they're less likely to press by accident.  Alternatively, they can adopt a habit of never putting sensitive information within the clipboard.

Users could continue to use the methods that currently exist to send text, regardless of whether this new feature is added for those who'd like to utilize it.

**Comment by while-loop** [comment]
@gyvess Is the request asking to send the clipboard contents to the mumble chat when the Mumble UI is not in the foreground?

**Comment by gyvess** [comment]
Yes, that way while you're talking about something you've seen you can immediately put it in chat rather than have the delay that comes with how things are shared now.
