### ISSUE TITLE
Switch to MSVC 2015 compiler

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#2502]
I think that we should switch to `MSVC 2015` as soon as possible.
The main problem about `MSVC 2013` is that you're obliged to install Visual Studio 2013 if you want to use it. The [Microsoft Build Tools 2013](https://www.microsoft.com/it-it/download/details.aspx?id=40760) aren't working, perhaps they actually don't include the C++ compiler?
This is a problem especially for who wants to create a new positional audio plugin using Qt Creator, because he needs to install another (heavy) IDE just to have the compiler.
The [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) include `MSVC 2015` and it works fine with Qt Creator.

PTAL @mkrautz @hacst @fwaggle @Kissaki @Natenom

**Comment by mkrautz** [comment]
1.3.0 has stabilized on MSVC 2013.

So you'll need MSVC 2013 to target that.

1.4.0 will update to MSVC 2015.

If you want to help along, you can try to fix some of the 1.3.0 milestoned issues. That should get us to 1.4.0 quicker!

Alternatives:

 - JS-based plugins (https://github.com/mumble-voip/mumble/issues/1322)
 - Plugins that only use the C ABI. We wouldn't be tied to a particular MSVC version.
