### ISSUE TITLE
Mumble log scrolls to top instead of bottom on some Qt versions (4.8, 5.2, maybe more?)

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2504]
From IRC:

```
22:27:27 <jemu> hiho, it seems that since some newer snapshot versions of mumble the chat scrolls to the top (as opposed to the bottom) when an image is posted. is this a known problem? is it maybe related to some older qt5 versions?
22:29:03 <@mkrautz> jemu: where are you seeing it?
22:29:57 <jemu> mkrautz: two people have reported this to me, one is one ubuntu trusty + snapshot ppa the other on windows 7 + official snapshot build
22:30:46 <jemu> mkrautz: sorry, i confused something, both are linux (one is ubutnu trusty + snapshot ppa, the other is a debian system)
22:31:03 <jemu> it works perfectly fine on my system (gentoo + manually build)
22:33:01 <jemu> i couldn't find a bug report, only some older ones with the opposite issue (not scrolling at all)
22:33:02 <@mkrautz> is the debian system using debian's own package?
22:33:13 <@mkrautz> if so, that would probably have the bug
22:33:29 <jemu> the debian user has done a custom build from git master
22:33:57 <jemu> the ubuntu user has: 1.3.0 (1.3.0~1326~gf4ca0cf~snapshot-1~ppa1~trusty1)
22:34:40 <@mkrautz> OK
22:34:48 <@mkrautz> seems like it's possibly an issue with older versions of Qt then, hmm...
22:34:58 <@mkrautz> jemu: that's pretty old
22:35:36 <@mkrautz> (not that anything should have changed in that regard, but ... it's still a bit oldold)
22:35:41 <@mkrautz> eh, old* :)
22:35:58 <@mkrautz> OK, trust has Qt 5.2
22:36:05 <@mkrautz> and the Debian user is... maybe on Qt 4?
22:37:14 <jemu> mkrautz: yes, the debian user is still on Qt 4
22:37:41 <@mkrautz> OK, I would expect the Qt 4 to be broken in that regard, actually :(
22:37:50 <@mkrautz> the Qt 4 version*
22:38:04 <@mkrautz> I seem to be missing a lot of words today :)
22:38:07 <jemu> good (or bad, depends on context), what about Qt 5.2?
22:38:27 <@mkrautz> jemu: I have no idea about that :(
22:41:21 <jemu> mkrautz: we have updated to 1508 on the ubuntu system, issue persists
22:41:38 <jemu> so maybe we should update from trusty to xenial?
22:41:54 <@mkrautz> jemu: well, it's a bug I'd like to fix... so :)
22:42:15 <jemu> ok, something we can do to help?
22:42:56 <@mkrautz> jemu: if the debian user could try to build 1.2.16 w/ qt 4 and check if that works, that would help :)
```

**Comment by mkrautz** [comment]
For Qt 4, we should probably forward-port

192ba96fddda2895a0fb0d143540eb2022bb07be
1a4ae8deddc9c833ee276cbbb08bd19940e2840c

to master from 1.2.x.

**Comment by promi** [comment]
That is kind of curious as there don't seem to be any changes to the chat between those commits:

https://github.com/mumble-voip/mumble/compare/e7ff17b...2aec53d

**Comment by mkrautz** [comment]
That's correct. No changes that I'd expect to affect this.

**Comment by promi** [comment]
The error is back for the trusty user (still version 1533), so the problem was not fixed between e7ff17b...2aec53d.

It also doesn't always happen as we first thought.

**Comment by promi** [comment]
The error is now also present on my system (Gentoo Linux), a user with Debian GNU/Linux and a third user with ArchLinux.

Its also present in the current Git version.

When I restart Mumble it works for a while, but after some time it starts to scroll to the top or near the top instead of the bottom where it should.

**Comment by promi** [comment]
I don't think the Qt version matters, but for completeness, my system has Qt 5.11.3-r2.

The ArchLinux system has 5.12.

**Comment by promi** [comment]
I have done some testing and debugging on this.

After starting Mumble everything is fine, up until a point where about 5000 lines are in the log widget. The scroll mechanism then scrolls more towards to the middle than towards the bottom. Clearing the log doesn't help either.

The log widget (LogTextBrowser) is a class derived from QTextBrowser in CustomElements.h.

When a new log message is written to the log widget the `scrollLogToBottom` method is called. There is some extra code in Log.cpp that detects whether the scroll position was already at the bottom, but that works as expected.

All that the `scrollLogToBottom` (in CustomElements.cpp) does is essentially this:

    verticalScrollBar()->setValue(verticalScrollBar()->maximum());

This should work just fine and it does initially, but stops working after a while (see above).

As far as I can see this is an upstream bug in Qt. I can't find an upstream bug report though. The thing is I haven't written a Qt application before, so I can't easilly create a test application.

Maybe someone would like to supply a test application? I currently don't have enough free time, but may get back to this later.

**Comment by davidebeatrici** [comment]
Thank you very much for investigating the issue!

I can write a test application, no problem.

**Comment by Krzmbrzl** [comment]
@davidebeatrici (or anyone else) do you know whether this bug has been reported in the meantime?

In the meatime I'll close this issue as apparently there's nothing we can do on our side to fix this (besides some dirty workarounds maybe but I'd vote against that)...

**Comment by promi** [comment]
I have created an upstream bug request here:

https://bugreports.qt.io/browse/QTBUG-83622

**Comment by Krzmbrzl** [comment]
@promi Thank you :)

**Comment by promi** [comment]
I have a bit more information on this:

When the bug occurs you can resize the chat edit by pressing Shift + Enter (entering a newline) and the log then scrolls to the bottom again. When a new chat message is received it stops working again. You can repeat this by adding / removing new lines so that the chat edit resizes.

I suspect that the problem has something to do with the layout as well as the QTextBrowser.

**Comment by philippbaumm** [comment]
just ran into this issue in my work related project(pyqt6 tho):
https://www.qtcentre.org/threads/32852-How-can-I-always-keep-the-scroll-bar-at-the-bottom-of-a-QScrollArea

connecting the rangeChanged signal worked for me!

**Comment by Irets** [comment]
Is there a way to hack the fix into QT somehow (if so, what needs to be changed?) or do we have to wait for QT to fix this?

**Comment by Krzmbrzl** [comment]
Well - it will certainly not be fixed in Qt5 anymore. Maybe it's fixed in Qt6, but we'll only see once we port Mumble to it.
Other than that, Qt is open source, so technically you Courland contribute a bug fix to Qt yourself instead of waiting on them to fix it on their own :eyes:

**Comment by Irets** [comment]
I could look into it but I don't have very high hopes.
How far are we from Mumble on QT6?

**Comment by Krzmbrzl** [comment]
> How far are we from Mumble on QT6?

Before we can start to work on that, we'll have to get Mumble to compile with C++17. Then we can start porting.
We have not yet (really) started with this though.
