### ISSUE TITLE
Mumble 1.3.0 1533 Deafen icon stuck activated

### ISSUE THREAD

**Issue by robozman** [mumble-voip/mumble#2516]
I've noticed that sometimes the deafen icon gets stuck in the activated states. Audio input and output are unaffected.  Upon clicking the button the chat log responds as if I am toggling the mute button on and off, outputting Muted and Unmuted.  If the issue occurs again I'll attempt to get screenshots / recordings. 
Client version is 1.3.0 (1.3.0~1533~g2aec53d~snapshot) on Windows 10 Version 10.0.14393 Build 14393 x86_64.  Server version is Murmur 1.2.12-1ubuntu1 on Ubuntu 16.04.1.

**Comment by Krzmbrzl** [comment]
I don't experience this with the current version on Linux (and I didn't notice it on Windows yet either). Do you still have this problem?
