### ISSUE TITLE
Broken Qt theme with Mumble 1.3

### ISSUE THREAD

**Issue by haasn** [mumble-voip/mumble#2520]
With mumble 1.3 I can no longer choose from my system-wide qt5 themes like I could with mumble 1.2.x and qt4.

Would it be possible to let me use my normal, system-wide qt5 theme like every other qt5 program?

**Comment by mkrautz** [comment]
Configure -> Settings -> User Interface -> Look and Feel -> Theme. Pick "None". This will use your system's default Qt theme.

Or are you looking for the built-in Qt 5 themes instead?

**Comment by haasn** [comment]
Let me explain with a screenshot of the problem.

This is what it looks like in mumble 1.2:
![mumble 1.2 (qt4)](https://0x0.st/MmV.png)

This is what it looks like in mumble 1.3, even with ‘none’:
![mumble 1.3 (qt5)](https://0x0.st/MmW.png)

If I build mumble 1.3 with qt4 instead of qt5, it works fine again. (Except for the part where the window still consistently disappears all the time, but that seems to be a separate issue)

This is a mumble-specific problem because other Qt5 programs work fine: (Shown here is the hawaii widget factory)
![widget factory](https://0x0.st/MmJ.png)

**Comment by Krzmbrzl** [comment]
I guess the problem persists in the released version of Mumble 1.3?
