### ISSUE TITLE
text screwed up (Zalgo, Unicode glitch text)

### ISSUE THREAD

**Issue by DGMurdockIII** [mumble-voip/mumble#2530]
can we get tthis text removed from mumble so it not supported as u see what it dose in picture    t ด็็็็็้้้็็็้็็็้็็็้็็็้็็็็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้ด็็็็็้้้็็็้็็็้็็็้็็็้็็็็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้็็็้ 

http://i.imgur.com/6TQqrR9.png

Im using lastest snapshot version on windows

**Comment by hacst** [comment]
That's so called Zalgo code. Dealing with that is harder than it one might think (as seen in your comment github thinks so too ;) ). http://stackoverflow.com/a/22280018 has some suggestions. For channel and user names you could apply a custom regex to prevent it on channel names.

**Comment by DGMurdockIII** [comment]
cant see the channel name now http://i.imgur.com/I4s5jVJ.png

**Comment by Lartza** [comment]
You can't use those characters without modifying the default restrictions, the admin has deliberately enabled them. There is nothing to fix except finding a proper server.

**Comment by mkrautz** [comment]
Related to https://github.com/mumble-voip/mumble/issues/2462 (for users and channels)

**Comment by Kissaki** [comment]
@DGMurdockIII as hacst suggested, you can prevent this for usernames and channelnames with the server-side allowed [user/server]name. You can only allow alphanumerics for example.
See https://wiki.mumble.info/wiki/Murmur.ini#channelname_and_username

Our defaults should already deny these. Did you change them?

**Comment by DGMurdockIII** [comment]
Any plans for this yet

**Comment by Krzmbrzl** [comment]
As this can be disabled via server-settings and stackoverflow basically agrees that you can't prevent this with a clean solution, I'll close this issue
