### ISSUE TITLE
[idea] Disguised One Time Quick Link

### ISSUE THREAD

**Issue by ksthiele** [mumble-voip/mumble#2543]
It's more of a service, basically a quick link like "mumble://TestUser:mypassword@server.com/?version=1.2.0" but disguised and therefore save for streamers.
1. A User wants to invite a friend
2. He generates a unique short url from the GUI and the Server he is on currently on, which could look like "https://www.mumble.com/invite/098f6bcd4621d373cade4e832627b4f6"
3. he shares the link which the friend could enter in Mumble or browser (browser could leak the server info)
4. the friend uses the link to connect to the server and the link deletes itself immediately after usage.

Maybe it could be better, but I think it'd be a good step in the right direction to prevent DDoS

**Comment by ksthiele** [comment]
@bontibon I don't think it's the same, but something that could be combined.

**Comment by Tarun80** [comment]
Basically, use a short one time link like what Discord does?

**Comment by ksthiele** [comment]
are they doing this? then yes.

Mumble has to compete a little bit with discord, curse and those things. I was also thinking about a portal for a community that could control multiple Mumble hosts or something.

**Comment by Tarun80** [comment]
@ksthiele They sure do. You can read about it [here](https://support.discordapp.com/hc/en-us/articles/204155938-How-do-I-invite-friends-to-my-server-).
