### ISSUE TITLE
EC key support

### ISSUE THREAD

**Issue by tycho** [mumble-voip/mumble#2544]
Right now Murmur doesn't understand EC private keys.

I applied and tested this on my Murmur daemon using an EC key and cert provided by the Let's Encrypt CA:

``` diff
diff --git a/src/murmur/Meta.cpp b/src/murmur/Meta.cpp
index d646faf..57a32af 100644
--- a/src/murmur/Meta.cpp
+++ b/src/murmur/Meta.cpp
@@ -407,11 +407,15 @@ void MetaParams::read(QString fname) {
            qskKey = QSslKey(key, QSsl::Rsa, QSsl::Pem, QSsl::PrivateKey, qbaPassPhrase);
            if (qskKey.isNull())
                qskKey = QSslKey(key, QSsl::Dsa, QSsl::Pem, QSsl::PrivateKey, qbaPassPhrase);
+           if (qskKey.isNull())
+               qskKey = QSslKey(key, QSsl::Ec, QSsl::Pem, QSsl::PrivateKey, qbaPassPhrase);
        }
        if (qskKey.isNull() && ! crt.isEmpty()) {
            qskKey = QSslKey(crt, QSsl::Rsa, QSsl::Pem, QSsl::PrivateKey, qbaPassPhrase);
            if (qskKey.isNull())
                qskKey = QSslKey(crt, QSsl::Dsa, QSsl::Pem, QSsl::PrivateKey, qbaPassPhrase);
+           if (qskKey.isNull())
+               qskKey = QSslKey(crt, QSsl::Ec, QSsl::Pem, QSsl::PrivateKey, qbaPassPhrase);
            if (! qskKey.isNull())
                qCritical("Using private key found in certificate file.");
        }
```

**Comment by L-P** [comment]
A very simple fix for an important feature, LE is progressively becoming the most popular CA.  

If this patch is accepted, will it be backported in 1.2.\*?

**Comment by tycho** [comment]
Note that this requires Qt5 as Qt4 doesn't have Qssl::Ec

**Comment by L-P** [comment]
I just noticed that LE supports RSA keys, acmetool default configuration used
ECDSA.

This makes the feature less important but I expect ECDSA to be more widespread
in the future, it's pushed by prominent actors eg. CloudFlare and Let's
Encrypt.

**Comment by mkrautz** [comment]
There are a few hurdles.

I don't know if you have time or want to work on getting this into a mergable state, @tycho?

If not, I can use this as base commit (with proper attribution) in a PR, and do some clean up commits to get it ready.

Here's a little brain dump:

1. The patch needs to be guarded with `#if QT_VERSION >= 0x050000`. We still build on Qt 4.

2. We should also check how 1.2.x clients react when encountering an EC certificate. They'll likely connect just fine, but how do they react when viewing the certificate? The certificate dialog contains the key type, size, etc. -- perhaps we weren't forward thinking enough to simply show "Unknown".

3. There are other places in Murmur that loads certificates. `Server::initializeCert()` in Cert.cpp, as well as `impl_Server_updateCertificate()` in MurmurIce.cpp. The one in MurmurIce.cpp is a little "broken" already, as it only handles RSA keys. (Not DSA, like the other places.). Perhaps we should just not support DSA at all in the other code paths...

**Comment by tycho** [comment]
@mkrautz Regarding #2, had no issues with 1.2.16 users connecting to it.

I'll look into the other two points later today.

**Comment by tycho** [comment]
Point 1 is done: https://github.com/tycho/mumble/commit/dab271df7b28b197b8e596cadf89531035d08151 I also found that there was another certificate loader in Cert.cpp for some reason.

I'm not sure what the deal is with MurmurIce. Is there a reason that it only supports RSA? There are comments around it saying that's the current state of affairs, but there's no rationale supplied with it. It also does some funny exponent comparisons instead of just using the Server::isKeyForCert function. I'm half tempted to just copy the code from Meta.cpp/Cert.cpp into there. But it does seem odd that we have this same code in three different places too, so maybe that calls for some refactoring?

**Comment by mkrautz** [comment]
@tycho said:
> @mkrautz Regarding point 2, had no issues with 1.2.16 users connecting to it.

They should be able to connect, but I am worried that the certificate viewer in Server -> Server Information is subtly broken. I haven't tested it myself.

@tycho said:
> I'm not sure what the deal is with MurmurIce. Is there a reason that it only supports RSA? There are comments around it saying that's the current state of affairs, but there's no rationale supplied with it. It also does some funny exponent comparisons instead of just using the Server::isKeyForCert function. I'm half tempted to just copy the code from Meta.cpp/Cert.cpp into there. But it does seem odd that we have this same code in three different places too, so maybe that calls for some refactoring?

The code in MurmurIce.cpp should probably be refactored to use `Server::isKeyForCert`. It might make sense to move that function (isKeyForCert) to src/SSL.cpp/h as a static function.

Also please note that the code in MurmurIce.cpp is only *verification* code. The cert, key and passphrase are only used to verify that those three mutually work together -- that the cert is valid,that  the key is valid for the cert, and that the passphrase unlocks the key, such that it is valid for cert.

It might also make sense to move some of the QSslKey loading logic into a static function in SSL.cpp/h that load keys and certs:

    /// Attempt to load a private key from |buf|. If |passphrase| is non-empty, it will
    /// be used in trying to decipher the key.
    /// If a valid RSA, DSA or EC key is found, it is returned.
    /// If no valid private key is found, a null QSslKey is returned.
    static QSslKey keyFromByteArray(const QByteArray &buf, QString passphrase);

**Comment by mkrautz** [comment]
@tycho Any progress? Or should I take over?

**Comment by tycho** [comment]
Go ahead, I've unfortunately been busy.

**Comment by Kissaki** [comment]
PR #2859 added EC key support.

Did you still want to test how 1.2 displays the certs?
Or make ice changes?
Should be separate issues then.
