### ISSUE TITLE
Switch to new icon for executable

### ISSUE THREAD

**Issue by ElPumpo** [mumble-voip/mumble#2546]
The Windows executable still uses the old Mumble logo. The new one shows up when you inspect the exe file but not when the application is loaded.

**Comment by mkrautz** [comment]
Actually, this one is the "current" logo:

![image](https://cloud.githubusercontent.com/assets/36527/18455300/6f228fd4-7949-11e6-99a7-ec83a01998bf.png)

The other logo is the logo from the new default theme. (Formerly known as MetroMumble.)
We haven't officially switched to that yet.

There is an issue tracking the refresh:
https://github.com/mumble-voip/mumble/issues/2137

Until we close that, perhaps the best course of action is to keep using the old icon...
