### ISSUE TITLE
text size on HiDPI displays

### ISSUE THREAD

**Issue by SeanMcG** [mumble-voip/mumble#2558]
Hi,

On my Surface 2 Pro, the text is illegibly small in the chat area, and in the comment screens (clicking on a [C]).

It only seems to be an issue on HiDPI displays -- and from what I have heard it is probably also Qt4 related.

**Comment by mkrautz** [comment]
Which version is this on?

Have you tried the development snapshots (1.3.x)?

The Qt 4-based 1.2.x series doesn't support HiDPI, and never will.
1.3.x is the way to go. We're stabilizing the developmenet branch, so don't be afraid to use that for your day-to-day Mumble duties.

Please report back if 1.3.x fixes the problem for you. Thanks!

**Comment by ElPumpo** [comment]
I use the 1.3.0 branch for my 1440p monitor and it works great! Best voip solution ever!

**Comment by mkrautz** [comment]
@ElPumpo But do you use Windows DPI scaling on it? That's the issue @SeanMcG had.

Our 1.3.x snapshots are built against Qt 5.6, and thus should be HiDPI compatible on Windows by default. If not, it should be simple to fix, and I'll look into it ASAP.

**Comment by ElPumpo** [comment]
@mkrautz yes my friend, I'm at 125% DPI scale.

**Comment by mkrautz** [comment]
👍

**Comment by Kissaki** [comment]
@SeanMcG Did you try 1.3?

**Comment by SeanMcG** [comment]
@Kissaki @mkrautz Sorry for the delay, yes I tried 1.3.0 and it appears to fix my issue.

Thanks for the great work!
