### ISSUE TITLE
1.3.0 Main window never appears QT5

### ISSUE THREAD

**Issue by jocelynthode** [mumble-voip/mumble#2559]
I built mumble 1.3.0 from the aur on Archlinux with KDE/Plasma. approximately 90% of the time I launch mumble through the desktop file, the main window (where you see the users and the channel) doesn't appear and thus mumble is absent from the workspace.

When launching mumble through the command line, the problem is present approximately 40% of the time.

I use the lite theme.

Kernel : Linux archfixe 4.7.4-1-ARCH
Plasma version : plasmashell 5.7.5

**Comment by mkrautz** [comment]
@jocelynthode Is the pkgbuild pinned to a particular git commit, or does it just build from the latest commit on the master branch?

https://github.com/mumble-voip/mumble/commit/99899d12decccb5670d4e6887c4f7ec7f3cf8faf was supposed to fix that.

**Comment by jocelynthode** [comment]
@mkrautz : My bad, I checked open issues and didn't see anything about it. I didn't think about checking the latests commits. The PKGBUILD isn't pinned to a particular commit so I reinstalled and it is gone !

You can close the issue ! Sorry

**Comment by mkrautz** [comment]
Great news. Thanks for confirming! :-)
