### ISSUE TITLE
Can't disable AES256-SHA cipher suite

### ISSUE THREAD

**Issue by Avamander** [mumble-voip/mumble#2561]
I'm using Mumble server 1.2.12-1ubuntu1 and client 1.3.0~1623~g0556b6c~snapshot-1~ppa1~xenial1.

I wanted to remove a few cipher suites from the default "sslCiphers=EECDH+AESGCM:EDH+aRSA+AESGCM:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA" mentioned in the wiki.

I noticed that the client is unable to connect when no AES256-SHA is not added to the list, so my question is, why can't it be removed? Is there a way I could make it use some other cipher suite (like one of the first in the list)?

**Comment by mkrautz** [comment]
1.2.x servers shipped by Linux distros use stock Qt 4, which doesn't support DHE or ECDHE cipher suites.

We have a patch for Qt 4 which adds support for them. You can use our static Linux binary to get it. It's available from https://www.mumble.info.

If you're on Ubuntu, you can also simply use the PPA for our snapshot builds: https://launchpad.net/~mumble/+archive/snapshot

For modern Ubuntu versions, we build against Qt 5, and those builds will have support for modern ciphers by default.

**Comment by mkrautz** [comment]
And I'd like to add:

1.2.x client binaries shipped by the Mumble project all support modern TLS 1.2 cipher suites.
1.3.x clients built with Qt 5 also support modern TLS 1.2 cipher suites.
