### ISSUE TITLE
Memory leak while idle, arch linux, v 1.2.17-1

### ISSUE THREAD

**Issue by nsgutierrez** [mumble-voip/mumble#2566]
Mumble was opened and left idle. Never even connected to a server. Left for work and came back to mumble using about 12 GB  memory. I don't really use mumble much or know much about it but I'm happy to answer any questions about my settings etc.

<a href="http://imgur.com/LkDmJeH"><img src="http://i.imgur.com/LkDmJeH.png" title="source: imgur.com" /></a>

**Comment by synapse84** [comment]
I've been trying to reproduce this over the past few days and have been unable to do so. Is it reproducible on your end, and is there anything that you can think of that's unique to your setup? (eg. JACK instead of PulseAudio or ALSA?)

**Comment by nsgutierrez** [comment]
I do have 32 bit pulse and alsa libs for steam, along with the steam-native meta package from the AUR. Let me see if I can even get it to happen again on _my_ system and I'll report back.

**Comment by KRE02** [comment]
It is also reproducible for me on Fedora (mumble from fedora repos).

**Comment by nsgutierrez** [comment]
KRE02, can you give steps to reproduce?

**Comment by mkrautz** [comment]
I'm assuming this is a dup of https://github.com/mumble-voip/mumble/issues/1074 ... Closing.
