### ISSUE TITLE
After suspending, global shortcuts no longer work

### ISSUE THREAD

**Issue by lhunath** [mumble-voip/mumble#2567]
All configured global shortcuts stop working when the computer is suspended and resumed from sleep.  They are re-activated by restarting mumble or by going into the settings screen and the shortcuts tab.

This was experienced on Mac OS X.

**Comment by mkrautz** [comment]
@lhunath 
Which version of Mumble? Which version of macOS?

**Comment by lhunath** [comment]
Mumble-1.3.0~1634~g2d6e099~snapshot
macOS Sierra 10.12 16A323

**Comment by mkrautz** [comment]
Seemingly not a shortcut problem. It seems, on my machine, that the audio system stops working...

**Comment by AndrewJDR** [comment]
I was recently observing how things like Chrome behave if you do a `pulseaudio -k` then `pulseaudio -D` to restart pulse on a system, Chrome automatically re-connects itself to pulse. I believe mumble will need to do something similar to be resilient to things like system suspend, restarting of the pulse daemon, etc.

For mumble, If I do a `pulseaudio -k` to kill pulse, I note that a "PulseAudio: Connection failure" error gets printed. Under the hood, contextCallback() in PulseAudio.cpp gets called, and PA_CONTEXT_FAILED block gets executed. Mumble never recovers from this situation, but Chrome does.

I believe handling this situation the way chrome does would lead to mumble being far more resilient in situations where connection to pulse is lost... e.g. the computer goes into suspend mode and wakes up, or other situations like that.

I believe that when pulse context failures occur PA_CONTEXT_FAILED/PA_CONTEXT_TERMINATED cases inside of contextCallback(), we need to enter an infinite retry loop where we try to reinitialize pulse (i.e. perhaps the stuff in PulseAudioInit::initialize()). Does this sound sensible? Is this difficult to do?

**Comment by AndrewJDR** [comment]
@mkrautz any thoughts on my comment above?

**Comment by mkrautz** [comment]
I think the idea is spot on. But I don't know how difficult it'd be (haven't looked at the Pulse code in a while.)

**Comment by ZeroAbility** [comment]
macOS Sierra 10.12 is end of life. Does this behavior still occur in new versions of macOS and Mumble?
