### ISSUE TITLE
Not always detecting release of modifier keys

### ISSUE THREAD

**Issue by LazyBoot** [mumble-voip/mumble#2568]
Since the Win10 anniversary update I've started having issues with mumble not detecting the release of modifier keys in certain situations.
ex. ctrl and alt will always be seen as mumble as down after using ctrl+alt+del, and will trigger shortcuts using ether as a modifier until the key is pressed again.

**Comment by LazyBoot** [comment]
I also feel I should mention at the same issue also happens with the windows key when doing win+L.

**Comment by ZeroAbility** [comment]
Is this still an issue in newer versions of Windows 10 or 11 and Mumble 1.4?

**Comment by Krzmbrzl** [comment]
There was a similar issue that has been fixed. Furthermore, the shortcut system on Windows has been rewritten, so unless proven otherwise, I'll assume this to be fixed.
