### ISSUE TITLE
Ice_MemoryLimitException on heavy server

### ISSUE THREAD

**Issue by sss123next** [mumble-voip/mumble#2570]
i have setup with lots of channels with long descriptions and heavy images in it and without limits on message length.
i have permanent error when trying to administer this server via ice with any available tools.
changing "Ice.MessageSizeMax=" does nothing.

**Comment by bddenhartog** [comment]
` Ice.MessageSizeMax` is the correct setting to update to handle this exception. Can you post your ice configuration settings here?

**Comment by sss123next** [comment]
```
cat murmur.ini  |grep Ice
#   with virtual server specific configuration via the Ice or DBus interface.
# If you want to use ZeroC Ice to communicate with Murmur, you need
# Ice primarily uses local sockets. This means anyone who has a
# user account on your machine can connect to the Ice services.
# You can set a plaintext "secret" on the Ice connection, and
# configure it here than through D-Bus or Ice.
# You can configure any of the configuration options for Ice here. We recommend
[Ice]
Ice.Warn.UnknownProperties=1
Ice.MessageSizeMax=65534

```

**Comment by bddenhartog** [comment]
What is the error you are seeing?

**Comment by sss123next** [comment]
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /home/www/www/admin/mumpi/classes/MurmurClasses.php on line 275`

**Comment by bddenhartog** [comment]
The error message you just commented is from PHP, not from murmur or ICE.

That error message is shown when your PHP program runs out of available memory to use. Either your `memory_limit` setting in your `php.ini` configuration file is too low, or there's a memory leak somewhere.

From the block of code you posted, I'm guessing whatever class you're in has an `iceObj` property that is itself another class. What does the `getTexture()` function do on the class that `iceObj` is an instance of?

**Comment by sss123next** [comment]
thx for reply, i have increased memory_limit to 256mb from 128mb, now problem looks solved

**Comment by bddenhartog** [comment]
While that's certainly a solution and I'm glad it fixed your issue, you may want to look into what, specifically, was causing your app to hit the memory limit and ensure that it can't happen again. If it's from user-uploaded content, enforcing the limit logic on the upload form would be the proper course of action.

**Comment by sss123next** [comment]
yes, most probably it's large user avatar, i used to have no limits until now
