### ISSUE TITLE
Audio sometimes doesn't flow until reconnection

### ISSUE THREAD

**Issue by sgtnoodle** [mumble-voip/mumble#2575]
This seems to happen maybe 1 in 20 times I connect a client. The client connects and everything looks ok, but I can't hear other users when the speak. When I push-to-talk, I can see myself speaking locally but other users don't see me speaking. The problem persists until I disconnect and re-connect.

I've had it occur on both windows and linux clients. Unfortunately I don't have any logs collected yet. It could be a server or client problem.

**Comment by Kissaki** [comment]
Maybe network. Any fancy firewall or router, provider, or driver stuff

**Comment by sgtnoodle** [comment]
I just had this bug pop up again. I'll probably spend some time in January figuring out a way to recreate this problem on the bench so that I can start sniffing network packets. Any suggestions where to look to save on debugging effort?

@Kissaki I've encountered this bug in the following configurations:

LAN setup:
1. Server running on arch linux based server ->wired Ethernet -> router's switch -> wired Ethernet -> Client running on arch linux based desktop
2. Server running on arch linux based server ->wired Ethernet -> router's switch -> WiFi -> Client running on windows 10 laptop
3. Server running on ubuntu linux based server ->wired Ethernet -> fancy cisco switch -> wired Ethernet ->dumb switch -> wired Ethernet -> Client running on windows 10 laptop

WAN setup:
Server running on ubuntu linux based server ->wired Ethernet -> fancy cisco switch -> wired Ethernet -> ISP equipment -> series of tubes -> ISP Equipment -> wired Ethernet -> switch -> wired Ethernet -> switch -> wired Ethernet -> Client running on ubuntu linux laptop

**Comment by Keridos** [comment]
I know somebody with a bit unstable internet connection and it happens to him every 5-10 minutes.

**Comment by Krzmbrzl** [comment]
Does this still happen with Mumble 1.3?

**Comment by sgtnoodle** [comment]
Unfortunately I haven't had a need to use mumble for a while and cannot say. Let's hope it's fixed, though!

**Comment by Krzmbrzl** [comment]
Alright then let's hope for the best. I'll close this issue for now and if someone encounters it again, we'll reopen it :)
