### ISSUE TITLE
Client can't switch usernames after logging in as a registered user

### ISSUE THREAD

**Issue by sgtnoodle** [mumble-voip/mumble#2576]
After logging in as a registered user, I can't disconnect and then reconnect with a different username. Upon reconnection I always end up as the registered user instead of the username specified in the Edit Server dialog.

I'm happy to take a crack at a fix, but I'm hoping someone more familiar with the code base than me has an idea of the root cause and can point me in the right direction.

**Comment by mkrautz** [comment]
This is the intended behavior.

However, administrators can change the name after registration via the Registered Users list in the client or via RPC.
