### ISSUE TITLE
Admin to have volume raise/lower control of users

### ISSUE THREAD

**Issue by magicrub** [mumble-voip/mumble#2579]
Instead of an admin only having a mute-user option, it would be nice to offer a volume raise/lower option.

**Comment by Natenom** [comment]
A user volume control is already implemented in the current development version of Mumble, see https://github.com/mumble-voip/mumble/commit/15f47f4f858ea0a95145e12f43f1c3f8e0d326ef.

Or do you mean that an admin could be able to change the volume of one user for all other users?

**Comment by magicrub** [comment]
well, really it would be nice for a user to change input volume but admin control would be nice too. Seems lots of people can't deal with the simple interface so if someone else could boost them "magically" in a given call then that would be nice too.

**Comment by WickedShell** [comment]
@Natenom I'd like a user option to adjust the local volume of a given user in the channel. (They have a low gain). Where in the UI is that option? (Version 1.2.17) I'm assuming from that commit that would be in this loaded version.

**Comment by Natenom** [comment]
You need the current snapshots to use that feature.
https://wiki.mumble.info/wiki/Main_Page -> Download Mumble -> Development snapshots

**Comment by WickedShell** [comment]
Ah just figured it would have that given the date of Oct, 15th 2015 and 1.2.17 was Sept 2016 :) didn't look in the tree to figure out when it was merged :) Cool thanks!

**Comment by magicrub** [comment]
I'm willing to close this now that users can adjust their own input Mic
volumes.
