### ISSUE TITLE
Targeted channel not found on connect

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#2584]
Just grabbed build 1645 and logged back into my Mumble server. No matter what channel I go to, I receive the error, "The targeted channel could not be found."

Tested with the root channel and deeper subchannels:
- /
- / AFK /
- / Main / General

All of them give that error when connecting.

**Comment by TFMvdBroek** [comment]
+1 same happens here.

**Comment by Kissaki** [comment]
Well, oops.
Confirmed.

**Comment by ElPumpo** [comment]
![namnlos](https://cloud.githubusercontent.com/assets/12564301/19700740/c54a1640-9af8-11e6-99dc-d9638d73bffb.png)
Exactly

**Comment by Kissaki** [comment]
???
