### ISSUE TITLE
Qt 4 build error via precise PPA

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2586]
g++ -c -include release/murmurd -m64 -pipe -fvisibility=hidden -Wall -Wextra -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -g -isystem ../mumble_proto -isystem murmur_ice -O2 -pthread -Wall -W -D_REENTRANT -DNO_UPDATE_CHECK -DPLUGIN_PATH=/usr/lib/mumble -DMUMBLE_VERSION=1.3.0~1643~g4add9ce~snapshot-1~ppa1~precise1 -DHAVE_LIMITS_H -DHAVE_ENDIAN_H -DRESTRICT=__restrict__ -DMUMBLE_VERSION_STRING=1.3.0 -DQ_DECL_OVERRIDE= -DQ_DECL_FINAL= -DMURMUR -DUSE_DBUS -DUSE_ICE -DUSE_BONJOUR -D_REENTRANT -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I../../src -I. -I../mumble_proto -Imurmur_ice -I../../3rdparty/qqbonjour-src -I/usr/include/avahi-compat-libdns_sd -Irelease -o release/ServerDB.o ServerDB.cpp
	Server.cpp: In member function ‘void Server::sendMessage(ServerUser*, const char*, int, QByteArray&, bool)’:
	Server.cpp:897:20: error: ‘class QAtomicInt’ has no member named ‘load’
	make[3]: *** [release/Server.o] Error 1
	make[3]: *** Waiting for unfinished jobs....
	ServerDB.cpp: In member function ‘void Server::updateChannel(const Channel*)’:
	ServerDB.cpp:1691:25: warning: ‘id’ may be used uninitialized in this function [-Wuninitialized]
	make[3]: Leaving directory `/«PKGBUILDDIR»/src/murmur'
	make[2]: *** [release] Error 2
	make[2]: Leaving directory `/«PKGBUILDDIR»/src/murmur'
	make[1]: *** [sub-src-murmur-sub_Release_ordered] Error 2
	make[1]: Leaving directory `/«PKGBUILDDIR»'
	make: *** [build-arch-stamp] Error 2
	dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by mkrautz** [comment]
https://launchpad.net/~mumble/+archive/ubuntu/snapshot/+build/11050031

**Comment by Kissaki** [comment]
The `QAtomicInt::load()` call in question was added in 46b5b62781c8d0a50c3786417f7bad4c2c0f9a39 to fix #2418 (Merge #2420).
Before, the `operator int()` method was used. In Qt 4.8, `QAtomicInt` is always an int. In Qt5.3, `QAtomicInteger` was introduced with a template parameter, and `QAtomicInt` is `QAtomicInteger<int>`.

[Qt4.8 operator int()](http://doc.qt.io/qt-4.8/qatomicint.html#operator-int)
[Qt5 load()](http://doc.qt.io/qt-5/qatomicinteger.html#load)
[Qt5 operator T()](http://doc.qt.io/qt-5/qatomicinteger.html#operator-T)
[Qt5.2 (unoff)](http://qt.apidoc.info/5.2.0/qtcore/qatomicint.html)

Strangely, Qt5.0, 5.1 and 5.2 do not have the `operator int()` function according to qt.apidoc.info, but 5.3 has it again.

So either we guard specific logic for these versions, or we change to using a `fetchAndAdd` method, adding 0.

**Comment by Kissaki** [comment]
As we have no multithreading, Relaxed should be fine for all (like `load()` does).

**Comment by mkrautz** [comment]
> As we have no multithreading

There is multithreading in there, FWIW.

See https://github.com/mumble-voip/mumble/blob/master/docs/MurmurLocking.md#data-with-no-ownership-synchronized-via-atomic-types
