### ISSUE TITLE
[Feature request] Cmd line mumble client (Linux / Raspberry pi)

### ISSUE THREAD

**Issue by mike6000** [mumble-voip/mumble#2595]
On Linux and Raspberry pi machines there is a need for starting the mumble client from cmd line. Please consider adding cmd line options so that the client can be started and run without x server or manual interaction.

**Comment by mkrautz** [comment]
Mumble proper is never going to get a CLI version. But there are other clients, such as 
Barnard (https://github.com/layeh/barnard) providing a CLI Mumble client.

Note that it's also possible to start mumble itself using things such as Xvfb, which can run w/o a display.
