### ISSUE TITLE
Notifications are delayed

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#2596]
I have experienced delayed (Windows) notifications time and time again for some time now. I think it’s the norm rather than occurring occasional.

I do not get a notification for user moves, joins etc for some time. Then, seemingly when another notification is triggered, the notifications show one after the other.

I wonder if this is only an issue on Windows.

**Comment by Kissaki** [comment]
They even come up a long time after Mumble has been closed…

**Comment by mkrautz** [comment]
Does this happen when you've been running a full screen game? That's when I typically have noticed behavior like this.

**Comment by Kissaki** [comment]
I *think* it also happens without a fullscreen game running.

**Comment by nicolasjoly** [comment]
I have the same problem. Win10 x64, latest mumble snapshot. But I have the exact same behavior with filezilla, so I think it's a Windows problem.

**Comment by Krzmbrzl** [comment]
At least on Linux I didn't have this problem.

Also notifications being shown after Mumble has been closed indicates to me that Windows somehow got stuck on them and is simply slow spitting them out again. Thus I'd close this issue as a Windows problem.
