### ISSUE TITLE
Build fails with Qt 5.7

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#2600]
Since commit e99b0c90 building Mumble fails because Qt 5.7 requires C++11. Reverting the commit or appending "c++11" to the CONFIG parameter makes it work again.

As I understand the commit message "-std=c++11" should be used automatically with newer Qt 5 versions. This is not the case here, hence the build fails.

Arch Linux
GCC 6.2.1
Qt 5.7.0

**Comment by mkrautz** [comment]
The thinking was that Qt 5.7 would automatically set CONFIG+=c++11.

Apparently not. We've had several reports of this.

We'll need to check what the correct thing to do here is.

The obvious fix is to simply check for >= 5.7 and do CONFIG+=c+11 ourselves.
But perhaps Qt 5.7 sets another CONFIG option or something similar that we can use as a hint.

**Comment by Ape** [comment]
Couldn't we just use `-std=c++11` always? GCC 6.1 and later actually default to `-std=c++14`. So it's considered stable for production use.

**Comment by mkrautz** [comment]
@Ape Some of our targets for 1.3.x have really old compilers. (CentOS 5 with GCC 4.1).

**Comment by mkrautz** [comment]
Fixed by https://github.com/mumble-voip/mumble/pull/2630.
