### ISSUE TITLE
Murmur only listening on IPv6

### ISSUE THREAD

**Issue by Fossil01** [mumble-voip/mumble#2601]
Just installed Murmur on CentOS 7 but I can only connect over IPv6. When trying v4 it doesnt connect. Tried telnetting and it just times out.

host=
host=0.0.0.0.
host=::
# host

All do not work on IPv4. When I set the host to 0.0.0.0 or the servers external IP Murmur logs this error:

```
<W>2016-10-26 20:22:50.706 Initializing settings from /etc/murmur.ini (basepath /etc)
<W>2016-10-26 20:22:50.706 Binding to address 0.0.0.0
<W>2016-10-26 20:22:50.707 Meta: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
<W>2016-10-26 20:22:50.707 OpenSSL: OpenSSL 1.0.2i  22 Sep 2016
<C>2016-10-26 20:22:50.707 WARNING: You are running murmurd as root, without setting a uname in the ini file. This might be a security risk.
<W>2016-10-26 20:22:50.746 ServerDB: Opened SQLite database /etc/murmur.sqlite
<W>2016-10-26 20:22:50.747 Resource limits were 0 0
<W>2016-10-26 20:22:50.747 Successfully dropped capabilities
<W>2016-10-26 20:22:50.749 DBus registration succeeded
<W>2016-10-26 20:22:50.778 Murmur 1.2.17 (1.2.17) running on X11: CentOS Linux release 7.2.1511 (Core): Booting servers
<W>2016-10-26 20:22:50.782 1 => Server listening on 0.0.0.0:64738
<W>2016-10-26 20:22:50.784 1 => Failed to set IPV6_RECVPKTINFO for 0.0.0.0:64738
<W>2016-10-26 20:22:50.787 1 => Announcing server via bonjour
<W>2016-10-26 20:22:50.790 1 => Not registering server as public
<W>2016-10-26 20:22:50.790 Object::connect: No such slot MurmurDBus::userTextMessage(const User *, const TextMessage &)
```

I've disabled the firewall and flushed IP tables so that's not the issue here.

**Comment by mkrautz** [comment]
I've just tried to reproduce this on a default CentOS 7 install with the latest stable static Murmur (the same one that you seem to be using).

Without adding tcp/udp 64738 to the firewall, I can't connect - it times out.

After adding the port to the firewall, I can connect fine.

This is with the default murmur.ini.

Sadly, I'm not able to reproduce the issue.

**Comment by Fossil01** [comment]
What does `Failed to set IPV6_RECVPKTINFO for 0.0.0.0:64738` mean?

**Comment by mkrautz** [comment]
It means that Murmur couldn't enable the IPV6_RECVPKTINFO option on the socket (which allows the program to get some extra metadata for received UDP datagrams). In this case, I believe the error happens because a socket listening on 0.0.0.0 is an IPv4 socket. Since this isn't an IPv6 socket, it shouldn't cause any problems.

**Comment by unrivaledcreations** [comment]
@Fossil01 - I had a similar issue with Ubuntu, and discovered that my server was simply firewalled.

## Digital Ocean One-Click Install Ubuntu Fix

In my case, I'm using a Digital Ocean droplet, so I had to allow port 64738/tcp and 64738/udp through the droplet firewall ([see droplet firewall instructions](https://www.digitalocean.com/docs/networking/firewalls/how-to/manage-droplets/)), _and_ through the Ubuntu virtual machine instance firewall ([see Ubuntu firewall instructions](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-18-04)).

The exact firewall commands I used after logging into my Ubuntu box were:

```
ufw allow 64738/tcp
ufw allow 64738/udp
```

In some cases, I could picture SELinux settings causing similar problems; but I can confirm that the stated error message, `Failed to set IPV6_RECVPKTINFO for 0.0.0.0:64738`, is harmless in IPv4 implementations of `murmurd`.

@mkrautz - This ticket is several years old and can probably be closed as resolved.
