### ISSUE TITLE
Document how to reset audio attenuation after a crash

### ISSUE THREAD

**Issue by rcoones1** [mumble-voip/mumble#2606]
I was speaking in mumble v1.3.0 and it crashed while i had the ptt held down. Now the attenuation that I had set at 75% remains in effect only on WoW. I can barely hear the game now at 100%. This is the second time it happened I thought nothing of it the first time and increased my wow game volume. So the effects have now stacked and even at 100% it is stuck at im assuming around 12.5% volume. I have tried it on different audio devices and it still works fine on them but through my headset device it is completely attenuated at all times now. I have tried reinstalling Mumble, disabled attenuation altogether, deleting my WTF in wow, changing audio settings on the hardware, I cannot think of anything else to try to fix this problem.

**Comment by JagJohn** [comment]
I presume you're using Windows, it sounds like Mumble's lowering of the WoW output is still in place. If you right-click on the speaker icon in the taskbar and click "Open Volume Mixer", you can check that the WoW output isn't turned down much farther than anything else.

**Comment by rcoones1** [comment]
How would I go about that.. i have been through the mixer in every area and I do not see any application specific settings. The sound is horribly low and makes it rough when using mumble because i have to max my volume to hear the game and turn everyone on mumble down to not have them screaming in my ears.. and like i said its only on the headphone ports as well which i found kind of odd.. if i switch the sound to come out of my laptop speakers everything sounds fine.

**Comment by rcoones1** [comment]
Wow, yeah I found that setting, and you sir are a god now. Thank you sooo much for helping me fix this. That is awesome. I dont know how I did not stumble upon this with as much clicking as I have put into trying to fix it.

**Comment by mkrautz** [comment]
This feels like it should be documented somewhere. Maybe a FAQ.

**Comment by Krzmbrzl** [comment]
https://wiki.mumble.info/wiki/FAQ/English#How_can_I_undo_audio_attenuation_applied_by_Mumble.3F
