### ISSUE TITLE
Mumble not hooking to LGS

### ISSUE THREAD

**Issue by Cynical8** [mumble-voip/mumble#2610]
I have the latest of both mumble and logitech gaming software and mumble refuses to create a logitech profile for me to be able to use my gkeys. I'm running a 64 bit os and my lgs is for 64 bit verison.

**Comment by mkrautz** [comment]
@Cynical8 Did you fix this? If so, it might be helpful for others if you describe what was wrong and how you fixed it. Thanks.

**Comment by Cynical8** [comment]
My problem was the version of mumble I was using was 1.2.7 but the wiki I found required me to have 1.3 so I downloaded a copy of 1.3

**Comment by mkrautz** [comment]
Ah, OK. Thanks!
