### ISSUE TITLE
 Debian builds fail with commit:    plugins: use the short form of peekProc

### ISSUE THREAD

**Issue by EmperorArthur** [mumble-voip/mumble#2615]
Commit 921ee19e3abd24482921d85b38c0c4b3d0cbcffe throws a compiler error on Debian Stretch.

`g++ -m64 -Wl,-z,relro -Wl,-z,now -Wl,-O1 -shared -o liblink.so release/link-posix.o  -L/usr/lib/x86_64-linux-gnu/c++11 -lrt  
In file included from ../mumble_plugin_linux_32bit.h:14:0,
                 from l4d2_linux.cpp:6:
../mumble_plugin_linux.h: In instantiation of ‘bool peekProc(procptr32_t, T&) [with T = unsigned char; procptr32_t = unsigned int]’:
l4d2_linux.cpp:26:41:   required from here
../mumble_plugin_linux.h:188:15: error: invalid conversion from ‘unsigned char’ to ‘void*’ [-fpermissive]
  out.iov_base = dest;
  ~~~~~~~~~~~~~^~~~~~
mv -f liblink.so ../../release/plugins/`

**Comment by mkrautz** [comment]
@davidebeatricci

**Comment by mkrautz** [comment]
@davidebeatrici 

https://github.com/mumble-voip/mumble/blob/master/plugins/mumble_plugin_linux.h#L188

This line should be `out.iov_base = &dest;`.
