### ISSUE TITLE
Allow client to identify when the TalkState of any user changes

### ISSUE THREAD

**Issue by iammeat** [mumble-voip/mumble#2619]
I am investigating a project at the moment that would entail knowing the TalkState of any user on the server, regardless of which channel they are in.  

Is it currently possible to obtain the actual TalkState of a user who is in another channel?  I've done my best looking through the code of the client and server and, while I can see in the server that the TalkState is updated, I was unable to find a method for obtaining this information for any user outside the current channel via the client.

**Comment by mkrautz** [comment]
The talkstate is a client-side concept. It's only updated when voice data for that user is being played backed, and when that playback ends.

**Comment by iammeat** [comment]
So there's no way to identify when users are transmitting if they're not in the same channel as the client user?

**Comment by mkrautz** [comment]
I suppose it would be possible to modify Murmur to expose this info.

But there's no built-in functionality for this, no.

**Comment by mkrautz** [comment]
This is not something we're likely to implement in Murmur.

There is no clear use-case, at least from my perspective.

@iammeat Can you please describe you use case for this in more detail? Maybe it's something that's generally useful, and warrants us considering it for inclusion in Mumble.

**Comment by mkrautz** [comment]
@iammeat 

A potential "easy-to-implement" variant of this feature would be to have a voice timestamp on each user on the server. This timestamp would note when the user's last voice packet was sent.

You'd be able to use that information to recreate a talk state indicator. You'd set a "talk duration" to something like 250ms and keep the talk state "active" is the timestamp is increased within the next 250ms.  If it isn't increased, talking has stopped.

This isn't 100% accurate (since voice frames typically have much smaller durations), but for visualization purposes it would work quite well I think.

**Comment by Kissaki** [comment]
We already have [`idleTime`](http://mumble.sourceforge.net/slice/1.3.0/Murmur/User.html#idlesecs), so that could be used as you described. As long as idleTime == 0 [s], he is talking.

**Comment by mkrautz** [comment]
Sure, idleTime could maybe be used for this. Depends on the precision that @iammeat needs.

**Comment by iammeat** [comment]
@mkrautz Regarding use-case, there are situations where an admin on the system may wish to set up monitoring that would trigger when specific users spoke no matter which channel they were on, such as users who had been warned due to offensive or disruptive behaviour.  

Another use case would be an "emergency" channel where specific users, such as in EVE Online, can jump in that channel when an attack occurs in their region.  It means that the channel doesn't have to be constantly linked but still be of great use.  It also allows an admin to only be notified when specific users broadcast in that channel.

This could then be used to either record the communication for later playback or the client could be modified so it would pull the admin user into the specific channel the user was on.

@Kissaki and @mkrautz idleTime looks like it could do the job, but the precision would be a bit low for what I'm thinking about.  If there was a way to see milliseconds idle, that would possibly be better.  I think a duration of 100 - 250ms would be quite a bit better than 1 second.

**Comment by Kissaki** [comment]
I still don’t get it. If you want to record if someone speaks in a channel, you will want to do that serverside anyway, or put a bot in there that records anything users say/shout. No?

By monitoring, do you mean listening to audio as well?

Would all this happen client-side in real time, or via backend/webinterface and recordings?
