### ISSUE TITLE
Settings reset sporadically

### ISSUE THREAD

**Issue by leonlag** [mumble-voip/mumble#2625]
I have an issue with the settings. They reset a lot after starting it up (even the setup wizard starts again). I have this issue with mumble 1.2.17 on arch linux (from the arch repo) and 1.3.0\~1650\~g30c779c~snapshot on windows 10.

**Comment by Kissaki** [comment]
Could this be due to your local settings being removed/unaccessible?
Should be in your home .local as per http://wiki.mumble.info/wiki/Client_Settings
