### ISSUE TITLE
Compiling murmurd on FreeBSD 10.3/11 fails

### ISSUE THREAD

**Issue by krismach** [mumble-voip/mumble#2629]
I've followed the guide from: https://wiki.mumble.info/wiki/BuildingFreeBSD

pkg install git
git clone git://github.com/mumble-voip/mumble.git mumble
cd mumble
git submodule init
git submodule update

pkg install boost-libs ice qt5-core qt5-network qt5-xml qt5-qmake qt5-sqldrivers-sqlite3 protobuf qt5-buildtools

/usr/local/lib/qt5/bin/qmake CONFIG+=no-client CONFIG+=no-dbus CONFIG+=no-bonjour main.pro
make release

I've tested on a VM with fresh install of FreeBSD 10.3 and FreeBSD 11, both with same exact results:

A very long list of errors similar to:

../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d850): undefined reference to `IceInternal::Cpp11FnCallbackNC::verify(IceInternal::Handle<Ice::LocalObject> const&)'
../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d858): undefined reference to `IceInternal::Cpp11FnCallbackNC::sent(IceInternal::Handle<Ice::AsyncResult> const&) const'
../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d860): undefined reference to `IceInternal::Cpp11FnCallbackNC::hasSentCallback() const'
../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d880): undefined reference to `typeinfo for IceInternal::Cpp11FnCallbackNC'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

**Comment by mkrautz** [comment]
Your Ice is built in C++11 mode, but Mumble isn't being built in C++11 mode.
For the current tree, you can add CONFIG+=c++11, which should fix it.

**Comment by krismach** [comment]
Didn't help.

/usr/local/lib/qt5/bin/qmake CONFIG+=c++11 CONFIG+=no-client CONFIG+=no-dbus CONFIG+=no-bonjour main.pro
make release

clang++ -c -Xclang -include-pch -Xclang release/murmurd/c++.pch -pipe -fvisibility=hidden -Wall -Wextra -isystem /usr/local/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -isystem ../mumble_proto -isystem murmur_ice -O2 -std=gnu++11 -pthread -Wall -W -pthread -D_THREAD_SAFE -fPIC -DRESTRICT=__restrict__ -DMUMBLE_VERSION_STRING=1.3.0 -DMURMUR -DUSE_ICE -D_THREAD_SAFE -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -Imurmur_ice -I/usr/local/include -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtSql -I/usr/local/include/qt5/QtXml -I/usr/local/include/qt5/QtCore -Irelease -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o release/moc_MurmurIce.o release/moc_MurmurIce.cpp
clang++ -Wl,-z,relro -Wl,-z,now -pthread -Wl,-rpath,/usr/local/lib -o ../../release/murmurd release/ACL.o  release/Group.o  release/Channel.o  release/Connection.o  release/HTMLFilter.o  release/User.o  release/Timer.o  release/CryptState.o  release/OSInfo.o  release/Net.o  release/SSL.o  release/Version.o  release/SSLCipherInfo.o  release/main.o  release/Server.o  release/ServerUser.o  release/ServerDB.o  release/Register.o  release/Cert.o  release/Messages.o  release/Meta.o  release/RPC.o  release/PBKDF2.o  release/UnixMurmur.o  release/MurmurIce.o  release/moc_ACL.o  release/moc_Channel.o  release/moc_Connection.o  release/moc_Server.o  release/moc_ServerUser.o  release/moc_Meta.o  release/moc_UnixMurmur.o  release/moc_MurmurIce.o   -L/usr/local/lib -L/usr/lib -L../../release -lmumble_proto -lcrypto -lssl -lIce -lIceUtil -lmurmur_ice -lprotobuf -D_THREAD_SAFE -pthread -lpthread -lQt5Network -lQt5Sql -lQt5Xml -lQt5Core

../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d850): undefined reference to `IceInternal::Cpp11FnCallbackNC::verify(IceInternal::Handle<Ice::LocalObject> const&)'
../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d858): undefined reference to `IceInternal::Cpp11FnCallbackNC::sent(IceInternal::Handle<Ice::AsyncResult> const&) const'
../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d860): undefined reference to `IceInternal::Cpp11FnCallbackNC::hasSentCallback() const'
../../release/libmurmur_ice.a(Murmur.o):(.data.rel.ro+0x1d880): undefined reference to `typeinfo for IceInternal::Cpp11FnCallbackNC'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

**Comment by EmperorArthur** [comment]
Can you please try this: `qmake -recursive main.pro "CONFIG += c++11"` on Pull #2600.

Information that would be helpful:  `g++ --version` and the version of QT that you have installed.

**Comment by mkrautz** [comment]
If that's the case, then I suppose what's happening here is that your version of clang defaults to c++11 mode. (Like gcc 6 defaults to c++11 mode).

But the version of Ice you're linking against was built in c++98 mode (the Ice ABIs are different in c++98 vs. c++11).

The errors you see are because the Ice headers think that your local Ice is built in C++11 mode, because the headers can see that the application code you're building is building in C++11 mode.

What we've tried now is:

1. Build current git master, which uses to -std=c++98
2. Build current git master with CONFIG+=c++11, which uses -std=c++11

If Ice is built against c++98, option 1 should've worked, unless clang overrides the -std=c++98 flag, forcing c++11 mode instead...

**Comment by krismach** [comment]
Yes, it looks like the pkg ice and ports ice are built as c++98. And mumble defaults to c++11 or clang 3.8 defaults it? Anyway I've added

CFLAGS+=-std=c++11
CPPFLAGS+=-std=c++11
CXXFLAGS+=-std=c++11

to /etc/make.conf and rebuild ice port and now I can compile mumble without issues.

But maybe someone should update the wiki, that you need to compile ice from ports with c++11, and the pkg ice wont work.

**Comment by mkrautz** [comment]
Up for grabs:

Document in the Wiki that Ice and Mumble should be built with the -std=c++XX flag.

Or come up with a way to detect that in the build, an make it an build-time error.

**Comment by Krzmbrzl** [comment]
Given that this issue is 4 years old now and nobody else seems to have had this problem, I think we can assume that all major distros are now using cpp11-versions of ice by default.

Furthermore the last Ubuntu LTS that ships a version of Ice <=3.6 is 16.04 which will become EOL in April next year.

Thus I think we can close this issue as "no longer relevant".
