### ISSUE TITLE
Murmurd dpkg-reconfigure issue

### ISSUE THREAD

**Issue by cnrat** [mumble-voip/mumble#2635]
After run 'dpkg-reconfigure mumble-server' it shows error:

> <W>2016-11-13 10:40:28.077 Initializing settings from /etc/mumble-server.ini (basepath /etc)
> <W>2016-11-13 10:40:28.082 Meta: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-> ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
> <W>2016-11-13 10:40:28.082 OpenSSL: OpenSSL 1.0.2j  26 Sep 2016
> <W>2016-11-13 10:40:28.536 ServerDB: Opened SQLite database /var/lib/mumble-server/mumble-server.sqlite
> Password: <F>2016-11-13 10:40:28.576 Superuser password set on server 1
> murmurd: /usr/include/IceUtil/Mutex.h:285: IceUtil::Mutex::~Mutex(): Assertion `rc == 0' failed.
> Aborted

Any one can help?

**Comment by mkrautz** [comment]
Hmm, not something I've seen before.

What version of Murmur? What Debian(-derived) distro? How did you get the Murmur package? etc.

**Comment by cnrat** [comment]
Kail Linux with 'apt-get install mumble-server'.
I'll try Ubuntu later.
