### ISSUE TITLE
Settings not saving properly in macOS Sierra

### ISSUE THREAD

**Issue by Xefir** [mumble-voip/mumble#2638]
When I save any settings on macOS Sierra, some settings isn't saved correctly.
All QVariant is saved "@Variant(" in the plist, instead of "@Variant([some hex])".
The only thing that look like this issue on the internet is this old ticket on the Qt Core : https://bugreports.qt.io/browse/QTBUG-40105

Before saving settings : 

![image](https://cloud.githubusercontent.com/assets/961976/20248576/50bccf90-a9e7-11e6-8907-c26d7123eee7.png)

The plist : https://cloud.crystalyx.net/index.php/s/N5kFTEIStePT6rE

After changing some settings, saving and restarted Mumble : 

![image](https://cloud.githubusercontent.com/assets/961976/20248631/61416118-a9e8-11e6-88d0-40feacf8b90c.png)

The plist : https://cloud.crystalyx.net/index.php/s/8WvCR6Cjn5BbMXv

PS : I have removed all sensitive informations on the plist like net.certificate.

**Comment by mkrautz** [comment]
Confirmed.

Easily reproducible by setting volume to somehing other than 100.

**Comment by mkrautz** [comment]
Perhaps https://github.com/qt/qtbase/commit/764f5bf48cc87f4c72550b853ab93b815454cd48?

**Comment by mkrautz** [comment]
OK, that patch worked for Qt 5.
I added it to the buildenv: https://github.com/mumble-voip/mumble-releng/commit/2c1752be4f140ae11e13c5153e81744540f928d0

So the issue should be gone in snapshots soon...

Also, I can confirm that the same thing happens on Qt 4... I guess we'll have to backport. :-(

**Comment by mkrautz** [comment]
Also, we should probably add a check for the invalid value... Something like `if (value == QLatin1String("@Variant(")) { // use default... }` (Or maybe a more robust solution where we detect whether the closing `)` is actually there?

**Comment by mkrautz** [comment]
I've also backported the fix to Qt 4 in 1.2.x.

**Comment by mkrautz** [comment]
I've snapshotted what will probably become 1.2.18:
https://dl.mumble.info/Mumble-1.2.17~5~gd254f6c~snapshot.dmg

It includes a fix for this.

Also available in latest macOS snapshots.

Can you confirm this fixes the issue for you? Thanks.

**Comment by Xefir** [comment]
It's work ! All settings are saved properly.
But the icons became HUGE ! 

![image](https://cloud.githubusercontent.com/assets/961976/20892843/099812f2-bb10-11e6-9af3-fab507d4a0fd.png)

I know it's not the same problem, but maybe it's related with https://github.com/mumble-voip/mumble/issues/1267

**Comment by mkrautz** [comment]
Yes, it's related to that. I enabled retina support for the binary.... Still undecided about the trade-offs... What do you think? Are the icons too big?

**Comment by winneon** [comment]
@mkrautz How did you go about backporting this fix to qt4? I am trying to use their fix on qt4.8 at https://github.com/qt/qtbase/commit/764f5bf48cc87f4c72550b853ab93b815454cd48 but I run into a few problems with CFData and CFStrings when compiling on macOS Sierra.

**Comment by mkrautz** [comment]
@winneon: https://github.com/mumble-voip/mumble-developers-qt/commit/38ca587a64499707cb375738758430f8d105fc7d

**Comment by mkrautz** [comment]
@Xefir Released in Mumble 1.2.18.
