### ISSUE TITLE
Mumble blocks ability for Xbox One controller to sync

### ISSUE THREAD

**Issue by Carts1** [mumble-voip/mumble#2649]
Hi,
I have found a annoying bug with Mumble (last x64 snapshot or stable versions)
I can't sync my Xbox One S controller (with the official wireless adapter) if mumble is running.
See the console.txt when I try to sync the controller : 

>  GlobalShortcutWin: excluded XInput device 'Controller (Xbox One For Windows)' (guid {18d873f0-ad01-11e6-8001-444553540000} guid product {02ea045e-0000-0000-0000-504944564944}) from DirectInput

If I close Mumble everything is ok, I can sync, desync, resync etc...
My firmware of the controller is up to date (with Xbox Accessories from Windows Store) and the drivers for the adapter are the last too.
Sorry if my english is not perfect, I do my best.

Thanks :)

**Comment by mkrautz** [comment]
I just tried to reproduce this, but couldn't.

I'm using an Xbox One S controller with the wireless adapter, just like you.
I'm on Windows 10, Anniversary Update, build 14393.447.

I was able to sync the controller to my PC just fine, even though Mumble was running.

I'm not sure if the controller is on the latest firmware, however... Will try that next.

**Comment by mkrautz** [comment]
Hmmm.. That didn't change anything, I'm afraid.

**Comment by Carts1** [comment]
Have you try to do you many resync ? Because I can do just only one when Mumble is started (always the msg in the console.txt) but after if I desync the pad (10sec on the Xbox home button, or wait for inactivity) I can't resync when Mumble is running, I need to stop Mumble and I can.
I have Windows 10, Anniversary Update, build 14393.447 too, up to date (Pro 64bits, and clean install since 15 days)
In Xbox Accessories app my controller firmware version is 3.1.122 (I can't see the lasts numbers, maybe the french traduction) and its linked to my Xbox Live account.
Thanks for your help.

**Comment by mkrautz** [comment]
Thank you, I am now able to reproduce the problem.

**Comment by Carts1** [comment]
Great :D

**Comment by mkrautz** [comment]
I haven't been able to identify a cause, but there's a workaround which works, as long as you don't use Xbox controllers for shortcuts in Mumble.

You can use the reg file contained in the ZIP below to disable Xbox controller support in Mumble:

[xboxinput-disable.zip](https://github.com/mumble-voip/mumble/files/604587/xboxinput-disable.zip)

**Comment by Carts1** [comment]
Wow nice, that was exactly what I search to do !
Thanks very much bro !

**Comment by mkrautz** [comment]
I'm not actively looking at this bug, so I've unassigned myself and marked it up-for-grabs.

**Comment by Krzmbrzl** [comment]
Does this problem still occur in Mumble 1.3?
