### ISSUE TITLE
libg15daemon registers a SIGSEGV handler

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2654]
See stacktrace in https://github.com/mumble-voip/mumble/issues/2620 (copied):

	The application (or it's libraries) caught a Segmentation Fault. Backtrace follows:
	Backtrace: /usr/lib/x86_64-linux-gnu/libg15daemon_client.so.1(+0xe2e) [0x7f8904a9de2e]
	Backtrace: /lib/x86_64-linux-gnu/libpthread.so.0(+0x11670) [0x7f890185d670]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5(_ZN21QNetworkConfigurationD1Ev+0x3f) [0x7f89053805df]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN9QHashData11free_helperEPFvPNS_4NodeEE+0x49) [0x7f8901b78019]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5(+0xa906f) [0x7f890539306f]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN18QThreadStorageData6finishEPPv+0x313) [0x7f8901b15ed3]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate17cleanupThreadDataEv+0x2c) [0x7f8901ceea2c]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivateD1Ev+0x10b) [0x7f890214784b]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivateD0Ev+0x9) [0x7f8902735869]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QObjectD1Ev+0x677) [0x7f8901d242c7]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplicationD1Ev+0x136) [0x7f8901cf0ec6]
	Backtrace: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplicationD1Ev+0x3b1) [0x7f8902737331]
	Backtrace: ./release/mumble(+0x66890) [0x562b6010b890]
	Backtrace: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f8900bfd3f1]
	Backtrace: ./release/mumble(+0x6b10a) [0x562b6011010a]
	End of Backtrace.

**Comment by davidebeatrici** [comment]
See also #3447.

**Comment by Krzmbrzl** [comment]
https://github.com/mumble-voip/mumble/issues/2620#issuecomment-595815998
