### ISSUE TITLE
mumble executable "rpc" argument: toggle versions of "mute" and "deaf"

### ISSUE THREAD

**Issue by dstensnes** [mumble-voip/mumble#2678]
the mumble executable supports an "rpc" argument with actions, but I suggest having a "togglemute" and "toggledeaf" too. I wish to bind them to keys in my window manager on linux, since (as far as I can tell) the suppress option in the keyboard shortcut options is missing on linux.

**Comment by mkrautz** [comment]
I believe there is a toggle mode already, but I can't check at the moment.

**Comment by mkrautz** [comment]
There isn't.

**Comment by mkrautz** [comment]
Added in https://github.com/mumble-voip/mumble/commit/541ac08f8731478f237fa204f569c3bbee934f82.
