### ISSUE TITLE
Disable text chat altogether?

### ISSUE THREAD

**Issue by mirabilos** [mumble-voip/mumble#2679]
How can we forcely disable the text chat, for example in the murmur configuration, so that users can only use voice chat, and TTS never distracts (I know clients can disable TTS, but that’s not the point)?

**Comment by mkrautz** [comment]
Currently not possible server-side. But you can disable text messages client-side in Settings -> Messages. Ensure all of 'Console', 'Notification', 'Text-to-speech', 'Soundfile' are disabled.

**Comment by mkrautz** [comment]
Would a server-side option to disable text messages be preferable?

**Comment by mirabilos** [comment]
That would probably help in some cases… if the server admin can be persuaded to enable that option, of course, but if it’s there… ;)

**Comment by bontibon** [comment]
I think this use case is to fringe to warrant a new server-side option. Denying the TextMessage ACL permission should work just as well.
