### ISSUE TITLE
Link Plugin Problem

### ISSUE THREAD

**Issue by robingroppe** [mumble-voip/mumble#2680]
For a few days Mumble is not usable while playing Counter Strike Global Offensive.
Problems begin when the game "connects" to mumble and ends with disconnecting.
While playing people can not hear me and I can not hear anyone either. 
Sometimes I can hear a lagged fragments of some sound.
Everything works fine with game plugins completely disabled.

Using Snapshot 1.3.0~1758.

**Comment by mkrautz** [comment]
@davidebeatrici Do you have CSGO? Tried to look at it in MumblePAHelper?

**Comment by davidebeatrici** [comment]
@mkrautz Sadly I don't own the game, but I can do a test with another Source Engine game.

**Comment by mkrautz** [comment]
Values look fine to me

![image](https://cloud.githubusercontent.com/assets/36527/20812910/b0e330c8-b813-11e6-81a8-02950c29c2c2.png)

**Comment by mkrautz** [comment]
@robingroppe Are the other people on the server also playing CSGO on the same server and team?

Also, what's your "max distance" setting set to in Settings -> Audio Output -> Positional Audio?

**Comment by robingroppe** [comment]
I have not tested with other players. 
In this situation I was alone with nobody else playing in my channel.
Every value should be the default one. 
Never changed anything about that.

**Comment by mkrautz** [comment]
Thanks.

In that case, it sounds like Mumble thinks everyone else is using positional audio, too... Hmmm...

**Comment by mkrautz** [comment]
Unfortunately, I can't seem to reproduce this issue with the manual plugin, which leads me to believe that CSGO might have given you bogus values.

Which OS, BTW? I'm guessing Windows?

If possible, could you try running https://dl.mumble.info/MumblePAHelper-winx64-2016-07-16.zip before you start CSGO. (Don't run Mumble while doing this)...

Once in a CSGO multiplayer match (or offline with bots) it should show you the values Mumble would use for positional audio.

Can you post a screenshot? Thanks.

**Comment by robingroppe** [comment]
I am using LinuxMint 18.

Am 01.12.2016 11:20 nachm. schrieb "Mikkel Krautz" <notifications@github.com

**Comment by mkrautz** [comment]
Ah, OK. I'll have to investigate further...

**Comment by robingroppe** [comment]
I will check a few things when I am at home this afternoon. 
Do I need to compile mumblepahelper?

**Comment by mkrautz** [comment]
You could try. To see what CSGO is sending you.

But the real problem is Mumble treating all other participants as having positional audio enabled as well. Not sure why that is...

**Comment by ElPumpo** [comment]
Having a similar issue, cannot hear anyone when a game is linked to 3rd pos audio on the latest snapshot.

**Comment by mkrautz** [comment]
@ElPumpo which game? which plugin?

**Comment by ElPumpo** [comment]
@mkrautz apparently for all games :/

**Comment by tatokis** [comment]
Just an update, as I recently came across this issue.

It appears to be an issue with murmur, instead of the mumble client.
Bisecting it returned that https://github.com/mumble-voip/mumble/commit/91dc3d39f0a20644e10143d30048be64a28b6d75 is the first bad commit.

Reverting it manually on the latest HEAD has fixed this issue for me.

**Comment by hacst** [comment]
@tatokis That commit looks highly suspicious. Thanks for the bisect.

**Comment by davidebeatrici** [comment]
Fixed in #2825.
