### ISSUE TITLE
notification when user leaves the server in my channel

### ISSUE THREAD

**Issue by ZEDGR** [mumble-voip/mumble#2701]
When a user lefts the server and he/she is in my channel I want to get notify.

I have the user left channel notification on and user left server notification off but I don't get notify when a user in my channel leaves the server. I know that if I have the user left server notification on everything works fine but I don't want to get notify for users outside of my channel.

**Comment by Kissaki** [comment]
I think we ave another ticket on this topic. Not sure if that is still open.
Basically, when you have both enabled, we don’t want both notifications; in that case, server disconnect supersedes the channel leave.
Of course, in your use case a notification is missing.

**Comment by davidebeatrici** [comment]
Feature added via #3442.
