### ISSUE TITLE
Backport SRV Record Handling for 1.2.X?

### ISSUE THREAD

**Issue by Omicron16** [mumble-voip/mumble#2710]
SRV records seem to be on the table for the 1.3.X release of Mumble, although it is unclear just how far out this update is. It sounds like 1.3.X resolves SRV records natively through QT 5.

My knowledge of how Mumble interacts with QT is limited (static versus dynamic,) but I assume that at least parts of the QT 4 library 1.2.X is static due to the special version being included with the srv for TLS tweak. Windows likely fully uses QT in a static fashion, while Linux doesn't.

Given this, is it possible to somehow transplant QT 5's SRV record handling into the QT 4 that Mumble already includes? Either that, or did someone patch an separate independent resolver that worked with 1.2.X?

I like Mumble, but I'm using Teamspeak at the moment because of this.

**Comment by Kissaki** [comment]
On Linux Mumble packages typically use the systems Qt packages, so shared. For Windows, we use our own Qt fork (for 1.2.x and Qt4 see [mumble-voip/mumble-developers-qt](https://github.com/mumble-voip/mumble-developers-qt), for 1.3.0 and Qt5 [see the patch files in mumble-releng](https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.3.x/win32-static/patches)).

I do not know how much effort backporting the Qt features we depend on would be.

**Comment by mkrautz** [comment]
It's unlikely we're going to port SRV support to 1.2.x once it lands. I expect SRV support to be one of the last feature additions to 1.3.x, so it'll release soon thereafter.

We generally don't backport features to 1.2.x, since it's a stable release. The only exception is when new OS releases break stuff, and our hand is forced (Xbox/XInput support).

I assume your concern is the ability of stable Mumble/Murmur packages with SRV support ASAP? :-)

Thanks for asking...

**Comment by Omicron16** [comment]
Yes, the stable 1.2.X branches. The only reason I ask here is that few to no people trust privately compiled and released versions if I were to attempt adding in my own SRV record support, and that most would only use official binaries.

I'd attempt creating my own patch and adding it in, but my unfamiliarity with Mumble's code, SRV record handling, the APIs used, and my limited time makes this task neigh impossible.

**Comment by Omicron16** [comment]
#1306
#1242
