### ISSUE TITLE
Mumble Client connects via IPv4, but IPv6 has lower Ping

### ISSUE THREAD

**Issue by jounathaen** [mumble-voip/mumble#2714]
Hey, 
I'm running a Mumble Server in my LAN, which is also acessible via Internet on IPv6.
As I'm not having a native IPv4 Addres for my LAN, i'm having a Portforwarding VPS in a Computing Center.
Long Story Short: IPv6 has lower Ping because it does not has to be forwarded.
(IPv6 Ping is about 2ms, IPv4 Ping is about 40ms)

When I add the Server via the IPv6 Address directly, I get 2ms ping shown in the Server connection window.
When I add the Server via DNS (A and AAAA Record) I get 40ms ping shown. 

**Does Mumble prefer IPv4, even through it has the higher Ping? Or is it just the Connection Page, showing the IPv4 Ping and it does connect via IPv6?**

Best Regards!
Jounathaen

_Using Mumble 1.2.18, Windows. But I think, I'll remember that it is the same behaviour on Linux_

**Comment by mkrautz** [comment]
When connecting to a server, we use Qt's resolver, and whichever strategies it employs.

When we we ping, we resolve via QDnsLookup.

The DNS results, and the ping times, from the ConnectDialog aren't used when connecting to a server.

When we land SRV support, we'll unify the resolver situation in Mumble, and probably fix this issue.

If there'sa v4 and a v6 address with equivalent priority/weight, it'd make sense to pick the one with the lowest ping time.
