### ISSUE TITLE
Mumble overlay works for all programs except eve.

### ISSUE THREAD

**Issue by shutupandshave** [mumble-voip/mumble#2720]
I'm using the 64 bit snapshot and it appears to be working in skype and or other programs but I cant get it working for eve.

**Comment by shutupandshave** [comment]
Ran it in admin mode and that fixed it

**Comment by mkrautz** [comment]
Do you run EVE in admin mode?

If so, you'd need to run Mumble in admin mode too, for it to see the overlay's pipe (etc.)

If not, then I'd consider this a bug.

**Comment by shutupandshave** [comment]
yes I do
