### ISSUE TITLE
(Being able to) Increase speech encryption

### ISSUE THREAD

**Issue by karstengit** [mumble-voip/mumble#2722]
Hello developers,

i want to ask if it is possible to increase the speech encryption?
AES256 would be much more secure than AES128.
The optimum would be to get AES512.

Is this possible?

I tried the following setting, but speech is still AES128
sslCiphers=EECDH+AESGCM:AES256-SHA

Thanks a lot for mumble and murmur!

**Comment by Omicron16** [comment]
Apparently the encryption for AES128 is hardcoded in there as they were balancing between best speed and security. The sslCiphers (to my knowledge) only affect OpenSSL's TLS negotiation for the TCP "main" connection of Mumble, and do not affect UDP voice packets.

If you disable UDP to the server and the clients fall back to TCP mode only, then voice would be encrypted via whatever stream cipher you have and not AES128 (not that this is really anymore secure.)

I'd like for AES256 to be supported too, but I doubt they would consider giving us the option as the gains are likely minimal for security.

**Comment by bendem** [comment]
@karstengit 
> AES256 would be much more secure than AES128.
> The optimum would be to get AES512.

I'd love it if you could explain why or link to what you read that gave you that impression.

**Comment by karstengit** [comment]
Just use a search engine. ;-)
http://www.newyorker.com/tech/elements/how-the-n-s-a-cracked-the-web

> Thomas Drake, an N.S.A. whistleblower who was profiled by Jane Mayer in the magazine, said over the phone that he believes the 2010 breakthrough was possibly more dramatic and may refer to the defeat of “some of the main-line encryption” algorithms in wide use, like the R.S.A. algorithm or the Advanced Encryption Standard at 256-bit level. (The length of the key used to encrypt and decrypt information, measured in bits, is one of many aspects of what determines how hard an encryption scheme is to crack: 128-bit encryption is now relatively easy; 2048-bit is much harder.)

Your link leaks the base how the "security" to crack a key is calculated.

> it takes with a 128 bit key 500 years to break a ciphertext and 1000000000 years with a 256 bit on

500 years calculating with what type of processor?
What's about the cluster used by the NSA?

But that's not the point. I don't want to discuss how man years it will need exactly.
**The main point is the difference of time it will need from 128 bit to 256 bit!**

The other thing is that it cost not really more computation time to use a 256 or 512 Bit cypher.
When i make a benchmark with the LUKS kernel encryption i can measure for
**AES-XTS  512 Bit more than 980 MiB/s for encryption and decryption**
So why i should save up with the encryption?
Are you payed by the NSA to write such things?

So please - **I want to use more than 128 Bit** - will you help me and answer my question?

**Comment by karstengit** [comment]
Hello Omicron16,

> Apparently the encryption for AES128 is hardcoded in there as they were balancing between best speed and security. The sslCiphers (to my knowledge) only affect OpenSSL's TLS negotiation for the TCP "main" connection of Mumble, and do not affect UDP voice packets.

Where is the encryption hardcoded in the source?
Maybe i can alter the cipher for my needs and compile the server and clients for the needs of me and the other people that want to talk secure.
At this time i would go to AES 256 Bit.

> If you disable UDP to the server and the clients fall back to TCP mode only, then voice would be encrypted via whatever stream cipher you have and not AES128 (not that this is really anymore secure.)

This would be a good quick alternative now.
How can i disable UDP?

**Comment by mkrautz** [comment]
@karstengit 

You can change the values at https://github.com/mumble-voip/mumble/blob/master/src/CryptState.cpp#L33-L49 and https://github.com/mumble-voip/mumble/blob/master/src/CryptState.h#L17

You'd need to change the key size to be 256 bits. Right now, it's AES_BLOCK_SIZE, 16. So you'd set it to 32.

You'd also need to change the calls to `memcpy`, `RAND_bytes`,`AES_set_encrypt_key` and `AES_set_encrypt_key`, as well as change the hard-coded `128` in the calls to `AES_set_encrypt_key` and `AES_set_decrypt_key`.

You'd also need to fix the key size at
https://github.com/mumble-voip/mumble/blob/master/src/murmur/Messages.cpp#L203

and at https://github.com/mumble-voip/mumble/blob/master/src/mumble/Messages.cpp#L721-L722

...This is not exhaustive, BTW. But I believe that should do it.

If you're interested, I'd be happy to accept patches that clean up the expectation that the keys are 128-bit with a preprocessor define (AES_KEY_SIZE_BYTES and AES_KEY_SIZE_BITS?).

Thanks.

**Comment by bendem** [comment]
@karstengit you might want to read crypto news instead of world news, they are generally much more accurate. The statement you provided concerns RSA keys, not AES keys. AES keys are 128, 192 and 256 bits, AES-512 is not a thing.

While I do agree that being able to choose the key size is a good thing, I think you are asking it for the wrong reasons, mislead by news (dated from 2013) that you didn't fully understand.

**Comment by lol768** [comment]
>The optimum would be to get AES512.

[kek](http://csrc.nist.gov/publications/fips/fips197/fips-197.pdf)

**Comment by karstengit** [comment]
Sorry for my late answer - the email notification of github seems only work sometimes.

Thank you for the links of the documents.
But i can't rely on it - specially when the source is .gov.
I only believe the reports i have manipulated by myself to trust the things.

Please - i don't want to discuss here why it is senseless in your eyes to use AES 256 for speech encryption.
I only want to know how i can implement it!?
Can you help me please?

**Comment by mkrautz** [comment]
@karstengit I already answered your question about an implementation. See https://github.com/mumble-voip/mumble/issues/2722#issuecomment-271251838.

**Comment by karstengit** [comment]
@mkrautz Oh - sorry - i didn't see this.
Thank you - i will try to change this and will see if it works.

When it's working i will give my feedback here.

**Comment by karstengit** [comment]
> You'd need to change the key size to be 256 bits. Right now, it's AES_BLOCK_SIZE, 16. So you'd set it to 32.

Sorry for my late answer, but i could test it today.

O.K. It was easy to alter the key size from 128 to 256.
It compiles and runs, but has no effect.

But i could find nowhere the define of the AES_BLOCK_SIZE ?
I grepped for it in the complete source tree and it is nowhere.

I could find it here:
```
/usr/include/openssl/aes.h
# define AES_BLOCK_SIZE 16
```

So i added in CryptState.h to overwrite the default value:
```
#include <openssl/aes.h>
# define AES_BLOCK_SIZE 32

```

This compiles, murmur started, but the client dies opening a connection with
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```


> You'd also need to change the calls to memcpy, RAND_bytes,AES_set_encrypt_key and AES_set_encrypt_key, as well as change the hard-coded 128 in the calls to AES_set_encrypt_key and AES_set_decrypt_key.

Sorry - i don't understand the meaning here.
Everything seems to be defined on the base of AES_BLOCK_SIZE, so what must be changed?

```
void CryptState::genKey() {
	RAND_bytes(raw_key, AES_BLOCK_SIZE);
	RAND_bytes(encrypt_iv, AES_BLOCK_SIZE);
	RAND_bytes(decrypt_iv, AES_BLOCK_SIZE);
	AES_set_encrypt_key(raw_key, 256, &encrypt_key);
	AES_set_decrypt_key(raw_key, 256, &decrypt_key);
	bInit = true;
}

void CryptState::setKey(const unsigned char *rkey, const unsigned char *eiv, const unsigned char *div) {
	memcpy(raw_key, rkey, AES_BLOCK_SIZE);
	memcpy(encrypt_iv, eiv, AES_BLOCK_SIZE);
	memcpy(decrypt_iv, div, AES_BLOCK_SIZE);
	AES_set_encrypt_key(raw_key, 256, &encrypt_key);
	AES_set_decrypt_key(raw_key, 256, &decrypt_key);
	bInit = true;
}

```

> You'd also need to fix the key size at
> https://github.com/mumble-voip/mumble/blob/master/src/murmur/Messages.cpp#L203
> and at https://github.com/mumble-voip/mumble/blob/master/src/mumble/Messages.cpp#L721-L722
> 
> ...This is not exhaustive, BTW. But I believe that should do it.
> 

Sorry - here it is the same.
I don't really understand what's happening here, but i can see again only a dependence on AES_BLOCK_SIZE.

> If you're interested, I'd be happy to accept patches that clean up the expectation that the keys are 128-bit with a preprocessor define (AES_KEY_SIZE_BYTES and AES_KEY_SIZE_BITS?).

I would do it, but i am only a novice C programmer as you can see.

I tried to understand the functions AES_set_encrypt_key and AES_set_decrypt_key, but i could not find the description of it.
I only could find https://www.openssl.org/docs/man1.0.2/ssl/ssl.html

**Comment by mkrautz** [comment]
https://github.com/mumble-voip/mumble/pull/2741

**Comment by mkrautz** [comment]
We've landed some better constants in the code that allows users to bump the AES key size to 256 bits if they so desire.

Better support for other algorithms will have to come in an update to the protocol.

Closing this, since I believe the reporter's problem was solved as good as we possibly can at the moment.
