### ISSUE TITLE
[FR] Tray Icon

### ISSUE THREAD

**Issue by Daebis** [mumble-voip/mumble#2725]
Bonjour, j'utilise Lubuntu 16.04x64 avec Mumble 1.3.0~1820~g4d3d4d8~snapshot-1
l’icône s'affiche bien dans la barre de menu 
le clic gauche active le menu
le clic droit active lxpanel-menu
clic milieu déplace l'icone

mais pas d'option pour afficher la fenêtre principale de mumble

- - -
The icon appears in the menu bar
The left click activates the menu
Right click active lxpanel-menu
Middle click moves icon

But no option to display mumble's main window

**Comment by Krzmbrzl** [comment]
Can't reproduce this on my Linux machine. Are you still experiencing this with Mumble 1.3?
