### ISSUE TITLE
setOpusEnabled=YES no send sound

### ISSUE THREAD

**Issue by evangelist88** [mumble-voip/mumble#2730]
Hi all,

I have an issue with opus codec.
I set the Audio Settings with these parameters:

       [[MKVersion sharedVersion] setOpusEnabled:YES];        
        _audio = [MKAudio sharedAudio];
        MKAudioSettings settngs;
        settngs.transmitType = MKTransmitTypeVAD;
        settngs.codec = MKCodecFormatOpus;
        settngs.quality = 24000;
        settngs.audioPerPacket = 10;
        settngs.noiseSuppression = -42;
        settngs.amplification = 20.0f;
        settngs.jitterBufferSize = 0;
        settngs.volume = 1.0f;
        settngs.outputDelay = 0;
        settngs.enablePreprocessor = YES;

if I set [[MKVersion sharedVersion] setOpusEnabled:YES];  my device doesn't send any sound instead if I set [[MKVersion sharedVersion] setOpusEnabled:NO]; my device sends the voice correctly.

Someone can help me?

Thanks a lot

**Comment by Kissaki** [comment]
I’m not sure what this is talking about.
What kind of settings are these?

**Comment by mkrautz** [comment]
@Kissaki MumbleKit. He moved the issue to the MumbleKit repo.
I'll close this.
