### ISSUE TITLE
Mumble  volume to corrent user 

### ISSUE THREAD

**Issue by adamexus** [mumble-voip/mumble#2731]
Hello,  admin. I rly Like Mumble! Plz add function to change volume any to any selected users in  room , like it released in team speak 3.

**Comment by mkrautz** [comment]
Hi @adamexus.

This is already implemented in Mumble 1.3.0, which is available in a developer snapshot on the front page of our website: https://www.mumble.info.

We hope to mark 1.3.0 stable as soon as we can. Thanks!
