### ISSUE TITLE
Flag icon for Aland Islands missing in server browser

### ISSUE THREAD

**Issue by Nuc1eoN** [mumble-voip/mumble#2732]
As you see the flag icon is missing:
![mumblealand](https://cloud.githubusercontent.com/assets/2538022/22004123/80b5786a-dc59-11e6-84ca-5f0da4609cc7.PNG)

Corresponding console error:
`Cannot open file ':/flags/ax.svg', because: No such file or directory`

EDIT: Guess you need this? -> https://github.com/Ranks/emojione/blob/master/assets/svg/1f1e6-1f1f2.svg
However I only find round flag emojis from EmojiOne!? The current mumble v1.3 however uses more square ones (see screencapture above), even though you claim to use EmojiOne SVGs... Hm

**Comment by mkrautz** [comment]
Emojione must have changed the shape of their icons. That's also why Åland Islands is missing - it wasn't there when we synced.

I think there are two issues to solve here:

- For regions we don't have a flag for, maybe we should use the default globe.
- Re-sync icons with EmojiOne, using https://github.com/mumble-voip/mumble/blob/master/scripts/extract-emojione-flags.py

**Comment by Nuc1eoN** [comment]
Hm yeah I see. I don't know how you feel about it but to be honest I am not really a fan of those new round flags.

However I have found really nice SVG flags (in a more classic square format) from a different author, and I consider them really really nice, just take a look: http://flag-icon-css.lip.is :)
The icons are located here https://github.com/lipis/flag-icon-css/tree/master/flags/4x3 ;)

So maybe just take a look, but IMO they look kinda better suited for mumble :)

**Comment by Kissaki** [comment]
The flags were changed in emojione from rectangles with rounded corners to circles in the commit https://github.com/Ranks/emojione/commit/3f955e4ea1bb60c906bdb54c6895aeb0592549a0 for version 2.0.0.

The last version before that is [v1.5.2](https://github.com/Ranks/emojione/tree/v1.5.2), which does not have the AX flag (the flag in question for Aland Islands). AX was introduced in 2.0.0 (`1f1e6-1f1fd.svg`).

Version 2.2.0 introduced single-character icons (sadly without a reason why in the commit) https://github.com/Ranks/emojione/commit/9de19bb2ba939dc330a5603b19987d156183f4a9, so our script will have to be adjusted to ignore those. ISO 3166 country codes are all two-letter codes.

**Comment by Kissaki** [comment]
Round flags don't look that bad. Before and after:

![2017-01-30 16_47_38-mumble server connect](https://cloud.githubusercontent.com/assets/93181/22431729/ddae9786-e712-11e6-82db-7f9760a4cd9f.png) ![2017-01-30 17_37_35-mumble server connect](https://cloud.githubusercontent.com/assets/93181/22431732/ded501a4-e712-11e6-822a-3f49f5272ab0.png)

I think I would actually prefer the right ones. Maybe there are better rectangle ones available though, with clearer colours and less/no rounded edges. That would be a different library then and not emojione.

**Comment by mkrautz** [comment]
I'm OK with the new Emojione flags. Fits with the globe icon...

**Comment by Nuc1eoN** [comment]
Yeah, doesn't look bad at all:)

**Comment by Kissaki** [comment]
Potential alternatives for flag icons (non-circle)

* https://github.com/lipis/flag-icon-css/tree/master/flags/4x3
* https://github.com/hjnilsson/country-flags/tree/master/svg

**Comment by Nuc1eoN** [comment]
> Potential alternatives for flag icons (non-circle)
>   - https://github.com/lipis/flag-icon-css/tree/master/flags/4x3
>   - https://github.com/hjnilsson/country-flags/tree/master/svg

The main difference here seems that the lipis icons go for one aspect ration ([4:3](https://github.com/lipis/flag-icon-css/tree/master/flags/4x3) or [1:1 square](https://github.com/lipis/flag-icon-css/tree/master/flags/1x1)), while the hjnilsson icons seem to kepp the original ratio of the country flags.
