### ISSUE TITLE
Audio Wizard (Positional Audio): Yellow text unreadable

### ISSUE THREAD

**Issue by Nuc1eoN** [mumble-voip/mumble#2735]
When doing the Audio Wizard there is some yellow text that is simply unreadable:
![mumbleyellow](https://cloud.githubusercontent.com/assets/2538022/22023289/d9e3356e-dcc5-11e6-97d0-853019f1425a.PNG)

I suggest to maybe change the color to blue, to make it more readable.

Also I am not really a fan of the animation, since the colors inside the circles are pretty difficult to perceive (didn't even notice them at first). Well and also it's just not very sexy. But that's a different issue I guess^^

**Comment by mkrautz** [comment]
Agreed, these icons need a touchup.

They weren't always this "ugly", with the big borders and aliasing, etc.

**Comment by Nuc1eoN** [comment]
Yeah but also the yellow text^^

**Comment by mkrautz** [comment]
This is how it used to look.

Not any better, but it didn't have the large borders and so on:

![image](https://cloud.githubusercontent.com/assets/36527/22182147/231ab2c6-e09e-11e6-85eb-65bba2b477f0.png)

**Comment by Nuc1eoN** [comment]
Hey thanks for the commit:)
Could you upload a screenshot of how this page looks after your commit? Thanks

**Comment by dennisschagt** [comment]
@Nuc1eoN: I just build mumble from source at commit 525f7fdb and took a screenshot (on linux with i3 window manager):

![image](https://cloud.githubusercontent.com/assets/4629607/24312399/b175dc70-10d8-11e7-84d3-a940c61e853c.png)

**Comment by Nuc1eoN** [comment]
thanks, that's much better!

**Comment by Nuc1eoN** [comment]
This is still not in the latest snapshot.. Any progress?
