### ISSUE TITLE
Push-to-Mute hotkey should indicate when it is active

### ISSUE THREAD

**Issue by Nuc1eoN** [mumble-voip/mumble#2736]
I tried to use the "Push-to-Mute" function implemented in mumble and assigned it the hotkey 'K':
![mumble-pushmute](https://cloud.githubusercontent.com/assets/2538022/22025846/4b418cb6-dccf-11e6-9388-dc83cfd9b5a5.PNG)

As you see I use 'F2' to toggle muting and it works just fine.
As a second function I want to be muted _while_ I'm pressing 'K', and this doesn't appear to work at all :/

I use voice activation btw.

**Comment by mkrautz** [comment]
That's not how push-to-mute works. It doesn't really mute you (server-side), it just inhibits audio from transmitting.

For example, if you're transmitting with voice activity, and hold K, you won't transmit while holding K.

Think of it as a "cough button".

Makes sense? (Except, for the name, maybe.)

**Comment by Nuc1eoN** [comment]
Hm yes indeed you are right. When I press my push-to-mute key it really does not transmit any audio.

I was expecting the tray button to change during that time, like it was the case in ts3 (which I used previously). However in ts3 instead of configuring a push-to-mute hotkey, it was needed to create a hotkey in this style:
* push 'K' -> mute.self
* release 'K' -> unmute.self

This was actually inferior since if you have previously muted yourself and pressed the hotkey, it would unmute your mic on release.
But yeah in this (ts3) case the tray button would indicate a mute.

So maybe it would be a could idea to actually indicate the user the 'cough'. I mean maybe the icon should change it's state, like getting a small indicator or change it's color?
It's just an idea, however otherwise users will wonder if their push-to-mute key actually works, since there is no indication at all really.

**Comment by mkrautz** [comment]
Hmmm, I would like to keep the feature local to the client, meaning that I would like to avoid informing the server of the state change. That means we can't really piggy-back on the existing self-mute feature.

Does that mean we need a new icon for that state? We could, but if it's just a color variant, then ... that'd also be hard to explain...

**Comment by Nuc1eoN** [comment]
Yes I fully agree that it should stay local to the client, as it is much cleaner and does make sense.

Considering the icon, well I think that even changing the color would be enough, the user will see it and adapt. However of course, it might also be possible to create a whole new icon.

You know, when you press the push-to-mute button you really just look out for some sign in the UI that your status has somehow changed. Maybe red mic without the cross? At least before some designer comes our way and designs something better^^

**Comment by Kissaki** [comment]
Ah, I had no idea. Then it makes sense to be separate from the mute function (with an active press "Data" setting).

IMO it should strike through and grey out the lips/speech indicator. That is the most immediate voice/transmission indicator (used for PTT as well), and fitting to the server status on the right of the nick, while speech on the left (as lips).

**Comment by Piratonym** [comment]
I implemented this change client-side only (which is really just four lines in `MainWindow.cpp`), but I would need an icon for it. I tried changing one of the icons myself, but didn't succeed.

**Comment by mkrautz** [comment]
@Piratonym feel free to submit at as a PR (maybe with a "WIP:" prefix in the title, so we know it's a work-in-progress), and we can work out the details from there?
