### ISSUE TITLE
Hiding the GUI (or: rewriting tray logic)

### ISSUE THREAD

**Issue by Link-Satonaka** [mumble-voip/mumble#2737]
Linux user here. I use a tiling WM with no system tray, and no concept of "minimizing" windows.

Typically, if a program supports hide-to-tray, I can just close the window and the program will still be running, just "closed to tray". The fact that I don't have a tray doesn't actually matter: I restore the program by re-running it. Plain and simple.

Mumble, unfortunately, doesn't have a "close to tray", but rather "minimize to tray". I have two problems with this implementation:

1) Since I cannot minimize windows in my Linux WM, I cannot hide mumble's GUI.
2) Even on Windows, this is atypical behavior. "Close to tray" is conventional, "minimize to tray" is not. To be fair, I used to see one or two programs "minimize to tray" back in the days of Windows XP, but now mumble is the one outlier that still does it. It fell out of favor because it doesn't make sense: it limits functionality. For WMs that DO support minimization, "minimize to tray" forces you to sacrifice the ability to minimize- and, having your minimized window vanish is somewhat unintuitive/non-sequitor. With "Close to tray", you can still minimize the window normally if you wish, AND you can hide to tray. Having the window vanish when you close it is intuitive. Quitting the program can be done by `File>Quit`, `Rightclick TrayIcon>Quit`, or the assigned quit hotkey.

Sorry for the wall of text, just verbosely making my case that this isn't _just_ a change for my own unique use case, but rather, this is a general design considation.

That being said, if the devs are unwilling to make the above switch, I would still like a way to hide mumble on Linux. Could I get a `--headless` commandline switch? This approach is generally less effective because I imagine there will be no way to invoke the GUI if it has been started headless....

If you do implement "close to tray", an option / commandline switch to "start hidden" would be nice, too :)

Thanks!

**Comment by mkrautz** [comment]
> [...] Even on Windows, this is atypical behavior. [...]

It's off by default on Windows 7+ because of the "new" task bar.

**Comment by mkrautz** [comment]
> Since I cannot minimize windows in my Linux WM, I cannot hide mumble's GUI.

As a workaround, couldn't you use the "Ask on quit while connected" feature to minimize Mumble?
Basically, Mumble will ask you if you wish to minimize it, instead of quitting, when that option is enabled.

**Comment by Link-Satonaka** [comment]
I did try that, and nothing happens because my WM does not have any concept of "minimizing".

**Comment by Link-Satonaka** [comment]
Do you still require more input? I'm not sure what you need to know.

**Comment by Piratonym** [comment]
I implemented a "Hide Mumble" option in the menu in my fork on branch [feature-hide-from-menu](https://github.com/Piratonym/mumble/tree/feature-hide-from-menu). It seems fairly simple and works for me (using Awesome on Linux). But since I don't know much about Qt and the current code used to hide Mumble is a bit more complex, I would appreciate comments and testing from @Link-Satonaka and those who are more familiar with the UI code.

If the code is acceptable (or required changes can be implemented), I can complete the menu entry stub and create a pull request. The "Minimize" option in the closing dialogue should probably be changed to "Hide" as well in this case.

Also, Mumble already becomes visible again when a new instance is started (without the --multiple flag).

**Comment by Link-Satonaka** [comment]
Building your branch fails for me with

```
AudioInput.cpp: In member function ‘int AudioInput::encodeCELTFrame(short int*, AudioInput::EncodingOutputBuffer&)’:
AudioInput.cpp:690:69: error: ‘CELT_SET_VBR_RATE’ was not declared in this scope
  cCodec->celt_encoder_ctl(ceEncoder, CELT_SET_VBR_RATE(iAudioQuality));
                                                                     ^
make[2]: *** [Makefile.Release:2816: release/AudioInput.o] Error 1
make[2]: Leaving directory '/home/Link/mumble/src/mumble'
make[1]: *** [Makefile:38: release] Error 2
make[1]: Leaving directory '/home/Link/mumble/src/mumble'
make: *** [Makefile:135: sub-src-mumble-make_first-ordered] Error 2
```

**Comment by mkrautz** [comment]
@Link-Satonaka You don't seem to have the correct CELT dependencies installed. You can use Mumble's bundled copies via CONFIG+=bundled-celt.

**Comment by Link-Satonaka** [comment]
I was able to test it- it does indeed work.

**Comment by mkrautz** [comment]
@Piratonym I am also ok with the changes made in your branch (with my comments taken care of). Feel free to submit a PR once ready. Please squash your changes into a single commit, since the change is pretty self-contained.

**Comment by gerroon** [comment]
Hi

Is this implemented with the current release? I cant tell, but I do not see such option :(

**Comment by Krzmbrzl** [comment]
#2747 has been merged. Thus it is contained in the 1.3 release.

The option should be in the server drop down menu.

**Comment by gerroon** [comment]
Thanks for the reply.

**Comment by Krzmbrzl** [comment]
You're welcome :)
