### ISSUE TITLE
Overlay interferes with Windows Photo Viewer (Win7)

### ISSUE THREAD

**Issue by Nuc1eoN** [mumble-voip/mumble#2738]
I have noticed that the mumble overlay interferes with the Windows Photo Viewer on on win7.
![mumbleoverlay](https://cloud.githubusercontent.com/assets/2538022/22044138/6221ffd0-dd13-11e6-8cff-20c714c9eba5.PNG)

Moreover it does not seem to work very well. The overlay does not seem to update. Often images will fail to load and after some time passes it will crash:
![mumbleoverlaycrash](https://cloud.githubusercontent.com/assets/2538022/22044288/31c8a81a-dd14-11e6-869b-108b113d9b58.PNG)
(sry for the chat log lol^^)
Dunno if it is needed but here is some info I gathered about the crash from Nirsoft's WhatIsHang: https://bpaste.net/show/b972cce237c9

**Comment by mkrautz** [comment]
The overlay is too eagerly injecting into things it shouldn't.

See https://github.com/mumble-voip/mumble/pull/2371 for a solution.

**Comment by Nuc1eoN** [comment]
Yeah I see the problem is kinda tricky.
Maybe for a start you could simply add the Windows Photo Viewer application to the blacklist.

Or do you consider taking other steps?

**Comment by mkrautz** [comment]
Sure thing, could you please add the .exe name to https://github.com/mumble-voip/mumble/issues/2422? Thanks.
