### ISSUE TITLE
Mumble forces logitech gaming software to create a profile

### ISSUE THREAD

**Issue by jammet** [mumble-voip/mumble#2739]
If you are a user of Logitech gaming hardware, like mice and keyboards, you will come across the problem that the logitech gaming software for some reason creates a profile just for mumble. There is no way that we've found, to force it to ignore mumble. We require the logitech software to keep profiles for mice and keyboards, as they're programmable through that software. But we want the software to recognise the *games* on launch. 

Please include the ability or option in mumble to not have Logitech Gaming Software see it. So that the game profiles are loaded and applied, only.

**Comment by mkrautz** [comment]
The reason is that Mumble 1.3.x has GKey support.

You think it should be opt-in?

**Comment by jammet** [comment]
I believe that this to be optional would help, yes. 

I do use the GKeys myself, and so far I've just ignored the mumble profile more or less, by trying to have it be a copy of the default profile. So nothing changes, but then I have to load profiles for games manually a lot, so they're used properly, and keep being used even when I alt-tab a lot. When you alt-tab and Mumble is pulled to the front, a lot of the times the mumble profile gets activated, but once I switch back to the game, the games profile isn't made active, right after that. Happens a quite a lot ;(. Then I have to go into Logitechs software and set them to be "persistant", and uncheck persistance once finished playing. 

I realise it's probably Logitechs software being problematic, but it would help if Mumble wouldn't have it's own profile, causing the mixup.

One of my coop partners says that he uses both keyboard and mouse, and this somehow prevents him from having a profile for each, so they're treated separately. That's probably a Logitech issue as well, I'm not sure.

**Comment by Nuc1eoN** [comment]
I don't understand, aren't you able to deactivate the mumble plugin like this:

![mumblelogi](https://cloud.githubusercontent.com/assets/2538022/22134027/60b94312-dec4-11e6-95e8-e5513ea838d4.PNG)

**Comment by Kissaki** [comment]
After removal (your second example), will it be automatically added again? (It being automatically added the first time around, that is what I would expect.)

**Comment by jammet** [comment]
Thank you for the screenshots. On the first one, "Applets" Mumble doesn't show on my end. 

As for Loeschen/Deletion of the profile? Yes this was one of the things I've already tried. The Gaming software re-creates it. I actually have two mumble profiles in there now (I modified one, when experimenting), but removing them will only remove Mumble until you start Mumble once again. It'll be detected again. 

![untitled](https://cloud.githubusercontent.com/assets/11940735/22145147/711788f4-df00-11e6-9a35-d1a9e5b4ca98.png)

**Comment by Nuc1eoN** [comment]
Hm, not really sure why one would need a special mumble profile for mouse/keyboard keys in the first place.

However it certainly makes sense as an applet on my G15 LCD display ;)

**Comment by Tarun80** [comment]
I believe it should be opt-in as well. Even if you remove it, it re-adds. I've had this interfere with talking due to profile switching when gaming, so if I have alt tabbed out of game, then when I go back in it cuts me off mid sentence. (That is, from Game profile -> Mumble profile -> going back in game goes back to Game profile)

I don't see a point in the Mumble profile in the LGS since it also adds/has an applet usually too.

**Comment by mkrautz** [comment]
Now, this isn't something we're doing on purpose.

The only we seemingly can avoid this behavior is to disable the GKey support in Mumble by default.

We really don't do anything special:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/GKey.cpp

**Comment by mkrautz** [comment]
cc @forivallforivall

**Comment by forivall** [comment]
Yup, we could some setting to enable the specific g-key support.

The use case is that this allows keys to be directly bound to an action in mumble, rather than having the g-key map to a different key, which is then bound in mumble.

**Comment by mkrautz** [comment]
@forivall Do you think it's an OK compromise to disable GKey support by default - to make it opt-in in the Shortcut settings pane?

Off-topic, @forivall:
Are you OK with us removing your long-form BSD license from GKey.cpp/GKey.h in favor of the new short-form one (If you look in the tree now, both are present)? You're still listed in AUTHORS, of course. And we can't remove the long-form license without your permission. :-)

**Comment by forivall** [comment]
Yes, I give my permission to remove the long form BSD Licesnse

**Comment by mkrautz** [comment]
Excellent, thanks.

**Comment by forivall** [comment]
> Do you think it's an OK compromise to disable GKey support by default - to make it opt-in in the Shortcut settings pane?
Yup, 100% Ok with that.

**Comment by dekeonus** [comment]
As a workaround:
Exit mumble if running
Browse to the mumble install directory. Copy mumble.exe to mumble_dummy.exe^
In the LGS software modify (R-Click select properties) the mumble profile.
  Remove mumble.exe (highlight and click [-])
  Add mumble_dummy.exe (click [+] and 'choose application'; browse to folder with, and select mumble_dummy.exe; click ok to save profile) 
Browse to the mumble install directory. Delete mumble_dummy.exe

This works here using a g13 and the 64bit drivers / application. Mumble does not recreate the profile and with the only target application non-existent, does not autoload the mumble proflie

^LGS does not seem like saving the mumble profile with no application set.

**Comment by mkrautz** [comment]
The other workaround would be to disable GKey support.

You can use the .reg files attached.

[gkey-regs.zip](https://github.com/mumble-voip/mumble/files/752884/gkey-regs.zip)
