### ISSUE TITLE
Invalid reference URL for workaround

### ISSUE THREAD

**Issue by Piratonym** [mumble-voip/mumble#2743]
Commit 694dca851 introduced a workaround to (apparently) a tray minimization and hide/show problem, in response to issue #1336. It added a reference to a post in the QT forum as comment: [MainWindow.cpp:474](https://github.com/mumble-voip/mumble/blob/694dca851b47e33b7bf09fdcd0b4ee583b934206/src/mumble/MainWindow.cpp#L474). Unfortunately, this URL now redirects to the start page of a new forum. Also, the Internet Archive Wayback Machine does not have any copies of the post due to the site's robots.txt.

Does anyone still know (or could find out) what this workaround was about and could replace the comment with a short explanation?

**Comment by Piratonym** [comment]
FYI, I found this while looking at the tray minimization code for issue #2737, and found it particularly interesting as – at least on my system (Linux) – commenting this line does not seem to have any effect on (de-)minimization, even though it usually is called when minimizing or restoring the window.

**Comment by Kissaki** [comment]
@hacst Your commit, maybe you still know something? 😃

**Comment by Kissaki** [comment]
Commit 694dca851b47e33b7bf09fdcd0b4ee583b934206 is a followup to 7c4fbee2248248003e14a27f6b2e59ad4603b104

**Comment by Krzmbrzl** [comment]
Linking this issue to #3977 as it might be relevant

Btw. I think the correct URL would be https://forum.qt.io/post/99813 as this seems to be the only  place in which `QTimer::singleShot` is being used in that thread.
