### ISSUE TITLE
Huge FPS drop in Overwatch when using overlay

### ISSUE THREAD

**Issue by PathosEthosLogos** [mumble-voip/mumble#2750]
I haven't tested in other games, but my FPS drops to double digits, as low as 15FPS.  Overlays from other programs doesn't behave like this at all. A buddy of mine is complaining about the same issue. If this is a known issue, I apologize.

**Comment by mkrautz** [comment]
Hi, I've just tested this myself and I get the same FPS when I have the overlay on vs. when I do not.

Which version of Mumble are you using? Is it 32-bit or 64-bit?

**Comment by PathosEthosLogos** [comment]
64-bit, Windows 8.1
i5 2550k
Radeon HD 7870
LMK if you need more info!

**Comment by mkrautz** [comment]
Thanks for that...

I'd also like to know:

Which version of Mumble are you using? Is it 32-bit or 64-bit?

Are you using a fully updated Windows 8.1 and the latest AMD Crimson driver?

**Comment by mkrautz** [comment]
Hi, I've just had @ngollan test this on an AMD card (thanks!), and he found no issues either.

He tested the training level, with the following specs:
Mumble 1.3, Win10, RX480 with 16.12.2 drivers

Maybe it's a Windows 7 thing?...

@PathosEthosLogos can you elaborate on when you see the framedrops? Is it only when your system is burdened? Or is it a permanent reduction in performance?

**Comment by Kissaki** [comment]
I tried as well, had no change in framerate at all playing around in the training area.

Closing this as no further input was provided.
