### ISSUE TITLE
Wiki: Third Party Applications

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2766]
On the front page of the wiki we have "Third Party Clients", which lists third party Mumble clients.

We also have a page for third party software in general: https://wiki.mumble.info/wiki/3rd_Party_Applications

That page doesn't list clients.

I suggest we do the following:
 - [x] Add clients to https://wiki.mumble.info/wiki/3rd_Party_Applications
 - [x] Rename "Third Party Clients" to "Third Party Applications" on the front page.
  - [x] Add sub-heading for "Clients" to the renamed "Third Party Applications" section.
- [x] Also, add a link to "Other third party software" which links to https://wiki.mumble.info/wiki/3rd_Party_Applications.

**Comment by Kissaki** [comment]
Most changes were already done. I adjusted the home page to say "clients" for the clients, and give a short introductory description (useful especially as its the frontpage).

Full-width text looks pretty bad IMO. Maybe it should be split horizontally into left for clients and right for other, or we should use manual line breaks (for lack of being able to specify max content width within the table cell).

I also thought about dropping the headlines and instead letting the text speak, but I think the headlines make it, their distinguishability and their discoverability better.

@mkrautz what do you think?

**Comment by mkrautz** [comment]
How about something like this?

![image](https://cloud.githubusercontent.com/assets/36527/23682377/c4c32a32-0393-11e7-9b2b-13a3ec709557.png)

Sorry, I only edited it live. Here are my changes:

- Clients -> Alternative Clients
- Add 30px left padding to the elements, to match the downloads table.
- Swap Name <-> OS in the table.
- Set min-width on the table to 450px to add some air.
- Drop bold client names.
- Drop bold text in "Other Third Party Software"
- Rename Resources -> Links.

(Maybe I forgot something?)

WDYT?

**Comment by Kissaki** [comment]
I put OS first thinking users may mostly be interested in finding clients for different/a specific OS. But maybe that's worse.

LGTM. I made the changes.

I was a little surprised the main page is no longer cached so no hassle waiting for changes to become visible. Makes sense with a CDN ofc, that we no longer need a static-page-cache. :)

**Comment by mkrautz** [comment]
LGTM. Closing :-)
