### ISSUE TITLE
GlobalShortcut suppress function not available Linux/X11

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#2773]
There is no key supress function in Linux, will this be soon put in? It really screws up workflow when you've binded your talk key to your third mouse button. Thanks. :)

**Comment by mkrautz** [comment]
Xorg deprecated the XEvie extension, which we were using for key suppression on X11.
If you can enable XEvie on your system, key suppression should work just fine.
But I don't believe that is possible on modern systems.

We don't currently know of an effective way to suppress keys. Perhaps it can be done with XInput2?

**Comment by nbv0800** [comment]
Very quick reply thank you! I've tried fucking around with xinput and had no hope, the key just stopped working. Maybe creating a new key for it to be assigned to?

**Comment by mkrautz** [comment]
@nbv0800 Most likely, the solution will need to be implemented inside Mumble... But perhaps it's possible to use some (external to Mumble) X magic to make a key only visible to Mumble.

**Comment by Krzmbrzl** [comment]
The suppress functionality has been dropped from most shortcut backends by now and we plan to get rid of it entirely. Therefore, I am closing this
