### ISSUE TITLE
Crashs on Windows XP 64 + Steelseries Wireless H (Headset) at USB

### ISSUE THREAD

**Issue by Avispa** [mumble-voip/mumble#2789]
To Reproduce:
- Disconnect Headset
- Start mumble
- Plugin Headset

=> Result: instant crash!

It's the same if the headset is already connect via USB during the start of Mumble. In that case Mumble creates the Window but without drawing anything to it, it crashes instantly before you can consider it started (from a users point of view.)

OS: Windows XP 64 Edition
Mumble: 1.2.x (tried all of them).

Side note: Latest _Mumble 1.1x_ (shipped with Mumble 1.2.2) runs perfectly fine!

**Comment by Kissaki** [comment]
Does it ask you to send a crash report when you start it again?

**Comment by Kissaki** [comment]
Does it ask you to send a crash report when you start it again?

**Comment by mkrautz** [comment]
@Avispa Have you tried Mumble 1.3.x development snapshots? Please do if you haven't and report back if it's fixed there. Thanks!

FWIW, I have a Steelseries Wireless H available for testing, but it's not connected to my PC. I can try to reproduce if necessary, but not right now.

**Comment by felixsinger** [comment]
@mkrautz Just for notice... Why do you support Windows XP yet?

**Comment by mkrautz** [comment]
@felixsinger Our build environments fully support Windows XP, and we hope to release 1.3.0 before long.
Once that's out the door, we'll drop various legacy OSes, but for now we might as well release 1.3.0 with broad support (even though people shouldn't be running those OSes).

**Comment by mirh** [comment]
Crazily, microsoft is still supporting XP *even* in VS2017

**Comment by Avispa** [comment]
Sorry for the long time of absence. I experience the "service" of cheap ISPs atm. To clearify: no serivce, no internet, just fraud. However..

> Does it ask you to send a crash report when you start it again, after the crash?
No.

> Have you tried Mumble 1.3.x development snapshots? Please do if you haven't and report back if it's fixed there. Thanks!
Nope

By the way: it also crashes when USB is just plugged in. Why this is markable: the Steelseries Wireless H has a internal USB audio device and a classic Jack 3,5mm.

Again, the faulty code got introduced between versions 1.1.x and 1.2.2.

**Comment by mirh** [comment]
Can't you like [bisect](https://sourceforge.net/projects/mumble/files/Mumble/) a bit more the problem?

**Comment by Avispa** [comment]
As already mentioned in my first post: it is 1.1.x shipped with 1.2.2 (and yes, the version is literally named "1.1.x"). So I would suspect it to be 1.1.8 but you probably know it better than I do.

**Comment by mirh** [comment]
> it is 1.1.x shipped with 1.2.2

😭 wtf does that mean
[This](https://sourceforge.net/projects/mumble/files/Mumble/1.1.8/) work and [this](https://sourceforge.net/projects/mumble/files/Mumble/1.2.0%7Ebeta1/) doesn't work?

**Comment by mkrautz** [comment]
@mirh In early 1.2.x releases we included a client that was compatible with older 1.1 servers. It was called mumble11x.exe (Mumble 1.1.x).

**Comment by mirh** [comment]
Oh, ok. 
But for the love of me I can't understand why one should make comparison with that instead of actual "live" builds.

**Comment by mkrautz** [comment]
@Avispa When it crashes, on next launch, do you get Mumble's crash reporter? Did you submit any of the crashes? Thanks.

**Comment by Avispa** [comment]
@mkrautz Why do we start over again? **kissaki** already asked and I already answered:
> > Does it ask you to send a crash report when you start it again, after the crash?
> No.

**Comment by mkrautz** [comment]
Sorry.
