### ISSUE TITLE
latest snapshot has celt issues

### ISSUE THREAD

**Issue by Newbrict** [mumble-voip/mumble#2809]
was getting client has no compatible CELT codec error on w10.64bit, a downgrade fixed it...

**Comment by Newbrict** [comment]
I dug a little bit this is the error I was getting

https://github.com/mumble-voip/mumble/blob/59275f54d3a93e03f8e5cf447b25b9c89c419e08/src/mumble/Messages.cpp#L864

**Comment by hacst** [comment]
Pretty sure this is another side-effect of #2806 .We are working on it.

**Comment by hacst** [comment]
Should be resolved with new snapshot 1.3.0~1907~g43109d1~snapshot
