### ISSUE TITLE
Channel user limitation setting is not visible

### ISSUE THREAD

**Issue by LeoVerto** [mumble-voip/mumble#2813]
I'm running Murmur 1.2.18 on Debian Jessie and Mumble 1.2.19 on Arch Linux, yet I don't see the maximum users per channel setting implemented in  #1889.

I did some digging in the source and found [this](https://github.com/mumble-voip/mumble/blob/73fe4578bc01b0ef8e8742d7ce5d172b9b9c0f5b/src/mumble/ACLEditor.cpp#L40) line particularly interesting.

Doesn't that line disable the functionality unless a Murmur version of 1.3.0 or higher is being used? If so, why is it included in current releases if it isn't usable outside dev builds?

**Comment by mkrautz** [comment]
> If so, why is it included in current releases if it isn't usable outside dev builds?

We don't backport features to 1.2.x. It's our stable branch.

Please use a snapshot build from the 1.3.x series instead if you need that feature.

Thanks!
