### ISSUE TITLE
Ubuntu PPA 1.2.18 doesn't include updateCertificate

### ISSUE THREAD

**Issue by kiu** [mumble-voip/mumble#2814]
In june last year the functionality to update certificates via ice was added. It seems those never made it into the Ubuntu builds. Those are crucial to run mumble-server in a modern secure environment (letsencrypt, reload every 30days without kicking all users).

Any plans to include this? Or is there a more experimental ppa available?

**Comment by mkrautz** [comment]
This is only in the 1.3.x branch. You can use the snapshot PPA to access it:
https://launchpad.net/~mumble/+archive/ubuntu/snapshot

This fix won't be backported into 1.2.x.
