### ISSUE TITLE
Mumble 1.3.0~1907~g43109d1 G15 LCD applet blank

### ISSUE THREAD

**Issue by dekeonus** [mumble-voip/mumble#2815]
The `mumble-1.3.0~1907~g43109d1~snapshot.winx64` is not rendering correctly; it appears that the text does not render. While disconnected from any server the mumble logo appears but not the "Not Connected" text. Once connected the display is blank - no text is visible.

**Comment by mkrautz** [comment]
Qt fixed this bug: https://github.com/mumble-voip/mumble/issues/2429

We should fix the workaround... On it.

**Comment by mkrautz** [comment]
Fix at https://github.com/mumble-voip/mumble/pull/2816
