### ISSUE TITLE
Our CDN is deprecating TLSv1.0 and 1.1

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble#2819]
As described in https://www.fastly.com/blog/phase-two-our-tls-10-and-11-deprecation-plan our fastly CDN will only support TLSv1.2 going forward.

Unless we become active, April 30, 2017 is the date they have set for switching the shared endpoints we are using over. If we contact them we might possibly be able to use a legacy shared endpoint but from the blog it seems like June 30, 2018 is a final hard cutoff date.

Given that in Qt 4 TLSv1.2 wasn't supported yet and the vast majority of our install base is still on clients with that Qt we'll have to figure out how to handle that or they'll no longer be able to reach any of our services behind the CDN.

**Comment by C0rn3j** [comment]
You're thinking of continuous support of a Qt4 client. 

Let me paste a snippet from the Qt blog:

> Qt 4.8.7 is planned to be the last patch release of the Qt 4 series. **Standard support is available until December 2015**, after which extended support will be available.

Qt 4 has been EOL for more than a year now.

https://github.com/mumble-voip/mumble/milestone/1

There's 46 open issues that are marked as the 1.3.0 milestone.

 I'm a mere user, but I suggest sorting the issues by priority, and moving those that aren't important to 1.3.1 release, and working on those that are important so you can release 1.3.0 around April '07, which gives users about a month to update.

I'd say that releasing the 1.3.0 version that is based on current Qt5 is the priority, instead of breathing life into a release that's already EOL for over a year.


https://github.com/mumble-voip/mumble/issues/2728

**Comment by mkrautz** [comment]
No, we aren't thinking too much about Qt 4. We try to be forward looking. But we have an existing userbase who can't easily update from Qt 4 -- people using Linux distros, that want to use distro packages. Linux distros still ship Qt 4, and they provide security support for it.

**Comment by C0rn3j** [comment]
> But we have an existing userbase who can't easily update from Qt 4 -- people using Linux distros, that want to use distro packages. 

I use a linux distro and I have no issues running both Qt4 and Qt5 apps at the same time.

Even Ubuntu 16.04.1 LTS has _qt5-default/xenial-updates **5.5.1**+dfsg-16ubuntu7.2 amd64_ in the repos.

I don't see a reason to postpone the update. Ancient distros that don't update packages will have Mumble 1.2 anyways.

**Comment by mkrautz** [comment]
The problem isn't Qt.

The problem is that the Mumble version they ship is 1.2, and they won't update to another version in their stable releases.

But as I said, it's not much of a concern - there's not much we can do about that.

**Comment by C0rn3j** [comment]
>The problem is that the Mumble version they ship is 1.2, and they won't update to another version in their stable releases.

So they will update, or they won't.

What does it matter, Mumble 1.2 is EOL anyways, let distros decide if they want to update or not? Personally I'm sure all mainstream distros will update, I don't see why they wouldn't.

**Comment by mkrautz** [comment]
Mumble 1.2 is not EOL. It's our current stable release.

Also, in general, no "mainstream" distros will update Mumble until their next release.

**Comment by C0rn3j** [comment]
Sorry, I meant Qt4 is EOL and Mumble 1.2 uses that.

>Also, in general, no "mainstream" distros will update Mumble until their next release.

Even Ubuntu 14.04 has Qt 5.2. 

Given that basically all distros have the required libraries, why do you think that current distros will refuse to update Mumble?

**Comment by mkrautz** [comment]
Because distros generally don't update packages in their stable releases. They just patch them for security problems.

**Comment by mkrautz** [comment]
For example,

Debian stable is still on Mumble 1.2.8 - but we're on Mumble 1.2.19 at the moment:
https://packages.debian.org/search?keywords=mumble&searchon=names&suite=stable&section=all

Ubuntu trusty (14.04 LTS) is still on Mumble 1.2.4:
http://packages.ubuntu.com/search?keywords=mumble&searchon=names&suite=trusty&section=all

**Comment by C0rn3j** [comment]
I see the issue now, I'm too used to a rolling release distro.

Marking 1.3 as a security release(as it should be imo) and advising everyone to switch to it while keeping the legacy endpoint till 2018 seems like the most painless solution.

**Comment by funkydude** [comment]
Who the hell cares?

Sorry but you're bleeding users on a daily basis to Discord and you're sitting here worrying about Linux. You guys seriously need to refocus your priorities. The entire point of this app was gaming, the idea of Linux being a gaming platform is not something that has been realised (if ever).

I know I've complained several times on IRC about this but the length of time 1.3 is taking is becoming a joke. You're killing your own project by reducing your userbase, thus reducing the changes of someone actually contributing code.

This is speaking as someone who was planning on making contributions as a side project, but lost all interest when everyone I knew moved to Discord. How can I blame them? They complain bout things like user-specific volume adjustment. Something that has sat rotting in 1.3 without a release for what, a year.

Swap to a faster release cycle, refocus onto gamers (Windows) or risk the project collapsing under a lack of interest.

**Comment by C0rn3j** [comment]
@funkydude I'm not sure if suggesting dropping all platforms except one is ever a good idea.

>refocus onto gamers (Windows)

Also hey, I game on Linux, don't assume I use Windows, thanks!

**Comment by bendem** [comment]
I'm using mumble on both linux and mac, never windows. And btw, mumble is about communication, which you can do in many other contexts than gaming.

**Comment by funkydude** [comment]
> @funkydude I'm not sure if suggesting dropping all platforms except one is ever a good idea.

I recommend you re-read my post, you seem to have come to some weird conclusions.

>I'm using mumble on both linux and mac, never windows. And btw, mumble is about communication, which you can do in many other contexts than gaming.

That's great, but let's look at the goal of this software:

>Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.

You can sit here and tell me how you use it for other things other than gaming all you want, the majority of people will not load Mumble for casual conversations when other apps do it better.

If they are are ok with loosing their primary audience just to support EOL versions of Qt, that's their prerogative, I'm just stating the consequences of that as I see them. If the current devs ever get bored or give up, good luck keeping this project alive with this current decay in interest.

This current focus of the project is holding it back for years, my 2c.

**Comment by C0rn3j** [comment]
@funkydude I totally agree that the EOL Qt shouldn't be cared about, that users will either update Mumble to 1.3 when it gets released and that linux people will upgrade their distro versions if their distro is outdated and only supports EOL Qt/Mumble.

>I recommend you re-read my post, you seem to have come to some weird conclusions.
>>you're bleeding users on a daily basis to Discord and you're sitting here worrying about Linux
>>refocus onto gamers (Windows) 

This suggests that you want the support for Linux, macOS and other OSs dropped. Moreover, if you're not suggesting that, what is the point of your last comment?

Moreover suggesting that people don't game on other OSs than Windows is pretty ridiculous. 
Especially Valve just released beta SteamVR on Linux few hours ago.

**Comment by funkydude** [comment]
> This suggests that you want the support for Linux, macOS and other OSs dropped.

No, it really, really doesn't. Suggesting focusing on the majority of users, the primary goal of this software, and not letting the 1% hold you back does not mean going through the code and purposely purging all support for other operating systems.

> Moreover suggesting that people don't game on other OSs than Windows is pretty ridiculous.

No, it really, really isn't.
http://store.steampowered.com/hwsurvey
Total Linux users: 0.8%
This has been dropping, not escalating, every since Windows 10 was released.
It used to be nearly 2%

**Comment by Avamander** [comment]
@funkydude The survey is a joke, it only shows who got the survey and who use Steam, not who use Mumble.

Though I agree that Mumble needs faster release cycle to compete with other VoIP software. It's hard for me to recommend Mumble, when it lacks quite a few basic features.

**Comment by funkydude** [comment]
I'm would not go so far as to call it a joke. It is not perfect, but being the primary PC gaming platform, it is good enough to draw conclusions. Having Linux drop that much, especially when you consider it should rise thanks to "Steam Machines" is shocking.

The discussion is probably moot at this point anyhow, I don't see anything stopping Discord at this point.

**Comment by C0rn3j** [comment]
> it is good enough to draw conclusions.

Making conclusions from the steam HW survey OS section is not a good idea, the information there is flawed.

The survey only appears for SOME people, the survey only appears when you don't use big picture(so SteamOS is EXCLUDED from that list), and the survey appears under WINE too, skewing the results.

**Comment by dekeonus** [comment]
The murmur server still needs QT^ and I'd be willing to bet most of those are on Linux platforms.

^Thankfully it doesn't use anything that ultimately relies on Xlib et. al. or I wouldn't be able to run murmur on my server.

**Comment by davidebeatrici** [comment]
#2728
