### ISSUE TITLE
Recorder hanging on shutdown

### ISSUE THREAD

**Issue by Darkman** [mumble-voip/mumble#2827]
The recorder sometimes hangs on the stopping phase, requiring the user to close the recorder window, which also sometimes crashes all of Mumble with it.

**Comment by Kissaki** [comment]
This is about stopping an active recording, not a system shutdown, right?

**Comment by Kissaki** [comment]
You say "sometimes". How often does this occur? I guess it is not consistently reproducible?

**Comment by Darkman** [comment]
It's about stopping an active recording, and it's not consistently reproducible for me. I gave @hacst a dump, and after looking at it, he said he had an idea of what it might be.

**Comment by Darkman** [comment]
Uploaded a memory dump of the hang to mkrautz. Ping me or him to get it.

**Comment by davidebeatrici** [comment]
@mkrautz What might it be?

**Comment by Krzmbrzl** [comment]
@Darkman does the issue still occur in Mumble 1.3 and if so, could you post that dump here please?
