### ISSUE TITLE
Logitech G13 Mumble display no longer works

### ISSUE THREAD

**Issue by jonberling** [mumble-voip/mumble#2831]
Starting in version 1.3.0\~1907\~g45109d1\~snapshot my G13 mumble display just shows a blank screen when using mumble. Prior to this the display worked properly and showed a who was talking when in a given channel.

**Comment by davidebeatrici** [comment]
@mkrautz It's probably related to https://github.com/mumble-voip/mumble/pull/2816.

**Comment by mkrautz** [comment]
Yes. I tested it in our emulator, and it worked. But The bits are probably swapped.

**Comment by jonberling** [comment]
If it helps, I'm using the 64 bit snapshot, on Win10.

**Comment by Nuc1eoN** [comment]
>Starting in version 1.2.0\~1907\~g45109d1~snapshot

Guess you meant  1.**3**.0\~1907\~g45109d1~snapshot

**Comment by jonberling** [comment]
Yes, that is correct

**Comment by Tarun80** [comment]
@Nuc1eoN , @jonberling That's not actually correct. The x64 snapshot is 1.3.0~1907~g43109d1~snapshot.

**Comment by jonberling** [comment]
I just downloaded snapshot 1.3.0/~1931/~g3315e01/~snapshot (as reported by the mumble app titlebar) and the Logitech G13 mumble display is working properly.

Thank you for fixing this issue so quickly.

**Comment by mkrautz** [comment]
Ah, sorry. I was confused... The fix went in after g43109d1, so yeah... It wasn't because of a bit-swap. It was because the version didn't have my fix yet. :-)

So - it was actually fixed in the tree before this was reported, which is what confused me.

Closing.
