### ISSUE TITLE
No Mumble 1.3.0 1917 x64 build for Windows?

### ISSUE THREAD

**Issue by Tarun80** [mumble-voip/mumble#2832]
Noticed that all the other builds for 1917 have landed days ago but the Windows x64 build has not yet appeared. Check for updates says latest and the dl.mumble.info doesn't have 1917 for x64 Windows.

**Comment by savv01** [comment]
Perhaps just use the x32 version until a new snapshot is released?

**Comment by Tarun80** [comment]
@savv01 No, I'm staying on the last x64 which is 1907. Why would I switch to x86 when I'm using x64? There's no point. I posted this to find out why the x64 build has not appeared.

**Comment by mkrautz** [comment]
It didn't appear because the code-signing failed. And since there have been a few CI builds after it, the built files for that build are gone now. I'll do a new snapshot today...

**Comment by mkrautz** [comment]
It's out. :-)

**Comment by Tarun80** [comment]
Thanks @mkrautz. Was just reading #2837 and is that a showstopper issue or go ahead and update?

**Comment by mkrautz** [comment]
It works as long as you also install Murmur

**Comment by Tarun80** [comment]
Shouldn't need to install murmur. In fact, I didn't install murmur and I don't have the error that was reported in the other issue. I do have several Visual C++ runtimes (2005-2015 from games) already installed. That might be more viable than installing murmur.

**Comment by mkrautz** [comment]
No, you shouldn't - that's why it's a bug. :-)

If you have the MVSCRT 2015 runtime redist that corresponds to the arch of the Mumble snapshot you've installed, you should be good, too.
