### ISSUE TITLE
Latest Mumble Windows snapshots broken on Windows 7 (and others)

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2837]
01:02:43 <tmberg> Hm.. Latest mumble 64bit snapshot ( mumble-1.3.0~1931~g3315e01~snapshot.winx64.msi ) is causing this: https://www.starka.st/run/shm/bandwidth/tmberg/EntryPointNotFound.png and this: https://www.starka.st/run/shm/bandwidth/tmberg/Error%202.png
	01:04:26 <tmberg> The same with mumble-1.3.0~1931~g3315e01~snapshot.msi.
	01:04:37 <tmberg> Im on Win7 btw.
	01:29:27 <@mkrautz> tmberg: hmm... workaround is to also install murmur
	01:29:54 <@mkrautz> ...I think
	01:31:15 <tmberg> mkrautz: Ok. Lets test.. :)
	01:31:36 <@mkrautz> that will install a separate copy of the CRT next to mumble.exe because murmur.exe requires that :)
	01:31:40 <@mkrautz> so it "fixes" the issue...
	01:32:13 <@mkrautz> Hmmmmmmmmm
	01:32:27 <@mkrautz> I really thought it loaded the CRT from Versions? I guess it doesn't
	01:33:11 <tmberg> mkrautz: Yepp. That got it to work.

**Comment by mkrautz** [comment]
![image](https://cloud.githubusercontent.com/assets/36527/22848920/5cbbcf1a-eff8-11e6-9dd8-8ddfb0fa933e.png)

Seems like the CRT DLLs are being correctly loaded by LoadLibraryEx with LOAD_WITH_ALTERED_SEARCH_PATH as they should.

However, something is trying to load ucrtbase.dll, seemingly without LOAD_WITH_ALTERED_SEARCH_PATH?
LoadLibraryEx without LOAD_WITH_ALTERED_SEARCH_PATH will try to load the DLL from the application (exe's) directory, instead of the one specified by the the original call to LoadLibraryEx.

Quite odd.

**Comment by mkrautz** [comment]
My guess is that the Forwarded Exports from api-ms-win-crt-runtrime-l1-1-0.dll are NOT loaded according to the original LoadLibraryEx rules. Hmmm. If that's true, then it's a Windows bug :-(

Perhaps it's only applicabl for older Windows versions? I guess we need a self-contained test-case, because with the UCRT, this would be hard to test across Windows versions.

**Comment by mkrautz** [comment]
Reproducible test case at:

https://github.com/mkrautz/forwardexports-bug

Fails on Windows 7, but not on Windows 10.

**Comment by mkrautz** [comment]
Microsoft bug logged at https://connect.microsoft.com/VisualStudio/feedback/details/3121208

**Comment by hacst** [comment]
We really need smoke tests for xp and win 7. I created https://github.com/mumble-voip/mumble/issues/2841 to discuss how we can achieve that.

**Comment by Nuc1eoN** [comment]
The snapshot works for me on Win7 64bit. I had never installed murmur neither.
However maybe there are some remnants from previous versions.

**Comment by mkrautz** [comment]
@Nuc1eoN we added a workaround to Mumble in https://github.com/mumble-voip/mumble/commit/289d0d4c44d18125831651f5f46ce0208efe79e9

**Comment by Nuc1eoN** [comment]
@mkrautz sure, the previous snapshot (mumble-1.3.0~1931) also worked for me though.

**Comment by mkrautz** [comment]
@Nuc1eoN OK, maybe you have the universal CRT installed via another program?
(In this case, check c:\Windows\System32 or c:\Windows\SysWOW64 for ucrtbase.dll -- or if that fails, maybe search your filesystem for ucrtbase.dll?)

Or did you install both Mumble and Murmur (in which case the DLLs would be installed in a way that masked this bug.

**Comment by Nuc1eoN** [comment]
@mkrautz indeed the file is already `C:\Windows\System32` and `C:\Windows\SysWOW64` (it dates like a year back). After searching my file system it has been found in many other application folders.
I do not recall ever installing murmur btw.

**Comment by mkrautz** [comment]
This was fixed by the workaround in https://github.com/mkrautz/mumble/commit/03a3a3ea708bfc22437c9a332ae46414d511cf37

I've also added extra docs to mumble_exe.cpp to explain the situation:
https://github.com/mumble-voip/mumble/commit/d3bacc5a348ef09a522eee38bd89b17d29fa831f
