### ISSUE TITLE
QWindowsWindow::setGeometry: Unable to set geometry

### ISSUE THREAD

**Issue by Nuc1eoN** [mumble-voip/mumble#2843]
When I start mumble, very often the following line warning appears in the Dev Console:

`QWindowsWindow::setGeometry: Unable to set geometry 1920x1018+0+22 on QWidgetWindow/'MainWindowWindow'. Resulting geometry:  1916x1018+0+22 (frame: 8, 30, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 300x189, maximum size: 16777215x16777215).`

I have found some explanations why this happens and how it can be fixed here:
http://stackoverflow.com/questions/31230975/qt-setgeometry-unable-to-set-geometry
https://forum.qt.io/topic/29623/qwindowswindow-setgeometry-unable-to-set-geometry

Hope it helps

**Comment by Nuc1eoN** [comment]
Ok, I have found out why it is not always reproducible. Sometimes when I open mumble it is maximized, and everytime I look into the dev console I see this error. However when I unmaximize mumble the window unmaximizes, but get actuially bigger than it would be maximized (-> it does not fit the screen and it out of the borders). Then when I close mumble and open it again, the error message will not appear anymore.

I think this is because the Windows 7 window manager caches the size of the window somewhere and makes it open in a different size.

So I am not sure how to reproduce this yet. We would need to find a way to delete this cache from the window manager (dwm right?).

However since I could reproduce this again (had this issue before but did not report it because it has gone away) I am sure there is a doable way. I think maybe reinstalling helps. Will try that.

**Comment by hacst** [comment]
Usually mumble itself tries to remember its window geometry on shutdown and then tries to restore it (using setGeometry) next launch. Do your desktop dimensions sometimes change (multi-monitor vs single monitor, dpi changes, etc.)? Also is it just the warning bothering you or do you actually have some unwanted behavior due to the warning?

**Comment by Nuc1eoN** [comment]
> Usually mumble itself tries to remember its window geometry on shutdown and then tries to restore it (using setGeometry) next launch.

This would explain why the warning reappeared to me after I installed a new mumble version.

> Also is it just the warning bothering you or do you actually have some unwanted behavior due to the warning?

Yes, when I unmaximze the window it gets bigger then when it was maximized. Of course this is an unwanted behaviour.

**Comment by Kissaki** [comment]
The setting to remember the window position and size should be HKEY_CURRENT_USER\SOFTWARE\Mumble\Mumble\ui\geometry

> Yes, when I unmaximze the window it gets bigger then when it was maximized. This is an unwanted behaviour.

When you make it smaller then, and restart Mumble, is it bigger again, or does it retain its size?

**Comment by Nuc1eoN** [comment]
>  The setting to remember the window position and size should be `HKEY_CURRENT_USER\SOFTWARE\Mumble\Mumble\ui\geometry`

Thanks! Unfortunately I cannot reproduce it by deleting this entry :/

> When you make it smaller then, and restart Mumble, is it bigger again, or does it retain its size?

No, luckily it happens only once. And that's the issue I have no idea how to reproduce it again, I imagine it will reappear after sometime like it did before.

**Comment by Kissaki** [comment]
hacst asked whether your monitor resolution or dpi changed, if you could answer that

> Do your desktop dimensions sometimes change (multi-monitor vs single monitor, dpi changes, etc.)?

**Comment by Nuc1eoN** [comment]
Ah sorry. No I have a single monitor setup and I do not change the resolution/dpi.

**Comment by Nuc1eoN** [comment]
I have updated mumble and got the issue with mumble unmaximizing over the display borders again.
After I resize mumble it does not happen again.

**Comment by Krzmbrzl** [comment]
@Nuc1eoN is this issue still present in Mumble 1.3?

**Comment by Nuc1eoN** [comment]
I don't use mumble anymore. I don't use Win7 anymore. I use a  dual monitor setup now.

I honestly don't know, but I can try if you help me. How do I open the mumble dev console?

**Comment by Krzmbrzl** [comment]
Thanks for the offer - that'd be great :)

You can open the developer console by first going to the settings and in the `user interface` tab you can enable the `developer menu` via the checkbox in the `Application` area.
After that you'll have an additional menu entry in Mumble's main window called `Developer` under which you can open the dev console.

**Comment by Nuc1eoN** [comment]
Hey I have tried to reproduce the issue but I couldn't^^

Might still be a Win7 issue though, although who cares since Win7 is EOL anyways.

If I encounter it again I will reopen:)

**Comment by Krzmbrzl** [comment]
Thank you for reporting back :+1:
