### ISSUE TITLE
OverlayConfig screen grab crashes on macOS Sierra with external monitor attached

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2845]
From IRC:

02:39:50 &lt;whitewolf&gt; mkrautz: mkrautz_: are you still the maintainer of mumble for macos? on latest dev the settings pane has a 100% crash rate on sierra software update - is there a workaround?
03:54:32 &lt;@mkrautz&gt; whitewolf: is that 10.12.3 or 10.12.4?
03:56:36 &lt;whitewolf&gt; mkrautz: i had it happen on both 16C* and 16E* betas - 10.12.2 and 10.12.4 - i assume 16D* is also affected (10.12.3)
03:59:24 &lt;whitewolf&gt; mkrautz: sip is enabled, here's the crash log: https://cpy.pt/8tH6SS5h
04:00:06 &lt;whitewolf&gt; mkrautz: it might be upstream in Qt - perhaps fixed in a newer version
04:08:13 &lt;whitewolf&gt; hah!
04:08:26 &lt;whitewolf&gt; mkrautz: it only reproduces if you have an external display attached, at least for me... perhaps it's actually a macos bug
04:10:18 &lt;whitewolf&gt; or maybe passing in the wrong params in the case of multimon
04:30:38 &lt;@mkrautz&gt; whitewolf: it's probably the screenshot grabbing for the overlay settings (as I suspected)
04:31:32 &lt;@mkrautz&gt; oh, saw the crash log. yup :)

**Comment by mkrautz** [comment]
Re-hosted crash log, so it doesn't disappear on us:

https://gist.github.com/mkrautz/c83bde12280a5179e20e7815c09c0f92

**Comment by mkrautz** [comment]
This is most likely a Qt bug, we should investigate and create a small reproducible test case.

**Comment by Krzmbrzl** [comment]
Assuming this really is an upstream bug, I'll close this issue
