### ISSUE TITLE
Automatically use new/rotated SSL certificates if the file is updated

### ISSUE THREAD

**Issue by ckimes89** [mumble-voip/mumble#2846]
I have Let's Encrypt set up to auto-renew my SSL certificate every 2 months. It seems if I don't restart murmur after a certificate is renewed, it will not use the new certificate so users will see a "certificate expired" message.

**Comment by bontibon** [comment]
related #1972

**Comment by mkrautz** [comment]
@ckimes89 Right now, you can use the new (in 1.3.0) Ice method updateCertificate to update the certificate at runtime.

Let's discuss in #1972 for an easier method.
Closing.
