### ISSUE TITLE
Specify config file for Mumble client

### ISSUE THREAD

**Issue by Yamakaky** [mumble-voip/mumble#2848]
I want to pipe the output of a mumble channel into [liquidsoap](http://liquidsoap.fm/). My current setup is to launch Mumble in a VNC connection, connect it to the desired server + channel and use the ALSA output as input for Liquidsoap. A few questions:
- Is it possible to specify a config file, like with "mumble -c <conf>"?
- Do you know any way I could use to remotely control the Mumble instance, like by chat commands or HTTP api? I can code, so it's find if I have to write a plugin myself. I read https://wiki.mumble.info/wiki/Pluginguide, but doesn't seem appropriate for what I want to do.

**Comment by mkrautz** [comment]
> Is it possible to specify a config file, like with "mumble -c "?

No, not currently. Mumble looks for its config file here, though:
https://github.com/mumble-voip/mumble/blob/91ebb8b0b5f81543eed5be1c99d9265b1376c633/src/mumble/Global.cpp#L113-L143

> Do you know any way I could use to remotely control the Mumble instance, like by chat commands or HTTP api? I can code, so it's find if I have to write a plugin myself. I read https://wiki.mumble.info/wiki/Pluginguide, but doesn't seem appropriate for what I want to do.

What do you have in mind? On Unix-like systems, we have DBus integration, but it's not very fleshed out:
https://github.com/mumble-voip/mumble/blob/91ebb8b0b5f81543eed5be1c99d9265b1376c633/src/mumble/DBus.cpp

...We'd be happy to have this interface be more featureful. :-)

We also have an ad-hoc "SocketRPC" feature that allows you to control some things:
https://github.com/mumble-voip/mumble/blob/91ebb8b0b5f81543eed5be1c99d9265b1376c633/src/mumble/SocketRPC.cpp

It's very likely that neither of those cover the things you want to be able to do, but if you're on Linux, it'd probably make sense to build on the DBus interface. (And, actually, it seems like you're more interested in remote-controlling... So neither of these might be good fits.)

Perhaps you should consider a bot like Piepan instead?
https://github.com/layeh/piepan

Though I am not sure if Piepan suports playing back audio, or has an API for the incoming frames. /cc @bontibon 

Happy to discuss what your plans are

**Comment by bontibon** [comment]
> Though I am not sure if Piepan suports playing back audio, or has an API for the incoming frames

piepan doesn't support incoming audio (and is pretty much dead, too); https://github.com/layeh/gumble might suit you.

**Comment by Yamakaky** [comment]
Ideally, I would like a headless mumble client with remote control (can be RPC, REST, DBus...). That way, I wouldn't have to setup VNC.

**Comment by dstensnes** [comment]
+1 for headless. For use with SIP i found https://github.com/slomkowski/mumsi . Maybe you can find some inspiration from that

**Comment by Krzmbrzl** [comment]
For a headless client see #3877
For specifying a config file see #3953
