### ISSUE TITLE
Review polish translation after Transifex plural changes

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#2854]
Transifex announced changes to the polish plural rules via email on
2017-01-17, with reminders/updates on 2017-01-30 and 2017-01-31.

We should make sure our polish translations remain correct, and that we use correct plural forms that may have become available now but not before (and us using an inadequate one because of that).

Unfortunately I could not find an announcement, news or information page on their website about this change I could link to.

**Comment by Kissaki** [comment]
From the initial email:

> To be more precise, as you probably already know, Transifex follows ISO Standards and Unicode CLDR data for the supported languages.
> 
> Currently, the number of Polish plural forms that Transifex supports is 3. However, according to CLDR data, the Polish language has 4 plural forms.
> 
> The new changes are going to be deployed on Feb 1st, so before that, we would like to ask you to keep a backup of your resources in Transifex where the Polish language is included in order to avoid losing any data.
> 
> After the new plural rules are applied to Transifex, you will need to update source files (if the source language is Polish) or translation files (if the target language is Polish) by adding the 4th plural form to all the existing pluralized entries.
> 
> Then you can upload your files back to Transifex in order to properly update your data. 

From the last update:

> but I would like to make some corrections regarding the initial email I sent you.
> 
> To be more precise, any existing pluralized translation string in Polish will be preserved in Transifex. This means that there would be no need to re-upload the Polish translation files after the new changes are live since all the existing translations will remain untouched.
> 
> The new plural form: "many" will automatically be filled with the translation that is currently available on the "other" plural form.
> 
> So, the Polish pluralized strings will remain translated in Transifex and the only difference will be the additional new form.  
> 
> Note: As far as the Polish source files (in case your project's source language is Polish), the steps that were mentioned in the initial email are still valid:
"After the new plural rules are applied to Transifex, you will need to update source files (if the source language is Polish) by adding the 4th plural form to all the existing pluralized entries."

**Comment by Kissaki** [comment]
@Zuko can you check and explain what changes might be necessary, and review the polish translation regarding plurals?

**Comment by Kissaki** [comment]
I tried referencing one of the other Transifex translators here with @ auto-completion, but found no matching name(s).

**Comment by Zuko** [comment]
Because there is no one else. 
Sorry but I stopped using Mumble, translating without using is pointless (it is very easy to make stupid mistakes).

**Comment by Krzmbrzl** [comment]
Closing as to my knowledge none of the (active) devs are speaking Polish. Besides this issue is three years old, so I assume that if something has been wrong with the Polish translation it would have been discovered (and fixed) by now.
