### ISSUE TITLE
Can't restore window normally after minimizing on macOS

### ISSUE THREAD

**Issue by epiqu1n** [mumble-voip/mumble#2856]
I am currently using MacOS 10.12.1.  Whenever I minimize Mumble, clicking on the Mumble icon does not bring the window back.  The only way to do so is to right click > show all windows, and then select the minimized Mumble window that shows up at the bottom of the screen (image attached for clarification).
<img width="1428" alt="screen shot 2017-02-17 at 6 00 10 pm" src="https://cloud.githubusercontent.com/assets/1347847/23086509/3b966334-f53b-11e6-8ccd-18440ceff507.png">

**Comment by Guigo-** [comment]
I have the same issue on Debian sid with Awesome/Gnome, with Mumble 1.2.18. It's solved with the current master. Did you try the development snapshot on https://wiki.mumble.info or with compiled source code ?

**Comment by epiqu1n** [comment]
I was using release 1.2.19.  I just downloaded the development snapshot and
that works, thanks.

**Comment by davidebeatrici** [comment]
Closing the issue as it has been confirmed as fixed.
