### ISSUE TITLE
Fix up all dependencies on all OSes to have matching versions and patches.

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2865]
Right now, not all dependencies are up-to-date on all platforms for 1.3.x.

In particular, libsndfile and Ice.

We should fix that before 1.3.0 beta.

**Comment by Kissaki** [comment]
For Windows, this would be mumble-releng.
What does this mean for mac and linux?
For Ubuntu, we have a PPA that should build but we have no control over lib versions.
Where/what else would I look for?

**Comment by mkrautz** [comment]
For Mac and Linux it's also mumble-releng (buildenv/1.3.x/centos-ermine and buildenv/1.3.x/osx and buildenv/1.3.x/osx-universal)...

I guess this is mostly on my table though :)

But buildenv/1.3.x/centos-ermine can be updated mostly anywhere. It doesn't "need" to be a CentOS 5.9 box, an Ubunut will do -- it should build there just fine. However, it'll probably need some fixups to actually build on CentOS 5.9.

**Comment by C0rn3j** [comment]
Since this is pretty much the last blocker for 1.3 release that can't be resolved almost immediately, what's the status on it?

>However, it'll probably need some fixups to actually build on CentOS 5.9.

I see you're concerning yourself with an OS that was already EOL by the time you posted it, why?

**Comment by Morgyn** [comment]
Is there a list of target OSs?

**Comment by xnox** [comment]
Is there anything not up to date on Ubuntu that you need to release 1.3? I can update anything...

**Comment by AzP** [comment]
Does Mumble really need to concern itself with library versions in (EOL) distributions?

**Comment by mkrautz** [comment]
We use CentOS as a base to get a good baseline libc that is compatible with older kernels.
Back when we initially did 1.2.5 (or 1.3.0 as it has become known), it wasn't as far-fetched as it sounds now.

Basically, our buildenvs are small distributions of their own. They only contain the dependencies that are relevant to us.

We aren't concerning ourselves with libraries for CentOS. We're concerning ourselves with the libraries that we link against in our "static"/AppImage build of Murmur on Linux. We use the same version of libraries with the same patches applied on all platforms we ship on.

**Comment by xTMxTM** [comment]
@mkrautz Any progress on this issue?

**Comment by C0rn3j** [comment]
Alright so this is the sole remaining issue for getting 1.3 out I guess.

What's the status on each Linux, Windows and macOS? I know that Ubuntu PPAs were fixed but that's about it.

Would it still be possible to tag a 1.3 release without releasing a build yet? Distros build from source anyways so this would enable Linux distros to build a 1.3 stable.

**Comment by promi** [comment]
It is important to make a 1.3 release branch and stabilize that, so distros have a known working version of the software again.

Why should the release be delayed any further by the build infrastructure? Can't that be fixed during the beta phase?

I vote for moving it from P0 to P1, so the beta can be started.

**Comment by anarcat** [comment]
i would punt this in the court of distributions, to be honest... debian is shipping the git snapshot of mumble 1.3, for example...

**Comment by promi** [comment]
> i would punt this in the court of distributions, to be honest... debian is shipping the git snapshot of mumble 1.3, for example...

That is a support nightmare. The idea of a stable version is that you have one version that you can report bugs / security issues against, etc. If everyone is maintaining their own git snapshot of Mumble work is duplicated.

**Comment by anarcat** [comment]
On 2019-01-16 22:15:23, Phobos wrote:
>> i would punt this in the court of distributions, to be honest... debian is shipping the git snapshot of mumble 1.3, for example...
>
> That is a support nightmare. The idea of a stable version is that you have one version that you can report bugs / security issues against, etc. If everyone is maintaining their own git snapshot of Mumble work is duplicated.

Yeah well, that nightmare is happening because there's no official
release of course.

**Comment by AzP** [comment]
I think tagging a release and getting some sort of release out (even if it is an _rc1) is better than not having one, since some distributions will either start shipping the git HEAD (which I believe most of them are adamant to do) or simply remove the package completely.
Instead of tagging a rc1, perhaps it's better to just release a buggy version, to get a build into distributions, receive bug reports and release a patched release ASAP.

**Comment by VVD** [comment]
FreeBSD is in state of removing Qt4 from ports now. All dependent from Qt4 ports will be removed soon, mumble 1.2.9 too.
Please, make release 1.3.0 before 1.2.9 removed.

**Comment by VVD** [comment]
It was just removed:
audio/mumble||2019-03-16|Has expired: Qt4 has been EOL since december 2015
audio/murmur||2019-03-16|Has expired: Qt4 has been EOL since december 2015
Please, make release 1.3.0!

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/issues/2728#issuecomment-473710939

**Comment by VVD** [comment]
mumble and murmur 1.3.0-r1 are in FreeBSD ports again!

**Comment by preterive** [comment]
I think this is no longer a problem, because there are appimages now.

**Comment by Kissaki** [comment]
@davidebeatrici @Krzmbrzl @ZeroAbility What’s the status of this ticket? It’s still labelled P0 Blocker. From the ticket description and followup comments it’s not really clear what it is about specifically?

I don’t think we want to change anything for 1.3 anymore in this regard? For 1.4 we already use up to date stuff? Is anything still open for the appimage or centos stuff then? I believe we dropped the old centos static binary?

**Comment by davidebeatrici** [comment]
Correct, all dependencies are synced for 1.4.x.

**Comment by Krzmbrzl** [comment]
Yep I think so to. Thus I'll close this issue :point_up: 

> Is anything still open for the appimage or centos stuff then?

Well the AppImage is currently broken in the first place but if it weren't the dependencies should not be an issue since they are now managed by vcpkg.
