### ISSUE TITLE
TestTimer: atomicity test sometimes fails

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2894]
********* Start testing of TestTimer *********
Config: Using QtTest library 5.6.1, Qt 5.6.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.2.0 20160914)
PASS   : TestTimer::initTestCase()
PASS   : TestTimer::resolution()
PASS   : TestTimer::accuracy()
FAIL!  : TestTimer::atomicity() 'abs((long)(ttime - b.elapsed())) < 100' returned FALSE. ()
   Loc: [TestTimer.cpp(73)]
PASS   : TestTimer::order()
PASS   : TestTimer::cleanupTestCase()
Totals: 5 passed, 1 failed, 0 skipped, 0 blacklisted
********* Finished testing of TestTimer *********

**Comment by mkrautz** [comment]
Another TestTimer failure:


	/Users/travis/build/mumble-voip/mumble/src/tests/TestTimer/target_wrapper.sh  ./TestTimer 
	********* Start testing of TestTimer *********
	Config: Using QtTest library 5.8.0, Qt 5.8.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 8.0.0 (clang-800.0.42.1) (Apple))
	PASS   : TestTimer::initTestCase()
	FAIL!  : TestTimer::resolution() 'tchange > (achange * 100)' returned FALSE. ()
	   Loc: [TestTimer.cpp(57)]
	PASS   : TestTimer::accuracy()
	PASS   : TestTimer::atomicity()
	PASS   : TestTimer::order()
	PASS   : TestTimer::cleanupTestCase()
	Totals: 5 passed, 1 failed, 0 skipped, 0 blacklisted, 1023ms
	********* Finished testing of TestTimer *********
	make[2]: *** [check] Error 1
	make[1]: *** [sub-TestTimer-check] Error 2
	make: *** [sub-src-tests-check_ordered] Error 2

**Comment by Krzmbrzl** [comment]
I never saw that bug occurring ever since I started working on Mumble a good half a year ago. Thus I assume this has been fixed (somehow) in the meatime
