### ISSUE TITLE
Mumble 1.3.0.1937 (g289d0d4) failed to load mumble_app.dll on WinXP 64

### ISSUE THREAD

**Issue by Avispa** [mumble-voip/mumble#2900]
.. as the subject says.

> Mumble Launcher Error -3
> Failed to load mumble_app.dll.

My 2 cents: wrong library/dll search path because *mumble_app.dll* is present in the install  directory. I've installed 1.3 parallel to 1.2 into "Mumble 1-3-0-1937".

This is an attempt to Issue #2789 suggested by **mkrautz**.

**Comment by Avispa** [comment]
Okay, just go get sure, I've searched my whole system for *mumble.exe* and the only one I can find is the one in the install directory of Mumble 1.3. Can any of the developers of the installer please explain me where Mumble 1.2 is gone to!?!

**Comment by mkrautz** [comment]
There is probably still an Windows XP issue in the UCRT from MSVC2015 which causes 1.3.0 not to load on XP.

As for the installer:
Did the installer present it like it could be installed next to Mumble 1.2.x? It should only allow you to upgrade your existing installation, IIRC.

**Comment by Avispa** [comment]
@mkrautz Does the installer present it like it could *not* be installed next to Mumble 1.2.x? -- I just re-checked: Nope.

As "installer" by common sense already implies: it installs something; it is not meant to un-install something (as long as it is not mentioned differently). I will open a new issue regarding that since it is in fact off topic here. Sorry for that.

**Comment by mkrautz** [comment]
An "upgrade" in our installer uninstalls the current product, and installs the new one on top. If it didn't, your old files wouldn't get removed, if you upgraded in-place.
But let's discuss in the new issue.

**Comment by mkrautz** [comment]
However, I understand the confusion if it was not presented as an upgrade.

**Comment by Avispa** [comment]
For the sake of completeness: I installed Mumble 1.3 in-place. Error "-3" persists: mumble_app.dll not found.

**Comment by mkrautz** [comment]
Yes! Thanks. I believe it might be XP-specific. Will look into it.

**Comment by mkrautz** [comment]
Current snapshots work on Windows XP. (Note: x64 snapshots do not work; they aren't built with an XP-compatible toolchain/SDK).
