### ISSUE TITLE
User Filter: Only display talking users

### ISSUE THREAD

**Issue by InteliWasp** [mumble-voip/mumble#2913]
Would it be possible to have an alternative for the osd? I currently have a Logitech G15 keyboard that needs to be replaced soon, the best feature is the LCD screen on it that mumble uses to show who is talking. I don't like the way the current OSD mechanic of overlaying on top of my game window to see who is talking but I do have a second (and third...) monitor that i place a small window that mimics the way mumble displays info on the G15 keyboard LCD. Bonus points for the ability to set text and background colors.

**Comment by mkrautz** [comment]
The alternative at the moment is to simply run the client on your other monitor.
You can use the minimal view feature to make it more minimalistic: Configure -> Minimal View.
Also, you can hide the window decorations (while in Minimal View)... Right click -> Configure -> Hide Frame.

To get out of Minimal View, right click inside the Mumble window -> Configure -> Uncheck minimal view.

**Comment by Kissaki** [comment]
@InteliWasp does that fit your use case? If not, what would you like to have?

**Comment by InteliWasp** [comment]
Sorry about the delay in replaying, i did try the above method but it still show ALL the people in the room. there are also connected rooms in other channels that also talk that i want to know who is talking. i was mainly asking for basically a mirror of the g15 screen that i can put on my secondary monitor and this only shows who is talking in the room (including connected rooms). BTW i deal regularly with rooms with 50 to 600+ in 1 room. (I play eve online)

**Comment by Kissaki** [comment]
So basically you would like a user filter (like our current channel filter) that only displays talking users? Relevant #2712 (which is for friended users, but a user filter nonetheless.

**Comment by Krzmbrzl** [comment]
For this exact use-case there is now the TalkingUI. See https://www.mumble.info/blog/first-mumble-1.4.0-development-snapshot/#talkingui

Given that we have that now, I think an additional filter option is no longer necessary. Thus I am closing this issue.
