### ISSUE TITLE
Link a channel to a user

### ISSUE THREAD

**Issue by UBren** [mumble-voip/mumble#2914]
Hello, I have never seen this feature before in any VOIP client, and I think it's will be very useful for server administrators.

example: User1 is a server administrator, and User2 is a moderator.
User1 have in the channel "Server administrators" the permission "Link to myself".
User1 is currently on the channel "Root".
User2 enter in the channel "Needing help" and talk to User1 about, for example, a user grefing in User1's game server.

If the User1 can have a special shortcut to talk in the channel "Server administrators", that will be better, but it's will probably add a lot of work, and it's maybe required another feature request.

My apologies if this feature already exists, even if I have found nothing about this, and my bad English.

**Comment by Kissaki** [comment]
I’m not sure I understand. Could you try to explain again?
