### ISSUE TITLE
Debian (Linux) - System Audio as input

### ISSUE THREAD

**Issue by BetaStacks** [mumble-voip/mumble#2923]
I am using Debian and could like to send the audio that is played from my Chromium browser into the input for the Mumble Client. 

Any advice on how I can achieve this?

**Comment by davidebeatrici** [comment]
The guide at https://wiki.debian.org/audio-loopback explains how to loopback the audio from an application that is showed in the mixer to a specific device. :wink:

**Comment by mkrautz** [comment]
Closing this, at this "support ticket" seems to be resolved.
If you feel this is in error, either post a comment saying so, or raise another issue. Thanks!
