### ISSUE TITLE
Markdown parser for chat

### ISSUE THREAD

**Issue by felixsinger** [mumble-voip/mumble#2945]
Would be great if the chat had a Markdown functionality :)

**Comment by LuaMilkshake** [comment]
In #2096 we discussed a 'mimetype'-like field and Markdown-like support. I agree that Markdown is closer to the limited formatting that a chat client like Mumble expects to use.

**Comment by Krzmbrzl** [comment]
We could use RegEx on the client side to automatically convert markdown to HTML before sending it to the server.

https://gist.github.com/jbroadway/2836900 might be helpful as it seems to contain RegEx patterns for the most common markdown elements.

**Comment by streaps** [comment]
> We could use RegEx on the client side to automatically convert markdown to HTML before sending it to the server.

Is this how it is implemented in #4076?

**Comment by Krzmbrzl** [comment]
@streaps yes
