### ISSUE TITLE
Mumble won't record

### ISSUE THREAD

**Issue by ptglhs** [mumble-voip/mumble#2968]
I'm trying to record an interview in Mumble. I keep getting the error message,

"Recorder failed to open the file '%s.'

This error message appears when I use push to talk, when I leave the mic open, or when the other person talks. Even if I just hit record and then stop several seconds later no .wav file appears in my mumble file. I'm using version 1.2.8. I'm not very computer savvy so please keep that in mind when responding. I'd appreciate any help.

**Comment by davidebeatrici** [comment]
Where are you trying to save the file?
Have you tried with another location?

**Comment by ptglhs** [comment]
I've tried to save the file in the default directory, in mumble. I've also tried to save it in:

C:\Program Files (x86)\Mumble\Interviews

**Comment by davidebeatrici** [comment]
Try to save it on the Desktop. If it doesn't work, run Mumble as administrator.

If it still doesn't work, try to set a custom file name.

**Comment by ptglhs** [comment]
Thanks, that worked! It wouldn't let me save in mumble but other directories work.

**Comment by davidebeatrici** [comment]
You're welcome!

Mumble wasn't able to save the file in _C:\Program Files (x86)_ because you need to have administrator rights to do that. :wink:
