### ISSUE TITLE
settings -> messages needs to be keyboard navigateable

### ISSUE THREAD

**Issue by chrys87** [mumble-voip/mumble#2972]
Howdy,
since mumble is one of the most awsome software on the world also blind people starting using it.
blind people are keyboard only. can you make "settings"->"messages" keaboard navigateble?
currently i can only select the "row" (the setting) but nut the booleans to toggle them.
can you please make them navigateable?
i will do some box of beer as donation for sure :).
cheers chrys
linux-a11y.org

**Comment by mkrautz** [comment]
Thanks for reporting this. This part of Mumble should obviously be more accessible. Sorry it isn't usable at the moment.

I can't give a timeframe, but it's someting that I personally would like to see fixed ASAP.

**Comment by Kissaki** [comment]
The code in question: Log.h, Log.cpp, Log.ui, QTreeWidget LogConfig::qtwMessages.

**Comment by Krzmbrzl** [comment]
The linked commits seem to sit in https://github.com/Kissaki/mumble/tree/config-log-keyboardinput

@Kissaki why has there never been a PR for this? Didn't it work?

**Comment by Kissaki** [comment]
🤷‍♂ 

Well, if it would have been ready I would have created a PR. Why it is not? I do not know.
