### ISSUE TITLE
Failed to build 1.3.0_2198_g282d672-1 on Arch Linux

### ISSUE THREAD

**Issue by ReekyMarko** [mumble-voip/mumble#2976]
I don't know if this really belongs here, but this morning I was updating my AUR packages on my Arch box and it failed to build the latest snapshot of Mumble. Here's the output of pacaur: https://pastebin.com/WJ2vNTiv

**Comment by mkrautz** [comment]
Hi, thanks for reporting this!

From things like

> make[2]: Entering directory '/home/sysadmin/.cache/pacaur/mumble-snapshot/src/mumble-1.3.0~2198~g282d672~snapshot/src/mumble_proto'
> make[2]: Nothing to be done for 'first'.
> make[2]: Leaving directory '/home/sysadmin/.cache/pacaur/mumble-snapshot/src/mumble-1.3.0~2198~g282d672~snapshot/src/mumble_proto'

it seems to me that the build directory isn't clean.

My best bet is that your compiler has been upgraded since last time the Mumble tree was built, and the PCH files are now incompatible with the new compiler.

**Comment by ReekyMarko** [comment]
Thanks for the input! How would I go about cleaning the build directory and fix the incompatible PCH files? I've been googling all day but I haven't been able to find a definitive answer.

**Comment by davidebeatrici** [comment]
Hi, the _make clean_ command should clean up everything.

**Comment by ReekyMarko** [comment]
make clean returns: "make: *** No rule to make target 'clean'.  Stop."

I found the command "pacaur -Scc clean" which seems to delete most everything related to pacaur from my system, but when I try to rebuild mumble, still tells me: "==> WARNING: Using existing $srcdir/ tree" and returns the same errors as before.

**Comment by mkrautz** [comment]
I'd just try to delete the `/home/sysadmin/.cache/pacaur/mumble-snapshot/src/mumble-1.3.0~2198&~g282d672~snapshot/` tree.

**Comment by ReekyMarko** [comment]
That did the trick! Thanks alot :)

**Comment by mkrautz** [comment]
👍 Excellent. Closing.
