### ISSUE TITLE
Build directions not in readme

### ISSUE THREAD

**Issue by BerndtSam** [mumble-voip/mumble#2991]
Hey, I'm trying to build mumble from your repository on Mac OSX Yosemite v10.10.5. What is the actual process to follow to do this?

Normally this information would be in the README, but I fail to see them there.

I've followed the wiki page: https://wiki.mumble.info/wiki/BuildingMacOSX, however, the files it says exists don't and thus I'm at a stand still.

Any information you can provide would be amazing.

Thanks!

**Comment by mkrautz** [comment]
Hi,

Sorry, the wiki is out of date right now.

The correct paths are:

    $ cd mumble-releng/buildenv/1.3.x/osx
    $ ./setup.command
    $ source /MumbleBuild/path/to/the/build/env
    $ cd ~/path/to/mumble
    $ qmake -recursive -Wall main.pro CONFIG+="release static"
    $ make

You can also build via Homebrew...
Depending on where you've installed Homebrew (typically /usr/local, which is what I've used below):

    $ brew install qt5 libogg libvorbis flac libsndfile protobuf openssl ice
    $ export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
    $ export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig
    $ export PATH=$PATH:/usr/local/opt/qt5/bin:/usr/local/bin
    $ export MUMBLE_PREFIX=/usr/local
    $ export MUMBLE_ICE_PREFIX=/usr/local/opt/ice
    $ qmake -recursive -Wall CONFIG+="release"
    $ make

Hope it helps.

**Comment by Kissaki** [comment]
While the README does not mention building, the `INSTALL` file does, pointing to the wiki page you mentioned as well.

**Comment by Krzmbrzl** [comment]
Linking this to #3942
