### ISSUE TITLE
compile protoc error plz help me

### ISSUE THREAD

**Issue by fpemdksk** [mumble-voip/mumble#2996]
```
protoc Internal or external commands are not executable programs or batch files
jom: C:\MumbleBuild\win64-static-1.3.x-2017-03-26-d219ea1-825\build-main-Desktop_Qt_5_6_2_MSVC2013_64bit-Debug\src\mumble_proto\Makefile.Debug [Mumble.pb.cc] Error 1
jom: C:\MumbleBuild\win64-static-1.3.x-2017-03-26-d219ea1-825\build-main-Desktop_Qt_5_6_2_MSVC2013_64bit-Debug\src\mumble_proto\Makefile [debug] Error 2
jom: C:\MumbleBuild\win64-static-1.3.x-2017-03-26-d219ea1-825\build-main-Desktop_Qt_5_6_2_MSVC2013_64bit-Debug\Makefile [sub-src-mumble_proto-make_first-ordered] Error 2
09:56:44: The process "C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project main (kit: Desktop Qt 5.6.2 MSVC2013 64bit)
When executing step "Make" 
```

my Qt version 4.0.3 msvn 2013

I have tried to compile the main.pro file in Qt

I did not compile. 
My protobuf 3.2.0 does not have vsproject, so I replaced it with protobuf 2.6.
I compiled vsproject and linked the library.
what was wrong?

**Comment by mkrautz** [comment]
It seems the build can't find your protoc binary. You can use the MUMBLE_PROTOC env var to specify a path to it if it isn't in your PATH.

(see also https://github.com/mumble-voip/mumble/blob/master/qmake/protoc.pri)

**Comment by mkrautz** [comment]
If there are future problems, please open a new issue. Thanks!
