### ISSUE TITLE
Should Certificate Wizard "strongly recommend you create a trusted certificate"?

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#3021]
Right now we prominently link to http://mumble.info/certificate.php (this is issue #3022), which redirects to a Wiki page about obtaining a "trusted" certificate...

Should we keep doing this? Maybe tone down the bolded "strongly"?

See screenshot for reference...

![image](https://cloud.githubusercontent.com/assets/36527/25040321/e840c81a-2108-11e7-8be9-c86a62259507.png)

**Comment by davidebeatrici** [comment]
In my opinion we should change it to something like "_If you want to create a trusted certificate, read the dedicated page in our Wiki_", with a link to the page.

**Comment by Kissaki** [comment]
A strong (email) certificate only gives trust to own an email address. This may be useful in some scenarios, maybe for automated identification with the email address according to a different user database. But I do not think this is useful in the vast majority of cases.

A few scenarios:

The users know each other before hand, and invite each other to the server. So they expect the other person, and can identify them. Maybe even by voice, or just by trusting it is actually the person after talking ingame, in a forum, or whatever.

The users do not know each other, but invite each other to a server (interview, public grouping). They will not immediately friend the other users or give permissions to the user, so an immediate trusted user verification is not likely expected.

For existing user databases, authenticators provide a good immediate trust alternative - although it is not a native Mumble feature but requires additional setup.

I guess comodo does not allow retrieval of certificates either, with the trusted mail? If that is the case, it is not a useful recovery option either.

A trusted certificate validates the user as identifiable per email address. But for this to be useful, the other users would have to make use of that email address. Which is not likely.

**I think we should entirely drop the recommendation.** We could mention the option.

I'm even thinking about not mentioning it and offloading it to specific admins/inviters that actually make use of their usefulness - but how will they know about the possibility? So briefly mentioning is probably the best.
