### ISSUE TITLE
CertificateWizard: create trusted certificate link points to HTTP URL

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#3022]
The "create a trusted certificate" link in the Certificate Wizard points to

http://mumble.info/certificate.php

This should be an HTTPS URL instead.

**Comment by Kissaki** [comment]
Accessing https://mumble.info/certificate.php asks for a user certificate in Firefox (52.0). However, it does not seem to ask for it in Chrome. Whether a user certificate is presented or not, the redirect works either way.

**Comment by Krzmbrzl** [comment]
To my knowledge all links have been upgraded to https by now. Plus I also can't find that URL in the code anymore...
