### ISSUE TITLE
Snapshot 1.3.0~2302~geca5d03 Crashes On Startup

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#3023]
After updating the snapshot to this version it no longer launches. Sending a crash report is not possible in this state, no error message is shown.

Uninstalling and installing an older Snapshot works.

ham5, hacst, Whooa21 reported in #mumble and I experienced it as well.

@hacst rolled back the snap links so no additional users should be updating.

@hacst said it crashed in zlib.

Sadly, this is the first snap after quite some time (11.02.2017). This was before the overlay exceptions were merged. We recently updated our build environment libraries in mumble-releng, so this may likely be introduced by these version updates.

Building it with my environment `win64-static-no-ltcg-1.3.x-2017-04-03-d3441b4-837`, which was before various updates (including zlib), my local build works fine.

**Comment by hacst** [comment]
Any ideas @mkrautz ?

**Comment by Kissaki** [comment]
[zlib update from 1.2.8 to 1.2.11](https://github.com/mumble-voip/mumble-releng/commit/67c469f7d8671da617009494b58ff9f7fcec8406)

The only (source) patch we apply to zlib is to [add the safeseh compilation flag](https://github.com/mumble-voip/mumble-releng/blob/master/buildenv/1.3.x/win32-static/patches/zlib-safeseh.patch).

**Comment by davidebeatrici** [comment]
Everything works fine for me, on Windows 7 x64.

**Comment by hacst** [comment]
I just checked and the issue only seems to occur with the 32bit Windows release. 64bit start fine for me on Windows 10 Pro.

**Comment by hacst** [comment]
> /SAFESEH is only valid when linking for x86 targets. /SAFESEH is not supported for platforms that already have the exception handlers noted. For example, on x64 and ARM, all exception handlers are noted in the PDATA. 
source https://msdn.microsoft.com/en-us/library/9a89h429.aspx

So maybe actually some issue with safeseh?

**Comment by Kissaki** [comment]
We are using safeseh since 2014 e873dcefd775a3bef064012d8737a0c8dea8a5ac

**Comment by Kissaki** [comment]
Potentially/Likely fixed by https://github.com/mumble-voip/mumble-releng/commit/3dcee9372daff97323f9b8614bd335e30e58ab7a

**Comment by mkrautz** [comment]
Fixed in mumble-1.3.0~2306~g46462cd~snapshot.msi
