### ISSUE TITLE
Mumble should use Windows 10's own DNS-SD implementation instead of Bonjour

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#3024]
On Windows 10, it would be nice to use Microsoft's own DNS-SD implementation.

https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.ServiceDiscovery.Dnssd

**Comment by DGMurdockIII** [comment]
Hell yes don't like Bonjour

**Comment by davidebeatrici** [comment]
Documentation: https://docs.microsoft.com/en-us/windows/win32/api/windns

**Comment by DGMurdockIII** [comment]
but what would linux version use

**Comment by davidebeatrici** [comment]
Either [Avahi](https://avahi.org) or [mDNSResponder](https://opensource.apple.com/source/mDNSResponder).

**Comment by DGMurdockIII** [comment]
Zeroconf

**Comment by ZeroAbility** [comment]
This and several companions:
https://docs.microsoft.com/en-us/windows/win32/properties/props-system-devices-dnssd-servicename
