### ISSUE TITLE
 Problem with overlay in game.

### ISSUE THREAD

**Issue by LOST100293** [mumble-voip/mumble#3027]
Hello, I have a problem with mumble overlay in gta san andreas multiplater (SAMP), on windows 10. Now when I turn on the overlay, this shows up in the game on the screen, sees channels but can not do anything because the course does not show.

And in addition, often when I turn on the overlay, this game is minimized when I press the buttons from the on. Please repair. And, I have mumble 1.3.0, keeps updating.
Screen:
http://i.imgur.com/ehHk3Hg.jpg

The game comes down to the bar, there is no cursor, you can not move between channels, you can not enter the setting, nothing can be done. Windows 10

**Comment by mkrautz** [comment]
Hi,

We don't support the "Toggle overlay" feature for using Mumble in-game in 1.3.0 anymore.

Are you using the "Toggle overlay" for showing Mumble in-game?
Or are you using that shortcut, thinking it will show/hide the overlay?

Thanks.

**Comment by mkrautz** [comment]
To clarify:

Using the "Toggle Overlay" shortcut actually means "Toggle In-Game Overlay".
The in-game overaly is what you're seeing inside your game window.

We don't support that feature in Mumble 1.3.0 (it's broken), and we should remove the ability to trigger the feature.

**Comment by LOST100293** [comment]
I want to use this large overlay while playing to use mummification without having to minimize the game. Well, then why delete if you can fix it somehow to be used? Also, as always, when I turn on the preview, I often minimize the game itself (when clicking the overlay button). In general, it would be nice to see what channel you are currently viewing in this little overlay.

**Comment by mkrautz** [comment]
Can you try to navigate to Configure -> Settings -> Shortcuts and disable `Enable Windows hooks` and see if that helps?

**Comment by mkrautz** [comment]
Sorry, this was not meant to go to this issue.

**Comment by LOST100293** [comment]
I turned it off, but that does not help, and on the contrary, when it is off, it minimizes it every time, not just randomly.

**Comment by Kissaki** [comment]
> why delete if you can fix it somehow to be used?

We don't have the capacity/time to do so. That’s why it was removed for 1.3.

**Comment by mkrautz** [comment]
That's not to say that an in-game overlay won't be coming back sometime. It's just that the current implementation is flawed in some ways.

**Comment by LOST100293** [comment]
And do you want to display the name of the channel we are on on a small overlay (where only people are shown online)? This is useful for SAMP (San andreas MultiPlayer) games on Role Play servers. Please do this. ;)

**Comment by Kissaki** [comment]
Regarding displaying the channel name in the overlay, see feature request #3035 (you can subscribe for updates there to be notified about new info on it)

**Comment by Kissaki** [comment]
To summarize:
* The interactive overlay client (seen in the screenshot) works for channel switching, but not buttons and opening the settings dialogue.
* We removed the interactive overlay in 1.3.0 because we can not adequately support the current (hacky?) solution (may return in the future).

Can we close this?
Are you describing another issue as well?
> often when I turn on the overlay, this game is minimized
