### ISSUE TITLE
PPA packages for Ubuntu 17.04 (Zesty)

### ISSUE THREAD

**Issue by tobiasgies** [mumble-voip/mumble#3030]
Hi Mumble team,

Ubuntu Zesty was released on April 13th. By default, its package repository contains mumble 1.2.18-1 and mumble-server 1.2.18-1.

Can you please extend your build script to add builds for zesty to Mumble's stable and snapshot PPAs?

Thanks!

**Comment by mkrautz** [comment]
Zesty support is now available in the snapshot PPA:
https://launchpad.net/~mumble/+archive/ubuntu/snapshot/+packages

**Comment by tobiasgies** [comment]
Thank you! :-)

**Comment by mkrautz** [comment]
Zesty support is now available in the release PPA:
https://launchpad.net/~mumble/+archive/ubuntu/release/+packages
