### ISSUE TITLE
Add closed mouth icon

### ISSUE THREAD

**Issue by mray** [mumble-voip/mumble#3036]
A grayed out mouth is one way to represent not speaking: 

![image](https://cloud.githubusercontent.com/assets/164785/25105176/d0d18490-23c3-11e7-8596-e9a3820d2a95.png)

Much clearer would be a closed mouth.

**Comment by mray** [comment]
Added a [pull request](https://github.com/mumble-voip/mumble/pull/3037) for this SVG file:

![image](https://cloud.githubusercontent.com/assets/164785/25108073/9c6eb960-23d3-11e7-8e9e-ff149bd02dc8.png)

**Comment by Kissaki** [comment]
Is the closed mouth clearly enough a mouth?

Maybe the speaking mouth should "emit soundwaves" instead (make it clearer speaking is speaking)?

**Comment by mray** [comment]
On its own I share your concern about this being a bad logo. In combination with the open mouth icon it should be self-explaining, though.

**Comment by DGMurdockIII** [comment]
I love the idea

**Comment by davidebeatrici** [comment]
#3037 Has been merged.
