### ISSUE TITLE
New option "Launcher Filter" causes lag on whatever program you have your mouse move over

### ISSUE THREAD

**Issue by Dreamerrrr** [mumble-voip/mumble#3042]
I noticed that when I had Mumble open with 1.3.0~2306~g46462cd~snapshot I would get a lot of lag in whatever program I had open. The most noticeable was trying to watch videos in Chrome on YouTube or Twitch. If the mouse wasn't moving the programs behaved normally, but moving the mouse made their CPU usage skyrocket in Task Manager, and the videos in particular to stutter. 

I narrowed down the culprit to the new "Launcher FIlter" option and changing it back to "Whitelist" fixed the issue.

EDIT: It's spread to lagging if the overlay is on at all.

**Comment by mkrautz** [comment]
Hi,

What OS is this on?

Did you customize the default settings for the overlay when this happened?

**Comment by Dreamerrrr** [comment]
Windows 10 x64 , Mumble x64, Mumble 1.3.0~2306 g46462cd snapshot, 

Expected a conflict with Nvidia Share overlay (Shadowplay). Lag happens either way on or off. Also looked at Discord overlay which I've always had disabled. Lag persists with Discord completely closed.

I reset overlay settings to default and the same lag appears.

Problem is worst if Launcher Filter is on, but CPU spikes appears on either Whitelist or Blacklist if overlay is enabled. Blacklist appears to have the least amount of lag. Doesn't affect task manager, Mumble window, or Microsoft Edge for some reason. Steam, Foobar2000, GeForce experience, Chrome, KeePass, qBittorrent, Discord are the programs I tested. All have their CPU usage spike if they have the mouse moving over them with overlay enabled. As soon as the mouse becomes stationary CPU usage and lag stops.

**Comment by mkrautz** [comment]
I can reproduce it with scroll events in Chrome:

If I enable the overlay, scrolling is choppy.
If I disable the overlay, it is very smooth.

Weird.

**Comment by mkrautz** [comment]
ProcMon shows that on every scroll event, the overlay DLL is attempted to be injected. WTF?

**Comment by mkrautz** [comment]
Ah, ok. We do actually use WH_CBT for our hooks. That, combined with my clever trick to unload the DLL when it's unused causes problems... Will revert.

**Comment by mkrautz** [comment]
Hopefully fixed in https://github.com/mumble-voip/mumble/commit/8f65051faf9e1cb4a921c4512387ddfc35eae9e5.

Building a new snapshot as we speak...

**Comment by mkrautz** [comment]
@Dreamerrrr New snapshot available:

1.3.0~2318~g8f65051~snapshot
https://dl.mumble.info/mumble-1.3.0~2318~g8f65051~snapshot.msi
https://dl.mumble.info/mumble-1.3.0~2318~g8f65051~snapshot.winx64.msi

**Comment by Dreamerrrr** [comment]
@mkrautz As far as I can tell the problem is fixed. Thank you.

**Comment by mkrautz** [comment]
Excellent, thanks!
