### ISSUE TITLE
one-click update

### ISSUE THREAD

**Issue by magicrub** [mumble-voip/mumble#3048]
I'm running snapshots and the auto-updater is handy - great work guys/gals! However, I feel like when I do an update it asks me questions that it already has the answers for. Would be nice to skip all that and "just work" with a simple upgrade yes/no and then [magic happens] and restarts into new version without running the Windows install wizard.

After the boot-up update detection kicks in which asks to update I then choose...
yes, I'm sure I want to update (which it defaults to)
yes, install the same components I already have installed (which it defaults to)
yes, install to same directory (which it defaults to)
yes, start mumble when i'm done... of course. (which it defaults to).

As a programmer myself I know I like to leave excessive options available in beta testing like these snapshots but I think 99.9% of users on snapshots just click right through all those menus so it should be best designed for the usual case instead of the developer corner-case.

I have found that Skype and Chrome is a good UI example for quick auto/self-updates.

currently running 1.3.0~2318~g8f65051 on Windows 7 x64.

**Comment by mkrautz** [comment]
Yep, I wholeheartedly agree!

I hope to implement silent auto-updates in the 1.4.0 timeline. See https://github.com/mumble-voip/mumble/issues/1976 (which you've also commented on some time ago, heh!)

Closing this in favor of that bug.
