### ISSUE TITLE
Setting Certificate Via Command Line Windows

### ISSUE THREAD

**Issue by s3m1s0n1c** [mumble-voip/mumble#3052]
Hey Guys,

Would it be possible in the next update to add a syntax for windows to specify the certificate?

I ask this as I would like to run Multiple Mumbles with different certificates as they need to be registered to access a special room where each one feeds audio into from different Digital Radio Scanners.

I've tried using different directories with mumble in it but it seems to store the cert in registry of the last mumble you opened. when u open the 2nd one it uses the cert in the first instance.

Thanks
Sonic

**Comment by mkrautz** [comment]
Hi,

You should be able to use separate directories.
The trick is to place an empty file, mumble.ini in the directory. If that's present, Mumble will store its settings in there.

Please let us know if that works for you, thanks.

**Comment by s3m1s0n1c** [comment]
Yep, That works a treat 👍 

Thanks
Sonic
