### ISSUE TITLE
Add Windows 10 visual elements manifest

### ISSUE THREAD

**Issue by ElPumpo** [mumble-voip/mumble#3058]
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-visualelements
We'd need a white background that would blend in with the logo

**Comment by ElPumpo** [comment]
https://pastebin.com/td8J7YqK VS2017, *filename*.visualelementsmanifest.xml

**Comment by ElPumpo** [comment]
https://pastebin.com/PNh4F4PM 
![namnlos](https://cloud.githubusercontent.com/assets/12564301/25558488/0ccdb2c6-2d28-11e7-9c1b-42cc32ca9574.png)
Kinda works with the "new" logo, but there is a thin black circle around

**Comment by ElPumpo** [comment]
![namnlos](https://cloud.githubusercontent.com/assets/12564301/25558663/8e8f2292-2d2b-11e7-9df8-275cc12b4466.png)
`#FFFFFF` also works

**Comment by Tarun80** [comment]
Personally, I think the previous one looks better.

**Comment by ElPumpo** [comment]
Yea, I'm not a fan of the full white color, tried to remove the black circle, but noticed that it was a faded color from top to bottom. Let the art guys do a correct image

**Comment by Kissaki** [comment]
That’s only for store apps?

**Comment by ElPumpo** [comment]
@Kissaki no, it's when you pin a exe on the start menu (Windows 10)

**Comment by ElPumpo** [comment]
Any updates on this?

**Comment by davidebeatrici** [comment]
How does the tile look like without the visual manifest?

**Comment by ElPumpo** [comment]
Closing this issue as it seems abandoned

**Comment by Krzmbrzl** [comment]
@ElPumpo why haven't you created a PR? To me it seems as if you know what had to be changed? :thinking:

**Comment by ElPumpo** [comment]
Yes sorry I've been busy with other projects. If you're interested I'll for sure propose a pull request.

**Comment by Krzmbrzl** [comment]
No need to be sorry :)

Sure looks useful to me. Wouldn't it be better to use a logo with transparent background in this case instead of turning the background white?  That way I think it'd better blend in with the other icons, wouldn't it?

**Comment by Krzmbrzl** [comment]
In the Screenshot you showed all other icons are blue whereas Mumble is white

**Comment by ElPumpo** [comment]
Yes they are blue because that's what my windows theme thing is set to, I'll look into a transparent background

**Comment by Krzmbrzl** [comment]
Yeah then I think it'd be nice if Mumble's icon was blue as well.
However if having the white background is certainly better than what it is like right now. So if you think that you don't want to spend more time on this (at the moment), feel free to create a PR for that already. If we find a solution to make it transparent we can always patch that in later on :)

PS: I'll reopen this issue for now

**Comment by ElPumpo** [comment]
For your information the documentation for this can be found over at https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-visualelements I'll get a pr ready

**Comment by ElPumpo** [comment]
You know what.. I have no clue where in the project to put this file

**Comment by Krzmbrzl** [comment]
> You know what.. I have no clue where in the project to put this file

You said it has to be installed into the same directory as the Mumble executable, right? In that case the file should be placed in the ' installer' directory in this project and we/I have to figure out how to use WiX to install this file as well :point_up:

**Comment by Krzmbrzl** [comment]
I might have an idea on how this could be done, but I'm far from sure. I never really touched the installer code.

@trudnorx recently changed the installer and appeared very competent at doing so. Any chance you (@trudnorx) could point us in the right direction here?
Or maybe @davidebeatrici knows what has to be done :point_up:

**Comment by streaps** [comment]
I don't understand why it needs a white background?

**Comment by Krzmbrzl** [comment]
In order to not look like https://user-images.githubusercontent.com/12564301/50525936-fcb13480-0ade-11e9-974c-377506ad1847.png

**Comment by streaps** [comment]
Isn't it possible to use the round Mumble icon with a transparent background? 
https://github.com/mumble-voip/mumble/blob/master/icons/mumble.svg

The one in the screenshot looks like it has some aliasing / scaling issues.

**Comment by ElPumpo** [comment]
Transparent backgrounds aren't possible

**Comment by Krzmbrzl** [comment]
> Transparent backgrounds aren't possible

But if that is the case how does the virtual box entry work that is located to the left of the Mumble icon in your screenshot? Are they just using the same background color by accident?

**Comment by Krzmbrzl** [comment]
@zeroability found https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2019

According to that Windows should actually support alpha channels which would then allow for a transparent background. The question is: What kind of icon are we currently using? :thinking:

**Comment by ZeroAbility** [comment]
> @ZeroAbility found https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2019
> 
For context:
"32-bit ICO: for Project icons and Add Item. All ICO files are 32-bit true color with alpha-channel transparency (RGB/A). Because ICO files can store multiple sizes and color depths, Vista icons are often in an ICO format containing 16x16, 32x32, 48x48, and 256x256 image sizes. In order to display properly in Windows Explorer, ICO files must be saved-down to 24-bit and 8-bit color depths for each image size."

The cpack created installer in the new cmake build system uses the ico file.
https://github.com/davidebeatrici/mumble/blob/481db81f87835d2fcc1a3591979df38ee9fea405/cmake/packaging.cmake#L19
