### ISSUE TITLE
Channel Select for Multi Channel Devices

### ISSUE THREAD

**Issue by Wildcarde** [mumble-voip/mumble#3064]
We've run into somewhat of a unique problem that I'm not sure how to solve:
Client: windows x64

We are using mumble for low latency voice chat between MRI scanners by plugging a noise reducing microphone system into the computer to use as the voice source. However these devices have two channels coming out of them and only one is the actual voice.  The other channel is a 'trigger pulse' for keeping gear synchronized elsewhere in the system, a large analog pulse that's used for temporal alignment of recordings from multiple sources. It's also extremely loud to have blasted in your ear while having a conversation. While recording that information is important for other tasks, it's at best a nuisance to have piped over to the other MRI suite and at worst can be data ruining if it distracts the subjects too much. Since it appears as a single stereo microphone, everything gets compressed down to one channel and transmitted over. We would like to be able to select just the left or right channel from the microphone to transmit across mumble eliminating this problem.

We've attempted to solve this with a number of virtual audio device solutions but have thus far come up dry, it's possible this could be resolved using some other tool we've yet to discover however.

**Comment by mkrautz** [comment]
It should be doable in Mumble itself. I'll see what I can do.

**Comment by hcchang73** [comment]
I am following this feature. 
Does anyone know how to do it?

**Comment by mkrautz** [comment]
Hi, I've implemented something that I hope should help you work around your issue.

PR at https://github.com/mumble-voip/mumble/pull/3098

I've also created a ZIP archive of .reg files that'll:
 - Force Mumble to only use the left mic channel, or...
 - Force Mumble to only use the right mic channel, or...
 - Restore the default channel mask (include all channels).

[mumble-channelmask-regs.zip](https://github.com/mumble-voip/mumble/files/1016365/mumble-channelmask-regs.zip)

**Comment by Wildcarde** [comment]
Sounds good! I'll get some time scheduled to test it out.

**Comment by Wildcarde** [comment]
This may be a silly question but how do we know when this is integrated into the development snapshots? They don't seem to have a date attached to them that I could find and using the latest one (as of 3pm EST yesterday) didn't seem to honor the registry key updates.  Launching from a fresh install it would show that the microphone was transmitting, but no sound was actually being transmitted. If you go into the audio settings pane select the microphone and hit apply the audio would start being transmitted but unfortunately it includes both channels.

The researcher I'm working with has gotten channel selection working using the ASIO interface, unfortunately this is an exclusive interface so it can't be recorded out of band by another program like Audacity or the microphones included software. We could make this work with audacity by recompiling it to have ASIO support and using a splitter program I suspect but will have to test that solution.

**Comment by mkrautz** [comment]
Hi. I understand your frustration.

We had some issues with our Windows code-signing, and builds were blocked because of that.

A new build went out today, mumble-1.3.0~2407~g3754898~snapshot. It's available from https://www.mumble.info/. That version (and all future versions) has the feature.

**Comment by Wildcarde** [comment]
Sounds good, we will hopefully get to test this soon. Thanks again for the help with this!

**Comment by Wildcarde** [comment]
Got to test this today and it worked great. Thank you for the work on this, it's enabled a significantly simplified workflow for our researchers.

One odd behavior that may be worth reporting, the microphone didn't work until we opened the settings panel, made sure the mic was selected (it already was by default) and then hit 'ok' or 'apply'. After that transmission began as expected. The client is configured for continual transmission and very short (10ms) capture windows but those were the only settings that stood out to me.

**Comment by krono86** [comment]
Are there new info about this feature?
It would be wonderful for particular routing implementation.

**Comment by Krzmbrzl** [comment]
As #3098 has been merged into master, I'd expect this feature to be present in the 1.3.0 release...

**Comment by krono86** [comment]
I’m talking about something more feberal.
Suppose you want use multichannel audio interface, it would be nice to select the preferred input/output channels (mono or stereo) to be used by mumble to obtain the desired audio routing.

**Comment by Krzmbrzl** [comment]
Well I guess you have looked for it and from the top of my head I don't know that this is possible right now. I guess it's best if you create a separate feature requests issue for this.
