### ISSUE TITLE
Windows installer doesn't respect not creating shortcuts

### ISSUE THREAD

**Issue by ElPumpo** [mumble-voip/mumble#3087]
The installer creates shortcutrs to the executables even when un-checked from the installer..?

- Windows 10 v1703
- Latest snapshot

**Comment by mkrautz** [comment]
I cannot reproduce this with the latest snapshot, mumble-1.3.0-2505-g346702f-snapshot.msi.

Unchecking the desktop shortcut option does not create a desktop shortcut for me.
Neither for Mumble, nor Murmur. (Nor if I only install Mumble, or Murmur).

Closing... If you still encounter this problem, please let us know.

**Comment by mkrautz** [comment]
Note that the option in the installer is for desktop shortcuts only. Are you talking about other shortcuts, i.e. start menu entries, etc.?

**Comment by ElPumpo** [comment]
I'm on VACation atm, and yes I'm talking about desktop shortcuts

**Comment by ElPumpo** [comment]
Weird, but this issue fixed itself

**Comment by mkrautz** [comment]
:+1: Well, at least it's fixed. :-)
