### ISSUE TITLE
What do snapshot release filenames correspond to? [question]

### ISSUE THREAD

**Issue by AndrewJDR** [mumble-voip/mumble#3094]
On https://wiki.mumble.info/wiki/Main_Page, there are snapshot release downloads, such as:
mumble-1.3.0\~2389\~gdde8173~snapshot.msi

etc.

Is the "gdde8173" in the filename a git commit sha? If so, which repo can I find that sha in? I looked in this mumble repo, but didn't see a gdde8173 commit here. I want to be able to identify which commit a particular snapshot release corresponds to...

**Comment by Abextm** [comment]
The format, as I understand it, is:
`mumble-[version][~[commits since last version]~g[hash]~snapshot]`.
So 1.3.0 is 2389 commits ahead of 1.2.x at commit dde8173

**Comment by AndrewJDR** [comment]
@Abextm Thanks. Doh! I hadn't removed the 'g' off the front when copy/paste searching for the hash, my mistake.
