### ISSUE TITLE
latest windows update breaks bluetooth compatibility

### ISSUE THREAD

**Issue by hawkeye1889** [mumble-voip/mumble#3102]
I've used my plantronics voyager legend with mumble for years without any issues until the latest update `KB4020102`. I can select it in the devices list but no one can hear me. Once I uninstall this update I can use my headset without issue. I've tried other microphones and they work fine and even bought a new plantronics voyager legend as well as another brand of bluetooth headset with no luck. I've tried both version 1.2.9 and version 1.30 as well. So for now I'm using the Mac version with no issues.

**Comment by davidebeatrici** [comment]
Hi, is the issue still present?

**Comment by Krzmbrzl** [comment]
Closing due to not having received an answer to our questions
