### ISSUE TITLE
convert plaintext correctly

### ISSUE THREAD

**Issue by treaki** [mumble-voip/mumble#3105]
```
[20:04] An CCC : lücken ?>>>
[20:05] An CCC : 
[20:05] An CCC : 
[20:05] An CCC : unterschied??
[20:05] An CCC : 
[20:05] An CCC : 
[20:05] An CCC : unterschied?
```

the first empty message was like
```
"                       "
```
the second one like
```
"  "
```
so you see that there should be a difference but there isnt.

different messages entered in the chat area (`Type message to channel '$CHANNELNAME' here`) are distinguishable if you copy them out from the chat again.

Please fix that, thanks in advance

so we need to see the differences i would say
Messages have been entered in debians mumble 1.2.8-2

**Comment by treaki** [comment]
```
[20:18] An CCC : the first empty message was like " " the second one like " " so you see that there should be a difference but there isnt.
```

to see it on the same example, thats mumbles output on that message from the secound code block. So you dont see the difference but you should imho

**Comment by Kissaki** [comment]
Your text/second quote was very confusing. I reformatted your message to what I think you were trying to say.

The issue is that multiple spaces / whitespace are dropped?

Could you describe a use case for this? Why is it important to retain these? Just for correctness, or for more?

**Comment by treaki** [comment]
yes the problem is that multiple whitespace are dropped.

an possible use case would be the usage of ascii art

but for me it dose not need a particular use case but its a question of correct representation. There is no need for dropping whitespace but users expect that messages are transmitted as they have been entered (like on other chat systems like irc or jabber to)

**Comment by dstensnes** [comment]
Pasting code is annoying, because all indentation is lost, making it harder to read.

**Comment by mkrautz** [comment]
Our messages are HTML, which doesn't preserve whitespace.
If you need to preserve whitespace, wrap it in `<pre></pre>`.

**Comment by mkrautz** [comment]
But it should definitely be more user friendly to send messages that preserve whitespace...

**Comment by dstensnes** [comment]
@mkrautz ah, i thought html tags were filtered out all together. My bad then :)

**Comment by bontibon** [comment]
Duplicate #1838
