### ISSUE TITLE
-v option for murmur

### ISSUE THREAD

**Issue by concatime** [mumble-voip/mumble#3106]
Hi. I just want to know why the -v argument is for verbosity and not for version?
-v / --version should be for version
--verbose should be for verbosity
http://catb.org/~esr/writings/taoup/html/ch10s05.html
https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

**Comment by reelsense** [comment]
It's fairly common to use `-v` and `-V` for those. 

`ssh -v` is verbose. `ssh -V` is version.

**Comment by concatime** [comment]
Rekt. Ok, that's clear, thank you ;)

**Comment by reelsense** [comment]
It's a common question. I wondered it my self not to long ago.

**Comment by mkrautz** [comment]
Thanks, closing this as this seems to be answered.

**Comment by concatime** [comment]
And what about [POSIX](//stackoverflow.com/a/677212)?
