### ISSUE TITLE
Mumble does not rejoin room on reconnect

### ISSUE THREAD

**Issue by TheLastProject** [mumble-voip/mumble#3122]
I'm using Mumble with my girlfriend, who currently is dealing with a rather bad Internet connection causing frequent disconnects. Unfortunately, every time she reconnects, she has to manually rejoin our room, which is a rather annoying thing to have to deal with.

Is there any way Mumble could remember the room it was last active in and automatically rejoin that upon automatically reconnecting, instead of putting the user back in the lobby?

She's using the latest stable on macOS, for what it's worth.

**Comment by mkrautz** [comment]
If the user is registered to the server, it should move the user back into the channel they were in during their last session.

Is it possible she does not have a registered user account on the server?

**Comment by TheLastProject** [comment]
She indeed does not have an account, but the server owner has registrations disabled. I requested for them to be enabled. Good to know it at least should work when she can get an account.

I'll close this issue then unless we run into this with an account as well. Thanks for the quick response.
