### ISSUE TITLE
murmurd: fall of virtual servers in 9:00 UTC (everyday)

### ISSUE THREAD

**Issue by lexesv** [mumble-voip/mumble#3126]
Hello.

Murmur build from git source.

Every day at exactly 9:00 UTC virtual servers fall.
There are no errors in the logs.

I can not understand what is the problem?

QT compiled with Glib support.

Part of the logs
```
.....
5061|<6:(-1)> New connection: 169.54.233.124:10000|2017-06-09 08:41:57
5061|<6:(-1)> Connection closed: The remote host closed the connection [1]|2017-06-09 08:42:28
5061|<7:(-1)> New connection: 222.153.21.61:42565|2017-06-09 08:49:11
1|Server listening on 94.23.165.XXX:65000|2017-06-09 09:00:03
1|Failed to set IPV6_RECVPKTINFO for 94.23.165.XXX:65000|2017-06-09 09:00:03
1|Not registering server as public|2017-06-09 09:00:03
2|Server listening on 94.23.165.XXX:9999|2017-06-09 09:00:03
2|Failed to set IPV6_RECVPKTINFO for 94.23.165.XXX:9999|2017-06-09 09:00:03
2|Not registering server as public|2017-06-09 09:00:03
1582|Server listening on 94.23.165.XXX:60005|2017-06-09 09:00:03
....
```

**Comment by mkrautz** [comment]
What do you mean "fall"? I can see from the log that the vservers start listening again at around 9:00, but what happens before that? Do the vservers restart themselves? If not, why does it begin listening again at 9:00?

Thanks.

**Comment by lexesv** [comment]
My apologies.
The error turned out to be different.
The administrator made a mistake in the server scripts)))
Please close this issue.

**Comment by mkrautz** [comment]
Alright, no problem. Thanks. :-)
