### ISSUE TITLE
iOS 11 incompatible with 32 bit apps

### ISSUE THREAD

**Issue by innowintay** [mumble-voip/mumble#3129]
iOS 10 warns that Mumble will be incompatible with future updates to iOS (because it's a 32-bit app) All iOS apps must use 64-bit architecture once iOS 11 releases in Fall 2017.

**Comment by mkrautz** [comment]
Wrong issue tracker.

**Comment by mkrautz** [comment]
https://github.com/mumble-voip/mumble-iphoneos/issues/107
