### ISSUE TITLE
Request to change UI for private message

### ISSUE THREAD

**Issue by peylight** [mumble-voip/mumble#3131]
Hi
I think the private message system in the mumble is some difficult for users.
When we click to other users to chat together, for every message we had to click and see a pop-up for that!
And when the message sent the receiver will be see a something different message in the messages box.

Instead of that i think be better to change the UI like this:
When i click to another user show me a new tab in the messages box. so we can chat together or change between tabs to chat to other peoples or chat to channel.

Also i think no need to exist 2 tabs for Display and Source Text. So just move Source Text tab to Display icons beside "Insert Image" icon , "Insert Link" icon, ...  (so make a source icon for that)

In reality i love mumble and i think it's one of the best open source application. I want to make it better to people to be love it.
So if you think you need help i can help you.

**Comment by Kissaki** [comment]
I’m not sure I get (your first) issue. When I click on a user I can type messages and press enter to sent to him in the quickchat input. He then instantly sees it in the chat log. No popup necessary for either of these actions.

**Comment by Kissaki** [comment]
In the future, please create separate tickets for separate suggestions so they can be discussed and handled/closed independently. (Your Send message dialog suggestion on Display and Source tabs seems to be independent of your other suggestions.)

**Comment by peylight** [comment]
Ok sorry for two suggestions!
But i can't understand where is quickchat and how can i do that?
In the Plumble there are no problem. i mean by touch a person we can conversation for a long time without any problem.
I think there are a bug:
I click a person but when i chat in the quickchat my message will be send to the channel (not to guy)

I'm using [Kubuntu 17.04](http://www.kubuntu.org/) with the [Mumble PPA](https://launchpad.net/~mumble/+archive/ubuntu/release)

**Comment by dstensnes** [comment]
@peylight in settings, i believe under User interface, there is a setting that says "use selection as target for chat" or something similar. I don't have mumble in front of me right now, but this is probably your problem

**Comment by peylight** [comment]
@dstensnes yes i see
thank you very much

**Comment by Kissaki** [comment]
Does that solve your issue?

**Comment by peylight** [comment]
@Kissaki 
yes, be better to close this issue.
