### ISSUE TITLE
Allow entering URLs in the "address" entry field

### ISSUE THREAD

**Issue by n1trux** [mumble-voip/mumble#3143]
I frequently have the problem that if you send people the domain of your server in some chat application (Steam, WhatsApp, Telegram) the client automatically makes a link out of it.

So `example.org` becomes `http://example.org/`.

In my opinion the client should ditch the non-domain parts of the URL and just use the domain for connecting or at least throw an error that you have to enter the domain without `http://` or a trailing slash.

If developers choose to implement the first idea, another step would be adding the port from the URL automatically. So if somebody enters one of the following in the address field, it will get split up in the other respective entry fields:

    scheme://username:password@example.org
    username:password@example.org:64738
    scheme://username@example.org/something

In this case I'd ditch `scheme://` and `/something` as these are only entered mistakenly by users without knowledge of the proper format. Another approach would be to use "something" as label for the server.

**Comment by Kissaki** [comment]
IIRC we have logic for parsing mumble-URLs. If not, that is a similar use case.

**Comment by Kissaki** [comment]
I implemented the suggestion.

But in the "add new server" dialog we pre-fill if there is a mumble URL in the clipboard.

While I can agree that if a user CTRL+V pastes from clipboard that he probably has a domain/address for Mumble to use, this is not necessarily the case if he opens the add server dialog. A lot of people will have random web URLs (http/s) in the clipboard that have nothing to do with the server they want to add (type manually).

Will have to think about that, maybe add some more code to differentiate.

**Comment by Kissaki** [comment]
How do these programs handle `mumble://` URLs? Do they ignore it and add a `http://`? Do they show them as hyperlinks? Do they keep them as is as text?

**Comment by Kissaki** [comment]
The code in question is [`ServerItem::fromMimeData` ConnectDialog.cpp L359](https://github.com/mumble-voip/mumble/blob/455ab1921507fa211c711d39ebebf973a0e8d271/src/mumble/ConnectDialog.cpp#L359).

For your second suggestions, using the port from an URL, that [should already work](https://github.com/mumble-voip/mumble/blob/455ab1921507fa211c711d39ebebf973a0e8d271/src/mumble/ConnectDialog.cpp#L411).

**Comment by Kissaki** [comment]
Telegram Desktop leaves `mumble://example.com:500` as is as text. example.com:400 is converted to a hyperlink; with right click the link can be copied, but the hyperlink text stays without http, so if the user selects the text of the hyperlink and copies that (no URL schema), it will work with current Mumble as well.

**Comment by Kissaki** [comment]
#3182 Landed in master. Will be in the next 1.3.0 development snapshot release.
