### ISSUE TITLE
In GTA: San Andreas Multi Player, the mumble overlay blocks the display of the steam overlay

### ISSUE THREAD

**Issue by LOST100293** [mumble-voip/mumble#3144]
When I open San Andreas Multiplayer (SAMP) by steam to have a steam overlay in the game then when the mumble overlay is on, this steam overlay does not work. I have windows 10, and mumble latest version, development. I would ask for a repair. ;)

**Comment by davidebeatrici** [comment]
What happens if you enable Mumble's overlay while the game is running?

**Comment by LOST100293** [comment]
The overlay does not load in this way.

**Comment by davidebeatrici** [comment]
Is there something related to the overlay in Mumble's developer console?

**Comment by LOST100293** [comment]
I do not know how to check it out.

**Comment by LOST100293** [comment]
However, when trying to enable mumble when I am already in the game it plays after the attempt to minimize it gets done in the window and pops up 'gta.exe has stopped running'

**Comment by davidebeatrici** [comment]
First you need to enable it from: **Settings** -> **User Interface** -> **Application** -> **Enable Developer menu**.
Once you did that, you can open it by clicking on the **Developer** menu and then on **Developer Console...**.

**Comment by LOST100293** [comment]
<W>2017-06-29 20:43:29.902 DirectSound: Disabled as WASAPI is available
<W>2017-06-29 20:43:29.902 ASIO: No valid devices found, disabling
<W>2017-06-29 20:43:29.912 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<W>2017-06-29 20:43:29.914 CELT bitstream 8000000b from C:/Program Files/Mumble/Versions/1.3.0~2424~gd66eeeb~snapshot/celt0.0.7.0.dll
<W>2017-06-29 20:43:29.916 CELT bitstream 80000010 from C:/Program Files/Mumble/Versions/1.3.0~2424~gd66eeeb~snapshot/celt0.0.11.0.dll
<W>2017-06-29 20:43:29.916 Theme: "Mumble"
<W>2017-06-29 20:43:29.917 Style: "Dark"
<W>2017-06-29 20:43:29.917 --> qss: ":builtin/themes/Mumble/Dark.qss"
<W>2017-06-29 20:43:29.917 Locale is "pl_PL" (System: "pl_PL")
<W>2017-06-29 20:43:29.968 Database SQLite: "3.18.0"
<W>2017-06-29 20:43:29.976 Overlay: Listening on "\\\\.\\pipe\\MumbleOverlayPipe"
<W>2017-06-29 20:43:29.977 OverlayPrivateWin: overlay helper process 'C:\Program Files\Mumble\Versions\1.3.0~2424~gd66eeeb~snapshot/mumble_ol_helper.exe' started with PID 7056.
<W>2017-06-29 20:43:29.979 OverlayPrivateWin: overlay helper process 'C:\Program Files\Mumble\Versions\1.3.0~2424~gd66eeeb~snapshot/mumble_ol_helper_x64.exe' started with PID 456.
<W>2017-06-29 20:43:29.980 Updating application palette
<W>2017-06-29 20:43:30.151 AudioInput: Opus encoder set for VOIP
<W>2017-06-29 20:43:30.151 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2017-06-29 20:43:30.107 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2017-06-29 20:43:30.138 GlobalShortcutWin: GKeys initialized, isValid: 0
<W>2017-06-29 20:43:30.139 XboxInput: using XInput DLL 'XInput1_4.dll'
<W>2017-06-29 20:43:30.139 XboxInput: using XInputGetStateEx() as querying function.
<W>2017-06-29 20:43:30.139 GlobalShortcutWin: XboxInput initialized, isValid: 1
<W>2017-06-29 20:43:30.153 WASAPIInput: Latencies 100000 30000 => 100000
<W>2017-06-29 20:43:30.155 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2017-06-29 20:43:30.164 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Mysz Mysz:8 type 0x00000112 guid product {6f1d2b60-d5a0-11cf-bfc7-444553540000}
<W>2017-06-29 20:43:30.164 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Klawiatura Klawiatura:127 type 0x00000413 guid product {6f1d2b61-d5a0-11cf-bfc7-444553540000}
<W>2017-06-29 20:43:30.171 Adding device {7b640880-6f7c-11e6-8001-444553540000} USB Device USB Device:573 type 0x00010011 guid product {909009da-0000-0000-0000-504944564944}
<W>2017-06-29 20:43:30.173 Adding device {96ceb4f0-dc12-11e6-8001-444553540000} USB Audio Device USB Audio Device:5 type 0x00010011 guid product {00120d8c-0000-0000-0000-504944564944}
<W>2017-06-29 20:43:30.182 Adding device {7b667980-6f7c-11e6-8002-444553540000} SI Gaming Keyboard SI Gaming Keyboard:573 type 0x00010011 guid product {86030c45-0000-0000-0000-504944564944}
<W>2017-06-29 20:43:30.184 WASAPIInput: Mic Stream format 1
<W>2017-06-29 20:43:30.184 WASAPIInput: Stream Latency 0 (970)
<W>2017-06-29 20:43:30.185 Adding device {7b6d5750-6f7c-11e6-8004-444553540000} SI Gaming Keyboard SI Gaming Keyboard:3 type 0x00010011 guid product {86030c45-0000-0000-0000-504944564944}
<W>2017-06-29 20:43:30.185 AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2017-06-29 20:43:30.188 Adding device {7b6d5750-6f7c-11e6-8005-444553540000} USB Device USB Device:184 type 0x00010011 guid product {909009da-0000-0000-0000-504944564944}
<W>2017-06-29 20:43:30.239 WASAPIOutput: Output stream format 1
<W>2017-06-29 20:43:30.239 WASAPIOutput: Stream Latency 0 (2880)
<W>2017-06-29 20:43:30.239 WASAPIOutput: Periods 10000us 3000us (latency 0us)
<W>2017-06-29 20:43:30.239 WASAPIOutput: Buffer is 60000us (5)
<W>2017-06-29 20:43:30.240 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2017-06-29 20:43:31.099 OpenSSL Support: 1 (OpenSSL 1.0.2k  26 Jan 2017)
<W>2017-06-29 20:43:31.106 SSL: CA certificate filter applied. Filtered size: 114, original size: 114
<W>2017-06-29 20:43:31.106 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2017-06-29 20:43:31.108 ServerHandler: QOS2 loaded
<W>2017-06-29 20:43:31.124 libpng warning: iCCP: known incorrect sRGB profile
<W>2017-06-29 20:43:31.352 ServerHandler: Failed to add UDP to QOS
<W>2017-06-29 20:44:00.719 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2017-06-29 20:44:00.719 OverlayClient: Failed to cleanly disconnect:  "Nieznany błąd"
<W>2017-06-29 20:46:35.040 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:46:35.040 File  ""  failed to open
<W>2017-06-29 20:46:39.280 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:46:39.280 File  ""  failed to open
<W>2017-06-29 20:46:42.970 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:46:42.970 File  ""  failed to open
<W>2017-06-29 20:46:47.840 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:46:47.840 File  ""  failed to open
<W>2017-06-29 20:46:53.320 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:46:53.320 File  ""  failed to open
<W>2017-06-29 20:46:58.080 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:46:58.080 File  ""  failed to open
<W>2017-06-29 20:47:02.790 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:47:02.790 File  ""  failed to open
<W>2017-06-29 20:47:06.190 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:47:06.190 File  ""  failed to open
<W>2017-06-29 20:47:09.640 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:47:09.640 File  ""  failed to open
<W>2017-06-29 20:47:13.420 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:47:13.420 File  ""  failed to open
<W>2017-06-29 20:47:16.930 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:47:16.930 File  ""  failed to open

**Comment by LOST100293** [comment]
And in addition, it does not run at all on windows 10 when the samp is not running by steam.

**Comment by davidebeatrici** [comment]
That's because **gta_sa.exe** is not in the list of allowed programs, by default.

**Comment by LOST100293** [comment]
How to do by yourself to find Algo You will not do the whole situation as you need to?

**Comment by davidebeatrici** [comment]
**Settings** -> **Overlay** -> **Overlay Exceptions**.

**Comment by Kissaki** [comment]
```
<W>2017-06-29 20:43:29.977 OverlayPrivateWin: overlay helper process 'C:\Program Files\Mumble\Versions\1.3.0~2424~gd66eeeb~snapshot/mumble_ol_helper.exe' started with PID 7056.
<W>2017-06-29 20:43:29.979 OverlayPrivateWin: overlay helper process 'C:\Program Files\Mumble\Versions\1.3.0~2424~gd66eeeb~snapshot/mumble_ol_helper_x64.exe' started with PID 456.
```
Looks good.

```
<W>2017-06-29 20:44:00.719 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2017-06-29 20:44:00.719 OverlayClient: Failed to cleanly disconnect:  "Nieznany błąd"
<W>2017-06-29 20:46:35.040 QFSFileEngine::open: No file name specified
<W>2017-06-29 20:46:35.040 File  ""  failed to open
```
Is this when you launch the game? Or does this happen even when you only launch Mumble (and wait)?

Does the Mumble and Steam Overlay (and the combination) work fine in other games?
If you recently updated Mumble, did you restart your system?
In the situation in question, the Mumble overlay works fine? The Steam Overlay does not appear on shortcut press?

**Comment by Kissaki** [comment]
> When I open samp

Uh, does that mean San Andreas Multiplayer? Did you add that as a third party application?

**Comment by Kissaki** [comment]
In general we are not aware of conflicts between the two overlays. The questions above were not answered so I am labeling it needs-more-input.
