### ISSUE TITLE
My Server not added to the public internet servers

### ISSUE THREAD

**Issue by peylight** [mumble-voip/mumble#3145]
hello
why my server not added to the public internet servers two weeks ?
my server address: mumble.4gamers.ir

**Comment by Kissaki** [comment]
Please check your server log. What does it say regarding registration?

**Comment by reelsense** [comment]
I've had to wait ~4 days before I saw it on the list on first registration.

**Comment by Kissaki** [comment]
While it can take some time (hours), as far as I know it should not take days.

**Comment by Kissaki** [comment]
Feel free to reopen if you have new information/still need support.
