### ISSUE TITLE
Murmur connection bugs

### ISSUE THREAD

**Issue by HarpyWar** [mumble-voip/mumble#3146]
These issues are not fixed for many years, at least from 2012.
I don't know how to reproduce them, because it occurs randomly on different virtual servers. And this was only seen on high visited instances with many users connections. At least I didn't see this behavior on small instances.

### Issue 1
Current users sometimes increases up to max slots and greater. When counter reached max slots then nobody could not connect to server with the following error (several users still can be inside a server in that time):
```
[7:36:13] Server connection failed: The remote host closed the connection.
[7:36:23] Reconnecting.
[7:36:23] Server connection failed: The remote host closed the connection.
[7:36:33] Reconnecting.
[7:36:33] Server connection failed: The remote host closed the connection.
```
![image](https://user-images.githubusercontent.com/1132835/27778246-06dd81c6-5fc2-11e7-9347-86b61b62aa71.png)

[virtual server logs from the screenshot (linux, version 1.2.16).txt](https://github.com/mumble-voip/mumble/files/1118412/global.ban.txt)

This can be fixed **by restarting a virtual server**.

### Issue 2
Another issue occurs **only on Windows** which starts with mass users disconnects from many virtual servers at once and then users could not connect to part of virtual servers. Even if slots are not exceeded! (there are 500 slots are set on each server to bypass the first described issue)
Logs starts with many times `Timeout` and after that with many times `Connection closed:  [-1]`. Then nobody could not connect for part of servers, restarting a virtual server does not help and actually this can be fixed only **by restarting whole the instance**. 

Error on a client side the following:
```
[5:52:48 AM] Server connection failed: Connection timed out.
[5:52:58 AM] Reconnecting.
[5:53:28 AM] Server connection failed: Connection timed out.
[5:53:38 AM] Reconnecting.
[5:54:08 AM] Server connection failed: Connection timed out.
```
[excerpt from logs (windows, version 1.2.19).txt](https://github.com/mumble-voip/mumble/files/1118473/excerpt.from.windows.logs.txt)

**Comment by HarpyWar** [comment]
Second issue is duplicate of this https://github.com/mumble-voip/mumble/issues/1417

**Comment by toby63** [comment]
@Krzmbrzl Closing candidate.
Isn't a bot doing this?

**Comment by Krzmbrzl** [comment]
As the first issue described could very well be linked to the second one via #4277, I think all issues are basically covered in other issues. Thus I am closing this now. Feel free to complain if you think this should not be closed (and state why) though :point_up: 

@toby63 thanks for the hint :+1:
