### ISSUE TITLE
SRV Fallbacks cause disconnects

### ISSUE THREAD

**Issue by Abextm** [mumble-voip/mumble#3153]
Consider the following SRV records:

    Hostname                       Timeout  Record Priority Weight Port   Host
    _mumble._tcp.srv.sauville.org. 1800 IN  SRV    0        10     64738  badserver.sauville.org.
    _mumble._tcp.srv.sauville.org. 1800 IN  SRV    10       10     64738  localhost.
    _mumble._tcp.srv.sauville.org. 1800 IN  SRV    20       10     64738  sauville.org.

`badserver.sauville.org` has no records at all. It does not resolve.
`sauville.org` has a running copy of murmur

Assuming you do not have a murmur running locally, When you connect to srv.sauville.org it first tries to connect to [0::1], then 127.0.0.1, then finally lands on sauville.org. 25 seconds after connecting to sauville.org, the client disconnects from the server, and never tries to reconnect. The client prints `Disconnected from server`, while the server logs: `Connection closed: The remote host closed the connection`.

The Developer console prints:

    <W>2017-07-07 20:23:21.230 OpenSSL Support: 1 (OpenSSL 1.0.2k  26 Jan 2017)
    <W>2017-07-07 20:23:21.240 SSL: CA certificate filter applied. Filtered size: 190, original size: 190
    <W>2017-07-07 20:23:21.241 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
    <W>2017-07-07 20:23:21.242 ServerHandler: QOS2 loaded
    <W>2017-07-07 20:23:23.321 ServerHandler: connection attempt to [0::1]:64738 failed: Connection refused (0); trying next server....
    <W>2017-07-07 20:23:25.324 ServerHandler: connection attempt to 127.0.0.1:64738 failed: Connection refused (0); trying next server....

This is on version `1.3.0~2460~gc93b087~snapshot`, currently the latest

**Comment by mkrautz** [comment]
Thanks, I think this is because we don't properly delete tConnectionTimeoutTimer in ServerHandler.

**Comment by Abextm** [comment]
I just recompiled with #3154, It stays connected until the connection fails, then it reconnects to the highest priority that it can find. AFAIK this is fixed when the pull gets merged.

**Comment by davidebeatrici** [comment]
Pull request merged, thank you for the detailed report!
