### ISSUE TITLE
I can not drop images into the send message dialog

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#3159]
My input does not accept image drops. mkrautz was able to do so.

Am I doing something wrong? Is this an issue for others as well? Can we get into this state somehow? What else could cause this?

Windows 10, dragging from firefox or a local file.

* [ ] Check code
* [ ] Debug code in question (on a client with the issue)

**Comment by mkrautz** [comment]
It doesn't accept them at all? OK, I misunderstood. I thought it generated "links" instead of images.

It's actually pretty simple: Mumble with uiAccess=true doesn't accept drops.
Building with CONFIG+=no-elevation does allow drops.

**Comment by Kissaki** [comment]
It works on my local self-compiled version, but not on the snapshot.

**Comment by Kissaki** [comment]
I can not attach a debugger or view process information in procxp running as non-admin.

Dropping works after copying the Mumble folder into my documents folder and running it from there. So I guess this is a uiAccess issue?

**Comment by Kissaki** [comment]
With the settings in Shortcuts:

| Enable shortcuts in privileged applications | Enable Windows hooks | drop works |
| --- | --- | --- |
| false | false | true |
| true | false | false |
| false | true | true |

**Comment by Krzmbrzl** [comment]
Drag and drop for image is not possible with latest master (at least it should be).
Thus I am closing this issue.
