### ISSUE TITLE
TestServerResolver can fail irregularly

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#3162]
Apple travis build failed at first but after restarting it succeeded in #3160 with
```
FAIL!  : TestServerResolver::simpleA() Compared values are not the same
   Actual   (spy.count()): 0
   Expected (1)          : 1
   Loc: [TestServerResolver.cpp(86)]
FAIL!  : TestServerResolver::simpleAAAA() Compared values are not the same
   Actual   (spy.count()): 0
   Expected (1)          : 1
   Loc: [TestServerResolver.cpp(125)]
```

**Comment by mkrautz** [comment]
I think this should just be attributed to the fact that network tests in general are flakey.
But let's see if it's something that happens more often -- if so, we should take action.

**Comment by Kissaki** [comment]
ServerResolver makes use of the static method `QHostInfo::lookupHost` (no mocking). We test with network addresses.

We use

```
QTestEventLoop loop;
loop.enterLoop(5);
```

to wait for the signal.

No docs for `QTestEventLoop` exist. The implementation uses `QEventLoop` and `QEventLoop::exec` with a timer for timeouting.

From the [docs}(http://doc.qt.io/qt-4.8/qeventloop.html) I understand that it creates a new event loop. We only make use of the timeout, so I don’t get why we don’t just use a timer.

It happened once on our travis env, so if we have such a network dependency I would increase the time (10s?) to prevent future false positives. Given that it happened once it will surely happen again.

**Comment by mkrautz** [comment]
The reason we use QTestEventLoop is:
https://github.com/mumble-voip/mumble/commit/8068772e82279e8de08e0af5ad2998fe967632d0

**Comment by Kissaki** [comment]
Oh I see. Code equivalent, not only logic equivalent.
I really don’t like that these tests can fail like that, but ok, let’s wait for the next occurrence.

**Comment by Kissaki** [comment]
Failed in #3166 and master.
I guess it’s time to raise the timeout.
