### ISSUE TITLE
SelfSignedCertificate: no newline at EOF

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#3175]
From the internal Jenkins for CentOS/Ermine:

	g++ -c -include release/murmurd -pipe -std=c++98 -fvisibility=hidden -Wall -Wextra -Werror -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/include -isystem /MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/include -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include -isystem /MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I../mumble_proto -isystem ../mumble_proto -isystem murmur_ice -O2 -pthread -Wall -W -D_REENTRANT -fPIC -DMUMBLE_VERSION=1.3.0~2488~gd817937~snapshot -DSNAPSHOT_BUILD=1 -DUSE_BUILDENV -DRESTRICT=__restrict__ -DMUMBLE_VERSION_STRING=1.3.0 -DMURMUR -DUSE_DBUS -DUSE_ICE -DUSE_BONJOUR -DUSE_QSSLDIFFIEHELLMANPARAMETERS -D_REENTRANT -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../../3rdparty/arc4random-src -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/ZeroC-Ice/include -Imurmur_ice -I../../3rdparty/qqbonjour-src -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/include -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/include/avahi-compat-libdns_sd -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include/QtNetwork -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include/QtSql -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include/QtXml -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include/QtDBus -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/include/QtCore -Irelease -I/MumbleBuild/centos-ermine-1.3.x-2017-06-03-f0df4cd-863~dirty/Qt5/mkspecs/linux-g++ -o release/SelfSignedCertificate.o ../SelfSignedCertificate.cpp
	../SelfSignedCertificate.cpp:280:2: error: no newline at end of file

**Comment by davidebeatrici** [comment]
Fixed by #3176.
