### ISSUE TITLE
Include problem compiling murmur with ice 3.7

### ISSUE THREAD

**Issue by IdleGandalf** [mumble-voip/mumble#3210]
Trying to compile murmur with ZeroC Ice 3.7, getting the following compile error:

`slice2cpp --checksum -I/usr/local/share/Ice -I/usr/share/Ice/slice -I/usr/share/slice -I/usr/share/Ice-3.7.0/slice/ ../Murmur.ice
/home/giovanni/.cache/aursync/murmur-snapshot-ice/src/mumble-1.3.0~2523~g5aaf1ed~snapshot/src/murmur/Murmur.ice:14: error: Can't open include file "Ice/SliceChecksumDict.ice"
    #include <Ice/SliceChecksumDict.ice>
1 error in preprocessor.
`

I noticed that the mentioned ice file exists, but is in a different directory: `/usr/share/ice/slice/Ice/SliceChecksumDict.ice`, while the include is set to `/usr/share/Ice/slice`

Just wanted to clear if this is a change in the Ice folder structure or if it is just the PKGBUILD file that's messing up. I checked the PKGBUILD that compiled ice and it doesn't seem to set this directory path structure anywhere.

**Comment by davidebeatrici** [comment]
What operating system are you on?

**Comment by IdleGandalf** [comment]
That's Archlinux.
