### ISSUE TITLE
Mumble Overlay: number of characters displayed before ...

### ISSUE THREAD

**Issue by webwizrd** [mumble-voip/mumble#3216]
Hi there,

I have a feature request for the overlay: Names in the overlay get cut off after 10 characters and then "..." is appended. Can this be made configurable?

Thanks!

**Comment by mkrautz** [comment]
It is configurable, but it is not very discoverable.

If you go to Settings -> Overlay, you can right click the "user list" widget in the overlay preview. A menu pops up, and you select Edit.

This allows you to configure the display of the overlay, including increasing the size of the username text boxes.

Hope it helps!

**Comment by mkrautz** [comment]
Please let me know if this fixes the problem for you. :-)

**Comment by webwizrd** [comment]
Perfect!
I was confused because I got the "hand" movement indicator when I hovered
over the TEXT box, also over the edges of the box.
But when you click, it changes to the sizing arrows.

Thanks for the quick response!
Andy
