### ISSUE TITLE
1.3.x client hangs on reconnect when connection lost

### ISSUE THREAD

**Issue by Grandpa-G** [mumble-voip/mumble#3220]
When there is an interruption of the internet connection for the client, and the connection is restored the client will try to reconnect. If there are several attempts and then the connection is restored, the client will hang indefinitely if the connection was made via a dns name. There will be a terminal warning "unable to resolve hostname" and a message on the client "reconnecting" and nothing further will happen. However, if the connection was made via an ip address instead, the reconnect seems to work every time.

using https://dl.mumble.info/mumble-1.3.0~2523~g5aaf1ed~snapshot.tar.gz.sig recompiled on raspberry pi with qt5.

**Comment by mkrautz** [comment]
I believe the correct fix would be to emit the disconnected signal at
https://github.com/mumble-voip/mumble/blob/master/src/mumble/ServerHandler.cpp#L296

Something like

    emit disconnected(HostNotFoundError, QString::fromLatin1("Unable to resolve hostname"));
    return;

**Comment by mkrautz** [comment]
...However, that might not work, because the server is not yet in the "connected" state, i.e. this signal:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/ServerHandler.cpp#L326

**Comment by mkrautz** [comment]
Ah, OK. The reconnect timer is only *started* when we get the disconnect signal from ServerHandler:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/MainWindow.cpp#L3008

However, as I said above, triggering the disconnected signal on resolver errors would not be totally right.
It might work for you as a quick workaround, but I think the correct solution would be to add another error for errors that happen before the connection is established (perhaps that's just resolver errors...), and hook it up into MainWindow to trigger the reconnect timer as well.

**Comment by mkrautz** [comment]
There should probably also be a "resolver" error triggered by not being able to connect to any of the hosts that we resolve:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/ServerHandler.cpp#L398

**Comment by Grandpa-G** [comment]
Just adding the emit as indicated in the first response seems to work well. The client keeps trying to resolve the name and as soon as the connection comes back the connection is established. I will use this solution for now.
