### ISSUE TITLE
[Documentation] CentOS 7 Installation wiki-entry missing dependency hint

### ISSUE THREAD

**Issue by Kharag** [mumble-voip/mumble#3232]
Hello, 

I compiled Mumble from source according to the wiki-entry:
https://wiki.mumble.info/wiki/Install_CentOS7

If you proceed to start murmur you get a Zombie process, described in this old bugreport:
https://sourceforge.net/p/mumble/bugs/542/
Installing 'redhat-lsb-core' with yum solved the problem but I think it should be mentioned in the Wiki-Entry (maybe in the Finishing up Section as a hint of some sort)

**Comment by davidebeatrici** [comment]
Hello,

Thank you very much for your report!

I updated the Wiki page: https://wiki.mumble.info/index.php?title=Install_CentOS7&diff=9973&oldid=9803
