### ISSUE TITLE
Changing TLS certificate invalidates client access tokens

### ISSUE THREAD

**Issue by C0rn3j** [mumble-voip/mumble#3233]
As per title.

When I refresh my TLS certificate from Let's Encrypt(which happens every two months) Linux desktop Mumble client (1.3.0 - 2017.08.24) "forgets" the access tokens for that server.

This seems like an overly paranoid feature - I don't see why the AT should be forgotten if the new certificate is considered valid by the client.

Also is there any way to make rooms prompt for access token? Having to go to Server>Access_tokens is too inconvenient especially when there's nothing that tells you that that's what you should do.

**Comment by promi** [comment]
I can confirm this, several users lost their access codes and we were wondering why.

It doesn't make sense the way it is now.

**Comment by Krzmbrzl** [comment]
Tracked via #4544
