### ISSUE TITLE
 Enhance positional audio with sound physics

### ISSUE THREAD

**Issue by SelfSealShelf** [mumble-voip/mumble#3234]
Is there any way to integrate sound physics into the positional audio plugin? Attenuation, reverb, occlusion? It would require the client to obtain additional information from the game or simulated environment, namely the size of the chamber the player is currently in, the shape of it (possibly simplified), and the texture of the surrounding environment (hard or soft).

As it stands the volume reduction by distance feature doesn't make a lot of sense without walls blocking sound. Players can be 2m apart separated by a 10cm metal wall and hear each other perfectly. Texture is also more important than initially apparent though, as a curtain or cloth would register as a wall with only a geometric analysis. Occlusion might be undesirable for some players who would quickly realize they have to yell at their computer microphones to be heard, but would still be an amazing feature for situations like cooperative puzzle solving.

More advanced things probably aren't necessary, but could include sound cancelation, pressure/altitude/propagation medium (sorta the same thing), etc. 

Implementing multiple different methods of obtaining map data would maximize compatibility. For games that can't have their map data extracted a 3-d replica could be created by users, then mumble could correlate position data from the game to the user provided map, then run the changes to the voice data stream. Games with variable maps such as sandboxes and procedurally generated games usually have more easily extracted map data, while fixed maps are more easily replicated but often difficult to extract.

A few successful user experiences could set the precedent for game designers to incorporate compatibility with mumble's positional audio by default.

**Comment by Krzmbrzl** [comment]
This is now tracked as part of #6597
