### ISSUE TITLE
Favorites disappear after restarting computer

### ISSUE THREAD

**Issue by bigbooner** [mumble-voip/mumble#3235]
Today, my computer randomly froze while having mumble and I had to restart it. After the restart, I tried to join mumble back but my favorites servers where gone. I checked mumble's appdata folder and my mumble.sqlite was there. I was wondering if it got corrupted and if I still get back my favorites.

**Comment by Kissaki** [comment]
`%APPDATA%\mumble.sqlite` indeed stores the favorites in the `servers` table.
If you have windows File History enabled you can restore an earlier version of the file. If you have any other backup mechanism, that.

Mumble itself does not store backups of `mumble.sqlite`. So if the file was indeed corrupted and repaired/replaced, there is little hope that it exists elsewhere still if neither of the above is the case.

As it is in %APPDATA% (roaming) - you're still on the same windows user account, right?
Did added friends preserve?
