### ISSUE TITLE
Audio wizard problem in Raspberry Pi 3

### ISSUE THREAD

**Issue by lpvm** [mumble-voip/mumble#3236]
Hi,

I don't know if I should address the official build, but nonetheless I'll present my problem.  

With raspbian 9, when trying to setup mumble default client, in the audio wizard, there are several options for ALSA cards.  I have the stock RPi, no extra sound card installed.  Tried all the possibilities, but could never hear the sound sample that I can hear in my desktop computer.  Please see attached image with the shown output 
![20170918_rpi_mumble_audio_wizard](https://user-images.githubusercontent.com/7320067/30544945-105b59f8-9c80-11e7-94c7-04c356a733c3.png)
devices for ALSA.

Audio in RPi seems fine, as I can play a mp3 file.

With OSS, got no luck.
I've also installed PulseAudio, tried all options as well, but none worked, too.

Can you please guide me to solve this issue? 
Thanks.

**Comment by toby63** [comment]
Is this still an issue?

@Krzmbrzl Otherwise outdated.

**Comment by cjhien** [comment]
have the same problem with RPI4B. It is a pity that mumble client can't work with Raspberry Pi while the server work perfectly.
