### ISSUE TITLE
Compile error on freebsd from git

### ISSUE THREAD

**Issue by Chris2000SP** [mumble-voip/mumble#3241]
I have compiled mumble from git and get an error:

```
./AudioInput.h:61:62: error: redefinition of parameter 'RESTRICT'
  ...typedef void (*inMixerFunc)(float * RESTRICT, const void * RESTRICT, uns...
                                                                ^
./AudioInput.h:61:39: note: previous declaration is here
                typedef void (*inMixerFunc)(float * RESTRICT, const voi...
                                                    ^
```
i have tried it a couple times and get the same error.

Compiler: LLVM
QT5:

Any ideas?

**Comment by mkrautz** [comment]
What command line did you use to build Mumble?

For Unix-like system, RESTRICT is defined here:
https://github.com/mumble-voip/mumble/blob/696e968/qmake/compiler.pri#L218

Can you see from the compiler output whether `-DRESTRICT=__restrict__` is being passed to the compiler?

**Comment by Chris2000SP** [comment]
`/usr/local/lib/qt5/bin/qmake -recursive CONFIG="no-bundled-celt no-embed-qt-translations no-server no-g15 no-speechd no-bonjour no-11x no-portaudio no-pch no-vld no-plugin no-alsa no-bundled-speex no-bundled-opus no-update no-pulseaudio no-xevie" main.pro`
I have checked the original ports Makefile and read it to get the right configs.
`clang++ -c -pipe -g -std=gnu++1z -Wall -W -pthread -fPIC -DSNAPSHOT_BUILD -DMUMBLE_VERSION_STRING=1.3.0 -DMUMBLE -DUSE_MANUAL_PLUGIN -DUSE_OPUS -DUSE_DBUS -DNO_UPDATE_CHECK -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../../3rdparty/arc4random-src -I../../3rdparty/qqbonjour-src -I../../3rdparty/smallft-src -Iwidgets -isystem /usr/include/celt -I../../3rdparty/opus-src/celt -I../../3rdparty/opus-src/include -I../../3rdparty/opus-src/src -I../../3rdparty/opus-build/src -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtSvg -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtSql -I/usr/local/include/qt5/QtXml -I/usr/local/include/qt5/QtDBus -I/usr/local/include/qt5/QtCore -I../../debug/.moc/mumble -I../../debug/.ui/mumble -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o ../../debug/.obj/mumble/Log.o Log.cpp
clang++ -c -pipe -g -std=gnu++1z -Wall -W -pthread -fPIC -DSNAPSHOT_BUILD -DMUMBLE_VERSION_STRING=1.3.0 -DMUMBLE -DUSE_MANUAL_PLUGIN -DUSE_OPUS -DUSE_DBUS -DNO_UPDATE_CHECK -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../../3rdparty/arc4random-src -I../../3rdparty/qqbonjour-src -I../../3rdparty/smallft-src -Iwidgets -isystem /usr/include/celt -I../../3rdparty/opus-src/celt -I../../3rdparty/opus-src/include -I../../3rdparty/opus-src/src -I../../3rdparty/opus-build/src -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtSvg -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtSql -I/usr/local/include/qt5/QtXml -I/usr/local/include/qt5/QtDBus -I/usr/local/include/qt5/QtCore -I../../debug/.moc/mumble -I../../debug/.ui/mumble -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o ../../debug/.obj/mumble/AudioConfigDialog.o AudioConfigDialog.cpp
In file included from AudioConfigDialog.cpp:41:
./AudioInput.h:61:62: error: redefinition of parameter 'RESTRICT'
                typedef void (*inMixerFunc)(float * RESTRICT, const void * RESTRICT, unsigned int, unsigne...
                                                                           ^
./AudioInput.h:61:39: note: previous declaration is here
                typedef void (*inMixerFunc)(float * RESTRICT, const void * RESTRICT, unsigned int, unsigne...`

I think not but you can read your self if i'm wrong.

**Comment by mkrautz** [comment]
It's not passing `-DRESTRICT=__restrict__` for some reason... Thanks! I'll take a look.

**Comment by Chris2000SP** [comment]
Thanks a lot!

**Comment by Chris2000SP** [comment]
in ports there is an update available for [murmur](https://www.freshports.org/audio/murmur/) and [mumble](https://www.freshports.org/audio/mumble/).

I have build it from ports today and it works very well, so i think we can close this issue.

**Comment by davidebeatrici** [comment]
Excellent, thank @feld for the port!
