### ISSUE TITLE
How to increase priority of mumble server (linux, debian)

### ISSUE THREAD

**Issue by thejustsoul** [mumble-voip/mumble#3242]
During installation of the package in debian, you can choose the option "Allow mumble-server to use higher priority?", how to do the same, but without the installation package to the system, i.e. when using a portable (just unpacked from archive) version of murmur (on debian stable)? 

And yet, tell me how to stop the server, not using systemd\init.d, only in bash (killall murmur.x86 is the right thing to complete the process or otherwise need)?

**Comment by davidebeatrici** [comment]
Yes, killing **murmur.x86** tells it to exit, unless you forcibly kill it.

As of the priority, you should ask the package mantainer's what it does specifically.

You can contact him via [email](mailto:Chris.Knadle@coredump.us).
