### ISSUE TITLE
Commit d2943a5 prevents mumble client from receiving UDP audio on arch

### ISSUE THREAD

**Issue by matmemo** [mumble-voip/mumble#3256]
I have built the current version of the mumble client (53c5a9172) with the mumble-git pkgbuild from the arch user repository.

Afterwards the client didn't play back any incoming audio, nor did it change the avatar symbols of others when they were speaking. My audiostream was still audible for others and I saw my avatar reacting to voice activation.

On IRC I was told to try the force TCP mode as a workaround, which did work.

By bisecting I found that commit d2943a5 introduced the problem. Dabbling a little with the changes I found that reverting line 710 in src/mumble/ServerHandler.cpp (from that commit) back to the version before (deleting Qt::QueuedConnection from the connect call) fixes the problem.

**Comment by davidebeatrici** [comment]
Thank you very much for the detailed report.

The problem doesn't seem to be present on Windows, which leads me to think that it's a Qt bug.

I'm going to create a pull request as soon as possible.

**Comment by matmemo** [comment]
You're very welcome. I'm glad if it helped and points you in the right direction.

**Comment by davidebeatrici** [comment]
Merged, thank you again.

**Comment by compuguy** [comment]
@davidebeatrici Do you know when this will be built/uploaded to the snapshot ppa? The current snapshot build has this bug.
