### ISSUE TITLE
Random audio glitch

### ISSUE THREAD

**Issue by Elinvention** [mumble-voip/mumble#3258]
On Mumble master audio stops randomly while other people are talking. When they stop talking and then start talking I'm able to hear them again. This is especially annoying when listening to music via mumbledj, because it won't output any music until the next track starts playing. If I mute mumbledj locally and then unmute, it works, but then it stops again after a random time.
I tried with both 1.3 and 1.2.8 server on debian testing.

**Comment by davidebeatrici** [comment]
Which client version are you using?

**Comment by Elinvention** [comment]
With Mumble master I mean not yet released 1.3.0

**Comment by davidebeatrici** [comment]
Have you tried with the latest 1.2.x release?

**Comment by Elinvention** [comment]
Yes, I have no problem with client and server 1.2.8

**Comment by davidebeatrici** [comment]
Is your 1.3.0 client built from the latest commit? It fixes a problem where our UDP system fails, maybe that's what you're experiencing.

**Comment by Elinvention** [comment]
I remember I had no problem with 1.3.0 some month ago. Maybe I can try git bisect.

**Comment by Elinvention** [comment]
Yes, latest commit.

**Comment by davidebeatrici** [comment]
Can you try to build from commit a8d8c136b68ab4502ec0cd08bd9e876b39d4c1ed and report back, please?

**Comment by Elinvention** [comment]
Same issue.

By the way I compiled with this configuration:

```qmake main.pro -recursive CONFIG+=no-server CONFIG+=optimize CONFIG+=no-crash-report CONFIG+=no-speechd CONGIG+=no-update```

I also tried with `CONFIG+=no-bundled-opus`

**Comment by davidebeatrici** [comment]
Do you have the same problem with Mumble 1.2.8 and Murmur compiled from latest commit?

**Comment by Elinvention** [comment]
No, it's fine.

**Comment by davidebeatrici** [comment]
Doing a `git bisect` is the best way, I don't have any more clues on where the problem could be.

**Comment by Elinvention** [comment]
Ok thank you for your time.

**Comment by davidebeatrici** [comment]
You're welcome.

**Comment by Elinvention** [comment]
Nope... it's a strange issue, I tried to build older version from January 2017, but the issue is still there.
Now it happens less times, than when I reported the issue. It seems there is something odd with my system...

**Comment by davidebeatrici** [comment]
@Elinvention Are you using PulseAudio?

**Comment by Elinvention** [comment]
Yes, I am using PulseAudio. However this evening I made some tests and I couldn't reproduce the issue anymore. It's gone! Thanks.
