### ISSUE TITLE
Server group icons

### ISSUE THREAD

**Issue by preterive** [mumble-voip/mumble#3261]
Hello,
i wish Server group icons because a normal user don't know the rank of another user.

**Comment by bendem** [comment]
Duplicate of https://github.com/mumble-voip/mumble/issues/1632

**Comment by davidebeatrici** [comment]
Hello, @preterive!

As pointed out by @bendem, there's already an open issue requesting the same feature.
Please write in #1632 if you want to give input on how the feature should be.
