### ISSUE TITLE
[Windows] mumble audio config corrupted (?)

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#3266]
Ok so first I don't know how to reproduce the issue and it might be a unique situation, so if you want to just close the issue that's fine too.

So I *think* the audio config for mumble got corrupted somehow. One of the side effect was that my audio input wouldn't work. 

There was a weird problem with` Transmission`>`Voice Activity`
the 2 sliders were placed at the same position as I left them but the black-green-brown bar above wouldn't match the sliders

Another quirk is that when i tried rerunning the audio wizard I could hear my input for a very short window when switching the drop down menu for my choice of input between `Default device` and `Logitech microphone` (the default device points to the logitech microphone). 

I tried reinstaling the problem but that didn't seem to help. It resolved itself when I removed mumble from HKEY_CURRENT_USER>Software>Mumble, that triggered a full restart of the audio settings and solved the issue.

**Comment by hydroflame** [comment]
I have managed to dig in a bit more, when I unplug/replug my headset, the

**Comment by hydroflame** [comment]
i managed to dig in a bit more, when I unplug-plug my headset it gets now temporarely corrupted (the sliders dont match the black-brown-green bar but if I just click apply without touching anything else, mumble re picks up my mic
