### ISSUE TITLE
My mouse's polling rate is unstable while Mumble is running.

### ISSUE THREAD

**Issue by assbutt69** [mumble-voip/mumble#3271]
I am using 1.2.19 on Windows 7. My mouse is a Logitech G102. When Mumble is not running, my mouse polls correctly at a constant 499hz. When Mumble is running it is unstable and polls anywhere from 500-600. If I close Mumble it polls correctly again.

**Comment by davidebeatrici** [comment]
How are you measuring the polling rate?

**Comment by assbutt69** [comment]
I'm using mouserate.exe.

**Comment by davidebeatrici** [comment]
Closing in favor of #3275.
