### ISSUE TITLE
URL pointing to the latest server snapshot

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3274]
From IRC:
```
<adde> is there are possiblity to get a linux server binary symlink to latest instead of version number because i have a automatic docker generator that download mumble server binary file when i create it
```

Something like https://dl.mumble.info/murmur-static_x86-1.3.0-latest?

**Comment by Kissaki** [comment]
This is implemented in the new website mumble-www which will land in the coming days. URL path will be for example `/downloads/windows-64/snapshot`.
