### ISSUE TITLE
LAN network not showing up

### ISSUE THREAD

**Issue by CodeGuro** [mumble-voip/mumble#3280]
This is done on a fresh install of BlackArch Linux, though I suspect a similar issue may occur with other arch distributions.

After I start the mumble server with `sudo systemctl start murmur`, and run `mumble`, on the same machine I get a list of mumble servers in the public domain but none in my wireless LAN group. However, I can still connect to the mumble daemon by adding it in for 'localhost' hostname/domain manually. I happen to have another machine, and am also able to connect to the to the machine running the daemon if I set the configurations to connect to an internal IP (10.x.x...)

This leads me to believe that this isn't a WIFI or firewall issue but is in fact an issue with mumble. Particularly the network discovery mechanism for internal WIFI networks. My internal devices cannot 'see' each other's servers but can still connect if configured to do so manually.

Setting up a mumble client and murmur server with default configurations on the specified distribution I mentioned above should be sufficient to reproduce this problem.  If it helps, I use `pacman` package manager to do the installations for me.

**Comment by reelsense** [comment]
This is normal. If you want local service announcements install the `avahi` _ZeroConf/bonjour_ dependencies on the server and the clients.

**Comment by CodeGuro** [comment]
Thank you @reelsense
