### ISSUE TITLE
Show notification in tray icon

### ISSUE THREAD

**Issue by thejustsoul** [mumble-voip/mumble#3283]
When receive message, Mumble shows it in the tray in the tooltip, and then it disappears. And it is impossible to see if there are new messages if the program is minimized.
If possible, tell how to enable it? If not, add flashing in the taskbar during receiving a message, and let the flashes until the message is read, plus the tray icon may displays the received message in the form of envelope for example.
`OS Windows 7, Mumble Stable 1.2.19`

**Comment by davidebeatrici** [comment]
The window highlight feature is now available.

I'm changing the name of the pull request for the tray icon notification feature request.

**Comment by thejustsoul** [comment]
When to wait for a release or developer build?

**Comment by davidebeatrici** [comment]
We are going to build a new snapshot as soon as #3356 is addressed.

**Comment by Krzmbrzl** [comment]
This has been introduced with #3354
