### ISSUE TITLE
Automatic user cert, not created in 1.3.0~2586 (64 bit)

### ISSUE THREAD

**Issue by Geraner** [mumble-voip/mumble#3284]
I realised that I can't "Register users" when running Mumble version 1.3.0~2586~g894ade2~snapshot.
Running this version both as server version (Linux) and windows version.
When connecting with Stable Client 1.2.19, the option "Register user" is not available either.

**Comment by reelsense** [comment]
Have you recently upgraded an existing mumble server?

Were you previously authorized in the server ACL?

Are you currently authorized in the server ACL?

**Comment by Geraner** [comment]
Upgraded the Mumble server through normal PPA Mumble repository when the updated snapshot was available.
No changes done on the ACL. Server admin can’t register new users. I also have set up that registered users can register new users. But this stopped working as well.

**Comment by Geraner** [comment]
I found the reason for the problem.
If you are running 1.3.2586 snapshot version the first time, Mumble offers you to create a Automatic Cert.
It looks like this cert is never created, which is resulting that the users who have the right to register new users, can't register any user. The next time, the new user starts 1.3.2586 again, the user is asked again to create an automatical certificate. (Usually Mumble asks only once, at the first startup after a new installation).
So it looks the problem is related to Error in Automatic Cert creation with this built. (64 bit version tested). - When creating an self signed cert, everthing is working well.

**Comment by bontibon** [comment]
Just ran into this issue as well.

Traced it a back a little bit:  [this branch in SelfSignedCert.cpp is taken](https://github.com/mumble-voip/mumble/blob/3ffd9ad3ed18176774d8e1c64a96dffe0de69655/src/SelfSignedCertificate.cpp#L265-L269)

**Comment by mkrautz** [comment]
Thanks @bontibon 

We need to refactor SelfSignedCertificate::generate a bit to work better with client certs.
Right now we use the presence of a client cert name/email as a flag to determine whether or not we're generating a client or server cert.

Instead, we should probably add an enum and pass that to ::generate.

Alternatively, the code should be refactored into a SelfSignedCertificateBuilder.
Then you could set the type (server/client) on the builder, along with the common name, email, etc. you'd want.
