### ISSUE TITLE
Murmur Crashing on WinServer 2012

### ISSUE THREAD

**Issue by prakash8083** [mumble-voip/mumble#3292]
My murmur was working fine past one year. After an update on Google cloud windows server, Murmur is crashing during startup. 

I've attached the windows crash logs below. 

[Console.txt](https://github.com/mumble-voip/mumble/files/1596898/Console.txt)
[Console1.txt](https://github.com/mumble-voip/mumble/files/1596899/Console1.txt)

**Comment by mkrautz** [comment]
Why is it called MYSBTVoIP.exe?

Does it also crash with Murmur from www.mumble.info?

It seems to me like the program is trying to use DLLs that you don't have.
The error code 0x0xc0000135 is STATUS_DLL_NOT_FOUND.

**Comment by prakash8083** [comment]
Why is it called MYSBTVoIP.exe?
**I just changed its name from murmur to MYSBTVoIP**

Does it also crash with Murmur from www.mumble.info?
**I tried reinstalling the app from mumble website. I've also verified the dlls. Its there.**

**Comment by mkrautz** [comment]
OK, I suppose we should check whether it also happens on a clean install of Windows Server 2012.
I assume it's Windows Server 2012 and not 2012 R2?

**Comment by mkrautz** [comment]
If anyone wants to try to reproduce/fix this, feel free.
