### ISSUE TITLE
libmumble.so: undefined symbol: glPopClientAttrib

### ISSUE THREAD

**Issue by OlliC** [mumble-voip/mumble#3293]
Hi, 

i am using mumble 1.2.19 on Arch Linux and see this errors in the terminal: 

```
Plugins: Failed to load libmumble.so: Cannot load library /usr/lib/mumble/libmumble.so: (/usr/lib/mumble/libmumble.so: undefined symbol: glPopClientAttrib)
Plugins: Failed to load libmumble.so.1: Cannot load library /usr/lib/mumble/libmumble.so.1: (/usr/lib/mumble/libmumble.so.1: undefined symbol: glPopClientAttrib)
Plugins: Failed to load libmumble.so.1.2: Cannot load library /usr/lib/mumble/libmumble.so.1.2: (/usr/lib/mumble/libmumble.so.1.2: undefined symbol: glPopClientAttrib)
Plugins: Failed to load libmumble.so.1.2.19: Cannot load library /usr/lib/mumble/libmumble.so.1.2.19: (/usr/lib/mumble/libmumble.so.1.2.19: undefined symbol: glPopClientAttrib)

```

Although it cannot load libmumble.so it seems to work fine now.

**Comment by davidebeatrici** [comment]
Hi,

This happens because Mumble tries to load **libmumble.so** as if it was a (positional audio) plugin, don't worry about it.

Could you write here the list of files you have in **/usr/lib/mumble**, please?

Thank you!

**Comment by mkrautz** [comment]
Note: only the log entries are because of what @davidebeatrici says. (They're harmless.)

Your original issue post also included problems with voice activication. Are you still seeing those?

**Comment by lynxthecat** [comment]
For me mumble-overlay is broken when trying to use mono (to play Zero-K):

```
mumble-overlay mono Zero-K.exe 
set
set
mono: symbol lookup error: /usr/lib64/mumble/libmumble.so.1: undefined symbol: glPopClientAttrib
```

**Comment by OlliC** [comment]
These are the files i have in /usr/lib/mumble: 

```
-rwxr-xr-x 1 root root 91840 13. Dez 05:24 libcelt0.so
-rwxr-xr-x 1 root root 91840 13. Dez 05:24 libcelt0.so.0
-rwxr-xr-x 1 root root 91840 13. Dez 05:24 libcelt0.so.0.11
-rwxr-xr-x 1 root root 91840 13. Dez 05:24 libcelt0.so.0.11.0
-rwxr-xr-x 1 root root 75456 13. Dez 05:24 libcelt0.so.0.7
-rwxr-xr-x 1 root root 75456 13. Dez 05:24 libcelt0.so.0.7.0
-rwxr-xr-x 1 root root  9936 13. Dez 05:24 liblink.so
-rwxr-xr-x 1 root root 46968 13. Dez 05:24 libmanual.so
lrwxrwxrwx 1 root root    19 13. Dez 05:24 libmumble.so -> libmumble.so.1.2.19
lrwxrwxrwx 1 root root    19 13. Dez 05:24 libmumble.so.1 -> libmumble.so.1.2.19
lrwxrwxrwx 1 root root    19 13. Dez 05:24 libmumble.so.1.2 -> libmumble.so.1.2.19
-rwxr-xr-x 1 root root 22128 13. Dez 05:24 libmumble.so.1.2.19
```

No i dont have the voice activation problems anymore. I just assumed this error messages have something to do with it. I was playing around with pasuspender and ardour5 and after that mumble had some weird problems with voice activation. I could see mic input with Signal-To-Noise ratio activation but not with Raw amplitude from input activation and with both it didnt actually work, meaning nobody could here me. Dont know what the problem was. After a reboot it worked.
