### ISSUE TITLE
Symbol lookup error glPopClientAttrib

### ISSUE THREAD

**Issue by lynxthecat** [mumble-voip/mumble#3296]
For me (also Archlinux) mumble-overlay is broken when trying to use mono (to play Zero-K):

mumble-overlay mono Zero-K.exe 
set
set
mono: symbol lookup error: /usr/lib64/mumble/libmumble.so.1: undefined symbol: glPopClientAttrib
Can be reproduced easily by simply running 'mumble-overyaly mono', resulting in the same error.

**Comment by mkrautz** [comment]
The overlay library on Linux expects the target process to be directly linked with libGL.

We'd need to change that to fix this.

**Comment by lynxthecat** [comment]
It certainly also used to load OK before, at least mono would launch, though I have a feeling that the overlay would work initially but then not survive an alt-tab and back, though my memory may be failing.

**Comment by lynxthecat** [comment]
Any workaround before this is resolved?

**Comment by mkrautz** [comment]
It seems to me that Arch is building the overlay library wrong.

If you get symbol lookup errors like that, it would seem that Arch is building the library with hardened compiler flags, although we try not to:

https://github.com/mumble-voip/mumble/blob/master/overlay_gl/overlay_gl.pro#L30-L31

...Which Arch package are you using? We should try to fix that.

**Comment by mkrautz** [comment]
Another problem is the fact that running Zero-K.exe does not pass on environment variables to the underlying Spring engine... If there's a way to run it without the launcher, you could probably get the overlay in there.

**Comment by lynxthecat** [comment]
Thanks for comments. This is just using the stock Archlinux mumble package:

https://www.archlinux.org/packages/community/x86_64/mumble/

**Comment by mkrautz** [comment]
Since you're using Mumble 1.2.19, it seems my fix for this isn't yet in a stable release... due to our slow release cycle :'( Sorry about that.

The fix I'm talking about is https://github.com/mumble-voip/mumble/commit/859da4dabec070959b5c06f8d32512990d7ec9c2

So my theory about Arch building with hardened flags was wrong. The default in 1.2.19 is to build with `-z now` by default. While in 1.3.x we use `-z lazy` to allow processes to not have the libGL symbols.

We should backport https://github.com/mumble-voip/mumble/commit/859da4dabec070959b5c06f8d32512990d7ec9c2 to the upcoming 1.2.20 release.

**Comment by davidebeatrici** [comment]
Fixed in #3307.

**Comment by kusky3** [comment]
still broken, same error
both mumble and muble-git on arch

**Comment by Krzmbrzl** [comment]
what's "mumble-git"?

We recently overhauled the wrapper script. Did you try with latest master?

**Comment by kusky3** [comment]
mumble-git is the package name in the arch linux aur. it is pulled form git and built from source.

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/0af10cdd959b664dc010d55afa3b9218d716958d/overlay_gl/CMakeLists.txt#L22-L25

Are perhaps the compiler options being overridden?

**Comment by ZeroAbility** [comment]
It seems like this hasn't been updated since October:
https://aur.archlinux.org/packages/mumble-git/

**Comment by Krzmbrzl** [comment]
In addtition their versioning schemeis wrong. They build with cmake (and thus they are building 1.4.0) but it is marked as version 1.3.0.rc2.r1004.gf5489231a

**Comment by Krzmbrzl** [comment]
@radioactiveman afaik you are a maintainer of the mumble AUR package. Do you have any thoughts on this issue?

**Comment by radioactiveman** [comment]
> It seems like this hasn't been updated since October:
> https://aur.archlinux.org/packages/mumble-git/
> 
This doesn't matter since it is a git package, meaning it fetches always the latest master branch before a build.

> Their PKGBUILD is also out of date but does not have anything that appears to modify the link options:
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mumble-git

No, it is not out-of-date. Same reason as above. And yes, link options are not modified.

> In addition their versioning scheme is wrong. They build with cmake (and thus they are building 1.4.0) but it is marked as version 1.3.0.rc2.r1004.gf5489231a

No, it is not wrong. It follows the [Arch VCS guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function). Since there is no 1.4.0 tag, it is currently 1.3.x.r[number of commits since this tag] and auto-generated on every build. So it is not required to update it in the PKGBUILD file itself.

**Comment by radioactiveman** [comment]
> https://github.com/mumble-voip/mumble/blob/0af10cdd959b664dc010d55afa3b9218d716958d/overlay_gl/CMakeLists.txt#L22-L25
> 
> Are perhaps the compiler options being overridden?

Arch Linux uses these defaults:
https://github.com/archlinux/svntogit-packages/blob/packages/pacman/trunk/makepkg.conf#L42

Attached is a full (verbose) [build log](https://github.com/mumble-voip/mumble/files/5681321/build.log.tar.gz), I hope this helps.
Linking the overlay is done at line 332.

**Comment by davidebeatrici** [comment]
I think `-z,now` is overriding `-z,lazy`.

**Comment by radioactiveman** [comment]
>  I think `-z,now` is overriding `-z,lazy`.

@davidebeatrici:
Because the order matters? In this case it may help to specify the BEFORE parameter.
See also: https://cmake.org/cmake/help/git-stage/command/target_link_options.html

**Comment by davidebeatrici** [comment]
Yep, I think that's the issue.

**Comment by Krzmbrzl** [comment]
@davidebeatrici will you do this or shall I do so?

**Comment by davidebeatrici** [comment]
Feel free to do it.

**Comment by Krzmbrzl** [comment]
Okay so if I understood this correctly we simply want to change
https://github.com/mumble-voip/mumble/blob/bf9550a68e30b77d2d7b63094022244d26c6fd50/overlay_gl/CMakeLists.txt#L22-L25
to
```
target_link_options(overlay_gl BEFORE
	PRIVATE
		"-Wl,-z,lazy"
)
```
right?

**Comment by davidebeatrici** [comment]
Yep, should work.

**Comment by carlocastoldi** [comment]
after hours of trying, I finally managed to get it working. For future people stumbling into this problem I suggest trying to launch 32bit games preloading libGL 32bit as well.

On steam you can do it by changing the launch options to `LD_PRELOAD=/usr/lib/mumble/libmumbleoverlay.x86.so:/usr/lib32/libGL.so %command%`

I tested it with Team Fortress 2.
I am on Manjaro. I assume it should work on Arch Linux as well
