### ISSUE TITLE
Roadmap/Qt5-based release

### ISSUE THREAD

**Issue by tgurr** [mumble-voip/mumble#3300]
As Qt4 is EOL since December 2015 and distributions and other packages (e.g. poppler) start phasing out Qt4 support and Qt4-based packages, is there any time frame for releasing a Mumble/Murmur version based on Qt5? Also there have been so many great enhancements made in git master which don't reach the end users and I couldn't find any indication or roadmap of when to expect a release or for when it is planned.

Getting bug fixes, improvements and new features in sure is always great but it's not like Mumble isn't usable like it is (we for example package a git snapshot of 1.3.0 since quite a while).

**Comment by stikonas** [comment]
This issue is a duplicateo a previous one (https://github.com/mumble-voip/mumble/issues/2728)

**Comment by mkrautz** [comment]
Closing in favor of #2728.
