### ISSUE TITLE
MumbleDJ playback broken after #3311

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3325]
@Athernar [reports](https://github.com/mumble-voip/mumble/pull/3311#issuecomment-360573089) that MumbleDJ doesn't work anymore after commit 0b5579c.

> Something in this recent string of commits broke mumbledj playback, mumbledj appears to be operating correctly (python and ffmpeg subprocesses spawn and terminate as expected) but no transmission is seen from the bot in mumble itself. Reverting murmur to an earlier commit restores functionality.

**Comment by davidebeatrici** [comment]
I tested both code snippets, the behavior is the same.

Test project at https://github.com/davidebeatrici/UDPMessageType_Test.

**Comment by Athernar** [comment]
In my testing I did try reverting to older revisions of go and youtube-dl, along with trying the precompiled binary on the mumbledj project page to no avail.

Possible GCC bug maybe? I am running Arch so GCC is a fairly recent build, I'll try an older release and report back when I have the opportunity.
