### ISSUE TITLE
registerLocation should not depend on certificate C or registerHostname

### ISSUE THREAD

**Issue by AlD** [mumble-voip/mumble#3328]
Through #1784 a restriction on registerLocation was implemented, to only accept the provided value if at least 1 of these 2 conditions is true:
* The TLD of `registerHostname` matches the country code provided in `registerLocation`.
* The server certificate isn't self-signed and the certificate country (`C=`) matches `registerLocation`.

IMHO this doesn't work very well in a number of situations:
- FQDN doesn't have a CCTLD (e.g. _.info_) → Neither requirement can be fulfilled, so server has to be in-country.
- Target language doesn't actually match server location, e.g. one may want to run a server for Icelandic speakers in Thailand.
- Countries like Germany, Austria, Switzerland share a common language and the location of the server doesn't matter with regards to network latency, language or even culture.

It's not clear to me what these restrictions are trying to protect against in the first place. Latency is a much better indicator of server connectivity and I think the location categorization would work much better as a signal for target audience.
Additionally it's also trivial to circumvent these checks.

So, easiest solution would be to simply lift the restrictions on `registerLocation` and let people choose freely where their server should show up.

Following the logic of separating signals for connectivity (for which we have Ping) and target audience, we could instead replace `registerLocation` with e.g. `registerLanguage` and show that in the server list. That's obviously a significantly larger effort with backwards compatibility implications, though.

@klausenbusk, @hacst, appreciate your comments :)

**Comment by mkrautz** [comment]
I think the original restriction was put in place as a way to restrict commercial hosts from "spamming" all countries with their servers, for visibility purposes.

I agree that it's kind of silly to require servers to use a ccTLD or a certificate with C set (in these Let's Encrypt times).

**Comment by mkrautz** [comment]
@Kissaki @davidebeatrici @Natenom @bontibon Thoughts? Should we drop these requirements? It seems like hacst and I are for.

**Comment by davidebeatrici** [comment]
Let's drop them.

**Comment by Natenom** [comment]
Drop.

**Comment by otavioarj** [comment]
There is any schedule for this issue? 
I have a GCloud server, running murmur with Let's Encrypt cert (C=US), where the end node of the cloud is at Brazil (latency of 5-10 in Brazil), but the TDL is .net and the I.P's block is from US-California. 

My server is showing at N.A-USA, but having about 120-150 ms of latency there. Setting `registerLocation` to BR results in the following error: `Registration: Registration updated [Location does not match hostname country code. Ignored unverified certificate]`

No brazilians will see the server, and no american will connect, as the higher latency.

**Comment by davidebeatrici** [comment]
I propose to rely on GeoIP for the server categorization, drop `registerLocation` and implement a field that defines the accepted languages.

That way a user can easily distinguish between servers that are closer and servers on which the desired language is effectively accepted.

**Comment by Krzmbrzl** [comment]
Sounds good to me

**Comment by Kissaki** [comment]
Our Client Connect Dialog shows servers explicitly categorized by location. Continent first, country second (it’s “Germany”, not “German”).

I can see how languages spoken on the server could be a useful view of the public server list. But the current implementation and presentation allows for that.

So I agree with your suggestion. If we geolocate servers server side there is no use in the `registerLocation` setting. And languages spoken on the server is a related but independent feature addition that would be useful.

**Comment by Krzmbrzl** [comment]
> Our Client Connect Dialog shows servers explicitly categorized by location. Continent first, country second (it’s “Germany”, not “German”).

From 1.4.0 onwards that's no longer true. We don't split the list by location anymore :point_up:

**Comment by davidebeatrici** [comment]
`registerLocation` is now ignored by our registration script, the location is deduced through [IP2Location](https://lite.ip2location.com/database/ip-country).

**Comment by Krzmbrzl** [comment]
@davidebeatrici so basically we can close this issue then?

**Comment by AlD** [comment]
My intention was to be able to freely choose the country or rather languages for a server. It looks like the country information will not be customizable anymore, so I think having a languages preference exposed in the server browser would still be very useful.

**Comment by Krzmbrzl** [comment]
Yes such a festure would be useful indeed. Howevee I don't think that this matches the original title of thid issue. Thus a new dedicated issue might be better :thinking:

**Comment by davidebeatrici** [comment]
Yep, I proposed the idea in https://github.com/mumble-voip/mumble/issues/3328#issuecomment-728637315.

New issue created: #4742
