### ISSUE TITLE
Another MXE mirror problem

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#3333]
From https://travis-ci.org/mumble-voip/mumble/jobs/338776781:
`E: Failed to fetch https://dl.mumble.info/mirror/pkg.mxe.cc/repos/apt/debian/pool/main/m/mxe-i686-w64-mingw32.static-gcc/mxe-i686-w64-mingw32.static-gcc_5.4.0-20170208_amd64.deb  GnuTLS recv error (-9): A TLS packet with unexpected length was received.`

**Comment by mkrautz** [comment]
Not a website issue. Not a P1 (release blocker).

**Comment by ZeroAbility** [comment]
> From https://travis-ci.org/mumble-voip/mumble/jobs/338776781:

This appears to be passing now? Please confirm.

**Comment by Krzmbrzl** [comment]
We used to have passing MXE builds but now we actually dropped support for it again, since MXE does jot provide all required libraries and they were not helpful when I tried to port the missing library (Poco) to it :shrug:

As such, I think this issue cam be closed.
