### ISSUE TITLE
Push to talk not working with Corsair K68 on Windows 10

### ISSUE THREAD

**Issue by dmullaney** [mumble-voip/mumble#3343]
Since getting this new keyboard - mumble push to talk down't work at all... I've tried setting to multiple different keys, running as admin, running the snapshot build, reinstalling - still not working.

**Comment by davidebeatrici** [comment]
Is there something related to the problem in the developer console's log?

**Comment by mkrautz** [comment]
What version of Mumble? If this is 1.3.0 snapshots, could you try to disable Settings -> Shortcuts -> Enable shortcuts in privileged applications?

And if that doesn't work, try disabling Settings -> Shortcuts -> Enable Windows hooks?

**Comment by mkrautz** [comment]
No replies to this from the reporter.

I will close this, as it's inactive. If the problem persists, please ping this thread or make a new one. Thanks!
