### ISSUE TITLE
Output cuts out on my end/Input still works

### ISSUE THREAD

**Issue by pepper-ann** [mumble-voip/mumble#3345]
This problem is especially annoying because I don't know it happens until I become aware of the long silence on the other end. I can still transmit sound but I don't hear anything. When I restart Mumble, my push to talk doesn't work for a good minute, after which point it works fine. That is, until the output eventually cuts out again. I haven't noticed any pattern as to what could be causing it. I have tried running in adminstrator mode with no luck.

**Comment by mkrautz** [comment]
What platform, audio system, and version of Mumble are you experiencing this on?

**Comment by pepper-ann** [comment]
Sorry..

Windows 10, realtek driver 6.0.1.7806, Mumble 1.2.19

**Comment by davidebeatrici** [comment]
Could you install the latest snapshot and see if the issue persists, please?

**Comment by pepper-ann** [comment]
Are you referring to 1.3.0~2586~g894ade2~snapshot?

**Comment by davidebeatrici** [comment]
Yes.

**Comment by pepper-ann** [comment]
Ok it is installed, I'll report back after using it later tonight or tomorrow. Thanks!

**Comment by davidebeatrici** [comment]
You're welcome, thank you!

**Comment by pepper-ann** [comment]
So same issue persists. Also with this snapshot, I noticed that mumble freezer for about a half a minute when I select "connect" from the list of servers.

**Comment by davidebeatrici** [comment]
Is there something related to the issue in the developer console's log?

**Comment by pepper-ann** [comment]
I don't have a way to view that, let me figure out how to use it and I'll
try to recreate the issue while the log is recording.

**Comment by davidebeatrici** [comment]
To enable it:
`Settings -> User Interface -> Enable Developer menu`

Then you can view it by clicking on "Developer" from the main window's menu and then on "Developer Console..."

**Comment by pepper-ann** [comment]
Here is the developer console log, I was in mumble for a bit and then the problem occurred. I verified that they could hear me, but I couldn't hear anyone else. 

`<W>2018-03-03 13:56:39.767 DirectSound: Disabled as WASAPI is available
<W>2018-03-03 13:56:39.767 ASIO: No valid devices found, disabling
<W>2018-03-03 13:56:39.797 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<W>2018-03-03 13:56:39.799 CELT bitstream 8000000b from C:/Program Files (x86)/Mumble/Versions/1.3.0~2586~g894ade2~snapshot/celt0.0.7.0.dll
<W>2018-03-03 13:56:39.801 CELT bitstream 80000010 from C:/Program Files (x86)/Mumble/Versions/1.3.0~2586~g894ade2~snapshot/celt0.0.11.0.dll
<W>2018-03-03 13:56:39.803 Theme: "Mumble"
<W>2018-03-03 13:56:39.803 Style: "Lite"
<W>2018-03-03 13:56:39.804 --> qss: ":builtin/themes/Mumble/Lite.qss"
<W>2018-03-03 13:56:39.804 Locale is "en_US" (System: "en_US")
<W>2018-03-03 13:56:39.862 Database SQLite: "3.18.0"
<W>2018-03-03 13:56:39.863 Bonjour: Failed to load dnssd.dll
<W>2018-03-03 13:56:39.863 Overlay: Listening on "\\\\.\\pipe\\MumbleOverlayPipe"
<W>2018-03-03 13:56:39.867 OverlayPrivateWin: overlay helper process 'C:\Program Files (x86)\Mumble\Versions\1.3.0~2586~g894ade2~snapshot/mumble_ol_helper.exe' started with PID 3824.
<W>2018-03-03 13:56:39.870 OverlayPrivateWin: overlay helper process 'C:\Program Files (x86)\Mumble\Versions\1.3.0~2586~g894ade2~snapshot/mumble_ol_helper_x64.exe' started with PID 13012.
<W>2018-03-03 13:56:39.873 Updating application palette
<W>2018-03-03 13:56:40.122 AudioInput: Opus encoder set for VOIP
<W>2018-03-03 13:56:40.123 AudioInput: 72000 bits/s, 48000 hz, 480 sample
<W>2018-03-03 13:56:39.946 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2018-03-03 13:56:40.095 GlobalShortcutWin: GKeys initialized, isValid: 0
<W>2018-03-03 13:56:40.096 XboxInput: using XInput DLL 'XInput1_4.dll'
<W>2018-03-03 13:56:40.096 XboxInput: using XInputGetStateEx() as querying function.
<W>2018-03-03 13:56:40.096 GlobalShortcutWin: XboxInput initialized, isValid: 1
<W>2018-03-03 13:56:40.128 WASAPIInput: Latencies 100000 30000 => 100000
<W>2018-03-03 13:56:40.128 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Mouse Mouse:8 type 0x00000112 guid product {6f1d2b60-d5a0-11cf-bfc7-444553540000}
<W>2018-03-03 13:56:40.129 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Keyboard Keyboard:127 type 0x00000413 guid product {6f1d2b61-d5a0-11cf-bfc7-444553540000}
<W>2018-03-03 13:56:40.137 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2018-03-03 13:56:40.157 WASAPIOutput: Output stream format 1
<W>2018-03-03 13:56:40.157 WASAPIOutput: Stream Latency 0 (1056)
<W>2018-03-03 13:56:40.157 WASAPIOutput: Periods 10000us 3000us (latency 0us)
<W>2018-03-03 13:56:40.157 WASAPIOutput: Buffer is 22000us (1)
<W>2018-03-03 13:56:40.158 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2018-03-03 13:56:40.194 Adding device {603dbd20-f12d-11e6-8001-444553540000} Corsair STRAFE Gaming Keyboard Corsair STRAFE Gaming Keyboard:4096 type 0x00010011 guid product {1b151b1c-0000-0000-0000-504944564944}
<W>2018-03-03 13:56:40.203 WASAPIInput: Mic Stream format 1
<W>2018-03-03 13:56:40.203 WASAPIInput: Stream Latency 0 (1056)
<W>2018-03-03 13:56:40.210 WASAPIInput: Echo Stream format 1
<W>2018-03-03 13:56:40.210 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2018-03-03 13:56:40.212 Adding device {7e16f710-f12f-11e6-8002-444553540000} Corsair composite virtual input device Corsair composite virtual input device:1024 type 0x00010011 guid product {1bf01b1c-0000-0000-0000-504944564944}
<W>2018-03-03 13:56:40.217 AudioInput: ECHO CANCELLER ACTIVE
<W>2018-03-03 13:56:40.426 libpng warning: iCCP: known incorrect sRGB profile
<W>2018-03-03 13:56:48.113 OpenSSL Support: 1 (OpenSSL 1.0.2k  26 Jan 2017)
<W>2018-03-03 13:56:48.186 SSL: CA certificate filter applied. Filtered size: 110, original size: 110
<W>2018-03-03 13:56:48.186 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2018-03-03 13:56:48.188 ServerHandler: QOS2 loaded
<W>2018-03-03 15:24:09.509 AudioInput: Opus encoder set for VOIP
<W>2018-03-03 15:24:09.510 AudioInput: 72000 bits/s, 48000 hz, 480 sample
<W>2018-03-03 15:24:09.511 WASAPIInput: Latencies 100000 30000 => 100000
<W>2018-03-03 15:24:09.513 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2018-03-03 15:24:09.570 WASAPIInput: Mic Stream format 1
<W>2018-03-03 15:24:09.570 WASAPIInput: Stream Latency 0 (1056)
<W>2018-03-03 15:24:09.584 WASAPIOutput: Output stream format 1
<W>2018-03-03 15:24:09.584 WASAPIOutput: Stream Latency 0 (1056)
<W>2018-03-03 15:24:09.584 WASAPIOutput: Periods 10000us 3000us (latency 0us)
<W>2018-03-03 15:24:09.584 WASAPIOutput: Buffer is 22000us (1)
<W>2018-03-03 15:24:09.587 WASAPIInput: Echo Stream format 1
<W>2018-03-03 15:24:09.587 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2018-03-03 15:24:09.587 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2018-03-03 15:24:09.587 AudioInput: ECHO CANCELLER ACTIVE`

**Comment by pepper-ann** [comment]
So after leaving the developer console open for a long time, I was able to pinpoint the entries that occured when the sound cuts out:

> <W>2018-03-11 10:25:36.047 WASAPINotificationClient: Default device changed flow= 0 role= 1 device "{0.0.0.00000000}.{dade4e67-55f9-4413-b5c2-825f5a4e94cf}"
> <W>2018-03-11 10:25:36.099 WASAPINotificationClient: Default device changed flow= 0 role= 0 device "{0.0.0.00000000}.{dade4e67-55f9-4413-b5c2-825f5a4e94cf}"
> <W>2018-03-11 15:58:35.788 WASAPINotificationClient: Default device changed flow= 0 role= 1 device "{0.0.0.00000000}.{6186de92-785e-41b5-962c-6b65b63adf83}"
> <W>2018-03-11 15:58:35.789 WASAPINotificationClient: Default device changed flow= 0 role= 0 device "{0.0.0.00000000}.{6186de92-785e-41b5-962c-6b65b63adf83}"
> <W>2018-03-11 18:57:37.922 WASAPINotificationClient: Default device changed flow= 0 role= 1 device "{0.0.0.00000000}.{dade4e67-55f9-4413-b5c2-825f5a4e94cf}"
> <W>2018-03-11 18:57:37.922 WASAPINotificationClient: Default device changed flow= 0 role= 0 device "{0.0.0.00000000}.{dade4e67-55f9-4413-b5c2-825f5a4e94cf}"
> <W>2018-03-11 19:03:38.039 WASAPINotificationClient: Default device changed flow= 0 role= 1 device "{0.0.0.00000000}.{6186de92-785e-41b5-962c-6b65b63adf83}"
> <W>2018-03-11 19:03:38.046 WASAPINotificationClient: Default device changed flow= 0 role= 0 device "{0.0.0.00000000}.{6186de92-785e-41b5-962c-6b65b63adf83}"

any ideas?

**Comment by pepper-ann** [comment]
updates:

still getting the same issue. it's very frustrating

i got new headphones, 
windows 10 pro 1709
audio driver: 10.0.16299.15
corsair void 

any help will be very appreciated

**Comment by Krzmbrzl** [comment]
I think this is the same issue as https://github.com/mumble-voip/mumble/issues/5421. Since we have some more active discussion over there, I'll close this issue in favor of the linked one
