### ISSUE TITLE
One way tunnel echoing trouble

### ISSUE THREAD

**Issue by CrumbleZ** [mumble-voip/mumble#3352]
Me and a group of friends have had this issue for as long as we can remember.

We all hear myself echoing through another user. but only him. Therefore we're having much trouble to pinpoint if the problem are his or my settings.

If the problem is unclear, imagine 4 users in the same channel : 
When User1  speaks, => User1, User2 and User3 hear an echo through User4 (as if User4 was speaking)
When any other user speaks => there's no echo whatsoever

We have tried changing many settings, but nothing fixes the issue.

What additional information can we provide to help pinpoint the issue and determine whether this is a bug or a settings problem.

Thanks in advance.

**Comment by mkrautz** [comment]
Well, it depends on that user's setup.

Does that user use headphones, or speakers?

If it is speakers, make sure Mumble has echo cancellation enabled. (Settings -> Audio Input.. Near the top, there's a drop-down called Echo Cancellation).

If it's headphones, I'd make sure Echo Cancellation is enabled there, too.
However, I'd also try to get the user to check whether there is some kind of crosstalk between the headphone's speakers and the microphone, which could cause the audio being played in the user's headphones to be mixed in with the microphone input.

If the user enables the Mumble audio wizard (Configure -> Audio Wizard...) while playing music or other audio, does the microphone pick up that audio? Should be possible to tell from, for example, the Volume Tuning part of the wizard...

Hope it helps.
