### ISSUE TITLE
Add "Hotbutton" (Icon ) 

### ISSUE THREAD

**Issue by teknoskillz** [mumble-voip/mumble#3357]
This would be an icon representing the "hotkey" feature more or less. When clicked on, it performs the same function as the hotkey would. User options for it would be:

1) Push and hold for continuous transmit (Icon shows as activated)
2) Click once for non stop transmit. (Icon shows activated) Click again to stop transmission. (icon goes back to normal)

**Comment by mkrautz** [comment]
Configure -> Settings -> Audio Input -> Transmission -> Display push to talk window

Is that what you're requesting?

**Comment by mkrautz** [comment]
You can combine that with the DoublePush time option to make it hold, etc.

**Comment by teknoskillz** [comment]
Oh ok, didnt see that, yep that works.


----- Original Message -----
