### ISSUE TITLE
Mumble still has the old icon on Mac OS X

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3358]
![macosx_icon](https://user-images.githubusercontent.com/5897523/36924608-955ec8c6-1e6f-11e8-9bad-aee9d75c4fc1.png)

**Comment by mkrautz** [comment]
This isn't "the old" icon. We discussed this before.

I think what you want to do is to change this to be consistent across platforms?

**Comment by davidebeatrici** [comment]
> This isn't "the old" icon. We discussed this before.

I call it "old" icon because it seems older compared to the one we use on other platforms.

> I think what you want to do is to change this to be consistent across platforms?

Yes.

**Comment by Kissaki** [comment]
I agree that in terms of style and logo clarity the new is preferable over the old one.

There is simply too much going on in the current/old one.
