### ISSUE TITLE
Murmur with PSQL crashes on startup

### ISSUE THREAD

**Issue by davidmehren** [mumble-voip/mumble#3361]
Hi!

We tried to setup murmur with Postgres, but on startup it crashes with the following message:
```
SQL Prepare Error [CREATE TABLE IF NOT EXISTS `murmur_meta`(`keystring` varchar(255) PRIMARY KEY, `value` varchar(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin]: ERROR:  syntax error at or near "CREATE"
LINE 1: PREPARE qpsqlpstmt_2 AS CREATE TABLE IF NOT EXISTS `murmur_m...
                                ^
(42601) QPSQL: Unable to prepare statement
```
This happens with the current version in the Ubuntu Artful Repos (1.2.18-1) and with our own build of 1.2.19.

Is using database drivers other than `QSQLITE` still supported?

**Comment by mkrautz** [comment]
Postgres has never been supported in 1.2.x. Someone contributed a backend for it in 1.3.x (current Git master) though!

You can, however, use MySQL with 1.2.x.
