### ISSUE TITLE
User icon doesn't reflect Push To Mute state

### ISSUE THREAD

**Issue by tatokis** [mumble-voip/mumble#3367]
Holding down a push to mute key only changes the tray icon to reflect the state, and not the icon in the GUI itself.
Happens in the latest code from master, with Qt5.

![62baf1ac5cb0](https://user-images.githubusercontent.com/6003656/37256624-0c2d7522-2566-11e8-9057-2011b54621b9.jpg)

**Comment by davidebeatrici** [comment]
Fixed by #3368.
