### ISSUE TITLE
signature file missing for 2717~gb25db3e source snapshot

### ISSUE THREAD

**Issue by IdleGandalf** [mumble-voip/mumble#3375]
I don't know if this is the right place to report this, but the latest snapshot .tar.gz is missing a corresponding .sig file.

Since I use signature verification for mumble-snapshot in the AUR this would mean I need to turn this off in future package updates, so I'm just asking if this was intentional.

**Comment by mkrautz** [comment]
Not intended.

**Comment by mkrautz** [comment]
I've manually uploaded the missing file.

The file went missing because we bumped our GPG keys, but forgot to update the signer to use the new key.

Apparently, the build could be deployed without a corresponding .sig.

That's another issue.

Thanks!

**Comment by IdleGandalf** [comment]
Thanks for the quick response!
