### ISSUE TITLE
Long hyperlinks posted in chat appears to break Windows 7 aero

### ISSUE THREAD

**Issue by BarneyGumball** [mumble-voip/mumble#3376]
I was screwing around with some friends and we found that posting a (very) long hyperlink in chat causes aero to turn off.  It's also effectively disabled until reboot.  Trying to force restart the aero service only has it run for a few seconds before it turns off again.

Long hyperlink: https://pastebin.com/JQJtqZgw

We tested some other long strings, like for example: https://pastebin.com/drzU4RgX but only had issues with long hyperlinks.

**Comment by mkrautz** [comment]
@davidebeatrici mentions that you specified Windows 7 in the title -- so sorry about that. :)

**Comment by BarneyGumball** [comment]
Sorry forgot to mention this is on version 1.3.0~2717~gb25db3e~ which I believe is the latest snapshot.
