### ISSUE TITLE
Toolbar button to toggle between transmit modes

### ISSUE THREAD

**Issue by sometoby** [mumble-voip/mumble#3377]
I find myself switching between push-to-talk and voice activity relatively often. Going through the options menu each time is a bit time-consuming, so it'd be really nice if the toolbar had an (optional?) button that lets you select a transmit mode from a drop-down.

**Comment by mkrautz** [comment]
It's already there:

Settings -> User Interface -> Look and Feel -> Show transmit mode dropdown in toolbar.

**Comment by sometoby** [comment]
I don't see it. This is Mumble 1.2.19 on macOS.

![screen shot 2018-03-22 at 15 06 57](https://user-images.githubusercontent.com/1444515/37775216-ac614134-2de2-11e8-9b40-e2f8533d05af.png)

**Comment by mkrautz** [comment]
Ah, my apologies. It is only in snapshot builds, then!

**Comment by sometoby** [comment]
In that case, I'm looking forward to the 1.3.0 release. Cheers! :)
