### ISSUE TITLE
Breakpoints not working in Qt Creator

### ISSUE THREAD

**Issue by hanboys87** [mumble-voip/mumble#3378]
hi. my name is tackjin
i wish to make server for mVoip. 
so, i try to run mumble.
Mumble is working well but when i debugging, it's not stop in the breakpoint

i have make makefile, following step.
1. qmake -recursive main.pro CONFIG+=no-client 
2. make
3. open the QT Creator & open the murmur.pro 
4.  start debugging (F5)

Program is working well, but breakpoint not working.

i using the Linux 16.0.04 & QT version5

**Comment by davidebeatrici** [comment]
Hi,

Have you tried opening **main.pro** in Qt Creator and building Murmur from there?

**Comment by hanboys87** [comment]
No. i open the murmur.pro file in Qt Creator.
and I write qmake -recursive main.pro CONFIG+=no-client in terminal before opening the murmur.pro file.

**Comment by mkrautz** [comment]
@hanboys87 I think what davidebeatrici suggested that you try what he does. Because he seems to be able to debug like that.

Generally, the build line you've pasted would build a release build, not a debug build. So that might be why you aren't able to set breakpoints: the debugger doesn't know where to break, because it's a release build without enough debug symbols.

Could you try doing it all in Qt Creator and see if that helps? Thanks.

**Comment by mkrautz** [comment]
If you're still having problems. Please ping this thread, I'll re-open. Thanks!

**Comment by davidebeatrici** [comment]
I'm reopening this because @hanboys87 contacted me via email: the proposed method didn't work for him.

**Comment by davidebeatrici** [comment]
I tried to set a breakpoint here:
https://github.com/mumble-voip/mumble/blob/26c732fb0819a4f2617a873a3a9088315ca576ea/src/murmur/main.cpp#L173

It works correctly.

Are you sure you are building Murmur with the **Debug** configuration?

**Comment by hanboys87** [comment]
Yes.
i tried to set a breakpoint there too.
and i am now outdoor.
so, i will capture my setting in qt creator and sending it after 9 hours later.
 
Thank you for caring me.
 
-----Original Message-----

**Comment by davidebeatrici** [comment]
You're welcome.

**Comment by hanboys87** [comment]
i retry to debug from the start 

step1. git clone https://github.com/mumble-voip/mumble.git

step2. git submodule update --init    (in mumble directory)

step3. open the main.pro file in QT Creator

step4. Build All

step5. make breakpoint in main.cpp (murmur) 

step6. Start Debugging

but it's not working........


my Build setting is 
![pro](https://user-images.githubusercontent.com/24707201/37949031-c8d4e2f0-31cd-11e8-899d-e29158e6b3ed.png)

**Comment by davidebeatrici** [comment]
Have you tried to set a breakpoint in a new project?

**Comment by davidebeatrici** [comment]
I'm closing this issue as it's not related to Mumble itself, feel free to reply in case you need further support.
