### ISSUE TITLE
UserRemove: misleading protocol docs

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#3387]
19:03:16 <ebol4> in the mumble protobuf, for the UserRemove message: https://github.com/mumble-voip/mumble/blob/master/src/Mumble.proto#L154
	19:03:42 <ebol4> it says that the "session" field will not be present if no one is being kicked
	19:04:11 <ebol4> however, in testing, when i have someone simply leave the server, the "session" field is present. the "actor" field is not present
	19:05:13 <ebol4> or rather, "actor" is set to 0
	19:13:55 <ebol4> one other weird thing, when i kick someone from the server, the server sends two UserRemove messages
	19:14:25 <ebol4> one with all the fields present, and then one with just the session ID of the person that is no longer in the server
	19:17:25 <ebol4> i guess it's just one message to say "user1 kicked user2" and then another message that says "user2 disconnected"
	19:17:34 <ebol4> seems strange to do it that way though

**Comment by bontibon** [comment]
The duplicate user remove message should also be fixed.

**Comment by ianling** [comment]
It might be better just to document the duplicate UserRemove message at this point. While I was investigating this (I'm ebol4 in IRC), I found at least one client implementation on Github that had a commit in 2013 to handle the two UserRemove messages: https://github.com/SFTtech/sftmumblebot/commit/c86c23f07ed5f3ef6df04d8a735e65e956ed16ea#diff-8400f8b07557ec4625a8c98fbcb4b027R187

It could break a lot of Mumble clients if this is changed now.

**Comment by bontibon** [comment]
There's no disputing that the bot you linked would have to be patched if the duplicate message was removed, but I'm wondering if that's just a necessary minor inconvenience in order to make our code, arguably, do the right thing.

Interestingly, [grumble only sends one UserRemove message](https://github.com/mumble-voip/grumble/blob/cb1d3db7273d28fcf02bb596f31bd3210ff538c5/cmd/grumble/server.go#L329).

**Comment by ZeroAbility** [comment]
>https://github.com/mumble-voip/mumble/blob/master/src/Mumble.proto#L154

The referenced line is now a comment so I gather this was fixed.

**Comment by Krzmbrzl** [comment]
The lines have simply changed over time as this is not a permalink. 
However, the current comment says
> The user who is being kicked, identified by their session, not present when no one is being kicked.

which seems correct. So it was fixed after all.
