### ISSUE TITLE
Images not showing up in 1.3.0~2723~g109ddd4~snapshot

### ISSUE THREAD

**Issue by fr31** [mumble-voip/mumble#3390]
Sorry if this is a duplicate, I searched but couldn't find it.

In the latest snapshot (1.3.0\~2723\~g109ddd4~snapshot) as well as the one before it, images stopped showing up in the chat window.

Here's what I mean: https://i.imgur.com/RudCYCJ.png

The image shows up in 1.2.19 as well as older snapshots. 

I am running the x64 version on Windows 10.

**Comment by davidebeatrici** [comment]
Since #3168, Mumble only supports images embedded via data URLs.
