### ISSUE TITLE
Compiling 1.3 on Raspberry Pi

### ISSUE THREAD

**Issue by olzzon** [mumble-voip/mumble#3397]
When I try to compile Mumble on a Raspberry Pi 3 (Cloned from: https://github.com/mumble-voip/mumble.git)

when running make I get this error:
g++: internal compiler error: Segmentation fault (program cc1plus)

I followed the description in https://wiki.mumble.info/wiki/BuildingLinux

------------------------

g++ -c -include release/mumble -pipe -fvisibility=hidden -Wall -Wextra -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I../mumble_proto -isystem ../mumble_proto -I../../3rdparty/celt-0.7.0-src/libcelt -isystem ../../3rdparty/celt-0.7.0-src/libcelt -I../../3rdparty/opus-src/celt -isystem  ../../3rdparty/opus-src/celt -I../../3rdparty/opus-src/include -isystem ../../3rdparty/opus-src/include -I../../3rdparty/speex-src/include -I../../3rdparty/speex-build -O2 -I../../3rdparty/speex-src/include -I../../3rdparty/speex-build -std=gnu++1z -pthread -Wall -W -D_REENTRANT -fPIC -DRESTRICT=__restrict__ -DMUMBLE_VERSION_STRING=1.3.0 -DMUMBLE -DUSE_MANUAL_PLUGIN -DNO_CRASH_REPORT -DUSE_OPUS -DUSE_ALSA -DUSE_OSS -DUSE_PULSEAUDIO -DUSE_BONJOUR -DUSE_DBUS -DUSE_SPEECHD -DUSE_SPEECHD_PKGCONFIG -DUSE_G15 -D_REENTRANT -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../../src -I. -I../mumble_proto -I../../3rdparty/arc4random-src -I../../3rdparty/qqbonjour-src -I../../3rdparty/smallft-src -Iwidgets -I../../3rdparty/speex-src/include -I../../3rdparty/speex-src/libspeex -I../../3rdparty/speex-build -I../../3rdparty/speexdsp-src/include -I../../3rdparty/speexdsp-src/libspeexdsp -I../../3rdparty/celt-0.7.0-src/libcelt -I../../3rdparty/opus-src/celt -I../../3rdparty/opus-src/include -I../../3rdparty/opus-src/src -I../../3rdparty/opus-build/src -I/usr/lib/oss/include -isystem /usr/include/alsa -isystem /usr/include/avahi-compat-libdns_sd -isystem /usr/include/speech-dispatcher -isystem /usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSvg -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSql -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtDBus -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I../../release/.moc/mumble -I../../release/.ui/mumble -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o ../../release/.obj/mumble/ACL.o ../ACL.cpp

g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Makefile.Release:2522: recipe for target '../../release/.obj/mumble/ACL.o' failed
make[2]: *** [../../release/.obj/mumble/ACL.o] Error 4
make[2]: Leaving directory '/home/pi/mumble/src/mumble'
Makefile:38: recipe for target 'release' failed
make[1]: *** [release] Error 2
make[1]: Leaving directory '/home/pi/mumble/src/mumble'
Makefile:264: recipe for target 'sub-src-mumble-make_first-ordered' failed
make: *** [sub-src-mumble-make_first-ordered] Error 2

**Comment by davidebeatrici** [comment]
Could you paste the commands you executed to build Mumble, please?

It seems like the issue is caused by low memory (RAM).

**Comment by olzzon** [comment]
Thanks a lot for the hint, it was as you say a memory issue.
I tried to compile it from a terminal running on the desktop.

A clean Boot to CLI and compiling from there, did the job 👍

**Comment by davidebeatrici** [comment]
You're welcome!

I asked for the commands you executed because I wanted to know if you run `make` with multiple jobs (`-j`), as many people solved the problem by lowering the number of jobs.

**Comment by olzzon** [comment]
I just did:
qmake -recursive main.pro CONFIG+="no-server no-overlay”
make

The no-overlay I did because of an issue with GL lib missing, I think "mesa-common-dev" or something should be added to dependencies. I´ll dig into that later and report back
