### ISSUE TITLE
Save and load audio input/output settings on a per-device basis

### ISSUE THREAD

**Issue by TheMadman** [mumble-voip/mumble#3404]
Some users would like to be able to switch quickly between devices by unplugging/plugging-in headphones. Currently the user has to alter the input/output settings manually after changing their input/output device.

Ideally we would save the input/output device settings on a per-device basis and load the correct settings when the user's input/output device has changed.

**Comment by bontibon** [comment]
Duplicate of #1264 (and more recently, #3353).
