### ISSUE TITLE
Some icons do not scale properly on UI.

### ISSUE THREAD

**Issue by Ytmndissue** [mumble-voip/mumble#3412]
For context, my OS is Windows 7 using classic mode, with 200% DPI scaling. Mumble is the latest snapshot, and is using the "classic theme." Under this scenario, the UI does not properly scale the "Window expansion checkboxes," or any "status updates" (representing the microphone/speakers/comment" to the right of people's names.

Not sure if this could just be a limitation of QT, or could just be related to the "classic theme" itself. Attached is a picture with red circles around the areas referred to:

![issues](https://user-images.githubusercontent.com/33916464/40673057-a5d8bffe-633e-11e8-9230-fa0d05ca0447.png)

**Comment by davidebeatrici** [comment]
Could you try to install the latest snapshot and check if the problem is still present, please?

**Comment by davidebeatrici** [comment]
Oh, sorry.

**Comment by Ytmndissue** [comment]
Where are all of the SVGs and theme logic for the "classic theme" in Mumble itself? Are they included in this source, or the "mumble-theme" repository? To demonstrate how small these icons appear, I shrunk the image to demonstrate the equivalent 100% situation:

![40673057-a5d8bffe-633e-11e8-9230-fa0d05ca0447_2](https://user-images.githubusercontent.com/33916464/42414752-6a200ad6-820a-11e8-899b-c69eca908b39.png)

**Comment by Ytmndissue** [comment]
The icons themselves do not seem like they have any obvious issues, is there an individual "theme file" for classic mode that might control the size of how these icons are displayed? 

Signs are leading me to believe that the issue lies in the theme itself opposed to the icons - the metro theme itself scales everything without issue.

In addition, what causes that black box off to the left when the Snapshots display their version?

**Comment by davidebeatrici** [comment]
> The icons themselves do not seem like they have any obvious issues, is there an individual "theme file" for classic mode that might control the size of how these icons are displayed?

The "classic" theme is called `None` because it uses the system's palette, we don't define a custom style like we do with `Light` and `Dark`.

> In addition, what causes that black box off to the left when the Snapshots display their version?

We disabled support for external images in #3168.

The snapshot message is now updated and the box doesn't appear anymore, as we removed the image in order to have more space for text.

**Comment by davidebeatrici** [comment]
#3475 replaces the classic icons with the ones provided by the Mumble theme.

What do you think about it?

**Comment by Ytmndissue** [comment]
I'm assuming this theme just replaces the icons, and leaves the native system theme/color alone (since this is tied into how QT renders when it emulates the system look?) So on Windows 7, it should still look like it does above (Win32 like?)

**Comment by davidebeatrici** [comment]
Exactly.

**Comment by Ytmndissue** [comment]
Sounds fine by me then, hopefully this fixes the scaling issue and its not tied into to something more complex such as QT itself.

**Comment by Ytmndissue** [comment]
Just checked the new build, icons definitely look better - but the scaling issue isn't resolved. Similar to the pictures in this thread/issue except with the new icons.

**Comment by Ytmndissue** [comment]
Okay, I've been thinking about this - assuming the three icons shown next to users are some sort of variables/objects that are passed in a very high level way to QT's "dialog drawer" (not really sure how all of this is done,) where is this done and what are their names?

I get a wacky feeling that the reason they are shrunk is that they are somehow nested in something else (like a compilation bar with all of them) which causes them to not quite be the right size.

Completely guessing here...

**Comment by Krzmbrzl** [comment]
Relevant: #5632
