### ISSUE TITLE
Survey on Mumble

### ISSUE THREAD

**Issue by everton-zoio** [mumble-voip/mumble#3415]
Good afternoon, I am representative of some researchers of computer science of the Federal University of Technology - Paraná, Brazil, and I come through this email because we initiated a research focused on MCI (man-Computer interaction) on the VoIP Application Mumble.
The idea of this project is to solve errors related to user interaction with the system, from changes in the software interface, in order to make it more intuitive. For this we need to carry out a survey with the community of users, in order to collect more information for the search. The link to the survey is attached below.
I thank you for your attention.
Sincerely, Everton Junior de Abreu.

[Survey](https://docs.google.com/forms/d/e/1FAIpQLScii4zKBu2zjUZVgSFYyJOxt7H1JPLD9NwYc47jFqqCMTiRKg/viewform)

**Comment by reelsense** [comment]
Do the Mumble Devs get to benefit from the results?

**Comment by everton-zoio** [comment]
Yes, at the end of the survey has a field to enter the email, if the person wants to have access to the results, then we will forward to whoever wants.

**Comment by HeroCC** [comment]
Looks like the link is dead, should we close this issue?
