### ISSUE TITLE
Mumble server: only listen to a subdomain

### ISSUE THREAD

**Issue by Turbito** [mumble-voip/mumble#3416]
Hi, I have read many posts but I can't find an answer
well, lets say I have _example.com_, _voice.example.com_ and _example2.com_ pointing to the same machine

I'd like the only way to connect to the server is though _voice.example.com_, but I can connect from any of these three directions.

in the mumble ini config I've set **host=**_voice.example.com_ with and withou dot at the end.

Any help/guide?
Thank you.

**Comment by reelsense** [comment]
Here is an example of how I would configure my DNS for your scenario: 

- `voice.example.com` will be the primary DNS `A` record. 

- `example.com` and `example2.com` would use `voice.example.com` as the `CNAME`.

When you update the `A` record the `CNAME` domains will follow.

**Comment by Sbgodin** [comment]
@reelsense, I'm afraid that your solution doesn't fit : connections to the domains will still allow connecting to the mumble instance.

Indeed, Mumble does not behave like a web server. There's no domain name. It's just a couple IP:port. So, you even can connect using the IP directly. The domain name is only used by your system to get the IP. The mumble server won't even see the domain name your requested.
