### ISSUE TITLE
MUMBLE Android(Plumble) Has Discontinued?

### ISSUE THREAD

**Issue by rock2rap** [mumble-voip/mumble#3421]
After 3 Years to using mumble, I think i know MUMBLE is the best for me, I've hosting mumble server on my local for PC and Mobile user

I love Plumble it's Battery Save/Power Save but PLUMBLE has not develop since 2017 (nightly build #12)

PLUMBLE Discontinued??

**Comment by bontibon** [comment]
Plumble isn't an official client, so we don't know. Wait for an answer on your ticket with them: acomminos/Plumble/issues/197
