### ISSUE TITLE
How to use on libreelec Arm64 (amlogic s912)??

### ISSUE THREAD

**Issue by wodgey** [mumble-voip/mumble#3423]
I had the static binairy running perfectly on an x86_64 libreelec machine but would like to run it on a lightweight s912 box. 

I don;t know where to begin, so any help/pointers of where to research next, would be greatly appreciatreed

**Comment by davidebeatrici** [comment]
You can compile Mumble on your device by installing the required dependencies.

**Comment by Kissaki** [comment]
It looks like the device you named Amlogic S912 runs Android on an ARM processor. Unfortunately we do not distribute compiled binaries for that.

[As per Wikipedia](https://en.wikipedia.org/wiki/Amlogic#Media_player_SoCs_(S9_family)) Amlogic does provide SDKs, which you will need to install to compile runnable binaries yourself. Please refer to their documentation for that.

> S905X was scheduled to be released in Q1 2016 while S905D and S912 were scheduled for Q2 2016. All three of SoCs have Android Marshmallow and Buildroot Linux SDKs released. 

To build the Mumble server you can check out our [Building Linux](https://wiki.mumble.info/wiki/BuildingLinux#Building_Mumble) page for, which is not specifically for Android, but may be close enough to get going alongside. If you find our docs lacking or missing, please feel free to suggest/provide a guide yourself for building for Android/your device..

To build the Mumble server you will also need to install Qt, and possibly some more dependencies. Please refer to our Building Linux 

The main compilation step/commands [are](https://wiki.mumble.info/wiki/BuildingLinux#Building_Mumble):

```
qmake -recursive main.pro CONFIG+=no-client
make
```

**Comment by Kissaki** [comment]
This should help you get going. If you have any specific problems feel free to ask about those again. You can also find us on #mumble on IRC freenode if you prefer interactive chat. (there may or may not be more people there to help - feel free to ask and stick around for delayed replies)

**Comment by wodgey** [comment]
Thank you. I'll have a look at this.

Libreelec is a lightweight Linux distribution. I'm not using android.
