### ISSUE TITLE
Murmurd registration rejecting correct I.P location  

### ISSUE THREAD

**Issue by otavioarj** [mumble-voip/mumble#3425]
Aside issue https://github.com/mumble-voip/mumble/issues/3328 , I'm now into a register bug I guess. My server was (until about 26 hours ago) in a USA I.P block, but now it's in a Brazil's block.

Checking its I.P whois, I got:
> inetnum:     177.71.128.0/17
> aut-num:     AS53032
> abuse-c:     SPAMA4
> owner:       A100 ROW SERVICOS DE DADOS BRASIL LTDA
> ownerid:     12.147.176/0001-50
> responsible: Tina Morris
> country:     BR

Its register info:
> registerHostname=177.71.202.199
> registerLocation=BR

But, I'm always getting this error: "Registration: Registration updated [Location does not match hostname country code. Ignored unverified certificate]"

I tried creating a new register, though it maybe an updating bug, but now I have two entries in US-California for the same I.P :(. Mumble listing is matching the correct I.P, so I don't know why it is putting the server into NA>US. 

Using Murmur 1.2.19 (1.2.19-2) on Debian 9.

**Comment by davidebeatrici** [comment]
This probably happened because the `C` attribute of the certificate was set to `US` instead of `BR`.

I'm closing the issue because we want to drop the requirement (#3328) anyway.
