### ISSUE TITLE
Build Murmur with gRPC by default

### ISSUE THREAD

**Issue by HeroCC** [mumble-voip/mumble#3429]
Hello!

I saw that Murmur now has support for gRPC instead of Ice for communications as of #1196. However, it doesn't look like the publicly build image has support for that built in. Would it be possible for gRPC to be enabled when building Murmur on all platforms? I am testing from a Mac and would love to not have to compile mumble and murmur manually.

Thanks!

---

# Status

* [ ] There seem to be segfaults/crashes in some cases - to be documented ([[1]](https://github.com/mumble-voip/mumble/pull/3947#issue-365020608), [[2]](https://github.com/mumble-voip/mumble/issues/2569#issuecomment-629134572))
* [ ] Our gRPC implementation [does not yet seem to provide all that Ice does](https://github.com/mumble-voip/mumble/issues/3429#issuecomment-505453643)

**Comment by HeroCC** [comment]
This might be a separate issue, but in the [wiki](https://wiki.mumble.info/wiki/BuildingLinux) enabling gRPC as a step would be helpful as well.

**Comment by davidebeatrici** [comment]
Hello!

gRPC support is still experimental:
https://github.com/mumble-voip/mumble/blob/6195761d290fd3ba4296215e525da8008ddf86d2/INSTALL#L149-L156

I added a link to the [INSTALL](https://github.com/mumble-voip/mumble/blob/master/INSTALL) file on the [Wiki](https://wiki.mumble.info/wiki/BuildingLinux#Building_Mumble).

**Comment by Kissaki** [comment]
Oh… I guess that’s why I didn’t get it to work last time I tried haha

**Comment by Kissaki** [comment]
The linked wiki page does not mention grpc?

**Comment by Kissaki** [comment]
> gRPC library's API is not yet stable

Is that still the case?

It’s way past a 1.0 release and I see no mention of unstabledness on the [grpc website](https://grpc.io/), about or FAQ.

**Comment by HeroCC** [comment]
Although I'm not a Mumble developer by any means, but looking at gRPC [when that comment was written](https://github.com/grpc/grpc/tree/7da3297be7068a5a167991efafb2ec4eba2b2779) and now, there have been 20672 commits to the repo; and they have released multiple stable releases for all OSes since then. The [MurmurRPC.proto](https://github.com/mumble-voip/mumble/commits/master/src/murmur/MurmurRPC.proto) file hasn't been touched (except for license header updates) since 2015, suggesting that it is reasonably frozen for now. I would say especially now with [issues using Ice on newer platforms](https://github.com/mumble-voip/mumble/issues/3409) this would be a good time prior to the full 1.3 release to re-enable gRPC by default. 

@bontibon, I saw you worked on most of the gRPC features in Mumble, would you mind weighing in as well?

**Comment by HeroCC** [comment]
I made a PR that would resolve this ticket, if you could take a look that would be much appreciated!

**Comment by Krzmbrzl** [comment]
If I compare https://github.com/mumble-voip/mumble/blob/4976c1ad2e0802755c15d051783403afc440b173/src/murmur/Murmur.ice with https://github.com/mumble-voip/mumble/blob/master/src/murmur/MurmurRPC.proto I'd say that the gRPC API doesn't provide the same functionality as the ICE interface.

From what I understand, gRPC shall replace the ICE framework. And as such the least I'd expect is that it provides the same functionality as is currently provided by ICE. But as I said I don't believe this is the case (yet).

If the above is correct I'm not sure whether it already makes sense to add the gRPC just yet :thinking:

**Comment by Kissaki** [comment]
I added a status section to the original post and linked the (undefined but vaguely mentioned) segfaults and incompleteness as open. The first of the two being the blocker.
