### ISSUE TITLE
Depend on deprecated Qt4 in Linux

### ISSUE THREAD

**Issue by androos** [mumble-voip/mumble#3430]
Qt4 is dead (for 3 years) and going away.
https://bugs.gentoo.org/656826

**Comment by ppfeufer** [comment]
Yep, this is an important one, dear mumble team, please update!

**Comment by C0rn3j** [comment]
Dupe of https://github.com/mumble-voip/mumble/issues/2728

**Comment by davidebeatrici** [comment]
Closing in favor of #2728.
