### ISSUE TITLE
How to use Certificate?

### ISSUE THREAD

**Issue by inukaze** [mumble-voip/mumble#3439]
Hi there, someone can explain how i can. set the "Comodo" Certificate with Murmur, and the client read the added Certificate (X509) i make one, is RSA 2048 with SHA1 and SHA256. But i don't know how set right to my local server.

For example, what i should put in the lines "sslCert" and "sslKey" ? 

sslCert=file.p12
sslKey=00 01 AB CD EF F0 00 01 02 03 04 05 06 07 08 09 10 AA AB AC

How is the right way?

i should edit files like : 
/etc/init.d/mumble-server
/etc/mumble-server.ini

One last thing, how i set mumble to ever put me a specific Nickname, and connect to my localhost, without show me the GUI Server Selector.

???

Reading this -> https://wiki.mumble.info/wiki/Obtaining_a_StartCom_Murmur_Certificate
i have a dunno, from where i get "ssl_mumble.crt" because in none part, explain from where get that file.

**Comment by davidebeatrici** [comment]
Hi!

> For example, what i should put in the lines "sslCert" and "sslKey" ?
>
>sslCert=file.p12
sslKey=00 01 AB CD EF F0 00 01 02 03 04 05 06 07 08 09 10 AA AB AC

You have to set the path to the corresponding file in each of the two variables, for example:
```
sslCert=certificate.pem
sslKey=key.pem
```

A PKCS #12 file (.p12) can contains both the certificate and the private key, you should generate two separate files instead.

> i should edit files like :
/etc/init.d/mumble-server
/etc/mumble-server.ini

`/etc/mumble-server.ini`, which contains your server's configuration.

> One last thing, how i set mumble to ever put me a specific Nickname, and connect to my localhost, without show me the GUI Server Selector.

Settings -> Network -> Reconnect to last server on startup

**Comment by davidebeatrici** [comment]
It would be better to create a dedicated folder for the certificate files and specify the path in `/etc/mumble-server.ini`.

**Comment by inukaze** [comment]
I SOLVED IT!

1 - [Get Comodo Certificate](https://www.comodo.com/home/email-security/free-email-certificate.php)
2 - Extract the Certificate from my Firefox Web Browser and Save it with **Name.p12**

3 - **Extract the RSA Public Key & Convert pkcs12 the certificate to pem format**, edit the server file, to put the absolute path of your files in my case both are named bloginukaze, and in the test i put on the tmp folder.

```
openssl pkcs12 -in bloginukaze.p12 -nocerts -nodes | openssl rsa > bloginukaze.rsa #This is for sslKey
openssl pkcs12 -in bloginukaze.p12 -nodes -out bloginukaze.pem #This is for sslCert

sudo sed -i "s|#sslCert=|sslCert=/tmp/Murmur/bloginukaze.p12|g" /etc/mumble-server.ini 
sudo sed -i "s|#sslKey=|sslKey=/tmp/Murmur/bloginukaze.pem|g" /etc/mumble-server.ini 
sudo sed -i "s|MURMUR_USE_CAPABILITIES=0|MURMUR_USE_CAPABILITIES=1" /etc/init.d/mumble-server

# Now test : 
sudo /sbin/murmurd #Not problem here
```

Screenshot The Certificate Working : 
[![Murmur_Certificado.png](https://s25.postimg.cc/4u5rmjnzz/Murmur_Certificado.png)](https://postimg.cc/image/7bhitt7wb/)

**Comment by davidebeatrici** [comment]
Awesome!

I created a [dedicated page](https://wiki.mumble.info/wiki/Obtaining_a_Comodo_Murmur_certificate) on our Wiki with a link to this issue, feel free to create an account and write your instructions.

Thank you.

**Comment by inukaze** [comment]
Thanks but i prefer, you test my instructions are easy to follow, and test you too :D, just for make secure all steps are easy and right explain it :D

**Comment by davidebeatrici** [comment]
No problem.
