### ISSUE TITLE
Overlay - Questions

### ISSUE THREAD

**Issue by inukaze** [mumble-voip/mumble#3452]
1 - Why the option "Enable Overlay" don't work well under GNU/Linux or Windows ?
When i try to disable, nothing happens, the overlay still there.

2 - Why when i am put the overlay on some position of the screen i can't see it directly?

3 - Why the Overlay don't have Vertical Orientation ? ( Because on someone i had vertical spaces on the screen i can use, but the unique orientation is horizontal )

4 - What are the default extension for Overlay, because when i save overlay under GNU/Linux, don't make any extension, and when the file explorer is open, because don't have extension don't appears in the list, but the file are there.

5 - You don't have think to make the overlay, like the Telegram Contacts for people connected, and the user can set if want see the public avatar of the contact, or set a customize contact picture for overlay ?

**Comment by Kissaki** [comment]
AFAIK disabling the overlay should hide it right away, on the next rendered frame, as Mumble no longer renders it.

The Overlay may still be injected until the process that previously showed the overlay is stopped/restarted, but as far as I know not display.

What do you mean see it directly? Our overlay only works by injecting into drawing code by Direct3D and OpenGL. Are you expecting it to show up on your desktop without another program running?

The overlay allows specifying how many columns should be used for usernames, up to 5 columns. So it will first extend horizontally up to five, and then start on the next row. Is that what you want? Did you know about this setting?

**Comment by inukaze** [comment]
Hi there well 

1 - Enabling the Overlay
[![Mumble_Overlay001.png](https://s25.postimg.cc/6slmbu827/Mumble_Overlay001.png)](https://postimg.cc/image/7uvsudqvf/)

2 - Trying to disable - Overlay don't hide.
[![Mumble_Overlay002.png](https://s25.postimg.cc/4b9v4kgfz/Mumble_Overlay002.png)](https://postimg.cc/image/c40iwjmez/)

3 - Well why see directly, instead view mumble window on the background. i prefer see the game window, to know where exactly i am putting the overlay

[![Mumble_Overlay000.png](https://s25.postimg.cc/ngd4edku7/Mumble_Overlay000.png)](https://postimg.cc/image/lok5jh1h7/)

4 - I know about that setting, but i mean, i need some more customizable, here a mockup made for me, i put very separate, and with the text rotate, and in a literal vertical & center mode. 

[![Mumble_Overlay003.png](https://s25.postimg.cc/rcqgabvj3/Mumble_Overlay003.png)](https://postimg.cc/image/gd58yq53v/)

i mean something like that for example.

**Comment by Kissaki** [comment]
Can you please create a separate ticket for your feature request (point 3) with your mockup screenshot and use case? Then we can label and track it as a feature request (which we can't in here because this handles three things at the same time).

**Comment by Kissaki** [comment]
As requested they added separate feature request tickets.

The numbering is used inconsistently across the two posts; it does not identify specific topics, so I can not refer to them here.

* #3460 Overlay Settings: Allow updating/using game window as background
* #3482 Overlay more Custumizable
* #3483 Overlay Contacts like Telegram but Customizable
