### ISSUE TITLE
Debug build does not link with debug libraries

### ISSUE THREAD

**Issue by Aglets** [mumble-voip/mumble#3462]
If you do a debug build *only* the link process tries to load release libraries instead of debug libraries; the trailing 'd' in the library name is missing. For example, when linking the protobuf library the created library name is libprotobufd.lib. However, the make files try to link in libprotobuf.lib instead.
I think the problem is that release builds may have been created first permitting the debug build to complete but linked with release libraries instead of debug libraries.

**Comment by davidebeatrici** [comment]
Fixed in #4252.
