### ISSUE TITLE
[Feature suggestion] Bridge to Matrix

### ISSUE THREAD

**Issue by homebeach** [mumble-voip/mumble#3463]
A bridge between Mumble and [Matrix](https://matrix.org). Here is corresponding issue in Matrix side: https://github.com/turt2live/matrix-wishlist/issues/143.

**Comment by trustable-code** [comment]
You can use a bot as bridge, like this one in Node.js: https://gist.github.com/trustable-code/8549c97ac3db99ef1f9e472ad42cef72

**Comment by bontibon** [comment]
This is something that is best written as a gRPC or ICE RPC script. A bot-based bridge could also work, as @trustable-code suggested.

Therefore, this is not something that will be added to Mumble itself.
