### ISSUE TITLE
Drop CELT 0.7 support in favour of Opus

### ISSUE THREAD

**Issue by devurandom** [mumble-voip/mumble#3469]
Would it be possible to drop CELT 0.7 support in favour of Opus?

We current have issues in Gentoo building Mumble from Git, because it tries to install CELT libraries to the system, which collide with the files by the CELT package itself (which is incompatible, because it is version 0.11).

See-Also: https://bugs.gentoo.org/661000

**Comment by Kissaki** [comment]
CELT 0.7 is our baseline version for backwards compatibility between servers and clients. This is definitely the case for 1.2 and 1.3. If the clients in a channel/server does not support a newer codec, all will fall back to CELT 0.7 so they can talk to each other.

We do plan to drop CELT 0.7 eventually, but not for 1.3 yet.

If I remember correctly debian built their package with a broken CELT implementation once that broke interoperability. I don't know what the state of that is or was. But breaking compatibility kinda sucks of course.

Servers can force to use opus with the opusthreshold setting. In that case clients that do not support Opus simply can not communicate audio.

**Comment by devurandom** [comment]
My problem is more with building Mumble: It comes with a bundled shared library that conflicts with the system library for CELT 0.11.

Currently I rename Mumble's bundled library when building the package: https://github.com/devurandom/gentoo-overlay/commit/b0d953539800a5b54951ce06a626b480d8d260cd
Are you interested in this patch? Then I'd submit it as a PR to Mumble.

**Comment by davidebeatrici** [comment]
Superseded by #3484.
