### ISSUE TITLE
Notification for "text message" appears when writing messages

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#3470]
When text to speech readback is enabled in the config (tts/readback=true) but tts itself is disabled (tts/enable=false) and you write a text message to a user/channel, then a "Text message" notification appears.

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/68aae1db52e3c26cb43cf69cd6304c6a795739b1/src/mumble/Log.cpp#L503-L504
