### ISSUE TITLE
Building the Installer using the Default configuration from README

### ISSUE THREAD

**Issue by edm7707** [mumble-voip/mumble#3478]
In the Build Instructions for Mumble in mumble-releng/buildenv/1.3.x/win32-static/README

in  step `4. Building Mumble itself`
  
it says to use the following to configuration the build 

` c:\users\builder\mumble> qmake -recursive main.pro CONFIG+="release static tests warnings-as-errors no-elevation" `

I set the following command line variable

`MumbleSourceDir = C:\MumbleBuild\win64-static-1.3.x-2018-07-01-x\mumble`

`MumbleNoSSE2 = True`

After Building the solution, this line throws an error ...
```
The system cannot find the file 'C:\MumbleBuild\win64-static-1.3.x-2018-07-01\mumble\scripts\murmur.ini.win32'.	MumbleInstall	C:\MumbleBuild\win64-static-1.3.x-2018-07-01\mumble\installer\Files.wxs	131	
```

`
<File Source="$(var.SourceDir)\scripts\murmur.ini.win32" Name="murmur.ini" KeyPath="yes" />
`

In order to generate the `murmur.ini.win32` file I needed to manually run` mkini-win32.bat 
`

Is this explained in the documentation somewhere or did I configure something wrong?
( I couldn't find this in here https://wiki.mumble.info/wiki/BuildingWindows)

**Comment by edm7707** [comment]
WIP: Various installer improvements #3186 .. Think this pull request related to some problems with the installer

**Comment by Krzmbrzl** [comment]
Are you still having trouble with this?
