### ISSUE TITLE
Thoughts on what can be deprecated/removed in mumble 

### ISSUE THREAD

**Issue by edm7707** [mumble-voip/mumble#3484]
Mumble has accumulated some vestigial features .... this makes the source harder to work with / increases build times )

- [x] Drop QT4 #3602

- [ ] Drop DBUS in Murmur #1991 

- [ ] Drop ASIO #1604

- [x] Drop DirectSound #3828

- [ ] ~~Drop Speex #3812~~

- [ ] Drop CELT 0.7 #3469 

- [x] Drop CELT 0.11 #2045 

- [x] Drop in-game GUI code #1172

Just wanted to get ppls thoughts and start a list/discussion about what should be depreciated/ removed

As these changes would probably break some compatibility with older versions... might be a good time to to go with a 2.0 instead of 1.4   (With the heavy focus being on clean-up instead of new features)

**Comment by Ytmndissue** [comment]
Thinking on this, I do think it's time to remove quite a lot of the old libraries and features, and focus on a non-backwards compatible 2.0 version that focused purely on Opus/QT5 and "cleaned out" a lot of the other un-used parts compiled in.

**Comment by sgtnoodle** [comment]
I use the client dbus to actuate a push-to-talk button when another user is speaking, but if I'm the only one I'll figure something else out.

**Comment by VVD** [comment]
IMHO: migrate from Qt 4 to Qt 5.

**Comment by davidebeatrici** [comment]
We will remove support for Qt 4 in 1.4.0.

**Comment by EmperorArthur** [comment]
I'd argue that some sort of on screen overlay is actually useful.  It's something Discord has and I've seen quite a few people using regularly.  Given that Discord is the dominant chat program at this time, I'd say removing features that make Mumble competitive isn't the best option.

**Comment by Ytmndissue** [comment]
Yeah, while I don't personally use the screen overlay (and if I were to fork and make my own slimmed down of Mumble, would remove it,) removing it from the mainline version does seem like a bad idea unless it was just too hard to maintain. Mumble is indeed intended as a gaming VOIP solution.
