### ISSUE TITLE
Fails to build with protobuf 3.6.0 due to c++11 requirement

### ISSUE THREAD

**Issue by eli-schwartz** [mumble-voip/mumble#3486]
While rebuilding mumble with the new protobuf version for Arch Linux, I discovered it would not build due to https://github.com/google/protobuf/issues/2780

The fix is to add `CONFIG+=' c++11 '`, but it would probably make sense to set this automatically rather than force users to figure out the need for this themselves after it errors the first time.

**Comment by radioactiveman** [comment]
This should already be fixed with https://github.com/mumble-voip/mumble/pull/2630. The AUR package [mumble-git](https://aur.archlinux.org/packages/mumble-git/) also does not require the mentioned workaround.

**Comment by eli-schwartz** [comment]
But that's not true, since the PR you reference in fact sets a default of c++98 and not c++11. With current protobuf this simply does not work at all.

As for why it did not detect support automatically and raise the bar to c++11, I guess that's because it is checking QT_CONFIG which for qt5 includes c++11 c++14 c++1z but for qt4 includes none of that. Now which one is being used for the two-year-old stable release?

**Comment by Krzmbrzl** [comment]
Is this still relevant. I thought that Mumble now switched to cpp11 now. Not sure though.

@davidebeatrici or @Kissaki do you have a better overview on this?

**Comment by davidebeatrici** [comment]
I confirm that we switched to C++11, thank you for bringing this up.
