### ISSUE TITLE
Mumble disconnects JACK ports which are not created by it

### ISSUE THREAD

**Issue by chaseology** [mumble-voip/mumble#3489]
Mumble, when using JACK, upon loading, disconnects any & all jack APP's connections to JACK system input and JACK system output; regardless of having set JACK SETTINGS to ignore all self connect requests. Therefore every currently residing JACK APP, has to be RE-WIRED to the JACK SYSTEM PINS(input OR output) each time MUMBLE is loaded OR each time a new setting in MUMBLE requires hitting the MUMBLE APPLY button.

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/7c08da0b3fcfe6a6a78f42fe58dc7f34ce2f944c/src/mumble/JackAudio.cpp#L250-L271

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue, I created #3490 to fix it.

**Comment by chaseology** [comment]
Excellent...thank you !

**Comment by davidebeatrici** [comment]
You're welcome!
