### ISSUE TITLE
Consistent Mouse/USB Lag when Connecting/Disconnecting USB device while Mumble is running

### ISSUE THREAD

**Issue by rickenwing** [mumble-voip/mumble#3492]
This issue has been persistent since Mumble ~1.2. It's gotten consistently worse and in the latest Windows x64 snapshot it's by far the worst I've seen. I believe this might be caused by having a DAC connected while Mumble is running or at least it significantly enhances the issue to where it's easily reproducible. I have a JDS Labs OL DAC and this also has happened with a schiit modi DAC. 

This lag will last anywhere between 5-10 seconds and affects all USB devices such as the mouse and keyboard. It seems like any USB event will cause this lag. 

If I disconnect the DAC and restart Mumble it will not occur the vast majority of the time if at all. 

I've recorded a webm of it occurring:
https://my.mixtape.moe/fnyyms.webm

From my testing this occurs on Windows 10 + Mumble. I've tested 1.2 and on each version on Windows 10 and all suffer from the same issue though the lag is less impacting on older versions. I've tested on a variety of different hardware with Windows 10 and it occurs on all with a DAC connected.

This doesn't occur on OSX High Sierra with a macbook air + DAC.

This occurs regardless if the DAC audio is selected as the audio output or not in either mumble or windows. 

Please let me know what logs/testing is needed. I'm more than happy to help fix this bug.

dxdiag here:
[DxDiag.txt](https://github.com/mumble-voip/mumble/files/2278534/DxDiag.txt)

**Comment by davidebeatrici** [comment]
Are you using ASIO?

**Comment by rickenwing** [comment]
From within mumble it auto selects wasapi.
![mumble_2018-08-10_09-50-18](https://user-images.githubusercontent.com/42275847/43967913-e462e880-9c82-11e8-9df0-a9f8a5be9fcd.png)

**Comment by pvomit20** [comment]
I am also having mouse input lag. Its been occurring since 2016.

Googling prompted me to rollback to 1.2.14 but the issue still occurs.

I also tried disabling xbox input in the registry but it still occurs.

Mumble always seems to open to high cpu priority by default, I don't know how relevant that is.

I'll be a happy man if this gets resolved. 

Thanks for your time
[DxDiag.txt](https://github.com/mumble-voip/mumble/files/2292126/DxDiag.txt)

**Comment by jr0n** [comment]
This is an issue for me as well using a DAC with Windows 10. The driver is "Generic USB Audio." When mumble is running, attaching any USB device causes all other USB input devices to stutter for 5-10 seconds. If I can provide any additional information, please let me know.

**Comment by wfjsw** [comment]
Still relevant by now. Version 1.3.4. I don't have DACs but I have Virtual Audio Cable installed. Dunno if it's relevant. Significant lag occurs when there is any changes to drivers.

**Comment by wfjsw** [comment]
Tried 1.4.0 RC1. No lag is observed by now.

**Comment by Krzmbrzl** [comment]
Ah that sounds promising :D

**Comment by davidebeatrici** [comment]
The removal of DirectInput fixed the various crashes that were reported, while the removal of input hooks fixed the polling rate instability issue.

#4039
