### ISSUE TITLE
Left 4 Dead 2 plugin needs to be updated

### ISSUE THREAD

**Issue by ark0nik** [mumble-voip/mumble#3493]
Basically LFD2 just wont link in any case, it links for garrysmod but left 4 dead 2 just seems to be giving it issues with linking? is there some sort of fix i need to download or a setting to make it link?

**Comment by davidebeatrici** [comment]
Operating system?

**Comment by davidebeatrici** [comment]
I'm working on a new plugin for both Left 4 Dead and Left 4 Dead 2, which retrieves the offsets dynamically from the game.

**Comment by davidebeatrici** [comment]
@ark0nik @Azlond @lyallz

New plugin for Mumble 1.3.0 64 bit: [se_msvc_2015_amd64.zip](https://github.com/mumble-voip/mumble/files/3357317/se_msvc_2015_amd64.zip)

The DLL should be put in `%AppData%\Mumble\Plugins`.
You can disable the old plugin in `Settings` -> `Plugins`, to prevent it from linking to the game.

Please let me know whether it works and/or there are any issues.

**Comment by lyallz** [comment]
Still have issues. Just to confirm all I need to do is have lfd2 open as well as mumble having all plugins enabled including Source Engine and LFD2 for it to work or is there anything else I need to do as it says its linked in the mumble chat but nothing works ingame with my friend??

**Comment by davidebeatrici** [comment]
I confirm that's all you have to do.

Right now the plugin uses the server's IP address and port as context, which means it will be different between who hosts (`loopback`) and who connects externally.

Are you playing on a lobby or on an external server?

**Comment by davidebeatrici** [comment]
> mumble having all plugins enabled including Source Engine and LFD2

If Mumble says that it is linked to "Left 4 Dead 2" instead of "Source Engine", you should disable the Left 4 Dead 2 plugin.

**Comment by davidebeatrici** [comment]
@lyallz Does it work?

**Comment by Azlond** [comment]
@davidebeatrici I just tested it, and it works for me after disabling the Left 4 Dead 2 plugin. Thank you!

**Comment by davidebeatrici** [comment]
You're welcome, thank you very much for testing it!
