### ISSUE TITLE
1.3 audio delay

### ISSUE THREAD

**Issue by constatinus** [mumble-voip/mumble#3497]
I compiled the latest mumble from git on my linux machine. Everything looked fluid and great until, by measuring the delay by murmurding a local server and joining my linux laptop and phone (which has plumble, android) and muting one device and putting headphones in it to measure how much time it took for the message to get to me. Now i'm not an expert, but i'd say that the delay on linux was way bigger, like 400ms to 50. I checked my built in mic and see that in almost insatnteniolsy gets audio as i make it. So the issue had to be something with linux, pulseaudio or my compilation?
I plugged in an old mic into my pc which has windows and release 1.2.19. Everything works fine and the delay is really small, like it should be. Then, i installed the latest snapshot binary on my windows machine and noticed the same big delay like on my latest git compiled mumble on linux.
So this has to be a mumble 1.3 issue right? Can i test anything else to help with this issue?

**Comment by SplotyCode** [comment]
I also had an huge delay on a local server it was also linux -> android!

**Comment by Krzmbrzl** [comment]
Does this issue still persist in Mumble 1.3.1?

**Comment by constatinus** [comment]
Oh so i have actually tested this in the latest release, and it seems fine.
