### ISSUE TITLE
Allow "recording" to /dev/random

### ISSUE THREAD

**Issue by scottmayo** [mumble-voip/mumble#3501]
The concept is that conversations during games can be compressed and fed to the system's random number generation, so that things said during games become part of the randomness that shapes the events in games. It's psychologically satisfying ("Maybe if you hadn't said that about Odin you wouldn't have rolled that 1" suddenly becomes literally true).

It doesn't work out of the box; even putting /dev for directory and random for the filename generates an error. It appears to work if I create a soft link to /dev/random and specify the link. 

What's needed to make it perfect: 1) separate it from the recording dialog, as we're not recording 2) make it optionally part of server configuration; ie, let the server be what writes to /dev/random on demand, as that's likeliest to be the system it's useful on 3) do hashing on the audio - and it doesn't have to be anything special - to cut down the amount of data dumped into /dev/random (and to eliminate the concern that "linux is listening")  and 4) don't bother when the channel is silent.

Oh, and users joining and leaving, text messages, etc should also be hashed and fed into /dev/random. Just showing up for a game should modify subsequent events, even if you never say a word. 

This should be computationally lightweight - you can use raw audio since /dev/random gets no advantage from the stream being decoded to any particular audio format, and hashing it down to hundreds of bytes per second instead of tens of thousands can be done very cheaply, and relieves load on the system. And note there's no reason to fiddle with the entropy settings in linux - you're not trying to _increase_ available randomness (and you shouldn't try), you're just _changing_ what exists. Simply doing an open() on /dev/random and doing periodic write() is all that's needed.

**Comment by bontibon** [comment]
This is not a feature that we have interest in adding nor maintaining.
