### ISSUE TITLE
Volume slider for message sound

### ISSUE THREAD

**Issue by bindi** [mumble-voip/mumble#3514]
There's a volume slider in settings under Messages, but it is labeled Text to Speech, and doesn't affect the sound files that are selected above.

**Comment by Katharsas** [comment]
Yeah and it would be nice if it was possible to disable all sound notifications (without having to tick 20 checkboxes).

**Comment by Krzmbrzl** [comment]
@Katharsas please open a new issue for this :)

**Comment by Krzmbrzl** [comment]
I'll close this as a duplicate to #3963 even though this issue has been created first. The other one is better formatted though, so we'll keep that one :)
