### ISSUE TITLE
Left 4 Dead 2 Positional Audio not working

### ISSUE THREAD

**Issue by Azlond** [mumble-voip/mumble#3518]
Hi,
I can't seen to get the positional audio working with Left 4 Dead 2. Unlike #3493, Mumble indicates that linking with the game works:

> [20:47:52] Left 4 Dead 2 linked.

The plugin is enabled, but maybe outdated? The plugin mentions version number 2.1.4.6, while the game is currently at version 2.1.5.2.

I'm using Windows 7 with the latest Mumble 1.3.0 Snapshot, while the mumble-server runs on a Raspberry Pi with Raspbian Stretch, and version 1.2.18.

**Comment by davidebeatrici** [comment]
The plugin is outdated, I'm closing this in favor of #3493.
