### ISSUE TITLE
Configure murmurd without requiring certificates

### ISSUE THREAD

**Issue by lwnexgen** [mumble-voip/mumble#3524]
I run a small games group (~10 people)

A few of our members are not overly technical, so managing certificates is not an easy task for them.

Is there any way to disable the automatic "storage" of user cert sigs? When my users switch between clients it is annoying to have the first auto-generated cert be stored as their credential because they don't expect to have to copy their cert off of their phone to their PC, for instance.

I've whitelisted my network configs so that only their devices can access my server, and I set a password server so I'm really not concerned about anyone impersonating a member of our group to join our chat.

**Comment by Kissaki** [comment]
Are you looking for using with non-authenticated users? But then without accounts no certs would be associated??

If you're using an authenticator then that replaces/can replace cert authentication, so that shouldn't be a problem either.

**Comment by lwnexgen** [comment]
I am not sure of the proper naming of this - what I would like is to run a max-10 client server with _only_ a password defined, and a list of usernames. That way I can give my friends instructions that say "connect to lwnexgen's mumble server on port 12345, use server password Games2%#Group, and your first name in lowercase" and not have to worry about any certificates or anything like that.

**Comment by Kissaki** [comment]
What do you mean by list of usernames? What would that list be for?

Do you want to accept only these usernames? So a whitelist for username?

Then wouldn't using no authentication not be viable? Certs would not be stored in accounts. Where do you run into problems with certificates?

**Comment by lwnexgen** [comment]
Yes, I would like to just use a whitelist for usernames and a server password, no cert authentication at all.

I was running into issues with certs where I would sign into my server on my desktop pc with username 'myname' with an autogenerated cert. After signing out of the server (disconnecting from my desktop computer) I then signed into the server using 'myname' on my phone, and got authentication errors until I manually reset the murmurdb sqlite database on the server.

**Comment by Kissaki** [comment]
If you simply don't register the users you should be fine then.

The simplest whitelist is allowing all. :)

Otherwise you can create/adjust an authenticator that checks usernames against a whitelist.

See for example the phpbb authenticator: https://github.com/mumble-voip/mumble-scripts/blob/master/Authenticators/phpBB3/phpBB3auth.py#L451-L460

**Comment by Krzmbrzl** [comment]
Closing as stale
