### ISSUE TITLE
Mumble 1.3.x does not work on MacOS 10.14

### ISSUE THREAD

**Issue by pl4st3** [mumble-voip/mumble#3529]
After upgrade to the latest MacOS release (10.14 aka macOS Mojave), the mumble client crashes on startup.
The sending crash report to developers, also crashes with "error 299".

mumble.dmp is empty (0 bytes).

**Comment by mklnz** [comment]
I managed to start the app (allow access in security & privacy preferences). However, every time I start another app it seems to ask for permissions to control which is extremely annoying.

Does this have something to do with push to talk function?

![image](https://user-images.githubusercontent.com/604101/46284510-b2391e00-c5aa-11e8-924d-0ea5d73e5da5.png)

**Comment by pl4st3** [comment]
this thread is a duplicate. 
Issue #3471 describes a solution/ workaround.
