### ISSUE TITLE
Add search field to server list

### ISSUE THREAD

**Issue by dnaf** [mumble-voip/mumble#3532]
Finding my server with a fresh install of the client can be annoying and would be much less annoying if the user could type its name into a search bar to easily find it.

Rather than simply filtering the server list to only contain server names containing the given search string, it would be nice if it used a fuzzy matching algorithm and returned the most similar results. A very simple way to implement this functionality would be to calculate the Damerau–Levenshtein distance and return the 10 or so least distant results in descending order.

The search results should be displayed in the same area that the current server list resides in, but it would conflict with the server list's tree structure. While searching, rather than displaying servers beneath their country and continent, the list should be flat with the country flags displayed to the left of each individual server.

**Comment by Krzmbrzl** [comment]
@Kissaki I guess this could get the `feature-request` tag and could be added to the feature-project :)

Might also be a `good first-issue` as this should be fairly easy to implement...

**Comment by sakibmahmud** [comment]
Hi, I would like to contribute to this project.

**Comment by davidebeatrici** [comment]
Hi, feel free to create a pull request.
