### ISSUE TITLE
Pathnames too long

### ISSUE THREAD

**Issue by Aglets** [mumble-voip/mumble#3543]
Some of the pathnames in Debug are longer than DOS permits, 260 characters (259 with terminating zero).

**Comment by azlux** [comment]
Maybe you can enable [longpath on windows](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) to avoid issue during debugging.

**Comment by Krzmbrzl** [comment]
Shouldn't be an issue with Win10 (afaik)
