### ISSUE TITLE
Upgrade Opus to 1.3

### ISSUE THREAD

**Issue by xaro1** [mumble-voip/mumble#3547]
https://people.xiph.org/~jm/opus/opus-1.3/

Lot of low bitrate speech improvements.

**Comment by wildxthing** [comment]
There is a newer version Opus 1.3.1 with some minor fixes.

http://opus-codec.org/release/stable/2019/04/12/libopus-1_3_1.html

**Comment by QmFzZTY0IGlzIGEgZW5jb25kaW5nI** [comment]
bump

**Comment by Krzmbrzl** [comment]
I assume this is more work than simply replacing the old library with the new one?

**Comment by davidebeatrici** [comment]
Updating the submodule is enough. If source files have been added/removed, we also have to update our build project:
https://github.com/mumble-voip/mumble/blob/713b92c3c233f8f38200c4a458e0196d3d39a3b0/3rdparty/opus-build/opus-build.pro#L77-L249
