### ISSUE TITLE
Question - Mumble Protocol - Ping necessary?

### ISSUE THREAD

**Issue by fbe** [mumble-voip/mumble#3550]
Hey,

I'm currently writing a mumble client library in Scala (https://github.com/fbe/mtbb) and I'm sure how to handle the keep alive ping.

Question 1: how often do I have to send a Ping package to avoid a connection close by the server?

Question 2: I figured out that sending Pings is only necessary when no other packages are being sent - sending packages like QueryUsers in an interval of 5 seconds is enough to avoid a disconnect - without sending additional ping packages. I think that this is a good behavior but is that as specified / wanted, too or may that change in further implementations of murmur?

Thanks =)

**Comment by bontibon** [comment]
If the server hasn't received any packet within 30 seconds it will drop the client.

While you could send other packet types to keep the connection alive, the Ping packet can be filled with statistical information. Sending a ping packet every 5-10 seconds is a good interval.

**Comment by fbe** [comment]
Thanks for the quick clarification!
