### ISSUE TITLE
Mouse lag when debugging

### ISSUE THREAD

**Issue by snaiperskaya96** [mumble-voip/mumble#3553]
Hi!
I'm sorry for opening an issue here. I'm like 99% sure i've seen something about it ages ago but i cannot manage to find it again.
Basically, while debugging, whenever a breakpoint is hit the mouse input becomes very unresponsive and it's hard to do anything.
In GlobalShortcut_win there's a comment in the winhook initialisation that describes the problem i'm having but still haven't find a way to prevent it without disabling hooks?
```
	// During this time, where the mouse callback is not able to be called,
	// the mouse in Windows becomes laggy. It makes the whole computer feel
	// like it has locked up -- because input "stops".
```

Any help would be very appreciated!
Thanks

**Comment by davidebeatrici** [comment]
Hi!

Sorry for the huge delay.

Hooks can be disabled with https://dl.mumble.info/reg/disable-winhooks.reg and be enabled again with https://dl.mumble.info/reg/enable-winhooks.reg.
