### ISSUE TITLE
In recent Mumble 1.3 versions you have to reconnect to see an updated registration status

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#3557]
In the current master version of Mumble I see the following behavior:

1. A new user joins the server
2. The user is registered
3. I don't see the tick mark appear immediately

I have to reconnect my client in order to see the updated registration status.

With commit 48277cb2 it still works immediatly.

I'm currently trying to find the exact commit where it stopped working.

**Comment by promi** [comment]
I have identified the problematic commit:

Commit 68aae1d still works.
Commit 3a51d6b breaks the immediate refresh. (which has 68aae1d as its parent commit!)

Here is a table of commits I tried:

1098afc 5.  July   = works
e54f60f 7.  July   = works
fbe0638 8.  July   = works
68aae1d 15. July   = works
3a51d6b 17. July   = broken
3fa973c 14. August = broken

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue and identifying the commit which introduced it!

I created #3559 to fix it, please test and review.
