### ISSUE TITLE
Notification consistency?

### ISSUE THREAD

**Issue by gyvess** [mumble-voip/mumble#3562]
I recently enabled notifications for specific events and I'm finding it to be fickle.  At times the notification will appear from a word bubble from tray icon in polybar.  Other times it will use my designated notification program, mate-notification-daemon.  Sometimes it doesn't show at all.

My desired behavior is Mumble notification would always pipe through your notification program of choice.  Is there anything I can do to get this to happen or does it require a change in the sourcecode?  Maybe Mumble plays better with a different notification program like Dunst?  I've been planning to switch to Dunst but have been procrastinating on setting it up.

**Comment by Kissaki** [comment]
Does it stay consistent between notification types? Or is it random?

What notification category shows in one compared to another? (So we can check what the difference is, if we possibly trigger them differently.)

**Comment by gyvess** [comment]
I've only enabled notifications for "Other self-muted/deafened" and the notification type it appears in is seemingly random, though it appears as a tooltip from tray far more often than using my notification daemon.

I guess I can play around with it a bit more to see what kind of behavior it exhibits with other messages toggled to send notifications.

**Comment by gyvess** [comment]
It has now been over a week since I've enabled notifications for a number of other messages, and I can report that the behavior remains the mostly same throughout.  Though I can't recall any notification ever using the mate-notification-daemon in the past week.  It has always been from the tray or not at all.

I could could chalk it up to mate-notification-daemon itself, the daemon has worked fine for something like streamlinkg-twitch-gui for example.  Absolutely no problems there.
