### ISSUE TITLE
Machine Learning Mumble

### ISSUE THREAD

**Issue by DarkArc** [mumble-voip/mumble#3581]
I'm posting this as a conversation starter... (in part in case I get time to explore any of these ideas further, I'd like to know the thoughts of the mumble community prior to starting the work)

Has there been much investigation of the possibility of integrating machine learning into mumble? I've listed a few ideas for potential problems with VoIP communication that -- I think -- have a high probability of being solvable with machine learning techniques.

### Audio Classification (Voice Activation 2.0)

How awesome would it be to completely remove the unfortunate circumstance where you're on mumble and you hear:
- someone typing
- someone clicking their mouse
- someone messing with a bag of some form
- someone eating potato chips
- etc

I think this has the most potential as far as being a "killer feature" for mumble, as I'm unaware of anyone else currently doing it. If high quality, low latency detection could be achieved, I could see this being something that people fall in love with.

### Volume Normalization

Using machine learning, in theory, it should be possible to better normalize volumes as well. This may also be solvable without machine learning, and I believe many other clients already do this with automatic volume gain. Regardless, I think it's something we could likely do.

### Personalized Voice Profile (Voice Activation 3.0?)

Give a sufficient audio classification implementation, or potentially making people read a small paragraph, we could potentially have a custom voice activation model on an individual level. This could allow for mumble to be used in louder environments with many people around -- lan parties, shared living spaces, etc.

### Separate Library

I think it's imperative that if this work is started, we keep it in a separate from the core mumble project as much as possible. That's to say, this should be developed in a library, or an existing library should be found and used. 

With commercial alternatives to mumble, teamspeak, and discord as primary competitors. I think mumble can take two approaches. One is to compete, one is to collaborate. 

If we're going to compete, it would likely be best to do this work under GPL and reliscense at least the combined form of mumble + this machine learning library as GPL. This would prevent commercial competitors from taking the work and using it in their own products as the current BSD license would allow.

If we're going to collaborate with them, the end goal would be to create a library so great that they want to use it, rather than starting over themselves -- with the hope they'd contribute upstream, and be good open source citizens. 

In either case, I think the best place for work along these lines that would be most likely to receive collaboration from developers not interested in mumble, but interested in these topics, would be a separate library.

**Comment by Kissaki** [comment]
Hello DarkArc

Thank you for the elaborative initiative and well presented arguments.

Machine learning is not fit to replace every algorithm. It is a current hype, and we should be careful not to introduce it where it does not make sense.

The disadvantages of machine learning are that it is not readable/verifiable like an classic algorithm is. It’s complexity is (probably) higher, and the performance hit for continuous learning is usually higher.

For example volume normalization seems to me like it can be solved best with a classic algorithm. Machine learning may work as well, but it is unnecessary, and complexity and non-analyzability always causes issues in maintainability or unnecessarily impacts performance. For normalization you have a target volume level, and some edge conditions - that seems like a relatively simple problem field. So I don’t see how machine learning to be “better” at it as you claim.

That being said, there are valid use cases for machine learning and if we can test impact and conclude it is useful/better than a classic algorithm then I’m all for it.

**Comment by Ytmndissue** [comment]
My guess is that you wouldn't use machine learning in Mumble itself, but rather use it with a dataset of proper use cases of when the mic is supposed to activate (like in the situations you mentioned) and use the resulting "data decision tree" with Mumble as a static blob of code in conjunction with its regular listening mode.

Unique, but I have no idea how you'd even get started with this - and there'd still be glitches for cases where this thing isn't trained for.

**Comment by azlux** [comment]
Have you try the version 1.3 ? 
https://github.com/mumble-voip/mumble/commit/e54f60f44dd61c33309b97e687c1e50751c822a9 : Added RNNoise - An advanced noise suppression system by Xiph.Org

This new feature work like a charm in my case, the microphone don't start with mouse click and keyboard button anymore.

**Comment by Kissaki** [comment]
Closing as the discussion seems to have concluded/subsided.

The RNNoise implementation has been pointed out, some areas were suggested but did not become actionable concrete for now. As a general discussion topic, this ended.
