### ISSUE TITLE
Disable News output on server connection

### ISSUE THREAD

**Issue by joeBwanKenobi** [mumble-voip/mumble#3582]
Is there any way to disable the mumble "News" or updates that are posted in text chat when joining a server?
![mumble-news](https://user-images.githubusercontent.com/3845419/51615206-467e1680-1ef5-11e9-8924-74f232a55de5.PNG)

**Comment by Kissaki** [comment]
That is not in fact on server connect. It is when you start a Snapshot client.

Development snapshots were originally planned for testing, this startup message was to announce any new features and testing focus. There is no way to disable this at the moment.

I can see it being somewhat much/big and often this is seen.

**Comment by Krzmbrzl** [comment]
I have never seen such things. Also recently snapshots are allowed to disable auto-updates (whcih I think this ultimately is).
Thus I think is issue can be closed
