### ISSUE TITLE
Disable Controller In Overlay

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#3596]
When I open the Steam Overlay for any of my games and use a XInput controller I am unable to control my character in the game while the overlay is opened. The Mumble overlay on the other hand does not do this. I would to have it where when the Mumble Overlay is open my controller will not interact with the game and that way I can interact with the Mumble Overlay instead.

**Comment by Krzmbrzl** [comment]
Isn't the overlay kind of "read-only" @davidebeatrici ?

**Comment by Kissaki** [comment]
The overlay does not use or block any input.

We had an interactive overlay previously, but this had to be toggled on and of and visibly changed between the readonly overlay and the interactive overlay.

This report is unclear and needs more info, or is not or can not be an issue (anymore) with only the reaonly overlay.
