### ISSUE TITLE
Are we stuck?

### ISSUE THREAD

**Issue by christianreiss** [mumble-voip/mumble#3599]
Hey folks,

year long user here. For over a year I was wondering what's up with the project as the latest release is dated 2017-- no official releases since then. Is there a reason for the apparent lack of releases?

Cheers,
-Christian.

**Comment by anarcat** [comment]
there's a discussion of the release process in #2728, i think this issue is a duplicate and should be closed.

**Comment by anarcat** [comment]
thanks!
