### ISSUE TITLE
Mumble crashes after starting

### ISSUE THREAD

**Issue by frontendschlampe** [mumble-voip/mumble#3609]
After updating from ```1.3.0~2729~g2126495~snapshot``` to ```1.3.0~2942~g755c290~snapshot``` on MacOS 10.14.3 (18D109) Mumble crashes directly after starting. I can send a crash report, but nothing more.

**Comment by hemna** [comment]
same for me.   Just installed 1.2.19 and it crashes instantly on start.  
Mac OSX 10.14.3

**Comment by davidebeatrici** [comment]
Workaround: https://github.com/mumble-voip/mumble/issues/3471#issuecomment-410490926

**Comment by frontendschlampe** [comment]
> Workaround: [#3471 (comment)](https://github.com/mumble-voip/mumble/issues/3471#issuecomment-410490926)

thx :-)

**Comment by davidebeatrici** [comment]
You're welcome!

Closing this as duplicate of #3471.
