### ISSUE TITLE
wrong object opacity calculation in overlay settings

### ISSUE THREAD

**Issue by deluxghost** [mumble-voip/mumble#3615]
https://github.com/mumble-voip/mumble/blob/1974ac0f2fc8880d351e5a905fa8c144e3257821/src/mumble/OverlayEditorScene.cpp#L559

this makes opacity options be 12.5%, 112.5%, 212.5%... which should be 12.5%, 25%...

should change this line to be same as user opacity:
https://github.com/mumble-voip/mumble/blob/1974ac0f2fc8880d351e5a905fa8c144e3257821/src/mumble/OverlayEditorScene.cpp#L528

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!
