### ISSUE TITLE
Global.h's g macro causes failure with protobuf-3.7.0

### ISSUE THREAD

**Issue by atsampson** [mumble-voip/mumble#3617]
I've just tried to build mumble 1.2.19 against the newly-released protobuf 3.7.0, and it fails as follows while building several source files (basically, anything that includes Mumble.pb.h indirectly after including Global.h). I'm passing `-ftrack-macro-expansion=0` to g++ here so it shows where the macro is being expanded from rather than its definition.

```
In file included from /gar/include/google/protobuf/message_lite.h:49,
                 from /gar/include/google/protobuf/wire_format_lite_inl.h:45,
                 from /gar/include/google/protobuf/map_type_handler.h:35,
                 from /gar/include/google/protobuf/map.h:49,
                 from /gar/include/google/protobuf/generated_message_table_driven.h:34,          
                 from Mumble.pb.h:26,
                 from ServerHandler.h:57,
                 from BanEditor.cpp:38:
/gar/include/google/protobuf/stubs/strutil.h: At global scope:
/gar/include/google/protobuf/stubs/strutil.h:720:47: error: expected ',' or '.. ' before '(' token             
                               const AlphaNum& g);
                                               ^
```

So the problem is that Global.h has defined a macro called `g`, and the protobuf headers use `g` as an argument name. Adding `#include "Mumble.pb.h"` before `#define g` in Global.h works as a horrible workaround but I'm sure there's a better fix out there!

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

It is now fixed in `master`.
