### ISSUE TITLE
Mumble 1.2.19 "freezes" 15s after launch, can still hear other talking 

### ISSUE THREAD

**Issue by vlsddy** [mumble-voip/mumble#3625]
Hi,

I'm having problems with mumble. For the first 15 seconds after launching mumble everything seems to be working fine. I can talk on channels and buttons on the UI are functional. But after that (about) 15 seconds, my voice stops transmitting and the "lips" next to my username wont show any activity when pressing my assigned push-to-talk button. I can write to channel chat and my messages are visible to my friends on the channel, but to me they don't show up, nor do I see the text I'm writing. Until I move or resize the window by dragging from some corner, then they all instantly come visible to me as well. All activity freezes until I resize the window, but I can still hear my friends talking.

All the menus are sort of not responding (Server, self, configure and help) . Some times they are greyed out, but then again after playing with the window size/position the text on them turns black again. But clicking on them seems to do nothing, as if the program is not responding. But if I click a menu, and then slide my cursor on the menu next to it, that menu opens up. So I can sort of navigate in the menus, but I can't see where I'm going since it doesn't react to my mouse clicks. Mute buttons seem to work normally though.

I've tried installing mumble again, installing an older version, and nothing seems to fix this. I had no problems with mumble before (with current build/windows), but can't really tell when this problem exactly appeared. For example in cs go the ingame voice communication works perfectly. The console file looks like this:

```
<W>2019-03-07 20:18:49.584 DirectSound: Disabled as WASAPI is available
<W>2019-03-07 20:18:49.616 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<W>2019-03-07 20:18:49.617 CELT bitstream 8000000b from C:/Program Files (x86)/Mumble/celt0.0.7.0.sse2.dll
<W>2019-03-07 20:18:49.618 CELT bitstream 80000010 from C:/Program Files (x86)/Mumble/celt0.0.11.0.sse2.dll
<W>2019-03-07 20:18:49.618 Locale is "fi_FI" (System: "fi_FI")
<W>2019-03-07 20:18:49.679 Database SQLite: "3.14.1" 
<W>2019-03-07 20:18:49.679 Bonjour: Failed to load dnssd.dll
<W>2019-03-07 20:18:49.797 Overlay: Listening on "\\.\pipe\MumbleOverlayPipe" 
<W>2019-03-07 20:18:49.893 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2019-03-07 20:18:50.049 XboxInput: using XInput DLL 'XInput1_4.dll'
<W>2019-03-07 20:18:50.049 XboxInput: using XInputGetStateEx() as querying function.
<W>2019-03-07 20:18:50.049 GlobalShortcutWin: XboxInput initialized, isValid: 1
<W>2019-03-07 20:18:50.062 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2019-03-07 20:18:50.068 WASAPIInput: Latencies 100000 30000 => 100000
<W>2019-03-07 20:18:50.079 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Hiiri Hiiri:5
<W>2019-03-07 20:18:50.081 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} N?pp?imist? N?pp?imist?:126
<W>2019-03-07 20:18:50.097 Adding device {c001bd60-28b2-11e9-8001-444553540000} Razer BlackWidow Ultimate Razer BlackWidow Ultimate:573
<W>2019-03-07 20:18:50.099 Adding device {c0020b80-28b2-11e9-8003-444553540000} Razer BlackWidow Ultimate Razer BlackWidow Ultimate:3
<W>2019-03-07 20:18:50.101 Adding device {c0023290-28b2-11e9-8005-444553540000} Razer BlackWidow Ultimate Razer BlackWidow Ultimate:1
<W>2019-03-07 20:18:50.118 Adding device {c001bd60-28b2-11e9-8002-444553540000} Razer DeathAdder Chroma Razer DeathAdder Chroma:573
<W>2019-03-07 20:18:50.122 Adding device {c00280b0-28b2-11e9-8007-444553540000} Razer BlackWidow Ultimate Razer BlackWidow Ultimate:1
<W>2019-03-07 20:18:50.124 Adding device {c0023290-28b2-11e9-8004-444553540000} Razer DeathAdder Chroma Razer DeathAdder Chroma:3
<W>2019-03-07 20:18:50.127 Adding device {c00259a0-28b2-11e9-8006-444553540000} Razer DeathAdder Chroma Razer DeathAdder Chroma:1
<W>2019-03-07 20:18:50.129 Adding device {c00280b0-28b2-11e9-8008-444553540000} Razer DeathAdder Chroma Razer DeathAdder Chroma:1
<W>2019-03-07 20:18:50.165 WASAPIInput: Mic Stream format 1 
<W>2019-03-07 20:18:50.165 WASAPIInput: Stream Latency 0 (1056)
<W>2019-03-07 20:18:50.317 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2019-03-07 20:18:50.317 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2019-03-07 20:18:50.410 WASAPIOutput: Output stream format 1 
<W>2019-03-07 20:18:50.410 WASAPIOutput: Stream Latency 0 (2880)
<W>2019-03-07 20:18:50.410 WASAPIOutput: Periods 10000us 3000us (latency 0us)
<W>2019-03-07 20:18:50.410 WASAPIOutput: Buffer is 60000us (5)
<W>2019-03-07 20:18:50.412 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2019-03-07 20:18:52.056 OpenSSL Support: 1 (OpenSSL 1.0.2k  26 Jan 2017)
<W>2019-03-07 20:18:52.063 SSL: CA certificate filter applied. Filtered size: 86, original size: 86
<W>2019-03-07 20:18:52.063 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA"
<W>2019-03-07 20:18:52.065 ServerHandler: QOS2 loaded
```

Any help/suggestions what to do?

**Comment by davidebeatrici** [comment]
Hi,

Could you try to install the latest snapshot, please?

**Comment by vlsddy** [comment]
Installed it, seems to be working even more poorly. Now it doesn't react to anything after freezing. Can't even shut it down without task manager.

**Comment by davidebeatrici** [comment]
Do you perhaps have echo cancellation enabled?

**Comment by vlsddy** [comment]
No, I don't.

**Comment by davidebeatrici** [comment]
```
2019-03-07 20:18:50.079 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Hiiri Hiiri:5
2019-03-07 20:18:50.081 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} N?pp?imist? N?pp?imist?:126
```

What device is that? Could you try to unplug it and see if the issue persists, please?

**Comment by vlsddy** [comment]
Those are my mouse and keyboard.

I made a breakthrough. I found an old post saying Spotify caused an identical problem. Here https://github.com/mumble-voip/mumble/issues/1091

I don't have spotify on, but tried shutting down everything I can (except Chrome). Now mumble is working as it should. I shut down:

-Steam
-Asus GPU Tweak
-RamCache
-Asus EPU engine
-Bluetooth adapter
-CCleaner.

So now it's about starting them one by one and waiting for mumble to freeze.

**Comment by davidebeatrici** [comment]
> Those are my mouse and keyboard.

Aren't your keyboard and mouse the ones linked below (Razer BlackWidow Ultimate and Razer DeathAdder Chroma)?

> I don't have spotify on, but tried shutting down everything I can (except Chrome). Now mumble is working as it should.

Excellent!

> So now it's about starting them one by one and waiting for mumble to freeze.

Once we know which of those programs cause Mumble to freeze, we can investigate the cause.

**Comment by vlsddy** [comment]
It was ASUS GPU Tweak II. Funny thing is, this also seems to be the reason for my other problem with Battlefield 3. (If this is any help for finding the cause, shortly: I have a new build with i7 9700K and RTX2070 but was only getting 40fps on BF3 (8 years old game), no matter if video settings are low or ultra. Sometimes I would get 200fps for a few seconds, and then it dropped back to 40.)

To be precise, GPU Tweak II itself doesn't seem to be the one causing this problem, but GPU Tweak II Monitor. If I have the monitor (which, like the name indicates, monitors your GPU usage, GPU and memory clocks, temps etc..) running and then start mumble, mumble freezes. 

If I'm only running GPU Tweak II without the monitor, everything works just fine. If I start mumble first and then the monitor, everything works just fine.

So the problem is caused by the ASUS GPU Tweak II Monitor, but I can run it if I start it up only after starting mumble first.

**Comment by davidebeatrici** [comment]
Do you perhaps have Origin's overlay and/or Mumble's one enabled?

I would check the CPU usage while you're getting low FPS on Battlefield 3 and/or Mumble is frozen.

**Comment by vlsddy** [comment]
I had the GPU Tweak II Monitor overlay enabled. Shutting down the monitor also shuts down the overlay. 

With BF3 my GPU usage was only 10% and GPU Clock speed would spike from time to time, getting me thouse 200fps for a few seconds and then getting back to low usage. Didn't check CPU usage. But like said, disabling that Asus monitor got rid of that and now I'm running at constant 200fps.

My CPU usage is around 2% when running just mumble and I can't tell by the graph if mumble has frozen or not.

And to be even more precise, it's not even the Monitor itself that causes mumble to freeze. It's the OSD (on screen display) function in it, so basically the overlay.

**Comment by davidebeatrici** [comment]
That's why I asked whether you had Origin's overlay or Mumble's one enabled. it's possible that GPU Tweak II Monitor's OSD conflicts with them.

If your GPU usage was only at 10% with Battlefield 3, it's possible that the CPU usage was at 100% and thus it bottlenecked everything else.

**Comment by vlsddy** [comment]
That doesn't seem to be the case, since I don't have mumble overlay (and origin and asus overlays didn't cause this problem in BF5). I tried turning Asus overlay back again and play BF3, CPU usage is howering around 20% and GPU at 10%, but at times I get those 200FPS my cpu usage peaks at 50%.

Without the overlay my CPU usage in BF3 is around 30-50% and GPU 40% and everything is smooth.

Also it's weird, that mumble only freezes if I enable the overlay before launching mumble? If mumble is launched first, everything is ok. Now I've had mumble on the background for maybe an hour while enabling and disabling the overlay back and forth, and it's still working.

**Comment by Krzmbrzl** [comment]
I'd consider this issue to be resolved. If you don't, please let me know
