### ISSUE TITLE
QUIC as a transport protocol

### ISSUE THREAD

**Issue by Avamander** [mumble-voip/mumble#3637]
I think Mumble could benefit quite a lot by using QUIC as the transport protocol, given it has:
  * It's going to be used in HTTP/3 so it has the backing of big corporations, that means quite a lot of platforms are going to get good QUIC libraries/support
  * It has encryption built into it which reduces security concerns
  * The renegotiation takes less time thanks to less round trips
  * HTTP/3 will also probably have something websocket-like so it would be less hassle to speak that on top of an existing QUIC transport

What do you think?

**Comment by Kissaki** [comment]
> It has encryption built into it which reduces security concerns

What are your issues with the current encryption? And how does QUIC do that better?

**Comment by Avamander** [comment]
> What are your issues with the current encryption?

The rather poor cipher suite selection available and the lack of TLSv1.3.
