### ISSUE TITLE
[macOS] Mumble fails to load Opus library in recent snapshots

### ISSUE THREAD

**Issue by frontendschlampe** [mumble-voip/mumble#3642]
After a clean system installation with Mojave 10.14.3 on my mac, I can't use the dev-version of Mumble 1.3. I can install and start the above mentioned version without any problems, but the speech with other users is not possible. I see that the other people are talking with the changing color of there icon, but I can hear nothing or just some strange noises like interfering noises. The same problem exists if I want to talk. I tried to change my audio setting, but I can't solve the problem.

The latest stable version of 1.2 is working without any problems.

/cc @baumannsven

**Comment by frontendschlampe** [comment]
Version Mumble (1.3.0~2729~g2126495~snapshot) is working without any problems

**Comment by frontendschlampe** [comment]
Version 1.3.0-rc1 crashed on startup - after 5-6 restarts it opened, but I have the same problems mentioned above.

**Comment by frontendschlampe** [comment]
```Mumble-1.3.0~2961~g1ee050a~snapshot``` and ```Mumble-1.3.0~2942~g755c290~snapshot``` crashed on startup - after 2-6 restarts it opened, but I have the same problems mentioned above.

```Mumble-1.3.0~2935~gc176974~snapshot``` starts without any crashes, but I have the same problems mentioned above. I get the message "Failed to load Opus, it will not be available for audio encoding/decoding."

**Comment by davidebeatrici** [comment]
> I get the message "Failed to load Opus, it will not be available for audio encoding/decoding."

Do you get it with all versions (except `1.3.0~2729~g2126495~snapshot`)?

**Comment by frontendschlampe** [comment]
> Do you get it with all versions (except 1.3.0~2729~g2126495~snapshot)?

yes
