### ISSUE TITLE
Does the Murmur support LibreSSL?

### ISSUE THREAD

**Issue by MAH69IK** [mumble-voip/mumble#3643]
Hello! I wanted install Murmur on my Gentoo server but looks like Murmur depends on OpenSSL, but my system use LibreSSL.
This is problem with ebuild file or I relly cann't build Murmur with LibreSSL support?

**Comment by davidebeatrici** [comment]
Hello!

LibreSSL was forked from OpenSSL in 2014, in recent versions there are some differences between the APIs.

You should try to build Murmur and then paste here any errors you get, so that we can fix them.

**Comment by MAH69IK** [comment]
So, no problem at the first blush? Thank you, I will try to complie manually and report.

**Comment by hacst** [comment]
LibreSSL is nothing we test against. Even if it works now it is likely there might be breakage down the line (e.g. when we adopt/require more recent OpenSSL functionality and API) so be aware of that.

**Comment by mob3d** [comment]
I cannot build murmur on FreeBSD 11.2-RELEASE-p9 with libressl-2.8.3
It fails when compiling SelfSignedCertificate.cpp:

`c++ -Wl,-rpath,/usr/local/lib -fstack-protector -Wl,-z,relro -Wl,-z,now -fstack-protector -pthread -Wl,-rpath,/usr/local/lib/qt5 -o ../../release/murmurd ../../release/.obj/murmur/ACL.o  ../../release/.obj/murmur/Group.o  ../../release/.obj/murmur/Channel.o  ../../release/.obj/murmur/Connection.o  ../../release/.obj/murmur/HTMLFilter.o  ../../release/.obj/murmur/User.o  ../../release/.obj/murmur/Timer.o  ../../release/.obj/murmur/CryptState.o  ../../release/.obj/murmur/OSInfo.o  ../../release/.obj/murmur/SSL.o  ../../release/.obj/murmur/Version.o  ../../release/.obj/murmur/SSLCipherInfo.o  ../../release/.obj/murmur/License.o  ../../release/.obj/murmur/LogEmitter.o  ../../release/.obj/murmur/CryptographicHash.o  ../../release/.obj/murmur/CryptographicRandom.o  ../../release/.obj/murmur/PasswordGenerator.o  ../../release/.obj/murmur/HostAddress.o  ../../release/.obj/murmur/Ban.o  ../../release/.obj/murmur/EnvUtils.o  ../../release/.obj/murmur/UnresolvedServerAddress.o  ../../release/.obj/murmur/ServerAddress.o  ../../release/.obj/murmur/ServerResolver_qt5.o  ../../release/.obj/murmur/ServerResolverRecord.o  ../../release/.obj/murmur/SelfSignedCertificate.o  ../../release/.obj/murmur/SSLLocks.o  ../../release/.obj/murmur/FFDHE.o  ../../release/.obj/murmur/arc4random_uniform.o  ../../release/.obj/murmur/main.o  ../../release/.obj/murmur/Server.o  ../../release/.obj/murmur/ServerUser.o  ../../release/.obj/murmur/ServerDB.o  ../../release/.obj/murmur/Register.o  ../../release/.obj/murmur/Cert.o  ../../release/.obj/murmur/Messages.o  ../../release/.obj/murmur/Meta.o  ../../release/.obj/murmur/RPC.o  ../../release/.obj/murmur/PBKDF2.o  ../../release/.obj/murmur/UnixMurmur.o  ../../release/.obj/murmur/BonjourServiceRegister.o  ../../release/.obj/murmur/BonjourServer.o  ../../release/.obj/murmur/moc_ACL.o  ../../release/.obj/murmur/moc_Channel.o  ../../release/.obj/murmur/moc_Connection.o  ../../release/.obj/murmur/moc_LogEmitter.o  ../../release/.obj/murmur/moc_ServerResolver.o  ../../release/.obj/murmur/moc_Server.o  ../../release/.obj/murmur/moc_ServerUser.o  ../../release/.obj/murmur/moc_Meta.o  ../../release/.obj/murmur/moc_UnixMurmur.o  ../../release/.obj/murmur/moc_BonjourServiceRegister.o  ../../release/.obj/murmur/moc_BonjourServer.o   -L/var/ports/usr/ports/audio/murmur/work/mumble-1.3.0-rc1/release -L/usr/lib -L/usr/local/lib -lmumble_proto -lcrypto -lssl -ldns_sd -lprotobuf -pthread -L/usr/local/lib/qt5 -lQt5Network -lQt5Sql -lQt5Xml -lQt5Core -lkvm -lprocstat
../../release/.obj/murmur/SelfSignedCertificate.o: In function `SelfSignedCertificate::generate(CertificateType, QString, QString, QSslCertificate&, QSslKey&)':
SelfSignedCertificate.cpp:(.text+0x13c): undefined reference to `X509_getm_notBefore'
SelfSignedCertificate.cpp:(.text+0x169): undefined reference to `X509_getm_notAfter'
`
Complete build log:
[murmurbuild.txt](https://github.com/mumble-voip/mumble/files/3084844/murmurbuild.txt)

Do you have any ideas to fix this?

**Comment by siavash119** [comment]
i'm on gentoo ~amd64 using libressl, and 1.3.0_rc1 builds and works fine

**Comment by Krzmbrzl** [comment]
I guess this question has been answered. Thus I'll close this issue.
If this isn't correct, please let me know :)
