### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by Immortalin** [mumble-voip/mumble#3647]
WebAssembly would allow it to run faster in browser.  Would be nice to integrate with https://github.com/mumble-voip/grumble/issues/33

There's also https://github.com/Rantanen/mumble-web

**Comment by Kissaki** [comment]
I don’t quite get what you’re trying to say?

WebAssembly is a web technology. We do not currently ship web tech clients or servers. If you want to feature request such then I think we already have a ticket for that, and WebAssembly is an implementation technology for that, but for now nothing we should have a separate ticket for.

So unless you object I will close this as such.

**Comment by Immortalin** [comment]
Would be great if you could reference the other ticket here. Would save a lot of code if you compile the existing client to WebAssembly directly and tunnel it through WebRTC.

**Comment by Kissaki** [comment]
There is #2131 and #3561.

Dunno how viable using existing client code in WebAssembly would be. I would not expect much. The target is quite different, and I don't think the client transport and decision code is separate enough from the Qt GUI, the multiplatform code makes it quite complex and conditional, …. Porting something like libmumble may be more viable.
