### ISSUE TITLE
Website IPv6 support

### ISSUE THREAD

**Issue by tambry** [mumble-voip/mumble#3648]
[The wiki/website](https://wiki.mumble.info/wiki/Main_Page) doesn't support IPv6.

Per [Fastly's IPv6 documentation](https://docs.fastly.com/guides/basic-setup/ipv6-support.html), it's simply necessary to change the CNAME from `osff.map.fastly.net` to `dualstack.osff.map.fastly.net`.

**Comment by davidebeatrici** [comment]
Done, thank you very much!
