### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [mumble-voip/mumble#3649]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [GRPCStop](https://github.com/mumble-voip/mumble/blob/4976c1ad2e0802755c15d051783403afc440b173/src/murmur/MurmurGRPCImpl.cpp#L129 "GRPCStop function")
- [JackAudioInit::destroy](https://github.com/mumble-voip/mumble/blob/4976c1ad2e0802755c15d051783403afc440b173/src/mumble/JackAudio.cpp#L88 "JackAudioInit::destroy function")
- [Server::removeBonjour](https://github.com/mumble-voip/mumble/blob/4976c1ad2e0802755c15d051783403afc440b173/src/murmur/Server.cpp#L623 "Server::removeBonjour function")

**Comment by davidebeatrici** [comment]
Thank you very much for your report!

**Comment by elfring** [comment]
:eyes: See also remaining update candidates:
* https://github.com/mumble-voip/mumble/blob/ff2a2332cccb267721553f09c0ded4de880622e0/src/mumble/Overlay.cpp#L199-L201
* https://github.com/mumble-voip/mumble/blob/ff2a2332cccb267721553f09c0ded4de880622e0/src/mumble/PluginInstaller.cpp#L72-L74
