### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [mumble-voip/mumble#3650]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")” (or “[QScopedPointer](https://doc.qt.io/qt-5/qscopedpointer.html#details "Description for the QScopedPointer class")”)?

Update candidates:
- [BonjourClient](https://github.com/mumble-voip/mumble/blob/4976c1ad2e0802755c15d051783403afc440b173/src/mumble/BonjourClient.cpp#L13)
- [OverlayClient](https://github.com/mumble-voip/mumble/blob/c014e04f44e66a41ad4a2ef12a4d4816726206f3/src/mumble/OverlayClient.cpp#L25)

**Comment by davidebeatrici** [comment]
Definitely.

**Comment by elfring** [comment]
[A few update candidates were left over](https://github.com/mumble-voip/mumble/blob/628c067034f598c0e2dd8ca5a1e28b551118986c/src/mumble/AudioOutputSpeech.cpp#L89 "Update candidate: AudioOutputSpeech class").
