### ISSUE TITLE
Static Murmur 1.3.0 RC1 permanently blocks a client's messages after the flood limit is triggered

### ISSUE THREAD

**Issue by ncc757** [mumble-voip/mumble#3662]
Mumble client version: 1.3.0 RC1 & 1.3.0 (1.3.0~2961~g1ee050a~snapshot)
Mumble server version: 1.3.0-rc1 Ubuntu 16.04 LTS Server

Users will get stuck local muted and deafened after local muting and deafening themselves. It shows the users as being local muted and deafened in the channel to everyone include whoever is having the issue, but the symbols next to the recording button indicates to the user that they are not.
![image](https://user-images.githubusercontent.com/47647314/55675455-58325180-5888-11e9-89f4-3a1e97c484d8.png)

Sometimes when users attempt to mute and deafen themselves they still hear everyone. They look like they are muted and deafened on their client, but still hear everyone. To clarify, while the symbols next to the record button indicate they are muted and deafened, the symbols that should occur opposite their name do not. When this happens they are able to un-mute and un-deafen themselves, but upon muting and deafening again, the issue returns. 
![image](https://user-images.githubusercontent.com/47647314/55675446-4e105300-5888-11e9-9e7a-76da17e0e5a5.png)

Additionally when either of these occur the user can no longer change channels or send text message. More specifically messages can be sent but no one will receive them. However, these issues can appear independently as well.

In all cases after disconnecting and reconnecting cause the issues disappear temporarily.

To reproduce the issue simply change between muted and deafened and un-muted and un-deafened. It does not occur every time, but it is rather frequent, so it is not hard for us to reproduce. Doing this produces all of the stated issues, which issue occurs appears to be random.

Issue appears **somewhat** similar to #2516 but is different

**Comment by davidebeatrici** [comment]
#3517

Could you try to increase the `messageburst` and `messagelimit` options' value, please?

**Comment by ncc757** [comment]
I increased the value of messageburst to 10 and messagelimit to 5.
Upon rebooting the mumble server, the issue still occurred.

I then increased them further
messageburst=100
messagelimit=50
And the issue remains

**Comment by Natenom** [comment]
Did you add both values into the murmur.ini file? If so, you must add it before the [Ice] section.

**Comment by ncc757** [comment]
I changed the existing values, which were located above `[Ice]`
![image](https://user-images.githubusercontent.com/47647314/55675784-00e2b000-588d-11e9-8450-10ec2d2e3f7e.png)

**Comment by maritz** [comment]
Same thing happening for me after I updated my murmur to 1.3.0-rc1. Happens regardless of client version. (Same for me with 1.3.0-rc1 as for a friend with 1.2.9)

I reverted to murmur-static_x86-1.3.0~1492~g2f88605~snapshot (a few months old) and it works fine again.

**Comment by ncc757** [comment]
@maritz interesting, when I increase the limit it seems to have no impact at all. What values did you set in your config? I do not believe it is simply lacking a feedback mechanism as the mute and deafen feature become broken, as previously described, until you reconnect. If you just wait, it remains broken.

Additionally it does not appear to be a spam issue because it occurs even if we use mute and deafen extremely infrequently.

I think I will follow your advice and revert to an earlier version for the time being, if I am able to, as this version is too unreliable.

**Comment by maritz** [comment]
I also used 100/50 now. If I then spam mute/unmute for a bit I get the same behaviour again, which I assume is intended.

So I definitely do not experience the same issues you are describing.

**Comment by davidebeatrici** [comment]
@ncc757 Are you using our static Murmur build?
