### ISSUE TITLE
Mumble configuration option consistency (1.3rc-1)

### ISSUE THREAD

**Issue by srive** [mumble-voip/mumble#3665]
This is an incredibly minor issue but you may want to consider removing the period from "Attenuate other users while talking as Priority Speaker." under audio output in the mumble configuration screen since none of the other options have one.

**Comment by Kissaki** [comment]
Thanks for the heads up. Should happen after the 1.3.0 release - as strings are frozen for that right now.

**Comment by darelover** [comment]
I think this issue should be closed now since PR #3669 has already solved it

**Comment by davidebeatrici** [comment]
Indeed, thank you!
