### ISSUE TITLE
mumble server for android

### ISSUE THREAD

**Issue by farooqkz** [mumble-voip/mumble#3668]

**Comment by Serkan-devel** [comment]
It wouldn't be a good idea to use server software like that on a mobile device that won't be secure

**Comment by farooqkz** [comment]
I don't understand, @Serkan-devel

**Comment by Serkan-devel** [comment]
You want to host a mumble server on an android phone?

**Comment by farooqkz** [comment]
I don't want to since I don't have an Android device but I think server software for Android is a good idea. I think mumble has other uses than just gaming. Consider many Android devices in the same place which their users can't talk each other like what they always do and need a VoIP solution.

**Comment by Serkan-devel** [comment]
I think projects like cjdns/hyperboria are more suited for lower-powered devices to interact with each over p2p. 

Running mumble server on a regular android phone would cause lag with higher CPU usage  for example

**Comment by farooqkz** [comment]
I didn't know about that high usage. I've got no idea.

**Comment by JuniorJPDJ** [comment]
Just use termux to set server up.
It's possible and as easy as on normal linux system.

**Comment by farooqkz** [comment]
> Just use termux to set server up.
> It's possible and as easy as on normal linux system.

How about binaries?

**Comment by JuniorJPDJ** [comment]
@farooqkz you don't need binaries, you can just build the server

**Comment by Serkan-devel** [comment]
Maybe binaries can be pre-built https://github.com/termux/termux-packages/issues/3766

**Comment by Carbonis** [comment]
I hosted for a while my own Mumble Server on an old Honor 4x (Android KitKat) installing Murmur via Debian No Root app downloadable for free in the PlayStore. It is surprisingly stable and fast.

**Comment by Krzmbrzl** [comment]
Using an android device (a phone or even a tablet) doesn't really make sense to me. If useful at all I suspect this to affect the absolute minority of users and I just don't see it worth the effort of creating an Android server.

**Comment by lexterror** [comment]
@farooqkz 

https://github.com/mumble-voip/mumble/issues/6207
