### ISSUE TITLE
Client targets messages incorrectly

### ISSUE THREAD

**Issue by sebastiannielsen** [mumble-voip/mumble#3671]
If a user does only have text write rights in the channel, lets say #talk, but does not have text write rights in the root channel.

If you then click on #talk, it will be greyed out and you can't write, even if you have write rights.
You must actually click a member of the channel for it to recongnize that you want to write to the current channel and not parent channel.

This behaviour needs to be changed. I would suggest that selecting a channel will target messages to the channel, and not the parent channel.

**Comment by azlux** [comment]
Hi,
What is you current mumble version ?
