### ISSUE TITLE
Horrible buzzing

### ISSUE THREAD

**Issue by MarcusLepidus** [mumble-voip/mumble#3672]
Whenever I join a channel, there is a loud buzzing sound, correlated with people speaking. I cannot hear any voices, just this buzzing. Sometimes, when someone is indicated to be speaking, there is no noise, but other times, this sound comes back.

I have tried using two types of headphones, changing Output between Default/Built-in, and unplugging my headphones, but they all have the same result.

I can hear the notification and connection noises fine, but when joining a channel there is often the buzzing, without a certain pattern or repeating frequency.

Edit: OS is MacOS Mojave, Version 10.14.

**Comment by Kissaki** [comment]
My guess would be the audio is decoded with the wrong codec/you're missing the adequate codec.

Which version of Mumble are you using and where did you get it from?

**Comment by Kas-tle** [comment]
Sorry for being a little late, but I had this issue and was able to fix by manually installing opus. If you have homebrew, `brew install opus` should do the trick.

**Comment by sollematthew** [comment]
That fixed the issue for me on MacOS Mojave. Thank you.

**Comment by Kissaki** [comment]
The client should probably make it more obvious that Opus is missing. Or better yet, make it a dependency.

We have the server setting `suggestversion`, but we should probably focus on adoption of Opus now, and reasonably so.

**Comment by davidebeatrici** [comment]
Fixed by #3646, the Opus library was missing from the App Bundle.

https://github.com/mumble-voip/mumble/blob/4976c1ad2e0802755c15d051783403afc440b173/src/mumble/Audio.cpp#L35

We should transform that into a chat (error) message.
