### ISSUE TITLE
Can not join channels after try to join a channel whith no permission to join

### ISSUE THREAD

**Issue by huggenknubbel** [mumble-voip/mumble#3673]
Mumble Server version: 1.3 RC1 running on debian 
Mumble Client version: 1.3 RC1 running on Windows
After try to join a Channel without permissions to join, i can't join any channel. Same issue as SuperUser.

**Comment by Krzmbrzl** [comment]
I performed the described steps multiple times during development and I wasn't able to reproduce this issue. Does this only occur on a specific server perhaps?
Does this issue even persist in the now released version 1.3?

**Comment by huggenknubbel** [comment]
Oh, Sorry, i forgot that issue. 
The issue dissapeared with RC 2 and the now released Stable version.
And i tested it only on my own server. So i can't say if it occoured on other Servers.

**Comment by Krzmbrzl** [comment]
No problem - glad to hear that it seems to have been fixed now :)
