### ISSUE TITLE
Cannot stop murmur server from command or bash on windows

### ISSUE THREAD

**Issue by ArnoBen** [mumble-voip/mumble#3678]
Greetings,
I am looking for a way to stop a murmur server on windows from a command line with no success and nothing stated in the documentation. Is it possible ? Of course I can start it with start murmur.exe but closing requires right-clicking on the icon in the taskbar which is not my desired behaviour.
The most "radical" solution would be to kill the process with taskkill /im "murmur.exe" /f but this doesn't strike me as a clean way to do things.
Thanks for any help.

**Comment by davidebeatrici** [comment]
Greetings,

You can use the `taskkill` command to terminate a process gracefully.

For example:
```
taskkill /IM murmur.exe
```

**Comment by ArnoBen** [comment]
I see that as force-quitting a program but actually it sounds good for a murmur server. Thank you very much for your fast answer, now that I know it's a good solution I'm all set 😄 .

**Comment by davidebeatrici** [comment]
You're welcome!

`taskkill` terminates the process forcibly if you specify the `/F` parameter.
