### ISSUE TITLE
Click on tray to toggle UI visibility

### ISSUE THREAD

**Issue by filippog** [mumble-voip/mumble#3680]
Hi,
thanks for mumble! I'm using `1.3.0~git20190125.440b173+dfsg-2` and when mumble is hidden I can click on the tray icon to make the UI visible again. What I can't do is hide mumble again by using only the tray icon to do so, either by clicking on the tray icon or right-click then "hide" from the menu.

What do you think?

**Comment by davidebeatrici** [comment]
Hi!

I agree, being able to hide the UI by clicking on the tray icon would be useful especially in case the "Hide in tray when minimized" option is disabled.

Right now Mumble cannot be minimized to the tray if that option is not enabled (it's minimized to the taskbar instead).

**Comment by filippog** [comment]
Hi, thanks for the quick reply. Looking forward to see this feature implemented :+1:

**Comment by davidebeatrici** [comment]
You're welcome!

**Comment by davidebeatrici** [comment]
Implemented in #3691.
