### ISSUE TITLE
Segfault if jackd is not available

### ISSUE THREAD

**Issue by gileri** [mumble-voip/mumble#3682]
JACK seems the default input/output system when built-in. When mumble fails to connect to jackd a segfault is triggered, so mumble cannot be started with its default configuration if jackd is not available.

## Logs
```<W>2019-05-01 22:00:13.544 AudioInput: Opus encoder set for VOIP
<W>2019-05-01 22:00:13.544 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2019-05-01 22:00:13.544 PulseAudio: Starting input alsa_input.pci-0000_06_01.0.analog-mono
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=Aucun fichier ou dossier de ce type)
attempt to connect to server failed
<W>2019-05-01 22:00:13.549 JackAudioSystem: unable to open client due to 2 errors:
<W>2019-05-01 22:00:13.549 JackAudioSystem:  JackFailure - overall operation failed
<W>2019-05-01 22:00:13.549 JackAudioSystem:  JackServerFailed - unable to connect to the JACK server
Segmentation fault (core dumped)
```

## Stack Trace

```                Stack trace of thread 27065:
                #0  0x00007efdeacb1dd5 jack_port_register (libjack.so.0)
                #1  0x00005579f3ab2a98 _ZN15JackAudioSystem15initializeInputEv (mumble)
                #2  0x00005579f3ab2b62 _ZN14JackAudioInput3runEv (mumble)
                #3  0x00007efde98d163c n/a (libQt5Core.so.5)
                #4  0x00007efde97f9a92 start_thread (libpthread.so.0)
                #5  0x00007efde9435cd3 __clone (libc.so.6)
```

Setting `jack/autoconnect` to `false` does not help.

# Environment
Up-to-date Archlinux with [jack](https://www.archlinux.org/packages/extra/x86_64/jack/) installed (`ffmpeg` dependency). Default JACK configuration on Arch doesn't allow `jackd` startup because of [permission issues](https://wiki.archlinux.org/index.php/Jack#Installation). I understand that jackd should be startable by mumble, but in case of errors I think it should disable JACK input/output instead of segfaulting, especially because this [error seems expected](https://github.com/mumble-voip/mumble/pull/3396/files#diff-34d235dc674ee341f5419adaf619b897R31)

Don't hesitate to ask for more info, I'm new around here.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

Did you install Mumble from AUR? If that's the case, please try to add:
```cpp
if (!jasys->bJackIsGood) {
	if (jao) { 
 		jao->qmMutex.unlock(); 
	}

	return;
}
```

After `init_jack();` inside the following functions:
https://github.com/mumble-voip/mumble/blob/0f39a12291400d6067a3ee7710b0fd28ed28779a/src/mumble/JackAudio.cpp#L372-L395

https://github.com/mumble-voip/mumble/blob/0f39a12291400d6067a3ee7710b0fd28ed28779a/src/mumble/JackAudio.cpp#L425-L455

**Comment by gileri** [comment]
No problem, thank you.

The problem is visible on the [current "stable" package version](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/mumble&id=aaf4876c8627702071a9c3d1ce702e1169f1b18d). I've created a [branch with your patch](https://github.com/mumble-voip/mumble/compare/master...gileri:master) and built it, and it kinda works.
Before initial mumble setup the main window freezes as JACK is selected by default and is being initialized (as visible in logs) but it I can completed with one more freeze. Not ideal but it helps.

I think you might be able to reproduce this issue on a system with functional JACK by doing something like `chmod 000 /dev/shm/jack-1000/default/jack_0`. In any case I can build/repro patches, and I don't think I will be able to propose patches; it's been years since I did any C++.

**Comment by davidebeatrici** [comment]
Thank you very much for testing the patch!

I created #3683, which should fix the freeze issue as well. Could you test it, please?

**Comment by svenstaro** [comment]
As a downstream maintainer, will you make a new release (rc2?) with this soon or are we advised to add some patches to rc1?

**Comment by davidebeatrici** [comment]
As we don't have an ETA for the next release yet, I recommend to add the patch to RC1.

https://github.com/mumble-voip/mumble/pull/3683.patch

Thank you very much for your work.

**Comment by svenstaro** [comment]
Ok, the current package in arch has that patch applied.

**Comment by davidebeatrici** [comment]
Excellent, thank you very much.

**Comment by Phistr90** [comment]
@svenstaro Problem still exists for me with current package in arch.

**Comment by svenstaro** [comment]
I had to roll back due to mumble not doing any idea work with that patch applied.

**Comment by Phistr90** [comment]
Any hotfix for arch users right now?

**Comment by davidebeatrici** [comment]
> I had to roll back due to mumble not doing any audio work with that patch applied.

Could you explain in detail the issue, please?

**Comment by svenstaro** [comment]
@davidebeatrici I applied the patch to rc1, rebuilt the package and audio didn't work at all. Mumble didn't register pulse sources and sinks anymore I think was the technical reason. I didn't really have time to investigate in-depth.

**Comment by Teteros** [comment]
@svenstaro I've rebuild the stable 1.3.0 PKGBUILD with JACK support enabled and ALSA/JACK work fine.

Maybe you could revert https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/mumble&id=577cafa8445cbbbbf592471d0d809cb189a0444b
for next `mumble-1.3.0-2` package in arch repos?

**Comment by svenstaro** [comment]
Ok.

**Comment by svenstaro** [comment]
Done, please test.

**Comment by Teteros** [comment]
@svenstaro Works, don't have to compile locally anymore. Thanks!
