### ISSUE TITLE
Ubuntu PPA is missing 'disco' version packages

### ISSUE THREAD

**Issue by netinetwalker** [mumble-voip/mumble#3689]
Please add builds for Ubuntu 19.04 disco

http://ppa.launchpad.net/mumble/snapshot/ubuntu/dists/disco
https://launchpad.net/~mumble/+archive/ubuntu/snapshot/

**Comment by Kissaki** [comment]
I am currently targeting working on this right after finishing the two blockers for the 1.3.0 release.

**Comment by Kissaki** [comment]
1.3.0 PPA packages are now available for all current Ubuntu versions.
