### ISSUE TITLE
symbol lookup error: undefined symbol: _ZN4grpc13ServerBuilderC1Ev [1.3.0rc1-1] ArchLinux

### ISSUE THREAD

**Issue by 9A9A** [mumble-voip/mumble#3693]
I've got crash on launch:

**journalctl -xe:**
`-- The job identifier is 9104.

May 22 17:47:04 vm-mumble-srv audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=murmur comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 22 17:47:04 vm-mumble-srv murmurd[949]: /usr/bin/murmurd: symbol lookup error: /usr/bin/murmurd: undefined symbol: _ZN4grpc13ServerBuilderC1Ev
May 22 17:47:04 vm-mumble-srv kernel: audit: type=1130 audit(1558547224.337:552): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=murmur comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 22 17:47:04 vm-mumble-srv systemd[1]: murmur.service: Main process exited, code=exited, status=127/n/a
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel`
`user@vm-mumble-srv sbin]$ sudo pacman -Qi murmur

Name            : murmur
Version         : 1.3.0rc1-1
Description     : The voice chat application server for Mumble
Architecture    : x86_64
URL             : http://mumble.sourceforge.net
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : qt5-base  avahi  lsb-release  protobuf  icu  zeroc-ice  grpc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 4.41 MiB
Packager        : Sven-Hendrik Haase <svenstaro@gmail.com>
Build Date      : Sun 28 Apr 2019 02:27:53 PM UTC
Install Date    : Wed 22 May 2019 05:12:15 PM UTC
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature`

**Comment by davidebeatrici** [comment]
Could you post the output of `ldd /usr/bin/murmurd`, please?

**Comment by 9A9A** [comment]
I've found out that the problem occured due upgrading grpc package to
1.21.0-1 version. i downgraded to 1.20.1-1 and it works just fine.

чт, 23 мая 2019 г., 0:18 Davide Beatrici <notifications@github.com>:

**Comment by AnonFuncsAreAwesome** [comment]
This looks like a missing rebuild after grpc update, evident by the build date listed above. Not a mumble bug and should be closed.
