### ISSUE TITLE
LFD2 Positional Audio

### ISSUE THREAD

**Issue by lyallz** [mumble-voip/mumble#3699]
There is not much out there in terms of instructions I tried loading the game and mumble in tandem but it nothing changed I could still hear people in the channel normally. So just isn't working at all, in addition I was on a public mumble server not sure if the server needs a plugin? Would love to know thanks.

Using windows 10  version 1803, OS build 17134.766
Mumble version 1.3.0-rc1

**Comment by davidebeatrici** [comment]
The plugin is outdated, see #3493.
