### ISSUE TITLE
Audio output disruption caused by speech-dispatch

### ISSUE THREAD

**Issue by nifker** [mumble-voip/mumble#3709]
Other applications(and mumble itself) sound delayed and crackling. Happens interestingly only on the ALC1220 but not when running any other VoIP software.

**Comment by nifker** [comment]
As far as I found out it seems to be an issue with the speech-dispatcher

**Comment by Krzmbrzl** [comment]
To which version of Mumble does this apply? If it happened with a version prior to 1.3, could you verify that the problem persists with v1.3?

**Comment by nifker** [comment]
IIRC correctly it happened on 1.3 but I can test it again.

**Comment by Krzmbrzl** [comment]
That'd be great :+1:

**Comment by Krzmbrzl** [comment]
Oh and btw: What's `ALC1220`?

**Comment by nifker** [comment]
Thats the sound chipset. But I cant seem to reproduce this for now.

**Comment by Krzmbrzl** [comment]
Alright - thanks for checking.
If the problem ever shows again, feel free to re-open this issue :)
