### ISSUE TITLE
Admin loses control over rooms created by other registered users

### ISSUE THREAD

**Issue by TalviT** [mumble-voip/mumble#3710]
I have allowed registered users to create permanent channels on my server. I have noticed that as an admin in these rooms I no longer have control over the users, nor am I able to edit or delete these channels.
I tested this on Windows and Linux, with client version 1.3.0-rc1, my (Debian) server runs on version 1.2.18-1+deb9u1.

**Comment by Kissaki** [comment]
What do you mean by "as an admin"?

What permissions do you have in what context?

The ACL allows configurable groups and permissions. There is no predefined, global admin group. (There is only SuperUser as a fallback full permission account.)
