### ISSUE TITLE
Communication between mumble and murmur breaks

### ISSUE THREAD

**Issue by ArkadiuszMichalRys** [mumble-voip/mumble#3712]
When a connected user performs multiple actions, the server stops responding to commands.

**Server version:** [Static Linux Server 1.3.0-rc1](https://dl.mumble.info/murmur-static_x86-1.3.0-rc1.tar.bz2)
**Client version:** [Windows x64](https://dl.mumble.info/mumble-1.3.0-rc1.winx64.msi) or [Ubuntu snapshop PPA](https://launchpad.net/~mumble/+archive/snapshot)

To reproduce this you need to connect to the server. Try switching channels rapidly. After switching 3 to 4 times in 2 seconds, the error occurs. The same happens when trying to mute, deafen or change ACL, group settings or perform any other _management_ action.
Here is a [short video with the steps to reproduce](https://youtu.be/5gqjb_NGCNo).

Note that audio still works, it's only the managing part that fails.
Reconnecting gives the user another 3 to 4 actions before the error is encountered again, this seems to be very consistent.

The issue is **not** there when using client version 1.3.0-rc1 with server version **1.2.19**.

**Comment by davidebeatrici** [comment]
#3662

Fixed in RC2: https://dl.mumble.info/murmur-static_x86-1.3.0-rc2.tar.bz2

**Comment by ArkadiuszMichalRys** [comment]
Thank you. I had only checked open issues, will remember for next time.

**Comment by davidebeatrici** [comment]
No worries, thank you very much for the detailed report!
