### ISSUE TITLE
Questions around the `continuous` tag and release generation.

### ISSUE THREAD

**Issue by sudoforge** [mumble-voip/mumble#3714]
I maintain a container image for Murmurd, and am using the "watch releases" functionality of GitHub. The creation of a release for the `continuous` tag is fairly noisy, and I'm hoping to get some insight into how it is currently being used -- at a high level, I imagine that this is a development build, and I'm wondering why we're tagging and creating a release for this instead of simply building on commit to `master`.

**Comment by davidebeatrici** [comment]
I agree that creating a release directly from `master` would be better, however it seems that GitHub requires a tag.

@probonopd

**Comment by sudoforge** [comment]
@davidebeatrici Sorry, maybe I wasn't being clear -- it _was_ at 04:37 for me 😴 

What is the `continuous` tag being used for? Why are we creating and re-creating releases with it?

**Comment by davidebeatrici** [comment]
For each commit on `master` we release an AppImage (#3703), we use the dedicated tag `continuous` because GitHub requires a tag to be attached to a release.

**Comment by sudoforge** [comment]
@davidebeatrici Okay, but _why_ is a release being created? I'm sure the resulting `AppImage` artifact is something like `:latest` in terms of Docker, right? Why do we need to create a GitHub release for this?

**Comment by sudoforge** [comment]
Never mind - I see why we're doing that: so the `AppImage` is downloadable via the GitHub Releases page.

How can I open a discussion around changing this behavior? The "development snapshot" shouldn't necessitate a GitHub Release, in my opinion -- this is noisy for people who are watching releases of this repository for `murmurd`/`mumble` updates.

**Comment by probonopd** [comment]
I don't know how to upload to GitHub Releases without making a release (at least if you want the git sha of the release to match the source code that was used to build the binaries). But it is marked as "Pre-release".

> this is noisy for people who are watching releases of this repository for murmurd/mumble updates.

They should watch only for real Releases, not Pre-releases.

**Comment by sudoforge** [comment]
> I don't know how to upload to GitHub Releases without making a release (at least if you want the git sha of the release to match the source code that was used to build the binaries). But it is marked as "Pre-release".

I'm asking _why we need to create a GitHub Release_. It seems silly to do this so that a development build artifact can be downloaded. Not many other projects do this -- at least, none that I follow.

> They should watch only for real Releases, not Pre-releases.

This is not possible to do within GitHub. A "Pre-Release" is a subset of a Release; you are only given to option to "Watch Releases".

<img width="372" alt="Screen Shot 2019-06-28 at 2 00 30 PM" src="https://user-images.githubusercontent.com/3893293/60371142-350dce80-99ad-11e9-9f5a-debdc650e287.png">

**Comment by probonopd** [comment]
> This is not possible to do within GitHub. A "Pre-Release" is a type of a Release; you are only given to option to "Watch Releases".

I'd say that's the real issue then ;-)

> I'm asking why we need to create a GitHub Release. 

So that we have some place where we can upload the binaries to. With the git hash matching between the source code and the binaries.

**Comment by sudoforge** [comment]
> I'd say that's the real issue then ;-)

Well, yes, GitHub's lack of granular customization leaves a lot to be desired.

> So that we have some place where we can upload the binaries to. With the git hash matching between the source code and the binaries.

Might I recommend an [open-source account on `Bintray`](https://bintray.com/signup/oss)?

**Comment by davidebeatrici** [comment]
Done: https://bintray.com/beta/#/mumble-voip/Mumble/Snapshot

**Comment by davidebeatrici** [comment]
@sudoforge Is the project on Bintray set up correctly?

If it is, we can start uploading the continuous releases there.

**Comment by sudoforge** [comment]
@davidebeatrici it appears to be, as far as I can tell.

**Comment by davidebeatrici** [comment]
Excellent.

@probonopd I propose to use Azure Pipelines instead of Travis CI, because our future build environment will be managed there.

**Comment by Kissaki** [comment]
@davidebeatrici Why are we using bintray instead of our existing snapshot infrastructure? We already have a system in place for snapshots so I don’t see why it should be different for AppImages?

**Comment by davidebeatrici** [comment]
Our current infrastructure treats snapshots as "fixed" (manually triggered) releases.

Ideally with the new infrastructure we should keep the snapshots as automated continuous releases.

**Comment by probonopd** [comment]
> @probonopd I propose to use Azure Pipelines instead of Travis CI, because our future build environment will be managed there.

Go ahead - just I can't help you there because I have no clue about it.

**Comment by sudoforge** [comment]
No other project (at least that I follow) creates GitHub releases for development builds. It's noisy. I don't know how else to effectively communicate this.

If the development artifact can be built from the source code, there's no reason to create a release. Just create a tag, push that up, and people who care can download the source code and alpha/beta users can build it themselves.

**Comment by davidebeatrici** [comment]
Right now the AppImage is only listed in AppImageHub (https://appimage.github.io/Mumble).

We could build an AppImage for each commit on `master` and then upload it to our download server (https://dl.mumble.info), perhaps with a symlink such as https://dl.mumble.info/latest/snapshot/appimage always pointing to the newest AppImage.

And, of course, remove the `continuous` tag on GitHub.

What do you think?

**Comment by sudoforge** [comment]
Again - what is the **goal** in **publishing** an artifact (be it an `AppImage`, `.exe`, `.dmg`, or other executable) on every commit? Who are the intended consumers of the `latest` artifact?

**Comment by davidebeatrici** [comment]
Mainly testers and people who are looking for the latest features (that's not the case right now because RC2 exists).

The alternative would be to entirely remove the continuous build and then use the snapshot channel instead, which allows us to choose when to trigger a release.

**Comment by sudoforge** [comment]
> The alternative would be to entirely remove the continuous build and then use the snapshot channel instead, which allows us to choose when to trigger a release.

Wouldn't a better alternative simply be to have these users build from source?

If there's a strong desire to compile artifacts for them, then I'd suggest compiling the artifacts for all supported platforms and publishing them to the download server, as you proposed in your earlier comment; a symlink would make it easy, I suppose, but might be solving the wrong problem -- if you version the software, and want to deliver an artifact for each commit, then your "version" simply becomes the commit sha. It wouldn't be uncommon or antipattern to include this in the artifact name, e.g. `mumble-acd83ef12.{extension}`

If there's a desire to make some sort of announcement, I'd suggest an IRC channel (or whatever platform, if any, is used for development), where your build bot would post links to the relevant artifacts, or some other such message notifying people that there is a new artifact to download.

This is typical of other projects that I have worked on, participate in the development of, or followed. You'll want to talk with the team about what their thoughts are.

**Comment by davidebeatrici** [comment]
> Wouldn't a better alternative simply be to have these users build from source?

Snapshots already exist, but we only distribute them via PPA on Linux (Ubuntu) right now.

> If there's a strong desire to compile artifacts for them, then I'd suggest compiling the artifacts for all supported platforms and publishing them to the download server, as you proposed in your earlier comment; a symlink would make it easy, I suppose, but might be solving the wrong problem -- if you version the software, and want to deliver an artifact for each commit, then your "version" simply becomes the commit sha. It wouldn't be uncommon or antipattern to include this in the artifact name, e.g. mumble-acd83ef12.{extension}

I'm not sure whether delivering an artifact for each commit makes sense.

As for the versioning, it's what we are doing right now for the snapshots. Basically, we only have to build the AppImage in addition to the other binaries.

> If there's a desire to make some sort of announcement, I'd suggest an IRC channel (or whatever platform, if any, is used for development), where your build bot would post links to the relevant artifacts, or some other such message notifying people that there is a new artifact to download.
>
> This is typical of other projects that I have worked on, participate in the development of, or followed. You'll want to talk with the team about what their thoughts are.

We could do that, yes.

**Comment by probonopd** [comment]
> I'm not sure whether delivering an artifact for each commit makes sense.

Absolutely, it's great for testing each and every commit. And every pull request, too.

**Comment by davidebeatrici** [comment]
What about uploading the releases on our own server instead?

**Comment by probonopd** [comment]
Sure, you can do as you wish, but in this case the zsync/AppImageUpdate magic won't work automagically, you'd have to supply the URL manually so that the update mechanism knows where to download the updates from.

**Comment by davidebeatrici** [comment]
What has to be done in order to make it work with a custom URL (that will not change)?

**Comment by probonopd** [comment]
Someone would have to implement a way in linuxdeployqt to pass a custom update information string to the lower-level `appimagetool -u ...`.

In the meantime, one could use  `appimagetool -u ...` manually but it is going to be additional work and chances are that bugs are introduced while trying to get everything right, so I'd say never touch a running system ;-)

**Comment by davidebeatrici** [comment]
On Azure Pipelines the `zsync` file is not generated because the update information is not present.

How should I generate it for an already existing AppImage?

**Comment by probonopd** [comment]
`sudo apt-get -y install zsync && zsyncmake *.AppImage` should do the trick.

**Comment by davidebeatrici** [comment]
```bash
for f in Mumble*.AppImage; do zsyncmake $f; done
```

The issue now is adding the update information to the AppImage.

**Comment by probonopd** [comment]
Easy: `echo "zsync|https://dl.mumble.info/Mumble-latest-x86_64.AppImage.zsync" | dd of=Mumble-*-x86_64.AppImage bs=1 seek=33651 count=512 conv=notrunc 2>/dev/null`

**Comment by davidebeatrici** [comment]
I thought that only worked when update information was already present in the image.

**Comment by probonopd** [comment]
No, it also works to add update information initially.

**Comment by davidebeatrici** [comment]
```
Could not find update information in the AppImage. Please contact the author of the AppImage and ask them to embed update information.
```

**Comment by davidebeatrici** [comment]
After analyzing another AppImage with a working update functionality, I found out that the correct offset is `0x2ae68` or `175720`.

Also, `\n` was being appended at the end of the string by `dd` (because it takes the output of `echo`), resulting in:
```
Updating from generic server via ZSync
zsync2: Reading and/or parsing .zsync file failed!
```

The `-n` parameter tells `echo` not to print `\n`.

This is the correct command:
`echo -n "zsync|https://dl.mumble.info/snapshot/latest-x86_64.AppImage.zsync" | dd of=Mumble-1e1848fb-x86_64.AppImage seek=175720 conv=notrunc oflag=seek_bytes`

**Comment by probonopd** [comment]
Sorry, you are correct, I copy-pasted the wrong information. Note that the offset can change from build to build of the embedded AppImage runtime, and can be got running `./some.AppImage --appimage-offset`.

**Comment by davidebeatrici** [comment]
No worries, thank you very much for your help.

Feel free to create a pull request to remove the hardcoded offset:
https://github.com/mumble-voip/mumble/blob/5ff56e446af80fdd975c0917664cef13115ee7e7/scripts/azure-pipelines/build_linux.bash#L26

**Comment by davidebeatrici** [comment]
@sudoforge @Kissaki

#3734 implemented the AppImage creation and upload logic on Azure Pipelines, #3735 removed it from Travis CI.

The `continuous` tag is gone, the latest AppImage can now be downloaded from https://dl.mumble.info/snapshot/latest-x86_64.AppImage

**Comment by sudoforge** [comment]
My sanity is very thankful :)

**Comment by sudoforge** [comment]
I suppose #3735 should have closed this issue -- I'll do that now.

**Comment by davidebeatrici** [comment]
There's only one issue: if you download the latest AppImage, the file's name is `latest-x86_64.AppImage` instead of the real one.

**Comment by probonopd** [comment]
See how the Open Build Service does it: They are using HTTP redirects. For example, if you download https://download.opensuse.org/repositories/home:/probono/AppImage/hexchat-latest-x86_64.AppImage it will give you one with the correct file name.
