### ISSUE TITLE
Microphone feedback in 1.3

### ISSUE THREAD

**Issue by LouisMT** [mumble-voip/mumble#3717]
Hello!

I'm hosting my own server. When I am in a room with someone else, I can hear myself talking through their stream. It sounds like microphone feedback: there's a little bit of distortion, sometimes it's a bit quiet but at other times it's really clear and there's a bit of delay too. However, the weird thing is that it's still happening when they unplug their microphone/speaker. I can see their icon light up as soon as I start talking, even if there is no microphone connected to their system.

We've tried enabling echo cancellation and changing other audio settings (in the OS and in Mumble), but nothing works. I've tested this with 2 other people. The issue is not present at all when using another voice chat application (we've tested using Riot/Matrix).

Server versions: 1.3.0-rc1, 1.3.0-rc2 (Linux)
My client versions: 1.3.0-rc1 (Linux), 1.3.0-rc1(Windows)
Other client versions: 1.2.19 (Linux), 1.3.0-rc1 (Linux), unknown (Windows)

**Comment by Kissaki** [comment]
Can they hear you fine? Does the distortion/volume change appear on their end as well?

When you local-mute them the issue disappears? (I guess so when you can clearly see them light up and transmitting the audio.)

You say you tested this with three people. This issue appears with all three of them? But they between them do not have this issue?

Do they hear you from one another as well, or only from you? Do they see each other light up when the issue occurs, or do they only see you light up?

**Comment by LouisMT** [comment]
> Can they hear you fine?

Yes.

> Does the distortion/volume change appear on their end as well?

No.

> When you local-mute them the issue disappears?

Yes.

----

I can't answer your other questions right now, I'll try to test again ASAP and answer those too! :)

**Comment by Kissaki** [comment]
I really don’t see how it could be possible others do not hear it on their end, but you hear yourself _from their end_.

Unless they have some output filtering either through audiodriver/system driver that filters some stuff out, or their hardware is not capable of outputting it. Which both seem unlikely.

You could try a server loopback to receive back the audio packets you send to the server, and see if it is an issue there. And also a local loopback to check if that makes a difference. Can be done enabled in Mumbles audio settings Loopback section. But from what you describe neither should produce the issue.

If it were local feedback from bad insulation between microphone and output cable it should be hearable locally, and not through others.

**Comment by Kissaki** [comment]
Have you tried the loopback tests I suggested?

I really don’t see what we could do here, or how it is an issue with Mumble. So unless you can provide more specific information I would close this ticket. @davidebeatrici WDYT?

**Comment by Kissaki** [comment]
Why would it work on other applications?
Maybe the codecs we use or input settings are more sensitive to noise?

**Comment by LouisMT** [comment]
> Have you tried the loopback tests I suggested?

I have, but I don't really understand what I should hear? I hear myself, but as this is a loopback test that's expected I guess. 

> So unless you can provide more specific information I would close this ticket.

Unfortunately I haven't had time to test more in depth, because I would have to test it with a number of different people. Feel free to close the issue, and I'll come back if it's still happening!

> Why would it work on other applications?

The other application I tested works in a web browser. My guess is that it's using WebRTC's noise cancelling. That's a guess though. The noise cancelling in Mumble doesn't seem to do anything for me.

**Comment by ymauray** [comment]
I do have that same problem : scratch sounds, localy, when I speak. The other parties hear me fine. 
What kind of test can I help you with ?
I'm on Ubuntu 18.04, using the snap version of Mumble 1.3.0
