### ISSUE TITLE
Hearing scratchy sounds and my own voice as if I was listening my microphone

### ISSUE THREAD

**Issue by DarckCrystale** [mumble-voip/mumble#3721]
Under Windows 10, everything is fine.

Under Ubuntu 16.04, when I connect to Mumble and enter a channel with another people in it, I start hearing a lot of scratchy noises, my own voice and the voice of the connected people at the same time. The noises almost covers their voice and my own one.

I use a jack microphone and a pair of jack speakers.

This problem make me unable to use Mumble when I boot under Ubuntu.

**Comment by DarckCrystale** [comment]
If you need more information about my configuration, don't hesitate to ask.

**Comment by davidebeatrici** [comment]
Probably the same issue as #3717.

Do you happen to know the Mumble version used by other people on the server?

**Comment by DarckCrystale** [comment]
I'll try to think about asking to my friend, please poke me if I forgot!

**Comment by Krzmbrzl** [comment]
@DarckCrystale did you get the respective information?
