### ISSUE TITLE
Feature Request - Loading Welcome Message from External Server

### ISSUE THREAD

**Issue by Jeselnik** [mumble-voip/mumble#3723]
A feature I think could be useful would be the ability to load a welcome message from an external web server akin to the RC messages at http://mumble.info/focus.php

For those with lengthy welcome messages it would simplify their config file as well as allow for easier editing of it.

I imagine #3168 may limit this somewhat and if so making the welcome message modular, possibly having it load an html file on disk would also work for the listed use cases.

**Comment by Popkornium18** [comment]
Wouldn't it be enough to load the message from an external file? Is it really that much of a benefit to load it from a website? I got loading from file working already.
If it's only about less clutter in the config file than this pretty much fixes this issue.

**Comment by Jeselnik** [comment]
Since the end result is the same I don't care where it gets loaded from. Feel free to close this issue when it gets committed.

**Comment by Krzmbrzl** [comment]
@Popkornium18 how did you make it work? With some additions to the code?

**Comment by Popkornium18** [comment]
Some minor additions to the code were necessary. I'll create a PR soon. I have to get ICE working first to test the RPC changes. But I'm having a bit of trouble with that.
