### ISSUE TITLE
mute function stuck ..

### ISSUE THREAD

**Issue by tomworxs** [mumble-voip/mumble#3725]
I have an issue when muting/unmuting myself that it gets stuck on mute.
To reproduce mute/unmute yourself fast (faster than 1s per action). After that its no longer possible to unmute.

I have version 1.2.19-1 and i'm using pulseaudio.

**Comment by K1773R** [comment]
same here for me, using 1.2.19 as well.

**Comment by davidebeatrici** [comment]
Actions should start working again if you wait for a few seconds (it depends on the server settings).

For more information: #3662

**Comment by davidebeatrici** [comment]
Closing in favor of #3724.
