### ISSUE TITLE
Error when compiling: error: ‘CELT_SET_VBR_RATE’ was not declared in this scope; did you mean ‘CELT_SET_BITRATE’?

### ISSUE THREAD

**Issue by HeyBanditoz** [mumble-voip/mumble#3727]
```
AudioInput.cpp: In member function ‘int AudioInput::encodeCELTFrame(short int*, AudioInput::EncodingOutputBuffer&)’:
AudioInput.cpp:780:38: error: ‘CELT_SET_VBR_RATE’ was not declared in this scope; did you mean ‘CELT_SET_BITRATE’?
  780 |  cCodec->celt_encoder_ctl(ceEncoder, CELT_SET_VBR_RATE(iAudioQuality));
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      CELT_SET_BITRATE
```
Doing the suggested change seems to fix the issue. Running Archlinux.

**Comment by CuriouslyCurious** [comment]
Same problem here. The suggested fix also works.

**Comment by Krzmbrzl** [comment]
@davidebeatrici don't we use CELT in the CI? If not, it should be added to avoid this kind of issues in the future :)

**Comment by quite** [comment]
I'm also on Arch Linux, which has celt-0.11.3 (released 2011-03-15!). `CELT_SET_VBR_RATE` is present in celt-0.10.0 (2010-12-21). Maybe that's what the CI system has...

**Comment by Krzmbrzl** [comment]
Now that I think of it: I think the max Celt version we are currently supporting is 0.7 or something like that...
Thus you'll probably have to use the one that omes as a Submodule and not one that is installed on your system.

**Comment by Krzmbrzl** [comment]
Besides CELT is mostly being dropped completely for 1.4: https://github.com/mumble-voip/mumble/issues/3484

I just checked though and it appears that
https://github.com/mumble-voip/mumble/blob/7ed7d95f4bee4a8aac437862cf6d4455de6ca24a/src/mumble/AudioInput.cpp#L789
is not contained in any kind of #ifdef-block that would prevent it from being included in the build normally. Thus it might still be worth fixing if only for people not running in this problem.
I'll check if we can fix that easily without breaking anything.

**Comment by Krzmbrzl** [comment]
After having read https://github.com/mumble-voip/mumble/pull/2045, I think we shouldn't fix the Celt-build as Celt 0.11 won't be working anyways (for Mumble).

Thus you'd just have to use the bundled celt version (Use config option `bundled-celt` to force using the version packaged with Mumble).

If you have good reasons why you think fixing this in our code base nonetheless, please let me know :)

**Comment by quite** [comment]
I couldn't get `bundled-celt` to work. Only uninstalling system celt 0.11 worked. Anyhow, great it is going away... I'll make a note about these things for [Mumla](https://gitlab.com/quite/mumla) as well

**Comment by Krzmbrzl** [comment]
> I couldn't get bundled-celt to work

Did it keep using the system's Celt or were there other errors?

**Comment by quite** [comment]
@Krzmbrzl  yes, it used the system Celt, and got the above error

**Comment by Reikion** [comment]
@quite Try to build again with bundled-cert option. 2 days ago mumble-1.3.1-rc1 was improperly released and it hadn't half of source code of 3rdparty libs.
I've modified [PKGBUILD](https://paste.reik.pl/WpBj/) from ABS and it looks like it works properly.
