### ISSUE TITLE
Mumble.info domain expired on 8/14/2019 (also causing big CPU usage in windows client)

### ISSUE THREAD

**Issue by JuniorJPDJ** [mumble-voip/mumble#3749]
oops

**Comment by Bertsz** [comment]
On windows having automatic updates enabled (both overlays and mumble itself) in the network settings seems to be causing very high CPU usage because of this.
Just a heads up

**Comment by JuniorJPDJ** [comment]
There's very high cpu usage also when disabling autoupdate on my friends PC. Mine is ok O.o

**Comment by Bertsz** [comment]
I checked the threads in process explorer and the ucrtbase.dll was causing the high usage. Killing the thread there was fine, but ultimately disabling all the updates/stats reporting and restarting mumble did the trick.
If that doesn't help maybe editing the hosts file will

**Comment by JuniorJPDJ** [comment]
I just try to prepare hosts file.
Do you know any past IP which domain was pointing to?

**Comment by JensMagnus** [comment]
This is happening for me too, and also one my friends. Just a random fact; we both have the ASIO option in Mumble, but our other two friends don't (and they don't have the problem).

**Comment by JuniorJPDJ** [comment]
@JensMagnus I've exactly the same situation, my friend have ASIO enabled too.

**Comment by JensMagnus** [comment]
We found the issue. It's caused because Mumble tries to lookup mumble.info

A quick fix would be to do the following in your hostfile.

`151.101.14.217 mumble.info`

**Comment by thorvald** [comment]
Aaargh. The registrar rejected the saved payment, and since the same registrar sends out advertisements all the time, the payment rejection warnings got tagged as spam by gmail.
Renewed for another 5 years, so this should resolve as soon as current caches expire. I'll get the domains transferred over to a team account so this doesn't happen again.

**Comment by Kissaki** [comment]
Thank god it’s not gotten worse than this

**Comment by Mikaela** [comment]
Have you thought about changing registrars? I am uncomfortable with [some of GoDaddy's controversies](https://en.wikipedia.org/wiki/GoDaddy#Controversies) and have moved my personal domain to [Gandi](https://gandi.net/) . They have some sort of a [organizations/teams support](https://docs.gandi.net/en/sharing_products/index.html) that I am not familiar with though.

**Comment by Kissaki** [comment]
The temporary domain issue has been resolved. I have created #3760 for improving the clients behaviour on update check failures.

**Comment by davidebeatrici** [comment]
@Mikaela The domain has been transferred to Amazon AWS (https://aws.amazon.com/route53).
