### ISSUE TITLE
[Q]: Speex in Mumble

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3752]
I was wondering on what the status of Speex inside Mumble is.

Someone on the IRC told me that Speex support has been dropped a while back and #3508 suggests the same thing. However in #3484 I see the unchecked checkbox for the "Drop Speex" task which suggests that Speex support is still in Mumble but is planned to be removed.

Furthermore I found e.g. https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioInput.cpp#L837 that indicates that speex is being used for some sort of (pre-) processing. Additionally I also think that in order to process any kind of Audio packet connected to speech (which should be the majority) is ultimately being converted into a Speex object (`JitterBufferPacket`) and sent into a speex function (`jitter_buffer_put`) - taken from https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutputSpeech.cpp#L159

Therefore I wanted to ask if someone could clarify this for me.

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/0008303a1ee4b4f645ac7ad8ffa1af4be6cd3323/src/mumble/AudioInput.cpp#L837

https://github.com/mumble-voip/mumble/blob/0008303a1ee4b4f645ac7ad8ffa1af4be6cd3323/src/mumble/AudioOutputSpeech.cpp#L159

These are part of SpeexDSP, which is a DSP library: https://github.com/xiph/speexdsp

The DSP functions were split from Speex when it was superseded by Opus, which doesn't have any DSP features.

**Comment by Krzmbrzl** [comment]
Ah so it's basically a set of utility functions used for digital signal processing (that's what DSP stands for, right)?

**Comment by davidebeatrici** [comment]
Correct. We use it for echo cancellation and noise reduction, for example.

**Comment by Krzmbrzl** [comment]
Alright thank you :)

**Comment by davidebeatrici** [comment]
You're welcome! :)

**Comment by davidebeatrici** [comment]
#3812
