### ISSUE TITLE
@all Permissions in root channel apply unexpectedly in sub-channel

### ISSUE THREAD

**Issue by casKd-dev** [mumble-voip/mumble#3754]
Denying permissions to speak in the root channel and applying it only to the root channel unexpectedly applies it to the sub-channels too.

Root channel:
![Screenshot_20190823_172804](https://user-images.githubusercontent.com/30688640/63604177-6d0b4980-c5cb-11e9-9bdd-d05a90cb781c.png)

Sub-channel:
![Screenshot_20190823_172947](https://user-images.githubusercontent.com/30688640/63604278-a04dd880-c5cb-11e9-9e74-55a849fa66ff.png)

User being automatically suppressed in both root channel:
![Screenshot_20190823_173107](https://user-images.githubusercontent.com/30688640/63604629-94164b00-c5cc-11e9-87b6-6d8b0890adc2.png)

The channels are set to inherit ACLs but in this case they should not be. Applying the given ACL to sub-channels is unchecked.

Mumble & Murmur version: 1.3.0_rc2-r0
Distribution: Alpine Linux 3.10.2
Database backend: PostgreSQL

**Comment by Johni0702** [comment]
If I'm not mistaken, this is the same as #3579.

**Comment by casKd-dev** [comment]
> If I'm not mistaken, this is the same as #3579.

Yep, my bad, closing.
