### ISSUE TITLE
Change Coding Guidelines for commenting

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3766]
In the Coding guidelines that can be found on https://wiki.mumble.info/wiki/Coding_Guidelines#Comments it states

> Try to use comments in a sensible way. Don't comment the obvious (e.g. no setBla() "Sets bla") and don't feel obligated to comment every single parameter and function if the variable naming and types already make the behavior obvious. 

Given that there are big parts of Mumble that aren't documented whatsoever, I think this is a really bad thing to tell new developers.

I'd suggest stating that _everything_ should be documented. That means that each and every function should get a function header stating what that function does. Even if the functions is ? setBla` and the header for it is `This sets bla`. Remember that this is the only way for the function to be documented by e.g. Doxygen.
This also means that the code itself should contain comments about what is going on at this particular point so that someone else looking at the code can see right away what the intention of that code section is.

I firmly believe that the legendary laziness of programmers will prevent a massive amount of unneeded comments in the source code - we don't explicitly need to tell them that they shouldn't comment everything.

And even if we get a bunch of unneeded comments, I'd say that this would still be better than having too few comments. After all I can skip comments I'm not interested in, but I can't magically create some that aren't there.

**Comment by Kissaki** [comment]
Every secondary documentation, like comments are, can get outdated or misplaced over time. Adding too much secondary documentation, especially when it does not provide value, should hence be avoided.

Telling developers to not comment the obvious comes from this, and because even if you can skip past reading the comments, it does bloat code files and hence worsens readability.

Our lack of architecture and logic flow documentation can not be made up by comments duplicating the obvious on the function and function body level.

Hence I strongly disagree with your argumentation and conclusion.

**Comment by Kissaki** [comment]
As an example
```
/// Adds value1 to value2 and returns the result.
///
/// @param value1 Value 1
/// @return value2
int Add(int value1, value2);
```

This is just unnecessary bloat. And while it does not give us anything useful, it decreases concise readability and leads to problems down the line as it is split redundancy.

**Comment by Krzmbrzl** [comment]
> Every secondary documentation, like comments are, can get outdated or misplaced over time.

Although that is true, I think in like 99% of all cases what changes are more or less subtle details. E.g. normally a function that was created to do A, won't be changed into a function doing B. Thus when the documentation states that this function does A, it is still describing the bigger picture even after some details of how A is being performed change.
Those details might be part of the documentation as well and if they don't get updated, the documentation is misleading in regards to those details.
However I still feel that even an outdated documentation like this is better, than no documentation as it still correctly describes the bigger picture which is quite often all that you need. 

> Telling developers to not comment the obvious comes from this, and because even if you can skip past reading the comments, it does bloat code files and hence worsens readability.

This is also correct. Nonetheless I think you have to view this from another angle as well: If I am specifically told to not comment the obvious, then I'll tend to use comments more rarely than I'd usually would, because I wouldn't want someone to think I don't know what I'm doing because what I did was obvious to them. And by commenting this code I am basically stating that it is not obvious to me (This is an exaggerated scenario, but I think you'll get what I am trying to say with that).
Additionally the definition of what is obvious and what is not, does strongly depend on your personal skill, experience and how well you know the code base. Thus you might consider a part of the code rather obvious because you know all the abbreviations that are used in the variable names, you know how the code is embedded in the bigger picture and maybe you even know exactly what the author of the code intends to do with each line because you are that author. If on the other hand someone is new to Mumble, doesn't know the abbreviations, the bigger picture of how that code plays with the rest of the framework, he/she will most likely not declare that code as "obvious" and thus would be grateful if there was some secondary documentation that contains information all of that.

> Our lack of architecture and logic flow documentation can not be made up by comments duplicating the obvious on the function and function body level.

Yet again I agree. However I think that 
a) these super obvious cases don't occur this often (as to me it appears that inside Mumble global variables are preferred over getter/setter methods) and 
b) when creating documentation via e.g. Doxygen it is a lot more convenient if simply _all_ functions appear in that documentation instead of only the ones that seemed complex enough for being worth a documentation.


And I'd like to stress that I think that even if instructed to comment/document everything the developers won't clutter the code with nonsense comments. On the other hand I do also believe that explicitly telling the devs to not comment/document (in certain situations) will keep them from adding those comments every once and a while when it would have been important/useful.
Or did you have the problem of a lot of nonsense documentation creeping into the code before establishing these guidelines?

**Comment by Kissaki** [comment]
> Or did you have the problem of a lot of nonsense documentation creeping into the code before establishing these guidelines?

As you have noticed we lack a lot of documentation and commenting. So no, that obviously never was a problem AFAIK.

> the developers won't clutter the code with nonsense comments

The point of (these) guidelines are that they are enforce-able. That code changes that are applied to the code base meet these requirements.

**Comment by Krzmbrzl** [comment]
> The  point of (these) guidelines are that they are enforce-able. That code  changes that are applied to the code base meet these requirements.

I don't quite see why a guideline stating that one should comment and document ones code shouldn't be enforce-able. It's a bit subjective as to what needs commenting and what doesn't but I'd say that's the same with the current guidelines :thinking:

**Comment by Kissaki** [comment]
Given that no additional comments have been made from other people, I am closing this.

I am strongly against commenting everything as that only adds redundancy. At least in such a generic requirement being formulated. If it is meant weaker then it is not much different from the current guidelines anyway - which basically says comment where it makes sense. There is no formulation that will fit all cases, so that’s the best one to use.
