### ISSUE TITLE
User can send text message to self

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3778]
As of right now I am able to send text messages to myself either via the context menu or by double clicking on my user in the UI.
From what appears in the UI the message seems to be sent (it says `To <MyUsername>: <Message>`) but isn't received (no further message appearing after that).

I believe that it is not intentional that one can send messages to oneself?

**Comment by Kissaki** [comment]
I would consider it a valid use case.

You can send yourself notes, or check out message formatting.

And although I am not sure if this is local or over the server, checking message send permission and making sure messages can be sent through the server may also be a use case for this. Of course if they’re delivered locally only and without permission restriction then that won’t work.

**Comment by Krzmbrzl** [comment]
Alright - that's not the kind of functionality I would have expected in a program like this, which is why I thought this might be a bug. But if you say that this is intended (or at least useful), then I'll close this issue :)

**Comment by Kissaki** [comment]
Thank you for raising the issue/discussion though. :)

**Comment by Krzmbrzl** [comment]
Sure :)
