### ISSUE TITLE
No sound by default when users enter the server after upgrading to 1.3

### ISSUE THREAD

**Issue by RodrigoTjader** [mumble-voip/mumble#3787]
Mumble 1.2 played sounds by default when an user joined or left the room.

In Mumble 1.3 the "joined the room" configuration was split into "User joined the room" and "User connected and joined the room", and similarly for leaving the room.

However, after I upgraded from Mumble 1.2 to Mumble 1.3 the setting for "User connected and joined the room" was set to Text-to-speech and I have TTS disabled, so Mumble made no sound when someone connected straight into the room I was in. It still played the usual soundfile when someone moved from another room into the room I was in.

**Comment by Krzmbrzl** [comment]
Did you have the `User joined the room` setting set to TTS as well?

**Comment by RodrigoTjader** [comment]
On Wed, Jan 15, 2020 at 5:46 AM Raven <notifications@github.com> wrote:
> Did you have the User joined the room setting set to TTS as well?

No, only the "User connected and joined the room" was set to TTS. If
someone joined the server in a different room and then moved into my
room I would hear the usual sound; but if someone joined the server
straight into my room I would hear nothing.

**Comment by Krzmbrzl** [comment]
Isn't this the expected behavior then?

**Comment by RodrigoTjader** [comment]
What is unexpected is that in the previous version I heard the bell
sound every time someone joined my room, regardless if they were
moving from another room or connecting.

When it was updated to 1.3 the setting was split in two, but the two
new settings had different values. In my opinion both new settings
("User joined the room" and "User connected and joined the room")
should retain the value of the old setting ("joined the room").

**Comment by Krzmbrzl** [comment]
Ah okay now I think I understand. So you'd expect the default value for both settings to be the same (and on top of that you suggest that both should be enabled per default), correct?

**Comment by RodrigoTjader** [comment]
On Wed, Jan 15, 2020 at 8:32 AM Raven <notifications@github.com> wrote:
> Ah okay now I think I understand. So you'd expect the default value for both settings to be the same (and on top of that you suggest that both should be enabled per default), correct?

I do expect both of those things, but I think even more important is
that when upgrading from 1.2 they should both keep the value that was
set there.

**Comment by Krzmbrzl** [comment]
> even more important is that when upgrading from 1.2 they should both keep the value that was
set there.

In principle, I agree with you. However I'm afraid that it's too late now as 1.3 has been released a while back now already. Thus I don't think that backporting those defaults would make much sense.
That of course is our fault for not processing this issue earlier. Sorry for that

**Comment by RodrigoTjader** [comment]
Indeed, but this is something to keep in mind for future releases. Silently
changing how a user has explicitly configured the program to behave is
rarely a good idea.
