### ISSUE TITLE
Mumble hangs for 0.5-1 min every launch

### ISSUE THREAD

**Issue by eeke1** [mumble-voip/mumble#3789]
I can see the usual server list etc. but the app is unresponsive for the first 30 sec+ or so. 

I've reinstalled Mumble 1.3.0 after deleting associated registry keys as well as any settings in appdata/roaming.

Using a Win10 Pro, 8362.295. Occurs using both x86/x64 version of mumble.

**Comment by davidebeatrici** [comment]
Could you paste the console log, please?

**Comment by eeke1** [comment]
WinDbg gives me a "requested operation requires elevation" error regardless of Admin or not. 

DbgView at least gives me something:

[dbgview_mumble.log](https://github.com/mumble-voip/mumble/files/3598464/dbgview_mumble.log)

Looks like adding devices takes an eternity. Full minute to be able to connect.

**Comment by davidebeatrici** [comment]
Indeed, that's the issue.

**Comment by eeke1** [comment]
A little more testing shows this becomes an issue when the computer is on for long periods of time, but not after a reset.

This is after all unecessary apps etc are closed.

**Comment by ZeroAbility** [comment]
Does this still occur with 1.4?
