### ISSUE TITLE
Mumble.exe should include snapshot version qualification

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#3798]
The exe has 1.3.0.0 as file version. This has to be four intergers.

However, the Product Version is free text and only contains 1.3.0 for rc2 when it should be 1.3.0-rc2 like we use in our window title. For non-rc snapshots it should be the extended version qualifier.

We set `MUMBLE_VERSION` on build.

1. Check how Qt sets the exe file metadata and how we can influence that

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/a38d19a7595c3e672f5ed549400b36348e01e442/src/mumble/mumble.rc#L1-L51

**Comment by Kissaki** [comment]
Yeah I saw it while working on #3761

**Comment by Hartmnt** [comment]
This was probably fixed when we switched to the new version scheme. Current released ``.exe`` files contain the correct version string (1.5.634.0)
