### ISSUE TITLE
How to murmur upgrade without changing configuration?

### ISSUE THREAD

**Issue by PPPPPPPPz** [mumble-voip/mumble#3802]
How to upgrade the murmur version to 1.3.0 without changing the configuration

- Platform CentOS 6
- No external database
- Version 1.2.19

There was any documents about murmur upgrade guide? Thanks.

**Comment by davidebeatrici** [comment]
Are you using the static Murmur server? You only have to copy the SQLite database and the configuration file.

**Comment by PPPPPPPPz** [comment]
@davidebeatrici thanks for labels add.

**Comment by davidebeatrici** [comment]
You're welcome.

**Comment by PPPPPPPPz** [comment]
Hi @davidebeatrici , Do you mean: just copy files 'murmur.ini' and 'murmur.sqlite' to the new murmur folder (murmur-static_x86-1.3.0), then murmur datas will be saved?

**Comment by davidebeatrici** [comment]
Correct.

**Comment by PPPPPPPPz** [comment]
COOOL~ It's worked. Thank you very much @davidebeatrici

**Comment by davidebeatrici** [comment]
You're welcome, enjoy the new version!

**Comment by Klagio** [comment]
Hi, can I have some instructions on how to achieve the same ugrade? Thank yoU!

**Comment by Krzmbrzl** [comment]
The instructions are still the same. In fact I'm not sure you have to do anything at all...
