### ISSUE TITLE
Mumble servers crash for a SQL error : Duplicate entry

### ISSUE THREAD

**Issue by Puma24000** [mumble-voip/mumble#3803]
Hello,

In reference to the topic created on the Mumble's forum : https://forums.mumble.info/viewtopic.php?f=4&t=4285

I'm hosting several hundred of Mumble servers with SQL database.

Sometimes, i get this error message from mumble logs and all mumble servers (600 servers) are crashed, i must restart the Mumble server service.

I suppose that one user is editing his server and enter an incorrect parameter...

> SQL Error [INSERT INTO `murmur_groups` (`server_id`, `channel_id`, `name`, `inherit`, `inheritable`) VALUES (?,?,?,?,?)]: Duplicate entry '3566-1-admin' for key 'murmur_groups_name_channels' QMYSQL3: Unable to execute statement

**Comment by davidebeatrici** [comment]
`Server::updateChannel()`:
https://github.com/mumble-voip/mumble/blob/21c1792317aabdc619ed46929243d4e02af7f8bd/src/murmur/ServerDB.cpp#L1710-L1716

**Comment by Puma24000** [comment]
Hi, any update ?
I had 2 crashes these 2 last weeks for the same errors :(
I told that because you seem on a good way.

Thanks for your help.

**Comment by Krzmbrzl** [comment]
Fixed in #4246
