### ISSUE TITLE
Modern Mumble Project Chat Platform

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3814]
I was wondering if you ever considered to create a Mumble Discord server that complements/replaces the current IRC channel.

The pros of Discord (in my opinion are):
1. Persistent messages from everyone. I can still see messages that have been sent when I wasn't online allowing me to answer questions asked when I was offline or my questions being answered  in that tims
2. Better support for mobile usage
3. More modern
4. Better support for formatting messages 

The cons:
1. Probably more spammers
2. Extra administration 
2. Would support a competitor

**Comment by Mikaela** [comment]
:-1: the Discord terms of service seem unacceptable to me and if the current IRC channel was replaced, it would be forced upon also to users for whom a big reason to use Mumble and selfhost is not having to accept the terms. Here are some snips from them:

>  The Company reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. The Company reserves the right to refuse any user access to the Services without notice for any reason, including but not limited to a violation of the Terms. If you violate these Terms, the Company reserves the right to issue you a warning regarding the violation or immediately terminate or suspend any or all Accounts you have created using the Service. You agree that the Company need not provide you notice before terminating or suspending your Account(s), but it may do so.

> We reserve the right to reject any username or to terminate your username or prevent use of a username in our sole discretion, and without any liability to you

> By uploading, distributing, transmitting or otherwise using Your Content with the Service, you grant to us a perpetual, nonexclusive, transferable, royalty-free, sublicensable, and worldwide license to use, host, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display Your Content in connection with operating and providing the Service. 

> The Company may terminate your Account and your access to the Service (or, at the Company's sole option, applicable portions of the Service) at any time and for any reason.

and a lot only affecting citizens of the US

* * * * *

> Data We Collect Automatically: When you interact with us through the Services, we receive and store certain information such as an IP address, device ID, and your activities within the Services. We may store such information or such information may be included in databases owned and maintained by affiliates, agents or service providers. The Services may use such information and pool it with other information to track, for example, the total number of visitors to our Site, the number of messages users have sent, as well as the sites which refer visitors to Discord.

> Aggregated Information: In an ongoing effort to better understand and serve the users of the Services, we may conduct research on our customer demographics, interests and behavior based on the information collected. This research may be compiled and analyzed on an aggregate basis, and we may share this aggregate data with our affiliates, agents and business partners. We may also disclose aggregated user statistics in order to describe our services to current and prospective business partners, and to other third parties for other lawful purposes.

> Info through other Services: You may give us permission to collect your information in other services. For example, you may connect a social networking service ("SNS") such as Facebook or Twitter to your Discord account. When you do this, it allows us to obtain information from those accounts (for example, your friends or contacts).

> We may use third party web site analytic tools such as Google Analytics on our website that employ cookies to collect certain information concerning your use of our Services. However, you can disable cookies by changing your browser settings. Further information about the procedure to follow in order to disable cookies can be found on your Internet browser provider's website via your help screen.

> Advertisements: You may see our Service advertised in other applications or websites. After clicking on one of these advertisements and installing our Service, you will become a user of the Service. Advertising platforms, which include Twitter and Facebook (and whose SDKs are integrated within our Service), may collect information for optimizing advertising campaigns outside of the Service.

> Our Services currently do not respond to “Do Not Track” (DNT) signals and operate as described in this Privacy Policy whether or not a DNT signal is received, as there is no consistent industry standard for compliance.

>  The Company is based in the United States. No matter where you are located, you consent to the processing and transferring of your information in and to the U.S. and other countries. The laws of the U.S. and other countries governing data collection and use may not be as comprehensive or protective as the laws of the country where you live.

> Business Transfers: As we develop our business, we might sell or buy businesses or assets. In the event of a corporate sale, merger, reorganization, bankruptcy, dissolution or similar event, your information may be part of the transferred assets.

> Related Companies: We may also share your information with our Related Companies for purposes consistent with this Privacy Policy.

>  We generally retain personal data for so long as it may be relevant to the purposes identified herein. To dispose of personal data, we may anonymize it, delete it or take other appropriate steps. Data may persist in copies made for backup and business continuity purposes for additional time.

**Comment by Mikaela** [comment]
Alternative suggestions:

* https://rocket.chat/
* https://matrix.org/ which while having privacy issues (https://github.com/privacytoolsIO/privacytools.io/issues/1049) is at least Open Source Software and self-hostable (and can be used without a phone number or email address)
* https://telegram.org/ which while having a closed source server and questionable security, has at least open source client packaged for multiple Linux distributions and unofficial FOSS Android client and otherwise good platform support
* https://keybase.io/ which again has closed source server

I imagine https://github.com/42wim/matterbridge or similar is necessary for supplementing.

**Comment by Krzmbrzl** [comment]
Good point.

Telegram requires to reveal ones phone-number though which is more than I'd be willing to share about myself with basically everyone

**Comment by Mikaela** [comment]
Your phone number would only be revealed to Telegram and be invisible towards people whom you didn't share it to or who didn't have it already.

* * * *

I edited my previous comment to add:

> EDIT: I forgot `#freenode_#matrix:matrix.org` is already a thing.

as I remembered that all of freenode is already bridged there.

**Comment by Kissaki** [comment]
It has not been discussed internally specifically. I do see value in using and promoting a friendlier platform than just IRC though. Some people already use Matrix with its IRC bridge, which gives them a modern and persistent chat while it still connected with out IRC channel and its messages.

I am currently trying to find a news article about a big FOSS project or organization working towards a new chat platform and deciding against Discord, with a few options left. The article was a few days ago, and I thought I had it left open or saved it for later review/reference. But I can not find it right now. Anyone familiar? Could have been GNOME, Mozilla, GNU or something…

With what @Mikaela wrote/referenced, and the weight of what I referenced I don’t see us going the Discord route. As I said the Matrix route is already an option, and we should see what the other big projects reasons, and promote something similar as well - either bridged with IRC, which would be neat, or another adequate platform.

**Comment by Mikaela** [comment]
http://exple.tive.org/blarg/2019/09/06/forward-motion/ ?

> … and a few words on some options we didn’t pick and why:
> ...
> Discord’s terms of service, particularly with respect to the rights they assert over participants’ data, are expansive and very grabby, effectively giving them unlimited rights to do anything they want with anything we put into their service. Coupling that with their active hostility towards interoperability and alternative clients has disqualified them as a community platform.
> ...

**Comment by Kissaki** [comment]
Yes, that’s it, thank you very much! I guess I discarded it waiting for later decisions and preferably announcements from Mozilla directly and not just a persons blog.

**Comment by Kissaki** [comment]
> On December 1st, assuming we can gather that support, we will stand up the new service.

so that will be a while until they announce and release

**Comment by Kissaki** [comment]
The post lists these candidates with my or their additional info added

* Rocket.Chat has a limited free tier
* Matrix/Riot.im is free, can bridge IRC
* Zulip has free tier, two-way bridge with IRC and Matrix possible
* Gitter free, has IRC bridge
* Spectrum ? free, has communities and sub-channels, profile posts
* Slack commercial
* Mattermost costs unless self hosted
* Discord discarded for their terms
* Telegram discarded; good for conversations, impractical for work
* IRCv3; not sufficiently evolved as a protocol and client adoption

**Comment by Mikaela** [comment]
> Mattermost costs unless self hosted

and when selfhosted, anyone can add/remove channels, because preventing that is a feature of their enterprise edition. https://github.com/mattermost/mattermost-server/issues/6320

**Comment by Mikaela** [comment]
I remembered that there is also https://xmpp.org/ which can be used to connect to e.g. `#mumble%irc.freenode.net@irc.disroot.org` (Biboumi) and which Disroot has chosen over Matrix. https://howto.disroot.org/en/tutorials/chat

A modern webchat would be ConverseJS https://conversejs.org/fullscreen.html and on Android there is https://conversations.im/ , on iOS I have been hearing about https://siskin.im/ (but I don't have iOS devices), Linux https://dino.im/ . I find it more mobile friendly than Riot.im, even if RiotX has improved it a bit and I think the clients I mentioned could be called as modern.

However I think the complaint for Telegram applies as it's what everyone (including most of Matrix clients other than their communities which everyone says are going to be rewritten) appears to be attempting to copy.

So far my best experience with actual teamchat has been a separate IRC client for a IRC network that is only for a single purpouse.

**Comment by Krzmbrzl** [comment]
I basically don't really mind which of the solutions we settle on as long as it is more modern that IRC and supports offline messages (and it doesn't involve sharing a lot of private data with everyone)

**Comment by tatokis** [comment]
I'll chime in by saying that whatever new option is welcome as long as it is open source/self hosted and has a bridge to IRC. If the IRC channel is gone, I'm most likely going with it, for whatever that's worth.

That said, I do think that the freenode matrix bridge is sufficient for anyone wanting a "modern" experience.

**Comment by davidebeatrici** [comment]
Unfortunately our bridged room on Matrix is in a Schrödinger state: it exists and messages from IRC appear, but it is marked as "replaced and no longer active" and messages cannot be sent.

This happened after I attempted to disable the end-to-end encryption after asking for support in `#irc:matrix.org`, because messages from Matrix weren't appearing on IRC.

I contacted support@matrix.org on February 16th and they replied in less than an hour saying that they would look into it. I asked whether there was any progress on the issue on April 1th, June 20th and September 14th. Unfortunately I never received a reply.

**Comment by Krzmbrzl** [comment]
There are some more recommendations found here: https://www.slant.co/options/4557/alternatives/~irc-alternatives

Also I just tried the matrix-integration of the IRC channel and if this will work again properly, I'd say that's modern enough (at least for me). It seems to feature everything I'd like to have

**Comment by Kissaki** [comment]
That doesn’t sound good for matrix.

I think we should take a look at Gitter then. See how well the IRC bridge works. As for noteworthy users, I know Jenkins uses it.

**Comment by Kissaki** [comment]
Looks like theirs is only providing an IRC server, not actually an IRC bridge to existing channels.

**Comment by davidebeatrici** [comment]
Our Matrix room is now completely working.

@Mikaela Thank you for reporting the issue!

**Comment by Krzmbrzl** [comment]
Maybe we should document somewhere that this matrix-room exists and poses a more modern interface to the general IRC channel (plus maybe a short list of instructions on how to connect to either one)...

**Comment by davidebeatrici** [comment]
Definitely.

**Comment by Krzmbrzl** [comment]
I don't have permission to edit https://wiki.mumble.info/wiki/Main_Page

Could someone add the link https://matrix.to/#/#irc://irc.freenode.org/mumble under the IRC-link with a comment that this allows a more modern UI than plain IRC (maybe even suggest to use the Riot app)

**Comment by davidebeatrici** [comment]
Added, thank you!

**Comment by hyperak** [comment]
xmpp?

**Comment by Krzmbrzl** [comment]
We're currently rather happy with the Matrix solution as this allows people to still use plain IRC and still communicate with everyone that uses matrix :point_up:

**Comment by hyperak** [comment]
well, I suppose there's bridges for xmpp, too, so one more way to make people happy.

don't rely on my service, but here goes:

#mumble%irc.freenode.org@biboumi.dieg.io
