### ISSUE TITLE
Cannot assign keybinds

### ISSUE THREAD

**Issue by derekagraham78** [mumble-voip/mumble#3816]
I tried to assign a keybind for push to talk and no matter what keys I hit it doesn't recognize any input when I click the shortcut assign a key. 
OS: Fedora Workstation 31
Desktop: GNOME
Flatpak install

**Comment by BenDrysdale** [comment]
I'm also having the same issue on MacOS Mojave and Mumble 1.3.0.

**Comment by davidebeatrici** [comment]
@BenDrysdale Have you given Mumble accessibility permissions?

**Comment by froggr** [comment]
I have the same issue. Mojave and mumble 1.3.0.

**Comment by froggr** [comment]
On Mojave and Mumble 1.3.0, this issue occurred on first install. Im assuming accessibility perms were granted _after_ the app started. Issue was solved for my by simply restarting the app.

**Comment by pferreir** [comment]
Same here one Fedora 31!

**Comment by Krzmbrzl** [comment]
@pferreir if you start Mumble from the console, does anything related seem to show up in the logs there?

**Comment by pferreir** [comment]
This is all I get:
```
$ mumble          
QSocketNotifier: Can only be used with threads started with QThread
<W>2020-05-18 15:06:08.812 CELT bitstream 8000000b from /usr/lib64/mumble/libcelt0.so.0.7.0
<W>2020-05-18 15:06:08.815 Theme: "Mumble"
<W>2020-05-18 15:06:08.815 Style: "Lite"
<W>2020-05-18 15:06:08.815 --> qss: ":themes/Mumble/Lite.qss"
<W>2020-05-18 15:06:08.816 Locale is "en_US" (System: "en_US")
<W>2020-05-18 15:06:08.860 Database SQLite: "3.30.0"
<W>2020-05-18 15:06:08.862 Overlay: Listening on "/run/user/1000/MumbleOverlayPipe"
<W>2020-05-18 15:06:08.882 GlobalShortcutX: Using XI2 2.3
<W>2020-05-18 15:06:08.882 QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
<W>2020-05-18 15:06:08.981 Wayland does not support QWindow::requestActivate()
<W>2020-05-18 15:06:08.987 AudioInput: Opus encoder set for VOIP
<W>2020-05-18 15:06:08.987 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-05-18 15:06:08.987 PulseAudio: Starting input alsa_input.pci-0000_00_1f.3.analog-stereo
<W>2020-05-18 15:06:08.987 PulseAudio: Starting output: alsa_output.pci-0000_00_1f.3.analog-stereo
<W>2020-05-18 15:06:08.992 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-05-18 15:06:08.995 AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2020-05-18 15:06:08.999 Updating application palette
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2020-05-18 15:06:43.974 OverlayConfig failed to grab desktop image, trying desktop widget...
<W>2020-05-18 15:06:43.974 QPixmap::grabWidget is deprecated, use QWidget::grab() instead
```

**Comment by Krzmbrzl** [comment]
> Wayland does not support QWindow::requestActivate()

Ah so you're using Wayland? Please have a look at #4073 and #3243 and see if that helps you :)

**Comment by pferreir** [comment]
Oh, thanks! So I take it the fix will be on 1.4? I'm using Wayland because it's the default in Fedora 31.

**Comment by Krzmbrzl** [comment]
As I understood it, the fix should already be in 1.3.0 but you'll have to use DBus to send the PTT events to mumble. See #3675

**Comment by moedn** [comment]
Same issue here on

- Fedora 32 (Workstation), 
- dnf install (as suggested in the [wiki](https://wiki.mumble.info/wiki/Installing_Mumble#Fedora));
- mumble version 1.3.0

I found the `Mumble.config` in `~/.config/Mumble` with the section `[shortcuts]` in line 30.

Anyone knows if and how one can define shortcuts there? → would be a great workaround :)

**Comment by Krzmbrzl** [comment]
> Anyone knows if and how one can define shortcuts there? → would be a great workaround :)

It should be possible but the format is more or less binary-ish, so I guess it's not easy. Additionally the shortcuts are platform dependent so you can't really copy it from elsewhere.

Furthermore you probably can't assign shortcuts, because the global shortcut engine is not working on your system (for some reason). That means that even if you were able to set the shortcuts via the settings, you wouldn't be able to trigger them.

**Comment by TheNyneR** [comment]
I'm having the same issue on Gentoo with Sway.
When creating a bindI can assign the function but not the input keys to the bind itself.

**Comment by Krzmbrzl** [comment]
Closing this bug in favor of #5257
