### ISSUE TITLE
UI Issues After Upgrading to 1.3.0

### ISSUE THREAD

**Issue by Jrawke** [mumble-voip/mumble#3817]
Hello,

After upgrading my mumble client to 1.3 (1.3.0-1~ppa1~bionic1) I am running into some UI issues.

First, the "layout" setting I choose does not seem to apply after I restart the client. Every time I close and re-open mumble, the text input box is gone, and I have to select the "classic" layout in the settings again to restore it.

Second, the system tray icon in XFCE has an annoying quirk. Left-clicking the icon brings up a context menu with "Quit Mumble" highlighted. So if you do a quick single left-click, it will close mumble when the mouse button is released. To open mumble from the tray icon, you actually have to hold down left click, and then move the mouse to the "Show" icon. I've attached a screenshot of this behavior.

Please investigate at your convenience. Thanks.

![Screenshot_2019-09-28_13-47-37](https://user-images.githubusercontent.com/9104212/65822342-1959d480-e1f7-11e9-9e8a-ab879a0625d6.png)
![2019-09-28-134952_3000x1920_scrot](https://user-images.githubusercontent.com/9104212/65822343-1959d480-e1f7-11e9-81e4-90b7e8e5bca1.png)

**Comment by davidebeatrici** [comment]
Hello,

> First, the "layout" setting I choose does not seem to apply after I restart the client. Every time I close and re-open mumble, the text input box is gone, and I have to select the "classic" layout in the settings again to restore it.

Try to delete the `[ui]` section in `~/.config/Mumble/Mumble.conf`.

> Second, the system tray icon in XFCE has an annoying quirk. Left-clicking the icon brings up a context menu with "Quit Mumble" highlighted. So if you do a quick single left-click, it will close mumble when the mouse button is released. To open mumble from the tray icon, you actually have to hold down left click, and then move the mouse to the "Show" icon. I've attached a screenshot of this behavior.

`Quit Mumble` is the first option in the menu because the actions' order is reversed when the system bar is at the top of the screen:
https://github.com/mumble-voip/mumble/blob/0cd23554a7c0b78bf757ba625e6c589cbe22754f/src/mumble/MainWindow.cpp#L3088-L3118

How's the actions' order in other applications' tray icon's menu?

**Comment by Jrawke** [comment]
I deleted the entire ~/.config/Mumble/Mumble.conf file, reconfigured my client, and the issue still persists.

For other applications' tray icons, a quick left-click will bring up the context menu, but not actually select any option. You then have to click a second time on the option you want to select.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issues, we'll look into them!

**Comment by Jrawke** [comment]
Thank you!

**Comment by davidebeatrici** [comment]
You're welcome!

**Comment by dstensnes** [comment]
I too have noticed that the chat input field disappears when restarting mumble with a custom layout. It is however not gone, but it's size is close to zero, so you can actually grab the separator line and move it a bit until it is all visible again.

**Comment by dstensnes** [comment]
it is just that this separator line is very close to the edge of the window, so a bit of pixel hunting might be needed. I use a tiling window manager without window borders, so it is probably much easier for me, since there is no window border to hit if i miss the separator line

**Comment by Jrawke** [comment]
@dstensnes I observe the same behavior. The chat box is actually not gone, but it's size is close to zero so you have to grab the line and drag it up.

**Comment by Krzmbrzl** [comment]
According to the issues that were described by the last comments, this is a duplicate of #3701

**Comment by Jrawke** [comment]
The textbox issue was fixed a while ago for me when you resolved #3701. The other problem I was able to fix by tweaking some settings with my desktop environment. Closing the issue since it is fixed. Thanks.

**Comment by Krzmbrzl** [comment]
Glad to hear that! And thanks for the status update :+1:
