### ISSUE TITLE
Mumble not connecting to server with .blue domain.

### ISSUE THREAD

**Issue by ZingBlue** [mumble-voip/mumble#3825]
I am running a Mumble server and I have recently bought a domain, the domain is a .blue domain, and whenever I try to add a .blue server to the Mumble favorite servers, the connect button greys out and no one can connect.

**Comment by davidebeatrici** [comment]
Could you write here your domain, please?

With an unresolved domain the `Connect` button is supposed to be disabled.

I tried with a random (existing) `.blue` domain and the button is enabled.

**Comment by ZingBlue** [comment]
The domain is "pinko.blue", it should be working, the DNS is connected to my server using a standard A record. It is connected to an Azure VM if that helps.

**Comment by davidebeatrici** [comment]
```
$ host pinko.blue
Host pinko.blue not found: 3(NXDOMAIN)
```

**Comment by ZingBlue** [comment]
I'm gonna try changin my DNS, I am using a sort of obscure domain registering service and it might have an buggy nameserver.

**Comment by ZingBlue** [comment]
It turns out it was a problem with the DNS, sorry for taking up your time. (I'm new to cloud sorry).

**Comment by davidebeatrici** [comment]
No problem.
