### ISSUE TITLE
Add support for PipeWire

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3834]
https://pipewire.org

**Comment by Gert-dev** [comment]
Just wanted to add that SDL recently added PipeWire support, and that [its code](https://github.com/libsdl-org/SDL/blob/main/src/audio/pipewire/SDL_pipewire.c) might prove to be a useful reference when in doubt - last time I checked the PipeWire documentation wasn't too extensive, though it's grown in the meantime.

**Comment by davidebeatrici** [comment]
Thanks for pointing it out!

**Comment by Kissaki** [comment]
To add some context of what this even is, from the linked website:

> PipeWire — Multimedia processing
> 
> PipeWire is a project that aims to greatly improve handling of audio and video under Linux.
> It provides a low-latency, graph based processing engine on top of audio and video devices that can be used to support the use cases currently handled by both pulseaudio and JACK. PipeWire was designed with a powerful security model that makes interacting with audio and video devices from containerized applications easy, with supporting Flatpak applications being the primary goal. Alongside Wayland and Flatpak we expect PipeWire to provide a core building block for the future of Linux application development.

**Comment by toby63** [comment]
There is pipiwire-pulse though, so this should work as well.

**Comment by JuniorJPDJ** [comment]
> There is pipewire-pulse though, so this should work as well.
It works, but for me personally it's workaround.

**Comment by davidebeatrici** [comment]
`pipewire-jack` exists too, but native support is the way to go.
