### ISSUE TITLE
Q: Audio input/output

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3838]
I am currently writing the audio hooks for the new plugin framework but I need to get some more info on how the audio PCM arrays are structured.

Condensed I think the question boils down to this:
1. Is the AudioInput in Mumble always mono (only one channel)? If not how many channels does it have and how many samples per channel
2. Are all audio sources (`AudioOutputUser`) mono? If not the same question as above applies
3. What is the memory structure of the final audio output-array (how does it arrange the samples of the different channels)?

Further details on what exactly I'd like to know are listed below.

# Input
I figured the best place to get a hold of all audio input would be in the `AudioInput::encodeAudioFrame()` function, grabbing the `psSource` variable. If anyone has a different suggestion I'd be glad to hear it.
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioInput.cpp#L792-L798

Ultimately that would boil down to using the `AudioInput::psMic`variable either directly or after echo-removal:
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioInput.cpp#L847-L854

I would grab the audio input right before this line
https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioInput.cpp#L969

The question that I am left with is the structure of `psMic`/`psSource`. I know that its size is `AudioInput::iFramesize`
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioInput.cpp#L132
but I need to know how many channels there are in the audio input and how many samples per channel.
Or is the input always just a single channel with `iFrameSize` samples?

# Output
For getting the hold of the audio output I figured I'll hook myself into `AudioOutput:mix` - again if there is a better way, let me know :)

My intention is to firstly grab the individual audio source's audio PCM via the `pfBuffer` variable:
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioOutput.cpp#L489

For this variable I am again asking the question of how many channels (and samples per channel) there are in that audio. From this code
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioOutput.cpp#L386
I suspect that it only has a single channel with `nsamp` samples in it. Is this correct?

As a second hook I want to grab the total audio after it has been mixed together. For this I think the `output` variable is the way to go as this one ensures that I can always use a float-array.
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioOutput.cpp#L407-L408
From the code above I deduce that this output now contains `AudioOutput::iChannels` channels and `nsamp` samples per channel.  However I don't get how this is tored in memory. I would have thought that the different channels are laid out one after another in the array. So if we have 10 samples per channel I'd expect the first 10 entries in `output` to belong to the first channel, the next 10 to the second one and so on.
However this code right here
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioOutput.cpp#L559-L565
seems to disagree with my theory. To me this seems as if `output` groups together the different samples from the different channels "by index". So if we have 4 channels, the first four entries in `output` would be the first sample in the first, second, third and fourth channel respectively. The next four entries would be the second samples of the respective channels and so on. Is this correct?

**Comment by davidebeatrici** [comment]
The audio input system supports multiple channels, but the protocol only uses one.

See `iMicChannels`:
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioInput.cpp#L377-L499

Technically speaking, the term "samples" indicates the frames multiplied by the number of channels.
Unfortunately it seems that the code doesn't take that into account and uses the terms interchangeably.

Here's the mixer code:
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/AudioInput.cpp#L207-L375

> To me this seems as if `output` groups together the different samples from the different channels "by index". So if we have 4 channels, the first four entries in `output` would be the first sample in the first, second, third and fourth channel respectively. The next four entries would be the second samples of the respective channels and so on. Is this correct?

Correct:
https://github.com/mumble-voip/mumble/blob/523d40c2b60bb4b0851b26169447f1e8df6625f8/src/mumble/JackAudio.cpp#L322-L336

**Comment by Krzmbrzl** [comment]
Thanks for the info :+1:

> The audio input system supports multiple channels, but the protocol only uses one.

so in different words: It's possible in theory but isn't used (yet)?

**Comment by davidebeatrici** [comment]
Correct, see #2829.

**Comment by Krzmbrzl** [comment]
Alright - thank you :)

**Comment by davidebeatrici** [comment]
You're welcome :)
