### ISSUE TITLE
QSslSocket::setDefaultCaCertificates is deprecated

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3840]
The function
https://github.com/mumble-voip/mumble/blob/cf81dee47d5adeb61b09c49c2096cf3c61772e66/src/mumble/main.cpp#L601-L602
is deprecated since Qt 5.12: https://doc.qt.io/qt-5.12/qsslsocket-obsolete.html#setDefaultCaCertificates

But then again there's this comment about it fixing some sort of memory leak. What does this mean? Can we fix this without breaking something or is this still important :thinking:

**Comment by davidebeatrici** [comment]
The code is only compiled with debug configurations:
https://github.com/mumble-voip/mumble/blob/cf81dee47d5adeb61b09c49c2096cf3c61772e66/src/mumble/main.cpp#L600-L607

It was added in bcaa6c73fe50d30c59624825d0ef2ffcf70b04c5, unfortunately no description is provided.

I think the comment refers to https://bugreports.qt.io/browse/QTBUG-6504, meaning that we can safely delete the workaround.
