### ISSUE TITLE
TestPacketDataStream fails on ARM64

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3845]
```cpp
FAIL!  : TestPacketDataStream::space() 'out.isValid()' returned FALSE. ()
   Loc: [TestPacketDataStream.cpp(124)]
```

https://github.com/mumble-voip/mumble/blob/bafcf47280a133801e4e6c7b5bb7f3bf2cfe5e8c/src/tests/TestPacketDataStream/TestPacketDataStream.cpp#L124

Once this is fixed as per #3846 the travis build make check should be enabled.

**Comment by Kissaki** [comment]
Added reference to missing make check mentioned in #3846; should be enabled once this is fixed.

**Comment by Krzmbrzl** [comment]
As I see it, the test is back in place...

**Comment by davidebeatrici** [comment]
It's not, tests are not run for the ARM64 build.

**Comment by carlwgeorge** [comment]
In addition to arm64 (aka aarch64), I see the same failure with s390x and ppc64le.  Only x86_64 passes as far as I can tell.

**Comment by Krzmbrzl** [comment]
Presumably this class relies on something like the size of an integer being exactly x bytes or something like this :thinking:

**Comment by thesamesam** [comment]
All of the arches which fail have unsigned char, so that's it I think.

**Comment by Krzmbrzl** [comment]
I fail to see why this would be a problem other than perhaps causing compiler warnings. But to my understanding signed and unsigned char should be of the exact same byte size :thinking:

**Comment by davidebeatrici** [comment]
The function used in the test behaves differently depending on whether the variable is signed:

https://github.com/mumble-voip/mumble/blob/73d8a4d5dbd2c45bd141518bb8b9a2ad796fde1f/src/PacketDataStream.h#L140-L192

https://github.com/mumble-voip/mumble/blob/73d8a4d5dbd2c45bd141518bb8b9a2ad796fde1f/src/PacketDataStream.h#L40-L50

https://github.com/mumble-voip/mumble/blob/73d8a4d5dbd2c45bd141518bb8b9a2ad796fde1f/src/PacketDataStream.h#L34

**Comment by Krzmbrzl** [comment]
How does
https://github.com/mumble-voip/mumble/blob/73d8a4d5dbd2c45bd141518bb8b9a2ad796fde1f/src/PacketDataStream.h#L143
really check for the _type_ of the variable passed? I would have interpreted as if it was merely checking whether the first bit is set, which afaik indicates a negative number, **if the respective type is signed** and has no special meaning for unsigned types :thinking: 
At least that's what I believe the first part does. What the second part with the inverted bits is trying to accomplish, I don't quite get :eyes:

**Comment by thesamesam** [comment]
If you want to avoid having to mess with the existing logic, you can build with `-fsigned-char` for now.

**Comment by davidebeatrici** [comment]
We can use `int8_t`, no problem. Would you like to create a pull request for it?

**Comment by Krzmbrzl** [comment]
I still fail to see how the issue can be in the variable's _type_. We're only testing its binary layout (the set bits) and afaik that doesn't change between signed and unsigned _types_ :eyes:

**Comment by sirjeannot** [comment]
In the meantime, would be possible to republish the last working version for aarch64 (for the docker image).
https://github.com/mumble-voip/mumble-docker/issues/3

**Comment by Krzmbrzl** [comment]
From https://github.com/mumble-voip/mumble/issues/5943#issue-1426314393:

> TestPacketDataStream::space() fails on aarch64, due to the fact that by default 'char' is unsigned on arm unlike i386 where 'char' is signed.
>
> Using gcc's '-fsigned-char' makes the test work.
>
> FWIW this is enough to run the server. The client does not seem to work, it can not connect to any server, "Invalid Server" appears on the shell.

**Comment by boletus-edulis** [comment]
> I still fail to see how the issue can be in the variable's _type_. We're only testing its binary layout (the set bits) and afaik that doesn't change between signed and unsigned _types_ eyes

I do not know much C++, but in C the following test.c illustrates the behavior:

```c
#include <stdio.h>

int
main(){
  char c = -2;

  printf("%hhx\n", c);

  // promoting a datatype retains sign
  printf("%hx\n", c);
  printf("%x\n", c);

  return 0;
}
```

x86_64 $ gcc -o test test.c
x86_64 $ ./test
fe
fffe
fffffffe

aarch64 $ gcc -o test test.c
aarch64 $ ./test
fe
fe
fe

x86_64 $ gcc -fsigned-char -o test test.c
x86_64 $ ./test
fe
fffe
fffffffe

aarch64 $ gcc -fsigned-char -o test test.c
aarch64 $ ./test
fe
fffe
fffffffe

**Comment by Krzmbrzl** [comment]
@boletus-edulis thanks for the illustration! I think that finally cleared things up for me. Especially in addition with the chat I had with @davidebeatrici about this this morning, where I/we realized that even though `PacketDataStream::operator<<` takes its argument as an unsigned 64-bit integer, the code actually manually checks for the most significant bit and if that is set, it interprets the number as negative:
https://github.com/mumble-voip/mumble/blob/73d8a4d5dbd2c45bd141518bb8b9a2ad796fde1f/src/PacketDataStream.h#L143-L144

Combined with the fact that the conversion from signed to unsigned makes the difference that it makes (in particular whether we convert the signed value to `unsigned char` or then a step later to `unsigned int64`, I think I now understand what is going on.
Let's see if I can get it fixed :D

**Comment by Krzmbrzl** [comment]
TODO: Make use of https://github.com/Krzmbrzl/cmake-compiler-flags to set the compiler flags to ensure signed chars on all platforms.
(This seems most robust as our code might depend on char-signedness in different places as well)
