### ISSUE TITLE
PCH header generation fails with MinGW

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3847]
After switching from Ubuntu Xenial (16.04) to Ubuntu Bionic (18.04) on Travis CI (#3850), our MinGW builds failed with the following error:

```
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: release/mumble_pch.hpp: No such file or directory
compilation terminated.
```

We disabled PCH for the builds, but we should investigate what is causing the issue.

**Comment by Krzmbrzl** [comment]
Possibly related: https://stackoverflow.com/questions/21008274/precompiled-headers-not-working-in-debug-build-with-qt-creator-qmake-mingw
