### ISSUE TITLE
Window decoration kept on Sway

### ISSUE THREAD

**Issue by nyovaya** [mumble-voip/mumble#3848]
On Wayland compositors it seems that Mumble keeps its decoration(like window bar, close, minimize, etc) even though it shouldn't be that case.
![Screenshot_13-10-2019_22-40-51](https://user-images.githubusercontent.com/5812753/66722170-98abf280-ee0a-11e9-802e-2f0cb6753efa.png)

Firefox as a direct comparison:
![Screenshot_13-10-2019_23-04-45](https://user-images.githubusercontent.com/5812753/66722445-e6762a00-ee0d-11e9-8c7e-1924c1bae588.png)

**Comment by davidebeatrici** [comment]
From: https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland

> Older versions of Qt always show window decorations. To hide them:
> ```
> QT_WAYLAND_DISABLE_WINDOWDECORATION=1
> ```
