### ISSUE TITLE
Codacy CI fails

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3852]
The (newly introduced) Codacy CI that aims to provide automatic PR reviews is either nont configured properly yet or it isn't suited for a project like Mumble as it fails a PR because the author of the PR is not a member of the Mumble organization (see #3743 - https://app.codacy.com/manual/mumble-voip/mumble/pullRequest?prid=4318600 - for further details)

**Comment by davidebeatrici** [comment]
It seems that Codacy only analyzes commits authored by organization members unfortunately: https://support.codacy.com/hc/en-us/articles/115001959985-Why-do-i-get-a-Not-a-member-of-the-organization-message-

I'm going to disable it for pull requests.
