### ISSUE TITLE
[Feature Request] UI indication for password-protected channels

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3856]
At the moment there seems to be no indication in Mumble's UI for password-protected channels. Thus making it impossible to tell which channels are password-protected and which are not.

Not even the error message `You were denied Enter privileges in XYZ` makes it clear that the channel is password-protected (one could think one simply doesn't have the permission to enter it when instead only the PW is missing).

I think adding a lock-symbol in the channel "bar" would be nice - See this TS3 screenshot for what I mean: http://img.creativemark.co.uk/uploads/images/558/11558/largeImg.png

In terms of implementation these links might be useful:
https://stackoverflow.com/questions/12316309/how-to-set-an-image-for-a-row
https://stackoverflow.com/questions/22093510/display-image-in-qtreeview

**Comment by davidebeatrici** [comment]
I agree.

**Comment by Krzmbrzl** [comment]
https://github.com/mumble-voip/mumble/pull/3872#issuecomment-547812750 indicated that  the client doesn't even know about channel passwords in the first place, which makes implementing this feature a bit harder than I thought it'd be. I checked the code and the comment seems to be correct.

Thus my proposal would be to add a new field `passwordHash` to the Channel class that contains the hashed password for this channel or nothing, if the channel isn't password protected. This way, the UI can not only indicate which channels are password-protected, but also which ones the user can enter nonetheless because he/she has the correct token set already (I am thinking about a red, closed lock vs a green open lock for the latter two  cases).
Using a hash has the advantage that the client still doesn't know the actual passwords so it shouldn't be able to read these out by using a custom version of Mumble.

In order for this to work though, we'd need to make sure that both the server and the client use the same hash-algorithm (with the same salt). Therefore I'd propose also adding the hashing function to e.g. `Channel.h` and `Channel.cpp` which is then used by both: server and client.

What do you think about this?
