### ISSUE TITLE
[Feature Request] Improve handling of password-protected channels

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3857]
When attempting to connect to a password-protected channel (without having the respective access-token set) the user gets a generic error message of type
```
You were denied Enter privileges in XYZ
```
From the error message one could assume that one doesn't have the permission to access the channel. Therefore I'd suggest to change the message to include something like `Wrong password` or `No password provided`.

Also I think that the attempt to enter a password-protected channel could optionally trigger a pop-up for entering the password for that channel. And on successful entering, the password could be stored permanently into the user's access tokens.

**Comment by davidebeatrici** [comment]
I agree.
