### ISSUE TITLE
[Feature Request] Add password option to connect dialog

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3858]
Right now I can only specify a name when connecting to a server. if I add the server to my favorites, I can set URL, port and a label in addition to that.
I think it would be a good addition to allow to specify a password as well - both: in the favorite server panel and in the default connect-prompt.

The lack of such an option forces Mumble to display an error message on connect stating (e.g.)
``` 
Wrong certificate or password for registered user. if you are certain this user is protected by a password please retry.
```
This in an of itself isn't bad but I'd prefer to have the option to specify a password to begin with :)

**Comment by davidebeatrici** [comment]
We were actually thinking about removing password authentication.

**Comment by Krzmbrzl** [comment]
Well that's another way of solving the problem :P 

But how would you handle e.g. setting up a server? The user connecting first gets to be admin?

**Comment by davidebeatrici** [comment]
`SuperUser` would be the only user with a password.

An access token could also be generated instead.

**Comment by ZingBlue** [comment]
While an access token would work, it is nice to have a password for private servers. Even if the feature is deprecated it would probably be nice to have.

**Comment by davidebeatrici** [comment]
The password to access the server will always remain.

Once a user is registered, the password is not required anymore.

**Comment by Krzmbrzl** [comment]
> An access token could also be generated instead.

In how far would that be different from a password? Like how do I have to imagine registering as admin for the first time? :thinking:

**Comment by davidebeatrici** [comment]
You connect to the server and then use the token; once you've done that you have full privileges.

**Comment by Krzmbrzl** [comment]
Ah okay so literally using the same system as is currently in use for entering channels :bulb:

**Comment by davidebeatrici** [comment]
Correct.

**Comment by toby63** [comment]
I might be wrong, but how do access tokens solve the problem on first connect?
As far as I see the problem described above, remains.
You should be able to type the password in the `add server`-window, instead of getting an error message and then typing the password.

**Comment by Krzmbrzl** [comment]
> I might be wrong, but how do access tokens solve the problem on first connect?

It doesn't

The point made here is that you basically never connect to the server via the SuperUser account. Thus adding this field to the UI would make folks think that they could password-protect their server or something like that which is not possible (afaik at least).
Thus for the vast majority of cases you don't need that password field and the few times that you'll actually need it, you can just type it in when prompted. No real harm done here

**Comment by toby63** [comment]
> No real harm done here

I think it's bad UX to show an error message and then prompt for a password, this should work differently, at least sometime in the future.
