### ISSUE TITLE
Mumble 1.3.0 release overlay crashes Black Ops II on Windows

### ISSUE THREAD

**Issue by ADAMPOKE111** [mumble-voip/mumble#3859]
Starting Call of Duty: Black Ops II (multiplayer in this instance, but singleplayer uses the exact same engine) when the Mumble overlay is enabled (version 1.3.0, Windows x64) causes it to crash.

Here's the crash report from event viewer:

```
Faulting application name: t6mp.exe, version: 1.0.0.1, time stamp: 0x54cb235b
Faulting module name: mumble_ol.dll, version: 1.3.0.0, time stamp: 0x5d741ecd
Exception code: 0xc0000005
Fault offset: 0x00010112
Faulting process ID: 0x15bc
Faulting application start time: 0x01d585369fedd81f
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Call of Duty Black Ops II\t6mp.exe
Faulting module path: C:\Program Files\Mumble\Versions\1.3.0\mumble_ol.dll
Report ID: 8aca0c04-f8f4-4d19-ac6a-c29dd2c483de
Faulting package full name: 
```

**Comment by davidebeatrici** [comment]
Could you debug the game with the overlay injected?

Our debug symbols are available at https://mumble.info/symbols.

**Comment by ADAMPOKE111** [comment]
I have just tried to launch the game again with the overlay enabled and now I am unable to reproduce the results. This is odd because all of my friends were having the same issue. It may just be a first-launch after the game is installed type of thing.

**Comment by davidebeatrici** [comment]
No problem, please let us know in case it happens again.

**Comment by Kissaki** [comment]
Placing a file named `debugoverlay` next to the game executable will produce more debug output. Running DebugView alongside will provide some useful log information. In case you/someone wants to provide some more information without going the more complex debugger and symbols route. It could still allow us to get a better idea of when/where it happens.

If it’s a first run issue it should be reproducible as such. Personally I do not own the game, so no way to test.

**Comment by Krzmbrzl** [comment]
Any news here?
