### ISSUE TITLE
Update Qt version to 5.6.3 for Mumble 1.3.1

### ISSUE THREAD

**Issue by wildxthing** [mumble-voip/mumble#3862]
Qt version 5.6.3 is the last version that supports windows xp. Current build of Mumble uses 5.6.2 I don't know why.

**Comment by davidebeatrici** [comment]
Our current environment was built before Qt 5.6.3 was released.

**Comment by Kissaki** [comment]
Changelog https://code.qt.io/cgit/qt/qtbase.git/plain/dist/changes-5.6.3?h=5.6

Anything that concerns us?

**Comment by Krzmbrzl** [comment]
I guess this is still relevant? If so, the title should be changed, as 1.3 is already released now, so that would be something for 1.4...

@davidebeatrici

**Comment by davidebeatrici** [comment]
The first 1.4 snapshot will probably use Qt 5.12.5.

**Comment by Krzmbrzl** [comment]
> The first 1.4 snapshot will probably use Qt 5.12.5.

But it is not yet configured?

**Comment by davidebeatrici** [comment]
Correct.

@ZeroAbility is currently working on a (vcpkg) portfile for ZeroC Ice.

After that, only a few things to fix/improve remain in the CMake project (not in `master` yet).

**Comment by wildxthing** [comment]
Sorry this request is something I was wondering for version 1.3 since this will be the last version that supports Windows XP and 5.6.3 is the last version of QT that supports windows XP. That is why I was wondering why 1.3 didn't use that version. If there is some small patch to update Mumble 1.3 perhaps this should be added. If not Mumble 1.4 should use QT version 5.13 or later .

**Comment by davidebeatrici** [comment]
Mumble 1.4 will indeed use a recent version of Qt.

As for Mumble 1.3: even if were were to release 1.3.1 I don't think it's worth updating Qt, because it would require us to recompile the build environment (which is being deprecated).

**Comment by wildxthing** [comment]
Do you think it would be best to delete this request then

**Comment by davidebeatrici** [comment]
Are there any changes in Qt 5.6.3 you're interested in?

**Comment by davidebeatrici** [comment]
We have to rebuild the environment in order to update OpenSSL.

For that reason we're going to update to Qt 5.6.3.

**Comment by wildxthing** [comment]
To make this version still compatible with Windows XP please see below. 

"The latest version that supports XP is Qt 5.6.3. The Windows XP support is not enabled by default. You have to download the Qt source-code and compile it with ./configure -target xp. This means, if you install Qt 5.6.3 (pre-built) package the Windows XP support is not enabled! You must compile the source-code. Qt 5.6.3 is in strict phase and reliable if you want to support Windows XP, which is still installed on many computers in China, India, etc."

https://stackoverflow.com/questions/50255414/is-it-possible-to-run-a-qt-5-10-programm-on-xp

**Comment by davidebeatrici** [comment]
Thank you for the info!

We already do that: https://github.com/mumble-voip/mumble-releng/blob/a449a6c39a8cdf7f8a23a12311d92085f661b5ae/buildenv/1.3.x/win32-static/qt5.build#L40-L43

**Comment by Krzmbrzl** [comment]
@wildxthing are you actually still using Windows XP :eyes:

**Comment by wildxthing** [comment]
@Krzmbrzl 
No, but the 1.3.x builds should support it and i'm pretty sure all other major gaming/voip programs no longer support it so it's nice to give them at least one solid option for the people that still use it.

**Comment by davidebeatrici** [comment]
I agree.

You may want to read the discussion at #4001, if you didn't yet.

**Comment by Krzmbrzl** [comment]
The update has been performed in the background (for our internal builders)

**Comment by davidebeatrici** [comment]
For reference: https://github.com/mumble-voip/mumble-releng/commit/4b879261006671982c74698e4786db791634bedb
