### ISSUE TITLE
[Feature Request] Add an option to disable the text-2-speech queue

### ISSUE THREAD

**Issue by Malow** [mumble-voip/mumble#3863]
I want to have text-to-speech enabled for when users mute/unmute or connect/disconnect to the server, but I don't want them to queue up. Sometimes there's someone who presses the mute/unmute button 100 times in rapid succession, or spam connects and disconnects, and the text-2-speech guy then spends 5 minutes talking catching up to all those events. I would like him to interrupt and just discard any previous message and read the most recent one only, or maybe have a queue-length setting allowing at most X amount of messages in the text-2-speech queue and for any older ones to be discarded.

**Comment by Hartmnt** [comment]
I took a look at the TTS implementations:

https://github.com/mumble-voip/mumble/blob/master/src/mumble/TextToSpeech_macx.mm
https://github.com/mumble-voip/mumble/blob/master/src/mumble/TextToSpeech_unix.cpp
https://github.com/mumble-voip/mumble/blob/master/src/mumble/TextToSpeech_win.cpp

https://github.com/mumble-voip/mumble/blob/7a6274f19e2d7c2ffb76b7ebcd22d0c1df9445d9/src/mumble/Log.cpp#L883-L887

And it does not appear that we queue any TTS messages. So this queue seems to be a "feature" of the specific TTS engine that was used on the system. I do not think we can do anything about this, except maybe arbitrarily send some sort of "stop reading all TTS messages" to the TTS engines - if they even allow such API calls.
On the bright side, there have been some additions to the TTS settings (enable TTS only for certain events etc.)

But the issue at hand, I do not think we can reasonable "fix" this. What do you think @Krzmbrzl @davidebeatrici ?
