### ISSUE TITLE
Feature_request: Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE feedback templates to standardize mumble feedback

### ISSUE THREAD

**Issue by dingpengyu** [mumble-voip/mumble#3871]
hi mumble Developers
I observed in mumble's daily issue feedback that some of the questions were ambiguous, and a comprehensive feedback template was needed to help users and developers improve the efficiency of the issue.
Do you have any suggestions?
thanks

**Comment by davidebeatrici** [comment]
Hi,

`ISSUE_TEMPLATE`: A template for issues would definitely be helpful. I would add some fields to fill such as the Mumble version and the operating system.

`PULL_REQUEST_TEMPLATE`: We probably don't need it, I don't think we ever received "unclear" pull requests.

**Comment by dingpengyu** [comment]
> Hi,
> 
> `ISSUE_TEMPLATE`: A template for issues would definitely be helpful. I would add some fields to fill such as the Mumble version and the operating system.
> 
> `PULL_REQUEST_TEMPLATE`: We probably don't need it, I don't think we ever received "unclear" pull requests.

hi davidebeatrici
Thanks for your instructions

**Comment by davidebeatrici** [comment]
You're welcome.

**Comment by Krzmbrzl** [comment]
Is somebody currently doing this? If not, I'd go ahead and create an issue-template

**Comment by davidebeatrici** [comment]
As far as I know nobody is working on it, feel free to do it.

**Comment by Krzmbrzl** [comment]
Apparently GitHub has moved that to the repo's settings: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
(and [advises against](https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository) creating them manually)

As I don't have access the repo's settings, I'm afraid this work falls to you @davidebeatrici :)
