### ISSUE TITLE
Murmur server causes windows blue screen

### ISSUE THREAD

**Issue by yanmingsohu** [mumble-voip/mumble#3881]
When a new user connects to the server, the system blue screen prompts tcpip.sys to cause the system to crash on windows 2019 server

**My wifi adapter uses the following items:**
Client for Microsoft Networks
File and Printer Sharing for Microsoft Networks
VirtualBox NDIS6 Bridged Networking Driver
Internet Protocol Version 4 (TCP/IPv4)
SoftEther Lightweight Network Protocol
Internet Protocol Version 6 (TCP/IPv6)
Link-Layer Topology Discovery Responder
Link-Layer Topology Discovery Mapper I/O Driver

**Comment by davidebeatrici** [comment]
Are the drivers up-to-date?

**Comment by yanmingsohu** [comment]
Latest driver:
Intel(R) Dual Band Wireless-AC 8260  
date: 2019/9/10
version: 20.70.13.2

**Comment by davidebeatrici** [comment]
Does it happen with the Ethernet NIC as well?

**Comment by yanmingsohu** [comment]
There is no problem with the client, 
The server receives a connection and causes the system to be blue screen.

`tcpip.sys IRQL_NOT_LESS_OR_EQUAL`

**Comment by davidebeatrici** [comment]
I asked whether it happens with the Ethernet NIC so that we can exclude that it's a problem with the Wi-Fi NIC.

**Comment by yanmingsohu** [comment]
Give me time to configure

**Comment by davidebeatrici** [comment]
Sure, no problem.

**Comment by yanmingsohu** [comment]
I disable all network devices, use 127.0.0.1 connect server, still blue screen

**Comment by davidebeatrici** [comment]
Does it happen with another software (client + server) as well?

**Comment by yanmingsohu** [comment]
This is a pure system without any software and drivers installed explicitly.

The only possibility is that the virtualbox is not compatible with the black screen, maybe I have to test it on VMware.

**Comment by Krzmbrzl** [comment]
What version of Mumble did you experience this with?

**Comment by yanmingsohu** [comment]
> 您使用过什么版本的Mumble？

1.3.0

**Comment by Krzmbrzl** [comment]
Did I understand it correctly that this is a problem that only appears when using Windows *server* not normal Windows Desktop?

**Comment by yanmingsohu** [comment]
Yes, my friend has no blue screen with win10 system, only my win server has problems.

**Comment by davidebeatrici** [comment]
Could you write the details of the BSoD, please?

You can retrieve them with [BlueScreenView](https://www.nirsoft.net/utils/blue_screen_view.html).

**Comment by yanmingsohu** [comment]
it is this?

[060520-11796-01.dmp.zip](https://github.com/mumble-voip/mumble/files/4733411/060520-11796-01.dmp.zip)

**Comment by davidebeatrici** [comment]
<img width="1280" alt="BlueScreenView" src="https://user-images.githubusercontent.com/5897523/83828540-324d4a80-a6e1-11ea-84ec-3fedf209a2fc.png">

There's something terribly wrong with the time string of the various files.

I would check whether the problem persists on a fresh virtual machine.

**Comment by yanmingsohu** [comment]
Interesting, maybe dump files of different versions
