### ISSUE TITLE
Timed (Not) Ignore Messages Feature

### ISSUE THREAD

**Issue by Chris2000SP** [mumble-voip/mumble#3883]
I'm annoyed by some users who send things I don't want to see. The same users also send me useful messages.

I would like to be able to allow messages to be sent for a certain period of time, so that later when this user is automatically ignored again.

I always forget to ignore the person, and that's not how often the meaningful messages are.

Thanks

**Comment by Krzmbrzl** [comment]
This seems like a very edge-use-case that I don't think warrants a dedicated implementation.
