### ISSUE TITLE
Pressing enter in private message screen should send the message

### ISSUE THREAD

**Issue by derlade** [mumble-voip/mumble#3888]
See above. IMO, pressing Enter should send the message, pressing Shift+Enter should create a new paragraph. This way, I don't have to type the message, then lift my hands from the keyboard to click OK in the message screen.

**Comment by Krzmbrzl** [comment]
This should be configurable in the settings though as there might be people not wanting this behavior.

**Comment by davidebeatrici** [comment]
I agree.

**Comment by Krzmbrzl** [comment]
Actually coming back to this I disagree with this functionality. The private text chat window is  a separate window and it is not common for separate message windows to send on hitting enter.

I'd expect that kind of behavior for cases in which I have the text box embedded as a one-line element (more or less) but not from a separate window that already indicates it is built for multi-line texts.

Thoughts?

**Comment by toby63** [comment]
:thinking: I think all chat windows/tabs should have the same behaviour.

I suggest implementing double-enter:
So if you hit enter two times in (I don't know) less than one second, the message gets send.

**Comment by Krzmbrzl** [comment]
> I think all chat windows/tabs should have the same behaviour.

I disagree. These windows are inherently different, so I don't see why they should behave the same in that single bit :shrug: 

> I suggest implementing double-enter:

I press Enter twice a lot when writing stuff as this creates a new paragraph. I'd be very annoyed if my message got sent instead

**Comment by toby63** [comment]
Triple-Enter? :smile: 
Jokes aside, I would still like an option for this, so not-default, but can be activated by the user.

**Comment by Krzmbrzl** [comment]
Maybe something like optionally using control & enter to send the message (though I think that itself would be in direct contrast to the normal chat window where I *think* that inserts a new line. Could also be shift & enter though)

**Comment by toby63** [comment]
> Maybe something like optionally using control & enter to send the message 

To me thats not convenient, I wouldn't use it then.

Alternative I see:
* `Control+Enter` as default for send
* Option für using `enter` for send

**Comment by CaptainZidgel** [comment]
In Discord, enter sends and shift+enter creates a new line. I would appreciate this functionality and use it if it were an option in settings.

**Comment by streaps** [comment]
In the Send Message popup it makes sense to send the message with a click on the OK button – I would label the button "Send" though. A window shouldn't close on Enter in a text field, that's confusing. I agree with @Krzmbrzl

The text chat UI could be improved and the Send Message popup replaced by something else. E.g. Slack / Matrix / Discord like interface or a private message window that stays open with a chat log and an input line (traditional instant messaging style). This would be a GUI redesign and someone would need to work on a convincing concept.

+1 for wontfix

**Comment by toby63** [comment]
> In the Send Message popup

Now I understand, we are talking about this badly designed "direct-message"-window.
Ok, then I agree, for now it is wontfix, but at some point the "direct-message"-procedure should be reworked.

I thought the normal chat window also does not have a send option with enter :thinking:.

**Comment by Krzmbrzl** [comment]
> I thought the normal chat window also does not have a send option with enter

No that one sends on simply pressing Enter :)

The chat UI is being reworked in #3465
