### ISSUE TITLE
ACL question; mumble automatically adds a write ACL rule

### ISSUE THREAD

**Issue by wjtk4444** [mumble-voip/mumble#3890]
Sorry if that's the wrong place, but I have no better ideas where to ask this question. Please, correct the issue's title if you believe that this one is wrong/non descriptive enough. I have no idea what causes the actual issue or how to put it into better words.

I am familiar with wiki entries on ACL and groups. The 
```
@group < allow | deny > <permission> [, permission]+
```
syntax is assumed, I am using the client GUI to manage the ACL rules.

Let's consider the following channel layout and two user groups:
**moderators** and **users**.
```
root/
    child1
    child2
    ...
    childN
```
Moderators need the **Write ACL** permission in root channel to be able to edit members of the **users** group. **root** is not a voice channel however, so I want to prevent moderators from accidentally entering it. Moderators can create additional temporary channels under **root**, but I want to prevent them from accidentally not checking the `[ ] temporary` box and creating a permament channel. I tried the following:
```
@moderator allow Write ACL
@moderator deny Enter, Move, Make channel
```
It seems to work, but only for a time. When someone from the **moderators** group edits the ACL (namely, adds or removes a member from the **users** group), mumble automatically adds a new ACL rule in the **root** channel:
```
@moderatornickname allow Write ACL
```
which effectively allows him to enter the **root** channel as well as make non-temporary channels under **root**.

Is there any permament way of allowing the **Write ACL** in **root** channel only, while stripping the user of other permissions? (I am aware that they are able to re-grant those permissions to themselves. It's meant as a quality of life improvement rather than a security feature).

I am assuming that the automatical `allow Write ACL` rule creation is supposed to prevent users from locking themselves out without permissions. Nevertheless, I think that it's unnecessary as the **SuperUser** account exists and can be used to fix eventual issues. Is there any way of disabling this mechanism server-side?

**Comment by Kissaki** [comment]
Yes, the ACL server will make sure users do not lock themselves completely out from access.

There is also a bit of a UI issue in that the editor will accept and save ACL permissions as seen, but on saving add the additional ACL rule that prevents lockout.

I won't test anything today, so maybe you can confirm this yourself: Is this indeed only after another moderator edited the ACL, or is this perhaps before, after the ACL has been saved (and you can already see it upon reopening the ACL editor).

What confuses me a bit is why the new rule would be added if you do not deny edit ACL. I guess it gets added when enter is denied? That seems… unnecessary. Because with edit ACL the user could still give themselves permission again.

**Comment by Kissaki** [comment]
@wjtk4444 Do you have new information regarding this?

**Comment by wjtk4444** [comment]
If anything, I have more questions. But that's my own fault for tinkering with the setup. I restructured groups on my server a bit and for some reason now I cannot reproduce the behavior I described earlier.

>`@moderator allow Write ACL`
>`@moderator deny Enter, Move, Make channel`

> It seems to work, but only for a time.

No matter what I'm doing, I can Enter, Move and Make channel, so no "automatic" ACL rules are being created in this case. I'm unsure whetver I was seeing things last time, or things work differently now. I guess that the first option is more likely.

--

I tried removing myself from the **moderators** group (which will guarantee loss of all write ACL permissions) and it seems that you are right here

>or is this perhaps before, after the ACL has been saved

After re-opening the editor I can see a new rule being created, mumble (server? client?) prevented me from locking myself out.

`@myusername ACL Write allow`

--

My main issue here is that fact that I cannot *lock* myself out of entering a channel while keeping the ability to edit ACL within it. If I was wrong about what I said in my first post, then there is no issue regarding lockdown prevention mechanism.

**Comment by wjtk4444** [comment]
I have some more thoughts on the topic. Why not just make the **Write ACL** permission to allow people Write ACL and nothing else? Right now it's implied that one with the Write ACL permission can skip other permission checks.

For example, let's look on how permissions work on linux:

```
$ echo "contents" > file
$ chmod -w file
$ echo "contents" > file
bash: file: Permission denied
$ chmod +w file
$ echo "contents" > file
```

The fact that I am in power to change permissions doesn't mean that I can do things I have no permissions to do. I like this model more because it offers more flexibility. That way I could deny myself from accidentially accessing the **root** channel or creating non-temporary channels.

**Comment by krtemre** [comment]
Hi, can we make channels through cmd or any other c# scripts, or can we change @all write acl permission. Thank you.

**Comment by Krzmbrzl** [comment]
@krtemre what you are looking for is the Ice RPC interface.

**Comment by krtemre** [comment]
@Krzmbrzl Actually, is it related with Ice or not ı dont know, My problem is ı want to create channels using WPF by c# so ı use MumbleSharp library, server does not gave permission the change/create channel but ı can change the acl rules. So does wpf client has to have a certificate or there are any way to skip that process. Thanks.

**Comment by Krzmbrzl** [comment]
I have no clue about MumbleSharp. You'll have to ask the developers of that library how it is supposed to work.

**Comment by krtemre** [comment]
Well ı wrote them too but no answer, thanks for the support 👍
