### ISSUE TITLE
segfault when trying to sendMessage to a disconnected client

### ISSUE THREAD

**Issue by wfjsw** [mumble-voip/mumble#3893]
Segfault may occur during `msgAuthenticate` (Messages.cpp) process if session go away before fully established and after `ServerDB::authenticate` due to Connection.cpp trying to directly write to a destructed socket.

The sendMessage after UDP crypt key negotiation is more likely to trigger a segfault.

`uSource->peerPort()` and similar functions are found to be vulnerable too but not with such high possibility.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

I assume this is related to #3878, a pretty bad issue.

Do you already have a solution in mind?

**Comment by wfjsw** [comment]
I actually fixed #3878 with a try-and-fail mutex on msgAuthenticate and another on MurmurGRPCImpl::authenticateSlot but they are temporary fix and not guaranteed to be stable. All Qt developers that I came across recently told me that the whole server must be rewritten from scratch to completely remove these bugs.

**Comment by davidebeatrici** [comment]
Did they tell you the specific reason why the server has to be rewritten?

**Comment by wfjsw** [comment]
From their words I can interpret that there are tons of similar bugs like this laying around, which can be found by choosing a random source file and read it. The problem behind these bugs is believed to be a symptom of bad overall design and too many monkey-patches.

**Comment by davidebeatrici** [comment]
Feel free to create a pull request with your fixes/workarounds, even if they are not guaranteed to be stable: it's better than keeping everything in the current state.

If the server is in such a bad shape, we can use the opportunity to write a library that can be used to create custom servers, which is something we absolutely want to do.

**Comment by wfjsw** [comment]
UPDATE:

Another segfault was discovered at `ToRPC(const ::Server, const ::User*u, ::MurmurRPC::User *ru)` when 
`ServerUser` destruction happened during `User` object serialization.

Honestly, I am out of any solution, so Help Wanted.

**Comment by wfjsw** [comment]
Why does it create and destroy socket in one thread while use it in another 🤔?

**Comment by wfjsw** [comment]
With a lot of trial & error, the # 1 solution comes to my head is to defer the deletion of socket so that it survives from disconnection, destruct together with `ServerUser` and hope r/w on that socket will cause a smaller issue than crashing everything together.

The # 2 solution, which is live on my production env now, is to wrap QSslSocket* with QPointer so I can check its validity before any usage. Then I set `timeout` from 60 to 10 to disconnect these sockets early before they break.

**Comment by wfjsw** [comment]
Daily fresh stacktrace:
```
#0  0x00007fe7148bca30 in QAbstractSocket::state() const () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#1  0x000056529b21d382 in Connection::disconnectSocket (this=0x56529ce297d0, force=false) at ../Connection.cpp:201
#2  0x000056529b274e48 in Server::msgAuthenticate (this=0x56529c31b910, uSource=0x56529ce297d0, msg=...) at Messages.cpp:232
#3  0x000056529b23b913 in Server::message (this=0x56529c31b910, uiType=2, qbaMsg=..., u=0x56529ce297d0) at Server.cpp:1539
#4  0x000056529b3cebf3 in Server::qt_static_metacall (_o=0x56529c31b910, _c=QMetaObject::InvokeMetaMethod, _id=28, _a=0x7ffd707d7130)
    at ../../debug/.moc/murmur/moc_Server.cpp:301
#5  0x00007fe71444c906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x000056529b3cdddc in Connection::message (this=0x56529ce297d0, _t1=2, _t2=...) at ../../debug/.moc/murmur/moc_Connection.cpp:239
#7  0x000056529b21cfc5 in Connection::socketRead (this=0x56529ce297d0) at ../Connection.cpp:138
#8  0x000056529b3cd8b6 in Connection::qt_static_metacall (_o=0x56529ce297d0, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7ffd707d72d0)
    at ../../debug/.moc/murmur/moc_Connection.cpp:114
#9  0x00007fe71444c906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fe714913e37 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#11 0x00007fe7148f5de1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#12 0x00007fe71444c906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fe7148bbb53 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#14 0x00007fe7148bbbe0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#15 0x00007fe7148cdf31 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#16 0x00007fe714423586 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fe71447547a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fe712fdcf2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fe712fdd1c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fe712fdd25c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fe714474863 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fe71442227b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fe71442a262 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x000056529b22ebfc in main (argc=4, argv=0x7ffd707d8b98) at main.cpp:583
```

**Comment by wfjsw** [comment]
@davidebeatrici Is it possible to enforce another timeout between connect and version exchange? It may help solve this problem.

**Comment by davidebeatrici** [comment]
It's possible, yes.

Feel free to write as many workarounds as you want, so that we can mitigate the issue (until we rewrite the server).

**Comment by wfjsw** [comment]
Closing this since:
 - I suspect it's a gRPC issue (not really sure on this one) and gRPC support got removed by #5552.
 - Nobody seems to be able to reproduce this, nor in similar fashion in 2 years.
 - I stopped using Murmur and switched to my own server implemention since then, thus no resource is available to further work on this.
