### ISSUE TITLE
TTS Speech Language stuck on English

### ISSUE THREAD

**Issue by BOUSILLOR** [mumble-voip/mumble#3900]
On a freshly installed win10pro mumble 1.3.0 seems stuck with the tts defined at install time,
using "repair" option doesn't work it still using the same. While other application take the change "on-the-fly" and so is mumble on windows 7, -and on linux- . It seems stuck on win10. A quick search seems to show I'm not alone, some report inconsticency on the changes, as it would be ok only on a gender preferences it's annoying if language used on mumble is different from what was selected at install time.

**Comment by Kissaki** [comment]
I don’t understand what you are trying to say.

There is no TTS selection in the Mumble installer.

**Comment by BOUSILLOR** [comment]
yeah : basically when I installed windows 10 I chose english as the system default, and I use it system wide. I then modified the region settings to set it to my country's locals. Then I installed mumble and TTS was set to an english female voice. Since I use mumble only with french users I've set a french tts voice, every softwares took into account the change but mumble. It's stuck on the english first set tts voice. If you uninstall mumble, set windows system wide to the desired voice local, so french in my case, and reinstall it, mumble still keep the very first set tts. My windows 7 is also part english part french, and so are my Gentoos and they are working as expected. I'm kinda new to windows 10 but it seems that the system tts and the narrator feature are more like two different, separated features that it was on win7. So maybe mumble 1.3.0 doesn't grep the good one?
Is it more clear now?

**Comment by Mikaela** [comment]
I think I may be having the same issue on Debian Testing.

Generally my TTS is in English (I think), but when I use https://clozemaster.com/ in Firefox, it uses system/Firefox TTS and sets the language to e.g. Czech affecting Mumble too which I have figured out by sending numbers and having TTS say those in a different language after wondering about the mispronuncing it does.

I think what Mumbe could do would be adding an option to force specific TTS language in settings.

**Comment by BOUSILLOR** [comment]
that would be even better, and a per-chan option for multi-language servers would be even better. But as for now I just want it to behave as it should! I tried to wipe the prefs dir. and reinstall and the tts is still stuck! I'll look into the registry once I'm done with my project.

**Comment by Kissaki** [comment]
The Windows 10 speech settings do not actually have a setting to define the TTS output language.

It does have a list of installed, supported voice languages though.

![image](https://user-images.githubusercontent.com/93181/69573627-c453f800-0fc6-11ea-8be3-fb886958ff35.png)

So it must be Mumble telling Windows 10 the desired language / Win10 expecting Mumble to do so.

Changing the Mumble UI display language does not change the TTS language.

**Comment by BOUSILLOR** [comment]
The win 10 settings seem define the tts language BY the selected installed voice.
I didn't change mumble UI I changed the whole Windows UI to see if mumble followed.
Also I read somewhere that you CAN set a multilanguage tts environnement but you need to install Gio of windows extras and like to keep my OS small especially windows.
On an other note, I don't have a Microsoft account, - but it's a legit windows install, I just don't wqnt the extras except tts - and it seems the local on win10 can also be defined through it? as per this link : https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings-winpc/adding-new-languages-to-the-win10-tts-text-to/4c4d9535-497d-464a-a5ed-1c0c726b6760. So maybe mumble is linked to this one?

**Comment by ViBE-HU** [comment]
I'm on Windows 10 Pro (build 2009) and it's pretty annoying that no matter what is the default TTS voice it only use English instead of the default TTS voice. On Ubuntu it's works like a charm. Is there any possible workaround for this on Windows?

**Comment by keven1229** [comment]
It seems like Windows has TWO DIFFERENT TTS SETTINGS
One is in Settings app -> Time and Language -> Voice , which seems no effect to mumble TTS ,maybe is used by UWP applications
![image](https://user-images.githubusercontent.com/41236776/118955208-0fb74e80-b991-11eb-99c2-757ebd7fb69f.png)

Another one is in classic control panel: 控制面板\轻松使用\语音识别\文本到语音转换 (search “text to speech” in control panel is the same) ,mumble will use the settings here to control which voice pack to use ( and also the voice language ) ,other non-UWP applications maybe the same.
![image](https://user-images.githubusercontent.com/41236776/118956076-dd5a2100-b991-11eb-82b9-3c6161565949.png)
![image](https://user-images.githubusercontent.com/41236776/118956455-33c75f80-b992-11eb-8cf9-9f7fc87df87a.png)

**Comment by Krzmbrzl** [comment]
@keven1229 just to be sure: with that setting you are able to change the TTS language successfully?

**Comment by keven1229** [comment]
> @keven1229 just to be sure: with that setting you are able to change the TTS language successfully?

Yes, I changed the language from English to Chinese
The setting in Settings App and setting in control panel is different.

**Comment by Krzmbrzl** [comment]
Perfect. Thank you very much for sharing this solution :+1: 

In that case I'll close this issue as resolved.

**Comment by Kissaki** [comment]
I started a client FAQ on the website and added this there because I think this may be a common issue and confusion.
