### ISSUE TITLE
Is there a way to generate the client certificate via the command line in Linux?

### ISSUE THREAD

**Issue by asheeshr** [mumble-voip/mumble#3902]

**Comment by Krzmbrzl** [comment]
What use-case do you have in mind? AFAIK Mumble generates a certificate on first start anyways...

**Comment by asheeshr** [comment]
The use case is to be able to share a standard configuration file with users that is read only as mentioned here https://github.com/mumble-voip/mumble/issues/3904#issuecomment-558828673

The client certificate seems to be the only information that is unique to each individual client and is stored in the configuration file. I'm wondering if there's a way to either generate it per client via a script and create a configuration file programatically or to store the client certificate outside of the configuration file thereby eliminating client specific information from the configuration file altogether.

**Comment by Krzmbrzl** [comment]
As I said, I don't think this functionality exists. Maybe @Kissaki knows of something.
And after that I think this issue could be closed. Alternatively you could rephrase your question as a feature request, but honestly I have the feeling that it won't be implemented any time soon. As I see it, it would require quite a hit of programming and at least from my perspective this wouldn't be worth the effort...

**Comment by Kissaki** [comment]
No, I am not aware of any such functionality.

You can pass `-h` or `--help` to list the available CLI arguments.

The argument code for the Mumble client is at [main.cpp#L144-L255](https://github.com/mumble-voip/mumble/blob/1.3.0/src/mumble/main.cpp#L144-L255). Nothing of the sort there.

To be honest I would expect this to be one of the easier tasks to implement, even if not trivial. But it is rather localized and touches only two distinct components (cert gen and cli arguments).

If this setting is left empty there is no generating of the cert? No wizard is shown? You could instruct users to run the certificate wizard on first use.

**Comment by asheeshr** [comment]
After some further investigation, it's not too bad to use OpenSSL directly to create a self signed certificate for Mumble. For example, something like this: https://stackoverflow.com/questions/14267010/how-to-create-self-signed-ssl-certificate-for-test-purposes

**Comment by davidebeatrici** [comment]
We should probably create a wiki page.
