### ISSUE TITLE
Registration: SSL Handshake error: The certificate has expired

### ISSUE THREAD

**Issue by Stefan-comkmits** [mumble-voip/mumble#3907]
><W>2019-11-30 00:34:06.818 1 => Registration: Registration updated

><W>2019-11-30 12:20:14.271 1 => Registration: SSL Handshake error: The certificate has expired
><W>2019-11-30 12:20:14.271 1 => Registration failed: SSL handshake failed

> <W>2019-12-01 18:17:33.135 1 => Registration: SSL Handshake error: The certificate has expired
> <W>2019-12-01 18:17:33.135 1 => Registration failed: SSL handshake failed
> <W>2019-12-01 19:20:45.130 1 => Registration: SSL Handshake error: The certificate has expired
> <W>2019-12-01 19:20:45.130 1 => Registration failed: SSL handshake failed
> 

What certificate has expired?
Is there a Problem with the Auth Server,or is it on my Side?

Or what is Mean?

**Comment by davidebeatrici** [comment]
The Let's Encrypt certificate for https://publist-registration.mumble.info failed to renew automatically.

**Comment by davidebeatrici** [comment]
Fixed, we had to wait because we accidentally triggered Let's Encrypt's rate limiter.

The issue was that the renewal script didn't detect the correct web root, it used the same one as https://mumble.info.
