### ISSUE TITLE
Mumble breaks Bluetooth Driver when using Wireless headset

### ISSUE THREAD

**Issue by racabu** [mumble-voip/mumble#3910]
I really have no idea on how to correct this. I already tried several things and nothing seems to work.
If I use my wireless headset (using bluetooth)... as soon as I open Mumble and try to change settings to use the headset, mumble freezes, headset gets disconnected and Bluetooth driver stops working.
To make the Bluetooth to work again takes a lot of effort... sometimes requires reinstalls.

https://pastebin.com/gvG7Btue

Any ideas?

**Comment by davidebeatrici** [comment]
Operating system?

**Comment by racabu** [comment]
Windows 10 home

**Comment by racabu** [comment]
https://imgur.com/a/8u2JFDo

**Comment by davidebeatrici** [comment]
> To make the Bluetooth to work again takes a lot of effort... sometimes requires reinstalls.

Does disabling and then enabling the device again or restarting Windows have any effect?

**Comment by racabu** [comment]
Tried the following:
Disable, Enable - Seems good but bluetooth not enabled.
Restart computer - Driver shows again the error message.
I dont see any way other than reinstalling.
But the biggest problem is how to make Mumble work with the Bluetooth and Wireless headset. Why breaks evreything.

**Comment by davidebeatrici** [comment]
According to the log, the audio system keeps being restarted.

```
<W>2019-12-04 22:08:23.889 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2019-12-04 22:08:23.889 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
<W>2019-12-04 22:08:31.685 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2019-12-04 22:08:31.686 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
<W>2019-12-04 22:09:03.167 QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
<D>2019-12-04 22:09:03.168 OverlayClient: Failed to cleanly disconnect:  "Unknown error"
```

@Kissaki Related to the overlay, we should take a look.

```
<W>2019-12-04 22:23:48.974 WASAPIOutput: Driver says no to 2 channel output. Closest format: 1 channels @ 8000 kHz
```

"kHz" is wrong, it should be "Hz". From https://docs.microsoft.com/en-us/windows/win32/wmdm/-waveformatex:

> **nSamplesPerSec**
>
> Sample rate, in samples per second (Hertz), at which each channel must be played or recorded. Common values for **nSamplesPerSec** are 8.0 kilohertz (kHz), 11.025 kHz, 22.05 kHz, and 44.1 kHz.

Fortunately it's just a cosmetic issue:
https://github.com/mumble-voip/mumble/blob/fc02822fb32b796bd138dd055a048e53da39e23e/src/mumble/WASAPI.cpp#L883-L969

> <W>2019-12-04 22:09:52.936 QMutex: destroying locked mutex

That's bad.

Unfortunately there are no debug messages indicating why the audio system (input + output) is being restarted, aside from:

```
<W>2019-12-04 22:22:43.974 WASAPINotificationClient: Device state changed newState= 1 device= "{0.0.0.00000000}.{65b30ff8-438b-4269-9b31-3faaf576b944}"
<W>2019-12-04 22:22:43.974 WASAPINotificationClient: Default device changed flow= 0 role= 2 device "{0.0.0.00000000}.{65b30ff8-438b-4269-9b31-3faaf576b944}"
<W>2019-12-04 22:22:43.974 WASAPINotificationClient: Triggering audio reset
<W>2019-12-04 22:22:43.974 MainWindow: Start audio reset
```

I see it only happened the second time you run Mumble, did you change the audio settings or reconnected the Bluetooth headset while it was running?

**Comment by racabu** [comment]
I was using a wired headset. Then I decided to try the Wireless Headset (second time).

**Comment by davidebeatrici** [comment]
Oh, I see.

Is Mumble working as expected with the wired headset?

**Comment by racabu** [comment]
I can reproduce it anytime you want. So let me know how to produce as much as log as you need.
I uploaded the last 12 hours of Windows Event Viewer.

[Error System Messages.zip](https://github.com/mumble-voip/mumble/files/3925425/Error.System.Messages.zip)

**Comment by racabu** [comment]
> Oh, I see.
> 
> Is Mumble working as expected with the wired headset?

Yes, it does. The problem is only related to the Bluetooth Wireless one.

**Comment by Kissaki** [comment]
> Related to the overlay, we should take a look.

So with the Overlay disabled entirely, and Mumble restarted, does the issue occur?

I would also suggest increasing the Jitter-Buffer in the Audio Output settings. We had users report issues with USB headsets and their drivers faulty handling of it breaking in some way.

**Comment by adagari** [comment]
Just to add to the discussion, I have been having issues trying to get a Bluetooth headset work when using Mumble and playing games on Windows 10. Sound in Windows would work find with the Bluetooth headset, but once I started Mumble all sound would stop. The sound options under control panel would still indicate sounds was occurring. 

After tinkering with different settings the one that resolved the issue for me was, in Mumble: 
Audio Input -> Device -> Microphone (Realtek Audio)
Audio Output -> Device -> Default Device

It seems setting Mumble to use the onboard microphone resolves this issue, at least for me. Setting the input device to the Bluetooth headset does indeed break the audio on my system.

My question would be, if you just change the input device does Mumble still misbehave?

**Comment by Krzmbrzl** [comment]
As there hasn't been a response to the posted questions, I'll close this issue.
