### ISSUE TITLE
Setting superuser password with mumble-server user fails silently

### ISSUE THREAD

**Issue by nekatak** [mumble-voip/mumble#3912]
The documentation says setting superuser password Debian systems like: 
```
sudo -i murmurd -ini /etc/mumble-server.ini -supw <password> [srv]
```
but attempting to set it up with a different user like `mumble-server` shows same output (as when run successfully as root user) but the password is not set. Output of the command:
```
root:~# sudo -u mumble-server murmurd -ini /etc/mumble-server.ini -supw password
<W>2019-12-05 12:33:32.768 SSL: OpenSSL version is 'OpenSSL 1.1.1d  10 Sep 2019'
<W>2019-12-05 12:33:32.768 Initializing settings from /var/lib/mumble-server/.murmurd/murmur.ini (basepath /var/lib/mumble-server/.murmurd)
<W>2019-12-05 12:33:33.063 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2019-12-05 12:33:33.097 ServerDB: Opened SQLite database /var/lib/mumble-server/murmur.sqlite
<W>2019-12-05 12:33:33.097 ServerDB: Using SQLite's default rollback journal.
<F>2019-12-05 12:33:33.190 Superuser password set on server 1
```
This is happening on Debian 10 installation with package mumble-server installed.

**Comment by Kissaki** [comment]
From the log you posted the significant line here that shows the issue is

> <W>2019-12-05 12:33:32.768 Initializing settings from /var/lib/mumble-server/.murmurd/murmur.ini (basepath /var/lib/mumble-server/.murmurd)

As you can see it does not use the configuration file in `/etc/mumble-server.ini` that you provided as an argument but `/var/lib/mumble-server/.murmurd/murmur.ini`.

Obviously it should throw an error here IMO if it can not read the provided path. But looks like it just falls back to a default path.

**Comment by nekatak** [comment]
My bad. Indeed this issue doesn't exist! I had messed up file permissions in /etc/mumble-server.ini and copy pasted wrong output from a command I wasnt passing the -ini parameter. Thank you for your help!
