### ISSUE TITLE
New crypto discussion

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3918]
We're currently using AES-128-OCB as cipher for the UDP channel (the TCP channel uses TLS, handled by Qt).

While there aren't known security issues, we believe it's time to switch to a better cipher.

We initially planned to switch from OCB to OCB3, but the patents issues would have remained.
AES-256-AEGIS, AES-256-GCM and ChaCha20-Poly1305 are the proposed alternatives.

@jedisct1 (libsodium's maintainer) recommended [AES-256-AEGIS for better performance](https://github.com/mumble-voip/crypto-benchmark/commit/3e5ec2e4ca26a786131117099178ec924d0929b9#commitcomment-36508623) and [ChaCha20-Poly1305 for better compatibility](https://github.com/mumble-voip/crypto-benchmark/commit/3e5ec2e4ca26a786131117099178ec924d0929b9#commitcomment-36511955).

Our baseline for Mumble 1.4 is Ubuntu 18.04, which provides:
- [OpenSSL](https://www.openssl.org) 1.1.1
- [libsodium](https://libsodium.org) 1.0.16
- [NSS](https://nss-crypto.org) 3.35
- [mbed TLS](https://tls.mbed.org) 2.8.0
- [wolfCrypt](https://www.wolfssl.com/products/wolfcrypt-2) 3.13.0

## Benchmarks

https://github.com/mumble-voip/crypto-benchmark is the tool we used to measure performance.

### AMD Ryzen 7-3800X
```
[NSS] AES-256-GCM took 3.267660 seconds for 1000000 iterations, 4096 bytes message
[NSS] ChaCha20-Poly1305 took 26.553126 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-GCM took 1.921156 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-OCB took 1.440563 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] ChaCha20-Poly1305 took 3.722622 seconds for 1000000 iterations, 4096 bytes message
[libsodium] AES-256-GCM took 3.553536 seconds for 1000000 iterations, 4096 bytes message
[libsodium] ChaCha20-Poly1305 took 5.054257 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] AES-256-GCM took 90.733242 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] ChaCha20-Poly1305 took 21.632958 seconds for 1000000 iterations, 4096 bytes message
```

### Intel Core i5-4690
```
[NSS] AES-256-GCM took 4.752897 seconds for 1000000 iterations, 4096 bytes message
[NSS] ChaCha20-Poly1305 took 30.735785 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-GCM took 2.975262 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-OCB took 2.436486 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] ChaCha20-Poly1305 took 4.410388 seconds for 1000000 iterations, 4096 bytes message
[libsodium] AES-256-GCM took 5.262651 seconds for 1000000 iterations, 4096 bytes message
[libsodium] ChaCha20-Poly1305 took 6.276619 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] AES-256-GCM took 129.391199 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] ChaCha20-Poly1305 took 28.194343 seconds for 1000000 iterations, 4096 bytes message
```

### AMD FX-6300
```
[NSS] AES-256-GCM took 8.369304 seconds for 1000000 iterations, 4096 bytes message
[NSS] ChaCha20-Poly1305 took 47.978501 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-GCM took 5.444225 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-OCB took 3.194741 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] ChaCha20-Poly1305 took 7.658956 seconds for 1000000 iterations, 4096 bytes message
[libsodium] AES-256-GCM took 7.680904 seconds for 1000000 iterations, 4096 bytes message
[libsodium] ChaCha20-Poly1305 took 13.378307 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] AES-256-GCM took 223.153596 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] ChaCha20-Poly1305 took 41.273524 seconds for 1000000 iterations, 4096 bytes message
```

### x86_64 CPU on Travis CI
```
[NSS] AES-256-GCM took 4.078755 seconds for 1000000 iterations, 4096 bytes message
[NSS] ChaCha20-Poly1305 took 15.603647 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-GCM took 2.390765 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-OCB took 2.436504 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] ChaCha20-Poly1305 took 4.282076 seconds for 1000000 iterations, 4096 bytes message
[libsodium] AES-256-GCM took 4.746877 seconds for 1000000 iterations, 4096 bytes message
[libsodium] ChaCha20-Poly1305 took 7.879056 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] AES-256-GCM took 125.962188 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] ChaCha20-Poly1305 took 27.405068 seconds for 1000000 iterations, 4096 bytes message
```

### ARM64 CPU on Travis CI
```
[NSS] AES-256-GCM took 154.621518 seconds for 1000000 iterations, 4096 bytes message
[NSS] ChaCha20-Poly1305 took 43.217945 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-GCM took 18.301692 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] AES-256-OCB took 24.131057 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] ChaCha20-Poly1305 took 29.108860 seconds for 1000000 iterations, 4096 bytes message
[libsodium] skipping AES-256-GCM benchmark due to missing requirements. SSSE3 extensions, "aesni" and "pclmul" instructions are required.
[libsodium] ChaCha20-Poly1305 took 32.916597 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] AES-256-GCM took 247.166981 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] ChaCha20-Poly1305 took 44.717989 seconds for 1000000 iterations, 4096 bytes message
```

## Thoughts

Please note that when talking about performance I'm only referring to ChaCha20-Poly1305, which is the cipher we're going to use.

### Advantages

- Permissive license (MPL 2.0).
- FIPS-140 and FIPS-140-2 validated.

### Disadvantages

- Low performance. The benchmark's code is based on the tests (https://github.com/nss-dev/nss/blob/master/gtests/pk11_gtest/pk11_aes_gcm_unittest.cc and https://github.com/nss-dev/nss/blob/master/gtests/pk11_gtest/pk11_chacha20poly1305_unittest.cc), thus the API usage should be correct.
- Scarce documentation (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference), but it seems that it's being rewritten.

### Advantages

- Permissive license (ISC).
- Good performance.
- Simple API and good documentation.

### Disadvantages

- Not FIPS-140 validated.

### Advantages

- FIPS-140 and FIPS-140-2 validated.
- Best performance, even better than OpenSSL, but only when optimizations are enabled...

### Disadvantages

- ... and they aren't by default. The official Debian and Ubuntu packages don't enable them, resulting in the very low performance shown in the benchmarks. See wolfSSL/wolfssl#2691 for further info.
- Restrictive license (GPLv2). May be problematic for a closed-source project based on Mumble.

**Comment by trudnorx** [comment]
The first question should be: When is Mumble 1.4 going to be released?

It took 10 years to go from Mumble 1.2 to Mumble 1.3. Maybe in 10 years there will be a lot better crypto technology and it's better to decide when Mumble 1.4 release is nearby. In 10 years, assuming OpenSSL is still relevant even very old Ubuntus are going to ship with a new version of it.

Is there any issue with any other OS?

I say:
Keep OpenSSL.

- Old, most widely used and tested.
- Don't have to change code much.
- Best performance.
- Who cares about some old Ubuntu version which is for sure going to be nearing EOL whenever Mumble is released?

**Comment by trudnorx** [comment]
OpenSSL changelog 1.1.0:
> Support for ChaCha20 and Poly1305 added to libcrypto and libssl.

Ubuntu 18.04 LTS has a libssl1.1 package in its repo, so it looks like it supports it to me. Just gotta install it in case it's not installed by default, what's wrong with that?

**Comment by Krzmbrzl** [comment]
Ubuntu 16.04 will have it's end of life in april 2021. So that's almost another 1,5 years.

Can't we statically link to OpenSSL and thus don't care what packages are available on the user's OS?

**Comment by davidebeatrici** [comment]
@trudnorx Mumble 1.4 is possibly going to be released in 2020.

Changing the code is not an issue, even with OpenSSL we would have to rewrite it, because we're not using the EVP interface right now.

As for the performance and testing, I agree. wolfCrypt would've been a perfect replacement if it wasn't for the optimizations issue and maybe also the license.

@Krzmbrzl That's a valid option, yes. The issue is that also Qt uses OpenSSL, meaning that we would have to link to two different versions of the same library...

**Comment by Krzmbrzl** [comment]
And Qt also links statically? Why do we need different versions then? Does Qt use a version that is too old?

**Comment by davidebeatrici** [comment]
Qt uses the version provided by the distribution (unless we link to our own Qt).

**Comment by Krzmbrzl** [comment]
Ah and I assume this would make things complicated once we start statically linking to another version of OpenSSL :bulb:

**Comment by trudnorx** [comment]
Problem with statically linking OpenSSL is that it wouldn't get security updates.

**Comment by davidebeatrici** [comment]
Indeed.

One thing we could do is write an implementation for OpenSSL and one for libsodium, using the latter only when `EVP_chacha20_poly1305()` is not available.

https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html

**Comment by trudnorx** [comment]
1. Keeping OpenSSL still sounds like the best option.

2. These benchmarks aren't really telling us much. Will it add any latency to voice communication and if so how much? In my opinion that would be unacceptable.

3. What is the problem with patents?
OCB is licensed free to use for OpenSSL and any programs using OpenSSL.
OCB is licensed free to use for any programs releasing source code and allowing free copying, modification, and re-distribution etc. of that source code.
OCB is also licensed free to use for any non-commercial and non-military software.

And as far as I understand these things are OR. So it's (uses OpenSSL) OR (free source) OR (noncommercial AND nonmilitary).

So what's the problem with just using OCB3?

4. How about keep OpenSSL but switch to DTLS with AES-256-GCM? Does this solve how it is "harder" to use without TLS? What is the problem with that? Any platforms is it incompatible with?

**Comment by Krzmbrzl** [comment]
The point about patents is that Mumble uses a BSD license which grants rights that are incompatible with those patents. Thus for people using mumble commercially, this would be a problem

**Comment by trudnorx** [comment]
> The point about patents is that Mumble uses a BSD license which grants rights that are incompatible with those patents. Thus for people using mumble commercially, this would be a problem

As far as I understand that wouldn't be a problem because the patent has a grant for programs using OpenSSL. So even if they make commercial software based on Mumble and don't release the source, there is still no patent problem.

https://web.cs.ucdavis.edu/~rogaway/ocb/license3.pdf

**Comment by Krzmbrzl** [comment]
Hm I'm far from being an lawyer but I guess you could be correct. I don't know though if this license allows OpenSSL to implement it only and does not grant further permission to the party using OpenSSL...

**Comment by davidebeatrici** [comment]
Also, OCB was introduced in OpenSSL 1.1 (https://www.openssl.org/docs/manmaster/man3/EVP_aes_256_ocb.html), meaning that the compatibility issue would remain.

> 2. These benchmarks aren't really telling us much. Will it add any latency to voice communication and if so how much vs. the current AES-128-OCB mode? In my any more latency would be unacceptable. How would it affect the average CPU usage of the program in the average situation?

Our current implementation doesn't make use of AES-NI, meaning that only the higher bits (256 instead of 128) can lower the performance.

**Comment by trudnorx** [comment]
> Hm I'm far from being an lawyer but I guess you could be correct. I don't know though if this license allows OpenSSL to implement it and does not grant further permission to the party using OpenSSL...

It allows all those permissions to the party using OpenSSL. Just read it.

**Comment by trudnorx** [comment]
Are there stats on how many people are using Ubuntu 16.04 for Mumble?
Mumble is planning on killing support for Windows XP even though lots of people use it, probably a lot more than Ubuntu 16.04.

**Comment by davidebeatrici** [comment]
> Are there stats on how many people are using Ubuntu 16.04 for Mumble?

Unfortunately not, our stats server has been offline for quite some time.

> Mumble is planning on killing support for Windows XP even though lots of people use it, probably a lot more than Ubuntu 16.04.

In the past we made patches to get some of our dependencies to work with XP, see https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.3.x/win32-static/patches.

We decided to stop doing that in 1.4 mainly because Qt dropped support for XP in 5.7, meaning that we would have to write (probably long and complex) patches for it.

> And what do you think about DTLS?

Let's ask @jedisct1.

**Comment by davidebeatrici** [comment]
@jedisct1 Could you elaborate on why AES-GCM is tricky to use correctly outside TLS, please?

**Comment by jedisct1** [comment]
AES-GCM has pretty low limits on the number of bytes and messages that can be encrypted under a single key. This requires frequent key updates. Something that the TLS protocol implements, but that has to be reimplemented in all other protocols.

The nonce is also short, requiring it to be a counter or the output of a permutation to avoid reuse. And AES-GCM fails catastrophically under nonce reuse.

See https://download.libsodium.org/doc/secret-key_cryptography/aead for a summary of the limits of common constructions including AES-GCM.

**Comment by davidebeatrici** [comment]
Thank you very much, the documentation is clear and detailed.

Ubuntu 16.04 provides libsodium 1.0.8: https://packages.ubuntu.com/xenial/libsodium18

According to https://download.libsodium.org/doc/secret-key_cryptography/aead/chacha20-poly1305/xchacha20-poly1305_construction, XChaCha20-Poly1305 was added in libsodium 1.0.12.

Is there a clean way to implement it using the ChaCha20-Poly1305 functions?

**Comment by jedisct1** [comment]
Phew, 1.0.8 is really old.

XChaCha is quite easy to implement on top of ChaCha (you'll need the `hchacha` hash function, but it's just a couple lines of code).

Do you really have to support these old distros?

**Comment by davidebeatrici** [comment]
Yes, our baseline is the oldest LTS version of Ubuntu that is still supported.

**Comment by QmFzZTY0IGlzIGEgZW5jb25kaW5nI** [comment]
Please use openSSL and AES-NI, this will increase performance.

**Comment by davidebeatrici** [comment]
Also using ChaCha20-Poly1305 would probably increase performance, because our current AES-OCB implementation doesn't make use of AES-NI.

**Comment by jedisct1** [comment]
If performance is the primary issue, use AEGIS. There is a small standalone implementation here: https://github.com/angt/aegis256

**Comment by toby63** [comment]
Regarding your problem with backwards compatability; what about [backports-repos](https://wiki.ubuntu.com/UbuntuBackports)?
These are of course a matter of the distributions, but it would be possible to provide newer versions of e.g. openssl (as far as I see openssl only has a dependency for libc6 and build-dependencies for m4 and bc (according to debian control), so it should be possible).   
There already exists a bug report/feature request for the backport of openssl 1.1.0 for xenial (16.04)([link](https://bugs.launchpad.net/xenial-backports/+bug/1785412)).
If people want to use mumble, they should then use the backports.   
Imo a fair compromise.

**Comment by streaps** [comment]
Ubuntu 16.04 EOL is in one year. When will the new crypto implemented, when will there be a release? Who are the users that are still running 16.04, but think Mumble/Murmur 1.3 is not good enough for the next couple of months?

EOL in a year means users should think about upgrading soon, like in a couple of months.

**Comment by toby63** [comment]
In addition to @streaps comment: 
The package of mumble from the xenial ubuntu repo is extremly old (1.2.12-1ubuntu1), see here:
https://packages.ubuntu.com/xenial/mumble
Last change from 08 Jan 2016 [see changelog](http://changelogs.ubuntu.com/changelogs/pool/universe/m/mumble/mumble_1.2.12-1ubuntu1/changelog).

**Comment by jtl999** [comment]
I think holding back improvements to Mumble because of old Ubuntu versions is the wrong approach in my opinion, and I agree with @streaps. As we get closer to 2021 this particular issue loses relevance, but I still think it's an interesting academic exercise to plan for the future and how to deal with whatever legacy challenges happen then.

Would providing statically linked binaries as a compromise for older operating systems be out of the picture?

**Comment by davidebeatrici** [comment]
Of course not.

However, now that Ubuntu 20.04 is out we'll probably use 18.04 as baseline.

**Comment by Krzmbrzl** [comment]
The discussion about how backwards compatible we should be is outsourced in #4080

**Comment by toby63** [comment]
To get back to the topic:
Even though using openssl 1.1.1 should be no problem anymore.
The overall question whether you want to choose a different crypto-software remains.
I want to add:
* questions:
    * How fast is openssl with AES-NI?
 
* factors to consider:
    * **Security:** Always very important.
        * For example: Do external security audits exist for wolfssl and libsodium? (for openssl there are security audits)
    * **Update frequency:** Though it is a debate whether updates just show how insecure a software is; still updates are a security factor:
        * **openssl:** As far as I can see openssl updates very often ([github releases page](https://github.com/openssl/openssl/releases)), also in distros (see [debian for example](https://tracker.debian.org/pkg/openssl)).
        * **wolfssl:** wolfssl is not updated as frequently as openssl ([github releases page](https://github.com/wolfSSL/wolfssl/releases))
        * **libsodium:** Does not update very often ([github releases](https://github.com/jedisct1/libsodium/releases))

* Regarding the additional options for wolfssl (for speed-up):
    * You could ask the package maintainers to activate the options (@davidebeatrici already asked the debian maintainer ([see here](https://github.com/wolfSSL/wolfssl/issues/2691#issuecomment-616834705)))

**Comment by Avatat** [comment]
[libsodium/master](https://github.com/jedisct1/libsodium), under i5-8250U:
```
[libsodium] AES-256-GCM took 4.678773 seconds for 1000000 iterations, 4096 bytes message
[libsodium] ChaCha20-Poly1305 took 6.351432 seconds for 1000000 iterations, 4096 bytes message
[libsodium] AEGIS-256 took 2.491907 seconds for 1000000 iterations, 4096 bytes message
```
I will add more info and create a pull request to [the benchmark](https://github.com/mumble-voip/crypto-benchmark) repository in the next few days :)

**Comment by Avatat** [comment]
@davidebeatrici and I, we added a lot of changes to Mumble's crypto-benchmark: https://github.com/mumble-voip/crypto-benchmark/commits/master

- libhydrogen has been disabled by default, because it's slow, and has additional requirements
- all code was rewritten to use generic "crypto" interface
- AEGIS-256 algorithm, implemented by libsodium, was added
- progress status was added, to inform about long-running benchmark

Results after running crypto-benchmark on i5-8250U:
```
[NSS] running AES-256-GCM benchmark...
[NSS] 4.003431 seconds for 1000000 iterations, 4096 bytes message
[NSS] running ChaCha20-Poly1305 benchmark...
[NSS] 32.628630 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] running AES-256-GCM benchmark...
[OpenSSL] 2.421589 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] running AES-256-OCB benchmark...
[OpenSSL] 2.458133 seconds for 1000000 iterations, 4096 bytes message
[OpenSSL] running ChaCha20-Poly1305 benchmark...
[OpenSSL] 4.486307 seconds for 1000000 iterations, 4096 bytes message
[libsodium] running AEGIS-256 benchmark...
[libsodium] 1.167790 seconds for 1000000 iterations, 4096 bytes message
[libsodium] running AES-256-GCM benchmark...
[libsodium] 4.644368 seconds for 1000000 iterations, 4096 bytes message
[libsodium] running ChaCha20-Poly1305 benchmark...
[libsodium] 5.799480 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] running AES-256-GCM benchmark...
[wolfCrypt] 122.228198 seconds for 1000000 iterations, 4096 bytes message
[wolfCrypt] running ChaCha20-Poly1305 benchmark...
[wolfCrypt] 29.561420 seconds for 1000000 iterations, 4096 bytes message
```
It's worth to mention, that OpenSSL has the fastest AES-256-GCM, because its uses "restricted" instructions from Intel: https://github.com/jedisct1/libsodium/issues/388

**Comment by dstensnes** [comment]
Just out of curiosity: Should mobile phones and tablets be taken into consideration, for future proofing the protocol?

**Comment by jtl999** [comment]
Doing benchmarks on mobile ARM platforms can't hurt. Third party Mumble clients for mobile exist.

**Comment by davidebeatrici** [comment]
Yes, we already do that.

**Comment by fedetft** [comment]
Not to drive the discussion off topic, but have you considered implementing end to end encryption?

I don't know how the protocol part works, so I don't know how hard it could be, but it could be a bigger improvement than just updating from OCB to something else.

**Comment by toby63** [comment]
>  implementing end to end encryption

See also #1813 
Would also be useful for #2560

**Comment by mymindstorm** [comment]
Adding on to phone support, I've been researching implementing the mumble protocol on Android, as the only client is unmaintained. It would be nice to use an algorithm that is natively supported by Android. [Here's the list of supported ciphers](https://developer.android.com/guide/topics/security/cryptography#SupportedCipher). The Android docs discourage frequent calls to native code because there is some performance overhead.

**Comment by jtl999** [comment]
@mymindstorm There is a maintained fork of [Plumble](https://f-droid.org/en/packages/se.lublin.mumla/) but I haven't tested it in depth

**Comment by fedetft** [comment]
That can be solved if the Mumble desktop app is split making a common core that runs also on the mobile.

Having a native core handling the audio stuff would also enable echo cancellation instead of echo suppression in mobile apps.

**Comment by TerryGeng** [comment]
I do hope we can update our cipher soon since currently the progress of having UDP support in pymumble stalled, just because there isn't any usable library for OCB2.

**Comment by streaps** [comment]
@TerryGeng I had the exact same problem yesterday. Have you tried this implementation:

https://github.com/mumble-voip/mumble/issues/3487#issuecomment-597856562

**Comment by TerryGeng** [comment]
@streaps In my implementation, I used a python library called pyOCB, which is a _pure python_ implementation of OCB2. I tested it, it works, but it ate up all my CPU while only transmitted intermittent audio data. 

I checked some other python library that used a C backend https://github.com/Legrandin/pycryptodome but it only supports OCB3.

**Comment by streaps** [comment]
If we already use TLS for the TCP stream, why not just use QUIC for messaging and audio? This would also give us a more stable connection for mobile clients.

**Comment by streaps** [comment]
Could OCB-AES128 (as in RFC 7253) be added to the benchmarks?

**Comment by TerryGeng** [comment]
Ok. Based on the discussion in #4219, as long as we don't drop the old OCB2 support, I think we can add all kinds of encryption methods we want. We can make a list of methods we'd like to use, and just check they are available when compiling. The cipher negotiation process has already been outlined in #4219, and I think the problem now is to nail down what ciphers we are going to adapt. So I get back to this issue.

According to my understanding, I think maybe we are going to end up with libsodium.
Cipher candidates are OCB3, ChaCha, and anything else?

I'm not really an expert in getting libraries working in a project. I guess I need the help from @davidebeatrici to help me add them into the project then I can start my attempts immediately.

**Comment by streaps** [comment]
Comments regarding the benchmark:

Why is the message size 4096 bytes? IIRC the UDP audio packets from Mumble are not bigger than ~1024 bytes. I'm not sure what the average message size for an audio packet. 

Would separate numbers for encoding and decoding be helpful?

Is there a difference in overhead (packet size)?

What about 32-bit performance (Raspberry, embedded stuff)?

**Comment by Avatat** [comment]
> According to my understanding, I think maybe we are going to end up with libsodium.
> Cipher candidates are OCB3, ChaCha, and anything else?

Here you can find a comparison table with libraries/ciphers: https://github.com/Avatat/sandbox/blob/master/project_work/topic.md#comparison-table
As I wrote there, OCB is patented mode and probably we don't want to use it. If we want to stick with AES, AES-GCM will be my choice. If we want to try development-version of libsodium, we should definitely go with AEGIS, because it's much faster. We should also consider a cipher for no-accelerated (AES-NI or ARM NEON) environments - my choice would be ChaCha.

> I'm not really an expert in getting libraries working in a project. I guess I need the help from @davidebeatrici to help me add them into the project then I can start my attempts immediately.

Currently, I declared that I will implement the new crypto in Mumble, with @davidebeatrici help. I also made it as a topic of my B.Eng work at University, but my supervisor cut the topic to benchmark only. I'm also not a developer, but I wanted to learn how to write good code by this issue :)
If you are feel good with this task, feel free to take it. I will have to find something different, when I end crypto-benchmark tasks :)

> Why is the message size 4096 bytes? IIRC the UDP audio packets from Mumble are not bigger than ~1024 bytes (and MTU =< 1500). I'm not sure what the average message size for an audio packet is.

I agree that we should do benchmark using smaller message sizes. I will check what size of packets Mumble uses, and prepare a change to the benchmark.

> Would separate numbers for encoding and decoding be helpful?

Can you say something more about it?

> What about 32-bit performance (Raspberry, embedded stuff)?

I can have some RPis to do the benchmark on them. AEGIS from libsodium works really fast on ARM platforms with NEON support. What embedded stuff do you mean?

**Comment by TredwellGit** [comment]
@Avatat Did you see [my comment about DTLS](https://github.com/mumble-voip/mumble/issues/4219#issuecomment-636151948)?

**Comment by davidebeatrici** [comment]
AEGIS seems to be the best choice at the moment.

@jedisct1 I see [libhydrogen](https://github.com/jedisct1/libhydrogen) has a CMake project.
Do you perhaps have any plans to add one for [libsodium](https://github.com/jedisct1/libsodium) as well? It would allow us to add the library as submodule.

**Comment by Avatat** [comment]
@jedisct1, oh wow! Thank you for adding AEGIS-128L to libsodium! I even asked for it: https://github.com/jedisct1/libsodium/issues/951 :)

**Comment by streaps** [comment]
> > Would separate numbers for encoding and decoding be helpful?
>
> Can you say something more about it?

Nevermiind. For some reason I thought encryption and decryption could differ in speed and should be benchmarked separately.  It's called "**symmetric** key encryption" not "compression algorithm", dummy ;) (talking to myself).
 
> > What about 32-bit performance (Raspberry, embedded stuff)?
> 
> I can have some RPis to do the benchmark on them. AEGIS from libsodium works really fast on ARM platforms with NEON support.

Even my slow Raspberry Pi does have NEON support :).

**Comment by TredwellGit** [comment]
The benchmarks posted here use 1000000 iterations. Will actual implementation will use 1 iteration?

**Comment by Avatat** [comment]
For the Mumble implementation we will use single iteration.

**Comment by davidebeatrici** [comment]
We use so many iterations just to easily understand the performance difference between the various ciphers and libraries.

**Comment by TerryGeng** [comment]
@Avatat Oh sorry I didn't know this task is already taken by you. The reason I'm pushing this is other 3rd mumble libraries like pymumble have been stuck at cipher thing for a while....
It's good to know that you are going to takle this. Thanks! 

As for the cipher negotiation when establishing connections, I'm not sure what's your opinion on it. If you are not really keen at it, I think I can help, so you can better concentrate on integrating ciphers to the codebase if you'd like :)

**Comment by TredwellGit** [comment]
For one iteration in the [latest benchmark posted](https://github.com/mumble-voip/mumble/issues/3918#issuecomment-624954631) there is a difference of .0012538 milliseconds between AES_256_GCM and AEGIS-256. For reference, my ping (measured in Mumble) to a Mumble server on an Ethernet network is around .5 milliseconds.

This is a very small difference and I have worries about how AEGIS will be implemented compared to DTLS. For example, has it been considered what will happen when a vulnerability is discovered in AEGIS and Mumble needs to move away from it? Right now, the voice channel in Mumble has no cryptographic agility and moving away from the vulnerable OCB2 crypto is difficult. Meanwhile, the control channel which uses TLS can easily switch cryptographic algorithms and parameters if some are proven insecure. DTLS is similar and would allow easy switching when necessary. Using DTLS also allows for less custom cryptographic code to be written and can be implemented with libraries that Mumble supports right now like Qt and OpenSSL.

>As for the cipher negotiation when establishing connections, I'm not sure what's your opinion on it. If you are not really keen at it, I think I can help, so you can better concentrate on integrating ciphers to the codebase if you'd like :)

Using DTLS would solve this without any work.

**Comment by TredwellGit** [comment]
See https://doc.qt.io/qt-5/qdtls.html#details, https://doc.qt.io/qt-5/qtnetwork-secureudpserver-example.html, and https://doc.qt.io/qt-5/qtnetwork-secureudpclient-example.html.

**Comment by jedisct1** [comment]
DTLS is quite inefficient, handles packet loss pretty badly and multiple vulnerabilities have been found in its implementations, mainly because it’s not used much and doesn’t get much attention.

As a full-fledged UDP-based protocol, QUIC would probably be a better choice nowadays.

**Comment by streaps** [comment]
I also doubt we are better off with DTLS. It's a lot of complexity and added overhead.

DTLS is still at version 1.2. It looks like the RFC will be releases soon, but when will it be supported on all Mumble platforms?

**Comment by streaps** [comment]
It looks like Grumble already has some support for multiple crypto modes:

https://github.com/mumble-voip/grumble/blob/7bb6dbcfb4d0fab51eb7b67553fcc2b50598d42e/cmd/grumble/client.go#L566

**Comment by TerryGeng** [comment]
@streaps Yes. It seems that Grumble assumes there's an extra field in Version message called CryptoModes. However, I cannot locate this field in our mumble.proto.

But anyway, I think it is also a good idea to add this CryptoModes to the Version message. I'll see what I can do.

**Comment by streaps** [comment]
I don't know if any client is using Grumble's unofficial implementation. If there is a better way to do it, it's not to late to change it.

From reading Mumble.proto it is not clear to me, if there is a recommended way of negotiating capabilites.
- supported codecs are announced in the Authenticate (?!) packet
- CodecVersion packet sent back from the server
- max bandwith is in ServerSync
- other stuff in ServerConfig
- CryptoMode in the Version packet?

Maybe we should define the intented behaviour for the crypto negotiation first.

Is it only about the codec? Maybe the AudioTransport should be negotiated instead? There is already feature request for WebRTC support in the server and a web client that uses WebRTC (via a webrtc proxy). A future version could also offer QUIC AudioTransport (very useful for future web clients).

**Comment by Krzmbrzl** [comment]
> From reading Mumble.proto it is not clear to me, if there is a recommended way of negotiating capabilites.

Afaik there is not

> Is it only about the cipher? Maybe the AudioTransport should be negotiated instead (which could imply the cipher or another method of negotiation like TLS)?

That way you'd still be stuck on a specific cipher for a given transport protocol. If you need to change the cipher (because it is deemed un-secure), you'd be out of luck.
Instead I think the audio transport protocol negotiation could be added in addition to the cipher negotiation.

Imo that belongs into a separate issue though :point_up:

**Comment by streaps** [comment]
> That way you'd still be stuck on a specific cipher for a given transport protocol

You just negotiate a name that defines the transport **and** the name, like:

udp-aes128-ocb
udp-chacha20-poly1305
udp-aegis-256
webrtc
quic

**Comment by TerryGeng** [comment]
@streaps I'm tracing the `opus` flag inside Authenticate message.

It looks like only few places referred to this field.
Set:
1. murmur/Server.cpp, inside `Server::recheckCodecVersions`, tell clients the codecs the server supported. Interestingly, I believe the server doesn't decode audio packets.
1. mumble/ServerHandler.cpp, inside `ServerHandler::serverConnectionConnected`, tell the server if the client support Opus. But there's already a flag doing the same thing inside CodecVersion. 

Read:
1. murmur/Message.cpp, inside `Server::msgAuthenticate`, set a flag to indicate the user support opus. But this field seems to be not very useful since codec information is included in voice packets.

Therefore, I believe it can be deleted without much to worry about.

What bothers me is
https://github.com/mumble-voip/mumble/blob/e6f988304aaee20d12bbbec53ce8ec0e655d413b/src/murmur/Server.cpp#L2020-L2021
I think this part is certainly deprecated and need to be removed in the next version.

Also, I discovered there're also many places in our proto has Opus field. Like UserStats and CodecVersion. I think we only need to keep the one inside CodecVersion. Other duplicated Opus fields should be removed.

I will open another issue regarding this.

**Comment by TerryGeng** [comment]
@streaps However, UDP ping packets is also encrypted, so it does not entirely belong to audio.

**Comment by streaps** [comment]
@TerryGeng,
the UDP ping packet is only relevant if UDP is used for audio. It's part of the UDP audio transport.

CryptoModes is a bad name as it suggest a "mode of operation" in crypto speak (IMO). I also feel that CryptoModes in the Version packet is the equivalent of "celt_versions" and "opus" fields the in Authenticate packet. More like a patchwork of stuff lacking any deliberate design.

**Comment by yuhong** [comment]
Keep in mind that OCB patents are about to expire as well.

**Comment by streaps** [comment]
There are no real problems with the OCB patents anyway. It's only FUD (yes, some libre software fanatics can spread that too).

**Comment by Krzmbrzl** [comment]
> There are no real problems with the OCB patents anyway. It's only FUD (yes, some libre software fanatics can spread that too).

According to https://en.wikipedia.org/wiki/OCB_mode#Patents it is only allowed to use OCB in software licensed under GPL (which Mumble is not) or in a non-commercial setting. There's the problem: Right now it is currently not possible to legally use Mumble commercially without fiddling with those patents.
That's at least how I understand it :shrug:

**Comment by streaps** [comment]
According to the same Wikipedia page:
"By January 2013, the author has granted a free license for **any open source license** certified by the Open Source Initiative."

and according to the linked license page:
"License 2 — General License for Non-Military Software Implementations OCB (Jan 10, 2013).
This license does not authorize any military use of OCB. Aside from military uses, you are authorized to make, use, and distribute (1) any software implementation of OCB"

also:
"License 3 — Patent License for OpenSSL (Nov 13, 2013).
This license was provided at the request of the OpenSSL Software Foundation to specifically authorize use of OCB in OpenSSL."

https://www.cs.ucdavis.edu/~rogaway/ocb/license.htm

**Comment by elch01** [comment]
Why not LibreSSL?

**Comment by ZeroAbility** [comment]
> Why not LibreSSL?

It appears to be in vcpkg:

https://github.com/microsoft/vcpkg/tree/master/ports/libressl

If their licensing is compatible it might be worth a discussion.

**Comment by thorvald** [comment]
To provide a bit of historical context: When we first implemented the crypt layer, we reached out to the inventor of OCB about the licensing. As a result, Mumble has an explicit permission, direct from the inventor, to include OCB under BSD (as well as GPL) on a royalty-free basis.

**Comment by andreygursky** [comment]
> > Why not LibreSSL?
> 
> It appears to be in vcpkg: ...

But it is missing in Debian GNU/Linux and perhaps all derivatives.
