### ISSUE TITLE
Doesn't work when selecting "use echo cancellation“ on Windows 10

### ISSUE THREAD

**Issue by johnnyzh86** [mumble-voip/mumble#3923]
Doesn't work when selecting "use echo cancellation“  on Windows 10 1803,have to uncheck the option going through audio wizard.if i check the checkbox,my voice is not going through,also 90% of the time i can only use signal to ratio,raw amplitude from input is not working also,anyone have a fix? this happens on both 1.2 and 1.3

**Comment by davidebeatrici** [comment]
Audio card and microphone?

**Comment by johnnyzh86** [comment]
Integrated audiocard on Intel Z370 in Alienware R8，the microphone is the one on AW988

**Comment by johnnyzh86** [comment]
@davidebeatrici 

Integrated audiocard on Intel Z370 in Alienware R8，the microphone is the one on AW988

**Comment by davidebeatrici** [comment]
I see they can be connected through USB. Is it just for power or audio as well?

**Comment by johnnyzh86** [comment]
@davidebeatrici 
Thanks,it happens on both wireless and wired mode,is it a compatibility issue? if i use signal to ratio in a very noisy environment,there will be a lot of squeal and echo going on

**Comment by davidebeatrici** [comment]
You're using WASAPI, right?

**Comment by johnnyzh86** [comment]
@davidebeatrici  yes it looks like that,the input and output have different names,if i want to use different input output,i have to uncheck echo checkbox and select signal to noise ratio,or it won't work

**Comment by davidebeatrici** [comment]
The fact that you have to select "signal to noise ratio" is a different issue though.

What happens when you select "Amplitude"? You don't see any input?

**Comment by johnnyzh86** [comment]
@davidebeatrici  okay..yeah,no input

**Comment by davidebeatrici** [comment]
Is the sound clean when using "signal to noise ratio"?

**Comment by johnnyzh86** [comment]
@davidebeatrici not at all,no matter how to config,the signal is really easy to get pass the gate,generates a lot of squeal

**Comment by Krzmbrzl** [comment]
We just received a patch for the echo canceller. It turned out that our implementation was buggy (see #4167 for details).

Thus it might very well be that the issues you have encountered are due to that.

Please let us know if the problem persists with Mumble 1.4.0 or newer (not released yet though - but you can get it if you compile the current master branch)
