### ISSUE TITLE
Mumble doesn't close properly after restart

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3930]
When I open Mumble, select another theme in the settings and let Mumble perform the requested restart, it doesn't close properly when closed via UI (the x-button in the top-right corner).
The UI disappears, but the console doesn't return indicating, that something remains running.

From my tests, this does not correspond to the specific theme (that is being switched to or that is being used). Instead I suspect, that this is a bug in the restart-logic. If there's another way to let Mumble restart itself, I think we could very that suspicion.

EDIT: Forgot to mention that I am using the (as of this moment) latest master-branch build (2575d301fa1528cf1d38c003675e8b960bc19f68) and am running Mumble on Linux (KDE Neon - Kernel: 5.0.0-37-generic)

**Comment by Krzmbrzl** [comment]
It seems as if something is reading stdin. Mumble properly shuts down after pressing enter in the console (before that I am able to type in some text)...

**Comment by Kissaki** [comment]
If you agree to the restart of Mumble it should do so automatically. No need for pressing the x button. At least that is the behaviour on Windows. (Is this different on Linux/KDE?)

**Comment by Krzmbrzl** [comment]
Ah no, that's not what I meant. The restart happens automatically just fine. It's when losing the restarted instance that this problem occurs

**Comment by Krzmbrzl** [comment]
Turns out this is not Mumble not closing properly but rather my terminal having shown the command prompt again at the time Mumble restarts. The output of it pushes the command prompt to the top and off the screen giving the illusion the terminal hasn't returned yet.
Using `top` I can confirm though that Mumble has shut down properly.
