### ISSUE TITLE
Getting rid of raw pointers, Qt pointers vs STD (C++11) pointers

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3937]
#3650 proposed to replace raw pointers with either [`std::unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr) or [`QScopedPointer`](https://doc.qt.io/qt-5/qscopedpointer.html) in `BonjourClient` and `OverlayClient`, #3660 accomplished the task using [`QScopedPointer`](https://doc.qt.io/qt-5/qscopedpointer.html).

We should do the same everywhere, especially in `AudioInput` and `AudioOutputSpeech`.

The baseline for 1.3 was C++03. We raised it to C++11 for 1.4, meaning that we can use STD pointers.

Our code is currently a mix of raw, Qt and Boost pointers. Ideally we should use a single (non-raw) type.

`JackAudio` and `PortAudio` have been recently revamped (#3826 and #3889, respectively) and they now use [`std::unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr). It was chosen over [`QScopedArrayPointer`](https://doc.qt.io/qt-5/qscopedarraypointer.html) in `JackAudio` because it required a type cast: [`QScopedArrayPointer::operator[]`](https://doc.qt.io/qt-5/qscopedarraypointer.html#operator-5b-5d) takes a signed integer. I decided to do the same in `PortAudio` for consistency.

I personally would use the standard pointers, but I would like to hear other opinions before making a final choice.

**Comment by Krzmbrzl** [comment]
As we are using Qt for almost everything else, I would tend to use qt pointers whenever appropriate (and I think the available pointer classes should suffice for all our needs).

One needs to test though, if they allow assignment of nullptr. In my plugin framework PR, I encountered a problem in which I got a compiler error when doing that. I'm not sure though whether that was a compiler bug or if it's Qt's fault...

**Comment by davidebeatrici** [comment]
Why not use [`QScopedPointer::reset()`](https://doc.qt.io/qt-5/qscopedpointer.html#reset)?

**Comment by Krzmbrzl** [comment]
Because I didn't know that function exists xD

That being said though, I think it is more expressive to directly assign nullptr. That way, I don't have to know, what reset does. I look at the code and see, that the pointer will be null afterwards. But maybe that's just me ^^

**Comment by davidebeatrici** [comment]
No, you're right.

Smart/automatic pointers are supposed to take the place of raw pointers without requiring any other changes in the code (aside from removing all instances of `delete`, of course).

At this point I think using standard pointers is the best choice, what do you think?

**Comment by Krzmbrzl** [comment]
Yeah - Plus they probably have the advantage that people are more familiar with them than they'd be with the qt pointers.

**Comment by davidebeatrici** [comment]
I agree.

**Comment by davidebeatrici** [comment]
From IRC:

> `<phobos4711>` +1 for std pointers, every C++ programmer needs to know them in modern C++

**Comment by McKayJT** [comment]
I know that in my rework on gRPC that I've extensively used STL pointers/containers over the QT stuff as it just wasn't working properly, QQueue for example doesn't support move only objects at all.

I also may be a bit biased as I did spent a lot of time working to avoid installing a 60mb+ Qt-base package (not including the X11 stuff it tried to pull in as dependencies) just to run murmur on a space limited VPS.

**Comment by davidebeatrici** [comment]
We are going to use STL pointers, thank you all for your input!
