### ISSUE TITLE
murmur can't be registered to public list

### ISSUE THREAD

**Issue by KruegerDead** [mumble-voip/mumble#3940]
Hello. I have a domain name in .CF zone, trying to set server as public, but get error in logs!

> <W>2020-01-14 08:09:17.800 1 => Registration: DNS name callback mydomain.cf=>'my ip' failed: Source-based callback failed. Server not reachable.

Server works fine, but not showing in a public list.

Is it problem with murmur or server registration API? Would be great if this have been fixed. Thanks

add: If this is important, the server starts on windows. The latest stable version to date

**Comment by Krzmbrzl** [comment]
> The latest stable version to date  

So you are running 1.3.0?

I could imagine, that the reported error stems from here:
https://github.com/mumble-voip/mumble/blob/c2469ac29cc9761b8d90de958ab37573858db272/src/murmur/Register.cpp#L125
Unfortunately that doesn't really indicate what the problem is and I'm not familiar enough with that part of the code.

Just to be sure: You are able to access that domain name via e.g. your browser and it's only Mumble/Murmur that can't seem to resolve the DNS, right?

**Comment by KruegerDead** [comment]
> So you are running 1.3.0?

Yes

> Just to be sure: You are able to access that domain name via e.g. your browser and it's only Mumble/Murmur that can't seem to resolve the DNS, right?

Yes, right. I have few domains, and test with other's but problem just with .CF. Also my mumble server works for all people by that .cf domain.

**Comment by Krzmbrzl** [comment]
Hm okay. Given that the server seems to work and that you are actually able to connect to the server, indicates that the problem lies somewhere in the API for public server registrations... @davidebeatrici do you have an idea, what the problem could be?

**Comment by KruegerDead** [comment]
> 
> 
> Are you using IPv4 or IPv6? #2252 indicates that there have been some issues with the latter in the past. Though from what I read there, I'd assume that specific problem to be fixed by now...
> 

IPv4

> Also #2597 appears to be (closely) related to this issue. In there it was stated that the error message is coming from OpenSSL internals...

Yes, looks like issue in certificate. I remove certificate and key from config, and now server succesfully registered.

**Comment by Krzmbrzl** [comment]
Could you share your config from before and after the change? Maybe we can use that to investigate the problem further :)

**Comment by KruegerDead** [comment]
For now i just comment lines with sslCert and sslKey.
