### ISSUE TITLE
Fold status join and leave messages, so they don't spam the message widget

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#3941]
Riot folds join and leave messages together to reduce clutter. Here is a screenshot from the Mumble IRC channel:

![Bildschirmfoto vom 2020-01-14 21-27-48](https://user-images.githubusercontent.com/404521/72380107-01aa4b80-3715-11ea-9630-52a296b5351c.png)

We have a user that is constantly leaving and joining due to WIFI issues and that is really annoying, but even with the normal users leave/join messages accumulate quickly and the important messages are hard to make out.

Being able to expand and collapse the unimportant messages would be really great.

PS: I know that I can completely disable the messages in the settings, but I'd like to have my cake and eat it too, I guess … Also it is cumbersome to tell everyone to disable those messages and the information is lost.

**Comment by Krzmbrzl** [comment]
Okay so just that I get this correctly: You are asking about this folding to be implemented in the Mumble chat, right? The IRC thing is simply an example illustrating how you'd like to have it?

First of all let me start by saying that I guess this would require quite some work as the log currently does not provide the functionality of editing a message (to my knowledge) of which I'm not entirely sure it is justified for such a "convenience feature".

Note however that #3465 aims at providing different tabs for different kinds of messages. Thus I could imagine, that the system messages (containing join and leave messages) are dumped in their own tab and actual chat happens in another one.
If implemented in that way, would you say that this solves the problem in a satisfying way?

**Comment by promi** [comment]
You understood me correctly, yes.

And #3465 would be sufficient to fix the problem for me.

**Comment by Krzmbrzl** [comment]
Alright, then I'd close this as a duplicate (more or less) of #2521, if that is okay for you (feel free to object) :)

**Comment by promi** [comment]
Feel free to do so.
