### ISSUE TITLE
Explicitly use this-ptr

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3944]
At the moment the coding style convention for Mumble appears to be to never explicitly use the `this` pointer to access member-variables and/or -functions, unless necessary.

Combined with the fact, that we don't have a convention in place that marks the names of these member fields somehow specially (e.g. by prefixing them with `m_`), this makes reading the code pretty damn hard sometimes (in my opinion at least).

Consider this code (and pretend it is inside a member-function):
```cpp
if (bMyFlag) {
    myFunc();
}
```
There is no way to tell, whether `bMyFlag` is  a member-variable or just a local variable declared somewhere above (or even a global variable that has not been declared in its own namespace). Furthermore it is (to my knowledge) impossible to tell whether `myFunc` is a member function or a free function.
This makes it increasingly hard, if yoou start looking at a piece of code and want to figure out what is going on. You always have to search a bunch of places in which these variables/functions *might* be declared and then you have to double-check that this is indeed the correct variable/function as sometimes (admittedly rarely though) there are multiple candidates with the same names.

For this reason I'd suggest to switch coding style to always use the `this` pointer explicitly. With that above example could be much clearer:
```cpp
if (this->bMyFlag) {
    this->myFunc();
}
```
Now it is imminent where to look for the declaration/definition.

Of course it's unfeasable to go through old code and change it everywhere, but if we respect that for new code and code-changes, then I think the code base will adapt this new style gradually. And I don't think it hurts to have the "old" and the potential "new" style side-by-side...

Another alternative would be to mark member variables with a prefix (e.g. `m_`), but this can't really be extended to member functions without making their names really ugly, so I'd prefer the use of `this`.

What do you think about this?

**Comment by Kissaki** [comment]
I don’t like the bloat of it. Function bodies should be no more than 100 lines, and whether a variable is local should be visible at a glance. It’s qualification that should become clear from code structure, naming and locality.

That being said I haven’t worked with it for a while.

**Comment by Krzmbrzl** [comment]
> Function bodies should be no more than 100 lines

This isn't really changed by using `this->`. Maybe the length of a line get s a bit more but I don't think it'll have a big impact on line count.

> whether a variable is local should be visible at a glance.

Exactly. Thus my proposal ^^

> It’s qualification that should become clear from code structure, naming and locality.

How would you do that in the example I provided above? I actually don't quite understand how you'd achieve this :thinking:

> That being said I haven’t worked with it for a while.

"it" being Mumble's source code?

**Comment by Kissaki** [comment]
> > Function bodies should be no more than 100 lines
> 
> This isn't really changed by using `this->`. Maybe the length of a line get s a bit more but I don't think it'll have a big impact on line count.

What I meant was if you can see the body at a glance you will spot a local variable without a need to infer it by a lack of a `this->` qualifier which is not a definite either.

**Comment by Krzmbrzl** [comment]
Ah okay now I understand.

While this is certainly true, I still think that even in these case explicit usage of `this->` allows me to see that immediately just from the single line of code I am currently looking at (no need to even glance at the rest of the function body). And even more importantly: We are far from having all function bodies in that size-region.
For instance
https://github.com/mumble-voip/mumble/blob/72e1f47b7b13d2ffd2a98cb2fd79c10674376698/src/mumble/AudioOutput.cpp#L362-L605
is well over 200 lines long. No chance to grasp the whole function in a few seconds when looking at it.

> which is not a definite either.

In which case is the `this->` qualifier not definite? :thinking:

**Comment by Kissaki** [comment]
How do other big projects and organizations handle this in their C++ coding guidelines?

I don't think using `this->` is prevalent? Broadening to not only C++ it definitely is not. I have not seen guidelines requiring this pointers.

**Comment by Krzmbrzl** [comment]
AFAIK in cpp the convention appears to be to prefix member variables with `m_`.

As far as other la guages are concerned, I think they don't need it that much, as there are proper IDEs for them highlighting member variables differently. However C/C++ have such a design that this is not really possible. Thus one can't rely on these things being overtaken by an IDE

**Comment by Krzmbrzl** [comment]
Iirc @McKayJT was also in favor of the this pointer (mentioned via IRC).

I'd also be interested in the opinion of @davidebeatrici.

**Comment by davidebeatrici** [comment]
I agree that in certain classes the variables' names are not intuitive, two potential examples could be `AudioInput` and `AudioOutput`.

While `this` undoubtedly makes it clear that a variable is declared inside a class, I believe it will ultimately bloat the code (as @Kissaki said).

In my opinion we should at least try to come up with better names for the variables, before resorting to `this`.

**Comment by Krzmbrzl** [comment]
Would you prefer a Prefix like `m_` for member variables?

**Comment by Kissaki** [comment]
To actually provide a reference, although not C++, Microsoft .NET (framework) guidelines use `Property`, `_field`, `s_staticField`, `local`, `Method`, `Class`, `Namespace`.

Obviously we would be better to follow some very common C++ guidelines, which I asked for, but was not answered yet.

Many projects and people came to their guidelines for good reasons, and well established conventions should not be broken with very good reason. An obvious candidate would be Qt which we base on and use, and it would include Qt constructs. Consequently KDE may be one. Others would be Microsoft C++ guidelines, Boost, Google, Linux(?).

Offering and discussing personal preference and unbased, unreasoned styles here without even looking at them really strikes me the wrong way.

Is there any reason why, if you want to change our current guidelines, you have not checked on them and presented them yet? We really should not invent our own wheel when there are well established ones out there.

**Comment by Krzmbrzl** [comment]
> which I asked for, but was not answered yet.

Not true. I already said that it is very common to use prefixes instead of the this-ptr. 

> unbased, unreasoned styles

I think the reason is rather obvious: Currently the code-base is pretty shitty and it takes a huge amount of work and dedication to get into it. This is to a good part due to missing documentation (on which I had opened a separate issue) but also in part to a missing naming convention for member variables making it increasingly difficult to understand what's going on and what effect each line of code has. 
If that's not reason enough, I don't know what is. 

> Is there any reason why, if you want to change our current guidelines, you have not checked on them and presented them yet? 

Uhm what? What do you mean by that? How far did I not present the way I'd like to change the guidelines? It's literally the title of this issue...
Or are you asking why I haven't dug up the style guides of other projects specifically? The answer to that is that ultimately it is a matter of taste which exact guideline one is using. There's no sense in basing the argument on how project XY does it unless they have a clever way of doing stuff no one here has thought about so far.
I presented all ways that I know are common for this purpose. If you know more then just name them.

**Comment by Kissaki** [comment]
> Currently the code-base is pretty shitty and it takes a huge amount of work and dedication to get into it. This is to a good part due to missing documentation (on which I had opened a separate issue) but also in part to a missing naming convention for member variables making it increasingly difficult to understand what's going on and what effect each line of code has.
If that's not reason enough, I don't know what is.

I agree it’s shitty, but I doubt just (having) a naming convention will fix that.

[Our existing, current coding guidelines already define and demand to use prefixes](https://wiki.mumble.info/wiki/Coding_Guidelines#Member_variables):

> m_ and s_ prefix
>     m_camelCase for member variables
>     s_camelCase for static member variables

Isn’t this what you are asking for? Differentiation between locals, members and static fields? But we already have it defined as such?

As for this pointers I’m against those.

[KDE code policy](https://community.kde.org/Policies/Library_Code_Policy#Naming_Conventions) is based on [Qt Coding Style](https://wiki.qt.io/Qt_Coding_Style). Neither use this pointers or scope qualifiers.

> The answer to that is that ultimately it is a matter of taste which exact guideline one is using. There's no sense in basing the argument on how project XY does it unless they have a clever way of doing stuff no one here has thought about so far.

I disagree. When big libraries we depend on, when we can make use of or support established familiarity, and if we can make use of other projects findings/road to rules then we should do so instead of inventing/defining our own unless there is a good reason not to.

**Comment by Krzmbrzl** [comment]
> but I doubt just (having) a naming convention will fix that. 

Sure but it's a relatively easy step in the direction of a better code-base. 

> Isn’t this what you are asking for

Yep that's exactly it. If I had known this rule exists, I wouldn't have created this issue xD

Okay so we actually have the guideline, we might consider checking whether there exists a tool like clang-tidy or so that helps us checking that this guideline is being followed :thinking:

**Comment by Krzmbrzl** [comment]
I just found https://github.com/mapbox/cncc/ that might be useful for this kind of stuff.
