### ISSUE TITLE
Installation of Mumble-server and Client after Compilation from the Source Code

### ISSUE THREAD

**Issue by tajummal-lab** [mumble-voip/mumble#3949]
Hy All,
I have compile the Source Code of Mumble-Server and Client and build my own Mumble server that`s running fine with Default Configuration.
Now i running Murmur and mumble on Ubuntu 18.04 using  "./ " manually.
how i can install mumble server and client Automatically so that all essential file will reside in there required directories. like, in etc , bin,.....etc.

Regards: Tajummal Hussain

**Comment by Krzmbrzl** [comment]
To be quite honest I'm not entirely sure whether there currently exists an automatic installation if you self-compiled murmur. @davidebeatrici is currently working on a cmake-build system that'll contain an install-target but as of now, I'm afraid that I don't know of something like this :thinking: 

But maybe @davidebeatrici knows more on this...

**Comment by Krzmbrzl** [comment]
I now know for sure that we currently have an automated way to install mumble after compilation.

The new cmake build system will also include a `make install` though
