### ISSUE TITLE
Defaults cause microphone to not work on windows

### ISSUE THREAD

**Issue by Bios-Marcel** [mumble-voip/mumble#3952]
No matter which windows user I told to get mumble, they all complained that it's trash because the microphone initially doesn't work. I think fixing this issue would greatly benefit the userbase and the potential userbase, since new users are pretty much scared of due to this. It all works perfectly fine on linux tho.

**Comment by Krzmbrzl** [comment]
I don't have this issue on windows. And without more information on the setups that were failing, we can't do much, I'm afraid.

You said that the microphone wasn't working *initially* and that it would be the fault of the default settings. So what exactly had to be changed to get the microphone working?

**Comment by Bios-Marcel** [comment]
What seemed to help was changing the voice activation from "amplitutde" to "Signal to Noise". And I had this with 4 people in a row. All of them were using x64 Windows 10 and had just installed mumble. This happened with both 1.2.3 and 1.3.

**Comment by Krzmbrzl** [comment]
Did these 4 people happen to have the same microphone as well? Did they run the audio-wizard or did they start using Mumble out-of-the-box?
And furthermore: Didn't Mumble receive any audio input (can be checked in the audio input settings - whether or not the colored bar spikes when speaking or not) or was the amplitude of the received audio simply too low for the set threshold? If the latter is the case, can the "amplitude" mode be made working by lowering the activation threshold?

**Comment by Bios-Marcel** [comment]
They all had different microphones and headsets. Both USB and Aux. None of them had the same host hardware. And yes, mumble didn't receive input. However, I myself can't reproduce it on linux and I assume virtualizing might yield totally different results anyway :D

**Comment by Krzmbrzl** [comment]
> virtualizing might yield totally different results anyway :D

Probably ^^

Any chance you could motivate one of the affected users to pay this issue a visit as well, in order to provide info directly? It seems unnecessary complicated to always ask you to ask them :D

**Comment by Bios-Marcel** [comment]
Yeah, i'll try over the next days.
