### ISSUE TITLE
Volume slider for PTT cue

### ISSUE THREAD

**Issue by RagingFlames** [mumble-voip/mumble#3954]
The ability to change how loud the PTT cue is would be really nice so we don't have to edit it manually in audacity. For me personally, the PTT cue is at least twice as loud as anyone talking in the channel, and since the PTT cue volume is tied to the volume for mumble in general there is no easy fix. Having a slider in the settings menu would be greatly appreciated.

**Comment by Krzmbrzl** [comment]
PTT cue being a sound that is played when pressing the PTT button? (I haven't used PTT yet)

I assume this might be a general enhancement for all internal sounds. 

How did you edit it with audacity though? I always was in the believe that the sounds were baked into the Mumble client :thinking:

**Comment by RagingFlames** [comment]
Open mumble, go to Audio input, misc. You can replace the audio file that is used for the audio cue. Just open those files in audacity, change the volume, then replace them in mumble.

**Comment by Krzmbrzl** [comment]
I'll close this in gabor of the more general #3963
