### ISSUE TITLE
Left 4 Dead 2 Mumble Plug-ins no longer showing when downloading new ones

### ISSUE THREAD

**Issue by MageOrnitier** [mumble-voip/mumble#3960]
I've recently been trying to use the Mumble Positional Audio, even downloading the new-er versions of the plugins [here](https://github.com/mumble-voip/mumble/issues/3493#issuecomment-508311111) and [here,](https://github.com/mumble-voip/mumble/pull/3771#issuecomment-526070770) but they no longer show up at all in the Plugins interface. I've tried placing them inside my mumble plugins %appdata% folder, and the installation folder too, but after downloading these they seem to disappear completely when i overwrite the .dll files. Reloading the plugins doesn't work, either. I'm just wondering if I'm doing something wrong or not. Thanks in advance.

**Comment by Krzmbrzl** [comment]
If im not mistaken, the current "plugin" system relies on the plugins being compiled with the same compiler, as Mumble itself. Thus I'd assume that the plugins you downloaded don't fulfill these requirements.

So if you want to get a more recent version, I think it might be best to compile Mumble with the plugins yourself on your machine
