### ISSUE TITLE
API to get link status of channel 

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3962]
Sort of in line with the above I'm also using Mumble in a TV broadcast setting. 

I'm currently using it to do small local intercom setups between remote contributors in place of costly comms setups like RTS and Clearcom. I've assigned a number of keyboard shortcuts to a little controller to do something similar to the above scenarios using ACL's, so various shouts and various rooms links so 1 user can speak to or listen to multiple other rooms/users. The controller has lights that can toggle on and off, so if I'm linked to room A (listening), the corresponding button on the controller lights up and when I'm not linked it turns off. 

The issue I'm running into is the controller currently just toggles the lights statically when you press the key, it doesn't poll Mumble so they can get out of sync pretty easily (Mumble seems to miss commands decently often). I'm trying to figure out if there is a way to get the status of room link/unlinks using an API so that I can then send that information to my controller to dynamically control the lights so that they reflect the true state of Mumble and not what my last button press was (whether the command took or not), or, to actually control the links/unlinks to the same effect. Any help would be greatly appreciated!

_Originally posted by @matthiasgraf in https://github.com/mumble-voip/mumble/issues/3319#issuecomment-582599198_

**Comment by Krzmbrzl** [comment]
I moved this to its own issue as it doesn't fit into the other one.

To answer your question: I don't think there is currently an API to get this kind of information. The only thing I could imagine is that this is accessible via the ICE interface (and in the future possibly gRPC). I don't know these interfaces very well though so I can't say for sure whether this is part of the API or not. 

@Kissaki should know more about the ICE API and @McKayJT probably knows the gRPC interface better than anyone else...

**Comment by matthiasgraf** [comment]
Apologies for the misposted issue, thanks for moving it @Krzmbrzl. 

Is there any sort of functionality in the works for Mumble that might be useful to this end?

Do you know where I can find documentation on the ICE API or gRPC?

**Comment by Krzmbrzl** [comment]
For ice there's https://wiki.mumble.info/wiki/Ice
And for gRPC there's https://wiki.mumble.info/wiki/GRPC 

But that's more of a description of the concept and not really an API documentation... :thinking:

**Comment by matthiasgraf** [comment]
Much appreciated, gives me a place to start. 

If @ Kissaki or @ McKayJT know of anything in either of those that can nudge me further in the right direction the help would be welcome!

**Comment by McKayJT** [comment]
So it sounds like you just want a record of what the server is seeing as far as who is in what channel listening or whatnot? The server events stream will give you who does what, and the tree query can be used to get the initial channel layout:

You can see how the tree and server events API work [here](https://gist.github.com/McKayJT/550cb368c2c7b71ba5fd9c40333b4e5f). You can see me and my bot joining channels, me unmuting-and muting, leaving channels, rejoining. And then at the end you can see the tree view which you probably want to query first to get the layout of the server. Also you probably want to work with gRPC directly instead of using the json-ish interface my testing utility uses.

**Comment by Kissaki** [comment]
The generated Ice slice documentation is at http://mumble.sourceforge.net/slice/1.3.0/Murmur.html

The Channel structure has a `links` field http://mumble.sourceforge.net/slice/1.3.0/Murmur/Channel.html#links

And the Server structure has a getChannelState method to get the Channel information. http://mumble.sourceforge.net/slice/1.3.0/Murmur/Server.html#getChannelState

Does that answer your question?

**Comment by Kissaki** [comment]
I just checked and I actually did migrate that data onto the new website, but it looks like that has not been updated yet to production. https://github.com/mumble-voip/mumble-www/issues/60 It should be a lot more discoverable then.

**Comment by Kissaki** [comment]
The GRPC API can be seen in [`Murmur.proto`](https://github.com/mumble-voip/mumble/blob/master/src/murmur/MurmurRPC.proto).

You are probably looking for [`ChannelQuery` or `ChannelGet`](https://github.com/mumble-voip/mumble/blob/master/src/murmur/MurmurRPC.proto#L718-L721).

Here as well the `Channel` structure has a [`links`](https://github.com/mumble-voip/mumble/blob/master/src/murmur/MurmurRPC.proto#L201) field.

**Comment by alexandermaisey** [comment]
Hi all.  I am working with @matthiasgraf on this.  To be fair, I am not familiar with either GRPC or ICE and we might've been hoping for a way to access this information via REST calls to our Murmur server.  Is this something that Murmur supports natively or should I look into an add-on?

**Comment by Kissaki** [comment]
There is no REST available.

Depending on your environment you can generate API classes for ICE or GRPC to use. So usage should be pretty straight forward after that.
