### ISSUE TITLE
Possibility to set a local nickname for users

### ISSUE THREAD

**Issue by nifker** [mumble-voip/mumble#3967]
Mumble-Client.

It would be nice if it would be possible to give others users(only seen by yourself) nickname next to the username, so people can be fastly recognized even if they e.g. have a username which is similiar to another users username.

Suggestion:
This can be set by right-clicking the users name with an entry called "Set nickname".

Then name would like the following in the UI:
< username > [< nickname >]

**Comment by Krzmbrzl** [comment]
Should this nickname be persistent or do you have a scenario in mind in which these nicknames apply to one server-session only.
In the latter case I think it would be almost trivial to implement this :thinking:

**Comment by nifker** [comment]
Would be saved client-side only and for one specific client(identified from cert) only.

**Comment by Krzmbrzl** [comment]
So persistence based on a certain certificate.

Hm, I don't even know right now whether a client will have access to another clients certificate. Though I think I read somewhere that one can view other user's certificates... 
If this is the case, this should still be more or less easy to implement.

**Comment by Vipulsh** [comment]
I would like to work on this. Everyone should have unique nicknames, is that correct?
I am a beginner on this , so looking forward to work on it.

**Comment by nifker** [comment]
@Vipulsh I dont think that would be mandatory, as many people just name them after real life names(and thus there can be people having the same name).

**Comment by Krzmbrzl** [comment]
@Vipulsh very good to hear you are willing tit ale up the task :+1:

Users are identified by an ID which is an integer that is assigned to them by the server. The user name is for displaying purposes only so there's no need for them to be unique.

I think it might be best if you were to join our IRC channel via matrix (https://riot.im/app/#/room/#mumble:matrix.org). That's often times the best place to discuss implementation details :)
If you don't want to it'd be also fine to do the discussion on this issue though.

If you need anything else, please let me know :D

**Comment by Vipulsh** [comment]
@Krzmbrzl @nifker Thanks for the updates . I'll surely be joining the channel to discuss it further. Meanwhile, I'll go through the code and see what changes I can make.

**Comment by toby63** [comment]
I would like to add two thoughts:
1. I would like to be able to just see the nickname I gave the user (instead of their own username).
2. Regarding the user certificate: I don't know the technical details, but someone somewhere else (I would need to look up the specific topic, to give a correct link) complained that it can be insecure etc. to give everyone access to the user certificate.
So maybe a different solution should be applied, for example:
    - a second certificate (so that we could use certificate 1 only for client<=>server and certificate 2 for user<=>user purposes)

**Comment by Krzmbrzl** [comment]
> I would like to be able to just see the nickname I gave the user (instead of their own username).

The problem with that is that in this case 2 users can end up with the same displayed name on a single server. If you use a composite of nickname and actual name, it'd be less likely to happen.

> Reasons for insecurity: As far as I remember the argument was: breaking the encryption when you have access to a user certificate.

I'm pretty sure that's nonsense. What gets transmitted is always only the hash of the user's certificate.

> a second certificate (so that we could use certificate 1 only for client<=>server and certificate 2 for user<=>user purposes)

Users are already confused about 1 certificate so adding a second one is probably a bad idea :thinking:

**Comment by toby63** [comment]
> The problem with that is that in this case 2 users can end up with the same displayed name on a single server. If you use a composite of nickname and actual name, it'd be less likely to happen.

And? One of them will be marked as a friend, the other not. So no way a real confusion can happen.
I agree that we can make Option 2 the default, but I would like to be able to use option 1 (only nickname), the reason for this is, that people sometimes use very inappropiate usernames and I don't want to see them all the time.

> I'm pretty sure that's nonsense. What gets transmitted is always only the hash of the user's certificate.
(If you get your hands on the actual certificate of a user then that's of course a security problem but you can't (realistically) reverse the hash back to the original certificate)

Interesting; sadly I am no expert, but I read sometime ago that not all hashes are as secure as many believe they are, so I would like to minimize risks.

> Users are already confused about 1 certificate so adding a second one is probably a bad idea :thinking: 

I remember there was already a discussion about this, I think mumble should not always display this whole certificate stuff.
Many programs and websites use certificates, the users don't even recognize that.
So mumble can simply create them in background and use them.

**Comment by Krzmbrzl** [comment]
> And? One of them will be marked as a friend, the other not. So no way a real confusion can happen.

I want to differentiate users by looking at their name and not by also having to check the symbol.

> I agree that we can make Option 2 the default, but I would like to be able to use option 1 (only nickname), the reason for this is, that people sometimes use very inappropiate usernames and I don't want to see them all the time.

Well I don't mind having this as an option for those that want it :shrug: 

> I read sometime ago that not all hashes are as secure as many believe they are, so I would like to minimize risks.

Yeah that's correct. As far as I know though we use cryptographic hashes for everything :thinking: 

> I remember there was already a discussion about this, I think mumble should not always display this whole certificate stuff.
Many programs and websites use certificates, the users don't even recognize that.
So mumble can simply create them in background and use them.

This discussion is a bit OT here (not blaming you - I started it).
I guess what I also wanted to say is that it'd also be more effort to maintain 2 certificates in the code. And I don't think it's necessary...

**Comment by toby63** [comment]
> Well I don't mind having this as an option for those that want it :shrug:

Ok, sounds like a good compromise :+1:

> Yeah that's correct. As far as I know though we use cryptographic hashes for everything :thinking: 

Well maybe you could discuss this (inside the team and/or with some of our "security experts" among the users/contributors).
You already mentioned that the certificate (and it's hashes etc.) seems to be used for several identification purposes and if it is insecure, I would change that.
At least users should not have (direct or indirect) access to the certificate that is also used for the user<=>server communication/verification etc., that's my understanding of the situation.
Maybe it is also possible to improve the security of the certificate itself (stronger encryption or hashes (methods, length etc.), (automatic) renewel of certificates after some time, more certificates etc.).

> I guess what I also wanted to say is that it'd also be more effort to maintain 2 certificates in the code. And I don't think it's necessary...

See above.

**Comment by nm17** [comment]
Great idea, waiting for any updates on this.

**Comment by tandunn** [comment]
Hey, I'm new. I see that this issue hasn't been touched in a while. Is this something that I could work on? I used this issue as a means to learn about the code, so I kind of already have a working solution. I would still need to add the setting mentioned above though.

**Comment by davidebeatrici** [comment]
Hi, you can of course work on it!

**Comment by Krzmbrzl** [comment]
As Davide said: We're always happy to accept contributions to the project. If you create a PR early on, we can work together on this by providing you with feedback early on :+1:
