### ISSUE TITLE
MacOS shortcut key bindings missing

### ISSUE THREAD

**Issue by jaycee58** [mumble-voip/mumble#3976]
Running Mumble 1.3.0 on an iMac and MacBook Pro, both using Catalina. Last night the shortcut key settings for push-to-talk and whisper disappeared from the iMac. It will not allow me to add new shortcuts. Nothing happens when I try to. MacBook was ok until this morning but now this exhibits the same behaviour. Both computer have been running Mumble since September 2019 without any problems.

**Comment by Krzmbrzl** [comment]
Did you change something else on your system? E.g. a system update or something like that? :thinking:

**Comment by jaycee58** [comment]
I've definitely not changed anything and there's been no system updates either. I have noticed that one app, WhatsApp Desktop, has updated on both machines in the last 24 hours. As a test I completely uninstalled this app but it's made no difference but I can't help wondering if it's related to my problem or whether this is extremely unlikely. I can still talk using voice activation but I need the whisper function to work. I've also uninstalled and reinstalled Mumble.

**Comment by Krzmbrzl** [comment]
Well I guess that would have been too easy ^^

I doubt that WhatsApp has anything to do with that.

Does something show up in Mumble's log when you try to add a shortcut? If there's nothing, could you try starting Mumble from a terminal and paste the output from the terminal (after having started Mumble and tries to add that shortcut)?

**Comment by jaycee58** [comment]
Thank you for that suggestion. I opened Mumble via terminal and this allows me to enter shortcuts once more.  I don't have the technical knowledge to know why but it works so I'm happy with that.

**Comment by Krzmbrzl** [comment]
Okay that's weird. Not being a Mac-user I have absolutely no clue why this could be though :man_shrugging: 

But if you are happy with how things are now, I'll close this issue as "resolved" :)

**Comment by 2drewlee** [comment]
I'm seeing the same issue described by Krzmbrzl. I tried opened Mumble from terminal to see if that would fix, but it didn't work for me.

**Comment by jaycee58** [comment]
Apologies for not updating...my fix only worked for a day or two. Here's what I tried next and so far all is well. Go to System Preferences...Security & Privacy...Accessibility then delete Mumble from the list of apps allowed to control your computer. I think I may have restarted the computer next (can't remember!). Then add Mumble to the list once again. After doing this my shortcuts were restored.  I hope this will fix the problem for you.

**Comment by Krzmbrzl** [comment]
This is very weird. If the shortcuts stop working again or if the fix described by @jaycee58 doesn't work for @2drewlee, I'll reopen this issue and we'll have to try and figure out what's going on...

**Comment by 2drewlee** [comment]
I followed instructions by @jaycee58... closed Mumble, removed Mumble from Privacy apps in System Preferences, reinstalled Mumble, added Mumble back Privacy apps, started Mumble, and now it works! Thank you 👍

**Comment by jaycee58** [comment]
Excellent. Glad to hear that it worked for you as well.
