### ISSUE TITLE
Hyperlink in welcome message

### ISSUE THREAD

**Issue by Qwerty-Space** [mumble-voip/mumble#3979]
**Describe the bug**
Hyperlinks aren't showing up in the welcome message

**Steps to Reproduce**
I set a hyperlink in the welcome message like this:
`<a href="https://oqwerty.space/">Long term backups</a><br>`

**Screenshots**
![image](https://user-images.githubusercontent.com/6967592/75636402-4e3edd00-5c16-11ea-815f-5c84f48b9765.png)

**Desktop (please complete the following information):**
 - Mumble client OS: Windows 10
 - Murmur OS: Debian
Mumble 1.3.0 Murmur 1.3.0

**Comment by Qwerty-Space** [comment]
It's because I used double quotes inside double quotes.

My previous `welcometext="foo <a href="example.com">bar</a>"` won't work, changing it to this fixed it:
`welcometext="foo <a href='example.com'>bar</a>"`

**Comment by Krzmbrzl** [comment]
Thanks for sharing the solution you found :+1:
