### ISSUE TITLE
Mumble Letsencrypt Wildcard unsupported

### ISSUE THREAD

**Issue by peylight** [mumble-voip/mumble#3994]
Hello
There is a problem.
Seems mumble is not supported wildcard ssl domain (letsencrypt tested)

**Comment by Krzmbrzl** [comment]
Uhm what? I'm afraid I can't really follow what the problem is.

What exactly have you tried to do, what has happened and what did you expect to happen?

**Comment by peylight** [comment]
@Krzmbrzl
I use wildcard ssl in letsencrypt and then use it for mumble server.
but when i connect to the server i see a pop up for issue about certification that is not verified.

**Comment by xenrox** [comment]
You need to set sslCA as well.

**Comment by peylight** [comment]
@xenrox 
It's work. Thanks.

**Comment by Krzmbrzl** [comment]
@xenrox thanks for jumping in on this one :)

For anyone that might stumble across this issue in the future: Here's a link to the wiki page describing the `sslCA` config option: https://wiki.mumble.info/wiki/Murmur.ini#sslCA
