### ISSUE TITLE
Migrate project to CMake

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#3996]
WIP https://github.com/davidebeatrici/mumble/tree/cmake

**Comment by Kissaki** [comment]
@davidebeatrici Can you please describe the current state of this here?

**Comment by davidebeatrici** [comment]
Build environment: https://github.com/mumble-voip/mumble-releng-vcpkg
Built environments: https://dl.mumble.info/build/vcpkg

Pull request for the CMake project coming soon, my branch can be used in the meantime.
