### ISSUE TITLE
Allow forcing UDP or UDP auto-detect

### ISSUE THREAD

**Issue by SLDiggie** [mumble-voip/mumble#3997]
**Context**
Due to covid-19, our team is working from home and using mumble to chat. We use various VPN profiles for different environments and sometimes have to switch between them. When this happens, mumble loses its connection to the server, and sometimes switches to TCP because it can't communicate over UDP briefly. However, once the VPN reconnects there's actually no problem sending UDP packets. Unfortunately mumble client doesn't realize this.

**Describe the feature you have in mind**
There are two reasonable solutions. One is that because I know I'm switching between endpoints often and none actually have problems with UDP traffic, allow me to specify that mumble should always wait for a UDP connection to become available. Another option is to have a mumble client that's connected over TCP try to send a small UDP packet every few seconds and if the server responds switch connection types. This would possibly be the better approach, given that perhaps I could connect to some networks that transport UDP and others that don't.

**Describe alternatives you've considered**
Manually disconnect/reconnect for better performance.

**Additional context**

**Comment by davidebeatrici** [comment]
Very pleased to hear that our project is being used in this (serious) emergency!

> Another option is to have a mumble client that's connected over TCP try to send a small UDP packet every few seconds and if the server responds switch connection types.

That's actually already the case, if it doesn't work it's a bug.

Do you see anything related in the developer console?

**Comment by unterwulf** [comment]
Just a wild guess, but as far as VPN is concerned, if it could be possible that the system got several IPs and the TCP connection still uses the same old one but the UDP connection picks a new one (I haven't looked into this part of Mumble code and cannot say if it is in fact possible), even though the client will send UDP pings, server won't recognize them as the client's ones and consequently will never send a UDP reply. So the client will have no trigger to switch back to UDP. 

If reconnection makes UDP working again, this theory may be the case. Not sure if murmur logs such wild UDP packets, but tcpdump will definitely help to understand the situation.

**Comment by Reikion** [comment]
@unterwulf I noticed two behaviours between OSes. See: #1697 — Windows keeps TCP connections, Linux closes gracefully TCP connection and reconnects. So your theory may be right.

**Comment by Krzmbrzl** [comment]
If someone finds any evidence of this misbehavior (preferably with a reproducible scenario) I can either reopen this issue or even better: Go ahead and create a new one. We'd appreciate any info on this :)
