### ISSUE TITLE
Talking indicator stays enabled when self-mute

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#4006]
**Describe the bug**
If I trigger the self-mute action while I am still speaking aka the speaking-icon is shown next to my user name, the icon will not change back to non-speaking again.
This is only a local effect though. ON another client I am no longer marked as speaking as it should be.

**Steps to Reproduce**
1. Start talking so that the speaking icon appears next to the name
2. Trigger self-mute while continue speaking
3. Stop Speaking
4. Icon won't change back

**Expected behavior**
The icon should go back to indicate me being silent

**Desktop (please complete the following information):**
 - OS: Linux (KDE Neon)
 - Version: current master (https://github.com/mumble-voip/mumble/commit/0319a77119de5bf03ab4274f353f316f4fed8fc8)

**Comment by Krzmbrzl** [comment]
Turns out this is not as easily reproducible as I thought. Can't reproduce it consistently. The only way I get it somewhat reliably is by spamming the mute-self button.

Thus I suspect that this might be related to the server's rate-limiter. That's just a wild guess though...

**Comment by ZingBlue** [comment]
I don't have this issue on Windows, it might be a Linux only bug.

**Comment by Krzmbrzl** [comment]
@ZingBlue thanks for the info. As I said the bug is very hard to reproduce in the first place and even then it seldomly shows in the UI. Only every now and then.
Could also be a Linux issue though - that's correct :)
