### ISSUE TITLE
mumble hangs on linux with multiple monitors in use

### ISSUE THREAD

**Issue by scottmayo** [mumble-voip/mumble#4008]
Start mumble on a linux laptop with two additional monitors plugged in (just one doesn't seem to do it in my case). 

Mumble displays several messages in the left panel of the form [[Text object too large to display]] (I think one for each welcome message it would normally display) and is unresponsive to all input. Only a hard kill will get rid of it. 

I have Overlay turned off so I don't know what business mumble has caring about how many displays I have. Even if it can't help but care, a failure should not hang it.

Starting with just the laptop screen allows mumble to start normally. Plugging in the additional monitors and then trying to do anything with mumble puts it in the hung state. Dragging it to other monitors or workspaces makes no difference; it must be killed.

**Comment by Krzmbrzl** [comment]
I assume you are using Mumble 1.3?

Which distribution are you using? What qt version is installed on your system?

I can confirm that 2 monitors work just fine. Been using it for a while on my Linux laptop with an additional monitor. 

Please start Mumble from the console and copy the output from there to this issue (with the 3 screen setup). Maybe that gives some clue as to what is going on...

**Comment by Avatat** [comment]
Everything works fine on Ubuntu 20.04.

**Comment by scottmayo** [comment]
Very sorry! I thought the latest was 1.2, because that's what Linux Mint thinks. I just upgraded to 1.3 and the problem doesn't reproduce. Thanks!

**Comment by Krzmbrzl** [comment]
Well that's even better. Every bug that "fixes itself" is a good bug :D
