### ISSUE TITLE
Audio from input is being included in output (immediately and at full volume, as opposed to an echo)

### ISSUE THREAD

**Issue by agnieder** [mumble-voip/mumble#4013]
Hi, sorry if this is an easy one but I'm new to Mumble. I'm using a Jabra Evolve 65 wired headset on a Windows 10 laptop, running Mumble 1.3.0. The issue I'm encoutering is that incoming audio is being included at full volume as part of the output back to Mumble. It's not an echo effect -- if I play audio on the laptop and physically cover (muffle) the earpiece the audio still goes completely through to the Output channel.

I've attached some screenshots of my Mumble and Windows Audio settings below. (Apologies for the blurry pictures; this is a work laptop and the Snipping tool has been disabled.)

I've tried several variations of the above and nothing has changed this behavior. Any help would be greatly appreciated, thanks!

![IMG_20200327_152402](https://user-images.githubusercontent.com/62776057/77806385-ef288880-705a-11ea-9e99-d5c8e40d0acd.jpg)
![IMG_20200327_120106](https://user-images.githubusercontent.com/62776057/77806386-efc11f00-705a-11ea-9c24-5d5987aca557.jpg)
![IMG_20200327_152333](https://user-images.githubusercontent.com/62776057/77806388-efc11f00-705a-11ea-9c4e-8bd5ddb98a58.jpg)

**Comment by Krzmbrzl** [comment]
Does this only happen with audio that is play through Mumble or does this also happen, if you e.g. play Music on your laptop with a different application?

Do you use the headset as an input device for other software as well? Does the problem occur in that other software too?

What happens if you turn the volume of your headset speakers down so that you can barely hear the sound that is being played. Does this affect the issue in any ways?

**Comment by agnieder** [comment]
It happens with all audio, mumble or not. During troubleshooting I'd been playing music via YouTube and seeing the red/yellow/green bar in the Audio Input/Transmissions menu light up, as if I were singing directly into the mic.

I have not been using the headset as an input device for other applications. And I don't have any other comparable applications that I use for which I can answer the "does it occur in other software".

If I turn the headset volume way down to the point where I can barely detect audio, that audio (e.g. YouTube) still comes clearly through to the Audio Input/Transmission menu.

**Comment by Krzmbrzl** [comment]
Okay in that case I'm almost certain that this is not a problem in Mumble but rather with the headset itself or with its settings.

To me this sounds somewhat similar to a loopback except that normally you'd route the input from the mic to the speakers when doing a direct loopback. 
Die you try a Google search for your specific headset and "loopback"? Or more generally "windows" and "audio loopback"...
