### ISSUE TITLE
Being able to change the message alert sound

### ISSUE THREAD

**Issue by TerryGeng** [mumble-voip/mumble#4014]
**Context**
The current message alert sound is kind of annoying. It comes too sudden and scares people.

**Describe the feature you have in mind**
Offer user options to switch between different alert sounds. Maybe like the "pop" sound from MacOS. Or at least, being able to mute it.

**Comment by Krzmbrzl** [comment]
AFAIK muting can be done in the settings under the Messages tab. The last column there should hold a reference to the sound that is being played for that message.
Maybe you can even set these to custom sounds as well. Not sure atm...

**Comment by Krzmbrzl** [comment]
Possible duplicate of #2339
Also related (to some extent): #3963

**Comment by TerryGeng** [comment]
Okay I see...
So there's a way to change the sound file. Sorry I didn't notice that before.

**Comment by Krzmbrzl** [comment]
No problem :)
