### ISSUE TITLE
The remote host closed the connection whenever i try to connect from outside my local network

### ISSUE THREAD

**Issue by 27md** [mumble-voip/mumble#4015]
i'm only able to connect to my server locally, this is what i get when i use a vpn and enter my global IP:

```
> <W>2020-03-29 03:03:37.315 1 => <19:(-1)> New connection: 40.89.x.x:51788
> <W>2020-03-29 03:03:37.351 1 => <19:(-1)> Connection closed: The remote host closed the connection [1]
> <W>2020-03-29 03:03:58.406 1 => <20:(-1)> New connection: 40.89.x.x:51800
> <W>2020-03-29 03:03:58.442 1 => <20:(-1)> Connection closed: The remote host closed the connection [1]
> <W>2020-03-29 03:04:03.356 1 => <21:(-1)> New connection: 40.89.x.x:51835
> <W>2020-03-29 03:04:03.392 1 => <21:(-1)> Connection closed: The remote host closed the connection [1]
> <W>2020-03-29 03:04:13.311 1 => <22:(-1)> New connection: 40.89.x.x:51847
> <W>2020-03-29 03:04:13.347 1 => <22:(-1)> Connection closed: The remote host closed the connection [1]
> <W>2020-03-29 03:04:14.965 1 => <18:tedt(-1)> Connection closed: The remote host closed the connection [1]
```
i also sometimes get  `Server: Failed to set TOS for UDP Socket` not sure if it's related

**Comment by Krzmbrzl** [comment]
I assume this is a murmur-log (aka server-log) excerpt?

Are you able to connect to your server without a VPN?

Could you also copy the output of the client dev-console please?
To get that you can go to the settings, `User interface` and under `Application` check `Enable developer menu`. Then in Mumble's menu there's an entry `Developer` and in there click `Developer console` and paste its content here.

And finally the obligatory question: Which version of Mumble and which version of Murmur are you using?

**Comment by 27md** [comment]
yes this is the output of the server log, i am able to connect without vpn when i enter my local IP
```
<W>2020-03-29 16:01:16.550 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2020-03-29 16:01:16.575 libopus 1.2.1 from /Applications/Mumble.app/Contents/MacOS/../Codecs/libopus.dylib
<W>2020-03-29 16:01:16.575 CELT bitstream 8000000b from /Applications/Mumble.app/Contents/MacOS/../Codecs/libcelt0.0.7.0.dylib
<W>2020-03-29 16:01:16.576 CELT bitstream 80000010 from /Applications/Mumble.app/Contents/MacOS/../Codecs/libcelt0.0.11.0.dylib
<W>2020-03-29 16:01:16.577 Theme: "Mumble"
<W>2020-03-29 16:01:16.577 Style: "Dark"
<W>2020-03-29 16:01:16.577 --> qss: ":themes/Mumble/OSX Dark.qss"
<W>2020-03-29 16:01:16.579 Using Mac OS X system langauge as locale name
<W>2020-03-29 16:01:16.579 Locale is "en-EG" (System: "en-EG")
<W>2020-03-29 16:01:16.834 Database SQLite: "3.14.1"
<W>2020-03-29 16:01:16.835 Overlay: Removing old socket on "/Users/x/.MumbleOverlayPipe"
<W>2020-03-29 16:01:16.836 Overlay: Listening on "/Users/x/.MumbleOverlayPipe"
<W>2020-03-29 16:01:16.852 Updating application palette
<W>2020-03-29 16:01:16.896 GlobalShortcutMac: Unable to create EventTap. Global Shortcuts will not be available.
<W>2020-03-29 16:01:16.973 SocketRPC: Removing old socket on "/Users/x/.MumbleSocket"
<W>2020-03-29 16:01:16.986 AudioInput: Opus encoder set for VOIP
<W>2020-03-29 16:01:16.986 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-03-29 16:01:16.986 CoreAudioInput: Set device to 'Default Device'.
<W>2020-03-29 16:01:17.009 CoreAudioInput: Input device with more than one channel detected. Defaulting to 1.
<W>2020-03-29 16:01:17.009 AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2020-03-29 16:01:17.010 CoreAudioInput: BufferFrameSizeRange = (14.00, 4096.00)
<W>2020-03-29 16:01:17.010 CoreAudioOutput: Set device to 'Default Device'.
<W>2020-03-29 16:01:17.011 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-03-29 16:01:17.011 CoreAudioOutput: BufferFrameSizeRange = (15.00, 4096.00)
<W>2020-03-29 16:01:17.603 Cannot open file '/skin:places/network-workgroup.svg', because: No such file or directory
<W>2020-03-29 16:01:17.603 Cannot open file '/skin:places/network-workgroup.svg', because: No such file or directory
<W>2020-03-29 16:01:29.265 Database SQLite: "3.14.1"
<W>2020-03-29 16:01:29.265 OpenSSL Support: 1 (OpenSSL 1.0.2k  26 Jan 2017)
<W>2020-03-29 16:01:29.620 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2020-03-29 16:01:41.093 CoreAudioInput: Shutting down.
<W>2020-03-29 16:01:41.119 CoreAudioOutput: Shutting down.
<W>2020-03-29 16:01:41.122 AudioInput: Opus encoder set for VOIP
<W>2020-03-29 16:01:41.122 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-03-29 16:01:41.122 CoreAudioInput: Set device to 'Default Device'.
<W>2020-03-29 16:01:41.125 CoreAudioInput: Input device with more than one channel detected. Defaulting to 1.
<W>2020-03-29 16:01:41.125 AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2020-03-29 16:01:41.125 CoreAudioInput: BufferFrameSizeRange = (14.00, 4096.00)
<W>2020-03-29 16:01:41.125 CoreAudioOutput: Set device to 'Default Device'.
<W>2020-03-29 16:01:41.126 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-03-29 16:01:41.127 CoreAudioOutput: BufferFrameSizeRange = (15.00, 4096.00)
<W>2020-03-29 16:01:41.909 CoreAudioInput: Shutting down.
<W>2020-03-29 16:01:41.935 CoreAudioOutput: Shutting down.
<W>2020-03-29 16:01:41.937 AudioInput: Opus encoder set for VOIP
<W>2020-03-29 16:01:41.937 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-03-29 16:01:41.937 CoreAudioInput: Set device to 'Default Device'.
<W>2020-03-29 16:01:41.940 CoreAudioInput: Input device with more than one channel detected. Defaulting to 1.
<W>2020-03-29 16:01:41.940 AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2020-03-29 16:01:41.940 CoreAudioInput: BufferFrameSizeRange = (14.00, 4096.00)
<W>2020-03-29 16:01:41.940 CoreAudioOutput: Set device to 'Default Device'.
<W>2020-03-29 16:01:41.941 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-03-29 16:01:41.942 CoreAudioOutput: BufferFrameSizeRange = (15.00, 4096.00)
<W>2020-03-29 16:01:51.669 Cannot open file '/skin:places/network-workgroup.svg', because: No such file or directory
<W>2020-03-29 16:01:51.669 Cannot open file '/skin:places/network-workgroup.svg', because: No such file or directory
<W>2020-03-29 16:01:57.297 AppNap: attempt to set AppNap suppression state to false while already in that state.
<W>2020-03-29 16:01:57.310 QSqlDatabasePrivate::removeDatabase: connection 'ServerHandler' is still in use, all queries will cease to work.
<W>2020-03-29 16:01:57.310 QSqlDatabasePrivate::addDatabase: duplicate connection name 'ServerHandler', old connection removed.
<W>2020-03-29 16:01:57.317 Database SQLite: "3.14.1"
<W>2020-03-29 16:01:57.317 OpenSSL Support: 1 (OpenSSL 1.0.2k  26 Jan 2017)
<W>2020-03-29 16:01:57.666 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2020-03-29 16:01:58.089 AppNap: attempt to set AppNap suppression state to false while already in that state.
<W>2020-03-29 16:02:08.988 AppNap: attempt to set AppNap suppression state to false while already in that state.
<W>2020-03-29 16:02:48.562 AppNap: attempt to set AppNap suppression state to false while already in that state.
```
this is the output in client dev-console, and i'm using clinet version 1.3.0 on Mac OS, server version 1.2.9, and i tried using the latest version for the server first it had the same issue. (btw my friend is on windows and also can't connect to my server so i'm guessing it's a server issue)

**Comment by Krzmbrzl** [comment]
Is your friend also using a VPN when the connection fails?

Is the server log also the same with v1. 3?
(Given how old the 1.2.x series is, I'd recommend upgrading the server independently of this issue anyways)

**Comment by 27md** [comment]
nope he isn't, and i was using 1.3 at first i only downgraded to see if the problem will be solved, i'll upgrade to 1.3 and reply  to this if the log is the same

**Comment by 27md** [comment]
```
<W>2020-03-29 22:40:35.457 Murmur 1.3.0 (1.3.0) running on OSX: 10.15.3 19D76: Booting servers
<W>2020-03-29 22:40:35.461 1 => Server listening on 192.168.1.11:64738
<W>2020-03-29 22:40:35.472 1 => Announcing server via bonjour
<W>2020-03-29 22:40:35.473 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.
<W>2020-03-29 22:40:43.509 1 => <1:(-1)> New connection: 40.89.147.30:51576
<W>2020-03-29 22:40:43.556 1 => <1:(-1)> Connection closed: The remote host closed the connection [1]
<W>2020-03-29 22:40:49.938 1 => <2:(-1)> New connection: 40.89.147.30:51583
<W>2020-03-29 22:40:49.975 1 => <2:(-1)> Connection closed: The remote host closed the connection [1]
<W>2020-03-29 22:41:00.568 1 => <3:(-1)> New connection: 40.89.147.30:51595
<W>2020-03-29 22:41:00.674 1 => <3:(-1)> Connection closed: The remote host closed the connection [1]
```
this is on 1.3.0 so yes i think it's the same

**Comment by 27md** [comment]
also worth noting that it did work like 3 times so far, if i turn on the autoreconnect thing and leave it it sometimes work but rarely

**Comment by Krzmbrzl** [comment]
I just checked and `Connection closed: The remote host closed the connection [1]` is the normal message for when a client disconnects from the server. Thus it might still be a client issue after all.

Some more questions for you:
1. Are you seeing a `Connecting to server XY` message in Mumble's chat/log when connecting to your server?
2. Could you please start the server with the `-v` option? That way debug messages are logged well. Maybe there's something in there that gives us a clue as to what is going on.
3. Could you also post the client log of your friend please?
4. Could you post the address of your server here so I can try it out myself?

From the input that has been provided so far, I think that the connection might be dropped somewhere in
https://github.com/mumble-voip/mumble/blob/310497a40054babeec7b39cfd9c1415b6cb9423d/src/mumble/ServerHandler.cpp#L672

**Comment by 27md** [comment]
![Screen Shot 2020-03-30 at 3 08 55 PM](https://user-images.githubusercontent.com/38043056/77915878-b8838580-7287-11ea-9d7b-267e325f8c02.png)
, i started the server with -v and nothing new shows up
i'll reply to this with the client log of my friend once he replies
and i don't have a static IP but here's a ddns i'll try to update it with my IP often mumbleserver.ddns.net

**Comment by Krzmbrzl** [comment]
Now wait a sec. I think there is our Problem right in your chat-log: `SSL verification failed`. That's why the connection is being dropped. Does your friend get the same message in his/her chat-log?

I did get the same error message in my client after I tried connecting to your server and not accepting the self-signed certificate. Any chance you did that as well? (This is done by the popup that jumps into your face when you first connected to your server)

**Comment by 27md** [comment]
hmm weirdly now i am able to connect through one vpn around 1/10 trials (VPN IP is fixed) though i still get the error sometimes, i'm not sure if he does i'll ask him but i get [15:51:49] Server connection failed: The remote host closed the connection. before i get the certificate trust pop up, i think i accepted it but i can't be 100% sure as i'm trying to disconnect and reconnect to get the same pop up again but i'm not getting it :/

**Comment by 27md** [comment]
i restarted both client and server, still can't get that pop up and it still connects when i keep trying for like 10 times 🤷‍♂️

**Comment by Krzmbrzl** [comment]
>  i get [15:51:49] Server connection failed: The remote host closed the connection. before i get the certificate trust pop up

Yeah I now have the same problem xD

I think it might be worth a try to clean the server. For that you'll have to remove/rename the `murmur.sqlite` database that should have been created in the directory you started `murmur` (the server).
If you spent some time configuring murmur I'd suggest a rename instead of removing it (to e.g. `murmur.sqlite.back`).

This should clear everything the server has stored and thus once you start it again, it'll be a completely fresh instance.

**Comment by 27md** [comment]
so i restarted dsl to get a new ip and i got the pop up again and i made sure to accept, it still connects once and fails a lot, i'll do that and check but i doubt it would fix it as i didn't do any configuration other than putting my ip, and when i ran 1.2.19 server i didn't copy the files over but i'll try anyway

**Comment by 27md** [comment]
so i'm able to connect with my VPN, will have my friend try to connect too and let you know :)

**Comment by 27md** [comment]
my friend was able to connect so i'll keep testing it through the day and let you know if there's any other issues, thanks for your time :)

**Comment by 27md** [comment]
one last issue.... he keeps hearing his voice echo and i can't enable echo cancelation cause its grayed out

**Comment by Krzmbrzl** [comment]
Glad to hear it's working now - whatever the cause was, I hope it's gone now :)

> he keeps hearing his voice echo and i can't enable echo cancellation cause its grayed out

Are you using normal speakers instead of a headphone?
I think echo-cancellation only works for your own voice as hi hearing himself due to his audio being played through your normal speakers is not really an echo (in the physical interpretation of it anyways).

If echo cancellation is disabled (grayed out), then your audio output system doesn't appear to support it...

**Comment by 27md** [comment]
headphones not speakers, i'll try to play around with the settings to fix it. sorry to have wasted your time :)

**Comment by Krzmbrzl** [comment]
No problem :)
