### ISSUE TITLE
Unable to start on Mac OS X 10.15.4

### ISSUE THREAD

**Issue by dns2utf8** [mumble-voip/mumble#4016]
**Describe the bug**
Unable to start

**Steps to Reproduce**
1. Download Binary
2. Open and Move it to Applications
3. See the warning dialoge

**Expected behavior**
Mumble starting

**Screenshots**
<img width="541" alt="image" src="https://user-images.githubusercontent.com/739070/77855150-24111880-71de-11ea-9f8b-03e79cc671bf.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.4
 - Version: Mumble 1.3.0

**Additional context**
This is a fresh installation

**Comment by Krzmbrzl** [comment]
This appears to be Apple "knowing best" what's good for you :facepalm:

I don't use a Mac so I cma only provide limited support for it. Googling the issue brought up https://www.addictivetips.com/mac-os/fix-cannot-check-for-malicious-software-error-on-macos/
Could you try the steps described there and see if that works?

Btw I'm assuming you got Mumble from the official mumble.info site, right?

**Comment by dns2utf8** [comment]
Yes I downloaded the application from https://www.mumble.info/downloads/
I verified it again today with the latest Updates.

**Comment by Krzmbrzl** [comment]
Did you try the steps suggested in the link I gave you?

**Comment by tylerjwatson** [comment]
Hi

macOS security stops you from opening non-store stuff without first right-clicking it and opening it.  You'll be able to open Mumble after dragging it to the Applications folder by right-clicking it, and choosing **Open**

![image](https://user-images.githubusercontent.com/5001408/80330664-1e642c80-8889-11ea-9383-e74678d25f8f.png)

_Note: This only needs to be done once, then macOS will allow you to open the App any way you like_

**Comment by Krzmbrzl** [comment]
@tylerjwatson thanks for the input! That's definitely good to know :)
