### ISSUE TITLE
Cannot assign keybindings under Mac OSX

### ISSUE THREAD

**Issue by netzego** [mumble-voip/mumble#4020]
Cannot assign keybindings under Mac OSX.

**Steps to Reproduce**
1. Go to Configure -> Settings -> Shortcuts
2. Click on 'Add'
3. Click on 'Function' and select something
4. Click on 'Shortcut'
5. Press a random key
6. Nothing happens

 - OS: Mac OSX 10.15.3
 - Version: 1.3.0 (precompiled version form https://www.mumble.info/)

**Comment by Krzmbrzl** [comment]
What's the 'Anykey'?

**Comment by netzego** [comment]
:) i meant any key -- none of the keys is working

**Comment by casipw** [comment]
For me, on macOS 10.13.6 + Mumble 1.3.0, the keys Alt/Option, Control and Command worked. On a modern MacBook Pro (probably latest macOS, don't have it at hand now), they didn't.

**Comment by Krzmbrzl** [comment]
> sorry, i thougt this joke is obvious 

Maybe if I wouldn't suspect Apple of doing the weirdest stuff it would have been xD

We had some trouble with shortcuts on macs before: #3976
There the issue seemed to have vanished once Mumble was started from a terminal. Have you tried that?

**Comment by netzego** [comment]
> There the issue seemed to have vanished once Mumble was started from a terminal.

Not jet. But, thx for the info. I let you know, if this solves the problem -- On the next meeting i will try this with one of those weired "computers" ;)

**Comment by Silox** [comment]
Got the same issue, starting from commandline (`open -a Mumble`) yields no different results.

**Comment by Krzmbrzl** [comment]
Could you post the output of the terminal after having started Mumble?

Besides I think the trick only works if you start Mumble by starting the executable directly and not via `open`. Not sure though...

**Comment by Silox** [comment]
@Krzmbrzl Ah, that works. For others:

```
cd /Applications/Mumble.app/Contents/MacOS 
./Mumble
```
Accept all OSX security notifications and allow Accessibility access to Terminal. Ctrl-C te process, open it again, and you should be able to add shortcuts.

It's a workaround though, I don't really like to give Terminal those Accessibility permissions.

**Comment by Krzmbrzl** [comment]
@Silox thanks for the instructions :+1:

Any idea what might be the cause of this? Or why you weren't asked for these permissions when starting Mumble normally?

**Comment by Silox** [comment]
Hmm, no, not a clue. I fixed it for the Mumble app itself now by taking away Mumbles permissions and re-adding them.

Steps followed:

0. Close Mumble if open
1. Go to OSX Settings
2. Select "Security and privacy"
3. Click the lock, fill in credentials
4. Go to "Accessibility"
5. Select Mumble
6. Click the - sign
7. Click the + sign
8. Navigate to your Mumble
9. Add it
10. Restart Mumble

**Comment by Krzmbrzl** [comment]
@netzego does the procedure provided by @Silox work for you as well?

**Comment by hutchisr** [comment]
Giving Mumble Accessibility Permissions didn't work for me in Ventura, but adding it to Input Monitoring  permissions did.

**Comment by nullx8** [comment]
can confirm @TomNaessens solution still works.
just updated to 1.4.287 and experienced the same problem.

removing the Accessibility permission and re-adding it solved the problem.

**Comment by kaalvoetranger-88** [comment]
can confirm @TomNaessens solution still works for 1.5.735  

Removing the Accessibility permission and re-adding it solved the problem for me as well.
