### ISSUE TITLE
DBus call to getCurrentUrl responds with empty string

### ISSUE THREAD

**Issue by floriansnow** [mumble-voip/mumble#4027]
**Description**
When calling the DBus method `getCurrentUrl`, it responds with an empty string instead of the URL.

**Steps to Reproduce**
1. Run client.
2. In a terminal, run `dbus-send --print-reply --session --type=method_call --dest=net.sourceforge.mumble.mumble / net.sourceforge.mumble.Mumble.getCurrentUrl`
3. The response is an empty string.

**Expected behavior**
The response should contain a Mumble URL, like the call to `getTalkingUsers` responds with a list of talking users.

**Desktop:**
 - OS: Debian 10 (Buster)
 - Version: Mumble 1.3.0

**Comment by Krzmbrzl** [comment]
Can't reproduce with current master on KDE Neon 5.18:

```
$ dbus-send --print-reply --session --type=method_call --dest=net.sourceforge.mumble.mumble / net.sourceforge.mumble.Mumble.getCurrentUrl
method return time=1585815724.003103 sender=:1.51 -> destination=:1.54 serial=37 reply_serial=2
   string "mumble://Krzmbrzl@mumble2.linux-power.de:64737?version=1.2.0"
```

**Comment by Krzmbrzl** [comment]
I compiled the 1.3.0 and wasn't to reproduce this bug either.

Is DBus working for you in other scenarios?

**Comment by floriansnow** [comment]
Wow, thank you for looking into this so quickly! DBus works for me for other calls to Mumble:
```
$ dbus-send --print-reply --session --type=method_call --dest=net.sourceforge.mumble.mumble / net.sourceforge.mumble.Mumble.getTalkingUsers
method return time=1585818919.397124 sender=:1.399 -> destination=:1.470 serial=193 reply_serial=2
   array [
      string "florian.snow"
   ]
```

Perhaps this is a bug in the Debian version. The exact version number here is 1.3.0~git20190125.440b173+dfsg-2, so I will check if I can reproduce the bug with a version compiled from source and possibly file this with Debian if it turns out it's only in that version.

**Comment by Krzmbrzl** [comment]
> 1.3.0~git20190125.440b173+dfsg-2

To me this looks suspiciously like a snapshot build from 25th of January 2019. If that was the case, then that'd be about 7 months of development work short when compared to the stable 1.3.0 release.

> I will check if I can reproduce the bug with a version compiled from source and possibly file this with Debian if it turns out it's only in that version.

:+1:

**Comment by floriansnow** [comment]
Actually, with current master, I get the same result:
```
dbus-send --print-reply --session --type=method_call --dest=net.sourceforge.mumble.mumble / net.sourceforge.mumble.Mumble.getCurrentUrl
method return time=1585821640.097746 sender=:1.486 -> destination=:1.490 serial=27 reply_serial=2
   string ""
```

**Comment by Krzmbrzl** [comment]
Might this be a problem of the server? Which server have you tried this on? And could you try it on `umble2.linux-power.de:64737` as I did, please :thinking:

**Comment by floriansnow** [comment]
Ok, it is actually a problem with that specific server, but I have no idea why.  I tried several things now, but I cannot reproduce the issue outside of that server.  If I self-compile any server version, it works, if I install the same Debian package in the same version locally, it also works.  So it's not a bug in Debian either.  If I find out anything, I will post it here, but for now, I am out of ideas.  Sorry for the unnecessary bug report!

**Comment by Krzmbrzl** [comment]
> If I find out anything, I will post it here

:+1:

> Sorry for the unnecessary bug report!

No worries. Glad we could (kinda) resolve it :)

**Comment by floriansnow** [comment]
Ok, I tested a bit more because I couldn't let this go and I can now reproduce it with a build from master for both the server and the client.  I get a proper response as long as I am in the root channel, but as soon as I move to any other channel, I get the empty response.
