### ISSUE TITLE
PPA build for Ubuntu 18.04: No option to choose jackd audio system

### ISSUE THREAD

**Issue by mark-orion** [mumble-voip/mumble#4036]
There seems to be no support for jackd in the builds for Ubuntu 18.04 "Bionic". Both audio input and output only offer to choose between ALSA, OSS and Pulseaudio.
Jackd is installed and configured on my system.

**Comment by Krzmbrzl** [comment]
Which version is in the repository?

**Comment by mark-orion** [comment]
> Which version is in the repository?

1.3.0-1. I tried both the release and snapshot repos. Both have the same problem. However a machine running Ubuntu 19.10 using the same repo shows the jackd option.

**Comment by Krzmbrzl** [comment]
@davidebeatrici any idea on this one?

**Comment by davidebeatrici** [comment]
The releases on our PPA don't provide support for JACK at the moment.

@mark-orion Are you sure APT is not installing the package from Ubuntu's repository instead?

https://packages.ubuntu.com/eoan/mumble
