### ISSUE TITLE
Microphone mute state is inconsistent between server and client

### ISSUE THREAD

**Issue by leonlag** [mumble-voip/mumble#4043]
**Describe the bug**
Some user on my mumble server seem to be having an issue where their client thinks they are unmuted but they are actually muted on the server.
Unfortunately I can't reproduce this issue so I'm starting a discussion to see if this is something that is limited to our server instance.

**Expected behavior**
The mute state between client and server is consistent. 

**Desktop**
 - OS: Windows 10
 - Version: Mumble 1.3

**Server**
 - OS: fedora 31
- Version: Murmur 1.3

Currently the fix is for the others to notice it and then tell the user to reconnect.

**Comment by davidebeatrici** [comment]
#4005

**Comment by Krzmbrzl** [comment]
To give some more context: Does this happen if the respective users mute/unmute themselves quickly in a row or when they have performed a lot of other actions in a short period of time (e.g. sending a text-message, switching channel, mute/unmute, deaf/undeaf)?

**Comment by leonlag** [comment]
I suppose the users hitting the rate limit seems like the most likely thing. I have changed the servers config to something less aggressive. I'll report back in a week or so to see if things have improved.

**Comment by leonlag** [comment]
Seems like this was it since it has not happened since I changed the rate limits

**Comment by Hartmnt** [comment]
I would like you to consider re-opening this issue, as I think there are two different sides to this problem. While, yes, the server should announce the rate-limit to the clients and the clients should respect the rate-limit as described in #4005, I would consider the fact that the UI on the client can become out of sync to the user-state as reported by the server as a different bug.

Furthermore, this bug/rate-limit is easily reached with a default settings server/client by quickly toggling the self-mute button.

**Comment by Krzmbrzl** [comment]
There is just no way to prevent out-of-sync states when rate-limiting kicks in, unless you make the client only a facade that is completely steered by the server's messages, which I think is not desirable
