### ISSUE TITLE
MURMUR - can't ban user that connected to mumble server

### ISSUE THREAD

**Issue by wabash1** [mumble-voip/mumble#4067]
**Describe the bug**
User connected via a tor exit node that did not hit my tor autoban and is not bannable via mumble client as it causes a user crash, the user kept spamming disconnect and reconnect, can't read info. Checking logs it adds a huge space in the log. I've banned the /24 block that the user connected from.

**Screenshots**
![image](https://user-images.githubusercontent.com/3643969/79161851-324c6080-7daa-11ea-96f8-9fd7e01fa44a.png)

![image](https://user-images.githubusercontent.com/3643969/79161921-514af280-7daa-11ea-93fc-7697ed798d47.png)

![image](https://user-images.githubusercontent.com/3643969/79162281-0087c980-7dab-11ea-8529-4c78c93e593f.png)

![image](https://user-images.githubusercontent.com/3643969/79162436-42187480-7dab-11ea-9844-dd07886da9f2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server Linux 
 - Version: Murmur 1.3

**Comment by TredwellGit** [comment]
>is not bannable via mumble client as it causes a user crash

Can you elaborate on this? Do you mean that your client is crashing or do you mean that your client is disconnecting? If it is a crash or freeze and not a disconnect, then what exactly triggers it?

**Comment by wabash1** [comment]
Right clicking on the user causes a crash for the client, presumably trying
to load a ton of text all at once. The blank spots in the logs are part of
that and I scrolled through them for a couple minutes without reaching a
non blank spot.

**Comment by TredwellGit** [comment]
@wabash1 Just right clicking or right clicking and selecting something from the menu?

@davidebeatrici @Krzmbrzl This seems like a `priority/P0 - Blocker` or `priority/P1 - Critical` issue. In the screenshots, the malicious client is setting the version to an excessively large value; there should be a limit on the size of these values both client and server side.

**Comment by Krzmbrzl** [comment]
It seems like the client is setting the OS version to this huge value... Will look into this :eyes:

**Comment by wabash1** [comment]
@TredwellGit Sorry for not clarifying, right click > ban > ban reason came up and the client crashed and right click > information also crashed the client.

**Comment by Krzmbrzl** [comment]
@wabash1 your screenshot seems to be cut-off.
Could you copy&paste the log-excerpt you posted as a screenshot here?

**Comment by Krzmbrzl** [comment]
And the client log (potentially with a backtrace) would be useful as well

**Comment by wabash1** [comment]
![image](https://user-images.githubusercontent.com/3643969/79195914-16be7580-7dfd-11ea-91e7-c90bc2e19204.png)

I assure you it was not cut off, there's lines and lines of blank spaces in the log after a ton of W's, do you have an email I can send you a log directly?

**Comment by Krzmbrzl** [comment]
> I assure you it was not cut off, there's lines and lines of blank spaces in the log after a ton of W's

I believe you about the empty space (probably newlines btw) but in your screenshot there seems to be a dollar sign after the Ws which seems cut off a bit, so I was wondering whether there might be something behind that...

You can send me the log at
https://github.com/mumble-voip/mumble/blob/7ed7d95f4bee4a8aac437862cf6d4455de6ca24a/.mailmap#L122
(either will work)

**Comment by Krzmbrzl** [comment]
Oh and btw.: With `crash` you really mean that Mumble closed on you, right? Not "just" freeze into place and becoming unresponsive?

'cause with what I have tried so far, I was only able to get the client freeze for some time when opening the Information panel for a user.

**Comment by wabash1** [comment]
I apologize, I did not get a measurement given the urgency, it does seem that you could be right that it would have eventually gone away but these users were constantly disconnecting and reconnecting. I have sent you the server log to your email, I do not have the client log.

**Comment by Krzmbrzl** [comment]
> I apologize, I did not get a measurement given the urgency, it does seem that you could be right that it would have eventually gone away but these users were constantly disconnecting and reconnecting

So it *was* a freeze and not a crash?

**Comment by wabash1** [comment]
Correct it appeared to be a indefinite freeze.

**Comment by Krzmbrzl** [comment]
Okay great (well not that it happened but this at least means I can reproduce).

If you are ever going to report this kind of bug again (be it here or elsewhere), please differentiate between a **freeze** (application becoming unresponsive) and a **crash** (application terminates unwanted and immediately).
This will help the devs figuring out what's actually going on :)

I'm glad we figured stuff out though. The fix is probably pretty easy: Restrict the size of strings we read in from somewhere. Will try to implement this now.
