### ISSUE TITLE
Option to disable the public list of servers.

### ISSUE THREAD

**Issue by argus33** [mumble-voip/mumble#4070]
**Context**
would be nice to have a feature to disable showing the public internet servers... keep them from populating.  i run this as a lan voice chat as intended and some of the server name/descriptions are not appropriate for kids... Nothing against free speech and all but i prefer to have some means of not corrupting my kids to early. 

**Describe the feature you have in mind**
check box in the channel tree section of the user interface to disable/enable the public internet server list

**Describe alternatives you've considered**
sorry i do not have any other idea for solutions than to use something else and i think this is a very useful tool and is very well put together... Thankyou

**Additional context**

**Comment by Krzmbrzl** [comment]
On my machine the Public servers don't even start to show until I explicitly start looking into them:
![Mumble_ServerBrowser](https://user-images.githubusercontent.com/12751591/79469891-07a81500-8001-11ea-8966-659f4a60e99f.png)

I don't really see how an extra checkbox would add any benefit here.

Does the ServerBrowser look different for you? If so, which version of Mumble are you using and on what OS?

**Comment by Kissaki** [comment]
> check box in the channel tree section of the user interface to disable/enable the public internet server list

I am a little confused what you mean/envision here? Channel tree implies you are talking about channels on a server. But it seems more likely you mean within the server list window?

We already have a hidden option to disable public server lists.

This was implemented in fd5a9b12e082e6292b3fded923c15efc6efe7ade

> Added ui/disablepubliclist which if set to true removes the
> public server list in the connect dialog. This option isn't
> available in the UI and is meant for customizing setups in
> specific deployments.
> 
> On windows you can enable the option by creating a string key
> disablepubliclist under HKEY_CURRENT_USER\Software\Mumble\Mumble\ui
> with the value true.

**Comment by Kissaki** [comment]
Someone very recently [asked about it on our forums](https://forums.mumble.info/viewtopic.php?f=5&t=4380) as well, where I searched this commit for. We should at least document this in our more elaborate documentation even if we do not add it as a in-client option.

**Comment by krono86** [comment]
I can’t see the public servers list in Mumble 1.3.0 on OS X 10.11.
Is it disabled by default?

**Comment by Krzmbrzl** [comment]
@krono86 no it's not. Also this doesn't really fit into this issue. If you need help finding out what's wrong, please create a separate issue :)

**Comment by streaps** [comment]
I also don't want Mumble Client to automatically connect to various servers without my consent (the directory server and then pings to listed servers).

**Comment by Krzmbrzl** [comment]
> I also don't want Mumble Client to automatically connect to various servers without my consent (the directory server and then pings to listed servers).

I'm not entirely sure right now but from what I remember, the pinging only starts once you start unfolding the public server list. Thus if you don't touch it, it probably doesn't ping these servers. (It'll probably still ping the Mumble server for requesting the list in the first place though :thinking: )

**Comment by streaps** [comment]
Let's say I want to track the IPs of Mumble client users in a country. I host a mumble server with an entry in the public server list and log all pings.

**Comment by Kissaki** [comment]
> the pinging only starts once you start unfolding the public server list

That is indeed correct.

**Comment by rwaight** [comment]
+1 for this request as an option in the UI.

> We already have a hidden option to disable public server lists.
> This was implemented in [fd5a9b1](https://github.com/mumble-voip/mumble/commit/fd5a9b12e082e6292b3fded923c15efc6efe7ade)

I am very thankful for the hidden option to disable public server lists, but it would help to have a check box in the UI.  If the `User Interface -> Channel Tree` section is not appropriate, would the `Network -> Mumble services` section be a more appropriate place for this?

**Comment by davidebeatrici** [comment]
Definitely.

**Comment by streaps** [comment]
The user should be informed about the implications and if they still want to enable the public directory and pings.

**Comment by TimMThomas** [comment]
Hey there,
I wanted to ask if this still is a desired feature and if i could try to implement this :)

**Comment by argus33** [comment]
I would like to have the feature... I am using the linux version what ever was the one in apt-get repository at the time of the post but if you update it for a new version I will download the updated version for sure... thanks for looking into this... sorry I didn't include all the information that I should when I wrote the feature request but I'm not the greatest and thinking about version and platform just figured that would be very similar Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Tim-M Thomas <notifications@github.com> Date: 6/16/20  12:58 PM  (GMT-05:00) To: mumble-voip/mumble <mumble@noreply.github.com> Cc: argus33 <argus33r@gmail.com>, Author <author@noreply.github.com> Subject: Re: [mumble-voip/mumble] Option to disable the public list of servers. (#4070) 
Hey there,
I wanted to ask if this still is a desired feature and if i could try to implement this :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mumble-voip/mumble/issues/4070#issuecomment-644889619",
"url": "https://github.com/mumble-voip/mumble/issues/4070#issuecomment-644889619",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Krzmbrzl** [comment]
@TimMThomas absolutely! We'd be happy to accept a PR :)
