### ISSUE TITLE
Quotes don't italicize in Text Messages

### ISSUE THREAD

**Issue by bkacjios** [mumble-voip/mumble#4075]
While working on a math command for my bot I discovered that putting something inside asterisks causes it to be bold in chat. This made me start to wonder if there were other markdown operations enabled. After some digging, I found some really old, uncommented, code which appears to be the source.

https://github.com/mumble-voip/mumble/blob/2c22eec08525d88cf275b4bc4a1a4bc671409ff2/src/mumble/TextMessage.cpp#L34

I found that there was some intention to make things inside quotations italic too, but it doesn't seem to actually work. I think the issue is the pattern for italics isn't escaped correctly like the bold one is, because when I tested the pattern on regexr.com it worked fine. Anyway, figured I would report this very weird and minuscule bug.

To be honest though, I really don't want quotes in chat italicized. If anything, I fell this should be changed to be more inline with markdown. Asterisks should be italic, double asterisks should be bold, in my opinion. The fact that this isn't even documented anywhere seemed super strange to me.

**Comment by Krzmbrzl** [comment]
#2945 contains a request for markdown support.

Attempting to render quotes italic is actually a nice touch (in my opinion) as it suits e.g. citations very well.
However I agree that this is probably not what everyone likes. Thus I think if we were to keep it, we should add an option for it. 

However I think quoting can be supported better if we implement markdown support. In that case I think we can easily drop the logic for general text in quotation marks...
