### ISSUE TITLE
Error: A referral was returned from the server.

### ISSUE THREAD

**Issue by pierremestrez1976** [mumble-voip/mumble#4077]
**Describe the bug**
When opening Mumble, an error message popup.
Error: A referral was returned from the server.
![Mumble](https://user-images.githubusercontent.com/61747142/79642135-20006700-819c-11ea-9176-433a93794183.jpg)

**Steps to Reproduce**
Open Mumble 1.3.1 RC1

**Expected behavior**

**Screenshots**
See attachment

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 64bits
 - Version: Mumble 1.3.1 RC1

**Comment by Krzmbrzl** [comment]
This error is due to an expired certificate we have used to sign the binary.

@davidebeatrici is already working on fixing this

**Comment by pierremestrez1976** [comment]
> This error is due to an expired certificate we have used to sign the binary.
> 
> @davidebeatrici is already working on fixing this

Thanks, looking forward to test the #3319 :-)

**Comment by Krzmbrzl** [comment]
That won't be included in 1.3.1.
1.4.0 will be the first version that includes this feature. If you want to try it out, you'll have to either build Mumble yourself or get yourself a snapshot release (which should reappear in the foreseeable future)

**Comment by Krzmbrzl** [comment]
The 1.3.1 rc binaries in the release tab should now be updated and properly signed.

If the error persists, please let me know
