### ISSUE TITLE
Windows 1.3.1 rc1 still wrongly signed

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#4084]
Still gives the error "A referral was returned from the server." with mumble.exe even though there is no error with murmur.exe according to the file I downloaded from https://github.com/mumble-voip/mumble/releases/download/1.3.1-rc1/mumble-1.3.1-rc1.winx64.msi

**Comment by trudnorx** [comment]
And the .msi is not signed:

![image](https://user-images.githubusercontent.com/42674312/79752916-51507280-8315-11ea-865d-aab04d06af73.png)

**Comment by davidebeatrici** [comment]
My fault: apparently I didn't replace that file on GitHub, thus you downloaded the one that was signed with @mkrautz's expired certificate.

Thank you for reporting the issue!
