### ISSUE TITLE
Mac CI builds missing libprotobuf.22.dylib

### ISSUE THREAD

**Issue by seantalts** [mumble-voip/mumble#4088]
**Describe the bug**
I can't open the Mumble executables produced by Continuous Integration on the master branch or recent PRs, it seems. 

**Steps to Reproduce**
https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=1474&view=artifacts&type=publishedArtifacts
Download the MacOS Installer and try to run the file.

![image](https://user-images.githubusercontent.com/805356/79791463-59abac00-831b-11ea-8c5c-3efe2f7504c1.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Catalina
 - Version: master

**Comment by Krzmbrzl** [comment]
Yes that is known. I tried fixing it up in #4042 but concluded that making it work on a non-Dev machine is not feasible.
As I see it, this would require us to create a static build (including qt) and this is just not really possible on the CI as we'd have to build all dependencies ourselves. 

If you have an idea about fixing it, please let me know. It's a bit disappointing as it stands but as I said I couldn't find a way to fix it...

**Comment by davidebeatrici** [comment]
We should probably download our environment, as we're doing for Windows.
