### ISSUE TITLE
configuring / quitting Mumble does not work but causes 100% CPU load

### ISSUE THREAD

**Issue by rkoe** [mumble-voip/mumble#4092]
**Describe the bug**
The graphical configuration-dialog causes Mumble to hang. So, no configuration is possible.
This makes Muble quite unusable.

**Steps to Reproduce**
1. start mumble
2. Configure -> Settings...
3. Click "OK" or "Apply"

Now, mumble hangs, and can only be killed / aborted with Ctrl-C on the commandline.

strace log:
```
...
writev(4, [{iov_base=";\3\5\0\36\0`\2\0\0\0\0?\1\0\1u\2\24\0\202\3\n\0\31\0`\2\36\0`\2"..., iov_len=76}], 1) = 76
poll([{fd=6, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}, {fd=18, events=POLLIN}, {fd=29, events=POLLIN}], 5, 18) = 1 ([{fd=13, revents=POLLIN}])
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(13, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="#\203\20\0\2\0\0\0\20\0\t\0\25ZK\16\1\0\0\0\t\0\2\0\0\0\0\0\0\0\0\0"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 80
recvmsg(13, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(13, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=4, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=4, revents=POLLOUT}])
writev(4, [{iov_base=";\3\5\0\36\0`\2\0\0\0\0\307\2\341\2V\0\33\0\202\3\n\0\31\0`\2\36\0`\2"..., iov_len=76}], 1) = 76
futex(0x1ab7d80, FUTEX_WAIT_PRIVATE, 0, NULL
```

**Desktop (please complete the following information):**
 - OS: Linux (NixOS)
 - Version: Mumble 1.3.0

**Comment by Krzmbrzl** [comment]
Can't reproduce on my Linux machen running KDE Neon. Also never heard of this before...

Does the CPU usage go up when this happens?

I assume you have Mumble installed via the software repositories and didn't compile it yourself, right? 'cause if you did, it'd be handy if you could compile a Debug build and attach gdb, interrupt when the freeze happens and then provide a back trace.

**Comment by rkoe** [comment]
Yes, CPU usage does go up to 100% by mumble.

I have not compiled it myself, but used the NixOS-distro-version. See my strace-log for what happened.

**Comment by Krzmbrzl** [comment]
> See my strace-log for what happened.

This doesn't tell me anything :shrug:

**Comment by Krzmbrzl** [comment]
Did you try reaching out to the package maintainers? Given that I have never heard of this bug before, it either seems to be something very specific to your machine or something with the package in the nixOS repositories.

If the problem is not related to the specific package on nixOS, I think you'd have to build Mumble from source with debug symbols and then provide a backtrace of when the freeze occurs :thinking: 

I just tried starting nixOS in a VM but the installer drops me into a console and I don't have the time nor the motivation to get to know how I'm supposed to set it up, so that I can run a graphical application like Mumble.

**Comment by rkoe** [comment]
I can try to compile it with debug-information when I have the time.

But suddenly using 100% CPU certainly is not caused by the package maintainers or a "specific machine", but by Mumble itself.

**Comment by Krzmbrzl** [comment]
> But suddenly using 100% CPU certainly is not caused by the package maintainers or a "specific machine", but by Mumble itself.

Yeah sure. It certainly is the Mumble application that consumes the CPU (most likely because it runs into some sort of endless loop). But my suspicion is that the package maintainers have changed the code and that this is responsible for the bug. This would at least explain why it doesn't show up on other devices (Opening the preferences is a very common task after all).

Now I don't want to exclude the possibility that the bug is indeed in our code base and that it only surfaces under some bizarre conditions you happen to have on your machine though :shrug:

**Comment by streaps** [comment]
The only code modification I found in https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/networking/mumble is this patch:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/mumble/fix-rnnoise-argument.patch

**Comment by trudnorx** [comment]
I recall having problems with settings option taking long to open or crashing in the past. This happened to me on Windows when messing with the exclusive setting. Apparently, enabling it sometimes doesn't work without a restart, and if you keep fiddling with the setting there's a crash. May have to do with this issue. Should be looked into anyway.

**Comment by Krzmbrzl** [comment]
> exclusive setting

What setting is that (where can I find it)?

**Comment by trudnorx** [comment]
Exclusive microphone or sound output

**Comment by Krzmbrzl** [comment]
Coming back to the original issue. When clicking Ok or Apply, this code is executed
https://github.com/mumble-voip/mumble/blob/dd9c261c521893f68bb75b1cd762aa7a6a873b56/src/mumble/ConfigDialog.cpp#L178-L196

As you can see there is no possibility of an endless loop in that code directly. However if we look at 
https://github.com/mumble-voip/mumble/blob/dd9c261c521893f68bb75b1cd762aa7a6a873b56/src/mumble/Audio.cpp#L283-L314
we can see the `while` loop which can potentially create an endless loop, if some other area of the code keeps a pointer to the AudioInput or AudioOutput.

`Audio::start` doesn't have any `while`-loops in it.

Thus I think if it freezes, then it'll probably freeze in said `while`-loop above

**Comment by Krzmbrzl** [comment]
@rkoe what audio interface are you using?

**Comment by trudnorx** [comment]
If you launch Mumble with the exclusive option already on, you can change it+click OK an infinite number of times without it crashing, I think, and the setting takes effect just by clicking OK, but if you're setting it to enabled for the first time, then the next time you change it it crashes, moreover, the setting requires a restart to take effect. No other applications are conflicting with exclusive mode in my system.

**Comment by Krzmbrzl** [comment]
For the the `exclusive` option is disabled for all interfaces anyways, so this might be hard to check...

**Comment by rkoe** [comment]
> @rkoe what audio interface are you using?

System: Alsa
Device: [default] Default Audio Device (via PulseAudio)

**Comment by rkoe** [comment]
> https://github.com/mumble-voip/mumble/blob/dd9c261c521893f68bb75b1cd762aa7a6a873b56/src/mumble/Audio.cpp#L283-L314
> 
> we can see the `while` loop which can potentially create an endless loop, if some other area of the code keeps a pointer to the AudioInput or AudioOutput.

For me, it looks like:
- Bug 1: Bad design: Busy waiting loop. Don't do that. Even in unexpected cases you don't want to use 100% CPU.
- Bug 2: Bad design: Endless loop without any error-message (neither in the GUI nor in the console) and without any timeout.
- Bug 3: The reason why this endless loop is actually triggered (reason not yet known).

**Comment by rkoe** [comment]
Extension: Quitting mumble also causes 100% CPU load.
(GUI window closes, but the Mumble-process does not quit but cause 100% CPU load.)

**Comment by Krzmbrzl** [comment]
Yeah that's likely the same issue

Can you try using a different audio interface (e.g. PulseAudio) and see if the problem persists?

**Comment by rkoe** [comment]
> Can you try using a different audio interface (e.g. PulseAudio) and see if the problem persists?
No.
- I'm already using PulseAudio ("Device: [default] Default Audio Device (via PulseAudio)")
- No matter what I select in the configuration window (for System or Device), clicking OK or Apply always shows the same 100%-CPU-behaviour.

**Comment by toby63** [comment]
Out of curiosity I just tested it on my system (with system monitoring).
Did not occur, not even a slight increase of CPU or RAM.

My system:
```
OS: Debian Testing
Resolution: 1920x1080
Mumble Version (two versions installed):
* 1.3.0+dfsg-1+b2 (debian package)
* 1.3.0 (snap package)

Desktop environment: Xfce 4.14
Qt: 5.12.5+dfsg-9

```

**Comment by toby63** [comment]
@Krzmbrzl @rkoe : 
I might be wrong, but the nixos package of mumble might have more commits added to it:
https://github.com/NixOS/nixpkgs/issues?q=mumble
https://github.com/NixOS/nixpkgs/pull/82505/commits

I could not verify which commits are included in the package though,
because the package site of nixos is very basic, I can't see dates, changelogs etc.:
https://nixos.org/nixos/packages.html?channel=nixos-20.03&query=mumble

Very strange distro, never heard of it.
Sry but I also have no interest in looking further into it :stuck_out_tongue_winking_eye: .

**Comment by rkoe** [comment]
> I might be wrong, but the nixos package of mumble might have more commits added to it:

No, the only code-modification is the small rnnoise-patch, which @streaps already mentioned
(https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/mumble/fix-rnnoise-argument.patch)

> I could not verify which commits are included in the package though,

It uses the 1.3.0 release.

> because the package site of nixos is very basic, I can't see dates, changelogs etc.

Unfortunately, the links to the package-descriptions are currently broken.
The relevant link would be: https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/networking/mumble
(But Nix-package descriptions can be a bit hard to read.)

> Very strange distro, never heard of it.

It's a great distro from a technical point of view, with really nice concepts.
But it's unfortunately still lacking in terms of (non-nerd-)usability and QA.

I guess I'll have to recompile it with debug-information, to track down the bug.

**Comment by Krzmbrzl** [comment]
> I guess I'll have to recompile it with debug-information, to track down the bug.

That'd be great. This would also reveal if the nix-package was indeed altered in a way that caused the bug or not :)

**Comment by toby63** [comment]
@rkoe : 
> No, the only code-modification is the small rnnoise-patch [...]
> It uses the 1.3.0 release.

Ok, might have been a wrong assumption by me (it looked at first as if some things were included, that are different from the upstream version).
Still your maintainers should maybe use a different version name (one patch is still a change).
So it downloads the mumble sources? And thus there are only the three files?
```
#Quote from default.nix:
src = fetchFromGitHub {
      owner = "mumble-voip";
      repo = "mumble";
      rev = version;     
      fetchSubmodules = true;
```

> It's a great distro from a technical point of view, with really nice concepts.

I admit the description provided on the main site sounds interesting, "multiple version of the same package" etc.

@Krzmbrzl 
> > I guess I'll have to recompile it with debug-information, to track down the bug.
> 
> That'd be great. This would also reveal if the nix-package was indeed altered in a way that caused the bug or not :)

Thats probably the best way of solving it :+1: .
