### ISSUE TITLE
Docs missing dependency, possibly

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#4106]
This MIGHT be considered a feature request.  I don't have wiki access currently...

https://wiki.mumble.info/wiki/BuildingLinux#Debian_or_Ubuntu
Version 1.3, my build also wanted me to install:
libjack-jackd2-dev

My Debian-stable doesn't have g15 support, so I might put a note (at least in the 1.3 section -- that's all I've tried building):
"Debian might not have g15 support. You can disable it with qmake CONFIG+=no-g15 or see https://wiki.mumble.info/wiki/BuildingLinux#Finding_missing_dependencies for more information."

**Comment by davidebeatrici** [comment]
Thank you very much for reporting that!

`libjack-jackd2-dev` should not be required, we have to add a required header to the repository.

As for G15 support, you're right.

Feel free to create an account on the wiki.

**Comment by Krzmbrzl** [comment]
As I see it, the g15 stuff has been added to the wiki...
