### ISSUE TITLE
Error finding uuid symbol, by libSM

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#4107]
Building in Debian Jessie (Stable), I get:
/usr/bin/ld: //usr/lib/x86_64-linux-gnu/libSM.so.6: undefined reference to `uuid_unparse_lower@UUID_1.0'

This is at the long linking line:
g++ -Wl,-z,relro -Wl,-z,now -Wl,-O1 -Wl,-rpath,/home/jaggz/miniconda3/lib -o ../../release/mumble .......

I tried adding -luuid to the end, but I still get the same error.
$ ldd /usr/lib/x86_64-linux-gnu/libSM.so.6 does show it finding libuuid:
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x000fd0e80)

* nm -D libuuid.so.1.3.0 | grep uuid_unparse shows it has 'uuid_unparse_lower'.
* The debian libuuid1 package is version 2.33.1-0.1, for what it's worth

This project had the 'same' error:
https://sft.its.cern.ch/jira/si/jira.issueviews:issue-html/SPI-199/SPI-199.html

**Comment by jaggzh** [comment]
The miniconda libuuid was being found first.
I moved it, as per this post (the very bottom):
http://www.programmersought.com/article/97791874444/

**Comment by Krzmbrzl** [comment]
Ah perfect. I was just trying to figure out what was going on. Thanks for reporting your fix :+1:

**Comment by jaggzh** [comment]
:) Thanks for looking into it.
