### ISSUE TITLE
Echo cancellation is greyed out.

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#4108]
This has been quite some time -- I just built from git in the hopes that it would help.
(I'm having a problem being unable to stop echo when using mics and computer speakers).
This is Debian Stable (Buster. Although in another issue report I misreported it as "Debian Jessie")

**Comment by Krzmbrzl** [comment]
I don't have the time right now to look into this. If I haven't answered until sometime tomorrow though, please ping me again as a reminder :)

**Comment by streaps** [comment]
The same in Debian Testing (Raspbian)

**Comment by Krzmbrzl** [comment]
Okay so this seems to be because the respective Mumble audio backend thinks that echo cancellation is unsupported on your system.

https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/AudioConfigDialog.cpp#L378

For PulseAudio this check seems to be whether the name of the current audio output system is the same as the one of the current audio backend:
https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/PulseAudio.cpp#L878-L880

Could you open your client's settings file and look for the variable `output` in the `audio` category and report back what value this is set to?

**Comment by jaggzh** [comment]
output=ALSA
(For what it's worth, if I set mumble's system to ALSA, and apply (and even restart mumble), it does not make the Echo Cancellation field activated again).  (I wonder why it needs them the same anyway...)  (...So many parenthesis.)

**Comment by davidebeatrici** [comment]
Our ALSA backend doesn't support echo cancellation:
https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/ALSAAudio.cpp#L113-L115

The reasoning behind `canEcho()` is that we can retrieve the echo device associated with the output one, when using audio systems such as PulseAudio and WASAPI.

ALSA doesn't provide a function for that.

Ideally we should remove the limitation and let the user choose a specific backend and device for the echo input.

**Comment by jaggzh** [comment]
Is there a way, like a build-time option, to set PA as the backend?

**Comment by davidebeatrici** [comment]
You can set `output=PulseAudio` in the configuration file.

However, if Mumble only shows ALSA it means that the other backends are not available.
They were disabled at compile time or they're not installed on your system.

Raspbian only has ALSA by default.

**Comment by jaggzh** [comment]
(I"m on a full desktop).  It re-sets it to ALSA even if I set it by hand (with mumble not running at the time).
It does list PulseAudio in the settings window, by the way.
INSTALL only lists an option to DISABLE pa support ("CONFIG+=no-pulseaudio"), which I imagine would prevent it from being listed at all.

**Comment by jaggzh** [comment]
Okay, I think I got it.  I didn't understand this earlier.  From the UI we can set the Output audio and the Input audio to PulseAudio -- and when those match we're good.  EXCEPT, "Apply" is not sufficient. I have to OK the window and re-open it.  So that would be nice to fix.  Nevertheless, what WOULD be a quick "fix" would be to have the Echo cancellation tooltip say "Requires Output and Input audio system to be the same. Some may not support echo-cancellation. May need to re-enter settings to enable."
Something more user-friendly than that though. :)

**Comment by davidebeatrici** [comment]
I agree.

**Comment by Krzmbrzl** [comment]
As this issue is resolved, I'll close it.

I created #4110 to keep track of your improvement-suggestion (which I am already working on in this very moment) :point_up:
