### ISSUE TITLE
Unsupported Ice version on Qt creator when building murmur

### ISSUE THREAD

**Issue by jafarulla15** [mumble-voip/mumble#4109]
I am trying to build murmur server in Qt creator and got this error (Unsupported Ice version):
I am using Qt creator version: 4.11.2 and Qt 5.14.2 and using MinGW_64 and trying on Windows 10 PC.

17:09:36: Running steps for project murmur...
17:09:37: Starting: "C:\Qt\5.13.2\mingw73_64\bin\qmake.exe" "E:\NybSys\BitBucket\PTT_Multicast\04_Mumble_All_Working\Mumble Server\0_New\mumble-master\mumble-master\src\murmur\murmur.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
Project ERROR: Unsupported Ice version
17:09:39: The process "C:\Qt\5.13.2\mingw73_64\bin\qmake.exe" exited with code 3.
Error while building/deploying project murmur (kit: Desktop Qt 5.13.2 MinGW 64-bit)
When executing step "qmake"

I am new at Qt creator and mumble. Please need kind help.

**Comment by Krzmbrzl** [comment]
What ICE version is installed on your system?

**Comment by jafarulla15** [comment]
@Krzmbrzl, thank you.
I have installed Ice-3.6.5.msi and getting same error.
Do I need to do any thing at Qtcreator IDE to get updated Ice version or I don't find any ice installer especially for Qtcreator. 
if you give me some detail instruction, it will be very helpful for me. Thank you for your support.

**Comment by Krzmbrzl** [comment]
> I have installed Ice-3.6.5.msi and getting same error.

I assume that it is still using the old Ice installation. You might want to uninstall that or configure your path in a way that'll find your freshly installed Ice first.

>  I don't find any ice installer especially for Qtcreator.

I don't think something like this exists. As said above this is usually handled via the PATH variable. Now I don't know QtCreator well but maybe you can configure the used path on a per-project basis somehow. That you'll have to check on your own though :shrug:

**Comment by Krzmbrzl** [comment]
Btw I assume you are following https://wiki.mumble.info/wiki/BuildingWindows right?
