### ISSUE TITLE
bug: no-op bug in Mumble: msgContextActionModify

### ISSUE THREAD

**Issue by wfjsw** [mumble-voip/mumble#4116]
https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/Messages.cpp#L965-L966

Probably used to prevent an action from being added twice, but this implemention is a no-op.

**Comment by Krzmbrzl** [comment]
I fail to see the problem with the code. For me it appears as if it should be doing what it appears to be supposed to :thinking: 
Could you elaborate a bit please?

**Comment by wfjsw** [comment]
* If action Exists Then:
  * Add: should return but continue (does not satisfy `msg.operation() != MumbleProto::ContextActionModify_Operation_Add`
  * Remove: already covered by https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/Messages.cpp#L960-L963
* If action Does Not Exist Then:
  * Add: covered by https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/Messages.cpp#L968-L977
  * Remove: would act as Add

**Comment by Krzmbrzl** [comment]
This is how I understand it:
https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/Messages.cpp#L960-L963
handles remove-messages

https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/mumble/Messages.cpp#L965-L966
filters out invalid/unknown operations ("remove" is handled above so everything that is not "add" is invalid at this point).
https://github.com/mumble-voip/mumble/blob/d945acb883186135143121ee2a9fcc501f3c52f7/src/Mumble.proto#L405
states that this field may only be used with the enum value, but the enum could be extended at some point and even if it is not: I'm not sure ProtoBuf actually validates that what gets written into that field is actually a valid enum entry.

Either way I think this falls in the category "better safe than sorry" :shrug:

**Comment by wfjsw** [comment]
It is half-baked even in your explanation:

* If action Does Not Exist Then:
    * Remove: would act the same as Add

This problem is more severe than `invalid/unknown operations`, as unknown operations will be resolved to Add anyway without that filter.

**Comment by Krzmbrzl** [comment]
There is no check whether an action exists or not. It all depends on what the message claims it wants to do.

Or am I missing something here?

**Comment by wfjsw** [comment]
Invalid/unknown operations are unexpected inputs, which could lead to undefined behavior. That's ok.

`Remove` is valid input, but according to the source code clients would do `Add` instead, which is an unexpected behavior. That's not nice.

**Comment by Krzmbrzl** [comment]
How is remove handled as Add? Remove is chekd first and the handled as remove...

**Comment by wfjsw** [comment]
🤔My bad. I'm interpreting protobuf command wrongly :(
