### ISSUE TITLE
Mumble link via tcp-socket / websocket / http

### ISSUE THREAD

**Issue by NikkyAI** [mumble-voip/mumble#4120]
**Context**
Connecting to mumblelink from games which cannot use https://wiki.mumble.info/wiki/Link#Initialization because of language constraints or similar things

**Describe the feature you have in mind**
the Mumblelink plugin would listen on a websocket (or tcp-socket) for position updates and keepalive pings
The game could connect to mumblelink and handle linking and connection loss using well defined protocols
more games or mods can add mumblelink support

all of these should ONLY ever work on connections from localhost

**Describe alternatives you've considered**

Using websockets would be possible because it standardizes 2 way commincation pretty well and libraries for that exist already, so hanshakes and keepalives are handled by the protocol

A plain http post endpoint is easiest to implement for "dumb" clients(games) that just fire the position updates

using tcp-sockets is also possible, but possibly harder for games and mod-devs to implement a custom protocol correctly (so i think http is easier)

**Comment by Krzmbrzl** [comment]
I don't think this should be implemented. It would blow up the simple Link plugin too much.
With the new plugin system of 1.4, you can easily write a custom plugin for the game/application in question and install it into Mumble separately.
