### ISSUE TITLE
How to upgrade Murmur server in Ubuntu server, from 1.12.19 to 1.3.0

### ISSUE THREAD

**Issue by Klagio** [mumble-voip/mumble#4121]
When I install automatically I get version 1.12.19  How can I upgrade it to 1.3.0 (server) Thanks!

**Comment by toby63** [comment]
@Klagio 
What Operating System/Distribution are you using?
Also version 1.12.19 is non existent, you surely mean 1.2.19.  

In general you have three options:
* if available on your distro, download a newer version of the mumble (or mumble-server) package from your distro (maybe through backports etc.)
* if not available, ask your distro maintainer(s) to update to a newer release
* you can download a static server build from the official [website](https://www.mumble.info/downloads/), but I don't recommend that as it has super outdated openssl at the moment (see #4001).
* Or you can compile it yourself.

**Comment by Klagio** [comment]
So update to Ubuntu 20 and reinstall 1.3.0 should fix it all?

**Comment by Krzmbrzl** [comment]
> But is it unsafe?

No that is our official PPA (see https://wiki.mumble.info/wiki/Installing_Mumble#Ubuntu). Afaik this should use the dynamically linked OpenSSL version. That means it uses whatever is present on your system.

I'll close this as resolved as it seems that you have everything working now :+1:
