### ISSUE TITLE
MacOS : AppNap problem on LAN connection

### ISSUE THREAD

**Issue by d-damien** [mumble-voip/mumble#4122]
MacOS Mumble works fine when connecting to external, public servers. It fails to connect to Linuxmint LAN server.

I can connect to this server with local Mumble client. Ports are open.

- Versions
  - Murmur 1.2.19 on Linuxmint 19.1
  - Mumble 1.3.0 on MacOS 10.13.4

- Logs
  - Mumble log : ``Server connection failed: Connection refused``. When using Bonjour : ``Host unreachable``
  - Shell log : ``AppNap: attempt to set AppNap suppression state to false while already in that state``
  - No log on Murmur side with ``-fg -v`` enabled.

**Comment by Krzmbrzl** [comment]
The error message about failed connection is coming from this line:
https://github.com/mumble-voip/mumble/blob/1bd7839a04bc3445fb3361ec40667081ecdac9fa/src/mumble/MainWindow.cpp#L3155

and the AppNap warning shouldn't be related (the warning means that some internal housekeeping didn't work as intended but it shouldn't affect the overall behavior).

It is really weird that you don't get any logs on the server side.
However 1.2.19 is ancient by now. Thus I'd ask you to upgrade your server to 1.3.0

Also could you try hosting a server locally on your Mac and try to connect to that one (so from the same machine) and see if that works?

**Comment by d-damien** [comment]
Tried it on 1.3 and now it seems to work on both versions − weird. Thanks.

**Comment by Krzmbrzl** [comment]
Great to hear that :+1:
