### ISSUE TITLE
[Quick help] I don't see the "Advanced settings" checkbox in mumble client

### ISSUE THREAD

**Issue by storca** [mumble-voip/mumble#4130]
Hello
I don't see the "advanced" checkbox in my client as described [here](https://wiki.mumble.info/wiki/Advanced_client_configuration)

I'm on Ubuntu 20.04 , Mumble version is 1.3.0+dfsg-1build1

Where is the option? I'm logged in as SuperUser and I can't configure the server

This is what I have in the options
![image](https://user-images.githubusercontent.com/24790162/80993763-ec7c3880-8e3b-11ea-979a-a2bda79c3038.png)

Thanks for any help

**Comment by Krzmbrzl** [comment]
Are you using Mumble 1.3.0 or newer? In that case this setting does not exist anymore. You will always see all settings now.

**Comment by storca** [comment]
I'm using the 1.30 you're right
Thanks a lot!

**Comment by Krzmbrzl** [comment]
You're welcome :)
