### ISSUE TITLE
[i18n] Add Occitan to transifex

### ISSUE THREAD

**Issue by Mejans** [mumble-voip/mumble#4131]
Please add the Occitan language to the languages available in Transifex.
I would like to translate Mumbe into this language.
Thanks

**Comment by Krzmbrzl** [comment]
I'm looking into this. Will get back to you once I have news :point_up:

**Comment by davidebeatrici** [comment]
Done!

**Comment by Mejans** [comment]
Nice! Made a request to joint the team :) Thanks

**Comment by davidebeatrici** [comment]
Accepted :)
