### ISSUE TITLE
MAC Catalina will now allow PTT shortcut assignments

### ISSUE THREAD

**Issue by fallenreaper** [mumble-voip/mumble#4133]
**Describe the bug**
When attempting to set up PTT for Mumble, I set the flag in settings and then create a shortcut for push to talk, but when I click the shortcut box, it wont let me set any shortcuts. Since I cant set a shortcut, it wont let me use the key to transmit.

**Steps to Reproduce**
1. Go to 'Settings'
2. Click on 'Shortcuts'
3. Click on 'Add'
4. Select 'Push-to-Talk' from the Function menu
5. Select the area where shortcut is
6. Attempt to create a shortcut

**Expected behavior**
It should accept my keys for the shortcut field.

**Desktop (please complete the following information):**
 - OS: MAC Catalina 10.15.4
 - Version: Mumble 1.3

**Additional context**
When looking at the Mac informational, it seems that the "Accessibility" informational is out of date, for Catalina at least.  I cant seem to follow it because the options do not exist where they say they do.

**Comment by Avatat** [comment]
Have you allowed for "Input Monitoring" in "Security & Privacy" settings?

**Comment by fallenreaper** [comment]
I have not as that wasn't a part of the work flow listed on the website.  I
will do that and provide you with some answers in about 45 minutes after my
meetings.

**Comment by Avatat** [comment]
Ok, thank you.
I've checked it a few days ago and PTT binding worked fine on Catalina.

If it will help, I will update the instruction.

**Comment by fallenreaper** [comment]
That works.

Settings and privacy > Privacy > Accessibility then select mumble.  You may
need to unlock.

Also, note to restart mumble.  It should then allow setting shortcuts.  It
did for me.

**Comment by Krzmbrzl** [comment]
Great to hear :+1:

**Comment by dichter** [comment]
I just had moved to a new Mac on Ventura and run into this issue too. It would be great if Mumble could check on startup for missing permissions and asking to open the mac-os security dialog for the user, so that this setting could be easily set... (like many other programs do)

**Comment by DrPhips** [comment]
I'm having this same issue where the window to set the keyboard bindings does not show the keyboard options and the window is essentially blank.  I'm on the latest Mac OS X - Ventura 13.3 and using the latest version of Mumble - 1.4.287

I have checked my Security settings and set Mumble to allow for Both Microphone access and for Input Monitoring.

**Comment by Krzmbrzl** [comment]
@DrPhips it also needs accessibility access

**Comment by DrPhips** [comment]
<img width="480" alt="Screenshot 2023-03-29 at 3 25 49 PM" src="https://user-images.githubusercontent.com/22800697/228646464-87ce7b3c-c761-40f6-9561-baf914e72d67.png">
<img width="487" alt="Screenshot 2023-03-29 at 3 26 49 PM" src="https://user-images.githubusercontent.com/22800697/228646680-a3b724ad-20bf-40ca-aae5-b71043515390.png">

Yes, but where?  I think they changed up the System Prefs panel in the last update.

**Comment by Krzmbrzl** [comment]
No idea, sorry. I'm nor using macOS at all :shrug:

**Comment by DrPhips** [comment]
Thanks @Krzmbrzl, not sure what to do from here in terms of getting help and don't want to make any forum faux pas. Suggestions?

**Comment by Krzmbrzl** [comment]
I would suggest joining our Matrix channel https://matrix.to/#/#mumble:matrix.org and ask there. Maybe someone there is a mac used and can help you. Otherwise, if @TerryGeng has a chance to see this here, he might also be able to help.
