### ISSUE TITLE
Mumble will not start in MacOS 10.15.2 Catalina

### ISSUE THREAD

**Issue by bbergstr** [mumble-voip/mumble#4135]
When attempting to start Mumble on MacOS 10.15.2 Catalina, it will not start. Says it can't be opened because Apple can't check for malicious software. Says this software needs to be updated. Contact the developer for more information. [https://photos.app.goo.gl/QWa4VxHmMvtGukD67](url)

**Comment by Avatat** [comment]
Try right-click on Mumble icon, and then click "Open".

**Comment by Krzmbrzl** [comment]
We had this issue in the past where MacOS is stubborn because it thinks it knows that you don't really want to open Mumble. The problem was solved by using the method @Avatat described once. After that it was possible t start Mumble normally...
