### ISSUE TITLE
Improve Overlay On Linux

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#4139]
I cannot get the overlay to work on any game on Linux. Weather it is a native linux game or a game running in Wine or Proton. Please improve the overlay on Linux to work in native games, Wine games and Proton games.

**Comment by Krzmbrzl** [comment]
Do you have gdb installed? #2129 seems to indicate that this is necessary for the overlay to work

**Comment by trymeouteh** [comment]
I do have the gdb package installed and I am using the latest version of Mumble from the Ubuntu PPA

**Comment by Krzmbrzl** [comment]
> Is the overlay supposed to work for Wine games, native linux games or both?

Tbh I don't know. I don't use it.

I think @Kissaki does probably know best...

**Comment by Kissaki** [comment]
I would expect it to work generally. But I have never used or tested it on Linux, and don’t know the limitations.

Wine translates DirectX calls to OpenGL. Given that our overlay supports OpenGL I would expect it to work.

This may change with OpenGL being replaced with Vulkan, if that is a thing.

**Comment by Krzmbrzl** [comment]
@trymeouteh please try and start Mumble form a console when attempting to use the overlay and then copy and paste the console output here.
