### ISSUE TITLE
Configurable timeout for rememberchannel

### ISSUE THREAD

**Issue by deluxghost** [mumble-voip/mumble#4143]
**Context**
rememberchannel is only useful while a user lost connection shortly. If that user rejoin server after 1 day, there is no reason to let him join the remembered channel, there might be some others users that he doesn't know at all. And these users might think "who tf are you and why tf you join our channel"

**Describe the feature you have in mind**
A config entry that define how long should the server remember the last channel, for example, 5 minutes. Then if the user rejoin server only in 5 minutes, he will be dropped in the last channel.

This can be implement while reading from db so we don't need deleting operation

**Comment by Krzmbrzl** [comment]
Sounds good.

> This can be implement while reading from db so we don't need deleting operation

I agree that we can check for the timeout when querying the database, but we should need to delete the property, if the timeout has been reached. So if I query for the remembered channel and the query function detects a timeout, the function should delete the entry in the database and return that there is no such entry.

**Comment by Krzmbrzl** [comment]
Any chance you want to implement that yourself? I think the necessary change would be very easy :point_up:

**Comment by deluxghost** [comment]
> the function should delete the entry in the database and return that there is no such entry.

oh, you are right, such lazy load behavior is better.

>Any chance you want to implement that yourself?

Maybe not, I don't really know how to code c++ project yet. 😥

**Comment by Avatat** [comment]
> Maybe not, I don't really know how to code c++ project yet. disappointed_relieved

Here you can learn from C++ experts!

**Comment by Krzmbrzl** [comment]
> Maybe not, I don't really know how to code c++ project yet. disappointed_relieved

As @Avatat said: Here's your chance to learn. I could guide you through the process :)

What OS are you using though? On Linux it's really easy but if you're on Windows, then this might not be the best introduction to cpp as our current build process on Windows is rather involved ^^

**Comment by deluxghost** [comment]
> > Maybe not, I don't really know how to code c++ project yet. disappointed_relieved
> 
> As @Avatat said: Here's your chance to learn. I could guide you through the process :)
> 
> What OS are you using though? On Linux it's really easy but if you're on Windows, then this might not be the best introduction to cpp as our current build process on Windows is rather involved ^^

Sadly i only use Linux cloud server for micro services. Anyway I will try Windows build again later.

**Comment by Krzmbrzl** [comment]
Later as in "someday" or as in "I'll give a try to implement this issue"? :)
Either way you should probably join our IRC dev-channel for potential questions that'll arise during the build: [#mumble-dev](https://matrix.to/#/!VNUpYnUPdhTAqagvUu:matrix.org?via=matrix.org)

**Comment by deluxghost** [comment]
> Later as in "someday" or as in "I'll give a try to implement this issue"? :)
> Either way you should probably join our IRC dev-channel for potential questions that'll arise during the build: [#mumble-dev](https://matrix.to/#/!VNUpYnUPdhTAqagvUu:matrix.org?via=matrix.org)

_I'll give a try to implement this issue_

I have already build mumble on master properly. The build process is painful, especially while I am using Win10+VS 2017. The mumble-releng is ok, but I still need to hack many things, e.g. locale bug of some libs, and wrong cl.exe path in makefile, etc. After 7 hours, finally I can build working x86 binaries.

I will look into this issue later, it's too late now.

![image](https://user-images.githubusercontent.com/5835759/81336026-23bc4500-90db-11ea-97d5-7e0179bcad05.png)

**Comment by Krzmbrzl** [comment]
Okay wow. For someone that doesn't really know c++ setting up the build env on WIndows is really an achievement (even I am having problems with it) :clap: 

You are right. It is a pain to set up, which is one of the reasons we're migrating to a different build system (cmake) in the background. With that it'll get much easier :)

> I will look into this issue later, it's too late now.

Sure. Do you know where the relevant code parts are located?

**Comment by deluxghost** [comment]
I created a PR at #4147, but I didn't update `lastchannel` while reading, because I'm not sure if the column is used elsewhere. Also I copied a method to read from DB, for the same reason, I don't know if the method is used elsewhere.

Tell me how to make it better

**Comment by Krzmbrzl** [comment]
> Also I copied a method to read from DB, for the same reason, I don't know if the method is used elsewhere.

It is also used here:
https://github.com/mumble-voip/mumble/blob/54eb261ca37de0acb75a001e9fb7dbefb6123926/src/murmur/ServerDB.cpp#L1050
but as far as I can tell, I think it's basically the same purpose. Thus I think it's fine (and even cleaner) to just change the original function instead if creating a new one.

> didn't update lastchannel while reading

I guess it's fine, given that it wouldn't be updated when `rememberchan` is disabled :thinking:

**Comment by Krzmbrzl** [comment]
Implemented via #4147
