### ISSUE TITLE
A command line option to set the window title 

### ISSUE THREAD

**Issue by newlaurent62** [mumble-voip/mumble#4153]
**Context**
I have minimum two mumble instances started in my use case:
- one for input my voice
- another to send the audio of the connected users to Jamulus.
 
**Describe the feature you have in mind**
Change the window title in order to add a descriptive string (Ex: my surname, or "Jamulus" ...)
I would like a command line option: --title ? 
Ex: 
  mumble -m --title "Edouard Victor" # (note the space in the descriptive title) 
  mumble -m --title "Jamulus"
=> window title should display something like: "Mumble ~ Edouard Victor"
When switching window, we will have more information to select the good mumble instance 

**Describe alternatives you've considered**
mumble --help

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/54eb261ca37de0acb75a001e9fb7dbefb6123926/src/mumble/MainWindow.cpp#L393-L401

We should probably add a QString to `g.s` (`Settings`) storing the specified window title.

@Krzmbrzl Thoughts?

**Comment by newlaurent62** [comment]
Well you could also add the current login name to the title? (No command line and no additional settings)

**Comment by davidebeatrici** [comment]
I would still prefer an option, the ability to specify a custom window name is definitely useful.

**Comment by Krzmbrzl** [comment]
> @Krzmbrzl Thoughts?

I don't think that this is something the majority of users will need but given that this is a really tiny change, I also don't see any harm in adding it, so the ones that do find it useful will have it :)

I wouldn't add it to the settings though. To me this only makes sense as a command-line option as it only comes into play when running multiple instances of Mumble in the first place. Thus there's a need to specify it on a per-instance level and also all instances share the same settings and thus this is yet another reason why I think, that this shouldn't be in the settings.

> Well you could also add the current login name to the title? (No command line and no additional settings)

What would that be good for? When running multiple instances they'd still have the same title and when only running 1 instances, what's the need to have your username in the title?
