### ISSUE TITLE
Hide overlay settings for no-overlay option

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#4157]
**Context**
`no-overlay` config option

**Describe the feature you have in mind**
If the overlay support is disabled via the `no-overlay` option, the settings page for the overlay should also not be included in Mumble.

@Kissaki thoughts?

**Comment by Kissaki** [comment]
You’re talking about the build parameter, right?

I agree. It should be dropped.

**Comment by Krzmbrzl** [comment]
> You’re talking about the build parameter, right?

Yes

> I agree. It should be dropped.

Okay perfect :+1:
