### ISSUE TITLE
Allow Murmur to work with VPNs

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#4160]
Allow Murmur to work on a windows and linux desktop computer when the computer is using a VPN. Allow the Murmur server to use the VPN IP address to protect my IP address from DDOS attacks.

**Comment by toby63** [comment]
And that is not possible right now?

https://wiki.mumble.info/wiki/Murmur.ini#Connectivity
`Host`
`The host setting configures the default interface which each virtual server will listen on.`

**Comment by Krzmbrzl** [comment]
We had reports of people using a VPN, so I'm pretty sure this works already.
