### ISSUE TITLE
Integrate TOR into Murmur

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#4161]
Please add TOR integration into Murmur for Windows and Linux to protect the IP address of the host without having to install any additional software to use TOR. This will be free way to protect my IP address from DDOS attacks since Tor is free to use. There are VPNs but free VPNs have poor privacy.

**Comment by Krzmbrzl** [comment]
If you are afraid of a server admin using your IP address for something inappropriate, host a server yourself and use https://wiki.mumble.info/wiki/Murmur.ini#obfuscate

And if you want to route your internet traffic through Tor, that's already possible. See e.g. https://www.wikihow.com/Route-All-Network-Traffic-Through-the-Tor-Network
For Mumble in particular see https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/Mumble

I don't see this as a responsibility of Mumble. How data is transferred over the internet, is not part of what Mumble cares about. It is only responsible for processing these data streams.

Besides I know that there exists a project that works on a Tor-Mumble integration thing. I just forgot how its name was... The devs are somewhat active on our IRC though, so you can go and ask there :thinking:

**Comment by streaps** [comment]
> Besides I know that there exists a project that works on a Tor-Mumble integration thing.

https://github.com/digitalautonomy/wahay

**Comment by Krzmbrzl** [comment]
Ah yes that was it. Thank you!
