### ISSUE TITLE
SQLite version question

### ISSUE THREAD

**Issue by deluxghost** [mumble-voip/mumble#4162]
https://github.com/mumble-voip/mumble/blob/185670a38130671792f4e13f946596df6fbbe897/src/murmur/ServerDB.cpp#L189

is this mean to `major > 3 || (major == 3 && minor >= 7)` ?

reference: https://www.sqlite.org/wal.html

**Comment by davidebeatrici** [comment]
Indeed, thank you very much for spotting it!

Could you create a pull request to fix it, please?

**Comment by deluxghost** [comment]
Yes, edit directly on github website for such a tiny change
