### ISSUE TITLE
Linux: Increased CPU% usage using RAW(!) ALSA when selected input has disabled capture

### ISSUE THREAD

**Issue by etosan** [mumble-voip/mumble#4171]
**Describe the bug**
First disclaimer, this bug concerns raw ALSA only, eg. no PulseAudio, eg on completely pulse-less Linux system. If you don't understand what previous sentence means, and/or are using PulseAudo (or are Pulse bigot), please pretend this bug report does not exist for you.

**Steps to Reproduce**
  - Select correct input device in `mumble`.
  - In `alsamixer` select given device for capture by moving `CAPTURE` indicator under it.
  - Verify audio capture and transmission works.
  - In `alsamixer` disable `CAPTURE` (or move it to other capture device NOT configured in mumble).
  - Mumble's `ALSAAudioInput` thread is now consuming considerably more CPU (in range +5% ~ +10% CPU).

**Expected behavior**
When CAPTURE is disabled on `mumble` selected ALSA input device, `mumble`'s `ALSAAudioInput` thread should not consume any more CPU then when capture is enabled. Preferably, when ALSA capture is disabled, `ALSAAudioInput` thread should have 0% CPU consumption. I don't know if ALSA provides capture detection APIs, but if it does those should probably be used to detect if `input` reading makes even sense. I theorise issue is cause by `mumble` trying to read input that is mute at lower level of the audio stack.

**Screenshots**
Will be provided on demand, if necessary.

**Desktop (please complete the following information):**
 - OS: Linux 5.4
 - Version: Mumble 1.3.0

**Additional context**
Mumble is one very few Linux audio solutions with wide audio backends support, that works reliably on pure ALSA systems without PulseAudio. This bug is not very bad but it's pretty annoying. It would be great if this could be fixed.

**Comment by ZeroAbility** [comment]
Is the issue still present in 1.4?
