### ISSUE TITLE
[FIXED] /home/$USER dir doesn't exist!

### ISSUE THREAD

**Issue by SiaNariman** [mumble-voip/mumble#4176]
By recording "/home/$USER" isn't your own user and outside from mumble client this dir doesn't exist even to copy or move the audio files from it.
Tested with debian and solus, both are the same with mumble flatpak.

Regards

**Comment by toby63** [comment]
Maybe others understand this, but could you rewrite this for better understanding?

**Comment by SiaNariman** [comment]
Mumble records located inside a dir '/home/$USER' this isn't the same as your /home/$USER. Try mumble via flatpak, then you understand this issue.

**Comment by toby63** [comment]
So mumble via flatpak trys to save audio recordings in `/home/$USER`, which is not accessable by the flatpak?

**Comment by SiaNariman** [comment]
Not exactly :-)

**Comment by SiaNariman** [comment]
![Untitled](https://user-images.githubusercontent.com/443190/82140885-5d572380-9832-11ea-9926-6cc8da023b11.png)
i hope that clear enogh :)

**Comment by toby63** [comment]
Thx for the clarification.

Can you give us the full paths of these folders?
and maybe also the output of:
`ls -l /home`

Strangely I can't see any difference between the normal mumble version and the flatpak here:
https://github.com/flathub/info.mumble.Mumble 
that could cause this different behaviour.

Guess the devs will look into it.

Do you have any special setup?
* What Debian Version + Desktop are you using?
* What Solus Version + Desktop are you using? 
(I assume you screenshot is from Solus? and the Desktop is Mate?)

**Comment by toby63** [comment]
Update:
Ok now I think I know the reason, this is intended behaviour by flatpak.
Flatpaks goal is to seperate applications as best as possible.
See also: https://docs.flatpak.org/en/latest/sandbox-permissions.html

To change this behaviour the Mumble flatpak would need to include the line:
`--filesystem=home` 
to access the user’s home directory.

**Comment by SiaNariman** [comment]
Great, this fixed it under solus ;)
 `sudo flatpak override info.mumble.Mumble --filesystem=home`

**Comment by Krzmbrzl** [comment]
I created an issue in the Mumble Flatpak repo in order for them to be aware of this.

**Comment by toby63** [comment]
> Great, this fixed it under solus ;)
> `sudo flatpak override info.mumble.Mumble --filesystem=home`

Interesting, thought it would be necessary to rebuild it.
Good solution for others, a general change of this might be useful though, I created an issue for this: https://github.com/flathub/info.mumble.Mumble/issues/14

Also next time open an issue first in:
https://github.com/flathub/info.mumble.Mumble/issues
:wink:

**Comment by toby63** [comment]
@Krzmbrzl Oh, you were faster, what are we gone do now? :smile:

**Comment by Krzmbrzl** [comment]
I'll close my issue as a duplicate of yours. You seem to have put a little more effort into creating the issue ;)

Yeah I can do that :+1:

**Comment by toby63** [comment]
> I'll close my issue as a duplicate of yours. You seem to have put a little more effort into creating the issue ;)
> 
> Yeah I can do that +1

Ok :+1:  Thank you, was conincidence and I was slower :smile:

**Comment by Krzmbrzl** [comment]
Thanks for providing support for this btw - much appreciated :D
