### ISSUE TITLE
Support special characters in Markdown

### ISSUE THREAD

**Issue by fedetft** [mumble-voip/mumble#4179]
Regarding the recently added Markdown feature https://github.com/mumble-voip/mumble/pull/4076

That's really cool to have, thanks @Krzmbrzl for implementing it.

However, I think I found a bug, the < and > characters in markdown code blocks get replaced by \&lt; and \&gt;

That's annoying when using markdown code to paste C++ snippets to friends.

**Comment by Krzmbrzl** [comment]
Ah yes I'm pretty sure that's because the input gets HTML-escaped. I'll have a look once I find the time to do so. Can't promise when that'll be though...
