### ISSUE TITLE
celt.h : No such file or directory

### ISSUE THREAD

**Issue by jafarulla15** [mumble-voip/mumble#4187]
I am new and trying to build mumble using IDE QtCreatror and getting error of celt.h missing.
I am using Ubuntu 16 and Qtcreator 4.11.1.

It will be very helpful for me, if anybody can brief me - how I can get rid of this issue.
Thanks and Regards
Jafar Ulla

**Details of Compile output:**

20:06:55: Running steps for project mumble...
20:06:55: Configuration unchanged, skipping qmake step.
20:06:55: Starting: "/usr/bin/make" -j1
/usr/bin/make -f Makefile.Debug
make[1]: Entering directory '/home/jafarulla/NybsysDev/mumble-master/src/build-mumble-Desktop_Qt_5_14_2_GCC_64bit-Debug'
g++ -pipe -fvisibility=hidden -Wall -Wextra -fstack-protector -fPIE -U_FORTIFY_SOURCE -I../mumble_proto -isystem ../mumble_proto -I../../3rdparty/celt-0.7.0-src/libcelt -isystem ../../3rdparty/celt-0.7.0-src/libcelt -I../../3rdparty/opus-src/celt -isystem  ../../3rdparty/opus-src/celt -I../../3rdparty/opus-src/include -isystem ../../3rdparty/opus-src/include -I../../3rdparty/speex-src/include -I../../3rdparty/speex-build -g -I../../3rdparty/speex-src/include -I../../3rdparty/speex-build -std=gnu++1y -pthread -Wall -Wextra -D_REENTRANT -fPIC -DRESTRICT=__restrict__ -DSNAPSHOT_BUILD -DMUMBLE_VERSION_STRING=1.4.0 -DMUMBLE -DUSE_MANUAL_PLUGIN -DNO_CRASH_REPORT -DUSE_OPUS -DUSE_RNNOISE -DUSE_ALSA -DUSE_OSS -DUSE_PULSEAUDIO -DUSE_BONJOUR -DUSE_DBUS -DUSE_SPEECHD -DUSE_G15 -D_REENTRANT -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -DQT_QML_DEBUG -I../mumble -I. -I../../src -I../mumble -I../mumble_proto -I../../3rdparty/arc4random-src -I../../3rdparty/qqbonjour-src -I../../3rdparty/smallft-src -I../mumble/widgets -I../../3rdparty/speex-src/include -I../../3rdparty/speex-src/libspeex -I../../3rdparty/speex-build -I../../3rdparty/speexdsp-src/include -I../../3rdparty/speexdsp-src/libspeexdsp -I../../3rdparty/celt-0.7.0-src/libcelt -I../../3rdparty/opus-src/celt -I../../3rdparty/opus-src/include -I../../3rdparty/opus-src/src -I../../3rdparty/opus-build/src -I../../3rdparty/rnnoise-src/include -I/usr/lib/oss/include -isystem /usr/include/speech-dispatcher -isystem /usr/include/alsa -I../../../../Qt5.14.2/5.14.2/gcc_64/include -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtSvg -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtWidgets -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtGui -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtNetwork -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtSql -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtXml -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtConcurrent -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtDBus -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtCore -I../../debug/.moc/mumble -isystem /usr/include/libdrm -I../../debug/.ui/mumble -I../../../../Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++ -x c++-header -c ../mumble/mumble_pch.hpp -o debug/mumble.gch/c++
../mumble/mumble_pch.hpp:48:18: fatal error: **celt.h:** No such file or directory
compilation terminated.
Makefile.Debug:2130: recipe for target 'debug/mumble.gch/c++' failed
make[1]: Leaving directory '/home/jafarulla/NybsysDev/mumble-master/src/build-mumble-Desktop_Qt_5_14_2_GCC_64bit-Debug'
Makefile:42: recipe for target 'debug' failed
make[1]: *** [debug/mumble.gch/c++] Error 1
make: *** [debug] Error 2
20:06:57: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project mumble (kit: Desktop Qt 5.14.2 GCC 64bit)
When executing step "Make"

**Comment by toby63** [comment]
* What mumble version/commit do you try to build?
* What config options have you applied?

Also:
Mumble is using a linked celt library:
see https://github.com/mumble-voip/mumble/commit/a642894f4a4417f6bbe35fb1344e66dc7e8f5481
This is also where the missing "celt.h" file is: https://github.com/mumble-voip/celt-0.11.0/blob/master/libcelt/celt.h

**Comment by Krzmbrzl** [comment]
As toby63 said.

In addition: Did you run `git submodule update --init --recursive` after having cloned the mumble repo?

**Comment by jafarulla15** [comment]
@Krzmbrzl  and @toby63
