### ISSUE TITLE
Cannot join the Russian translation team

### ISSUE THREAD

**Issue by user-en** [mumble-voip/mumble#4191]
Hello! 
A week ago, I sent a request to join a Russian translation team on Transifex, but still get no response.
How can I help with translation?

Only two profiles are active on this page: https://www.transifex.com/mumble/teams/7752/ru/
1) https://www.transifex.com/user/profile/B0nuse/
2) https://www.transifex.com/user/profile/Oleksandr_Osypenko/

My profile: https://www.transifex.com/user/profile/user4532/

**Comment by Krzmbrzl** [comment]
I forwarded the issue to the responsible person. The issue should be resolved in the coming days :+1:

**Comment by Krzmbrzl** [comment]
Your request should have been approved now.
