### ISSUE TITLE
Unable to change channels after being connected to a server for some time

### ISSUE THREAD

**Issue by mckernanin** [mumble-voip/mumble#4199]
**Describe the bug**
After being connected to a server for some time, I lose the ability to change channels. Relogging fixes the issue.

**Steps to Reproduce**
1. Stay connected to mumble server for a while
2. Try to change channels

**Expected behavior**
I should be able to change channels, but nothing happens

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.3.0

**Additional context**
Working on details from other people, seeing if this is related to a single client version or our whole server. I looked for a bug similar and didn't see one.

**Comment by Krzmbrzl** [comment]
Which server version are you using? We had some issues with the rate limiter in 1.3.0 That should be fixed with 1.3.1. If you're using 1.3.0 or earlier, please try if the problem persists with 1.3.1 (right now you can use the RC from the release page)
