### ISSUE TITLE
Mumble spells text-to-speech messages with Festival.

### ISSUE THREAD

**Issue by DeltaTimo** [mumble-voip/mumble#4216]
**Describe the bug**
Mumble spells text-to-speech messages when using speech-dispatcher and it's festival module on manjaro linux.

**Steps to Reproduce**
1. Enable the festival module in speech-dispatcher.
2. Start Mumble
3. Do anything that lets TTS speak.

**Expected behavior**
Mumble speaks the message in complete words and sentences.

**Desktop (please complete the following information):**
 - OS: 5.4.40-1-MANJARO x86_64 GNU/Linux
 - Version: Mumble 1.3

**Additional context**
I am using `DefaultModule festival` in speech-dispatcher and it appears to be using the correct voice and module. Further, if tested with `spd-say` complete words are spoken whilst Mumble spells the words.

I am unsure if this is an issue related to Mumble, Festival, or Speech-Dispatcher as my debugging capabilities with these programs are very limited.

**Comment by Krzmbrzl** [comment]
I *think* that this is a quirk of the used TTS engine. For all I know Mumble worked okay with screen readers in the past :thinking: 

@ethindp you are using Mumble with a screen reader, aren't you? Did you have problems of it spelling the words to you instead of speaking them out properly?

**Comment by Reikion** [comment]
@DeltaTimo Yeah, you're right. `spd-say` works correctly, but Mumble synthesize letter by letter, while festival is used. However if you use espeak-ng backend it speaks properly, like `spd-say`, so it may or may not be Mumble's issue. I would rather bet on QTextToSpeech bug, because code basically call `QTextToSpeech->say("Hello")`.

**Comment by Krzmbrzl** [comment]
Okay in that case I'll close this issue. If someone find evidence that this is indeed Mumble's fault, I'll reopen :point_up:
