### ISSUE TITLE
Caching the build environment on Azure Pipelines

### ISSUE THREAD

**Issue by TerryGeng** [mumble-voip/mumble#4218]
It looks like our Azure CI/CD always fails when fetching the build environment. If it doesn't fail, still, it would take some time to download the environment before it can start to build.

In #3575, caching has already been discussed and today I came across https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops and learned that Azure started to support caching recently. Maybe we can adopt it?

**Comment by davidebeatrici** [comment]
Yep, it will be used as soon as we switch to the new environment.

**Comment by TerryGeng** [comment]
@davidebeatrici Great to know you are working on this! Thanks!

And just a little question: it looks like building mumble on Linux and MacOS only take ~10 min. However, for MSVC it takes half an hour. I'm wondering if it will speed up after we switch to MSVC 2019.

**Comment by davidebeatrici** [comment]
More specifically, it will speed up after we switch to CMake and Ninja!
