### ISSUE TITLE
XFCE Focus-Stealing on All Notifications

### ISSUE THREAD

**Issue by Fidgetcetera** [mumble-voip/mumble#4225]
**Describe the bug**

When clicking the activation button for XFCE notifications, Mumble takes focus, on *any* notification, including Riot messages (where only Riot should be moved to the front) and the notification previews when changing notification settings in XFCE.

**Steps to Reproduce**
1. Use XFCE.
2. Have mumble open at all.
3. Receive any notification which has a button.
4. Click button.
5. Mumble will take focus/jump in front of other windows, in addition to any existing behavior the button should have.

**Expected behavior**
I only expect to have mumble take focus if I activate a button for Mumble notifications.

**Desktop:**
 - OS: Ubuntu 20.04 Focal Fossa LTS, XFCE 4.14 (best results for replication may involve using xubuntu, though. this is a server install with the xubuntu-desktop package installed.)
 - Version: Mumble 1.3.0+dfsg-1build1

**Comment by Krzmbrzl** [comment]
Uhm this sounds like a bug in XFCE to me. As far as I know Mumble doesn't implement any notification handling at all.

Does this also happen with other apps?

Is it only notifications or does the problem occur on other actions as well (e.g. clicking somewhere else)?

**Comment by Fidgetcetera** [comment]
This does not happen with any other apps in my experience, and it is only on notfications, yes.

**Comment by Krzmbrzl** [comment]
Were you able to test this with different versions of XFCE?

**Comment by Fidgetcetera** [comment]
Just tested with a laptop running XFCE 1.12 and it appears to not occur there. Same window manager (and window manager tweaks) focus settings on both.

**Comment by Krzmbrzl** [comment]
Thanks for the additional test :+1: 

Interesting. In that case I'd tend to say that this is indeed a XFCE bug... Have you reported it to XFCE yet?

Until we get evidence that this is instead a bug in Mumble, I'll close this issue. If you have further info (or an answer/statement from the XFCE devs), feel free to share it here and we'll see if that changes the situation :)

**Comment by NoraCodes** [comment]
This also happens in GNOME 3, on stock Ubuntu 20.04.

**Comment by Krzmbrzl** [comment]
Hm... Really weird :thinking:
