### ISSUE TITLE
UI text is incomplete in Spanish? (Windows)

### ISSUE THREAD

**Issue by felix91gr** [mumble-voip/mumble#4237]
**Describe the bug**
The app gives some feedback about what you've just done. For example, "You joined Office", or "You have been muted".

In Spanish at least, this functionality is incomplete.

**Steps to Reproduce**
1. Have Windows 10 installed
2. Have it on Spanish
3. Open Mumble
4. Join a channel
5. See error: chat shows the feedback text `You joined <channel_name>`

**Expected behavior**

That step 5 shows instead the text `Has entrado a <channel_name>` or something similar.

**Screenshots**

This is how the chat log of my Mumble looks after I've entered and exited some rooms.
As you can see, the UI is in Spanish overall, but some of the text isn't showing in Spanish.
![imagen](https://user-images.githubusercontent.com/11747623/83582241-4a866380-a541-11ea-8dab-3ed60c6258a1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.3

**Additional context**
This might be happening in other OSes as well, but I've messed up Linuxes enough to want to fiddle with mine, and mine is in English so... I don't know if the same thing happens there.

**Comment by Krzmbrzl** [comment]
As you can see at https://www.transifex.com/mumble/mumble/languages/ the spanish translation is incomplete. For untranslated strings Qt falls back to the source's language (english)

The `You joined ...` message however seems to already be translated though, so my guess is that it wasn't at the point 1.3.0 was released (and probably won't make it in the 1.3.x series in general).

Could you try this with a version compiled from the master branch?

**Comment by Krzmbrzl** [comment]
I just checked and the translation for `You joined ...` happened 7 months ago and is therefore not included in the 1.3.x series.

**Comment by felix91gr** [comment]
Ahaa, so that was what it was. Okay, tell you what: imma grab that transifex thing and translate as much as I can of it :)

**Comment by Krzmbrzl** [comment]
> Ahaa, so that was what it was. Okay, tell you what: imma grab that transifex thing and translate as much as I can of it :)

Awesome! :)

There are only 153 untranslated strings left for Spanish, so you have a chance of finishing it up for 1.4.0 ;)
