### ISSUE TITLE
[Question] Mumble protocol - When is message type 13 sent?

### ISSUE THREAD

**Issue by CaptainZidgel** [mumble-voip/mumble#4255]
According to the [docs](https://mumble-protocol.readthedocs.io/en/latest/protocol_stack_tcp.html), type 13 is the ACL information ([protobuf](https://github.com/mumble-voip/mumble/blob/master/src/Mumble.proto#L317))
At what point is this message sent to the client?
I am hoping to use this to add ACL-reading support to a mumble bot library. From debugging logs in the bot library, I am unable to see this message sent at all and I assume something has to be done before it is sent.

**Comment by Johni0702** [comment]
IIRC you first need to send an `ACL` message with `channel_id` and `query = true` and the server will then reply with the full `ACL` message for that channel (assuming you have write acl permission for it).
You can then send that ACL message back to the server with your changes and the server will apply them (again, assuming you got permission).

I don't think it's ever sent by the server unsolicited.

**Comment by Krzmbrzl** [comment]
To be more precise, these here are the occasions in which an ACL message is being used:
```
src/murmur/Messages.cpp:1505:void Server::msgACL(ServerUser *uSource, MumbleProto::ACL &msg) {
src/murmur/Messages.cpp:1544:                                   MumbleProto::ACL_ChanACL *mpacl = msg.add_acls();
src/murmur/Messages.cpp:1566:                   MumbleProto::ACL_ChanGroup *group = msg.add_groups();
src/murmur/Messages.cpp:1639:                           const MumbleProto::ACL_ChanGroup &group = msg.groups(i);
src/murmur/Messages.cpp:1659:                           const MumbleProto::ACL_ChanACL &mpacl = msg.acls(i);
src/mumble/ACLEditor.h:29:              MumbleProto::ACL msg;
src/mumble/ACLEditor.h:67:              ACLEditor(int channelid, const MumbleProto::ACL &mea, QWidget *p = NULL);
src/mumble/ServerHandler.cpp:900:       MumbleProto::ACL mpacl;
src/mumble/Messages.cpp:919:void MainWindow::msgACL(const MumbleProto::ACL &msg) {
src/mumble/ACLEditor.cpp:79:ACLEditor::ACLEditor(int channelid, const MumbleProto::ACL &mea, QWidget *p) : QDialog(p) {
src/mumble/ACLEditor.cpp:203:           const MumbleProto::ACL_ChanACL &as = mea.acls(i);
src/mumble/ACLEditor.cpp:221:           const MumbleProto::ACL_ChanGroup &gs = mea.groups(i);
src/mumble/ACLEditor.cpp:333:                   MumbleProto::ACL_ChanACL *mpa = msg.add_acls();
src/mumble/ACLEditor.cpp:347:                   MumbleProto::ACL_ChanGroup *mpg = msg.add_groups();
```

Thus in particular if you want to retrieve the ACL list, you'll ave to send an ACL message that has the `query` field set to `true`
https://github.com/mumble-voip/mumble/blob/6dd5db768c55da0119b8fb4b7c44f560f81fa823/src/Mumble.proto#L359-L360
In that case the server will execute
https://github.com/mumble-voip/mumble/blob/6dd5db768c55da0119b8fb4b7c44f560f81fa823/src/murmur/Messages.cpp#L1505
and verify that you actually do have the permission to **Write** the ACLs
https://github.com/mumble-voip/mumble/blob/6dd5db768c55da0119b8fb4b7c44f560f81fa823/src/murmur/Messages.cpp#L1512-L1515
If you do, you pass this check and continue with the block that'll fill out the ACL details and send that message back to your client.
