### ISSUE TITLE
[Discussion]: Drop packet size limit from protocol

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#4260]
According to [the protocol documentation](https://mumble-protocol.readthedocs.io/en/latest/voice_data.html#packet-format) a UDP packet must not exceed a size of 1024 bytes.

We are thinking about changing this protocol specification to either remove this limit completely or applying this restriction only to packets sent to the server.

The rationale of this is that this would allow for the server to attach meta-data to a client's UDP packet (e.g. where are the packets sent to so that the receiver can know who else received this audio).

I thin right now we tend to remove the size limit only for messages sent from the server. This is how the implementation of the official Mumble and Murmur clients works already (the client doesn't enforce the 1024 bytes size limit whereas the server does) and it'd also guarantee that packets are not getting insanely huge (e.g. due to a client sending huge chunks).
Furthermore I was made aware of the fact that there exists something like a "maximum transmission unit" (MUTU - see https://en.wikipedia.org/wiki/Maximum_transmission_unit) and according to Wikipedia the limit on the most commonly used interface (ethernet v2) is 1500 bytes per packet. Restricting the packet size sent from the client would us help to guarantee staying within this MTU as well.

Before making this change to the protocol though, we wanted to gather some opinions on this topic (especially from developers of 3rdParty applications, which might (or might not) explicitly depend on that size limit being present). Thus the question: What do you think about this?

If you don't want to write a comment, you can also leave a reaction on this post here. :+1: for agreement and :-1: for disagreement (though for the latter it'd be nice if you could write a comment stating why you disagree).

Furthermore: Does somebody here know what happens when a packet exceeds the MTU? Will it be silently dropped? Or truncated to that size?

**Comment by streaps** [comment]
MTU, packet size and UDP is complicated. It's possible to send UDP datagrams up to 64 Kb, but if it's bigger than the MTU it gets fragmented. There are different issues with fragmentation, just google it. The short form: avoid fragmentation of UDP datagrams.

Adding a few bytes to the 1024 limit would not be a problem at the network level. 1024 is pretty conservative and there is enough headroom. QUICs maximum packet size is 1275 IIRC.

But is it a good idea to add additional data to the UDP audio transport? With low latency settings (small Opus frame sizes) the overhead really matters. If you send the data in real, time you get significant overhead – if you don't need meta data with milliseconds accuracy, you could use the tcp channel.

**Comment by Krzmbrzl** [comment]
@streaps thanks for the critical thoughts. I agree that we should keep the amount of additional data appended to the UDP packets to a minimum, but for this specific application a single byte is probably enough already: We just need to add the info about the VoiceTarget to the packet for the clients as well. What exactly that VoiceTarget is referring to (in terms of which users it includes), can be sent via TCP.

From your reply I take it though that you are not against removing the size-limit from the protocol but rather wanted to raise criticism against overpacking the UDP packets, right?

**Comment by streaps** [comment]
I guess 1 byte is an acceptable overhead, it's 1/48th of an IPv6 header :).

I would do it like this (and if I understand it correctly this is the same as your proposal (?)):

- a client must not enforce the size limit on incoming connections. If there is a valid packet that can be decoded, just use it.
- there should be some size limit on packets from the client to the server and the server should enforce it.
- the server is allowed to add (a few bytes of) meta data and is not bound to the same size limit.

The mumble-protocol says:
_"The maximum size for the whole audio data packet is 1020 bytes. This allows applications to use 1024 byte buffers for receiving UDP datagrams with the 4-byte encryption header overhead."_
How important is it that applications are allowed to use buffers of exactly 1024 bytes? 

Is there any good reason to increase the size limit for the packet created by the client? Most packets are much smaller anyway.
64 kbps * 60 ms = 480 bytes
1000 bytes / 10 ms = 800 kbps

I ignored the overhead, but the numbers don't suggest that the 1020 bytes limit is too small for the Opus audio packets.

**Comment by Krzmbrzl** [comment]
> and if I understand it correctly this is the same as your proposal (?)

yes

> How important is it that applications are allowed to use buffers of exactly 1024 bytes?

You mean for receiving the packet? I don't know - that's part of the reason why I put this on for discussion.
One thing you get by an upper size limit is that you can use arrays on the stack instead of allocating one on the heap (as the maximum size is known at compile time), but I guess it'd be rather simple to adapt to variable-sized arrays :shrug: 

> I ignored the overhead, but the numbers don't suggest that the 1020 bytes limit is too small for the Opus audio packets.

Yeah I think right now we don't need more than 1020 bytes for the packages a client sends. I think that's enough as well.

**Comment by Krzmbrzl** [comment]
I guess we can resolve this discussion by saying that the limit can be removed from the protocol. However audio packets should obviously only be as big as necessary and not full of unnecessary junk.

**Comment by streaps** [comment]
No idea how you come to that conclusion. Removing the packet size limit completely is a bad idea (IMO) and nobody brought up any good argument why it is necessary.

**Comment by Krzmbrzl** [comment]
Quoting yourself:
> Adding a few bytes to the 1024 limit would not be a problem at the network level. 1024 is pretty conservative and there is enough headroom.

> I guess 1 byte is an acceptable overhead, it's 1/48th of an IPv6 header :).

And in regards to 
> Removing the packet size limit completely is a bad idea (IMO) and nobody brought up any good argument why it is necessary.

have a look at 
> The rationale of this is that this would allow for the server to attach meta-data to a client's UDP packet (e.g. where are the packets sent to so that the receiver can know who else received this audio).

**Comment by streaps** [comment]
Which doesn't mean that the limit has to be removed completely. Adding data by the server is different than removing all restrictions from the specification. Letting the clients do whatever they want doesn't improve anything.

**Comment by Krzmbrzl** [comment]
I agree that the size of client packets should be limited. And in fact my original proposal (though admittedly not formulated super clearly) was about removing the size limit for the server only:
> I think right now we tend to remove the size limit only for messages sent from the server. 

Thinking about this some more though, I think the client's packet size restrictions doesn't need to be part of the protocol. Instead this should be a server-specific setting that'll be communicated to the client in e.g. the capabilities message requested in #4224).
This way we aren't limited by a hard-coded limit in the protocol. If a server thinks that for some reason its clients need bigger packages, it can allow it. On the other side if this is a server that doesn't have too much bandwidth, it can also reduce the allowed size for all clients.

All in all I think we gain quite a bit of flexibility by not having this as part of the protocol.

**Comment by Krzmbrzl** [comment]
In the last team meeting we agreed on dropping the limit from the protocol specification and turning this into a server-side setting instead.
