### ISSUE TITLE
Mumble 1.3.1 build failed with new OpenSSL 3.0.0 alpha3 - undeclared identifier 'CRYPTO_MEM_CHECK_ON'

### ISSUE THREAD

**Issue by AngryPenguinPL** [mumble-voip/mumble#4266]
**Describe the bug**
When build new Mumble 1.3.1 for OpenMandriva Cooker I see build error:
```
make[2]: Leaving directory '/builddir/build/BUILD/mumble-1.3.1/src/mumble'
../SelfSignedCertificate.cpp:48:22: error: use of undeclared identifier 'CRYPTO_MEM_CHECK_ON'
          if (CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON) == -1) {
                              ^
1 error generated.
make[2]: *** [Makefile.Release:2865: ../../release/.obj/mumble/SelfSignedCertificate.o] Error 1
make[2]: *** Waiting for unfinished jobs....

```
**Steps to Reproduce**
1. Build on OpenMandriva Cooker
1. Or on any distro with new OpenSSL 3.0.0 alpha3
2. See build error 

**Expected behavior**
Compilation will be successful

**Desktop (please complete the following information):**
 - OS: [Linux OpenMandriva Cooker]
 - Version: [e.g. Mumble 1.3.1]
 - LLVM/Clang 10.1 compiler

**Additional context**
The problem is probably the new OpenSSL 3.0.0 alpha3. When building with the old version 1.1.1 the build is successful.

Here is build content: https://abf.openmandriva.org/build_lists/780879
Full build log: https://file-store.openmandriva.org/api/v1/file_stores/d739d03599c19d1f9decd35d59200e05757122b7.log?show=true

**Comment by davidebeatrici** [comment]
Does this happen with 1.4.0 (`master`) as well?

**Comment by bendem** [comment]
From the openssl's [master man page](https://www.openssl.org/docs/manmaster/man3/CRYPTO_mem_ctrl.html):


> HISTORY
>
> OPENSSL_mem_debug_push(), OPENSSL_mem_debug_pop(), CRYPTO_mem_debug_push(), CRYPTO_mem_debug_pop(), CRYPTO_mem_leaks(), CRYPTO_mem_leaks_fp(), CRYPTO_mem_leaks_cb(), CRYPTO_set_mem_debug(), CRYPTO_mem_ctrl() were deprecated in OpenSSL 3.0. The memory-leak checking has been deprecated in OpenSSL 3.0 in favor of clang's memory and leak sanitizer.

**Comment by streaps** [comment]
deprecated usually doesn't mean removed and unavailable.

**Comment by bendem** [comment]
> deprecated usually doesn't mean removed and unavailable.

I'm no openssl developper, there is probably a flag to bring it back.

**Comment by AngryPenguinPL** [comment]
> Does this happen with 1.4.0 (`master`) as well?

Yes, same error with today's master.

**Comment by loqs** [comment]
https://github.com/openssl/openssl/blob/89cd17a031e022211684eb7eb41190cf1910f9fa/crypto/mem.c#L267

If CRYPTO_mem_ctrl is defined then it returns -1 so 

https://github.com/mumble-voip/mumble/blob/f04d6635a9158a5dc42ccc814eb36e5272fdf4b3/src/SelfSignedCertificate.cpp#L45

will error out when built against an openssl 3.0.0 debug build that has OPENSSL_NO_CRYPTO_MDEBUG undefined and hence CRYPTO_MEM_CHECK_ON defined and would pass and ifdef guard?

**Comment by Krzmbrzl** [comment]
No idea :shrug:

**Comment by TerryGeng** [comment]
A similar error that has something to do with OpenSSL 3.0.0:
```
../src/SelfSignedCertificate.cpp:64:8: error: 'RSA_new' is deprecated [-Werror,-Wdeprecated-declarations]
        rsa = RSA_new();
/usr/local/opt/openssl/include/openssl/rsa.h:201:1: note: 'RSA_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 RSA *RSA_new(void);
```
