### ISSUE TITLE
[Question] Setting background images in html tables in Mumble

### ISSUE THREAD

**Issue by DuckBoss** [mumble-voip/mumble#4268]
Hello! Not sure if this is the right place to ask, but how do you add a background image to an html table in mumble?

I've found background colors and other table stylings to work just fine but background images don't seem to work. I've tried both base64 encoded strings as well as image paths.
```
<table style="background: url('img_string')", blah blah blah> table content </table>
```
Am I doing this wrong or does the current Qt version not support background images in html tables for the mumble client?

**Comment by Krzmbrzl** [comment]
Qt seems to support the `background-image` CSS: https://doc.qt.io/qt-5/richtext-html-subset.html but but I can't find a mention of `url(...)` there. Thus my guess is that this is unsupported and thus the reason why your example doesn't work :thinking:

**Comment by DuckBoss** [comment]
I've been trying all sorts of combinations of the `background/background-image` tags and none of them seem to be working for me.
The closest I got was with `background-image: url(base64_encoded_string)` where it generated a black image (sometimes white image).

**Comment by Krzmbrzl** [comment]
As we don't do any HTML parsing ourselves, I'm like 95% sure that this is a Qt thing. You'll probably be better off asking this kind of question in a Qt forum. I have no idea about what exactly Qt is capable of and where the limitations are :shrug: 

Or do you know of other Qt applications that render this properly? :thinking:

**Comment by DuckBoss** [comment]
Hmm, I'm not sure. The only thing I've found about this issue was about QtStyleSheets which seem to be a bit different than the raw html I've been using. Apart from that, the background-image tag seems to be valid for Qt 5+.
I'll look further into this and see if I can find anything, please let me know if you find something as well! =)

**Comment by Krzmbrzl** [comment]
Yeah I also found something on styleSheets but these cases typically deal with images and icons that are baked into the application somehow, so I'd say that's a different manner :shrug:

**Comment by DuckBoss** [comment]
I've been looking into this for a while, and although the Qt5 docs say it supports background images for tables, I haven't been able to get it to work.
Thanks for the help @Krzmbrzl  but I don't think this one is possible.
