### ISSUE TITLE
Discussion: Should we abandon the QT GUI and go to wxWidgets?

### ISSUE THREAD

**Issue by dingpengyu** [mumble-voip/mumble#4269]
hello team
Currently mumble mainly uses qt gui.
The advantage of qt gui is that it has a large number of users, perfect functions and modules, and good community support.
The disadvantages of qt gui in my opinion are these:
First of all, the running speed of qt gui is very slow, and it is when using the keyboard to browse.
Secondly, qt gui is not ideal for accessible support.
Finally, the IE8N translation of qt gui is not satisfactory.
So what are the advantages of wxWidgets?
First of all, wxWidgets has good cross-platform performance, whether it is Windows or Linux, including Mac OS.
Secondly, wxWidgets has good support for accessible.
Finally, wxWidgets can use gettext to translate IE8N multilingual.
You can comment below
thanks

**Comment by Krzmbrzl** [comment]
First of all: Should we decide to do so, it'll take quite a while until we would even be able to.

We are currently planning a major refactoring of our code base that'll also split the backend from the frontend. The backend will throw out Qt entirely.

Therefore it should be comparatively easy to create a custom frontend (in whatever language you want) on top of the backend that'll provide all functionality.

I guess however that for now we'll stay with Qt for the frontend. I did think about trying out wxWidgets as well though and maybe there could be an alternative UI (frontend) that uses wxWidgets (which would have to be maintained separately though).

In terms of your arguments: I haven't experienced the UI to be slow, the translation seems to work just fine and afaik the accessibility is also reasonable :shrug:

**Comment by streaps** [comment]
I'm using Mumble on an Raspberry Pi 2 and even if it's not super snappy, it's also not slow. There is some delay until the Settings window opens, but I'm not sure that this is Qt's fault.

> First of all, the running speed of qt gui is very slow, and it is when using the keyboard to browse.

Which OS do you use? Can you describe in more detail what performance problems you experience?

> Secondly, qt gui is not ideal for accessible support.

I rarely use the keyboard for navigation. I tried to tab through the Settings dialogs and it is indeed a mess. (at least with my outdated Mumble 1.3 pre-release version on Debian).

Is the accessibility support a general Qt problem or a Mumble thing? How could wxWidget solve it when it uses GTK or Qt on Linux?

**Comment by trudnorx** [comment]
My experience with wx is that it's limited, annoying and suitable for no more than small projects.

**Comment by Krzmbrzl** [comment]
I guess for now we can conclude: Probably not - though in the future it'll get a lot easier to develop UI frontends for Mumble, so if at any point you want to give it a shot, feel free to do so :)

**Comment by RockBrentwood** [comment]
Audacity is written on top of wxWidgets. We've been considering, for a while now, putting out a replacement for it integrating some of the advanced DSP routines we have and use (forward and inverse spectrographs, frequency relocation similar to CSound & Loris, scalographs, reverse-mixing, etc.) The question has come up in our discussions of whether to make the replacement Qt-based. It can also be used for games, like Asteroid Cresta, which we had no difficulty porting over from Windows to Linux. For applications like these, commercial licensing restrictions are not going to come into play.

**Comment by EnziinSystem** [comment]
I've observed that applications built with wxWidgets have a very rough and ugly interface. It was only recently that issues like DPI, anti-aliasing were discussed and implemented in version 3.15.
wxWidgets has very little documentation and a GUI creation tool of enough magnitude, it's almost as if you have to create a GUI from C++ code while imagining a GUI interface.

**Comment by ErikLethDanielsen** [comment]
wxWidgets is slow just look at KICAD, maybe it's OK on windows but on linux it sucks
QT is much better KDE and FREECAD is written in that
even Linux Torvalds have moved to QT
https://www.youtube.com/watch?v=ON0A1dsQOV0

apt install qtcreator //fantastic ide
2 minutes and you have a cross platform app
