### ISSUE TITLE
Mumble 1.3.1 crashes at start with "Failed to create d8input"

### ISSUE THREAD

**Issue by Aneduna** [mumble-voip/mumble#4272]
**Describe the bug**
Sometimes until I restart my computer when opening mumble an [error dialog with the text "GlobalShortcutWin: Failed to create d8input"](https://i.imgur.com/mqhtzHS.png).

After the popup the other windows are unresponsive until I close the error popup and mumble closes. This makes mumble unusable.

**Steps to Reproduce**
This is tough. Sometimes it starts just fine, then the next day without changing anything it doesn't work at all until I restart. I haven't seen a pattern yet.

When it happens, it is really easy to reproduce:
1. Start mumble.exe
2. popup comes

Considering nobody else seems to have this specific issue, it's hard for me to give a specific thing to reproduce.

**Expected behavior**
I expect mumble to start and afterwards being able to join a server.

**Screenshots**
![dwm_2020-06-09_13-01-36](https://user-images.githubusercontent.com/9990060/84144134-4679aa80-aa47-11ea-807f-3bd97e3000b3.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Mumble 1.3.1 from release page

**Additional context**
Unless I restart the computer, a mumble reinstall doesn't change my problem.
Restarting is not a good solution as having to close everything kills my workflow for a good 10 minutes, this is annoying.
This seems to happen on older Versions as well, I tried 1.3.0 and 1.2.15.
No overlay enabled.
I don't seem to have any other special problems with other programs when that happens.
console.txt:
> <W>2020-06-09 12:48:21.953 DirectSound: Disabled as WASAPI is available
<W>2020-06-09 12:48:21.953 ASIO: No valid devices found, disabling
<W>2020-06-09 12:48:21.967 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2020-06-09 12:48:21.970 libopus v1.1.3 from C:/Program Files/Mumble/Versions/1.3.1/opus.dll
<W>2020-06-09 12:48:21.978 CELT bitstream 8000000b from C:/Program Files/Mumble/Versions/1.3.1/celt0.0.7.0.dll
<W>2020-06-09 12:48:21.986 CELT bitstream 80000010 from C:/Program Files/Mumble/Versions/1.3.1/celt0.0.11.0.dll
<W>2020-06-09 12:48:21.986 Theme: "Mumble"
<W>2020-06-09 12:48:21.986 Style: "Lite"
<W>2020-06-09 12:48:21.986 --> qss: ":themes/Mumble/Lite.qss"
<W>2020-06-09 12:48:21.987 Locale is "en_DE" (System: "en_DE")
<W>2020-06-09 12:48:22.035 Database SQLite: "3.18.0"
<W>2020-06-09 12:48:22.036 Bonjour: Failed to load dnssd.dll
<W>2020-06-09 12:48:22.037 Updating application palette
<F>2020-06-09 12:48:22.046 GlobalShortcutWin: Failed to create d8input
<W>2020-06-09 12:48:22.139 AudioInput: Opus encoder set for VOIP
<W>2020-06-09 12:48:22.139 AudioInput: 96000 bits/s, 48000 hz, 480 sample
<W>2020-06-09 12:48:22.148 WASAPIInput: Latencies 100000 30000 => 100000
<W>2020-06-09 12:48:22.153 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2020-06-09 12:48:22.157 WASAPIInput: Mic Stream format 1
<W>2020-06-09 12:48:22.157 WASAPIInput: Stream Latency 0 (970)
<W>2020-06-09 12:48:22.159 AudioInput: Initialized mixer for 2 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2020-06-09 12:48:22.160 WASAPIOutput: Output stream format 1
<W>2020-06-09 12:48:22.160 WASAPIOutput: Stream Latency 0 (1440)
<W>2020-06-09 12:48:22.160 WASAPIOutput: Periods 10000us 3000us (latency 0us)
<W>2020-06-09 12:48:22.160 WASAPIOutput: Buffer is 30000us (2)
<W>2020-06-09 12:48:22.161 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-06-09 12:48:24.685 QThreadStorage: Thread 0x2a8ab4fded0 exited after QThreadStorage 7 destroyed
<W>2020-06-09 12:48:24.685 QWaitCondition: Destroyed while threads are still waiting
<W>2020-06-09 12:48:24.685 QWaitCondition: Destroyed while threads are still waiting
<W>2020-06-09 12:48:24.686 QObject::~QObject: Timers cannot be stopped from another thread

I am pretty much only opening this issue because I have no idea how to even troubleshoot this.

**Comment by Krzmbrzl** [comment]
The line causing the warning is
https://github.com/mumble-voip/mumble/blob/1d7fbd936562d59b6ddd17b009183e68c4c4bf92/src/mumble/GlobalShortcut_win.cpp#L147-L150

To me it seems that [DirectInput](https://en.wikipedia.org/wiki/DirectInput) can't be started for some reason... Apparently the `DirectInput8Create` (https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416756(v=vs.85)) fails. I have never worked with that though, so I can only guess as of why this could be...

The fact that it only happens sometimes is weird though :thinking:

**Comment by davidebeatrici** [comment]
We probably shouldn't use `qFatal()`, global shortcuts are not a mandatory feature...

We should also print the return value. From https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416756(v=vs.85):

> If the function succeeds, the return value is DI_OK. If the function fails, the return value can be one of the following error values: DIERR_BETADIRECTINPUTVERSION, DIERR_INVALIDPARAM, DIERR_OLDDIRECTINPUTVERSION, DIERR_OUTOFMEMORY.

I'm already working on implementing raw input (#4039) though, which should allow us to get rid of DirectInput.

**Comment by BonzoG** [comment]
If it helps anyone work around the issue, this also happens to me but **only** when I am running Parsec (remote desktop/game streaming software). Parsec also causes issues in certain DirectInput games, and when I quit it Mumble runs perfectly.

**Comment by ZeroAbility** [comment]
Is this still an issue in 1.4?

**Comment by Aneduna** [comment]
I am not using Mumble actively anymore. I downloaded 1.4 and it _seems_ to work first try.
Looking back at the issue in regards to the comment about Parsec. I think I also had Parsec installed back then.

Also I imagine this got fixed back in 2021 when hooking was replaced by raw input, but who knows.

**Comment by Krzmbrzl** [comment]
Thanks for the feedback :+1: 
In this case, let's close this as resolved until proven otherwise.
