### ISSUE TITLE
Mumble + Game causes massive mouse sensitivity spikes

### ISSUE THREAD

**Issue by krosenfeld0** [mumble-voip/mumble#4274]
Whenever I play games (via steam, specifically TF2) and use mumble at the same time my mouse sensitivity instantly increases drastically, specifically seeming like an extreme form of mouse acceleration gets turned on. 

I can be in a server and my mouse will be fine, then launch mumble and instantly in-game the increased sensitivity effect happens. I am using the most current version of mumble, Windows, and overlay is turned off. When Googling I see some people having the same issue with WoW, but no fixes to be found. Any help with this would be greatly appreciated.

**Comment by davidebeatrici** [comment]
#4039.
