### ISSUE TITLE
Overlay does not work anymore in 1.3.1

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#4281]
The Overlay does not work anymore in 1.3.1.

**Desktop:**
 - OS: Windows 10 (should be an issue for all)
 - Version: Mumble 1.3.1

PR #4041 disabled the overlay by default. It includes commit aac3214d4be2ba31c852619bc8d3666391dcd02a which improves the code base, but introduces a regression. In introduces the `createPipe` method, moves initialization code there but never calls it.
https://github.com/mumble-voip/mumble/pull/4041/commits/aac3214d4be2ba31c852619bc8d3666391dcd02a#diff-bd43cc370108609b2ea02c12eae197c4R226

**Comment by MS-CLAN** [comment]
The last version of Mumble, 1.2.19, had a working overlay for Lineage 2. I checked all versions, but it doesn't work in newer versions. More accurately, it doesn't turn on. However, if I open the old version with the overlay, close it, and immediately open the new version, the overlay sometimes turns on for the new version. However, this doesn't last long; after half an hour, it freezes, and I have to reopen the old version, then the new one. Please support the Lineage 2 overlay in the new version of Mumble.
