### ISSUE TITLE
1.3.1 Mumble Update, Battleye Blocking Overlay (R6 Siege) - Certificate Needs To Be Whitelisted

### ISSUE THREAD

**Issue by grravity** [mumble-voip/mumble#4286]
**Describe the bug**

Battleye (Rainbow Six Siege) blocking Mumble 1.3.1 (Windows 10). Worked no issues on 1.3.0.
I do not have positional audio on, just the visual overlay.

```
19:16:08: Starting BattlEye Service...

19:16:17: Launching game...
19:16:26: Note: File blocks can be ignored if they don't cause problems with the game.
19:16:26: [INFO] Blocked loading of file: "C:\Program Files (x86)\Mumble\Versions\1.3.1\mumble_ol_x64.dll".
```

**Steps to Reproduce**
1. Open Mumble, Enable Overlay
2. Start up Rainbow Six Siege (Yes I started Mumble first)
3. Receive Battleye error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.3.1

**Additional context**
Worked no issues on 1.3.0.
Hope to see this fixed soon, it sucks not being able to see who's talking.  I guess I can downgrade,  but there's no way to downgrade via installer. I'd have to completely uninstall and reinstall which is frustrating to be quite honest. But still hope to see it resolved soon with an update.

**Comment by Krzmbrzl** [comment]
I don't know how BattleEye's technique of figuring out what is allowed works, but this is not Mumble's responsibility. If they decide to block Mumble or rather the overlay component of Mumble, then there's nothing we can do (afaik).

/cc @davidebeatrici, @Kissaki did I miss something?

**Comment by davidebeatrici** [comment]
Could you check whether the DLL file appears to be properly signed, please?

Right click on it -> `Properties` -> `Digital Signatures`

**Comment by grravity** [comment]
> I don't know how BattleEye's technique of figuring out what is allowed works, but this is not Mumble's responsibility. If they decide to block Mumble or rather the overlay component of Mumble, then there's nothing we can do (afaik).

Yes but again, it was working last update. I find it hard to believe they would randomly block it. Something must've changed on Mumble's side between one update. I know most anti-cheats try to block `.dll` injections, but again, something specific must've changed between Mumble 1.3.0 and Mumble 1.3.1.

> Could you check whether the DLL file appears to be properly signed, please?

The digital signature for `Program Files (x86\Mumble\Versions\1.3.1\mumble_ol_x64.dll` shows `Open Source Developer, David Beatrici |  sha1 | Monday, June 8, 2020 05:53:58`
So it looks like it's signed properly.
I also checked `mumble_ol_helper.exe`, `mumble_ol_helper_x64.exe`, `mumble_ol.dll` and they all have the same signature applied.

**Comment by davidebeatrici** [comment]
I think BattlEye whitelisted our previous signing certificate (which was Mikkel's).

Unfortunately that certificate could not be renewed anymore, which is why 1.3.1 is signed with a new one (mine).

You can verify my theory simply by replacing the DLL with Mumble 1.3.0's one.

**Comment by grravity** [comment]
> I think BattlEye whitelisted our previous signing certificate (which was Mikkel's).
> You can verify my theory simply by replacing the DLL with Mumble 1.3.0's one.

In response to my edit above, I've tried multiple games and it seems the overlay is just straight up not showing on any games for me.

Will replacing the dll with Mumble 1.3.0's one break anything? 
Also is it just `mumble_ol_x64.dll` or is it also `mumble_ol.dll` that needs to be replaced?

**Comment by Krzmbrzl** [comment]
> In response to my edit above, I've tried multiple games and it seems the overlay is just straight up not showing on any games for me.

See #4281 - there was a bug introduced in the overlay code for 1.3.1

**Comment by grravity** [comment]
> > In response to my edit above, I've tried multiple games and it seems the overlay is just straight up not showing on any games for me.
> 
> See #4281 - there was a bug introduced in the overlay code for 1.3.1

Ok, so the overlay should be fixed in 1.3.2? Do we have an ETA on that just curiously?
Also, I just replaced the .dll with the one from 1.3.0, and I do not seem to be triggering the Battleye detection anymore. 

So, it looks like Battleye needs to be contacted to get it whitelisted? I assume Battleye is not the only one who is going to cause warnings for players, not sure how we'd go about that? 

Anyways, is it a bad idea in _anyway_ to continue using the overlay dll file for 1.3.0 in 1.3.1? Or is it fine to leave it for now?

**Comment by davidebeatrici** [comment]
It's completely fine, there are no changes in the overlay library's code.

But yes, the real solution would be to get the new certificate whitelisted.

**Comment by grravity** [comment]
Problem has not been resolved,  Battleye needs to be contacted.

**Comment by davidebeatrici** [comment]
@grravity Would you like to do it?

**Comment by grravity** [comment]
> @grravity Would you like to do it?

I can sometime tonight or tomorrow. Haven't had a chance.

**Comment by davidebeatrici** [comment]
Awesome, thank you very much!

**Comment by Krzmbrzl** [comment]
I marked this issue as "needs-more-input" in order to for this issue to not be forgotten.

**Comment by grravity** [comment]
Just want to point out, It's been over a week and I am yet to hear a reply from Battleye, and it's still being blocked.
I will report back if they reply, but so far nothing.

**Comment by Krzmbrzl** [comment]
Given that there is nothing we can do about this, we decided to close this issue.

The situation will from now on be tracked in the "Known issues" category of the most recent release - see https://github.com/mumble-voip/mumble/releases/tag/1.3.2

**Comment by grravity** [comment]
Alright, I still have yet to receive a response back from Battleye and the issue is stil occuring, can anyone else try reaching out as well? Thanks

**Comment by toby63** [comment]
> Alright, I still have yet to receive a response back from Battleye and the issue is stil occuring, can anyone else try reaching out as well? Thanks

@Krzmbrzl Maybe it would be more sucessful if you (the team) contact them, with an official emailadress (mumble.info).

@grravity Can you tell us what exactly you wrote to them?

---

Also interesting:
_Short Version:_
Specific game developers decided against allowing overlays and visual enhancement tools.

_Long Version:_
```
I’m using the software XY while playing my game with BE enabled, is it allowed or can I get banned for it?

Generally we only ever ban for the use of actual cheats/hacks or components of such hacks which are designed to intentionally bypass BE’s protection. Otherwise you don’t need to worry about getting banned. For example, non-cheat overlays and visual enhancement tools like Reshade or SweetFX are generally supported unless desired otherwise by the game developers (the latter two are currently blocked in PUBG, Fortnite and Islands of Nyne). We might decide to kick (not ban) you at some point for using a specific program (such as macro tools), but that won’t automatically flag you as a cheater.
```
From https://www.battleye.com/support/faq/

@grravity 
So maybe you should contact the developers of Rainbow 6 as well.

**Comment by grravity** [comment]
I did it through their site, and they sent me a confirmation email but it doesn't include a quote of my message.

>1.3.0

Yes, we discussed the new certificate needs to be whitelisted which was the issue. I contacted Siege as well and they were extremely unsupportive copy-pasting useless help messages until finally saying it'd be best to contact Battleye which I already did and told them I did, which they completely ignored.

This isn't an issue with Siege/Battleye blocking Mumble's overlay, it's an issue with them not having the new certificate Mumble has added to their whitelist which is why the old one works.

**Comment by grravity** [comment]
Has anyone heard anything from Battleye? I have not received any replies personally still.

> Maybe it would be more sucessful if you (the team) contact them, with an official emailadress (mumble.info).

Has this been done @Krzmbrzl ? Not sure what else to do. It will never get whitelisted at this rate lol.

**Comment by Krzmbrzl** [comment]
No it hasn't been done and I don't think that it would have more success given that you didn't even receive a reply.
In the end I just think that BattleEye doesn't care that much about whitelisting smaller applications and therefore they are processing requests really slowly.

If they had denied your request saying that they don't whitelist stuff on demand of 3rdparty people, then I think it would make sense to approach them officially again. But before they haven't answered you, I don't think that'd change anything.

> I also saw about CS:GO's new Trusted Mode having issues. Any luck with that one?

Nope. I didn't get a reply either (as I kinda expected) :shrug:

**Comment by Krzmbrzl** [comment]
I just sent them an email:
```
Hello,

I am a core developer of the Mumble application (https://www.mumble.info/) and part of this project is a so-called "Overlay" that can be displayed on top of fullscreen games in order to see who's currently talking to you.

https://github.com/mumble-voip/mumble/issues/4286 reported that recently BattleEye stopped allowing the Overlay to work which we think is because we had to get ourselves a new certificate for signing the binaries and we believe it has not yet been whitelisted by you.

Thus we'd kindly ask you to whitelist our certificate / the overlay itself so our users can continue using it. Please let me know how the process of getting it whitelisted works and what additional information you need from us.
```

Let's see if we get a response to that...
