### ISSUE TITLE
Client treats signed certificates as self-signed

### ISSUE THREAD

**Issue by TredwellGit** [mumble-voip/mumble#4289]
**Describe the bug**
https://github.com/mumble-voip/mumble/commit/974ee68df303f99360999a2ee17f99b05d3f4437#diff-42822532959c42a47c7dbc9ff2049e93L111 makes clients treat signed certificates as self-signed.

**Steps to Reproduce**
Connect to server with signed certificate.

**Expected behavior**
Not display the self-signed certificate window.

**Desktop:**
 - OS: Arch Linux
 - Version: Mumble client d73465e, qt5-base 5.15.0-3, openssl 1.1.1.g-2

**Comment by Krzmbrzl** [comment]
Damn - so I misunderstood the docs after all... Thanks for reporting it! :)

**Comment by Krzmbrzl** [comment]
Could you test whether #4293 properly fixes this issue, please?

**Comment by TredwellGit** [comment]
Thanks, #4293 fixes the issue.
