### ISSUE TITLE
building with boost-1.73.0 requires changes in bind placeholders

### ISSUE THREAD

**Issue by Polynomial-C** [mumble-voip/mumble#4295]
I get lots of messages like this when building murmur with boost-1.73.0 (haven't verified if it also affects mumble):
```
In file included from /usr/include/boost/bind.hpp:30,
                 from ./murmur_pch.h:91,
                 from ../ACL.cpp:9:
/usr/include/boost/bind.hpp: At global scope:
/usr/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
```
I suppose this warning might turn into an error with future boost releases.

**Comment by Polynomial-C** [comment]
They also mention this in their [1.73.0 changelog](https://www.boost.org/users/history/version_1_73_0.html):

`Changed all uses of the boost.bind placeholders to use the boost::placeholders namespace.`

**Comment by Krzmbrzl** [comment]
Yeah I noticed these as well but as long as it doesn't actually break compilation, I think this is really low priority right now.

Besides: I don't even know where we're using bind... I think (partly) in the auto-generated code for e.g. the ICE interface. That'd make it a bit more complicated to refactor...

If someone finds the time and motivation to refactor accordingly, we'd happily accept a PR :)
