### ISSUE TITLE
Losing Voice Chat after some time

### ISSUE THREAD

**Issue by PiotrSzurek** [mumble-voip/mumble#4300]
**Describe the bug**
During using the mumble in ver 1.3.0 - its randomly losing Voice Chat communication - I dont get dropped from server, I see list of users and I can activate voice chat - but no one hear me or I dont hear them. Its happening for around 3 months now totally randomly. That happening on each server I used.

**Steps to Reproduce**
1. Open Mumble
2. Do stuff - e.g. playing/switching alt+tab between applications. 
3. Find out that you dont communicate with anyone on chat (I can see everyone)
4. Relog on server
5. Voice chat is working normally. 

**Expected behavior**
I wont lose voice communication.

**Screenshots**
None -

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: Mumble 1.3.0

**Additional context**
None... might be the reason of alt+tab...

**Comment by Krzmbrzl** [comment]
Any chance this happens every time you changed the settings?

Potentially related: #2064

**Comment by PiotrSzurek** [comment]
I do not change any settings - sometime (really rarly) I need go torugh voice configuration to get back activated push to talk. That issue I described happen without any changes in settings.

**Comment by Krzmbrzl** [comment]
When this happens could you monitor the incoming and outgoing UDP packets on your computer? See e.g. https://stackoverflow.com/questions/9163241/is-there-a-way-to-monitor-what-process-sends-udp-packets-source-dest-ip-and-por

It would be interesting to see whether your client actually stops sending messages or if something else is going on.

**Comment by PiotrSzurek** [comment]
Hi, I checked with LiveTCPUDPWatch and its looks like I do not loosing packages or anything - that case happen durring running this program. Ofc I deleted some of not important stuff :P

==================================================
Process ID        : 3972
Received Bytes    : 146 077
Sent Bytes        : 117 986
Received Packets  : 1 357
Sent Packets      : 1 108
Receive Speed     : 
Send Speed        : 
Connect Time      : 
Disconnect Time   : 
Accept Time       : 
Connections Count : 
Disconnect Count  : 
Remote IP Country : 
==================================================

**Comment by Krzmbrzl** [comment]
I assume the amount of received and sent bytes still increases even though you can't hear or talk in Mumble?

**Comment by PiotrSzurek** [comment]
Its hard to tell, because its totally random - and that most of those applications do not catch upcoming packets by each sended package... I will try today to check this again with veryfing packets upcoming and sending - also I will paste log here.

**Comment by Mnior** [comment]
Are you using Remote Desktop (RDP)?

On my version 1.4.287 I also observe similar behavior.
Keyboard shortcuts don't work, audio doesn't work in both directions.
But after re-saving the settings, everything starts working.

RDP are used from a Linux computer via Remmina. But I can't yet test whether Mumble works directly when running Remote Desktop.
