### ISSUE TITLE
[Question] How can one download builds from azure?

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4303]
I saw mentions of this in https://github.com/mumble-voip/mumble/pull/4209#issue-423646143. 
But I can't seem to find a method to download things, I can only look at the artifacts but not download them.
For example: https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=2049&view=artifacts&type=publishedArtifacts

Reason/Usecase: I would like to try out some features including #4167, #4209 and #4212 with friends who use windows and mac os.

**Comment by Popkornium18** [comment]
Click on the three dots on the right.
![image](https://user-images.githubusercontent.com/46488511/85032310-f655c300-b17f-11ea-9ffb-8e5b0f47662a.png)

**Comment by toby63** [comment]
Thank you.

But what a silly design decision of the Azure makers (Microsoft is it, right?), the dots are not visible at first.
