### ISSUE TITLE
Channel listener not exists on mumble server version 1.3

### ISSUE THREAD

**Issue by mrkmenonuiu** [mumble-voip/mumble#4315]
![image](https://user-images.githubusercontent.com/31846312/85672357-9eb9d900-b6e4-11ea-8cc5-3f6147249752.png)

channel listener feature added on march 26 2020. but after that no mumble server version is released. i need channel listener feature for my project. i am using slice2cs to convert murmur.ice to cs file. server give me method not found exception because mumble 1.3 server does not have that method. how would i get that? thanks.

**Comment by Popkornium18** [comment]
Compile it from the latest commit.

**Comment by streaps** [comment]
You also can go to
https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=2066&view=artifacts&type=publishedArtifacts

and download the nightly build from Saturday.

**Comment by streaps** [comment]
Or got to
https://dev.azure.com/Mumble-VoIP/Mumble/_build?view=runs&branchFilter=5

click on the latest pipeline run. Then in the top box on "3 published".

**Comment by Krzmbrzl** [comment]
ChannelListeners will only be part of Mumble's 1.4.0 release as features aren't backported to existing versions.

Thus you either have to wait until its release (or snapshot releases), compile it from source yourself or pick a snapshot from the CI as mentioned by streaps :point_up:
