### ISSUE TITLE
Mumble always lights up in the windows volume mixer when there's any audio at all from any source

### ISSUE THREAD

**Issue by AirPhforce** [mumble-voip/mumble#4319]
**Describe the bug**

https://i.imgur.com/EW89IoN.png

Any audio at all makes mumble light up. Happens even when deafened or muted by the server or myself. I can't 'hear' it though it's just in the mixer

**Steps to Reproduce**
1. Load mumble
2. Play any noise from any source

**Expected behavior**
Mumble to not do that

**Screenshots**

https://i.imgur.com/EW89IoN.png

**Desktop (please complete the following information):**
Windows 10 

**Additional context**
Posted about it on le epic reddits but decided to post here as well since it seems to be a legit bug. 

Edit; Muting the mic via windows 'fixes' this but mumble can't be used then.

**Comment by Krzmbrzl** [comment]
What happens if you mute the actual audio source (in the screenshot Firefox) in the mixer?

Inside Mumble does anything light up (e.g. is any client (maybe your own) is marked as speaking?)

**Comment by AirPhforce** [comment]
If I mute the audio source, it does not light up in Mumble.

Mumble does not light up as if I am speaking and nobody can hear the 'extra' audio or whatever from Firefox.

**Comment by Krzmbrzl** [comment]
Does this also happen if you're not connected to a server?

**Comment by AirPhforce** [comment]
Yes it does.

**Comment by Krzmbrzl** [comment]
> Happens even when deafened or muted by the server or myself.

Inside Mumble this essentially disables the whole audio code (to my knowledge), so it seems pretty weird that the artifacts come from Mumble in this case :thinking: 

The only thing I can think of is that maybe the audio backend will either still fetch the microphone input or writes empty audio data into the stream (aka silence).

Maybe @davidebeatrici has an idea about what's going on...

**Comment by AirPhforce** [comment]
I appreciate you guys looking into this for me. Let me know what other details I need to provide.

**Comment by TerryGeng** [comment]
I noticed the output level of mumble inside that mixer in your screenshot (the green bar) is not zero. Do you mean that green bar is always there even if no audio signal comes out from mumble? Does the height of that bar changes over time or it just stands there?

**Comment by AirPhforce** [comment]
> 
> 
> I noticed the output level of mumble inside that mixer in your screenshot (the green bar) is not zero. Do you mean that green bar is always there even if no audio signal comes out from mumble? Does the height of that bar changes over time or it just stands there?

Yes. 

Sorry about the slow reply for some reason git didn't email me.

On the newest mumble, issue still happens.

**Comment by Krzmbrzl** [comment]
@AirPhforce have you tried using a different audio interface in the audio input settings?

**Comment by AirPhforce** [comment]
Yes

**Comment by Krzmbrzl** [comment]
Which interfaces did you try?
Did you also try to switch the output interface?

**Comment by AirPhforce** [comment]
Interfaces? Sorry I don't know what you mean.

I only have mic and speaker, no other options there.

**Comment by Krzmbrzl** [comment]
Lol how can you say that you tried to change it and that it doesn't make a difference if you don't know what I'm talking about?!

If you go into the settings window, at the top of the audio input tab as well as the audio output tab, there's a dropdown selection for the audio interface (for the input and output respectively).
What is selected there and does it make a difference what you select there (and accept the changed settings)?

**Comment by AirPhforce** [comment]
I changed it to default device and then back to the actual device. Those are the only ones I had and what I did.

**Comment by Krzmbrzl** [comment]
Please give me the exact names of the interfaces that you are selecting in the dropdown.
And you did that for input and output and tried different input/output combinations?

**Comment by AirPhforce** [comment]
Here

https://imgur.com/a/gkq0nsR

**Comment by Krzmbrzl** [comment]
@AirPhforce could you please verify that the issue also persists with echo cancelling disabled, please?

**Comment by AirPhforce** [comment]
It's fixed with echo canceling disabled.

**Comment by Krzmbrzl** [comment]
Now that is very interesting. We had a fix for tue echo canceller that'll be part of 1.4.0 but hasn't been backported to 1.3.x

I'm not sure whether this issue here is covered by this though...

Would you be willing to test it out? You'd hage to uninstall 1.3.x before installing 1.4.0 though

**Comment by AirPhforce** [comment]
I use mumble too much to risk messing it up with multiple uninstalls. Seeing as this is only a display issue, once 1.4 hits, I'll re-open this and let you know if it's still happening.

**Comment by Krzmbrzl** [comment]
Understandable :) 

In that case I'll close this issue as "probably resolved" :+1:
