### ISSUE TITLE
Talking UI does not open in floating mode on tiling WMs

### ISSUE THREAD

**Issue by Popkornium18** [mumble-voip/mumble#4324]
**Describe the bug**
So this might be a very niche problem, but the talking UI does not open in floating mode (like the server browser for example).
Currently it looks like this on i3:
![image](https://user-images.githubusercontent.com/46488511/85953959-56b0e580-b974-11ea-850e-009340b3e36a.png)

**Steps to Reproduce**
1. Open Mumble with tiling WM
2. Open talking UI

**Expected behavior**
The window should open in floating mode, like this:
![image](https://user-images.githubusercontent.com/46488511/85954002-a4c5e900-b974-11ea-8723-85687ec99ea0.png)

**Comment by Krzmbrzl** [comment]
What's "floating mode"?

The problem seems to be that you don't have a window border (at the top to grab the window) :thinking:

**Comment by Popkornium18** [comment]
So in a tiling window manager the first window you open fills the whole screen. If you open a second window the space is split in half. A third one splits the window sizes in thirds. The windows never overlap each other and you don't need window decorations as you move everything arount with keyboard shortcuts.

There is however an exception for windows that set some specific hints. These are opened in "floating mode" because they don't tile but float above everything else like in every other desktop environment. This can be handy for small windows like "Are you sure?" Dialogs, since you probably never want those to fill up half of your monitor space.

The talking UI should set one of those hints since it should be floating :thinking: I am currently looking at what hint should be used.

**Comment by Krzmbrzl** [comment]
I know that the server-browser is modal but that means that you can't access anything else while it is open...

These are the available window flags available with Qt: https://doc.qt.io/qt-5/qt.html#WindowType-enum

**Comment by Popkornium18** [comment]
I try to solve this. Yes, modal window won't work. But if it's not possible to solve this in the mumble source, it's no big deal. People can just configure the WM to automatically switch this window to floating based on the title.

**Comment by Popkornium18** [comment]
Does anything not work as intended if you use `setWindowFlags(Qt::Tool | Qt::WindowStaysOnTopHint);`? That works for me :thinking: However I have no Idea how the "smaller than usual title bar and decoration" look since I don't have those in the first place.

**Comment by magnus-gross** [comment]
One could also set the X11 window flag to something that is considered to be a floating window by TWMs: https://github.com/rust-windowing/winit/issues/862#issuecomment-500168711

See https://doc.qt.io/qt-5/qt.html#WidgetAttribute-enum

That would only work on X11 then, but stuff like this (that is always on top stuff) is broken on Wayland anyway.

**Comment by Krzmbrzl** [comment]
Okay so `Qt::Tool` doesn't work as it basically removes the always on top behavior.

These flags seem to be working
- Dialog (though it made the window be a bit shorter than it is right now)
- SubWindow

(I have used these flags in place of `Qt::Window` in the current code)

Does any of those make the window float?

**Comment by Popkornium18** [comment]
`Qt::Dialog` makes the window float, `Qt::SubWindow` does not. Is the shorter window a problem?

**Comment by Krzmbrzl** [comment]
It turned out that the window doesn't actually get smaller. Instead Qt adds an additional button to the title bar (the "?" button) but I was able to remove it again, so at least on my system everything is back to how it was before with that.

Could you please verify that #4333 does indeed fix the issue on your machine? :)
