### ISSUE TITLE
My user is added to the talking UI over and over whenever I talk

### ISSUE THREAD

**Issue by Popkornium18** [mumble-voip/mumble#4325]
**Describe the bug**
So whenever I talk my username is added to the talking UI. This does not happen for the other users

**Steps to Reproduce**
1. Open Talking UI
2. Talk
3. Stop
4. Talk again

**Expected behavior**
No duplicates of my user are added

**Screenshots**
Windows 10:
![grafik](https://user-images.githubusercontent.com/46488511/85956111-c084bb80-b983-11ea-85f9-c98b16a5d7a8.png)
Linux
![image](https://user-images.githubusercontent.com/46488511/85956017-caf28580-b982-11ea-8612-c3906767c182.png)

**Desktop (please complete the following information):**
 - OS: Linux and Windows 10
 - Version: Mumble compiled from latest Commit. Murmur 1.3.0

**Comment by Krzmbrzl** [comment]
Uhm... I'll look into this. Never had this issue though :thinking:

**Comment by Krzmbrzl** [comment]
Can reproduce. Must have been introduced with one of the more recent commits :thinking: 

Maybe I'll have the time to dig into this this afternoon... Can't promise it yet though :shrug:

**Comment by Krzmbrzl** [comment]
Found some time right now and it turned out it was an easy fix - see #4326 :)
