### ISSUE TITLE
Mute microphone when others are talking (feedback / echo)

### ISSUE THREAD

**Issue by casipw** [mumble-voip/mumble#4328]
Hi, we have a rather unusual setup for meetings here: Some people are meeting on site, some are remote. We have a boundary layer microphone on site, which is continously on. Remote members use push-to-talk. The sound on site is good, but remote team members are hearing their own voice as a feedback.

An option which mutes the own (on-site) microphone when someone else is talking would be helpful. Would that be possible?

**Comment by Krzmbrzl** [comment]
That's what echo cancelation is for. You can enable that in the settings.

If you're not using a self-compiled version of the current master branch the echo cancelation is probably broken. It got fixed recently. 

The mute-when-others-are-talking is basically poor man's echo cancelation. 
And tbh I think this is a clumsy workaround at best as every I time I experienced this in other software, it annoyed me ^^

**Comment by casipw** [comment]
Thank you very much! Looking forward to the new version where echo cancellation is fixed.

**Comment by Krzmbrzl** [comment]
You're welcome :)
