### ISSUE TITLE
Mumble client 1.4.0 - Server Infos Page - French translation - Visual Problem - Missing "/" character

### ISSUE THREAD

**Issue by MadDeydey** [mumble-voip/mumble#4329]
Hello, 

I just built a new version of mumble and it seems that there is a visual problem with "Server Infos Page" on French translation (cf screenshot)
![2](https://user-images.githubusercontent.com/65441871/86125561-2afd3f00-badd-11ea-8935-9fbf6c381c96.PNG)

After investigations, it seems that the problem comes from the "/src/mumble/mumble_fr.ts" file.
Line 4510 - Col 47, a "/" character is missing, causing the bold tag staying open.

Regards

**Comment by Krzmbrzl** [comment]
Should be fixed on Transifex - thanks for reporting :+1:

(it's a `h2` tag though and not a bold tag but that's just details)

**Comment by Krzmbrzl** [comment]
In the next couple of days it should find its way into the master branch and from then on it should be fixed :point_up:

**Comment by Krzmbrzl** [comment]
Should be fixed now in the latest version of the master branch
