### ISSUE TITLE
macOS 11 Big Sur freeze

### ISSUE THREAD

**Issue by PhilipLPYT** [mumble-voip/mumble#4338]
Most of the time if I open Mumble on the new macOS 11 Beta and try to connect to my server, the application freezes and I need to force quit it. But sometimes, it would connect.

**Comment by Krzmbrzl** [comment]
Which version of Mumble are you using?
Which version is the server you are trying to connect to?
Does the CPU usage go up when Mumble freezes?
What is written to the developer console (can be enabled in the settings) when this happens?
Does this happen with any server you are trying to connect to or only a specific one?
Does Qt even support the macOS beta yet?
