### ISSUE TITLE
No .msi for new version 1.3.2

### ISSUE THREAD

**Issue by TalkLounge** [mumble-voip/mumble#4353]
[There's](https://github.com/mumble-voip/mumble/releases) no mumble-1.3.2.msi for the new version 1.3.2
404 not found

![grafik](https://user-images.githubusercontent.com/26689633/87063910-44a23300-c20f-11ea-80b8-af6d8ab13f25.png)

**Comment by Krzmbrzl** [comment]
We had to re-build the release as the initial build had the wrong version number set.

The binaries will be available shortly

**Comment by davidebeatrici** [comment]
We rebuilt the release, files are now available.

**Comment by dvzrv** [comment]
Hi, I work on the mumble/murmur packages for Arch Linux and would like to add, that removing a tag and all release assets and retagging from a packaging perspective is not great at all.

We had already built from the first tag and pushed the packages to the repository. I would rather appreciate a new tag in a situation like this in the future (e.g. 1.3.3 with a note about why).

**Comment by Kissaki** [comment]
I agree. Tags should be persistent. The next version number should be assigned for a different commit.
