### ISSUE TITLE
TLS 1.3 + 0-RTT

### ISSUE THREAD

**Issue by urlordjames** [mumble-voip/mumble#4356]
**Context**
TLS 1.3 and 0-RTT could potentially improve speed and security.

**Additional context**
#3663 seems to imply this is already implemented, but I've tried the following ciphers in Murmur 1.3.2 and none work.  Sorry if this is already implemented and I just didn't notice it...

`TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_8_SHA256:TLS_AES_128_CCM_SHA256`

(aka the ciphers listed on https://wiki.openssl.org/index.php/TLS1.3)

**Comment by Krzmbrzl** [comment]
What's 0-RTT? Some extension to TLS?

We are currently using OCB2 encryption which I believe is not part of OpenSSL due to patent problems...

See also: #3918

**Comment by urlordjames** [comment]
To my knowledge, 0-RTT is a feature of TLS 1.3 which makes the TLS handshake shorter which increases speed for handshakes which meet a certain criteria.  I’m just a server admin, not a cryptographer, might be wrong about that.

**Comment by Krzmbrzl** [comment]
I think in theory it is possible to use TLS 1.3 already:
https://github.com/mumble-voip/mumble/blob/e90eb8c4cd7edc0cd3eddafac622edc45efff794/src/murmur/Server.cpp#L1376-L1384

To my understanding and knowledge we basically allow any TLS version that exists. (which in itself is a problem - see #1436)

**Comment by Krzmbrzl** [comment]
Okay I just tested the approach @streaps posted in https://github.com/mumble-voip/mumble/issues/1436#issuecomment-644319996:
```
openssl s_client -tls1_3 localhost:64738
```
after having launched a local mumble server.

The handshake seems to have worked flawlessly and thus I'd say that the Mumble server already supports TLS 1.3 :thinking:

**Comment by Krzmbrzl** [comment]
When starting connecting my Mumble client (built in debug mode) it prints these as its TLS cipher preference:
```
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-AES128-GCM-SHA256
ECDHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-SHA
DHE-RSA-AES128-SHA
AES256-SHA
AES128-SHA
```

**Comment by urlordjames** [comment]
Hold on, I'm a bit confused...  How does that command enable TLS 1.3?  When I run it I get `s_client: Option unknown option -tls1_3`.  Is that supposed to go somewhere in my config.ini?

**Comment by Krzmbrzl** [comment]
No. That's 100% `openssl`. If this option isn't recognized on your system then I assume you're using an old version of OpenSSL that doesn't support TLS 1.3 yet? :thinking:

**Comment by urlordjames** [comment]
I suspected the same since I'm using Debian and the packages on the official repos are pretty much always outdated.  I went and compiled 1.1.1g from source and it still didn't work.  What version were you using?

**Comment by urlordjames** [comment]
I'm just going to assume this is a thing in the latest nightly build.  It seems you were able to get this to work.

**Comment by Krzmbrzl** [comment]
I seem to be using a version 1.1.1 from 2018 :thinking:

**Comment by streaps** [comment]
I'm not sure if Qt supports 0-RTT and I wouldn't expect it to be enabled by default. 

https://blog.trailofbits.com/2019/03/25/what-application-developers-need-to-know-about-tls-early-data-0rtt/

**Comment by Krzmbrzl** [comment]
Excellent article. Thanks for the link!
It seems like 0-RTT is quite tricky to get right... 

I couldn't find specific information about whether Qt enables it by default (if it is supported at all) but I share your suspicion that if they do support it, it would be disabled by default :point_up:
