### ISSUE TITLE
[Not bug, just trouble] Mumble is untrusted in CS:GO

### ISSUE THREAD

**Issue by maximilianrob** [mumble-voip/mumble#4357]
**Description of the bug**
After the last updates in CS:GO there is a new Trusted mode, that doesn't give me access to use your program.

**Expected behavior**
When I have launched CS:GO it says me, that I can't play in Trusted mode, because some restricted apps works (as I understood).

**Screenshots**
Message from game with launched Mumble and Murmur:
![scr](https://user-images.githubusercontent.com/12274109/87126774-7827a080-c295-11ea-8cbd-932aeec5030c.png)

 
**Desktop:**
 - OS: Windows 10 Home x64
 - Version: 1.3.2

**Additional context**

Earlier, It just had overlay restrictions (avatar in-game), but for now Mumble and Murmur are fully restricted.

I can decline Trusted mode, but that will destroy my Trust factor, so I'm gonna be connected mostly to cheaters.

Can you ask Valve to whitelist your program? Please. And thanks anyway.

**Comment by Krzmbrzl** [comment]
Where would such a request have to be made?

**Comment by Krzmbrzl** [comment]
Could you check if it works with [1.3.0](https://github.com/mumble-voip/mumble/releases/tag/1.3.0)? We had to use a new certificate from 1.3.1 onwards which is the reason why the overlay for these versions is blocked by BattleEye.

Maybe the same applies to CS:GO with the main application? :thinking:

**Comment by maximilianrob** [comment]
> Where would such a request have to be made?
I'm sorry, I don't know where actually it have to be, because It's not a Feature request or Report a security vulnerability as I think

> Could you check if it works with [1.3.0](https://github.com/mumble-voip/mumble/releases/tag/1.3.0)? We had to use a new certificate from 1.3.1 onwards which is the reason why the overlay for these versions is blocked by BattleEye.
> 
> Maybe the same applies to CS:GO with the main application? 🤔
The same problem with that version.

By the way, not only you have such a problem, for example, OBS, MSI Afterburner, GeForce Exp does not work too, CS:GO has individual whitelist IMO, It's not uses BattleEye.

**Comment by Krzmbrzl** [comment]
> CS:GO has individual whitelist IMO, It's not uses BattleEye.

Yeah I figured. I was just curious whether perhaps the old certificate has been whitelisted for this before. But as 1.3.0 doesn't work either, I assume this is really a completely new thing now.

Just to be clear: You have disabled the overlay in Mumble's settings when this happens?

**Comment by maximilianrob** [comment]
> Just to be clear: You have disabled the overlay in Mumble's settings when this happens?

Also it happens with disabled overlay

**Comment by Krzmbrzl** [comment]
That's weird then as from what I found online, only apps are blocked that try to interact with CS:GO. Mumble shouldn't do that though if the overlay is disabled.

When you disabled the overlay, did you restart Mumble before trying again?

**Comment by maximilianrob** [comment]
> That's weird then as from what I found online, only apps are blocked that try to interact with CS:GO. Mumble shouldn't do that though if the overlay is disabled.
> 
> When you disabled the overlay, did you restart Mumble before trying again?

Nope. It's launched without problem.

**Comment by Krzmbrzl** [comment]
Ah okay that makes sense then. Once the overlay has been started at Mumble's start it doesn't actually get shut down completely if you disable it in the settings.

So basically this setting only takes effect after a restart as then the overlay backend won't get started.

Alright so that means that we only have to ask for the overlay to be whitelisted.

I have searched a bit, but I can't find the proper way to approach Valve for this. The only thing I did find was the support area for CS:GO in Steam but this seems to be very specific to a few ingame-problems and none of these fit the overlay-case.
Also all support-sites I found for Valve redirect to the Steam ones.

So until someone can point me to where the whitelist has to be requested, there's nothing I/we can do.

For now I see this issue to be resolved. I'll add the CS:GO issue to the known issues in the release-area of Mumble.

**Comment by toby63** [comment]
@Krzmbrzl 
`questions@valvesoftware.com` 
According to https://store.steampowered.com/legal

By the way it seems they have big trouble :smile: : 
https://www.pcgamer.com/uk/csgos-trusted-mode-anticheat-system-is-live-but-its-causing-problems/

**Comment by Krzmbrzl** [comment]
@toby63 thanks for looking this up. I'll reach out to them and see what I can do :point_up:
