### ISSUE TITLE
Mumble can't connect to server

### ISSUE THREAD

**Issue by JimmyNT** [mumble-voip/mumble#4362]
Dear Staff,

My mumble can't connect to server, please check and give me some advise.

**Mumble Config** 
  Address : mumble.pandemic-horde.org
  Port       : 41001
  Username : JimmyNT Hachi

**tcping :** 

C:\Users\admin>tcping mumble.pandemic-horde.org 41001

Probing 5.39.74.90:41001/tcp - No response - time=2000.693ms
Probing 5.39.74.90:41001/tcp - No response - time=2001.098ms
Probing 5.39.74.90:41001/tcp - No response - time=2001.854ms
Probing 5.39.74.90:41001/tcp - No response - time=2001.216ms

Ping statistics for 5.39.74.90:41001
     4 probes sent.
     0 successful, 4 failed.  (100.00% fail)
Was unable to connect, cannot provide trip statistics.

**Check Port :**

C:\Users\admin>netstat -an | findstr 41001
  TCP    192.168.1.200:61303    5.39.74.90:41001       SYN_SENT

![image](https://user-images.githubusercontent.com/11498303/87241483-e020e700-c44d-11ea-8d9e-1f51efababfc.png)

Thank,
PhuocNguyen

**Comment by Krzmbrzl** [comment]
Have you been able to connect to this server before?
Are you able to connect to any other server?

**Comment by JimmyNT** [comment]
> Have you been able to connect to this server before?
> Are you able to connect to any other server?

yes, i was able to connect it before.

**Comment by Krzmbrzl** [comment]
Are you able to connect to any other server?

**Comment by Kissaki** [comment]
Looks like the server is offline/does not exist anymore.

Can you confirm if the server is running, and if other people can connect to it?

**Comment by JimmyNT** [comment]
Dear all,

I back to normal in this day, i dont know why, please close ticket.

Thank,
PhuocNguyen

![image](https://user-images.githubusercontent.com/11498303/87695247-72601c80-c7b9-11ea-82b5-4b1652d25e1e.png)

**Comment by Krzmbrzl** [comment]
Good to hear! :)
And thanks for the status update :+1:
