### ISSUE TITLE
ChannelListener IDs collide for multiple VServers

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#4366]
**Describe the bug**
As the ChannelListener's backend is implemented as a singleton, different VServers use the same backend. This means however that the user and channel IDs are no longer unique and thus prone to overwriting one another.

I guess the code needs to be refactored to move away from the singleton design (which worked fine for the client but is not suited for the server) and towards an instance per VServer.

**Comment by LucasToole** [comment]
In my original proposed fix for #4277 I changed User ID creation to use the in-tree CryptographicRandom::uint32() for random User IDs, as opposed to the current implementation which uses a queue of possible IDs. I ultimately scrapped it for a simpler solution, but could that be a solution to this bug? Or is there a more elegant way to handle this?

**Comment by Krzmbrzl** [comment]
The root cause of this issue is that the ChannelListener feature was developed without VServers in mind. Therefore the listener instances are managed by a singleton that is the same for different VServers. Thus the potential for ID clashes.

Therefore the fix will be to remove the singleton pattern from this feature and instead have a dedicated "listener manager instance" for each virtual server.

**Comment by Kissaki** [comment]
You described the technical issue but not what that means for server admins and users. How does the issue behave for them? Listening suddenly stops working because another user on another server starts listening on their server?

**Comment by Krzmbrzl** [comment]
Not exactly as you described. But listeners can start and stop appearing apparently at random because users on another VServer are changing their listen status
