### ISSUE TITLE
Ubuntu PPAs are missing focal packages.

### ISSUE THREAD

**Issue by blandin** [mumble-voip/mumble#4373]
20.04 has been out for three months, and it's an LTS version. This really shouldn't have happened, IMO.

**Comment by davidebeatrici** [comment]
See mumble-voip/mumble-ubuntu-ppa.

**Comment by davidebeatrici** [comment]
@blandin A package for 1.3.2 is now available. Does it work for you?

**Comment by blandin** [comment]
@davidebeatrici Yes, thank you.
