### ISSUE TITLE
While running mumble, cannot listen audio from other applications

### ISSUE THREAD

**Issue by francoisthire** [mumble-voip/mumble#4381]
**Describe the bug**

When I started `mumble`, the audio from other applications stops. In the case of `Youtube` for example, the video stops and cannot be run. It shows a loading icon.

The robot voice of mumble is also stopped and when I exit the application I hear all the messages at once as if they were bufferized.

**Steps to Reproduce**
For me, I just run `mumble` via the command line. The output is a bit weird (see below) and in particular I have errors from `jack` which I did not manage to get rid off. Is it related? `jack` is started even if I don't plug my headphones.

**Expected behavior**
I would like to be able to listen to a video while being on Mumble for example.

**Desktop (please complete the following information):**
- Debian sid with the window manager `i3`.

**Additional context**

`Mumble` was installed via `apt`.

When I start `mumble` I get the following messages:
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.14
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2019 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
Cannot use real-time scheduling (RR/10) (1: Operation not permitted)
AcquireSelfRealTime error
<W>2020-07-27 15:09:17.716 JackAudioSystem: client "mumble" opened successfully
<D>2020-07-27 15:09:18.748 libopus 1.3 from libopus.so.0
<W>2020-07-27 15:09:18.750 CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
<W>2020-07-27 15:09:18.753 Theme: "Mumble"
<W>2020-07-27 15:09:18.753 Style: "Lite"
<W>2020-07-27 15:09:18.753 --> qss: ":themes/Mumble/Lite.qss"
<W>2020-07-27 15:09:18.753 Locale is "en_US" (System: "en_US")
<W>2020-07-27 15:09:18.833 Database SQLite: "3.32.3"
<W>2020-07-27 15:09:18.840 Overlay: Listening on "/run/user/1000/MumbleOverlayPipe"
<W>2020-07-27 15:09:18.849 Updating application palette
<W>2020-07-27 15:09:18.879 GlobalShortcutX: Using XI2 2.3
<W>2020-07-27 15:09:19.032 AudioInput: Opus encoder set for VOIP
<W>2020-07-27 15:09:19.032 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-07-27 15:09:19.033 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
Cannot use real-time scheduling (RR/5) (1: Operation not permitted)
JackClient::AcquireSelfRealTime error
```

**Comment by Krzmbrzl** [comment]
What version of Mumble are you using!

**Comment by streaps** [comment]
> `Mumble` was installed via `apt`

This would be Mumble 1.3.0.

> The output is a bit weird (see below) and in particular I have errors from `jack` which I did not manage to get rid off. Is it related?

The "errors" from jackd are just warnings and not related to the problems you describe. jackd might prevent audio playback from other applications though. Try running `jackd -d alsa` on the command line – does it also prevent audio from other apps?

What audio output is configured in the Mumble Settings?

> `jack` is started even if I don't plug my headphones.

jack is an audio server and it also provides also virtual inputs and output. The 'jack' in `jack` is more about virtual software jacks than real hardware jacks.

**Comment by francoisthire** [comment]
>  Try running jackd -d alsa on the command line – does it also prevent audio from other apps?

Ah, yes, it does! So, I guess the issue comes from `jackd`. Thank you for you help!

**Comment by Krzmbrzl** [comment]
In that case, I'll close this issue as it seems that it is not Mumble's fault :point_up:
