### ISSUE TITLE
RNNoise leads to overdrive noise

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#4391]
When RNNoise is enabled an overdrive noise is audible that is not there with RNNoise disabled.

Will add audio samples later.

**Comment by Krzmbrzl** [comment]
Which version of Mumble are you using?
Which OS are you using?

Could you check out #4212 and see if the issue persists with that?

**Comment by promi** [comment]
Mumble version is 1.3.1, OS is Windows 10 x64.

We now tried the nightly build of 1.4 where it seems to be a lot better, but the error still occasionally happens.

I don't have a Windows build environment, so will probably wait for the pull request to be merged.

**Comment by Krzmbrzl** [comment]
There is an installer attached to the first post in #4212 that you could try :)

**Comment by promi** [comment]
Ok, we tried the attached installer. The problem still persists.

**Comment by Krzmbrzl** [comment]
Too bad ^^
Could you add audio samples, please?

Does it only happen when you speak or does it appear to be random?

**Comment by CoolOppo** [comment]
Me and a friend have the same issue. Both using Windows 10 64-bit with Mumble 1.3.2.

Only happens when you speak. The audio just sounds like it has been amplified a lot to the point of clipping. It's only when you're speaking over a certain threshold of loudness and then it just goes into overdrive. [Here is an audio clip](https://dl.dropboxusercontent.com/s/4zxa16hqf0mb543/rnnoise-clipping.mp3)

**Comment by bioblatt** [comment]
Same for me on Ubuntu, Mumble 1.30, one of my friends sounds exactly like in your audio example, if he enables RNNoise.

**Comment by Krzmbrzl** [comment]
Most recent findings seem to indicate that the issue is dependent on how load one is speaking. It also seems to depend on the personal voice but in general the issue seems to be reproducible by speaking louder.

This might be somehow related to input clipping of some sort :thinking:

**Comment by Popkornium18** [comment]
It is definitely related to input clipping and it's not just a problem with Mumble, but RNNoise in general. It just does not seem to handle clipping input very well.

To test this I recorded some audio with and without clipping. This has to be Mono 48kHz 16-Bit PCM as it's the only thing the test program bundled with RNNoise can handle.
![image](https://user-images.githubusercontent.com/46488511/108109269-ea652c80-7091-11eb-8e51-8ccd1c364afb.png)
Then let RNNoise do it's magic: `./examples/rnnoise_demo ~/rnnoise_input.pcm ~/rnnoise_output.pcm`.
Convert to wav using ffmpeg and lo and behold, it sounds like garbage: [rnnoise_test.zip](https://github.com/mumble-voip/mumble/files/5991069/rnnoise_test.zip)

**Comment by Krzmbrzl** [comment]
Okay then I assume this is something that should be reported upstream (I'll create a report).

On another note: The last person I talked to about this issue said, that this issue would show up regardless of the microphone settings made in the OS. This would suggest that Mumble does some sort of autogain that in some cases can lead to clipping which then in turns triggers this issue.
Can anybody support this claim?

**Comment by Popkornium18** [comment]
> Okay then I assume this is something that should be reported upstream (I'll create a report).

I think you have to use [this repo](https://gitlab.xiph.org/xiph/rnnoise), the GitHub mirror seems to be a "convenience copy".

> On another note: The last person I talked to about this issue said, that this issue would show up regardless of the microphone settings made in the OS. This would suggest that Mumble does some sort of autogain that in some cases can lead to clipping which then in turns triggers this issue.
> Can anybody support this claim?

I'll definitely try it.

**Comment by Krzmbrzl** [comment]
> I think you have to use this repo, the GitHub mirror seems to be a "convenience copy".

It seems like most issues are reported there though (118 on GitHub vs 2 on GitLab) :sweat_smile: 

> I'll definitely try it.

Thanks :+1:

**Comment by Krzmbrzl** [comment]
The reports I have received indicate that while there seems to be an issue with RNNoise, the problem got worse by upgrading Mumble a time ago. The commits that were traced down that could be related (not actually tested yet though) are
52d11e4
01db6e2
b798e56
5b6dfdb
248da41

I think the last three are probably most likely candidates. In order to be sure though, we'd have to do a `git bisect` to find the commit that has worsened the issue.
If someone has finds the time for this, the results of that would be much appreciated :eyes:

**Comment by remjey** [comment]
Hello, I think this is not an RNNoise problem as the floating-point signal that it outputs is actually ok, it just goes over the bounds of the 16-bit signed PCM that Mumble uses internally. I think it's Mumble's job to clamp the signal to the range of values it uses internally. It's a very simple a short fix.

Also RNNoise has very low activity so maybe it's best if it's fixed here instead.
