### ISSUE TITLE
Azure CI-Builds have "0.0.0" as the version string

### ISSUE THREAD

**Issue by Popkornium18** [mumble-voip/mumble#4406]
**Describe the bug**
The version string is not set to "1.4.0" but to "0.0.0". This triggers the "required minimum version warning" when connecting to a server that uses this feature.

**Steps to Reproduce**
1. Download AppImage from Azure
2. Connect to Server 
3. Look at your own Information

**Expected behavior**
The version String should look like this: (Self compiled)
![image](https://user-images.githubusercontent.com/46488511/89738187-0babe700-da77-11ea-95e2-5591ba4305b3.png)

**Screenshots**
But it looks like this:
![image](https://user-images.githubusercontent.com/46488511/89738134-81fc1980-da76-11ea-9916-eacfd8ec80ff.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: latest master

**Comment by hjf288** [comment]
Same on Windows x64

**Comment by ZeroAbility** [comment]
Based on the following url, it seems like trying to pass alphanumeric to the Version db entry for the msi might be failing:

https://docs.microsoft.com/en-us/windows/win32/msi/version

For some reason they call it a string but the documentation clearly doesn't allow chars like `-` and alpha. If we don't want upgrade issues with snapshots then we may want to revise how the version number is passed. Possibly like so:

```
1.4.0.20222
```

This includes the version with a julian date suffix.

**Comment by Krzmbrzl** [comment]
@ZeroAbility I think the issue with this kind of versioning is that once we release the stable version (`1.4.0` in this case) it'll be interpreted as being older than all previous snapshot releases.
Thus if we'd use this version style, we'd also have to use it for stable releases which then makes it a bit harder to tell whether someone is running a stable or a snapshot version :thinking: 

Unless we'd introduce a convention to use `x.x.x.99999` for stable releases. That'd be pretty ugly though imo :thinking: 

Besides: Given that the issue occurs on Linux as well, my guess is that the version is not properly retrieved with the CI builds.
