### ISSUE TITLE
MSI installer built with CMake doesn't allow direct upgrade

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#4407]
From https://github.com/mumble-voip/mumble/issues/4393#issuecomment-671063827:
> One slightly off topic note - it would be helpful if the Snapshot MSI builds are able to upgrade the installed version, it's a bit frustrating to have to remove the old version via Add/Remove programs in order to upgrade the snapshot.

I believe this happens because the version is the same (`1.4.0`). However, `1.3.0` development builds allowed direct upgrade.

![](https://user-images.githubusercontent.com/5897523/89850043-27ec7880-db8a-11ea-82ce-87d6c69019b3.png)

**Comment by Krzmbrzl** [comment]
Shouldn't the version be determined by the python script? In that case it should be in our snapshot format 🤔

**Comment by ZeroAbility** [comment]
#4406 may also be causing this.

**Comment by Krzmbrzl** [comment]
@hjf288 could you please connect to a server, right click your user and view your user's information? What is printed for your Mumble version?
Alternatively/Additionally you could just check what the title bar of the Mumble window states.

If #4406 is the root of the issue, then I'd expect you to see `0.0.0`. If however you are seeing `1.4.0`, then it's probably a different issue :thinking:

**Comment by hjf288** [comment]
> @hjf288 could you please connect to a server, right click your user and view your user's information? What is printed for your Mumble version?
> Alternatively/Additionally you could just check what the title bar of the Mumble window states.
> 
> If #4406 is the root of the issue, then I'd expect you to see `0.0.0`. If however you are seeing `1.4.0`, then it's probably a different issue 🤔

Same as #4406 - user info shows version as 0.0.0 and then the snapshot ver in brackets.

The window title is correct, the user info isn’t

**Comment by Krzmbrzl** [comment]
Ah interesting. But then I assume that the two issues are indeed related.
Thanks for the info :+1:
