### ISSUE TITLE
It's not possible to build Mumble with CMake and enable DBus-Support

### ISSUE THREAD

**Issue by Popkornium18** [mumble-voip/mumble#4409]
**Describe the bug**
The `dbus` Option in CMake is enabled by default, but it is not used to configure a DBus enabled build.

**Steps to Reproduce**
1. Make sure `dbus` is enabled in CMake configuration
2. Run CMake
3. `USE_DBUS` is not passed to the compiler

**Expected behavior**
Enabling `dbus` makes sure Mumble is built with DBus support

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: latest master

**Additional context**
I tried fixing it myself, but I only managed to pass `-DUSE_DBUS`, but it's not enough and my CMake-Fu is lacking.

**Comment by ZeroAbility** [comment]
https://github.com/mumble-voip/mumble/blob/e563b1f2a4683fd904f3c69bb1774549a1596359/src/CMakeLists.txt#L145-L150

Suggest the following insert on line 150:
```
elseif(UNIX AND dbus)
   target_compile_definitions(shared PUBLIC USE_DBUS)
```

**Comment by Popkornium18** [comment]
Also because of missing Dbus support the current CI snapshots do not use native notifications but weird "Qt-Tray-Icon-Notifications" which don't look very good and are barely readable.

With Dbus Support (Self compiled with qmake): 
![with_dbus](https://user-images.githubusercontent.com/46488511/89776327-f2a04600-db09-11ea-92c1-bcaf455c7c61.png)

Without Dbus Support (Snapshot downloaded from Azure):
![without_dbus](https://user-images.githubusercontent.com/46488511/89776373-13689b80-db0a-11ea-8896-2e15a13d07c2.png)

**Comment by Krzmbrzl** [comment]
The DBus stuff is actually added here:
https://github.com/mumble-voip/mumble/blob/e563b1f2a4683fd904f3c69bb1774549a1596359/src/murmur/CMakeLists.txt#L170-L181

This only handles DBus for the server though. It's missing on the client-side :point_up:

**Comment by Krzmbrzl** [comment]
@Popkornium18 could you check whether #4411 fixes the issue?
