### ISSUE TITLE
Request for up-to-date English language translation

### ISSUE THREAD

**Issue by Crisses** [mumble-voip/mumble#4415]
**Describe the bug**
Using the words "mute yourself" and "deafen yourself" are unnecessary. The push of a button are not creating mutism or deafening anyone.

**Steps to Reproduce**
Any time the English language is used in Mumble.

**Expected behavior**
Simply "Mic" and "Sound" would suffice. Or "Toggle Mic" and "Toggle Sound" - the current wording isn't necessary.

**Screenshots**
Screenshots unnecessary.

**Desktop (please complete the following information):**
 - Any English version.

**Additional context**
I'm using Mumble with the disability activist community. Some cultural/disability awareness and sensitivity would be nice, and help people feel more comfortable with the interface. Also this might discourage other translations from using these types of words.

**Comment by Krzmbrzl** [comment]
No - let's not start reinventing common expressions that everyone understands

**Comment by tthbaltazar** [comment]
I support this issue. As a non-native English speaker "deafen yourself" isn't self explanatory. It also unusual to use this term to describe disabling audio output, when most software uses different but more common terms (which might not be perfect either).

"Mute yourself" has nothing to do with me, just my computer. I don't mute myself, I disable audio input. If someone asked me what do to if they don't want others to heard them when someone comes in to their room, they would probably ask "How do I disable my microphone?"

**Comment by nukeop** [comment]
As a non-native English speaker "deafen" and "mute" are commonly used terms in the context of voice chat applications and are perfectly clear to anyone with IQ at or over room temperature.

**Comment by davidebeatrici** [comment]
In Celsius or Fahrenheit?

Anyway, if the terms sound weird to some non-native English speakers they can always use Mumble in their native language, which we can add if missing.

**Comment by ZeroAbility** [comment]
A decision was made on this PR and it was closed. The beauty of open source is that someone can download the source code and change it to their liking.
