### ISSUE TITLE
UDP keep getting packet loss to server on localhost

### ISSUE THREAD

**Issue by huizichin** [mumble-voip/mumble#4417]
UDP keep getting packet loss to server on localhost 
TCP worked well but it kept getting out of sync after about 2 hour and had to reconnect to resync it.
also there is this weird bug when i stop speaking there will be a buzz sound??????
i have no idea if it is also caused by packet loss but it sure is annoying
any idea?

Operating System:
Xubuntu 20.04.1 LTS

**Comment by Krzmbrzl** [comment]
How much packet loss are you encountering?
What version of Mumble (client and server) are you using?

Are you using noise suppression?

And the buzz sound could be one of the configurable sounds in the settings. Please check whether that might be the case

**Comment by huizichin** [comment]
Client version: 1.3.2-1
Server version: 1.3.2-1
the packet loss occur when i do not talk and i wait for like 10 second or something
and when i start talking it will be quite until like 4 second later it resync and stop packet losing
no i am not using noise suppression it is on continuous

  And the buzz sound could be one of the configurable sounds in the settings. Please check whether that might be the case
what should i check for?

**Comment by Krzmbrzl** [comment]
Are you using a headset (so that when you're not talking it's actually silent)?

I think this could be related to #4385 :thinking: 

> and when i start talking it will be quite until like 4 second later it resync and stop packet losing

Does your voice arrive 4 seconds delayed or are the first 4 seconds actually cut-off from the transmission?

**Comment by huizichin** [comment]
totally cutted off

**Comment by hhejkhalkfahjahsf** [comment]
I have the same problem

**Comment by TredwellGit** [comment]
This packet loss is present using master branch Mumble client and server on localhost.

**Comment by huizichin** [comment]
oh, if this is the case then yeah. i havent tried without local host

**Comment by TredwellGit** [comment]
I think the packet loss indicator is broken. 1.3.3 and master report ~60% packet loss on networks, not just localhost, with no packet loss according to iperf3, yet sound fine.

**Comment by huizichin** [comment]
But what about the cutting off of the audio

**Comment by TredwellGit** [comment]
I seem to be experiencing https://github.com/mumble-voip/mumble/issues/4385.

**Comment by Krzmbrzl** [comment]
This should have been fixed by #4720 (will be part of 1.3.4)
