### ISSUE TITLE
Programmatically setting Silence Below, Speech Above, and voice hold

### ISSUE THREAD

**Issue by storrgie** [mumble-voip/mumble#4419]
Actually not asking for this to be built in as a feature unless others ratify it as something they want to be doing. We're doing effectively a big "lanparty" with about 40-50 people in a... gymnasium if you will. We were wondering if it would be possible to set these parameters either via command line argument (unlikely), or by forcibly changing a registry value.

If its possible to do so, we'd change this across all machines via ansible... but we don't actually understand the registry values that are stored in relation to these configurations (they are binary and the range is confusing... like `?` --> `8` for `vadmax` (which I'm not sure what that translates to in the UI).

**Comment by Krzmbrzl** [comment]
The settings as they are right now (stored in the registry on Windows or in an ini file on Linux (and I think on MacOS as well)) are not really meant to be read or written by anything but Mumble itself.

The format is half-binary. In fact the format is how Qt's `QVariant` is being serialized for the respective data types. 

For this reason I don't think that this will be a good option to perform this kind of manipulation. What should be doable though would be to configure the settings in Mumble on one machine (maybe it's needed for this to be on the same OS as the target machines) and then basically copy&pasting the respective entries on the other machines (and thereby potentially overwriting whatever value they have on there). That way you don't have to parse the setting's format.

As a non-workaround solution to this I'll add this functionality to my ToDo-list in #3743. That'd then allow you to write a plugin that sets these settings for you. That plugin could then either use a configuration file of some sort on its own or simply use hard-coded values.

**Comment by storrgie** [comment]
@Krzmbrzl excellent, closing as it's captured in #3743. Love this project.
