### ISSUE TITLE
No Function found at ice to one to one whisper talk

### ISSUE THREAD

**Issue by mrkmenonuiu** [mumble-voip/mumble#4421]
there is a function to redirect to whisper group at ice but not no function to one to one whisper. this functionality exists at mumble client.
![image](https://user-images.githubusercontent.com/31846312/90117703-14533480-dd79-11ea-8b21-80b223c00b77.png)

**Comment by Krzmbrzl** [comment]
Could you elaborate on that? Are you referring to the ICE interface of the server? If so could you explicitly state the ICE function you are referring to?

And what do you mean by "redirect to whisper group" and "one to one whisper" in this context?

**Comment by mrkmenonuiu** [comment]
> there is a function to redirect to whisper group at ice but not no function to one to one whisper. this functionality exists at mumble client.
> ![image](https://user-images.githubusercontent.com/31846312/90117703-14533480-dd79-11ea-8b21-80b223c00b77.png)



> Could you elaborate on that? Are you referring to the ICE interface of the server? If so could you explicitly state the ICE function you are referring to?
> 
> And what do you mean by "redirect to whisper group" and "one to one whisper" in this context?

**Comment by mrkmenonuiu** [comment]
> Could you elaborate on that? Are you referring to the ICE interface of the server? If so could you explicitly state the ICE function you are referring to?
> 
> And what do you mean by "redirect to whisper group" and "one to one whisper" in this context?

I have added .ice library in my project.
![image](https://user-images.githubusercontent.com/31846312/90355627-c1c29280-e06e-11ea-90c7-2221592a08cf.png)
there is a function to group talk
![image](https://user-images.githubusercontent.com/31846312/90355700-fc2c2f80-e06e-11ea-975b-957858791230.png)
but i want to talk one to one using library.
@Krzmbrzl

**Comment by Krzmbrzl** [comment]
So you want to redirect whispers of a user to a single other user (instead of redirecting whispers/shouts to a group of users)?
Aka if I whisper to user A you want to be able to redirect my whisper to another user B?

Or do you want to that that not for a single user but for a group of users. Aka instead of whispering to users A, B and C you want to redirect that to D, E and F?

**Comment by mrkmenonuiu** [comment]
i want  one to one  whisper using ice. can i implement following features using ice library. i have found some of these like deafen, mute, join channel  at ice.
![image](https://user-images.githubusercontent.com/31846312/91436888-c8c97c00-e88a-11ea-945d-21a4e05f142b.png)

**Comment by Krzmbrzl** [comment]
Could you please answer my questions explicitly instead of repeating what you wrote before? Or at least be a bit more verbose in describing what exactly you want to do.
I don't get what your aim is when all you say "one to one whisper using ice". What are the applications of this concretely?
