### ISSUE TITLE
Amplification not good enough

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#4428]
For example: Certain user I know sounds quiet even with Mumble amplification all the way the max. If user uses non-Mumble AGC option to amplify their microphone, it makes user sound loud and clear (i.e. optimal) and auto-adapts well to their distance from the mic (which Mumble doesn't; sounds too loud when too close, very quiet when far). And raising "local volume" for that user in Mumble makes them sound loud but noisy and distorted.

**Comment by Krzmbrzl** [comment]
The code that seems to be responsible for the amplification is the following:
https://github.com/mumble-voip/mumble/blob/43975f3a8712d1fbf440b96cd9afbd78f496c8a3/src/mumble/AudioConfigDialog.cpp#L198

The maximum value of this slider is 19500 while the minimum one is 2000.

The corresponding label is populated like this
https://github.com/mumble-voip/mumble/blob/43975f3a8712d1fbf440b96cd9afbd78f496c8a3/src/mumble/AudioConfigDialog.cpp#L275-L279

https://github.com/mumble-voip/mumble/blob/43975f3a8712d1fbf440b96cd9afbd78f496c8a3/src/mumble/AudioInput.cpp#L715-L717

According to https://www.speex.org/docs/api/speex-api-reference/group__SpeexPreprocessState.html#g2199a5b52d1c9a1bd881510f4cee5dd8 `iArg` should be in dB.

----

When you turn that slider all the way to the right, `iMinLoudness = 500`. When you plug in the numbers, that'll result in `iArg = 40`. Thus the maximum gain we pass to speexdsp is 40dB.
If I understood the working principle behind AGC (automatic gain control) correctly, then this means that speex will lower the input levels (gain) of the mic as soon as they pass 40dB :thinking: 

I did not understand yet though how this affects amplification at all :shrug: 

Does lowering this setting actually make the user less loud? Aka: Would the problem perhaps be fixable by simply letting the user choose a higher max-gain?

**Comment by grravity** [comment]
wait wut no-response bot lole

**Comment by Krzmbrzl** [comment]
> Does lowering this setting actually make the user less loud? Aka: Would the problem perhaps be fixable by simply letting the user choose a higher max-gain?

This question is still unanswered. Therefore the label was not removed and the bot is correct

**Comment by grravity** [comment]
> This question is still unanswered. Therefore the label was not removed and the bot is correct

why would it close it though? It's just unanswered.

**Comment by Krzmbrzl** [comment]
Because that's how it is configured.
If there is information missing, we can't really work on the issue :shrug: 

But this is OT here.
