### ISSUE TITLE
SSL Version Mismatch 

### ISSUE THREAD

**Issue by frakier** [mumble-voip/mumble#4434]
Using...

`Mumble (1.3.2) on Windows 10`
and
`Mumble (1.3.2-1~ppa1~focal1) on Linux Mint 20 Ulyana 64-bit Mate 1.24.0 Kernal 5.4.0-42-generic x86_64`

attempt connecting to a server at my brothers house and a server at east1.mmo-mumble.com.

Windows 10: works on bother servers.
Linux: complains SSL Version Mismatch on both servers.

**Comment by Krzmbrzl** [comment]
What Server are you trying to connect to and what version of Mumble are they running?

And what is the exact error message you get on Linux?

**Comment by frakier** [comment]
no idea on east1.mmo-mumble.com, you would have to ask mumble. When I tried putting east1.mmo-mumble.com in firefox to see what whould happen I got...
`Secure Connection Failed

An error occurred during a connection to mmo-mumble.com. Peer using unsupported version of security protocol.

Error code: SSL_ERROR_UNSUPPORTED_VERSION

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…

This website might not support the TLS 1.2 protocol, which is the minimum version supported by Firefox. Enabling TLS 1.0 and TLS 1.1 might allow this connection to succeed.

TLS 1.0 and TLS 1.1 will be permanently disabled in a future release.`

for my brothers server [this would be easier if you could copy the mumble server information that you get when you use 
the menu server->information]
`Protocol 1.2.19 
1.2.19-1ubuntu1 (x11)
Connection uses TSL 1.0`

Like I said on windows it works and linux does not work, guessing it is linux but figured to start here because I have no idea how to proceed through linux channels.

**Comment by frakier** [comment]
The full error that pops up is...
SSL Version mismatch
"This server is using an older encryption standard, and is no
longer supported by modern versions of Mumble."

I have no problems with trying to just update my brother server to a newer mumble if that is the problem but I do not see why this would work on windows and not linux if it was just the server. I can't update the east1.mmo-mumble.com it is not mine.

**Comment by davidebeatrici** [comment]
Updating the server is indeed the real solution.

If that's not feasible, you can lower the minimum protocol version in `/etc/ssl/openssl.cnf`:
```
[system_default_sect]
MinProtocol = TLSv1.0
```

**Comment by frakier** [comment]
> [system_default_sect]
> MinProtocol` = TLSv1.0

is not in the openssl.cnf, are you saying just to add it.

**Comment by davidebeatrici** [comment]
At the bottom of the file. On Debian Testing it's set to `TLSv1.2`.

**Comment by frakier** [comment]
Not there, Tried just adding it to see but no luck. Guess I will downgrade to a older version of LinuxMint where it was still working.

**Comment by TredwellGit** [comment]
> > [system_default_sect]
> > MinProtocol = TLSv1.0
> 
> is not in the openssl.cnf,

Good.

>are you saying just to add it.

No, he is saying to update the server. Mumble 1.2.3 is well over nine years behind what you should be using and TLS 1.0 is almost twenty-two years old. Both using TLS 1.0 and Mumble 1.2.3 are security vulnerabilities that should not be done. The version of Linux Mint you are using now is correct in rejecting TLS 1.0; your server is broken.

That being said, I have been meaning to send in a pull request to up the TLS requirements for Mumble.

**Comment by frakier** [comment]
I got it working for now by lowering the TLS using a how to I found. Until east1.mmo-mumble.com updates I have little choice. 
Guessing windows 10 is still allowing the v1.0 is the reason it still worked on win10.
I'm behind a firewall and the only people that use the two mumble servers I use are family. Never connected to any other server.
It will do for now, going to rebuild the computer again in another case soon anyhow.

**Comment by TredwellGit** [comment]
Just be advised that being behind a firewall will not protect you at all in this situation (only using modern TLS will) and that lowering the minimum TLS setting in OpenSSL will create security issues with other programs. Consider a different server host.

**Comment by Krzmbrzl** [comment]
@frakier I think you should try to contact the host of east1.mmo-mumble.com nonetheless and ask them to update. Their version of Mumble is indeed ancient and as TredwellGit already pointed out: Using versions that old does come with a (significant) security risk for both: The server-hosters and their clients.

**Comment by frakier** [comment]
@Krzmbrzl the one at east1.mmo-mumble.com is not mine. My Brothers server is the one we use 99.9 % of the time anyway, I'm going to update my brothers version next chance I get [probably this Friday evening]. For now it works if it is needed. east1.mmo-mumble.com is more a backup it is hardly ever used. Knowing all I have to do is un-commment some config to get on east1.mmo-mumble.com if I really need to is good enough.

**Comment by Krzmbrzl** [comment]
Yeah I got that - but if you have a way of contacting the admin/owner of that server, it'd probably be a good idea to do so. That's what I meant :)

**Comment by frakier** [comment]
Right now I'm looking into why my win10 machine allows the  1.0 because from what I understand that should not be happening either. May be time for a rebuild on that machine as well.

**Comment by TredwellGit** [comment]
>Right now I'm looking into why my win10 machine allows the 1.0 because from what I understand that should not be happening either.

My guess is that because Mumble uses an ancient version of OpenSSL on Windows in order to support Windows XP. I really dislike this because it means supporting end of life platforms at the expense of security. This is also why Mumble on Windows 10 does not use TLS 1.3. See https://github.com/mumble-voip/mumble/issues/4001.

Updating Mumble on Windows to OpenSSL 1.1.1.g should be reconsidered.

**Comment by davidebeatrici** [comment]
Mumble 1.4.x is built with the new environment, the first snapshot is coming this week.

**Comment by TredwellGit** [comment]
While that is appreciated, I am talking about OpenSSL on 1.3.x.

**Comment by Krzmbrzl** [comment]
> I am talking about OpenSSL on 1.3.x.

For that there will be no update of the dependencies as this would mean recompiling the entire environment (which is a real PITA). Given that 1.4.x is coming, this effort doesn't really make sense.

**Comment by WBTMagnum** [comment]
JFTR: I just posted a workaround to connect with Mumble 1.3.x on Focal to a legacy server here: https://github.com/mumble-voip/mumble/issues/4639#issuecomment-819307806

HTH
