### ISSUE TITLE
Windows Green Screen on recent Windows 10 Pro Insider Previews

### ISSUE THREAD

**Issue by Supernaut91** [mumble-voip/mumble#4440]
**Describe the bug**

Launching mumble and connecting to a Server causes my Windows 10 machine to green screen. This has only started happening on the latest dev channel Microsoft Insider Previews. I'm not sure if anyone else is aware, or has a machine with a dev channel windows build that can potentially replicate the issue.

**Steps to Reproduce**
Launch Mumble
Connect to Server - Green Screen - machine reboots.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10] Build 20201
 - Version: [e.g. Mumble 1.3.1 & 1.32]

**Comment by davidebeatrici** [comment]
Could you try to update the network driver(s)? I suggest using [Snappy Driver Installer](https://sdi-tool.org): https://sdi-tool.org/releases/SDI_R2000.zip

**Comment by Supernaut91** [comment]
I would much rather not use Snappy Driver Install.
For context, my motherboard is the x570 AORUS MASTER.

This issue only occurs with recent InsiderPreview builds. I do believe this is potentially network related as I am trying to replicate the issue on more than just mumble. 

I will download the latest driver from here

https://www.gigabyte.com/uk/Motherboard/X570-AORUS-MASTER-rev-10/support#support-dl-driver-lan

Realtek LAN driver
(Note) Win10 ver.1903 supported.	[1‎0.32.1206.2018]	4‎.83 MB	2‎019/06/13

Although this might be considerably out of date?

**Comment by Supernaut91** [comment]
David. The NIC driver fix worked. This is worrying as Gigabyte UK page is considerably out of date. I will try and contact them so that they use Install_Win10_10042_07222020 which is available from Realteks website. Hopefully other people wont get the issue as I was pulling my hair out!

https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

-   Win10 Auto Installation Program (SId:1152921505690824610) | 10.042 | 2020/07/27 | 10 MB
-- | -- | -- | --

**Comment by davidebeatrici** [comment]
The reason why I suggest using Snappy Driver Installer is due to it providing up-to-date drivers for almost all devices. And, of course, it's open-source.

It seems like the Realtek NIC drivers provided in recent Windows 10 Insider Preview builds are broken, see #4405.
