### ISSUE TITLE
Can't set Push to Talk button on macOS Mojave

### ISSUE THREAD

**Issue by gstauffer-toast** [mumble-voip/mumble#4460]
**Describe the bug**
I am trying to set the Push-to-Talk button on my laptop and it is not recognizing any keyboard inputs as buttons. This means that I am not able to set Push-to-Talk at all on my laptop and it is bothering my friends!

**Steps to Reproduce**
1. Go to "Configure"
2. Click on "Audio Wizard"
3. Proceed to "Voice Activity Detection" (I clicked Next 4 times...)
4. Select "Push to Talk" radio button
5. See the dialog box say "Press Shortcut"
6. Attempt to set the short-cut... no results!

**Expected behavior**
It should accept my keyboard inputs as valid PTT buttons.

**Screenshots**
Lengthy gif attempting showing reproduction steps...

In Audio Wizard:
![2020-09-05 13 20 23](https://user-images.githubusercontent.com/25013790/92310318-25a7ef00-ef7b-11ea-9637-82cd59eeb9d8.gif)

In System Preferences
![2020-09-05 13 22 29](https://user-images.githubusercontent.com/25013790/92310321-280a4900-ef7b-11ea-84fa-861767dfc800.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (Mojave)
 - Version: Mumble 1.3.2

**Additional context**
*I also attempted to manually set a shortcut under "Settings > Shortcuts" and am running into the same issue*. In Mojave there were a ton of permissioning changes, I'm wondering if there could be something that's blocking Mumble from reading the inputs? 

Unsure what could be causing this.. let me know if there's any way I can help!

**Comment by gstauffer-toast** [comment]
I had someone else try on their version of Mojave and they ran into the same issue on a fresh install of Mumble

**Comment by Krzmbrzl** [comment]
I'm pretty sure this is a duplicate of #4133. Could you please check the solution there and report back whether it worked for you, please?

**Comment by gstauffer-toast** [comment]
@Krzmbrzl Ahh I didn't find this in my searches, sorry! I'm not sure what change enabled it as I couldn't find input monitoring in Mojave, but it seems to be working now. Maybe just "Accessibility" controls it? Thanks 😄

**Comment by Krzmbrzl** [comment]
You're welcome :)

Could you perhaps post a screenshot of the respective setting here? I am thinking about adding this issue to our FAQ and a screenshot would probably be nice :point_up:

**Comment by gstauffer-toast** [comment]
@Krzmbrzl Sure thing, here's the pic:
![Screen Shot 2020-09-08 at 9 35 23 AM](https://user-images.githubusercontent.com/25013790/92483500-e4038800-f1b6-11ea-9f23-8c4f70e26850.png)

And as a side note, when I changed the permissions I had to relaunch mumble to get it to work. Thanks for the help again!

**Comment by davidebeatrici** [comment]
#4522
