### ISSUE TITLE
Parameter CMAKE_BUILD_TYPE should not be enforced

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#4470]
**Describe the bug**
Mumble (latest version from Git) cannot be compiled with the parameter `CMAKE_BUILD_TYPE='None'`.
Arch Linux recommends this option to compile CMake projects since `Release` overwrites the default compiler flags of the distribution and may cause undesired behavior.

**Steps to Reproduce**
1. Fetch latest Mumble code from Git
2. Compile it with `cmake -DCMAKE_BUILD_TYPE='None'`

**Expected behavior**
Mumble does not enforce using `'Release'` and is then compiled with the default compiler flags of the distribution.

**Desktop**
 - OS: Arch Linux
 - Version: [mumble-git](https://aur.archlinux.org/packages/mumble-git/)

**Additional context**
More details can be found in the [Arch Linux wiki](https://wiki.archlinux.org/index.php/CMake_package_guidelines#CMake_can_automatically_override_the_default_compiler_optimization_flag).
The check in Mumble can be found here: https://github.com/mumble-voip/mumble/blob/master/CMakeLists.txt#L79
My suggestion is to simply remove these two lines.

**Comment by radioactiveman** [comment]
Probably related is the use of `dpkg-buildflags` for Debian builds which was a build option for QMake (and is still mentioned in the INSTALL file).

Although [CMakeLists.txt#L47](https://github.com/mumble-voip/mumble/blob/master/CMakeLists.txt#L47) contains a CMake option, I found no usage of it. So it has probably no function at all. Which means Debian package maintainers should also use CMAKE_BUILD_TYPE='None' to compile with the Debian build flags.

**Comment by davidebeatrici** [comment]
`dpkg-buildflags` was added when importing the qmake options, I forgot to remove it, sorry about that.

I agree that we shouldn't enforce the build type.
Also, we should probably remove the `symbols` option and use `RelWithDebInfo` instead.

**Comment by Krzmbrzl** [comment]
If we are to remove the restrictions for the build type,we have to name sure that there are no parts in the buildsystem that rely on the build type being a binary choice (e.g. testing for Release and if it's not that assume that it's Debug).

**Comment by davidebeatrici** [comment]
There are indeed some parts that rely on the build type name, such as:
https://github.com/mumble-voip/mumble/blob/0ba1eac51b5f4443e6fbb1bc3e157403903e9a01/cmake/compiler.cmake#L15-L20
https://github.com/mumble-voip/mumble/blob/0ba1eac51b5f4443e6fbb1bc3e157403903e9a01/src/mumble_exe/CMakeLists.txt#L30-L33

**Comment by ZeroAbility** [comment]
> There are indeed some parts that rely on the build type name, such as:
> https://github.com/mumble-voip/mumble/blob/0ba1eac51b5f4443e6fbb1bc3e157403903e9a01/cmake/compiler.cmake#L15-L20
> 
> 
> https://github.com/mumble-voip/mumble/blob/0ba1eac51b5f4443e6fbb1bc3e157403903e9a01/src/mumble_exe/CMakeLists.txt#L30-L33

I believe that pertains to MSVC which requires a config type, Ninja also uses it, and the Makefile generator. It's good practice to specify which config during the CMake configure process or using an editor after the CMakeCache is created. Both should be enclosed in a `if(MSVC)` block. Unless there is specific logic for non-Windows systems, these shouldn't be affected if there isn't a hard definition.

https://cmake.org/cmake/help/v3.15/variable/CMAKE_BUILD_TYPE.html

**Comment by Krzmbrzl** [comment]
There are also other places in which the build type is checked but from what I can tell it mostly checks if the config is `Debug` and if it is, it adds some debugging flags/utilities.

Having thought about this a bit more though, I much prefer the build type being a binary choice though as this facilitates working with the cmake files down the line.

The issue of default compiler options being overwritten could be better addressed (imo) by providing a new cmake option like `build-type-specific-compiler-flags=OFF` that could then do
```
if(NOT build-type-specific-compiler-flags)
    # clear all default compiler flags
    set(CMAKE_C_FLAGS_DEBUG "")
    set(CMAKE_C_FLAGS_MINSIZEREL "")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "")
    set(CMAKE_C_FLAGS_RELEASE "")
    set(CMAKE_CXX_FLAGS_DEBUG "")
    set(CMAKE_CXX_FLAGS_MINSIZEREL "")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "")
    set(CMAKE_CXX_FLAGS_RELEASE "")
endif()
```

This should the  prevent cmake from setting build-type specific compiler flags that would the override the default flags of any distro.
We could then also fake a "None" build type by catching this choice early on, setting `build-type-specific-compiler-flags=OFF` and then setting the build type to `Release` instead. I think that would probably do what you are looking for @radioactiveman, wouldn't it?

I think this allows us to fix the issue at hand while still keeping the simplicity of only having to differentiate between `Debug` and `Release` build-types in our build files.

**Comment by radioactiveman** [comment]
@Krzmbrzl: Sorry for the late response. I have tried your suggestion meanwhile by copying all the `set` commands into the main `CMakeLists.txt`. This works technically but in my opinion you should not reinvent the wheel here.

Is it not possible to introduce a new boolean variable (just a variable, not a CMake option) which can be read in all CMakeLists.txt files? This can then be used instead of checks like `if($<CONFIG:Release>)`. It would also allow using other build types like `RelWithDebInfo` which @davidebeatrici suggested [above](https://github.com/mumble-voip/mumble/issues/4470#issuecomment-689321864).

**Comment by ZeroAbility** [comment]
This SO post might also help clarify:

https://stackoverflow.com/questions/24460486/cmake-build-type-is-not-being-used-in-cmakelists-txt/24470998#24470998

I have also updated the vcpkg readme to reflect these options.

**Comment by Krzmbrzl** [comment]
> Is it not possible to introduce a new boolean variable (just a variable, not a CMake option) which can be read in all CMakeLists.txt files?

Absolutely but how should that one be initialized then (since we can't init on the build-type) :thinking:

**Comment by radioactiveman** [comment]
> > Is it not possible to introduce a new boolean variable (just a variable, not a CMake option) which can be read in all CMakeLists.txt files?
> 
> Absolutely but how should that one be initialized then (since we can't init on the build-type) thinking

Why not? :thinking: From the CMake build types only `Debug` should have a different value. The other types can be considered as release build. To be clear, I am not talking about setting `CMAKE_BUILD_TYPE` to `Release` but a binary choice for use in CMake files.

- Debug
- Release
- RelWithDebInfo
- MinSizeRel
- None (the build type this issue is all about)
- Empty (default - overwritten by Mumble with `Release`)

**Comment by ZeroAbility** [comment]
According to this:

https://cmake.org/cmake/help/v3.15/variable/CMAKE_BUILD_TYPE.html

An empty value should be supported. I suspect that passing specific flags would be done using this built-in:

https://cmake.org/cmake/help/v3.15/variable/CMAKE_LANG_FLAGS.html

Does it work if you don't specify `-DCMAKE_BUILD_TYPE`, and supply the needed flags using `-DCMAKE_CXX_FLAGS=<flags>` and `-DCMAKE_C_FLAGS=<flags>` during the generate step?

**Comment by ZeroAbility** [comment]
This section will probably need a rewrite first:

https://github.com/mumble-voip/mumble/blob/6e33d349b07d26cd3ebb97067df7daa41a9b508f/CMakeLists.txt#L56-L85
