### ISSUE TITLE
Handling man files in make install target

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#4472]
Since the migration from QMake to CMake there is now a proper "make install" target. :+1:

A nice addition for it would be the installation of the [man files](https://github.com/mumble-voip/mumble/tree/master/man) into the directory `/usr/share/man/man1/`.
If the compilation of the client / server is disabled, the corresponding man file should be ignored.

**Comment by Krzmbrzl** [comment]
Added in #4473
