### ISSUE TITLE
I am prompted when compiling with visual studio 2019

### ISSUE THREAD

**Issue by donggua2096** [mumble-voip/mumble#4474]
Severity code description project file line disable display status
Error at cmake / PKG- utils.cmake:87  (message):
Qt5 component not found: core C: \- utils.cmake	 Eighty-seven

**Comment by ZeroAbility** [comment]
If you are opening the CMake project in the Open Folder feature in Visual Studio, you will need to add Configure arguments as described here:

https://github.com/mumble-voip/mumble-releng-vcpkg

Important to note is this argument and it must be set this way for the components to be detected:

`VCPKG_TARGET_TRIPLET=x64-windows-static-md`

You may also need to specify the toolchain file like so:

`CMAKE_TOOLCHAIN_FILE=<vcpkg_root_directory>/scripts/buildsystems/vcpkg.cmake`

Builds with Ice also need the following:

`Ice_HOME=<vcpkg_root_directory>/installed/x64-windows-static-md`

We build static for Windows:

`static=ON`

**Comment by donggua2096** [comment]
Can you take a look at it for me
![image](https://user-images.githubusercontent.com/63895372/92624063-a8bda200-f2f9-11ea-970e-10c55e3da70b.png)

**Comment by ZeroAbility** [comment]
On the third line add:
`-DCMAKE_TOOLCHAIN_FILE=G:/vcpkg/scripts/buildsystems/vcpkg.cmake`
