### ISSUE TITLE
qt5-base build error when preparing dependencies with Get-MumbleDeps.ps1

### ISSUE THREAD

**Issue by donggua2096** [mumble-voip/mumble#4475]
> Installing Mumble dependency qt5-base ...

---------------------------------------

```
Computing installation plan...
The following packages will be built and installed:
    qt5-base[core]:x64-windows-static-md
Detecting compiler hash for triplet x64-windows-static-md...
Starting package 1/1: qt5-base:x64-windows-static-md
Building package qt5-base[core]:x64-windows-static-md...
Could not locate cached archive: C:\Users\王睿\AppData\Local\vcpkg/archives\eb\ebde57d2d16de4e82084fbe0a2ccfff9102ca124.zip
-- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: G:\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Figuring out qt target mkspec. Target arch x64
-- Target mkspec set to: win32-msvc
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Downloading http://download.qt.io/official_releases/qt/5.15/5.15.0/submodules/qtbase-everywhere-src-5.15.0.tar.xz...
-- Extracting source G:/vcpkg/downloads/qtbase-everywhere-src-5.15.0.tar.xz
-- Applying patch patches/winmain_pro.patch
-- Applying patch patches/windows_prf.patch
-- Applying patch patches/qt_app.patch
-- Applying patch patches/gui_configure.patch
-- Applying patch patches/icu.patch
-- Applying patch patches/xlib.patch
-- Applying patch patches/egl.patch
-- Applying patch patches/8c44d70.diff
-- Applying patch patches/Qt5BasicConfig.patch
-- Applying patch patches/Qt5PluginTarget.patch
-- Applying patch patches/create_cmake.patch
-- Applying patch patches/Qt5GuiConfigExtras.patch
-- Using source at G:/vcpkg/buildtrees/qt5-base/src/5.15.0-f256990b37.clean
-- Configuring x64-windows-static-md-dbg
-- Configuring x64-windows-static-md-dbg done
-- Configuring x64-windows-static-md-rel
-- Configuring x64-windows-static-md-rel done
-- Building x64-windows-static-md-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: G:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe /J 5
    Working Directory: G:/vcpkg/buildtrees/qt5-base/x64-windows-static-md-dbg
    See logs for more information:
      G:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-out.log
      G:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-err.log

Call Stack (most recent call first):
  ports/qt5-base/cmake/install_qt.cmake:66 (vcpkg_execute_build_process)
  ports/qt5-base/portfile.cmake:306 (install_qt)
  scripts/ports.cmake:79 (include)


Error: Building package qt5-base:x64-windows-static-md failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-base:x64-windows-static-md
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
vcpkg_install : Failed at installing package qt5-base (x64-windows-static-md)
所在位置 G:\mumble-releng-vcpkg-master\Get-MumbleDeps.ps1:82 字符: 4
+             vcpkg_install -package $dep -targetTriplet $triplet -clea ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,vcpkg_install
```
![image](https://user-images.githubusercontent.com/63895372/92625503-52e9f980-f2fb-11ea-8813-4cc8352b632d.png)

**Comment by ZeroAbility** [comment]
> See logs for more information:
G:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-out.log
G:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-err.log

Please review the contents for errors.

**Comment by donggua2096** [comment]
cd src\ && ( if not exist Makefile G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\src\src.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile
	cd tools\bootstrap\ && ( if not exist Makefile G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\src\tools\bootstrap\bootstrap.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile
	cd qmake\ && ( if not exist Makefile.qmake-aux G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile.qmake-aux G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\qmake-aux.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.qmake-aux
	G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.qmake-aux.Debug
	G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe binary
	cl -Yuqmake_pch.h -FIqmake_pch.h -Fpqmake_pch.pch -c -Fo./ -Fdqmake.pdb  -W2 -nologo -O2  /MP /wd4577   -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\library -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators\unix -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators\win32 -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators\mac  -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/src/3rdparty/tinycbor/src  -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include\QtCore -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include\QtCore\5.15.0 -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include\QtCore\5.15.0\QtCore  -I..\src\corelib\global  -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\mkspecs\win32-msvc   -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS  -DQT_VERSION_STR=\"5.15.0\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=15 -DQT_VERSION_PATCH=0  -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_FOREACH -DUNICODE -D_ENABLE_EXTENDED_ALIGNED_STORAGE  -Foqlibraryinfo_final.obj G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\src\corelib\global\qlibraryinfo.cpp
qlibraryinfo.cpp
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\Users\?T¿¬y¿¬??¿ê\AppData\Local\Temp\_CL_bff8b5edex': Invalid argument
	cd doc\ && ( if not exist Makefile G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\doc\doc.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile
	G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.Debug
	G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.Release

**Comment by ZeroAbility** [comment]
> Error: cannot open C:\Users?Tíyí??▓\AppData\Local\Temp\qlatincodec.obj.7124.187.jom for write

> c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\Users?T¿¬y¿¬??¿ê\AppData\Local\Temp_CL_bff8b5edex': Invalid argument

I would guess this also has to do with region and language settings of your system. You can try something like this to set it to Latin characters for your powershell session but it may still throw an error:

https://stackoverflow.com/a/7052955

I briefly searched through the issues for https://github.com/microsoft/vcpkg and could not find anything specific pertaining to translations so this might be something you should bring to their attention since several others may be affected by this.

**Comment by ZeroAbility** [comment]
Please try adding English as a language in Windows 10 if you have not already:

https://support.microsoft.com/zh-cn/help/14236/windows-language-packs

Let us know if that resolves the error.

**Comment by donggua2096** [comment]
jom and its issues....... maybe use a junction (via mklink with /J option) or subst the path with non-ASCII characters away.

**Comment by donggua2096** [comment]
How to set it?

**Comment by donggua2096** [comment]
#https://github.com/microsoft/vcpkg/issues/13418

**Comment by donggua2096** [comment]
#https://github.com/microsoft/vcpkg/issues/13418
How to set it?

**Comment by davidebeatrici** [comment]
@Neumann-A suggested to create a junction (`mklink /J`), so that you can build the environment in a folder that only contains ASCII characters.

However, it's not a solution in your case: the path to the vcpkg directory is fine, it's the temporary directory that is causing the issue because your Windows username contains non-ASCII characters.

As a workaround I would create a folder in `C:\` and edit the `TMP` and `TEMP` environment variables so that they point to it.

If there are multiple users, make sure that only yours can access the directory (for security).

**Comment by BeLucky-219** [comment]
PS D:\mumble-releng-vcpkg> .\Get-MumbleDeps.ps1
Setting triplets for AMD64
Checking for D:\mumble-releng-vcpkg\vcpkg...
Computing installation plan...
The following packages are already installed:
    mdnsresponder:x64-windows-static-md@1557.140.5.0.1#1
mdnsresponder:x64-windows-static-md is already installed
Total install time: 1.01 ms
Computing installation plan...
The following packages are already installed:
    icu:x64-windows-static-md@74.2#5
icu:x64-windows-static-md is already installed
Total install time: 1.05 ms
icu provides pkg-config modules:

  # International Components for Unicode: Internationalization library
  icu-i18n

  # International Components for Unicode: Stream and I/O Library
  icu-io

  # International Components for Unicode: Common and Data libraries
  icu-uc

Installing cross compile packages...
Computing installation plan...
The following packages are already installed:
    boost-optional:x86-windows-static-md@1.87.0
boost-optional:x86-windows-static-md is already installed
Total install time: 6.53 ms
The package boost-optional is compatible with built-in CMake targets of FindBoost.cmake:

    find_package(Boost REQUIRED COMPONENTS optional)
    target_link_libraries(main PRIVATE Boost::optional)

or the generated cmake configs via:

    find_package(boost_optional REQUIRED CONFIG)
    target_link_libraries(main PRIVATE Boost::optional)

Beginning package install...
---------------------------------------
> Installing Mumble dependency qt5-base ...
---------------------------------------
Computing installation plan...
The following packages will be built and installed:
  * double-conversion:x64-windows@3.3.0
  * double-conversion:x64-windows-static-md@3.3.0
  * egl-registry:x64-windows@2024-01-25
  * egl-registry:x64-windows-static-md@2024-01-25
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows@2.13.3
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows-static-md@2.13.3
  * harfbuzz[core,freetype]:x64-windows@10.2.0#2
  * harfbuzz[core,freetype]:x64-windows-static-md@10.2.0#2
  * libjpeg-turbo:x64-windows@3.1.0#1
  * libjpeg-turbo:x64-windows-static-md@3.1.0#1
  * libpng:x64-windows@1.6.46
  * libpng:x64-windows-static-md@1.6.46
  * openssl:x64-windows@3.4.1
  * openssl:x64-windows-static-md@3.4.1
  * pcre2[core,jit,platform-default-features]:x64-windows@10.43
  * pcre2[core,jit,platform-default-features]:x64-windows-static-md@10.43
  * qt5-base:x64-windows@5.15.16
    qt5-base:x64-windows-static-md@5.15.16
  * sqlite3[core,json1]:x64-windows@3.49.1
  * sqlite3[core,json1]:x64-windows-static-md@3.49.1
  * zlib:x64-windows@1.3.1
  * zlib:x64-windows-static-md@1.3.1
  * zstd:x64-windows@1.5.7
  * zstd:x64-windows-static-md@1.5.7
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:7890".
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.43.34808/bin/Hostx64/x64/cl.exe
Detecting compiler hash for triplet x64-windows-static-md...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.43.34808/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\14413\AppData\Local\vcpkg\archives in 3.88 ms. Use --debug to see more details.
Installing 1/24 double-conversion:x64-windows@3.3.0...
Building double-conversion:x64-windows@3.3.0...
-- Using cached google-double-conversion-v3.3.0.tar.gz
-- Extracting source D:/mumble-releng-vcpkg/vcpkg/downloads/google-double-conversion-v3.3.0.tar.gz
-- Using source at D:/mumble-releng-vcpkg/vcpkg/buildtrees/double-conversion/src/v3.3.0-b26640509d.clean
-- Found external ninja('1.12.1').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/mumble-releng-vcpkg/vcpkg/buildtrees/double-conversion/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\mumble-releng-vcpkg\vcpkg\buildtrees\double-conversion\config-x64-windows-dbg-CMakeCache.txt.log
      D:\mumble-releng-vcpkg\vcpkg\buildtrees\double-conversion\config-x64-windows-rel-CMakeCache.txt.log
      D:\mumble-releng-vcpkg\vcpkg\buildtrees\double-conversion\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  ports/double-conversion/portfile.cmake:9 (vcpkg_cmake_configure)
  scripts/ports.cmake:196 (include)


error: building double-conversion:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle double-conversion:x64-windows: 956 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+double-conversion
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[double-conversion]+Build+error+on+x64-windows&body=Copy%20issue%20body%20from%20D%3A%2Fmumble-releng-vcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

vcpkg_install : Failed at installing package qt5-base (x64-windows-static-md)
所在位置 D:\mumble-releng-vcpkg\Get-MumbleDeps.ps1:83 字符: 4
+             vcpkg_install -package $dep -targetTriplet $triplet -clea ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,vcpkg_install





l   get the simliar problem,when l preparing dependencies with "Get-Mumbledeps.ps1"

**Comment by BeLucky-219** [comment]
> That script is outdated. Instead, see the build script in our vcpkg fork at github.com/mumble-voip/vcpkg

l use “build_mumble_dependencies”，but some libs could not build

### 
Additional packages (*) need to be exported to complete this operation.
There are packages that have not been built. To build them run:
vcpkg install libflac:x64-windows-static-md libmysql:x64-windows-static-md libogg:x64-windows-static-md libsndfile:x64-windows-static-md libvorbis:x64-windows-static-md qtbase:x64-windows-static-md qtsvg:x64-windows-static-md qttools:x64-windows-static-md qttranslations:x64-windows-static-md soci:x64-windows-static-md speexdsp:x64-windows-static-md

### And the problem is ：
error: building speexdsp:x64-windows-static-md failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle speexdsp:x64-windows-static-md: 16 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+speexdsp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[speexdsp]+Build+error+on+x64-windows-static-md&body=Copy%20issue%20body%20from%20D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

And then ，l found this sentence： Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v

It‘s need ninja？

**Comment by Krzmbrzl** [comment]
It does need Ninja but it installs it automatically. You need to post the actual error message for me to be able to get an idea of what the issue might be.

**Comment by BeLucky-219** [comment]
> It does need Ninja but it installs it automatically. You need to post the actual error message for me to be able to get an idea of what the issue might be.

<img width="744" alt="Image" src="https://github.com/user-attachments/assets/34317f58-3d64-43ba-98c7-151ab154079d" />

And the config-x64-windows-static-md-out-log is：

<img width="595" alt="Image" src="https://github.com/user-attachments/assets/037e1da9-6b67-4ef5-8dfb-de090bb71fd9" />

**Comment by Krzmbrzl** [comment]
Okay seems like the issue is a too recent CMake version. To work around this, you can simply remove speexdsp from the list of dependencies (the txt file) as it is currently not strictly needed.
