### ISSUE TITLE
1.4.x Windows installer doesn't upgrade properly

### ISSUE THREAD

**Issue by ZeroAbility** [mumble-voip/mumble#4488]
**Describe the bug**
When the 1.4.x full msi is created using `cpack` the resulting file does not properly remove the previous application from Apps when installed over the top.

**Steps to Reproduce**
1. Create a MSI file using `cpack` with options `client` and `server` enabled in the CMake project.
2. Install the MSI on a system with 1.3.x or later installed.

**Expected behavior**
Uninstall of previous installed version (including files, shortcuts, and registry entries) should occur using the static defined `<Upgrade id="<upgrade_guid />"` and incrementing the version number.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.4.x

**Additional context**
WiX Toolset documentation and various other how-to's and sources all indicate that the only required changes are to the `<Version>` field and that the upgrade GUID needs to be identical for the previous version to be removed during the upgrade process. Suggested workaround would be to manually uninstall 1.3.x and earlier prior to installing 1.4.x

https://github.com/mumble-voip/mumble/tree/master/installer
https://github.com/mumble-voip/mumble/blob/master/cmake/packaging.cmake

**Comment by davidebeatrici** [comment]
@barnson @robmen @rseanhall

@ZeroAbility and I tried searching for similar issues on http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org, but the search engine appears to be broken (query results not visible):
![](https://user-images.githubusercontent.com/5897523/93279170-dbb6d880-f7c6-11ea-9f20-e946c320c889.png)

**Comment by robmen** [comment]
Correct. A support ticket is open on the distribution list search issue. It has not been resolved yet.

**Comment by davidebeatrici** [comment]
I see. Is there an ETA for the resolution?

Also, do you perhaps have any hints about the issue we're encountering?
