### ISSUE TITLE
murmurd does not recognize/use mumble-server.ini

### ISSUE THREAD

**Issue by Hams3c** [mumble-voip/mumble#4496]
**Describe the bug**
On ubuntu 18LTS, mumble-server.ini does not load/get picked up when the daemon is run

**Steps to Reproduce**
1. Make updates to mumble-server
2. Forcefully restart mumble because the daemon service does not do it for me.
3. Expect to see changes from my updated config...which does not occur.

**Expected behavior**
When I update a config, I expect my config changes to be loaded by mumble-server

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Ubuntu 18.0 LTS

**Additional context**
This occurs when using `apt` to install, not when run after extraction from the tar.gz.

**Comment by Krzmbrzl** [comment]
Where is the ini file located relative to the used murmur executable and what are the command line parameters murmur is started with?

If the file is in the same directory as the executable it should be named `murmur.ini` in order to get loaded automatically and if it is not, you have to use the `-ini` option to point murmur to the respective file :point_up:

**Comment by Hams3c** [comment]
> If the file is in the same directory as the executable it should be named murmur.ini in order to get loaded automatically and if it is not, you have to use the -ini option to point murmur to the respective file ☝️

My solution was to download the server `tar.gz` directly from the mumble website, rather than install from `apt`.  You are correct in that it recognizies `murmur.ini` when passed the `-ini` file.  

When downloaded from `apt` on Ubuntu, `mumble-server` defaults to using `-ini mumble-server.ini`.  This may have resulted in my problem.

**Comment by Krzmbrzl** [comment]
Yeah if it uses that command line parameter then it searches for a file with that name in the executable's directory :)
