### ISSUE TITLE
Bug Voice Car

### ISSUE THREAD

**Issue by daviten74** [mumble-voip/mumble#4498]
**Describe the bug**
I don't know why sometimes it happens to us that we listen to each other at a distance or we hear voices in our heads from people who are far away, but these people previously thought we had shared a vehicle, you don't know if it's the bug.

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. Mumble 1.3 or Murmur 1.3]

**Additional context**

**Comment by Krzmbrzl** [comment]
To me this doesn't seem like a serious report at all. It doesn't contain any real information and talks about voices in your head?!
Plus: We don't have any vehicles in our software.

If this is indeed an actual report, please take the time and provide some useful information and fill out the other details in the bug-report form.
Once you have done that, ping me and I will consider re-opening this issue
