### ISSUE TITLE
startListening give unknown user exception

### ISSUE THREAD

**Issue by mrkmenonuiu** [mumble-voip/mumble#4504]
i have installed murmur server from github latest naughty build to my windows 10. At mumble 1.4 have some facilities of startListening, stopListening,  isListening etc. features. Which was not included at mumble version 1.3.2. 

two months earlier i was installed naughty build of mumble 1.4 msi from this link 
https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=2066&view=artifacts&type=publishedArtifacts

(startListening, stopListening,  isListening etc) functionalities was working perfectly at that time.
![image](https://user-images.githubusercontent.com/31846312/94141963-58187e00-fe8f-11ea-9d70-6f78f51a1215.png)

but  latest naughty build of mumble 1.4 give unknown user exception when try to start listening . i have checked user at online but start listening not working.
![image](https://user-images.githubusercontent.com/31846312/94143097-29030c00-fe91-11ea-880b-f0f8194c33af.png)
![image](https://user-images.githubusercontent.com/31846312/94143124-34563780-fe91-11ea-90b7-6bd64d67afd6.png)
![image](https://user-images.githubusercontent.com/31846312/94143340-839c6800-fe91-11ea-98db-c5a464c0623a.png)

**Comment by Krzmbrzl** [comment]
The ICE API for the ChannelListeners has not been changed ever since it has been implemented.

If you are now getting an `UnknownUserException`, then I am pretty sure this is indeed because it can't find the requested user.
You said that you checked whether the user existed using a different ICE call. Could you show the respective code (preferrably including how you check whether the user exists and how you the call `startListening`)?

**Comment by mrkmenonuiu** [comment]
@Krzmbrzl thanks. yes working now after restart my pc.

**Comment by mrkmenonuiu** [comment]
@Krzmbrzl how can I install nightly version at my linux?
![image](https://user-images.githubusercontent.com/31846312/94355966-def57280-00aa-11eb-933b-039883a8e6f6.png)
I can install at my windows from windows nightly version installer file.

**Comment by Krzmbrzl** [comment]
On Linux you'll have to compile Mumble from source since our AppImage is currently broken.

**Comment by Krzmbrzl** [comment]
I think this issue can be closed as the original issue seems to be resolved.
