### ISSUE TITLE
Port to Serenity OS

### ISSUE THREAD

**Issue by chaziei** [mumble-voip/mumble#4512]
**Context**
In which context would you expect your suggested feature to be useful? 
Itll be useful for people that start to use SerenityOS and use Mumble

**Describe the feature you have in mind**
Just port Mumble to https://www.github.com/SerenityOS/serenity

**Describe alternatives you've considered**
none

**Additional context**

**Comment by Krzmbrzl** [comment]
I could not find any indication that Qt supports SerenityOS. Do you have information proving the opposite?

If Qt doesn't support this platform, then there is no way that Mumble can be ported to it.
But even if it does support it, we don't have the capacity to support yet another OS that is different from Windows, macOS, Linux and FreeBSD (and if it isn't then there should be no need for a part in the first place).

**Comment by chaziei** [comment]
Oh okay, you can close this now

**Comment by ZeroAbility** [comment]
For reference, they are trying to port Qt to SerenityOS:

https://github.com/SerenityOS/serenity/issues/152

There are several other dependencies we use that may or may not be present. If you have not submitted an Issue to the SerenityOS project, that might be a good place to start first. As @Krzmbrzl stated, we don't have the resources to devote to porting to a new OS.
