### ISSUE TITLE
Please repair Dockerfile

### ISSUE THREAD

**Issue by manalejandro** [mumble-voip/mumble#4514]
**Describe the bug**
Please repair the Dockerfile :whale2: with the new install system :floppy_disk: 

**Steps to Reproduce**
1. clone this repo
2. docker build .
4. See next error

**Expected behavior**
Cannot find file: main.pro.
ERROR: Service 'mumble' failed to build: The command '/bin/sh -c qmake -recursive main.pro CONFIG+="no-client grpc"' returned a non-zero code: 2

**Desktop (please complete the following information):**
 - OS: Docker amd64
 - Version: Latest mumble version

**Additional context**
Thanks

**Comment by Avatat** [comment]
I confirm the issue.
It's related to this change: https://github.com/mumble-voip/mumble/pull/4448
