### ISSUE TITLE
Question about mumble protocol : Target is only 5 bits - does it mean Mumble only supports 30 unique targets ? 

### ISSUE THREAD

**Issue by spexocta** [mumble-voip/mumble#4518]
According to Mumble protocol : 

```

Target
The target portion defines the recipient for the audio data. The two constant targets are Normal talking (0) and Server Loopback (31). The range 1-30 is reserved for whisper targets. These targets are specified separately in the control channel using the VoiceTarget packets. The targets are listed in Audio targets table.
```

Does this mean i can only address 30 unique targets ? ( 30 groups or 30 groups/whisper users ) ?

**Comment by Krzmbrzl** [comment]
Yes this is indeed the case.

These targets may be reused though. So you can assign target 1 to a certain list of users, go on in your code and then later on re-assign target 1 to something else.

Therefore the restriction really is that you can't have more than 30 separate targets simultaneously, which I think should be more than sufficient :thinking: 

In fact Mumble itself is only ever using 5 different targets. See
https://github.com/mumble-voip/mumble/blob/34c9b2503361163b649a35598de7de727a64148f/src/mumble/Messages.cpp#L143-L151

and in particular (the comments should give you an idea of what is happening)
https://github.com/mumble-voip/mumble/blob/5d238094ae4e1d599b52e3e4a94e5241fc93bd04/src/mumble/MainWindow.cpp#L2858-L2941

**Comment by spexocta** [comment]
Ah i see that is actually pretty smart :) cool !
