### ISSUE TITLE
OSX - Cant Set keybind for any shortcut keys - 1.3.3

### ISSUE THREAD

**Issue by s3m1s0n1c** [mumble-voip/mumble#4521]
**Describe the bug**
Cant Set key bind for any shortcut keys

**Steps to Reproduce**
Go to shortcuts and set a PTT shortcut then assign the key.. example "Option" key

**Expected behavior**
Being able to set key binds.

**Desktop (please complete the following information):**
 - OS:  MacOS Catalina 10.15.7
 - Version: Mumble 1.3.3

This is after having Mumble 1.3.2 installed

**Comment by Krzmbrzl** [comment]
Duplicate of #4460
