### ISSUE TITLE
Logitech C270 Webcam microphone cannot be used as voice input at first Mumble start

### ISSUE THREAD

**Issue by ellegance** [mumble-voip/mumble#4523]
Logitech C270 Webcam microphone cannot be used as voice input at first Mumble start. You always have to close and re-open Mumble after:
Cold start
Waking from sleep

Windows 7 64bit
Mumble 1.3.0 and 1.3.3 tested.
Similar issue is here: https://github.com/mumble-voip/mumble/issues/2085

**Comment by ellegance** [comment]
It is worth mentioning that it is possible not to restart Mumble after waking from sleep to get Mic working, but open Preferences and press OK.  During this manipulation, following log generated:

<W>2020-10-11 17:17:25.367 AudioInput: Opus encoder set for VOIP
<W>2020-10-11 17:17:25.367 AudioInput: 56933 bits/s, 48000 hz, 480 sample
<W>2020-10-11 17:17:25.369 WASAPIInput: Latencies 100000 30000 => 100000
<W>2020-10-11 17:17:25.376 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2020-10-11 17:17:25.385 WASAPIInput: Mic Stream format 1
<W>2020-10-11 17:17:25.385 WASAPIInput: Stream Latency 53333 (960)
<W>2020-10-11 17:17:25.386 WASAPIOutput: Output stream format 1
<W>2020-10-11 17:17:25.387 WASAPIOutput: Stream Latency 53334 (3840)
<W>2020-10-11 17:17:25.387 WASAPIOutput: Periods 10000us 3000us (latency 5333us)
<W>2020-10-11 17:17:25.387 WASAPIOutput: Buffer is 20000us (1)
<W>2020-10-11 17:17:25.387 WASAPIInput: Echo Stream format 1
<W>2020-10-11 17:17:25.387 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 2 channel 192000 hz echo
<W>2020-10-11 17:17:25.387 AudioOutput: Initialized 2 channel 192000 hz mixer
<W>2020-10-11 17:17:25.396 AudioInput: ECHO CANCELLER ACTIVE

After waking from sleep, by default log was not generated, only logs from previous time.

**Comment by ellegance** [comment]
Opening Preferences and pressing OK after cold start also enables Mic. Here are the logs:

<W>2020-10-11 18:25:31.887 DirectSound: Disabled as WASAPI is available
<W>2020-10-11 18:25:31.887 ASIO: No valid devices found, disabling
<W>2020-10-11 18:25:31.897 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2020-10-11 18:25:31.899 libopus v1.1.3 from C:/Program Files/Mumble/Versions/1.3.3/opus.dll
<W>2020-10-11 18:25:31.902 CELT bitstream 8000000b from C:/Program Files/Mumble/Versions/1.3.3/celt0.0.7.0.dll
<W>2020-10-11 18:25:31.904 CELT bitstream 80000010 from C:/Program Files/Mumble/Versions/1.3.3/celt0.0.11.0.dll
<W>2020-10-11 18:25:31.907 Theme: "Mumble"
<W>2020-10-11 18:25:31.907 Style: "Lite"
<W>2020-10-11 18:25:31.907 --> qss: ":themes/Mumble/Lite.qss"
<W>2020-10-11 18:25:31.908 Locale is "en_US" (System: "en_US")
<W>2020-10-11 18:25:31.960 Database SQLite: "3.18.0"
<W>2020-10-11 18:25:31.961 Bonjour: Failed to load dnssd.dll
<W>2020-10-11 18:25:31.965 Updating application palette
<W>2020-10-11 18:25:31.990 GlobalShortcutWin: Found LowLevelHooksTimeout with value = 0x1388
<W>2020-10-11 18:25:32.038 XboxInput: using XInput DLL 'xinput1_3.dll'
<W>2020-10-11 18:25:32.038 XboxInput: using XInputGetStateEx() as querying function.
<W>2020-10-11 18:25:32.038 GlobalShortcutWin: XboxInput initialized, isValid: 1
<W>2020-10-11 18:25:32.070 Adding device {****GUID A****} Mouse Mouse:8 type 0x00000112 guid product {****GUID A****}
<W>2020-10-11 18:25:32.071 Adding device {****GUID A****} Keyboard Keyboard:127 type 0x00000413 guid product {****GUID A****}
<W>2020-10-11 18:25:32.080 Adding device {****GUID B****} USB Receiver USB Receiver:652 type 0x00010011 guid product {****GUID B****}
<W>2020-10-11 18:25:32.084 Adding device {****GUID B****} USB Receiver USB Receiver:3 type 0x00010011 guid product {****GUID B****}
<W>2020-10-11 18:25:32.090 AudioInput: Opus encoder set for VOIP
<W>2020-10-11 18:25:32.090 AudioInput: 69933 bits/s, 48000 hz, 480 sample
<W>2020-10-11 18:25:32.092 WASAPIInput: Latencies 100000 30000 => 100000
<W>2020-10-11 18:25:32.094 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2020-10-11 18:25:32.100 WASAPIInput: Mic Stream format 1
<W>2020-10-11 18:25:32.100 WASAPIOutput: Output stream format 1
<W>2020-10-11 18:25:32.100 WASAPIInput: Stream Latency 53333 (960)
<W>2020-10-11 18:25:32.100 WASAPIOutput: Stream Latency 53334 (3840)
<W>2020-10-11 18:25:32.100 WASAPIOutput: Periods 10000us 3000us (latency 5333us)
<W>2020-10-11 18:25:32.100 WASAPIOutput: Buffer is 20000us (1)
<W>2020-10-11 18:25:32.100 AudioOutput: Initialized 2 channel 192000 hz mixer
<W>2020-10-11 18:25:32.101 WASAPIInput: Echo Stream format 1
<W>2020-10-11 18:25:32.101 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 2 channel 192000 hz echo
<W>2020-10-11 18:25:32.181 Database SQLite: "3.18.0"
<W>2020-10-11 18:25:32.181 OpenSSL Support: 1 (OpenSSL 1.0.2u  20 Dec 2019)
<W>2020-10-11 18:25:32.186 SSL: CA certificate filter applied. Filtered size: 116, original size: 116
<W>2020-10-11 18:25:32.186 ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2020-10-11 18:25:32.190 ServerHandler: Failed to create QOS2 handle

**** Here I open preferences and press OK ****

<W>2020-10-11 18:25:45.215 AudioInput: Opus encoder set for VOIP
<W>2020-10-11 18:25:45.215 AudioInput: 56933 bits/s, 48000 hz, 480 sample
<W>2020-10-11 18:25:45.216 WASAPIInput: Latencies 100000 30000 => 100000
<W>2020-10-11 18:25:45.220 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2020-10-11 18:25:45.233 WASAPIInput: Mic Stream format 1
<W>2020-10-11 18:25:45.234 WASAPIInput: Stream Latency 53333 (960)
<W>2020-10-11 18:25:45.234 WASAPIOutput: Output stream format 1
<W>2020-10-11 18:25:45.234 WASAPIOutput: Stream Latency 53334 (3840)
<W>2020-10-11 18:25:45.234 WASAPIOutput: Periods 10000us 3000us (latency 5333us)
<W>2020-10-11 18:25:45.235 WASAPIOutput: Buffer is 20000us (1)
<W>2020-10-11 18:25:45.235 AudioOutput: Initialized 2 channel 192000 hz mixer
<W>2020-10-11 18:25:45.237 WASAPIInput: Echo Stream format 1
<W>2020-10-11 18:25:45.237 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 2 channel 192000 hz echo
<W>2020-10-11 18:25:45.244 AudioInput: ECHO CANCELLER ACTIVE

It would be great if Mumble client will not require opening Preferences each time PC starts to work

**Comment by Ledarium** [comment]
@ellegance can you check whether the issue still happens in 1.4.0 snapshot? https://www.mumble.info/downloads/#development-snapshots
