### ISSUE TITLE
Mumble Debug Windows x64 fails to build

### ISSUE THREAD

**Issue by PaulDana** [mumble-voip/mumble#4525]
**Describe the bug**
A recent attempt to grab mumble source and compile on 64 bit windows for a debug target leads to a build error. A PDB file for a library was not found, dnssd.dll.pdb, and warnings-as-errors leads to no linker output. 

**Steps to Reproduce**
1. Go to https://github.com/mumble-voip/mumble-releng-vcpkg to setup mumble build env
2. Clone https://github.com/mumble-voip/mumble.git recursively 
3. Follow setup instructions on building, choose a debug target
4. See build error ... failed (exit code 4099) with the following output:
dnssd.lib(dnssd_clientstub.obj) : warning LNK4099: PDB 'dnssd.dll.pdb' was not found with 'dnssd.lib(dnssd_clientstub.obj)' or at 'D:\dev\fork_mumble\debug_build\dnssd.dll.pdb'; linking object as if no debug info
LINK : error LNK1218: warning treated as error; no output file generated
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Expected behavior**
A build without failures

**Desktop:**
 - OS: Windows 10
 - Version: Mumble latest source (1.4) 

**Additional context**
This same process worked for me a few weeks back, and a release build works fine. I get the same error result attempting a Debug build for both cmake on the command line and using Visual studio.

**Comment by Krzmbrzl** [comment]
A temporary workaround would be to use `-Dwarnings-as-errors=OFF`

**Comment by PaulDana** [comment]
Robert,

That is a great idea, thank you. I will likely take advantage of that.

-Paul

**Comment by Krzmbrzl** [comment]
I'll close this as this is nothing we can change. It has to be fixed by vcpkg. For anybody encountering this, you can work around the issue by using `-Dwarnings-as-errors=OFF` when invoking cmake
