### ISSUE TITLE
Snap version of mumble is not allowed to record audio

### ISSUE THREAD

**Issue by raek** [mumble-voip/mumble#4527]
**Describe the bug**

I installed the snap version of mumble (version 1.3.3, revision 1348, publiusher snapcrafters) on Ubuntu 20.04. Everything seemed to work, except that mumble could not receive any audio from my microphone. It showed up as a capture device, but the audio meter never moved at all in the audio setup wizard. I managed to find the cause (se end).

**Steps to Reproduce**
1. Use a Ubuntu 20.04 machine
2. sudo snap install mumble
3. Start mumble and the audio wizard
4. Select the capture device

**Expected behavior**
Audio level meter should move as I speak. It did not.

**Screenshots**
```
Qt: Session management error: None of the authentication protocols specified are supported
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
<W>2020-10-10 19:17:21.270 JackAudioSystem: unable to open client due to 2 errors:
<W>2020-10-10 19:17:21.270 JackAudioSystem: JackFailure - overall operation failed
<W>2020-10-10 19:17:21.270 JackAudioSystem: JackServerFailed - unable to connect to the JACK server
<D>2020-10-10 19:17:22.319 libopus 1.2.1 from /snap/mumble/1348/bin/libopus.so.0
<W>2020-10-10 19:17:22.349 CELT bitstream 8000000b from /snap/mumble/1348/bin/libcelt0.so.0.7.0
<W>2020-10-10 19:17:22.354 CELT bitstream 80000010 from /snap/mumble/1348/bin/libcelt0.so.0.11.0
<W>2020-10-10 19:17:22.365 Theme: "Mumble"
<W>2020-10-10 19:17:22.365 Style: "Lite"
<W>2020-10-10 19:17:22.365 --> qss: ":themes/Mumble/Lite.qss"
<W>2020-10-10 19:17:22.365 Locale is "en_US" (System: "en_US")
<W>2020-10-10 19:17:22.430 propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.68\" (uid=1000 pid=2057 comm=\"/snap/mumble/1348/bin/mumble \" label=\"snap.mumble.mumble (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=716 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
<W>2020-10-10 19:17:22.430 nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.68\" (uid=1000 pid=2057 comm=\"/snap/mumble/1348/bin/mumble \" label=\"snap.mumble.mumble (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=716 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
<W>2020-10-10 19:17:22.432 "Object path cannot be empty"
<W>2020-10-10 19:17:22.497 Database SQLite: "3.22.0"
<W>2020-10-10 19:17:22.564 Updating application palette
<W>2020-10-10 19:17:22.607 GlobalShortcutX: Using XI2 2.3
Mumble Link plugin: error creating shared memory
<W>2020-10-10 19:17:24.383 AudioInput: Opus encoder set for VOIP
<W>2020-10-10 19:17:24.386 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-10-10 19:17:24.386 PulseAudio: Starting input alsa_input.usb-Samson_Technologies_Samson_C01U-00.analog-stereo
<W>2020-10-10 19:17:24.408 PulseAudio: Stream error: Access denied
<W>2020-10-10 19:17:24.408 PulseAudio: Starting output: alsa_output.pci-0000_00_14.2.analog-stereo
<W>2020-10-10 19:17:24.409 OSInfo: Failed to execute lsb_release
<W>2020-10-10 19:17:24.669 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-10-10 19:17:27.999 PulseAudio: Forcibly disconnected from PulseAudio
```
Note the "Access denied" line right after opening the capture device (Samson_Technologies_Samson_C01U-00).

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: Mumble version 1.3.3, revision 1348, publisher snapcrafters

**Additional context**
Apparently Mumble can list the audio devices, play audio, but just not record audio. Other applications on my system can record fine (for example audacity). Mumble does not show up in the volume control in the list of capture applications.

I was able to work around the problem by manually giving the mumble snap the "audio-record" connection:

```snap connect mumble:audio-record :audio-record```

It looks like others have had a similar problem. You might need to add "audio-record" to some configuration file when building the snap? https://forum.snapcraft.io/t/access-denied-on-capture-data-from-audio-device/19570

**Comment by raek** [comment]
Oh, just found out that someone else found this bug today: https://github.com/snapcrafters/mumble/issues/16

**Comment by Krzmbrzl** [comment]
This seems like a snap-specific problem to me. As we do not maintain the snap distribution, I will simply refer you to the ticket you already found.

If it turns out that this is a problem of Mumble itself after all, let me know and I'll re-open this issue again :)
