### ISSUE TITLE
Watch welcometextfile and reload its content

### ISSUE THREAD

**Issue by deluxghost** [mumble-voip/mumble#4532]
**Context**
The welcome message, is more like a motd somehow, for example, add some news or server updates there. I should be allowed to change it without restart the server

**Describe the feature you have in mind**
Use something like inotify in Linux, watch the file changes, and reload when it changes.

**Describe alternatives you've considered**

* Allow reloading of the entire INI: maybe overkilled, as the welcometextfile is the only thing I want to reload, and such feature still needs the admin trigger the reloading manually after modifying the file.
* Make a script send a welcome message when a user connects: if the user enabled TTS, the client will read the welcome message which is annoying as hell (that's why I prefer welcometext[file])
* Make a script to watch the file and reload server: we can't reload it. I don't know if RPC has such API, but even if there is one, it's still too hard for a normal server admin.

**Additional context**

**Comment by Krzmbrzl** [comment]
I don't think this is a good way to go here - this'd probably involve a lot of OS-specific code in order to handle the watching properly for what I'd consider very little gain.

I much prefer the solution suggested in #2185. An additional bonus seems to be that @Kissaki has already done some work on it a while back, so I assume actually implement it one would "only" have to pick up from where he left things.

**Comment by deluxghost** [comment]
Indeed, if we have a client feature it will be more convenient.

After reading some code, I found setConf in ICE interfaces, which might be the only way to change welcome text without restarting (currently).

**Comment by Krzmbrzl** [comment]
Yes using ICE (or gRPC if it is enabled) is currently the only way.

The client feature will also enable you to set the welcome text on a per-server basis whereas the file-reloading would cause all virtual servers that you have running to change their welcome text to the one specified by you. This might of course not be what you want.

Do you agree that this issue can be closed as a duplicate of #2185?

**Comment by deluxghost** [comment]
I agree, and this issue is already a good archive if someone wants the same feature.
