### ISSUE TITLE
MacOS: Not always able to speak after starting mumble

### ISSUE THREAD

**Issue by TerryGeng** [mumble-voip/mumble#4547]
I simply quote these from #4503 

> The problem (probably not a new one) is I can't speak. This actually happened after we shift to the cmake build system.
> I believe this is, again, the safeguard of MacOS causing troubles, because sometimes a Microphone Permission Request popup shows up when starting mumble and after I clicked "Yes", I can speak. But this popup doesn't always show up.
> I tried to edit the Info.plist file manually but it didn't work, and I was busy with other work at hand so I didn't look into it further.
> Today I found this link: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos, it indicates we should always check if we can access the microphone before actually getting audio out of it. In the case we not yet have permission, we should request it by calling some requestAccess.
> 
> I think I will try this out today or tomorrow and see if the problem is solved.
> 
> But of course, this bug is not related to this PR and I think I should open on an issue over this.

I was actually wondering if I'm the only person who has this problem. I have multiple mumble instance with different versions on my Mac for testing purpose, and probably they got messed up.

**Comment by TerryGeng** [comment]
Some updates: I checked out the 1.3.3 image published recently and I did get this:
![image](https://user-images.githubusercontent.com/2306637/97084499-145d9380-164a-11eb-8ff2-02967040740c.png)

After accepting this, I can use the microphone properly. But this doesn't happen to the dmg file I downloaded from the CI, nor the image I compiled on my Mac.

**Comment by TerryGeng** [comment]
Looks like my investigation on explicitly requesting permission for the microphone is running into a dead end. I have to call some Mac API in the middle Apple only provides Obj-C API for them.
I come across this post while struggling: https://developer.apple.com/forums/thread/129276

It looks like this is actually a code-sign problem that can be resolved by add "--deep" argument when signing the bundle

I think the image of 1.3.3 is properly signed, but not the CI build.

**Comment by davidebeatrici** [comment]
Thank you very much for investigating this!

The CI builds are actually not signed at all.

**Comment by TerryGeng** [comment]
Thanks, @davidebeatrici!

As discussed in the IRC channel, it is a good idea to document this somewhere so people don't get confused when they find their self-compiled/downloaded mumble can't speak. But it would also be great if we can get the signing automatically done in the CI.

**Comment by Krzmbrzl** [comment]
> I have to call some Mac API in the middle Apple only provides Obj-C API for them.

Iirc that is not that big of an issue. I think we are already embedding some Obj-C code in our C++ code, so we could do the same for this issue :thinking:

**Comment by davidebeatrici** [comment]
Indeed.

**Comment by TerryGeng** [comment]
Yeah... I'm thinking about why shouldn't I give it a try. I will see what I can do.
