### ISSUE TITLE
Please include ca-certificates package in the Dockerfile

### ISSUE THREAD

**Issue by manalejandro** [mumble-voip/mumble#4549]
**Context**
Dockerfile

**Describe the feature you have in mind**
Please include ca-certificates package in the Dockerfile for use Certificated Authorities with mumble

**Describe alternatives you've considered**
```
diff --git a/Dockerfile b/Dockerfile
index ff025b6e..83727cef 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -49,6 +49,7 @@ RUN apt-get update && apt-get install -y \
        libqt5sql5 \
        libqt5xml5 \
        libqt5dbus5 \
+        ca-certificates \
        && rm -rf /var/lib/apt/lists/*
 
 COPY --from=0 /root/mumble/build/murmurd /usr/bin/murmurd
```

**Additional context**
Thanks a lot

**Comment by Krzmbrzl** [comment]
@manalejandro why don't you submit a pull request with these changes? That way the changes will be properly attributed to you.

If you don't want to, I can of course do it for you. Just let me know :)

**Comment by manalejandro** [comment]
So sorry for the late answer, please apply these changes i will do one PR next time,

Thanks a lot :+1:
