### ISSUE TITLE
murmur server does not ask for Password upon login

### ISSUE THREAD

**Issue by beatstick** [mumble-voip/mumble#4552]
I have set up a fresh murmur server today. 
I tried setting serverpassword=mysupersecretpassword first 
and password=mypassword (according to the wiki page). 
Having either of these entries in the servers config file does not seem to make any difference. 
I can connect from the Windows client (and open a new room) without ever being asked a password.

I'd like to run a private server. Is this not possible with murmur/mumble?

**Comment by Avatat** [comment]
It's possible to run a private server.

Are you sure, that your client isn't registered at the server?
I'm asking because `serverpassword`/`password` description says:
> This setting configures the default password for unregistered users - registered users will not be prompted for this password

**Comment by beatstick** [comment]
Ah, ok. I am being asked for a password when connnecting via Android. It was probably an error on my end, I changed the configuration a lot when trying to set everything up. The serverpassword setting seems to be the correct one. 
Thanks for the quick help.
