### ISSUE TITLE
How to compile this version of Git for Windows?

### ISSUE THREAD

**Issue by absfilho2** [mumble-voip/mumble#4558]
Gentlemen,

I'm trying to compile version 1.4.0 for windows and I can't get it in any way.
Did they have any tips? Is it complicated to compile and leave in the repository?

Thankful,

**Comment by Krzmbrzl** [comment]
Have you checked out our [build documentation](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/README.md)?

**Comment by absfilho2** [comment]
Yes, I tried to install by script and also manually without success.

By the script for this error.

PS C:\Users\absfi\Documents> .\get_mumble_dependencies.ps1
Setting triplets for AMD64
Checking for C:\Users\absfi\vcpkg...
Your feedback is important to improve Vcpkg! Please take 3 minutes to
complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    mdnsresponder[core]:x64-windows-static-md
Detecting compiler hash for triplet x64-windows-static-md...
Starting package 1/1: mdnsresponder:x64-windows-static-md
Building package mdnsresponder[core]:x64-windows-static-md...
Could not locate cached archive:
C:\Users\absfi\AppData\Local\vcpkg\archives\97\97d415a84752e285493ca63c96e727690914e938.zip
-- Using community triplet x64-windows-static-md. This triplet
configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from:
C:\Users\absfi\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Using cached
C:/Users/absfi/vcpkg/downloads/mDNSResponder-765.30.11.tar.gz
-- Cleaning sources at
C:/Users/absfi/vcpkg/buildtrees/mdnsresponder/src/ponder-765-35f1c06423.clean.
Use --editable to skip cleaning for the packages you specify.
-- Extracting source
C:/Users/absfi/vcpkg/downloads/mDNSResponder-765.30.11.tar.gz
-- Using source at
C:/Users/absfi/vcpkg/buildtrees/mdnsresponder/src/ponder-765-35f1c06423.clean
-- Building
C:/Users/absfi/vcpkg/buildtrees/mdnsresponder/src/ponder-765-35f1c06423.clean/mDNSResponder.sln
for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85
(message):
    Command failed: msbuild
C:/Users/absfi/vcpkg/buildtrees/mdnsresponder/src/ponder-765-35f1c06423.clean/mDNSResponder.sln
/p:Configuration=Release /t:dns-sd /p:Platform=x64 /p:PlatformToolset=v141
/p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No
/p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgManifestInstall=false
/m /p:WholeProgramOptimization=false
    Working Directory:
C:/Users/absfi/vcpkg/buildtrees/mdnsresponder/x64-windows-static-md-rel
    Error code: 1
    See logs for more information:

C:\Users\absfi\vcpkg\buildtrees\mdnsresponder\build-x64-windows-static-md-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:121
(vcpkg_execute_required_process)
  ports/mdnsresponder/portfile.cmake:60 (vcpkg_build_msbuild)
  scripts/ports.cmake:79 (include)


Error: Building package mdnsresponder:x64-windows-static-md failed with:
BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mdnsresponder:x64-windows-static-md
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
vcpkg_install : Failed at installing package mdnsresponder
(x64-windows-static-md)
No C:\Users\absfi\Documents\get_mumble_dependencies.ps1:68 caractere:3
+         vcpkg_install -package mdnsresponder -targetTriplet $triplet
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error],
WriteErrorException
    + FullyQualifiedErrorId :
Microsoft.PowerShell.Commands.WriteErrorException,vcpkg_install

PS C:\Users\absfi\Documents>

Now manually, trying to install the qt5-base package.

PS C:\src\vcpkg\vcpkg> .\vcpkg.exe install qt5-base --triplet
x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows-static-md
  * bzip2[core]:x64-windows-static-md
  * double-conversion[core]:x64-windows-static-md
  * egl-registry[core]:x64-windows-static-md
  * freetype[bzip2,core,png]:x64-windows-static-md
  * harfbuzz[core]:x64-windows-static-md
  * icu[core]:x64-windows-static-md
  * libjpeg-turbo[core]:x64-windows-static-md
  * libpng[core]:x64-windows-static-md
  * libpq[core,openssl,zlib]:x64-windows-static-md
  * openssl[core]:x64-windows-static-md
  * openssl-windows[core]:x64-windows-static-md
  * pcre2[core]:x64-windows-static-md
    qt5-base[core]:x64-windows-static-md
  * ragel[core]:x64-windows-static-md
  * sqlite3[core]:x64-windows-static-md
  * zlib[core]:x64-windows-static-md
  * zstd[core]:x64-windows-static-md
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static-md...
Error occurred while detecting compiler information. Pass `--debug` for
more information.
PS C:\src\vcpkg\vcpkg> qt5-base

Finally with the debug command, where we see an SSL connection error.

PS C:\src\vcpkg\vcpkg> .\vcpkg.exe install qt5-base --triplet
x64-windows-static-md --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Using vcpkg-root: C:\src\vcpkg\vcpkg
[DEBUG] Using installed-root: C:\src\vcpkg\vcpkg\installed
[DEBUG] Using buildtrees-root: C:\src\vcpkg\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\src\vcpkg\vcpkg\downloads
[DEBUG] Using packages-root: C:\src\vcpkg\vcpkg\packages
[DEBUG] Using scripts-root: C:\src\vcpkg\vcpkg\scripts
[DEBUG] Default binary cache path is:
C:\Users\absfi\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   118451 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe"
-DVCPKG_ROOT_DIR=C:/src/vcpkg/vcpkg
-DPACKAGES_DIR=C:/src/vcpkg/vcpkg/packages
-DBUILDTREES_DIR=C:/src/vcpkg/vcpkg/buildtrees
-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/vcpkg/installed
-DDOWNLOADS=C:/src/vcpkg/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P
"C:\src\vcpkg\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    76354 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe"
-DVCPKG_ROOT_DIR=C:/src/vcpkg/vcpkg
-DPACKAGES_DIR=C:/src/vcpkg/vcpkg/packages
-DBUILDTREES_DIR=C:/src/vcpkg/vcpkg/buildtrees
-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/vcpkg/installed
-DDOWNLOADS=C:/src/vcpkg/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P
"C:\src\vcpkg\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    84079 us
The following packages will be built and installed:
  * brotli[core]:x64-windows-static-md
  * bzip2[core]:x64-windows-static-md
  * double-conversion[core]:x64-windows-static-md
  * egl-registry[core]:x64-windows-static-md
  * freetype[bzip2,core,png]:x64-windows-static-md
  * harfbuzz[core]:x64-windows-static-md
  * icu[core]:x64-windows-static-md
  * libjpeg-turbo[core]:x64-windows-static-md
  * libpng[core]:x64-windows-static-md
  * libpq[core,openssl,zlib]:x64-windows-static-md
  * openssl[core]:x64-windows-static-md
  * openssl-windows[core]:x64-windows-static-md
  * pcre2[core]:x64-windows-static-md
    qt5-base[core]:x64-windows-static-md
  * ragel[core]:x64-windows-static-md
  * sqlite3[core]:x64-windows-static-md
  * zlib[core]:x64-windows-static-md
  * zstd[core]:x64-windows-static-md
Additional packages (*) will be modified to complete this operation.
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual
Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format
xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    71890 us
Detecting compiler hash for triplet x64-windows-static-md...
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    62632 us
[DEBUG]
CreateProcessW("C:\src\vcpkg\vcpkg\downloads\tools\powershell-core-7.0.3-windows\pwsh.exe"
--version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   560587 us
[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.1
amd64   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)
[DEBUG] cmd_execute_and_stream_data() returned 0 after  2290782 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe"
-DCURRENT_PORT_DIR=C:/src/vcpkg/vcpkg/scripts/detect_compiler
-DCURRENT_BUILDTREES_DIR=C:/src/vcpkg/vcpkg/buildtrees/detect_compiler
-DCURRENT_PACKAGES_DIR=C:/src/vcpkg/vcpkg/packages/detect_compiler_x64-windows-static-md
-DCMD=BUILD -DTARGET_TRIPLET=x64-windows-static-md
"-DTARGET_TRIPLET_FILE=C:\src\vcpkg\vcpkg\triplets\community\x64-windows-static-md.cmake"
-DVCPKG_PLATFORM_TOOLSET=v141 -DDOWNLOADS=C:/src/vcpkg/vcpkg/downloads
-DVCPKG_CONCURRENCY=5 "-DGIT=C:/Program Files/Git/cmd/git.exe"
-DVCPKG_ROOT_DIR=C:/src/vcpkg/vcpkg
-DPACKAGES_DIR=C:/src/vcpkg/vcpkg/packages
-DBUILDTREES_DIR=C:/src/vcpkg/vcpkg/buildtrees
-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/vcpkg/installed
-DDOWNLOADS=C:/src/vcpkg/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P
"C:\src\vcpkg\vcpkg\scripts\ports.cmake")
[DEBUG] -- Found ninja('1.8.2') but at least version 1.10.1 is required!
Trying to use internal version if possible!
[DEBUG] -- Downloading
https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip.
..
[DEBUG] -- Downloading
https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip...
Failed. Status: 35;"SSL connect error"
[DEBUG] CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182
(message):
[DEBUG]
[DEBUG]       Failed to download file.
[DEBUG]       If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
environment
[DEBUG]       variables to "https://user:password@your-proxy-ip-address
:port/".
[DEBUG]       Otherwise, please submit an issue at
https://github.com/Microsoft/vcpkg/issues
[DEBUG]
[DEBUG] Call Stack (most recent call first):
[DEBUG]   scripts/cmake/vcpkg_find_acquire_program.cmake:525
(vcpkg_download_distfile)
[DEBUG]   scripts/cmake/vcpkg_configure_cmake.cmake:161
(vcpkg_find_acquire_program)
[DEBUG]   scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
[DEBUG]   scripts/ports.cmake:135 (include)
[DEBUG]
[DEBUG]
[DEBUG] cmd_execute_and_stream_data() returned 1 after 21796957 us
[DEBUG]
[DEBUG] Compiler information tracking can be disabled by passing
--feature-flags=-compilertracking
Error occurred while detecting compiler information. Pass `--debug` for
more information.
[DEBUG] c:\src\vcpkg\vcpkg\toolsrc\src\vcpkg\build.cpp(578)
[DEBUG] Exiting after 25171260 us (25134815 us)
PS C:\src\vcpkg\vcpkg>

Can you help me try to understand where I'm going wrong?

Regards,

Antonio Barbosa.


Em sex., 30 de out. de 2020 às 09:41, Robert Adam <notifications@github.com>
escreveu:

**Comment by absfilho2** [comment]
I also did the following commands and was not successful.

PS C:\src\vcpkg\vcpkg> .\vcpkg.exe update
Using local portfile versions. To update the local portfiles, use `git
pull`.
No packages need updating.
PS C:\src\vcpkg\vcpkg> git pull
Already up to date.
PS C:\src\vcpkg\vcpkg>

Em sex., 30 de out. de 2020 às 09:41, Robert Adam <notifications@github.com>
escreveu:

**Comment by Krzmbrzl** [comment]
> Command failed: msbuild

and 

> Error occurred while detecting compiler information. Pass `--debug` for
more information.

Seem to indicate that you either don't have the necessary build tools installed or that your installation is broken/unavailable.

Did you install visual studio as described?

**Comment by BeLucky-219** [comment]
error: building boost-headers:x64-windows-static-md failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle boost-headers:x64-windows-static-md: 1.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-headers
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-headers]+Build+error+on+x64-windows-static-md&body=Copy%20issue%20body%20from%20C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

error: The following packages are not installed:
  boost-accumulators:x64-windows-static-md
Building dependency boost-algorithm
Computing installation plan...
The following packages will be built and installed:
    
l got the problem,when l download the dependency.（build_mumble_dependencies.ps1)(win11)(vs2022)

Can you help me try to understand where I'm going wrong?

**Comment by Krzmbrzl** [comment]
I would need the actual error message to say anything meaningful. You'll find it in the contents of the files the vcpkg error references.
