### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by 61Awesome** [mumble-voip/mumble#4576]
So I had just downloaded mumble. I am clicking through all of the buttons to see what they do. One of them said "minimal view" and I clicked it and now there is just a window that says "Mumble - Minimal View -- 1.3.3" and the whole window is just white. How do I fix this? Also, It wouldn't let me join any servers which is another reason that I was clicking around in the first place. SOMEONE PLEASE HELP me to fix this. A quick way of reaching out to me is my discord:
Asteroid Pal#9371
spaces and capital sensitive
PLEASE HELP and TY

**Comment by davidebeatrici** [comment]
Right click -> Configure -> Minimal View

**Comment by 61Awesome** [comment]
Hey, thanks, but I did manage to find a follow up link that lead me to that
solution. But I do have another two problems with mumble.
1. I can’t make my own server. I need some sort of address or port. Where
do I find that?
2. How can I get mumble to work for Minecraft 1.8.9 as for the proximity
chat?
Thanks for your help,
[AP]

**Comment by davidebeatrici** [comment]
1. You have to either join a server that already exists or host a new one.
2. https://www.curseforge.com/minecraft/mc-mods/mumble-integration

**Comment by 61Awesome** [comment]
1. How do I host a new one if I can’t join it because it tells me I need an
IP and a port?
2. I can’t do it on 1.8.9? That link is for a 1.16.4 version...

**Comment by davidebeatrici** [comment]
1. If you host it locally you can write `localhost` and `64738` (default port).
2. I think it works for all versions.

**Comment by 61Awesome** [comment]
1. What would I write for the IP address if it is not local and port as
well?
2. I’ll test it, but what if it doesn’t work for 1.8.9?

**Comment by Krzmbrzl** [comment]
If you do not know thw IP address of a server, tben I assume you don't have a specific server you want to connect to.
Thus you can simply choose one of the available public servers from the list in the connect dialog.

**Comment by 61Awesome** [comment]
I want to make my own server. I can’t connect to it though... I don’t know
the IP address or port number. How do I find it?

**Comment by Krzmbrzl** [comment]
If you don't know the IP address of your server, how did you connect to it in the first place?

The port can be specified in the `murmur.ini` file. Have a look at https://wiki.mumble.info/wiki/Murmur.ini#port
(The default is 64738)

**Comment by 61Awesome** [comment]
I didn’t connect to it... I made it, but it would not allow me to connect
to it.

**Comment by Krzmbrzl** [comment]
You have to jave connected to your server hardware in order to start the Mumble server.

Or are you trying to create a servee on your local computer?

**Comment by 61Awesome** [comment]
I don’t know how to do that.

**Comment by Krzmbrzl** [comment]
???

What exactly are you doing? Please write it up step by step

**Comment by 61Awesome** [comment]
ok,
1. I click “connect”
2. I click “make new” server
3. It gives me a pop up where I put in the display name of the server, my
display name, a port number, and an IP address. Where do I find the port
and IP address numbers? I can’t join the server without them apparently.

**Comment by Krzmbrzl** [comment]
Ah I see. That popup is not for creating a new server. It is actually for adding one to your list of favorites. So if you don't know the address of a server you want to add to that list, don't click that button. Instead expand the list item "public internet" in the connect dialog. There you'll find a list of available servers that you can join.

**Comment by toby63** [comment]
https://wiki.mumble.info/wiki/Running_Murmur describes how to run a server.
It's not a simple "click & run", but it's also not too complicated.
Basically adjust some values in the configuration file and run murmur.

And some notes offtopic:
@61Awesome For the future:
1. Don't use titles like "please help", they are not informative and in some communities you will be ignored, because of something like that.
2. Inform yourself before posting, there is a wiki, which tells you everything.
