### ISSUE TITLE
Chat Messages not Received

### ISSUE THREAD

**Issue by gagefredricks-ucsd** [mumble-voip/mumble#4578]
**Describe the bug**
After an indeterminate amount of time, messages will appear to send but will not be received by the other party.
After reconnecting to the server, message system will function as expected. No client reboot or server reboot necessary.

**Steps to Reproduce**
Stay connected to a server with another user. Attempt to send messages to the general Channel, and verify that the other user has not received the message.

**Expected behavior**
Sent messages should be received by all applicable users.

**Desktop (please complete the following information):**
Windows 10
Mumble 1.3.2

**Comment by Krzmbrzl** [comment]
What version is the server running that you are experiencing this on?

Have you seen this behavior only on a single server or did you observe it on multiple servers?

Does audio still work in cases when text messages are not reaching their destination?

**Comment by gagefredricks-ucsd** [comment]
Hi, thank you for the follow up. I have attached an image of the server information.

Testing has not been done on other servers. Audio communication functions as expected during observed error condition.

![MumbleServerInfo](https://user-images.githubusercontent.com/57237800/99204347-338fa280-276a-11eb-8262-cb763641fd2b.png)

**Comment by Krzmbrzl** [comment]
When this happens, are you able to switch channels?

**Comment by gagefredricks-ucsd** [comment]
No. Channels cannot be switched even when user has entry privileges.

**Comment by Krzmbrzl** [comment]
Oh that is interesting then. This means that the TCP connection between the client and the server stops working after a given time...

Could you post the output of the "Developer console" after this has happened again?
You can enable this console in the settings (I think under the user interface tab) and then open it from Mumble's menu bar at the top)

**Comment by gagefredricks-ucsd** [comment]
![MumbleTicket](https://user-images.githubusercontent.com/57237800/99466397-323cb200-28f1-11eb-9f68-2ba8e281f23b.png)

**Comment by Krzmbrzl** [comment]
I assume the log does not continue beyond what's shown in the screenshot?

Would have been too easy if the log contained a conclusive hint, I guess xD

Still I think it is very curious that the TCP connection would drop but the UDP one still works.

It would be important to know whether this issue appears on a different server as well. Any chance you could try that out?

**Comment by exrok** [comment]
Using murmur 1.3.3 on arch linux, and clients running  mumble 1.3 from various linux distro, I have observed messages sometimes not being received, reconnecting to the server fixes the problem temporarily. This issue has been happening for 3-4 months now. I have not tried switching channels when the problem occurs, next time the problem happens I will test it and I will report back.

**Comment by exrok** [comment]
Can confirm, that switching channels fails when messages are not being received.  Also, when the problem is occurring, lsof still shows a tcp stream established: `lsof -a -i4 -itcp`

```
mumble 513061 username 44u IPv4 1773093 0t0 TCP laptop:49240->[REDACTED]:64738 (ESTABLISHED)
```

**Comment by Krzmbrzl** [comment]
@exrok to me it sounds like you are hosting the server yourself. Is that correct?

> This issue has been happening for 3-4 months now.

Have you upgraded your server (or client) recently (In that period of time perhaps)?
Looking at our [releases](https://github.com/mumble-voip/mumble/releases), 3-4 months earlier from now would correspond to Mumble v1.3.2.
Have you been using that version before? If so: Did you already encounter this issue then?
If not: What was the last Mumble version you had in use and when did you upgrade?

> mumble 513061 username 44u IPv4 1773093 0t0 TCP laptop:49240->[REDACTED]:64738 (ESTABLISHED)

Has the `[REDACTED]` been inserted by you?

How long do you usually have to be connected to a server before messages stop arriving?

**Comment by exrok** [comment]
Yes we are hosting the server our selves on, an OVH vps (my friend hosts it).

The murmur server has been updated over the last couple months server. Honestly, we do not recall exactly when the problem started occurring. We looked in the murmur logs last night and didn't see anything that stands out. 

What are the logs we should we collect? I don't mind running a debug version of a mumble client if that would help although I did not see any more verbose logging builds described in `cmake_options.md`. 

Our clients have also been updated. 

Although their was other bugs at the time I do not recall the problem occurring before 1.3, over an year ago, (hosting from the same server, I think).  

Sometimes the problem does not occur all day. However, sometimes it happens after just a few minutes but if had to guess I would say the mean time to failure is around 2 hours. Again, sometimes you don't notice it happen because on the senders end everything thing looks to be working (unless you try to change a channel of course). 

The [RADACTED] was inserted by myself to obscure the IP of server.

**Comment by Krzmbrzl** [comment]
> What are the logs we should we collect?

If it's not in the normal server log, there are no other logs. The only thing that could be done on the server-side is to start the server with the `-v` option. I don't really think that this will bring up useful information though :thinking: 

> I don't mind running a debug version of a mumble client if that would help although I did not see any more verbose logging builds described in cmake_options.md.

Nah, there is no such option.

Given that you are using Mumble on Linux I assume you are using the version supplied by your distribution? If so, I would expect you and your friends using different versions and therefore I currently tend to think that this is probably rather a server-side issue.

What could be helpful would be if you were able to downgrade the server to e.g. 1.3.2 (but back up your server's DB beforehand. I'm not sure how Murmur deals with downgrades) and check if the issue will still show up...

**Comment by exrok** [comment]
Turns out that the murmur server hadn't been updated, it was running in a docker container as was still on 1.3.0. We rebuilt the docker container and updated to 1.3.3 and haven't had any issue yet. Hopefully, it stays fixed. Sorry for the inconvenience.

**Comment by Krzmbrzl** [comment]
Ah that would be even better - A bug that fixes itself is a good bug :D 

@gagefredricks-ucsd could you also try upgrading your server to 1.3.3, please?

**Comment by gagefredricks-ucsd** [comment]
Hi,
I upgraded the Murmur server to 1.4.0. I will update this ticket if the issue is still observed.
For now, I think we can assume this is fixed due to the findings done by @exrok 
Please keep up the great work. Mumble is very close to my heart.

**Comment by Krzmbrzl** [comment]
Okay, thanks for the update and your kind words :)
