### ISSUE TITLE
Warn when microphone access has been denied/blocked by OS privacy controls

### ISSUE THREAD

**Issue by ancarda** [mumble-voip/mumble#4580]
**Context**
Improved User Experience and Troubleshooting, especially first time users.

**Describe the feature you have in mind**
Programs on some operating systems (such as macOS) need to ask the system for access to the microphone. Mumble does this, but does not behave any differently when the user has not granted access.

Given Mumble's reason for existing is VoIP, I think it would be good to detect this and show a warning in the console, perhaps:

>WARNING: Your Operating System (macOS) has denied Mumble access to the microphone.
>
>You can enable access by checking "Mumble" in the "Privacy" tab of the "Security & Privacy" pane in System Preferences. Restart Mumble once checked to apply.

The second line could be platform specific instructions on how to fix this problem.

Perhaps it would also be good to force the client-side mute toggle so other people on the server know the user cannot speak and the user cannot unmute to send "null audio".

**Describe alternatives you've considered**
I'm not aware of any relevant alternatives.

**Additional context**
Idea came from this issue: https://github.com/mumble-voip/mumble/issues/1140#issuecomment-727619689

**Comment by davidebeatrici** [comment]
#3572 implemented something similar for WASAPI (Windows).

**Comment by ancarda** [comment]
Thanks @davidebeatrici, do you know if other platforms have this? If it's just Windows and macOS, can you add the macOS tag to this issue?

I've been looking into a fix for this, and I think it would be possible to call [`authorizationStatusForMediaType`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624613-authorizationstatusformediatype?language=objc) somewhere in CoreAudio.cpp and see if that returns [`AVAuthorizationStatusDenied`](https://developer.apple.com/documentation/avfoundation/avauthorizationstatus/avauthorizationstatusdenied?language=objc). That would be a similar change to bring macOS in line with Windows.

Though, the pedantic part of me feels this isn't quite right -- CoreAudio could be one of many APIs for audio on macOS. It feels like the wrong place to put a system-wide permission check that isn't actually part of CoreAudio (technically part of AVFoundation). Is there a better/more ideologically pure place to put this check?

Nevertheless, I will see if I can get Mumble to build and will send a PR if I'm successful in implementing this.

**Comment by davidebeatrici** [comment]
As far as I know only Windows and macOS provide a way to explicitly block access to the microphone.

However, it may be worth adding a new virtual function to `AudioInput` so that we can have a common handler in `MainWindow` (i.e. print a message or show a dialog).

**Comment by TerryGeng** [comment]
I think this issue is a duplication of #4547. I'm on my way to fix it, but I was just busy this month.

**Comment by Krzmbrzl** [comment]
I thought that these might be related as well (https://github.com/mumble-voip/mumble/issues/1140#issuecomment-727585052). At least they are very similar.

The difference I see though is that in #4547 you stated that only sometimes the mic wouldn't work whereas with this scenario here I am assuming that this should be rather consistent :thinking:
