### ISSUE TITLE
Glitching graphic, screen flickers

### ISSUE THREAD

**Issue by Amanuense-del-diavolo** [mumble-voip/mumble#4583]
**Describe the bug**
When Mumble gets maximized the mumble window starts flickering, the program is killalble only trought a terminal and a terminal (killall comand) Alt+F4 doesn't work, mumble isteslf (voice chat) keeps working

**Steps to Reproduce**
the step aren't really clear, I've managed to reproduce this issue in 2 ways

Steps to reproduce the behavior (1):
1. Have the mumble window minimized
2. Maximize it to fullscreen

Steps to reproduce the behavior (2):
1. Change the configuration
2. Press "Apply"
3. Press "Ok"
4. Sometimes the screen flickers

Usually I use Mumble as a fullscreen window, I can't tell if it happens with a normal window as well
while Mumble flickers it doesn't respond to any comand, and forcefully stays in the foreground, so it's not possible to reduce it

**Expected behavior**
Not to be a rave party

**Screenshots**
due to the nature of the problem I don't have a screenshot

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Kernel: 5.9.8-arch1-1
 - Version: Mumble 1.3.3

**Additional context**
launcing the trought the terminal the following error appeared while the glith was happening:

```<W>2020-11-16 13:47:51.511 internal error:  void QXcbWindow::setNetWmStateOnUnmappedWindow() called on mapped window
<W>2020-11-16 13:47:51.614 internal error:  void QXcbWindow::setNetWmStateOnUnmappedWindow() called on mapped window
<W>2020-11-16 13:47:51.798 internal error:  void QXcbWindow::setNetWmStateOnUnmappedWindow() called on mapped window
<W>2020-11-16 13:47:52.065 internal error:  void QXcbWindow::setNetWmStateOnUnmappedWindow() called on mapped window
<W>2020-11-16 13:47:52.219 internal error:  void QXcbWindow::setNetWmStateOnUnmappedWindow() called on mapped window
[...]
```

and another time (after changing the configuration) this error appeared:

`<W>2020-11-16 13:50:06.129 QXcbConnection: XCB error: 3 (BadWindow), sequence: 13092, resource id: 14683493, major code: 40 (TranslateCoords), minor code: 0`

**Comment by Krzmbrzl** [comment]
Seems like a duplicate of #3977 - could you check whether you get the same behavior when performing the following steps?
1. Maximize Mumble
2. Hide/Minimize to tray
3. Click the tray icon

If this is the case do you still get the flickering in the scenarios described by you if "minimize to tray" is disabled in Mumble's settings?

**Comment by Amanuense-del-diavolo** [comment]
I've disabled the "minimize to tray" option in Mumble's settings, if the issue doesn't re-happen in the next 24h I'll consider mine as a duplicate of issue https://github.com/mumble-voip/mumble/issues/3977 and close it (sorry but I didn't find https://github.com/mumble-voip/mumble/issues/3977 earlier)

**Comment by Krzmbrzl** [comment]
> sorry but I didn't find #3977 earlier

No worries :)

**Comment by Amanuense-del-diavolo** [comment]
seems to have solved it 
thanks for the help

**Comment by suppadeliux** [comment]
Unchecking the option `Hide in tray when minimized` did the job. thanks
