### ISSUE TITLE
Is trymumble.com a Scam?

### ISSUE THREAD

**Issue by Per0x** [mumble-voip/mumble#4585]
Hello, I recently discovered the site: https://trymumble.com/ which takes the name Mumble and shows screenshots very close (exact copy) to what Discord does. The links all go back to the main page or fails at DNS, and it looks a lot like a dummy site.
What is the purpose of this, and why would they want to make people believe that it is related to mumble when there is obviously nothing behind it?

**Comment by davidebeatrici** [comment]
Hello,

Thank you very much for bringing this to our attention.

The owner contacted us in November 2019 to ask whether he could use the name, after people [pointed out](https://www.producthunt.com/posts/mumble) that a VoIP project with the same name already existed.

We recommended to change the name to avoid confusion and it seems that they're rebranding to Bondfire: https://dev.to/davidyapdy/a-weekend-hack-that-gained-1-300-users-3he0

However, the article is from December 2019 and we didn't hear back from them.

Maybe we should ask for updates on the matter.

**Comment by Krzmbrzl** [comment]
We talked about this in our latest meeting and concluded that we don't really mind them using that name. It is obviously not ideal but in the end this seems like a rather niche product so the chance of our users getting confused by this website seems rather slim.

And as we don't have a trademark in the name "Mumble" anyways, there wouldn't be that much we could do about it anyways (other than ask nicely of course).

Thanks nonetheless for bringing this to our attention though :+1:

**Comment by Per0x** [comment]
could it be a problem if THEY trademark Mumble, and prevent you from using it since it's the same type of software ?

**Comment by Krzmbrzl** [comment]
I'm not a lawyer but I was always under the impression that you can't trademark a name that has been used by another product for years already :thinking:

**Comment by Per0x** [comment]
Like Apple ? ^^
I'm not a lawyer too, I hope it will be ok for the real Mumble.

**Comment by Krzmbrzl** [comment]
> Like Apple ? ^^

Fair point xD

I just did a quick research and according to https://secureyourtrademark.com/can-you-trademark/trademark-a-name-already-in-use/ nobody should be able to trademark "Mumble" at least as long as they are providing a communication software of some sort :point_up:

**Comment by toby63** [comment]
> that we don't really mind them using that name.

There is always potential for confusion, so I would advocate you to deny such requests always, especially if it's exactly the same software category.
