### ISSUE TITLE
Would like to use on ARM processor (Lenovo Miix 630), native 64 bit

### ISSUE THREAD

**Issue by 0verflw** [mumble-voip/mumble#4589]
Is that possible?

**Comment by davidebeatrici** [comment]
Should be possible, but right now you have to compile it yourself.

See https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_static.md.

**Comment by 0verflw** [comment]
Okay, i will try. I hope i can coma back to you if i dont get the process x)

**Comment by Krzmbrzl** [comment]
Fell free to do so :)

In the meanwhile I'll close this issue though :point_up:
