### ISSUE TITLE
Filter for who has spoken recently

### ISSUE THREAD

**Issue by strich** [mumble-voip/mumble#4594]
**Context**
It is quite common amongst the EVE Online playerbase that the mumble overlay is not workable due to the complexity of the EVE UI and not wanting to overlay more text on top. Furthermore a number of other utilities conflict with the dx overlay and Mumble will fail to show it. Many of us end up trying to use the channel user list on another monitor to show who is talking. However this is often a hack and inaccurate as it doesn't take many to overfill the window with users.

**Describe the feature you have in mind**
There are two options I have in mind:

1. The existing Mumble UI filter supports an option to sort channel users by last spoken time instead of name.
2. A minimal always-on-top window can be spawned that is exactly the existing mumble overlay render, which can be moved around on to any monitor and location.

**Describe alternatives you've considered**
AFAIK there is no known alternative to this.

**Comment by Krzmbrzl** [comment]
Does the "Talking UI" introduced in https://github.com/mumble-voip/mumble/pull/4066 fulfill your needs? To me it seems that this is exactly what you mentioned as your second option.

It will be part of the 1.4.0 release (no ETA on that yet though)

**Comment by strich** [comment]
Yep that seems perfect! I would go test it but I see that the dev/beta/snapshot build infrastructure is dead. :/

I would be tempted to build a snapshot myself if v1.4 not even has an ETA at this point.

**Comment by Krzmbrzl** [comment]
> the dev/beta/snapshot build infrastructure is dead

I don't even know what that is xD

Building the current master branch is relatively simple. Just follow the instructions at https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions

We working on releasing the first snapshot releases ASAP, but I can't promise anything :/

**Comment by Krzmbrzl** [comment]
Oh and btw: I'll close this issue as the requested feature has already been implemented in master :point_up:

**Comment by strich** [comment]
> I don't even know what that is xD
Most projects have build infrastructure that auto builds and publishes builds for download so each individual doesn't have to do the build process themselves. Seems like on your website it says that the build infrastructure is being upgraded and daily builds aren't working right now.

**Comment by Krzmbrzl** [comment]
Ah okay - yeah that's something I wanted to tackle at some point, but never got around actually doing it. The update of the build env has been completed by now, so in theory it would be possible to do so.

In the meantime you can take the less pretty route of directly downloading the artifacts of our CI builds (at least for Windows & macOS as the AppImage is currently broken). 
You can find the links to the CI runs by clicking on the green tick or the red cross (depending on the build status) on this repo's main page next to the most recent commit. Then you'll have to select any of the builds that have been run on Azure Pipelines and from their website you can download the artifacts (although they are a bit hidden. Look for the phrase "4 published").
The most recent ones can currently be found here: https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=2986&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by strich** [comment]
Holy moly that Azure DevOps website is certainly something - Accessing almost any other page than the one you linked and the specific pages you mentioned causes it to first render fine and _then_ force ask for auth, which I don't have access for, which then kicks me out.

I did get that snapshot you linked and it appears to be running fine, thank you! I'll see how this Talking UI goes. 👍

**Comment by Krzmbrzl** [comment]
Yep that website is quite complicated xD
