### ISSUE TITLE
API to create rooms dynamically

### ISSUE THREAD

**Issue by rkachach** [mumble-voip/mumble#4601]
**Context**
When using Mumble as private Audio server for multiple conferences that are created on-demand

**Describe the feature you have in mind**
Basically some API in order to create new rooms (one for each conference). Right now I think it's only possible from the UI.

**Describe alternatives you've considered**
Right now I think it can only be done manual which doesn't scale when we need multiple conferences.

**Additional context**

**Comment by Krzmbrzl** [comment]
This is already supported. You have to use the ICE interface the server provides. In there there is this function
https://github.com/mumble-voip/mumble/blob/916f8ed0a742c2236e4dcd5df8886ed19d9d904d/src/murmur/Murmur.ice#L655-L660
That allows you to create rooms (channels) on demand.

There is also this documentation on the topic: https://wiki.mumble.info/wiki/Ice

To get an idea on how this could work, you might take a look at [Mumo](https://github.com/mumble-voip/mumo) which makes use of the ICE API.

**Comment by rkachach** [comment]
Thank you very much for the detailed information. In fact using ICE interface I was able to achieve what I need.

**Comment by Krzmbrzl** [comment]
Perfect! I'm glad I could be of service :)
