### ISSUE TITLE
Mumble disconnects from the audio backend when applying audio settings

### ISSUE THREAD

**Issue by polyzium** [mumble-voip/mumble#4603]
**Describe the bug**
After going into the Mumble Configuration window, changing ANY setting and clicking "Apply", Mumble stops outputting any sound.

**Steps to Reproduce**
1. Click the "Configure Mumble" button or go to Configure -> Settings...
2. Change any setting, for example, toggle RNNoise.
3. Click "Apply"
4. Audio stops playing

**Expected behavior**
Mumble would reconnect to the audio backend and continue playing the sound.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux, kernel 5.4.77-1-MANJARO
 - Version: Mumble 1.3.3

**Additional context**
I was in a server while doing this. A restart fixes this bug.

**Comment by Krzmbrzl** [comment]
Ho, I thought this was a bug that crept in in 1.4.0. The fact that this also shows in 1.3.3 is very interesting :thinking:

**Comment by Erudition** [comment]
I have this in 1.3.3 as well on Ubuntu Studio. Very frustrating, not usable. Which version should I downgrade to?

**Comment by Krzmbrzl** [comment]
I don't have any knowledge as to which version introduced this bug. I have switched computer since my last comment and the issue is gone. This makes me believe that this is a non-trivial bug that might even be hardware-dependent. Which makes it really hard to find a fix of course :eyes:

**Comment by TerryGeng** [comment]
Not even sure if this is a bug of Mumble. Mumble does re-initialize the audio backend after hitting "Apply", but it does nothing different than the first time it initializes the audio backend.

Would you please run Mumble in the terminal and paste the log when pressing "Apply"?
