### ISSUE TITLE
mumble/docs/dev/build-instructions/build_static.md not working for me

### ISSUE THREAD

**Issue by k1ttt-remote** [mumble-voip/mumble#4608]
Starting to try to build mumble on windows on a brand new win10 machine, i think i have vs2019 and all the stuff it needs installed.  i tried following instructions in mumble/docs/dev/build-instructions/build_static.md.  the powershell script kept failing on the ice package so commented those lines out and everything else worked

i downloaded the mumble-voip/ice into ports/zeroc-ice and it looks like what is needed is in there.  but when trying to install it can't see the directory for some reason...
```
C:\Users\k1ttt\vcpkg>vcpkg install zeroc-ice --triplet x64-windows-static-md
Computing installation plan...
Error: while loading zeroc-ice:
no such file or directory
Error: Failed to load port zeroc-ice from C:\Users\k1ttt\vcpkg\ports\zeroc-ice
```
while the above is confusing i don't really need to build the server side so i 'think' i can ignore that.  

ignoring ice for a while i continued on and got to step 5 under "Building Mumble" and plugged in the command line:
```
d:\SoftwareDev\mumble\mumble\build>cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=c:/users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DIce_HOME=c:/users/k1ttt/vcpkg/installed/x64-windows-static-md" "-DCMAKE_BUILD_TYPE=Release" ..

which gets off to a good start but apparently can't find opus and some other dependencies

-- Using Win7 as the oldest supported Windows version
-- ##################################################
-- Mumble version:  1.4.0
-- Architecture:    64bit
-- Build type:      Release
-- ##################################################
-- Qt5 component found: Core | Version: 5.15.1
-- Qt5 component found: Network | Version: 5.15.1
-- Qt5 component found: Xml | Version: 5.15.1
-- OpenSSL component found: Crypto
-- OpenSSL component found: SSL
-- Qt5 component found: Concurrent | Version: 5.15.1
-- Qt5 component found: Sql | Version: 5.15.1
-- Qt5 component found: Svg | Version: 5.15.1
-- Qt5 component found: Widgets | Version: 5.15.1
CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)
  cmake/pkg-utils.cmake:79 (find_package)
  src/mumble/CMakeLists.txt:390 (find_pkg)


-- Boost component found: system | Version: 1.74.0
CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)
  cmake/pkg-utils.cmake:79 (find_package)
  src/mumble/CMakeLists.txt:390 (find_pkg)


CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)
  cmake/pkg-utils.cmake:79 (find_package)
  src/mumble/CMakeLists.txt:390 (find_pkg)


CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)
  cmake/pkg-utils.cmake:79 (find_package)
  src/mumble/CMakeLists.txt:390 (find_pkg)


CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)
  cmake/pkg-utils.cmake:79 (find_package)
  src/mumble/CMakeLists.txt:390 (find_pkg)


-- Boost component found: thread | Version: 1.74.0
-- Disabling warnings for targets: xinputcheck
CMake Error at src/mumble/CMakeLists.txt:504 (add_subdirectory):
  The source directory

    D:/SoftwareDev/mumble/mumble/3rdparty/opus

  does not contain a CMakeLists.txt file.


-- Disabling warnings for targets:
CMake Error at src/mumble/CMakeLists.txt:519 (set_target_properties):
  set_target_properties Can not find target to add properties to: opus


CMake Error at cmake/install-library.cmake:7 (get_target_property):
  get_target_property() called with non-existent target "opus".
Call Stack (most recent call first):
  src/mumble/CMakeLists.txt:525 (install_library)


CMake Error at 3rdparty/celt-0.7.0-build/CMakeLists.txt:5 (message):
  D:/SoftwareDev/mumble/mumble/3rdparty/celt-0.7.0-build/../celt-0.7.0-src
  was not found.


  Please checkout the submodule:

  git submodule update --init --recursive


-- Configuring incomplete, errors occurred!
See also "D:/SoftwareDev/mumble/mumble/build/CMakeFiles/CMakeOutput.log".
See also "D:/SoftwareDev/mumble/mumble/build/CMakeFiles/CMakeError.log".

d:\SoftwareDev\mumble\mumble\build>
```
the 3rdparty/opus directory is empty as is the celt-0.7.0-src directory.  i have o idea about the boost warnings.  been working on this for about 6 hours now and have to quit for the night.  am i missing something or have the tools not been updated for building 1.4.0 yet?

**Comment by davidebeatrici** [comment]
Run `git submodule update --init --recursive`.

**Comment by k1ttt-remote** [comment]
Hmmm, I thought I did that once… maybe I was in the wrong directory because this time it seems to have done something useful and the cmake generator got farther… I did take the ice directory out of the command line but it seems to have given an error related to it anyway:

 

d:\SoftwareDev\mumble\mumble\build>cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=c:/users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake"  "-DCMAKE_BUILD_TYPE=Release" ..

-- Using Win7 as the oldest supported Windows version

-- ##################################################

-- Mumble version:  1.4.0

-- Architecture:    64bit

-- Build type:      Release

-- ##################################################

-- Qt5 component found: Core | Version: 5.15.1

-- Qt5 component found: Network | Version: 5.15.1

-- Qt5 component found: Xml | Version: 5.15.1

-- OpenSSL component found: Crypto

-- OpenSSL component found: SSL

-- Qt5 component found: Concurrent | Version: 5.15.1

-- Qt5 component found: Sql | Version: 5.15.1

-- Qt5 component found: Svg | Version: 5.15.1

-- Qt5 component found: Widgets | Version: 5.15.1

CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):

  New Boost version may have incorrect or missing dependencies and imported

  targets

Call Stack (most recent call first):

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)

  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)

  cmake/pkg-utils.cmake:79 (find_package)

  src/mumble/CMakeLists.txt:390 (find_pkg)

 

 

-- Boost component found: system | Version: 1.74.0

CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):

  New Boost version may have incorrect or missing dependencies and imported

  targets

Call Stack (most recent call first):

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)

  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)

  cmake/pkg-utils.cmake:79 (find_package)

  src/mumble/CMakeLists.txt:390 (find_pkg)

 

 

CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):

  New Boost version may have incorrect or missing dependencies and imported

  targets

Call Stack (most recent call first):

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)

  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)

  cmake/pkg-utils.cmake:79 (find_package)

  src/mumble/CMakeLists.txt:390 (find_pkg)

 

 

CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):

  New Boost version may have incorrect or missing dependencies and imported

  targets

Call Stack (most recent call first):

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)

  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)

  cmake/pkg-utils.cmake:79 (find_package)

  src/mumble/CMakeLists.txt:390 (find_pkg)

 

 

CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):

  New Boost version may have incorrect or missing dependencies and imported

  targets

Call Stack (most recent call first):

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)

  C:/Users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake:586 (_find_package)

  cmake/pkg-utils.cmake:79 (find_package)

  src/mumble/CMakeLists.txt:390 (find_pkg)

 

 

-- Boost component found: thread | Version: 1.74.0

-- Disabling warnings for targets: xinputcheck

-- Opus version: 1.3.1

-- Looking for floor in m

-- Looking for floor in m - not found

-- Looking for intrin.h

-- Looking for intrin.h - found

-- Check SIMD support by compiler

-- Looking for xmmintrin.h

-- Looking for xmmintrin.h - found

-- Looking for emmintrin.h

-- Looking for emmintrin.h - found

-- Looking for smmintrin.h

-- Looking for smmintrin.h - found

-- Looking for immintrin.h

-- Looking for immintrin.h - found

-- Performing Test AVX_SUPPORTED

-- Performing Test AVX_SUPPORTED - Success

-- The following features have been enabled:

 

* STACK_PROTECTOR, Use stack protection

* FLOAT_API, compile with the floating point API (for machines with float library)

* X86_MAY_HAVE_SSE, does runtime check for SSE1 support

* X86_MAY_HAVE_SSE2, does runtime check for SSE2 support

* X86_MAY_HAVE_SSE4_1, does runtime check for SSE4_1 support

* X86_MAY_HAVE_AVX, does runtime check for AVX support

* X86_PRESUME_SSE, assume target CPU has SSE1 support

* X86_PRESUME_SSE2, assume target CPU has SSE2 support

 

-- The following features have been disabled:

 

* USE_ALLOCA, Use alloca for stack arrays (on non-C99 compilers)

* CUSTOM_MODES, Enable non-Opus modes, e.g. 44.1 kHz & 2^n frames

* BUILD_PROGRAMS, Build programs

* FIXED_POINT, compile as fixed-point (for machines without a fast enough FPU)

* X86_PRESUME_SSE4_1, assume target CPU has SSE4_1 support

* X86_PRESUME_AVX, assume target CPU has AVX support

 

-- Disabling warnings for targets: opus

-- Disabling warnings for targets: celt

-- Disabling warnings for targets: speex

-- Disabling warnings for targets: rnnoise

-- Qt5 component found: LinguistTools | Version: 5.15.1

-- Qt5 component found: Sql | Version: 5.15.1

-- File: D:/SoftwareDev/mumble/mumble/build/src/murmur/murmur_autogen

-- Qt5 component found: Widgets | Version: 5.15.1

CMake Error at cmake/pkg-utils.cmake:87 (message):

  Ice component not found: Ice

Call Stack (most recent call first):

  src/murmur/CMakeLists.txt:267 (find_pkg)

 

 

-- Configuring incomplete, errors occurred!

See also "D:/SoftwareDev/mumble/mumble/build/CMakeFiles/CMakeOutput.log".

See also "D:/SoftwareDev/mumble/mumble/build/CMakeFiles/CMakeError.log".

 

d:\SoftwareDev\mumble\mumble\build>

 

 

 

 

David Robbins K1TTT
e-mail:  <mailto:k1ttt@arrl.net> mailto:k1ttt@arrl.net
web:  <http://wiki.k1ttt.net/> http://wiki.k1ttt.net
AR-Cluster node:  <telnet://k1ttt.net:7373/> telnet://k1ttt.net:7373

**Comment by davidebeatrici** [comment]
Unfortunately email replies do not support markdown, I'm going to format the relevant output here:

```
cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=c:/users/k1ttt/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=Release" ..

...

CMake Error at cmake/pkg-utils.cmake:87 (message):

  Ice component not found: Ice

Call Stack (most recent call first):

  src/murmur/CMakeLists.txt:267 (find_pkg)
 ```

You have to specify `-Dserver=OFF`.

**Comment by k1ttt-remote** [comment]
Ah, that’s better… it would be good if that option was listed in the cmake generator options.

 

Any idea why the ice component won’t install?

 

I’m just glad I’m not trying this on my old machine, it would be next week before I would get even this far.  Ok, 1.4.0 built and work, thanks for the help… now to find that one little change I want to try!  Tomorrow.

 

David Robbins K1TTT
e-mail:  <mailto:k1ttt@arrl.net> mailto:k1ttt@arrl.net
web:  <http://wiki.k1ttt.net/> http://wiki.k1ttt.net
AR-Cluster node:  <telnet://k1ttt.net:7373/> telnet://k1ttt.net:7373

**Comment by davidebeatrici** [comment]
The folder to copy is https://github.com/mumble-voip/mumble/tree/master/helpers/vcpkg/ports/zeroc-ice, not https://github.com/mumble-voip/ice.

**Comment by Krzmbrzl** [comment]
> it would be good if that option was listed in the cmake generator options.

A list of all cmake options can be found here: https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/cmake_options.md

As you can see there are quite a few and therefore we can't all list them in the instructions for the static build :point_up:

**Comment by k1ttt-remote** [comment]
Ah, now I’m awake and understanding this a bit more… the reason the ice wouldn’t build from the script was that the script doesn’t define  PSScriptRoot and seems to assume that the mumble source root directory is at the same directory as vcpkg so using the path  $PSScriptRoot/../../helpers/vcpkg/ports/zeroc-ice to copy the zeroc-ice files couldn’t work.  I manually copied them and now it looks like zeroc-ice is building properly.

 

 

 

David Robbins K1TTT
e-mail:  <mailto:k1ttt@arrl.net> mailto:k1ttt@arrl.net
web:  <http://wiki.k1ttt.net/> http://wiki.k1ttt.net
AR-Cluster node:  <telnet://k1ttt.net:7373/> telnet://k1ttt.net:7373

**Comment by Krzmbrzl** [comment]
I assume you are referring to this line?
https://github.com/mumble-voip/mumble/blob/4b2d3465155b589b812f4bc7abca36e945cb28ff/scripts/vcpkg/get_mumble_dependencies.ps1#L58

> seems to assume that the mumble source root directory is at the same directory as vcpkg so using the path  $PSScriptRoot/../../helpers/vcpkg/ports/zeroc-ice to copy the zeroc-ice files couldn’t work.

From my understanding this shouldn't be the case. The script only assumes that it hasn't been moved manually...

And why should we have to define `PSScriptRoot`? Shouldn't this be automatically provided by PowerShell?

**Comment by k1ttt-remote** [comment]
Unfortunately  PSScriptRoot is not defined, at least not in the latest win10 version ISE editor/debugger.  

 

The other problem is that in https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_static.md you go through installing vcpkg first and don’t mention cloning the mumble project till later… then I had to fail building mumble to get the message about doing the “git submodule update --init --recursive” which finally gets the zeroc-ice fixes so that the copy from $PSScriptRoot/../../helpers/vcpkg/ports/zeroc-ice has the files to copy to fix the vcpkg setup, but only if PSScriptRoot pointed to probably the build directory under mumble, or is empty and the mumble and vcpkg directories are in the same directory.

 

 

David Robbins K1TTT
e-mail:  <mailto:k1ttt@arrl.net> mailto:k1ttt@arrl.net
web:  <http://wiki.k1ttt.net/> http://wiki.k1ttt.net
AR-Cluster node:  <telnet://k1ttt.net:7373/> telnet://k1ttt.net:7373

**Comment by Krzmbrzl** [comment]
I guess the fact that you have to clone the repo is implicitly assumed to be a per-requisite for the whole process. Explicitly stating it probably doesn't hurt though :thinking:

**Comment by MarKat123** [comment]
> Run `git submodule update --init --recursive`.

I ran into the same thing and your reply above seems to work - thanks

**Comment by Krzmbrzl** [comment]
I also extended the description in https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/README.md to include the submodule step after cloning the repo.

**Comment by Merkaber** [comment]
Since I am considering contributing to this project, I followed the installation instructions. I ran into this problem and could solve it by placing the script into the cloned directory, e.g. `C:\Users\Merkaber\Documents\dev\oss_projects\mumble\helpers\vcpkg\get_mumble_dependencies.ps1`.

**Comment by Merkaber** [comment]
Never mind, I didn't realize it was in the `/scripts` folder. I just copied and pasted it from github and tried to execute it within some unrelated folder, which of course could not work.

**Comment by Krzmbrzl** [comment]
Ah okay, I see :+1:
