### ISSUE TITLE
Mumble as a library

### ISSUE THREAD

**Issue by olivier-vr** [mumble-voip/mumble#4609]
**Context**
Integration in game engines such as Unity & Unreal.

**Describe the feature you have in mind**
A library version of Mumble that can be integrated in other programs.

**Additional context**
Hi there,

I'm working for Dreamscape Immersive, a company doing location based VR. We are building virtual reality experiences which allow up to six people to simultaneously explore a virtual 3D environment.

We're looking for a high quality VOIP solution and Mumble looks like a great choice. However we would like it to be build in our experiences rather than running in a separate process. But we've only found an outdated Mumble fork that looked like an attempt to make Mumble available as a library.

We're using Unity and Unreal for building our experiences. Have you guys already considered making Mumble available as an asset/plugin for those engines? If so we would be interested to contribute to this effort.

Thank you,

Olivier

**Comment by Krzmbrzl** [comment]
We discussed this topic not too long ago (part of the discussion in #4195). We came to the conclusion that we want to separate the frontend (UI related) and the backend (the core functionality) and by doing so this would then also allow us to provide a Mumble library (the backend) which could then be used by 3rdParty frontends.

So yeah: We're definitely aiming for this to happen. Unfortunately we didn't find the time yet to start working on that (We are currently busy trying to push 1.4.0 towards a release in the foreseeable future).

> Have you guys already considered making Mumble available as an asset/plugin for those engines?

To my knowledge we did not discuss that yet. Given the current state of the code (entanglement of frontend and backend and tight dependence on Qt), I don't think that as it is, this would be a viable option (at least I don't see how that'd work. But then again I don't have a whole lot of experience with these engines).
I think however that once we have separated out the backend functionality, creating such plugins should be more or less straight forward and I also think that I can speak for the team as a whole by saying that we would definitely see value in such plugins :)

**Comment by olivier-vr** [comment]
Hi @Krzmbrzl, thanks for your quick reply!
We're going to evaluate on our side if we want to commit to making a Mumble library.
Have a nice day!

**Comment by StarGate01** [comment]
@olivier-vr  Hi, I am working on building the mumble client implementation of the GTA FiveM mod (https://github.com/citizenfx/fivem) as a standalone library, due to the lack of any good c++ Mumble libraries with positional audio support. It is still a pretty young project, and the library is far from production ready, but it is promising: https://github.com/StarGate01/FiveMumblePatchset (also see: https://forum.cfx.re/t/building-components-voip-mumble-out-of-tree-as-a-library/1845811/4) .

Feel free to contact me for any questions.
