### ISSUE TITLE
Confirm Transifex forced-licensing issues and decide on alternatives

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#4614]
@comradekingu in https://github.com/mumble-voip/mumble/issues/1180#issuecomment-716673233 mentions Transifex supposedly forces you to agree to relicense everything you contributed on the platform retroactively. They have concerns about or do not want to share this data for the Transifex global translation database (used I presume primarily for translation suggestions).

# Confirm Transifex Issues

First we should confirm these issues. Check on the license and what Transifex forces you to agree to by using the service. If this user has concerns so will others, so this arguably is a critical issue for our translations.

# Alternative Services

If we decide to switch, we have to decide to what.

## [Crowdin](https://crowdin.com/)

A while ago I mentioned on IRC how I was very positively impressed by crowdin. 

They provide a free (hosted) option for open source projects ([pricing](https://crowdin.com/pricing)).

> Crowdin for Open Source
> 
> We support the open source community. If you're building awesome non-profit projects that could use the power of Crowdin, we're happy to help with this free option. Make your content multilingual to reach a global audience.

We will have to check their licensing approach as they provide similar cross-project suggestions to Transifex (plus more with machine translation?).

## [Weblate](https://weblate.org/en/)

Weblate is an open source solution that was suggested, which looks good. [features](https://weblate.org/en/features/) 

We would have to self-host as the free for open source hosted solution is only for one project (we currently host two with the iOS app as a second one).

I would rather not have another self-hosted service for our team to manage.

**Comment by Krzmbrzl** [comment]
> we currently host two with the iOS app as a second one

Well if we are realistic the iOS app is dead and therefore does not need to migrate to the new platform. The existing translations can stay on Transifex for the time being (imo) :shrug:

**Comment by Krzmbrzl** [comment]
I think the relevant parts of Transifex's [terms of service](https://www.transifex.com/legal/terms/) are (highlighting mine):

### Your Words & Your Privacy

By using the Services, you provide us with information, files, and folders that you submit to Transifex (together, “your words”). **You retain full ownership of your words, and Transifex has no ownership rights in your words. These Terms do not grant us any rights to your words or intellectual property except for the limited rights that are needed for Transifex to run the Services, as explained below.**

We may need your permission to do things you ask us to do with your words, for example, hosting your files, or sharing them at your direction. This includes product features visible to you, for example, image thumbnails or document previews. It also includes design choices we make to technically administer our Services, for example, how we redundantly backup data to keep it safe. You give us the permissions we need to do those things solely to provide the Services. This permission also extends to trusted third parties we work with to provide the Services, for example, RackSpace, which provides our storage space (again, only to provide the Services).

To be clear, aside from the rare exceptions we identify in our Privacy Policy, **no matter how the Services change, we will not share your content with others for any purpose unless you direct us to**. How we collect and use your information generally is also explained in our Privacy Policy.

You are solely responsible for your conduct, the content of your words and files, and your communications with others while using the Services. For example, it is your responsibility to ensure that you have the rights or permission needed to comply with these Terms.  You grant Transifex a non-exclusive, world-wide, perpetual, royalty-free, irrevocable, sublicensable and transferable license to use your words for purposes of performing the Services. You agree to indemnify Transifex for any third party claims, demands or losses arising as a result of your failure to obtain all such necessary rights, permissions and authorizations.

We may choose to review public content for compliance with our community guidelines, but you acknowledge that Transifex has no obligation to monitor any information on the Services. We are not responsible for the accuracy, completeness, appropriateness, or legality of files, user posts, or any other information you may be able to access using the Services.

### Sharing Your words

The Services provide features that **allow you to share** your words with others or to make your words public. There are many things that users may do with those words (for example, copy it, modify it, re-share it). Please consider carefully what you choose to share or make public. Transifex has no responsibility for that activity.

----

I did not check the Privacy policy yet but to me it seems that Transifex explicitly states that they will not (can not) use your translations in any way unless you give explicit permission :thinking:

**Comment by Kissaki** [comment]
> > we currently host two with the iOS app as a second one
> 
> Well if we are realistic the iOS app is dead and therefore does not need to migrate to the new platform. The existing translations can stay on Transifex for the time being (imo) 🤷

I would be fine with that.

**Comment by Kissaki** [comment]
I did not check full docs yet either, but what you quoted is entirely reasonable and even necessary for them to even allow us the basic translation functionality.

**Comment by comradekingu** [comment]
@Krzmbrzl Boy did you get conned. Let's read what it actually says, keeping in mind what it tries to say, by the words it elects to put to use.

> "Rights to your words or intellectual property, _except_ (operative word) "rights needed for Transifex to run the Services"

There is an exception, double negative

"not share your content with others, _unless_ (operative word) you direct us to"

4x negative

> "The services (remember "rights needed for Transifex to run the Services"?) provide features … make your words public." "Many things users may do with those words" "copy, modify, re-share it".

_may_. Look for the word "may" in documents such as these. Keep reading till there is a clause thrown in with a bunch of other stuff, that is where the payload is.
What this all meant is you are (by deduction) sharing words, and on the premise of that being part of what operates the services, the "limited rights" include "copying, modifying, and re-sharing".

And now, for the "aside from the rare exceptions we identify in our Privacy Policy" "will not share your content with others" "unless you direct us to". That sure _sounded_ nice…

https://www.transifex.com/legal/privacy/

> We may collect your‎ name, email address, phone number, username, demographic information (such as your occupation), as well as other information you directly give us on our website.

Collected.

> We may also receive Personal Information (for example, your email address) through other users, for example when they share something with you, invite you to their Transifex organization, or refer Transifex to you.
We may receive data about organizations, industries, website visitors, marketing campaigns, and other matters related to our business from affiliates, subsidiaries, partners, or others that we use to make our own information better or more useful. This data may be combined with other information we collect and might include aggregate level data.

Aggregated (read accumulated)

>We may collect information about the devices accessing our website and application.

> We use “cookies” (small data files that we transfer to your Device) and other tracking technologies to operate and administer the Site and the Service, analyze trends and improve your access to, and use of, our Service.

> We automatically collect information from the files and content you upload in the Service, including but not limited to files and images you upload, translations you submit, information related to translations, and comments.

"translations you submit" is "information".

We use your personal information for the following purposes:

    To operate, maintain, and improve our site, products, and services and ensure the provision of third party services integrated therein.
    To be able to provide to our users products and services they request from based on our contractual relationship. 

Sold

>    To link or combine user information with other personal information.

Tracked

> Our Legal Bases for Processing Your Personal Information
(one of many cited reasons)

> Delivering, developing and improving our services and products.
    Determining whether marketing campaigns are effective.
    Gaining insights from your behavior on our website in order to be able to offer you and third-party services and products which they find useful.
    To ensure smooth provision of third party services integrated in our site, products, and services.

Datalogged tracking

> We may share other information with consent with third parties when we have consent to do so.

Bingo

> We also may share personal data with certain marketing and advertising partners to send you promotional communications about Transifex.

> We may share aggregated or anonymized data. We may disclose or use aggregated or anonymized data for any purpose. An example would be for marketing, analytics or research purposes.

Sent

> We may share information from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data.

Honeypot

> We may share your personal information with third-party services integrated in our platform.

Which there are a lot of, look at all the scripts.

> If you are an european economic zone citizen you can 

This is where you usually find the dead giveaways if you have no time to comb through all the spaghetti language and tricks.

> ask us not to use your information for direct marketing purposes.
> You can object to us using your information for profiling you or making automated decisions about you.

And with that said, there is still the 
Terms
DMCA
Acceptable Use
Cookies policy
Security Policy

@Kissaki You aren't even wrong there, specifically. It however isn't "entirely reasonable" in isolated fashion :)

https://hosted.weblate.org/legal/terms/ is the Weblate equivalent, and if that is somehow unreasonable in any way, it can be self-hosted.
