### ISSUE TITLE
Add links to the commit guidelines and build documentation.

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4622]
Add links for: https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md and https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions in README.md.

**Comment by Krzmbrzl** [comment]
The build instructions are already linked

**Comment by toby63** [comment]
> The build instructions are already linked

Oh sry, must have readover that.

Thank you for fixing, will be useful I guess.

**Comment by Krzmbrzl** [comment]
No problem :) 
Thx for bringing it up. In the future you could also just go ahead and create a PR for it. The README file should be easily editable directly in the GitHub UI anyways :point_up:

**Comment by toby63** [comment]
> In the future you could also just go ahead and create a PR for it. The README file should be easily editable directly in the GitHub UI anyways :point_up:

I will consider that, but in this case I thought you wanted to formulate that yourself.
