### ISSUE TITLE
Readme.md - Add section "Usage" or similar

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4623]
**Context**
Followup to #4622.

I think you could put the instructions for each Operating System into a new Main Section, maybe called `Usage` or something similar.
This way it has a better structure.

**Comment by Krzmbrzl** [comment]
I agree. Ultimately though I would like to move these instructions into separate files that can then be linked to from the README (as is done for the build instructions) :point_up:

**Comment by toby63** [comment]
I will probably add a pull request for this. Just so there is no double work.

**Comment by Krzmbrzl** [comment]
Usage guides shouldn't be written here on GitHub. They should be created on our Website (or until the docs have moved there: in our wiki) and then we can link to that from the README file.
