### ISSUE TITLE
Disable Text-To-Speech by default

### ISSUE THREAD

**Issue by peylight** [mumble-voip/mumble#4626]
**Context**
Hi,
Please disable Text-To-Speech by default installation.
There are many languages that Text-To-Speech are not supported so when we try to type other language but by English keyboards, that will be inconvenient.
Also, it is just a feature that players can enable it, there are many new mumble users that they don't know how mumble is working and scratch them when they see Text-To-Speech in the middle gaming.
Also it is difficult to teach every players to how disable Text-To-Speech. We trying to increase Mumble's popularity but this feature decrease it.

**Describe the feature you have in mind**
Disable Text-To-Speech by default installation.

**Describe alternatives you've considered**
Remove Text-To-Speech feature.

**Comment by Krzmbrzl** [comment]
I assume that the majority of users will not want TTS enabled (I have no evidence for that though). Thus making this an opt-in feature seems reasonable to me :+1:

**Comment by Krzmbrzl** [comment]
@peylight this is the line that needs to be modifed:
https://github.com/mumble-voip/mumble/blob/0af10cdd959b664dc010d55afa3b9218d716958d/src/mumble/Settings.cpp#L297
Do you want to create a PR yourself?

**Comment by peylight** [comment]
@Krzmbrzl it's fixed now.
