### ISSUE TITLE
Wildcard Certificate Problem

### ISSUE THREAD

**Issue by Nisutec** [mumble-voip/mumble#4643]
**Describe the bug**
I have tried to use a wildcard certificate for my mumble server, but it does not work. The Server starts with the certificate without any problems, but the clients gets a warning message on joining that the certificate cannot be validated. The Certificate is valid and work without any problems on other services like a web server how I can fix this problem with the mumble server.

**Steps to Reproduce**
I have configured the following settings in the `mumble-server.ini`:
```
sslCert=<path to .cert file>
sslKey=<path to .key file>
```

**Expected behavior**
The possibility that the clients can validate the certificate.

**Screenshots**
<details>
  <summary>Client Warning Message</summary>
  
  ![Client Warning Message](https://p52.p0.n0.cdn.getcloudapp.com/items/GGu2JPNy/4d52b4fd-a33e-4653-8450-b652d2175d2d.png?v=4188a37deee8e46ec9d6c23299e2ccf5)
</details>
<details>
  <summary>Client Server Information</summary>
  
  ![Client Server Information](https://p52.p0.n0.cdn.getcloudapp.com/items/z8u4lAZj/13555667-30a2-4400-8bde-518842d3831c.png?v=81edd6b873882327227070f0a8381302)
</details>
<details>
  <summary>Certificate Information</summary>
  
  ![Client Server Information](https://p52.p0.n0.cdn.getcloudapp.com/items/yAuZA8WZ/db77faa9-ae88-43de-b4b2-5dde8eab6f2a.png?v=85fa37e9b8ee2ede29eb9ff934c7915a)
</details>

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version: Murmur 1.3

**Comment by davidebeatrici** [comment]
I assume you figured out what the issue was, could you confirm?

**Comment by Nisutec** [comment]
> 
> 
> I assume you figured out what the issue was, could you confirm?

Yes i have found the setting sslCA in the wiki and this has solved my problem.

**Comment by davidebeatrici** [comment]
Excellent!
