### ISSUE TITLE
.dmg packages cannot be opened on old macOS versions (APFS unsupported)

### ISSUE THREAD

**Issue by Xansta** [mumble-voip/mumble#4655]
**Describe the bug**
The application won't install

**Steps to Reproduce**
1. Download Mumble 1.3.3
2. Open .dmg file
3. See error

**Expected behavior**
.dmg to open for installation

**Screenshots**
![Screen Shot 2020-12-25 at 11 17 09 AM](https://user-images.githubusercontent.com/35241832/103139573-36ec4700-46a3-11eb-9799-ecf572ae8682.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.9.5
 - Version: Mumble 1.3.3
<img width="321" alt="Screen Shot 2020-12-25 at 11 23 14 AM" src="https://user-images.githubusercontent.com/35241832/103139630-c560c880-46a3-11eb-998e-77e32b6a462c.png">

**Comment by Krzmbrzl** [comment]
According to [this article](https://deciphertools.com/blog/2017-10-02-no-mountable-file-systems/) this could mean that your download got corrupted. Could you try to delete the download and re-download it from our website?

**Comment by Xansta** [comment]
I tried a couple of times and still got the message
![Screen Shot 2020-12-25 at 12 23 37 PM](https://user-images.githubusercontent.com/35241832/103140457-4fad2a80-46ac-11eb-82a0-e821414222fd.png)

**Comment by Xansta** [comment]
This is the link I'm using for download:
https://download.mumble.com/en/mumble-1.3.3.dmg

**Comment by Xansta** [comment]
Following the instructions on the referenced article, I got this:
```Davids-MacBook-Pro-4:Downloads plaindavid$ curl -O https://download.mumble.com/en/mumble-1.1.1.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    180      0 --:--:-- --:--:-- --:--:--   180
Davids-MacBook-Pro-4:Downloads plaindavid$ hdiutil attach -verbose /Users/plaindavid/Downloads/mumble-1.3.3\(3\).dmg 
Initializing…
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CMacBinaryEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CAppleSingleEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CEncryptedEncoding
DIFileEncodingInstantiatorProbe: interface  0, score      900, CUDIFEncoding
DIFileEncodingNewWithBackingStore: CUDIFEncoding
DIFileEncodingNewWithBackingStore: instantiator returned 0
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CSegmentedNDIFEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CSegmentedUDIFEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CSegmentedUDIFRawEncoding
DIDiskImageInstantiatorProbe: interface  0, score     1000, CUDIFDiskImage
DIDiskImageInstantiatorProbe: interface  1, score        0, CSparseBundleDiskImage
DIDiskImageInstantiatorProbe: interface  2, score        0, CSparseDiskImage
CRawDiskImage: data fork length 0x000000000114A62D (18130477) not a multiple of 512.
DIDiskImageInstantiatorProbe: interface  3, score     -100, CRawDiskImage
DIDiskImageInstantiatorProbe: interface  4, score        0, CDARTDiskImage
DIDiskImageInstantiatorProbe: interface  5, score        0, CDiskCopy42DiskImage
DIDiskImageInstantiatorProbe: interface  6, score    -1000, CNDIFDiskImage
DIDiskImageInstantiatorProbe: interface  8, score     -100, CShadowedDiskImage
DIDiskImageInstantiatorProbe: interface  9, score    -1000, CCFPlugInDiskImage
DIDiskImageInstantiatorProbe: interface 10, score     -100, CWrappedDiskImage
DIDiskImageNewWithBackingStore: CUDIFDiskImage
DIDiskImageNewWithBackingStore: instantiator returned 0
Verifying…
Verification completed…
Error 0 (Undefined error: 0).
expected   CRC32 $D5B62999
Attaching…
DI_kextWaitQuiet: about to call IOServiceWaitQuiet...
DI_kextWaitQuiet: IOServiceWaitQuiet took 0.000002 seconds
2020-12-25 12:36:10.741 diskimages-helper[74849:4513] DIHelperHDID serveImage: attaching drive
{
    autodiskmount = 1;
    "hdiagent-drive-identifier" = "80546523-0B3F-49D7-A3BB-170E1F8CEBD1";
    "unmount-timeout" = 0;
}
2020-12-25 12:36:10.743 diskimages-helper[74849:4513] DIHelperHDID serveImage: connecting to myDrive 0x4E0B
2020-12-25 12:36:10.743 diskimages-helper[74849:4513] DIHelperHDID serveImage: register _readBuffer 0x10da6f000
2020-12-25 12:36:10.743 diskimages-helper[74849:4513] DIHelperHDID serveImage: activating drive port 19467
2020-12-25 12:36:10.743 diskimages-helper[74849:4513] DIHelperHDID serveImage: set cache enabled=TRUE returned SUCCESS.
2020-12-25 12:36:10.743 diskimages-helper[74849:4513] DIHelperHDID serveImage: set on IO thread=TRUE returned SUCCESS.
Volume check completed…
Mounting…
2020-12-25 12:36:10.752 diskimages-helper[74849:2a03] -remountReturningDictionary: detaching because no mountable filesystems.
Attaching…
Error 112 (no mountable file systems).
Finishing…
DIHLDiskImageAttach() returned 112
hdiutil: attach failed - no mountable file systems
Davids-MacBook-Pro-4:Downloads plaindavid$ 
```

**Comment by davidebeatrici** [comment]
https://dl.mumble.info/stable/Mumble-1.3.3.dmg

**Comment by Xansta** [comment]
And finally, point 4 of the article points out that versions of MacOS earlier that 10.12 (which mine is: 10.9) can't open the new apple filing system. I don't suppose anyone has a more backwards compatible packaging method for those of us that have not upgraded to newer MacOS version?

**Comment by Xansta** [comment]
Thanks for the alternative link, @davidebeatrici 
It gave me the same error as the others

**Comment by Xansta** [comment]
Merry Christmas everyone! I appreciate you responding to my queries on such a day as today

**Comment by davidebeatrici** [comment]
> Thanks for the alternative link, @davidebeatrici

It's actually the official link.

> Merry Christmas everyone! I appreciate you responding to my queries on such a day as today

Thanks, you too!

> And finally, point 4 of the article points out that versions of MacOS earlier that 10.12 (which mine is: 10.9) can't open the new apple filing system. I don't suppose anyone has a more backwards compatible packaging method for those of us that have not upgraded to newer MacOS version?

This is how we build the `.dmg` package:
https://github.com/mumble-voip/mumble/blob/6625f9a877d0b107c05a32c0c4189843965a59a7/macx/scripts/osxdist.py#L246-L261

Looks like older macOS versions want `UDZO` instead: https://github.com/zulip/zulip-desktop-legacy/blob/master/admin/mac/create-dmg.sh

**Comment by Krzmbrzl** [comment]
> This is the link I'm using for download:
https://download.mumble.com/en/mumble-1.3.3.dmg

As Davide already pointed out: this is a 3rd-party website that we are not involved with at all. To download from our website, visit https://www.mumble.info/downloads/

> Merry Christmas everyone! I appreciate you responding to my queries on such a day as today

Merry Christmas to you, too :)

> Looks like older macOS versions don't support APFS and expect HFS+ instead:

Ah yes that's actually also mentioned in https://deciphertools.com/blog/2017-10-02-no-mountable-file-systems/ which I linked above.
It also lists a workaround for it. Might be worth a try :point_up:

**Comment by davidebeatrici** [comment]
I attached an HFS+ package, please let me know whether it works.

[Mumble-1.3.3_HFS+.zip](https://github.com/mumble-voip/mumble/files/5742312/Mumble-1.3.3_HFS%2B.zip)

**Comment by Xansta** [comment]
I was able to download and install, thank you. Now I've got other issues. However, I'll write those up in a separate thread

**Comment by zeroheure** [comment]
Same issue here, Mac OSX 10,11.10 and Mumble 1.3.4 and 1.3.3. Temporarily solved with Mumble 1.2.18.
Please reopen this bug to help other users.

**Comment by Krzmbrzl** [comment]
>  Mumble 1.3.4

That's impossible since there are no available binaries for Mac yet.

Where did you get the binaries from? And did you try (re)downloading the one provided at https://www.mumble.info/downloads/ ?

**Comment by zeroheure** [comment]
@Krzmbrzl Sorry, it was 1.3.3 and 1.3.2 coming from mumble.info and Github. We tried to download several times, as I suspected a corrupted file. 
Mounting the dmg file, gives exactly the same error as the report (no file system). Probably lack of support for the new Apple File System. Mumble 1.2.18 package works well though. Did you changed your packaging script ?

My little son report the problem by phone, so I don't have a lot of informations. As soon he will finish to play with Minecraft , I will try to instruct him how to dive into the problem.

**Comment by Krzmbrzl** [comment]
Which version of macOS are you (or your son) using?
I think we had a report on IRC before that reported this to not work due to a too old version of mscOS that does not support the used file format :thinking:

**Comment by zeroheure** [comment]
Mac OSX 10.11.10

**Comment by Krzmbrzl** [comment]
Ah lol I just realized that the report I mentioned was not on IRC but was.in fact this very issue. Given your macOS version I assume the issue is the same. See Davide's post in this issue for a build with the older filesystem and please try that to see if that installs :point_up:

**Comment by zeroheure** [comment]
Yes it works well with Davide file. My son sent the Terminal output of `hdiutil` on mumble-1.3.3.dmg and it is definitely the APFS problem. Will you be able to package next versions with both APFS and HFS+ ?
I heavily suggest to keep this report open or to write advice on release notes, as I saw other Apple users unable to understand what happened (many of them are kids).
Anyway, thanks for your time.

**Comment by Krzmbrzl** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/MacOS_version_history#Releases) has gone out of support in October 2019. Thus I can't promise that we'll provide backwards compatibility for it.
If it turns out to be easily doable however, I guess we might as well do it.

If we chose that we can't provide the older version, then we'll definitely add a note on the release page :point_up: 

@davidebeatrici how much work was it to create the HFS+ version of the Apple binary? And what did you have to do in order to get it?

**Comment by davidebeatrici** [comment]
```zsh
hdiutil attach Mumble-1.3.3.dmg
hdiutil create -srcfolder "/Volumes/Mumble 1.3.3" -format UDBZ -fs hfs+ -volname "Mumble 1.3.3"
hdiutil create -srcfolder "/Volumes/Mumble 1.3.3" -format UDBZ -fs hfs+ -volname "Mumble 1.3.3" Mumble-1.3.3_HFS+.dmg
hdiutil unmount "/Volumes/Mumble 1.3.3"
```

As simple as that.

**Comment by Krzmbrzl** [comment]
Ah okay. I guess we should be able to provide these builds for older Macs then :+1:

**Comment by zeroheure** [comment]
Thanks everyone.

Please reopen the bug to help current Mac users to find the HFS package.

**Comment by davidebeatrici** [comment]
https://dl.mumble.info/stable/Mumble-1.3.3-HFS+.dmg

**Comment by Krzmbrzl** [comment]
The HFS+ binary is now available on our website.

**Comment by zeroheure** [comment]
Thanks a lot @davidebeatrici and @Krzmbrzl  ! 
It is a very good proof for my son to understand why bug reports are important.
