### ISSUE TITLE
mumble_*.qm files are not used

### ISSUE THREAD

**Issue by Ledarium** [mumble-voip/mumble#4657]
**Describe the bug**
Wiki page https://wiki.mumble.info/wiki/Language_Translation mentions that in order to test translation: 

> Go to your Mumble folder and put the mumble_*.qm file inside of it. Now start Mumble and make sure that your language is set in the user interface section of the Mumble configuration. The language should be displayed in Mumble after you restart the client.

I have tried placing mumble_ru.qm file into `~/.local/share/Mumble/`, `~/.local/share/Mumble/Mumble`, `~/.config/Mumble/`. Mumble does not acknowledge this file in any of these locations and uses internal translation.
That is what I see in log when running compiled Mumble from `80de4268`:
```
<W>2020-12-26 13:15:54.757 Theme: "Mumble"
<W>2020-12-26 13:15:54.757 Style: "Lite"
<W>2020-12-26 13:15:54.757 --> qss: ":themes/Mumble/Lite.qss"
<W>2020-12-26 13:15:54.757 Locale is "ru" (System: "en_US")
```

Is the wiki page outdated and this feature is not supported, am I doing something wrong, or is this a bug?

**Expected behavior**
`mumble_*.qm` translation files should be picked and used in interface

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: Mumble 1.3.3, also tried building from git commit `80de4268` - same behavior.

**Comment by Krzmbrzl** [comment]
Did you try using the current master branch? I think if you just use the defaults, it should already include localization support :thinking:

**Comment by Ledarium** [comment]
> Did you try using the current master branch?

**Comment by Krzmbrzl** [comment]
So in a regular build using cmake the stribgs in the UI are not translated? That's odd :thinking:

**Comment by Ledarium** [comment]
Strings are translated, but translation is not picked up from `mumble_*.qm` files, but from `*.ts` translation files from `src/mumble`.

**Comment by davidebeatrici** [comment]
`*.ts` files are never used directly, they are compiled into `*.qm` binaries.

The binaries are "baked" into the executable, just like the notification sounds.

We should probably add a new folder called "translations" or "languages", for custom `*.qm` files.

**Comment by itsTurnip** [comment]
This method seems to be working fine at Windows 10. I've used Russian translations from transifex, placing it as `mumble_ru.qm` in binary folder.

**Comment by Krzmbrzl** [comment]
> Strings are translated, but translation is not picked up from mumble_*.qm files, but from *.ts translation files from src/mumble.

@Ledarium 
Okay so wait a sec. You are building Mumble from source, right? And additionally you create a separate .qm file that you want to be loaded by Mumble, but Mumble always defaults to the internal translations that it built from the .ts files during compilation?
Which language are you trying to use? And is this language also translated as a .ts file? I could imagine that Mumble prefers the internal one if present. In order to verify that, you could (temporarily) remove the respective .ts file and perform a clean build and check with that :thinking:

**Comment by Ledarium** [comment]
@Krzmbrzl that is correct. The problem was that I have been placing `mumble_ru.qm` file in wrong directories :D When I had put it alongside compiled mumble executable as mentioned by @itsTurnip , it had worked fine. I can test my translation now!

One more thing before closing the issue. I think it should be mentioned in the wiki that `.qm` translation files should be placed in the same directory as the executable. I think it is not *that* obvious now: https://wiki.mumble.info/wiki/Language_Translation
> Go to your Mumble folder and put the mumble_*.qm file inside of it

**Comment by Krzmbrzl** [comment]
> The problem was that I have been placing mumble_ru.qm file in wrong directories :D

Ah :sweat_smile: :bulb: 

> I can test my translation now!

Perfect! :+1: 

>  I think it should be mentioned in the wiki that .qm translation files should be placed in the same directory as the executable.

Agreed. I added this information just now :point_up: 
It now reads:
> Go to your Mumble folder and place the mumble_*.qm file next to the Mumble executable (e.g. mumble.exe on Windows).
