### ISSUE TITLE
Client notifies "This server does not allow sending images." when pasting text in chatbox

### ISSUE THREAD

**Issue by woodkoodaa** [mumble-voip/mumble#4660]
**Describe the bug**
When pasting plaintext in chatbox, client notifies "This server does not allow sending images." before sending message.

**Steps to Reproduce**
1. Copy plaintext from notepad.
2. Go to chatbox
3. Paste text

**Expected behavior**
I expect text to be pasted and nothing else to happen.

**Screenshots**
[https://i.ibb.co/SwLShZ2/mumble-chat-paste-issue.png](https://i.ibb.co/SwLShZ2/mumble-chat-paste-issue.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble-1.4.0-2020-12-24-gdb4b6be-snapshot.winx64.msi

**Additional context**
Does not happen with stable 1.3.3.
Mumble server is compiled from master 26.12.2020.

**Comment by TerryGeng** [comment]
It may have something to do with the new "paste images into the chatbox" support in 1.4.0. Will investigate.

**Comment by TerryGeng** [comment]
Investigated. Commit https://github.com/mumble-voip/mumble/commit/3d2a196830e9a71590100594595d89591c048b06 breaks this. I think we need to consult @merua for more details.

**Comment by merua** [comment]
> I think we need to consult @merua for more details.

Oh sorry, my bad. You are right, thanks for fixing it!
