### ISSUE TITLE
Weird number in Server Info window

### ISSUE THREAD

**Issue by wfjsw** [mumble-voip/mumble#4670]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2220320/103520745-9c65e200-4eb2-11eb-90fa-0508133f435c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.3.3

**Comment by Krzmbrzl** [comment]
What is this about? :thinking:

**Comment by wfjsw** [comment]
Grr I screwed the UDP buffer pool up while debugging packet drops.

**Comment by Krzmbrzl** [comment]
Ah okay ^^
