### ISSUE TITLE
Improve CMake error “Did you install g++-multilib?”

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#4672]
CMake Error at overlay_gl/CMakeLists.txt:39 (message):
  Can't find the 32bit version of sys/cdefs.h - did you install g++-multilib?

Can we be more clear in the error message?
1. Which of the many g++-multilib's is needed?
(Yeah, my g++-multilib is installed, it's debian (stable), multilib version is 4:8.3.0-1)
2. The message might also include, for instance:
"Disable requirement with -Doverlay-xcompile=OFF or see build docs".

Debian Stable (Buster), with Backports available.
mkdir build && cd build && cmake ..

cmake's errors show:
```
/usr/bin/cc   -m32  -fPIE   -o CMakeFiles/cmTC_bd0b4.dir/CheckIncludeFile.c.o   -c /home/jaggz/src/mumble/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c                                 
/home/jaggz/src/mumble/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: sys/cdefs.h: No such file or directory
#include <sys/cdefs.h>                                                                      
          ^~~~~~~~~~~~~
```

**Comment by Krzmbrzl** [comment]
Impeoving the message is always a good thing. The issue is that I don't know whether any specific version is needed. For me there is only a single package called `g++-multilib`  in the repos (iirc) and installing that resolved all dependencies...

Documenting that this is only reauired for the cross-compilation of the overlay is probably a good idea in any case though :+1:

**Comment by Krzmbrzl** [comment]
This is the code part that needs changing:
https://github.com/mumble-voip/mumble/blob/38974e766499d88b1709dabae8908da8f76a4ded/overlay_gl/CMakeLists.txt#L34-L42

Other than mentioning that the dependency can be eliminated, do you have an idea on how you' rephrase the message?

**Comment by jaggzh** [comment]
Hmm. I didn't figure out which package works work (the plain one didn't). I
ended up using the option to disable it.

Here are the packages available with g++-multilib in their name:
https://packages.debian.org/search?keywords=g%2B%2B-multilib&searchon=names&suite=buster&section=all

I'm looking and asking around to find out how the plain package works --
like, if it's supposed to handle the local architecture AND install the
32-bit version.

Let's work on the message more once we know more about the problem I guess.
:)

**Comment by Krzmbrzl** [comment]
Apparently Ubuntu also offers a bunch of them:
https://packages.ubuntu.com/search?keywords=g%2B%2B-multilib&searchon=names&suite=groovy&section=all

There it seems to be enough to install the `g++-multilib` package. Just out of curiosity you could try and remove simply the error message from the cmake file and just check if it compiles. I hacked together the test for g++-multilib and was happy once it worked on Ubuntu. Maybe this quick and dirty check does not apply for Debian :shrug:
So please comment out the following line and try to rebuild with overlay-xcompile enabled
https://github.com/mumble-voip/mumble/blob/38974e766499d88b1709dabae8908da8f76a4ded/overlay_gl/CMakeLists.txt#L39

> Let's work on the message more once we know more about the problem I guess.
:)

Yes that sounds like a plan :D

**Comment by jaggzh** [comment]
That seems to have built (and runs) fine. I just used a plain cmake with no
options.
Hmm.. I do wonder about that test, and whether it's the debian package
that's weird (I didn't end up finding out anything), or the test method
itself.

# aptitude show g++-multilib
Package: g++-multilib
Version: 4:8.3.0-1
State: installed
Architecture: amd64
Depends: cpp (= 4:8.3.0-1), gcc-multilib (= 4:8.3.0-1), g++ (= 4:8.3.0-1),
        g++-8-multilib (>= 8.3.0-1~)
Conflicts: g++-multilib:i386
Provides: g++-multilib:amd64 (= 4:8.3.0-1)

...and for Package: g++-8-multilib:
Architecture: amd64
Uncompressed Size: 6,144
Depends: gcc-8-base (= 8.3.0-6), g++-8 (= 8.3.0-6), gcc-8-multilib (=
8.3.0-6),
        lib32stdc++-8-dev (= 8.3.0-6), libx32stdc++-8-dev (= 8.3.0-6)
Suggests: lib32stdc++6-8-dbg (>= 8.3.0-6), libx32stdc++6-8-dbg (>= 8.3.0-6)
Conflicts: g++-8-multilib:i386

...etc?

**Comment by Krzmbrzl** [comment]
> That seems to have built (and runs) fine. I just used a plain cmake with no
options.

Did you clean your build directory beforehand? Otherwise cmake caches the previously used `overlay-xcompile=OFF` option :point_up: 

> Hmm.. I do wonder about that test, and whether it's the debian package
that's weird (I didn't end up finding out anything), or the test method
itself.

I could easily imagine the test being flawed. As I said before, the test was developed in a pretty quick and dirty way ^^
