### ISSUE TITLE
vcpkg script for Windows fails with -CleanAfterBuild $true

### ISSUE THREAD

**Issue by ZeroAbility** [mumble-voip/mumble#4674]
**Describe the bug**
When running the vcpkg script for Windows with `-CleanAfterBuild $true` the script will fail while building `qt5-base`

**Steps to Reproduce**
1. Run: `./mumble/scripts/vcpkg/get_mumble_dependencies.ps1 -CleanAfterBuild $true`
2. The script has a build error and exits attempting to build `qt5-base`

**Expected behavior**
The script should run successfully

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.4.0

**Additional context**
The issue is related to the dependency `icu` which handles Unicode for Windows. An issue has been opened with the vcpkg team:
https://github.com/microsoft/vcpkg/issues/15488

**Comment by Krzmbrzl** [comment]
In the linked issue it was mentioned that maybe the issue is that we invoke vcpkg for each package separately instead of invoking it once with all packages we need, allowing it to determine the optimal order of the downloads.

This actually sounds like a promising solution...

**Comment by ZeroAbility** [comment]
I'm testing a revised script now. I'll submit a PR when possible.
