### ISSUE TITLE
Hide the password from log channel when connecting to server via a link

### ISSUE THREAD

**Issue by wfjsw** [mumble-voip/mumble#4680]
**Context**
When connecting a server via `mumble://` link the cleartext password would show up in logs. Some measure should be taken to hide this sensitive information from logs.

**Describe the feature you have in mind**
Scrub the password field with asterisks 

**Describe alternatives you've considered**
Instead of connect to server directly, prompt user to save the connection info to Favorites for later use.

**Comment by Krzmbrzl** [comment]
In which logs does the password appear as cleartext? On the server?

**Comment by wfjsw** [comment]
For example:

![image](https://user-images.githubusercontent.com/2220320/104199526-86cc5b80-5462-11eb-8c72-a7bccf379392.png)

**Comment by Krzmbrzl** [comment]
Am I correct in assuming that the password has been contained in the original link in plaintext already?

In that case I don't see a big problem in it also appearing in the console as the user can already read it out from the link provided to him/her :thinking: 
And the client logs are not saved (for all I know) and thus there should be no issue with that either :eyes: 

Could you elaborate on why you think this is an issue, please?

**Comment by wfjsw** [comment]
So I wanna create a better user experience by using a link on the website that helps you fill everything needed in one-click. The raw password won't show up unless holding on the link which is less likely to happen when screenshoting. However, it is much more likely to happen if user take a screenshot that contains his password in the log window while he actually have no idea what he has done.

**Comment by Krzmbrzl** [comment]
Fair enough.

I think in that case it's probably best (and easiest) to not log the URL used for connection in the first place :thinking:
