### ISSUE TITLE
Channel comment accessible through padlock icon only (if there is one)

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#4685]
To see the channel description, I need to click on the padlock(?) instead on the "comment" icon if there is one. If there is no padlock icon, it works clicking on the comment icon.

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you know where we handle the click-action for the comment? I can only find the code part in `UserModel` that sets the tooltip to a channel's description (and that is still working fine) :thinking:

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/82cfcb84a59b9b66dba0dbdf6d877fb8e2451813/src/mumble/UserView.cpp#L144-L208
