### ISSUE TITLE
Padlock icon is missing in the "help window"

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#4686]
**Steps to Reproduce**
1. Press Shift+F1 (cursor changes to Help icon)
2. Click on Padlock icon.
3. No description for the padlock icon.

**Comment by Krzmbrzl** [comment]
The associated code part is
https://github.com/mumble-voip/mumble/blob/ffb2b70b32558c4db0619ea22a7c6865fba58dc2/src/mumble/UserModel.cpp#L766-L780

And while we're at it, we can also add the new talking state introduced in #4322 to
https://github.com/mumble-voip/mumble/blob/ffb2b70b32558c4db0619ea22a7c6865fba58dc2/src/mumble/UserModel.cpp#L697-L711

**Comment by Krzmbrzl** [comment]
Furthermore the listener icon is also not explained in the what's this? help messages :point_up:
