### ISSUE TITLE
[Github] Automatically add the feature request label to feature requests

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4698]
That would make things a bit easier.

**Comment by Krzmbrzl** [comment]
Nah I prefer new issues not having any labels at all. That way there is a clear distinction between issues that have just been created and ones that have been processed by a maintainer.
Besides: Sometimes issues get created as feature request but end up being support issues or bug reports :shrug: 

If there are no contra-arguments, I'll close this issue :point_up:

**Comment by toby63** [comment]
Contra Argument is mainly that not all feature requests are labeled as such.

**Comment by Krzmbrzl** [comment]
This is due to them being old and unprocessed though. Thus this should not apply to newer issues.

**Comment by toby63** [comment]
> Thus this should not apply to newer issues.

If thats the case, then there is no problem.

**Comment by Krzmbrzl** [comment]
It is (at least as far as I am aware) :+1:
