### ISSUE TITLE
[1.4.0 snapshot] Logitech Gkeys not being read

### ISSUE THREAD

**Issue by ProjectPatatoe** [mumble-voip/mumble#4701]
**Describe the bug**
Logitech Gkeys are not being detected. 

**Steps to Reproduce**
I already have them setup from 1.3.3
1. update mumble
2. press G key
3. nothing happens

**Expected behavior**
G keys being read. 

**Desktop (please complete the following information):**
 - OS: Win10 20H2
 - Version: `1.4.0~2020-12-24~gdb4b6be~snapshot`

**Additional context**
I already tried rebinding them but they aren't being detected

**Comment by Krzmbrzl** [comment]
@davidebeatrici were there any changes to the shortcut code? I don't think so, right? Then maybe this could be a cmake issue where the ghelper or however it is named is not being included? :thinking:

**Comment by ProjectPatatoe** [comment]
mumble-g15-helper.exe is missing compared to 1.3.3. Is this what you are talking about?

**Comment by Krzmbrzl** [comment]
Yes exactly! :+1: 
Then this seems to be a build/release issue.

**Comment by Krzmbrzl** [comment]
@ZeroAbility is this related to how the installer gets packed?

**Comment by davidebeatrici** [comment]
The file is missing from the list:
https://github.com/mumble-voip/mumble/blob/4b36f0f9a7892d03fbac4f40f4862cfb3ab46504/installer/ClientInstaller.cs#L79-L107

**Comment by ZeroAbility** [comment]
Do you have the Logitech software installed for the device?

**Comment by davidebeatrici** [comment]
Please note that `g15-helper` is only needed for the LCD, G-Keys should work as long as you have Logitech's software installed (as @ZeroAbility said).

**Comment by ProjectPatatoe** [comment]
That's what I assumed about the G15 helper (which would be nice to actually not have running when I don't have a G15?). Yes I do have the Logitech software installed. I went straight from 1.3.3 working to 1.4.0 not working. Just confirmed again since 1.4.0 installed in the wrong location (already reported) and so I still have 1.3.3 installed.

**Comment by ZeroAbility** [comment]
The install location changed in 1.4.0 as did the installer. 1.3.3 should be removed first. Since it is already installed, you can remove it and repair the 1.4.0 install to fix the menu and desktop shortcuts. Or if you want to roll back to 1.3.3 you can remove 1.4.0 and repair 1.3.3.

**Comment by ProjectPatatoe** [comment]
I'm not concerned about the shortcuts. I'll not discuss that here since it's off topic.
No other changes to system including the Logitech software. 1.3.3 works, 1.4.0 doesn't detect.
I've already tried changing Logitech's mumble profile to the new mumble path but I am under the impression that they're only looking at executable name and not the entire path. I think this is the case since after pointing to 1.4.0, 1.3.3 still works.

**Comment by ZeroAbility** [comment]
It sounds like the change is not persisting in the Logitech software.
