### ISSUE TITLE
[1.4.0-snapshot] Unable to choose install location during install

### ISSUE THREAD

**Issue by ProjectPatatoe** [mumble-voip/mumble#4702]
**Describe the bug**
I used to be able to choose where I install mumble. Or at the least, install to previous location (which it did not)

**Steps to Reproduce**
Install/update mumble (while previous(1.3.3) still installed)

**Expected behavior**
able to choose install location or install to same location

**Desktop (please complete the following information):**
 - OS: Win10 20H2
 - Version: going from 1.3.3 to `1.4.0~2020-12-24~gdb4b6be~snapshot`

**Comment by Krzmbrzl** [comment]
@ZeroAbility how hard would it be to add this feature to the new installer?

**Comment by ZeroAbility** [comment]
@ProjectPatatoe please see this response in your other issue:
https://github.com/mumble-voip/mumble/issues/4701#issuecomment-762660029

>how hard would it be to add this feature to the new installer?

@Krzmbrzl  We would have to use a different UI type. This was also anticipated and the documentation would reflect that it will not have a path choice during release of 1.4.0. There should be minimal concern regarding file size and permissions to just let it install where programs normally do. If we need to have a further discussion about it, we can.

**Comment by ZeroAbility** [comment]
>We would have to use a different UI type.

I believe we will also need to modify the banner image because the dimensions are too large.

**Comment by ProjectPatatoe** [comment]
Having both 1.3.3 and 1.4.0 installed has been a boon since I was able to compare the two versions and use the previous version if I need a feature that doesn't work yet.
Having the new installer go straight into Program Files typically requires admin permissions. Does it automatically go into appdata if it doesn't?
The lack of indication is something I really find annoying in the Firefox web installer as there's no indication of which path it actually used. I don't know if maybe I could have made the path to go into Program Files instead if I just "Run as admin". (the offline installer isn't ambiguous).

**Comment by ZeroAbility** [comment]
> Having both 1.3.3 and 1.4.0 installed has been a boon since I was able to compare the two versions and use the previous version if I need a feature that doesn't work yet.

The reason this is a thing is we were previously using an installer project that was bloated and had too many WiX values that were hard defined. As a result, the value that would normally be defined to allow 1.3.3 to upgrade normally does not work. After the release of 1.4.0, it will behave as a normal installer with versions and snapshots released after. The snapshots already behave this way, but anything older is ignored as a version it can upgrade. Installing multiple versions gets tricky with `msi` files. Another functional issue is it clutters up menus and desktops for normal install cases when unique installers and shortcut paths are created for each version. The shortcut paths not being unique is why the shortcuts break.

> Having the new installer go straight into Program Files typically requires admin permissions. Does it automatically go into appdata if it doesn't?

Yes it does require admin and that is a best practice. The application itself writes values to `%AppData%`.

> The lack of indication is something I really find annoying in the Firefox web installer as there's no indication of which path it actually used. I don't know if maybe I could have made the path to go into Program Files instead if I just "Run as admin". (the offline installer isn't ambiguous).

We may have to provide that in documentation, as well. I think there should probably be a larger discussion about this to get a consensus about adding the feature to the installer. Alternatively, the desktop shortcut can be right clicked and in the Properties option it should provide the path to where Mumble is installed. The installer UI currently doesn't have the feature to change the install path, so "Run as Admin" will only prompt you before the installer is execute instead of when the License Agreement is accepted.

**Comment by ProjectPatatoe** [comment]
Switching installers makes sense that it didn't just "upgrade." However, the average person won't think to uninstall the previous version first. Above the download link for release should have some strong text stating something along the lines of "New installer, Uninstall previous mumble first. Config will carry over"

I don't think automatically keeping multiple versions is necessary. It's just a useful thing to be able to do when testing snapshots / development so I can still use the last stable.

Average person doesn't read the documentation before installing. If it's just left to check install path after installation, then I would have to install, check, uninstall, and start over.

**Comment by ZeroAbility** [comment]
>Above the download link for release should have some strong text stating something along the lines of "New installer, Uninstall previous mumble first. Config will carry over"

That is the plan. :)

>I don't think automatically keeping multiple versions is necessary. It's just a useful thing to be able to do when testing snapshots / development so I can still use the last stable.

Another possibility worth discussing is a standalone compressed folder for snapshots. This would accomplish what you are suggesting and not interfere with a stable install.

**Comment by ProjectPatatoe** [comment]
I think a standalone zip would be great actually. Is there any actual usage of the windows registries? If not then the release as a zip would almost be the "portable" version. Back when I was more mobile I copied mumble on a flash drive and it seemed fine other than configs lost but that was in the 1.2.x days.

**Comment by davidebeatrici** [comment]
Unfortunately it's still the case: settings are saved in the registry on Windows.

**Comment by Krzmbrzl** [comment]
In the long run however I would much like to unify the settings framework across all OS by using a (custom) settings file that we write and load and that looks the same on every OS.

**Comment by davidebeatrici** [comment]
Indeed.

**Comment by ZeroAbility** [comment]
> I think a standalone zip would be great actually. Is there any actual usage of the windows registries? If not then the release as a zip would almost be the "portable" version. Back when I was more mobile I copied mumble on a flash drive and it seemed fine other than configs lost but that was in the 1.2.x days.

There is a discussion for this now: https://github.com/mumble-voip/mumble/discussions/4714

**Comment by ProjectPatatoe** [comment]
Just remembered, why not just have that "typical" vs "custom" installer option? This way you still achieve Program Files / appdata for those who click through and still retain the choice for others. 

In regard to installing things in Program Files vs appdata, I really prefer to know exactly where something goes when I install it. I absolutely hate how Google Chrome and Discord just install wherever they want with no notice. Not to mention that Discord never installs into Program Files! At least Chrome does when it has permission.

As far as the requiring the old version to be uninstalled, why not just call the uninstaller in the background? It can check for what version is currently installed and call what is required from there.

**Comment by Krzmbrzl** [comment]
> As far as the requiring the old version to be uninstalled, why not just call the uninstaller in the background? It can check for what version is currently installed and call what is required from there.

We tried to do something like that but we simply were not successful with this. If you get that to work out, then that'd be amazing!

**Comment by davidebeatrici** [comment]
We actually already tested code based on https://stackoverflow.com/a/17936065 to find an installed application by GUID and uninstall it:
```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.Win32;

namespace UpgradeCodeTest
{
	class Program
	{
		static void Main(string[] args)
		{
			Guid guid = Guid.Parse("E028BDFC-3FE2-4BEE-A33B-EB9C80611555");

			string productCode = '{' + RegistryHelper.GetProductCode(guid).ToString() + '}';
			string uninstallCommandString = string.Format("/x {0} /qn", productCode);

			Process process = new Process();
			ProcessStartInfo startInfo = new ProcessStartInfo();
			process.StartInfo = startInfo;

			startInfo.UseShellExecute = false;
			startInfo.RedirectStandardError = true;

			startInfo.FileName = "msiexec";
			startInfo.Arguments = uninstallCommandString;

			process.Start();
			Console.Read();
		}
	}
}

internal static class RegistryHelper
{
	private const string UpgradeCodeRegistryKey = @"SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UpgradeCodes";

	private static readonly int[] GuidRegistryFormatPattern = new[] { 8, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2 };

	public static Guid? GetProductCode(Guid upgradeCode)
	{
		// Convert the product code to the format found in the registry
		var productCodeSearchString = ConvertToRegistryFormat(upgradeCode);

		// Open the upgrade code registry key
		var upgradeCodeRegistryRoot = GetRegistryKey(Path.Combine(UpgradeCodeRegistryKey, productCodeSearchString));

		if (upgradeCodeRegistryRoot == null)
			return null;

		var uninstallCode = upgradeCodeRegistryRoot.GetValueNames().FirstOrDefault();
		if (string.IsNullOrEmpty(uninstallCode))
		{
			return null;
		}

		// Convert it back to a Guid
		return ConvertFromRegistryFormat(uninstallCode);
	}

	private static string ConvertToRegistryFormat(Guid code)
	{
		return Reverse(code, GuidRegistryFormatPattern);
	}

	private static Guid ConvertFromRegistryFormat(string code)
	{
		if (code == null || code.Length != 32)
			throw new FormatException("Product code was in an invalid format");

		code = Reverse(code, GuidRegistryFormatPattern);

		return Guid.Parse(code);
	}

	private static string Reverse(object value, params int[] pattern)
	{
		// Strip the hyphens
		var inputString = value.ToString().Replace("-", "");

		var returnString = new StringBuilder();

		var index = 0;

		// Iterate over the reversal pattern
		foreach (var length in pattern)
		{
			// Reverse the sub-string and append it
			returnString.Append(inputString.Substring(index, length).Reverse().ToArray());

			// Increment our posistion in the string
			index += length;
		}

		return returnString.ToString();
	}

	static RegistryKey GetRegistryKey(string registryPath)
	{
		var hklm64 = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64);
		var registryKey64 = hklm64.OpenSubKey(registryPath);
		if (((bool?)registryKey64?.GetValueNames()?.Any()).GetValueOrDefault())
		{
			return registryKey64;
		}

		var hklm32 = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32);
		return hklm32.OpenSubKey(registryPath);
	}
}
```

However, we're not sure whether the imports can be used in WiX#.

**Comment by ProjectPatatoe** [comment]
This really should be a requirement for stable. Having everyone install the new version, then explaining that the shortcut they made is still pointing to the old version and needs to be uninstalled is just... well bad. 

I also make it a point to not install things into Program Files because windows handles permissions in those directories much differently. Which by the way, will fix alot of issues with self-updating programs/games. 

Sorry, wish I knew more about wix ):

**Comment by Krzmbrzl** [comment]
I would not consider it a blocker for the stable release. Installing into program files should be what most users do anyway 🤷

It would be nice to have control over where to install though. But as I said: I would definitely not block the release because of it.

**Comment by davidebeatrici** [comment]
> I also make it a point to not install things into Program Files because windows handles permissions in those directories much differently.

It's exactly why programs are supposed to be installed in that directory.

**Comment by ProjectPatatoe** [comment]
I understand the reasons why, but it doesn't actually change the problems it causes. For mumble, since it doesn't self update, fine.
Let's put 'custom location' itself aside then. If it's going to force program files, then we need to also remove the old version. I would still end up with two versions.
I just tested and verified actually. I guess since people keep pushing back on this, I'll just leave it alone then. I realize that there is #5076 that no one has linked in here yet so I'll suggest that one be a blocker and not this one.

**Comment by Krzmbrzl** [comment]
That is also not a blocker since it just doesn't work. For some stupid reason all our attempts at solving it failed and we ran out of ideas to try. Thus that is not a blocker either

**Comment by Krzmbrzl** [comment]
After having talked about this issue again in one of our meetings, we came to the conclusion that we will not change this behavior. Mumble is generally very light-weighted and thus disk space shouldn't really be a concern. Furthermore, installing Mumble in a non-standard location can cause the shortcut system to stop working (and we don't want to receive a bunch of reports of this).

Finally, we are planning on releasing a portable version of Mumble (no installation necessary) which should fit the needs of anyone, who is missing the ability to specify a custom install location.

**Comment by eebssk1** [comment]
Is portable mumble windows client available now?
I need to install it on locked down system which do not have admin rights.
