### ISSUE TITLE
Merge and remove some GitHub issue labels

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4703]
We already have more than enough labels, so duplicates, unused ones etc. should probably be removed.

Some things I see:

- wontfix and `won't fix` (merge)
- is there a difference between `enhancement` and feature requests?
- website, wiki (already described as obsolete; issues will be transfered to the right repo, so can be deleted)
- [theme](https://github.com/mumble-voip/mumble/labels/theme) either belongs in mumble-theme repo or should probably be merged into something like `UI`
- ubuntu, debian: Are those really necessary? Either it's a general problem with linux or a problem that the distro has to fix imo.
One exception would be your ubuntu-package. Maybe add a general label `distro` if it's distro/package specific.
- pr-available: maybe not necessary, because you see all linked PRs
- KnownIssues-1.3.0: outdated?
- upstream-bug: is a bit missleading, maybe rename it to clarify that it's not a mumble bug; `external-bug` maybe
- a11y and accessibility (merge)

**Comment by Krzmbrzl** [comment]
> is there a difference between enhancement and feature requests?

I once used it for different things but in the end it was not practical and thus they are now to be understood as synonymous and can therefore be merged.

> upstream-bug: is a bit missleading, maybe rename it to clarify that it's not a mumble bug; external-bug maybe

I think `upstream` is the usual term here. But given that `external` is more descriptive, I'm fine with changing it as suggested :+1:

**Comment by Kissaki** [comment]
I looks like wontfix has already merged/cleaned up

We have 50+51 enhancement and 224+335 feature-request (open+closed counts).

I merged `ehnhancement` into `feature-requests`. I am now dropping the `enhancement` label.

**Comment by Kissaki** [comment]
`website` and `wiki` no longer exist

**Comment by Kissaki** [comment]
23 issues with `theme`. 327 `ui`. 7 have `theme` *and* `ui`.

UI concerns are not always a theme issue though. So I don't know if that's a useful merge. The separate mumble-theme repository has been merged into this mumble repository. Moving theme issues out is no longer an option, and I would have been skeptical because of the separation anyway.

So I don't think it's obvious dissolving `theme` is a good idea, and I am skeptical that it is at all. Theme is a considerable sub-area/-category of UI. Maybe every `theme` issue is a `ui` issue. But `theme` still gives us a useful categorization of that particular scope.

**Comment by Kissaki** [comment]
`pr-available` no longer exists

**Comment by Kissaki** [comment]
That leaves

> ubuntu, debian: Are those really necessary? Either it's a general problem with linux or a problem that the distro has to fix IMO.
> One exception would be your ubuntu-package. Maybe add a general label distro if it's distro/package specific.

and the question of `upstream` -> `external` rename

> upstream-bug: is a bit missleading, maybe rename it to clarify that it's not a mumble bug; external-bug maybe

**Comment by Kissaki** [comment]
For me, `upstream` is intuitive, common terminology. But I can't say how common or prevalent it is overall and overall in the dev space.

I like how `external` is generally descriptive, even without the *stream" terminology and dependency on knowledge of its use. It is more descriptive even for people unfamiliar with software development or technical tools and terminology.

So, with @Krzmbrzl approval in their comment above, I will change `upstream-bug` to `external-bug`. It has 21 tickets, two of which are open.

**Comment by Kissaki** [comment]
Regarding the linux labels:

I think it's a good point.

* If we have linux specific issue it is a `linux` issue.
* If it is debian specific, it must be upstream packaging and must be a ticket on their platform and our tickets only reference them, or a general linux issue.
* If it is an ubuntu issue, it is either upstream packaging, or our PPA https://github.com/mumble-voip/mumble-ubuntu-ppa with it's own issues https://github.com/mumble-voip/mumble-ubuntu-ppa/issues.

Is having PPA issues in a separate tracker good, neutral, or bad? This mumble issues tracker will be the entry point and point of search and discovery for most people. We could apply the same reasoning as for debian: Such tickets here will be forwarding to our PPA issues, and be general `linux` labelled.

**Comment by Krzmbrzl** [comment]
> Is having PPA issues in a separate tracker good, neutral, or bad? 

I think issues should go into the relevant repo. That means PPA bugs should not be in this repository but in the PPA repo (essentially analogously to how Debian package issues should be in their own bug tracker)

**Comment by Kissaki** [comment]
With agreement of Krzmbrzl and Davide on chat I assigned the `linux` label to the few tickets missing them, and removed the `debian` and `ubuntu` labels.

That concludes this ticket.
