### ISSUE TITLE
murmur: Audio output does not work until you transmit voice the first time logging in a murmur server

### ISSUE THREAD

**Issue by mellow311** [mumble-voip/mumble#4709]
This has been an issue for me for years now. I always hoped it would be fixed in future updates but hasnt. When first starting up mumble and logging into a server I can not hear anything from anyone until I simply press the transmit button 1 time or speak for the first time with the auto voice activity.  This happens on all my clients around the house I use.  Mumble for android.. mumble for Apple and the windows clients. Im also running the murmur server on a  windows 2003 server

**Comment by Krzmbrzl** [comment]
I have never experienced this issue before :thinking: 
Is this a problem specific to your own server or does it happen on other servers as well?
What version of murmur are you using?
Do you have any evidence that this is indeed a server-side issue (e.g. by network monitoring)?
