### ISSUE TITLE
Mumble on mac not working

### ISSUE THREAD

**Issue by lemonsaa** [mumble-voip/mumble#4710]
When i open mumble it wont let me click anything or close it. Please help i dont know what to do

**Comment by Krzmbrzl** [comment]
First of all: Which version of Mumble are you trying to launch, where did you get it from and how did you install it?
Secondly: Which version of macOS are you using?
Thirdly: Have you tried starting Mumble from the command line yet? This tends to circumvent Apple's "security" features which I could imagine are interfering here.
