### ISSUE TITLE
Duplicate button hotkey c for Connect and Cancel in server list window

### ISSUE THREAD

**Issue by mk-pmb** [mumble-voip/mumble#4726]
**Describe the bug**
In the server list window, both the Connect and Cancel button have their first C underlined, and alt+c seems to have no effect.

**Steps to Reproduce**
1. Install Mumble 1.3.3-1~ppa1~focal1 on Ubuntu focal
1. Configure it to open the server list on startup
1. Add a favorite server
1. Connect to that favorite server
1. Quit Mumble
1. Start Mumble
1. (Expected observation: The server list opens, and the fav server is selected.)
1. Press alt+c
1. Nothing happened.

**Expected behavior**
Alt + whatever letter is underlined on the connect button, connects me to my favorite server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu focal
 - Version: Mumble 1.3.3-1~ppa1~focal1

**Additional context**
Fortunately I discovered that I can press Enter to connect.

**Comment by Krzmbrzl** [comment]
@Kissaki are we even responsible for these kind of navigational controls or is this something Qt offers automatically? :thinking:

**Comment by Kissaki** [comment]
We signify these mnemonic shortcodes with ampersands (`&`) in the control caption text.

The difficulty is of course following common conventions, of platforms and in general, and at the same time implementing a consistent interface to the user within our context; menus, buttons, controls to jump focus to.

In this case I would expect `&Connect` and `&Cancel`. The question then is what would be more intuitive to the user. Which one should stay, and which be changed. E.g. to `C&onnect`, or `C&ancel`.

**Comment by mk-pmb** [comment]
Where possible, please use the same hotkeys as the [GTK3 Stock Items](https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html).

**Comment by Krzmbrzl** [comment]
Ah so that's what these ampersands are for :sweat_smile: 

> Which one should stay, and which be changed. E.g. to C&onnect, or C&ancel.

Given that you can connect by hitting enter I would say that using C for cancel would be best :thinking:

**Comment by mk-pmb** [comment]
In US English, my GTK uses c for Cancel and Close (nice because they are similar in meaning), and o for connect.
