### ISSUE TITLE
Simulated Packet Loss at High Bitrates and Audio Per Packet settings.

### ISSUE THREAD

**Issue by SC1040-TS2** [mumble-voip/mumble#4734]
**Describe the bug**
When using Push to Talk, assuming you are on a server with enough supported bandwidth, it is possible to generate packet loss on Upload packets in the right conditions with at least 40ms Audio Per Packet set. This has been tested on three different servers running different Murmur versions (1.2.19, 1.3.0, and 1.3.3), each with the same result.

**Steps to Reproduce**
1. Go to the Audio Input settings.
2. Set the Compression Quality to between 60 to 96kbps, and Audio Per Packet to 40ms or higher. For the purpose of this test, the Jitter Buffer was disabled, and settings Audio Per Packet to 20ms or lower did not have this effect.
3. Join any server.
4. Right-click on yourself and click on Information.
5. Repeatedly press the push to talk key at half-second intervals or faster. The user information should report a consistent loss in From Client packets from this behavior.

Holding down the Push to Talk key does not result in this behavior. Only pressing it at frequent enough intervals.

**Expected behavior**
Regardless of key-press intervals, bitrate quality, or audio per packet settings, minimal to no packet loss generated assuming no other factors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 X64 2009/20H2.
 - Version: Mumble 1.3.3, tested on Murmur versions 1.2.19, 1.3.0, and 1.3.3.

**Additional context**
Bear in mind that the Windows Mumble clients do not have libopus 1.2 due to an accidental failure to include it in those repositories at the time of 1.3.0, so if this was fixed in the static Linux versions already thanks to that or another merged commit, the Windows clients are simply behind.

This may also be related to the ending discussion in the thread here: https://github.com/mumble-voip/mumble/issues/4719 , where a music bot could now generate packet loss for clients with a new version after the OCB2 mitigation was introduced. If this new issue is also related, then a much more common use case of frequently turning Push to Talk on and off can induce the same effect, which is not ideal.

**Comment by TredwellGit** [comment]
I strongly assume that this is https://github.com/mumble-voip/mumble/issues/4719.

**Comment by SC1040-TS2** [comment]
> I strongly assume that this is #4719.

Perhaps, but I will test again with TCP mode to be sure.

If it also shows up there, there is a separate problem. If it is strictly tied to UDP packets, then it may very well be the OCB2 mitigation revealing more flaws.

**Comment by SC1040-TS2** [comment]
Okay, I have tested the UDP with Mumble client version 1.3.4 on the same servers as before. No visible packet loss was reported.

It was in fact the OCB2 mitigation packet loss issue in https://github.com/mumble-voip/mumble/issues/4719, but https://github.com/mumble-voip/mumble/issues/4734 served as further documentation that it was responsible for a much more common problem with users happening to use Push to Talk just by pressing the key as needed at a short enough interval.

**Comment by SC1040-TS2** [comment]
Okay, I have tested the UDP with Mumble client version 1.3.4 on the same servers as before. No visible packet loss was reported.

It was in fact the OCB2 mitigation packet loss issue in https://github.com/mumble-voip/mumble/issues/4719, but https://github.com/mumble-voip/mumble/issues/4734 served as further documentation that it was responsible for a much more common problem with users happening to use Push to Talk just by pressing the key as needed at a short enough interval.
