### ISSUE TITLE
Version was not bumped from 1.3.3 to 1.3.4.

### ISSUE THREAD

**Issue by TredwellGit** [mumble-voip/mumble#4743]
There was no https://github.com/mumble-voip/mumble/commit/6863742b2efd783a13148c3f348d9242eaca331a equivalent for 1.3.4. For example: https://github.com/mumble-voip/mumble/blob/1.3.4/src/mumble.pri#L11

**Comment by Krzmbrzl** [comment]
Yes you are right. We forgot about that (again).
Thanks foe bringing this to our attention :+1:

**Comment by davidebeatrici** [comment]
Thank you very much and sorry for that.

c0b5be7134673fa1c4c434b72552c200bca37b8d
