### ISSUE TITLE
« Unautorized certificat » on Android 5.1

### ISSUE THREAD

**Issue by TomD629** [mumble-voip/mumble#4745]
**Describe the bug**
An access with mumla on a Android 9 is OK, but an access from a Android 5.1 is refused by the error : « unautorized certificat ».
It’s the same with other Android Client (Plumble and WiMic).

**Steps to Reproduce**
Mumla on a Android 5.1

**Expected behavior**
Could use client on all Android version

**Screenshots**

**Desktop (please complete the following information):**
*  Mumla on Android 5.1
* Murmur 1.3.0

**Additional context**

**Comment by Krzmbrzl** [comment]
Mumla is not maintained by us nor is it part of this repository.

Please report your issue to the respective project at https://gitlab.com/quite/mumla

If this was an issue that you were seeing using the regular desktop client, then this would be the right place. But if it is only an issue with Mumla, that is probably out of our control :point_up:
