### ISSUE TITLE
New public list registration script often fails to resolve domains

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#4750]
**Describe the bug**
Server no longer shows up in the public server list after updating to 1.3.4

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Update to murmur-static_x86-1.3.4
2. Restart daemon

**Expected behaviour**
Servers shows up in the public server list as before

**Actual behaviour**
Server does not show up in the public server list

**Additional context**
The log contains many `Registration: No DNS records found for mumble.ourcompany.com` lines. Both A and SRV records are confirmed to be present as tested directly from the server, not to mention there was no such issue before the update.

Absolutely no changes were made besides updating to murmur-static_x86-1.3.4. If there are any methods I can debug this further, please let me know.

**Comment by davidebeatrici** [comment]
A few days ago we replaced the registration script with a new one, which is set to resolve queries through `systemd-resolved`.

Reliability seems to be pretty poor, considering we received a report of the issue from an user on IRC two days ago.

I just installed `unbound` and set the script to use it, please let me know whether the issue is fixed.

**Comment by StrangePeanut** [comment]
Unfortunately, our server continues not to show up after restarting the murmur daemon. The log also kept returning `No DNS records found` on 1.3.4. However, the following lines could be observed after downgrading to 1.3.3:

```log
<W>2021-02-12 07:51:36.174 1 => Registration: Attempting to connect...
Your certificate is validated by a CA, congratulations!
Registration updated!
```

No more `No DNS records found` to be seen on 1.3.3. I've given it a good 30 minutes since. No luck. I’m completely lost on where to look considering nothing was changed configuration wise.

**Comment by StrangePeanut** [comment]
It's just begun to show up again. Hesitant to update to 1.3.4 now.

**Comment by StrangePeanut** [comment]
All good on 1.3.4 now 🥳

**Comment by davidebeatrici** [comment]
Interesting... at this point I wonder whether it's the Lua library we're using that sometimes fails to resolve the domain.

For reference: https://github.com/mumble-voip/LuaResolver

**Comment by MaxwellCody** [comment]
> Interesting... at this point I wonder whether it's the Lua library we're using that sometimes fails to resolve the domain.
> 
> For reference: https://github.com/mumble-voip/LuaResolver

The demos and examples in this repo make judicious use of the `ANY` (type 255) DNS query type. Does the registration server also use `ANY`? If so, that should probably be changed since `ANY` is on its way out: https://tools.ietf.org/html/rfc8482

**Comment by skobkin** [comment]
Same for me. My server was dropped from the public server list several days ago.

Today I updated it to 1.3.4 just in case, but it didn't help. Output says:

```
Registration: No DNS records found for mumble.skobk.in
```

```
# host mumble.skobk.in
mumble.skobk.in is an alias for mumble-msk1.skobk.in.
mumble-msk1.skobk.in has address 185.189.14.117
mumble-msk1.skobk.in has IPv6 address 2a04:5200:fff7::b5e
```

Several dozens of users are now unable to reach the server because they were using public list to connect.

I also can see that number of public servers in Russia dropped down. Can't find some servers located in Germany too.

**Comment by Krzmbrzl** [comment]
@davidebeatrici you broke the system :scream:

**Comment by davidebeatrici** [comment]
@MaxwellCody Good catch! Time to switch to https://luarocks.org/modules/zash/luaunbound.

**Comment by davidebeatrici** [comment]
Done!

**Comment by Krzmbrzl** [comment]
I assume everything is working now. If not, please let us know.

**Comment by MaxwellCody** [comment]
@Krzmbrzl Doesn't look like this issue has been solved completely yet. My server still doesn't show up on the public list and here's what grepping for "registration" in my logs gets me (times are in UTC):

```
$ sudo cat /var/log/mumble-server/mumble-server.log | grep -i registration
<W>2021-02-14 00:31:02.167 1 => Registration: No DNS records found for hedonics.org
<W>2021-02-14 01:31:11.156 1 => Registration: No DNS records found for hedonics.org
<W>2021-02-14 02:34:38.119 1 => Registration: No DNS records found for hedonics.org
<W>2021-02-14 03:35:14.034 1 => Registration: No DNS records found for hedonics.org
<W>2021-02-14 04:36:46.295 1 => Registration: No DNS records found for hedonics.org
<W>2021-02-14 05:39:59.390 1 => Registration: No DNS records found for hedonics.org
<W>2021-02-14 06:44:14.122 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Internal Server Error
<W>2021-02-14 07:46:59.420 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Internal Server Error
<W>2021-02-14 08:50:45.435 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Internal Server Error
<W>2021-02-14 09:54:22.247 1 => Registration failed: Error transferring https://publist-registration.mumble.info/v1/register - server replied: Internal Server Error
```

**Comment by Krzmbrzl** [comment]
@davidebeatrici

**Comment by skobkin** [comment]
> Doesn't look like this issue has been solved completely yet.

Same in my server logs.

**Comment by davidebeatrici** [comment]
> attempt to call a nil value (global 'sizeof')

I accidentally wrote `sizeof` instead of `ffi.sizeof` in the the A record handler while refactoring the code, sorry about that.

And thank you very much for the fast report!

**Comment by Krzmbrzl** [comment]
Okay could some of you confirm that it is now working as intended? :eyes:

**Comment by MaxwellCody** [comment]
> Okay could some of you confirm that it is now working as intended? eyes

<W>2021-02-14 18:13:37.235 1 => Registration failed: Connection closed

**Comment by davidebeatrici** [comment]
> exit signal Segmentation fault (11), possible coredump in /etc/apache2

The error was in:
```lua
ffi.C.inet_ntop(AF_INET, ffi.cast("void *", in_addr.addr), buffer, ffi.sizeof(buffer))
```

Corrected:
```lua
ffi.C.inet_ntop(AF_INET, ffi.cast("void *", ffi.addressof(in_addr.addr)), buffer, ffi.sizeof(buffer))
```

@MaxwellCody I'm not spotting any more errors in Apache's log, is the registration working fine now?

**Comment by MaxwellCody** [comment]
@davidebeatrici

```
<W>2021-02-14 18:33:35.478 1 => Registration: Attempting to connect to [2600:3c00::f03c:92ff:feb3:ef2b]:64738...
Your certificate is validated by a CA, congratulations!
Registration updated!
```

Not seeing the server back on the public list yet, but I suppose that might take moment.

**Comment by davidebeatrici** [comment]
I just triggered an update, you should see your server now.

**Comment by MaxwellCody** [comment]
> I just triggered an update, you should see your server now.

Yup, there it is. :+1:

**Comment by davidebeatrici** [comment]
Awesome! Thank you for your patience and sorry for the various errors on my side, it's the first time I use Lua + FFI.

**Comment by skobkin** [comment]
Fixed for me.

**Comment by Krzmbrzl** [comment]
Then I guess it is finally working. Thanks for your collaboration and patience :+1:
