### ISSUE TITLE
Missing database driver QSQLITE in Docker container

### ISSUE THREAD

**Issue by Chessmasterrr** [mumble-voip/mumble#4755]
**Describe the bug**
When trying to run the Dockerfile, the database driver QSQLITE cannot be found by murmur:

`ServerDB: Database driver QSQLITE not available`

**Steps to Reproduce**
1. I forked the official repo to build an up-to-date image in the Docker hub. See https://hub.docker.com/r/chessmasterrr/mumble
2. Execute `docker run chessmasterrr/mumble`
3. See error:
```
<X>2021-02-13 08:35:31.549 SSL: OpenSSL version is 'OpenSSL 1.1.1f  31 Mar 2020'
<W>2021-02-13 08:35:31.550 Initializing settings from /etc/murmur/murmur.ini (basepath /etc/murmur)
<W>2021-02-13 08:35:31.785 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<F>2021-02-13 08:35:31.813 ServerDB: Database driver QSQLITE not available
```

**Expected behavior**
Mumble should start with the default settings.

**Additional context**
If the container is started interactive (`docker run -it --user root chessmasterrr/mumble /bin/bash`) I can verify, that `libQt5Sql.so.5.12.8` is located under `/usr/lib/x86_64-linux-gnu/` and also in `/lib/x86_64-linux-gnu/`. Also `ldd /usr/bin/murmurd` states `libQt5Sql.so.5 => /lib/x86_64-linux-gnu/libQt5Sql.so.5`.

Am I missing something?

**Comment by Krzmbrzl** [comment]
Could you try if installing `libqt5sql5-sqlite`  (https://packages.ubuntu.com/focal/libqt5sql5-sqlite) resolves the issue?

**Comment by Chessmasterrr** [comment]
Perfect, that solved the issue. Thanks for the fast response!

I added the missing package to the Dockerfile and created a merge request.
