### ISSUE TITLE
Mumble neither pings favourites nor lists any public servers until reopening the Server Connect dialogue upon start

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#4757]
**Describe the bug**
Mumble neither pings favourites nor lists any public servers until reopening the Server Connect dialogue upon start

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open Mumble
2. Expand any location under Public Internet

**Expected behaviour**
Favourites are being pinged, public servers are being listed

**Actual behaviour**
Favourites are not being pinged, public servers are not being listed

**Screenshots**
https://imgur.com/bVGjvMm

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.3.4

**Additional context**
The issue seems to occur 50% of the time.

**Comment by Krzmbrzl** [comment]
Have you tried waiting a bit longer. Lately I seem to have experienced that the list takes a couple of seconds in order to do anything.
So just to be sure, could you try opening the list, waiting for some time (e.g. 10-20s just to be sure) and then check whether server pings and public servers are being listed?

**Comment by StrangePeanut** [comment]
I've just given it a go, waited a minute and nothing.

**Comment by Krzmbrzl** [comment]
Were you using Mumble before on your machine? If so: did this work before?

Could you paste the output from the Developer console here, please? You hsve to enable the developer menu from the settings and then use the new dropdown menu to open up the console.

**Comment by StrangePeanut** [comment]
Yes, I use Mumble regularly. Not sure if it's always done it, sorry.

The developer console remains empty, but it works on the VM where I can also replicate the issue:

```log
<W>2021-02-13 14:53:18.388 DirectSound: Disabled as WASAPI is available
<W>2021-02-13 14:53:18.388 ASIO: No valid devices found, disabling
<W>2021-02-13 14:53:18.422 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2021-02-13 14:53:18.422 libopus v1.1.3 from C:/Program Files/Mumble/Versions/1.3.4/opus.dll
<W>2021-02-13 14:53:18.422 CELT bitstream 8000000b from C:/Program Files/Mumble/Versions/1.3.4/celt0.0.7.0.dll
<W>2021-02-13 14:53:18.422 CELT bitstream 80000010 from C:/Program Files/Mumble/Versions/1.3.4/celt0.0.11.0.dll
<W>2021-02-13 14:53:18.422 Theme: "Mumble"
<W>2021-02-13 14:53:18.422 Style: "Lite"
<W>2021-02-13 14:53:18.422 --> qss: ":themes/Mumble/Lite.qss"
<W>2021-02-13 14:53:18.422 Locale is "en_GB" (System: "en_GB")
<W>2021-02-13 14:53:18.441 Database SQLite: "3.18.0"
<W>2021-02-13 14:53:18.441 Bonjour: Failed to load dnssd.dll
<W>2021-02-13 14:53:18.441 Updating application palette
<W>2021-02-13 14:53:18.562 AudioInput: Opus encoder set for VOIP
<W>2021-02-13 14:53:18.562 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2021-02-13 14:53:18.454 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2021-02-13 14:53:18.545 XboxInput: using XInput DLL 'XInput1_4.dll'
<W>2021-02-13 14:53:18.545 XboxInput: using XInputGetStateEx() as querying function.
<W>2021-02-13 14:53:18.545 GlobalShortcutWin: XboxInput initialized, isValid: 1
<W>2021-02-13 14:53:18.562 WASAPIInput: Latencies 101587 29025 => 100000
<W>2021-02-13 14:53:18.576 WASAPIOutput: Latencies 101587 29025 => 100000
<W>2021-02-13 14:53:18.576 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Mouse Mouse:5 type 0x00000112 guid product {6f1d2b60-d5a0-11cf-bfc7-444553540000}
<W>2021-02-13 14:53:18.576 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Keyboard Keyboard:127 type 0x00000413 guid product {6f1d2b61-d5a0-11cf-bfc7-444553540000}
<W>2021-02-13 14:53:18.576 WASAPIOutput: Output stream format 1
<W>2021-02-13 14:53:18.576 WASAPIOutput: Stream Latency 0 (2646)
<W>2021-02-13 14:53:18.576 WASAPIOutput: Periods 10158us 2902us (latency 0us)
<W>2021-02-13 14:53:18.576 WASAPIOutput: Buffer is 60000us (5)
<W>2021-02-13 14:53:18.576 AudioOutput: Initialized 2 channel 44100 hz mixer
<W>2021-02-13 14:53:18.576 WASAPIInput: Mic Stream format 1
<W>2021-02-13 14:53:18.576 WASAPIInput: Stream Latency 0 (984)
<W>2021-02-13 14:53:18.592 AudioInput: Initialized mixer for 2 channel 44100 hz mic and 0 channel 48000 hz echo
```

**Comment by Krzmbrzl** [comment]
Hm... :eyes: 
I just verified that I can't reproduce this issue on my machine (with a 1.4.0 snapshot). So this already means that in general the public server list is available.

My suspicion would be that maybe this is a firewall problem on your side. However this would not explain why at a later point it suddenly works... :thinking: 
Do you think you could try disabling firewalls in order to check whether the problem still exists? Definitely re-enable them afterwards though!

**Comment by StrangePeanut** [comment]
This didn't help, unfortunately!

**Comment by Krzmbrzl** [comment]
Then I am out of ideas :thinking:

**Comment by SC1040-TS2** [comment]
I cannot replicate this on my Windows 10 and 1.3.4 Client version, but if not a networking problem, ruling out a very common form of underlying Windows corruption as being responsible for this may help.

To do that, press Start key+X or Right-click on the Start Menu icon to open the Power User Start Menu. From there, click on either **Command Prompt (Admin)** or **Windows PowerShell (Admin)**.

Inside the terminal, type the command **sfc /scannow** to run the System File Checker, and wait for that to finish.

Regardless of whether SFC reports any corrupted files, to truly repair the OS image, type the command **DISM /Online /Cleanup-image /Restorehealth** to repair the OS, assuming Windows Update still works as it should.

**Comment by SC1040-TS2** [comment]
That said, the OS possibly running on a VM might complicate things, which I assumed was the case considering the white overlay borders around the Windows 10 desktop in the video.

**Comment by StrangePeanut** [comment]
Unfortunately, I could replicate the issue on both host and guest; this is not VM-specific. I’m also on a recent, fresh 20H2 install. I’ll do some further testing when I get the chance.

**Comment by Krzmbrzl** [comment]
@StrangePeanut but I assume you were using one and the same network when testing the VM and the host, right?
I think in your case it'd be best to monitor your computer's network traffic to see if there are any outgoing pings that are sent. If they are sent the next thing to check would be your router. It might (for some weird reason) be blocking packets from actually going out into the wild.
Do you think you have the technical knowledge to do something like this?

Another test that you can perform is to try to access https://publist.mumble.info/v1/list in your browser. That should hopefully work.
Next up, open a terminal and type in the following command:
```batch
ping publist.mumble.info
```
and copy the resulting output here, please.
With that we can check whether you can (in principle) access the public server list from your computer.
