### ISSUE TITLE
Directional audio is opposite

### ISSUE THREAD

**Issue by DcypLShock** [mumble-voip/mumble#4768]
Used game: Minecraft

**Comment by davidebeatrici** [comment]
Game?

**Comment by DcypLShock** [comment]
minecraft

**Comment by DcypLShock** [comment]
I am using a logitech g432 and in minecraft everything is opposite

**Comment by DcypLShock** [comment]
left is right forwars is back etc.

**Comment by DcypLShock** [comment]
Im using the latest version of mumble and this isnt happening on anything other then positional audio

**Comment by Krzmbrzl** [comment]
This sounds like the plugin being broken. Were do you get the plugin from?

**Comment by DcypLShock** [comment]
It is default mumble and im using the mumble link mod for minecraft the only thing i changed in mumble plugins section is the option to link to game and transmit position

**Comment by Krzmbrzl** [comment]
Ah okay so Minecraft is connected via Link.

Where does the support for the Link plugin come from on Minecraft's site? Is it integrated into the main game or is there a Mod or 3rdParty application that does the interfacing?

Also: Were you using positional audio in Minecraft before? If so: did the problem exist back then? if not: did you update anything in the meantime?

**Comment by Kissaki** [comment]
This may be something to confirm and verify with the Minecraft link mod rather than Mumble. Did you check their known issues and support requests for something like this?
