### ISSUE TITLE
Outdated copyright

### ISSUE THREAD

**Issue by 1Maxnet1** [mumble-voip/mumble#4784]
**Describe the bug**
The Copyright in the about window is outdated (2019).

**Steps to Reproduce**
1. Open Mumble
2. Go to: Help > About

**Expected behavior**
See the current copyright 2005-2021

**Screenshots**
![grafik](https://user-images.githubusercontent.com/24827631/108868350-69a8b200-75f6-11eb-9e3b-72307e6877fc.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: Mumble 1.3.3

**Additional context**
-

**Comment by Krzmbrzl** [comment]
Yes indeed. That's what you get for hardcoding such things ^^

Thanks for reporting this :+1:
