### ISSUE TITLE
Searchbar for finding servers

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#4787]
The Android client Mumla comes with a searchbar which allows you to search for servers by name and by country. Something like this would be useful for querying though all the Mumble servers on the desktop client.

**Comment by Krzmbrzl** [comment]
Which version are you using? 
There is a server browser in the desktop version. So what do you require exactly?

**Comment by deluxghost** [comment]
I think this issue is a feature request. He wants a searchbar with keyword inputbox, country filter and shows search result, just like what Mumla has. Not only a treeview browser

**Comment by Krzmbrzl** [comment]
In that case 1.4.0 should have everything you want already. For a screenshot have a look at https://github.com/mumble-voip/mumble/pull/4291 and for testing it out yourself, you can get a development snapshot from https://www.mumble.info/downloads/#development-snapshots

**Comment by trymeouteh** [comment]
> In that case 1.4.0 should have everything you want already. For a screenshot have a look at #4291 and for testing it out yourself, you can get a development snapshot from https://www.mumble.info/downloads/#development-snapshots

If what I see gets added in future releases then that is all I ask for.

**Comment by Krzmbrzl** [comment]
Yes this will be parr of the 1.4.0 version. And as I mentioned: it id already part of the 1.4.0 snapshot version :)
