### ISSUE TITLE
Do not echo welcometext when set via Ice

### ISSUE THREAD

**Issue by KetchupBomb** [mumble-voip/mumble#4788]
**Describe the bug**
Setting (at least) `welcometext` via Ice echoes the new welcome message to the server for which it was configured.

**Steps to Reproduce**
1. Join a server which has the Ice endpoint exposed with write privileges.
1. Invoke `server.setConf(key='welcometext', value='foobar')` interface.
1. View that "`foobar`" has been echoed to the chat log in the Mumble client.

**Expected behavior**
I would think that _setting_ the `welcometext` config key should do just that, and **not** actively echo the new value to all connected clients.

**Screenshots**
![1](https://user-images.githubusercontent.com/13783465/108962159-333a5980-762d-11eb-98b0-2a22bb24b10a.JPG)
![2](https://user-images.githubusercontent.com/13783465/108962165-36cde080-762d-11eb-966f-7e83585e4c55.JPG)
![3](https://user-images.githubusercontent.com/13783465/108962173-3897a400-762d-11eb-9160-698fc95aafbf.JPG)

**Desktop (please complete the following information):**
 - OS:
   - Client: `Microsoft Windows 10 Enterprise` `10.0.18363 N/A Build 18363`
   - Server: `Linux 24fc4c3fb73f 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 GNU/Linux`
 - Mumble/Murmur:
   - Client: 1.3.4
   - Server: 1.3.4

**Comment by Krzmbrzl** [comment]
I agree that the new welcome message should not be displayed to users that are already connected.

The code portion responsible for this is

https://github.com/mumble-voip/mumble/blob/569336e78a9a5d516306f2ba2d9ce7e35afbf622/src/murmur/Server.cpp#L595-L602

@davidebeatrici I tend to simply remove the creation and sending of the Protobuf message. Objections?

**Comment by davidebeatrici** [comment]
No objections.

**Comment by deluxghost** [comment]
I am using this... feature.

**Comment by KetchupBomb** [comment]
> @deluxghost: I am using this... feature.

I was thinking of a clean way to provide the ability to opt in or out of this behavior; the Ice Slice definition doesn't leave much room to do so. Writing an interface to set just the `welcometext` is probably overkill, as is extending `server.setConf()` with additional parameters.

All of this is to ask, @deluxghost, if you could _set_ the `welcometext` and then _explicitly_ `server.sendMessage()` to all connected users to mimic the existing behavior?

**Comment by deluxghost** [comment]
I guess the client-side TTS engine will read the message from `sendMessage`?

**Comment by KetchupBomb** [comment]
@Krzmbrzl, I put up #4794 for you to review. I am coming from a world of Mercurial and getting more comfortable with Git & Github, so I hope you don't mind the PR.

---

@deluxghost, I'm unsure what TTS engine is, can you elaborate?

Regardless, I can confirm that setting `welcometext` and then using a `server.sendMessage()`/`server.sendMessageChannel()` call to broadcast the newly set `welcometext` is mostly functionally equivalent to what you have now. One difference I _can_ see is that the messages appear slightly differently in the text log:

![1](https://user-images.githubusercontent.com/13783465/109189400-d633c600-7748-11eb-9ac9-a7c55cd6947e.JPG)

The first line is from (via `mice.py`):

```
In [5]: s.setConf(key='welcometext', value='foobar')
```

And the second line is from (via `mice.py`):

```
In [9]: s.sendMessageChannel(0, True, 'foobar')
```

**Comment by deluxghost** [comment]
If you enable TTS, the client will read normal messages for you, that I want to avoid. TTS engine never read welcome message.

(maybe my use case is weird, because I consider the welcome message as MOTD, which should show again while changing)

**Comment by Krzmbrzl** [comment]
> so I hope you don't mind the PR.

Quite the contrary :+1:

**Comment by deluxghost** [comment]
either adding an option (by any means) to toggle the broadcasting, or adding a new rpc call to broadcast manually, is good to me.

**Comment by Krzmbrzl** [comment]
I think broadcasting the welcome text on change is semantically wrong.

Introducing an option to the existing RPC call is not an option since the call is not specific for the welcome message.
I think however that it should be easily doable to create a new RPC call that allows explicitly broadcasting the currently set welcome text.

**Comment by KetchupBomb** [comment]
> @deluxghost: If you enable TTS, the client will read normal messages for you...

Ah, Text-To-Speech. Gotcha.

Utilizing `server.sendMessage()`/`server.sendMessageChannel()` **will undergo Text-To-Speech** if "**Text Message**" is enabled in settings, unfortunately.

I agree with @Krzmbrzl, that an additional interface to broadcast the new `welcometext` seems to be a clean way to "fix" the existing semantics, while also allowing administrators to rely on the `welcometext` as a rotating MOTD.

I am a far cry from a competent C++ developer, but I can give it whirl in the coming days.

**Comment by Krzmbrzl** [comment]
> I am a far cry from a competent C++ developer, but I can give it whirl in the coming days.

Hehe ^^
Updating the Ice stuff is actually a rather weird process that requires some fiddling. I could take over that part if you want. At least I have done that before, so maybe I'll figure that out again faster :sweat_smile: 
If you want to give it a shot though, by all means: do :D
