### ISSUE TITLE
Linux build external language support

### ISSUE THREAD

**Issue by ViBE-HU** [mumble-voip/mumble#4796]
Mumble [Windows build has already have this feature](https://wiki.mumble.info/wiki/Language_Translation#Testing_The_Results_.28intended_for_developers_only.29). I guess I'm not alone with that but my main OS is Ubuntu and this feature is Windows exclusive at the moment. As a translator it's a bit confusing that I cannot test the translated file step by step. And since the Mumble releases not contains the fresh translations it would be a nice feature.

**Comment by Krzmbrzl** [comment]
@ViBE-HU I assume you are referring to being able to download the translation files and then simply "swapping them into" your Mumble installation?

@Kissaki do you know something about this?

**Comment by ViBE-HU** [comment]
Yes. The installed version can read the external language file .po file.

**Comment by Kissaki** [comment]
And the Linux version can not do that? Or you do not know where to place the files so they are found by Mumble?

**Comment by ViBE-HU** [comment]
If it can do that then I don't know how. I tried several ways but none of them worked. I tried the very common folders:

` ~/.config/Mumble`
` ~/.local/share/Mumble/Mumble`
` /usr/share/locale/hu/`

I tried .mo/.po/.ts formats and used _mumbe_ and _mumble_xx_ filenames.

**Comment by Krzmbrzl** [comment]
Looking at the source code
https://github.com/mumble-voip/mumble/blob/e2b648103713683d8bbe197ae8c459a6551316c7/src/mumble/main.cpp#L513-L519

you have to place the translation files into the "application dir" of Mumble. Quoting from the [Qt docs](https://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath):
> Returns the directory that contains the application executable.
>
>For example, if you have installed Qt in the C:\Qt directory, and you run the regexp example, this function will return "C:/Qt/examples/tools/regexp".
>
>On macOS and iOS this will point to the directory actually containing the executable, which may be inside an application bundle (if the application is bundled).
>
>Warning: On Linux, this function will try to get the path from the /proc file system. If that fails, it assumes that argv[0] contains the absolute file name of the executable. The function also assumes that the current directory has not been changed by the application.

Therefore you have to locate where the Mumble binary lives (probably doable via `whereis mumble` and then place the translation files into that directory (using the `mumble_` prefix). That should result in your local translation file being used over the bundled one.

**Comment by ViBE-HU** [comment]
I checked on Ubuntu and it is placed in `/usr/bin/mumble` folder. It reads tha external language files if I place there. But this is very uncommon and it's system area. `~/.config/Mumble` or `~/.local/share/Mumble/Mumble` would be better and less harmful on Linux.

**Comment by Krzmbrzl** [comment]
I agree. But at least this verifies that the system works in principle. Extending it to pick the data from a different directory should be really easy :+1:
