### ISSUE TITLE
Mac OS 1.3.3 won't install

### ISSUE THREAD

**Issue by FunCoder2021** [mumble-voip/mumble#4800]
**Describe the bug**

**Steps to Reproduce**
1. Go to 'https://www.mumble.info/downloads/
2. Click on 'for macOS >= 10.13 (x64)'
3. Open the file

**Expected behavior**
The program should install

**Screenshots**

<img width="419" alt="Screen Shot 2021-02-27 at 7 58 51 AM" src="https://user-images.githubusercontent.com/40500696/109391284-85040d80-78d3-11eb-9e2f-a4c858e392db.png">

**Desktop (please complete the following information):**
 - Mac OS

**Additional context**
my macOS is 10.14.6

**Comment by Krzmbrzl** [comment]
This is because the Mumble binary is not (yet) certified by Apple (see #4263)

For working around this have a look at https://macresearch.org/fix-cant-be-opened-because-apple-cannot-check-it-for-malicious-software/

**Comment by Devon7** [comment]
No $99 ransom to Apple!  Their contempt for customers drives me to Debian.

MacOS 10.14.6 "Mojave" refused to open it:
`Apple > System Preferences > Security & Privacy > General > Open Anyway` grayed out

But this worked:
`Right-Click Mumble-1.3.3.dmg >`
```
	“Mumble-1.3.3.dmg” can’t be opened because Apple cannot check it for malicious software.
	This software needs to be updated. Contact the developer for more information.
	Firefox downloaded this file today at 18:43 from www.mumble.info.
	(?)                                                            [   Open   ]  [  Cancel  ]
```
`> Open > Mumble install window opens … drag'n'drop Mumble into Applications`
