### ISSUE TITLE
Provide new static linux server or alternative (v.1.4)

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4801]
**Description:**
I haven't seen an open issue for this, so I thought I might open one to discuss the issue and note the progress.

The basic problem is that the software that is used for the static builds is outdated, so we would need an alternative.

But I also see disadvantages in a "classic" static package, mainly outdated software, so it might be worth to discuss whether a classical static server is a good idea at all.
There are several alternatives, such as LXD and Docker images or snap which would be updated regularly, so these could replace the static server package instead.

Thus there are several options:
- "Classic" static package:
   - https://github.com/lexesv/static-murmurd , also mentioned here: https://github.com/mumble-voip/mumble/issues/2721#issuecomment-283506828
   - flatpak, see: https://flatpak.org/faq/#Can_Flatpak_be_used_on_servers_too_
   - Appimage
- Dynamic Container(-like) solution:
   - Snap
   - LXD 
   - Docker

**Comment by Krzmbrzl** [comment]
There is already a flatpak package (https://www.flathub.org/apps/details/info.mumble.Mumble) and also a snap package (https://snapcraft.io/mumble). Both are maintained by 3rdParties.

There are also various Docker images for the server floating around out there.

We are working on getting the AppImage to work again though. Just recently the static linux environment got fixed up (by vcpkg) to a point that it produces a working application. This we want to use as the basis for a new AppImage.

The AppImage thingy is tracked in #3959 and #4659

**Comment by toby63** [comment]
> There is already a flatpak package (https://www.flathub.org/apps/details/info.mumble.Mumble) and also a snap package (https://snapcraft.io/mumble). Both are maintained by 3rdParties.

Those are Mumble Clients not servers.

> There are also various Docker images for the server floating around out there.

An official one would be better and yea I know about the Dockerfile, but that is not really visible in a central place.
Reason for this is that people would avoid potential "harmful" or outdated custom Dockerfiles out there.

> We are working on getting the AppImage to work again though. Just recently the static linux environment got fixed up (by vcpkg) to a point that it produces a working application. This we want to use as the basis for a new AppImage.

Ok, thx for the information, so Appimage is the replacement then?

> The AppImage thingy is tracked in #3959 and #4659

Not the best and descriptive issues tbh.

---

By the way:
I could provide an LXD profile (something similar to a Dockerfile), if you are interested in that.

**Comment by Krzmbrzl** [comment]
Yes AppImage is what we are currently planning as a replacement.

> An official one would be better

We were planning on going down that route bht the person that wanted to do it, never actually picked up the work :shrug:

> Not the best and descriptive issues tbh.

Well we have this on our ToDo list anyways, so it doesn't really matter ^^

> I could provide an LXD profile (something similar to a Dockerfile), if you are interested in that.

What is the difference/advantage of LXD over Docker? I have never heard of that.

**Comment by toby63** [comment]
> Yes AppImage is what we are currently planning as a replacement.

:+1:

>> An official one would be better

> We were planning on going down that route bht the person that wanted to do it, never actually picked up the work :shrug:

Ok, sad for the docker users. Well as I don't use Docker anymore I can't provide it either, even though a theoretical script would be possible, but it should be tested of course :smile:.

>> Not the best and descriptive issues tbh.

> Well we have this on our ToDo list anyways, so it doesn't really matter ^^

Ok.

> What is the difference/advantage of LXD over Docker? I have never heard of that.

It's basically just an alternative to Docker.
I don't know if there are any advantages.
I switched from Docker to LXD some time ago, thus I could do something for that.

**Comment by Krzmbrzl** [comment]
Looking at https://www.educba.com/lxd-vs-docker/ I don't see real advantages of using LXD over Docker.
If we were to add an LXD image, then we'd also have to support it, increasing maintenance work. I don't think that is worth it (at the moment).
You are more than welcome to create an inofficial LXD image though.

**Comment by pataquets** [comment]
On recent Docker versions you can build directly from source on Github:
```
docker build -t mumble-server github.com/mumble-voip/mumble
```
I'm not sure if/how you can checkout specific tags/branches.

**Comment by JuniorJPDJ** [comment]
>I'm not sure if/how you can checkout specific tags/branches.

Using hash character after address:
https://docs.docker.com/engine/reference/commandline/build/#git-repositories

**Comment by JuniorJPDJ** [comment]
Also docker images are open standard compliant with more runtimes like podman. I'd stay with just docker-compatible build recipe as it's main standard for application containers.

LXD and snap are totally different things.

LXD is VM-like runtime running on top of LXC, so should be maintained like VMs and bare-metal - eg. with ansible.

Snap is very poorly supported beyond ubuntu and I wouldn't really support it.
