### ISSUE TITLE
Is it possible to set frequency range of encoded voice?

### ISSUE THREAD

**Issue by MarioPL98** [mumble-voip/mumble#4802]
I've noticed that mumble cuts off a lot of lower and higher frequencies. How can I disable this filter or allow it to use wide range? If it's not possible yet, I will make a feature request.

**Comment by Krzmbrzl** [comment]
I am rather sure this is simply the Opus Codec doing its work :thinking: 
Do you know of other applications that use Opus and do not suffer from this?

**Comment by Green-Sky** [comment]
> Do you know of other applications that use Opus and do not suffer from this?

well, YouTube. And most people don't even know :D .

**Comment by Krzmbrzl** [comment]
YT is using Opus? Interesting. That I indeed did not know ^^
But I assume that the way Opus is being used there differs to how we are using it since we want to use it for realtime audio transmissions (while keeping a reasonable small footprint on the bandwidth)

@MarioPL98 have you played with the audio quality settings yet?

**Comment by MarioPL98** [comment]
I have it on 96Kbps, maxed out. In audacity there is much more bass and "depth" of voice than there is on Mumble. When I hit my desk, in Audacity it sounds like a drum, while in mumble it's less than a knock.

**Comment by MarioPL98** [comment]
Is it possible to increase frequency range of this codec, so it sounds similar to aac?

**Comment by Johni0702** [comment]
Mumble by default uses Opus' VOIP mode, Opus also has an AUDIO mode which is probably what you're looking for:  https://github.com/mumble-voip/mumble/pull/2542

**Comment by MarioPL98** [comment]
How do I use this? I tried adding useopusmusicencoding REG_SZ in audio but it doesn't seem to work. How can I confirm if it works?

**Comment by Krzmbrzl** [comment]
@MarioPL98 which OS are you on?

**Comment by MarioPL98** [comment]
Windows 10

**Comment by Krzmbrzl** [comment]
>  I tried adding useopusmusicencoding REG_SZ in audio

What exactly did you do in this step?

**Comment by MarioPL98** [comment]
I added a new value in regedit under Mumble/audio.

**Comment by Krzmbrzl** [comment]
I think you are using the wrong name and you are creating it in the wrong position:
https://github.com/mumble-voip/mumble/blob/067c7504eac422c918212c959720b9ecd8079d26/src/mumble/Settings.cpp#L647

From this I would assume that you have to create the key under `HKEY_CURRENT_USER\Software\Mumble\codec\opus\encoder` and then name that key `music`.

Note also that it seems like this setting has been removed in 1.4.0, so this approach only works with the 1.3.x series.
