### ISSUE TITLE
Ice callback for broadcasting welcome message

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#4805]
**Context**
#4794 removed the automatic broadcasting of the welcome message set via Ice. In #4788 however @deluxghost said that this automatic such a broadcasting is actually useful though.

**Describe the feature you have in mind**
Therefore we concluded (https://github.com/mumble-voip/mumble/issues/4788#issuecomment-786071267) that there should be a new Ice callback that allows to explicitly send out the current welcome message. This way a server admin can set the new welcome message and then explicitly broadcast it in order to get the old behavior back.

**Comment by Krzmbrzl** [comment]
@KetchupBomb do you want to give this a shot or shall I take over this part?

**Comment by KetchupBomb** [comment]
Yeah, lemme give it a whirl. Though don't hesitate to kick me off if my code is so bad that you're unable to continue giving good support as you have been so far.

I'm essentially going to follow #2221 for modifying `Murmur.ice` and implementation. I'll also refer back [ZeroC Documentation](https://doc.zeroc.com/). Any other advice to give?

**Comment by Krzmbrzl** [comment]
> Are there docs for extending the Slice definitions, or is it tribal knowledge?

Unfortunately this is currently tribal knowledge. It is even tribal knowledge that has almost been forgotten in the tribe as well (at least I can't remember 100% what steps were necessary).
I definitely wanted to document the necessary steps when I have figured them out again :sweat_smile: 

In general though I am rather sure that calling `slice2cpp` is not necessary. Iirc this is handled automatically either by cmake or by the `generateIceWrapper.py` :thinking: 

But I'll try to get into this myself again by taking over this issue here and then I can hopefully document it :point_up:
