### ISSUE TITLE
[BUG] Mumble Overlay does not work in Escape From Tarkov

### ISSUE THREAD

**Issue by slize26** [mumble-voip/mumble#4825]
**Describe the bug**
The overlay is enabled in the settings of mumble, but does not show in Escape From Tarkov. Its working fine in CS:S for example.

**Steps to Reproduce**
1. Enable the overlay
2. Open Escape From Tarkov
3. The overlay is missing

**Expected behavior**
The overlay does not get displayed, but the correct DLL (mumble_ol_x64.dll) is loaded by the mumble client into the game.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Murmur 1.3.4

**Additional context**

**Comment by Krzmbrzl** [comment]
@davidebeatrici could you have a look, please?

**Comment by davidebeatrici** [comment]
@slize26 Do you perhaps know what renderer the game is using? Our overlay library doesn't support Vulkan yet.

**Comment by slize26** [comment]
Hey, thanks for the fast reply. They are using Unity https://unity.com/de as engine and as far as i know Directx11 as renderer.

**Comment by davidebeatrici** [comment]
In that case it should just work, as the library supports Direct3D 9, 10 and 11.

**Comment by Kissaki** [comment]
Not necessarily in all cases though. Anyway that’d be a task for further analysis.

I don’t own the game (apparently still in closed beta?). If you want to take a look, check the debug console, and for it to log more information, place a file called `debugoverlay` next to your exe. It may give some info on failed hooks, failures, or why it does not attempt to work.

**Comment by slize26** [comment]
I will check the log tomorrow and post the results here.

Tarkov is still in beta, but not closed beta. (https://www.escapefromtarkov.com/) As i understand you need an account to access the game to fix it, right?

**Comment by Kissaki** [comment]
What is the context of that log? Startup? In rendering? On shutdown? A combination of them?

Looks like it indeed initializes into D3D11, and does resize to a resolution. No problems immediately visible.

Having the game could help in debugging the issue of why it does not show up.

**Comment by slize26** [comment]
I startetd and stopped the game, yes. And the log seems fine to me aswell. But there was no overlay. Its working fine in other games. 

Alright and i dont think you want to buy the game for that ;-). Do you got another way for me to contact you?

**Comment by seniorm0ment** [comment]
Doesn't Tarkov use Battleye?
If so, I presume Battleye is blocking it (just like with Rainbow Six Siege)

**Comment by Krzmbrzl** [comment]
If BattleEye is used then that would indeed explain the issue. It is known that BattleEye blocks the Overlay (and ignores our request to whitelist it)...

**Comment by skobkin** [comment]
@Krzmbrzl https://forum.escapefromtarkov.com/topic/101954-%D0%B0%D0%BD%D1%82%D0%B8%D1%87%D0%B8%D1%82-battleye/

It basically says that they're adding BattleEye to their game.

I think this issue should be opened or better to create a separate issue until BattleEye problems aren't fixed. AFAIR, there are several games where overlay isn't working because of BE anti-cheat. For example I'm getting a warning from BE each time I start R6: Siege.

**Comment by Krzmbrzl** [comment]
No there is no point in having an open ticket about this, since this is nothing we can do about it.
We already reached out to BattleEye but have been ignored. If you want to bring this forward, you can start poking BE about it because it is them that have to take action :shrug:

**Comment by skobkin** [comment]
> No there is no point in having an open ticket about this

It's be a good point of entry for users who wants to know why Mumble overlay doesn't work in their game.

**Comment by Krzmbrzl** [comment]
It's listed as a known issue in the release announcement: https://www.mumble.info/blog/mumble-1.4.230/#known-issues
