### ISSUE TITLE
Missing or not working translatable/translatated strings

### ISSUE THREAD

**Issue by ViBE-HU** [mumble-voip/mumble#4834]
Maybe this is not a bug but I don't find some string in the language files Most of them related with the updates. I did not collected all of them but here's an example when manually check update:

> You have the latest version.

Another related issue is that the translated text just won't appears. An exact example in the `ConnectDialogEdit` section:

> Ignore

The translated text never appears for some reason. Tested the latest 1.3.4 x64 build on Windows 10 and Ubuntu 20.04. Both have this issue.

**Comment by Krzmbrzl** [comment]
What version are you referring to? When reporting bugs it'd be nice if you could use the template for bug reports :point_up: 

I am not quite sure I understand what you are trying to explain. You found some Strings that don't get translated? Are you sure these Strings even _are_ translated in the first place?

Note also that e.g. the `ConnectDialog.cpp` class does not seem to even contain the String `Ignore`, so I am not sure how you got this to appear :eyes:

**Comment by ViBE-HU** [comment]
Sure. Checked the Weblate sources. Some strings are not even in the English translation like the update related message above.

The _Ignore_ button appears when Mumble detects that there are some host address on the clipboard has been copied. You can check the translation on Weblate. It already contains the following string:

```
    <message>
        <source>&amp;Fill</source>
        <translation>&amp;Kitöltés</translation>
    </message>
    <message>
        <source>&amp;Ignore</source>
        <translation>&amp;Elvetés</translation>
    </message>
```

Every strings what are related with that window are translated but this is the only word what appears still in English while I tested.

![kép](https://user-images.githubusercontent.com/640109/110240833-13b90000-7f4e-11eb-95c2-aa43c01adbc7.png)

**Comment by Krzmbrzl** [comment]
> What version are you referring to?

**Comment by ViBE-HU** [comment]
Oh, I already added details to the report. 1.3.4 x64, Windows 10 and Ubuntu 20.04.

**Comment by Kissaki** [comment]
We currently have a discrepancy between the Weblate translation texts which are our current development source code version in the master branch.

The 1.3 strings may be part of this. But new translations are not currently backported to 1.3. We are looking at ways to do so in the future. See #4740

Does this answer your question?

**Comment by ViBE-HU** [comment]
Not sure. But looks like not. Back in the days I just used Mumble. The translation was usually up to date. Then my gaming community just "died" and I had no reason to use it. Then I started to revive my servers and when I installed 1.3.2 I noticed the tons of not translated and not accurate strings. This is the reason why I started the maintenance of the translation. So I already noticed these issues since the Transifex translation. In this case I'm absolutely sure that this difference is not related with Transifex or Weblate.

**Comment by Krzmbrzl** [comment]
But you are using an older version of Mumble (older of the current master branch - aka 1.4.0 snapshot) and thus the translation file that you get from Transifex/Weblate is for a newer version of the code (current master branch).
That's the discrepancy that Kissaki mentioned.

Thus it'd be very interesting whether these issues still apply to the 1.4.0 snapshots (downloadable on our website) and if yes, if the issue still persists when building Mumble yourself from current master branch (not sure if you can/want do the latter though)

**Comment by ViBE-HU** [comment]
Now I got it. I will take a try soon with the snapshot. Btw snapsots: I don't see too much Ubuntu snapshots nowadays in the snapshot PPA. Is this normal?

**Comment by Krzmbrzl** [comment]
> I don't see too much Ubuntu snapshots nowadays in the snapshot PPA. Is this normal?

Yes. We simply did not get to setting up PPAs for the new build environment yet. It's on our ToDo list though.

On Linux you currently have to build Mumble yourself, following [these instructions](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md)

**Comment by ViBE-HU** [comment]
I downloaded and tested 1.4.0 snapshot on Windows. Now the _Ignore_ works but some others expressions are now English.

![connect](https://user-images.githubusercontent.com/640109/110256078-33c0e180-7f97-11eb-8d4e-6bf76675f2ac.jpg)

The _You have the latest version_. message is still English. Are the Weblate files fresh? I mean does it really follow the actual snapshots? I would build snapshots but I'm a real noob and it does not really helps in this case that I'm a long-term Linux user.

**Comment by Kissaki** [comment]
Missing translations will fall back to the English source text. Without having checked my first assumption would be that these texts were not translated.

Specifically, for Connect I know that is the case. Because the mnemonic key was changed from C to o, which invalidated the translation.

(I want to look at this later, whether we can keep partial, similar strings. I feel like the lupdate similar heuristic may be useful for this. But at the moment a changed source string will invalidate the translation.)

I am kinda surprised about OK and Cancel though. Those should be standard and be translated. I guess they are not native from the OS? Not a native dialog?

**Comment by ViBE-HU** [comment]
I guess yes. May those missing from the language files. Cause I translated these very common words already. But _Cancel_ is a strange exception. _Reset_ and _Default settings_(?) buttons are now English too.

What native mean in this case? You mean the OS language/region setting? Cause if yes that's cannot be a problem. The environment is Hungarian on Windows and ubuntu too.

**Comment by Kissaki** [comment]
Sometimes programs use platform native controls that a standard library provides. Other times dialogs are implemented with custom buttons.

I also think to remember that the reset to default buttons may have changed. Something about the descriptions? I am not sure though. Either way it's verifyable in the current files and Weblate whether they are translated or not and what happened is verifyable in the files git log.

**Comment by Krzmbrzl** [comment]
Iirc the `Cancel` button is not a standard button from Qt but one that we set the text on explicitly. This might be the reason why it is not already translated by default

**Comment by ViBE-HU** [comment]
> I also think to remember that the reset to default buttons may have changed. Something about the descriptions? I am not sure though. Either way it's verifyable in the current files and Weblate whether they are translated or not and what happened is verifyable in the files git log.

You mean the hints when move over the mouse on the buttons? All appears as translated (even _Cancel_ and _OK, Apply, Reset, Restore Default_). The only exception is restore _Defaults (All)_. But that's a new button afaik.

@Krzmbrzl Done already.

**Comment by Kissaki** [comment]
So can we close this? Think we answered that they are not expected in 1.3 currently (#4740), and those that were missing are not translated yet.

**Comment by ViBE-HU** [comment]
Yes then.
