### ISSUE TITLE
1.4 Linux 1.4 snap release date update?

### ISSUE THREAD

**Issue by sfwright101** [mumble-voip/mumble#4844]
I work with a big community of amateur (ham) radio operators who use Murmur/Mumble for remote audio operation of their radio setups.  I have built/installed Linux 1.4 beta and find it vastly superior to 1.3x for quieter backgrounds when noise suppression (RNNoise, etc) is turned off.  Anybody have an idea when the Linux 1.4 snap version will be released?  Right now a CMake build is far too complex for most users to try themselves.  Thanks!

**Comment by Krzmbrzl** [comment]
We actually don't maintain a snap package. The existing one(s) is maintained by some external developers. Thus we can't tell when they'll decide to update (or whether they will provide snapshots at all).

What we do have on our ToDo list though is updating the PPA and providing a working AppImage. Unfortunately I can't give you an ETA for that.

In terms of build complexity: Using cmake is actually very straight forward. Especially on Linux. Are you aware of our build instructions at https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions ?
I think following these steps should be easily doable even if you don't understand what that is supposed to do :)
It obviously doesn't replace proper releases but for the time being that is the only option.

**Comment by sfwright101** [comment]
Thanks for your quick/thorough response!   I’ll let our stakeholders know
about the uncertain ETA.  Yes, I did the cmake process to build/install 1.4
on  Raspberry Pi 4B.   Fun!  Took about two hours, other than being slow,
no problem.  Instructions are crystal clear.

Problem is, many of our users are older, borderline PC literate, zero
Pi/Linux,  so the full build is, unfortunately, not realistic.   Even
simple stuff is a challenge.  They live in retirement homes that prohibit
all the big antennas required, so we build them remote access capabilities
allowing them to remotely control radio stations via the internet,
sometimes 1000 km away.
They use speech and Morse code.  Low background for non-speech is
especially critical for pulling low level code signals from background
noise.  Both of Mumble’s noise reduction packages of course favor speech,
so Morse code at lower signal strength gets treated as noise.  Only 1.4
allows us to totally kill noise processing.  Even with all settings off
(RNNoise, etc.), 1.3x versions still show significant noise reduction is
being applied.  You can hear the signal quiet down about 5 sec after
connecting.

I really appreciate the work you and your teammates do for Mumble/Murmur.
Super efficient, low latency app!

Steve Wright (KE4LC)

**Comment by Krzmbrzl** [comment]
> Problem is, many of our users are older, borderline PC literate, zero
Pi/Linux,  so the full build is, unfortunately, not realistic.

Indeed. In that case I am afraid that currently you'll have to tell them that they'll have to wait. Sorry :shrug: 

> I really appreciate the work you and your teammates do for Mumble/Murmur.
Super efficient, low latency app!

Thanks for your kind words. Much appreciated :blush:
