### ISSUE TITLE
Mumble can't connect to minecraft server

### ISSUE THREAD

**Issue by GalaxyGamerYT** [mumble-voip/mumble#4849]
![image](https://user-images.githubusercontent.com/66827801/110690775-382a0c00-81dc-11eb-9c48-7fcc217c7927.png)
How do I fix this?

**Comment by Kissaki** [comment]
Are you the server operator/hoster?

If not, contact the server hoster so they fix it, or switch to an alternative server.

**Comment by GalaxyGamerYT** [comment]
Oh wait do I have to host a server then I thought it just went off the minecraft server

**Comment by GalaxyGamerYT** [comment]
Do you mean the minecraft server host or do i need to make a mumble server to connect to?

**Comment by Krzmbrzl** [comment]
To make it very explicit: The Minecraft server and the Mumble server are in no way, shape or form related to one another.
(At most it could happen that these server programs happen to run on the same hardware, but for your problem this would be irrelevant anyways)

**Comment by toby63** [comment]
I assume @GalaxyGamerYT is talking about a Mumble Server which is titled something with "Minecraft".

So @GalaxyGamerYT:
You don't have to host a server yourself (but you can).
But if want to use that server you mentioned, you should contact the Server owner, so he can update his server. If you have no contact information, then there is nothing that can be done about it.

**Comment by toby63** [comment]
1. In that case I think the error message should be fixed, because it should not show this misleading message if the client is not even connecting to a mumble server.
2. The main problem is that the user simply ignored the issue template that should be filled out.
