### ISSUE TITLE
Mumble does not display most icons inside the UI as of yesterday

### ISSUE THREAD

**Issue by 2xsaiko** [mumble-voip/mumble#4853]
**Describe the bug**
After rebooting after yesterday's system update (I believe this is caused by the KDE Frameworks 5.80.0 update since that was most of -) all the icons are missing from Mumble except for the configuration button icon. Changing the Mumble theme to anything that isn't None also doesn't help.

**Steps to Reproduce**
1. Open Mumble
2. ???
3. Icons are either missing entirely, replaced by the "empty document" icon, or replaced by their icon text.

**Expected behavior**
The icons should be displayed as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/3987560/111078654-e264a500-84f6-11eb-97b5-279cd6aab792.png)

**Desktop (please complete the following information):**
 - OS: Gentoo x64 unstable
 - Version: media-sound/mumble-9999 (commit f5177b8)

**Additional context**
[This][1] is a list of everything I've updated yesterday.

[1]: https://paste.2x.ax/~saiko/eeb6bb74e12697dd1ede4f49d69dfcd01b3da631

**Comment by lutobler** [comment]
I can confirm this, looks the same for on Arch Linux as of today.

**Comment by Kissaki** [comment]
May be related to #4856 if it does not find embedded resources anymore. cc @Krzmbrzl

**Comment by Krzmbrzl** [comment]
I don't see this being related to the translation issue. Plus I still see all icons as expected...

I tried this out with the latest  version on master (which is also f5177b8bfac723c950e78a1143e5633c275b926c) both in Debug and Release mode, but I can't reproduce this issue.
I am using KDE Neon using KDE Plasma 5.21.2 and KDE frameworks 5.79.0 (Qt 5.15.2)

@2xsaiko @lutobler are you perhaps using Wayland instead of X11?

**Comment by 2xsaiko** [comment]
> are you perhaps using Wayland instead of X11?

Nope, this is X11.

> Did you also update Qt yesterday before this happened?

Not sure if that's what you meant but I'm pretty sure it was the KDE Frameworks update for me (if that's correct, and it does happen with 5.80.0, it would explain why you don't get this issue). I haven't had a Qt update in some time.

**Comment by Krzmbrzl** [comment]
> Not sure if that's what you meant but I'm pretty sure it was the KDE Frameworks update for me

Yes this is exactly what I meant. But for some reason I only wrote "Qt" xD

> if that's correct, and it does happen with 5.80.0, it would explain why you don't get this issue

That could be (though I am really buffled by the fact that a different distro gets KDE updates before I do on KDE Neon :sweat_smile:  )
@lutobler what version of KDE Plasma, KDE frameworks and Qt are you using (Are you even using KDE)?

**Comment by davidebeatrici** [comment]
I would make sure that the SVG plugin for Qt is installed (the settings icon is PNG, we have to replace it).

On Arch Linux: `sudo pacman -S qt5-svg`

**Comment by lutobler** [comment]
@Krzmbrzl I have updated to Qt 5.15.2 and KDE framework is on 5.80.0 (`qt5-svg` is installed). I am running on X11, but not on KDE Plasma, just using a window manager (herbstluftwm).

**Comment by Krzmbrzl** [comment]
Then maybe the issue is indeed KDE frameworks 5.80.0? :thinking:

**Comment by SingularityCat** [comment]
I can also confirm this, Mumble did indeed stop drawing icons (aside from the settings icon) after updating to KDE frameworks 5.80.0 on Arch Linux.

Specifically, this seems to involve the `kiconthemes` part of it, downgrading from 5.80.0-1 to 5.79.0-1 restores the icons.

**Comment by Krzmbrzl** [comment]
Yep I just got the update myself and now I also have KDE frameworks 5.80.0 and all of a sudden the icons are gone.

**Comment by Krzmbrzl** [comment]
Upstream bug reported: https://bugs.kde.org/show_bug.cgi?id=434451

**Comment by murlakatamenka** [comment]
> Mumble did indeed stop drawing icons (aside from the settings icon) after updating to KDE frameworks 5.80.0 on Arch Linux.
> 
> Specifically, this seems to involve the `kiconthemes` part of it, downgrading from 5.80.0-1 to 5.79.0-1 restores the icons.

Can confirm. Downgraded, icons are back. Before that only settings icon was shown, as it's png as @davidebeatrici has mentioned.

Out of curiosity, how comes that KDE frameworks broke it? I'm using i3 but have Plasma installed too (rarely use it lately) and this happens :thinking: `qt5ct`

**Comment by Krzmbrzl** [comment]
> Out of curiosity, how comes that KDE frameworks broke it?

I don't even have a suspicion how these frameworks interact with Mumble :shrug:

**Comment by Krzmbrzl** [comment]
According to the linked bug report this is the commit that breaks the icons: https://github.com/KDE/kiconthemes/commit/5666c0c46e913fecbe2b41157f241685f126ab30

**Comment by murlakatamenka** [comment]
@Krzmbrzl thanks

It wasn't planned :smile: 

> Ok, this is naturally unintended :/
