### ISSUE TITLE
Decide on monolingual vs bilingual translation workflow approach

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#4855]
The mumble_en.ts file is of no use. We use it as a translation source, which is not necessary, as we currently use en text as source texts.

Using an ID based approach may solve us losing translations on fixups though. So we may want to switch to that instead.

Analyse this in relation to our current conflicts with the always update translations on changes too.

**Comment by Krzmbrzl** [comment]
It seems this has stalled so far? I think we should either decide on something or close the issue as a dead issue is of no value to us :eyes:

**Comment by Kissaki** [comment]
I’ll close it then. I doubt anyone else will look at this now, our current workflow works well enough.
