### ISSUE TITLE
Regression: Translations are no longer applied

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#4856]
**Describe the bug**
Mumble (latest Git version) no longer applies the translations. The whole UI is in English, regardless of the system locale or Mumble settings.

**Steps to Reproduce**
1. Start Mumble
2. Notice that the UI language is always English

**Expected behavior**
The UI language should match the system locale.

**Desktop:**
 - OS: Arch Linux
 - Mumble version: Git (compiled today)

**Additional context**
This is very likely a regression from commit 0dcc1f614b2ab4f0d4bbac5fd29676595072a133.
Reverting it together with commit fcabef87d996cc21dcc0f8a817d894776e286c3d (due to conflicts) restores the correct behavior.

**Comment by Kissaki** [comment]
Probably related to #4820, @Krzmbrzl can you take a look?

**Comment by Krzmbrzl** [comment]
@radioactiveman what does the Mumble UI state for the selected language (in the settings)? Does it say "System default" (or something like that)?

**Comment by radioactiveman** [comment]
@Krzmbrzl:

Console output:
> <W>2021-03-15 19:29:27.070 Locale is "de_DE" (System: "de_DE")

Settings UI:
> Language: System default

But even changing it to German here does not change the UI language.
To reproduce this on Linux you can also overwrite the system language for example with
```bash
$ LC_ALL=de_DE.UTF-8 mumble
```

**Comment by Krzmbrzl** [comment]
Yikes. Then I really must have broken something :see_no_evil: 

I'll look into this :point_up:

**Comment by Krzmbrzl** [comment]
Ok I found the issue: The `QApplication` does not make a copy of the installed translator and thus the translator object has to remain alive for the translation to work out. Interesting though that the application doesn't simply SegFault :shrug:

**Comment by radioactiveman** [comment]
@Krzmbrzl: Thanks for the fix. :+1: 

Some buttons are still not translated though, but have been in the past.
I guess these use the translations from Qt, not Mumble itself.
Affected buttons are for example "Cancel" in the connect dialog and "Apply", "OK", "Cancel" in the settings dialog.

**Comment by Krzmbrzl** [comment]
Were these buttons translated immediately before my tinkering with the translations? :eyes:

**Comment by radioactiveman** [comment]
Yes, the buttons were translated until commit 8d1d77772ef0169a2e8eba81138f372df6d84632.

**Comment by Krzmbrzl** [comment]
Meh... Okay let me look into this agin

**Comment by Krzmbrzl** [comment]
Okay I can't reproduce these buttons being translated at 8d1d77772ef0169a2e8eba81138f372df6d84632. For me they remain in English.

I did however find another issue with how the Qt translations are searched for, so maybe this fixes the issue for you regardless :shrug:
