### ISSUE TITLE
mumble 1.3.4 creates libmumble.so.1.3.3

### ISSUE THREAD

**Issue by carlwgeorge** [mumble-voip/mumble#4857]
**Describe the bug**
Building mumble from the [1.3.4 tag](https://github.com/mumble-voip/mumble/tree/1.3.4) results in a `libmumble.so.1.3.3` file.

**Steps to Reproduce**
1. Run `make release` from the 1.3.4 tag.
2. Observe that the file `release/libmumble.so.1.3.3` is created.

**Expected behavior**
The file should be named `release/libmumble.so.1.3.4`.

**Desktop (please complete the following information):**
 - OS: Fedora 35 (rawhide)
 - Version: Mumble 1.3.4

**Additional context**
I compared the files modified in 6863742b2efd783a13148c3f348d9242eaca331a and c0b5be7134673fa1c4c434b72552c200bca37b8d, and the only difference I see is `overlay_gl/overlay_gl.pro`, which indeed [still has version 1.3.3 in the 1.3.4 tag](https://github.com/mumble-voip/mumble/blob/1.3.4/overlay_gl/overlay_gl.pro#L13).

**Comment by Krzmbrzl** [comment]
Did you try manually updating the version in `overlay_gl/overlay_gl.pro` to see if that fixes the issue? 'cause I am actually suspecting that `libmumble.so` is in fact the overlay binary...

**Comment by davidebeatrici** [comment]
I confirm it is.

**Comment by Krzmbrzl** [comment]
Should be fixed via #4859
