### ISSUE TITLE
Windows Scale and Layout vs Logitech G15

### ISSUE THREAD

**Issue by as-spaargaren** [mumble-voip/mumble#4861]
**Describe the bug**
The Logitech G15 screen follows the Windows Scale and Layout.
When windows is scaled at 150%, the G15 s also scaled at 150%.

**Steps to Reproduce**
1. Go to '...' Windows 10 settings, display, Scale and layout
2. Click on '....' Change the size of text, apps, and other items
3. Scroll down to '....' anything other than 100%
4. See error  G15 (mumble) screen also goes to the percentage selected.

**Expected behavior**
I expected the G15 to stay at 100% scale regardless of the Windows 10 settings for my big displays.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]  Windows 10
 - Version: [e.g. Mumble 1.3 or Murmur 1.3] Mumble 1.3.4  (also older versions)

**Additional context**

**Comment by Krzmbrzl** [comment]
I think I don't understand. Why would you expect these elements to remain at their original size?

**Comment by as-spaargaren** [comment]
Mumble messes up the letters on the G15 screen.  [Root:  ]  and every other line is missing lines.
![IMG_1618](https://user-images.githubusercontent.com/22529327/111209041-cbdc4d80-85cb-11eb-9a29-c5825275e1d3.JPG)

**Comment by Krzmbrzl** [comment]
Ah okay this is an external screen :bulb:

@davidebeatrici do you know the G15 code?

**Comment by davidebeatrici** [comment]
Unfortunately not, but the render code is in https://github.com/mumble-voip/mumble/blob/master/src/mumble/LCD.cpp.

**Comment by Krzmbrzl** [comment]
Hmm... To me it appears as if explicit font sizes are set in that code though:
https://github.com/mumble-voip/mumble/blob/88d7f31311892f50a1459c662e24cd33d2db6ecf/src/mumble/LCD.cpp#L157-L202

I assume Qt performs scaling automatically based on Window's scaling factor. See also https://doc.qt.io/qt-5/highdpi.html#microsoft-windows

According to https://www.charlesodale.com/setting-qt-to-ignore-windows-dpi-text-size-personalization we can explicitly overwrite the scaling behavior by calling `setPixelSize` on the `QFont` object. I think that'd make a lot of sense in this case. @davidebeatrici any objections?

**Comment by davidebeatrici** [comment]
No, I think that's the correct way.

**Comment by Krzmbrzl** [comment]
@as-spaargaren could you test this again with this snapshot, please? https://dev.azure.com/Mumble-VoIP/_apis/resources/Containers/5766195/Windows%20(x64)%20installer?itemPath=Windows%20%28x64%29%20installer%2Fmumble_client-1.4.0.0-x64.msi

First unistall your current Mumble installation though :point_up:

**Comment by as-spaargaren** [comment]
{"$id":"1","innerException":null,"message":"TF400813: The user 'Windows Live ID\\<<MY Github Email>>' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}

**Comment by Krzmbrzl** [comment]
@as-spaargaren in what context and where did you get thid error?
Interestingly this seems to be entirely ubrelated with the changes made in that PR :thinking:
