### ISSUE TITLE
Icons not showing up since last update

### ISSUE THREAD

**Issue by Clemenk** [mumble-voip/mumble#4865]
Since the last update Icons are no longer showing up except for the options.
Also, I cannot see checked radio buttons.

OS : Arch-Linux
Mumble version : 1.3.4-3
![image](https://user-images.githubusercontent.com/69971519/111361699-4372b100-868e-11eb-8df4-c7d8c47d572d.png)
![image](https://user-images.githubusercontent.com/69971519/111361751-55545400-868e-11eb-8804-87f2c94a82bc.png)

**Comment by Krzmbrzl** [comment]
Duplicate of #4853
