### ISSUE TITLE
users of same channel will have different order when use different OS

### ISSUE THREAD

**Issue by yifan513** [mumble-voip/mumble#4873]
As the title, the users of same channel will have different order when use different OS, such as windows vs MAC, or even windows Chinese GB VC Big5.
I checked the code
https://github.com/mumble-voip/mumble/blob/master/src/User.cpp
Hope you can think about using something like strcasecmp to replace QString::localeAwareCompare.
Thanks.
David

**Comment by Krzmbrzl** [comment]
Yep I think this can be considered a bug :+1:

**Comment by Krzmbrzl** [comment]
@yifan513 do you perhaps want to fix this yourself?

**Comment by yifan513** [comment]
Yes. I can but just do not want to spend time to setup a new building env.
If you want to put a fix to 1.4 soon, then I will wait.
If as you said 1.4 will be a little bit longer time for waiting, I may think of build the both windows and Mac version myself.

**Comment by Krzmbrzl** [comment]
I can't give a proper ETA for another snapshot release yet.

I'll go ahead and fix it then, though :+1:

**Comment by yifan513** [comment]
So is the order will be case sensitive after you fix it?

**Comment by Krzmbrzl** [comment]
Yes

**Comment by yifan513** [comment]
Good to know. Thanks.
