### ISSUE TITLE
Mumble does not show icons after system update

### ISSUE THREAD

**Issue by PajeroBajo** [mumble-voip/mumble#4874]
**Describe the bug**
After the last linux system update, Mumble no longer displays icons:
- The toolbar icons are missing, except the settings-icon.
- The channel tree only shows "broken" icons ("paper-sheet"-icon).
- In the menu masks, all checkboxes only show those paper-sheet icons instead of checkmarks.
- (The icons of the categories in the settings menu are still displayed corretly)

-- See screenshots below --
![Screenshot_20210317_231854](https://user-images.githubusercontent.com/69982039/111552382-7f873e00-8782-11eb-9da2-c2e64030ce49.png)
![Screenshot_20210317_232622](https://user-images.githubusercontent.com/69982039/111552420-9332a480-8782-11eb-88dc-f41c831bd891.png)

**Steps to Reproduce**
_Dont know if it's reproducable, but this is what happened:_
I used Mumble 1.4.0 from AUR for quite a long time without any problems.
Today I performed a system update in the usual way (`pacman -Syu`).
Pacman reported this:
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing protobuf (3.15.6-1) breaks dependency 'libprotobuf.so=23-64' required by mumble-git
```

I decided to remove `mumble-git` to perform the system update, which has worked as expected afterwards.
After the update was completed, I restarted the system and reinstalled `mumble-git` using yay.
**This is where the problem has appeared for the first time.**
I first suspected the AUR version of mumble could be broken, so i removed it and installed the stable `mumble` version from the arch repository.
But there was no difference using this version.
I also renamed the `~/.config/Mumble` folder because I expected the 1.4 config could possibly cause trouble in mumble 1.3. But this had no effect as well (on the icons).

**Expected behavior**
I did not expect to loose the icons in Mumble after a system update.
Other Qt applications (VLC, Notepadqq, virtualbox, optimusmanger-qt) work as usual and show icons and checkboxes/checkmarks.

**Desktop :**
 - OS: Archlinux, Linux 5.11.7, X11, KDE 5.21.3, Qt 5.15.2
 - Mumble-Version: Mumble 1.3.4 (arch-community-repository, 1.3.4-3); Mumble 1.4.0 (mumble-git from AUR, 1.3.0.rc2.r1232.g1808273e1-1)

**Additional context**
Tried to use the Mumble AppImage provided in azure, but that does not work as well (tested on Archlinux and Debian 9).
Problem described in issue https://github.com/mumble-voip/mumble/issues/3959

Thanks in advance for your support! :-)
_Let me know if you need any further information_

**Comment by PajeroBajo** [comment]
Okay, this is possibly a duplicate of https://github.com/mumble-voip/mumble/issues/4853 ...

**Comment by Krzmbrzl** [comment]
Indeed :+1:
