### ISSUE TITLE
Overlay does not show up in Team Fortress 2

### ISSUE THREAD

**Issue by suprovsky** [mumble-voip/mumble#4880]
**Describe the bug**
Mumble overlay does not show up in games at all. It happensin all versions since stable 1.3.1 until now.

**Steps to Reproduce**
1. Go to 'Install any Mumble version later than stable 1.3.0'.
2. Make sure the Overlay is enabled in Mumble options and make sure you've started Mumble **before** the game.
3. Start the game (in my case it's Team Fortress 2.
4. The overlay does not show up.

**Expected behavior**
The overlay should show up.

**Screenshots**
Test on `1.4.0~2021-02-23~g569336e~snapshot`: https://i.imgur.com/yyUVw4I.png
Test on `stable 1.3.0`: https://i.imgur.com/6oNow1V.png

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 20H2
 - Version: >1.3.0

**Comment by deluxghost** [comment]
I have mumble 1.3.4 and win10 20h2, but the overlay is good (I normally disable it but I just enabled it to test)
too lazy to test 1.4.0 tho

looks like you was running tf2 in noborder mode, also the same as me

**Comment by suprovsky** [comment]
> I have mumble 1.3.4 and win10 20h2, but the overlay is good (I normally disable it but I just enabled it to test)
> too lazy to test 1.4.0 tho
> 
> looks like you was running tf2 in noborder mode, also the same as me

This is weird, are there any logs/debug more which I can check in order what's going on?

**Comment by Krzmbrzl** [comment]
Did I understand you correctly that with version 1.3.0 or older the overlay works whereas in 1.3.1 and newer ir no longer does?

> are there any logs/debug more which I can check in order what's going on?

You can check the developer console and post its contents here. See https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md

**Comment by Kissaki** [comment]
When I launch Mumble 1.3.4 and then TF2 in windowed the Overlay works just fine in the main menu.

**Comment by suprovsky** [comment]
Looks like I had multiple versions of Mumble installed in my OS, deleting them and installing one version resolved the problem.
