### ISSUE TITLE
Recognize Right/Left Modifiers independently (for PTT)

### ISSUE THREAD

**Issue by Vorror** [mumble-voip/mumble#4889]
Currently, mumble only recognizes left and right modifiers(ctrl, cmd, option, etc, shift) as a single key.

Could we add an option to mumble accurately discriminate between right/left versions of a key? I prefer to use the _right_-option key for talking but I don't want it to activate when I press _left_-option.

Since I don't want to break the current PTT/shortcuts for anyone who relies on the current behavior — how about we add an checkbox option to settings to enable right/left discrimination?

**Comment by davidebeatrici** [comment]
Operating system?

**Comment by Vorror** [comment]
OSX

**Comment by Krzmbrzl** [comment]
Duplicate of #4529
