### ISSUE TITLE
Mumble 1.4.0 won't open on macOS Big Sur (Apple M1)

### ISSUE THREAD

**Issue by iJaack** [mumble-voip/mumble#4893]
**Describe the bug**
Mumble won't open at launch. It just crashes immediately.

**Steps to Reproduce**
1. Open the app

**Expected behavior**
I'm expecting the app to open.

**Screenshots**
A "Mumble quit unexpectedly" banner appears.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3 on Mac Mini M1
 - Version: Mumble 1.4.0

**Comment by Krzmbrzl** [comment]
Please start Mumble through a debugger (eg. gdb) to obtain a backtrace.

Did this only start happening recently or have you never started Mumble on that machine before?

**Comment by iJaack** [comment]
I had v1.3.3 installed, but I had the issue described in #4894 so I can't get a backtrace now.. I could try reinstalling it.

**Comment by Krzmbrzl** [comment]
In the original post you stated that this issue id with 1.4.0. So if you don't have 1.3.x installed anymore, then that's actually a good thing :eyes:

**Comment by iJaack** [comment]
Yeah, I did a lot of things today:
- uninstalled 1.3.3 (didn’t work per the problems mentioned in issue #4894, including the info the last comment)
- installed 1.4.0 pre-compiled, but that crashed at launch
- compiled 1.4.0 using the help from https://github.com/mumble-voip/mumble/issues/4876#issuecomment-809263299, and it worked for a few minutes then crashed eventually
- Turned up downloading the iPhone version from App Store and that seems to work fine, but there’s little flexibility there...

**Comment by Krzmbrzl** [comment]
The pre-compiled versions crashing is no surprise given that it is not compiled for ARM.
The self-compiled version crashing is a different matter though. This is what we need a backtrace of :point_up:
