### ISSUE TITLE
mumble positional audio not working minecraft Lunar

### ISSUE THREAD

**Issue by EnbyEmoo** [mumble-voip/mumble#4898]
Hello, I have been trying to use mumble however I have run into a issue. My friend's mumble works fine but mine isn't. I hear them no matter where they are at the same volume. I've tried everything I could find online, even switched the processor I was using, didn't help. hoping to get some help on this.

**Comment by Krzmbrzl** [comment]
Do you have the Minecraft plugin enabled? 
Did Mumble report "... linked" in the chat window?

**Comment by EnbyEmoo** [comment]
Yes to both.

**Comment by Krzmbrzl** [comment]
Is this the case for all of your friends as well?

Also wait a minute... Do you hear your friends from a certain direction but simply not quieter when they move away or do you always hear your friends as if they were standing directly in front of you no matter where they are relative to you in the game?

And your friends hear themselves from a certain direction and for them the volume fades with increasing distance? Do they hear you in the same way?

Furthermore: Which version of Mumble are you using and where did you get the Minecraft plugin from? :thinking:

**Comment by Kissaki** [comment]
Something about Lunar client also reported at https://www.reddit.com/r/mumble/comments/mh5wx9/lunar_client_help/ and https://www.reddit.com/r/mumble/comments/m4dr0w/mumble_with_lunar_on_mac/
