### ISSUE TITLE
Unexpected error verifying GPG signature on macOS with gnupg

### ISSUE THREAD

**Issue by grepmew** [mumble-voip/mumble#4900]
**Describe the bug**
Cannot verify GPG signature on macOS with gnupg

**Steps to Reproduce**
1. Install macOS 11.2.3
2. Download Mumble for macOS from mumble.info
3. Install gnupg from brew `brew install gnupg`
4. Download `mumble-auto-build-2021.asc`
5. Try to verify GPG key from downloaded file above: `gpg --verify mumble-auto-build-2021.asc mumble-1.2.19.dmg`
6. You will see an error: `gpg: verify signatures failed: Unexpected error`

**Expected behavior**
Expected to be able to verify GPG signature

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Version: mumble-1.2.19.dmg

**Additional context**
Website also says "macOS download will still refer to version 1.3.3" but the actual download seems to be mumble-1.2.19.dmg

**Comment by davidebeatrici** [comment]
The signature is `mumble-auto-build-2017.asc` for `mumble-1.2.19.dmg`.

Where are you downloading the file from, precisely? https://dl.mumble.info/latest/stable/client-macos-x64 points to the correct one.

**Comment by grepmew** [comment]
I tried to download it from https://www.mumble.info/downloads, but was confused by this text on the website:

```
Version 1.3.4 is the latest stable version of Mumble and was released on February 10th, 2021.

Note: Due to problems with our macOS builder, we are currently unable to provide 1.3.4 binaries for macOS. We are working on it, but for the time being the macOS download will still refer to version 1.3.3.
```
Clicking the big greepn "Mumble for macOS >= 10.13 (x64)" button results in downloading mumble-1.2.19.dmg.

**Comment by davidebeatrici** [comment]
Just checked: it downloads `Mumble-1.3.3.dmg`.
