### ISSUE TITLE
Trying and Unable to use Positional Audio in a Source game with Radmin

### ISSUE THREAD

**Issue by Biozeminade** [mumble-voip/mumble#4905]
Self-explanatory. Am currently trying to host a Mumble server to try positional audio for L4D2 only for the positional audio to not work at all despite all of the settings checked to "on". Same goes for my friend on his end. I am hosting the murmur server by using a Radmin network for easier online connectivity on both of our ends. 

In addition, some of the plugins for certain games that I have installed like CS:S and DOD:S aren't even appearing...
![qfOTLgpj86](https://user-images.githubusercontent.com/35079939/113501416-c5116e00-94d9-11eb-9535-96b99f820edd.gif)

Can somebody please help us out and tell us what we're doing wrong and how we can get this working (and also to get the other plugins to appear)?

**Comment by Krzmbrzl** [comment]
I assume you are on Windows?

Which version of Mumble are you using (on the client-side)? And where did you get that version from?

Note that the server is not really involved in positional audio. This is a client-side feature.

**Comment by Biozeminade** [comment]
> I assume you are on Windows?
> 
> Which version of Mumble are you using (on the client-side)? And where did you get that version from?
> 
> Note that the server is not really involved in positional audio. This is a client-side feature.

I'm using 1.3.4 on Windows 10. I initially had 1.3.3 from here: https://www.mumble.com/mumble-download.php although upon installation, it prompted me saying an update was available which I ended up downloading.

**Comment by davidebeatrici** [comment]
Plugins for CS:S and DOD:S are not supposed to appear: they are deprecated in favor of the Link plugin, as Source Engine provides integration for it.

Unfortunately Left 4 Dead uses an older branch of the engine which doesn't provide said integration.
Mumble 1.4.0 provides a completely new plugin which currently works with both L4D and L4D2.

**Comment by Krzmbrzl** [comment]
You can get a snapshot version of the upcoming 1.4.0 release from https://www.mumble.info/downloads/#development-snapshots

**Comment by Kissaki** [comment]
So to clarify: With it turned on, on your start and connect to a server Mumble should show that it linked with the Link plugin, and then it should work.

**Comment by davidebeatrici** [comment]
For games that have integration for the Link plugin, otherwise it should show that it's linked with the Source Engine one.

**Comment by Biozeminade** [comment]
Well right now I'm trying another game with a friend. Specifically Garry's Mod (retail) and it's still not working. Both me and my friend have the newest snapshot installed AND the checkbox for Positional Audio is set to 'on'.

**Comment by Krzmbrzl** [comment]
What is the version of the server that you are using?

**Comment by Biozeminade** [comment]
> What is the version of the server that you are using?

If you mean Murmur, it's the latest revision (based off of the latest Mumble 1.4 snapshot: [Murmur-1.4.0_2021-04-03_ge0d0056_snapshot.x64]).

But if you mean Garry's Mod, it's the latest revision on the (x86-64) branch: [2021-04-02].

**Comment by Krzmbrzl** [comment]
Just for fun, did you try out a different server yet? Just choose one from the public server list and connect to that to see if it is working.

@davidebeatrici could it be that the Source Engine plugin is currently broken (for these games)?

**Comment by Sannz** [comment]
I have tried it for the left 4 dead 2  game and on different servers (latest 1.4 snapsnot / current / online hosted). The results appears to be the same. The message that mumble got linked never appears in this case, but looking how the size of ram usage and also that it completely freeze the game in that time frame makes it seems it is trying to get the data. (periodically after a certain amount of seconds) 

![MumbleLink](https://user-images.githubusercontent.com/11075726/114176209-22bf1380-993b-11eb-910e-795f8f84e5fa.gif)

And to make sure the hitches were caused by mumble, after closing mumble the game runs normally without any freezes.

**Comment by Krzmbrzl** [comment]
Hm to me it appears as if the plugin is broken and simply fails to fetch the respective data.

@davidebeatrici

**Comment by davidebeatrici** [comment]
I'm unable to test Link with Garry's Mod because I don't own the game, but I confirm that the dedicated Left 4 Dead plugin works fine.

@Sannz Looks like a memory leak, however it cannot be caused by the plugin because it only reads the process' memory.
If you have Mumble's overlay enabled I would try to disable it, there's a high chance it causes issues because it's injected into the process.

**Comment by Sannz** [comment]
@davidebeatrici You are correct, did another run without the overlay and the freezes are gone. Looking at the task manager however still showed the RAM usage is periodically increasing and then decreasing. Disabling the Source Engine plugin ceases this behavior.

**Comment by Kissaki** [comment]
If Mumble says it linked that’s what you want. Note that the server context may be different depending on the game and how you connect to it. E.g. if you self-host locally and connect to 127.0.0.1 then that is a different server address than your friend using a remote local address a.b.c.d. If the game uses that as the context then you will not be in the same context.

I own garry's mod and could test.

I didn't quite get what you changed that it did not link anymore? Anyway, that's not what you want. So if you can go back to where it linked.
