### ISSUE TITLE
Wrong usage of ALSA library API may cause a memory leak

### ISSUE THREAD

**Issue by Zero0one1** [mumble-voip/mumble#4910]
**Describe the bug**
When reading the source code, I found an API misuse but didn't figure out if this misuse can cause serious consequences, so I report it here. I hope it's ok.
According to the ALSA library document of [snd_card_get_name()](https://www.alsa-project.org/alsa-doc/alsa-lib/group___control.html#gad48d44da8e3bfe150e928267008b8ff5), we should free the second parameter `cname` when it is no longer needed. But the following code doesn't, which can cause a memory leak. Do you have any idea how serious this leak can be? Thanks a lot : )
https://github.com/mumble-voip/mumble/blob/fbb2a8c8230a51f9bbc0ee755355675cff93313d/src/mumble/ALSAAudio.cpp#L220

**Comment by Krzmbrzl** [comment]
I'm not sure how bad it'll get but in any case I think we can just fix it and then we don't have to worry about it anymore :sweat_smile: 

Do you happen to know which function one should use in order to free the allocated name? Do we have to use an API function for that or do we simply have to use `free` on it? :thinking:

**Comment by Krzmbrzl** [comment]
According to some code I found online (https://github.com/alsa-project/alsa-utils/blob/eefc2c61cfda4325373e1fa2d3be1642c92eee83/alsactl/utils.c#L81-L101) it seems as if we simply have to use `free` :eyes:

Since you were the one who spotted the issue, do you want to create a PR with the fix or shall I do it?

**Comment by Zero0one1** [comment]
I encountered new questions when writing the PR: do we need to check the return value of `snd_card_get_name()` and `snd_card_get_longname()` ?(As the document says, it returns a error code when fail)

I'm new to the ALSA library. What does the integer `card` in these APIs represent? The sound card in the machine? 
Does every sound card, which has an id, always have a name? In this case, we don't need the check of the return value.

Thanks for your time. 😄

**Comment by Krzmbrzl** [comment]
> I encountered new questions when writing the PR: do we need to check the return value of snd_card_get_name() and snd_card_get_longname() ?(As the document says, it returns a error code when fail)

Uhm. I would think that yes we should indeed do that :eyes: 

> What does the integer card in these APIs represent? The sound card in the machine?
Does every sound card, which has an id, always have a name? In this case, we don't need the check of the return value.

That I actually don't know (I am not familiar with ALSA myself).
Maybe @davidebeatrici knows more about this though :point_up:

**Comment by davidebeatrici** [comment]
> I'm new to the ALSA library. What does the integer `card` in these APIs represent? The sound card in the machine? 

Correct.

> Does every sound card, which has an id, always have a name? In this case, we don't need the check of the return value.

I'm not sure, but I would expect the name (`snd_card_get_name()`) to be mandatory and the long name (`snd_card_get_longname()`) to be additional.

**Comment by Krzmbrzl** [comment]
Explicitly checking the return codes of these functions should be done anyway though (imo).

@Zero0one1 do you want to create another PR for fixing this as well? :)
