### ISSUE TITLE
Force PTT bug

### ISSUE THREAD

**Issue by D1og0** [mumble-voip/mumble#4931]
**Describe the bug**
Everything I click, it tells me the Set PTT Message

**Steps to Reproduce**
1. I don't know

**Expected behavior**
I  can't change to Voice Detect

**Desktop (please complete the following information):**
 - Windows 10
 - Mumble 1.3.4
 -

**Comment by Krzmbrzl** [comment]
I am afraid I can't follow. What did you try to do to change away from PTT and what was the result of that? Maybe you could also nake a screenshot to illustrate the issue?

And where do you get a message to set PTT? And how does it read?

**Comment by D1og0** [comment]
here is a video showing my problem


![Yrr2rIDY0P](https://user-images.githubusercontent.com/58633798/114896930-0d515a00-9e11-11eb-95af-fe585b11d02c.gif)

**Comment by D1og0** [comment]
Idk how but i fixed the issue...

**Comment by Krzmbrzl** [comment]
Hm it seems that for some reason your client got caught in some sort of loop. I have never seen that before though :thinking: 

But as it has resolved itself for now, let's hope it stays that way :)
