### ISSUE TITLE
Mumble won't work on macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by vsrrly** [mumble-voip/mumble#4935]
**Describe the bug**
When I attempt to join a server on mumble I keep getting the incorrect password message even though I have not been prompted to enter a password. I am also having issues where the Mumble application keeps freezing and the only way I am able to exit the application is by force quitting the app. I am also unable to click on any of the functions in the screenshot I have attached (i.e the mute button, settings cog).

<img width="874" alt="Screenshot 2021-04-18 at 09 58 14" src="https://user-images.githubusercontent.com/82753388/115139938-a5775b00-a02c-11eb-917e-4315a250528e.png">

**Steps to Reproduce**
1. Open app

2. Try to connect to server

**Expected behavior**
When trying to join the server I am expecting an enter password prompt to appear

**Desktop (please complete the following information):**
 - Macbook Air 13, 2018
 - Version: Mumble 1.3.3

**Comment by Krzmbrzl** [comment]
> When I attempt to join a server on mumble I keep getting the incorrect password message even though I have not been prompted to enter a password.

This is kinda expected as password authentication is considered obsolete. However after having received the incorrect password message, you should normally be prompted for a password.

What server are you trying to connect to and what username are you using? Have you tried connecting to a different server yet?

**Comment by davidebeatrici** [comment]
> This is kinda expected as password authentication is considered obsolete.

I'm pretty sure he's referring to the server password.
