### ISSUE TITLE
Restart Button

### ISSUE THREAD

**Issue by GDur** [mumble-voip/mumble#4962]
**In which context would you expect your suggested feature to be useful?**
It would be useful in the main menu and the tray menu next to the "Quit Mumble" buttons.

**Describe the feature you have in mind**
**A clear and concise description of what you want to happen.**
Restart the App.

**Describe alternatives you've considered**
Can't think of one.

**Comment by JuniorJPDJ** [comment]
In what case would it be useful?

**Comment by GDur** [comment]
> In what case would it be useful?

Thank you for the reply :)

Sometimes mumble doesn't work as expected and a simple restart fixes the problem.
e.g., Sometimes Mumble doesn't send nor receives sound and the hotkeys don't work. After a restart it works again.

**Comment by Krzmbrzl** [comment]
> Clearly it would be much better to fix the bugs instead that would warrant a restart in the first place.

I guess you have a point there.

On the other hand a new entry in the main menu that says "restart" instead of "Quit" doesn't really hurt (imo).
Thus if this can bridge the time that it takes to find and eliminate the bug(s) I think that'd be a compromise that I could live with :thinking:

**Comment by vimpostor** [comment]
I agree, adding a "Restart" button would only achieve that people will be ok with working around a bug and make it less likely that they will report the bug, which is what we would want. I have never seen a "Restart" button in any application whatsoever (except for restarting after update) and I think it would look absolutely ridiculous.
Opensource apps are unfortunately already kinda known for having not the best UX, we don't have to give those people more mocking material by adding such a button.

I appreciate that the Mumble team is taking every issue seriously but sometimes it is also okay to close an issue as "won't fix".

**Comment by Krzmbrzl** [comment]
Alright you convinced me :)

Closing as "won't fix"

**Comment by vimpostor** [comment]
Just in case I was being unclear or too much of a prick to the issue reporter:
If there is any issue with Mumble, feel free to create a new bug report with a more clear message than just "Sometimes Mumble doesn't work as expected" and we will be happy to try to fix the problem directly - without any workaround buttons necessary. :)

**Comment by GDur** [comment]
> Just in case I was being unclear or too much of a prick to the issue reporter:

It's good to see you acknowledging this. But again you quoted my general statement and not my example which is weird behavior 
 at best.
Here is my example statement you left out:
> e.g., Sometimes Mumble doesn't send nor receives sound and the hotkeys don't work. After a restart it works again.

I appreciate most of the comments and will make a bug report out of this instead.

**Comment by vimpostor** [comment]
> e.g., Sometimes Mumble doesn't send nor receives sound and the hotkeys don't work. After a restart it works again.
Whoops sry, I totally skipped over this part, I am sry!
Perhaps this is the same issue as the one we are tracking that is fixed by switching all users to Opus.

**Comment by GDur** [comment]
Alright, thank you for the apology and for the tip as well 👍
