### ISSUE TITLE
QMutex recursion mode is deprecated

### ISSUE THREAD

**Issue by DarkDefender** [mumble-voip/mumble#4973]
**Describe the bug**
Newer QT version seems to have deprecated QMutex recursion mode.

**Steps to Reproduce**
1. Use the live 5.15 qtcore git branch
2. Try to compile mumble
3. Compilation fails with the following error:

```
/var/tmp/portage/media-sound/mumble-9999/work/mumble-9999/src/mumble/Plugin.cpp:18:45: error: ‘QMutex::QMutex(QMutex::RecursionMode)’ is deprecated: Use QRecursiveMutex instead of a recursive QMutex [-Werror=deprecated-declarations]
   18 | QMutex Plugin::s_idLock(QMutex::NonRecursive);
      |                                             ^
In file included from /usr/include/qt5/QtCore/QMutex:1,
                 from /var/tmp/portage/media-sound/mumble-9999/work/mumble-9999/src/mumble/Plugin.h:15,
                 from /var/tmp/portage/media-sound/mumble-9999/work/mumble-9999/src/mumble/Plugin.cpp:6:
/usr/include/qt5/QtCore/qmutex.h:140:14: note: declared here
  140 |     explicit QMutex(RecursionMode mode);
      |              ^~~~~~
cc1plus: all warnings being treated as errors
```

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Version: Mumble git master

**Comment by Krzmbrzl** [comment]
Does Qt also state what to use instead?

**Comment by Kissaki** [comment]
From the error:

> ‘QMutex::QMutex(QMutex::RecursionMode)’ is deprecated:
> Use QRecursiveMutex instead of a recursive QMutex [-Werror=deprecated-declarations]

Followup line shows

>    18 | QMutex Plugin::s_idLock(QMutex::NonRecursive);

So I assume NoNRecursive is what we pass to it, so we just drop that parameter to continue to not use recursive mode..

**Comment by Krzmbrzl** [comment]
> From the error:

Oh oops. Didn't read the entire error message on my phone xD
