### ISSUE TITLE
Outdated protobuf

### ISSUE THREAD

**Issue by wvffle** [mumble-voip/mumble#4979]
**Describe the bug**
I just wanted to update my archlinux machine with `mumble-git` installed from AUR. Some of other packages depend on protobuf 3.16.0, so I had to uninstall mumble until you guys update protobuf.

**Steps to Reproduce**
1. Update archlinux
2. Try to install mumble-git with aur helper

**Expected behavior**
Install just fine

**Screenshots**
![image](https://user-images.githubusercontent.com/13330620/117574475-c03d6c80-b0cc-11eb-87bd-b3d0d4803209.png)

**Desktop (please complete the following information):**
 - OS: archlinux
 - Version: b2798e81d418ae0a834497cb45c4dc43ea22671c

**Additional context**

**Comment by Krzmbrzl** [comment]
We are not responsible for packaging the Arch package and afaik we don't enforce any particular protobuf version.

Please file a bug report against the AUR / that particular package.
