### ISSUE TITLE
Increase (or allow input for) Maximum Positional Audio Distance

### ISSUE THREAD

**Issue by random-sb** [mumble-voip/mumble#4990]
![7liwvque1zw61](https://user-images.githubusercontent.com/76538731/118020670-58835d80-b328-11eb-8fb1-b3a98767cbef.png)
A maximum distance of 100m can be too short for some applications. The feature I am requesting is to either increase this limit or allow a positive number input for this value.

Thank you.

**Comment by Krzmbrzl** [comment]
What exactly is your application? Do you want to be able to hear players regardless of their distance? So after some threshold distance it won't get quieter? In that case you can set the `Minimum Volume` setting to something > 0.

**Comment by vimpostor** [comment]
I guess the problem could be that in some games 100m is a very small distance. Perhaps something like a flight simulator. In that case this could also be fixed by scaling down the world distances in the positional audio game specific plugin.

I am not sure if that is a better fix though, allowing to edit maximum distance arbitrarily would not be that wrong either.

**Comment by Kissaki** [comment]
This was [originally reported on Reddit by them](https://www.reddit.com/r/mumble/comments/n47jkb/farther_positional_audio_maximum_distance/).

They want PA to go towards silence, but not end at 100 m. Effectively, the max limit is too low.

I’m not sure what feels better as max distance as I have unfortunately not used it as much. But I can see 100 being too low.

If we do not expect it to be a default case, or if we want to allow even higher values than e.g. 200 for custom scenarios, I think replacing the label with an input would be nice where the slider is available for easy adjustment according to our expected standard cases, while the user can still input a higher value (where the slider is right-most but no longer necessarily representative of the actual value).

**Comment by Kissaki** [comment]
I would be interested in what people think a good, common maximum value is. How far would you hear people in real life? How far feels good in game, where hearing over distance may be more critical due to the nature of the game?
