### ISSUE TITLE
Push-To-Talk works focusless

### ISSUE THREAD

**Issue by mungo59** [mumble-voip/mumble#5011]
- Linux Mint 20.1 Cinnamon
- Mumble 1.3.0+dfsg-1build

I have always picked the left mouse button in combination with an active PTT-window.
IMHO this should result in activation when the mouse is clicked **on** the PTT-window only.

Now I experience activation in **any** window on any click, e.g. clicking on some image of another program and moving it around activates PTT unintendedly.
I would expect this behavior while the "Activate Push-To-Talk-button" is unchecked.

Any hints?

**Comment by Krzmbrzl** [comment]
So you set the PTT key to be your left mouse button? Then this is working as intended. All shortcuts are _global_ shortcuts and as such they can be triggered regardless of whether or not Mumble has focus.

**Comment by mungo59** [comment]
That did the trick.

So, the shortcut - whatever it might be - replenishes the mouse button on the PTT-window.
If the mouse is chosen here, it activates, no matter what the focus is.
Got it.
Thank you.

**Comment by Krzmbrzl** [comment]
Yes exactly. You're welcome :)
