### ISSUE TITLE
'Hide in tray when minimized' feature doesn't work on Wayland

### ISSUE THREAD

**Issue by 2xsaiko** [mumble-voip/mumble#5012]
**Describe the bug**
When the feature is enabled and the window is minimized, it sticks around in the taskbar. The only way to actually get it to go to the tray is to close the window so the Close/Minimize dialog box pops up and then select Minimize.

**Steps to Reproduce**
1. Enable 'Hide in tray when minimized' in settings
2. Click the minimize button in the window decoration
3. Window gets minimized normally but doesn't close itself

**Expected behavior**
The window closes itself so that it's gone from the taskbar and only visible in the tray.

**Screenshots**

**Desktop (please complete the following information):**
Operating System: Gentoo
KDE Plasma Version: 5.21.90
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.4-gentoo (64-bit)
Graphics Platform: Wayland
Mumble Version: commit 998eb37 (17 May 2021)

**Comment by Krzmbrzl** [comment]
> Window gets minimized normally but doesn't close itself

With "doesn't close itself" I assume you mean that it does not remove itself from the taskbar so that it is only visible in the Tray. Is that correct?

**Comment by 2xsaiko** [comment]
Yeah, exactly.

**Comment by Hartmnt** [comment]
I investigated this in #6466 

This is a limitation of (X)Wayland (or possibly a bug in Qt) which we have no way of fixing or working around. In the new tray implementation you will be able to minimize to tray by:

* Clicking the close button of the Mumble MainWindow, provided that you selected "Always minimize" in the settings or hit the additional "Minimize" button you were already talking about
* Clicking the tray icon, or the first action within the context menu of the tray icon
* Binding a shortcut to "Show/Hide Mumble"

which will all do exactly the same.

https://bugreports.qt.io/browse/QTBUG-74310
