### ISSUE TITLE
Edit Shortcut dialog issues with position and modal

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5024]
The dialog currently opens on the top of my screen, even in negative position so that the title bar is mostly outside of my screen.
It also shows way off horizontally.

I would also expect it to show modally, blocking input to the settings window. At the moment you can click shortcut again, closing the previous dialog and opening a new dialog.
This is confusing and can lead to current changes being lost without any warning.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.4

**Comment by Krzmbrzl** [comment]
It seems that on Linux this works as expected

**Comment by davidebeatrici** [comment]
I can reproduce the first issue (title bar almost completely hidden), but when I click outside of the dialog it's simply closed.

**Comment by Krzmbrzl** [comment]
> but when I click outside of the dialog it's simply closed.

That's what I also observe on Linux
