### ISSUE TITLE
Configured shortcut settings lost when moving from 1.3.x to 1.4.x

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5025]
With the switch to raw input it looks like all current shortcuts setup are broken when upgrading to 1.4, without any notice to the user.

All my shortcuts show with shortcuts 'Unknown' for me.

This is pretty confusing to users, and not a good upgrade path.

![image](https://user-images.githubusercontent.com/93181/119222936-1233b880-baf7-11eb-9a05-e5abea986181.png)

**Comment by Krzmbrzl** [comment]
/CC @davidebeatrici 

My suspicion is that the issue here is that the String representation of the shortcuts was changed and thus the system can't parse the old specs anymore... :thinking:

**Comment by davidebeatrici** [comment]
Shortcuts were saved in a completely different format, meaning that they just don't work anymore.

We could detect that case and warn the user accordingly.

**Comment by Krzmbrzl** [comment]
I think there should be a migration path at least for the most common devices (keyboard & mouse)

**Comment by davidebeatrici** [comment]
Keyboard: https://github.com/mumble-voip/mumble/blob/c0b5be7134673fa1c4c434b72552c200bca37b8d/src/mumble/GlobalShortcut_win.cpp#L307-L355

Mouse: https://github.com/mumble-voip/mumble/blob/c0b5be7134673fa1c4c434b72552c200bca37b8d/src/mumble/GlobalShortcut_win.cpp#L357-L373

Migrating XInput and G-keys shortcuts would be much simpler.

**Comment by Krzmbrzl** [comment]
> Migrating XInput and G-keys shortcuts would be much simpler.

Well then I would say we can easily migrate these as well. But keyboard and mouse seem essential to me

**Comment by Krzmbrzl** [comment]
Yes but that doesn't really matter. Discarding all shortcuts of a user is pretty-much a no-go. There should always be a migration path (at least for the most common devices).

Besides: Shouldn't it be possible to simply restore the code that loaded shortcuts before and use that as the migration path?

**Comment by davidebeatrici** [comment]
Unfortunately not, because as I mentioned in another issue we don't save shortcuts based on their display value. We save the `QVariant` that is set by the backend, meaning that we would have to map the DirectInput values to our new ones.

**Comment by Krzmbrzl** [comment]
And that is a huge problem, because ...?
This still sounds like a single function that you input the QVariant for DirectInput and that outputs the corresponding mapping in RawInput :thinking:

**Comment by davidebeatrici** [comment]
The mouse is not a huge problem, the keyboard may be due to the extended bit. I'll have to check whether it refers to `e0`, `e1` or both.

**Comment by Krzmbrzl** [comment]
Wdym with "extended bit"? 👀

**Comment by davidebeatrici** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawkeyboard

https://github.com/mumble-voip/mumble/blob/c0b5be7134673fa1c4c434b72552c200bca37b8d/src/mumble/GlobalShortcut_win.cpp#L375-L396

https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-kbdllhookstruct

UUnfortunately `LLKHF_EXTENDED` is only described as `Test the extended-key flag.`.

**Comment by Krzmbrzl** [comment]
But it is a macro and as such it must be defined in the header (which we should have access to in order to get that value out of it). We can simply hard-code that in the transition code and then do the same thing as we used to, can't we?

**Comment by davidebeatrici** [comment]
Yes, but I need to make sure that `LLKHF_EXTENDED` only refers to E0.

**Comment by Krzmbrzl** [comment]
What is the e0 vs e1 about? I can't seem to find that being mentioned in the docs you linked :thinking:

**Comment by davidebeatrici** [comment]
https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html

**Comment by Krzmbrzl** [comment]
Okay I still don't see the big problem. So far I have not found something that seems overly complicated for a migration function. Plus we must have had that code already (and still.do thanks to git history), so why can't we simply use that old code? :thinking:

**Comment by davidebeatrici** [comment]
The old code does the opposite: backend -> settings.

**Comment by Krzmbrzl** [comment]
But we had to load from the settings at some point, so how did we do that? It seems like the reverse operation must have been implemented somewhere :thinking:
