### ISSUE TITLE
windows: client build failed

### ISSUE THREAD

**Issue by jisopo** [mumble-voip/mumble#5030]
**Describe the bug**
Unable to build mumble client

**Steps to Reproduce**

`cmake .. -G"Visual Studio 14 2015 Win64" -DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DCMAKE_TOOLCHAIN_FILE=D:/Data/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -Dice=OFF -Dstatic=ON -Dtranslations=OFF -Dsymbols=ON -Dzeroconf=OFF -Dserver=OFF -Dcrash-report=OFF -Dwarnings-as-errors=OFF -Doverlay=OFF -Doverlay-xcompile=OFF`

build though GUI in visual studio

**Expected behavior**
build without errors

**Screenshots**
<details>
  <summary>Screenshots</summary>
  
![snap000026](https://user-images.githubusercontent.com/22599108/119241845-3aa4cc80-bb62-11eb-879f-36acfa521bbd.png)
![snap000020](https://user-images.githubusercontent.com/22599108/119241847-3bd5f980-bb62-11eb-8eef-bc5ba23d59fc.png)
![snap000021](https://user-images.githubusercontent.com/22599108/119241848-3c6e9000-bb62-11eb-9150-579f4c19233c.png)
![snap000022](https://user-images.githubusercontent.com/22599108/119241849-3c6e9000-bb62-11eb-978b-ddbc6ec09e02.png)
![snap000024](https://user-images.githubusercontent.com/22599108/119241850-3c6e9000-bb62-11eb-9d9d-faf2321b3a5d.png)
![snap000025](https://user-images.githubusercontent.com/22599108/119241851-3d072680-bb62-11eb-85d2-ab4fb7c8af01.png)
</details>

**Desktop:**
**OS:** windows 8.1
**VS version:** visual studio 2015 update 3
**cmake:** cmake version 3.19.0-rc1
**mumble version** 232d4b3c0d2410062c36b81fb5e9545a42191ab3
Dependencies installed via vckpg

**Additional context**
<details>
  <summary>errors</summary>
1. 
file missing

`mumble_positional_audio_utils.h\corecrt_math_defines.h`

what is this file? where i cant get it?
2. mumble\plugins\amongus\amongus.cpp:15
```
std::unique_ptr< Game > game;
Severity    Code    Description Project File    Line    Suppression State
Error   C2039   'unique_ptr': is not a member of 'std'  amongus mumble\plugins\amongus\amongus.cpp 15  
Error   C2143   syntax error: missing ';' before '<'    amongus mumble\plugins\amongus\amongus.cpp 15  
Error   C4430   missing type specifier - int assumed. Note: C++ does not support default-int    amongus mumble\plugins\amongus\amongus.cpp 15  
```

include missing
`#include <memory>`

same with cod2, se and ut99 projects
3. 
```
Severity    Code    Description Project File    Line    Suppression State
Error   LNK1120 1 unresolved externals  amongus mumble\build\plugins\Debug\amongus.dll 1   
Error   LNK2001 unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt<char16_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_SDU_Mbstatet@@@std@@2V0locale@2@A)   amongus mumble\build\plugins\amongus\Game.obj  1   
Error   LNK2001 unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt<char16_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_SDU_Mbstatet@@@std@@2V0locale@2@A)   amongus mumble\build\plugins\amongus\HostWindows.obj   1   
```

depend on [this](https://stackoverflow.com/questions/32055357/visual-studio-c-2015-stdcodecvt-with-char16-t-or-char32-t), [this](https://github.com/antlr/antlr4/issues/1953) and [this](https://codedump.io/share/2mV7vCOLlxM1/1/visual-studio-c-2015-stdcodecvt-with-char16t-or-char32t)

looks like as known bug , should i add some check on currently used _MSC_VER version?

same with cod2, se and ut99 projects
4. 
```
GlobalShortcut_win.cpp:469
Severity    Code    Description Project File    Line    Suppression State
Error (active)      incomplete type is not allowed  mumble  mumble\src\mumble\GlobalShortcut_win.cpp   469 
Error (active)      no operator "<<" matches these operands mumble  mumble\src\mumble\GlobalShortcut_win.cpp   470 
Error (active)      no operator "<<" matches these operands mumble  mumble\src\mumble\GlobalShortcut_win.cpp   471 
Error (active)      no operator "<<" matches these operands mumble  mumble\src\mumble\GlobalShortcut_win.cpp   472 
Error (active)      no operator "<<" matches these operands mumble  mumble\src\mumble\GlobalShortcut_win.cpp   473 
Error (active)      no operator "<<" matches these operands mumble  mumble\src\mumble\GlobalShortcut_win.cpp   474
``` 

include missing
`#include <sstream>`

5. 
```
Severity Code    Description Project File    Line    Suppression State
Error   C2065   'HID_USAGE_GENERIC_MULTI_AXIS_CONTROLLER': undeclared identifier    mumble  mumble\src\mumble\GlobalShortcut_win.cpp   285 
```

C:\Program Files (x86)\Windows Kits\8.1\Include\shared\hidusage.h does not contains define for HID_USAGE_GENERIC_MULTI_AXIS_CONTROLLER

[depend on](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/hid-usages) value must be 0x08
sdk is too old?

6. src/mumble/SearchDialog.h:263

```
Severity    Code    Description Project File    Line    Suppression State
Error   C2440   'return': cannot convert from 'initializer list' to 'Search::SearchResult'  mumble  mumble\src\mumble\SearchDialog.cpp 263 
Error   C2440   'return': cannot convert from 'initializer list' to 'Search::SearchResult'  mumble  mumble\src\mumble\SearchDialog.cpp 278 
```

class constructor missing/visual studio 2015 does not support struct initialization like this

file with patches:
[link](https://pastebin.com/F9Am9gvk)
</details>

**Comment by davidebeatrici** [comment]
I strongly recommend to update to Visual Studio 2019 and open the CMake project directly.

**Comment by Krzmbrzl** [comment]
Given that there are STL headers that your compiler doesn't seem to find, it seems to me that your compiler does not (fully) support Cpp14 which is required for compiling Mumble.

I just checked and the build docs don't actually mention that yet. I'll add this information.

For the time being I will assume that Davide's suggestion will fix the issue and as such I'll close this issue. Should you have troubles building Mumble after having upgraded to a more recent compiler, let us know

**Comment by davidebeatrici** [comment]
> it seems to me that your compiler does not (fully) support Cpp14 which is required for compiling Mumble.

C++11, actually (`<memory>` is not found).

**Comment by jisopo** [comment]
**Describe the bug**
Unable to build mumble client

**Steps to Reproduce**
directory - mumble\build

`cmake .. -G"Visual Studio 16 2019" -A x64 -DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DCMAKE_TOOLCHAIN_FILE=D:/Data/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -Dice=OFF -Dstatic=ON -Dtranslations=OFF -Dsymbols=ON -Dzeroconf=OFF -Dserver=OFF -Dcrash-report=OFF -Dwarnings-as-errors=OFF -Doverlay=OFF -Doverlay-xcompile=OFF -DCMAKE_UNITY_BUILD=ON`

`cmake --build .`

**Expected behavior**
build without errors

**Screenshots**
<details>

![snap000027](https://user-images.githubusercontent.com/22599108/119268222-ae92b380-bbfa-11eb-913b-39acc02e92b1.png)

![snap000029](https://user-images.githubusercontent.com/22599108/119268870-907a8280-bbfd-11eb-976a-66cefa52c33c.png)
</details>

**Desktop:**
 - OS: win 8.1
 - Version: 8c99fe8119ce00fbcba55c69bde0a48383e7fa79
 - cmake: cmake version 3.19.0-rc1
 - vs: Microsoft Visual Studio Enterprise 2019 Version 16.5.5

**Errors**:
<details>
  <summary>errors</summary>

- ` \mumble\plugins\amongus\../mumble_positional_audio_utils.h(21,11): fatal error C1083: Cannot open include file: 'corecrt_math_defines.h': No such file or directory `
- cmake
`Effect-Compiler tool not found!`
- `mumble/src/mumble/GlobalShortcut_win.cpp(504,46): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)`
</details>

**Fixes**:

windows sdk 8.1 is too old, windows sdk 10 required(installed 10.0.18362.0 - ok)
[mumble_client_build_fix.diff](https://pastebin.com/tFPLZX8p)

**Additional context**
can i add compatibility with vs2015? will my pr merged?

**Comment by davidebeatrici** [comment]
The Windows 10 SDK is supposed to be selected automatically, your change hardcodes `10.0.18362.0` (x64).

**Comment by jisopo** [comment]
@davidebeatrici
`The Windows 10 SDK is supposed to be selected automatically,`
but it not. cmake finds 8.1 by default

**Comment by davidebeatrici** [comment]
I would uninstall 8.1.

**Comment by jisopo** [comment]
> For the time being I will assume that Davide's suggestion will fix the issue and as such I'll close this issue. Should you have troubles building Mumble after having upgraded to a more recent compiler, let us know

new information added
