### ISSUE TITLE
windows: client build failed

### ISSUE THREAD

**Issue by jisopo** [mumble-voip/mumble#5033]
**Describe the bug**
Unable to build mumble client

**Steps to Reproduce**
directory - mumble\build

`cmake .. -G"Visual Studio 16 2019" -A x64 -DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DCMAKE_TOOLCHAIN_FILE=D:/Data/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -Dice=OFF -Dstatic=ON -Dtranslations=OFF -Dsymbols=ON -Dzeroconf=OFF -Dserver=OFF -Dcrash-report=OFF -Dwarnings-as-errors=OFF -Doverlay=OFF -Doverlay-xcompile=OFF -DCMAKE_UNITY_BUILD=ON`

`cmake --build .`

**Expected behavior**
build without errors

**Screenshots**
<details>

![snap000027](https://user-images.githubusercontent.com/22599108/119268222-ae92b380-bbfa-11eb-913b-39acc02e92b1.png)

![snap000029](https://user-images.githubusercontent.com/22599108/119268870-907a8280-bbfd-11eb-976a-66cefa52c33c.png)
</details>

**Desktop:**
 - OS: win 8.1
 - Version: 8c99fe8119ce00fbcba55c69bde0a48383e7fa79
 - cmake: cmake version 3.19.0-rc1
 - vs: Microsoft Visual Studio Enterprise 2019 Version 16.5.5

**Errors**:
<details>
  <summary>errors</summary>

- ` \mumble\plugins\amongus\../mumble_positional_audio_utils.h(21,11): fatal error C1083: Cannot open include file: 'corecrt_math_defines.h': No such file or directory `
- cmake
`Effect-Compiler tool not found!`
- `mumble/src/mumble/GlobalShortcut_win.cpp(504,46): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'int' (or there is no acceptable conversion)`
</details>

**Fixes**:

windows sdk 8.1 is too old, windows sdk 10 required(installed 10.0.18362.0 - ok)
[mumble_client_build_fix.diff](https://pastebin.com/tFPLZX8p)

**Additional context**
can i add compatibility with vs2015? will my pr merged?

**Comment by davidebeatrici** [comment]
Please read our replies in #5030.
