### ISSUE TITLE
Set password to channel on mumble-server using ICE(rpc) api's

### ISSUE THREAD

**Issue by prashant-17-dev** [mumble-voip/mumble#5036]
**Context**
creating predefined private channels.

Let me know if there is an existing API to set the password to the channel.

**Comment by Kissaki** [comment]
This is a feature request?

**Comment by Krzmbrzl** [comment]
I guess by knowing the dark magic behind the current ACL implementation as stated here:
https://github.com/mumble-voip/mumble/blob/8c99fe8119ce00fbcba55c69bde0a48383e7fa79/src/ACL.cpp#L336-L340
you could use the current [ACL type](https://github.com/mumble-voip/mumble/blob/8c99fe8119ce00fbcba55c69bde0a48383e7fa79/src/murmur/Murmur.ice#L179-L194) type to effectively set a password.

This is of course a really ugly "API" and also not guaranteed to work for all eternity as the actual implementation might be changed at some point. However for the time being it might be worth a shot :)

**Comment by Kissaki** [comment]
To word it explicitly: A channel with a password has an ACL group prefixed with `#` and the password as its name.

So you can use Ice to set such an ACL group rule.

_I looked at the slice docs to verify and link this as I remembered it as such, but unfortunately the slice docs do not document it._

**Comment by Krzmbrzl** [comment]
*Closing this as resolved*
