### ISSUE TITLE
Scaling murmur server. 

### ISSUE THREAD

**Issue by prashant-17-dev** [mumble-voip/mumble#5042]
How can mumble-server be scaled up i.e how do I link 2 or more mumble-server together to handle the connections? Is there any way to handle a large set of users?

**Comment by Avatat** [comment]
Currently, it is not possible to add more "replicas" of mumble-server.

**Comment by Krzmbrzl** [comment]
Yeah as Avatat said: There is no way to get what you want but from the reports we have received from our users so far you should basically never actually require something like this :thinking:

**Comment by Kissaki** [comment]
To be more explicit with the wording:

We do not expect you to hit limits that would require you to “link servers”.

If you do, please provide some context for us to reason and work with.

**Comment by stephenanning** [comment]
I really wish the server was scalable. I have an audio app that I'm using a less good audio streaming service to achieve lesser audio results. I'm about to release the app. Intended listener numbers are over 10k at a time and on multiple channels of that.... It's not a gaming app

**Comment by stephenanning** [comment]
I really wish the server was scalable. I have an audio app that I'm using a less good audio streaming service to achieve lesser audio results. I'm about to release the app. Intended listener numbers are over 10k at a time and on multiple channels of that.... It's not a gaming app

**Comment by stephenanning** [comment]
I really wish the server was scalable. I have an audio app that I'm using a less good audio streaming service to achieve lesser audio results. I'm about to release the app. Intended listener numbers are over 10k at a time and on multiple channels of that.... It's not a gaming app


> To be more explicit with the wording:
> 
> We do not expect you to hit limits that would require you to “link servers”.
> 
> If you do, please provide some context for us to reason and work with.
