### ISSUE TITLE
"Unable to find matching CELT codecs with other clients."

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#5051]
This message shows up even if there are **no** users. I'm pretty sure that shouldn't be the intended behavior.

**Comment by Krzmbrzl** [comment]
You mean "no _other_ users", don't you? 'cause how would you see that message otherwise? :eyes:

**Comment by Kissaki** [comment]
Which version?

Could this be a very old client and server enforcing opus or newer celt (no 0.9)?

**Comment by trudnorx** [comment]
This is the newest client and server snapshot. Way to reproduce, host a server and join it. Error shows up right on joining.

**Comment by Krzmbrzl** [comment]
Interesting. I'll try to see if I can reproduce this

**Comment by Kissaki** [comment]
On Linux?

Using shared libs and missing shared libs may behave very differently to a static (Windows) build.

**Comment by Krzmbrzl** [comment]
Indeed. I'll try it first on Linux though as that's what I am using.

**Comment by Krzmbrzl** [comment]
I also saw this message on Linux (both client and server running on Linux - same machine actually). To me it happened when I had 2 instances of Mumble running and both connecting to the same server with the same username.

**Comment by Krzmbrzl** [comment]
I just saw this message again when connecting to a locally hosted server on Linux.
What I see in the server logs is `celt_versions: -2147483637` which seems like an odd (uninitialized?) value is used somewhere in the process :thinking:

**Comment by davidebeatrici** [comment]
A few times I have seen a weird number instead of `0.7.0` in the user info dialog, however I thought it was only a cosmetic issue because I didn't realize the server enforced Opus.

**Comment by Krzmbrzl** [comment]
I am currently trying to bisect our history to find the cause of this.

The weird number from above is `INT_MIN` that gets set in the `CELTCodec` class. I still think this looks suspicious as it stays at this initial value, but the code in there seems to not have changed in years therefore I think it's probably unlikely to have caused the issue

**Comment by Krzmbrzl** [comment]
Bisecting tells me that the issue was introduced by eabfbab403e6ba10219c262518899db5a60d0c1e
Now we only have to figure out why and how ^^

**Comment by Krzmbrzl** [comment]
Alright I think I know what the general problem is (at least it is _a_ problem):
The new user's `uiSession` is used in the `msgAuthenticated` message _before_ it gets assigned. That is because previous to the mentioned commit the `uiSession` was assigned as the first thing.

**Comment by davidebeatrici** [comment]
I actually encountered the user info dialog issue before eabfbab403e6ba10219c262518899db5a60d0c1e, but it may just be cosmetic after all.

**Comment by Krzmbrzl** [comment]
I think that is a different issue and probably unrelated :eyes: 
Especially given that this bug is entirely based on the server
