### ISSUE TITLE
CMake generate fails on bundling Qt translations

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5055]
A Windows static build fails cmake generate on trying to find the python interpreter.

import fails
```
CMake Error at cmake/qt-utils.cmake:6 (include):
  include could not find requested file:

    FindPythonInterpreter
Call Stack (most recent call first):
  src/mumble/CMakeLists.txt:17 (include)
```
consequently find fails
```
-- Bundling Qt translations from "C:/Users/REDACTED/vcpkg/installed/x64-windows-static-md/share/qt5/translations"
CMake Error at cmake/qt-utils.cmake:109 (find_python_interpreter):
  Unknown CMake command "find_python_interpreter".
Call Stack (most recent call first):
  src/mumble/CMakeLists.txt:815 (bundle_qt_translations)
```

The cmake code in question was introduced in 19e16a0524876c3b29f59e9844c650d1a2a7ba73

```
include(FindPythonInterpreter)
```
```
	set(PYTHON_HINTS
		"C:/Python39-x64" # Path on the AppVeyor CI server
	)

	find_python_interpreter(
		VERSION 3
		INTERPRETER_OUT_VAR PYTHON_INTERPRETER
		HINTS ${PYTHON_HINTS}
		REQUIRED
	)
```

Where is FindPythonInterpreter is supposed to come from?

I found [https://cmake.org/cmake/help/latest/module/FindPythonInterp.html](FindPythonInterp) which is deprecated

Using CMake from VS, version 3.20.

Shouldn’t python be included from vcpkg as a dependency? Is that hint path only for AppVeyor CI which does not use vcpkg, and should otherwise make use of

**Comment by Krzmbrzl** [comment]
Run `git submodule update --init`

That script thst it doesn't find is a new submodule

**Comment by Kissaki** [comment]
Mhm, okay. Apparently my client had the submodule deselected on the update/init dialog, I guess because it was not initialized before.

I feel like our build scripts should check for required submodules and give an explicit error to guide users into what the issue is and what to do.

**Comment by Krzmbrzl** [comment]
If we do that however we have to do it in an automated way in order to not have multiple places in which submodules are defined
