### ISSUE TITLE
Installer shows in other language than Windows display language

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5057]
The Mumble installer shows up in a different language than the configured display language.

I use en-US display language, but de-DE keyboard layout and formatting.

The installer shows up in German.

I know of other programs that wrongfully use the formatting (date and number formatting) preference and use the language derived from that. Maybe the installer does that too?

**Comment by Krzmbrzl** [comment]
@ZeroAbility is it even us that sets the installer language or is that something Wix does on its own?

**Comment by Kissaki** [comment]
That’s something the produced thing does by default. Maybe we can influence or fix it up though.

**Comment by Krzmbrzl** [comment]
Well we want it to switch language but if it fails to do so correctly then this sounds like an upstream bug to me 🤷

**Comment by Krzmbrzl** [comment]
To me this seems like an upstream issue as the docs don't seem to indicate any manual involvement in which language is chosen:
https://github.com/oleg-shilo/wixsharp/blob/61777afd40936ddcf5114edbea9ceb708a350da1/Source/src/WixSharp/Extensions.cs#L3123-L3124
