### ISSUE TITLE
Building installer requires BUILD_NUMBER

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5060]
`CMakeLists.txt` [ensures](https://github.com/mumble-voip/mumble/blob/master/CMakeLists.txt#L17-L23) BUILD_NUMBER is set when packaging is enabled.

Shouldn’t users be able to build mumble without it?

@davidebeatrici What’s the reasoning for/idea of this?

The installer build docs does not currently mention or describe this. I do not think it is described anywhere else either. The original commits introducing it seem to only talk about our CI and official builds.

**Comment by Krzmbrzl** [comment]
I think the rational is that when you create an installer, you create a serious release and as such you should add a build number.
