### ISSUE TITLE
Crash in Pipewire backend on first start

### ISSUE THREAD

**Issue by vimpostor** [mumble-voip/mumble#5075]
When Mumble is started for the first time (`rm -r ~/.config/Mumble`), then it crashes in `PipeWireOutput::processCallback` due to `chunk->stride` being `0` in:

```c++
chunk->stride = sizeof(float) * pwo->iChannels; // iChannels is 0 on first start
const uint32_t frames = std::min(data.maxsize / chunk->stride, pwo->iFrameSize); // crash here
```

The problem is that `iChannels` is `0` on first start, but the `connect()` succeeds even with `nChannels == 0`.

The following quick hack fixes the crash:
```diff
diff --git a/src/mumble/PipeWire.cpp b/src/mumble/PipeWire.cpp
index 361288eb0..c0042d2f6 100644
--- a/src/mumble/PipeWire.cpp
+++ b/src/mumble/PipeWire.cpp
@@ -224,6 +224,10 @@ PipeWireEngine::~PipeWireEngine() {
 }
 
 bool PipeWireEngine::connect(const uint8_t direction, const uint32_t *channels, const uint8_t nChannels) {
+	if (nChannels == 0) {
+		return false;
+	}
+
 	uint8_t buffer[1024];
 
 	spa_pod_builder builder{};

```

I am not submitting this directly as PR because there are many different ways to fix the crash, but I am not sure if this one is the cleanest way. Perhaps @davidebeatrici can give some insight if that would be the cleanest way.

For instance one could also fix this problem by giving `iChannels` the default value of `1` instead of `0`.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

The change you proposed is a clean way to fix the crash. However, for a better user experience we should probably set a sane default:

```patch
diff --git a/src/mumble/Settings.cpp b/src/mumble/Settings.cpp
index d35e67ea0..62d25e612 100644
--- a/src/mumble/Settings.cpp
+++ b/src/mumble/Settings.cpp
@@ -413,6 +413,9 @@ Settings::Settings() {
        qsALSAInput  = QLatin1String("default");
        qsALSAOutput = QLatin1String("default");
 
+       pipeWireInput = 1;
+       pipeWireOutput = 2;
+
        qsJackClientName  = QLatin1String("mumble");
        qsJackAudioOutput = QLatin1String("1");
        bJackStartServer  = false;
```

**Comment by vimpostor** [comment]
Sounds good to me. I was worried for a moment, that using Stereo by default (`pipeWireOutput=2`) would then just cause a crash for persons with only a Mono output, but then I realized that the `connect()` call would not return ok in that case, so it is fine.

I will test that on my system and then create a PR.

**Comment by davidebeatrici** [comment]
I actually think `pw_stream_connect()` would simply connect the two channels to the same input, performing downmixing.
