### ISSUE TITLE
liblink.dyllib does not load in packaged Apple Silicon compiled client

### ISSUE THREAD

**Issue by jason-green-io** [mumble-voip/mumble#5121]
**Describe the bug**
Local build of master on MacOS Big Sur 11.4 on Apple Silicon

liblink gets compiled, no errors, the macOS package script makes the DMG and copies the plugin just fine.

When I open the app, the Link plugin is not loaded.

**Steps to Reproduce**
Build as described in 1.4.x build docs for MacOS

Run compiled app and see plugin not loaded.

**Expected behavior**
Plugin loaded and ready for apps to connect to it.

**Screenshots**

**Desktop (please complete the following information):**
MacOS 11.4
Mumble master branch

**Additional context**
Where should I start looking for info on why it's not getting loaded?

**Comment by Krzmbrzl** [comment]
Iirc this was an issue that  @TerryGeng reported on IRC (twice actually) and the issue was that the path for where the plugins are installed to is wrong (which then causes the plugins to never be found by Mumble).

Could you check where the plugins are copied to?

You can cross-check that with Mumble's search path as set here:
https://github.com/mumble-voip/mumble/blob/ff947a60f0f431fda97e5ef5303afbe89a0476f8/src/mumble/PluginManager.cpp#L56-L72

The install paths are specified here:
https://github.com/mumble-voip/mumble/blob/ff947a60f0f431fda97e5ef5303afbe89a0476f8/cmake/install-paths.cmake#L24-L31

**Comment by jason-green-io** [comment]
The packaging script does indeed copy it to the correct location. Search and where the plug-in ends up matches. To note, the packaging script copies liblink into the AppBundle which is the first ifdef in the search logic.

**Comment by davidebeatrici** [comment]
Is there perhaps something related in the developer console?

**Comment by jason-green-io** [comment]
I checked Console.app filtered on Mumble, nothing jumped out to me that showed issues loading plugins.

**Comment by Krzmbrzl** [comment]
Just to be sure: Did you also check Mumble's [developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) for any related output?

If the search path matches but you don't see the plugin listed nor did you see any error message logged to Mumble's developer console nor in Mumble's regular chat window (something like "non-plugin found in plugin directory"), then I don't understand :thinking: 
Maybe it would be worth it to add debug statements to `PluginManager::rescanPlugins` to see which directories it searches and which files it finds in there. :eyes:

**Comment by jason-green-io** [comment]
After a second look, seems the package script failed to copy the lib (I suspect I'm not calling it from the correct folder or with the wrong flags .. or maybe a bug with it). I copied it manually after a clean compile using cmake and it picks up the plugin now from inside the bundle in `Plugins`.

**Comment by Krzmbrzl** [comment]
@jason-green-io could you provide details on how and from where you are calling the script?
