### ISSUE TITLE
Murmur: monitoring server health

### ISSUE THREAD

**Issue by tomj** [mumble-voip/mumble#5137]
Thanks for a great project.

I'm looking for a way to monitor the audio connection health of an arbitrary connection to a Murmur server (ie: can users join channels? when users join a channel, what is the quality of their audio going to be like?).

I have looked through the wiki and also done some broad searching on the web but haven't found a solution to date.  _Is there a preferred method for monitoring Murmur server health?_

🙌

**Comment by Krzmbrzl** [comment]
I don't think there is a _preferred_ way to do it but one way might be by using a framework such as [PyMumble](https://github.com/azlux/pymumble) and write a bot with it that jumps into the respective channels every now and then.

Other than explicitly connecting to a channel, I don't think there is currently a way to get the information that you are after :thinking:

**Comment by tomj** [comment]
Thank you for the prompt response @Krzmbrzl - much appreciated.

I will investigate the PyMumble approach, and for posterity will add findings here if I have any alternative discoveries.

**Comment by Krzmbrzl** [comment]
Sounds good. In that case I'll close this issue as _resolved_ for the time being :)
