### ISSUE TITLE
unable to open database file Error opening database

### ISSUE THREAD

**Issue by sebubd10** [mumble-voip/mumble#5140]
I have Imported SQLite DB from the old server and replace the new mumble server's DB. Both mumble server version is 1.3

After replacing the new DB with imported DB getting an error: mumble unable to open database file Error opening database.

**Details:**
![image](https://user-images.githubusercontent.com/20083164/122664062-ca20b800-d1c0-11eb-9601-38557c563deb.png)

**Comment by Kissaki** [comment]
As you said both, can you clarify whether you imported data or copied and replaced the sqlite file?

First step would be verifying the DB file that is used has the correct user and permission set.

**Comment by sebubd10** [comment]
I have copied the SQLite file and replaced it. 

How to set the permission?

**Comment by davidebeatrici** [comment]
Depends on the user the server is running as. Assuming it's `mumble-user`:
```bash
sudo chown mumble-server:mumble-server mumble-server.sqlite
sudo chmod 640 mumble-server.sqlite
```

**Comment by sebubd10** [comment]
Thanks, @davidebeatrici now working after running two commands.

**Comment by sebubd10** [comment]
@davidebeatrici after running this command Ice is not working.

**Comment by Krzmbrzl** [comment]
_Closing as resolved_
