### ISSUE TITLE
Ability to rename friends

### ISSUE THREAD

**Issue by RVRX** [mumble-voip/mumble#5143]
**Context**
When you add a user as a friend it will save their current mumble name on the server you are in. It would be useful to have a way to change this friend name to anything you want, not just changing to their current name with "Update Friend"

**Describe the feature you have in mind**
This could be added to the bottom of the context menu when you right click on a user/friend. Alternatively, have "update friend" prompt the user what name they would like to update the friend to, auto-filling to their current name (what update friend sets them to now).
![image](https://user-images.githubusercontent.com/45409688/122682306-a19bbc80-d1c6-11eb-853a-516388f9ee27.png)

**Comment by Krzmbrzl** [comment]
There already is the functionality of specifying a nickname for users.
That should cover your needs.

Note that the nickname functionality is only available since 1.4.0
