### ISSUE TITLE
Include strings beginning with "magnet:?" as recognized links

### ISSUE THREAD

**Issue by gyvess** [mumble-voip/mumble#5146]
At the moment magnet links posted in chat are output as plain text, forcing the user the copy the link in order to make apply the link. This behavior also happens when sending the magnet link through "Send Message". Although pasting it in the "Send Message" box auto wraps the link in the appropriate tags to be sent as a link, pressing OK will result in plain text within the chat box.

Allowing magnet links to be recognized as proper links will not only enable the user to simply click them from the chat box, but also allow notifications to enact the desired action should the user have those enabled as well.

**Comment by davidebeatrici** [comment]
Feel free to create a pull request, the relevant code is at https://github.com/mumble-voip/mumble/blob/adf38593153a5ade60e89b4f92195006383ab201/src/mumble/Log.cpp#L444-L463.

**Comment by Krzmbrzl** [comment]
I already created a PR: #5147

**Comment by deluxghost** [comment]
https://github.com/mumble-voip/mumble/blob/adf38593153a5ade60e89b4f92195006383ab201/src/mumble/Log.cpp#L456

massager? is that really spelled like this? :rofl:

**Comment by Krzmbrzl** [comment]
I added a commit that corrects that as well ^^
