### ISSUE TITLE
Push to talk with registered user.

### ISSUE THREAD

**Issue by prashant-17-dev** [mumble-voip/mumble#5150]
how can we speak or to the PTT with a single member in the channel? is it possible?

**Comment by Krzmbrzl** [comment]
Yes that is possible. It's called "whispering" and you haveto set up a specific shortcut for this purpose in the settings

**Comment by prashant-17-dev** [comment]
@Krzmbrzl Thanks for the help I'm able to do the whispering to specific users. just curious couple of users were not getting listed in the list of whisper users. is any condition so that they appear in the list.

**Comment by Krzmbrzl** [comment]
There probably is, yeah ^^

It could be that users are required to have a certificate or that they need to be registered on the server. I'm not sure though :thinking:

**Comment by prashant-17-dev** [comment]
> There probably is, yeah ^^
> 
> It could be that users are required to have a certificate or that they need to be registered on the server. I'm not sure though

Okay, thanks @Krzmbrzl
