### ISSUE TITLE
Allow recording of pre-processed audio

### ISSUE THREAD

**Issue by frankdeath** [mumble-voip/mumble#5151]
**Context**
People using mumble to conduct remote interviews for podcasts would benefit greatly from an option to record pre-processed audio locally.

**Describe the feature you have in mind**
Add an uncompressed & pre-processed .wav option to the recording dialog when multitrack recording is selected. Only the audio of the person running the client would be recorded pre-processed.

**Describe alternatives you've considered**
Jack could be used on Linux to route audio from a microphone to both mumble and a DAW, but this results in a much more complicated setup.  I don't know how this could be done on Windows.

**Additional context**
For two people to capture pre-processed audio of a conversation, both would need record the conversation with this new option selected.

**Comment by Krzmbrzl** [comment]
What do you mean exactly with "pre-processed"? :thinking:

**Comment by frankdeath** [comment]
A blog post describing what is recorded (https://www.mumble.info/blog/for-the-record/) says this:

"But the audio geeks among you might ask themselves what we do actually save? Currently the answer to that is: Pretty much the same as you can hear minus positional audio (mono only at this time) plus what you say. Meaning it receives the same post-processing as the audio you hear does"

I have recorded uncompressed multitrack audio using mumble and the recording still has obvious artifacts in it that aren't present when recording directly in Ardour. These artifacts are obvious at default Mumble's default quality levels and subtle if the quality is raises to the max allowed by Opus using (using the config file to exceed the max allowed by the mumble client).

It sounds like the uncompressed .wav is being saved after the Opus codec is applied to the audio, since the quality of the resulting uncompressed audio depends on the quality setting in the mumble client.

I would like mumble to be able save the raw audio that it receives from the mic, so that the audio sounds the same as it would if it were recorded in Audacity or Ardour.

**Comment by frankdeath** [comment]
My mumble server might be defaulting to the CELT codec and not using Opus as I expected. It looks like I need to set ``opusthreshold`` in the server config file:
```
opusthreshold=0
```

**Comment by JuniorJPDJ** [comment]
You are asking about just recording mic without any processing of audio? Why just not do this with other app? Eg. something from your OS? Anyway you would need to record it from both sides.

**Comment by frankdeath** [comment]
Mumble is used because the two people having the conversation are not in the same location, so using another app like a DAW is not an option.

I understand that both people having a conversation would need to enable the feature I'm suggesting to capture raw audio from both sides of a conversation. That is much less work than teaching an interviewee to use another piece of software.

I don't think the recording of raw audio needs to be a mutually exclusive option with the existing uncompressed .wav option.  Recording the input audio in addition to the output audio could be very useful for troubleshooting other audio quality problems.

**Comment by Krzmbrzl** [comment]
Let's suppose we were adding the functionality of recording the mic before encoding it via Opus. Wouldn't that then record your interview partner at a lower quality than yourself because all you hear from them will inadvertently have been encoded using Opus?

Or would you want your partner to record themselves using Mumble and then passing on the recorded audio to you afterwards so both audio files can be merged? :thinking:

**Comment by frankdeath** [comment]
The latter. Your partner would record themselves using Mumble and then pass the raw audio to you afterwards.

**Comment by Krzmbrzl** [comment]
To me it seems that this kind of feature is not in the scope of Mumble.
If you need the raw input of the mic, you should record that using a dedicated software.

Having the feature inside Mumble in addition to the already existing functionality would make the implementation a bit chaotic as you'd have to attach to the audio stream in multiple places. I would consider this a bit of a readability killer :thinking:

**Comment by vimpostor** [comment]
I agree that this is out of scope of Mumble. Just use an OS and an audio stack that does support easy routing in the audio node graph (like Jack or Pipewire). From what I heard, this is very easy on MacOS too.
