### ISSUE TITLE
Launching Vegas Pro with mumble running mutes mumble

### ISSUE THREAD

**Issue by RagingFlames** [mumble-voip/mumble#5153]
**Describe the bug**
If I have mumble running and am connect to a server with people in it, then launch Vegas pro 16, mumble will stop playing audio. I will no longer hear people talking, and it will not show up as muted in the windows sound mixer.

**Steps to Reproduce**
1. Launch mumble
2. Connect to server
3. Join a channel with people in it
4. Launch Vegas Pro 16

**Expected behavior**
Mumble should not stop playing audio when Vegas Pro is running

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.3.4

**Additional context**
This very well could be a bug with Vegas Pro, I'm not sure though. Mumble is the only program that has these audio problems only happen with mumble. I can report this to Magix if this is on them though.

**Comment by davidebeatrici** [comment]
Does perhaps Vegas Pro open the audio device in exclusive mode?

**Comment by RagingFlames** [comment]
I think that may be it actually. I'm going to close this issue because I think this is a Vegas Pro issue. I found another program that takes issue with opening vegas pro. It is weird that I can open mumble after vegas pro and have no issue, but I think this is a vegas pro thing, not a mumble thing.

**Comment by davidebeatrici** [comment]
Vegas Pro probably opens the audio device in shared mode if it detects that another program is using it.
