### ISSUE TITLE
[macOS] "Can't be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by vichug** [mumble-voip/mumble#5160]
Hey there, 
I've been trying the mumble release on Mojave (1.3.3) and the OS won't let the .dmg open when i double click it, the error displayed is "Can't be opened because Apple cannot check it for malicious software". There is no possibility by default in the system preferences to open said .dmg ; i say that because sometimes you go there and see a clickable button "open anyway" which is enough to open said application.

macOS version is Mojave 10.14.6

To effectively succeed in opening Mumble, one must enter this in terminal :
`sudo spctl --master-disable`
**which is not recommended** because it disables any Apple check for application : you will see another option checked in the same security preferences pane, which says to accept opening applciations from "anywhere". Once that command is enterde, it is then possible to mount Mumble-1.3.3.dmg .
Here is a screenshot of the displayed pop-up - in french, sorry. 
<img width="420" alt="impossible" src="https://user-images.githubusercontent.com/4671710/124385597-adaf7000-dcd6-11eb-8586-34fd2c1233be.png">

I am unsure if this has been reported already - sorry if that's the case, i searched both open and closed issues.

**Comment by Krzmbrzl** [comment]
This is macOS being retarded. See https://github.com/mumble-voip/mumble/issues/4016#issuecomment-619688036

(also see #4263 which I think is related in the overall scheme)

**Comment by vichug** [comment]
https://github.com/mumble-voip/mumble/issues/4016#issuecomment-619688036 wouldn't help, because the .dmg cannot be opened, it's not only the app... Plus, you may be right in macos beeing "retarded", but that's just how macos works, so this doesn't count in what i would call a "resolved" issue. Then again i guess the userbase on macos is probably low, but the problem still remains.

**Comment by Krzmbrzl** [comment]
> The present issue is totally a replicate of #4263 actually.

There is (was) an option to still start non-notarized apps somewhere, I think :thinking: 
I forgot how that is to be done though and don't have a machine with macOS to test it on.

If in fact there is no such option (anymore), you'll have to wait for the 1.4.0 release (or upcoming release candidate) as that will be notarized.

**Comment by davidebeatrici** [comment]
Did they seriously remove the option to ignore the warning?

**Comment by deraffe** [comment]
@davidebeatrici No they have not, it's just hidden: right click → Open shows you a different dialog that allows you to run the app.

**Comment by vcekron** [comment]
For anybody who stumbles upon this thread in 2025 looking for a solution, I did not find that right-clicking and pressing "Open" was enough. However, this worked: https://github.com/mumble-voip/mumble/issues/4263#issuecomment-1955805532. That is:
```
xattr -d com.apple.quarantine Mumble.app
```
