### ISSUE TITLE
PulseAudio no longer loaded

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#5181]
**Describe the bug**
Since commit 8aa7d9ab09b4411a1e6796659dd254628514844a initializing PulseAudio no longer works and hence it is not selectable in the Mumble settings for audio input/output. 

**Steps to Reproduce**
1. Compile Mumble on Linux, latest Git version (ce90876bf02866ea08ab66c940f0c73ba66d531a)
2. Start Mumble
3. Check if PulseAudio is enabled

**Expected behavior**
PulseAudio should be initialized properly and selectable in the Mumble settings.

**Desktop**
 - OS: Arch Linux
 - Version: Mumble-git

**Additional context**
```
$  LC_ALL=C mumble
<D>2021-07-12 20:08:30.532 PulseAudio 14.2.0 from libpulse.so
<W>2021-07-12 20:08:30.535 PulseAudio: Forcibly disconnected from PulseAudio
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<D>2021-07-12 20:08:30.551 PortAudio V19.7.0-devel, revision unknown from libportaudio.so
<X>2021-07-12 20:08:30.552 PipeWire 0.3.31 from libpipewire-0.3.so
<D>2021-07-12 20:08:30.552 JACK 1.9.18 from libjack.so
<D>2021-07-12 20:08:30.560 libopus 1.3.1 from libopus.so.0
<W>2021-07-12 20:08:30.561 CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
<W>2021-07-12 20:08:30.561 Applying fallback style sheet
<W>2021-07-12 20:08:30.561 Locale is "C" (System: "C")
<W>2021-07-12 20:08:30.561 Unable to find bundled translations for locale "C"
<W>2021-07-12 20:08:30.586 Database SQLite: "3.36.0"
<W>2021-07-12 20:08:30.596 Overlay: Listening on "/run/user/1000/MumbleOverlayPipe"
<W>2021-07-12 20:08:30.597 Updating application palette
<W>2021-07-12 20:08:30.604 GlobalShortcutX: Using XI2 2.3
<W>2021-07-12 20:08:30.616 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2021-07-12 20:08:30.674 AudioInput: Opus encoder set for low delay
<W>2021-07-12 20:08:30.674 AudioInput: 128000 bits/s, 48000 hz, 480 sample
<W>2021-07-12 20:08:30.675 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2021-07-12 20:08:30.676 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2021-07-12 20:08:30.693 Zeroconf: Third-party browser API reports error -65537
<W>2021-07-12 20:08:45.365 QXcbConnection: XCB error: 3 (BadWindow), sequence: 2344, resource id: 8584451, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/ce90876bf02866ea08ab66c940f0c73ba66d531a/src/mumble/PulseAudio.cpp#L62-L73

https://github.com/mumble-voip/mumble/blob/ce90876bf02866ea08ab66c940f0c73ba66d531a/src/mumble/PulseAudio.cpp#L90

https://github.com/mumble-voip/mumble/blob/ce90876bf02866ea08ab66c940f0c73ba66d531a/src/mumble/PulseAudio.cpp#L112-L118

https://github.com/mumble-voip/mumble/blob/ce90876bf02866ea08ab66c940f0c73ba66d531a/src/mumble/PulseAudio.cpp#L858

This is far from ideal: we should not start the loop until either audio input or output is started and is set to use PulseAudio.

As for the good/OK check, we should only care about the initialization functions succeeding.

**Comment by davidebeatrici** [comment]
Turns out the API requires the context to always be associated to a loop: https://gist.github.com/andrewrk/6470f3786d05999fcb48

Which means that if the loop is not running we cannot even get a list of input/output devices.

This explains why we had the awful timer in the first place...

**Comment by Krzmbrzl** [comment]
Okay so that means we have to start the asynchronous PulseAudio loop in order to determine whether or not we can use PA, right?
To me it seems that as soon as the system is ready, it calls back into `PulseAudioSystem::contextCallback` and once that happened, we can determine whether we are to load PA or discard it.

In that case I would propose to add a `std::condition_variable` (plus a few others) member to the PA-system class and add a public function like this:
```cpp
void PulseAudioSystem::waitOnInit() {
    std::lock_guard<std::mutex> guard(m_lock);
    
    if (m_initialized) {
        return;
    }

    m_conditionVariable.wait(guard);

    assert(m_initialized);
}
```
and then we'd have to add the following to `PulseAudioSystem::contextCallback`:
```cpp
void PulseAudioSystem::contextCallback(pa_context *c) {
    // ...
    // The default: return; block has to be removed

    {
        std::lock_guard<std::mutex> guard(m_lock);
        m_initialized = true;
    }

    m_conditionVariable.notifiy_all();
}
```

This should then cut the waiting to be precisely as long as needed (plus a minor overhead for the synchronization) and seems to be much, much more efficient (and reliable) than an arbitrary timer.

@davidebeatrici thoughts?

**Comment by davidebeatrici** [comment]
That's probably the best solution. What about writing the code directly in the constructor instead of creating a new function?

**Comment by Krzmbrzl** [comment]
You mean performing the waiting at the end of the constructor instead of having to explicitly having to (remember to) call a function?

That sounds good to me. The function-approach has the advantage that the program could go and do something else before it starts waiting but I assume we currently don't have a use-case for that anyway :thinking: 

So yeah delaying the constructor until the initialization is actually done sounds good to me :+1:

**Comment by davidebeatrici** [comment]
The function-approach has the advantage that the program could go and do something else before it starts waiting but I assume we currently don't have a use-case for that anyway :thinking:

Only if you run the function in a separate thread.

**Comment by Krzmbrzl** [comment]
> Only if you run the function in a separate thread.

I was meaning to not call the function until being done with the other work. But anyway - we don't need that :)
