### ISSUE TITLE
Mumble prefers system rnnoise to the bundled one, even if it has a different API

### ISSUE THREAD

**Issue by WGH-** [mumble-voip/mumble#5182]
I have a rnnoise installed system-wide (version https://gitlab.xiph.org/xiph/rnnoise/-/commit/1cbdbcf1283499bbb2230a6b0f126eb9b236defd). It has a different API than the one bundled with Mumble, and Mumble prefers the system-wide version, causing build failure.

```
AudioInput.cpp: In constructor ‘AudioInput::AudioInput()’:
AudioInput.cpp:109:32: error: too few arguments to function ‘DenoiseState* rnnoise_create(RNNModel*)’
  109 |  denoiseState = rnnoise_create();
      |                                ^
In file included from AudioInput.cpp:25:
/usr/include/rnnoise.h:80:30: note: declared here
   80 | RNNOISE_EXPORT DenoiseState *rnnoise_create(RNNModel *model);
```

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Version: 1.3.4, also tested f5bf5f17f3c207bb18ecd2dfc9ccdfa3136b6c7f (the tip of 1.3.x branch, a few commits ahead of 1.3.4).

See also https://bugs.gentoo.org/801961

**Comment by WGH-** [comment]
My bad, it seems I'm supposed to explicitly use `bundled-rnnoise`.

**Comment by WGH-** [comment]
On second thought, rnnoise has no releases, no API/ABI compatibility, no sonames, etc. 

Maybe it's a bad idea to attempt to use the system one by default, since there's a great chance that it won't be compatible?

**Comment by WGH-** [comment]
See also some discussion here: https://bugs.gentoo.org/801961#c6

**Comment by Krzmbrzl** [comment]
@WGH- The issue you are seeing should not occur when building against current master or against the 1.4.x branch. Could you verify that?

**Comment by Krzmbrzl** [comment]
Oh and I just checked: The option you used no longer exists in these branches and on all platforms but Windows we build rnnoise as a static library that gets linked into Mumble anyway.
Thus as far as I can tell this issue is already fixed.

As we are not responsible for packaging Mumble on Gentoo, I'll close this issue again as it seems to me that everything that can be fixed on our side has already been fixed :thinking:
