### ISSUE TITLE
Mumble 1.4 locks up after a while

### ISSUE THREAD

**Issue by hbeni** [mumble-voip/mumble#5187]
With a Mumble 1.4 snapshot (ccbfa5fd5ec) on Linux and with fgcom-mumble plugin running, my Mumble locks up after a while (10 minutes or so) when i get much talking.

I'm still in the process of trying to get more info, but it somehow looks like something (a buffer?) is running over after a while.

The symptom is that the GUI is frozen, but incoming audio is still audible. I can't talk to anyone however.

**Comment by Krzmbrzl** [comment]
From you description it seems as if it is reproducible. If so, could you attach GDB to Mumble to check where it does lock?

Is the CPU spiking when Mumble is locking? Or does it seem to to remain as usual?

Does this issue also persist without the plugin loaded?

**Comment by hbeni** [comment]
What I already have seen is that it was triggered with me beeing the only one with plugin loaded.
It seems to not trigger when I'm alone in the server.

**Comment by hbeni** [comment]
(I suspect, the plugin does trigger some locking issue again, like we already fixed some weeks ago)

**Comment by hbeni** [comment]
(may possibly related to https://github.com/hbeni/fgcom-mumble/issues/138?)

**Comment by Krzmbrzl** [comment]
> Is this triggered, when the GC cleans out local state, and then wants to update the local user comment?

GC? Are you talking about a garbage collector? If so: What GC are you talking about? :eyes:

**Comment by hbeni** [comment]
> > Is this triggered, when the GC cleans out local state, and then wants to update the local user comment?
> 
> GC? Are you talking about a garbage collector? If so: What GC are you talking about? eyes

Yes, GarbageCollector. It's the one I made myself :)
https://github.com/hbeni/fgcom-mumble/blob/master/client/mumble-plugin/lib/garbage_collector.cpp

It just walks down the data and then removes old entries. I *think* it may be at least causing part of this - if the GC removes the local data, and it is then referenced, it is clear that there is a segfault.
However, it just removes the local data struct entry, and not the `localMumId` not the `ownPluginID`, so i don't exactly know whats going on. I need to learn gdb a bit better to inspect the internal state at the segfaulted program.

**Comment by Krzmbrzl** [comment]
Ah okay I see. After looking at the issue in more detail now, I don't think that this causes the lock though. If you experience this Segfault, then Mumble will crash. What you describe here is not a crash though :thinking: 

For the time being I'll wait to see if you can reproduce the lock again in order to give the details I asked about earlier :point_up:

**Comment by hbeni** [comment]
I could no reproduce with the build from PR #5193.
Will try next wednesday a last time, then we finally can close this.

**Comment by hbeni** [comment]
hbeni/fgcom-mumble#139:
> So, I will close this now.
> Was not reproducable with 7 real human clients.

**Comment by hbeni** [comment]
sorry for the noise
