### ISSUE TITLE
Typing in the main window no longer searches

### ISSUE THREAD

**Issue by schoerg** [mumble-voip/mumble#5206]
**Describe the bug**

Previously you could search a user or channel by typing the channel name (or user) in the tree. The selection would then go to that channel if found. This no longer works. Typing in the main window does nothing.

**Steps to Reproduce**
1. Join server with multiple channels
2. Type channel name

**Expected behavior**
The channel or user found via typing should be selected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: `1.4.0~2021-05-16~g789f2d7~snapshot`

**Additional context**
I don't know if this change is intentional as there is a "Search for user or channel" function now.
This was introduced in #4967 but no mention that the old way is no longer possible.

Edit: 27832656208a45f07e3d67cb344fbc91f99fe954 mentions that this is intentional. Oh well...

**Comment by Krzmbrzl** [comment]
This is expected behavior. It got replaced by a proper search function as you have discovered already :point_up: 

> Edit: 2783265 mentions that this is intentional. Oh well...

Yes indeed :D
