### ISSUE TITLE
Mumble server listens on IPv6 only when started before network is configured

### ISSUE THREAD

**Issue by WGH-** [mumble-voip/mumble#5208]
When Mumble server starts, and `host` is unset, it enumerates network interfaces to determine whether it wants to bind to IPv4, IPv6, or both.

Note that IPv6 link-local addresses are usually autoconfigured when link simply becomes up. This means that when ethernet link is up, but there's no DHCP server/gateway in the network, Mumble will consider the network to be IPv6-only, and thus will bind to IPv6 only, and will be unavailable over IPv4 until manually restarted.

https://github.com/mumble-voip/mumble/blob/2d2225b85f2bcec7883b7d9cc430fcb9eacdb2c5/src/murmur/Meta.cpp#L244-L297

**Steps to Reproduce**
The following command simulates a system with only IPv6 address configured:
```
sudo unshare -n sh -c 'ip link add dev dummy0 type dummy && ip link set dev dummy0 up && ip addr show && strace -e bind,setsockopt murmurd -v -fg'
```

Note that the command above doesn't set up IPv6 address explicitly: the autoconfigured link-local address (fe80::/64) is enough.

Mumble creates an IPv6 socket with `IPV6_V6ONLY` set:
```
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether a6:ad:f1:50:06:7a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a4ad:f1ff:fe50:67a/64 scope link
       valid_lft forever preferred_lft forever

<...>

setsockopt(11, SOL_SOCKET, SO_OOBINLINE, [1], 4) = 0
setsockopt(11, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(11, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
bind(11, {sa_family=AF_INET6, sin6_port=htons(64738), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::", &sin6_addr), sin6_scope_id=0}, 28) = 0
<W>2021-07-27 16:37:25.069 1 => Server listening on [::]:64738
```

**Expected behavior**
I think Mumble should simply bind to `::` (any IPv6 address) with "IPv6 only" disabled (meaning it will also accept IPv4 connections). `QHostAddress::Any` does exactly that.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: `1.3.0+dfsg-1build1` (Ubuntu 20.04), `1.3.3` (the relevant code doesn't seem to be changed since)

**Additional context**
Workaround available:
```
host="0.0.0.0  ::"
```

**Comment by Krzmbrzl** [comment]
> I think Mumble should simply bind to :: (any IPv6 address) with "IPv6 only" disabled (meaning it will also accept IPv4 connections). QHostAddress::Any does exactly that.

That sounds very reasonable to me. The only question would be: Would that cause any errors on machines that really don't have either IPv4 or IPv6 support? I would imagine the latter would be a problem? :thinking:

**Comment by WGH-** [comment]
I suppose Mumble could catch errors from `bind`, and fall back to `QHostAddress::AnyIPv4`?

**Comment by WGH-** [comment]
On second thought, calling `socket` should be enough. If corresponding family (`AF_INET`/`AF_INET6`) is supported, you should be able to bind to the "any" address alright.

I looked at the code again: it seems half of the work is already done by `hasDualStackSupport`. We only need another function that checks for `AF_INET6` support (without checking the `IPV6_V6ONLY` part).

So something like this, I guess?
```
if hasDualStackSupport():
    addresses = [QHostAddress::Any]
elif hasIPv6():
    addresses = [QHostAddress::AnyIPv4, QHostAddress::AnyIPv6]
else:
    addresses = [QHostAddress::AnyIPv4]
```

**Comment by Krzmbrzl** [comment]
That seems logical to me - though admittedly I know next to nothing to how this networking stuff is supposed to work on such a low-level :shrug: 

Would you mind creating a PR? :innocent:

**Comment by WGH-** [comment]
Yeah, will do.

I still want to figure out a couple of questions first:
- Does Qt's `QHostAddress::Any` already do something (or all) of it for us?
- Is there any system not supporting `IPV6_V6ONLY`?

**Comment by vimpostor** [comment]
From the Qt documentation: 
```
QHostAddress::Any | The dual stack any-address. A socket bound with this address will listen on both IPv4 and IPv6 interfaces.
```

For me this sounds like using it directly would not cause any problems, if a device does not support IPv6. Listening on all ipv6 interfaces is still listening on 0 interfaces, if there are no ipv6 interfaces.

**Comment by WGH-** [comment]
https://github.com/qt/qtbase/blob/3b8127c3fcf07905180e274c7e554aaa757963c3/src/network/socket/qnativesocketengine_unix.cpp#L501-L525

It seems it does what we need: try IPv6 socket with `IPV6_V6ONLY` set to 0, retry with IPv4 in case of failure.

**Comment by pucgenie** [comment]
Experiencing a similar problem where some TLS renew causes mumble-server to rebind - but then it does IPv6-only. Can't reproduce at will, but got some logs and will try to raise a new issue... (host not set in config - version 1.3.4-1)
