### ISSUE TITLE
link PA Minecraft mod doesn't work in 1.4.x (works in 1.3.3)

### ISSUE THREAD

**Issue by jason-green-io** [mumble-voip/mumble#5217]
**Describe the bug**
Are 1.3.x link apps expected to be able to "just work" with the "new" legacy running built-in link plugin? Trying a Minecraft mod utilizing link under 1.4.x doesn't put me positional audio. Works as expected in 1.3.x.

**Steps to Reproduce**
1. Use 1.4.0 snapshot 6 on MacOS x86
2. Use fabric-mumblelink-mod 0.8.3 from https://github.com/magneticflux-/fabric-mumblelink-mod
3. Positional audio doesn't work (works if you switch to Mumble 1.3.3)

**Expected behavior**
Same behavior as 1.3.3, positional audio works.

**Desktop (please complete the following information):**
 - OS: MacOS 11.5 Big Sur x86
 - Version: 1.4.x

**Additional context**
 It not sure if this a Mumble issue or an interaction between the plug-in and mod.

**Comment by davidebeatrici** [comment]
I confirm legacy plugins are supposed to just work, there were also no changes whatsoever to Link compared to 1.3.x.

**Comment by jason-green-io** [comment]
Does the legacy header or new framework maybe clobber values passed into shared memory from an app?

**Comment by jason-green-io** [comment]
Perhaps 1.4.x does this:

https://github.com/mumble-voip/mumble/blob/cc037569471c4bf614a84b7d1f7cef20edefa235/src/mumble/PluginManager.cpp#L418

and 1.3.x doesn't, which makes the same app have different contexts depending on Mumble version?

**Comment by Krzmbrzl** [comment]
@jason-green-io yes that is indeed new. To verify that this is the issue, please try using positional audio with someone who ID also running the latest client snapshot. If that was the root cause, then it should work in this case 👀

**Comment by jason-green-io** [comment]
I have tested:

2 clients on 1.4.0 snapshot 6, PA works as expected.
2 clients on 1.3.3, PA works as expected.

1 client on 1.4.0 snapshot 6 and one client on 1.3.3, PA does not work.

I think 1.4.0 is doing something with the context that 1.3.x doesn't.

**Comment by jason-green-io** [comment]
Alright.. the Minecraft mod calls itself "Minecraft", which gets set in shared memory, in 1.3.x this is the "plugin name" that get tagged on to the context. In 1.4.x, the name that get tagged on to the context is the name of the plugin as defined in the Link source.. "Link". If I cheat and rename the 1.4.x Link plugin from "Link" to "Minecraft", the positional audio works as indented between 1.3.x and .14.x clients.

**Comment by Krzmbrzl** [comment]
Okay yeah then this is indeed an artifact of my change to how contexts are handled.

I prepend the plugin's name in order to avoid context clashes of different plugins (thus players playing different games would end up hearing one another.

> If I cheat and rename the 1.4.x Link plugin from "Link" to "Minecraft", the positional audio works as indented between 1.3.x and 1.4.x clients.

Yikes that means that the comparison on the server stops at the first null byte which it should not. Is the server still running 1.3.x or is that also a snapshot version?

----

All in all though I would consider the case that users are in the same channel but are playing different games whose Mumble plugins collide with their contexts is pretty unlikely. Thus I think the best thing would be to remove the logic of prepending the plugin's name to the context.

**Comment by jason-green-io** [comment]
The server is a hosted instance on mumble.com

**Comment by jason-green-io** [comment]
1.3.x also has this though. Stripping it out of 1.4.x isn't going to fix compatibility.

https://github.com/mumble-voip/mumble/blob/c0b5be7134673fa1c4c434b72552c200bca37b8d/src/mumble/Plugins.cpp#L434

I believe the fix in 1.4.x should be appending the same values as provided by shared memory. Like in 1.3.x.

**Comment by davidebeatrici** [comment]
Good catch. Link, unlike other plugins, has a dynamic name.

**Comment by davidebeatrici** [comment]
It may make sense to prepend the name in the plugin itself, as there may be cases where achieving the same context across multiple plugins is desirable.

I would migrate Link to the new API and then prepend the name in Mumble only for plugins that use the legacy API.

@Krzmbrzl What do you think?

**Comment by Krzmbrzl** [comment]
Sounds like a plan. I would implement it by extending the plugin API by an optional getter function for the context prefix. If the plugin doesn't provide it, we can default to the plugin name but that way a plugin can use whatever prefix it wants...

**Comment by Krzmbrzl** [comment]
@jason-green-io could you test whether the issue persists with the changes of #5316?
(Be prepared that it might not work at all, since I did not test these changes yet)
