### ISSUE TITLE
Support - How to check number of active users can be handled on the mumble server.

### ISSUE THREAD

**Issue by prashant-17-dev** [mumble-voip/mumble#5219]
I was trying to check the number of active connections that can be handled on the Mumble server. 
was trying below command ->

murmurd -ini /etc/mumble-server.ini -limits

which is constantly giving the same output on different configurations servers.

<W>2021-08-02 07:12:24.341 Initializing settings from /etc/mumble-server.ini (basepath /etc)
<W>2021-08-02 07:12:24.341 Binding to address x.x.x.x
<C>2021-08-02 07:12:24.619 Successfully switched to uid 1000
<W>2021-08-02 07:12:24.619 Resource limits were 0 0
<W>2021-08-02 07:12:24.619 Successfully dropped capabilities
<W>2021-08-02 07:12:24.619 Running descriptor test.
<W>2021-08-02 07:12:24.619 0 descriptors...
<C>2021-08-02 07:12:24.624 Managed to open 1014 descriptors
<W>2021-08-02 07:12:24.624 0 threads...
<F>2021-08-02 07:12:24.639 Managed to spawn 126 threads

I have customized the .ini file with a user count of 10000. 

I just want to check whether those many users can be handled by the server.  TIA.

**Comment by Krzmbrzl** [comment]
I think there is no other way than to actually have users connect to your server and meanwhile monitoring the server load.
You could also fake clients using a bot framework like PyMumble.

**Comment by prashant-17-dev** [comment]
@Krzmbrzl To support the maximum number of users what do you suggest a better configuration of the machine?

(basically, what should we consider RAM/external storage)

**Comment by JuniorJPDJ** [comment]
This is not real issue with mumble, please close it.
You can still comment on closed issues if you still want to get some help.

**Comment by Krzmbrzl** [comment]
You mean what kind of hardware you will want to rent in order to support any given amount of users?
With that I probably won't be a big help since I have never hosted a big server nor have I performed resource benchmarks...

You could consider joining our Matrix channel (see README) and ask there. I am sure there are folks who know more details there :thinking:
