### ISSUE TITLE
Mumble Positional Audio not working with bluetooth headphones

### ISSUE THREAD

**Issue by phlipped** [mumble-voip/mumble#5220]
Positional audio doesn't work with my bluetooth headphones (Airpods)  - audio volume is the same in both channels regardless of position of the audio source.

This happens in the "Audio Wizard", as well as when linked to a game (Minecraft with Mumblelink, using  Mumble's Link plugin v1.2)

Positional audio works using the built-in speakers. (It even still works when bluetooth headphones are connected, and I explicitly configure Mumble to use the built in speakers as the output device)

**Steps to Reproduce**
1. Activate bluetooth headphones, then open Mumble
2. Configure > Audio  Wizard
3. On Device Selection panel, ensure 'Enable positional audio'  is selected in the Output Device pane
4. Click  'Next' repeatedly to get to the 'Positional Audio' panel
5. An audio clip plays ... "This is an example of speaks ...", but the audio volume in each left/right channel stays the same regardless of the location of the little circles in the pane
6. Selecting "Use headphones" doesn't seem to change anything, other than resetting the audio sample
7. Also, there aren't any little circles that represent the speakers as there normally are when positional audio is working.

**Expected behavior**
The audio volume in each left/right channel would be adjusted in accordance with the position of the moving circle. And there would be little circles in the display that represent the position of the speakers.

**Desktop (please complete the following information):**
 - OS: MacOS 11.4, Macbook Pro 2018
 - Version: Mumble 1.3.3 (but also occurs when I compile it myself from the head of the master branch)

**Additional context**
I'm able to build the app and might be able to try out debug builds and/or run a debugger or turn on additional logging, but I'd need some help with that

**Comment by phlipped** [comment]
Having just discovered the developer console, I can add the following:

Whenever the bluetooth headphones are the output device (ie positional audio not working), the developer console log shows:
...
<W>2021-08-03 22:25:15.198 CoreAudioOutput: Set device to 'b4-40-a4-ac-a1-a9:output'.
<W>2021-08-03 22:25:15.200 AudioOutput: Initialized 1 channel 16000 hz mixer
<W>2021-08-03 22:25:15.201 CoreAudioOutput: BufferFrameSizeRange = (5.00, 2880.00)
...

Whereas with the built-in speakers as the output device, I get the following:
<W>2021-08-03 22:24:19.982 CoreAudioOutput: Set device to 'BuiltInSpeakerDevice'.
<W>2021-08-03 22:24:19.989 AudioOutput: Initialized 2 channel 44100 hz mixer
<W>2021-08-03 22:24:19.990 CoreAudioOutput: BufferFrameSizeRange = (14.00, 4096.00)

**Comment by Krzmbrzl** [comment]
From the log you can see that the airpods are recognized as a mono device. With that positional audio is not possible.

In the settings for positional audio there is a "headphones" checkbox - did you try checking that?

**Comment by phlipped** [comment]
Yes, I tried checking the headphones checkbox - didn't help (see Step 6 in my initial report).

Additional info:
The problem doesn't occur if I configure Mumble to use a different device for Input (ie ... if I use the built-in Mic for input, and the Airpods for output, then positional audio works)

So ... I guess this is all tied up with Bluetooth audio profiles. As I understand it, there are various different profiles that control bandwidth and codecs between the bluetooth device and the computer. Presumably the number of channels is part of that as well. And they bluetooth profile that is selected depends on whether or not the Mic on the bluetooth device is active.

I'm not sure if there's anything Mumble is going to be able to do about that - it feels like the kind of thing that is going to be outside of Mumble's control.

BUT ...

Even if this can't be fixed in Mumble, it would be super helpful if Mumble could warn the user that the Output Device is  Mono. (Especially if they are trying to use Positional Audio). It's basically impossible for the end user to know that their bluetooth headphones are in Mono mode (unless they open up the Developer console).

**Comment by ZeroAbility** [comment]
Are you able to confirm if this happens when listening to music or other audio files that would test audio separation? If it does, try troubleshooting the bluetooth pairing by deleting it from the Mac, cradling the Airpods for a minute or two, and turning off airplane mode and pairing again. I don't know if there are software updates for those, but that may help.

**Comment by phlipped** [comment]
Thanks for the suggestions.

At this stage I don't think the underlying issue can be fixed - it's just not possible to have Airpods in stereo mode while using the mic. And in any case it's not Mumble's responsibility to try to fix it. And I have workarounds.

So I think the only thing left to consider is the idea of adding a warning in Mumble when the output device is mono - perhaps only if the user has positional audio enabled? Otherwise, this bug could probably be closed.

**Comment by JuniorJPDJ** [comment]
>Even if this can't be fixed in Mumble, it would be super helpful if Mumble could warn the user that the Output Device is Mono. (Especially if they are trying to use Positional Audio). It's basically impossible for the end user to know that their bluetooth headphones are in Mono mode (unless they open up the Developer console).

very big +1

**Comment by Krzmbrzl** [comment]
Closing in favor of #5238
