### ISSUE TITLE
1.4.0 snapshot 6 does sometimes not cap key in background

### ISSUE THREAD

**Issue by ViBE-HU** [mumble-voip/mumble#5222]
**Describe the bug**
It's a bit new to me cause it was not an issue before. So if I start a game after a short time Mumble will not cap the assigned voice key. May other hotkey related functions works well but I only use voice key atm.

**Steps to Reproduce**
1. Start Mumble
2. Start a full screen game/application
3. Push the voice key after a short time

**Expected behavior**
It should instantly start transmit voice.

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19043 (19041.vb_release.191206-1406)
 - Version: Mumble 1.4.0.191

**Additional context**
Nowadays I use Windows less but the stable 1.3.4 is still installed and comparing with that the stable version has no issue with key capping.

**Comment by Krzmbrzl** [comment]
What do you mean by "cap"? From your description I assume that the hotkey stops working when entering a game?

**Comment by ViBE-HU** [comment]
i mean capture. it behaves strange cause it works for a few minutes after a full screen game started but then it does nothing. after an alt+tab it will works again for a few minutes in-game.

**Comment by Krzmbrzl** [comment]
Does this happen with any fullscreen application or only games? And if the latter: Did you test this in multiple games or only a specific one?
