### ISSUE TITLE
Support - How many virtual mumble server can be created on Single instance.

### ISSUE THREAD

**Issue by prashant-17-dev** [mumble-voip/mumble#5224]
My use case is - We have thousands of teams for those teams we want to create separate virtual servers on a single machine now we are worried about how many virtual servers can be created on one machine. stats or suggestions will really appreciate.

**Comment by Krzmbrzl** [comment]
I assume that the amount of virtual servers you can create mainly depends on two factors:
1. How many users you can manage on your given hardware. I think that the overhead in processing for having users on different virtual servers is not that big so I would assume that the maximum amount of users that can be served this way is about the same as if all users were on a single server.
2. If the overall user count is not the bottleneck, then I would assume that the thing to consider is that each server instance will occupy at least 2 threads (one control thread for handling control messages over TCP and one voice thread handling the voice packets over UDP). Thus you might have to check what the limit of simultaneously existing threads on your system is.

Both factors will vary greatly on different hardware though, so it is hard to give general estimates...

That being said though, I think that it might be more efficient to use a single server and create channels with access restrictions (using ACLs) such that only specific members can enter these channels :shrug:

**Comment by prashant-17-dev** [comment]
@Krzmbrzl currently I am relying on ACLs only but my problem is with whispering. 

My use case wants to solve 1 to 1 talk. for that I am using the whispering feature. 
Now I can't control who can whisper to whom using ACL. is there any way please do let me know. 

because of this, I was thinking of having separate virtual servers per team and allowing them to speak(i.e. 1 to 1) with everyone on their server.

I got your point regarding virtual servers thanks for the explanation.

**Comment by Krzmbrzl** [comment]
Iirc you can restrict who can whisper to clients that are in a given channel using the Whisper ACL :thinking:

**Comment by prashant-17-dev** [comment]
Yes, we can decide who can whisper using ACL using whisper permission. but whom to whisper can't be controlled. Users having whisper permission can whisper to another team member.

**Comment by Krzmbrzl** [comment]
I just looked it up and the ACL I was referring to was "Speak". And iirc you can't whisper to a person who is in a channel that you don't have speak permission. Did you try that out?

**Comment by prashant-17-dev** [comment]
Ohh on root, channel speak was allowed to all and that ACL was getting inherited. I think I can achieve it @Krzmbrzl thanks

**Comment by Krzmbrzl** [comment]
Yes that's the default but you should be able to overwrite this ACL on a per-channel basis :)
