### ISSUE TITLE
cannot change the push to talk key from shift and i wanna

### ISSUE THREAD

**Issue by StrikersGamingTV** [mumble-voip/mumble#5228]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. Mumble 1.3 or Murmur 1.3]

**Additional context**

**Comment by StrikersGamingTV** [comment]
also cannot open the radio have to do the command

**Comment by Krzmbrzl** [comment]
Missing information. If you want help, please spend at least a minimal amount of work into providing the necessary information
