### ISSUE TITLE
cannot change any bindings

### ISSUE THREAD

**Issue by StrikersGamingTV** [mumble-voip/mumble#5230]
**Describe the bug**
I try to change the keybindings to different fivem keys and everytime I do it stays at LSHIFT, my other members say it is on capslock but for me it is LSHIFT I also cannot open the radio

**Steps to Reproduce**
1. I have no idea it is prolly a personal error
2. again I have no idea, it is only bad for me and there is no keybind in keybinds
3. still

**Expected behavior**
no way to change my keybinding

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: newest

**Comment by davidebeatrici** [comment]
I think you're looking for https://github.com/FrazzIe/mumble-voip-fivem.
