### ISSUE TITLE
SSL Certificate problem

### ISSUE THREAD

**Issue by MoeruIshiki** [mumble-voip/mumble#5231]
Hello, I have set up my Mumble server on an Ubuntu 20.04 VPS, but for some reason murmurd generates its own SSL certificate, although I specified the path to my certificate in mumble-server.ini. Because of this, when I try to log in to my server, I get the message "Untrusted Certificate" and "CN=Murmur Autogenerated Certificate v2" in Subject. How can I solve this problem?

Thank you.

**Comment by Krzmbrzl** [comment]
Please create a minimal configuration file that reproduces the issue and show us its content - you may anonymize any sensitive information in it.
Furthermore providing the logs of the server starting up could be helpful.

**Comment by MoeruIshiki** [comment]
Sorry, here is my config file and server logs:
[mumble-server.txt](https://github.com/mumble-voip/mumble/files/6995489/mumble-server.txt)
[mumble-server.log](https://github.com/mumble-voip/mumble/files/6995490/mumble-server.log)

**Comment by Krzmbrzl** [comment]
I assume the settings file you provided is indeed the one at `/etc/mumble-server.ini`?

**Comment by MoeruIshiki** [comment]
Sure, the file I showed is the one at /etc/mumble-server.ini

I tried deleting the database and restarting the server like you said, and... It worked! Thank you very much!

**Comment by Krzmbrzl** [comment]
Okay great :+1: 

The explanation for this is that the ini file only provides _default values_ for these settings (in the vast majority of cases) which get set on the server when it boots up for the first time. After that these settings are stored on each server in the database and thus changing these values in the ini will not have any effect on an already existing server. They would only take effect if you were to create a new virtual server.
By deleting the DB you essentially deleted all known servers and thus the next time Murmur starts, it will create a fresh server that uses the current values from the ini to initialize its config.
