### ISSUE TITLE
Separate audio outputs for notifications/feedback and actual voice?

### ISSUE THREAD

**Issue by amackenzie** [mumble-voip/mumble#5232]
**Context**
With the growing amount of software noise filters (Krisp and Nvidia Broadcast come to mind), it would be nice to be able to still get things like PTT beeps and stuff while using those --- the beeps and other non-speech notification stuff get filtered out by these types of software normally.

Since these types of software generally create virtual mic/speaker devices, and Mumble currently can only select one device at a time, this means that there's no way to get audible non-voice alerts to various events.

**Describe the feature you have in mind**
The simplest (at least from the current user perspective) way might be to allow notification sounds (beeps, TTS, etc) to go to one audio device (actual speakers, etc) and actual voice to go to another audio device (Krisp Speakers, etc).

**Comment by Krzmbrzl** [comment]
I would say that in the current implementation of how audio works this is not possible and would thus require a (major) redesign of how the audio system works :thinking:

Therefore I am not sure if this is a common enough requirement to justify the effort that would be needed to implement this.

We want to rewrite the audio backend eventually but even then this seems like a lot of overhead (implementation-wise) for little gain.

@davidebeatrici @Kissaki what are your thoughts on this?

**Comment by Kissaki** [comment]
Technical issues and effort aside, I like the idea of having the feature - but off by default to prevent confusion/complexity.

With your thoughts in mind, I don’t see this happening any time soon.

**Comment by Kissaki** [comment]
We could keep this open as a feature request? Or what did you want feedback on?

**Comment by Krzmbrzl** [comment]
Yeah I was wondering if it was worth keeping this open since effectively I would say this is not actionable for anyone, unless we decide to do a rewrite (which given our current availability I don't think to be likely).

Maybe it would be worth collecting this kind of issues into a single "Nice to have should we ever make the necessary major changes to the stuff surrounding it" issue in order to not clutter the list of issues with unactionable things :thinking:

**Comment by Kissaki** [comment]
I would be fine with something like that. Differentiating rejected and postponed feature requests.

**Comment by Krzmbrzl** [comment]
Alright then I'll create such a "collector-issue" and add this idea to it.
