### ISSUE TITLE
celt.h is not found when $make 

### ISSUE THREAD

**Issue by maverick077** [mumble-voip/mumble#5233]
When I try to build mumble on linux(arm)，I successfully run $cmake .. 

So I $make, and celt is not found when $make.  

It says, "
In file included from /home/pi/programs/mumble/mumble-dev/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_AudioOutputSpeech.cpp:9,
                 from /home/pi/programs/mumble/mumble-dev/build/src/mumble/mumble_autogen/mocs_compilation.cpp:19:
/home/pi/programs/mumble/mumble-dev/src/mumble/AudioOutputSpeech.h:9:10: fatal error: celt.h:  No such file or directory.
 #include <celt.h>
          ^~~~~~~~
compilation terminated.
"

But I had installed celt0.7.0 before I build mumble. 

What's wrong? Where can I get the file "celt.h"?

![2](https://user-images.githubusercontent.com/67913398/130013760-33cc24ea-b73a-4bb7-b320-84a14f0eb9fe.jpg)

![1](https://user-images.githubusercontent.com/67913398/130013176-bc139998-75cf-4f4c-a714-d7c7acd4cb04.jpg)

**Comment by Krzmbrzl** [comment]
Did you run `git submodule update --init --recursive`?
You are not supposed to use the system's Celt version but the bundled one which comes as a submodule

**Comment by maverick077** [comment]
Hahaha，I had solved it on another way. Just copy all files from "celt-0.7.0/libcelt" and paste them to "mumble/src/mumble". And then you can $make successfully.

**Comment by Krzmbrzl** [comment]
Yeah well I suppose that works but beware that this might break in the future since this is not the supported way of doing this xD

**Comment by vimpostor** [comment]
> What's wrong? Where can I get the file "celt.h"?

Just to solve this issue for real: You specified `-D bundled-celt=off` on the cmake command line. If you don't have the correct celt installed system-wide, you have to either omit this option or specify `-D bundled-celt=on`. This way you don't need to copy the `celt` directory manually.
