### ISSUE TITLE
Unable to find matching CELT codes with other clients.

### ISSUE THREAD

**Issue by maverick077** [mumble-voip/mumble#5234]
When I start mumble, and connect with server, it shows:
"Unable to find matching CELT codes with other clients. You will not be able to talk to all users."
What's meaning? what CELT is? Does it influence the connection?
![4](https://user-images.githubusercontent.com/67913398/130025220-ca647987-9d54-4cf8-94ed-081ee5b89871.jpg)

**Comment by Krzmbrzl** [comment]
If (as I assume) this is the bug that we fixed in a more recent version, then no it doesn't affect anything. It's just a message that is shown when it shouldn't.
