### ISSUE TITLE
Start mumble with the command line instead of GUI

### ISSUE THREAD

**Issue by maverick077** [mumble-voip/mumble#5236]
I have successfully build mumble on raspberry pi 4B (Debian, linux, ARM), so I can use it communicate with others using mumble.
Now, I expect to build a special version of mumble, which can be controlled by the command line instead of GUI. 
After all, as an embedded device, it requires lower power consumption and no display.
Please give me some tips or suggestions so I can find the relevant module or source code.

**Comment by maverick077** [comment]
Or another easier question: how to control mumble with command line?

**Comment by Kissaki** [comment]
This is not currently supported by the official Mumble client. See request/ideas #3877

**Comment by maverick077** [comment]
> This is not currently supported by the official Mumble client. See request/ideas #3877

Thank you for your hint. 
Actually something like mumble is widely needed on embedded devices like raspberry pi, or other ARM platforms. So nobody #3877(command line controlled) is very useful. Mumble will be more popular for it.

**Comment by Krzmbrzl** [comment]
I agree that this would be a neat feature but it would require decoupling the frontend from the backend. This is our longterm goal but given how intertwined these currently are, it will take quite a bit to reach it, I'm afraid

**Comment by cantudo** [comment]
There is actually a headless mumble client [https://github.com/layeh/barnard](url). I have made my own fork, [https://github.com/cantudo/barnard](url), integrating a rest api allowing you to control it from a web browser, also starting and closing from the terminal. It is not well documented, the code is there, barnard is currently unmaintained but it still works.

**Comment by HongLouWang** [comment]
> There is actually a headless mumble client [https://github.com/layeh/barnard](url). I have made my own fork, [https://github.com/cantudo/barnard](url), integrating a rest api allowing you to control it from a web browser, also starting and closing from the terminal. It is not well documented, the code is there, barnard is currently unmaintained but it still works.

Link is broken

**Comment by cantudo** [comment]
> > There is actually a headless mumble client [https://github.com/layeh/barnard](url). I have made my own fork, [https://github.com/cantudo/barnard](url), integrating a rest api allowing you to control it from a web browser, also starting and closing from the terminal. It is not well documented, the code is there, barnard is currently unmaintained but it still works.
> 
> Link is broken

fixed!
