### ISSUE TITLE
No rule to make target when $make

### ISSUE THREAD

**Issue by maverick077** [mumble-voip/mumble#5242]
When I try to $make mumble on raspberry Pi again, it shows that:
"
make[2]: *** No rule to make target '../themes/Mumble/authenticated.svg', needed by 'src/mumble/mumble_autogen/6RJHKKPRHE/qrc_MumbleTheme.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1386: src/mumble/CMakeFiles/mumble.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 50%] Built target murmur
make: *** [Makefile:130: all] Error 2
"
I am confused, what's mean?  how to sovle it?

![4](https://user-images.githubusercontent.com/67913398/130392943-3734c965-bd82-4b4e-a91b-331d11a38f0c.jpg)

**Comment by Krzmbrzl** [comment]
Please run `git submodule update --init --recursive`

**Comment by maverick077** [comment]
> Please run `git submodule update --init --recursive`

It shows
"
fatal: not a git repository (or any of the parent directories): .git
"
More hints needed.

**Comment by Krzmbrzl** [comment]
You have to be in your clone of the repository when executing this command

**Comment by maverick077** [comment]
> You have to be in your clone of the repository when executing this command

Emmm... I have done it but nothing changed. The error is not solved.

**Comment by maverick077** [comment]
> > You have to be in your clone of the repository when executing this command
> 
> Emmm... I have done it but nothing changed. The error is not solved.

I run "git submodule update --init --recursive ", $make clean and $make, the problem still shows. 
Do I run it in an incorrect path?
![7](https://user-images.githubusercontent.com/67913398/130407260-6d150cf7-b9d3-41c9-9e87-4d3543939460.jpg)

**Comment by Krzmbrzl** [comment]
Since you closed the issue, I take it the problem is solved?

**Comment by maverick077** [comment]
> Since you closed the issue, I take it the problem is solved?

Emmm... 
I used to try the option "-D static=on", and I have the problem. So I delete it and the problem is solved. So strange is it.

Actually, I've been debugging gumble(3rd party mumble client) these days, it needs to modify the ini config:
"opusthreshold=0"
So how to modify "murmur.ini" directly or use murmurd to do it since I have installed mumble-server?  
I'm sorry to keep bothering you.

**Comment by Krzmbrzl** [comment]
Why would you use the `static` option in the first place? Are you aware of our [build documentation](https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions)?

> So how to modify "murmur.ini" directly or use murmurd to do it since I have installed mumble-server?

The ini file is just a regular plain-text file. So you would simply locate it, open it in your favorite text editor, make the changes and save again :shrug: 

However keep in mind that the ini only specifies _default values_ that are loaded the first time a server is created but after that point these options are saved on a per-server basis in its database and thus changes to the ini don't reflect in already existing servers.
If you want to make sure that the latest changes from the ini are picked up, delete the database and then start the server again. Note however that this will also let you lose all server-side configuration (e.g. channel tree, ACLs, registered users, etc.).
If you can't afford that, you'll have to use the ICE RPC interface to make your changes.

**Comment by maverick077** [comment]
> Why would you use the `static` option in the first place? Are you aware of our [build documentation](https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions)?
> 
> > So how to modify "murmur.ini" directly or use murmurd to do it since I have installed mumble-server?
> 
> The ini file is just a regular plain-text file. So you would simply locate it, open it in your favorite text editor, make the changes and save again 🤷
> 
> However keep in mind that the ini only specifies _default values_ that are loaded the first time a server is created but after that point these options are saved on a per-server basis in its database and thus changes to the ini don't reflect in already existing servers.
> If you want to make sure that the latest changes from the ini are picked up, delete the database and then start the server again. Note however that this will also let you lose all server-side configuration (e.g. channel tree, ACLs, registered users, etc.).
> If you can't afford that, you'll have to use the ICE RPC interface to make your changes.

Thanks.

**Comment by Kissaki** [comment]
> but after that point these options are saved on a per-server basis in its database and thus changes to the ini don't reflect in already existing servers.

I don’t think that’s correct, as general as that.

Some settings definitely update when changed in the ini. And I assume and expect server specific settings to change for the default virtual server too if they were not explicitly changed. Namely, I'm pretty sure welcometext changes work just fine, and I expect port changes to work from the ini too (unless they were changed for the/a vserver specifically).
