### ISSUE TITLE
CMake Error at cmake/qt-utils.cmake:130 (message): generate-mumble_qt-qrc.py returned exit code 1	

### ISSUE THREAD

**Issue by kartikkhullar** [mumble-voip/mumble#5244]
**Error while building the project**
Severity Code Description Project File Line Suppression State Error CMake Error at cmake/qt-utils.cmake:130 (message): generate-mumble_qt-qrc.py returned exit code 1	

**Desktop**
 - OS: Windows 10

**Comment by Krzmbrzl** [comment]
If you want help, please take the time to write a proper report that actually contains some information that can be acted on (e.g. how did you invoke cmske, which version are you trying to build, what is the complete output from cmake, ...)
