### ISSUE TITLE
Show number of participants in currently joined channel in tray icon

### ISSUE THREAD

**Issue by ellegance** [mumble-voip/mumble#5261]
**Context**
Showing number of participants in channel in tray icon might be useful in following cases:
1. You see that you are not alone in channel, it makes sense to start speaking (number >1).
2. You constantly talk to for ex. 5 people and expect that they are all present, and you see number 5 in tray without need to open Mumble window.
3. It would be great to show both number of participants and talking status (which is already implemented) at the same time.

**Comment by Krzmbrzl** [comment]
For the time being you might also be interested in the new TalkingUI that found its way into Mumble 1.4.0.
It is described in the [changelog for the first dev snapshot of it](https://www.mumble.info/blog/first-mumble-1.4.0-development-snapshot/#talkingui)

**Comment by Krzmbrzl** [comment]
Closing this as infeasible as
>  you can not really add text to the tray icon. So you would have to use the themed status icon you want to display and - at runtime - add some numbers to it, which seems... cumbersome

to which I have to agree

Source: https://github.com/mumble-voip/mumble/pull/6466#issuecomment-2169204310
