### ISSUE TITLE
Language files does not contain update related strings

### ISSUE THREAD

**Issue by ViBE-HU** [mumble-voip/mumble#5263]
**Describe the bug**
May I reported this already around the transition from Transifex or just wanted to but there are a few strings which are still not available in the language files.

**Steps to Reproduce**
1. Start the latest snapshot for example
2. Check the console (cause Mumble thinks RC1 is not the latest)

**Expected behavior**
Mumble warns you that there is a newer version. But the related strings cannot be translatable because they are not present in the language files. As far as I remember back in the days the related strings has translations too.

**Screenshots**
https://i.imgur.com/18rHa6c.jpg

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19043
 - Version: 1.4.0~2021-09-04~g37ee677~snapshot

**Additional context**
I know it's not a big deal but it's still annoying.

**Comment by davidebeatrici** [comment]
Thanks for reporting the issue!

Our updater was not aware of the new snapshot, I fixed that.

As for the untranslatable text: the strings are actually downloaded from our server.
