### ISSUE TITLE
ACL change is not applied when there are users in the channel already

### ISSUE THREAD

**Issue by cjunekim** [mumble-voip/mumble#5264]
**Describe the bug**

ACL change is not applied when there are users in the channel already

**Steps to Reproduce**

1. Get into a channel with Speak allow permission for all
2. Change the ACL of that channel so that no one can't Speak and OK
3. See you can still Speak

However, if you go out of that channel and enter it again, the new ACL is applied now. You can't speak.

**Expected behavior**

As soon as the ACL of the channel is changed and submitted, it should be applied.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.4.0(2021-04-03), Murmur 1.4.0(2021-04-03)

**Comment by Krzmbrzl** [comment]
> See you can still Speak

Did you verify that someone in that channel can actually hear you? Or are you only referring to the avatar turning blue when you are speaking?

**Comment by cjunekim** [comment]
Yes I actaully confirmed with multiple people. Not only that I did a controlled experiment. For example,

I opened two clients to connect to the local murmur server. On one client's audio input, a sound file is played. I monitored the other client's audio output.

It was reproducible.

**Comment by Krzmbrzl** [comment]
Okay interesting - then this seems like a bug :thinking:

**Comment by Krzmbrzl** [comment]
Alright, checking the source code it seems that the server never actually bothered checking whether someone has `Speak` ACL in the channel they are currently in. The limitation that clients can't speak in such channels is entirely client-side :sweat_smile: 

And in the scenario you are describing apparently the client doesn't realize (or is not informed) that it no longer has this ACL and thus it continues to allow you to talk. If however you rejoin the channel, the permission set is updated and the client now forbids you to speak.
