### ISSUE TITLE
Deprecation warning when built against OpenSSL 3.0

### ISSUE THREAD

**Issue by jtmaston** [mumble-voip/mumble#5277]
**Describe the bug**
Cannot build under macos.

**Steps to Reproduce**
Follow steps as described.
cmake ..
Deprecation errors appear: "error: 'EVP_PKEY_assign' is deprecated [-Werror,-Wdeprecated-declarations]"

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Latest mumble sources

**Comment by Krzmbrzl** [comment]
Could you please post the full console output?

**Comment by jtmaston** [comment]
Here is the error part:
```
[ 26%] Building CXX object src/CMakeFiles/shared.dir/SSLCipherInfo.cpp.o
/Users/aanas/Desktop/mumble 2/src/SelfSignedCertificate.cpp:63:8: error: 'RSA_new' is deprecated [-Werror,-Wdeprecated-declarations]
        rsa = RSA_new();
              ^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/rsa.h:201:1: note: 'RSA_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 RSA *RSA_new(void);
^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/Users/aanas/Desktop/mumble 2/src/SelfSignedCertificate.cpp:79:6: error: 'RSA_generate_key_ex' is deprecated [-Werror,-Wdeprecated-declarations]
        if (RSA_generate_key_ex(rsa, 2048, e, nullptr) == 0) {
            ^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/rsa.h:260:1: note: 'RSA_generate_key_ex' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int RSA_generate_key_ex(RSA *rsa, int bits, BIGNUM *e,
^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/Users/aanas/Desktop/mumble 2/src/SelfSignedCertificate.cpp:84:6: error: 'EVP_PKEY_assign' is deprecated [-Werror,-Wdeprecated-declarations]
        if (EVP_PKEY_assign_RSA(pkey, rsa) == 0) {
            ^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/evp.h:496:41: note: expanded from macro 'EVP_PKEY_assign_RSA'
#  define EVP_PKEY_assign_RSA(pkey,rsa) EVP_PKEY_assign((pkey),EVP_PKEY_RSA,\
                                        ^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/evp.h:1327:1: note: 'EVP_PKEY_assign' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0
^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/Cellar/openssl@3/3.0.0/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
[ 26%] Building C object src/mumble/opus/CMakeFiles/opus.dir/silk/LP_variable_cutoff.c.o
```

( I used -j 10 after cmake --build which is why the log continues even after the errors ).

Of note, however, is I managed to get it to compile by setting the CXX flag -Wno-deprecated

**Comment by Krzmbrzl** [comment]
Ah okay so you did start the actual build after all. Now that makes a lot more sense :sweat_smile:

I see that you are using OpenSSL 3. This is not yet supported (afaik it is in general not (fully) backwards compatible).

For later reference: https://www.openssl.org/docs/man3.0/man7/migration_guide.html
I assume that the error encountered here falls under "deprecated low-level API".

**Comment by jtmaston** [comment]
Right, sorry for the wrong title :))).

**Comment by Krzmbrzl** [comment]
No worries :)

**Comment by chir4gm** [comment]
Does the code need to be migrated to OpenSSL 3 or should there be a way to choose OpenSSL1.1?

**Comment by mtasaka** [comment]
Note that even if deprecation is off explicitly, some mumble code apparently needs fixing anyway. For example:

https://github.com/mumble-voip/mumble/blob/0ee6508ba6569dc73d11eb38dcec4d8b4a69502b/src/SelfSignedCertificate.cpp#L45

https://www.openssl.org/docs/manmaster/man3/CRYPTO_mem_ctrl.html says 
> CRYPTO_mem_ctrl() are deprecated and return -1.

so `SelfSignedCertificate::generate` will always returns false.

**Comment by MariuszXC** [comment]
Just reporting for information, when trying to build mumble client on Ubuntu 22.04.1 LTS I ran into this issue. 

Steps taken:
git clone https://github.com/mumble-voip/mumble.git
git checkout v1.4.287
git submodule update --init --recursive
mkdir build 
cd build 
cmake -Dclient=ON -Dplugins=ON -Dserver=OFF -Dtranslations=OFF -Doverlay-xcompile=OFF -Dwarnings-as-errors=OFF ..
make -j4

This produced the SSL deprecation errors as mentioned in the first message. However, when I checked out the master branch:

git checkout master
git submodule update --init --recursive
(and rest of steps as above)

build succeeded without errors.

My master points to commit ea24da44e52c602e7f8d501f89ff569f13f9f0e8

This makes me think, that either I made a mistake somewhere, or the code migration to SSL 3.0 did not make it to 1.4.287 tagged branch?

**Comment by Krzmbrzl** [comment]
> This makes me think, that either I made a mistake somewhere, or the code migration to SSL 3.0 did not make it to 1.4.287 tagged branch?

This is indeed true. We encountered some serious crashed after the migration to the new API, which is why we decided that these changes won't be backported to the stable 1.4.x version

**Comment by MariuszXC** [comment]
Thank you for clearing things up.

FYI, the Mumble client built from 'master' _seems_ to be working fine on my end. It even picked up new version of fgcom-mymble plugin and updated on its own. So far so good :)

BR, Mariusz

**Comment by Krzmbrzl** [comment]
That's good to hear :+1: 
So far we are not aware of major difficulties with the master branch version. In fact it is planned to release 1.5 from master essentially as soon as time allows :)
