### ISSUE TITLE
Static server build and development dockerfiles

### ISSUE THREAD

**Issue by EPNW** [mumble-voip/mumble#5279]
It seems that the project repo already contains a dockerfile for building and running a dynamicly build server. I highly appriciate that in this file, a builder container approach is used, where in the first container all building depencencies are installed and the build itself happens, and in the running container only a minimal environment is present.

It would be nice to have two more dockerfiles though:
1. One for a staticly build server. Ideally, this file also uses the same builder container approach as the dynamicly build server.
2. A development container

While point 1 should be clear I wan't to talk about point 2 a bit more. The first difficulty when starting to develop is in my opinion setting up a suitable environment. Due to the build characteristics (only static builds for windows) I belive that developing the mumble server on a windows machine is hard and would be interested in knowing if someone actually does that? While picking up my work on my last mumble PR again, I started noticing that my old environment was no longer suitable, so this time I opted for a containered one for developing.

I'll be sharing my insights on developing in a container using vscode below, and if there is interest in it, maybe we could (after some discussion) integrate it in the wiki.

As for a static build and run container it would be nice if someone who is more experienced with the mumble server and the build process could contribute a dockerfile.

# Remote development using a container and VSCode

Sometimes it can be a hurdle to set up a development environment. This is especially true if there is a need for external dependencies which need to be installed: They are sometimes incompatible with already installed things, or are only used to develop for that one project, and the rest of the time just fill up and slow down your system. Even if everything is installed and setup correctly, things can go wrong at unexpected places, and due to different and individual system prequesitions, error identifying can be hard. And don't get me started on different operating systems... For all this problems, developing in a isolated container, containing all the dependencies and a reproducable setup, is a suitable and easy solution. This guide will show you, how to develop the mumble server using a docker container and visual studio code (VSCode).

Note that this guide will be using the remote ssh and not the remote container VSCode extension, since the remote ssh extension is more agnostic and even runs easily over the network.

Also a quick note on nameing: This guide referes to the machine the container is executed on as `host`, and machines the IDE (in our case VSCode) runs on as `development machines`.

## The dockerfile

First, we need a dockerfile to build a container image. The following one can be pasted and contains all dependencies and prequesitions needed for development. You have to adjust the git identity, these lines are marked with `ACTION REQUIRED`. Also, you have to place an `authorized_keys` file next to the dockerfile, containing all the public ssh keys of the machines you want to connect the container from. If you are using a windows machine for development, you can find your public ssh key usually at `C:/Users/%USERNAME%/.ssh/id_rsa.pub`, on linux it should be at `~/.ssh/id_rsa.pub`. The following is an example for a `authorized_keys` file with two allowed development machines:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGhOgWsSnFnMNetKfNlF1J2vSr/oC1kUw3DaBVJLbHz0eOX/NTULCFmq/JZc0YkdTCSgtczqVZWVDKKhiiETXmrbDr51GTE0DfrHw13lljGVPOc2RYISVmIMHFkA9TBXfYDJWwMHv19AYZwMF/dYBIfk9zb/tASsC6WlxlYep/VQA7LdmyzillCLvlPHYHZF95z7jkvxIu34bCHVNkdW2UdsWKClMKO13u40/X3HDEZ6hAFI/5k5QuV7k/ATPSToxSNLX5kYRc4B3Hq+NqRmLdxirsA49/+1urHo1oHOP9m8uPX4weSqux1nQ8yQmayXk9/i/KSb9jLYFAToglLkdQ1FCALLj8hh5VnTYZZLcqkBBvJaJmpXMQT9q/SEEDq7IknaJ+qDEAdjDmLhyi6klFfjQQq8eHjYSmdh92wJqQLNSM/j4UWGTd0xVXArkfPFfAn/YqwzfybnI/isr9YqNfxmPYzSMKra6pmPCnaE4LyrA8qcmD8JRIVuzh9LUN3nk= ep@development_machine1
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDeXBKu3xNron850lmAGGNIbSpIDLXh9uGnWxakM+E+ec5wC0OGom7JVgPL+hypv23N+LWes2Nk7ypgqfSyEPufDDpaHcemGX5yGaCCLpSSfhiQzuJZsFtRatBhlO+hH+yBcDvteLpP2Yo5RraX0ktSkCH4qJeg9NKlw2i9pFLkFYpR5rg3YmmTfq5f+4RJ4L+a1o4s1T8ZGeDM62jAkxFeVWC7v1tBui8FGie9s/26U17Ww/iYzTYeYnH9vYZHRpfReht9yd7Alr6UA99P4oThsYi53HyvH4HiyJkxHilJFwbgRHvveEWmSjt/TE0bCgHGO1Iv+hiceEeFelnCQ0jFMWAQAHTvmyfdOdndXTYOt6VG3tkDnNczNy5pAOdMl48Uhzdz49ditTZSieBSosucSLzG1YsushTSu38h9PwdDQCCoNpM0Wl5cokk8WPoX5qc5XvRlilcth7CJLcRUxy+O4dVu0t7t8QKMBiYPzuEoeOGv/Pa9D+l5rZalJbwNLWkklLI3xk5oJMD10Fd+IYubJmnbzoeAsmPOaMC0FS0X/5HH0qMYggN7k4Z24XNEpm0oJBPowjOfw29uySOD0S6X80IQwGFWpCtHZ28ioTLYHMN3lKxtRVEHCupEDANUOgOe7IuN3d14f32bu+0/qIthbyQUqbH2Q8DRn7bq7J+Xw== nw@development_machine2
```

The password of the `developer` user defaults to `devops`, and can also be edited below.
Finally, here is the dockerfile:

```dockerfile
FROM ubuntu:focal

# Needed to install tzdata
ARG DEBIAN_FRONTEND=noninteractive

# Installs all the building dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
	ca-certificates \
	git \
	build-essential \
	cmake \
	pkg-config \
	qt5-default \
	libboost-dev \
	libasound2-dev \
	libssl-dev \
	libspeechd-dev \
	libzeroc-ice-dev \
	libpulse-dev \
	libcap-dev \
	libprotobuf-dev \
	protobuf-compiler \
	protobuf-compiler-grpc \
	libprotoc-dev \
	libogg-dev \
	libavahi-compat-libdnssd-dev \
	libsndfile1-dev \
	libgrpc++-dev \
	libxi-dev \
	libbz2-dev \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
	
# For later debugging, also the run dependencies are installed
RUN apt-get update && apt-get install --no-install-recommends -y \
	libcap2 \
	libzeroc-ice3.7 \
	'^libprotobuf[0-9]+$' \
	'^libgrpc[0-9]+$' \
	libgrpc++1 \
	libavahi-compat-libdnssd1 \
	libqt5core5a \
	libqt5network5 \
	libqt5sql5 \
	libqt5sql5-mysql \
	libqt5sql5-psql \
	libqt5sql5-sqlite \
	libqt5xml5 \
	libqt5dbus5 \
	ca-certificates \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

# Finally, the development dependencies are installed
RUN apt-get update && apt-get install --no-install-recommends -y \
	sudo \
	openssh-server \
	wget \
	nano \
	gdb \
	clang-format \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

RUN service ssh start
RUN echo "ALL ALL = (root) NOPASSWD: /usr/sbin/sshd" >> /etc/sudoers

# Set up a user for development
RUN useradd -p $(openssl passwd -1 devops) developer
RUN usermod -aG sudo developer
WORKDIR /home/developer

COPY authorized_keys ./.ssh/
RUN chown -R developer:developer /home/developer
USER developer

# ACTION REQUIRED: Adjust with your git user details, only needed if you want to do commits
RUN git config --global user.name "Mumble Developer" \
	&& git config --global user.email developer@mumble.info

EXPOSE 64738/tcp 64738/udp 50051 22
CMD ["sudo","/usr/sbin/sshd","-D"]
```

## Including the source code

Next, it is important to think about how you want to include the mumble source code into the container. Here are three posibilities:
1. Clone the git repo right into the container/image. You can do this either if the container is running, or add a `RUN` instruction to the above dockerfile. The problem with integrating the source into the container/image is that changes will be lost as soon as the container is removed, so you'd have to make sure to that this doesn't accidentally happen.
2. Using a bind mount. This will map a directory form the host machine into the container. The adventage of this is that your source code is stored directly and persistently on your hard drive. However, if your host is a windows machine, this approach is discouraged since building may fail. For linux hosts, this approach is fine.
3. Using a persistent docker volume. Here, a volume is created that is independent from the container, so if the container is removed, the volume still persists. A volume can be explicitly created like this: `docker volume create mumble_source`

For linux hosts, using a bind mound or a persistent docker volume are equally fine, for windows hosts the persistent docker volume approach is recommended. This guide also follows the later.

## Running the container

When running the container, some extra options are needed. First, we need to expose some ports. The mumble server will run at `64738`, so this port needs be exposed if you later want to test what you've developed. If you also want to interact with the grpc interface, port `50051` should be exposed. Finally, the ssh deamons port, defaulting to `22` needs to be publicly available. Since this port should already be in use on most hosts, it could be mapped to port `2222` for example.
Next, to use the above created volume and mount it to the appropriate folder `-v mumble_source:/home/developer/mumble` is added to the run command.
Lastly, for debugging with gdb we need some extra options: ` --cap-add=SYS_PTRACE --security-opt seccomp=unconfined`.
Assuming the image was tagged `mumble_developer` while building, this all results in the following run command:
`docker run -d -p 2222:22 -p 64738:64738 -p 50051:50051 --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v "mumble_source:/home/developer/mumble" mumble_developer`

## Preparing VSCode

After the container runs, it is time to prepare VSCode.
First, install the ssh remote development extension (ms-vscode-remote.remote-ssh) in VSCode on your development machine.
Next, add an appropriate configuration for connecting the container. When adding such a configuration (by clicking on the `remote explorer` and then `Add Target`), VSCode will usually prompt you for a ssh command which should look like this: `ssh developer@your_host_address -p 2222 -i path_to_your_private_key`
After creating the configuration, connect it.
Following a successfull connection, the c++ extension (ms-vscode.cpptools) should be installed in the container (not locally on the development machine!).

## Perparing the source code

While you are now connected to the container, VSCode's terminal can be used to prepare the mumble source code. 
First, use it to go into the home directory of the `developer` user. Since this guide follows the persistent docker volume approach, there should already be an empty mumble directory. You need to execute `sudo chown developer:developer -R mumble` to claim it (if you haven't changed it, the password is `devops`). Next, `cd` into the mumble directory and clone the source code using `git clone https://github.com/mumble-voip/mumble .` (note the dot at the end of the command). Then initialize the needed submodules using `git submodule update --init --recursive`.
Now the standard mumble build commands can be executed to create a test build to verify that all build dependencies are there.
Inside the mumble directory run `mkdir build && cd build`. Then use cmake to create the nesseccary make files using `cmake -Dclient=OFF -DCMAKE_BUILD_TYPE=Debug -Dgrpc=ON ..`. Lastly use `make` to start the build.

# Finishing VSCode configuration

With everything in place it is time to open the mumble folder in VSCode. Once open, open the `src/murmur/About.cpp` file and you'll notice some include errors. We need to tell VSCode where the qt5 headers are located. Click on the underlined `#include <QtWidgets/QApplication>` directive and then on the lightblub. Select the option to edit the include path there. A new tab will open, scoll until you see the include path settings and change
```
${workspaceFolder}/**
```
to
```
${workspaceFolder}/**
/usr/include/x86_64-linux-gnu/qt5/**
```
The include errors should now be gone.
As last step in this guide, a debugging configuration will be added, so you can use breakpoints from within VSCode.
Open the run and debug tab in VSCode, and then choose the option to create a `launch.json`. In the popup, select `C++ (GDB/LLDB)` and finally alter the `program`, `args` and `cwd` options to this values:
```json
"program": "${workspaceFolder}/build/mumble-server",
"args": ["-fg"],
"cwd": "${workspaceFolder}/build"
```

**Comment by Krzmbrzl** [comment]
@EPNW I think instead of writing these instructions here as an issue, i would be more fit as a separate documentation file somwhere in `docs/dev` or `docs/dev/build-instructions`.
Could you create a PR to add it there?

Furthermore, I am not opposed to adding more dockerfiles. But if we do, we should probably create a new subdirectory `docker` at the repo's root and move all related files into there.
