### ISSUE TITLE
Minimize / Close: [X] Remember this choice

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#5282]
When closing the mumble window, an option to remember our choice for the future would be nice (or we can put it in prefs -- or is it already in prefs?)
![Screenshot_20211012_104846](https://user-images.githubusercontent.com/20318973/137004721-eb24c4bb-89be-4271-884f-01adda78cbcc.png)

**Comment by Krzmbrzl** [comment]
@Umang375 absolutely! If you need anything or have any questions about the code, feel free to ask me. I'll see if I can answer ^^

**Comment by Umang375** [comment]
what are the tools and frameworks that i should install ?

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions

**Comment by Umang375** [comment]
> https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions

is there a slack channel or something like that, for communication

**Comment by Krzmbrzl** [comment]
We are using Matrix for that purpose. Our development  channel is available at https://matrix.to/#/#mumble-dev:matrix.org

The general Mumble channel is linked in the main README of this repo

**Comment by juanrodl** [comment]
I want to work on this issue if possible, @Krzmbrzl do you have any tips as to where I can start?

**Comment by Krzmbrzl** [comment]
in theory @Umang375 wanted to work on this already. Not sure what the status of that is though :eyes:

**Comment by Stefan-comkmits** [comment]
Why is so hart to at a Option for this?

Steam,Discord,Thunderbird,
all this have a Option for Minimize(certainly at Thunderbird the option breaks the Maximized option),
but in a Voice Tool like Mumble or Discord,its a reale Usefull Feature to minimze in try by Using X.

**Comment by Krzmbrzl** [comment]
It's not hard. Bur someone has to do it 🤷

**Comment by Krzmbrzl** [comment]
@Merkaber yeah afaik there has not been progress on this front, so you are free to give this a shot.

The currently used dialog does not use a Qt UI file (yet), but is instead a standard Qt MessageBox:
https://github.com/mumble-voip/mumble/blob/db8b6a3310d8891e49b1158204e62417a6fff03d/src/mumble/MainWindow.cpp#L509-L527

I'm not sure if there is an easy way to add a checkbox to this dialog and wire that up with the functionality that we need. If not, I think we could also simply recreate that dialog in Qt Designer as a dedicated `.ui` file (and then also write the corresponding `.cpp` and `.h` files). Long-term that will probably be the most customizable solution.

**Comment by Merkaber** [comment]
Since Qt 5.2 it seems to be really easy to add a checkbox as mentioned [here](https://stackoverflow.com/questions/35130673/qmessagebox-with-a-do-not-show-this-again-checkbox). Or is there a need to customize such dialogs further in the future and therefore a new UI element should be added as you pointed out?

PS: I joined the matrix room for a question related to the git workflow.

**Comment by Krzmbrzl** [comment]
> Since Qt 5.2 it seems to be really easy to add a checkbox as mentioned [here](https://stackoverflow.com/questions/35130673/qmessagebox-with-a-do-not-show-this-again-checkbox). Or is there a need to customize such dialogs further in the future and therefore a new UI element should be added as you pointed out?

Ah, nice. In that case just go ahead and make use of that. Should we ever require more customizations, we can still create a dedicated dialog UI for it :+1:
