### ISSUE TITLE
"The program can't start because qwave.dll is missing from your computer.  ... " - False System Error message - Mumble Server won't run on my Server

### ISSUE THREAD

**Issue by life777eternal** [mumble-voip/mumble#5284]
**Describe the bug**
"The program can't start because qwave.dll is missing from your computer. Try reinstalling the program to fix this problem."

![2021-10-14 19_44 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/137419328-4d838e60-b345-472d-a2c5-9ffcbe4e4c5e.png)

**Steps to Reproduce**
1. Installed Mumble Server 
2. Tried to run it
3. See error screenshot above.

**Expected behavior**
Some kind of running program.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows Web Server 2008 R2
 - Version: mumble_server-1.4.0_2021-09-04_g37ee67716_snapshot.x64.msi

**Additional context**
Uninstalled it with Geek Uninstaller, and installed it again... with same result.

**Comment by Krzmbrzl** [comment]
It seems there is entry in our FAQ about this: https://wiki.mumble.info/wiki/FAQ/English#I_get_the_error_.22Meta:_Failed_to_load_qWave.dll.2C_no_QoS_available.22_in_the_Murmur_log_when_I_start_Murmur

And here is some general info what qWave seems to be: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831592(v=ws.11)

It seems to me that this is a system DLL that should always be present. Have you tried letting Windows repair your installation? :thinking:

That being said I am wondering why we require this thing in the first place (for the server) :eyes:

/CC @davidebeatrici

**Comment by life777eternal** [comment]
Actually, my server does have qwave, as I found from the folder locations that Vinhold Starbrook sent me. But that error still appears. And I tried to add a registry entry to point to the location, but that didn't change anything. ... Also copying the qwave.dll to the Mumble Server folder just breaks the program.  

Thank you.

**Comment by Kissaki** [comment]
From the screenshot the qwave.dll is in a wow64 folder, so I suspect it is a 32-bit dll. Given you installed a 64-bit Mumble server it that mismatch may be why it crashes (and why it correctly does not find this one on launch).

**Comment by Kissaki** [comment]
* [Windows Server 2012 R2 qWAVE docs](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831592(v=ws.11))
* (Current Windows Server QoS docs](https://docs.microsoft.com/en-us/windows-server/networking/technologies/qos/qos-policy-top)
* [MS Open Specification qWAVE protocol docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dsmn/473c60be-888d-468e-8a7e-6debc71bddf7)
* [Previous Windows Desktop qWAVE docs](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/qos/about-qwave)
* ["Win32" Desktop networking links QoS to prev ver docs](https://docs.microsoft.com/en-us/windows/win32/networking)
* [Windows Drivers QoS](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/setting-local-ndis-qos-parameters)
* [None in Lifecycle search](https://docs.microsoft.com/en-us/lifecycle/products/?terms=qWave)

Notably, the current Windows Server networking docs do not have a section on qWAVE. I wonder if this feature was dropped? Then it could make sense that it is still on 32-bit, but not on 64-bit, and not going forward.

**Comment by Kissaki** [comment]
Either way, as krzmbrzl said, it should not be a required dependency.

And what the Windows Server state for this is - installable or dropped feature, would be interesting for us to know too, to document it or take action according to it.

**Comment by Krzmbrzl** [comment]
So I was looking into this some more and found out that we in fact link to `qwave` here:
https://github.com/mumble-voip/mumble/blob/e2d5fcc6c8762f9eb015cc577c71affa53759c03/src/CMakeLists.txt#L159
and it is also mentioned here:
https://github.com/mumble-voip/mumble/blob/e2d5fcc6c8762f9eb015cc577c71affa53759c03/src/mumble/CMakeLists.txt#L548

Removing the explicit linking to `qwave.lib` causes a compile error at
https://github.com/mumble-voip/mumble/blob/e2d5fcc6c8762f9eb015cc577c71affa53759c03/src/murmur/Meta.cpp#L634
(unresolved symbol error from the linker)

With everything as-is, there seems to be a dependency to `C:\Windows\system32\qwave.dll` for the server executable. But even when removing the explicit linking to `qwave.lib` (and commenting out all QOS* functions in the source code) this dependency remains.

I don't see how this dependency is coming to be :eyes: 

In any case though it seems that `qwave.dll` is what is called an "import library" and thus by linking to it, we are effectively linking to `qwave.dll` and as such its presence is indeed required. Therefore, I'll convert this issue back into a support issue.

**Comment by Krzmbrzl** [comment]
@life777eternal you siad that you found qwave.dll in some weird location on your machine. I assume that that location is not in the standard library search path (see https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order) and is therefore not found. It is probably interesting why it isn't in one of the standard locations but maybe moving/copying it to such a location is enough to fix the issue?

In my Windows VM (Win10 client), qwave.dll is under `C:\Windows\system32`.

**Comment by life777eternal** [comment]
@Krzmbrzl Last month, Vinhold Starbrook sent me a zip file with some info about the qwave files on his Windows Web Server 2008 R2, noted the file folder locations to look for, and I found them all and I have all the same dll files on my server. Plus he noted in a text file to add a registry "url' entry which I did, and the system error still appears for Mumble Server. 

![2021-11-21 12_22_55-142 44 178 114 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/142776060-d7dde55f-a31e-4c8d-a53f-dd77c9d20342.png)

![2021-11-21 12_18_21-142 44 178 114 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/142776072-a0e49d2a-0197-463a-b9f5-a8ca060ece47.png)

![2021-11-21 12_07_23-142 44 178 114 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/142776085-f582f1e3-f6ea-4c92-9a6d-7fc1b3361e09.png)


[qWaveFiles.zip](https://github.com/mumble-voip/mumble/files/7576921/qWaveFiles.zip)

**Comment by Krzmbrzl** [comment]
Who's Vinhold Starbrook?

I have no clue about windows servers but from the error I am quite sure that the DLL is not in the path that is searched. Either that or the DLL is for some reason not loadable on your system.

**Comment by life777eternal** [comment]
He is one of the developers for Halcyon World which is the online 3D world that we're hoping Mumble can be made workable on. As an alternative to the [Vivox Voice](https://vivox.com/) service. 

https://github.com/HalcyonGrid/halcyon

**Comment by Krzmbrzl** [comment]
Ah okay, I see.

Might be relevant: https://social.msdn.microsoft.com/forums/en-US/85f2ba18-93b8-4720-ab8a-fca473755bbd/using-qwave-on-windows-server-2008-but-cannot-find-dll

**Comment by life777eternal** [comment]
Ok, Thank you @Krzmbrzl I have actually seen that first link before, and the other link on that page is a microsoft site that was discontinued a while ago, so I found it on Archive.org [here](https://web.archive.org/web/20100430190304/http://blogs.techrepublic.com.com/datacenter/?p=294). ... And the imgur.com tutorial is helpful although the available features on my server is missing two of the Features that are shown in the third screenshot with the '6' & '7' ... "Peer Name Resolution Protocol" & "Quality Windows Audio Video Experience" are missing on my server. 

![2021-11-21 13_35_00-142 44 178 114 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/142778138-0518e5e9-00fe-4446-9451-8a8b4ecddfc0.png)

**Comment by Krzmbrzl** [comment]
Then I don't know what is the issue. Do you knownof anyone who is running Mumble successfully on their Windows server 2008? Maybe this is just too old by now 👀

**Comment by life777eternal** [comment]
Ok, no I don't know anyone else who is running Mumble successfully on Windows Web Server 2008 R2. Vinhold hasn't been able to get to trying out Mumble server yet.

**Comment by davidebeatrici** [comment]
`Quality Windows Audio Video Experience` is the feature you should install.

For reference: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/qos/quality-windows-audio-video-experience--qwave-

**Comment by life777eternal** [comment]
> `Quality Windows Audio Video Experience` is the feature you should install.

Aye, I've noticed that that's the one I probably have to install. Though it's not in the list 📃 on my server. 

> I see it's missing in your screenshot, I honestly don't know why.

Aye it is missing, that's what I was trying to show... I don't know why either. Might have to call 📞 Microsoft I imagine.

**Comment by Krzmbrzl** [comment]
If you do call them, please share what they told you. Maybe this information turns out to be useful for someone else in the future.

**Comment by k1ttt-remote** [comment]
just trying mumble server 1.4.230 x64 on win server 2012r2 essentials and get the same error about not having cwave.dll.  anything new on this???

**Comment by Krzmbrzl** [comment]
@k1ttt-remote is this just a double-posting of the support request you created or is this a separate issue that actually says it is missing **c**wave.dll?

**Comment by k1ttt-remote** [comment]
well, i posted here but then thought that maybe this one wouldn't be seen because the case was closed so started a new issue.... so this one could be ignored.

**Comment by Krzmbrzl** [comment]
Alright :+1:

**Comment by MichaelAgarkov** [comment]
Works on Windows Server 2012 R2 for me after enabling "Quality Windows Audio Video Experience".

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/174858d9-ea5f-44b8-ba03-416582107b6d" />
