### ISSUE TITLE
Build fails (c032df803 and others)

### ISSUE THREAD

**Issue by savchenko** [mumble-voip/mumble#5301]
**Describe the bug**
Build fails with:
```sh
$ cmake --build .
src/CMakeFiles/shared_autogen.dir/build.make:81: *** target pattern contains no '%'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:1396: src/CMakeFiles/shared_autogen.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
```

**Steps to Reproduce**
1. Checkout c032df803
2. `cd` into `./build`
3. `cmake -DRELEASE_ID=$(python "../scripts/mumble-version.py") -Dserver=OFF -Doverlay-xcompile=OFF ..`

**Expected behavior**
Mumble-client compiles.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian v11 `stable` aka Bullseye
 - Version: trunk/master/HEAD - c032df803

**Additional context**
Was trying to look into https://github.com/mumble-voip/mumble/issues/5300

**Comment by ZeroAbility** [comment]
`overlay-xcompile` is a helper option for `overlay` that turns on when the system is 64 bit so it can build a 32 bit version of the overlay for 32 bit apps. Do you want to disable the overlay or just the 32 bit version?

**Comment by savchenko** [comment]
> Do you want to disable the overlay or just the 32 bit version?

I want to build only the 64 bit client and see if there are any clues that might help with https://github.com/mumble-voip/mumble/issues/5300.

**Comment by ZeroAbility** [comment]
You can replace `overlay-xcompile=OFF` with `overlay=OFF` if you just need to test it. The latter disables the former.

**Comment by ZeroAbility** [comment]
> I want to build only the 64 bit client and see if there are any clues that might help with #5300.

Also keep in mind, `1.3.x` does not use CMake, `1.4.x` does.

**Comment by savchenko** [comment]
> Also keep in mind, 1.3.x does not use CMake, 1.4.x does.

Same error when building from [1.4.0-release-candidate-01](https://github.com/mumble-voip/mumble/releases/tag/1.4.0-release-candidate-01)

Am I missing something obvious here?..

**Comment by ZeroAbility** [comment]
Try `grpc=OFF` in your CMake config.

**Comment by savchenko** [comment]
Hold on. `protobuf-compiler` was missing, hence the erroneous makefile! With `protoc` in `$PATH` the section looks sane:
```make
src/Mumble.pb.h: /usr/bin/protoc
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/lbr/Code/mumble/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Running cpp protocol buffer compiler on /home/lbr/Code/mumble/src/Mumble.proto"
	cd /home/lbr/Code/mumble/build/src && /usr/bin/protoc --cpp_out /home/lbr/Code/mumble/build/src -I /home/lbr/Code/mumble/src /home/lbr/Code/mumble/src/Mumble.proto
```

There is also a missing check for Boost, but this is fixed by the generous `apt install libboost-all-dev`.

**Comment by savchenko** [comment]
Closing as build succeeds now. Hope the information above will help someone in future.
