### ISSUE TITLE
Disable XInput when running on Wayland

### ISSUE THREAD

**Issue by savchenko** [mumble-voip/mumble#5303]
**Describe the bug**
Mumble shouldn't attempt to setup a "global shortcut" if current session is Wayland.

Ref.:
https://github.com/mumble-voip/mumble/blob/c10d636cef79b07784318671df97dba6c1af2b83/src/mumble/GlobalShortcut_unix.cpp#L127-L128

**Steps to Reproduce**
1. Launch under a pure Wayland WM
2. Observe in the stdout:
    ```
    <W>2021-11-10 15:38:44.209 Updating application palette
    <W>2021-11-10 15:38:44.217 GlobalShortcutX: No XInput support, falling back to polled input. This wastes a lot of CPU resources, so please enable one of the other methods.
    <W>2021-11-10 15:38:44.230 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
    <W>2021-11-10 15:38:44.275 Wayland does not support QWindow::requestActivate()
    ```

**Expected behavior**
Don't _"waste a lot of CPU resources"_.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 11, Sway WM
 - Version: `master` / c032df803

**Additional context**
N/A

**Comment by Krzmbrzl** [comment]
@savchenko could you verify that #5307 disables shortcuts on Linux if Wayland is used?

**Comment by savchenko** [comment]
Looks like it:
![image](https://user-images.githubusercontent.com/300146/141210482-1e68992e-dc57-48a7-9d33-e07bcf134bea.png)

With the changes merged onto `master` CPU usage when not talking stays between 0-0.5%.
