### ISSUE TITLE
do not apply text-to-speech for commands

### ISSUE THREAD

**Issue by rhetr** [mumble-voip/mumble#5313]
a number of mumble bots i've come across use exclamation mark prefixes (e.g. !play, !pause, !next). it would be nice if mumble had the option to turn off TTS for !-prefixed messages.

**Comment by Krzmbrzl** [comment]
It seems like you shouldn't have TTS read back your own messages to you, if you are not visually impaired in the first place. Does it do that? And isn't there a setting for that already?
And in case a user is visually impaired, I don't see why `!`-prefixed messages should be an exception :thinking:
