### ISSUE TITLE
Disable positional audio from Mumble Link

### ISSUE THREAD

**Issue by Epicalert** [mumble-voip/mumble#5321]
**Context**
When playing games that support positional audio through the Link plugin.

**Describe the feature you have in mind**
Games that directly interface with the link plugin could set a flag or add a string like ".dead" to the end of the context. This would be useful when you don't want to hear positional audio from dead players or other situations where a player temporarily does not exist in 3D space.

**Describe alternatives you've considered**
The context could be set to a UUID generated upon death.

**Additional context**
None

**Comment by Krzmbrzl** [comment]
Cushing the context will cause positional audio to mot be effective anymore but then everyone in the channel will hear these users regardless of where they are.

I think what you would probably want to do in these cases is set these player's position to an insanely far away point (e.g. max out the 32bit integer range for all three coordinates).

However, this is nothing Mumble can do. This is up for the games to implement themselves as Mumble only offers the interface. 
Or did I misunderstand your request?

**Comment by Epicalert** [comment]
Ah I see, could both of these workarounds be added to the [developer documentation?](https://www.mumble.info/documentation/developer/positional-audio/link-plugin/) There's no clear method in the documentation to handle player death.

In some games with smaller maps the first case is fine but the second case would also be desirable in some situations. I was thinking there could be a flag somewhere to directly toggle the positional audio and/or proximity attenuation via the Link plugin. e.g. `usePositional = false` would cause everyone to not hear the direction of the player and `useDistance = false` would cause everyone to hear the user at the same volume regardless of position?

**Comment by Krzmbrzl** [comment]
I think maxing out the coordinate values should work on large maps as well. Rmember thst these are 32bit numbers, so we can set them to 2^32 - 1 = 4,294,967,295 (and they are understood to be in meters).
Except some insanely huge space simulation, I can't think of any game reaching close to these coordinate values during normal gaming.

What you are describing is essentially disabling positional audio. This could be achieved by unlinking the plugin temporarily. However, I don't really see why you would want to disable positional audio during a game session :thinking:
