### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by aerilox** [mumble-voip/mumble#5322]
**Describe the bug**
\src\mumble\GlobalShortcut_win.cpp(233): error C2065: 'InputGkey': undeclared identifier
\src\mumble\GlobalShortcut_win.cpp(233): error C2672: 'qMetaTypeId': no matching overloaded function found
src\mumble\GlobalShortcut_win.cpp(233): error C2974: 'qMetaTypeId': invalid template argument for 'T', type expected
vcpkg\installed\x64-windows-static-md\include\qt5\QtCore/qmetatype.h(1929): note: see declaration of 'qMetaTypeId'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"' : return code '0x2'

**Steps to Reproduce**
cmake --build .

**Desktop (please complete the following information):**
 - OS: win 10
 - Version: latest and also from archive 48 commits before

.

**Comment by Krzmbrzl** [comment]
Did you install all required dependencies? And on that note: did you follow the build instructions from https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_static.md?

**Comment by aerilox** [comment]
Yes, including vcpkg installation on a clean machine,and zero-ice patch, everything was done by the word and there were no major hickups. The build string is:
cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=c:\.....\vcpkg/scripts/buildsystems/vcpkg.cmake" "-DIce_HOME=c:\...\vcpkg/installed/x64-windows-static-md" "-DCMAKE_BUILD_TYPE=Release" ..
I tried to deselect gkey and someother options, but without success.

**Comment by Krzmbrzl** [comment]
Now wait a sec. I just checked and `InputGKey` is a struct defined in our code right here:
https://github.com/mumble-voip/mumble/blob/64f8880789007cb45caa5ecca710ac410b74c853/src/mumble/GlobalShortcut_win.cpp#L138

It is guarded by the `USE_GKEY` macro whereas the error you showed is at s location that doesn't seem to be protected by the same guard.

Could you try whether explicitly enabling gkey fixes the issue? And if that fails whether manually defining that macro at the beginning of the file removes this particular error?

**Comment by Krzmbrzl** [comment]
It seems at this place there is also an unguarded use of the xinput class:
https://github.com/mumble-voip/mumble/blob/64f8880789007cb45caa5ecca710ac410b74c853/src/mumble/GlobalShortcut_win.cpp#L232-233

**Comment by aerilox** [comment]
option "-Dgkey=ON" does the trick
adding #define USE_GKEY creates a double macro error more downstream
Thank you!

**Comment by Krzmbrzl** [comment]
Alright - with #5323 the compile error should be fixed even when using `-Dgkey=OFF`
