### ISSUE TITLE
Connecting to Murmur using domain?

### ISSUE THREAD

**Issue by GabenCrying** [mumble-voip/mumble#5332]
I got a domain pointing to the same VPS that my murmur server is hosted on. I should just be able to connect to the murmur server with the domain right? The domain is rage.city, so theoretically since  everythings tied to the same VPS, all I'd have to put in the mumble address is rage.city and I should connect. But I have to put the VPS IP address, am I missing something in the murmur.ini? 

Looking inside the **murmur.ini**, I do see the following lines

```

;registerName=
;registerPassword=
;registerUrl=
;registerHostname=
;registerLocation=

```

I did try to fill them out as such

```
registerName=rage.city
registerPassword=
registerUrl=https://rage.city
registerHostname=rage.city
registerLocation=US
```

Did not work. Any ideas?  I am using NFO as the VPS and Cloudflare, so I am wondering if perhaps I am missing something on the cloudflare end. Any suggestions would be dearly appreciated. 

Edit: Do I need to create a service record on cloudflare? Currently the domain DNS has a **CNAME** and a **A** record only. 

********### Solution: Disable cloudflares proxy - Bandaid**

**Comment by ppfeufer** [comment]
This should do the trick

```
; Specific IP or hostname to bind to.
; If this is left blank (default), Murmur will bind to all available addresses.
host=rage.city
```

**Comment by 6b45** [comment]
> This should do the trick
> 
> ```
> ; Specific IP or hostname to bind to.
> ; If this is left blank (default), Murmur will bind to all available addresses.
> host=rage.city
> ```

based gentoo user

**Comment by GabenCrying** [comment]
> This should do the trick
> 
> ```
> ; Specific IP or hostname to bind to.
> ; If this is left blank (default), Murmur will bind to all available addresses.
> host=rage.city
> ```

Thank you for your quick response, upon making that change and restarting murmur, the server is no longer connectable via mumble; with the following Log in /var/log/murmur

```
<W>2021-11-25 19:07:41.617 SSL: OpenSSL version is 'OpenSSL 1.1.1l  24 Aug 2021'
<W>2021-11-25 19:07:41.617 Initializing settings from /etc/murmur/murmur.ini (basepath /etc/murmur)
<W>2021-11-25 19:07:41.704 Binding to address 104.21.94.209
<W>2021-11-25 19:07:41.704 Binding to address 172.67.140.14
<W>2021-11-25 19:07:41.704 Binding to address 2606:4700:3037::6815:5ed1
<W>2021-11-25 19:07:41.704 Binding to address 2606:4700:3031::ac43:8c0e
<W>2021-11-25 19:07:42.161 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:EC
DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SH
A:AES256-SHA:AES128-SHA"
<W>2021-11-25 19:07:42.334 ServerDB: Opened SQLite database /var/lib/murmur/murmur.sqlite
<W>2021-11-25 19:07:42.334 ServerDB: Using SQLite's default rollback journal.
<W>2021-11-25 19:07:42.342 MurmurIce: Endpoint "tcp -h 127.0.0.1 -p 6502 -t 60000" running
<W>2021-11-25 19:07:42.357 Murmur 1.3.3 (1.3.3) running on X11: Gentoo Base System release 2.7: Booting servers
<W>2021-11-25 19:07:42.411 1 => Server: TCP Listen on 104.21.94.209:64738 failed: The address is not available
<W>2021-11-25 19:07:42.415 1 => Server: TCP Listen on 172.67.140.14:64738 failed: The address is not available
<W>2021-11-25 19:07:42.420 1 => Server: TCP Listen on [2606:4700:3037::6815:5ed1]:64738 failed: The address is not available
<W>2021-11-25 19:07:42.422 1 => Server: TCP Listen on [2606:4700:3031::ac43:8c0e]:64738 failed: The address is not available
```

**Comment by Krzmbrzl** [comment]
From your initial post it seems like you solved the issue. Is that correct?
