### ISSUE TITLE
Chat Window detached

### ISSUE THREAD

**Issue by Cammi187** [mumble-voip/mumble#5344]
For some time now i am to stupid to fix the problem i have with the chat window. I don´t know how i detached the window from the main window. i am only able to resize the chat window

allready tried to delete all the user data i found and reinstalled mumble. did not worked
Its not like i can´t use mumble because of it or that i use the chat window at all, its just annoying me. any1 knows which button i have to press to fix it?

![image](https://user-images.githubusercontent.com/95302763/144085499-ebe70127-14d6-43ec-97e2-0db9c2e77460.png)

**Comment by Krzmbrzl** [comment]
Hm - I wasn't aware that this was possible.

However, in order to get rid of this, you could try going to the settings and then `User interface`. Then select a different layout (choose either `Classic` or `Stacked`) and hit `Ok`. This should rearrange the chat window. Afterwards you should be able to switch back to your original layout :thinking:

**Comment by Cammi187** [comment]
sadly thats only changing the main window and does nothing to the chat window

**Comment by Krzmbrzl** [comment]
Does the chat window move when you move the main window?

**Comment by Cammi187** [comment]
no it stays where it it. i can move it when i resizethe chat window in different directions

**Comment by Krzmbrzl** [comment]
what happens if you click on the chat window and then hit Ctrl+F4?

**Comment by Krzmbrzl** [comment]
And what OS are you on? We could also try to remove the settings file to check whether this might be the effect of a bogus setting. See https://wiki.mumble.info/wiki/Client_Settings for where to find the settings (file).

**Comment by Cammi187** [comment]
crtl f4 does nothing. 

running windows. you mean to remove something in the regedit?

ok i deleted the whole mumble folder in the regedit. now all my settings are gone but at least the problem is fixed. thx very much

**Comment by Krzmbrzl** [comment]
Yes that's exactly what I meant.

Great to hear it's fixed now. Would have been interesting to figure out which setting was causing the trouble exactly but in any case: fixed is fixed :D

**Comment by Cammi187** [comment]
i did a backup of the folder before i deleted it. if u want it i can upload it

**Comment by Krzmbrzl** [comment]
Yes that would be great. Then I can check whether I can reproduce the issue. If I can, I can try to find out which setting was causing the issue and maybe there is also a way to prevent that in the future :)

**Comment by Cammi187** [comment]
are there any passwords or stuffed safed in the reg mumble folder or do i have to remove something out of it before i upload it?

**Comment by Cammi187** [comment]
ok i have no idea how i can remove something from that export i created

**Comment by Krzmbrzl** [comment]
Couldn't you re-import them, edit the certificate entry and then export it again?
