### ISSUE TITLE
mumble_autogen doesn't build in 1.4.x

### ISSUE THREAD

**Issue by powerjungle** [mumble-voip/mumble#5346]
### The issue

...branch, but it builds in the master branch, so my uneducated guess is that some commit wasn't backported. 

My guess is, might be this one: https://github.com/mumble-voip/mumble/commit/fea45e3e9288335b02cde27c7f621627cd6c0e59

```
make[2]: *** No rule to make target '../themes/Mumble/layout_stacked.svg', needed by 'src/mumble/mumble_autogen/6RJHKKPRHE/qrc_MumbleTheme.cpp'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1243: src/mumble/CMakeFiles/mumble.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:166: all] Error 2
```

### Mumble version

1.4.x

### Mumble component

Both

### OS

Linux

### Additional information

```
cmake -Doptimize=ON \
        -Doverlay=OFF \
        -Doverlay-xcompile=OFF \
        -Dplugins=OFF \
        -Dqtspeech=ON \
        -Dserver=OFF \
        -Dstatic=OFF \
        -Dtests=ON \
        -Dtranslations=OFF \
        -Dupdate=OFF \
        -Dxboxinput=OFF \
        -Dcrash-report=OFF \
        -DRELEASE_ID=$(python "../scripts/mumble-version.py") \
        -Ddebug-dependency-search=ON \
        -DOPUS_CUSTOM_MODES=ON \
        .. 
```

**Comment by Krzmbrzl** [comment]
Did you run `git submodule update --init`?
That should clone the theme submodule and then the build should succeed 👀

The theme integration into the main repo was only done on master (on purpose) :)

**Comment by powerjungle** [comment]
Oh okay so my bad, didn't realize I need to do that for the other branch as well. Welp, thanks for the quick response, appreciate it!

**Comment by Krzmbrzl** [comment]
Sure, no problem :)

At this point I am really thinking that maybe we should just run that command by default when invoking cmake xD

**Comment by powerjungle** [comment]
Yeah I think it would resolve a lot of frustration, although I don't know if that will introduce problems.
