### ISSUE TITLE
Wrong HTML generation when putting a quote after a link

### ISSUE THREAD

**Issue by 2xsaiko** [mumble-voip/mumble#5347]
### Description

When you type something such as `"https://example.com"` into the chat box (including the quotes), the HTML gets generated wrongly. The output will show as just ", and the generated HTML is `&quot;<a href="https://example.com"">https://example.com&quot;</a>` (expected: `&quot;<a href="https://example.com">https://example.com</a>&quot;`. This also happens with just the last quote, it seems like it wrongly interprets that as part of the link and then doesn't escape it in the href string, which leads to the broken HTML.

### Steps to reproduce

1. Join a server
2. Type `https://example.com"` including the quote into the chat box
3. Resulting message is displayed as empty

### Mumble version

4de7e4be7de8636c1cc8302d9aeeaa1101d14bd8

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
I wouldn't be too surprised if this is related to the markdown "parser" that gets hung up on this somehow 👀

**Comment by 2xsaiko** [comment]
Heh, TIL the input box parses markdown!

**Comment by Krzmbrzl** [comment]
Yes - since 1.4.0 :D
