### ISSUE TITLE
cmake: Tried to create a Mumble package, without specifying BUILD_NUMBER

### ISSUE THREAD

**Issue by 7wells** [mumble-voip/mumble#5380]
### The issue

Hello!

Yesterday, I was able to create a working mumble (client only) with `cmake ..` for Endeavour OS (Arch Linux), but today I got this message (without having changed anything, except that my OS updated cmake):
```
cmake .. -Dalsa=off -Dasio=off -Dbundled-celt=on -Dbundled-opus=on -Dbundled-speex=on -Dclient=on -Dcoreaudio=on -Dcrash-report=off -Ddbus=on -Ddebug-dependency-search=off -Delevation=off -Dg15=off -Dg15-emulator=off -Dgkey=on -Dgrpc=off -Dice=on -Djackaudio=off -Dmanual-plugin=on -Donline-tests=off -Doptimize=on -DOPUS_BUILD_SHARED_LIBRARY=on -DOPUS_STACK_PROTECTOR=off -Doss=on -Doverlay=on -Doverlay-xcompile=on -Dpackaging=on -Dpipewire=off -Dplugin-callback-debug=off -Dplugin-debug=off -Dplugins=on -Dportaudio=off -Dpulseaudio=off -Dqssldiffiehellmanparameters=on -Dqtspeech=on -Dretracted-plugins=off -Drnnoise=on -Dserver=off -Dspeechd=on -Dstatic=off -Dsymbols=off -Dtests=off -Dtranslations=on -Dupdate=on -Dwarnings-as-errors=on -Dwasapi=off -Dxboxinput=on -Dxinput2=on -Dzeroconf=on
CMake Error at CMakeLists.txt:19 (message):
  Tried to create a Mumble package, without specifying BUILD_NUMBER!

-- Configuring incomplete, errors occurred!
```

I did a fresh `git clone https://github.com/mumble-voip/mumble.git` and in the cloned folder a `git submodule update --init --recursive`, following the instructions [there](https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions) and [there](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md).

Thanks for sharing your hints with me! :)

### Mumble version

85a7ce56b6342fe93e5877200751809983dffc01

### Mumble component

Client

### OS

Linux

**Comment by Krzmbrzl** [comment]
When invoking cmake, use `-DBUILD_NUMBER=42` (or any other number).

However, you are on Linux and we don't support packaging from cmake as of now, so you shouldn't be using the packaging oprionthere anyway :thinking:
If you didn't do this intentionally, try using `-Dpackaging=OFF` when invoking cmake

**Comment by Krzmbrzl** [comment]
Note that if you are actually attempting to publish a package of Mumble, you will want to look up the build-number for the commit you are building from, from https://mumble.info/build-number.json
