### ISSUE TITLE
PTT not working in 1.4.0`2021`049`04   However other key bindings work...

### ISSUE THREAD

**Issue by 19dk** [mumble-voip/mumble#5381]
### The issue

PTT does not work despite configure/settings/audio input/transmit... set to 'push-to-talk'   and.........
configure/settings/shortcuts... 'push to talk' short cut created and assigned.

other key binds work when created.  some function in audio wizard. audio cue and indices but no mic capture. ---- audio cue only in the app and no other indication of transmitting

thanks for the attention 

### Mumble version

1.4.0`2021`09`04

### Mumble component

Client

### OS

Windows

**Comment by ZeroAbility** [comment]
Which key(s) are you binding it to?

**Comment by 19dk** [comment]
L

**Comment by 19dk** [comment]
L functions no problem when assigned to another

**Comment by Krzmbrzl** [comment]
Does any other audio transmission mode (continous or voice activation) work for you?
