### ISSUE TITLE
Connection to murmur server 1.3.4 with serverpassword not possible

### ISSUE THREAD

**Issue by karstengit** [mumble-voip/mumble#5382]
### Description

I installed "mumble-server 1.3.4-1" in Debian 11 (bullseye) via package on an internal server.
In the config mumble-server.ini the serverpassword is set.

I can connect with an client 1.3.4 without problems.
On another PC the client asked for the server password and afterwards the login works.

Now a friend tries to login from outside with a client 1.3.0 and the connection is always refused.
There is no pop-up window asking for the server password!

Where this server password is stored for the client?
It cannot be found in any settings in the client?

### Steps to reproduce

1.Enter the needed informations for the server connection for a new server
2. Try to connect
3. Connection always fails

### Mumble version

1.3.0 for the client
1.3.4 for the server

### Mumble component

Client / Server combination

### OS

Linux

### Reproducible?

Yes

### Screenshots

As you can see in the screenshot the connection works with the same client and server configuration, but with an older server version 1.2.18-1~bpo8+1 running on an different server that is in migration.

![image](https://user-images.githubusercontent.com/5941550/147267375-1830afad-030d-4f99-879d-609b3a6021ef.png)

**Comment by Krzmbrzl** [comment]
> I can connect with an client 1.3.4 without problems.
On another PC the client asked for the server password and afterwards the login works.

Does that mean that the 1.3.4 client connected successfully without having asked for the password?

> Where this server password is stored for the client?
It cannot be found in any settings in the client?

You could try using `SuperUser` as the username. Normally that should convince the connect-dialog to show you an additional password field when editing your server's entry in your favorites. Maybe that allows to enter a different password (or clear any password that might be restored in there to (hopefully) prompt Mumble to re-ask you).

And just to make sure that the issue is actually the password set on the server: Could you check if the mentioned client is able to connect to your server if the serverpassword is removed?
(Note that in order to remove the password from the server again, it might be necessary to use Ice, change the server's DB manually or delete the DB - a simple change in the ini might not be enough (the ini usually only provides _defaults_ for server configuration))

**Comment by karstengit** [comment]
Thanks for the quick reply!

> > I can connect with an client 1.3.4 without problems.
> > On another PC the client asked for the server password and afterwards the login works.
> 
> Does that mean that the 1.3.4 client connected successfully without having asked for the password?

Yes - my client did not ask and the connection did work.
But my user is Admin.

The other client that works is on Debian 10 with client V 1.3.0

> You could try using `SuperUser` as the username. Normally that should convince the connect-dialog to show you an additional password field when editing your server's entry in your favorites. Maybe that allows to enter a different password (or clear any password that might be restored in there to (hopefully) prompt Mumble to re-ask you).

This works in my client.
Is ask my friend to try this hack.

> And just to make sure that the issue is actually the password set on the server: Could you check if the mentioned client is able to connect to your server if the serverpassword is removed? (Note that in order to remove the password from the server again, it might be necessary to use Ice, change the server's DB manually or delete the DB - a simple change in the ini might not be enough (the ini usually only provides _defaults_ for server configuration))

In my client there is no password shown in the hidden field.
After altering the user back it still connects.

Can you explain this concept?

**Comment by Krzmbrzl** [comment]
> But my user is Admin.

Admin as in `SuperUser` or as in "has `Write` ACL permission?

> In my client there is no password shown in the hidden field.
After altering the user back it still connects.

So you mean that you changed your username to `SuperUser` but the password field that showed up was empty but when changing your username back again you were still able to connect?

**Comment by karstengit** [comment]
> > But my user is Admin.
> 
> Admin as in `SuperUser` or as in "has `Write` ACL permission?

I must research, because i have simply copied the mumble-server.sqlite from the old system i created 5 years ago ...

My user is not the superuser, it has user_id 1.
My user is member of the group admin.

![grafik](https://user-images.githubusercontent.com/5941550/147337590-d3c23512-ea1b-4a3a-83dc-ad60f20ef287.png)

This superuser has an user password - is this the password that is entered in the setup of the server?

But this cannot be identical with the server password!?

> > In my client there is no password shown in the hidden field.
> > After altering the user back it still connects.
> 
> So you mean that you changed your username to `SuperUser` but the password field that showed up was empty but when changing your username back again you were still able to connect?

Yes. When i alter my username to superuser the password field appears. It is empty.

**Comment by Krzmbrzl** [comment]
> This superuser has an user password - is this the password that is entered in the setup of the server in the client?

Yes

> But this cannot be identical with the server password!?

It probably _can_ be, but I guess that in general it is not. (Note that what you are seeing in the DB is only the password's hash)

Alright, I guess to further proceed, it would probably be best, if you were to remove the password from your server again and then check whether your friend is able to connect to your server.
Also, please ask them to start Mumble from the console and then copy&paste the stuff that gets written to it when he tries to connect to your server, but is refused. Maybe the logs can tell us something interesting :thinking:

**Comment by karstengit** [comment]
Hmmm - all the time there was no problem with the serverpassword, that keeps the server privat.
So where is this serverpassword stored in the client?
Or it is not stored and only transmitted once to the server for allowing the registration process of the key of the user?

Today i am hopefully able to check the output on the console of the client of my friend.
I will report the result.

**Comment by Krzmbrzl** [comment]
I think the client always sends the last used PW for a given server (which would indicate that it is stored in the client's DB) and when the connection fails, the user should be prompted for a (new) password.

**Comment by karstengit** [comment]
Something generally is going wrong in the new version of murmur.

Here is the console output when i connect with my user and client to the new server:

```
$ mumble
Cannot connect to server socket err = Datei oder Verzeichnis nicht gefunden
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<W>2021-12-27 10:28:20.663 JackAudioSystem: unable to open client due to 2 errors:
<W>2021-12-27 10:28:20.663 JackAudioSystem: JackFailure - overall operation failed
<W>2021-12-27 10:28:20.663 JackAudioSystem: JackServerFailed - unable to connect to the JACK server
<D>2021-12-27 10:28:21.698 libopus 1.3.1 from libopus.so.0
<W>2021-12-27 10:28:21.700 CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
<W>2021-12-27 10:28:21.705 Theme: "Mumble"
<W>2021-12-27 10:28:21.705 Style: "Lite"
<W>2021-12-27 10:28:21.705 --> qss: ":themes/Mumble/Lite.qss"
<W>2021-12-27 10:28:21.712 Locale is "de_DE" (System: "de_DE")
<W>2021-12-27 10:28:21.754 Database SQLite: "3.34.1"
<W>2021-12-27 10:28:21.774 Updating application palette
<W>2021-12-27 10:28:21.796 GlobalShortcutX: Using XI2 2.3
<W>2021-12-27 10:28:22.345 AudioInput: Opus encoder set for VOIP
<W>2021-12-27 10:28:22.345 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2021-12-27 10:28:22.346 PulseAudio: Starting input alsa_input.pci-0000_04_06.0.analog-stereo
<W>2021-12-27 10:28:22.346 PulseAudio: Starting output: alsa_output.pci-0000_04_06.0.analog-stereo
<W>2021-12-27 10:28:22.347 AudioOutput: Initialized 1 channel 48000 hz mixer
<W>2021-12-27 10:28:22.352 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-12-27 10:28:31.263 Database SQLite: "3.34.1"
<W>2021-12-27 10:28:31.263 OpenSSL Support: 1 (OpenSSL 1.1.1k  25 Mar 2021)
<W>2021-12-27 10:28:31.372 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2021-12-27 10:28:31.399 ServerHandler: connection attempt to [2001:4dd0:af1b:3a0f:ca0e:14ff:fee6:a090]:64738 failed: Verbindung verweigert (0); trying next server....
```
As you can see the connection failed and then worked with "a next server".

With the older server this message does not appear.

```
<W>2021-12-27 10:32:36.579 QSqlDatabasePrivate::removeDatabase: connection 'ServerHandler' is still in use, all queries will cease to work.
<W>2021-12-27 10:32:36.579 QSqlDatabasePrivate::addDatabase: duplicate connection name 'ServerHandler', old connection removed.
<W>2021-12-27 10:32:36.587 Database SQLite: "3.34.1"
<W>2021-12-27 10:32:36.587 OpenSSL Support: 1 (OpenSSL 1.1.1k  25 Mar 2021)
<W>2021-12-27 10:32:36.624 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
```

With the older client of the friend the message of trying a next server does not appear and the connection keeps failing.

**Comment by Krzmbrzl** [comment]
Are you perhaps running multiple virtual servers within a single process?

**Comment by karstengit** [comment]
> Are you perhaps running multiple virtual servers within a single process? Check by looking in the `servers` table in your server's database

There is only one process running.

mumble-+  142930       1  0 Dez23 ?        00:00:07 /usr/sbin/murmurd -ini /etc/mumble-server.ini

In pstree there are no other dependent processes.
Everything is standard configuration.

**Comment by Krzmbrzl** [comment]
That is why I said multiple _virtual_ servers within a single murmur process. Every murmur-process can create and serve (in theory) infinitely many virtual server instances

**Comment by Krzmbrzl** [comment]
First, check if you even have multiple vServers running :eyes: 

> Why the first connection is always rejected?

Impossible to tell without further info - potentially because they are configured differently

**Comment by karstengit** [comment]
> First, check if you even have multiple vServers running eyes

Where this can be seen?

**Comment by karstengit** [comment]
Locally it makes no difference when the serverpassword is commented out in the configuration file.
So here is definitely a problem / bug and this is not only a problem of support.

**Comment by karstengit** [comment]
Bug reported to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002723

**Comment by crknadle** [comment]
I'm the maintainer for Mumble in Debian.

This initially looks to me like it might be an IPv6 vs IPv4 issue, because in the error when the connection fails I see an IPv6 address:

```
<W>2021-12-27 10:28:31.399 ServerHandler: connection attempt to [2001:4dd0:af1b:3a0f:ca0e:14ff:fee6:a090]:64738 failed: Verbindung verweigert (0); trying next server....
```
but in the configuration file it looks like the host is a local LAN IPv4 address:
```
; Specific IP or hostname to bind to.
; If this is left blank (default), Murmur will bind to all available addresses.
host=192.168.1.3
```
So that's the first thing I'd like to point out because I didn't see that discussed in the bug.
It's still possible the setup might be valid if perhaps there's some kind of 6-to-4 translation going on in a router, but again I'd expect to see that mentioned somewhere in the bug if so.

**Comment by karstengit** [comment]
The idea sounds good, but is there any chance to debug the reason for it?
The router is an Fritzbox 7360 and IPV6 has been activated for test purposes to use IPV6 now.
There are massive problems to use XMPP over port 5222 to, because there is always the message "no route to host".
It's interesting that there is IPV6 for such a long time, but it seems not really possible to analyze what is going on.
Recently i found out that there is no difference with static / nonstatic IP's in IPV6 and so on ...

Do you have any other idea to switch of IPV6 in the Fritzbox?

**Comment by ppfeufer** [comment]
Check in your FritzBox's web interface if it says something like this:

![image](https://user-images.githubusercontent.com/2989985/147847648-6dc3e32b-55c4-467e-ad56-28112a235f26.png)

If so, you're pretty much out of options, a DS-Lite tunnel prevents your network from being reachable from the internet, even prevents port forwarding. Unfortunately, a lot of providers do that nowadays ...

It also means, you don't have an IPv4 address anymore and everything IPv4 related is tunnelled...

**Comment by karstengit** [comment]
> Check in your FritzBox's web interface if it says something like this:
> 
> If so, you're pretty much out of options, a DS-Lite tunnel prevents your network from being reachable from the internet, even prevents port forwarding. Unfortunately, a lot of providers do that nowadays ...

No - there is an IPV4 and IPV6 address that can be used over DynDNS:

Internet
IPv4, verbunden seit 01.01.2022, 10:38 Uhr
IP-Adresse: 89.97.159.231 Internet

IPv6, verbunden seit 01.01.2022, 10:38 Uhr
IPv6-Adresse: 2009:4cd0:af5a:d939:Fa0d:14ff:fea6:a190

I have tested to disable IPV6 and then there is only one connection directly opened over IPV4.
I must test if the older client of the friend can connect without IPV6 ...

Now i am asking me if IPV6 has 'only' disadvantages, specially regarding the firewall and routing?
I already did not update the firmware of the Fritzbox, because newer versions don't allow a distinct NAT of ports.
I should take the time and compile a freetz for the box to get root privileges and more tools.

**Comment by karstengit** [comment]
> Now i am asking me if IPV6 has 'only' disadvantages, specially regarding the firewall and routing?

The answer seems to be yes - specially when using a Fritzbox with activated Firewall.
There was a missing portforwarding for IPV6, but after configuring the needed ports and a reboot of the fritzbox, the portforwarding still does not work with IPV6 - the firmware is rubbish!
So IPV6 is deactivated now again.
More and more it seems to be a good idea to use the fritzbox only as modem and make the rest with an dedicated server.

**Comment by Krzmbrzl** [comment]
Closing as _resolved_
