### ISSUE TITLE
murmur should pick up updated certificate automatically

### ISSUE THREAD

**Issue by stblassitude** [mumble-voip/mumble#5404]
### Context

When using Let's Encrypt or similar, the certificate will be renewed relatively often. It's easy to point murmur at the LE certificate, but the cert is only read on server startup.

### Description

murmur should use the current version of the certificate everytime a new client connects. Alternatively, murmur should monitor the certificate file (or poll regularly) for changes, and update it's server socket to use an updated certificate, without the need to restart the server.

### Mumble component

Server

### OS-specific?

No

### Additional information

While it's possible to restart the server (through cron or a hook) with only minimal disruption, a completely seamless solution would be preferable.

**Comment by Krzmbrzl** [comment]
I will merge this with #4544
