### ISSUE TITLE
Unable to hear other participants

### ISSUE THREAD

**Issue by khers** [mumble-voip/mumble#5409]
### Description

WHen connected to a mumur server I run, I cannot hear other users.  The can hear me and I can see that they are talking on the mumble interface, but they cannot hear me.

### Steps to reproduce

1. Install mumble on Pop!OS 21.10
2. connect to server version 1.3.4 running on Debian 11
3. have windows user connect
4. try to talk with them

### Mumble version

1.3.4

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Initially we assumed this was on the window client side as reported in #5407 but when another windows user connected they could talk with each other.

**Comment by khers** [comment]
I should note that other audio things work fine (zoom, steam, etc)

**Comment by khers** [comment]
Disregard, this is a PEBKAC issue, application had been muted by desktop environment, not sure why TTS was still playing.

**Comment by Krzmbrzl** [comment]
Good to hear, you figured it out :D
