### ISSUE TITLE
Questions about high availability

### ISSUE THREAD

**Issue by ficzve** [mumble-voip/mumble#5420]
### The issue

Dear support,

I'm trying to make a automatic failover for when a mumble server dies, enabling simple and high availability mumble server hosting with the use of two servers.

Whats the best practice ?

Best Regards, Hélio Ficz

### Mumble version

1.3.4

### Mumble component

Server

### OS

Linux

### Additional information

I performed tests with this step by step but it was not stable

https://github.com/ohaal/murmur-failover-daemon

**Comment by Krzmbrzl** [comment]
There is no built-in way of achieving what you need.
My best guess would be to have something that repeatedly checks whether the server is still alive and if not, starts a separate one (or restarts it).

**Comment by Silmerias** [comment]
There is a way out of mumble, any cloud services have load balancers / traffic director. It periodically check the port / service and redirect in case of crash. That requires an external public address and 2 murmur services docker or instances.

**Comment by azlux** [comment]
I think the best for you is to have a vrrp ip (or load balancer in front of your murmur server) and a MariaDB server (galera) to have active-active database backend.
This way, you can fallback to your secondary server very fast.
