### ISSUE TITLE
Allow pasting of images into the "Type message to channel" box

### ISSUE THREAD

**Issue by archer007** [mumble-voip/mumble#5424]
### Context

Quickly sharing images in the system clipboard with the rest of the people in the Mumble channel you are in

### Description

Instead of right-clicking the current channel, clicking "Send Message", the pasting in the image from the clipboard, allow pasting an image directly into the "Type message to channel 'X' here" box. The input box currently does not support this and appears to do nothing if this is attempted in Mumble 1.3.4

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
I am somewhat certain that this has been implemented in 1.4. Could you check that version out?

**Comment by Krzmbrzl** [comment]
I can confirm, this is implemented in 1.4 (since the very first snapshot release): https://github.com/mumble-voip/mumble/pull/4265
