### ISSUE TITLE
Download link for client 1.4.230 leads to a 404

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#5427]
### Description

Download link for client 1.4.230 leads to a 404

### Steps to reproduce

1. Open Mumble
2. Click 'our server'

### Mumble version

1.3.4

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

Bad URL: https://dl.mumble.info/stable/client-windows-x64.msi  
Good URL: https://dl.mumble.info/stable/mumble_client-1.4.230.x64.msi

### Screenshots

![Screenshot01](https://user-images.githubusercontent.com/56807288/149677126-4f1d2bf2-32c7-45fd-ac4d-a02386a99d29.png)

![Screenshot02](https://user-images.githubusercontent.com/56807288/149677244-cf48820e-fdda-4e8e-b36b-de80f9f3719e.png)

**Comment by davidebeatrici** [comment]
The link should be https://dl.mumble.info/latest/stable/client-windows-x64.

**Comment by Krzmbrzl** [comment]
Whoopsie, I screwed up the links. Thanks for letting us know! It should be fixed now
