### ISSUE TITLE
No PGP signed sources for 1.4.230

### ISSUE THREAD

**Issue by dvzrv** [mumble-voip/mumble#5434]
### Description

Hi! I package mumble/murmur for Arch Linux.
We are relying on PGP signed sources for our builds, but there have been none made available for [1.4.230](https://github.com/mumble-voip/mumble/releases/tag/v1.4.230).
Can you please add them? :)

### Steps to reproduce

Try to download PGP signed sources for [1.4.230](https://github.com/mumble-voip/mumble/releases/tag/v1.4.230)

### Mumble version

1.4.230

### Mumble component

Both

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
@davidebeatrici you wanted to add the signing stuff

**Comment by Krzmbrzl** [comment]
Out of curiosity though: why are you relying on signed sources instead of just downloading the sources from GitHub yourself and then compile from that? 👀

**Comment by dvzrv** [comment]
> Out of curiosity though: why are you relying on signed sources instead of just downloading the sources from GitHub yourself and then compile from that? eyes

Signed sources give us the confidence that "someone" (not just anyone) has created the release that we are building. Signatures for releases are added on a trust-on-first-use (TOFU) basis and from then on are supposed to be changed using a chain-of-trust going forward (i.e. the first key signs the next, or the first key establishes the next in a signed commit e.g. in a README document).
Signatures can be used in the form of signed tarballs or signed tags.

As you can imagine, not providing signed sources anymore without prior notice or explanation raises many red flags for downstreams that have been relying on them. From the outside it is not visible whether a supply-chain-attack is in motion or not (e.g. due to compromised code hoster accounts), which requires them to audit your source code to understand what is going on.
Depending on policy they might still not update then.

Sidenote on building from unsigned git tags:
Many source hosters (github included) do not allow finely grained access restriction on branches or tags. So a tag could be removed, or moved (e.g. by a malicious entity).

**Comment by tgurr** [comment]
@Krzmbrzl not directly related, but another reason we need a proper release tarball is that the GitHub source archive tarball doesn't include any git submodules which were/are usually present in a proper release tarball.

**Comment by Krzmbrzl** [comment]
> another reason we need a proper release tarball is that the GitHub source archive tarball doesn't include any git submodules which were/are usually present in a proper release tarball.

Ah interesting - didn't know that. However, I guess that could be mitigated by simply using `git` to clone the repo in the first place (and then to init the submodules).

**Comment by davidebeatrici** [comment]
Uploaded.

**Comment by dexgs** [comment]
Am I missing something? I don't see any sources uploaded, only binaries.

**Comment by davidebeatrici** [comment]
My fault, I was following #5446 for that.

**Comment by davidebeatrici** [comment]
Uploaded.
