### ISSUE TITLE
Appstream ID

### ISSUE THREAD

**Issue by JBBgameich** [mumble-voip/mumble#5441]
### Description

I'm the maintainer of the Mumble flatpak, and since previously there was no official Appstream ID, I used info.mumble.Mumble, according to the Appstream specification.

It seems you have now chosen to use org.mumble_voip.mumble instead, which has the problem of not following the spec:
>  The ID must follow a reverse-DNS scheme, consisting of {tld}.{vendor}.{product}, for example org.kde.gwenview or com.hugski.colorhug2. Ownership of {vendor}.{tld} in the domain name system guarantees uniqueness of IDs. 

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic

mumble_voip.org doesn't seem to be a valid domain name, since domain names should not contain underscores.
Also mumble_voip.org is not registered, probably because it's not a valid domain.

Should I nevertheless switch to the new id, or would you rather change it upstream before it sees general usage in distributions?

### Steps to reproduce

Not applicable

### Mumble component

Client

### OS

Other

### Reproducible?

Haven't tried

**Comment by Krzmbrzl** [comment]
Uhm - iirc we didn't choose the given ID out of a specific reason other than to make some sort of linter happy that was running when building an AppImage. So if the thing we finally settled on, violates some guidelines, we could also just change it ^^

`info.mumble.Mumble` sounds good to me :thinking:

**Comment by Kiwii** [comment]
The window class should also use the correct ID then. It currently seems to be using `net.sourceforge.mumble.mumble`, causing Mumble's windows to not be associated with the correct *.desktop file on Wayland desktops (at least on Plasma), resulting in it showing the default Wayland icon on the task bar and being unable to be pinned to it.

Apologies if this might be considered a separate issue.

**Comment by Krzmbrzl** [comment]
@Kiwii this seems to be closely related, so having it here is fine.
Just to be sure: window class is something that is set inside the project and not something specified in some external file like the desktop file?

**Comment by Kissaki** [comment]
I diffusely remember the sourceforge string to be used somewhere, and us not being able to just replace it because of it. So if there will be a change, please make sure potential issues are accounted for with a migration path; I am thinking of Qt settings mainly, but maybe also some Windows or Linux specific things making use of it (linux paths?). Or theming?

Unfortunately I can’t provide what it is used for concretely. I remember some time ago I changed it in a commit for me locally, which I subsequently discarded though.

I guess I’m just pointing out it’s not a simple string replacement without side effects.

**Comment by Kiwii** [comment]
@Krzmbrzl I'm not sure where it is set but I don't think it's specified in an external file. I assume it's handled by Qt for each window that is created. "Window class" might also not be the correct term for it on Wayland (I think it's the X11 term), but it's what it is referred to by KDE's special window settings menu: https://i.imgur.com/obs7S5f.png

Kwin's debug window calls it "resourceClass" so maybe that's the correct term on Wayland (?) https://i.imgur.com/nwoZp0C.png

@Kissaki It seems to be used for the D-Bus service and the PulseAudio sink properties at least.

**Comment by Krzmbrzl** [comment]
I think the window class is probably assembled from this:
https://github.com/mumble-voip/mumble/blob/1a5dd7c72c27c495c6dc37aa5b3a30168e1aa495/src/mumble/main.cpp#L154-L158
