### ISSUE TITLE
Multiple shortcuts broken

### ISSUE THREAD

**Issue by Silmerias** [mumble-voip/mumble#5444]
### Description

**Shortcuts aren't working anymore if you add a second entry.**

![image](https://user-images.githubusercontent.com/5228878/149801229-17dedc31-131a-48af-955b-376fd53ed7e6.png)

### Steps to reproduce

1. Open Settings menu
2. Go to shortcut menu
3. Add a keyboard AND a mouse shortcut for any actions like 'Mute Self'
4. Save and try the shortcut

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows 10

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Wdym with "second entry"? A second shortcut?

**Comment by Silmerias** [comment]
@Krzmbrzl like the screenshot, you add 2 entry in one shortcut : 

![image](https://user-images.githubusercontent.com/5228878/149805874-2e1fa516-1067-45a3-8361-2b25e2f884e6.png)

**Comment by Silmerias** [comment]
No any role seems to suffer the same issue. Yes the two buttons do not work.

**Comment by Krzmbrzl** [comment]
> And does it occur with any two buttons or only if one of the buttons is a mouse button?

:point_up:

**Comment by Silmerias** [comment]
The legacy way of doing it still working tho. This is only the new system.

![image](https://user-images.githubusercontent.com/5228878/149809378-103311f4-3d69-402f-9674-7c9f3f0c14d4.png)

**Comment by Silmerias** [comment]
> 

2 keyboard or 2 mouse button are suffering the bug too.

![image](https://user-images.githubusercontent.com/5228878/149809668-417feff2-9642-4e40-b489-b26d823c029b.png)

**Comment by Krzmbrzl** [comment]
> The legacy way of doing it still working tho. This is only the new system that suffer the bug =)

Ah hold on - you expected the buttons to work _independently_ where pressing either button activates the shortcut? What actually happens is that you assign the shortcut to the _combination_ of buttons pressed at the same time. So if you configure button A AND button B, you'll have to press both of them to activate the shortcut :)

**Comment by Silmerias** [comment]
Oh, that was unexpected. I think it's not user friendly and need a description or a tool tip then :D
Let's close this.

**Comment by Krzmbrzl** [comment]
I think I have never seen a UI that allows you to assign multiple shortcuts in a single window for one and the same window :eyes: 

Anyways, do you happen to have a suggestion as to how the UI could/should be changed which would have helped you to grasp the meaning of it more easily? :thinking:

**Comment by Silmerias** [comment]
![image](https://user-images.githubusercontent.com/5228878/150139719-6944f1eb-b5c8-4e32-b55d-845fe123d67c.png)

Well I think you could add under "Add / Remove", a small text like : "Add key to create a combination"

The new window for add multiple key, at start I was thinking the shortcuts module had changed to set multiple possibility of input for one shortcut. A small description could vanish any confusion.

That is not really important IMO, that was just a suggestion from a user perspective, don't give it too much attention. Mumble is for me the best vocal system and I would love to see much more important features in it than just a tooltip as, hiden channel and user when no enter access (for security reasons), scalability, clustering and so on (I know it is barely impossible without rewriting entirely mumble but that would be a blast).

And many thanks for all what you have done with this awesome project. I have much respect for you guys.
