### ISSUE TITLE
How do you use the new 1.4.230 static server?

### ISSUE THREAD

**Issue by FlyveHest** [mumble-voip/mumble#5447]
### The issue

Having downloaded the new static server, I was somewhat confused when I ended up with a .linux file, that seems to be an executable (Which I should mention, haven't tried running yet)

The older static downloads was a TAR file with various files, including a murmur.x86 executable, an ini file and more.

Is the .linux file a drop-in replacement for murmur.x86?  Or how am I supposed to use it?

I haven't done any experimentation, as there are no mentions of this new packaging in the changelog, and I do not want to risk overwriting settings, database or anything else in my existing setup.

### Mumble version

1.4.230

### Mumble component

Server

### OS

Linux

**Comment by davidebeatrici** [comment]
It's supposed to be a drop-in replacement, however we should probably compress it into an archive along with the corresponding `mumble-server.ini`.

**Comment by milaq** [comment]
`./server-linux-x64: error while loading shared libraries: libmysqlclient.so.21: cannot open shared object file: No such file or directory`
and
`server-linux-x64: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2`

The "static binary" on the main downloads page is dynamically linked.

**Comment by PhilThurston** [comment]
> It's supposed to be a drop-in replacement, however we should probably compress it into an archive along with the corresponding `mumble-server.ini`.

As a drop in replacement we get the same error that @milaq above has. Is there and ETA on a tarball of a working copy of the linux binary? That way we can get this working?

**Comment by Krzmbrzl** [comment]
There will be no static server anymore, unless a volunteer finds out how the vcpkg environment has to ve configured to produce an actually static binary. Until then no static binary (for Linux) will be released

**Comment by PhilThurston** [comment]
> There will be no static server anymore, unless a volunteer finds out how the vcpkg environment has to ve configured to produce an actually static binary. Until then no static binary (for Linux) will be released

Alright, noted. That being said @davidebeatrici said there would be some more complete option so we can get this working. If you @Krzmbrzl or @davidebeatrici could give us a step by step rundown to your users of how to get this latest version of Mumble working in linux that would probably clear up a lot of confusion with the majority of your userbase that may use linux.

**Comment by Krzmbrzl** [comment]
>  davidebeatrici said there would be some more complete option so we can get this working

I think he was only referring to also packaging a default configuration file alongside the server. That won't get us anywhere though, since the server binary itself won't be able to run in the first place.

> give us a step by step rundown to your users of how to get this latest version of Mumble working in linux

Essentially, follow our [build instructions](https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions). Except that once you have cloned the repository, run `git checkout v1.4.230` inside the repo to check out the code corresponding to the 1.4.230 release.

**Comment by PhilThurston** [comment]
Thank you that helps. One of our guys has worked with vcpkg and I'll have him ping you guys in a private message. Maybe we could automate the build and deployment of all these assets for future releases. Thanks for the help.
