### ISSUE TITLE
The sound of the version 1.4.230 is way worse then 1.3.4

### ISSUE THREAD

**Issue by Pamalosebi** [mumble-voip/mumble#5448]
### The issue

The sound transferred using a 1.4.230 Mumble client is way worse compared with the previous 1.3.4 version.

To make that clear, the systems and microphones used are identical. (> All what changed is the Mumble client)
And the results are reproducable with multiple PCs and setups.

It's tough to describe but it sounds very "muffled" and robotic in direct comparison.
Also noticable is a very high latency (without any changes to server or network?).

We didn't manage to improve the results through changing the "input" or "output" settings.
So, we will change back.

Is there anything to improve on our end?
Otherwise we can't really upgrade. Which is very sad, we would like to stick with mumble in the long run :(

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Additional information

Official Murmur Server on Ubuntu Server -> Version 1.3.4, since there is no update yet.

**Comment by Krzmbrzl** [comment]
Did you tinker with the noise suppression and/or echo cancellation options? Both of these systems have received changes between 1.3 and 1.4, so maybe some of that is interfering in your case.

**Comment by Sonasword** [comment]
I came here experiencing similar issues. Yesterday, I was using 1.3 with no issues on mic quality. Later in the day, I saw there was the update to 1.4.230 and other users in my server called out either a static sound or a somewhat canny / muffled sound from mic, which hasn't happened in the past. I tried messing with echo cancellation and noise suppression options, but couldn't get the audio to clear up in audio wizard tests. I checked connections with the mic and the Scarlet Solo audio interface and they seemed to be working correctly. I tested my mic in Windows and Discord and didn't run into the same issue.

Perhaps it's a special combination of settings between the echo and noise cancellation that I haven't tested yet, but it seems weird that the issue persists even when I tried going back to 1.3 or earlier versions of Mumble. Is there any way the update to Mumble changed drivers or some other setting I'm unaware of?

**Comment by Pamalosebi** [comment]
> other users in my server called out either a static sound or a somewhat canny / muffled sound from mic

That sounds pretty much like the issues we encounterd.

> Did you tinker with the noise suppression and/or echo cancellation options? Both of these systems have received changes between 1.3 and 1.4, so maybe some of that is interfering in your case.

Yes, we did tinker with those settings. We turned everything off, too. But sadly nothing changed.


If I think about it... I had looong time ago such a situation with Teamspeak.
They didn't implement Opus and used speex. That led to horrible quality.
-> Something like we experience right now. But has probably nothing to do with this...

**Comment by vimpostor** [comment]
Sounds like maybe the CELT codec is used. Try forcing Opus by setting opusthreshold in the server config to 0.
There were already plans to remove CELT support, I think now that 1.4 is released, we should finally erase CELT from the codebase completely.

**Comment by Krzmbrzl** [comment]
Yes that would definitely be worth a try. And yes we should definitely get rid of that old CELT stuff

**Comment by pet0ruk** [comment]
It seems like for some reason the noise suppression changes from Speex to RNNoise in the new version.

Under `Configure -> Settings -> Audio Input` turn `Echo Cancellation` to `Disabled`, `Noise Suppression` to `Speex` (can leave it at the default `-30 dB`). It's the Noise Suppression change that makes the difference though.

**Comment by Pamalosebi** [comment]
Okay, I did as advised (forced Opus) and now, when we turn off the RNNoise it is way better!
As soon we put RNNoise on it sounds really bad.

**Comment by Krzmbrzl** [comment]
Are the input levels on your mic perhaps rather high? RNNoise is known to cause really bad audio when the input audio is clipping

**Comment by Krzmbrzl** [comment]
> It seems like for some reason the noise suppression changed from Speex to RNNoise in the new version.

It's because that's the new default, iirc.


Okay but by enforcing Opus and disabling RNNoise the issue is fixed?

**Comment by pet0ruk** [comment]
> Are the input levels on your mic perhaps rather high? RNNoise is known to cause really bad audio when the input audio is clipping

I'm not the issue opener but we've had 5 people upgrade so far and every single one has static noises on their mic after the upgrade and switching back to Speex has immediately restored the quality to the level before the update. We were all using Opus, RNNoise is what was at fault.

**Comment by Krzmbrzl** [comment]
RNNoise is really weird - some swear that it is the best noise suppression ever, working magically well and others, like you, report that it is complete garbage. Maybe it only works for certain types of input devices or setups :thinking:

**Comment by Pamalosebi** [comment]
> > It seems like for some reason the noise suppression changed from Speex to RNNoise in the new version.
> 
> It's because that's the new default, iirc.
> 
> Okay but by enforcing Opus and disabling RNNoise the issue is fixed?

Yes. Opus forced by the server and RNNoise off is helping greatly.

After some testing, we figured, that these settings mights sound even better than what we had with 1.3.4:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/49550055/149834674-21de4ba8-81fd-468c-90bc-5de87bf2cb06.png">

**Comment by Green-Sky** [comment]
random thought: maybe this rnnoise depends on the sample rate?
the log files should contain the sample rates.
mine look like this:
```
...
<W>2022-01-16 22:57:46.458 AudioInput: Opus encoder set for low delay
<W>2022-01-16 22:57:46.458 AudioInput: 70044 bits/s, 48000 hz, 480 sample
...
```

**Comment by Krzmbrzl** [comment]
The sample rate is hardcoded at 48 kHz

**Comment by Snowknight26** [comment]
I've noticed this as well using several of the older 1.4.0 development builds. The users that had RNNoise enabled had discernably worse transmit quality (can't remember the exact details as it was months ago) on a server with a maximum audio bandwidth of ~100Mbps (yes, Mbps) - each user typically has their audio input settings as high as they will go quality-wise. At least one of those users was using an identical input setup to me: MXL AC-404 USB mic, Windows mic volume set to ~80, Windows format set to the default of 1 channel/16 bit/48KHz.

Coincidentally, those that had RNNoise enabled also suffered from the issue described in #4538.

**Comment by vimpostor** [comment]
Has anyone been able to reproduce this on another OS than Windows?

**Comment by Krzmbrzl** [comment]
Hold on, stale-bot. I still want to change the defaults base don this issue....

**Comment by hartmunt** [comment]
> Has anyone been able to reproduce this on another OS than Windows?

Yes. We had a single user with this problem on Linux. After the upgrade from 1.3.4 to 1.4 their sound quality was pretty bad. Tweaking the RNNoise parameters did not help. Only after switching manually to Speex the sound quality was the same as before. Note that their microphone was a fairly low-tier one with some static noise present in raw recordings.
Other users, Linux and Windows, had no problem after the upgrade even when using RNNoise.

**Comment by bkacjios** [comment]
One thing I've noticed is that ever since I updated to 1.4 my friends, who are still on 1.3.4, say my audio quality is sometimes terrible and laggy while the ones who also updated to 1.4 say it's always completely fine. Could this be the same issue? Is the client version mismatch somehow to blame?

**Comment by Krzmbrzl** [comment]
No that seems unrelated. The different versions shouldn't affect audio quality at all (afaict) :thinking:

**Comment by Pamalosebi** [comment]
> Note that their microphone was a fairly low-tier one with some static noise present in raw recordings.

Hmm... our microphones are fine. We don't have any interferences while recording.
Nevertheless, we have that issue. (just tested with windows, tho)

**Comment by 0xC0ncord** [comment]
I'm also having the same problem on Gentoo Linux and Pipewire. I can also report that I had this problem on earlier 1.4.0 development builds.

Strangely, if I apply RNNoise directly in Pipewire instead of using the Mumble settings UI to do it, I get the same behavior. This did not happen on 1.3.4.
