### ISSUE TITLE
ServerDB: Database driver QMYSQL not available

### ISSUE THREAD

**Issue by Bagu** [mumble-voip/mumble#5450]
### Description

Hello,
When I install Mumble server 1.4.230 to update my 1.3.4 installation, I don't have the choice of the installation path.
Moreover, when I try to start the server, I receive the message :
ServerDB: Database driver QMYSQL not available

While the latter works perfectly with version 1.3.4.

### Steps to reproduce

1. Have a mumble server running under windows
2. Use QMYSQL driver
3. Try to install mumble server 1.4.230
4. Can't choose the install path, so copy files to the right install folder
5. Try to start the server

### Mumble version

1.4.230

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

**Comment by ZeroAbility** [comment]
The client and server installs for Windows do not allow changing of the directory. Here is the original issue:
https://github.com/mumble-voip/mumble/issues/4702

**Comment by Bagu** [comment]
Ok, so only the QMYSQL driver problem left... But i really hope the portable version to be available soon.
Thanks

**Comment by davidebeatrici** [comment]
Ouch, the QMYSQL issue is due to the static Qt plugin not being included...

**Comment by davidebeatrici** [comment]
@Bagu Could you check whether QDBC works instead?

**Comment by Bagu** [comment]
Unfortunatly, i can't. If someone else can test :(

**Comment by davidebeatrici** [comment]
As a temporary solution, you should be able to load the plugin provided at https://github.com/thecodemonkey86/qt_mysql_driver.

**Comment by davidebeatrici** [comment]
Where did you put the driver?

**Comment by Bagu** [comment]
I try three places :
-App dir
-System32
-Syswow64

**Comment by davidebeatrici** [comment]
You have to create a directory called `sqldrivers` in the application's directory and put the DLL in it.

**Comment by Bagu** [comment]
Already done - i follow the insallation instructions to do it.

**Comment by Bagu** [comment]
Hello, i'v just try to install v1.4.274
The problem is still here... Is there something to do to make MySQL work with 1.4.x version ?

**Comment by Krzmbrzl** [comment]
Yes, we were unable to update the build environment for 1.4 as vcpkg also switched to OpenSSL 3, which is not supported in the 1.4 branch. So this issue will only be fixed once we release 1.5
Until then, there's nothing you can do (unless you self-compile a 1.5 version)
