### ISSUE TITLE
Release assets are no longer published on the Github release

### ISSUE THREAD

**Issue by iamkubi** [mumble-voip/mumble#5451]
### Description

For the 1.4.230 release the Assets section of the Github release is empty:
https://github.com/mumble-voip/mumble/releases/tag/v1.4.230

Compared to the previous releases where the builds are usually included in the release assets:
https://github.com/mumble-voip/mumble/releases/tag/1.3.4

### Steps to reproduce

N/A

### Mumble component

Both

### OS

Other

### Reproducible?

Yes

**Comment by PhilThurston** [comment]
It looks like on the linked blog post it also says that download links are available on the github release page but they are missing. Could this be a problem with the CI?

**Comment by PhilThurston** [comment]
The main website also references the github page for individual files: "For the individual files and for a zipped sources file see the 1.4.230 GitHub release page." https://www.mumble.info/downloads/

**Comment by davidebeatrici** [comment]
We upload assets manually, I'm going to do that as soon as possible.

**Comment by iamkubi** [comment]
Hmm, I might suggest in the future it could make sense not to publish the release until the artifacts are available?  You can create the release as a draft, upload the artifacts, and then publish once everything is complete.

**Comment by davidebeatrici** [comment]
Uploaded.

> Hmm, I might suggest in the future it could make sense not to publish the release until the artifacts are available? You can create the release as a draft, upload the artifacts, and then publish once everything is complete.

The artifacts were actually available, but we only uploaded them to our servers as we were busy fixing the issue with the macOS build.

But yes, creating a draft release and then publishing it would be ideal.

**Comment by dexgs** [comment]
Is everything finished? Unless I'm missing something, the release is still missing a source tarball that compiles.

**Comment by iamkubi** [comment]
The source code tarball is there.  The file names for the compiled assets seem to have changed, although the source code filename format is still the same.

https://github.com/mumble-voip/mumble/archive/refs/tags/v1.4.230.tar.gz

**Comment by iamkubi** [comment]
Oh, the tag has a `v` in it now, which is likely why you can't find the source tarball.

**Comment by davidebeatrici** [comment]
https://dl.mumble.info/stable/mumble-1.4.230.tar.gz
https://github.com/mumble-voip/mumble/releases/download/v1.4.230/mumble-1.4.230.tar.gz

**Comment by Software-Noob** [comment]
The latest server releases have changed the tarballs from murmur_static to mumble_server, thus most likely breaking other scripts.

Is this a permanent release style, or was it done by mistake?

**Comment by Krzmbrzl** [comment]
I am not aware of any strict format for the directory names, but generally speaking we want to drop the term "murmur" and use "mumble-server" instead. So at least the "murmur_static" is likely to disappear for good

**Comment by Software-Noob** [comment]
> I am not aware of any strict format for the directory names, but generally speaking we want to drop the term "murmur" and use "mumble-server" instead. So at least the "murmur_static" is likely to disappear for good

I am referring to the releases. To automatically pull them through a script, we must grep the release assets. In the past, we grepped for `murmur_static`. This new change breaks this functionality, so will it stay as `mumble_server` from now on?

Making sure we don't have to push new updates again on the next release.

**Comment by Krzmbrzl** [comment]
Ah, yes that will most likely remain at `mumble_server`
