### ISSUE TITLE
[1.4.230][macOS] Cannot Add Keyboard Shortcuts

### ISSUE THREAD

**Issue by philipbel** [mumble-voip/mumble#5452]
### Description

I have been running the RC for a while. Just downloaded the official 1.4.230.

After fixing #5429 locally, I am seeing another issue—I cannot change the keyboard shortcuts. The Add button of the "Edit shortcuts" window does nothing.

I have explicitly given Mumble input monitoring permissions (and restarted).

### Steps to reproduce

1. Start Mumble.
2. Open Preferences
3. Go to Shortcuts
4. Click on Push-to-Talk
5. In the newly opened "Edit shortcuts" window, click add.

- Actual: nothing happens
- Expected: being able to add a shortcut.

### Mumble version

1.4.230

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

### Additional information

This used to work with the previous RC.

### Screenshots

<img width="624" alt="Screen Shot 2022-01-17 at 23 27 39" src="https://user-images.githubusercontent.com/145237/149843584-fba2bd4a-3bf0-49fa-894e-2e2fa73bc851.png">

<img width="680" alt="Screen Shot 2022-01-17 at 23 24 00" src="https://user-images.githubusercontent.com/145237/149843298-581debd8-0d4c-4990-a1dc-d31bfab6ef3f.png">

**Comment by davidebeatrici** [comment]
You need to give Mumble Accessibility permissions.

**Comment by philipbel** [comment]
> You need to give Mumble Accessibility permissions.

Mumble did have Accessibility permissions.
<img width="579" alt="Screen Shot 2022-01-18 at 09 54 52" src="https://user-images.githubusercontent.com/145237/149903581-696e29e0-f28b-4461-b318-3bd94c70209a.png">

What fixed the issue was removing Mumble.app from the Accessibility permissions list and manually adding it by dragging it from the Finder. Now shortcuts work.

I now recall seeing similar issues with the Accessibility APIs before, and believe this is actually a bug in macOS.

**Comment by Krzmbrzl** [comment]
Now that you write that, I think we have encountered a similar issue at some point before :eyes: 

Anyway - glad to see it is working for you now! :+1: 

Closing as _resolved_

**Comment by Exoticccaming** [comment]
i tried the same but it isnt working

**Comment by Krzmbrzl** [comment]
@Exoticccaming did you try removing Mumble from accessibility access before explicitly re-adding it again?

**Comment by G-kell** [comment]
> > You need to give Mumble Accessibility permissions.
> 
> Mumble did have Accessibility permissions. <img alt="Screen Shot 2022-01-18 at 09 54 52" width="579" src="https://user-images.githubusercontent.com/145237/149903581-696e29e0-f28b-4461-b318-3bd94c70209a.png">
> 
> What fixed the issue was removing Mumble.app from the Accessibility permissions list and manually adding it by dragging it from the Finder. Now shortcuts work.
> 
> I now recall seeing similar issues with the Accessibility APIs before, and believe this is actually a bug in macOS.

I was about ready to give up when i found your comment. This would be really useful on the downloads page in reference to macOS builds. Took me a while to find it.

**Comment by Oclair** [comment]
bump
