### ISSUE TITLE
[1.4.230] Static linux server binary is dynamically linked

### ISSUE THREAD

**Issue by milaq** [mumble-voip/mumble#5453]
### Description

The "static linux server" binary available on the main download page (https://dl.mumble.info/latest/stable/server-linux-x64) is dynamically linked.

`server-linux-x64: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2`

Furthermore, there are no statically linked release assets for 1.4.230 available:
https://github.com/mumble-voip/mumble/releases/tag/v1.4.230

### Steps to reproduce

1. Try to run the "static binary"
2. Notice it being dynamically linked

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by davidebeatrici** [comment]
Honestly, we would like to get rid of the static server binary in favor of something like an AppImage. Suggestions are welcome.

**Comment by Krzmbrzl** [comment]
The static server has been removed from our website and from GitHub releases.

**Comment by fefrei** [comment]
Oh no! It would be really nice to get a static Linux build back – these were super easy to deploy, with no extra fuzzing around 😢

**Comment by Krzmbrzl** [comment]
If you find a way to convince vcpkg to actually build a completely static binary (minus libc, probably), let us know and we'll give it another shot. But that obviously wasn't quite as easy as I thought it should be :shrug:

**Comment by fefrei** [comment]
Sorry, I'm completely clueless here – I was just commenting on the usefulness of the static builds. Hope you're able to get this fixed up ❤️

**Comment by PHLAK** [comment]
I've been using the static Linux binary to build a [custom Docker image](https://hub.docker.com/r/phlak/mumble). With this removal this will become more difficult. Sure I can still build from source but the statically linked binary was super nice and convinient.

**Comment by Krzmbrzl** [comment]
Potentially as a replacement for the static server, you can make use of the new Docker image available at https://github.com/mumble-voip/mumble-docker

**Comment by fefrei** [comment]
Heyho! Just to report back: The new Docker image works fine for our use case. Nice to finally have an official image ❤️

Hints for anyone who rolled their own container before: `/etc/mumble` is now `/data`. You may need to adjust permissions – Mumble (which is not running as `root` in the container) needs to be able to write to the `/data` _folder_, plus the database within it, if you are using the SQLite database.

**Comment by lupinia** [comment]
Are there any updates on this issue?  The installation instructions for RHEL servers require a static binary, which does not exist, so this is a blocking problem (not sure why it's marked Closed if it's not actually resolved).

**Comment by davidebeatrici** [comment]
Because you're supposed to compile it yourself. Which instructions for RHEL are you referring to?

**Comment by lupinia** [comment]
These:  https://wiki.mumble.info/wiki/Install_CentOS7

**Comment by davidebeatrici** [comment]
Follow https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md instead.

**Comment by Krzmbrzl** [comment]
> (not sure why it's marked Closed if it's not actually resolved

It is resolved. It's a wontfix
