### ISSUE TITLE
Revert Global Shortcut blocking on Wayland

### ISSUE THREAD

**Issue by Max-FT** [mumble-voip/mumble#5454]
### The issue

#5307 breaks shortcuts for Wayland users. Users opened numerous issues regarding global shortcuts not working outside the window on Wayland. However, there's a full workaround. Wayland users can add these two lines under the [shortcut] section in
Mumble.conf:

```ini
[shortcut]
linux\evdev\enable=true
linux\evdev\framesperpacket=1
```

I have personally used this workaround for the last year just fine on Wayland with both 1.3.4 and the git build of 1.4 before the team released it. Please consider reverting the commit blocking shortcut access and update your documentation to include this
workaround. As an aside, I'd like to thank the Mumble contributors for 1.4. It's looking like a solid release otherwise.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Linux

**Comment by davidebeatrici** [comment]
We should enable Evdev by default and eventually add an option in the settings.

**Comment by Krzmbrzl** [comment]
The commit should not simply be reverted as it fixed a specific issue that we should not re-introduce. In addition to that, for all I know in order to use evdev, the user has to be in some special group, which most users will not be in by default. Thus, for most users I think simply disabling the shortcuts on Wayland until we have implemented proper Wayland support is the best thing to do. Everything else will just lead to loads of bug reports of broken shortcuts.

That being said, I think we could improve upon the current situation by introducing an option to override this disablement for users that know how to make evdev work (we could even describe how to get it to work on our website and then link to that).

**Comment by Max-FT** [comment]
For any Wayland users who use push-to-talk and are struggling in the meantime, there's still a workaround. Follow the instructions at my handbook: https://maxft.gitlab.io/mumble-docs/chapter_4/settings/shortcuts.html#global-keyboard-shortcuts

**Comment by Krzmbrzl** [comment]
@Max-FT could you please check whether #5688 addresses this issue in a suitable way?
The shortcuts should be disabled by default but you should be able to manually enable them again through the settings.

**Comment by Max-FT** [comment]
I fetched your PR and rebuilt. I don't see any option to re-enable the shortcuts menu.
![2022-05-21_11-05-1653151710](https://user-images.githubusercontent.com/59484023/169661407-47e3c5a5-235f-405b-8541-8411ae31e5ed.png)

**Comment by Krzmbrzl** [comment]
Are you sure that you actually fetched the changes from my PR? 'cause with those changes these settings shouldn't be disabled anymore (I completely deleted the code part responsible for deactivating the settings box)... :thinking: :eyes: 
I did miss a second code part in the backend though which would prevent the shortcuts from working. I fixed that now. Could you just try again and see if that was what was preventing you from using shortcuts?

**Comment by Krzmbrzl** [comment]
Ho - I just realized that we don't even seem to expose the setting that enabled/disables the shortcuts to the user. So with the default being off now, it seems there is indeed no way in the UI to turn them back on.
I'll have to add an option for that :eyes:

**Comment by Krzmbrzl** [comment]
@Max-FT long time no see (sorry for that). I have updated #5688 and now it should be possible for you to switch the shortcut engine on and off to your heart's content. The default should be off, if you're on Wayland but enabling it should be as simple as clicking on the checkbox in the `Shortcuts` settings page.
Could you test this and tell me whether it works as intended?

**Comment by Max-FT** [comment]
Thank you very much. I fetched your PR and it works!
