### ISSUE TITLE
Remove `python` as a dependency from `mumble-server` build

### ISSUE THREAD

**Issue by vitoyucepi** [mumble-voip/mumble#5459]
### Context

Is it really necessary to depend on `python` when building `mumble-server`?

### Description

https://github.com/mumble-voip/mumble/blob/8505df958fc16a6f3ad902d84aed415742c5bb20/src/murmur/CMakeLists.txt#L16
depends on python because of

https://github.com/mumble-voip/mumble/blob/8505df958fc16a6f3ad902d84aed415742c5bb20/cmake/qt-utils.cmake#L6 and https://github.com/mumble-voip/mumble/blob/8505df958fc16a6f3ad902d84aed415742c5bb20/cmake/qt-utils.cmake#L93-L135

I removed this part in my custom server build, because it's only used to build client.

### Mumble component

Server

### OS-specific?

No

### Additional information

1. Do I need any `3rdparty` libraries to build the server?
2. New release artifacts from `1.4.230` has new strange directory name `/mumble-1.4.230.src` unlike `1.3.4` which has `/mumble-1.3.4`.

**Comment by vitoyucepi** [comment]
@Krzmbrzl 

1. Do I need any `3rdparty` libraries to build the server?
1. Is it possible to hide `python` behind a feature flag?
   For example if I build server without `ICE` support then I don't need `python`, right?
1. Does `cmake` built-in `FindPythonInterp.cmake` module has a fatal flaw?
1. What about strange name `/mumble-1.4.230.src`?

**Comment by Krzmbrzl** [comment]
1. Yes. From a quick lookup you'll at least need `arc4random` and `FindPythonInterpreter` (if you are building from current master, you'll also need `tracy`). If you have `zeroconf` enabled, you'll also need `qqbonjour`
2. As far as I can tell that's already the case
3. Yes - see the README in https://github.com/Krzmbrzl/FindPythonInterpreter
4. What about it? That just seems to be the name that Davide has chosen. It shouldn't have any further implications :eyes:

**Comment by vitoyucepi** [comment]
> 1.

I tried to build from [automatic github artifact](https://github.com/mumble-voip/mumble/archive/refs/tags/v1.4.230.tar.gz). It has no submodules, for example `FindPythonInterpreter`. So I just patched it out of `CMakeLists.txt`.

> 2. As far as I can tell that's already the case

So there's no need to include `FindPythonInterpreter` in global scope of server `CMakeLists.txt`.

> 4.

https://github.com/mumble-voip/mumble/releases/download/v1.4.230/mumble-1.4.230.tar.gz
vs
https://github.com/mumble-voip/mumble/archive/refs/tags/v1.4.230.tar.gz
I'd prefer dir names to be the same.

**Comment by Krzmbrzl** [comment]
> I tried to build from automatic github artifact. It has no submodules, for example FindPythonInterpreter. So I just patched it out of CMakeLists.txt.

So I was told - that means that we don't support building from the automatic source artifacts generated by GitHub :eyes: 

> So there's no need to include FindPythonInterpreter in global scope of server CMakeLists.txt.

Technically not, but starting to engineer at this point doesn't seem to be worth it. Generally we don't support building without submodules, even though in this case it seems like it might actually be possible :shrug:
