### ISSUE TITLE
Mumble Client 1.4.230 looses CR/LF when pasting Clipboard to Channel

### ISSUE THREAD

**Issue by Karybdus** [mumble-voip/mumble#5460]
### Description

When Pasting Clipboard to a Channel (in the left Area - Send message to Channel) it will be only a Floating Text,
if i post it directly to the user it will keept it CR/LF 
if i post it via right-mouse-button on the Channel send message it will keep it also

### Steps to reproduce

Windows Client 1.4.230

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Are you explicitly referring to Windows-style newlines (CRLF) instead of Unix ones (LF) or is your issue that no line breaks are inserted in your message? In case of the latter: that'd be a duplicate of https://github.com/mumble-voip/mumble/issues/5445

**Comment by udgithub** [comment]
I have the same problem on Windows 10. It's reproducable. Pasting text with newlines behaves different. Newlines vanish when sending by using the huge field (send to channel). They don't dissappear if I use the context menu "send to channel" / "send to user".

**Comment by Krzmbrzl** [comment]
That's the new markdown feature in action. On Markdown you have to use two consecutive newlines to create an actual newline in the sent message. A single newline will be ignored.

**Comment by udgithub** [comment]
Thanks for the clarification. And why does the system behave in 2 different ways? Does only the huge field for channel notifications support Markup ?

**Comment by chinese-soup** [comment]
> That's the new markdown feature in action. On Markdown you have to use two consecutive newlines to create an actual newline in the sent message. A single newline will be ignored.

So now instead of just pasting a text with newlines in it, I have to manually make two new newlines between them before sending? How is that a feature and not a bug, changing something that has been a default behaviour for 10+ years surely isn't the way to go, is it?

**Comment by Krzmbrzl** [comment]
Go file that "bug" against the Markdown spec then.

If you want to send text literally, you can always wrap it in a code block using triple backticks. In there your line breaks are sent as-is.

**Comment by chinese-soup** [comment]
I mean a toggle to disable client-side Markdown parsing isn't really a bug to file against the Markdown spec, is it? Changing the default behavior of something and not introducing an option to change the behavior (again, that's been there for 10+ years) back to the original one is the ```"""""```bug```""""""``` here.
