### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [mumble-voip/mumble#5471]
Dear @mumble-voip team,

In first, I wish you a Happy New Year.

It will be nice to remove old parts like:
- https://sourceforge.net/p/mumble/news/
- https://sourceforge.net/p/mumble/_list/tickets
- https://sourceforge.net/p/mumble/bugs/
- https://sourceforge.net/p/mumble/feature-requests/
- https://sourceforge.net/p/mumble/patches/
- https://sourceforge.net/p/mumble/discussion/
- https://sourceforge.net/p/mumble/discussion/492606/
- https://sourceforge.net/p/mumble/discussion/492607/
- https://sourceforge.net/p/mumble/mailman/
- https://sourceforge.net/p/mumble/mailman/mumble-packaging/
- https://sourceforge.net/p/mumble/mailman/mumble-translations/

To remove the old not updated: http://mumble.sourceforge.net/ and use only https://www.mumble.info/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/mumble/

To disable/delete tabs, go here: https://sourceforge.net/projects/mumble/
To add a new tab, go here: https://sourceforge.net/projects/mumble/
To change informations, go here: https://sourceforge.net/p/mumble/admin/overview
To export, go here: https://sourceforge.net/p/mumble/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/mumble/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/mumble/admin/overview
- A new tab, go here: https://sourceforge.net/projects/mumble/

Remove the false Twitter and Facebook links: https://sourceforge.net/p/mumble/admin/overview

The support page will be updated: https://sourceforge.net/projects/mumble/support

Thanks in advance.

**Comment by Krzmbrzl** [comment]
I have to check if we still have someone around who has administrative access to that page...

**Comment by Krzmbrzl** [comment]
Alright as I have been told, @hacst might be be our only chance here.

**Comment by Neustradamus** [comment]
@Krzmbrzl: Thanks for your replies!
- https://sourceforge.net/p/mumble/_members/

**Comment by Krzmbrzl** [comment]
Ah it seems @Kissaki should also have access.

**Comment by Kissaki** [comment]
Yes, I do have access there

**Comment by Krzmbrzl** [comment]
@Kissaki could you then take care of archiving the project on SourceForge, please?

**Comment by Kissaki** [comment]
Yeah, I’ll take a look in the coming days

**Comment by Neustradamus** [comment]
@Kissaki (or others): Please do all specified steps that I have noted.

Note: You can create an export before.

Thanks in advance.

**Comment by Kissaki** [comment]
The wiki content is process of being migrated to our website as documentation.

This has already happened for some unproblematic content. Some content is problematic licensing wise as history or at least authorship/copyright holders have to be retained.

See target https://www.mumble.info/documentation/

**Comment by Kissaki** [comment]
I removed the ticket trackers, forums, and mailing lists (privating hides the menu item).

I made sense to keep the stuff for a while, but I agree it’s outdated now and even as an archive is not worth it any more; does more harm than good.

I also found the project moved setting which puts the banner on there.

I also removed links to twitter and facebook, which were still set there.

The files menu item seemingly can not be removed or hidden. There is a GitHub integration available, which I assume would map/mirror GitHub releases to Sourceforge too. Something that may be worthwhile for us to consider. Especially since I don’t feel like the 'project moved' banner is big or prominent enough for every user to notice.

**Comment by Kissaki** [comment]
I update the redirect configuration for SF web too to improve the redirect targets of `http://mumble.sourceforge.net/` and `https://mumble.sourceforge.io/`.

**Comment by Neustradamus** [comment]
@Kissaki: Excellent, thanks! :)

In more, you can add tabs:
- to https://github.com/mumble-voip
- to https://mumble.info/
- to https://forums.mumble.info/

Have you looked to drop the www?

**Comment by Kissaki** [comment]
> Have you looked to drop the www?

What do you mean?

**Comment by Neustradamus** [comment]
@Kissaki: Please read here: https://github.com/mumble-voip/mumble/issues/5471#issuecomment-1017286966 ^^

**Comment by Kissaki** [comment]
We will not drop www.

Despite what the linked website says, there are (caching configuration) reasons why www (or any subdomain) should be preferred over using none.
