### ISSUE TITLE
Internet links with protocoltype mumble:// not working

### ISSUE THREAD

**Issue by back2live** [mumble-voip/mumble#5473]
### Description

After installation of Mumble on Windows the Internetshortcuts with mumble://my.url.to are not working

### Steps to reproduce

1. create a new shortcut with die destination to your mumbleserver for example mumble://my.url.to 
2. windows cant resolve mumble:// /protocoll "mumble" ist not linked to any Program"

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

![mumble](https://user-images.githubusercontent.com/1230213/150101101-7c9426ac-5d12-49d0-b8e1-e1996b354d71.png)

**Comment by Krzmbrzl** [comment]
We probably have to explicitly register ourselves as handler for that protocol when running the installer

**Comment by crazydisi** [comment]
Version 1.3.4 did the correct Registry entry the current versions seems to miss out on that one.

here is the export of the registry which is needed to make this functional again (default installation):

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\mumble]
@="URL:Mumble"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\mumble\DefaultIcon]
@="C:\\Program Files\\Mumble\\client\\mumble.exe"

[HKEY_CLASSES_ROOT\mumble\shell]

[HKEY_CLASSES_ROOT\mumble\shell\open]

[HKEY_CLASSES_ROOT\mumble\shell\open\command]
@="C:\\Program Files\\Mumble\\client\\mumble.exe \"%1\""
```

**Comment by magneticflux-** [comment]
Looks like the installer used to be configured to register it here:
https://github.com/mumble-voip/mumble/blob/e799cc320d5b110e8eaf55b999531d75d87174fd/installer/Files.wxs#L106-L109

That file was removed by https://github.com/mumble-voip/mumble/commit/88e17868493b7e08fe3339069c11cbc5c39e62e5. It seems like WixSharp should have some kind of analogue for the registry value addition.

**Comment by Krzmbrzl** [comment]
Yes, the installer has been completely rewritten in WixSharp and I am sure there is a way to set this association within WixSharp as well - we simply forgot to do it.
Thanks for digging out the required configs, though.
