### ISSUE TITLE
[1.3.4] Microphone doesn't work and no input devices are visible

### ISSUE THREAD

**Issue by mikebdp2** [mumble-voip/mumble#5475]
### Description

I'm using [PostmarketOS](https://postmarketos.org/) which is based on Alpine Linux: it provides **[Mumble v1.3.4](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/mumble)** ARM aarch64 package built with these options:

- **[APKBUILD](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/APKBUILD)**
- [murmur.initd](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/murmur.initd)
- [murmur.pre-install](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/murmur.pre-install)

When I'm trying to set up sound at Mumble, it fails to find any microphone - despite that a mic is available for phone calls or the apps like Gnome Sound Recorder. At Mumble sound settings, I only see these devices - which seem to be the output-only ones:

```
ALSA:
[sysdefault:CARD=PinePhone] PinePhone, 1c22c00.dai-sun8i-codec-aif1 sun8i-codec-aif1-0 Default Audio Device
[default] Default ALSA Output (currently PulseAudio Sound Server)
[null] Discard all samples (playback) or generate zero samples (capture)
[pulse] PulseAudio Sound Server
OSS:
--- no devices available ---
```

I've already installed/enabled the ALSA packages [from this page](https://wiki.alpinelinux.org/wiki/ALSA), but don't know what to do next. Please, could you suggest how to debug this situation?

**P.S.** Somehow a Mumble worked for me once when I was on a previous pmOS version - which confirms that Mumble really can work on this hardware. But then it broke, and I can't reproduce this successful result even with a full pmOS reinstallation.

### Steps to reproduce

1. Get a Pinephone
2. Install Mumble as a great opensource VoIP alternative
3. Open the Audio Settings and see - there are no input devices

### Mumble

1.3.4 Client for Linux

**Comment by Krzmbrzl** [comment]
Did you try a different audio Backend yet? E.g. PulseAudio or PipeWire?

**Comment by mikebdp2** [comment]
@Krzmbrzl Thank you very much for your kind & such a fast reply!
> Did you try a different audio Backend yet? E.g. PulseAudio or PipeWire?

It seems that I already have a PulseAudio installed, judging by the output of `sudo apk list pipewire` command:
> pipewire-0.3.43-r1 aarch64 {pipewire} (LGPL-2.1-or-later)

However, Mumble is showing only ALSA and OSS at its' dropdown options at Audio settings

**Comment by Krzmbrzl** [comment]
Uhm - I have to admit that I am not entirely sure how Mumble determines which backends are available :thinking: 
@davidebeatrici might know more on that topic, though.

**Comment by Krzmbrzl** [comment]
From #5506 it seems that with 1.4 the microphone is found. Is that correct?
