### ISSUE TITLE
Is version 1.4 released for the Raspberry PI?

### ISSUE THREAD

**Issue by hindsa-nabeel** [mumble-voip/mumble#5476]
### Context

Hello,
Is there a version (1.4) for the Raspberry PI, If so, where can I download it?
Regards.

### Description

Release 1.4 server for the Raspberry PI

### Mumble component

Server

### OS-specific?

Yes

### Additional information

Raspberry PI (Debian) based/ARM

**Comment by Krzmbrzl** [comment]
We are not in charge of packaging for the Raspi and we currently don't provide packages for Linux distributions for direct download either. You'll have to wait until the package maintainer of your chosen distribution to update the package.

**Comment by Krzmbrzl** [comment]
Or, in the meantime, you could self-compile Mumble by following our [build instructions](https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions)
