### ISSUE TITLE
Mumble PPA doesn't contain version 1.4.0

### ISSUE THREAD

**Issue by Boehrsi** [mumble-voip/mumble#5484]
### The issue

I'm using the Mumble server on my Ubuntu 20.04 server and checked if the PPA repository provides an update to version 1.4.0, but it seems the repository isn't updated yet.

**How to reproduce:**

- Follow the instructions in the wiki https://wiki.mumble.info/wiki/Installing_Mumble
- Add the PPA https://launchpad.net/~mumble/+archive/ubuntu/release
- Install Mumble
- The delivered version is 1.3.4-1

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

**Comment by skobkin** [comment]
Currently static server build option is broken, so maybe they're planning to fix it and then populate all Linux server packages at once.

So I've used Docker image which is building murmur from the source and linking dynamically for my server. You can temporarily use it too: [`skobkin/murmur`](https://hub.docker.com/r/skobkin/murmur) ([source](https://gitlab.com/skobkin/docker-murmur)) or from [Gitlab Container Registry](https://gitlab.com/skobkin/docker-murmur/container_registry).

The only caveat is that in my image ICE and DBus are disabled. But you can easily modify the `Dockerfile` to bring them back if you need them.

**Comment by Krzmbrzl** [comment]
> Currently static server build option is broken, so maybe they're planning to fix it and then populate all Linux server packages at once.

Nah, that's not it. The main reason is that our PPA system is super, super ugly and we only barely understand it ourselves at this point xD

Plus the scripts used to publish the PPA packages (see https://github.com/mumble-voip/mumble-ubuntu-ppa) don't work with 1.4 and we don't have means to create native Linux packages with the new build system (cmake) yet. Thus, it is currently not possible for us to populate our PPA.

I started working on packaging but didn't get to finish it yet: https://github.com/mumble-voip/mumble/pull/5006

_I'll transfer this issue to our PPA repo_

**Comment by Krzmbrzl** [comment]
As for some reason I can't transfer this issue to our PPA repo, I'll close this issue here and create a new one over there and reference it to this one...

**Comment by Boehrsi** [comment]
> As for some reason I can't transfer this issue to our PPA repo, I'll close this issue here and create a new one over there and reference it to this one...

Thanks for moving it over there and sorry that I haven't created it there initially. Wasn't aware that there is a dedicated repo for the PPA.

**Comment by Krzmbrzl** [comment]
No problem - apparently not even GitHub is aware of this repo since it told me it doesn't exist when I wanted to transfer the issue :joy:
