### ISSUE TITLE
[Regression] Server built for Linux with gRPC support crashes on start with segfault

### ISSUE THREAD

**Issue by Fereffe** [mumble-voip/mumble#5492]
### Description

Building the master branch on Ubuntu Server 20.04.3 with gRPC support enabled causes mumble-server to crash on launch with segmentation fault (core dumped).

Using the same build environment and the same flags, the 1.4.x branch works without issues.

Build flags:
`-Dclient=OFF -Dserver=ON -Dpackaging=ON -Dgrpc=ON -Ddbus=OFF -Dice=OFF -Dcrash-report=OFF -Dgkey=OFF -Doverlay=OFF -Doverlay-xcompile=OFF -DBUILD_NUMBER=230`

### Steps to reproduce

- Build master and 1.4.x branches on Ubuntu Server 20.04.3, gRPC 1.43.0, protobuf 3.18.1
- Launch mumble-server directly from build dir with: `./mumble-server`
- master branch build will crash with `segmentation fault (core dumped)`, the 1.4.x build will work without issues

### Mumble version

1.4.230

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by botanegg** [comment]
Not reproduced on Archlinux from master
<details>
<summary>Part of cmake output</summary>
```
-- ##################################################
-- Mumble version:          1.5.230
-- Architecture:            x64
-- Build type:              Release
-- Using LTO:               ON
-- ##################################################
-- Qt5 component found: Core | Version: 5.15.2
-- Qt5 component found: Network | Version: 5.15.2
-- Qt5 component found: Xml | Version: 5.15.2
-- OpenSSL component found: Crypto | Version: 1.1.1m
-- OpenSSL component found: SSL | Version: 1.1.1m
-- Protobuf found | Version: 3.19.2
-- Found Threads: TRUE  
-- TRACY_ENABLE: OFF
...skip some tracy variables...
-- Qt5 component found: Sql | Version: 5.15.2
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found c-ares: /usr/lib64/cmake/c-ares/c-ares-config.cmake (found version "1.18.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Found RE2 via pkg-config.
-- gRPC found | Version: 1.43.0
```
</details>

**Comment by Krzmbrzl** [comment]
Note also that the gRPC feature is completely unmaintained and we don't recommend anyone to use it.

**Comment by Krzmbrzl** [comment]
Could you compile Mumble in Debug mode and then start the server through gdb and provide a backtrace of the segfault?

**Comment by Fereffe** [comment]
I'd like to try rebuild with a more up to date version of Qt, since the one used was 5.12.8 and I've seen from botanegg's log he used 5.15.2.

It's a shame the gRPC feature is unmaintained, I find it useful. Are the future plans to only use ICE?

**Comment by Krzmbrzl** [comment]
No concrete plans yet, but I am strongly considering to remove gRPC support completely since in its current state it mainly causes trouble.
In the long run I think it would be beneficial to completely rewrite the RPC Backend in order to streamline the implementation and at the same time provide multiple Backend alternatives.

But as I said: no concrete plans yet

**Comment by Fereffe** [comment]
Ok, after updating everything, the issue was not due to outdated libs.

- If I build the master branch as-it-is, mumble-server launches correctly.
- If I checkout to commit 8505df9, which should be the one used for 1.4.230, mumble-server segfaults.

Should I close this bug report?

PS: Yeah, multiple backends would be nice.

**Comment by Krzmbrzl** [comment]
> Should I close this bug report?

either that or provide a backtrace so we could have a quick look at the cause

**Comment by botanegg** [comment]
will try to check it on clean ubuntu 20.04.3 today

**Comment by botanegg** [comment]
Ok, after clean install i run commands from Dockerfile (apt-get for deps, and build commands with @Fereffe parameters)  
Build was clean. Running ./mumble-server did not causing any segfaults

**Comment by Fereffe** [comment]
@botanegg did you try the exact same commit as the one used for the 1.4.230 release or did you build the master branch directly (1.5.x)?

**Comment by botanegg** [comment]
Oh, sorry, will check again from 8505df9

**Comment by Fereffe** [comment]
Thanks for the feedback!

I'll retry from `8505df9` when I have a bit of time. 
Meanwhile, I'll close this report since the bug is probably caused by my building environment.
