### ISSUE TITLE
Minimal View causes everything to disappear

### ISSUE THREAD

**Issue by mikebdp2** [mumble-voip/mumble#5495]
### Description

If I click **"Configure --> Minimal View"**, all the UI elements disappear and I get a completely blank window.
This is on Pinephone - so a smaller screen the usual. `rm -rf ./.config/Mumble` is required to get back to normal

### Mumble version & environment

1.4.230 Client at Alpine Linux - based PostmarketOS on Pinephone

**Comment by Krzmbrzl** [comment]
Indeed - I can reproduce on my machine (KDE Neon (aka Ubuntu 20.04) on a regular desktop).

**Comment by Krzmbrzl** [comment]
I am somewhat certain that this used to work in the not too distant past as I remember triggering it by accident at some point. A `git bisect` should probably produce the commit that introduced the issue

**Comment by Krzmbrzl** [comment]
I've went back as far as 54e313481d2fe2fe36fbd30f55c5f055cbbee615 and the issue persists. I have the feeling that this is actually related to a change within Qt that breaks the process we are currently relying on to create the minimal view.

**Comment by Hartmnt** [comment]
Is this actually a bug? When not connected to a server "minimal view" will only show an empty window. However right-clicking creates a context menu with the main menu options added. This can be used to turn off "minimal view".
Or maybe the bug is, that the chat log is not displayed in some circumstances? Or is this intended behavior?

If this is not a bug after all, maybe a label with some info about minimal view should be displayed when unconnected.

**Comment by Krzmbrzl** [comment]
I am not entirely sure how the minimal view is intended to function in detail... Iirc the respective commits never bothered to explain in detail 🤷

**Comment by Hartmnt** [comment]
[these](https://forums.mumble.info/topic/2096-mumble-window-not-showing-properly/) [posts](https://forums.mumble.info/topic/720-toggle-log-and-chatbar-in-minimal-view/) indicate that this is all intended (and also slightly undocumented) behavior.

So I would consider this bug not-a-bug or a usability/ux feature request for a label which explains minimal view when not connected to a server.

**Comment by Krzmbrzl** [comment]
I'm currently wondering whether minimal view even makes sense when not connected to a server. I would argue that it doesn't...
