### ISSUE TITLE
FindPythonInterpreter.cmake missing in repository

### ISSUE THREAD

**Issue by FlyveHest** [mumble-voip/mumble#5498]
### Description

Can not run CMake on source from release

### Steps to reproduce

1. Download and unpack source from release (https://github.com/mumble-voip/mumble/archive/refs/tags/v1.4.230.tar.gz)
2. Run `cmake -Dclient=OFF .`
3. Error

### Mumble version

1.4.230

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

CMake fails with the following error

```
CMake Error at cmake/qt-utils.cmake:6 (include):
  include could not find load file:

    FindPythonInterpreter
Call Stack (most recent call first):
  src/murmur/CMakeLists.txt:16 (include)
```

I downloaded the file from https://raw.githubusercontent.com/Krzmbrzl/FindPythonInterpreter/main/FindPythonInterpreter.cmake and placed it in `cmake/FindModules` and then cmake could run, and I can build the server.

**Comment by Krzmbrzl** [comment]
Run `git submodule update --init` - that initializes all submodules (see also our build documentation)

**Comment by Krzmbrzl** [comment]
Oh I see you downloaded the source ball: As I have been told, these don't contain the submodules. For that reason we don't actually support building in that way, since we require our submodules, which (I guess) can only be initialized if you have proerply cloned the repo via git.

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/releases/download/v1.4.230/mumble-1.4.230.tar.gz

**Comment by FlyveHest** [comment]
> https://github.com/mumble-voip/mumble/releases/download/v1.4.230/mumble-1.4.230.tar.gz

That doesn't contain the FindPythonInterpreter either.

The reason I am looking for a complete source download is to avoid having to clone the repository, as my build process is in a Docker environment and getting keys in there is somewhat of a hassle.

I don't think GIT supports modules via https, but I might remember wrong.

**Comment by Krzmbrzl** [comment]
> getting keys in there is somewhat of a hassle.

What keys? You shouldn't need any keys to clone this repo and its submodules afaik.

**Comment by FlyveHest** [comment]
You can't anonymously clone from Github via SSH

```
root@d93b162f3da2:/# git clone git@github.com:mumble-voip/mumble.git
Cloning into 'mumble'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

But, I can see that you have defined the submodules via https, so I think it should work a https checkout, and yes, that does work, sorry for the inconvenience. :)

**Comment by Krzmbrzl** [comment]
I barely ever clone a repo via SSH - https is always the way to go for me ^^
Glad to hear that it's working now :+1:
