### ISSUE TITLE
[1.4.230] Unlike 1.3.4, the right scrollbar at Settings isn't accessible on a small screen

### ISSUE THREAD

**Issue by mikebdp2** [mumble-voip/mumble#5507]
### Description

This is related to https://github.com/mumble-voip/mumble/issues/5425 and https://github.com/mumble-voip/mumble/issues/5426 . UI became more extended horizontally in 1.4.230 than in 1.3.4: and, with a lack of horizontal wrapping of UI elements, now the right scrollbar stopped being accessible on a small screen of Pinephone. Unfortunately, moving a horizontal scrollbar to the right - doesn't help to reach the right scrollbar.

### Mumble version & environment

I'm using [PostmarketOS](https://postmarketos.org/) which is based on Alpine **Linux**: it provides **[Mumble v1.4.230](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/mumble)** ARM aarch64 **Client** package built with these options:

- **[APKBUILD](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/APKBUILD)**
- [murmur.initd](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/murmur.initd)
- [murmur.pre-install](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/murmur.pre-install)
- [libgen.patch](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/libgen.patch)
- [no-rnnoise.patch](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/no-rnnoise.patch)
- [poll.patch](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/poll.patch)

**Comment by Krzmbrzl** [comment]
That's not _related_ to the mentioned issues, I would say that this is a (pretty close) willigte of these
