### ISSUE TITLE
Provide official images on dockerhub

### ISSUE THREAD

**Issue by J0s3f** [mumble-voip/mumble#5510]
### Context

Setting up a server using Docker and keeping it up to date

### Description

The repo contains a dockerfile which works great. But building this file takes time and uses resources everytime.
Murmur itself doesn't need very much resources and runs also on weaker systems (e.g. cheap vServer or ARM SBC) where compiling it takes significant time.
It would be great, if there could be official dockerimages on dockerhub.

Apart from just building all releases, there should also be some additional tags  for major versions. e.g not only have a v1.4.230 tag but also v1.4 so a server administrator can use this and get minor updates on each `docker-compose pull` or similar command.

There are some people putting builds of the Dockerfile from this repo on dockerhub already, but as a server administrator I don't feel comfortable just pulling some random persons image. Pulling an official image on the other hand would just require the same level of trust in the mumble developers as pulling this repo and building it.

Docker has a open source program which might even allow to [build and upload the images for free on their infrastructure](https://docs.docker.com/docker-hub/builds/), if I understand it correctly.

### Mumble component

Server

### OS-specific?

Yes

**Comment by botanegg** [comment]
Seems like some work was made in https://github.com/mumble-voip/mumble-docker but it is base on mumble-server-static releases witch is dropped https://github.com/mumble-voip/mumble/issues/5453#issuecomment-1015133736

I can suggest next `APKBUILD` for alpine to build mumble-server directly from source code (from github releases) for alpine

```
pkgname=mumble-server
pkgver=1.4.230
pkgrel=0
pkgdesc="Mumble-server"
url="https://www.mumble.info/"
arch="all"
options="!check" # No test suite.
source="https://github.com/mumble-voip/mumble/releases/download/v$pkgver/mumble-$pkgver.tar.gz"
depends=""
makedepends="cmake qt5-qtbase-dev protobuf-dev libcap-dev boost-dev"

build() {
	cd mumble-$pkgver.src
	mkdir -p build
	cd build
	cmake --install-prefix "$pkgdir/usr" -DCMAKE_BUILD_TYPE=Release -Dclient=OFF -Dzeroconf=OFF -Ddbus=OFF -Dgrpc=OFF -Dice=OFF ..
	cmake --build . --parallel $(nproc) --target mumble-server
}

package() {
	cd src/mumble-$pkgver.src/build
	cmake --install . --prefix "$pkgdir/usr" -v --component mumble_server --strip
}

sha512sums="6cffc7a95d88b33876f4093b99266468210f5c14f190fbd2fbe4991bef91a567e55296e7c8c6cc99e19c054853211085cc3cc08109e367e6776afb70766b3a53  mumble-1.4.230.tar.gz"

```

**Comment by Krzmbrzl** [comment]
We are already in the process of establishing a Docker infrastructure.

@azlux is in charge of that at https://github.com/mumble-voip/mumble-docker
