### ISSUE TITLE
Overlay not working on Valheim.

### ISSUE THREAD

**Issue by Redd181** [mumble-voip/mumble#5511]
### The issue

Mumble overlay will not work on Valheim at all. I feel at this point I've done every possible thing imaginable. 

### Mumble version

1.4.230

### Mumble component

I don't know

### OS

Windows

**Comment by Krzmbrzl** [comment]
Does Valheim happen to use BattleEye?

**Comment by Redd181** [comment]
> 

It does not, no.

**Comment by Krzmbrzl** [comment]
Maybe a different Anti-Cheat software?

**Comment by Kissaki** [comment]
I just tested and it works fine in the main menu for me when not launching with Vulkan.

Are you launching it with Vulkan?

**Comment by Redd181** [comment]
It has worked on and off just by pressing random buttons/enabling/disabling random things. It makes no sense to me.

**Comment by Kissaki** [comment]
Please answer my question.
