### ISSUE TITLE
Mumble Launcher Error -3 

### ISSUE THREAD

**Issue by Beureguard** [mumble-voip/mumble#5512]
### Description

After installing the updated version and uninstalling the old I keep getting this error
FAiled to load mumble_app.dll

### Steps to reproduce

uninstalled old version.
installed new version using wizard
tried to launch
errors out

### Mumble version

Mumble 1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by davidebeatrici** [comment]
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

**Comment by PetukhovArt** [comment]
hello , i have the same trouble . 
for some reasons i don't see mumble in HKEY 
![reg](https://user-images.githubusercontent.com/50843331/150670469-f500b539-2ef3-43df-8952-6cd04d6a5d76.PNG)
![Снимок](https://user-images.githubusercontent.com/50843331/150670470-b2550d71-82b8-4f82-ad47-bf18ff473641.PNG)

**Comment by Krzmbrzl** [comment]
What Davide wanted to say: Please verify that you have the latest VC Redistributable installed (seehis link).

@PetukhovArt if Mumble fails to load, how should it create an entry in the registry?

**Comment by Alcolawl** [comment]
Just had this issue pop up on a sibling's computer. Fresh install of Windows 10, installed the proper VC Redistributables and the error still occurs. I had the user install Mumble 1.3.4 and they were able to successfully launch the program and join the server.

**Comment by davidebeatrici** [comment]
Could you check whether there are unsatisfied dependencies for `mumble_app.dll` using [Dependencies](https://github.com/lucasg/Dependencies)?

**Comment by vitoyucepi** [comment]
Just come here to say that I used `winget` to download `vcredist`.
Maybe not all `vcredist` packages are equal.

Commands that work for me:
- `winget install -e --id Microsoft.VC++2015-2022Redist-x64`.
- `choco install vcredist140`

I think this could be tested with official windows 10 VM images.

**Comment by davidebeatrici** [comment]
https://github.com/abbodi1406/vcredist

**Comment by Rovanion** [comment]
Following Davids advice of installing [VC Redist](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) solved the problem for me.

**Comment by Krzmbrzl** [comment]
Closing in favor of #5549
