### ISSUE TITLE
[OL8] Error on installing murmur with DNF

### ISSUE THREAD

**Issue by johnwick1** [mumble-voip/mumble#5520]
### Description

Hello guys,

I encounter an error when i try to install murmur from Oracle Linux 8, this is the result:

`dnf install murmur
Last metadata expiration check: 0:19:21 ago on Tue 25 Jan 2022 04:24:49 PM CET.
Error:
 Problem: conflicting requests
  - nothing provides libdns_sd.so.1()(64bit) needed by murmur-1.3.4-4.el8.x86_64
`
libdns_sd.so.1() seems to be missing

Anyone having the same issue or know how to fix this lib ?

Thanks

### Steps to reproduce

boot a fresh vm with Oracle Linux 8
dnf install murmur

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
We are not responsible for packaging Mumble for the various Linux distributions. Please contact the package maintainer about this.

From the error message it seems that your system is lacking a package that provides libdns - but since I'm not using Oracel Linux, I'm afraid I can't help :shrug:
