### ISSUE TITLE
[1.4.230]

### ISSUE THREAD

**Issue by MerreM** [mumble-voip/mumble#5527]
### Description

Two issues - no more text to speech when user joins channel.

Attempted to modify settings (Cannot read in the setting view what they all do) - cannot modiy column size

Instead left with "bo-up and bo-oh" noises whenever I key up and down - with no apparent way to stop it.

Reset to defaults didn't work.

Downgrading now.

### Steps to reproduce

Install 1.4.230 - Attempt to modify settings.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Haven't tried

**Comment by MerreM** [comment]
Might be a my mistake after downgrading saw a "Audio Cue" setting - in the main option that turned it off.

**Comment by MerreM** [comment]
Still be able to read the options would be nice!

**Comment by Krzmbrzl** [comment]
I'm not sure I understand your problem(s)... are you using Mumble on a device with a small screen which doesn't fit the settings window?

And TTS is now disabled by default, so if you want it, you'll have to enable it explicitly.

**Comment by MerreM** [comment]
Hey, so that was posted in a mild panic during a game session as I tried to play/debug with the "Misc > Audio Cue" settings enabled by accident.

I looked for the setting in the "Messages" tab - but couldn't find it - hence the down grade. "Restore defaults" in 1.4.230 didn't turn it off.

Whilst looking the in Settings > Messages tab I could not see the full title of the settings - I tried to resize the columns, could not, so panicked.

This morning I've re-upgraded and resized the window to see the settings names, but it wasn't my first thought.

I haven't yet worked out how to turn Text to speech back on for notifications, in Settings > Messages it appears to be enabled, but still no TTS.

**Comment by Krzmbrzl** [comment]
Okay, I see ^^

The setting for the mute cue is located in the `Audio Input` category at the bottom of the page.

In terms of TTS, I think in order to enable that, you'll have to use the checkbox in the `Configure` dropdown menu (in addition to whatever you configure in Mumble's actual settings)

**Comment by FlyveHest** [comment]
> In terms of TTS, I think in order to enable that, you'll have to use the checkbox in the Configure dropdown menu

I had this exact same problem, and this was the solution.  Not sure if the Text-to-speech option was in the configure prior, but upgrading to 1.4 either added it, or disabled it.

**Comment by Krzmbrzl** [comment]
It was there all along but the default has changed from bein enabled to being disabled.
