### ISSUE TITLE
`mumble://` links no longer work

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5534]
### Description

With 1.4.230 mumble links no longer seem to work.

### Steps to reproduce

1. Open a `mumble://` link

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

This was reported at https://www.reddit.com/r/mumble/comments/s9pid1/mumble_links_no_longer_work/

I just confirmed this for myself. Nothing happens for me when I click one (that I set up a long time ago and should still work).

**Comment by Krzmbrzl** [comment]
You're late to the party: https://github.com/mumble-voip/mumble/issues/5473
