### ISSUE TITLE
Empty "List of Users" in Whisper/Shout target

### ISSUE THREAD

**Issue by mungle** [mumble-voip/mumble#5537]
### The issue

Adding a Whisper/Shout shortcut, if I chose `Shout/Whisper to: List of users` the list is empty.
I don't know if is an issue or my app/server bad configuration.

What I want to achieve is push-to-talk to a specific user using a keyboard shortcut (one to one talk). Different shortcut will "call" a different user.

### Mumble version

1.4.230

### Mumble component

Client

### OS

macOS

### Additional information

My server is hosted on a Synology NAS using the 0.2.20-8 uMurmur package

**Comment by Krzmbrzl** [comment]
You can add users to the mentioned list. Not entirely sure what exactly your question is here 👀

**Comment by mungle** [comment]
Hi @Krzmbrzl, thank you for your reply. I can’t... otherwise, I would not disturb anyone here. My list is empty even if users are connected. I could share a screenshot, but it shows nothing more than empty fields…

**Comment by Krzmbrzl** [comment]
Presumably none of the users on the server are registered, correct? Iirc you can only configure shortcuts for registered users :thinking:

**Comment by mungle** [comment]
I wasn’t aware about this… I apologies… I can try next week.

**Comment by Krzmbrzl** [comment]
No worries - this system is not the most transparent thing in the world ^^
