### ISSUE TITLE
Update Ubuntu/Debian apt-Packgages to Latest version

### ISSUE THREAD

**Issue by hofq** [mumble-voip/mumble#5547]
### Context

on Ubuntu 21.04 / Debian 11 only Version 1.3.4-1 is availible. That is the Case for the Client and the Server.

### Description

It would be cool if you could update the Version, so that i can use the Latest Version without building it myself

### Mumble component

Both

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
We don't maintain these packages and as such don't have any influence on what what versions are available in the respective repositories. 

Please refer to your distribution's package manager about this.

**Comment by davidebeatrici** [comment]
@crknadle
