### ISSUE TITLE
mumble server missing qwave.dll on win server 2012r2

### ISSUE THREAD

**Issue by k1ttt-remote** [mumble-voip/mumble#5548]
### The issue

mumble server won't run.  produces error "The program can't start because qwave.dll is missing from your computer.  Try reinstalling the program to fix this problem".  i have reinstalled and then found issue 5284 from last fall about the same thing on server 2008, i am running server 2012r2 which is up to date and get the same error.

### Mumble version

1.4.230

### Mumble component

Server

### OS

Windows

### Additional information

server 2012r2 up to date on patches, had been running murmur 1.3.3 with no problems.

**Comment by Krzmbrzl** [comment]
Closely related: https://github.com/mumble-voip/mumble/issues/5548

Based on the findings in that issue, you should be able to install this as a separate "feature" . See e.g. https://imgur.com/a/RDS6J

**Comment by Krzmbrzl** [comment]
Note that if you also don't have the option to install the necessary feature, then I think this server version is also too old to be supported by us. After all its mainline EOL has been in 2018 already (see https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2012)

**Comment by k1ttt-remote** [comment]
ok, server 2012r2 has the proper feature and installing it worked to get cwave.dll.  i also needed to install the 2015-2022 vc runtimes as was required for the client from issue 5549:  https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by Krzmbrzl** [comment]
Perfect :+1:

Closing as _resolved_
