### ISSUE TITLE
Mumble overlay for linux x86_64 is not available

### ISSUE THREAD

**Issue by kingbeowulf** [mumble-voip/mumble#5562]
### Description

It is not clear from the cmake build instructions and options whether one can build just the x86_64 overlay without the 32-bit version. It appears from past Issues that 32-bit libraries are required to build any overlay on 64-bit Linux. With "overlay=[ON | OFF] you get either no overlay (OFF) or both arch overlays (ON).  "overlay-xcompile=NO" is ignored and seems superfluous.  The expectation is that a pure x86_64 with only a 64-bit overly should be possible and available.

For Slackware64 a 32-bit overlay should not be required.  Slackware64 does have a community maintained multilib add-on (unsupported by upstream), but this should not be a requirement for multtlib support.

### Steps to reproduce

cmake 
-Doverlay=ON"
-Doverlay-xcompile=OFF

...Can't find the 32-bit version of sys/cdefs.h ...

### Mumble version

1.4.230

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Slackware64 15.0 (no 32-bit multlib)
Mumble/Murmur package maintainer for Slackbuilds.org

### Relevant log output

```shell
Performing C++ SOURCE FILE Test COMPILER_HAS_MBIG_OBJ failed with the following output:
Change Dir: /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_40f85/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_40f85.dir/build.make CMakeFiles/cmTC_40f85.dir/build
gmake[1]: Entering directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_40f85.dir/src.cxx.o
/usr/bin/c++ -DCOMPILER_HAS_MBIG_OBJ  -O2 -fPIC  -fPIE   Wa,-mbig-obj -std=gnu++14 -o CMakeFiles/cmTC_40f85.dir/src.cxx.o -c /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp/src.cxx
c++: warning: Wa,-mbig-obj: linker input file unused because linking not done
c++: error: Wa,-mbig-obj: linker input file not found: No such file or directory
gmake[1]: *** [CMakeFiles/cmTC_40f85.dir/build.make:78: CMakeFiles/cmTC_40f85.dir/src.cxx.o] Error 1
gmake[1]: *** Deleting file 'CMakeFiles/cmTC_40f85.dir/src.cxx.o'
gmake[1]: Leaving directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_40f85/fast] Error 2


Source file was:
int main() { return 0; }
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_bd488/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_bd488.dir/build.make CMakeFiles/cmTC_bd488.dir/build
gmake[1]: Entering directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_bd488.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD  -O2 -fPIC  -fPIE -o CMakeFiles/cmTC_bd488.dir/src.c.o -c /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_bd488
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bd488.dir/link.txt --verbose=1
/usr/bin/cc -O2 -fPIC  CMakeFiles/cmTC_bd488.dir/src.c.o -o cmTC_bd488 
/usr/bin/ld: CMakeFiles/cmTC_bd488.dir/src.c.o: in function `main':
src.c:(.text.startup+0x15): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text.startup+0x1f): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text.startup+0x29): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text.startup+0x35): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_bd488.dir/build.make:99: cmTC_bd488] Error 1
gmake[1]: Leaving directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_bd488/fast] Error 2


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_87537/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_87537.dir/build.make CMakeFiles/cmTC_87537.dir/build
gmake[1]: Entering directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_87537.dir/CheckFunctionExists.c.o
/usr/bin/cc   -O2 -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE -o CMakeFiles/cmTC_87537.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.21/Modules/CheckFunctionExists.c
Linking C executable cmTC_87537
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_87537.dir/link.txt --verbose=1
/usr/bin/cc -O2 -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_87537.dir/CheckFunctionExists.c.o -o cmTC_87537  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_87537.dir/build.make:99: cmTC_87537] Error 1
gmake[1]: Leaving directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_87537/fast] Error 2



Determining if the include file sys/cdefs.h exists failed with the following output:
Change Dir: /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_0528f/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_0528f.dir/build.make CMakeFiles/cmTC_0528f.dir/build
gmake[1]: Entering directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0528f.dir/CheckIncludeFile.c.o
/usr/bin/cc   -O2 -fPIC -m32  -fPIE -o CMakeFiles/cmTC_0528f.dir/CheckIncludeFile.c.o -c /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
In file included from /usr/include/features.h:497,
                 from /usr/include/sys/cdefs.h:23,
                 from /tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:
/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
      |           ^~~~~~~~~~~~~~~~
compilation terminated.
gmake[1]: *** [CMakeFiles/cmTC_0528f.dir/build.make:78: CMakeFiles/cmTC_0528f.dir/CheckIncludeFile.c.o] Error 1
gmake[1]: Leaving directory '/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_0528f/fast] Error 2
```

**Comment by Krzmbrzl** [comment]
The overlay-xcompile option does always do what you'd expect on my system.

Could you show us your full cmake invocation?

**Comment by kingbeowulf** [comment]
here's the output on a pure x86_64, with script defaults [OVERLAY=${OVERLAY:-yes} and COMPAT32=${COMPAT32:-no} ]. 
`-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_MBIG_OBJ
-- Performing Test COMPILER_HAS_MBIG_OBJ - Failed
-- ##################################################
-- Mumble version:          1.4.0
-- Architecture:            x64
-- Build type:              Release
-- ##################################################
-- Qt5 component found: Core | Version: 5.15.3
-- Qt5 component found: Network | Version: 5.15.3
-- Qt5 component found: Xml | Version: 5.15.3
-- OpenSSL component found: Crypto | Version: 1.1.1m
-- OpenSSL component found: SSL | Version: 1.1.1m
-- Protobuf found | Version: 3.19.4
-- Qt5 component found: Concurrent | Version: 5.15.3
-- Qt5 component found: Sql | Version: 5.15.3
-- Qt5 component found: Svg | Version: 5.15.3
-- Qt5 component found: Widgets | Version: 5.15.3
-- Poco component not found: Zip
-- Regular Poco search failed - looking for Poco include dir manually...
-- Found Poco include dir at "/usr/include"
-- Found Poco Zip library at "/usr/lib64/libPocoZip.so"
-- sndfile found | Version: 1.0.31
-- X11 component found: Xext
-- X11 component found: Xi
-- opus found | Version: 1.3.1
-- Disabling warnings for targets: celt
-- speex found | Version: 1.2.0
-- speexdsp found | Version: 1.2.0
-- Disabling warnings for targets: rnnoise
-- speech-dispatcher found | Version: 0.10.2
-- Qt5 component found: DBus | Version: 5.15.3
-- Qt5 component found: LinguistTools | Version: 5.15.3
-- ALSA found
-- Looking for sys/cdefs.h
-- Looking for sys/cdefs.h - not found
CMake Error at overlay_gl/CMakeLists.txt:39 (message):
  Can't find the 32bit version of sys/cdefs.h - did you install g++-multilib?


-- Configuring incomplete, errors occurred!
See also "/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/SBo/mumble-1.4.230/build/CMakeFiles/CMakeError.log".
`

**Comment by kingbeowulf** [comment]
oh ffs.  had a typo in "$COMAPT32" = "no" stanza.  should be COMPAT32.  sigh.  It was defaulting to 'overlay-xcompile=ON'.  Compiling now with that off and overlay=on on Slackware64.  I'll have some lunch and then a nap.  report back later.

**Comment by kingbeowulf** [comment]
Sorry for the spam.  compiles fine on Slackware64 with '-Doverlay-xcompile=OFF'  Either new reading glasses or a larger monitor font size.

**Comment by Krzmbrzl** [comment]
Hehe ^^
Good to hear everything is working after all :+1:
