### ISSUE TITLE
Mumble server not starting up with -supw parameter

### ISSUE THREAD

**Issue by Amannda123** [mumble-voip/mumble#5569]
### Description

When adding the supw parameter via console, the server is not coming up.
Without its starting right away, but then i cant get admin access.

...or am i missing something here?

Thanks in advance for your help

### Steps to reproduce

1) open cmd or an elevated cmd
2) navigate to install directory
2) run mumble-server.exe -supw Password1! 

### Mumble version

1.4.230

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

### Additional information

Tested on two diffrent Machines (virtual and pyhsical)

### Relevant log output

```shell
None, since server is not starting up
```

**Comment by Krzmbrzl** [comment]
> ...or am i missing something here?

Yes - when using the `-supw` option the server only sets the SuperUser password and then exits. This is intended behavior. The password is stored in the DB afterwards, so starting the server without the `supw` option afterwards will have the desired effect.

So what you need are two calls:
1. Set SuperUser pw on your server (only required once)
2. Actually start the server (no `-supw`)

**Comment by Amannda123** [comment]
Ooooh...  sorry my bad, 
Its clearly written in the line below where i stopped reading... also it isn't like its marked in bold text
