### ISSUE TITLE
Positional audio Plugin not showing up on Mac osx

### ISSUE THREAD

**Issue by Cardboard-Friend** [mumble-voip/mumble#5571]
### The issue

When installing the latest version of mumble to use for positional audio in Minecraft the "Link" plugin is missing and positional audio doesn't work without it.

### Mumble version

1.4.0

### Mumble component

Client

### OS

macOS

**Comment by Krzmbrzl** [comment]
Did you check the actual installation directory or did you only check whether the Link plugin was listed inside Mumble's settings?

**Comment by Bruciemm** [comment]
I check both inside the mumble app and in the directory located in ~library/application support/mumble/mumble/plugins

**Comment by Bruciemm** [comment]
I have also tried deleting all the program files and cache files and doing a fresh install of mumble but to no avail.

**Comment by Krzmbrzl** [comment]
> I check both inside the mumble app and in the directory located in ~library/application support/mumble/mumble/plugins

And in none of these places was the plugin? Are there any other plugins that you found?

> also downloaded the source code and manually copied the plugin data from the source code to the plugin folder but still nothing.

Which plugin folder?

**Comment by Krzmbrzl** [comment]
Hm weird :thinking: 

And when you manually copied the plugin, where did you copy it to?

**Comment by Bruciemm** [comment]
I manually copied it to the plugin folder in the apps program files

**Comment by Bruciemm** [comment]
on older versions of mumble, the link plugin is shown in the app but doesn't work with other users on the latest version

**Comment by Krzmbrzl** [comment]
> I manually copied it to the plugin folder in the apps program files

Try to instead open Mumble and the go to Settings > Plugins > Install (at the bottom) and select the plugin library that way. I wonder what that'll do :eyes:

**Comment by Bruciemm** [comment]
also might be worth noting but when using older versions of mumble paired with the Minecraft mumble link mod for positional audio the linking doesn't automatically update when switching servers, It only works initially on the first server join which doesn't work out when trying to use it on a minigame server on which you change servers each game. when testing on windows there is no issues on both old and new versions of mumble.

**Comment by Krzmbrzl** [comment]
The file that you manually color earlier. Should be called `link.dylib`

As to the server switching issue: that should probably be reported to the Minecraft Link plugin Deva.

**Comment by Bruciemm** [comment]
the file doesnt seem to exist in the source code
<img width="761" alt="Screenshot 2022-02-14 at 15 00 39" src="https://user-images.githubusercontent.com/73123134/153937617-653b3db9-d932-4312-9e52-de9255b5fd48.png">

**Comment by Krzmbrzl** [comment]
What did you copy before? You can't copy anything from the source code. You'll have to compile the source code and thst will produce the binary I mentioned

**Comment by Bruciemm** [comment]
Is there not a way to make it work without compiling the source code? I'm not sure how to compile it correctly

**Comment by Krzmbrzl** [comment]
No it won't work without compiling. Normally it shouldn't be needed but for whatever reason it is. Maybe we have an issue with the script bundling our macOS binary (it might forget to include the plugin) 🤷

**Comment by Krzmbrzl** [comment]
Right - in there we wouldn't expect plugins anyway (not the default ones at least).

@davidebeatrici where should the default plugins be located on macOS? Are they also missing on your machine?

**Comment by davidebeatrici** [comment]
`/Applications/Mumble.app/Contents/Plugins`

Looks like the folder is empty in the release.

**Comment by filleduchaos** [comment]
Hello! I ran into this issue yesterday - I was able to just compile the plugin and put it in the correct folder myself, so that was alright, but also I could take a look at the macOS app bundler later this week/raise a PR

**Comment by Krzmbrzl** [comment]
> I could take a look at the macOS app bundler later this week/raise a PR

That would be much appreciated! :heart: 
The bundler sits at https://github.com/mumble-voip/mumble/blob/master/macx/scripts/osxdist.py. Note that we suspect that the issue might not even be the bundler itself but rather the signing script as presented in https://github.com/mumble-voip/mumble/pull/5428 (it unpacks the bundle, signs the files and then repacks it again). We suspect that maybe during the repack we lost the plugins, but weren't able to dig into this more, as of yet.

**Comment by Krzmbrzl** [comment]
@filleduchaos did you get any insights into this yet?

**Comment by Goofygooberyeah** [comment]
Can confirm still an issue ;( not sure if this happens for every mac user or just a select few. Hope to see fixes soon!

**Comment by blackxmat** [comment]
HI,I am on MacOS Catalina and Today I installed mumble version 1.4.230 and the issue is here and 
I want to know if you have a another solution because i can't compile the plugin and also i wanted to know if you found any solution for this issue.

**Comment by Krzmbrzl** [comment]
No progress on this, so far

**Comment by Krzmbrzl** [comment]
I found and fixed the issue causing this behavior. Starting with the next Mumble 1.4 release (coming soon-ish) the Link plugin should be bundled with the macOS release again.

**Comment by SuperStik** [comment]
bug still exists on 1.4.230, still no plugins
