### ISSUE TITLE
Cannot find ini file to edit to customize Murmur in 1.4.230

### ISSUE THREAD

**Issue by W7KHZ** [mumble-voip/mumble#5572]
### The issue

After downloading Mumble/Murmur for a new computer install, I cannot find the ini file to edit to customize the server. I have not been able to find any guidelines that would help a "simple" user set up this new version, if the ini file approach is no longer being used. What am I missing?

### Mumble version

1.4.230

### Mumble component

Server

### OS

Windows

**Comment by Krzmbrzl** [comment]
The INI file is still used. If you need to customize anything, just create the INI file with the respective options set by hand.

**Comment by W7KHZ** [comment]
OK. Since it is no longer created when the server program is newly installed, its likely this will be an opportunity for all of the online “how-to” guides that have been written to be updated. Just because I am a basic user, I would say that this is a significant change with this application. Unless this started happening during a 1.3 revision.  

-Mark-

**Comment by Krzmbrzl** [comment]
We don't have any (up-to-date) guides at this point anyway, which should be changed at some point anyway.

In the meantime, you can also copy the INI from https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini if you want.

**Comment by W7KHZ** [comment]
Thank you for the support. 

-Mark-

**Comment by klemkadiddlehopper** [comment]
https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini seems to be a bad link.

**Comment by Krzmbrzl** [comment]
Yeah, the file has been moved to https://github.com/mumble-voip/mumble/blob/master/auxiliary_files/mumble-server.ini

**Comment by craigthings** [comment]
Is there no longer an option to set the superuser password? Looking to just get something up and running for a LAN. Doesn't need to be weapons grade security.

**Comment by Krzmbrzl** [comment]
The SU password gets printed the first time a server boots. Afterwards you can set a custom SU password via the `-supw` CLI option at any time.
