### ISSUE TITLE
Upgrading to 1.4.230 is not consistent

### ISSUE THREAD

**Issue by W7KHZ** [mumble-voip/mumble#5573]
### Description

I have upgraded to 1.4.230 on several computers, but am now getting a failure on a Windows 10 computer that states a DLL isn't found and won't run. I have run System Restore (Windows 10) on this computer to get the previous version (1.3.4) restored and it is working fine. I have also uninstalled 1.3.4 and run the new version install on this computer and get the same missing dll error issue. For some reason, this computer and its configuration will not take this new install or upgrade. It is an 

HP 64 bit AMD A6-5400K 
running Windows 10 Home version 21H2
OS build19044.1466
Windows Feature Experience Pack 120.2212.3920.0

What am I missing here. Have never had an install issue with this computer related to Mumble/Murmur.

It does not appear to be impacting the Murmur server as it seems to start fine.

### Steps to reproduce

Installed new version and attempted to run.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Relevant log output

```shell
Error -3 Failed to load mumble_app.dll
```

**Comment by Krzmbrzl** [comment]
You might have to install the VC Redistributable package manually.

**Comment by W7KHZ** [comment]
OK. We will try and find that one and see what happens. In this one case for this one computer, it appears that the MSI download for the upgrade isnt working. Hope that information is helpful. 

-Mark-
