### ISSUE TITLE
Can't build mumble 1.4.230 on Ubuntu 20.04

### ISSUE THREAD

**Issue by androos** [mumble-voip/mumble#5574]
### The issue

Tried to compile on linux mint 20.3 which is basically ubuntu 20.04
'cmake ..' fails with this massage.
```
CMake Error at CMakeLists.txt:71 (find_pkg):
  Unknown CMake command "find_pkg".                                                                                                                                    



```
### Mumble version

1.4.230

### Mumble component

Client

### OS

Linux

**Comment by androos** [comment]
cmake --version
cmake version 3.22.2

**Comment by Krzmbrzl** [comment]
From what directory are you executing `cmake ..`?

**Comment by androos** [comment]
build in src/mumble

**Comment by androos** [comment]
I misunderstood the documentation, now it works.
