### ISSUE TITLE
Show game activity in comments

### ISSUE THREAD

**Issue by GameOneYT** [mumble-voip/mumble#5576]
### Description

Show game activity in comments (I think it can be done using plugins)

For example:
![image](https://user-images.githubusercontent.com/71568087/154229168-f39f705d-9942-4eaf-8b53-456aaf7983ad.png)

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
This should not be part of the main Mumble client as it is too specific and not everyone will want this (e.g. those that rather use a self-written comment and don't appreciate it, if that gets overwritten automatically).

If desired, this could be implemented as a plugin though. You only have to find a way to detect the start of a game and then use the plugin API to set a user's comment accordingly.
For more details on how to do this, I refer to https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/README.md
