### ISSUE TITLE
Is there a way to get the certificate without exporting?

### ISSUE THREAD

**Issue by Horuyuki** [mumble-voip/mumble#5578]
### The issue

I had mumble on windows 10 and running, after I messed with that and windows won't boot, I would want to recover the certificate that was used.

But since I can't boot it up I can't export the cert, the only way left is to find it in the file system.

I do have an img back up of the drive where I can access all the files, would it be possible to find the certificate stored somewhere?

### Mumble version

1.3.4

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
If you're lucky you'll find a certificate backup file in your home directory. 
Otherwise you'd have to access the registry to extract the certificate, but I'm not sure if it can be accessed without booting Windows :thinking:

**Comment by Horuyuki** [comment]
> If you're lucky you'll find a certificate backup file in your home directory. Otherwise you'd have to access the registry to extract the certificate, but I'm not sure if it can be accessed without booting Windows thinking

Is it possible to move the files and config of the old app onto a working windows and access it that way?

**Comment by Krzmbrzl** [comment]
Just place the backup cert into your new installation's home directory and when you start Mumble dor the first time, it should be imported automatically

**Comment by Krzmbrzl** [comment]
As for the entire settings, you'd have to export the respetive registry tree and import tharbinto the new registry.
In 1.5 there will be a config file instead that will facilitate all of this

**Comment by Horuyuki** [comment]
> As for the entire settings, you'd have to export the respetive registry tree and import tharbinto the new registry. In 1.5 there will be a config file instead that will facilitate all of this

Indeed, but to my delight that is no longer needed!

Mumble and sonant has automatically backed up the certs to my documents directory, which I can access!
So now no need for moving the whole directory tree which I will have to somehow locate it amongst the crazy directory tree window uses.

All hail backups and automatic back ups!

**Comment by Horuyuki** [comment]
But if it is possible for someone coming in later to have that data directory it will be great. They might now have the certs auto backed up.
