### ISSUE TITLE
How to delete old server?

### ISSUE THREAD

**Issue by jobber2955** [mumble-voip/mumble#5579]
#### ~Here's my setup info, will test Windows 10 client later~
```
Server System: Ubuntu 20.04 LTS
Server Version: 1.3.3 (1.3.4-1~ppa2~focal1) from log file
MacOS Version: 12.1
MacOS Client Version: 1.4.230
Android Client: Mumla 3.5.8 with mumble client 1.2.5 from log file
```

#### My newly installed public mumble server is configured in these step:
1. Add the ppa repo to apt, and apt-get install it, and dpkg-reconfigure it. Pretty simple.
2. Edit the /etc/mumble-server.ini, and change serval info there.
3. systemctl restart the mumble server, and test it.
4. Found that i could not discover my server in ```MacOS``` client but ```Android's Mumla``` could, and it shows my server's IP is ipv6. Also i can found my server in [Server List](https://www.mumble.com/serverlist/) with IPV6 address, i have not access to ipv6(mumble server or vps has ipv6 but my network hasn't), So i decided to changed it.
5. Edit the server.ini, uncomment the ```host``` to my hostname, and my hostname is only resolve in ipv4. Then restart mumble server..
6. Again i can see the update(ipv6 to ipv4) in ```Android's Mumle``` , but not in ```MacOS```. I visit [Server List](https://www.mumble.com/serverlist/) again and it still shows my IPV6.
7. I'm afraid if the [Server List](https://www.mumble.com/serverlist/) didn't update, so i change my server name and tried again but got same result: ```Android's Mumle``` updates at excepted(New server name and correct address in domain rather than ipv4 or ipv6), but [Server List](https://www.mumble.com/serverlist/) and ```MacOS``` client doesn't.

#### ~The possible reason i've thought of~
~1. DNS record failed I've flush my dns and successfully resovle my hostname and be able to ping.~
~2. Server firewall issues My ```Android client Mumle``` can connect normally and will shown at log file, so this is not the problem~
~3. I assume that ```Android's Mumle``` using a different server list api and has much more real-time update than ```Mumble official client```.Don't know for sure.~

~Later i will try windows 10 official client and give you feedabck!~

### Mumble version

murmur 1.3.3 (1.3.4-1~ppa2~focal1)

### Mumble component

Client

### OS

Windows, macOS, Other

**Comment by jobber2955** [comment]
Found ```Mumle``` source code and here's the link to fetch server list [GitLab](https://gitlab.com/quite/mumla/-/blob/master/app/src/main/java/se/lublin/mumla/servers/PublicServerFetchTask.java)
On line 44, ```private static final String MUMBLE_PUBLIC_URL = "https://mumble.info/list2.cgi";```, Seems it request a cgi and i found that this api is the most updated one with correct server info

**Comment by jobber2955** [comment]
After capture Macos Mumble client, I found it actually using this api for getting server list:```https://publist.mumble.info/v1/list?version=1.4.230```, and it's response did exist correct server(old and new one both) with correct hostname, But why the client itself could not parse it?

**Comment by jobber2955** [comment]
After reinstalling the MacOS server, I got my server shownm at the public server list, This could be a cache issues, And using a proxy for the client cause it fetch latest server list.

Now is the problem: How can i delete the old server? (Both old and new are shown online)

**Comment by Krzmbrzl** [comment]
So first of all: You'll have to be patient with any changes to the public server list. It usually takes (quite) a while for it to show new servers. The requests to the list are cached and so I assume it could happen that one device happens to access a newer cache than the other.

On another note: mumble.com is 100% unrelated to us as a project team. It is owned by a different company that are selling Mumble hosts, but we are in no way related to them. The official list that we curate, is at https://publist.mumble.info/v1/list

In terms of the old entry: Afaik it will become stale at some point and will then be removed automatically.

**Comment by jobber2955** [comment]
> So first of all: You'll have to be patient with any changes to the public server list. It usually takes (quite) a while for it to show new servers. The requests to the list are cached and so I assume it could happen that one device happens to access a newer cache than the other.
> 
> On another note: mumble.com is 100% unrelated to us as a project team. It is owned by a different company that are selling Mumble hosts, but we are in no way related to them. The official list that we curate, is at https://publist.mumble.info/v1/list
> 
> In terms of the old entry: Afaik it will become stale at some point and will then be removed automatically.

Thanks, I've understood!

**Comment by jobber2955** [comment]
> Correct, the server simply disappears from the list if unreachable for a prolonged period of time.

Thanks, I will offline my server and wait for 24h !
