### ISSUE TITLE
Can the -ini argument of mumble-server be set by an Linux environment variable?

### ISSUE THREAD

**Issue by androos** [mumble-voip/mumble#5580]
### The issue

I would like to set server environment variables like this:
MUMBLE-SERVER-INI=~/mumble-server/murmur.ini
so when I start mumble-server it does:
mumble-server -ini ~/mumble-server/murmur.ini
I could find anything about murmur and env variables

### Mumble version

1.4.260

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
At this point the Mumble server does not check any env variables.
You could write a wrapper shell script though  that would give you the desired result

**Comment by androos** [comment]
I will do an alias in .zshrc
