### ISSUE TITLE
Chat image zooming

### ISSUE THREAD

**Issue by Bartkk0** [mumble-voip/mumble#5582]
### Description

When sending very wide images (for example) the text is barely readable. It would be nice if it would be possible to click on images to zoom on them.

![image](https://user-images.githubusercontent.com/32180149/154981845-a87e4a5a-3542-42d9-810b-2946b27d35ed.png)

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
I would argue that this is a duplicate of #3282. Would you agree with that?

**Comment by Bartkk0** [comment]
I think it probably is a duplicate of #3282.
