### ISSUE TITLE
Please provide option to build against system copy of nlohmann_json

### ISSUE THREAD

**Issue by Polynomial-C** [mumble-voip/mumble#5584]
### Context

Build of mumble client

### Description

Bundling each and every third party software [is bad](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies). In order to reduce those bundled deps a bit I'd like to request an option to build mumble against a system copy of nlohmann_json. I gave this a try by patching `src/mumble/CMakeLists.txt` and the build succeeded:

```
diff --git a/src/mumble/CMakeLists.txt b/src/mumble/CMakeLists.txt
index bb8df1671..51f83850e 100644
--- a/src/mumble/CMakeLists.txt
+++ b/src/mumble/CMakeLists.txt
@@ -472,12 +472,7 @@ else()
 endif()


-set(JSON_BuildTests OFF CACHE INTERNAL "")
-set(JSON_ImplicitConversions OFF CACHE INTERNAL "")
-add_subdirectory("${3RDPARTY_DIR}/nlohmann_json/" "${CMAKE_CURRENT_BINARY_DIR}/nlohmann_json/")
-
-target_link_libraries(mumble_client_object_lib PUBLIC nlohmann_json::nlohmann_json)
-
+find_pkg("nlohmann_json" REQUIRED)
 find_pkg("SndFile;LibSndFile;sndfile" REQUIRED)

 # Check if sndfile version supports opus
```

How about adding a CMakeLists.txt option to switch between system and bundled nlohmann_json?

### Mumble component

Client

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
Could you check out #5585 and verify that this does the job for you?

**Comment by Polynomial-C** [comment]
> Could you check out #5585 and verify that this does the job for you?

Sorry for the late reply. Yes, https://github.com/mumble-voip/mumble/pull/5585 does the job for me. Thank you very much :smile:

**Comment by Krzmbrzl** [comment]
Perfect :+1:
