### ISSUE TITLE
Link Highlighting does not support URL-encoded characters

### ISSUE THREAD

**Issue by mpldr** [mumble-voip/mumble#5586]
### Description

Some Links are not correctly parsed as `%` is not parsed as part of the URL
### Steps to reproduce

1. Send a link using chat

### Mumble version

1.4.230

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Screenshots

![mumble_url](https://user-images.githubusercontent.com/33086936/155805309-510005d1-eec0-479c-9fff-0b9065a146ba.png)

**Comment by Krzmbrzl** [comment]
This has already been fixed via https://github.com/mumble-voip/mumble/pull/5564
