### ISSUE TITLE
Murmur server stop accepting new clients

### ISSUE THREAD

**Issue by MrSentex** [mumble-voip/mumble#5588]
### Description

When too many clients try to connnect to the server or more than 200 clients are connected for a long time mumble server stop working and stop accepting new connections giving the error (Connection closed: The remote host closed the connection)

### Steps to reproduce

1. Start the server
2. Clients connects and all work successfully
3. Murmur starts to slow down and clients stop hearing
4. Mumrur does not accept new connections
5. Restart mumble
6. No connections can be done
7. Change port
8. All works for one client
9. All clients try to connect to the new server
10. Murmur stop working again

### Mumble version

1.3.4

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Relevant log output

```shell
<W>2022-03-01 02:10:12.553 1 => <36:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-03-01 02:10:12.734 1 => <38:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-03-01 02:10:12.947 1 => <40:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-03-01 02:10:13.119 1 => <42:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-03-01 02:10:13.363 1 => <44:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-03-01 02:10:13.547 1 => <46:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-03-01 02:10:13.787 1 => <48:(-1)> Connection closed: The remote host closed the connection [1]
<W>2022-03-01 02:10:13.915 1 => <103:(-1)> New connection: 90.94.130.***:57385
<W>2022-03-01 02:10:14.139 1 => <104:(-1)> New connection: 85.55.42.***:55644
<W>2022-03-01 02:10:14.344 1 => <105:(-1)> New connection: 87.236.181.***:64993
<W>2022-03-01 02:10:14.564 1 => <106:(-1)> New connection: 47.62.147.***:61046
<W>2022-03-01 02:10:14.791 1 => <107:(-1)> New connection: 46.25.36.***:55711
<W>2022-03-01 02:10:14.973 1 => <108:(-1)> New connection: 81.34.192.***:53535
<W>2022-03-01 02:10:15.123 1 => <109:(-1)> New connection: 185.112.76.***:60248
<W>2022-03-01 02:10:15.298 1 => <110:(-1)> New connection: 159...
```

**Comment by Krzmbrzl** [comment]
To me it seems that the hardware you are using is too weak to support that many users and therefore the connection process takes too long, causing the clients to think the server is not reachable anymore and thus disconnect.

**Comment by Krzmbrzl** [comment]
Multiple core won't really help you, since the server is currently not really parallelized. Maybe check the CPU usage via `htop` to see if one core might be maxed out.

Generally speaking, using a container should not cause any big issues.

**Comment by MrSentex** [comment]
I just check the cpu and any core reach 100%. Not even 1% i have 14 clients now and is happend the commented before.

**Comment by Krzmbrzl** [comment]
What does the client's log have to say about these issues? (See https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md)

**Comment by MrSentex** [comment]
```
<W>2022-03-02 17:52:43.464 JackAudioSystem: unable to open client due to 2 errors:
<W>2022-03-02 17:52:43.464 JackAudioSystem: JackFailure - overall operation failed
<W>2022-03-02 17:52:43.464 JackAudioSystem: JackServerFailed - unable to connect to the JACK server
<D>2022-03-02 17:52:44.466 libopus 1.2.1 from /snap/mumble/1675/bin/libopus.so.0
<W>2022-03-02 17:52:44.466 CELT bitstream 8000000b from /snap/mumble/1675/bin/libcelt0.so.0.7.0
<W>2022-03-02 17:52:44.466 CELT bitstream 80000010 from /snap/mumble/1675/bin/libcelt0.so.0.11.0
<W>2022-03-02 17:52:44.467 Theme: "Mumble"
<W>2022-03-02 17:52:44.467 Style: "Lite"
<W>2022-03-02 17:52:44.467 --> qss: ":themes/Mumble/Lite.qss"
<W>2022-03-02 17:52:44.467 Locale is "es_ES" (System: "es_ES")
<W>2022-03-02 17:52:44.488 Database SQLite: "3.22.0"
<W>2022-03-02 17:52:44.492 Updating application palette
<W>2022-03-02 17:52:44.474 propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.212\" (uid=1000 pid=35087 comm=\"/snap/mumble/1675/bin/mumble \" label=\"snap.mumble.mumble (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1461 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
<W>2022-03-02 17:52:44.474 nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.212\" (uid=1000 pid=35087 comm=\"/snap/mumble/1675/bin/mumble \" label=\"snap.mumble.mumble (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1461 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
<W>2022-03-02 17:52:44.474 "Object path cannot be empty"
<W>2022-03-02 17:52:44.505 GlobalShortcutX: Using XI2 2.3
<W>2022-03-02 17:52:44.895 AudioInput: Opus encoder set for VOIP
<W>2022-03-02 17:52:44.895 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2022-03-02 17:52:44.895 PulseAudio: Starting input alsa_input.usb-Corsair_Corsair_VOID_PRO_Wireless_Gaming_Headset-00.mono-fallback
<W>2022-03-02 17:52:44.896 PulseAudio: Starting output: alsa_output.usb-Corsair_Corsair_VOID_PRO_Wireless_Gaming_Headset-00.analog-stereo
<W>2022-03-02 17:52:44.902 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2022-03-02 17:52:44.912 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2022-03-02 17:53:29.080 Database SQLite: "3.22.0"
<W>2022-03-02 17:53:29.080 OpenSSL Support: 1 (OpenSSL 1.1.1  11 Sep 2018)
<W>2022-03-02 17:53:29.109 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-03-02 17:54:38.203 OSInfo: Failed to execute lsb_release
```

**Comment by Krzmbrzl** [comment]
What is the ping to your server?

**Comment by MrSentex** [comment]
When the server start to hang no ping is recivied from the mumble process but when the server is up and running normaly 20-30 ms

**Comment by davidebeatrici** [comment]
Okay, that means the server is unreachable through both TCP and UDP.

Once that happens, are you able to stop the process gracefully? If not, it's definitely a complete deadlock.

**Comment by MrSentex** [comment]
It takes some time but I can stop it

**Comment by Krzmbrzl** [comment]
When the clients start disconnecting, can you still access your server outside of Mumble (e.g. via SSH or ping)?

**Comment by Krzmbrzl** [comment]
Are you using any special configuration that deviates from the defaults? E.g. an external authenticator or a remote database?

**Comment by MrSentex** [comment]
> When the clients start disconnecting, can you still access your server outside of Mumble (e.g. via SSH or ping)?

Yes.



> Are you using any special configuration that deviates from the defaults? E.g. an external authenticator or a remote database?

I'm not using anything special.

```
database=/var/lib/mumble-server/mumble-server.sqlite

icesecretwrite=

autobanAttempts = 10
autobanTimeframe = 120
autobanTime = 300

logfile=/var/log/mumble-server/mumble-server.log
pidfile=/var/run/mumble-server/mumble-server.pid

welcometext="<b>Murmur</b>"

host=0.0.0.0
port=7777
bandwidth=72000
users=1000
messageburst=100
messagelimit=20

username=(.*)+.

textmessagelength=20
imagemessagelength=10

logdays=7

uname=mumble-server

[Ice]
Ice.Warn.UnknownProperties=1
Ice.MessageSizeMax=65536

**Comment by davidebeatrici** [comment]
I would attach GDB to the server and look at the backtrace when it hangs.

**Comment by Krzmbrzl** [comment]
Another thing that could be tried is to upgrade to 1.4.230. Maybe the issue has been resolved there (not terribly likely, but who knows?)

**Comment by MrSentex** [comment]
Running docker on a LXC container is not posible due to permission issues

**Comment by Krzmbrzl** [comment]
In that case, I think compiling is your only option to upgrade at this point.

**Comment by NormandoHall** [comment]
Hmmm.... sorry for this dumb suggestion, but can you check Max Open Files limit under the user you run murmur?

**Comment by egrain** [comment]
I have the same issue, also in an LXC container. Works fine, once more than 6 people on the server everyone disconnects and reconnects.
The log gives me a few of these:
murmurd: INFO: Connection closed by peer - ....

**Comment by Krzmbrzl** [comment]
@egrain I think it'd be best if you created a separate issue with alk relevant information (in particular server version and full log messages)

**Comment by egrain** [comment]
I misread anyhow. I'm having the issue with umurmurd. Don't now how I managed to cut of the u. Anyway, I can't really reproduce it because we rarely get seven people together. And most of those have serious instant gratification issues, so yeah... Next time I try it outside of the container with the same keys and config. If that works, well, than it works and it's more likely to be an lxc issue.
Anyway, if someone else wants to test it in the meanwhile though: void musl host, void musl container. umurmur-0.2.20_3. Both host and container are freshly updated.
