### ISSUE TITLE
Background color set in preformated message persists

### ISSUE THREAD

**Issue by XDjackieXD** [mumble-voip/mumble#5590]
### Description

When sending a preformatted message that contains a background color (for example when pasting code with highlighting from IntelliJ), the background color persists for all messages sent after that one (see screenshot below).

### Steps to reproduce

1. Paste HTML formatted code into the "Send Message" dialog:
Example (aparently this has to be marked as formatted in the clipboard. copy-pasting the source code below does not work):
```
<pre style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#2b2b2b;"><span style="color:#a9b7c6; font-family:'Noto Sans Mono','monospace'; font-size:9pt">env_logger::</span><span style="color:#ffc66d; font-family:'Noto Sans Mono','monospace'; font-size:9pt">builder</span><span style="color:#a9b7c6; font-family:'Noto Sans Mono','monospace'; font-size:9pt">()<br/>    .</span><span style="color:#ffc66d; font-family:'Noto Sans Mono','monospace'; font-size:9pt">filter_level</span><span style="color:#a9b7c6; font-family:'Noto Sans Mono','monospace'; font-size:9pt">(LevelFilter::</span><i><span style="color:#9876aa; font-family:'Noto Sans Mono','monospace'; font-size:9pt">Info</span></i><span style="color:#a9b7c6; font-family:'Noto Sans Mono','monospace'; font-size:9pt">)<br/>    .</span><span style="color:#ffc66d; font-family:'Noto Sans Mono','monospace'; font-size:9pt">parse_default_env</span><span style="color:#a9b7c6; font-family:'Noto Sans Mono','monospace'; font-size:9pt">()<br/>    .</span><span style="color:#ffc66d; font-family:'Noto Sans Mono','monospace'; font-size:9pt">init</span><span style="color:#a9b7c6; font-family:'Noto Sans Mono','monospace'; font-size:9pt">()</span><span style="color:#cc7832; font-family:'Noto Sans Mono','monospace'; font-size:9pt">;</span></pre>
```

2. Send it
3. Send another "normal" message

### Mumble version

1.4.230

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/4963868/156902037-1b15b36c-9b80-4701-aa90-537ec1ab5f7b.png)

**Comment by Snowknight26** [comment]
This is fixed by https://github.com/mumble-voip/mumble/commit/ae097d6354d99325093dd5a12cb8632e2ba20edf, though a backport would be great.

**Comment by Krzmbrzl** [comment]
Thanks for bringing this to our attention!

This actually even has been backported already: https://github.com/mumble-voip/mumble/pull/5621

So the next release will fix it.
