### ISSUE TITLE
iOS notification sounds

### ISSUE THREAD

**Issue by zz0rk** [mumble-voip/mumble#5591]
### Context

Message notification sounds

### Description

Unless I am mistaken there currently is no option to select a sound file for text message notifications, e.g. a text message posted to a channel does not trigger a notification sound on the iOS device. 

### Mumble component

Client

### OS-specific?

Yes

### Additional information

iOS

**Comment by Krzmbrzl** [comment]
This repo is completely unrelated with the iOS app. Please refer to https://github.com/mumble-voip/mumble-iphoneos but also keep https://github.com/mumble-voip/mumble-iphoneos/issues/129 in mind.
