### ISSUE TITLE
Add user definable GPIO with Linux OS.

### ISSUE THREAD

**Issue by KB6mcc** [mumble-voip/mumble#5595]
### Context

This option will push this application into many useful area.  Especially a small form factor used desktop PC is dirt cheap these day. 

### Description

Please add this option into the application. This option will enable many external hardware can interface to like PTT for walkie talkie, channel status LEDs, switch and relay etc.  

### Mumble component

Client

### OS-specific?

Yes

### Additional information

I think a USB FIDI port should be a good start.

**Comment by Krzmbrzl** [comment]
You'll have to elaborate more on this as I don't understand what it is that you want... Hoe do GPIO (hardware) relate to Mumble (software)? :thinking:

**Comment by davidebeatrici** [comment]
Shortcuts.

**Comment by KB6mcc** [comment]
> You'll have to elaborate more on this as I don't understand what it is that you want... How do GPIO (hardware) relate to Mumble (software)? 🤔

Hi Basically just make Mumble Client to have an option to interface the Push to Talk with a external hardware toggle switch or push button and a LED for the  channel activity.  Maybe using a USB serial with the PAC9502BS serial/GPIO chip.

**Comment by Krzmbrzl** [comment]
This sounds like a perfect use-case for a plugin to me.

Given the limited applicability (to cases where Mumble runs on hardware that even has GPIO) I don't think that this should be supported by Mumble itself.

However, implementing this as a plugin seems was enough (provided you know how to interface with GPIO). Have a look at https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/README.md
