### ISSUE TITLE
Error: A referral was returned from the server.

### ISSUE THREAD

**Issue by ptrvc** [mumble-voip/mumble#5597]
### Description

When opening Mumble, an error message popup.
Error: A referral was returned from the server.

### Steps to reproduce

Open Mumble 1.3.4

### Mumble version

1.3.4

### Mumble component

Client

### OS

Windows Vista 32-bit

### Reproducible?

Yes

### Additional information

The certificate used to sign this has expired.

### Screenshots

![certificate1](https://user-images.githubusercontent.com/101967235/159154689-02f3487c-c40a-43a3-a502-c22a5c3d10bd.jpg)
![certificate2](https://user-images.githubusercontent.com/101967235/159154690-6156939c-20f6-4e1f-ab5c-5b5485d5d6dd.jpg)
![description](https://user-images.githubusercontent.com/101967235/159154691-19ebae4e-a202-40e8-99ed-f67741d3cdd9.jpg)
![Error](https://user-images.githubusercontent.com/101967235/159154693-63a0507d-01a4-4212-a60e-0c977ecb9837.jpg)
![signage](https://user-images.githubusercontent.com/101967235/159154695-7d6166a2-bdd5-4eda-ad7e-8e810b6555e1.jpg)
.

**Comment by Krzmbrzl** [comment]
Yes, we don't use this certificate anymore. Please upgrade to the 1.4.230 release. This should resolve the issue as that is signed with our new certificate.

**Comment by ptrvc** [comment]
No, you don't understand. I need to use 1.3.4, because I am running Vista and when I try to launch 1.4.230 it gives me an kernel error, because it needs Windows 7. You even have this written in the Readme:

"Please note that with "Windows" we mean 7 and newer. Vista may be supported, but we can't guarantee it. If you don't want to encounter potential issues, you may download Mumble 1.3.x, the last version to provide support for XP". 

That's why I am not using 1.4.230. Thank you.

**Comment by Krzmbrzl** [comment]
Ah okay, I see. In that case you'll have to ask @davidebeatrici whether or not he wants to extend his certificate for you :shrug:

**Comment by ptrvc** [comment]
I will try to reach him. Thank you very much for your help. Have a nice day.

**Comment by davidebeatrici** [comment]
The certificate lasts one year and cannot be extended, as long as the file is timestamped (it is) the signature remains valid:

![](https://user-images.githubusercontent.com/5897523/159178231-492f7edd-3d1c-4cd9-b132-cf4550cee2d4.png)
![](https://user-images.githubusercontent.com/5897523/159178232-90af525f-e6e2-4c1e-887c-d999f08f3057.png)

**Comment by ptrvc** [comment]
I don't understand this a little bit. So what can I or you to make my client launch?

**Comment by davidebeatrici** [comment]
Disable the security setting: https://superuser.com/questions/1314839/how-to-turn-on-only-elevate-executables-that-are-signed-and-validated-setting

**Comment by ptrvc** [comment]
The setting was already disabled.
I messed with the properties of mumble.exe, turned on Launch this app as an Administrator in the Compatability tab and now it works! Thank you.

**Comment by davidebeatrici** [comment]
No problem, please note that you should get away from Vista as soon as possible if you care about security.

**Comment by ptrvc** [comment]
Don't worry, I daily drive Fedora on my laptop. This is an old PC that I use for legacy games and apps. I just wanted to play these games with my friends and be able to talk with without having me to run Mumble on a another device. Again, thank you very much for your help. Goodbye.
