### ISSUE TITLE
Provide --version CLI flag

### ISSUE THREAD

**Issue by piegamesde** [mumble-voip/mumble#5598]
### Context

I've run multiple times into the situation that I wanted to know the version of my mumble client. Instinctively, I typed `mumble --version` just to find out that it simply starts Mumble (or joins an existing instance if possible). Especially in the latter case this is rather unhelpful since the running instance might be of another version than the binary on which the command was called.

### Description

Have `mumble --version` and `mumble -V` print the current version and then quit

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
> the running instance might be of another version than the binary on which the command was called.

How could that happen? 👀
Are you perhaps referring to the server's version in this case, instead of the client's one?

**Comment by piegamesde** [comment]
> How could that happen?

I am using Nix, which as a feature allows to install software multiple times in different versions. This is usually a cool feature, especially when developing applications, but sometimes it makes things a bit more confusing.

**Comment by Krzmbrzl** [comment]
Ah okay, I see :bulb:

**Comment by piegamesde** [comment]
Thank you.
