### ISSUE TITLE
Mumble Launcher Error -3 Failed to load mumble_app.dll Win 11 22000.588

### ISSUE THREAD

**Issue by iCeOL8TRAmnesia** [mumble-voip/mumble#5602]
### Description

New windows not working seems like dll is blocked for some reason.  Is there a known dependency tree for mumble?  Really would love to get this working I cannot stand discord..............

### Steps to reproduce

1. Install latest release on new windows 22000.588 mumble version 1.4.320 x64.

### Mumble version

1.4.320 x64

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

Did it on 2 different pcs.......

**Comment by davidebeatrici** [comment]
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist

**Comment by Krzmbrzl** [comment]
Context: #5549

**Comment by SC1040-TS2** [comment]
@iCeOL8TRAmnesia , check this post again. Someone has posted a solution to resort to.

The error is caused by Mumble checking for and not finding Microsoft Visual C++ 2015-2022 Redistributables. The link provided above is to a Microsoft download page for them.
