### ISSUE TITLE
Server connection failed: Connection refused.

### ISSUE THREAD

**Issue by H3ll0W0lrd** [mumble-voip/mumble#5607]
### Description

Server connection failed: Connection refused.
![image](https://user-images.githubusercontent.com/30374511/160987303-aafbd5fc-c48e-4b1a-90a6-1b66602424d2.png)

But others can connect.

Open Webpage
![image](https://user-images.githubusercontent.com/30374511/160987064-2e058b82-d450-487f-8cda-0c973b415767.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/30374511/160987918-7f10e9cd-deb5-47e3-ba7a-ec713c0c5e42.png)

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Could you post the output of the [developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) when attempting this?

> Open Webpage

What do you mean by that?

**Comment by H3ll0W0lrd** [comment]
> 您可以在尝试此操作时发布[开发者控制台](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md)的输出吗？
> 
> > 打开网页
> 
> 你是什​​么意思？

OK

**Comment by H3ll0W0lrd** [comment]
> Could you post the output of the [developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) when attempting this?
> 
> > Open Webpage
> 
> What do you mean by that?

OK
I now open the developer console.
![image](https://user-images.githubusercontent.com/30374511/160991837-4a9723e8-86ce-4f93-b4c2-9aa8b562e669.png)
a0096113.synology.me. I failed to connect, but others connected successfully.
But I connect to other server successfully.
![image](https://user-images.githubusercontent.com/30374511/160992538-a57f346b-9886-434e-9a4f-27e7ed9a621c.png)

Open Webpage
![image](https://user-images.githubusercontent.com/30374511/160992736-f957bda3-5e14-47d9-8d04-f235ea5b6eb1.png)
![image](https://user-images.githubusercontent.com/30374511/160992821-4d5bb46d-3b07-4386-8db6-59da35f84d69.png)
I guess the problem starts here?

**Comment by Krzmbrzl** [comment]
Okay so I think the webpage issue doesn't have anything to do with your connection problems. That just means that the server host has configured an invalid URL (missing scheme) and apparently we currently don't default to a https scheme in that case.

As far as the actual connection is concerned, we'd need the server logs as it appears that the server is refusing your client (for some reason). Could you contact the server admin about that?

Also please try to connect to a different server to see if that works as expected.

**Comment by H3ll0W0lrd** [comment]
> 



> Okay so I think the webpage issue doesn't have anything to do with your connection problems. That just means that the server host has configured an invalid URL (missing scheme) and apparently we currently don't default to a https scheme in that case.
> 
> As far as the actual connection is concerned, we'd need the server logs as it appears that the server is refusing your client (for some reason). Could you contact the server admin about that?
> 
> Also please try to connect to a different server to see if that works as expected.

Connected to different servers and they all work fine.
![image](https://user-images.githubusercontent.com/30374511/160998810-ca8771d5-8ec0-4d51-8d25-50c0ff68ff1c.png)
![image](https://user-images.githubusercontent.com/30374511/160998898-eda0aaab-e437-4f19-a48b-45fc885b27d4.png)

**Comment by H3ll0W0lrd** [comment]
> Okay so I think the webpage issue doesn't have anything to do with your connection problems. That just means that the server host has configured an invalid URL (missing scheme) and apparently we currently don't default to a https scheme in that case.
> 
> As far as the actual connection is concerned, we'd need the server logs as it appears that the server is refusing your client (for some reason). Could you contact the server admin about that?
> 
> Also please try to connect to a different server to see if that works as expected.

Anyone can connect to this server except me. And I can connect to other servers except this one.
![XY~5V`F4B DQ9WDYD5%S23](https://user-images.githubusercontent.com/30374511/161001933-18d53549-1df9-4eb2-933e-cf90c6205258.jpg)

**Comment by H3ll0W0lrd** [comment]
> 
Unfortunately I cannot contact the administrator.

**Comment by Krzmbrzl** [comment]
In that case, I am afraid that there is no way we can help you :eyes:
