### ISSUE TITLE
Server stopped appearing in the public server list

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#5622]
### The issue

Our server mumble.zova.io stopped appearing in the public server list. The following lines appear in the log repeatedly:

```
Registration: SSL Handshake error: The issuer certificate could not be found
Registration failed: SSL handshake failed
```

Nothing but the IP should have changed. Restarting does not help. Certificate (issued by Letsencrypt) is valid till 2022-06-04 and can be read with no issues.

Please advise.

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
@davidebeatrici any ideas?

**Comment by davidebeatrici** [comment]
I see several `AH02039: Certificate Verification: Error (66): EE certificate key too weak` in our log, but nothing else relevant.

**Comment by StrangePeanut** [comment]
Removing the expired DST Root CA X3 solved the issue. Thanks so much! ❤

```
Registration: Attempting to connect to [2a05:d014:d43:6600:79e1:2596:a7fd:74c]:64738...
Your certificate is validated by a CA, congratulations!
Registration updated!
```

**Comment by davidebeatrici** [comment]
You're welcome!
