### ISSUE TITLE
Dependency scripts may have issues after merge of ZeroC Ice port to vcpkg

### ISSUE THREAD

**Issue by ZeroAbility** [mumble-voip/mumble#5624]
### Description

A ZeroC Ice port was recently merged to vcpkg: 

https://github.com/microsoft/vcpkg/pull/23764

By default, it builds with C++11 support and does not appear to have a feature/option to build using the C++98 project types. Our script for Windows checks for the presence of the folder `zeroc-ice` and if it does not exist it copies our custom port files to a new directory with that name. We need to move the vcpkg port folder in `vcpkg/ports` to something like `vcpkg/ports/zeroc-ice_msbuild` so we can add our custom port.

### Steps to reproduce

1. Run the script in `mumble/scripts/vcpkg` to install vcpkg and dependency packages.
2. zeroc-ice package installs and produces a C++11 ice library which our project does not support.

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

### Additional information

Will most likely affect macOS and Linux, possibly CI

**Comment by ZeroAbility** [comment]
The pertinent script section is here:

https://github.com/mumble-voip/mumble/blob/0c2e398f392f3d6ac392e7472a0e5ff0cbe80790/scripts/vcpkg/get_mumble_dependencies.ps1#L61-L65

**Comment by Krzmbrzl** [comment]
> My recommendation would be to change the name of the directory to helpers/vcpkg/ports/zeroc-ice_mumble and update the scripts accordingly.

Sounds good to me :+1:

**Comment by ZeroAbility** [comment]
The port name can't have underscores. I'm looking at revising the script and directory.
