### ISSUE TITLE
[Support] How to hide users in password-protected channel from beening seen by others?

### ISSUE THREAD

**Issue by jobber2955** [mumble-voip/mumble#5627]
### The issue

I don't know if this is a implemented feature, but I searched the issues and found something related, but  without a tutorial.

Here's what I image:

====== Channel A (With password, users outside this channel could not see who's in here)
====== Channel B (Without password, users could see who's in here)

I think this maybe a interesting feature, adding more privacy to users. But also, If this is a no-implemented-yet feature, there are some problem to think of, like: How to calcaulate total user amount for the info shown at public server list.

If there's a way for this situation, could you give me a document to it? If this hasn't been implemented yet, will mumble consider adding this feature?

### Mumble version

1.4.230

### Mumble component

Both

### OS

Linux, Windows

**Comment by Krzmbrzl** [comment]
This feature does not exist in Mumble, but I'm reasonably sure that there is a feature request for that (or something like that) somewhere :thinking:
