### ISSUE TITLE
Unable to join forum, never receiving the confirmation email

### ISSUE THREAD

**Issue by shodanx2** [mumble-voip/mumble#5645]
### Description

I got the warning to respond to confirmation email

I checked my emails everywhere, searched for the address, checked for spam, it's just not there !

![image](https://user-images.githubusercontent.com/10621885/166233170-7c035264-4e12-4962-822b-f0464978cd58.png)

### Steps to reproduce

create new account on forum
maybe my domain in particular it doesn't like ?

### Mumble component

Both

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
I manually approved your account. You should have access now.
