### ISSUE TITLE
[docker] aarch64 (arm) gone missing?

### ISSUE THREAD

**Issue by sirjeannot** [mumble-voip/mumble#5683]
### Context

hello,
I've been using this image/container following issues with other and older mumble containers.
However with the last update pushed a few days ago to dockerhub, aarch64 has gone missing, only amd64 is available.
this rules out hosting mumble server on any arm based single board computer (raspi, rockchip, amlogic, ...), which is too bad.

### Description

Make aarch64 available again for docker/linux.

### Mumble component

Server

### OS-specific?

Yes

### Additional information

amd64 doesn't run on aarch64, still not compatible :)

**Comment by Krzmbrzl** [comment]
This does not belong here. Also there is already an issue covering this in the respective repo. Please refer to https://github.com/mumble-voip/mumble-docker/issues/3 for more information.

**Comment by Krzmbrzl** [comment]
Also FYI, we had to recreate the docker image from scratch due to the issue detailed in https://github.com/mumble-voip/mumble/issues/5613
That's why we can't provide backwards compatibility with previously existing images.
