### ISSUE TITLE
deny listen doesn't 'stick'

### ISSUE THREAD

**Issue by atomGit** [mumble-voip/mumble#5691]
### The issue

trying to set up a channel where users cannot speak nor listen, however setting the deny listen option is not saved

essentially i want to mute and deafen users that enter the channel

i'm trying to set this up using the ACLs on the client end but i don't know if this is a server or client issue

### Mumble version

1.4.230

### Mumble component

I don't know

### OS

Linux

**Comment by Krzmbrzl** [comment]
What server version are you using?

**Comment by Krzmbrzl** [comment]
Well if the version is <1.4 then it is no wonder that the ACL doesn't stick: The server doesn't even support Listening to begin with. This feature has only been introduced in 1.4.
However, if this is indeed the case, then there is an issue on the client-side as it shouldn't even offer you to set this ACL on a server <1.4 :thinking: 

You can check the server version by connecting to the server and then using the Server > Info menu. The "protocol version" corresponds to the server version. Please let me know what server version you are using.

**Comment by atomGit** [comment]
ok, then we got a bug :)

also it looks like 1.3.4 is the latest available for linux, so i can't upgrade

should i close this and open a new bug issue?

**Comment by Krzmbrzl** [comment]
> should i close this and open a new bug issue?

Nah, I'll create the new issue myself :)
