### ISSUE TITLE
Linux Server Support

### ISSUE THREAD

**Issue by lorentedford** [mumble-voip/mumble#5693]
### Context

I noticed on the latest you dropped linux server support.

### Description

Please provide latest linux server support so that it works with linuxgsm setup. 

https://linuxgsm.com/servers/mumbleserver/

### Mumble component

Server

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
We did not drop Linux server support. We did drop the _static_ server binary though.

The general consensus was that we don't have any real plans of bringing the static server back to life. Instead modern package formats such as flatpak or snap or AppImage should be used.
Another alternative would be to use Docker. There is an official Docker image available at https://github.com/mumble-voip/mumble-docker

I don't know how linuxgsm works but it should be possible to switch to one of the alternatives listed above. Alternatively it is of course always possible to just use the server as provided in the respective distro repository or build from source.

**Comment by davidebeatrici** [comment]
Consider that the static server binary was being built through [Ermine](https://www.magicermine.com) on an ancient CentOS version.

The rationale behind that was to set the minimum libc version very low. Every other dependency was built from source, as we did for Windows and macOS releases.

At one point the infrastructure became pretty much impossible to maintain and we decided to drop the Linux static server after a few failed attempts to produce a "modern" one with the help of vcpkg.

Consider that with the switch to CMake (1.4.x) pretty much anyone should be able to build on Linux without any issues, enabling machine-specific optimizations if desired.

**Comment by dgibbs64** [comment]
This is a shame that the static binary is no longer supported (I do however understand the rationale) as we have no practical way to distribute the latest Mumble server via LinuxGSM as it stands. 

I think the best option for us is to use the available distro versions of mumble server. 

However, looking at both Ubuntu and Debian this is now out of date.
https://packages.ubuntu.com/jammy/mumble-server
https://packages.debian.org/bullseye/mumble-server

Having a quick google it may be possible to build an rpm and deb using github actions.

**Comment by lorentedford** [comment]
This is so messed up... I mean Mumble was only used as a backup for us.. But I suppose I will have to look for an alternative open source project that is more open to server environments and cross platform compatibility.. It's easy to just use discord but when Discord goes down what are you going to use..... This is why I always like having backups..

**Comment by trymeouteh** [comment]
Would like to see a portable linux server installation that can work offline and not depend on a package repository or app store. Not against having murmur in a package repository or app store.

Windows users have the ability to download the installers for Mumble server which allows them to install the erver offline and backup the EXE installers. Mumble makes for a good communication app and service over mesh networks and having the ability to backup the client and server is essential if the internet goes down to deploy Mumble.

**Comment by EricZhang456** [comment]
Any updates on this? I was able to build 1.5.857 with vcpkg "statically" [here](https://github.com/EricZhang456/static-mumble-server-linux). The resulting binary is not 100% static however. I would like to see an official static build in the future.

```
$ ldd mumble-server
        linux-vdso.so.1 (0x00007fa73d885000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fa73d823000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa73b400000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa73d733000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa73b7d3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa73b20c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa73d887000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fa73b6be000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007fa73d725000)
```

**Comment by Krzmbrzl** [comment]
> The resulting binary is not 100% static however.

Exactly - that's the problem we've been seeing as well. And we don't see enough demand for this in order to justify spending hours fixing that issue. Especially when people can simply use the docker image, which seems to be what most folks prefer anyway 🤷
