### ISSUE TITLE
Hi, I don't know where is murmur.ini :-(

### ISSUE THREAD

**Issue by luqaska** [mumble-voip/mumble#5694]
### The issue

That :-(

### Mumble version

1.4.230

### Mumble component

Server

### OS

Windows

### Additional information

It is not on `C:\Program Files\Mumble`, nor on its sub-directories

**Comment by Krzmbrzl** [comment]
You just have to create it yourself. Just create a text file, give it the extension ` .ini`  and then point the Mumble server to that file using the respective command line option.

**Comment by Krzmbrzl** [comment]
Or copy https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini and use that as a default config file

**Comment by Superfech** [comment]
> Referência
**this link is inaccessible**

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/master/auxiliary_files/mumble-server.ini

**Comment by ztx-lyghters** [comment]
Why is it not being created automatically? Or why is there not even an argument for creating it? Not even an example in /usr/share/examples. Am I expected to just remember the config syntax for mumble?

**Comment by davidebeatrici** [comment]
@Krzmbrzl We should probably install the file to the correct directory in CMake.

**Comment by Krzmbrzl** [comment]
Cmake does install it correctly iirc. Everything else is up to package maintainers. On Windows we need to explicitly add it to the installer though. But that is independent of cmake.

**Comment by davidebeatrici** [comment]
Ah, yes. I assume @ztx-lyghters is on Windows too.

**Comment by ztx-lyghters** [comment]
> Ah, yes. I assume @ztx-lyghters is on Windows too.

I was setting it up on Void Linux

**Comment by davidebeatrici** [comment]
We should check the source package, to be sure. Do you perhaps know where we can find it?
