### ISSUE TITLE
IPv6 address should always be displayed first in tooltips

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#5696]
### Description

Not much of an issue or a feature request but an issue nonetheless:

Sometimes (50/50), the dual-stack server's IPv4 address is displayed before the IPv6 address in tooltips, whereas clients always connect via IPv6 as they should. For the sake of consistency and to ease some peoples’ OCD, the IPv6 address should always be displayed before the server’s IPv4 address.

Backstory: I mistakenly assumed our server was preferring IPv4 for some reason. Upon further inspection, my client would connect via IPv6 every time regardless of the tooltip.

### Mumble component

Client

### OS-specific?

No

**Comment by vimpostor** [comment]
I agree that there should be a consistent ordering, but I think IPv4 should always be first, as it is the more conservative choice and mainly also because IPv4 addresses are much more readable than IPv6 ones.

**Comment by GuybrushThreepwoodII** [comment]
Hello,

a friend and I would like to work on this issue.

**Comment by Krzmbrzl** [comment]
@GuybrushThreepwoodII great to hear that! You are of course more than welcome to do so. If you need any help, let me know.

With regards to the ordering of the addresses: Personally, I don't really mind which one is shown first (though I tend to agree with vimpostor's line of argument) so this decision would be up to you as the ones implementing this.

**Comment by inodanus** [comment]
I'm the friend of @GuybrushThreepwoodII. We have an idea. Instead of changing the ordering we could display both ip addresses on different labels. Splitting Addresses to "IPv4 address" and "IPv6 address". What is your opinion about it?

**Comment by StrangePeanut** [comment]
> Instead of changing the ordering we could display both ip addresses on different labels.

This would tackle another consistency issue where IPs can be displayed next to each other or stacked depending on the total length of both addresses combined.

**Comment by Krzmbrzl** [comment]
Yeah separating in different fields and stacking them sounds good to me :+1:

**Comment by inodanus** [comment]
Thank you for your answers. We will stack IPv4 over IPv6 because it is more relevant for most users in our opinion.
