### ISSUE TITLE
Mumble PPA not update

### ISSUE THREAD

**Issue by awatchar** [mumble-voip/mumble#5700]
### The issue

I found that mumble ppa on (https://launchpad.net/~mumble/+archive/ubuntu/release) is still the old version (1.3.4-1). Could you pls update to the lastest version ? or How I can upgrade my ubuntu to the lastest version manually.

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

**Comment by Kissaki** [comment]
Unfortunately, this is stuck after the build change and general PPA build hassle. Please refer to https://github.com/mumble-voip/mumble-ubuntu-ppa/issues/16
