### ISSUE TITLE
How does OverLay include all windows (including desktops)?

### ISSUE THREAD

**Issue by ImAmelie** [mumble-voip/mumble#5708]
### Description

I hope Overlay can be seen at all places.
All programs and desktops.

### Steps to reproduce

I used the following configuration, but it could not be achieved.

![00](https://user-images.githubusercontent.com/7888766/170866997-70f04d2c-e322-49cd-ade5-f804b04699f5.png)

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Haven't tried

**Comment by Krzmbrzl** [comment]
That's not what the overlay is meant to do.

You might want to try out the TalkingUI that was introduced in 1.4 though

**Comment by ImAmelie** [comment]
thanks, i get it.
