### ISSUE TITLE
Raspberry Pi Mumble Cleint

### ISSUE THREAD

**Issue by jaymoore962** [mumble-voip/mumble#5709]
### Context

is there a newer version of mumble client for the rasbian or debian right now i have version 1.3.4-1 i want to have the latest version on the raspberry pi we are useing this for wireless sound at a race track

### Description

Mumble Client Newer Version

### Mumble component

Client

### OS-specific?

Yes

**Comment by davidebeatrici** [comment]
You can compile it yourself, we have instructions at https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md.

**Comment by Krzmbrzl** [comment]
Note also that we are not responsible for packaging Mumble for the various distros. Please contact the respective package maintainer of the distro of your choice.
