### ISSUE TITLE
How to open/install mumble_server-1.4.230.x64.macos ?

### ISSUE THREAD

**Issue by Christoph111** [mumble-voip/mumble#5718]
### The issue

Hi,

how to open mumble_server-1.4.230.x64.macos on Mac? what file format is this? Mac Monterey M1
Thanks for any help
Cheers
Chris

### Mumble version

1.4.0

### Mumble component

Server

### OS

macOS

**Comment by davidebeatrici** [comment]
Run it through the terminal:

```
./mumble_server-1.4.230.x64.macos
```

**Comment by Christoph111** [comment]
thanks, this worked (after changing chmod +x). but nothing comes up, besides an empty murmur.log
no folder was created, nothing....Mac Monterey m1 pro max...
is this machine to new?

**Comment by davidebeatrici** [comment]
What happens if you append the `-fg` parameter to the command?

**Comment by Christoph111** [comment]
hi, this happens:
<X>2022-06-05 10:53:51.773 SSL: OpenSSL version is 'OpenSSL 1.1.1k  25 Mar 2021'
<W>2022-06-05 10:53:51.775 Initializing settings from /Users/cc/.murmurd/murmur.ini (basepath /Users/cc/.murmurd)
<W>2022-06-05 10:53:52.193 MetaParams: TLS cipher preference is "###"
<W>2022-06-05 10:53:52.404 ServerDB: Opened SQLite database /Users/cc/Downloads/murmur.sqlite
<W>2022-06-05 10:53:52.404 ServerDB: Using SQLite's default rollback journal.
<W>2022-06-05 10:53:53.794 Performed initial PBKDF2 benchmark. Will use 32000 iterations as default
<W>2022-06-05 10:53:53.795 Generating new tables...
<W>2022-06-05 10:53:53.798 Murmur 1.4.230 (1.4.230) running on macOS: macOS 12.3.1 21E258 [x64]: Booting servers
<W>2022-06-05 10:53:53.820 1 => Password for 'SuperUser' set to '##'
<W>2022-06-05 10:53:53.824 1 => Server listening on 0.0.0.0:64738
<W>2022-06-05 10:53:53.825 1 => Server: Failed to set TOS for UDP Socket
<W>2022-06-05 10:53:54.250 1 => Generating new server certificate.
<W>2022-06-05 10:53:54.278 1 => Registering zeroconf service...
<W>2022-06-05 10:53:54.279 1 => Not registering server as public

but I can't see any murmur folder or app, and this path "/Users/cc/.murmurd" does not exist..... the log file is still empty, but there is a new file murmur.sqlite with 111kb size....

any ideas? thank you!

**Comment by Krzmbrzl** [comment]
> and this path "/Users/cc/.murmurd" does not exist

My guess would be that this is a default path that is reported and that the server just falls back to using defaults as that default path doesn't point anywhere. You can specify an actual ini file to use via the `-ini` command line option

> the log file is still empty

What log file? The server doesn't create a log file (afaik) :eyes: 

> but there is a new file murmur.sqlite with 111kb size....

That in combination with the console output seems to indicate that everything is working as expected. The DB contains all actual information and permanent storage of the server and the console output indicates that the server started correctly.
