### ISSUE TITLE
text-align in welcome message keeps applying forever

### ISSUE THREAD

**Issue by t0uch** [mumble-voip/mumble#5722]
### Description

While setting a welcome message with 
`<div align="center">any text</div>`  or `<div style="text-align:center">any text will do</div>`
any subsequent text (or console message) will keep the center alignment.
This did not happened in 1.3

### Steps to reproduce

0. by default any text is left-aligned in the chat.
1. edit the welcome message with either `<div align="center">some text</div>` or `<div style="text-align:center">some text</div>`
2. write anything in the chat, it's center-aligned.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/24417613/172512994-b0992dfe-23a1-4ad3-8e37-4c7e55d08f11.png)

**Comment by Krzmbrzl** [comment]
Yep, this is fixed in latest master
