### ISSUE TITLE
Windows 11 notifications keep getting turned off

### ISSUE THREAD

**Issue by warrenspe** [mumble-voip/mumble#5726]
### The issue

Hi all,

Not quite sure where to start for this, but since this only seems to happen with mumble I'm going to try my luck here first!

I have noticed that after upgrading to windows 11 that when I close and re-open mumble its notification settings in windows will be toggled from enabled to disabled.

That is to say, that in the windows notification settings where you can enable/disable notifications on a per-app basis, mumble will go from:
* Mumble running, notifications enabled
* Close mumble, refresh windows notifications center, mumble notifications listing is removed
* Reopen mumble, refresh windows notification center, mumble notifications listing returns, but as disabled
* Attempting to enable mumble notifications results in them being immediately togged back off
* After something happens that would cause mumble to trigger a notification (if they were enabled), then notifications for mumble can be turned back on

I am not well versed in how windows 11's notifications differ from windows 10's, but this only seemed to happen post-upgrade to 11.

Anyone have any idea what might be going on here?

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
Do you have other apps running on Qt on your system? If so, do they show the same behavior or does it work as expected with those?

**Comment by warrenspe** [comment]
Tried with VLC and yes, it appears to work similarly - I'll raise this with the QT folks instead, thanks!

**Comment by warrenspe** [comment]
Hey @Krzmbrzl ,

Sorry to bug you - would you be able to point me in the direction of which Qt project I should be creating this ticket with?  There seem to be quite a few of them and I'm not sure which mumble is using

**Comment by Krzmbrzl** [comment]
I suspect the bug would be somewhere in the main Qt library. Thus, the report should be filed against them: https://bugreports.qt.io/secure/Dashboard.jspa
