### ISSUE TITLE
Russian Font in Windows App

### ISSUE THREAD

**Issue by MarcS1975** [mumble-voip/mumble#5734]
### Description

Murmur shows Russian writing in the Windows App. See screenshot

![mumb](https://user-images.githubusercontent.com/52089754/176997938-12619612-e79e-4a57-9ce2-c6644727b8f5.JPG)

### Steps to reproduce

Start Murmur

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![mumb](https://user-images.githubusercontent.com/52089754/176997990-284d8f8c-0396-4101-9134-dab14c9448e6.JPG)

**Comment by MarcS1975** [comment]
The problem is that even uninstalling and reinstalling Mumble does not reset the language to English
The only Solution: the language can be switched in settings user settings. But since the menu points are in Russian, it is trial and error to find the reight setting to get the language back to English.

**Comment by Krzmbrzl** [comment]
Hm interesting... Normally I would expect the system default or English to be used if nothing is explicitly configured 👀
