### ISSUE TITLE
No user password in Mumble Windows App

### ISSUE THREAD

**Issue by MarcS1975** [mumble-voip/mumble#5735]
### Description

There is no user authentication !!! So anyone can join anonymously and without user authentication!

### Steps to reproduce

Add server
Connect

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Yeah, you have to configure restrictions if you want them. Either use a server password or use ACLs to control who can join which channels on your server

**Comment by MarcS1975** [comment]
How do I add a restriction on joining a Chanel?

**Comment by Krzmbrzl** [comment]
Via the Enter ACL. You can edit these via the context menu while being logged in with an account with appropriate permissions (typically as SuperUser)
