### ISSUE TITLE
Unable to receive Mumble Forms Verification Email

### ISSUE THREAD

**Issue by AlexGamerNice** [mumble-voip/mumble#5736]
### Description

When I attempt to create an account on the Mumble Forms it tells me to verify my account by an email sent to my address. No email is sent

### Steps to reproduce

1. Open Mumble Forms
2. Start a registration 
3. add all my details
4. Wait for the verification email to come

### Mumble version

None

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/64309667/177544864-65c084e8-0671-4c7d-bde4-2e77ee31d7c0.png)

**Comment by Krzmbrzl** [comment]
@davidebeatrici

**Comment by AlexGamerNice** [comment]
I still am not receiving a verification email, or even a password reset email. I check junk and looked everywhere in my inbox

**Comment by davidebeatrici** [comment]
I don't see you in the member list, could you try to register again?

**Comment by AlexGamerNice** [comment]
Tried again with another email still didn't work
