### ISSUE TITLE
client installer bug

### ISSUE THREAD

**Issue by bilbibalou** [mumble-voip/mumble#5737]
### The issue

hello due to an issue with the lastest version of mumble with mumble link mod minecraft i wanted to install the 1.3.3 release but when i install it on anothe folder i have an error not specified https://prnt.sc/hj0pgaOvQ7vN "the installation assistant ended prematurely"
so i tried to unistall my 1.4.230 with the control panel but it didn't work for 1 milisecond i see a windows oppening  and it instantly close i tryed same thing with windows option and settings -> app with the same result and Ccleaner again same thing
I downloaded the clientx86.msi and use it choosing repare and remove both also give the error
so I can't remove properly or install a new mumble have you an idea for fix it? or a software witch remove every files and folders of mumble on my computer? or have you the list where i can find them to remove them? or anything that can help me please
thank

### Mumble version

1.4.230 / 1.3.3

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you have any idea about this one?

If not, then my suggestion would be to manually remove the installed directories and also cleaning the respective registry sub-tree. I guess that should pretty much be equivalent to a regular uninstall :thinking:

**Comment by ZeroAbility** [comment]
I would try running the 1.4. install file again and see if there is an option to repair the 1.4 install. If it allows the 1.4. install to be repaired, then I would run the 1.4 install file again and chose the remove option. Then try to run the 1.3 install file again and see if the same error is present.

**Comment by bilbibalou** [comment]
i have already remove the installed directories but still have the error with the installer and I tried tu use the clientx86 1.4 to use the option repair and remove both give again and again the error

**Comment by Krzmbrzl** [comment]
After a quick Google search, I came up with https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d. This might be worth a try to see if it does any good.

Another thing to try would be to reboot in safe-mode and re-try the uninstall step (see also https://www.makeuseof.com/windows-cant-uninstall-program-fix/).

You said that you already removed the installation directories manually. Have you also tried to remove the corresponding registry keys manually?
For that open the registry editor (Win+R, then enter `regedit` and hit enter), locate `HKEY_CURRENT_USER\Software\Mumble` and delete the entire sub-tree (right-click on `Mumble` and choose delete).
