### ISSUE TITLE
Shortcuts no longer work in either 1.3.x or 1.4.x

### ISSUE THREAD

**Issue by jlandahl** [mumble-voip/mumble#5738]
### Description

A few months ago, I noticed my shortcut keys were no longer working. I tried reinstalling 1.4.x but it didn't help. I finally tried setting up new shortcuts with the same keys and functions and they worked. Only temporarily, though. If I had to restart my computer (or just Mumble) I had to set them up again, despite just adding the same shortcuts that were already there.

Now I've returned from being on a break for a month, started up my laptop, and found that now no matter how many times I add my shortcuts they simply will not work. This means I can't talk in Mumble. I uninstalled 1.4.x and installed 1.3.x and the exact same thing happens.

### Steps to reproduce

1. Open settings
2. Go to shortcuts
3. Add shortcut
4. Assign shortcut to whisper/shout
5. Set shortcut to current channel
6. Set shortcut key to anything

### Mumble version

1.3.x, 1.4.x

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by davidebeatrici** [comment]
Is the issue specific to the whisper/shout action?

**Comment by jlandahl** [comment]
I don't think so. It happens with PTT as well.

**Comment by jlandahl** [comment]
I just realized that I was relying on the overlay to determine if I was speaking or not. When I look at myself in the Mumble window my whisper/shout key does appear to be working in 1.3.x. But the overlay isn't working in general, even when others are speaking.

I also noticed that with my 5 button mouse, buttons 4 and 5 are both seen as the same button. I used to be able to assign them separately.

**Comment by davidebeatrici** [comment]
In 1.4.x, 1.3.x or both?

**Comment by jlandahl** [comment]
Sorry, tracking multiple weird things at once here.

The mouse button 4/5 thing showing up as the same button was affecting me in both 1.3.x and 1.4.x.

I'm currently on 1.3.x where I noticed the overlay not working. I'll try 1.4.x again and report back.

**Comment by jlandahl** [comment]
BTW just restarted 1.3.x and the whisper/shout shortcut works without me having to set it up again.

**Comment by davidebeatrici** [comment]
Consider that we completely revamped the system in 1.4.x and as a result settings are saved differently, causing shortcuts not to work if you go back to 1.3.x.

The opposite (upgrade) should work just fine though.

**Comment by jlandahl** [comment]
Quick update: I uninstalled 1.3.x and reinstalled 1.4.x and my whisper/shout shortcut worked without having to redefine it. Also the mouse4/mouse5 distinction is working as expected again. Now it looks like the only problem is that the overlay no longer works in Eve, so I'll close this ticket in favor of one for the overlay issue.
