### ISSUE TITLE
1.4.230 build fails

### ISSUE THREAD

**Issue by vitoyucepi** [mumble-voip/mumble#5742]
### Description

I found myself trying to rebuild mumble 1.4.230 after another update with custom settings.
But I failed to do that, because of error
```
CMake Error at overlay_gl/CMakeLists.txt:37 (CHECK_INCLUDE_FILE):
  Unknown CMake command "CHECK_INCLUDE_FILE".
```
Is it arch problem, or https://cmake.org/cmake/help/latest/module/CheckIncludeFile.html macros should be included in upstream?

### Steps to reproduce

1. Get archlinux. For example I test it with
   `docker run -it --rm archlinux bash`
2. Prepare building
   1. `pacman -Sy asp base-devel`
   2. `useradd -m user`
   3. `echo 'user ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers`
   5. `sudo -i -u user`
   6. `asp checkout mumble`
   7. `cd mumble/repos/community-x86_64`
   8. `gpg --recv-keys 25F63C66245DFC60`
3. `makepkg -s`

### Mumble version

1.4.230

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

I patched this problem with the following patch
```diff
--- a/overlay_gl/CMakeLists.txt
+++ b/overlay_gl/CMakeLists.txt
@@ -34,6 +34,7 @@ if(NOT APPLE)
 		# Just check for this header file while using a 32bit target as a really small and incomplete check whether g++-multilib seems to be
 		# installed. If we don't find it, we can assume it's not there but if we do find it, we still don't know. Thus we still print the
 		# message about the 32bit target potentially failing due to missing g++-multilib.
+		INCLUDE(CheckIncludeFile)
 		CHECK_INCLUDE_FILE("sys/cdefs.h" FOUND_CDEFS "-m32")
 		if(NOT FOUND_CDEFS)
 			message(FATAL_ERROR "Can't find the 32bit version of sys/cdefs.h - did you install g++-multilib?")
```

**Comment by Krzmbrzl** [comment]
Hm. Have you tried building it the traditional way using cmake directly? I have never seen this issue, so at least in general it appears that it is working as-is :thinking:

**Comment by vitoyucepi** [comment]
Found it.

```sh
wget https://github.com/mumble-voip/mumble/releases/download/v1.4.230/mumble-1.4.230.tar.gz
tar -xzf mumble-1.4.230.tar.gz
cd mumble-1.4.230.src
grep -rli CheckIncludeFile
```

```
3rdparty/opus/cmake/OpusConfig.cmake
3rdparty/opus/cmake/OpusFunctions.cmake
```

Option `-D bundled-opus=OFF` disables this includes.

**Comment by vitoyucepi** [comment]
Patch from downstream https://github.com/archlinux/svntogit-community/commit/32e22d3ad9a3a055c476320aef913bcb2f163754

```
# fix Unknown CMake command "CHECK_INCLUDE_FILE"
sed '1 i include(CheckIncludeFile)' -i overlay_gl/CMakeLists.txt
```
