### ISSUE TITLE
Voice Activation should have an option to set whisper or shout

### ISSUE THREAD

**Issue by strich** [mumble-voip/mumble#5745]
### Context

Voice activated comms is unfortunately useless as a feature for any mumble server that is setup to use any form of whisper/shout configuration amongst its channels. Right now it automatically shouts when voice is heard and comms are transmitted, which means any user on a mumble server that enforces any kind of whisper cannot use this feature.

### Description

The Voice Transmission settings should have an option to setup a default whisper/shout config. This can be copied from the shortcuts settings found when you configure a Whisper/Shout shortcut and configure the data for that shortcut.

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
I don't quite follow. Could you elaborate a bit more on the specific server configuration and client setup that you are talking about?

**Comment by strich** [comment]
The vast majority of Mumble servers I've ever used have setup a series of channels to use, and if you "shout" talk you will be talking across more than the channel you're in. So one must setup the whisper push to talk shortcut to avoid this. 
This means no one can use the voice activation feature because it only "shouts".

**Comment by Krzmbrzl** [comment]
Why would VAD cause one to shout? Without pushing any buttons, VAD should just cause regular speech in which case the folks in your channel should hear you and nobody else (potentially also users with listeners in your channel and channels that yours is linked with).

Or do you want to say that on these servers essentially all channels have been linked to each other such that regular speech will effectively be broadcast to all channels acting as if one had shouted to the Root channel?

**Comment by strich** [comment]
> Or do you want to say that on these servers essentially all channels have been linked to each other such that regular speech will effectively be broadcast to all channels acting as if one had shouted to the Root channel?
I believe that is the case yes. When I talk via VAD my icon goes "blue", which I assumed to be shout. Whisper is "orange".

**Comment by Krzmbrzl** [comment]
Shout is yellow. Blue just means regular speech.

In this case though, it does sound like a badly configured server to me :eyes:

**Comment by Krzmbrzl** [comment]
As I said: What you describe is the default behavior. If the server you are using changes this explicitly by using channel links, then this is their choice. There might be good reason to do so, but I don't see a reason for us to engineer a feature to work around such configuration. 

If you think that this setup is inappropriate, I suggest talking to the server admin.
