### ISSUE TITLE
Comment in section "welcometext" let Mumble Server ignore the whole config

### ISSUE THREAD

**Issue by r4dh4l** [mumble-voip/mumble#5749]
### Description

Context is: https://github.com/mumble-voip/mumble/issues/5702

### Steps to reproduce

1. Comment out something like this:

```
welcometext="<br />
<br />Welcome to ...
<br />...
<br />Etherpad needed?
;<br />-> <a href="https://pad.example.org/" style="color:green">pad.example.org</a>"
<br />-> <a href="https://pad.example2.org/" style="color:green">pad.example2.org</a>"
```

2. Restart Mumble Server and and client will report an invalid certificate because the server does not use the config file anymore.

### Mumble version

1.3.4

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by ppfeufer** [comment]
https://github.com/mumble-voip/mumble/issues/5702#issuecomment-1187428562

Please check this beforehand

Your "commented" line has a `"` at the end, which means the string is closed here. Noe the following line in your example would be the actual error...

I'm pretty sure that is the case here, not the "commented" line.

**Comment by ppfeufer** [comment]
Also all the other `"` in your example might cause the string to be interrupted.

Explanation:

In your example, you use `"` as delimiter for the welcome text string

```
welcometext="String does here"
```

As you can see, there is a `"` at the beginning and the end of the string. These tell the config parser where the string begins and ends ...

Now in your example:

```
welcometext="<br />
<br />Welcome to ...
<br />...
<br />Etherpad needed?
;<br />-> <a href="https://pad.example.org/" style="color:green">pad.example.org</a>"
```

The config parser will detect the string ending probably at `<a href="` as there is a `"`, which - as we have established - is used as string delimiter here.

So you might want to try something like this:

```
welcometext="<br />
<br />Welcome to ...
<br />...
<br />Etherpad needed?
;<br />-> <a href='https://pad.example.org/' style='color:green'>pad.example.org</a>"
```

Note that the double quotes (`"`) inside the `a`-tag are now replaced with single quotes (`'`), which should not end the string.

Please check this as well.

**Comment by ppfeufer** [comment]
Confirmed, just tested on my local test Mumble, it is the `"`

With:
```ini
welcometext="<br />
<br />Welcome to ...
<br />...
<br />Etherpad needed?
;<br />-> <a href='https://pad.example.org/' style='color:green'>pad.example.org</a>"
```
It is the expected result, the welcome text is the complete string, including the `;`

![image](https://user-images.githubusercontent.com/2989985/180010650-2a647f1c-302b-4d96-a3a1-8eaf882203b6.png)

**Comment by Krzmbrzl** [comment]
I think the actual issue here is that the server never reports that a syntax error was found and instead just silently discards the entire config file.
For the specific issue at hand, it is exactly as ppfeufer wrote.
