### ISSUE TITLE
Modify the Protocol page on the wiki

### ISSUE THREAD

**Issue by lolcatw** [mumble-voip/mumble#5759]
### The issue

Hello! Sorry about making the issue here, the account signup form does not work on the [mumble wiki](https://wiki.mumble.info/wiki/)! (Getting some kind of SMTP mail error...)

I want to make a quick edit inside this "Mumble" wiki. More precisely, this page right here: https://wiki.mumble.info/wiki/Protocol
I have made a mumble serber pinger in PHP (here: https://git.lolcat.ca/lolcat/mumble-ping) and it would mean alot to me if you could add it at the bottom of the page as reference, as it's easier to read than other implementations (that's only my opinion though, I'm not really used to python!)

Looking forward to the team's reply!
will

### Mumble version

1.3.4

### Mumble component

I don't know

### OS

Linux

**Comment by Krzmbrzl** [comment]
Added.

As a side-node (as I have seen the same typo in your post here on GH, the starting page of your git web page as well as in the README of the linked PHP implementation): It's ser**v**er and not ser**b**er :)

**Comment by powerjungle** [comment]
Wouldn't it makes sense to move the wiki to GitHub or make it as Sphinx documents?

**Comment by davidebeatrici** [comment]
Yes.

**Comment by powerjungle** [comment]
Also forgot to add, maybe something like Sphinx would be a better idea in case you want to move the repo elsewhere.
