### ISSUE TITLE
Selective Vocal

### ISSUE THREAD

**Issue by Aerolyse** [mumble-voip/mumble#5763]
### Context

Hello, 

im trying to setup an intercom system with wireless Raspberry Pi and a Mumble server but i was wondering is it to do selective vocal 

### Description

like when i press this Button i can talk to User 1 but User 2 and 3 can't hear me like a push to talk but a specific push to talk like when i press this button only those user can hear me (push to talk to)

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
Yes, this is what is called "whispering" in Mumble terms and is already implemented.
You can create a shortcut for Whispering/Shouting and then in the data configuration for that shortcut, just select the user you want to whisper to. That should be all that is needed.
