### ISSUE TITLE
Windows Notification incorrectly handles pasted images

### ISSUE THREAD

**Issue by Snowknight26** [mumble-voip/mumble#5764]
### Description

When someone pastes an image from the clipboard to Mumble, a Windows notification is shown if enabled, but the notification shows a Unicode Object Replacement Character instead (￼, U+FFFC).

### Steps to reproduce

1. Open Mumble
2. Connect to a server
3. Paste an image from the clipboard into the chatbox

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/5608270/181678478-cdb7e6d1-33ca-4d4d-8024-a68db0070847.png)

**Comment by Snowknight26** [comment]
I think the issue stems from https://github.com/mumble-voip/mumble/blob/0b7d5f3f391cae6389a577af0ff0df3a3745fb6b/src/mumble/Log.cpp#L663

At least the [Qt documentation](https://code.woboq.org/qt5/qtbase/src/gui/text/qtextdocument.cpp.html#1184) says as much:
>  \note Embedded objects, such as images, are represented by a
    Unicode value U+FFFC (OBJECT REPLACEMENT CHARACTER).

**Comment by Krzmbrzl** [comment]
I think we probably don't want to show the image itself anyway. Maybe we could simply replace that unicode character by some placeholder text like `(image)` or `(embedded content)` :thinking:

**Comment by Snowknight26** [comment]
`[embedded content]` was what I was thinking (brackets, not parenthesis, to match the current style). Would this need to be a translatable string via `tr()`? I'm asking in case I decide to make the change in an upcoming PR.

**Comment by Krzmbrzl** [comment]
> [embedded content] was what I was thinking (brackets, not parenthesis, to match the current style).

Right, even better :+1: 

> Would this need to be a translatable string via tr()?

Yes, I think it should be.
