### ISSUE TITLE
Server disappeared from the public list

### ISSUE THREAD

**Issue by skobkin** [mumble-voip/mumble#5774]
### The issue

Some time ago my server disappeared from the public listing.

Here's the configuration of the registration parameters:
```ini
registerName="mumble.skobk.in - Дегенератуша Скобкина"
registerHostname=mumble.skobk.in
registerPassword=<removed>
registerUrl=https://mumble.skobk.in/
#registerLocation=RU
```

I've also tried to enable `registerLocation` back, but id didn't have any effect.

What I see in the log:
```
murmur    | <W>2022-08-08 03:35:57.286 Shutting down
murmur    | Failed to set initial capabilities
murmur    | <X>2022-08-08 03:35:59.964 SSL: OpenSSL version is 'OpenSSL 1.1.1l  24 Aug 2021'
murmur    | <W>2022-08-08 03:35:59.967 Initializing settings from /config/murmur.ini (basepath /config)
murmur    | <C>2022-08-08 03:35:59.974 MetaParams: Adding 2 intermediate certificates from certificate file.
murmur    | <W>2022-08-08 03:36:00.809 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
murmur    | <C>2022-08-08 03:36:00.812 WARNING: You are running murmurd as root, without setting a uname in the ini file. This might be a security risk.
murmur    | <W>2022-08-08 03:36:00.813 Resource limits were 0 0
murmur    | <C>2022-08-08 03:36:00.813 Failed to set priority limits.
murmur    | <C>2022-08-08 03:36:00.813 Failed to set final capabilities
murmur    | <W>2022-08-08 03:36:00.847 ServerDB: Opened SQLite database /data/murmur.sqlite
murmur    | <W>2022-08-08 03:36:00.848 ServerDB: Using SQLite's default rollback journal.
murmur    | <W>2022-08-08 03:36:00.851 Murmur 1.4.0 (1.4.0) running on Linux: Alpine Linux v3.15 [x64]: Booting servers
murmur    | <W>2022-08-08 03:36:00.861 1 => Server listening on 0.0.0.0:64738
murmur    | <W>2022-08-08 03:36:07.389 1 => <0:(-1)> New connection: xx.xx.xx.xx:63891
murmur    | <W>2022-08-08 03:36:07.451 1 => <0:(-1)> Client version 1.4.230 (Windows Windows 10 Pro xxxx xxxx.xxxx [x64]: 1.4.230)
murmur    | <W>2022-08-08 03:36:07.462 1 => Starting voice thread
murmur    | <W>2022-08-08 03:36:07.465 1 => CELT codec switch ffffffff8000000b 0 (prefer ffffffff8000000b) (Opus 1)
murmur    | <W>2022-08-08 03:36:07.474 1 => <1:skobkin(1)> Authenticated
<...>
```

Murmur is running in the Docker (built by me because official Murmur build wasn't available). That is the reason why murmur says about running from root.

I'm not sure that the build specifics are somehow related, but I thought that it's better to point that than not. I also think that registration was working for some time because my server was the first in the region which switched to 1.4.0 because I built it myself and it was perfectly showing in the public list for some time.

I think that earlier when starting Murmur I saw something about registration (at least on previous version), but as you can see, nothing about that is showing now.

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

### Additional information

* [Docker image source](https://gitlab.com/skobkin/docker-murmur/-/blob/master/Dockerfile)
* [Image in the registry](https://gitlab.com/skobkin/docker-murmur/container_registry/2667847)

**Comment by davidebeatrici** [comment]
Is the server publicly reachable? Does it have a valid certificate?

**Comment by skobkin** [comment]
Yes, at least I don't see any signs of it to be unavailable. You can check it out yourself, the `registerHostname` value from the config is valid.
Me, a bunch of my friends and some of users who were using it before it got unlisted are still using it. But most of the users who were choosing the server due to the lowest ping available in the public list are now gone.

**Comment by skobkin** [comment]
I'll leave a comment then...

**Comment by Krzmbrzl** [comment]
@davidebeatrici

**Comment by skobkin** [comment]
Today I found out that mine is in the list again. And I didn't do anything to achieve that...

**Comment by Krzmbrzl** [comment]
Hm - then maybe this was just another instance of the registration service taking forever to update for some reason :eyes: 

In this case I'll close this issue. Please let us know, should it disappear again.
