### ISSUE TITLE
HyperX headset sounds static-filled when using Mumble during FiveM

### ISSUE THREAD

**Issue by LoganW156** [mumble-voip/mumble#5787]
### The issue

I've been having issues between the Hyper X Cloud II headset and Mumble while playing FiveM. I've been told it sounds very static-filled and sometimes not even intelligible. I don't have any static issues with other applications. Has anyone heard of a possible fix?

### Mumble version

1.4.0

### Mumble component

I don't know

### OS

Windows

**Comment by Krzmbrzl** [comment]
Have you tried disabling echo cancellation and noise cancelling? Especially disabling RNNoise, which was shown to cause issues in certain setups (but was turned on by default in 1.4.230)

**Comment by LoganW156** [comment]
I haven't. What's the best way to do that?

**Comment by Krzmbrzl** [comment]
In the audio input settings

**Comment by Krzmbrzl** [comment]
Since no further response was given, I'll close this issue as _resolved_
