### ISSUE TITLE
Cannot get self hosted server to show up in public server list

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5791]
### The issue

I have tried over a dozen times to get my self hosted server to appear on the Mumble public server list.

- I tried this setup on Linux Mint with Murmur 1.3.0 and Windows 1.4.230
- I am using a different port than the default port number 64738 and I am using a VPN with port forwarding. I did set the port number in the INI file and I know my port forwarding it working since I was able to connect to my server using my VPN's IP address with the port number I forwarded to connect to my server from my phone using the Mumla client.
- I am able to see my server in the mumble client on the self host computer under LAN in the mumble client connect menu
- I do not have a domain name, however I do see servers in the public server without a domain name

I will provide my INI file in the additional notes, however I did change my port number and passwords for security reasons.

### Mumble version

1.3.0 & 1.4.230

### Mumble component

Server

### OS

Linux, Windows

### Additional information

```
; Murmur configuration file.
;
; General notes:
; * Settings in this file are default settings and many of them can be overridden
;   with virtual server specific configuration via the Ice or DBus interface.
; * Due to the way this configuration file is read some rules have to be
;   followed when specifying variable values (as in variable = value):
;     * Make sure to quote the value when using commas in strings or passwords.
;        NOT variable = super,secret BUT variable = "super,secret"
;     * Make sure to escape special characters like '\' or '"' correctly
;        NOT variable = """ BUT variable = "\""
;        NOT regex = \w* BUT regex = \\w*

; Path to database. If blank, will search for
; murmur.sqlite in default locations or create it if not found.
database=/var/lib/mumble-server/mumble-server.sqlite

; Murmur defaults to using SQLite with its default rollback journal.
; In some situations, using SQLite's write-ahead log (WAL) can be
; advantageous.
; If you encounter slowdowns when moving between channels and similar
; operations, enabling the SQLite write-ahead log might help.
;
; To use SQLite's write-ahead log, set sqlite_wal to one of the following
; values:
;
; 0 - Use SQLite's default rollback journal.
; 1 - Use write-ahead log with synchronous=NORMAL.
;     If Murmur crashes, the database will be in a consistent state, but
;     the most recent changes might be lost if the operating system did
;     not write them to disk yet. This option can improve Murmur's
;     interactivity on busy servers, or servers with slow storage.
; 2 - Use write-ahead log with synchronous=FULL.
;     All database writes are synchronized to disk when they are made.
;     If Murmur crashes, the database will be include all completed writes.
;sqlite_wal=0

; If you wish to use something other than SQLite, you'll need to set the name
; of the database above, and also uncomment the below.
; Sticking with SQLite is strongly recommended, as it's the most well tested
; and by far the fastest solution.
;
;dbDriver=QMYSQL
;dbUsername=
;dbPassword=
;dbHost=
;dbPort=
;dbPrefix=murmur_
;dbOpts=

; Murmur defaults to not using D-Bus. If you wish to use dbus, which is one of the
; RPC methods available in Murmur, please specify so here.
;
;dbus=system

; Alternate D-Bus service name. Only use if you are running distinct
; murmurd processes connected to the same D-Bus daemon.
;dbusservice=net.sourceforge.mumble.murmur

; If you want to use ZeroC Ice to communicate with Murmur, you need
; to specify the endpoint to use. Since there is no authentication
; with ICE, you should only use it if you trust all the users who have
; shell access to your machine.
; Please see the ICE documentation on how to specify endpoints.
#ice="tcp -h 127.0.0.1 -p 6502"

; Ice primarily uses local sockets. This means anyone who has a
; user account on your machine can connect to the Ice services.
; You can set a plaintext "secret" on the Ice connection, and
; any script attempting to access must then have this secret
; (as context with name "secret").
; Access is split in read (look only) and write (modify)
; operations. Write access always includes read access,
; unless read is explicitly denied (see note below).
;
; Note that if this is uncommented and with empty content,
; access will be denied.

;icesecretread=
icesecretwrite=

; If you want to expose Murmur's experimental gRPC API, you
; need to specify an address to bind on.
; Note: not all builds of Murmur support gRPC. If gRPC is not
; available, Murmur will warn you in its log output.
;grpc="127.0.0.1:50051"
; Specifying both a certificate and key file below will cause gRPC to use
; secured, TLS connections.
;grpccert=""
;grpckey=""

; How many login attempts do we tolerate from one IP
; inside a given timeframe before we ban the connection?
; Note that this is global (shared between all virtual servers), and that
; it counts both successfull and unsuccessfull connection attempts.
; Set either Attempts or Timeframe to 0 to disable.
;autobanAttempts = 10
;autobanTimeframe = 120
;autobanTime = 300

; Specifies the file Murmur should log to. By default, Murmur
; logs to the file 'murmur.log'. If you leave this field blank
; on Unix-like systems, Murmur will force itself into foreground
; mode which logs to the console.
logfile=/var/log/mumble-server/mumble-server.log

; If set, Murmur will write its process ID to this file
; when running in daemon mode (when the -fg flag is not
; specified on the command line). Only available on
; Unix-like systems.
pidfile=/run/mumble-server/mumble-server.pid

; The below will be used as defaults for new configured servers.
; If you're just running one server (the default), it's easier to
; configure it here than through D-Bus or Ice.
;
; Welcome message sent to clients when they connect.
; If the welcome message is set to an empty string,
; no welcome message will be sent to clients.
welcometext="Welcome to my server!"

; Port to bind TCP and UDP sockets to.
port=55555

; Specific IP or hostname to bind to.
; If this is left blank (default), Murmur will bind to all available addresses.
;host=

; Password to join server.
serverpassword=password to join

; Maximum bandwidth (in bits per second) clients are allowed
; to send speech at.
bandwidth=72000

; Maximum number of concurrent clients allowed.
users=6

; Per-user rate limiting
;
; These two settings allow to configure the per-user rate limiter for some
; command messages sent from the client to the server. The messageburst setting
; specifies an amount of messages which are allowed in short bursts. The
; messagelimit setting specifies the number of messages per second allowed over
; a longer period. If a user hits the rate limit, his packages are then ignored
; for some time. Both of these settings have a minimum of 1 as setting either to
; 0 could render the server unusable.
messageburst=5
messagelimit=1

; Respond to UDP ping packets.
;
; Setting to true exposes the current user count, the maximum user count, and
; the server's maximum bandwidth per client to unauthenticated users. In the
; Mumble client, this information is shown in the Connect dialog.
allowping=true

; Amount of users with Opus support needed to force Opus usage, in percent.
; 0 = Always enable Opus, 100 = enable Opus if it's supported by all clients.
;opusthreshold=100

; Maximum depth of channel nesting. Note that some databases like MySQL using
; InnoDB will fail when operating on deeply nested channels.
;channelnestinglimit=10

; Maximum number of channels per server. 0 for unlimited. Note that an
; excessive number of channels will impact server performance
;channelcountlimit=1000

; Regular expression used to validate channel names.
; (Note that you have to escape backslashes with \ )
;channelname=[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|]+

; Regular expression used to validate user names.
; (Note that you have to escape backslashes with \ )
;username=[-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+

; Maximum length of text messages in characters. 0 for no limit.
;textmessagelength=5000

; Maximum length of text messages in characters, with image data. 0 for no limit.
;imagemessagelength=131072

; Allow clients to use HTML in messages, user comments and channel descriptions?
;allowhtml=true

; Murmur retains the per-server log entries in an internal database which
; allows it to be accessed over D-Bus/ICE.
; How many days should such entries be kept?
; Set to 0 to keep forever, or -1 to disable logging to the DB.
;logdays=31

; To enable public server registration, the serverpassword must be blank, and
; this must all be filled out.
; The password here is used to create a registry for the server name; subsequent
; updates will need the same password. Don't lose your password.
; The URL is your own website, and only set the registerHostname for static IP
; addresses.
; Only uncomment the 'registerName' parameter if you wish to give your "Root" channel a custom name.
;
registerName=My Mumber Server Alpha
registerPassword=ZF57Fl88EEV8IaWBkSbHHthY9X91xg3s
registerUrl=http://www.mywebsite.com/
registerHostname=
registerLocation=AT

; If this option is enabled, the server will announce its presence via the
; bonjour service discovery protocol. To change the name announced by bonjour
; adjust the registerName variable.
; See http://developer.apple.com/networking/bonjour/index.html for more information
; about bonjour.
;bonjour=True

; If you have a proper SSL certificate, you can provide the filenames here.
; Otherwise, Murmur will create its own certificate automatically.
;sslCert=
;sslKey=

; The sslDHParams option allows you to specify a PEM-encoded file with
; Diffie-Hellman parameters, which will be used as the default Diffie-
; Hellman parameters for all virtual servers.
;
; Instead of pointing sslDHParams to a file, you can also use the option
; to specify a named set of Diffie-Hellman parameters for Murmur to use.
; Murmur comes bundled with the Diffie-Hellman parameters from RFC 7919.
; These parameters are available by using the following names:
;
; @ffdhe2048, @ffdhe3072, @ffdhe4096, @ffdhe6144, @ffdhe8192
;
; By default, Murmur uses @ffdhe2048.
;sslDHParams=@ffdhe2048

; The sslCiphers option chooses the cipher suites to make available for use
; in SSL/TLS. This option is server-wide, and cannot be set on a
; per-virtual-server basis.
;
; This option is specified using OpenSSL cipher list notation (see
; https://www.openssl.org/docs/apps/ciphers.html#CIPHER-LIST-FORMAT).
;
; It is recommended that you try your cipher string using 'openssl ciphers <string>'
; before setting it here, to get a feel for which cipher suites you will get.
;
; After setting this option, it is recommend that you inspect your Murmur log
; to ensure that Murmur is using the cipher suites that you expected it to.
;
; Note: Changing this option may impact the backwards compatibility of your
; Murmur server, and can remove the ability for older Mumble clients to be able
; to connect to it.
;sslCiphers=EECDH+AESGCM:EDH+aRSA+AESGCM:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA

; If Murmur is started as root, which user should it switch to?
; This option is ignored if Murmur isn't started with root privileges.
uname=mumble-server

; If this options is enabled, only clients which have a certificate are allowed
; to connect.
;certrequired=False

; If enabled, clients are sent information about the servers version and operating
; system.
;sendversion=True

; This sets password hash storage to legacy mode (1.2.4 and before)
; (Note that setting this to true is insecure and should not be used unless absolutely necessary)
;legacyPasswordHash=false

; By default a strong amount of PBKDF2 iterations are chosen automatically. If >0 this setting
; overrides the automatic benchmark and forces a specific number of iterations.
; (Note that you should only change this value if you know what you are doing)
;kdfIterations=-1

; You can configure any of the configuration options for Ice here. We recommend
; leave the defaults as they are.
; Please note that this section has to be last in the configuration file.
;
[Ice]
Ice.Warn.UnknownProperties=1
Ice.MessageSizeMax=65536
```

**Comment by Krzmbrzl** [comment]
What's the log output when starting your server?

**Comment by trymeouteh** [comment]
Here is a log using v1.3.0 on Linux Mint.

`<W>2022-08-12 11:43:23.933 SSL: OpenSSL version is 'OpenSSL 1.1.1f  31 Mar 2020'
<W>2022-08-12 11:43:23.933 Initializing settings from /etc/mumble-server.ini (basepath /etc)
<W>2022-08-12 11:43:24.106 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-08-12 11:43:24.123 ServerDB: Opened SQLite database /var/lib/mumble-server/mumble-server.sqlite
<W>2022-08-12 11:43:24.123 ServerDB: Using SQLite's default rollback journal.
<W>2022-08-12 11:43:24.145 Murmur 1.3.0 (1.3.0+dfsg-1ubuntu0.1) running on X11: Linux Mint 20.1: Booting servers
<W>2022-08-12 11:43:24.224 1 => Server listening on 0.0.0.0:44141
<W>2022-08-12 11:43:24.515 1 => Announcing server via bonjour
<W>2022-08-12 11:43:24.591 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.
<W>2022-08-12 11:43:36.215 1 => <1:(-1)> New connection: 127.0.0.1:50240
<W>2022-08-12 11:43:36.390 1 => <1:(-1)> Client version 1.3.0 (X11: 1.3.0+dfsg-1ubuntu0.1)
<W>2022-08-12 11:43:36.522 1 => Starting voice thread
<W>2022-08-12 11:43:36.598 1 => CELT codec switch ffffffff8000000b 0 (prefer ffffffff8000000b) (Opus 1)
<W>2022-08-12 11:43:36.732 1 => <1:SuperUser(0)> Authenticated
<W>2022-08-12 11:44:38.711 1 => <2:(-1)> New connection: 82.221.107.187:58734
<W>2022-08-12 11:44:41.152 1 => <2:(-1)> Client version 1.2.5 (Android: Mumla 3.6.3)
<W>2022-08-12 11:44:41.402 1 => <2:androidman(2)> Authenticated
<W>2022-08-12 11:44:58.593 1 => <2:androidman(2)> Connection closed: The TLS/SSL connection has been closed [1]
<W>2022-08-12 11:45:11.575 1 => <1:SuperUser(0)> Connection closed: The remote host closed the connection [1]
<W>2022-08-12 11:45:11.650 1 => Ending voice thread
<W>2022-08-12 11:47:02.467 1 => <3:(-1)> New connection: 91.115.31.44:36387
<W>2022-08-12 11:47:02.824 1 => <3:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 11:47:03.267 1 => <4:(-1)> New connection: 91.115.31.44:45229
<W>2022-08-12 11:47:03.351 1 => <4:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 11:57:48.602 1 => <5:(-1)> New connection: 202.142.113.206:48843
<W>2022-08-12 11:57:48.686 1 => <5:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 11:58:51.599 1 => <6:(-1)> New connection: 202.142.113.206:6883
<W>2022-08-12 11:58:51.674 1 => <6:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 11:59:56.795 1 => <7:(-1)> New connection: 202.142.113.206:26635
<W>2022-08-12 11:59:56.886 1 => <7:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:01:29.664 1 => <8:(-1)> New connection: 202.142.113.206:15255
<W>2022-08-12 12:01:29.756 1 => <8:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:03:54.580 1 => <9:(-1)> New connection: 202.142.113.206:35304
<W>2022-08-12 12:03:54.664 1 => <9:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:04:37.345 1 => <10:(-1)> New connection: 154.160.23.237:63606
<W>2022-08-12 12:04:37.420 1 => <10:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:05:04.327 1 => <11:(-1)> New connection: 185.21.217.34:49676
<W>2022-08-12 12:05:04.402 1 => <11:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:05:04.809 1 => <2:(-1)> New connection: 185.21.217.34:50472
<W>2022-08-12 12:05:04.959 1 => <2:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:06:21.581 1 => <1:(-1)> New connection: 202.142.113.206:49761
<W>2022-08-12 12:06:21.714 1 => <1:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:10:25.917 1 => <3:(-1)> New connection: 202.142.113.206:41189
<W>2022-08-12 12:10:25.992 1 => <3:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:14:05.621 1 => <4:(-1)> New connection: 185.21.217.34:39368
<W>2022-08-12 12:14:06.788 1 => <4:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:14:08.296 1 => <5:(-1)> New connection: 185.21.217.34:40886
<W>2022-08-12 12:14:09.428 1 => <5:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:18:36.755 1 => <6:(-1)> New connection: 202.142.113.206:37157
<W>2022-08-12 12:18:36.822 1 => <6:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:21:39.437 1 => <7:(-1)> New connection: 154.160.23.237:63612
<W>2022-08-12 12:21:39.552 1 => <7:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<W>2022-08-12 12:21:50.470 1 => <8:(-1)> New connection: 41.114.94.196:45069
<W>2022-08-12 12:21:50.553 1 => <8:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
<C>2022-08-12 12:24:06.099 Caught SIGTERM, exiting
<W>2022-08-12 12:24:06.099 Killing running servers
<W>2022-08-12 12:24:06.170 1 => Stopped announcing server via bonjour
<W>2022-08-12 12:24:06.253 1 => Stopped
<W>2022-08-12 12:24:06.254 Shutting down`

**Comment by trymeouteh** [comment]
And the logs for Windows 10 v1.4.230

```
<X>2022-08-12 12:45:19.205 SSL: OpenSSL version is 'OpenSSL 1.1.1k  25 Mar 2021'
<W>2022-08-12 12:45:19.212 Initializing settings from C:/Program Files/Mumble/server/murmur.ini (basepath C:/Program Files/Mumble/server)
<W>2022-08-12 12:45:19.379 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-08-12 12:45:19.379 Failed to open logfile murmur.log. No logging will be performed.
<W>2022-08-12 12:45:19.379 SSL: CA certificate filter applied. Filtered size: 96, original size: 96
<W>2022-08-12 12:45:19.394 ServerDB: Opened SQLite database C:/Users/LegoManIAm94/murmur.sqlite
<W>2022-08-12 12:45:19.394 ServerDB: Using SQLite's default rollback journal.
<W>2022-08-12 12:45:19.473 MurmurIce: Endpoint "tcp -h 127.0.0.1 -p 6502 -t 60000" running
<W>2022-08-12 12:45:19.473 Murmur 1.4.230 (1.4.230) running on Windows: Windows 10 Home 2009 19044.1889 [x64]: Booting servers
<W>2022-08-12 12:45:19.488 1 => Server listening on 0.0.0.0:55555
<W>2022-08-12 12:45:19.691 1 => Registering zeroconf service...
<W>2022-08-12 12:45:19.691 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.
<W>2022-08-12 12:45:41.176 1 => <0:(-1)> New connection: 127.0.0.1:60807
<W>2022-08-12 12:45:41.180 Connection: Failed to add flow to QOS
<W>2022-08-12 12:45:41.209 1 => <0:(-1)> Client version 1.4.230 (Windows Windows 10 Home 2009 19044.1889 [x64]: 1.4.230)
<W>2022-08-12 12:45:41.230 1 => Starting voice thread
<W>2022-08-12 12:45:41.235 1 => CELT codec switch ffffffff8000000b 0 (prefer ffffffff8000000b) (Opus 1)
<W>2022-08-12 12:45:41.248 1 => <1:winboy(2)> Authenticated
<W>2022-08-12 12:45:43.809 1 => <1:winboy(2)> Connection closed: The remote host closed the connection [1]
<W>2022-08-12 12:45:43.826 1 => Ending voice thread
```

**Comment by Krzmbrzl** [comment]
> <W>2022-08-12 11:43:24.591 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.

There you go - that seems to describe the problem, doesn't it? :eyes:
