### ISSUE TITLE
"What's this?" on User in TreeView has duplicate entry.

### ISSUE THREAD

**Issue by Hartmnt** [mumble-voip/mumble#5793]
### Description

The entry and icon "talking while being muted at your end" is duplicated.

### Steps to reproduce

1. Connect to a server
2. Use Help -> "what's this?" on any user
3. Observe the error

### Mumble version

``>= 1.4.0``

### Mumble component

Client

### OS

any

### Reproducible?

Yes

### Additional information

The string in the source code is simply copied and pasted an additional time by accident. The fix is trivial.

### Screenshots

![screenb](https://user-images.githubusercontent.com/1348773/184377391-01abccd6-3cca-4ee9-b83e-be2a179a30a0.png)

**Comment by Krzmbrzl** [comment]
Oh interesting. Probably got duplicated during resolving a metre conflict 👀
