### ISSUE TITLE
registerLocation Not working

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5798]
### The issue

My server on the public server list is listed under the country its IP address originates from and not the country which is set with the [registerLocation](https://wiki.mumble.info/wiki/Murmur.ini#registerLocation) in the INI file.

Here is how it looks in my INI file

`registerLocation=AT`

It should show up in Austria but it still show up in the country the IP address is from.

### Mumble version

1.3.0

### Mumble component

Server

### OS

Linux

**Comment by davidebeatrici** [comment]
#4742

**Comment by trymeouteh** [comment]
https://github.com/mumble-voip/mumble/issues/4742 seems to be about language, is registerLocation setting about language or the country a server is categorised under? To my understanding it is a country/region category and not a language category.

**Comment by davidebeatrici** [comment]
You're right, we never implemented the feature.

**Comment by trymeouteh** [comment]
Why is registerLocation in the [mumble wiki](https://wiki.mumble.info/wiki/Murmur.ini#registerLocation) if it was never implemented?

Is there a open feature request to add registerLocation feature to Murmur?

**Comment by davidebeatrici** [comment]
I was referring to the language list feature, `registerLocation` is simply not taken into account anymore.
