### ISSUE TITLE
Bring back registerLocation feature

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5800]
### Context

Bring back registerLocation in the murmur INI file.

### Description

Bring back registerLocation in the murmur INI file to allow servers to be listed under any country regardless of the servers location via IP address.

### Mumble component

Server

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
For what purpose? We already have a request to allow admins to specify a language for their server. This seems to be the only relevant information, so what would you use the country info for?

**Comment by trymeouteh** [comment]
If your self hosting a server behind a VPN. Your VPN server which is what the internet sees may not be the same country you are actually in. Therefor by being able to set what country your server is in, you can clarify the server true country regardless of what VPN server the murmur server is forwarded to.

**Comment by powerjungle** [comment]
Sure but the latency is dependent on the first server in this case. If the VPN is in the USA and your server is in Germany, isn't it better for the users to see where the connection starts? I know there are latency statistics as well, but I find it intuitive to be able to see the country as well.

**Comment by Krzmbrzl** [comment]
Yeah, but my question was more broadly: What is the user supposed to do with the information that a server is hosted in country X?

**Comment by trymeouteh** [comment]
The server country can tell a user where a server is actually hosted or for what country it is targeted for.

When it comes to latency, VPNs will cause a delay especially if your connecting to a server across the world, however VPNs are useful for the host users privacy.

**Comment by Krzmbrzl** [comment]
How is the host location relevant? 👀

And a server being meant for folks from a given country only, seems also a bit odd to me. I mean the only relevant infinite that I can see in that would be the language spoken on that server, but as mentioned earlier, there already is an open request for that.

**Comment by trymeouteh** [comment]
If a user wants to host a server for Irish people for example but your VPN provider or your Mumble server provider does not provide a server in Ireland, by changing the location to Ireland it will show up in the public server list under Ireland.

**Comment by Krzmbrzl** [comment]
Okay, I see. Note however that the categorization on countries in the public server list has been dropped in Mumble 1.4. Thus, this argument no longer applies.
Since then, servers are simply sorted by ping (by default).

We still display the country's flag next to the server-name, but I don't think it is worth it to have the ability for server-admins to select their preferred flag for this. Going forward, this should really be the preferred language on that server, which is covered by #4742.

**Comment by CGsama** [comment]
there are cases the location for the server not accurate at all, e.g. my server is locate at singapore, but in the software it shows at canada
