### ISSUE TITLE
registerHostname resolve?

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5801]
### The issue

It states the following in the [mumble wiki](https://wiki.mumble.info/wiki/Murmur.ini#registerHostname)

> This setting is the DNS hostname where your server can be reached. It only needs to be set if you want your server to be addressed in the server list by its hostname instead of by IP, but if it's set it must resolve on the internet or registration will fail.

By "Resolve" does this mean I need to add additional things to the INI file such as the domain name certificate? Or does the domain name need to to direct me to the IP address of the mumble server and nothing more?

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

**Comment by ZeroAbility** [comment]
That the hostname resolves to the correct IP address. Meaning, there has to be a host record for the name and the IP for that feature to work.

**Comment by trymeouteh** [comment]
> Meaning, there has to be a host record for the name and the IP for that feature to work.

The host record is not something I need to add to the murmur INI, it is on the domain registrar I use?

**Comment by Krzmbrzl** [comment]
Yes. This essentially means that if you are using a registerHostname of example.com, then when performing a regular DNS lookup (independent of Mumble) for example.com that this returns the IP of your server.
So as long as you have registered the domain specified there, you're good
