### ISSUE TITLE
Deafen self with Push to Talk

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#5804]
### Context

I'm unable to resolve a sound feedback issue due to our room's shape, speaker + mic placement, etc.

### Description

Can we add a option, near the Attenuate options, to deafen self on Push-to-Talk (or something more broadly applicable?)

Attenuate 100% does not reduce others' sound to zero.

### Mumble component

Client

### OS-specific?

No

**Comment by Hartmnt** [comment]
This is a duplicate of #5320

**Comment by Krzmbrzl** [comment]
Indeed - I was just about to write the same ^^
