### ISSUE TITLE
Text chat link detection should not be interrupted by %

### ISSUE THREAD

**Issue by alexbobp** [mumble-voip/mumble#5805]
### Description

Right now, mumble's http/https link detection gets interrupted by the % symbol.  That means a link such as
`https://example.com/path%20with%20spaces`
will be turned into a clickable link to (likely broken) `https://example.com/path`, followed by straggling plaintext.
Given % being a standard escape character for URL encoding, I can't help but call this a bug, even if minor.

### Steps to reproduce

Paste a URL into mumble plaintext chat containing % escape sequences.
Click the resulting link.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
This was already fixed in #5564
