### ISSUE TITLE
[macOS] mumble 1.4.274 is not code-signed

### ISSUE THREAD

**Issue by core-code** [mumble-voip/mumble#5815]
### Description

previous releases were properly signed [ Developer ID Application: Davide Beatrici (N83M93MNSH) ] but the latest version is not code-signed at all. 

### Steps to reproduce

1. download
2. try to launch.- prevented by gatekeeper

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Yes this is known. Apple is just ridiculous (again) and thus prevented us from doing as we did for 1.4.230

**Comment by davidebeatrici** [comment]
For reference, the details that we sent on Matrix:

> More specifically, Apple's web interface to manage certificates is absolutely atrocious :
>
> 1. No information (e.g. hash, date) whatsoever to identify a certificate, aside from the type (Application or Installer in our case).
> 2. Impossibility to delete a certificate, according to what I found you have to contact Apple: https://developer.apple.com/forums/thread/674115
> 3. A limit of 5 certificates per type, which we accidentally reached as we created one for each macOS machine and there was also extensive testing involved due to the official signing utilities being poorly made.

> Fortunately I should still have a pair (Application and Installer) of certificates on a MacBook, if there is interest in a signed (and notarized) release I can attempt to export them to our builder.
>
> I can't promise anything though. Also, I just received an email today: the Apple Developer subscription expires in 30 days and it's ~€100 per year.

**Comment by core-code** [comment]
thanks for the info, lets close this
