### ISSUE TITLE
No 32 bit Windows client download available in GitHub release for v1.4.274

### ISSUE THREAD

**Issue by striezel** [mumble-voip/mumble#5824]
### Description

The GitHub release of version 1.4.274 (https://github.com/mumble-voip/mumble/releases/tag/v1.4.274) does fail to provide a MSI installer for 32 bit versions of the Windows client, i. e. __mumble_client-1.4.274-x86.msi__ is missing.

Since there is a signature file for it ([mumble_client-1.4.274-x86.msi.sig](https://github.com/mumble-voip/mumble/releases/download/v1.4.274/mumble_client-1.4.274-x86.msi.sig)), I suppose there should be an MSI file as well. Please add it to the release assets.

Thanks.

### Steps to reproduce

1. Go to release for v1.4.274: https://github.com/mumble-voip/mumble/releases/tag/v1.4.274
2. Try to find x86 MSI client installer.
3. It's not there.

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by striezel** [comment]
Yes, but why not add it to the existing release? AFAIK it is possible to add more files to a GitHub release after it has been released.

**Comment by davidebeatrici** [comment]
Done.

**Comment by striezel** [comment]
Thanks.

**Comment by Krzmbrzl** [comment]
> but why not add it to the existing release?

Because I was answering you from my phone - I intended to add it today, but apparently Davide was faster ^^
