### ISSUE TITLE
Cannot register or use push to talk keys on MacOS Mumble v1.4.274

### ISSUE THREAD

**Issue by Xuderis** [mumble-voip/mumble#5825]
### Description

Adding a new push to talk key does not work.  Pressing an existing push to talk key that was registered on a previous version does not work.  Issue occurs even when Mumble has Microphone, Accessibility, and Input Monitoring enabled in macOS System Preferences.

### Steps to reproduce

1. Open mumble
2. Connect to a server
3. Make sure you are unmuted
4. Press an existing push to talk key
5. Open preferences
6. Click "Audio Input"
7. Under "Transmission" select push to talk
8. Click "Shortcuts"
9. Check "Enable Global Shortcuts"
10. Click "Add"
11. Click "No buttons assigned"
12. Click "Add"
13. Press a keyboard key

### Mumble version

1.4.274

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

### Additional information

Downgrading to 1.4.230 and setting push to talk keys does not allow you to use them in 1.4.274.

**Comment by Krzmbrzl** [comment]
I'm pretty sure this is due to the binary not being signed. Check the settings where you should be able to grant Mumble accessibility access, which I believe was necessary to get shortcuts to work regardless.
Just another macOS stupidity :shrug:

**Comment by Xuderis** [comment]
From the description:
> Issue occurs even when Mumble has Microphone, Accessibility, and Input Monitoring enabled in macOS System Preferences.

I have confirmed that Mumble still has these permissions.  Any other ideas?

**Comment by Xuderis** [comment]
Okay, I removed access to Input Monitoring **and** Accessibility and it worked.  Thank you!

**Comment by Meghdeep** [comment]
> Okay, I removed access to Input Monitoring **and** Accessibility, then restored it by dragging it from Applications and it worked. Thank you!

How did you remove the permissions ? I'm having the same issue.

**Comment by Xuderis** [comment]
@Meghdeep 
Select the Mumble app and click the minus at the tbottom.

<img width="706" alt="Screenshot 2022-11-16 at 12 46 48" src="https://user-images.githubusercontent.com/45051192/202255005-9703c2e5-8f83-486a-bdb8-262dd69eff16.png">
