### ISSUE TITLE
Shutdown murmurd command?

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5829]
### The issue

Is there a command to shutdown a specific server instance? I like to run multiple servers and I use this command to start one of my server instances

`murmurd -ini "/home/john/Services/murmur 2.ini"`

Is there a way to shutdown a specific instance while keeping other instances running?

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
Iirc there is a possibility to do this via the Ice interface. But otherwise I wouldn't be aware of such a feature

**Comment by trymeouteh** [comment]
When the renaming from murmur to mumble-server is completed, will murmurd be renamed to mumble-serverd?

**Comment by Krzmbrzl** [comment]
No - the binary is called mumble-server and that is how it will remain

**Comment by trymeouteh** [comment]
By using the PID, you can shutdown the correct murmurd instance.

https://wiki.mumble.info/wiki/Murmur.ini#pidfile
