### ISSUE TITLE
Server disappeared from public list

### ISSUE THREAD

**Issue by BRUTme** [mumble-voip/mumble#5830]
### The issue

My server disappeared from public list when I updated to the first 1.4 version, I thought it is a bug, but today I updated to the newest 1.4.274 and still no visibility, so i decided to write here. I was using murmur for years and before no problem, I have the BRUT.me MURMUR Voice Chat server, the only server registered in Slovakia

### Mumble version

1.4.274

### Mumble component

Server

### OS

Windows

**Comment by Krzmbrzl** [comment]
Could you provide the server log produced during startup?

**Comment by BRUTme** [comment]
<X>2022-08-24 16:13:25.669 SSL: OpenSSL version is 'OpenSSL 1.1.1k  25 Mar 2021'
<W>2022-08-24 16:13:25.671 Initializing settings from C:/Program Files/Mumble/server/murmur.ini (basepath C:/Program Files/Mumble/server)
<W>2022-08-24 16:13:26.749 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-08-24 16:13:26.750 Failed to open logfile murmur.log. No logging will be performed.
<W>2022-08-24 16:13:26.768 SSL: CA certificate filter applied. Filtered size: 110, original size: 110
<W>2022-08-24 16:13:26.769 ServerDB: Opened SQLite database C:/Users/saradsmejem/murmur.sqlite
<W>2022-08-24 16:13:26.770 ServerDB: Using SQLite's default rollback journal.
<W>2022-08-24 16:13:26.772 Murmur 1.4.274 (1.4.274) running on Windows: Windows 8.1 - 6.3.9600: Booting servers
<W>2022-08-24 16:13:26.805 1 => Server listening on 0.0.0.0:64738
<W>2022-08-24 16:13:28.873 Zeroconf: Native mDNS/DNS-SD API not available, falling back to third-party API
<W>2022-08-24 16:13:28.874 Zeroconf: Failed to load dnssd.dll, assuming third-party API is not available

**Comment by Krzmbrzl** [comment]
Okay the log does not indicate any attempt at registering the server... could you also show me your init file (please redact any sensitive information as you see fit before posting here)

**Comment by BRUTme** [comment]
yes I saw your registration at our forum and your yesterdays thread here too, when u started firstly to run your server and add it to public list, I wish u luck with it, hope our server will be again visible there too

**Comment by BRUTme** [comment]
> Okay the log does not indicate any attempt at registering the server... could you also show me your init file (please redact any sensitive information as you see fit before posting here)

http://brut.me/brut/murmur.txt

I have read here that registerLocation does not work from 1.4 so I put # before it.

**Comment by Krzmbrzl** [comment]
> \# To enable public server registration, the serverpassword must be blank, and
\# this must all be filled out.

-> So maybe try un-commenting `registerHostname` and `registerLocation`? Also `registerHostname` should probably be set to `brut.me` in your case :thinking:

**Comment by BRUTme** [comment]
> > # To enable public server registration, the serverpassword must be blank, and
> > # this must all be filled out.
> 
> -> So maybe try un-commenting `registerHostname` and `registerLocation`? Also `registerHostname` should probably be set to `brut.me` in your case 🤔

I did it, but it seems not to work :/

**Comment by Krzmbrzl** [comment]
Could you give me the server log when using this new ini file?

**Comment by BRUTme** [comment]
<X>2022-08-25 12:41:42.697 SSL: OpenSSL version is 'OpenSSL 1.1.1k  25 Mar 2021'
<W>2022-08-25 12:41:42.699 Initializing settings from C:/Program Files/Mumble/server/murmur.ini (basepath C:/Program Files/Mumble/server)
<W>2022-08-25 12:41:43.668 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-08-25 12:41:43.669 Failed to open logfile murmur.log. No logging will be performed.
<W>2022-08-25 12:41:43.693 SSL: CA certificate filter applied. Filtered size: 110, original size: 110
<W>2022-08-25 12:41:43.694 ServerDB: Opened SQLite database C:/Users/brut/murmur.sqlite
<W>2022-08-25 12:41:43.694 ServerDB: Using SQLite's default rollback journal.
<W>2022-08-25 12:41:43.696 Murmur 1.4.274 (1.4.274) running on Windows: Windows 8.1 - 6.3.9600: Booting servers
<W>2022-08-25 12:41:43.725 1 => Server listening on 0.0.0.0:64738
<W>2022-08-25 12:41:44.738 Zeroconf: Native mDNS/DNS-SD API not available, falling back to third-party API
<W>2022-08-25 12:41:44.739 Zeroconf: Failed to load dnssd.dll, assuming third-party API is not available
<W>2022-08-25 12:41:48.363 1 => <0:(-1)> New connection: 21.21.120.59:49349
<W>2022-08-25 12:41:48.483 1 => <0:(-1)> Client version 1.3.4 ( : 1.3.4)
<W>2022-08-25 12:41:48.514 1 => Starting voice thread
<W>2022-08-25 12:41:48.530 1 => CELT codec switch ffffffff80000010 0 (prefer ffffffff80000010) (Opus 1)
<W>2022-08-25 12:41:48.559 1 => <1:DON-METAL(32)> Authenticated
<W>2022-08-25 12:43:06.793 1 => Registration failed: Permission denied

> Could you give me the server log when using this new ini file?

of course

<X>2022-08-25 12:41:42.697 SSL: OpenSSL version is 'OpenSSL 1.1.1k  25 Mar 2021'
<W>2022-08-25 12:41:42.699 Initializing settings from C:/Program Files/Mumble/server/murmur.ini (basepath C:/Program Files/Mumble/server)
<W>2022-08-25 12:41:43.668 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-08-25 12:41:43.669 Failed to open logfile murmur.log. No logging will be performed.
<W>2022-08-25 12:41:43.693 SSL: CA certificate filter applied. Filtered size: 110, original size: 110
<W>2022-08-25 12:41:43.694 ServerDB: Opened SQLite database C:/Users/brut/murmur.sqlite
<W>2022-08-25 12:41:43.694 ServerDB: Using SQLite's default rollback journal.
<W>2022-08-25 12:41:43.696 Murmur 1.4.274 (1.4.274) running on Windows: Windows 8.1 - 6.3.9600: Booting servers
<W>2022-08-25 12:41:43.725 1 => Server listening on 0.0.0.0:64738
<W>2022-08-25 12:41:44.738 Zeroconf: Native mDNS/DNS-SD API not available, falling back to third-party API
<W>2022-08-25 12:41:44.739 Zeroconf: Failed to load dnssd.dll, assuming third-party API is not available
<W>2022-08-25 12:41:48.363 1 => <0:(-1)> New connection: 21.21.120.59:49349
<W>2022-08-25 12:41:48.483 1 => <0:(-1)> Client version 1.3.4 ( : 1.3.4)
<W>2022-08-25 12:41:48.514 1 => Starting voice thread
<W>2022-08-25 12:41:48.530 1 => CELT codec switch ffffffff80000010 0 (prefer ffffffff80000010) (Opus 1)
<W>2022-08-25 12:41:48.559 1 => <1:DON-METAL(32)> Authenticated
<W>2022-08-25 12:43:06.793 1 => Registration failed: Permission denied

**Comment by Krzmbrzl** [comment]
> Registration failed: Permission denied

Okay - now we're at least a step further. For some reason the registration is failing, though...

@davidebeatrici do you have an idea?

**Comment by BRNSystems** [comment]
Isn't it possible, that he is using a wrong password?

**Comment by Krzmbrzl** [comment]
Maybe, yes :thinking: 
I am not too familiar with the entire process, so I'm not sure if that would result in a different error message or not...

**Comment by BRNSystems** [comment]
I would suggest changing name up a little to see if it was the case.
If it succeeds, then I think the password was wrong.
And I noticed, he is not using SSL certificates in mumble, and his website uses TLS so old, my browser refuses to display it.

**Comment by BRUTme** [comment]
I changed it, there was no error message, but I did not see the server appear in the public list, I have the same password from the beginning

yes I do not use SSL certificates, the old TLS  for web was for some testing purposes, it will be disabled in near future...

**Comment by BRNSystems** [comment]
I waited some time(one hour I think) and then it showed up. That is why I have two names of my server.
And a website without SSL? Every website with a login should have SSL.
And in my log, there is no registering, but it just works and it is present in the serverlist.
So I think, you should keep the changed name from a hour to a day and then check the server list in the mumble app again.

**Comment by BRUTme** [comment]
if I remember correctly, the server showed in a minute in times when it worked for me, I will test it again for an hour though in the night, because now I have people there
it is nearly impossible to update to the newest php and apache without loosing functionality, so thats why... people do not need to put any private information to our website

**Comment by Krzmbrzl** [comment]
Yeah, it can take quite a bit for a new server to appear in the public server list

**Comment by davidebeatrici** [comment]
> people do not need to put any private information to our website

But if they accidentally do and someone is monitoring their traffic it's over.

**Comment by BRUTme** [comment]
so I tried it and left for more hours, but no change, there are still Registration failed: Permission denied messages



> > people do not need to put any private information to our website
> 
> But if they accidentally do and someone is monitoring their traffic it's over.

I know, thats why all browsers warn them, I would have to build everything from scratch as phpBB software changed a lot from my version, I have a lot of mods and modifications and most of them arent converted to extensions, so for now it has to stay this way, but I want to make it safer as soon as possible of course

**Comment by BRNSystems** [comment]
> so I tried it and left for more hours, but no change, there are still Registration failed: Permission denied messages

I meant the subtly modified mame that did not give the message. And if that shows up, you were using a wrong password

**Comment by BRUTme** [comment]
I changed it the same way, how could my password be wrong, when I always use the same password / config only updated the program, there were some bigger changes in 1.4, but meanwhile I changed the IP address of my servers too, could this have something to do with this issue?

**Comment by davidebeatrici** [comment]
Is your Mumble server's certificate perhaps expired?

**Comment by BRUTme** [comment]
I do not know, everything works fine, just the public visibility not, how can I check?

**Comment by davidebeatrici** [comment]
When you're connected to the server you can see the certificate info from Mumble itself.

**Comment by BRNSystems** [comment]
He uses a self signed mumble cert

**Comment by BRNSystems** [comment]
And if someone is interested in connecting to him:

Address: brut.me
Port: 64738

**Comment by BRUTme** [comment]
right a self signed certificate from the beginning, and I was without any problem visible, the certificate was generated in the year 2018

**Comment by BRUTme** [comment]
is there anything what can I do to fix this issue? werent there any changes to the cfg from the 1.4 version, or is the master server remembering the ip of the server too besides name and password?

**Comment by Krzmbrzl** [comment]
There have been no changes with regards to the registration procedure. 
As we have no idea why you are seeing the permission denied error, there is no way we could help you. 

In the meantime, have you attempted to simply create a completely separate server instance with custom INI file and a separate database and see if you can get that one to register (Using a different name and password). If that works, then the issue is somewhere in your other server's configuration. If it also doesn't work, it's either some sort of bug in Mumble that so far only seems to appear on your system or it is something about your system's configuration.

**Comment by BRUTme** [comment]
Hi, no it has not been fixed, or are u able to see my server between Slovak servers? I have just a lot of work these days so I did not have time to create a complete new server to test it, will do it in the next days
