### ISSUE TITLE
Hiding Icon Toolbar does not persist across Mumble sessions

### ISSUE THREAD

**Issue by kevinfiol** [mumble-voip/mumble#5832]
### Description

![image](https://user-images.githubusercontent.com/4752973/186559755-7757526d-debe-4a32-816d-8af474cc6ab0.png)

After upgrading from 1.4.230 to 1.4.274, the Icon Toolbar did not remain hidden even after unchecking `Icon Toolbar`.

Downgrading back to 1.4.230 fixed this for me.

### Steps to reproduce

1. Right-click on the empty space below the menubar
2. Uncheck `Icon Toolbar`
3. Restart Mumble. The Icon Toolbar is still visible, even though it was removed before restarting

Additionally, you can try unchecking it, and then go to Settings > User Interface and clicking `Apply`. This will make the icon toolbar reappear (it should not).

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
I wasn't even aware that these things could be hidden individually ^^

**Comment by Hartmnt** [comment]
Can confirm this behavior on Linux and on the 1.5 branch. You have to first set the user interface layout to "custom".

**Comment by Krzmbrzl** [comment]
I assume this issue was introduced with [6aa88691e16c807b998301f2cbecfda599ef4592](https://github.com/mumble-voip/mumble/commit/6aa88691e16c807b998301f2cbecfda599ef4592)
