### ISSUE TITLE
Font in console extremely small after update to 1.4.274

### ISSUE THREAD

**Issue by AirPhforce** [mumble-voip/mumble#5836]
### Description

After upgrading on Windows, the font size in the console is small. Noticeably smaller then it was before I upgraded and less the half the size of the channel list.

As there is no way to edit text size that I can see, and ctrl+scroll just makes all the text run over each other so what do I do to fix this? I hate needing to squint. I'm on a 2k monitor, don't know how this tiny font could be read on a 4k.

### Steps to reproduce

Upgrade to new version.

Open mumble.

Feast your eyes on text for ants.

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

[Pic](https://i.imgur.com/kU9aDor.png)

**Comment by Hartmnt** [comment]
Good news, this is a known bug of 1.4.274 and already fixed via #5820. (Duplicate #5818)

**Comment by BenJamesAndo** [comment]
I'm facing the same thing. Is there a beta release that I could use while I wait for the next official release?

**Comment by Krzmbrzl** [comment]
Not really (unless you were willing to use a 1.5 snapshot instead), but the fixed version is probably going to be released in the upcoming days anyway.
