### ISSUE TITLE
Mumble Channels

### ISSUE THREAD

**Issue by jaymoore962** [mumble-voip/mumble#5840]
### The issue

is there a way to have mutiple channels on 1 mumble server 

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

**Comment by davidebeatrici** [comment]
Yes, of course, it's a basic feature.

**Comment by Krzmbrzl** [comment]
You have to be logged in with an account that has the necessary permissions (e.g. the `SuperUser` account) and then you can add channels via the context menu.
