### ISSUE TITLE
Unable to click links in chat, chat overlapping 1 line

### ISSUE THREAD

**Issue by Nethya** [mumble-voip/mumble#5847]
### Description

Since the recent update I cannot click on links properly. Shown is cursor not changing and link not being clickable:
![image](https://user-images.githubusercontent.com/11967520/187549504-18335082-c699-4de9-aa0c-7af6b4fa1af3.png)

Text overlapped once right after the update, so it might be related:
![image](https://user-images.githubusercontent.com/11967520/187549753-32038d36-1dd3-48e9-bde2-88dbb80a5ec6.png)
  
However resizing window to cut text lines allows you to click on the broken part in the new line:
![image](https://user-images.githubusercontent.com/11967520/187550122-50030271-4abd-4cd0-bf17-5829676ae31f.png)

I will do a clean reinstall unless you need some logs or details.

### Steps to reproduce

1. Open Mumble
2. Try to click a link

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

Shown is cursor not changing and link not being clickable:
![image](https://user-images.githubusercontent.com/11967520/187549504-18335082-c699-4de9-aa0c-7af6b4fa1af3.png)

Text overlapped once right after the update, so it might be related:
![image](https://user-images.githubusercontent.com/11967520/187549753-32038d36-1dd3-48e9-bde2-88dbb80a5ec6.png)
  
However resizing window to cut text lines allows you to click on the broken part in the new line:
![image](https://user-images.githubusercontent.com/11967520/187550122-50030271-4abd-4cd0-bf17-5829676ae31f.png)

**Comment by Hartmnt** [comment]
Good news, this is a known bug of 1.4.274 and already fixed via #5820. (Duplicate #5818)

P.S. @Krzmbrzl Maybe you should seriously consider a hotfix release for this.

**Comment by Krzmbrzl** [comment]
The hotfix will come as soon as the version issue is fixed.

**Comment by Hartmnt** [comment]
> The hotfix will come as soon as the version issue is fixed.

Damn, that is what I was afraid of ;)

**Comment by Krzmbrzl** [comment]
Feel pressured :P
