### ISSUE TITLE
Inconsistent Mumble-Server behavior regarding the murmur.ini file

### ISSUE THREAD

**Issue by NiallEHunt** [mumble-voip/mumble#5848]
### Description

When installing Mumble-Server with the Windows installer, the murmur.ini settings file is not created/copied to the directory that the server is looking for. With the default installation settings murmur is looking in `C:/Users/<user>/AppData/Local/Mumble/Murmur` for the murmur.ini file. When navigating to this directory, you can see that no Mumble or Murmur folders were created and the murmur.ini file is nowhere to be found. 

Additionally, the Wiki pages all mention that the murmur.ini file is located in `C:/Program Files/Mumble`. There is no murmur.ini file present in this directory either.

Work around:
1. Navigate to `C:/Users/<user>/AppData/Local`
2. Create a folder called `Mumble` and navigate into that folder
3. Create a folder called `Murmur` and navigate into that folder
4. Create a file called `murmur.ini`
5. Copy the contents of the murmur.ini file from github ([link to file](https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini)) to your newly created file
6. Edit any settings you want for your server

### Steps to reproduce

1. Install Mumble-Server using the Windows MSI installer
2. Use the default installation settings
3. Run Mumble-Server and open the logs to see where it is trying to read the settings from

### Mumble version

1.4.274

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

### Additional information

Reproducible on Windows 10 and Windows 11.
Only tested with the x64 installer.

### Relevant log output

```shell
<X>2022-08-31 22:18:07.175 SSL: OpenSSL version is 'OpenSSL 1.1.1k  25 Mar 2021'
<W>2022-08-31 22:18:07.175 Initializing settings from C:/Users/Niall/AppData/Local/Mumble/Murmur/murmur.ini (basepath C:/Users/Niall/AppData/Local/Mumble/Murmur)
<W>2022-08-31 22:18:07.401 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-08-31 22:18:07.410 SSL: CA certificate filter applied. Filtered size: 102, original size: 102
<W>2022-08-31 22:18:07.410 ServerDB: Opened SQLite database C:/Users/Niall/murmur.sqlite
<W>2022-08-31 22:18:07.410 ServerDB: Using SQLite's default rollback journal.
<W>2022-08-31 22:18:07.410 Murmur 1.4.274 (1.4.274) running on Windows: Windows 10 Home 2009 22000.675 [x64]: Booting servers
<W>2022-08-31 22:18:07.426 1 => Server listening on 0.0.0.0:64738
<W>2022-08-31 22:18:07.646 1 => Registering zeroconf service...
<W>2022-08-31 22:18:07.646 1 => Not registering server as public
```

**Comment by NiallEHunt** [comment]
Presumably this is related to PR #4637? The ini file was removed from the installer as it was overwriting user's existing settings if I understand correctly

**Comment by Krzmbrzl** [comment]
Exactly - this is intended behavior

**Comment by Krzmbrzl** [comment]
See also #5694 and #5572

**Comment by NiallEHunt** [comment]
Interesting, thanks for the info and apologies for the duplicate. Can anyone update the Wiki? It seems this would be beneficial to mention there.

**Comment by Krzmbrzl** [comment]
Which page are your referring to specifically?

**Comment by NiallEHunt** [comment]
In the [Murmurguide](https://wiki.mumble.info/wiki/Murmurguide) on the wiki, specifically in the Preparations->Installation section and the Set Up Server->Configuring ini File section and in the [Installing Mumble](https://wiki.mumble.info/wiki/Installing_Mumble) page on the wiki, specifically in Windows->Mumble-Server (aka Murmur):

**Comment by NiallEHunt** [comment]
Would it make sense to mention it there?

**Comment by Krzmbrzl** [comment]
Well, looking at these pages, they are just completely outdated. So much so, that I don't think correcting information about the ini file actually makes a difference...
Someone would have to take the time to completely rewrite these pages

**Comment by NiallEHunt** [comment]
That is very fair. That makes a lot of sense to me. I see there is an ongoing effort to migrate the pages to the website as well. Thanks for the info and thanks for looking into this :)

**Comment by DesolatePsyche** [comment]
Link doesn't lead anymore to murmur.ini. Says page not found. So how I costumize my server port and such with newer mumble server versions lol?

**Comment by Krzmbrzl** [comment]
https://wiki.mumble.info/wiki/Murmur.ini

**Comment by moh21amed** [comment]
link to ini file is not working 
all online tutorials are outdated now
no GUI for setting change
I can't even change the server password or anything
hours lost trying all suggested solutions worst experience ever

**Comment by Krzmbrzl** [comment]
Step 1: Be able to use a text editor
Step 2: Create INI file with desired contents
Step 3: Start the server and tell it to use your initial file

Easiest fix ever

**Comment by Superfech** [comment]
> Step 1: Be able to use a text editor Step 2: Create INI file with desired contents Step 3: Start the server and tell it to use your initial file
> 
> Easiest fix ever

![image](https://user-images.githubusercontent.com/73236131/197678069-a4873c74-8e4c-4b97-a78d-028d0a99c7a5.png)


Please provide the correct link to the configuration model of this project that is unavailable. Please?

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/master/auxiliary_files/mumble-server.ini

**Comment by UBFI** [comment]
This is really stupid. The windows version of the server literally says that it loaded settings from the INI file but it doesnt exist.
![image](https://user-images.githubusercontent.com/69093516/223404904-550e3685-adb5-45e7-b39b-740e5fd2667a.png)
There is no Mumble folder in my local appdata. This needs to be fixed don't just call this a feature. There is no note no warning no error, nothing.

**Comment by Hartmnt** [comment]
> This is really stupid. The windows version of the server literally says that it loaded settings from the INI file but it doesnt exist. ![image](https://user-images.githubusercontent.com/69093516/223404904-550e3685-adb5-45e7-b39b-740e5fd2667a.png) There is no Mumble folder in my local appdata. This needs to be fixed don't just call this a feature. There is no note no warning no error, nothing.

I agree. The server logging that it is reading the INI file, when it is in fact not, seems like a valid bug to me. This is also independent of shipping an INI file by default, which the other linked issues are talking about. Ideally, the server should log that it did not find any INI file and is using default values or something.

**Comment by Krzmbrzl** [comment]
Please use a separate issue for this.
