### ISSUE TITLE
Does not build on i586 (GTAV plugin fails)

### ISSUE THREAD

**Issue by susnux** [mumble-voip/mumble#5849]
### Description

When building for i586 the GTAV Plugin fails (which is ok as the game only works on amd64), but rather then failing the i586 build should default to disable amd64 only plugins.

### Steps to reproduce

build on i586

### Mumble version

1.4.274

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Caused by memory alignment, which is different on 32 bit and 64 bit machines:

```
[ 1615s] In file included from /home/abuild/rpmbuild/BUILD/mumble-src/plugins/gtav/Game.h:9,
[ 1615s]                  from /home/abuild/rpmbuild/BUILD/mumble-src/plugins/gtav/gtav.cpp:6:
[ 1615s] /home/abuild/rpmbuild/BUILD/mumble-src/plugins/gtav/structs.h:218:37: error: static assertion failed
[ 1615s]   218 | static_assert(sizeof(CCameraAngles) == 0x408, "");
[ 1615s]       |               ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
[ 1615s] /home/abuild/rpmbuild/BUILD/mumble-src/plugins/gtav/structs.h:218:37: note: the comparison reduces to '(1028 == 1032)'
```

**Comment by Krzmbrzl** [comment]
> i586

What even is that?

**Comment by Krzmbrzl** [comment]
You'll have to build without plugins using `-Dplugins=OFF` when invoking cmake

**Comment by susnux** [comment]
> What even is that? Isn't this like archaically old?

32bit x86 processor.
There are still people running 32bit OS on their 64bit CPU for reasons. 

> You'll have to build without plugins using `-Dplugins=OFF` when invoking cmake

That will disable all plugins, while only one plugin is causing the build failure.

Currently I use this patch for building the latest release:
```diff
diff -Nur mumble-src/plugins/CMakeLists.txt new/plugins/CMakeLists.txt
--- mumble-src/plugins/CMakeLists.txt	2022-08-21 18:52:23.000000000 +0200
+++ new/plugins/CMakeLists.txt	2022-09-01 12:24:10.507433751 +0200
@@ -24,6 +24,9 @@
 
 foreach(ITEM ${ITEMS})
 	if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${ITEM}")
+		if (ITEM STREQUAL "gtav" AND CMAKE_SIZEOF_VOID_P LESS 8)
+			continue()
+		endif() 
 		set(PLUGIN_RETRACTED OFF)
 
 		# If the plugin is retracted the corresponding CMakeLists.txt is supposed to set the
```

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you think this is something we can fix in-code?

**Comment by davidebeatrici** [comment]
Yes, absolutely, we just have to force alignment.

> When building for i586 the GTAV Plugin fails (which is ok as the game only works on amd64), but rather then failing the i586 build should default to disable amd64 only plugins.

Back when we introduced the very first `x86_64` (`x64`, `amd64`) plugins, we excluded them from `x86` (`i386`, `i486`, `i586`, `i686`) builds as at the time our code did not support targeting processes with a different pointer size: #2607

The restriction was removed in #3262.

**Comment by davidebeatrici** [comment]
@susnux Could you verify that #5850 fixes the issue for you, please?

**Comment by susnux** [comment]
@davidebeatrici 

> Could you verify that #5850 fixes the issue for you, please?

Still getting this error 
[log.txt](https://github.com/mumble-voip/mumble/files/9472933/log.txt)

**Comment by davidebeatrici** [comment]
Fixed, sorry. Could you test again?

**Comment by susnux** [comment]
@davidebeatrici
> Fixed, sorry. Could you test again?

Now it works!

**Comment by davidebeatrici** [comment]
Excellent, thanks for testing!
