### ISSUE TITLE
"Failed to load the launcher entry proc" when running Team Fortress 2 with mumble overlay

### ISSUE THREAD

**Issue by carlocastoldi** [mumble-voip/mumble#5852]
### Description

After a quick search I know that between 17/02/2022 and 27/04/2022 TF2 fails to launch with the 32bit overlay. It instead crashes and throws a a strange error: `Failed to load the launcher entry proc`

it could be of some help that I found this very same `printf` in Counter Strike's leaked code (still Source engine like TF2 ): https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/launcher_main/main.cpp#L684

Today I even tried to downgrade `mumble`, `protobuf` and `poco` to the version prior to April 24th but without success. I still get the same error.
Setting up the a clean Ubuntu 22.04 virtual machine, installing Steam, TF2 & compiling mumble's 32bit overlay still doesn't seem to have fixed it

### Steps to reproduce

1. `cd /path/to/SteamLibrary/steamapps/common/Team\ Fortress\ 2`
2. `export LD_LIBRARY_PATH="$PWD/bin"`
3. `LD_PRELOAD=/usr/lib/mumble/libmumbleoverlay.x86.so:/usr/lib32/libGL.so ./hl2.sh -game tf` (on archlinux)
4. the game crashes immidiately

Without linking `libGL.so` I get the usuale `undefined symbol: glPopClientAttrib` error. Linking only `libGL.so` the game starts smoothly without errors (but no overlay, obv)

### Mumble version

1.4.230-13-x86_64

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

I am on Arch Linux with `poco 1.12.1-1`, `protobuf 21.4-1` and `libglvnd 1.4.0-3`

**Comment by Krzmbrzl** [comment]
What is the default value of `LD_PRELOAD` on your system? I would expect it to be empty, bur let's double check.

**Comment by carlocastoldi** [comment]
`echo $LD_PRELOAD` in both my host system and the Ubuntu VM return empty value :\

**Comment by Krzmbrzl** [comment]
@davidebeatrici any ideas?

**Comment by davidebeatrici** [comment]
The issue may be in https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/overlay_gl/init_unix.c#L130-L162

@carlocastoldi Could you try to export the `MUMBLE_OVERLAY_DEBUG` environment variable? It should enable debug logs.

**Comment by carlocastoldi** [comment]
> Could you try to export the MUMBLE_OVERLAY_DEBUG environment variable? It should enable debug logs.

```
LD_PRELOAD=/usr/lib/mumble/libmumbleoverlay.x86.so:/usr/lib32/libGL.so ./hl2.sh -game tf
ERROR: ld.so: object '/usr/lib/mumble/libmumbleoverlay.x86.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libGL.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/mumble/libmumbleoverlay.x86.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libGL.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: hashTable: 0xf7de5044, strTable: 0xf7de3314, symTable: 0xf7de3244
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Request for symbol; name: pthread_create, handle: (nil), odlsym: (nil)
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: hashTable: 0xf7de5044, strTable: 0xf7de3314, symTable: 0xf7de3244
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Request for symbol; name: pthread_create, handle: (nil), odlsym: (nil)
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: hashTable: 0xf7de5044, strTable: 0xf7de3314, symTable: 0xf7de3244
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Mumble overlay library loaded
MumbleOverlay: hashTable: 0xf7de5044, strTable: 0xf7de3314, symTable: 0xf7de3244
MumbleOverlay: Using DT_HASH
MumbleOverlay: Failed to find original address of dlsym().
MumbleOverlay: Request for symbol; name: LauncherMain, handle: 0x929c000, odlsym: (nil)
Failed to load the launcher entry proc
```

Note: the 4 `ld` errors are non-actual issues. If i remember correctly, even when the overlay worked they appeared to screen
