### ISSUE TITLE
Modify 3rd party page on the wiki

### ISSUE THREAD

**Issue by lolcatw** [mumble-voip/mumble#5854]
### The issue

Hello! It's me again...

I made a mumble music bot, since the other alternatives on github are either overengineered or straight up don't work, and I was wondering if anyone with the permission to do so could modify this page https://wiki.mumble.info/wiki/3rd_Party_Applications so that my bot could be included in the list of bots?

Here is the repo for Rena Mumble: https://git.lolcat.ca/lolcat/rena_mumble

Many thanks!!

### Mumble version

1.3.4

### Mumble component

Client

### OS

Linux

**Comment by Krzmbrzl** [comment]
From your repo's README:
> Welcome to the only working music bot for mumble (as of writing)!

That is just wrong. There's at least https://github.com/azlux/botamusique, which seems to be quite commonly used and last time I checked was working perfectly fine

**Comment by Krzmbrzl** [comment]
Done
