### ISSUE TITLE
Mumble Launcher Error -3

### ISSUE THREAD

**Issue by Namtrodar** [mumble-voip/mumble#5855]
### Description

After reinstalling Windows 10 Home Edition because of a booting problem, I downloaded the setup file mumble_client-1.4.274.x64 and started the setup. No Errors appaered. But when I want to launch the Program the Error appaers: Failed to load mumble_app.dll
I found the information that sometimes installing C++ helps. Did not worked for me.
So I uninstalled mumble and downloaded the file again. No Problems while installing the Program. But when I want to start it, the same error appears again.
Now I have no idea what else will help

### Steps to reproduce

Cleaned the disk and installed Windows 10 again. (It was Windows 10 before cleaning)
Started setup for Mumble.
Could not start the program.
Installed C++ 
Tried again to launch. Did not work either.
Uninstalled Mumble and downloaded the setup file again.
Installed Mumble again.
Count still not start the program.

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![Mumble Fehler](https://user-images.githubusercontent.com/112887835/188478999-9684e56c-3c46-461a-a21a-17d472d94996.jpg)

**Comment by Krzmbrzl** [comment]
> Installed C++

What do you mean by that? The C++ Redistributables? If so, which version did you install and where did you get it from?

**Comment by Namtrodar** [comment]
> > Installed C++
> 
> What do you mean by that? The C++ Redistributables? If so, which version did you install and where did you get it from?

Yes, I meant the Redistributables. I got it from microsoft.com and took the permalink for latest supported x86 version.

**Comment by Krzmbrzl** [comment]
So you are on a 32bit system? Are you sure about that? If not, you'll need the x86_64 ones 👀

**Comment by Namtrodar** [comment]
nope... i am on a 64bit system

**Comment by Krzmbrzl** [comment]
Yeah, then please try installing the x86_64 redistributables

**Comment by Namtrodar** [comment]
Well... I just installed now three different downloads... the last one worked... Thanks :-)
