### ISSUE TITLE
Publishing to Windows Package Manager (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [mumble-voip/mumble#5870]
### Context

Provide users an easier and more hassle-free install method on Windows.

### Description

Currently, both Mumble Client and Server are present in WinGet under the following identifiers:
- Client: `Mumble.Mumble`
- Server: `Mumble.Mumble.Server`

1. Would it be OK to move `Mumble.Mumble` to `Mumble.Mumble.Client` to keep consistency with the server package.
2. Feature request: Automate publishing to WinGet using GitHub Actions.

### Mumble component

Both

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
Hm? We don't provide any WinGet packages, so we don't control what name they use :eyes:

**Comment by Krzmbrzl** [comment]
Oho, wait. I just noticed that you seem to be the one currently providing the Mumble package(s) for WinGet, correct?

> Would it be OK to move Mumble.Mumble to Mumble.Mumble.Client to keep consistency with the server package.

Sure

> Feature request: Automate publishing to WinGet using GitHub Actions.

How would that look like? It seems like one had to create a PR against https://github.com/microsoft/winget-pkgs.
I'm not sure if we can easily automate that using GitHub Actions :eyes:

**Comment by vedantmgoyal2009** [comment]
You can easily do that using https://github.com/marketplace/actions/winget-releaser.

**Comment by Krzmbrzl** [comment]
Ah nice - would you mind creating a PR for adding a workflow for this?
