### ISSUE TITLE
Latest Mumble Server static release is nearly two years old

### ISSUE THREAD

**Issue by DC7IA** [mumble-voip/mumble#5877]
### Description

Hello,

the latest Murmur Static Release is murmur-static_x86-1.3.3.tar.bz2 and nearly two years old. Please release a new one.

### Steps to reproduce

Look at the Release Page

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Yes, there will be no static server anymore.
