### ISSUE TITLE
Mac Client not allowing me to set a shortcut key for push to talk

### ISSUE THREAD

**Issue by Meghdeep** [mumble-voip/mumble#5878]
### The issue

Initially the system said that I needed to provide the screen capture permission in order to accept a shortcut key, even after providing this permission, it does not accept any new keys.

I open the shortcut window and click on creating a new row, I set it to `push to talk` then when I click on the button to register the command it opens a new box with `Add` and `Remove` as options. Neither button does anything when I try to click it. The client asked for screen capture permissions and I provided it and still there is no change. 
<img width="666" alt="Screen Shot 2022-09-11 at 11 59 27 PM" src="https://user-images.githubusercontent.com/3457774/189543564-7c0f4d9a-0241-4682-93db-fc86cc5a3a89.png">
<img width="463" alt="Screen Shot 2022-09-11 at 11 59 21 PM" src="https://user-images.githubusercontent.com/3457774/189543566-ca0f00cd-e64e-4735-9f7c-4cdb942c7aa3.png">

### Mumble version

1.4.274

### Mumble component

Client

### OS

macOS

**Comment by Krzmbrzl** [comment]
Please see https://github.com/mumble-voip/mumble/issues/5825. Normally that should fix the issue

**Comment by mattkuzma** [comment]
I have the same issue after upgrading to Mumble (1.4.287)
In the Shortcuts pane, click shortcut, click add, nothing happens. Can't select a key to assign a shortcut to.

**Comment by Krzmbrzl** [comment]
Then I refer you to the same issue, that I linked above

**Comment by mattkuzma** [comment]
Thank you, clicked through the threads. This is the particular item that fixes it: Removing Mumble.app from the Accessibility permissions list, then manually adding it by dragging Mumble from the Finder to that permissions list. Now shortcuts work.

**Comment by Krzmbrzl** [comment]
Great to hear this! :+1: 
My guess is that macOS is stubborn, because 1.4.230 was signed and 1.4.274 and 1.4.287 are not anymore.

**Comment by afrofur** [comment]
This issue is not resolved for me. It's the same issue on every new release where you need to reinstate accessibility permissions. In this case though, manually removing and dragging the app back into the permissions list will not allow me to add a short cut key of choice. I'm limited to the keys: SHIFT, CONTROL, OPTION, COMMAND, CAPS LOCKS . No other key will register.

**Comment by Krzmbrzl** [comment]
Please read the linked issue
> I removed access to Input Monitoring and Accessibility, then restored it by dragging it from Applications and it worked

**Comment by mattkuzma** [comment]
Ugh - With Ventura 13.1 this problem has reappeared for me, and the new control panel doesn't look or work the same. Not able to assign PTT keys even after following the steps here.

**Comment by Krzmbrzl** [comment]
All Ivan say is that Mumble requires accessibility access to your computer. No idea how exactly this can be achieved on modern macOS :shrug:
