### ISSUE TITLE
1.4.274 chat pane in Windows is completely broken and other UI issues

### ISSUE THREAD

**Issue by Warmag2** [mumble-voip/mumble#5883]
### Description

Since update to 1.4.274, the UI has suffered a meltdown. The following issues are present:

- UI text scale, at least in chat panes, can no longer be changed
- Links in chat panes cannot be clicked or interacted with
- Pasted images will display very small in chat panes
- All icons after user names (checkmark for registration, personal note) are about half as large as normal and no longer fill the line they are placed on, like they are supposed to

After downgrading back to 1.4.230, all these issues vanish.

Tried workarounds (neither helped):

Delete mumble configuration from APPDATA and reinstall
Delete all mumble registry keys and configuration and reinstall

### Steps to reproduce

1. Install 1.4.274
2. Try to use the chat pane in any server in any channel in any way
3. Try to look at a users nameline

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

https://imgur.com/a/vTZ2IyX

**Comment by Krzmbrzl** [comment]
All has been reported before and has already been fixed. The fixes will be shipped with the next release sometime soon.
