### ISSUE TITLE
Bug fixes on master missing in 1.4.x branch

### ISSUE THREAD

**Issue by klemensn** [mumble-voip/mumble#5888]
### The issue

Is there any chance the following commits could make it into the next release?
Then OpenBSD can stop carrying them locally.

42ad5ed
ccbacbf
a707213
0c769d8
904bae1

### Mumble version

1.4.287

### Mumble component

Both

### OS

OpenBSD

**Comment by Krzmbrzl** [comment]
#5889 
I don't know if or when a new 1.4 release will happen. But if we create another one, these fixes will be contained :)
