### ISSUE TITLE
I have installed murmur, all works, I can hear but when I transmit, they cant hear me.

### ISSUE THREAD

**Issue by vipermz** [mumble-voip/mumble#5897]
### The issue

Hello, hope you can help. I recently had mumble all worked fine. Nit sure what happened but I reinstalled and updated mumble and murmur (running 1.3) . I can hear my friends talk form the outside but when I transmit they cannot see me, when I do the voice test all works but when I talk from the app, they cannot hear me. 

My question is, do you think firewalls are preventing this and if so, is it on the mumble side? Any work arounds on how to fix this. I have added mumble to the rules, it is both public and private and accepting connections, not sure what else I can do.

Please help me, 

Thank you.

### Mumble version

1.4.287

### Mumble component

Both

### OS

Windows

**Comment by Krzmbrzl** [comment]
You can go into the audio settings and choose Server Loopback. After applying the settings you should hear back everything you are saying. If that doesn't work, then there is an issue with your server connection.

**Comment by vipermz** [comment]
HI Robert,

Loopback test I can hear msyelf talk. The issue is transmitting to my friends, they cannot hear me but I can hear them

When I transmit, I see the blue, the mic system is working not sure what else it can be. Do you think it is firewall or something being preventing in the UDP or TCP ports?


________________________________

**Comment by vipermz** [comment]
SHould I be running x64 or z86 for server, and if my server is set up correctly with mumble 1.3.4, should I do it using a newer version if so which one?


________________________________

**Comment by Krzmbrzl** [comment]
> Loopback test I can hear msyelf talk.

Note that you should specifically use _server_ loopback mode. Did you use that? I'm asking because there also exists plain loopback mode, but that doesn't give you any information about the server connectivity.

> SHould I be running x64 or z86 for server

You should be running the version matching your host's architecture. So if your host is x64, you should also use the x64 server binary.

>  should I do it using a newer version if so which one?

Well by now we have released version 1.4.287, so in general that'd be the version I'd recommend. However, I don't think that this is related to the problem at hand.

**Comment by vipermz** [comment]
Seems everything or anything I do, nothing is heard on the other end of the communication.


  1.  Server seems to be working well
  2.  I created a new server from scratch,  all channels and all work well.
  3.  I can communicate fine within my home network but it is not able to go over the net.
  4.  I verified firewalls, all seems to be ok - private network and accepting all connections.

What can be the reason why I cannot broadcast over the net when all else is working^?

Any idea what I can do to verify if all is well. (I do hear my friends talking) They cannot hear me when I transmit.

Really appreciate your help,
________________________________

**Comment by vipermz** [comment]
This is my log:

<W>2022-09-22 20:42:16.247 SSL: OpenSSL version is 'OpenSSL 1.0.2u  20 Dec 2019'
<W>2022-09-22 20:42:16.248 Initializing settings from C:/Program Files (x86)/Mumble/murmur.ini (basepath C:/Program Files (x86)/Mumble)
<W>2022-09-22 20:42:16.396 MetaParams: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2022-09-22 20:42:16.404 SSL: CA certificate filter applied. Filtered size: 100, original size: 100
<W>2022-09-22 20:42:16.404 ServerDB: Opened SQLite database C:/Program Files (x86)/Mumble/murmur.sqlite
<W>2022-09-22 20:42:16.404 ServerDB: Using SQLite's default rollback journal.
<W>2022-09-22 20:42:16.409 MurmurIce: Endpoint "tcp -h 127.0.0.1 -p 6502 -t 60000" running
<W>2022-09-22 20:42:16.409 Murmur 1.3.3 (1.3.3) running on Win: Windows 8.1 x64 - 6.3.9600: Booting servers
<W>2022-09-22 20:42:16.621 1 => Server listening on 0.0.0.0:64740
<W>2022-09-22 20:42:16.798 Bonjour: Failed to load dnssd.dll
<W>2022-09-22 20:42:16.969 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.
________________________________

**Comment by davidebeatrici** [comment]
> <W>2022-09-22 20:42:16.969 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.

Have you done this?

**Comment by vipermz** [comment]
What needs to be done here?

The server is all named and channels done, how would I adress the below? I hear client voice. They cannot hear mine.



Sent from my iPhone

On Sep 22, 2022, at 9:17 PM, Davide Beatrici ***@***.***> wrote:

﻿

2022-09-22 20:42:16.969 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.

Have you done this?

**Comment by davidebeatrici** [comment]
Sorry, I confused this issue with #4569 (both notifications in my inbox at the same time).

Have you tried to force TCP mode in the client settings?

**Comment by Krzmbrzl** [comment]
So the server lives inspired local network? In that case it would appear as if for some reason something is preventing outgoing UDP packets from leaving your local network...

**Comment by vipermz** [comment]
So server is on a laptop, I had it working till jsut recently then all of a sudden, my friends cannot hear me despite me hearing them.

I re installed and created a server from scratch thinking it was an issue.  (no change)

I also change its port number to se emaybe my port was blocked. (no change)

Loop back test (server) - i hear voice

TCP FORCE    - yes but still nothing.

At this point I am out of ideas on what it can possibly be.



________________________________

**Comment by Krzmbrzl** [comment]
Do your friends hear each other?

**Comment by vipermz** [comment]
Yes so I read up on UDP ports and went into the windows firewall adamvanced settings and created an inbound rule for server port. Tested it today and it was working.

So maybe for future users experiencing theae issues, their modems may have blocked port and firewall may be blocking udp connextion.

All works fine now.

Thanks all for your help,



Sent from my iPhone

On Sep 23, 2022, at 4:04 PM, Robert Adam ***@***.***> wrote:

﻿

Do your friends hear each other?

**Comment by Krzmbrzl** [comment]
Okay great to hear you got it working now :+1:
And thanks for sharing your solution!
