### ISSUE TITLE
Allow user to select install directory or drive

### ISSUE THREAD

**Issue by crius-al** [mumble-voip/mumble#5901]
### Context

Installing mumble

### Description

When I installed mumble, it forced itself onto my C: system drive which is an ssd exclusively for the operating system. Applications need to go on my D: drive.
Older mumble installs allowed alternative install locations. The newest mumble does not.

### Mumble component

Client

### OS-specific?

Yes

**Comment by davidebeatrici** [comment]
Duplicate of #4702.
