### ISSUE TITLE
Mumble Push to Talk no longer works in Mac OS Ventura Beta

### ISSUE THREAD

**Issue by rickenwing** [mumble-voip/mumble#5910]
### Description

Version: Mumble 1.4.287
OS: Mac OS Ventura Beta 9
Machine: M1 pro Macbook pro 16 inch, also tested macbook air intel

Issue started I believe with Venutra Beta 8, but since updating push to talk no longer functions, any attempts to re-register push to talk keys fails as the window "edit shortcuts" fails to register any keys. 

- Confirmed Mumble has appropriate permissions under Privacy and Security (input monitoring, accessibility, and microphone)

- "Push to talk" will work with the Mumble PTT window but any previously registered keys for push to talk do not work.

- Tried removing Mumble completely and installing fresh, no dice. 

I understand this is running on Beta OS software and not necessarily seeking a fix, but reporting this more for awareness and to see if others have run into this issue. I will spend some time trying to find a workaround. 

### Steps to reproduce

1. Update to at least Ventura Beta 8 or 9
2. Any previously registered push to talk key combinations will no longer work.
3. Trying to register any new ones will fail as the edit shortcuts won't register any key combinations, either singular or combos. 

### Mumble version

1.4.287

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Plesse see #5825

**Comment by rickenwing** [comment]
Ah thank you, I was searching for Ventura. I re-tried removing the permissions and re-adding them and that fixed the issue.

**Comment by Krzmbrzl** [comment]
Great to hear that!

**Comment by nissaba** [comment]
Getting same problem, reset permissions still not able to use PTT
