### ISSUE TITLE
Tray icon has name of server on it

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5914]
### Context

The name of the server will be listed in the mumble server (murmur) tray icon.

### Description

The name of the server will be listed in the mumble server (murmur) tray icon.

This way if your running multiple servers and have multiple mumble server (murmur) tray icons in your tray, you will know which tray icon is for which server and always shutdown the correct server.

### Mumble component

Server

### OS-specific?

No

### Additional information

Would be great to get a tray icon for mumble server (murmur) on Linux.
https://github.com/mumble-voip/mumble/issues/5913

**Comment by Krzmbrzl** [comment]
No, this is not going to happen. There is just too little space on a tray icon to write server names onto it. It might work for really short server names, but in the general case it won't. 

And all workarounds that would then only show partial server names or something like this don't seem to be worth it.

**Comment by davidebeatrici** [comment]
It would make more sense to print info in a tooltip.

**Comment by trymeouteh** [comment]
> It would make more sense to print info in a tooltip.

That will work also, as long the user can tell which server is which.

**Comment by Krzmbrzl** [comment]
That would still not make that much sense, since you can (and should) host multiple servers through a single server instance by making use of the virtual server feature. In that case however, there will only be a single tray icon, bur multiple servers.
