### ISSUE TITLE
Mumble as intercom for video production

### ISSUE THREAD

**Issue by Michal123456747** [mumble-voip/mumble#5920]
### The issue

I am going to use Mumble as intercom for video production and I have a few questions about that:
1. When I have linked for example 2 child channels and 1 master channel, can I mute one of children channels on parent channel from cli?
2. Can I shout to multiple channels from cli?
3. Can I do these thinks from first account on second or on another instance of connection: I'm going to manage users from script launched on server, but all clients will be launched on phones.

### Mumble version

1.4

### Mumble component

Both

### OS

Other

**Comment by Krzmbrzl** [comment]
1. No, this is not supported. Muting a channel in this scenario requires changing the ACLs and that can currently not be done via CLI
2. No. CLI does not support any audio input. 

I think you have two possibilities for achieving (roughly) what you are looking for: Use the server's ZeroC Ice RPC interface to make the necessary changes or - if you want to use a separate client for performing these actions - you could write a plugin that does what you need. Though, I don't think the latter option would play nice with having all other clients connected via phone as for some of this functionality you'd have to have your plugin running on every client.

**Comment by Michal123456747** [comment]
Could you send me some example of using ZeroC Ice RPC interface? About separate client I mean that these actions cannot be done from any client using for communication. If I can do that without creating user, it's fine for me.

**Comment by Hartmnt** [comment]
@Michal123456747 [Mumble Moderator](https://github.com/mumble-voip/mumo) can be used to interact/change mumble servers with python. Not sure if it provides all the features you need, but this might be a good start for server side automation.

**Comment by Michal123456747** [comment]
@Hartmnt will check Mumble Moderator. Could you provide me link to ice interface docs?

**Comment by Krzmbrzl** [comment]
The only Ice doc at this point is our definition file: https://github.com/mumble-voip/mumble/blob/master/src/murmur/MumbleServer.ice

**Comment by Michal123456747** [comment]
Thanks for help.

**Comment by Krzmbrzl** [comment]
You're welcome
