### ISSUE TITLE
On systems with a lot of fonts mumble freezes for a few seconds on the first console entry

### ISSUE THREAD

**Issue by hashworks** [mumble-voip/mumble#5922]
### Description

My Mumble client freezes for a few seconds on the first chat message send and the CPU usage spikes to 100% (single thread). After that everything works as expected, only the first message is affected.

EDIT: It doesn't have to be a chat message, any console log is enough, even the "Welcome to Mumble" message.
EDIT2: This is only noticeable on systems with a lot of fonts.

### Steps to reproduce

1. Start mumble
2. Connect to server
3. Try to send message to room
4. Observe freeze and high CPU for a few seconds
5. Send another message
6. Observe normal operation

### Mumble version

1.4.287

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Relevant log output

No log output at all.

**Comment by Krzmbrzl** [comment]
Have you been using Mumble before and if so: did this ever happen to you with an older version of Mumble?

What distro are you using?

**Comment by hashworks** [comment]
I've repeated the bug with trace, it spams this during the freeze:
```
 22959.037 ( 0.004 ms): mumble/160828 mmap(len: 22736, prot: READ, flags: PRIVATE, fd: 36)                  = 0x7f2dcefc6000
 22959.042 ( 0.001 ms): mumble/160828 close(fd: 36)                                                         = 0
 22959.054 ( 0.003 ms): mumble/160828 munmap(addr: 0x7f2dcefc6000, len: 22736)                              = 0
 22963.326 ( 0.005 ms): mumble/160828 openat(dfd: CWD, filename: 0x269c2c38)                                = 36
 22963.332 ( 0.001 ms): mumble/160828 fcntl(fd: 36, cmd: SETFD, arg: 0)                                     = 0
 22963.333 ( 0.001 ms): mumble/160828 newfstatat(dfd: 36, filename: 0xf20dddd5, statbuf: 0x7ffe33dc6320, flag: 4096) = 0
 ```

**Comment by vimpostor** [comment]
Can't reproduce this with the same version on Arch Linux.
Does this happen on all servers?

**Comment by hashworks** [comment]
> Does this happen on all servers?

I tested a random public server, same result.

**Comment by hashworks** [comment]
Here is a video of the bug with `Console` enabled for the `Information` message: https://fb.hash.works/5RTgV/

**Comment by hashworks** [comment]
Found the culprit: I have a lot of fonts.
```sh
$ fc-list | wc -l
9924
```

I did another strace run - mumble simply opens every font file I have.
```
[...]
openat(AT_FDCWD, "/usr/share/fonts/noto/NotoSansTifinaghTawellemmet-Regular.ttf", O_RDONLY) = 23
fcntl(23, F_SETFD, FD_CLOEXEC)          = 0
newfstatat(23, "", {st_mode=S_IFREG|0644, st_size=39752, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 39752, PROT_READ, MAP_PRIVATE, 23, 0) = 0x7f2d613f6000
close(23)                               = 0
munmap(0x7f2d613f6000, 39752)           = 0
openat(AT_FDCWD, "/usr/share/fonts/noto-sans-tirhuta/NotoSansTirhuta-Regular.ttf", O_RDONLY) = 23
fcntl(23, F_SETFD, FD_CLOEXEC)          = 0
newfstatat(23, "", {st_mode=S_IFREG|0644, st_size=96864, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 96864, PROT_READ, MAP_PRIVATE, 23, 0) = 0x7f2d613e8000
close(23)                               = 0
munmap(0x7f2d613e8000, 96864)           = 0
openat(AT_FDCWD, "/usr/share/fonts/noto/NotoSansZanabazarSquare-Regular.ttf", O_RDONLY) = 23
fcntl(23, F_SETFD, FD_CLOEXEC)          = 0
newfstatat(23, "", {st_mode=S_IFREG|0644, st_size=19896, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 19896, PROT_READ, MAP_PRIVATE, 23, 0) = 0x7f2d61d60000
close(23)                               = 0
munmap(0x7f2d61d60000, 19896) 
[...]
```

That takes a while. It shouldn't do that.

**Comment by Krzmbrzl** [comment]
Do you have other Qt application on your system that you could use to see if they suffer from the same problem? 'cause my gut tells me that we don't do any explicit font handling ourselves and therefore I would tend to suspect a Qt bug here :eyes:

**Comment by vimpostor** [comment]
I have installed both `noto-fonts` and `noto-fonts-extra` and now have 2660 fonts installed, but still can't reproduce it - I don't notice any delay at startup.

When I use `strace -e openat`, I also see only about 80 fonts being tried, not 2000.

**Comment by vimpostor** [comment]
@hashworks Does the problem also happen when you start mumble with the following environment variable: `FONTCONFIG_FILE=/etc/fonts/`

**Comment by hashworks** [comment]
For testing purposes I've thrown the `ttf-google-fonts-git` pacman package-files in my filebin, feel free to download them since the build takes a while:
```sh
$ wget --content-disposition https://fb.hash.works/fag6xjgM/ https://fb.hash.works/plLS9QY/ https://fb.hash.works/mWFhzU3/ https://fb.hash.works/PzIiQrA/ https://fb.hash.works/kShaSUH/ https://fb.hash.works/2dR57Wz/
$ file ttf-*
ttf-google-fonts-git-1:r4058.97004a80c-1-any.pkg.tar.zst: Zstandard compressed data (v0.8+), Dictionary ID: None
ttf-merriweather-1:2.100-1-any.pkg.tar.zst:               Zstandard compressed data (v0.8+), Dictionary ID: None
ttf-merriweather-sans-1.008-3-any.pkg.tar.zst:            Zstandard compressed data (v0.8+), Dictionary ID: None
ttf-oswald-4.101-3-any.pkg.tar.zst:                       Zstandard compressed data (v0.8+), Dictionary ID: None
ttf-quintessential-1.001-6-any.pkg.tar.zst:               Zstandard compressed data (v0.8+), Dictionary ID: None
ttf-signika-2.000-1-any.pkg.tar.zst:                      Zstandard compressed data (v0.8+), Dictionary ID: None
```

**Comment by Hartmnt** [comment]
I can reproduce this with a custom 1.5 client build on an Ubuntu system. Having 1203 fonts (mostly LaTeX related) the Mumble client takes 3 seconds to start up with the "Welcome to Mumble message" enabled. I confirmed I reproduce the issue stated here by running strace and observing the font file calls.

However, this problem fixes itself for me for undefined reasons at some point. I recompile mumble often when I work on features and re-start the client dozens of times each session. Sometimes, the problem just vanishes and stays fixed for some unknown period of time. In the future I will try to note what I did when the problem vanishes.

**Comment by Krzmbrzl** [comment]
Thanks for letting us know! This is certainly interesting given that the commits don't actually deal with fonts :shrug:

In any cade though, I'm glad to hear that it is fixed!

**Comment by Hartmnt** [comment]
I kinda doubt this was fixed because, as I said, I was experiencing the bug on the 1.5 branch in November. I think this bug triggers conditionally, with the specific conditions still unknown.
But let's keep this closed until, I or someone else, can reproduce this with a recent version of Mumble.
