### ISSUE TITLE
Weird sound

### ISSUE THREAD

**Issue by CGsama** [mumble-voip/mumble#5942]
### The issue

this sound been replay over and over when connected
https://user-images.githubusercontent.com/15722562/197664915-e3b21593-f3a5-4f0a-a0e7-98911dcf614b.mp4

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

**Comment by ppfeufer** [comment]
See here » https://github.com/mumble-voip/mumble/issues/5921#issuecomment-1272412221

**Comment by CGsama** [comment]
> 见这里 » [#5921（评论）](https://github.com/mumble-voip/mumble/issues/5921#issuecomment-1272412221)

thx!
