### ISSUE TITLE
Cant hear any voice in Mumble

### ISSUE THREAD

**Issue by michaelwanmars** [mumble-voip/mumble#5963]
'### The issue

I suddently cant get any voice from others. I tried everything I can to fix it but not worked.

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Additional information

I suddently cant get any voice from others. I tried everything I can to fix it but not worked. Which includes every audio setting, updated to the newest version and even reinstall my windows 10 system. But still nothing. And the network is also ok. I tried to use my MAC in the same net to trooble shooting and everything is fine. I tried in some public server in my windows client and I can hear the others. The server I am in problem is as follow: 
user name: ASCEE - Michael Swan
server address: mumble.goonfleet.com
Port: 64738
 I am really desperate. Please help!
Best regards!

**Comment by Krzmbrzl** [comment]
Can others hear you while you can't hear them?

And have you tried forcing TCP mode yet?

**Comment by michaelwanmars** [comment]
> Can others hear you while you can't hear them?
> 
> 
> 
> And have you tried forcing TCP mode yet?

I tried force tcp but not worked. I can hear others in public servers so I think its not a setting error. And I haven't tried if others can hear me. Is it necessary? I can try it tommorow if it is.

**Comment by Krzmbrzl** [comment]
> And I haven't tried if others can hear me. Is it necessary?

That would help in figuring out what is going on

**Comment by michaelwanmars** [comment]
> > And I haven't tried if others can hear me. Is it necessary?
> 
> That would help in figuring out what is going on

Roger that. I am not at home now. I will try and tell you as soon as I can. Thanks!

**Comment by michaelwanmars** [comment]
> > > And I haven't tried if others can hear me. Is it necessary?
> > 
> > 
> > That would help in figuring out what is going on
> 
> Roger that. I am not at home now. I will try and tell you as soon as I can. Thanks!



> > > And I haven't tried if others can hear me. Is it necessary?
> > 
> > 
> > That would help in figuring out what is going on
> 
> Roger that. I am not at home now. I will try and tell you as soon as I can. Thanks!

I suddenly repaired my mumble without doing anything. I have no idea what happened but it works now. Thanks you so much!

**Comment by Krzmbrzl** [comment]
Well :shrug:
Good to hear that it works though
