### ISSUE TITLE
Public server duplicate registration appears

### ISSUE THREAD

**Issue by lumineyuri** [mumble-voip/mumble#5969]
### Description

When configuring the Mumble public server, the server list is duplicated

### Steps to reproduce

1. configure register
2. Adjust registerPassword after the first test is successful
3. Check the public server list, there are two duplicate servers

### Mumble version

1.4.278

### Mumble component

Both

### OS

Windows

### Reproducible?

Yes

### Additional information

server address : voice.yuanshen.info
```shell
<server name="原神 | 往生堂" ca="0" continent_code="AS" country="China" country_code="CN" ip="voice.yuanshen.info" port="64738" region="Beijing" url="https://www.yuanshen.info/"/>
<server name="原神 | 往生堂 | 开放&公益&欢迎加入" ca="1" continent_code="AS" country="China" country_code="CN" ip="voice.yuanshen.info" port="64738" region="Beijing" url="https://www.yuanshen.info/"/>
```
### Relevant log output

```shell
<W>2022-11-21 11:10:14.206 1 => Registering zeroconf service...
<W>2022-11-21 11:12:54.949 1 => Registration: Attempting to connect to 124.222.84.236:64738...
Your certificate is validated by a CA, congratulations!
Registration updated!

<W>2022-11-21 11:12:55.199 1 => <0:(-1)> Connection closed: The TLS/SSL connection has been closed [1]
```

### Screenshots

![图片](https://user-images.githubusercontent.com/110418934/202965949-2657ba0a-f558-49e5-92d5-c89b29adf14f.png)
![图片](https://user-images.githubusercontent.com/110418934/202966119-a3d1d8f5-8687-415f-8a65-ef223a2cbb77.png)
![图片](https://user-images.githubusercontent.com/110418934/202966137-a5afa0d9-9783-47a5-bda1-edbc011d1c59.png)
![图片](https://user-images.githubusercontent.com/110418934/202965963-c6df0d30-7879-49c5-99f9-9856be716c2d.png)

**Comment by Krzmbrzl** [comment]
Yeah, if you changed the server details (password in this case) the Backend treats those servers as separate entries.

@davidebeatrici should be able to remove the servers from the list though, so you can re-register your server in order for it to appear only once.

**Comment by lumineyuri** [comment]
> 

thank very much! This issue has been resolved and the redundant server has been removed

**Comment by lumineyuri** [comment]
> Yeah, if you changed the server details (password in this case) the Backend treats those servers as separate entries.
> 
> @davidebeatrici should be able to remove the servers from the list though, so you can re-register your server in order for it to appear only once.

thank very much! This issue has been resolved and the redundant server has been removed
