### ISSUE TITLE
How to re-register our server?

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#5982]
### The issue

```ini
registerHostname=mumble.zova.io
```

I've been wanting to include the region in the server name for a while, because Mumble no longer respects `registerLocation`, and auto-assigned EC2 addresses occasionally (not currently) have an incorrect geolocation attached to them.

When I update `registerName`, the server eventually no longer appears in the public server list. I've also tried changing it together with `registerPassword` before but to no avail. Restoring the original values is the only way to get it to reappear.

How would I go about re-registering our server without having to use a new hostname? Currently running with an updated `registerName` and `registerPassword` again.

Many thanks!

### Mumble version

1.4.287-2

### Mumble component

Server

### OS

Linux

**Comment by davidebeatrici** [comment]
I deleted your server from the database manually, you should now be able to register it with the new info.

**Comment by StrangePeanut** [comment]
Cheers!

**Comment by StrangePeanut** [comment]
@davidebeatrici sorry to bother you again, but the server is no longer popping up in the list today. The logs return `Registration failed: Host requires authentication` many times. All I've done is restart to trigger registration. I have not touched the config at all; `registerName` and `registerPassword` are still using the new values. Hostname is `mumble.zova.io`

**Comment by StrangePeanut** [comment]
@davidebeatrici hope that you are well? Just to let you know that I've restored the original config (`registerName` and `registerPassword`) now. Assuming that this will allow it to appear in the public server list again.

**Comment by davidebeatrici** [comment]
It seems to be in the public list right now.

**Comment by StrangePeanut** [comment]
@davidebeatrici yep but with the old name and password, so we’re back to square one.
