### ISSUE TITLE
Temporarily local mute user

### ISSUE THREAD

**Issue by thexa4** [mumble-voip/mumble#5983]
### Context

When using mumble for remote working we sometimes have to local mute people that sit in the same room to avoid hearing them twice.

Unfortunately this setting is sticky, causing them to still be locally muted when they rejoin the server a while later.

### Description

It would be great if it would be possible to temporarily local mute someone until they disconnect from the server

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
Having two different kinds of local mute seems like it would bloat the UI for little gain.
However, I think it could be argued that locally muting someone should just not be sticky in the first place :thinking:

**Comment by Krzmbrzl** [comment]
> causing them to still be locally muted when they rejoin the server a while later.

Do you have to remain connected for that time in order for the mute status to be restored?

**Comment by thexa4** [comment]
The mute status persist after they disconnect and reconnect. It also persists when quitting mumble and starting it again.

**Comment by Green-Sky** [comment]
> just not be sticky in the first place 

personally disagree.

I think the way to go would be to add an option to clear local mutes on restart/reconnect/remote-reconnect .

**Comment by Krzmbrzl** [comment]
> The mute status persist after they disconnect and reconnect. It also persists when quitting mumble and starting it again.

Okay then that means that the value is stored (presumably) in the database.

> personally disagree.

Mind giving a scenario in which having it stick around is useful?

**Comment by thexa4** [comment]
I'm not sure what information I can provide, what can I do to keep this open?

**Comment by Krzmbrzl** [comment]
Don't worry - the label was only a leftover (can be seen by the fact that I removed it now and I also deleted the bot's comment).

**Comment by Green-Sky** [comment]
OH sorry, totally forgot to replay.

So I thought about it a bit more, and I not think forgetting local mute should be the default too. :)

But it should still be an option. It is the only way to moderate for yourself when no moderator is around.
Well, beside local volume, which has the same behavior, but no visual indicator(?), so not _really_ an alternative.

**Comment by schoerg** [comment]
>When using mumble for remote working we sometimes have to local mute people that sit in the same room to avoid hearing them twice.

I would instead opt for a workaround:  use "Local Volume Adjustment" and set it to a low value.

**Comment by Hartmnt** [comment]
Ok, so I run into this semi-regulary, too. I local mute a user for whatever reason and days later I meet that user again and wonder why they do not talk...

I personally see no reason why a local mute should be so persistent that it basically lasts forever. Local volume adjustment exists and if I want to permanently rid of a user I would have to ban them or - if I am not an admin - join another server/channel whatever. Local-Mute-Ghosting is not ideal for that scenario.

On the other hand, I do not want users to "circumvent" my local mute by reconnecting (or losing the connection or something) when I have a good reason to temporarily mute them.

So what I propose is the following: When *I* - as the person who local muted someone - restart my Mumble client, I want to have a new, clean session and get rid of all local-muted entries in my local database. I think this is the ideal compromise between local-mute persistence (self moderation) and usefulness (forgetting local muted users are muted days later).

I would like to implement it this way, if that is fine by whoever is still interested in this issue (ping @Krzmbrzl )

**Comment by Krzmbrzl** [comment]
Sounds good :+1:
