### ISSUE TITLE
MUMBLE SERVER 1.4.X ON UBUNTU NOT AVAILABLE?

### ISSUE THREAD

**Issue by tomeroto** [mumble-voip/mumble#5988]
### The issue

Hi I prefer to use Linux Ubuntu 20.x to install mumble server.
But after I try install by using command:

`sudo apt-get install mumble-server`

But after I check, mumble server has only old version 1.3.x.

How to update it to 1.4.x?

### Mumble version

1.4.X

### Mumble component

Server

### OS

Linux

**Comment by davidebeatrici** [comment]
Unfortunately you'll have to build it yourself for the time being, see #5354.
