### ISSUE TITLE
plugins for mumble

### ISSUE THREAD

**Issue by zockerboy1yt1** [mumble-voip/mumble#5993]
### The issue

i have linux mint 21.1 cinamon and use mumble 1.4.287, i have  downloade mumble by flathub, i want to use the positoinal audio in counte rstrike source so i locked for the plugin in settings plugins, then i saw that my plugin ordner is empty only the manual placement plugin.
can i download the plugins manualy? please help

### Mumble version

1.4.287

### Mumble component

Client

### OS

Linux

### Additional information

![Bildschirmfoto vom 2022-12-24 01-30-59](https://user-images.githubusercontent.com/121323001/209415292-bddfab59-417f-416c-8e68-1562acf20c76.png)

**Comment by Krzmbrzl** [comment]
It seems like the Flatpak version of Mumble is built without the plugins. 
Thanks to the new plugin framework introduced with Mumble 1.4, it is in theory possible to download plugins separately, but
1. We don't have any infrastructure to provide downloadable plugins yet
2. Almost none of the positional audio plugins have been ported to the new plugin framework yet. And legacy plugins can't (really) be downloaded separately. 

I just checked and the CS plugin is indeed still in legacy format and can therefore not be downloaded separately.

If you want to use Mumble with plugins, you'd currently either have to install it from your distribution's repos (might be a rather outdated version though) or build Mumble yourself (which on Linux is quite easy).

**Comment by zockerboy1yt1** [comment]
i have instal with my apt install command and tehen i habe the version 1.3.4 and tehre was no plugins i had teh same probleme

**Comment by Krzmbrzl** [comment]
Hm - then the Debian package also ships without plugins. In that case the only option really appears to be to build Mumble yourself, unfortunately (there are instructions for how to do this in this repo)

**Comment by firecakes** [comment]
Also having the same issue. I don't understand why this is marked as closed, as this is not resolved.

**Comment by Krzmbrzl** [comment]
It's marked as closed because there is absolutely nothing we can do about it. These packages are maintained externally and not by us. Please file bug reports against the flatpak and/or deb package respectively.
