### ISSUE TITLE
Paid project to voice chat and text chat random site.

### ISSUE THREAD

**Issue by FaizanZahid** [mumble-voip/mumble#5996]
### Description

Can you help me?
I want a clone of this site on Wordpress with random voice chat and random text chat https://www.airtalk.live/
What is the technology and software behind this voice call software, it is working on all browsers and fully responsive?
Read my full requirements here https://docs.google.com/document/d/1S2-0WjIsmJ8-jQARCPqYRuuBEIjTjCSoLFdIeCcmEwQ/edit#
Also watch this video https://www.youtube.com/watch?v=XTy4YVVMgkQ&ab_channel=FaizanZahid
My skype ID is https://join.skype.com/invite/p6d2RhASBvUo

Happy to pay for this work, please reach me on faizan.zad@gmail.com

### Mumble component

Client

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
This seems completely unrelated to Mumble and in addition to that, a project's issue tracker seems like the wrong place for posts like yours.
