### ISSUE TITLE
Add Assetto Corsa to the list of supported PA games

### ISSUE THREAD

**Issue by LeoLTM** [mumble-voip/mumble#6003]
### Context

Reading the wiki to check which games are compatible with PA in Mumble

### Description

Assetto Corsa (with "CSP" aka. "Custom Shaders Patch") now supports the connection to the Link plugin in Mumble when playing online. This feature is only available when using a CSP version `>= 0.1.77`. 

### Mumble component

Both

### OS-specific?

No

### Additional information

This is not really affecting client / server, but the website / wiki

**Comment by Krzmbrzl** [comment]
Done: https://wiki.mumble.info/wiki/Games
