### ISSUE TITLE
Get all connected users and all active channel information.

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6021]
### The issue

I would like to get all connected users and all existing channels. Is there a way to do this from the server class?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
As you are asking to do this from the server _class_, I take it that you are trying to modify the source code and want to know how to obtain the desired information in that context, correct?
If so, the relevant information can be found in
https://github.com/mumble-voip/mumble/blob/362b092e7eb5d3d493639e7f9fd34954ffb22e49/src/murmur/Server.h#L304
and
https://github.com/mumble-voip/mumble/blob/362b092e7eb5d3d493639e7f9fd34954ffb22e49/src/murmur/Server.h#L307
