### ISSUE TITLE
Move user to a channel

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6030]
### The issue

How would we programmatically move a user to a channel.

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
On the server:
https://github.com/mumble-voip/mumble/blob/1c9ec36b28aa0545404690eba788dec5dae6d24e/src/murmur/Messages.cpp#L1026
On the client:
https://github.com/mumble-voip/mumble/blob/1c9ec36b28aa0545404690eba788dec5dae6d24e/src/mumble/ServerHandler.cpp#L900-L901
