### ISSUE TITLE
Any chance to easily upgrade Mumble-server to lastest version via PPA (Ubuntu 18.04.6)

### ISSUE THREAD

**Issue by awatchar** [mumble-voip/mumble#6035]
### The issue

I installed mumble-server via PPA on my Ubuntu server (18.04.6) for a long time 
and still using version 1.3.4.

Are there any chance that I can upgrade my mumble-server to lastest version 
or any instructions that I can follow.

I am very new to ubuntu server.
Hope someone can shed the light.

### Mumble version

1.3.4

### Mumble component

Server

### OS

Other

**Comment by Hartmnt** [comment]
> Are there any chance that I can upgrade my mumble-server to lastest version
> or any instructions that I can follow.

It is very unlikely that newer versions of Mumble will be included in the Ubuntu 18.04 Repos at any point. You will have to compile the mumble-server executable yourself. For this, you can follow this guide: https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md

**Comment by Krzmbrzl** [comment]
And the PPA is unmaintained for the time being. Maybe we can get it working again at some point but I can't give you an ETA.
