### ISSUE TITLE
Weird failure to bind to Localhost

### ISSUE THREAD

**Issue by I2pRandom** [mumble-voip/mumble#6036]
### The issue

I've configured murmur to bind to 127.0.0.1:64738 
But bizarrely even when i nmap my localhost ports, the port 64738 is not open. i've also attempted binding to a different port.
![2023-01-18_00-41](https://user-images.githubusercontent.com/42506001/213102232-824df702-99af-4d57-94dc-a3f5a79e9b29.png)

### Mumble version

1.4.287

### Mumble component

Server

### OS

Linux

### Additional information

The specific Distribution i am using is Arch

**Comment by Krzmbrzl** [comment]
Which port is the server using instead? Could you check, if this problem is reproducible with a fresh database? For that, simply rename your existing database to something else and let the server create a new database during startup. Config options in the INI file don't apply if they have ever been overwritten via e.g. Ice as then the config is stored in the database, which will take precedence.

**Comment by I2pRandom** [comment]
The server is not binding to any port, an nmap scan of both localhost and the external IP does not show an open or filtered port.
I didn't need the database anyways, so i moved it elsewhere, then just let murmur generate a new one and it's still not binding to any port.

**Comment by davidebeatrici** [comment]
Does anything related appear in the server log?

**Comment by I2pRandom** [comment]
Had to figure out how to manually launch the server 
I'm getting this error before murmur closes, turns out systemd is just acting like the mumble server is open when it's been closing with an error

<F>2023-01-19 19:02:21.529 ServerDB: Failed initialization: unable to open database file Error opening database

**Comment by Krzmbrzl** [comment]
Ah - well in that case your server isn't even starting up and therefore not binding to any ports.
It seems that there are issues connecting to the DB during startup.

What are the DB-related settings in your INI file? Make sure the referenced DB path is in a location where the user that is starting the server has write access.

**Comment by I2pRandom** [comment]
I'm a fool. it runs just find as a systemd service task. it's presenting the error to me as root because root does not own the DB file. 
But i've run into this 
Jan 20 02:54:35 rocketmonke murmurd[2050990]: <W>2023-01-20 02:54:35.081 1 => Server listening on <<2961b3c6e6eaf1a2c91fd3d7d0b5f30d8b5dddb4:64738>>
Jan 20 02:54:35 rocketmonke murmurd[2050990]: <W>2023-01-20 02:54:35.081 1 => Server listening on <<06a489523dd32bb257685ec3cd9d3f2846583492:64738>>
Jan 20 02:54:35 rocketmonke murmurd[2050990]: <W>2023-01-20 02:54:35.082 1 => Failed to set IPV6_RECVPKTINFO for <<06a489523dd32bb257685ec3cd9d3f2846583492:64738>>

It seems to be binding on Ipv4, tho i can't see the port on ipv4 being open with nmap as well i cannot connect to it inside of the i2p network. this may be a problem with my i2p configuration and not mumble.
