### ISSUE TITLE
Case-sensitive arguments in Murmur

### ISSUE THREAD

**Issue by Rufubi** [mumble-voip/mumble#6037]
### Description

There is an option `-V` that currently works as "verbose", but it is implied to be "version". This is happening because of the `.toLower()` method. I think it would be possible to remove the argument lowering, but it might break the server startup for those who rely on argument lowering.
https://github.com/mumble-voip/mumble/blob/72d2d55b3e4e4dc0d37a016d87fdd491b233ba4d/src/murmur/main.cpp#L295

### Steps to reproduce

1. Execute `murmur -V`
2. Instead of outputting the version, the server starts up as if `murmur -v` had been run

### Mumble version

72d2d55b3e4e4dc0d37a016d87fdd491b233ba4d

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Good finding!
The relevant checks are
https://github.com/mumble-voip/mumble/blob/72d2d55b3e4e4dc0d37a016d87fdd491b233ba4d/src/murmur/main.cpp#L343-L345

Imo, the best approach here would simply be to remove the `-V` option as a shortcut for the version. Does anything speak against that? :thinking:

**Comment by Rufubi** [comment]
Removing the '-V' option will not change the server's behavior. However, is it possible to bring all options to the unified format (as in the "[POSIX Utility Syntax Guidelines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02)") in the next release?

**Comment by Krzmbrzl** [comment]
Well it will change the server's behavior in so far as that (afaict) it removes the only ambiguity that currently exists, so all command line arguments are well defined.

> s it possible to bring all options to the unified format (as in the "[POSIX Utility Syntax Guidelines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02)") in the next release?

I was thinking about removing that horrible hand-crafted option parsing in favor of using a dedicated library for this for a while. That would (almost certainly - depending on the lib) also solve this issue. However, so far I have not come around actually doing that. So I can't promise that this will be in the next release (almostcertainly not in 1.5 though) :eyes:

**Comment by Krzmbrzl** [comment]
We're trying to get rid of Qt as much as possible, but thanks for the suggestion :)

**Comment by Hartmnt** [comment]
How about we split this ticket into two issues: One for the bug at hand, and one for replacing the command line argument parsing altogether.

**Comment by Krzmbrzl** [comment]
Yep: https://github.com/mumble-voip/mumble/issues/6063
