### ISSUE TITLE
Cmake setup does not detect pkgconf variables, wrong fallback location for configs

### ISSUE THREAD

**Issue by dvzrv** [mumble-voip/mumble#6038]
### Description

Hi! When trying to package 1.5.517 for Arch Linux, I ran into the issue, that the cmake build system always wants to install files to the /etc/ location and not the one detected via pkg-config.

On my host the following works as intended:

```
pkgconf --variable systemd_system_unit_dir systemd
/usr/lib/systemd/system
```

```
pkgconf --variable sysusersdir systemd
/usr/lib/sysusers.d
```

But these directories are not detected by mumble's cmake setup, although systemd (and its pkg-config integration) is available in the build environment.

### Steps to reproduce

Changing the calls in https://github.com/mumble-voip/mumble/blob/e166ea1276b7859980ce1b7a35eb842fbc4b0701/auxiliary_files/CMakeLists.txt#L77-L82 and https://github.com/mumble-voip/mumble/blob/e166ea1276b7859980ce1b7a35eb842fbc4b0701/auxiliary_files/CMakeLists.txt#L67-L72 from `QUIET` to `REQUIRED` yields:

```
CMake Error at cmake/pkg-utils.cmake:285 (message):
  get_pkgconf_variable: Failed to fetch "sysusersdir" of module "systemd"
Call Stack (most recent call first):
  auxiliary_files/CMakeLists.txt:67 (get_pkgconf_variable)


-- Configuring incomplete, errors occurred!
```

### Mumble version

1.5.517

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

The detection of the components should *not* be set to `QUIET` as it makes things very intransparent for downstreams and unnecessarily hard to debug.

As the custom function [get_pkgconf_variable](https://github.com/mumble-voip/mumble/blob/e166ea1276b7859980ce1b7a35eb842fbc4b0701/cmake/pkg-utils.cmake#L219-L297) has been used for detecting the two directories, it is unclear what went wrong there and how to further debug it.

Simply using [pkg_get_variable](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_get_variable) does the right thing and detects the two variables correctly:

```
diff -ruN a/auxiliary_files/CMakeLists.txt b/auxiliary_files/CMakeLists.txt
--- a/auxiliary_files/CMakeLists.txt    2023-01-18 07:54:18.355957000 +0100
+++ b/auxiliary_files/CMakeLists.txt    2023-01-22 00:35:54.387905181 +0100
@@ -64,22 +64,12 @@
        file(COPY "config_files/mumble-server.conf" DESTINATION ${CMAKE_CURRENT_BINARY_DIR})

        if(UNIX AND NOT APPLE)
-               get_pkgconf_variable(
-                       OUTPUT_VARIABLE SYSUSERS_DIR
-                       MODULE systemd
-                       VARIABLE_NAME sysusersdir
-                       QUIET
-               )
+               pkg_get_variable(SYSUSERS_DIR systemd sysusersdir)
                if(NOT SYSUSERS_DIR)
                        # Fallback value, in case it could not be fetched via pkg-config
                        set(SYSUSERS_DIR "${CMAKE_INSTALL_SYSCONFDIR}/sysconfig.d")
                endif()
-               get_pkgconf_variable(
-                       OUTPUT_VARIABLE SYSTEMD_SERVICE_DIR
-                       MODULE systemd
-                       VARIABLE_NAME systemd_system_unit_dir
-                       QUIET
-               )
+               pkg_get_variable(SYSTEMD_SERVICE_DIR systemd systemd_system_unit_dir)
                if(NOT SYSTEMD_SERVICE_DIR)
                        # Default to /etc/systemd/system - This is not where packages ought to install their service files (rather
                        # it's where an admin is supposed to add their system files), but this seems to be the most consistent
```

**Comment by dvzrv** [comment]
Somewhat related: The fallback `etc/sysconfig.d/mumble-server.conf` is not correct and should be `etc/sysusers.d/mumble-server.conf`

**Comment by Krzmbrzl** [comment]
> how to further debug it

The function takes an option argument `DEBUG` that should make it print a few more things about what it is trying to do. Maybe that already helps.

Just by looking at the code right now and by taking into consideration what you wrote, my first bet would be that the script is unable to find the `systemd` module in the first place:
https://github.com/mumble-voip/mumble/blob/72d2d55b3e4e4dc0d37a016d87fdd491b233ba4d/cmake/pkg-utils.cmake#L255-L256
(Unfortunately that is only reported when the debug option is given - that should probably be changed)

**Comment by dvzrv** [comment]
Using `DEBUG` instead of `QUIET` I get:

```
-- Unable to find module "systemd" via pkg-conf
CMake Warning at cmake/pkg-utils.cmake:288 (message):
  get_pkgconf_variable: Failed to fetch "sysusersdir" of module "systemd"
Call Stack (most recent call first):
  auxiliary_files/CMakeLists.txt:67 (get_pkgconf_variable)


-- get_pkgconf_variable: Determined sysusersdir="NOTFOUND"
-- Unable to find module "systemd" via pkg-conf
CMake Warning at cmake/pkg-utils.cmake:288 (message):
  get_pkgconf_variable: Failed to fetch "systemd_system_unit_dir" of module
  "systemd"
Call Stack (most recent call first):
  auxiliary_files/CMakeLists.txt:77 (get_pkgconf_variable)


-- get_pkgconf_variable: Determined systemd_system_unit_dir="NOTFOUND"
```

As mentioned in the initial report, using cmake's default `get_pkg_variable` works as intended and returns the correct directories though.

Aside from the issue at hand: I believe using a fallback below /etc should be explicit (e.g. *at least* a message saying what is happening), since this is not the packaging default and breaks a lot of use-cases such as immutable systems (which do not even have an /etc).
