### ISSUE TITLE
Improve file permission and user access of mumble-server.ini

### ISSUE THREAD

**Issue by dvzrv** [mumble-voip/mumble#6039]
### Description

Hi! When working on the package for mumble-server 1.5.517, I noticed that the file permissions for the `mumble-server.ini` configuration file are set to `644`, which makes them world-readable.
As the configuration file contains passwords to databases and the server itself, this would leak information to other users on the same host, which should be circumvented.

### Steps to reproduce

Build 1.5.517 (and create package), check contents:
```
drwxr-xr-x root/root         0 2023-01-22 17:36 etc/
drwxr-xr-x root/root         0 2023-01-22 17:36 etc/mumble/
-rw-r--r-- root/root     41815 2023-01-22 17:36 etc/mumble/MumbleServer.ice
-rw-r--r-- root/root     18046 2023-01-22 17:36 etc/mumble/mumble-server.ini
```

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

The mumble-server.ini configuration file should be installed using a file mode of 640 (i.e. not world readable).
To allow the dedicated `_mumble-server` user to read the file, the file can be group-owned by it. This can be achieved using [tmpfiles.d](https://man.archlinux.org/man/tmpfiles.d.5), e.g. with something like this:

```
z /etc/mumble/mumble-server.ini 0640 root _mumble-server
```

It is important to note here, that the file should nonetheless be installed with a file mode of 640 by cmake, so that there is no discrepancy in file mode between what cmake does and what is later on enforced by tmpfiles.d (else the file mode will be different for a short amount of time after updating the package on downstream distributions).

**Comment by Krzmbrzl** [comment]
Good point!
For future reference (for myself, probably): cmake's `install` command supports a `PERMISSIONS` option that should allow us to do what we want here: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Install.html
