### ISSUE TITLE
Reconnect client

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6042]
### The issue

How would I disconnect and then reconnect a client from the server?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
What do you mean? The anderen to your question would be
1. Click disconnect
2. Reconnect to that server

But I kinda doubt this is the answer you are looking for...

**Comment by Hartmnt** [comment]
Based on the other issues OP posted recently, I assume that they want to do this programmatically server side?
In that case you could disconnect the client by kicking them, or changing the server code to terminate the control connection. However, forcing a client to reconnect without user input would be hard/impossible in that case.
