### ISSUE TITLE
v1.5.517 Strange chat log selection behaviour on linux

### ISSUE THREAD

**Issue by dexgs** [mumble-voip/mumble#6045]
### Description

There seems to be some weird behaviour in the chat log in v1.5.517. It seems visual, but the problem wasn't present in previous versions. The problem has to do with the chat log not always re-drawing text as needed.

The easiest way I found to reproduce the problem is to select a whole line (with triple-click) and then select other text in the log. The previously selected line stays highlighted until it's forcibly re-drawn, i.e. by scrolling the text out of view and scrolling back.

There seem to be some other minor related visual issues, but the one I described above is the most noticeable.

### Steps to reproduce

1. Send some messages to the chat log
2. Select a whole line (i.e. by triple-clicking)
3. Try to select other text in the log

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
What version of Qt are you using on your system? This appears Luke somthing that should entirely be handled by Qt to me :thinking:

**Comment by Hartmnt** [comment]
I can reproduce this with the exact steps OP posted. v1.5.517, Mumble reports Qt 5.15.6, Ubuntu 22.04, XFCE, X11

**Comment by Hartmnt** [comment]
![Peek](https://user-images.githubusercontent.com/1348773/214914600-53ce26ac-7e66-42f8-91f8-9d1a1ebbf516.gif)

**Comment by Krzmbrzl** [comment]
For me this only works if the second selection is performed via click&drag. If I double click to select a word, this always unselects the previously selected text passage as expected.
Therefore, my guess is that we are somehow preventing the click in click&drag from deselecting the previous selection.

Side-note: I tried with different KDE apps (all Qt5-based) and none showed the same issues, so the problem has to be on our side

**Comment by Hartmnt** [comment]
> For me this only works if the second selection is performed via click&drag. If I double click to select a word, this always unselects the previously selected text passage as expected. Therefore, my guess is that we are somehow preventing the click in click&drag from deselecting the previous selection.

What happens, if you triple-click?

**Comment by Krzmbrzl** [comment]
Then it selects the new line and also deselects the old one. So everything seems to work as intended

I'm currently bisecting the selection issues...

**Comment by Hartmnt** [comment]
Also note how for me, and you can see this in the gif, the cursor becomes an edit cursor for the entire time after triple selecting a line.

**Comment by Krzmbrzl** [comment]
The problem was introduced via c21c6a0dcd8e465e47ddbd9adcc033836ae4ba5e (I half suspected this already)

**Comment by Krzmbrzl** [comment]
Not sure if this is related, but ae097d6354d99325093dd5a12cb8632e2ba20edf has before already broken selecting a line only partially. At least for plain-text messages. The selection seems to still work fine within HTML-styled (welcome) messages

**Comment by dexgs** [comment]
I took another shot at fixing this, hopefully I didn't screw it up this time.
