### ISSUE TITLE
MacOS Ventura 13.1 - Apple echo cancellation (experimental) prevents PTT from functioning

### ISSUE THREAD

**Issue by digitalpho3nix** [mumble-voip/mumble#6046]
### Description

Enabling Apple experimental echo cancellation on MacOS Ventura 13.1 stops push to talk from functioning at all. Disabling this feature immediately rectifies issue.

### Steps to reproduce

Enable Apple acoustic echo cancellation

### Mumble version

1.4.287

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
My gut tells me that this is probably yet another macOS weirdness of some sort. But idk.
If someone wants to give this a shot, be my guest.

**Comment by Hartmnt** [comment]
Possibly a duplicate of #4912
Maybe the mentioned workaround still works for you @digitalpho3nix
