### ISSUE TITLE
Cropping the link in the welcome message

### ISSUE THREAD

**Issue by Alterak** [mumble-voip/mumble#6047]
### Description

I added the information in the welcome message and inserted the link, but it is cut off and becomes incomplete, so it is impossible to follow this link. Here is an example:
```
welcome text="
<ul>
<<li><strong>Constant channel: </strong><a href="https://itforum.ustim.ru/viewforum.php?f=19">Leave a request</a>
</li>
</ul>
"
```
As a result, the link becomes like this https://itforum.ustim.ru/viewforum.php?f  the last 3 characters disappeared from me.

Tell me how to make sure that the number of characters in the links is not cut off?

### Steps to reproduce

1. Change the welcome text in the configuration file /etc/mumble-server.ini
2. Add a link in html style
3. Link error, limited number of characters. The link doesn't work

### Mumble version

1.3.4-1

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
The link seems to be malformed in the first place. Afaik links must not contain spaces. Maybe try fixing that and then see if the problem goes away as well

**Comment by Alterak** [comment]
> The link seems to be malformed in the first place. Afaik links must not contain spaces. Maybe try fixing that and then see if the problem goes away as well

I inserted a link with an error on GitHub... Fixed it.
There are no spaces in the configuration file-) don't worry. The problem is the limited number of characters in the link.

**Comment by Krzmbrzl** [comment]
I'm not aware of any character count limit that we impose on links :thinking:

Could you perhaps try to see what the result with this link is?
`http://itfo.ustim.ru/viewforum.php?f=19`. If there was a character count limit, this should result in the link as-is.

If the link is still cut off, this is likely a problem with special characters that might need escaping of some sort (somewhere)

**Comment by Alterak** [comment]
> Could you perhaps try to see what the result with this link is? `http://itfo.ustim.ru/viewforum.php?f=19`. If there was a character count limit, this should result in the link as-is.
> 
> If the link is still cut off, this is likely a problem with special characters that might need escaping of some sort (somewhere)

Here is the result:
```
welcometext="<br>
<ul>
<li><strong>Constant channel: </strong><a href="http://itfo.ustim.ru/viewforum.php?f=19">Leave a request</a></li>
</ul>
<br>
"
```
![Скриншот 29-01-2023 010834](https://user-images.githubusercontent.com/11453567/215293244-da117f75-f364-4bb2-b5cc-202292b70e99.jpg)

**Comment by Alterak** [comment]
> It seems there is a problem with the equal sign "=", this sign and all characters after this sign do not work

I decided to write other characters instead of the "=" sign and they are displayed correctly. Indeed, the problem is with the equal sign.
<a href="https://itforum.ustim.ru/viewforum.php?..fqwert..19">

![Скриншот 29-01-2023 011819](https://user-images.githubusercontent.com/11453567/215293718-fdd6491a-f9dd-4c92-a255-3f0d2076ef16.jpg)

**Comment by ppfeufer** [comment]
Or you can try the following:

```js
welcometext="<br>
<ul>
<li><strong>Constant channel: </strong><a href='http://itfo.ustim.ru/viewforum.php?f=19'>Leave a request</a></li>
</ul>
<br>
"
```
This is with corrected quotes in the HTML code.

Explanation:
The `welcometext` option expects a string wrapped in `" "` as its delimiter for the string's beginning and end. Your HTML code also contains `"`, which the config parser then assumes marking the end of the string.

With a bit of syntax highlight you can see what I mean (see the difference in colours in your original bit):
```js
welcometext="<br>
<ul>
<li><strong>Constant channel: </strong><a href="http://itfo.ustim.ru/viewforum.php?f=19">Leave a request</a></li>
</ul>
<br>
"
```

**Comment by Alterak** [comment]
> Or you can try the following:

It really works
`<a href='https://itforum.ustim.ru/viewforum.php?f=19'>`

Thanks! You've been very helpful!
