### ISSUE TITLE
It is not possible to insert an image into the greeting text

### ISSUE THREAD

**Issue by Alterak** [mumble-voip/mumble#6048]
### Description

In the mumble configuration file, I want to insert an image. I'm trying to add an image by the link and also a local file that lies in the directory /home/mumble/img/test.png
I added links to the <img> tag it turned out like this

![Скриншот 28-01-2023 195801](https://user-images.githubusercontent.com/11453567/215279246-55940c4e-ea27-42e5-b420-564135b34bf9.jpg)

```
welcometext="<br>
<h3>Test Link Image</h3> <br>
<img src="https://www.cookieserv.com/img/offers/game/5.png" alt="test link img"> <br>
<h3>Test Local Image</h3> <br>
<img src="/home/mumble/img/test.png" alt="test local img"> <br>
"
```
But the images don't appear, instead there is an empty space... this can be seen in the screenshot

![Скриншот 28-01-2023 195725](https://user-images.githubusercontent.com/11453567/215279253-1c4231e1-fe96-4531-9e61-e9ce7b274b31.jpg)

I've tried different images, different sizes, as well as different extensions and .png and .jpg and .gif but nothing works. Help solve this problem? Is this a server or client error?
In older versions, the image on the link worked, but the local file did not work. I can't say in which versions it was, I don't remember.

My operating system is Debian 11.
Server version - 1.3.4-1
The client version is 1.517, I also tried release 1.4.287

### Steps to reproduce

1. Open the Mumble server configuration file
2. Insert a link to the image in the greeting text
3. The image does not appear in the client.

### Mumble version

1.3.4-1

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
I believe images have to be embedded as Base64 encoded inline images as we don't load any external sources on-the-fly.

See also https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html

**Comment by Alterak** [comment]
> I believe images have to be embedded as Base64 encoded inline images as we don't load any external sources on-the-fly.
> 
> See also https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html

Ok. I decided to do so... I downloaded the same small file from the link, added an image of the channel to get the Base64 code

![Скриншот 29-01-2023 004606](https://user-images.githubusercontent.com/11453567/215292763-a53f49f4-8cde-4516-8418-4b0d2fffde63.jpg)

And what I saw... I got a very very long code...

![Скриншот 29-01-2023 004645](https://user-images.githubusercontent.com/11453567/215292780-a52ebacd-2228-4653-85ea-2f9e337e97e2.jpg)

Do I really need to insert this code into the Mumble configuration file? Are you kidding?? Why do such terrible things?
I'm sorry, but this is very repulsive to the server administrators, I really hoped to find a simple solution to insert an image, but everything turned out to be so confusing and very inconvenient-(

**Comment by ppfeufer** [comment]
This might be the same as with your link in the other issue.

As you can see here with syntax highlight (difference in colours):
```js
welcometext="<br>
<h3>Test Link Image</h3> <br>
<img src="https://www.cookieserv.com/img/offers/game/5.png" alt="test link img"> <br>
<h3>Test Local Image</h3> <br>
<img src="/home/mumble/img/test.png" alt="test local img"> <br>
"
```

You probably need to fix the quotes as I write in the other issue.

**Comment by Alterak** [comment]
> As you can see here with syntax highlight (difference in colours):

This does not work with a local file-(
my file is located here, it has "mumble-server" rights

```
root@voice-test:/home/mumble/img# ls -l
итого 8
-rwxrwxr-x 1 mumble-server mumble-server 7511 янв 27 17:28 test.png
```

In the configuration file I added this
```
welcometext="<br>
<img src='/home/mumble/img/test.png' alt="test local img">
<br>
"
```
Here is the result-(

![Скриншот 29-01-2023 021651](https://user-images.githubusercontent.com/11453567/215295495-c7b6c30f-3893-4ba8-ac3b-74a7d7d885fb.jpg)

**Comment by ppfeufer** [comment]
You are still messing up your quotes.

**Comment by Alterak** [comment]
> You are still messing up your quotes.

You suggest enclosing any tags in single quotes inside the main block, for example like this
```
welcometext="<br>
<img src='/home/mumble/img/test.png' alt='test local img' width='300'>
<br>
" 
```

Do I understand you correctly? - That doesn't work either. But if I insert the Base64 code with any quotes, then the picture appears. But I need to use a local file-(

**Comment by Krzmbrzl** [comment]
> Do I really need to insert this code into the Mumble configuration file

Yes - that's how Base64 works. If you want a smaller string representation, you have to use a smaller image.

> This does not work with a local file

But it does work with the remote file? Then your local file is not accessible from the internet at the specified address.

**Comment by ppfeufer** [comment]
> You suggest enclosing any tags in single quotes inside the main block, for example like this

Yes. Since the double quote is the delimiter for the string value of the option in your config, you need to use single quotes inside that string. Otherwise, you end up breaking the config parsing.

**Comment by Alterak** [comment]
> But it does work with the remote file? Then your local file is not accessible from the internet at the specified address.

Of course, the local file is not accessible from the Internet, because it is a **local file** that lies in a directory on the server-)

> You need to understand that this HTML is interpreted at the client side and therefore any local paths from your server are then interpreted as local paths on the client, which simply do not exist.

The Mumble client receives all the data from the server, and the image file is in the directory on the server, as well as added to the server configuration... so this file should be displayed in any client that connects to my server.

**Comment by ppfeufer** [comment]
> The Mumble client receives all the data from the server, and the image file is in the directory on the server, as well as added to the server configuration... so this file should be displayed in any client that connects to my server.

No.
In case of using a local file on the server, the client tries to load `/home/user/filename.jpg` which does not exist on the client's machine.

**Comment by Alterak** [comment]
> you need to use single quotes inside that string

I showed you [an example](https://github.com/mumble-voip/mumble/issues/6048#issuecomment-1407593215), but it doesn't work.

**Comment by ppfeufer** [comment]
> > you need to use single quotes inside that string
> 
> I showed you [an example](https://github.com/mumble-voip/mumble/issues/6048#issuecomment-1407593215), but it doesn't work.

Read my previous comment.

**Comment by Alterak** [comment]
> No.
> In case of using a local file on the server, the client tries to load `/home/user/filename.jpg` which does not exist on the client's machine.

I don't understand the meaning of such a complex implementation!
It would be correct to add the ability to specify in the configuration the path where files and images will be stored. And so that the client can access these files and display them.

**Comment by ppfeufer** [comment]
After playing around with this on my test server, it seems that it is not possible to add images to the welcome text after all. Tested with an image that is accessible from the internet as well as a base64 data string. Both times the image will not be loaded.

Looks like some restrictions on the server's capabilities.

**Comment by Alterak** [comment]
> Should this not be the case, please let us know.

There is a problem. No solution found. If the image file is located on the host, then it will not be displayed in the client.

**Comment by Krzmbrzl** [comment]
Yes, this is not supported.
