### ISSUE TITLE
Cannot compile ice to java

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6050]
### The issue

I am getting the following error when compiling ice for java.

`MumbleServer.ice:14: error: Can't open include file "Ice/SliceChecksumDict.ice"
    #include <Ice/SliceChecksumDict.ice>
1 error in preprocessor.`

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
How do you compile the ice file?
These files must be available in your local Ice installation (if I'm not mistaken)

**Comment by terenc3** [comment]
As @Krzmbrzl mentioned you need to specify where slice can find includes e.g on debian.

`slice2java Murmur.ice -I /usr/share/ice/slice/`
