### ISSUE TITLE
CELT support?

### ISSUE THREAD

**Issue by TheBjoel2** [mumble-voip/mumble#6056]
### The issue

When I try to connect to mumble server, I get the following error
```
(Private) Server: WARNING: Your client doesn't support the CELT codec, you won't be able to talk to or hear most clients. Please make sure your client was built with CELT support.
```
And then it disconnects me
```
Disconnected from server.
```

### Mumble version

1.5.517-1 arch package

### Mumble component

Client

### OS

Linux

**Comment by Hartmnt** [comment]
What version is the Mumble server running you are trying to connect to?
