### ISSUE TITLE
Turn off shortcut key overlap

### ISSUE THREAD

**Issue by HHBP** [mumble-voip/mumble#6068]
### Description

Click to exit the mumble shortcut key overlap

### Steps to reproduce

![20230217124902](https://user-images.githubusercontent.com/117415653/219553285-88893025-d85e-4253-ab98-18abe6c7b493.jpg)

### Mumble version

1.5.517

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Can't reproduce on Linux:
![image](https://user-images.githubusercontent.com/12751591/229275405-08e8043a-e523-4da5-813f-7c6c07123293.png)

This does seem like a Qt problem to me as it should take care of not overlapping the different elements :thinking:

**Comment by davidebeatrici** [comment]
@HHBP Does it happen with the system theme as well?
