### ISSUE TITLE
Priority Speaker user flag not persistant across server restarts

### ISSUE THREAD

**Issue by GR0B** [mumble-voip/mumble#6072]
### Context

Priority speakers setting is not persistant across server restarts. 

In our setup we use the "Priority Speaker" feature to have a few users that when they speak all other users in the channel are attenuated.  Previously we were running an older version Murmur on Debian 10 running on a Raspberry Pi that would only be rebooted every few months. Once a user was given the "Priority Speaker" ability, it would follow them around the server as be persistant over disconnections/reconnections (as we wanted). 

We have since moved the server to a higher spec'ed Windows 10 PC that is rebooted daily. But since doing this, an Admin needs to mannually set the "Priority Speaker" for these users everyday after the server is started and they have connected. 

Ideally, We could set a user as a "Priority Speaker" once and this setting remembered. 

Current server version: mumble_server-1.4.287.x64   

### Description

Have the "Priority Speaker" user flag saved and loaded to be persistant across server restarts.

### Mumble component

Server

### OS-specific?

No

### Additional information

Link to request I first posted on reddit https://www.reddit.com/r/mumble/comments/119lmy5/auto_set_a_user_as_priority_speaker_and_be/

**Comment by Krzmbrzl** [comment]
Remembering this flag across server restarts defeats what we are currently aiming for. In fact, we have recently removed the persistence of this flag across different channels (https://github.com/mumble-voip/mumble/pull/5925) which will be part of 1.5.

The priority speaker flag is not intended as a permanent attribute. Instead, it is intended as some sort of channel moderation option that is local to this channel and active only for that session.

Why do you need a persistent priority speaker flag? That seems rather inconvenient to me as this seems to make regular conversations a bit annoying :thinking:

**Comment by GR0B** [comment]
We use this as a "voice of god" were when the priority speaker talks, the microphones for all the other users in the channel are muted. 

Some of the clients are setup with microphones that always transmit and loud speakers in the same room. 
We have not been able to get echo cancellation to work in our enviroment and there is no option in the client for a half-duplex mode style echo cancellation, So we have been using the "priority speaker" feature.

**Comment by GR0B** [comment]
Deafen self while talking (push-to-talk-and-deafen) #5320 may be a alternative solution for use if priority speaker is being nerfed.

**Comment by Hartmnt** [comment]
As a workaround, you could try to set the priority speaker automatically using external moderation tools such as https://github.com/mumble-voip/mumo
