### ISSUE TITLE
DB connection

### ISSUE THREAD

**Issue by NurayJannat** [mumble-voip/mumble#6073]
### The issue

I want to run the DB in separate container. But I can't find where to start and where the statement of connection of DB in source code. Could anyone help me to find that?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
Depending on the used exact configuration, the connection to the DB happens via
https://github.com/mumble-voip/mumble/blob/master/src/murmur/ServerDB.cpp#L123
https://github.com/mumble-voip/mumble/blob/master/src/murmur/ServerDB.cpp#L144
or
https://github.com/mumble-voip/mumble/blob/master/src/murmur/ServerDB.cpp#L167

Not sure how this will help you though... The DB management is currently wrapped by Qt - but this will be replaced by a hand written version in the foreseeable future (I'm currently rewriting the entire server-side DB code).

**Comment by Hartmnt** [comment]
If you are just looking for a way to configure which database/connection to use you will have to edit your ``mumble-server.ini`` file. The relevant variables are documented here: https://github.com/mumble-voip/mumble/blob/master/auxiliary_files/mumble-server.ini#L16-L49

**Comment by NurayJannat** [comment]
Actually I wanted to connect mumble server with a mysql docker container under same docker network or with a remote mysql server. That's why I was asking how to modify the code in a way, that I will configure the address of database server, it will automatically hit that server.

**Comment by Krzmbrzl** [comment]
The address of the used server should be configurable via the config file. I don't think that modifying the code will be necessary.
