### ISSUE TITLE
Ubuntu PPA : Not updated

### ISSUE THREAD

**Issue by Antoine2tt** [mumble-voip/mumble#6074]
### The issue

Hi !

I just want to know if the ubuntu PPA are still maintened ? 

The version of mumble (and mumble server) i have with the PPA is 1.3.0 

Which is not the last final version.. 

Thanks !

### Mumble version

1.3.0

### Mumble component

Server

### OS

Linux

**Comment by Hartmnt** [comment]
> I just want to know if the ubuntu PPA are still maintened ?

Nope, but they will be again eventually. There is no ETA for that though. We also did not manage to get 1.5 into the Debian package freeze, which means it will take a long time to drip down to Debian based distros. For the foreseeable future, you will have to compile Mumble yourself, use a docker image, or stick with the old version. 

For progress on the PPA see:
https://github.com/mumble-voip/mumble-ubuntu-ppa/issues/16
