### ISSUE TITLE
Install the DBus policy file by default

### ISSUE THREAD

**Issue by K900** [mumble-voip/mumble#6078]
### Context

When setting up a new server with DBus remote control enabled.

### Description

Install the default DBus policy when running `make install`, which should also expose it automatically in (most) distribution packages.

### Mumble component

Server

### OS-specific?

Yes

### Additional information

When no DBus policy is installed, you have to go to https://wiki.mumble.info/wiki/DBus#Your_own_machine_with_root_access and add the policy to your system manually for Murmur to even start with DBus enabled, which is confusing for new users and creates additional work for distributions that want this to work out of the box (:wave:). It would be really nice to have a default policy in-tree.

**Comment by Krzmbrzl** [comment]
That would be [this file](https://github.com/mumble-voip/mumble/blob/master/auxiliary_files/config_files/mumble-server.conf), correct?
This should in theory already be installed via
https://github.com/mumble-voip/mumble/blob/c0880180867dce9d97bb0f14342799e977600008/auxiliary_files/CMakeLists.txt#L115

What version did you try this with?

**Comment by K900** [comment]
Yes, this is the file, and I only tried the current stable release. I'll close this then. Thanks and sorry!

**Comment by Krzmbrzl** [comment]
No problem - better to ask one time too much :)
