### ISSUE TITLE
Push-to-talk shortcut breaks when Mumble is not the active window

### ISSUE THREAD

**Issue by heyyitsdaniel** [mumble-voip/mumble#6080]
### Description

See title, more or less. If I click out of Mumble, or minimize it, or click over to my other monitor, my push-to-talk shortcut stops working. I am running Mumble as an administrator. 

### Steps to reproduce

1. have push to talk enabled
2. click outside Mumble window
3. try using push to talk

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
What version of Windows are you using?

**Comment by heyyitsdaniel** [comment]
> using

10 Home

**Comment by Krzmbrzl** [comment]
Could you try installing the 1.5 RC to see if that solves the problem? Iirc we re-enabled privileged access for the Windows build there :thinking:

**Comment by davidebeatrici** [comment]
Mumble is being run as administrator though.

**Comment by heyyitsdaniel** [comment]
> Could you try installing the 1.5 RC to see if that solves the problem? Iirc we re-enabled privileged access for the Windows build there 🤔

Seems to work. Thanks!

**Comment by Krzmbrzl** [comment]
Great! :+1:
I don't understand why running as administrator is not enough, but I guess that would be a question for a Windows dev...
