### ISSUE TITLE
Switching to mysql from sqlite

### ISSUE THREAD

**Issue by NurayJannat** [mumble-voip/mumble#6085]
### The issue

I want to switch to mysql database from sqlite. I have edited the mumble_server.ini file and uncommented these lines with appropriate values:
dbDriver=QMYSQL
dbUsername=my username
dbPassword=my password
dbHost=localhost
dbPort=3306
dbPrefix=mumble-server_

But it is not being connected and not running.

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
What is the server's output upon startup?
