### ISSUE TITLE
Short white noise static noise/pop when using JACK

### ISSUE THREAD

**Issue by fuck-shithub** [mumble-voip/mumble#6087]
### Description

OS: Gentoo Linux
Sound server: JACK, 256 frames @ 96 kHz, ALSA back-end. Same issue present at 48 kHz as well, although possibly less?
Audio hardware: MOTU M2 (Realtek also has same problem)

People tell me they hear a loud static sound coming from my mic for a split second. This has always been the case when using JACK, and a friend who also uses Linux with JACK has the same issue. You guys should really rework the audio system because this is garbage. Sometimes I've also had issues with weird audio glitches in output, but most of the time it's just static pops on my input. Sometimes it's so bad it's unbearable. I'm literally working on writing my own Mumble library and client due to dissatisfaction with the main Mumble implementation.

### Steps to reproduce

1. Use JACK
2. Suffer

### Mumble version

1.4.287

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by davidebeatrici** [comment]
We already have a library: https://github.com/mumble-voip/libmumble
One for audio as well: https://github.com/mumble-voip/libcrossaudio

Once deemed ready they will find their way into Mumble.

In any case, I have a MOTU M2 and a Realtek ALC1220. Both work flawlessly.

Could you check whether the issue can be reproduced with another backend, please?

**Comment by fuck-shithub** [comment]
I'm unsure how to test other JACK back-ends. ALSA is kind of the only usable back-end for Linux systems. I could theoretically test netjack but I don't want to set all that up. If you mean Mumble back-ends, I'm going to try compiling JACK with portaudio support and see if that is any better.

Also what audio system are you using? PipeWire, assuming from the biased priorities in libcrossaudio? When my friend still used PipeWire, I think there were no issues, but when I switched him over to JACK due to issues present in PipeWire back then that completely made PipeWire useless, I started hearing the issues happening on his end as well, so I think Mumble's JACK implementation is just outright broken, as it's both reproducible for me and my friend using JACK.

I've tried running PipeWire on my system before to see if it lives up to its promises, but the thing doesn't want to run without elogind, so it's essentially crapware to me. On my friend's Fedora system, we were unable to see programs using the PulseAudio APIs pop up in the JACK graph, making PipeWire essentially useless because we literally couldn't route Pulse programs around, which is essentially the same effect of running the traditional JACK with PulseAudio on top, which is what my current configuration looks like.
I've heard that this issue can somehow be resolved now but honestly this and the elogind requirement has left a bad taste in my mouth that this is just GNOME crapware.

Ah, my Mumble is done compiling, and it seems like Mumble's portaudio backend is broken too. It doesn't show up in the JACK graph at all and my mic doesn't work. Shit, seems like I have to compile Mumble with PulseAudio support. Time to suffer.

Also half a month into the development of my library, I found out you guys were already working on a library, so that's really cool. Still, your library is in C++, and I'm mainly a C dev, so I think I'll continue my efforts. As far as I can see, libmumble still has no high-level abstractions like event-based callbacks, but instead you have to do all the events yourself through manually encoding and decoding packets?

Okay my Mumble finished compiling again, with pulseaudio support. And... what? Just like with portaudio, there is no audio. It doesn't pick up my mic, and doesn't even output anything. That's kind of weird. While I have experienced portaudio acting up in other programs, pulseaudio usually always works, because I run pulseaudio on top of JACK. Even programs with obscure audio systems like OpenMPT tend to work fine with pulseaudio. But Mumble? No. None of it. So yeah, very weird. I wonder if I'm the only one or whether pulseaudio support in Mumble is just broken just like portaudio and the glitchy JACK implementation.

**Comment by davidebeatrici** [comment]
> Also half a month into the development of my library, I found out you guys were already working on a library, so that's really cool. Still, your library is in C++, and I'm mainly a C dev, so I think I'll continue my efforts.

We're actually thinking about providing C bindings for the library.

> As far as I can see, libmumble still has no high-level abstractions like event-based callbacks, but instead you have to do all the events yourself through manually encoding and decoding packets?

Callbacks are fully implemented, for both TCP and UDP.

The `Pack` class represents a packet and provides the decoder and encoder.

> Okay my Mumble finished compiling again, with pulseaudio support. And... what? Just like with portaudio, there is no audio. It doesn't pick up my mic, and doesn't even output anything. That's kind of weird. While I have experienced portaudio acting up in other programs, pulseaudio usually always works, because I run pulseaudio on top of JACK. Even programs with obscure audio systems like OpenMPT tend to work fine with pulseaudio. But Mumble? No. None of it. So yeah, very weird. I wonder if I'm the only one or whether pulseaudio support in Mumble is just broken just like portaudio and the glitchy JACK implementation.

Are there any X-runs?

**Comment by fuck-shithub** [comment]
I'm not sure. I don't think the issue is related to X-runs because when I was running Audacity at the same time, my friends still reported they heard the static pops while Audacity did not report any dropouts. Also my X-run diagnosis always gets inflated by misbehaving programs with similarly poor JACK implementations like e.g. web browsers.

**Comment by fuck-shithub** [comment]
Also it turns out my pulseaudio was in a broken state, so after restarting pulse, Mumble works with pulseaudio fine. Now let's see if it still pops with this setup.
