### ISSUE TITLE
Audio processing

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6088]
### The issue

Is there any doc regarding how mumble processes audio data?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
No docs that I am aware of (other than the source code itself). What exactly are you looking for?

**Comment by Neloy262** [comment]
I just want to explore a bit more about echo cancellation.

**Comment by Krzmbrzl** [comment]
So are you looking for code parts inside Mumble that handles echo cancellation or are you interested how Mumble performs echo cancellation in a more general way.
In case of the latter: we use the echo cancellation feature of SpeexDSP - almost all of the magic is handled there

**Comment by Neloy262** [comment]
Yes I am looking for code parts inside mumble

**Comment by Krzmbrzl** [comment]
Not so fast, stale bot. I do intend to answer this properly. I'll only have to find the time.

**Comment by Krzmbrzl** [comment]
For how echo cancellation is implemented, have a look at the `AudioInput.cpp` file. In particular
https://github.com/mumble-voip/mumble/blob/e0bc60086db27ee9dc52fc9db7ee4719420de9b9/src/mumble/AudioInput.cpp#L603
is probably a good start to trace things around.
