### ISSUE TITLE
Share Feature Suggestions

### ISSUE THREAD

**Issue by hogum** [mumble-voip/mumble#6089]
### Context

Connect to new server

### Description

Can the client support some kind of link to add a new server?Like steam://connect/xxx
Or how to build a client that automatically connects to a server :D
Recently, when I was using Rustdesk, I found that they can use a certain server by directly modifying the file name.Like rustdesk-host=xxx,key=xxx.exe

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
This already exists. See e.g. https://wiki.mumble.info/wiki/Mumble_URL
I _think_ you can get an appropriate URL via the context menu of a channel on a given server, but that I am not sure of atm.
