### ISSUE TITLE
Generate custom murmur.ini file

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6090]
### The issue

Is there a way to generate a custom murmur.ini file during build?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Neloy262** [comment]
By default, it sets up sqlite. I want to configure for mysql.

**Comment by Krzmbrzl** [comment]
And why do you want to make these changes to happen during build?
The way to go here is to simply change the INI file manually.
