### ISSUE TITLE
Add dialog to disable mute cue when it is first activated

### ISSUE THREAD

**Issue by Hartmnt** [mumble-voip/mumble#6094]
### Context

Multiple users have reported issues related to confusion caused by the mute cue, which is now enabled by default.

#5558
#5921

And several instances on Matrix.

### Description

Mumble should prompt the user with a dialog asking them, if they want to keep the mute cue enabled.

The dialog should:
* Only trigger once, when the mute cue is activated for the first time
* Do not trigger, if the user switches the mute cue on or off manually
* Be accessible (a11y)

### Mumble component

Client

### OS-specific?

No

**Comment by kbanushi** [comment]
Hi, I would like to work on this issue and have talked to someone in the Matrix about it as well.  They recommended that I consider adding an option to disable the mute cue from the setup wizard.  Is there a preference on how to solve this issue or would both a popup and a setting in the wizard be preferred?

**Comment by Krzmbrzl** [comment]
> would both a popup and a setting in the wizard be preferred?

absolutely, yes. Many people skip the wizard and would then still be confused about the mute cue once they encounter it. A popup is the way to go here. Adding an option to the audio wizard is a nice bonus on top of that.
