### ISSUE TITLE
Can't build by docker file

### ISSUE THREAD

**Issue by peylight** [mumble-voip/mumble#6096]
### Description

When i try to run this command:
`docker build --pull -t mumble-server github.com/mumble-voip/mumble#master`
I see an error:
`ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1996830079/Dockerfile: no such file or directory`

### Steps to reproduce

1. Install docker by docker manual.
2. Run this command:
`docker build --pull -t mumble-server github.com/mumble-voip/mumble#master`

### Mumble version

master

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Yeah the docker image has migrated to its own repository: https://github.com/mumble-voip/mumble-docker

**Comment by peylight** [comment]
I make a script file to build mumble server release inside docker.
You can download these two files:
[mumble-builder.sh](https://paste.debian.net/1276085/)
[Dockerfile_Debian.template](https://paste.debian.net/1276086/)
And then run the `./mumble-builder.sh` script.
