### ISSUE TITLE
Disable/Enable Encryption Feature ?

### ISSUE THREAD

**Issue by aswin19996** [mumble-voip/mumble#6097]
### Context

Is there a way to enable or disable encryption feature ?

### Description

I would like to know, if the encryption of packets can be disabled during the VoIP communication between the client and server, so the packets are exchanged over plain text and unencrypted?

### Mumble component

Both

### OS-specific?

No

### Additional information

I would like to integrate this application with an open source software, and use the security feature provided by them.

**Comment by Krzmbrzl** [comment]
No there is no such option and there won't ever be one. Encryption is part of the Mumble protocol and not using it poses a security threat.
