### ISSUE TITLE
 Mumble Launcher Error-1 "Unable to config environment"

### ISSUE THREAD

**Issue by Smitchi74** [mumble-voip/mumble#6102]
### The issue

Hello smarty-folk!

As of this morning, when I open Mumble, this appears every time.
Any work-arounds?  Was using windows 10 while it failed. Updated to windows 11 today just in case that helped (didn't). 
I've searched online and found nothing.
Oddly enough, when I search Mumble's properties it doesn't show the version # (hence I typed in a BS #1.4.287 just so this post would be granted).

TIA for your help!!

![Cawefwepture](https://user-images.githubusercontent.com/130411628/231013693-c93efdc7-76ba-4548-9c0c-887d3f00a12d.JPG)

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Additional information

Thanks for your help on this - seriously!

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/6313cc57183c7290a5d864b83cc9bee3b8f9a594/src/mumble_exe/mumble_exe.cpp#L140-L143

https://github.com/mumble-voip/mumble/blob/6313cc57183c7290a5d864b83cc9bee3b8f9a594/src/mumble_exe/mumble_exe.cpp#L70-L119

Could you try to reinstall Mumble, please?
