### ISSUE TITLE
Simplex

### ISSUE THREAD

**Issue by Timon2023** [mumble-voip/mumble#6115]
### Context

When one user presses the PTT (Push-To-Talk) button, he sends his voice to the network while other users can only listen. When one user speaks, other users can only listen, not speak. If another user tries to press the PTT button while someone is already talking, they will have a red light and an error sound, indicating that they cannot talk now because the channel is busy. How and where to change in the source code? For Mumla applications to work this way, or does it need to be changed on the Mumla source code? Tell me where to dig?

### Description

Simplex

### Mumble component

Server

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
I'm not convinced that this is a feature that Mumble should have. What would it be good for? Users can already see (and hear) when someone else is talking. If you want to ensure that users can't interrupt, then you could manage that with ACLs or by assigning the current speaker priority status (then the interrupting voices are played at lower volume).

**Comment by Krzmbrzl** [comment]
> How to do it, ACL priority speaker not working in Mumla app

That sounds like it should be a feature request for Mumla instead.
The ACL stuff however is handled on the server, so that'd work. However, with ACLs you could create a channel in which only the operator can talk. But not switch that depending on whether or not the operator is currently talking.

I still haven't quite understood what your exact usage scenario is. Why is it necessary to have everyone else muted if a person is currently speaking? I would expect people to shut up and listen if someone speaks with them.

**Comment by Timon2023** [comment]
1. Why is it necessary? because when 1 user speaks and at the same moment another user speaks, noise appears and incomprehensible speech occurs. in the Zello application, if someone is talking, then the rest are listening, if another user presses the ptt button while another user is talking, then his ptt button becomes inactive or a message pops up stating that the channel is busy. So I wanted to make it happen. It turns out that this should be implemented on the Mumla side?
2. And how to save the history of audio conversations in the chat?

**Comment by Krzmbrzl** [comment]
1. This is the feature that I am not sure is a good idea to have in Mumble. I don't think this is really necessary. But since this is a client side feature, the Mumla dev might see this differently and decode to implement it nonetheless. 
2. This is not possible
