### ISSUE TITLE
Unable to Install latest client on computer.

### ISSUE THREAD

**Issue by Luka-Nightwind** [mumble-voip/mumble#6122]
### The issue

Hello there,

I am trying to install Mumble latest first on my Windows 10 machine on an admin account and getting this error. Google / ChatGPT haven't found any solution that worked, or any instance of this which feels strange.
![image](https://user-images.githubusercontent.com/51938120/235544232-9aa94763-dfd0-483e-8fbc-822bd71213bd.png)

I've tried disabling UAC, that didn't help, making the folder manually, get this error. Haven't had installing issues on 
![image](https://user-images.githubusercontent.com/51938120/235545156-34bd92e2-b062-4da7-92cd-6a8eb3c15e4f.png)

I'm almost certain it's a permissions issue.

### Mumble version

 1.4.287 Client

### Mumble component

Client

### OS

Windows

**Comment by davidebeatrici** [comment]
There's something wrong with the privileges in `Programs` or its parent(s), I would check their ACL.

**Comment by Luka-Nightwind** [comment]
> There's something wrong with the privileges in `Programs` or its parent(s), I would check their ACL.

I manually made the mumble folder, then granted Everyone permissions in security and it worked.

Uhhh how do I close this now? Not used to using Git

**Comment by davidebeatrici** [comment]
Please note that giving write access to everyone can be considered a security issue.

**Comment by Luka-Nightwind** [comment]
I'll remember that, haven't had this issue other than mumble. Thanks for the help though
