### ISSUE TITLE
Mention about SignPath Foundation and free code certificate in Readme.md missing

### ISSUE THREAD

**Issue by SabotageAndi** [mumble-voip/mumble#6128]
### Description

Hi
I am the Developer Evangelist from SignPath.

I noticed that there is no mention of us in the readme. 
Could you please add this to your Readme:

```
## Code Signing
This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=mumble), and a free code signing certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=mumble)
```

If you want, I can provide a Pull Request for this change.

Thanks!

### Steps to reproduce

-

### Mumble version

Source

### Mumble component

Both

### OS

Other

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Oh yes, indeed. Thanks for the reminder! I'll add it via #6129

**Comment by SabotageAndi** [comment]
Awesome! Thanks!
