### ISSUE TITLE
Shortcut toggling positional audio

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#6133]
### Discussed in https://github.com/mumble-voip/mumble/discussions/6130

<div type='discussions-op-text'>

<sup>Originally posted by **jaxankey** May 12, 2023</sup>
Hi all,

Is it possible to bind a button to enable / disable positional audio? When we are racing, sometimes we need to pop out of the local neighborhood and talk to / listen to everyone. 

There is "Shout", but this is one-way (I cannot hear everyone far away) and you have to hold the button, which will cause us to crash if we do it too much. I found "Unlink Plugin", which kinda almost seems like it affects whether link is enabled, but it is unpredictable and I can't get it to do what I want.

Thanks!
Jack</div>

**Comment by GrossTrevor** [comment]
Hi! I'm looking for a good first issue and came across this. Could I be assigned to this issue if it is still open?

**Comment by Krzmbrzl** [comment]
Sure, go ahead :)
