### ISSUE TITLE
File sharing

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6136]
### The issue

Could someone direct me to the segment of the codebase that handles file sharing?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by felixsinger** [comment]
AFAIK Mumble isn't capable of file sharing.

**Comment by Krzmbrzl** [comment]
Yeah, file sharing is not supported. However, there is an open feature request for it: https://github.com/mumble-voip/mumble/issues/3324
