### ISSUE TITLE
ChannelListener: Save Channellist somewhere

### ISSUE THREAD

**Issue by IT-Ing** [mumble-voip/mumble#6137]
### Context

Using the Client, automatic setup of the communication environment at startup

### Description

If you use mumble in a more complex channel setup, it is useful to have an ear in some standard channels. The ChannelListener feature ist great, but after a logout, you have to add the ear manually to the channels you are interested in during the login process.

Is it possible to save the information somewhere? Either as a client side configuration (listen to the following channels by default at login) oder as a server feature (save the ChannelsListen state for the account)?

### Mumble component

Both

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
If you upgrade your server to 1.5, you will (should) find that the server will remember channel listeners (and their volume adjustment) for registered users.
