### ISSUE TITLE
Can not open URLs from chat window anymore

### ISSUE THREAD

**Issue by sithdaddy** [mumble-voip/mumble#6139]
### Description

I am using the flatpack version of mumble on Linux Mint.

The issue i am facing is that URLs to websites in the chat window do not open a browser anymore. The emphasis lies on "anymore". It used to work fine until a few weeks ago i think.

- My main browser is firefox. It is set in the system as main browser.
- I have also tried to use Chrome as default browser , it did not help.

When i hover over the URL , the cursor turns to a pointing hand. But when i click on the URL , nothing happens.

### Steps to reproduce

1. start flatpack version 1.4.287 of mumble 
2. connect to server
3. receive or enter a URL to a website in chat
4. click on that URL in the chat window in order to open the website.

### Mumble version

1.4.287

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Relevant log output

```shell
<D>2023-05-20 10:41:57.609 PulseAudio 15.0.0 from libpulse.so.0
<X>2023-05-20 10:41:57.612 PipeWire 0.3.35 from libpipewire-0.3.so.0
<D>2023-05-20 10:41:57.613 JACK 3.0.0.0 (using PipeWire 0.3.35) from libjack.so.0
<D>2023-05-20 10:41:57.619 libopus unknown from /app/lib/mumble/libopus.so.0
<W>2023-05-20 10:41:57.619 CELT bitstream 8000000b from /app/lib/mumble/libcelt0.so.0.7.0
<W>2023-05-20 10:41:57.619 Theme: "Mumble"
<W>2023-05-20 10:41:57.619 Style: "Lite"
<W>2023-05-20 10:41:57.619 --> qss: ":themes/Mumble/Lite.qss"
<W>2023-05-20 10:41:57.620 Locale is "en_CA" (System: "en_CA")
<W>2023-05-20 10:41:57.635 Database SQLite: "3.36.0"
<W>2023-05-20 10:41:57.643 GlobalShortcutX: Using XI2 2.4
<W>2023-05-20 10:41:57.666 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2023-05-20 10:41:57.820 AudioInput: Opus encoder set for high quality speech
<W>2023-05-20 10:41:57.820 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2023-05-20 10:41:57.822 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2023-05-20 10:41:57.823 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2023-05-20 10:41:57.824 Public list disabled
<W>2023-05-20 10:41:57.825 Zeroconf: Third-party browser API reports error -65537
<W>2023-05-20 10:41:57.832 Updating application palette
<W>2023-05-20 10:41:57.852 AudioInput: Using Speex as noise canceller
<W>2023-05-20 10:41:59.118 Database SQLite: "3.36.0"
<W>2023-05-20 10:41:59.118 OpenSSL Support: 1 (OpenSSL 1.1.1s  1 Nov 2022)
<W>2023-05-20 10:41:59.143 ServerHandler: TLS cipher preference is

<W>2023-05-20 10:48:52.548   OpenType support missing for "Ubuntu", script 20
<W>2023-05-20 10:48:52.552   OpenType support missing for "Ubuntu", script 17
<W>2023-05-20 10:49:07.493 AudioInput: Opus encoder set for high quality speech
<W>2023-05-20 10:49:07.493 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2023-05-20 10:49:07.498 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2023-05-20 10:49:07.498 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2023-05-20 10:49:07.523 AudioInput: Using Speex as noise canceller
```

**Comment by Krzmbrzl** [comment]
Does it work with the non-flatpak version? I could imagine this being a sandboxing issue

**Comment by sithdaddy** [comment]
any idea how it could be fixed ? it looks like the flatpack version is using wine to run mumble ?

**Comment by Krzmbrzl** [comment]
Conceptually, the packagers will have to somehow punch a hole in the sandbox that allows Mumble to open the browser (if that's what is actually the issue here). But how that works specifically, I don't know. 

> Not keen on using non flatpack version its somewhat behind in some features.

If you know how that works, self-compiling might be an option (see the corresponding docs).

**Comment by sithdaddy** [comment]
It seems like something on this specific PC got botched somehow and that is why flatpak mumble does not open URLs anymore.

I installed the same flatpak version of mumble on the same linux distro (linux mint) and it is able to open URLs from the chat window.

Is there anything i could look for that might have caused this issue ?

**Comment by Krzmbrzl** [comment]
Hm. I'm far from being a Flatpak expert, but something that's always worth a try is to start the program from a terminal window to see whether clicking on an URL prints some sort of error to the console. 

Other than that, I would also check whether `xdg-open` works as expected for URLs.

**Comment by sithdaddy** [comment]
There is indeed an issues. Here is an extract from the terminal when i click on an URL in the chat window...

```
...
C42: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop

B473: <- :1.72 return error org.freedesktop.DBus.Error.UnknownMethod from C42
...
```


`xdg-open` works fine. it opens URLs without any issues.

**Comment by Krzmbrzl** [comment]
Looks like some sort of DBus issues. But I don't know what might be wrong :thinking:
