### ISSUE TITLE
Not display full welcome text if contains single quote

### ISSUE THREAD

**Issue by CGsama** [mumble-voip/mumble#6144]
### Description

When the welcome text include the escape word &#39; for single quote, the welcome text will cut after the display the single quote

### Steps to reproduce

add 
```
&#39;
``` 
to welcome text in server

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by CGsama** [comment]
try to use &comma; also, but cut at &comma , seems is the ';' got the problem

**Comment by CGsama** [comment]
okay is the escape problem, have to use \', but not work for ,

**Comment by Krzmbrzl** [comment]
How do you set the welcome message? Via the INI file,I assume. How does your input look exactly? 'cause you need to take care of escaping inside the INI format itself.

**Comment by CGsama** [comment]
Thanks for point out its INI file! Warp with quote would make comma work
