### ISSUE TITLE
Enable push to talk shortcut button settings in wayland session

### ISSUE THREAD

**Issue by denppa** [mumble-voip/mumble#6146]
### The issue

Many wayland compositors are able to forward shor cut keys to certain apps, the shortcut settings should be enabled at this point in wayland development.

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

**Comment by Krzmbrzl** [comment]
It should be possible to enable shortcuts. But afaik they still don't work properly - only while another X window has focus

**Comment by denppa** [comment]
I am running `Mumble version 1.5.517`, not sure if the patch has been reversed in this version. I had to explicitly start the app in xwayland mode to set the shortcuts. Though as I am using Hyprland, I was able to set in the configuration to forward my PTT buttons to mumble and therefore it works without focus even.

**Comment by Krzmbrzl** [comment]
> I am running Mumble version 1.5.517, not sure if the patch has been reversed in this version. I had to explicitly start the app in xwayland mode to set the shortcuts, it works if I have focus, but not otherwise.

Yeah, shortcuts rely on X11 functionality so it makes sense to me that xwayland mode is required for them to work. Afaik shortcuts then work whenever another application in X11 mode has focus. But that's all.
In terms of how to pass along other kinds of shortcuts to the application, I simply don't know enough about that to comment on it in any way :thinking:

**Comment by Hartmnt** [comment]
Basically, for the "correct" way to enable global shortcuts in Wayland #5976 has to be completed.
In the mean time you can try this hacky workaround: https://github.com/mumble-voip/mumble/issues/5257#issuecomment-1279844091
