### ISSUE TITLE
Mumble Admin does not work

### ISSUE THREAD

**Issue by Megamichi123** [mumble-voip/mumble#6152]
### Description

Hello according to the guide you should select admin in the dropdown menu but it doesn't work somehow.

![image](https://github.com/mumble-voip/mumble/assets/125511169/adf7aff2-77bc-4e35-b650-023312ea8ea8)

can someone tell me how ?

I just can't push the arrow.

But I'm superuser.

### Steps to reproduce

1. Right click on the root channel
2. Open the Groups tab
3. Clicking on the small arrow does not work

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Haven't tried

### Screenshots

![image](https://github.com/mumble-voip/mumble/assets/125511169/03b98e5c-320a-4a06-838a-63d4b403375f)

**Comment by Krzmbrzl** [comment]
What version is the server you are connecting to? And is this (the server) a new setup or had it been used before?

**Comment by Megamichi123** [comment]
Client: 1.4.287
Server: 1.3.4-1

**Comment by Megamichi123** [comment]
And I can't get back to it after I stopped the server for a moment and started it again

**Comment by Krzmbrzl** [comment]
> And I can't get back to it after I stopped the server for a moment and started it again

What do you mean by that? You restart the server and then you can no longer authenticated as the user that you have created before?

Could you post the server log here?

**Comment by Megamichi123** [comment]
![image](https://github.com/mumble-voip/mumble/assets/125511169/3a6699ca-241f-40cc-b16b-9cb93966a633)

**Comment by Krzmbrzl** [comment]
That's the client's log. I would like to see the server log (from starting to when you fail to connect to your server).

**Comment by Megamichi123** [comment]
where can i find the server log i always start the server with murmurd

do I have to somehow --log or do it

**Comment by Megamichi123** [comment]
where can i find the server log i always start the server with murmurd

do I have to somehow --log or do it

**Comment by Rovanion** [comment]
This piece of the documentation could be of help: https://wiki.mumble.info/wiki/Murmurguide#Windows_3

**Comment by Megamichi123** [comment]
<X>2023-06-21 15:02:35.556 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:02:35.557 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:02:37.362 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:02:37.450 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:02:37.450 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:02:38.343 Performed initial PBKDF2 benchmark. Will use 4000 iterations as default
<W>2023-06-21 15:02:38.343 Generating new tables...
<W>2023-06-21 15:02:38.478 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:02:38.526 1 => Password for 'SuperUser' set to 'ZxTByx4iY7Jd'
<W>2023-06-21 15:02:38.594 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:02:38.607 1 => Stopped
<W>2023-06-21 15:13:20.520 Caught SIGHUP, will reopen /home/megamichi/murmur.log
<W>2023-06-21 15:13:20.520 Log rotated successfully
<C>2023-06-21 15:13:20.521 Caught SIGTERM, exiting
<W>2023-06-21 15:13:20.521 Killing running servers
<W>2023-06-21 15:13:20.521 Shutting down
<X>2023-06-21 15:14:15.778 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:14:15.778 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:14:17.606 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:14:17.694 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:14:17.694 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:14:17.807 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:14:17.828 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:14:17.841 1 => Stopped
<X>2023-06-21 15:24:46.322 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:24:46.323 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:24:48.132 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:24:48.219 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:24:48.220 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:24:48.335 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:24:48.354 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:24:48.366 1 => Stopped
<X>2023-06-21 15:25:14.248 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:25:14.249 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:25:16.071 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:25:16.158 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:25:16.158 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:25:16.270 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:25:16.289 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:25:16.302 1 => Stopped
<X>2023-06-21 15:28:16.051 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:28:16.052 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:28:17.859 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:28:17.945 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:28:17.946 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:28:18.059 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:28:18.077 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:28:18.093 1 => Stopped
<X>2023-06-22 07:14:18.145 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-22 07:14:18.146 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-22 07:14:19.951 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-22 07:14:20.038 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-22 07:14:20.038 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-22 07:14:20.153 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-22 07:14:20.174 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-22 07:14:20.187 1 => Stopped
<X>2023-06-25 15:41:23.774 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-25 15:41:23.774 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-25 15:41:25.575 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-25 15:41:25.662 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-25 15:41:25.662 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-25 15:41:25.773 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-25 15:41:25.793 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-25 15:41:25.805 1 => Stopped

**Comment by Megamichi123** [comment]
`<X>2023-06-21 15:02:35.556 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:02:35.557 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:02:37.362 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:02:37.450 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:02:37.450 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:02:38.343 Performed initial PBKDF2 benchmark. Will use 4000 iterations as default
<W>2023-06-21 15:02:38.343 Generating new tables...
<W>2023-06-21 15:02:38.478 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:02:38.526 1 => Password for 'SuperUser' set to 'ZxTByx4iY7Jd'
<W>2023-06-21 15:02:38.594 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:02:38.607 1 => Stopped
<W>2023-06-21 15:13:20.520 Caught SIGHUP, will reopen /home/megamichi/murmur.log
<W>2023-06-21 15:13:20.520 Log rotated successfully
<C>2023-06-21 15:13:20.521 Caught SIGTERM, exiting
<W>2023-06-21 15:13:20.521 Killing running servers
<W>2023-06-21 15:13:20.521 Shutting down
<X>2023-06-21 15:14:15.778 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:14:15.778 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:14:17.606 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:14:17.694 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:14:17.694 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:14:17.807 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:14:17.828 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:14:17.841 1 => Stopped
<X>2023-06-21 15:24:46.322 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:24:46.323 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:24:48.132 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:24:48.219 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:24:48.220 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:24:48.335 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:24:48.354 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:24:48.366 1 => Stopped
<X>2023-06-21 15:25:14.248 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:25:14.249 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:25:16.071 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:25:16.158 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:25:16.158 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:25:16.270 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:25:16.289 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:25:16.302 1 => Stopped
<X>2023-06-21 15:28:16.051 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:28:16.052 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:28:17.859 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:28:17.945 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:28:17.946 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:28:18.059 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:28:18.077 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:28:18.093 1 => Stopped
<X>2023-06-22 07:14:18.145 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-22 07:14:18.146 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-22 07:14:19.951 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-22 07:14:20.038 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-22 07:14:20.038 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-22 07:14:20.153 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-22 07:14:20.174 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-22 07:14:20.187 1 => Stopped
<X>2023-06-25 15:41:23.774 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-25 15:41:23.774 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-25 15:41:25.575 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-25 15:41:25.662 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-25 15:41:25.662 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-25 15:41:25.773 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-25 15:41:25.793 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-25 15:41:25.805 1 => Stopped
`

**Comment by Krzmbrzl** [comment]
And you tried connecting to the server while recording this log? Then it looks like there is some firewall issue as the server doesn't even report a connection attempt or a low-level issue with the SSL stuff :thinking:

You could try whether updating the server to 1.4 has any effect.

**Comment by davidebeatrici** [comment]
> TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use

Probably another instance of the server running on that port.
