### ISSUE TITLE
Your software is good

### ISSUE THREAD

**Issue by larsenv** [mumble-voip/mumble#6156]
### The issue

I'm using my Mac because someone has a crappy laptop and can't use Discord. I don't echo like hell and this program was easy to figure out. Thank you developers. It even works on iOS.

### Mumble version

IT3490UI-4OP2I34UT8902-OPT

### Mumble component

Client

### OS

macOS

### Additional information

THANK YOU MUMBLE

**Comment by Krzmbrzl** [comment]
You're welcome :)
And thanks for the kind words!
