### ISSUE TITLE
Mumble lags when playing l4d2

### ISSUE THREAD

**Issue by DkBobo** [mumble-voip/mumble#6157]
### The issue

I wanted to try out l4d2 with my brother with proximity chat and whenever we tick off the Source Engine plugin with l4d2 open, mumble begins to lag like hell and barely any sounds get through, and if they do it's very short and very delayed. And the whole mumble application begins to lag as well.

It seems to be the same issue as issue #5728 but it was never resolved. 
Any help would be appreciated.

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
Then let's keep tracking it in #5728.
