### ISSUE TITLE
Certain Mumble elements hard to read as they have a hard-coded background color 

### ISSUE THREAD

**Issue by jvbsl** [mumble-voip/mumble#6160]
### Description

While it seemed that this was already addressed
https://github.com/mumble-voip/mumble/issues/1438

it does not work for me on Manjaro XFCE in Light/Dark or No theme on Linux, as you can see in the screenshot below.

It stems from this method:
[ApplicationPaletteTemplate.h:](https://github.com/mumble-voip/mumble/blob/master/src/mumble/ApplicationPaletteTemplate.h#L65C10-L65C33)

It is called twice in the startup process, at the first execution everything is fine and set correctly and at the end of the method resetAllProperties is called, which resets all loaded theming information, at the second execution as the theming information was reset, the application palette is set to m_originalPalette, which does not seem to reset the theming for everything, but it does apply to QWhatsThis, which results in the wrong look.

One way to workaround that would be to just remove the resetAllproperties call, which worked for me(for Light and Dark theme, not for the "No theme"), but I do not know what kind of side effects that would have, especially on other systems.

Another way to workaround the problem is to insert
```
QApplication::processEvents();
QApplication::processEvents();
```
at https://github.com/mumble-voip/mumble/blob/master/src/mumble/main.cpp#L594

yes twice, don't ask me why but it does work for Light and Dark themes(not the "No theme") as well.

To fix the problem for "No theme" which is my preferred option I found a simple workaround as well, which would be to insert the following code at https://github.com/mumble-voip/mumble/blob/master/src/mumble/ApplicationPaletteTemplate.h#L72:
```
if (!m_tooltipbase_active || !m_tooltiptext_active) {
    newPalette.setBrush(QPalette::Active, QPalette::ToolTipBase, newPalette.window());
    newPalette.setBrush(QPalette::Active, QPalette::ToolTipText, newPalette.windowText());
}
```
basically if either the theming for tooltipbase or the theming for tooltiptext is not set, we fallback to color the active ToolTipBase to the window brush, and the active ToolTipText to the windowText.
While it works for me I again don't know the side effects for other system configurations.

I'm open for suggestions or any ideas. Especially if someone knows why resetAllProperties needs to be called.

Thank you very much

### Steps to reproduce

1. Choose any theme on Linux
2. Look at a comment(which uses QWhatsThis for displaying)

### Mumble version

e828ef0458927b21df590f84efce051abd33b2b0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Same of course for version 1.5

### Screenshots

![image](https://github.com/mumble-voip/mumble/assets/13928225/634c8d3a-fc68-4815-8d7f-3e35d4f15b6e)

**Comment by Hartmnt** [comment]
Both the "What's This" and Mumble comment tool tips are correctly styled for me using Mumble 1.5, XFCE and Qt 5.15.8 with the Mumble - Dark theme. Which version of Qt are you running Mumble with?

The "resetAllProperties" was introduced in cbe3956e40e27ed985efc08e0217dbfdd4f120 . At first glance I was not able to understand why it was needed.
FYI, the Mumble theming was refactored some time ago and the actual theme files were split into their own repository. This refactoring could hypothetically have left some code in the Mumble source tree which is no longer needed.
On the other hand this could be one of the many Qt bugs or behavior changes that break Mumbles theming every once in a while...

Let's first try to fully understand what exactly causes this, before trying to fix it.

**Comment by jvbsl** [comment]
I use QT version 5.15.9.

I read somewhere that QWhatsThis is kinda special case, as it does not use the style information correctly, that is the reason why it needs to be set explicitly using QPalette, otherwise I would not need the last workaround for "No theme".

For normal themes we in turn set the QPalette and it should work in theory.

Could perhaps someone else debug, whether updateApplicationPalette, is called for them twice as well? I mean the workaround using two times processEvents could be some kind of timing issue perhaps, I don't really know though, sleeping instead did not help at all.

> Let's first try to fully understand what exactly causes this, before trying to fix it.

That's the reason why I only opened an issue, because I would not like to introduce these workarounds with more information, and whether it works on other systems or not^^

**Comment by Krzmbrzl** [comment]
Iirc, we're not using `QPalette` at all, because we are using stylesheets and those can't be combined with setting colors in-code via `QPalette`. I consider this to be somewhat dumb but that's how Qt decided to implement things (in Qt 5) :shrug: 

If `QWhatsThis` can't be styled via stylesheets - which is how I understood your last comment - then this seems to be a Qt bug and trying to work around this in our code seems error-prone and a bit futile :thinking:

**Comment by jvbsl** [comment]
But there is at least code that uses `QPalette` and affects the QWhatsThis https://github.com/mumble-voip/mumble/blob/master/src/mumble/ApplicationPaletteTemplate.h#L65C10-L65C33 

And yes I think one could consider it a bug, but as it is known for some time now, I don't think QT has any interest of fixing this^^
I don't think these small changes are that big of a workaround to be really error prone. But I thought to ask here if some one knows more about the whole system. I mean it isn't that big of a priority to me atm, as I don't really use comments.
And as I understood it was planned to switch to QT6 some time in the future, I guess it should not be a problem in QT6^^

**Comment by Hartmnt** [comment]
> If `QWhatsThis` can't be styled via stylesheets

It certainly can be in some configurations, as my ``QWhatsThis`` objects are correctly styled with any of the available styles. Do you have any issues with that on your client, @Krzmbrzl ? This could be a change introduced in some recent Qt 5 version.

**Comment by Hartmnt** [comment]
Still can not reproduce this with Ubuntu 23.10 with Qt 5.15.10 neither with XFCE nor with KDE. The user comments as well as any other "What's this?"-Popup are correctly styled according to the theme selected in Mumble. Even the "None" theme works...

**Comment by jvbsl** [comment]
As I have a new Laptop and in that turn switched to KDE, I just wanted to try it, now I've got this one:
![image](https://github.com/mumble-voip/mumble/assets/13928225/4d932934-6b6a-48aa-af34-818b63329f49)

But I do not have the problem with the description QWhatsThis anymore

**Comment by Hartmnt** [comment]
@jvbsl Right, so this specific unreadable notice I can reproduce with KDE by setting the system theme to dark and applying the ``None`` Mumble theme. However, the comments and all other "What's this" are fine. All other themes/configurations are fine. Can you confirm that @jvbsl ?

**Comment by jvbsl** [comment]
Yes it was in the none theme as well(which I do prefer for all my applications, because it matches the rest)
So for the new system, which is now KDE, I did not see any other theming issues, including the one that was in the initial issue.

But on my old Laptop I still have the exact issue from the first message.
But to be honest I don't care much about that currently, as long as I won't switch back to XFCE(which I probably won't in the near future) and have that same issue on my current Laptop.

But the new issue I found would be nice to have fixed as well ofc^^

**Comment by Hartmnt** [comment]
@jvbsl Thanks for checking. Well I could not and still can't reproduce this on XFCE. But I will have a quick look at the notice. It is a simple ``QLabel`` which is probably hard-coded to yellow somwhere...

**Comment by Hartmnt** [comment]
There we go:

https://github.com/mumble-voip/mumble/blob/5d895617402a32d0fb02eb9d411df24d80ffbe03/src/mumble/Themes.cpp#L145-L148

I will go ahead and update the title of this issue.

**Comment by jvbsl** [comment]
Alright, thank you very much ;)
