### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by shahbazaly** [mumble-voip/mumble#6161]
### The issue

Hi, I am trying to perform static build on windows following the the instructions as it is. I have installed the dependencies manually and have been stuck on this error for sometime now. Any solutions are more than welcome. Thanks!

C:\Users\Shahbaz\mumble\build>cmake -G "Ninja" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Shahbaz/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DIce_HOME=C:/Users/Shahbaz/vcpkg/installed/x64-windows-static-md" "-DCMAKE_BUILD_TYPE=Release" ..
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at CMakeLists.txt:54 (include):
  include could not find requested file:

    FindPythonInterpreter

CMake Error at CMakeLists.txt:61 (find_python_interpreter):
  Unknown CMake command "find_python_interpreter".

-- Configuring incomplete, errors occurred!

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
`git submodule update --init --recursive`

**Comment by shahbazaly** [comment]
Thanks! I did the update and now am stuck to a similar problem. How can I fix the python version issue?

`
-- SndFile found | Version: 1.2.0
-- Boost component found: system | Version: 1.82.0
-- Boost component found: thread | Version: 1.82.0
-- Disabling warnings for targets: xinputcheck
-- opus found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- speexdsp: Variable sized arrays supported: FALSE
-- speexdsp: alloca available: FALSE
-- speexdsp: SSE available: TRUE
-- speexdsp: SSE2 available: TRUE
-- Disabling warnings for targets: speexdsp
-- Disabling warnings for targets: rnnoise
-- Qt5 component found: LinguistTools | Version: 5.15.10
-- Bundling Qt translations from "C:/Users/Shahbaz/vcpkg/installed/x64-windows-static-md/share/qt5/translations"
-- Found Python version  but required at least 3
CMake Error at 3rdparty/FindPythonInterpreter/FindPythonInterpreter.cmake:128 (message):
  Did NOT find Python interpreter
Call Stack (most recent call first):
  cmake/qt-utils.cmake:128 (find_python_interpreter)
  src/mumble/CMakeLists.txt:835 (bundle_qt_translations)


-- Configuring incomplete, errors occurred!
`

**Comment by Krzmbrzl** [comment]
You'll have to install Python 3 on your system

**Comment by shahbazaly** [comment]
I do have it installed and have it in system variable path aswell. How can I check in which path it usually looks for python?

**Comment by Krzmbrzl** [comment]
Try re-running cmake from scratch and pass `--log-level=VERBOSE`. This might shed some light on what the Python search module is doing...

**Comment by shahbazaly** [comment]
I solved the error however I have a new issue exactly as #6163 on windows 10 Pro

**Comment by Krzmbrzl** [comment]
Okay then let's close this issue and keep #6163 instead.

**Comment by theAkito** [comment]
> `git submodule update --init --recursive`
> 
> See also the main README in the build instructions: https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/README.md

I just want to point out, that this should be emphasized in more places. I've now shot myself in the knee twice, when I at first did not issue this command & on the second try, I issued it in the wrong situation, making it futile.

To prevent the spreading virus of headaches in the world, I am completing this with a heads up about what can happen, if you don't issue the command or if you do not do it the right way.

```
In file included from /root/mumble/build/src/murmur/mumble-server_autogen/EWIEGA46WW/../../../../../src/murmur/Server.h:16,
                 from /root/mumble/build/src/murmur/mumble-server_autogen/EWIEGA46WW/../../../../../src/murmur/DBus.h:1 ,
                 from /root/mumble/build/src/murmur/mumble-server_autogen/EWIEGA46WW/moc_DBus.cpp:10,
                 from /root/mumble/build/src/murmur/mumble-server_autogen/mocs_compilation.cpp:7:
/root/mumble/build/src/murmur/mumble-server_autogen/EWIEGA46WW/../../../../../src/murmur/AudioReceiverBuffer.h:17:10: fatal error: Tracy.hpp: No such file or directory
   17 | #include <Tracy.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/murmur/CMakeFiles/mumble-server.dir/build.make:83: src/murmur/CMakeFiles/mumble-server.dir/mumble-server_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:279: src/murmur/CMakeFiles/mumble-server.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

It wasn't immediately clear, that this is included via a submodule. It also wasn't clear, why this was needed, when its resulting feature was [explicitly excluded via a `cmake` option](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/cmake_options.md#tracy).

**Comment by Krzmbrzl** [comment]
Indeed.

I wanted to switch from using submodules to using cmake's FetchContent for a while now as the latter will automatically fetch the required deps for you when you want to build.
But so far, I have not actually gotten around to doing that...
