### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by Megamichi123** [mumble-voip/mumble#6164]
### The issue

hallo ich habe eine murmur server auf meinen raspberrypi 400 es hat 2 tage funktioniert aber jetzt geht es nicht mehr

hello i have a murmur server on my raspberrypi 400 it worked for 2 days but now it doesn't work anymore

### Mumble version

1.3.4-1

### Mumble component

Both

### OS

Linux

### Additional information

log:<X>2023-06-21 15:02:35.556 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:02:35.557 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:02:37.362 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:02:37.450 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:02:37.450 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:02:38.343 Performed initial PBKDF2 benchmark. Will use 4000 iterations as default
<W>2023-06-21 15:02:38.343 Generating new tables...
<W>2023-06-21 15:02:38.478 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:02:38.526 1 => Password for 'SuperUser' set to 'ZxTByx4iY7Jd'
<W>2023-06-21 15:02:38.594 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:02:38.607 1 => Stopped
<W>2023-06-21 15:13:20.520 Caught SIGHUP, will reopen /home/megamichi/murmur.log
<W>2023-06-21 15:13:20.520 Log rotated successfully
<C>2023-06-21 15:13:20.521 Caught SIGTERM, exiting
<W>2023-06-21 15:13:20.521 Killing running servers
<W>2023-06-21 15:13:20.521 Shutting down
<X>2023-06-21 15:14:15.778 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:14:15.778 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:14:17.606 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:14:17.694 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:14:17.694 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:14:17.807 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:14:17.828 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:14:17.841 1 => Stopped
<X>2023-06-21 15:24:46.322 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:24:46.323 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:24:48.132 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:24:48.219 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:24:48.220 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:24:48.335 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:24:48.354 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:24:48.366 1 => Stopped
<X>2023-06-21 15:25:14.248 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:25:14.249 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:25:16.071 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:25:16.158 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:25:16.158 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:25:16.270 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:25:16.289 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:25:16.302 1 => Stopped
<X>2023-06-21 15:28:16.051 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-21 15:28:16.052 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-21 15:28:17.859 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-21 15:28:17.945 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-21 15:28:17.946 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-21 15:28:18.059 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-21 15:28:18.077 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-21 15:28:18.093 1 => Stopped
<X>2023-06-22 07:14:18.145 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-22 07:14:18.146 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-22 07:14:19.951 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-22 07:14:20.038 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-22 07:14:20.038 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-22 07:14:20.153 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-22 07:14:20.174 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-22 07:14:20.187 1 => Stopped
<X>2023-06-25 15:41:23.774 SSL: OpenSSL version is 'OpenSSL 1.1.1n  15 Mar 2022'
<W>2023-06-25 15:41:23.774 Initializing settings from /home/megamichi/.murmurd/murmur.ini (basepath /home/megamichi/.murmurd)
<W>2023-06-25 15:41:25.575 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2023-06-25 15:41:25.662 ServerDB: Opened SQLite database /home/megamichi/murmur.sqlite
<W>2023-06-25 15:41:25.662 ServerDB: Using SQLite's default rollback journal.
<W>2023-06-25 15:41:25.773 Murmur 1.3.4 (1.3.4-1) running on X11: Raspbian GNU/Linux 11 (bullseye): Booting servers
<W>2023-06-25 15:41:25.793 1 => Server: TCP Listen on 0.0.0.0:64738 failed: The bound address is already in use
<W>2023-06-25 15:41:25.805 1 => Stopped

**Comment by Krzmbrzl** [comment]
Any chance you have another server instance running? Check via `pgrep -f murmur`

The error message you get is that the port the server tries to bind to, is already occupied. You should be able to use standard Linux CLI tools to find out what process is occupying the port. 
But as I wrote above: in all likeliness, it's another server instance.

**Comment by Megamichi123** [comment]
This is another murmur server but if it's already running why can't I connect

I have seen that udp6 and tcp6 are used. My router does not support ipv6 at all, how do I set it to ipv4

**Comment by Megamichi123** [comment]
I switched off my firewall but it doesn't work either. I update to 1.4

**Comment by Krzmbrzl** [comment]
> This is another murmur server but if it's already running why can't I connect

We'd have to look into its log to figure that out.
For now though, you should find the other process and kill it.
