### ISSUE TITLE
Mumble may need to be built with C++17

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#6165]
### Description

Arch Linux ships a recent version of protobuf (currently 23.4). If its dependency abseil is built with C++17 (which is the case), Mumble needs to be compiled with this version standard as well.

I assume you don't want to switch from C++14 to 17 yet but wanted to let you know about this. Maybe a version check for protobuf is reasonable? Or a hint in the documentation?

See also:
- Relevant [protobuf commit](https://github.com/protocolbuffers/protobuf/commit/13a1a3effea680489974566dfe6c685dc47dd7f0) 
-  [Build fix](https://gitlab.archlinux.org/archlinux/packaging/packages/mumble/-/commit/c3384d07a6e25a5d08c52d0e8422569a6858a1b0) for Arch Linux
- abseil [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/abseil-cpp/-/blob/1846afb3dd43f9a0dbbbda2c762cc36339b827fc/PKGBUILD#L29)

### Steps to reproduce

Compile Mumble on Arch Linux

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
We would very much like to use C++17, but we can't. 
If we switch to C++17, then our Ice interface yields tons of compile errors. Thus, that will have to be rewritten before we can make the switch. 

See also https://github.com/mumble-voip/mumble/pull/4493

**Comment by Krzmbrzl** [comment]
Using a version check doesn't seem appropriate per se though. As far as I understand the Protobuf commit message, it'll work fine with C++14 - only when abseil is built with C++17, does that requirement populate through. Thus, that version of Protobuf should be usable from a C++14 project as long as a C++14 abseil version is used :thinking:
