### ISSUE TITLE
SSL Version Mismatch

### ISSUE THREAD

**Issue by wfjsw** [mumble-voip/mumble#6166]
### The issue

One or two clients of my server have reported that they encounters `SSL Version Mismatch` error recently, while the server operates on TLS 1.3. One of them has been able to connect to the server previously. The server has no change since then.

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Additional information

Windows 10 22H2

The server is a grumble fork. Here is the TLS config of the server:
```
	server.tlscfg = &tls.Config{
		ClientAuth:               tls.RequestClientCert,
		PreferServerCipherSuites: true,
		CurvePreferences: []tls.CurveID{
			tls.CurveP256,
			tls.X25519, 
		},
		MinVersion: tls.VersionTLS12,
		CipherSuites: []uint16{
			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
		},
	}
```

Other users are able to connect to the server with the following connection detail (I'm on Win11 22H2):
![image](https://github.com/mumble-voip/mumble/assets/2220320/06d14718-37d9-44ae-a793-f522d7c727ff)

**Comment by Krzmbrzl** [comment]
Do the clients support TLS 1.3?

And does the same error appear with the main Mumble server as well?

**Comment by wfjsw** [comment]
I've instructed the client to enable TLS 1.3 through Internet Settings with no luck. Though the majority of users have no issue with the server even with the 1.2 client.

The client encountered the issue have no problem connecting to other servers.

**Comment by davidebeatrici** [comment]
Which TLS version is used when connected to working servers?

**Comment by wfjsw** [comment]
According to his screenshot it shows:
TLS 1.3
TLS_AES_256_GCM_SHA384

**Comment by davidebeatrici** [comment]
Just like when connecting to your server, basically?

**Comment by wfjsw** [comment]
Yes, it appears so.

**Comment by davidebeatrici** [comment]
I wonder if Grumble doesn't take the order into account or perhaps it's reversed...

**Comment by Krzmbrzl** [comment]
That's why I asked whether this issue also occurs with the main Mumble server

**Comment by wfjsw** [comment]
I'll try tweaking the settings and see what happens.

**Comment by wfjsw** [comment]
Removed the cipher preference altogether and no luck :(
