### ISSUE TITLE
Startup change?

### ISSUE THREAD

**Issue by Megamichi123** [mumble-voip/mumble#6167]
### The issue

Hello how can I adjust the startup command as ipv4 is used and the superuser password is set:

### Mumble version

1.3.4-1

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
I have no clue what you are asking. Could you try rephrasing your request? Also this feels like a continuation of you previous issue. If so, please stick to the old one and don't open new tickets for it.

**Comment by Megamichi123** [comment]
When I start my Raspberry Pi, murmur starts incorrectly, so I wanted to ask how I can adjust it

It uses ipv6 although it is not supported by me and the superuser password is set incorrectly

**Comment by Krzmbrzl** [comment]
What does "start incorrectly" mean? The IPv4/IPv6 issue?

> It uses ipv6 although it is not supported by me

How can you tell? And with "not supported by me" I assume you mean that your Raspberry Pi or rather your network doesn't support IPv6?
