### ISSUE TITLE
Test migration to 1.5.517 destroys Mumbel installation 

### ISSUE THREAD

**Issue by Gallimathias** [mumble-voip/mumble#6169]
### Description

Because of the other issue I opened, I wanted to test the latest version. I installed it but did not notice any change.

Then (because a friend suggested it) I closed Mumbel and started it as administrator. The application crashed and could no longer be started (a task was still running with 4 % CPU and 8 MB RAM).

Now Mumbel can no longer be started because I receive the error message Database: File Not found.

Even a downgrade to 1.4.287 did not solve the problem.

### Steps to reproduce

1. Upgrade to 1.5.517
2. Start Mumbel as Admin (mayby belongs to the Crash)

3. optional downgrade (deinstall, install 1.4.287)

4. Start Mumbel
5. Enjoy the Error Message 

### Mumble version

1.5.517 / 1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

Windows version: Windows 10, 22H2, 19045.3086

### Relevant log output

```shell
<W>2023-07-09 14:56:01.578 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2023-07-09 14:56:01.605 libopus 1.3.1-97-g6b6035ae from C:/Program Files/Mumble/client/opus.dll
<W>2023-07-09 14:56:01.648 CELT bitstream 8000000b from C:/Program Files/Mumble/client/celt0.0.7.0.dll
<W>2023-07-09 14:56:01.648 ASIO: No valid devices found, disabling
<W>2023-07-09 14:56:01.666 Theme: "Mumble"
<W>2023-07-09 14:56:01.666 Style: "Dark"
<W>2023-07-09 14:56:01.666 --> qss: ":themes/Mumble/Dark.qss"
<W>2023-07-09 14:56:01.666 Locale is "de_DE" (System: "de_DE")
<W>2023-07-09 14:56:02.231 Updating application palette
<F>2023-07-09 14:56:05.100 Database: File not found
<W>2023-07-09 14:56:14.770 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2023-07-09 14:56:14.779 libopus 1.3.1-97-g6b6035ae from C:/Program Files/Mumble/client/opus.dll
<W>2023-07-09 14:56:14.804 CELT bitstream 8000000b from C:/Program Files/Mumble/client/celt0.0.7.0.dll
<W>2023-07-09 14:56:14.804 ASIO: No valid devices found, disabling
<W>2023-07-09 14:56:14.821 Theme: "Mumble"
<W>2023-07-09 14:56:14.822 Style: "Dark"
<W>2023-07-09 14:56:14.822 --> qss: ":themes/Mumble/Dark.qss"
<W>2023-07-09 14:56:14.822 Locale is "de_DE" (System: "de_DE")
<W>2023-07-09 14:56:15.377 Updating application palette
<F>2023-07-09 14:56:16.660 Database: File not found
```

### Screenshots

![grafik](https://github.com/mumble-voip/mumble/assets/16351673/800354d6-32a6-4211-ae5e-9c434a377b54)

**Comment by Krzmbrzl** [comment]
First of all: a minor nitpick: it's `Mumble` and not `Mumbel`

In terms of your actual problem: Could you tell me what files the directory `%APPDATA%\Mumble\` contains?

**Comment by Gallimathias** [comment]
Sorry about the name, I didn't mean to. I'm trying to get used to it.

All Files in the folder are this (and a bunch of empty folder)

````
@{FullName=C:\Users\Maximilian Krüger\AppData\Roaming\Mumble\Console.txt}
@{FullName=C:\Users\Maximilian Krüger\AppData\Roaming\Mumble\Mumble\Console.txt}
@{FullName=C:\Users\Maximilian Krüger\AppData\Roaming\Mumble\Mumble\mumble.sqlite}
````

**Comment by Krzmbrzl** [comment]
> Sorry about the name, I didn't mean to. I'm trying to get used to it.

Don't worry - I just wanted to point it out :)

Okay, the database file is present there (the `mumble.sqlite` file). Try renaming that file and then try to start Mumble again.
Potentially, starting Mumble as admin has changed the access permissions of the DB.

**Comment by Gallimathias** [comment]
I changed the name now to `notworking.sqlite` but didn't change anything

**Comment by Gallimathias** [comment]
I delete now the hole Regestry Key from Mumble, this fix the issue. The client generates a new sqlite database

**Comment by Krzmbrzl** [comment]
Okay. Good to hear that it is working again :+1:
