### ISSUE TITLE
Locked channels should not be listenable

### ISSUE THREAD

**Issue by hamilton5** [mumble-voip/mumble#6173]
### Description

I can't join a channel, but I can listen to it

### Steps to reproduce

red locked icon, can't join channel, but I can right click and listen to channel

### Mumble version

1.5.

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by roughnecks** [comment]
Thanks for this.

We tested on my server with a server build from yesterday, 1.5.517-rc and also the dev mumble client on Windows, same version.

**Comment by Krzmbrzl** [comment]
Yes - Enter and Listening permissions are independent. You have to configure them separately. 

Iirc revoking Enter permission by default also deselects the Listen permission in the ACL editor, but ultimately these two are independent.

**Comment by Krzmbrzl** [comment]
Ah yes - upgrading will use the default, which is to allow listening.
