### ISSUE TITLE
Windows Asserts cache.isValid

### ISSUE THREAD

**Issue by jvbsl** [mumble-voip/mumble#6177]
### Description

Windows asserts in newest master builds at https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutputSpeech.cpp#L290
Introduced with:
https://github.com/mumble-voip/mumble/commit/bcbf86ecabf2ee5e39c6ff077907e577386e500c

### Steps to reproduce

1. Open mumble client
2. Connect to some server
3. Somebody else speaks
4. Crashes

### Mumble version

master

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

I don't have much of a clue what that code does, and why e.g. the index was changed to be one less then it was before. Don't get why that would make a difference on windows, as I do not have that same problem on Linux, but something seems to be different

~~But my best guess would be, because the cache is now cleared which it wasn't before, and a cleared cache isInvalid, so when we get to that position before the cache is again filled with data we assert~~
Edit: Should not happen, there are mutexes in place which should prevent exactly that...

**Comment by davidebeatrici** [comment]
@nJ3ahxac

**Comment by Hartmnt** [comment]
I am very much not into the audio processing code, so take what I say with a grain of salt. Looking over the code, I do not fully understand why [``cache.clear()`` ](https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutputSpeech.cpp#L325C20-L325C20) would invoke the Speex destroy callback.

It calls [``AudioOutputCache::clear``](https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutputCache.cpp#L72), which itself clears a buffer of the type ``std::vector< Mumble::Protocol::byte >``. How would this trigger the speex to remove the sample from the ``s_audioCaches`` store?
So if the sample is "cleared" but not removed from the ``s_audioCaches``, the next time the code path is hit, the ``assert`` would fail.

However, that does not explain why the assert is only hit on Windows. Maybe I am missing something important here though.

**Comment by jvbsl** [comment]
at the end of addFrameToBuffer:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutputSpeech.cpp#L216
calls invalidateAudioOutputCache from here
https://github.com/mumble-voip/speexdsp/blob/6e4634f44ae93df56105ff54c1e120f64e7a0dd4/libspeexdsp/jitter.c#L382

It happens at the second call of addFrameToBuffer, at the first call invalidateAudioOutputCache is not called and it works like it should.

invalidateAudioOutputCache wasn't called in the previous version, because the index of the first cache was 0 and it wasn't called for that, but I don't know why it would work with caches with index >= 1....

**Comment by Hartmnt** [comment]
> invalidateAudioOutputCache wasn't called in the previous version, because the index of the first cache was 0 and it wasn't called for that, but I don't know why it would work with caches with index >= 1....

What we see as ``index`` in the Mumble source code is ``data`` in Speex. The problem that the MR - which introduced this new bug - solved, is that Speex regulary checks for ``data == NULL``. That fails for us, as we previously stored indices with 0 (which evaluates to ``NULL`` of course) in the data field. The previous MR just added ``+1`` to the stored data which solves the ``data==NULL`` problem.



> at the end of addFrameToBuffer:
> https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutputSpeech.cpp#L216
> calls invalidateAudioOutputCache from here
> https://github.com/mumble-voip/speexdsp/blob/6e4634f44ae93df56105ff54c1e120f64e7a0dd4/libspeexdsp/jitter.c#L382

Right, ok. That explains that the destroy callback is called on some of the existing entries, when a new jitter entry is added. That does not explain to me why we have to call ``cache.clear()`` in our code though.

**Comment by Hartmnt** [comment]
Ah right, I understand that part now: ``jitter_buffer_get`` removes the entry from the Speex internal buffer, and we have to apply the EFFECT of the destroy callback to the object. We do not have to actually call the destroy callback.

**Comment by Hartmnt** [comment]
> It happens at the second call of addFrameToBuffer, at the first call invalidateAudioOutputCache is not called and it works like it should.

That could maybe suggest the following scenario:

1) For reasons yet unknown, the first audio data that is added to the jitter buffer on Windows is empty.
1) The first - but empty - audio data always got ``index = 0`` as would be expected.
1) The previous MR fixed the ``==NULL`` bug and introduced no other bugs directly
1) Fixing the ``==NULL`` bug unmasked the already existing problem of the empty audio data, as ``jitter_buffer_get`` contains also a check for [``data==NULL``](https://github.com/mumble-voip/speexdsp/blob/6e4634f44ae93df56105ff54c1e120f64e7a0dd4/libspeexdsp/jitter.c#L480). That means the jitter buffer entry with index 0 could never have been returned by ``jitter_buffer_get``
1) ``jitter_buffer_get`` now asserts if the first entry is valid, which it is not because it is empty. But not because it was already destroyed, but it was empty to begin with.

**Comment by jvbsl** [comment]
> What we see as index in the Mumble source code is data in Speex. The problem that the MR - which introduced this new bug - solved, is that Speex regulary checks for data == NULL. That fails for us, as we previously stored indices with 0 (which evaluates to NULL of course) in the data field. The previous MR just added +1 to the stored data which solves the data==NULL problem.

Yes, I got that part and it made sense and I could not see anything wrong with the code itself, I mean beforehand for index 0 it would never call the cleanup, as it was equivalent to a nullptr

> Ah right, I understand that part now: jitter_buffer_get removes the entry from the Speex internal buffer, and we have to apply the EFFECT of the destroy callback to the object. We do not have to actually call the destroy callback.

So we actually do not need to call cache.clear()?

Could it have something to do with the fact, that this line:
https://github.com/mumble-voip/speexdsp/blob/master/libspeexdsp/jitter.c#L606
should not only be called in the else branch, but in both branches? Because that is exactly what the upstream repository is doing:
https://github.com/xiph/speexdsp/blob/master/libspeexdsp/jitter.c#L607

Alright, I wrote the above part before your new message, you are too fast :P

I don't think your described scenario matches what I debugged, because to me it looked, like it was filled with 253 bytes of data, before it was added. But not too sure if I overlooked something/misunderstood something

**Comment by Hartmnt** [comment]
Right, so that suggests that 6e4634f44ae93df56105ff54c1e120f64e7a0dd4 tried to fix the same problem (memory leaks) as #6150 but failed to notice that the actual problem were the 0 indices and ``==NULL`` checks, correct?

In that case we would to simply revert 6e4634f44ae93df56105ff54c1e120f64e7a0dd4.

I am still failing to understand the Windows only situation, though...

**Comment by jvbsl** [comment]
Oh yeah that seems to be exactly it, didn't recognize what that commit did.

But little OT, what is actually the reason that we need our own repository? I do not see a lot of difference between the two repositories, a few things are newer in ixph, and we instead have alloca stuff:
https://github.com/mumble-voip/speexdsp/blob/master/configure.ac#L46
That would be the only reason I can see that we would need our own repo, but then again any reason that we would not just PR that upstream?

> I am still failing to understand the Windows only situation, though...
Don't ask me, I don't understand it either^^

**Comment by Krzmbrzl** [comment]
> I am still failing to understand the Windows only situation, though...

Asserts only fire in Debug builds so maybe that simply means that so far everyone has built the binaries in Release mode and thus didn't notice the issue. :thinking:

> what is actually the reason that we need our own repository?

I believe the only reason was that "fix" of mine.

**Comment by jvbsl** [comment]
> Asserts only fire in Debug builds so maybe that simply means that so far everyone has built the binaries in Release mode and thus didn't notice the issue. thinking

No, release build just hard crashes without any information :D

> I believe the only reason was that "fix" of mine.

Alright, then I'm gonna test the upstream version if it works, wouldn't be too bad to get rid of that extra fork, right?

**Comment by davidebeatrici** [comment]
Indeed.

**Comment by jvbsl** [comment]
Should I then change https://github.com/mumble-voip/mumble/pull/6179 to be WIP, and use the upstream fork, after I tested whether that works(at least on Linux and Windows)? Or should that just happen in a different PR?

**Comment by Krzmbrzl** [comment]
> No, release build just hard crashes without any information :D

This is then likely a segmentation fault, which is not guaranteed to happen (accessing invalid memory is undefined behavior).

> Should I then change #6179 to be WIP, and use the upstream fork, after I tested whether that works(at least on Linux and Windows)? Or should that just happen in a different PR?

Doing it in the same PR seems like the way to go.

**Comment by jvbsl** [comment]
> This is then likely a segmentation fault, which is not guaranteed to happen (accessing invalid memory is undefined behavior).

Yeah could be, but the debugger didn't tell me anything, but I'm not that good with VS debugging. Gdb would have told me directly where it happened etc. even in release builds. But I didn't investigate further, as it is fixed now anyway

> Doing it in the same PR seems like the way to go.

Done
