### ISSUE TITLE
Positional plugin issues

### ISSUE THREAD

**Issue by Foereaper** [mumble-voip/mumble#6178]
### The issue

Hi!

I'm currently writing a version of the WoW positional audio plugin for Wrath of the Lich King. I have fetched all the required offsets, compiled said plugin (using MSVC14 - 2015) out of tree as a dll, but when trying to load it in Mumble 1.4.287 I get the following error message:

Non-plugin found in plugin directory: "C:/Users/xxx/AppData/Roaming/Mumble/Plugins/wow3.dll

When trying to install the plugin through settings, I get this message:

Unable to load plugin "wow3.dll" - check the plugin interface!

Since none of the guides covered writing plugins for 1.4, am I correct to assume MSVC2015 is still to be used? Does it expect a newer compiler possibly?

This is a carbon copy of one of the other WoW plugins, so it uses the legacy interface. I assume this is still supported in 1.4, so I reckon I'm compiling the dll wrong.

Any help is appreciated!

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

**Comment by Foereaper** [comment]
Quick update, I use VS2022, but I downloaded the 2015 build tools and set the project toolset to 2015. Upon inspection, it seems MSVC version is still set to 1933 (2022) instead of 1900 as expected. Does anyone have any experience with this, or do I need to bite the bullet and try to get 2015 installed separately?

**Comment by davidebeatrici** [comment]
The legacy interface requires the C++ ABI to match, the new one has no such issue as its plugin API is in C.

By the way, official Mumble releases are built with the MSVC version that is provided on Azure Pipelines, more specifically: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Comment by Foereaper** [comment]
Thank you! So since it is built with 2022, I should also build this legacy plugin using the 2022 toolset? I'd ideally like to get this plugin to work with whatever the release version is built with, asking end users to compile their own version of the application is a bit too big of an ask.

I looked at the newer API, and porting this legacy plugin to the newer API seems like a much bigger task than potentially getting the legacy DLL working.

**Comment by Krzmbrzl** [comment]
> Thank you! So since it is built with 2022, I should also build this legacy plugin using the 2022 toolset?

Yes

However, it'd be when better to use the new plugin interface introduced with 1.4 as this Wilk be completely independent of the used compiler.
See https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/README.md for documentation of the new plugin framework.

**Comment by Foereaper** [comment]
As an update, I tried to compile using VS2022, and 1.4 would still not accept the plugin with the same error as mentioned above.

I bit the bullet and downloaded VS2015, compiled the exact same plugin code and it works perfectly with 1.3, so I suspect there's some weird VS version discrepancy that I can't figure out.

Could it be that 1.4 in release was originally compiled with 2019 or something? The compile logs are unfortunately gone from the action, so I can't really double check.

I might look into porting the code to the new API at some point, but for now it works with 1.3.

**Comment by Krzmbrzl** [comment]
> Could it be that 1.4 in release was originally compiled with 2019 or something?

I just checked on our build server and yes, it was indeed built with VS2019
