### ISSUE TITLE
PTT not working on MacOS Ventura (M1) with accessability and input monitoring on

### ISSUE THREAD

**Issue by xuwhite** [mumble-voip/mumble#6182]
### Description

I cant set a push-to-talk button on mac os Ventura M1 
accessability and input monitoring set in settings

### Steps to reproduce

Go to "Prefferences"
Click on "Shortcuts"
Add Shortcut Push-to-talk
Press on "No button assigned"
Click on "Add" nothing happens

### Mumble version

1.4.287

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

### Additional information

My Mac has an M1 chip

**Comment by Krzmbrzl** [comment]
Did you have Mumble installed previously or is this a fresh installation on this device? Aka: have the extra permissions been granted for the first time or have they been set for an older Mumble installation before?

In the latter case, please try removing the permissions and then re-granting them to Mumble.

**Comment by xuwhite** [comment]
That helped thank you very much

**Comment by Krzmbrzl** [comment]
I would be very much interested as to why this happens all the time :thinking: 
But anyway, great to hear it is working again!

**Comment by floyd-fuh** [comment]
As @Krzmbrzl is still wondering why this always happens and people are struggling, I would like to write a little bit a longer explanation:

* AFAIK, there wasn't a separate "Input Monitoring" section (next to "Accessiblity" and "Microphone) that says "Allow the applications below to monitor input from keyboard even while using other applications" permission before MacOS Ventura
* IIRC, I was used to a dialogue saying "type your shortcut now", which is not coming up anymore in 1.4.287 (it changed from 1.3 to 1.4). Very counter-intuitive, the "Add" button has to be pressed but nothing happens. It's *normal* that nothing happens, that's how it works, you have to just press your shortcut after hitting the "Add" button.
* MacOS settings are very confusing, even after "uninstalling" Mumble (throwing it in the bin), the settings might still show that Mumble is allowed to have the permissions.

Here's a short guide on how to get Mumble (tested with 1.4.287) setup properly:

* Close the "System Settings" app (Right click - Quit)
* Uninstall Mumble by draggin it from /Applications to the bin
* Execute the following commands to clear permissions for Mumble:
```tccutil reset Accessibility mumble-client
tccutil reset Microphone mumble-client
```
* Open "System Settings - Privacy & Security" and make sure Mumble is not in "Microphone", "Accessibility" or "Input Monitoring" anymore. If it's still in there reboot or something.
* Close the "System Settings" app (Right click - Quit)
* Install newest Mumble
* Open Mumble. It should request at least Microphone permission.
* Close Mumble app (Right click - Quit)
* Open "System Settings - Privacy & Security" and make sure Mumble is allowed (toggle to the right) in three categories: Microphone", "Accessibility" or "Input Monitoring". If it is not, add it manually.
* Open Mumble, go through the audio wizard until you get to Push-To-Talk (PTT). Click the "No buttons assigned" or whatever it says. 
* Click Add - beware, nothing happens!
* Press your keyboard shortcut. It should now show in the visible window.
* Click "OK" and finish the wizard.

It's all just very confusing coming from pre-Ventura and Mumble 1.33.

Btw. this was on a x64 Intel Mac, but it probably works with M1, M2 too
