### ISSUE TITLE
Linux murmur

### ISSUE THREAD

**Issue by A1e-3** [mumble-voip/mumble#6185]
### Description

First of all, I really like the mumble software, and thank the author for developing the software that works well. A few questions would like to ask: What is the difference between 1.murmur 1.3.4 for Linux and murmur 1.5.517 for win? Is murmur 1.3.4 recommended for building services? 2. Are you considering updating APT's mumble-server this year? Or provide the murmur 1.5.x for Linux file download address.

### Mumble component

Server

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
The Debian (apt) package is not maintained by us. It has its own maintainer who so far hasn't found the necessary time to update the package.

The difference between 1.3 and 1.5 is that the latter is newer and thud has new features and fixes that 1.3 doesn't have. It goes without saying that we always recommend the most recent version.

If you are interested in the exact differences, I recommend reading the changelogs on our website (mumble.info).

We currently don't have any standalone executables for Linux that could be downloaded, so for the time being your only option would be to compile Mumble yourself.
