### ISSUE TITLE
Is Mumble Server out of updates for Linux or Ubuntu anymore?

### ISSUE THREAD

**Issue by rock2rap** [mumble-voip/mumble#6188]
### The issue

I'm using OrangePi (arm64) version 1.3.1 for about 5 years till now, today when I use update command it doesn't update to version 1.4 or 1.5 whatsoever, or anyone have a better way to update please suggest.

### Mumble version

1.4.1

### Mumble component

Server

### OS

Linux

### Additional information

![image](https://github.com/mumble-voip/mumble/assets/13579884/d086aa46-25d8-440b-b994-2be442688a61)

**Comment by Krzmbrzl** [comment]
You can compile the server yourself and/or poke the maintainer of the Debian package to finally update to the latest version.

Alternatively, we have an official Docker image: https://github.com/mumble-voip/mumble-docker
