### ISSUE TITLE
PPA on Pop-OS (Jammy) doesnt include a Release-File

### ISSUE THREAD

**Issue by infraunited** [mumble-voip/mumble#6190]
### Here's what my Terminal says:
Ign:3 https://ppa.launchpadcontent.net/mumble/release/ubuntu jammy InRelease
OK:4 http://apt.pop-os.org/proprietary jammy InRelease          
Fehl:5 https://ppa.launchpadcontent.net/mumble/release/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
OK:6 http://apt.pop-os.org/release jammy InRelease
OK:7 http://apt.pop-os.org/ubuntu jammy InRelease
OK:8 http://apt.pop-os.org/ubuntu jammy-security InRelease
OK:9 http://apt.pop-os.org/ubuntu jammy-updates InRelease
OK:10 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Paketlisten werden gelesen… Fertig
E: Das Depot »https://ppa.launchpadcontent.net/mumble/release/ubuntu jammy Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

### Translated with deepl:
Ign:3 https://ppa.launchpadcontent.net/mumble/release/ubuntu jammy InRelease
OK:4 http://apt.pop-os.org/proprietary jammy InRelease          
Ign:5 https://ppa.launchpadcontent.net/mumble/release/ubuntu jammy Release
  404 Not Found [IP: 185.125.190.52 443]
OK:6 http://apt.pop-os.org/release jammy InRelease
OK:7 http://apt.pop-os.org/ubuntu jammy InRelease
OK:8 http://apt.pop-os.org/ubuntu jammy-security InRelease
OK:9 http://apt.pop-os.org/ubuntu jammy-updates InRelease
OK:10 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Package lists are read... Done
E: The "https://ppa.launchpadcontent.net/mumble/release/ubuntu jammy Release" depot does not contain a release file.
N: Updating from such a depot cannot be done in a safe way, so it is disabled by default.
N: For more details about creating package repositories and their user configuration, see the apt-secure(8) manual page

Anyone knows what to do or if this is a bug?

### Mumble version

none yet

### Mumble component

I don't know

### OS

Linux

**Comment by Krzmbrzl** [comment]
Yes - we currently don't have a working PPA. See https://github.com/mumble-voip/mumble-ubuntu-ppa/issues/16
