### ISSUE TITLE
Old icon used in start menu when pinned

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#6196]
### Description

Mumble uses the old icon in the start menu on Windows 11 when pinned.

### Steps to reproduce

1. Open the start menu and search for Mumble
2. Right-click and pin to Start
3. The old icon is used

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

> Apps should have, at the bare minimum: 16x16, 24x24, 32x32, 48x48, and 256x256. This covers the most common icon sizes, and by providing a 256px icon, ensures Windows should only ever scale your icon down, never up.

https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction#icon-scaling

### Screenshots

Expected result

![01](https://github.com/mumble-voip/mumble/assets/56807288/449807ec-7822-403b-be28-ac1a553fd594)

Actual result

![02](https://github.com/mumble-voip/mumble/assets/56807288/1e0c5950-e94d-4c34-85b2-e2b4f027a21c)

**Comment by Krzmbrzl** [comment]
I think this might actually be semi-intentional. If the icon is large enough, I think we use the "old" icon and only use the "new" one when using smaller icons :thinking: 
@davidebeatrici do you know anything about that?

**Comment by davidebeatrici** [comment]
I'm pretty sure that's the case.

However, see #3058.

**Comment by Krzmbrzl** [comment]
Okay so this is working as intended, it seems :+1:
