### ISSUE TITLE
Linux Mumble refuses to let ALSA-using software touch it's precious input/output hardware

### ISSUE THREAD

**Issue by Phazeus** [mumble-voip/mumble#6197]
### Description

When using ALSA (PulseAudio is disabled), if Mumble is running, then, for example, in the wine application, the audio playback device becomes unavailable.
I use default device.

### Steps to reproduce

1. Disable PulseAudio and use ALSA only.
2. Start Mumble.
3. Start winecfg and look in "Audio" tab. There no audio device until Mumble close.

### Mumble version

1.3.4

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

(03:06:56 25.10.2021)(alsa dbus opus oss portaudio pulseaudio rnnoise speech -debug -g15 -jack -pch -zeroconf ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")

### Screenshots

![mumble](https://github.com/mumble-voip/mumble/assets/14029387/7cfd3f72-3481-4120-ba16-eecf181a3139)
![wine_with_mumble](https://github.com/mumble-voip/mumble/assets/14029387/f27caf4a-e403-4053-b205-4f078278ce02)
![wine_without_mumble](https://github.com/mumble-voip/mumble/assets/14029387/26900565-1a3b-4fb9-9df3-e0b946b4e530)

**Comment by Phazeus** [comment]
> Is this behavior still the same with newer Mumble versions?

Yes. Just compiled the latest stable version (mumble-1.4.287) and the problem still there.

**Comment by Krzmbrzl** [comment]
Iirc there should be an "exclusive" checkbox in the audio settings (might be in input and output). Have you tried unchecking that?

**Comment by Phazeus** [comment]
> Iirc there should be an "exclusive" checkbox in the audio settings (might be in input and output). Have you tried unchecking that?

This item is inactive and not checked.

**Comment by Phazeus** [comment]
Hey, don't close it! I gave all information. What wrong?

**Comment by Krzmbrzl** [comment]
If you check the state of this issue again, you will find that I have already deleted the bot's message and changed the labelling of this issue.

**Comment by vimpostor** [comment]
Using the normal hardware output device with Alsa does not support multiple applications using it at the same time. This is not a limitation of Mumble, but a limitation of Alsa.
You [can setup dmix in Alsa to support multiple applications at the same time](https://unix.stackexchange.com/a/355663), but then you need to choose dmix as the output in Mumble (or setup dmix to be the default Alsa audio card).

These days on Linux it is not recommended to use Alsa though, it will make lots of stuff (like this) more complicated. If you don't like Pulseaudio, you can use Pipewire instead.
