### ISSUE TITLE
Ice interface documentation

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6203]
### The issue

I am working with ice. I need to know which functions are available to the Meta object. Can anyone provide a link for the documentation?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
We only have the in-source documentation at https://github.com/mumble-voip/mumble/blob/master/src/murmur/MumbleServer.ice
