### ISSUE TITLE
Mumble server runs on Android if xcfe is installed on Termux!

### ISSUE THREAD

**Issue by lexterror** [mumble-voip/mumble#6207]
### The issue

Hi, 

Im trying to run mumble server on android without xcfe environment but it wont run. Am I missing something. It runs perfectly with xcfe on Android with termux.

Thank you!

### Mumble version

1.5

### Mumble component

Server

### OS

Other

**Comment by lexterror** [comment]
Any possibility of providing a version 1.4 of mumble-server for armv7 and armv8. I think there is issues with version 1.5 and openssl/qt5

**Comment by Krzmbrzl** [comment]
Why would you run the _server_ on Android? This is not something that we can provide support for. I also have never heard of anyone who has done something like that :thinking:

> Any possibility of providing a version 1.4 of mumble-server for armv7 and armv8.

No. For arm you'll currently have to compile Mumble yourself.

**Comment by lexterror** [comment]
Well, the steps I followed are:

Adding this line on termux:

pkg install x11-repo

the binaries are already at:

https://packages-cf.termux.dev/apt/termux-x11/pool/main/m/mumble-server/

From here you can directly do:

apt-get install mumble-server

And it installs fine, but does not run most likely because of a config or dependency problem.

However, if you install xfce environment first and then install mumble server it runs perfectly.

The sad part is that it does not require a powerful phone depending on how many users you allow. Also does not require root. It runs without any problems.

**Comment by lexterror** [comment]
I just realized you can just install xfce environment and mumble server will run directly from termux without even starting xfce environment.

There are several github repo with xfce for termux installations that are hassle free. One liners!

example:

https://github.com/techpanther22/Termux-Desktop

After termux, xfce, mumble-server installation simply run:

murmurd -supw *password*

and then simply edit the following file for customization:

nano /data/data/com.termux/files/usr/etc/mumble/mumble-server.ini

to start server run:

murmurd

**Comment by lexterror** [comment]
@Krzmbrzl if you see with the links/resources I provided a possibility of maintaining a termux only mumble-server please let me know. I think many would want to use it. There are many benefits for people that may not want to buy/setup a computer. For those who only like using phones. Thank you!

**Comment by Krzmbrzl** [comment]
I don't quite understand what you are getting at with your last comment. I don't see hosting a Mumble server on phones as something that warrants special considerations on the development front. If it works nonetheless that's neat, but I kinda doubt that this will represent a common usage scenario :eyes: 
That's not to say that we would reject PRs targeting at improving the usability in such scenarios - just that the main development efforts will likely not go into this direction.

**Comment by romanovj** [comment]
> I just realized you can just install xfce environment and mumble server will run directly from termux without even starting xfce environment.
> 
> There are several github repo with xfce for termux installations that are hassle free. One liners!
> 
> example:
> 
> https://github.com/techpanther22/Termux-Desktop
> 
> After termux, xfce, mumble-server installation simply run:
> 
> murmurd -supw _password_
> 
> and then simply edit the following file for customization:
> 
> nano /data/data/com.termux/files/usr/etc/mumble/mumble-server.ini
> 
> to start server run:
> 
> murmurd

you don't need GE

**Comment by lexterror** [comment]
Im just saying that a more simple installation would be great for those who want to communicate with their phones only. It takes 10minutes to install termux xfce and mumble server if you're familiar with the installation process. Also takes up about 1gb with xfce depending on the packages. It would be great for a quicker and less space consuming process. Im not as familiar with mumble-server packages/software as you are. So, Im just saying that a more "standalone" installation would be better/easier. You are the expert, and I have no doubt that if such an option was possible it would make it even more appealing/usable to people with less computer/tech knowledge.

**Comment by lexterror** [comment]
@romanovj whats GE?

**Comment by romanovj** [comment]
@lexterror Graphical Environment

**Comment by lexterror** [comment]
@romanovj I tried without xfce but some config/dependencies were preventing mumble-server from running. I agree that it can run without xfce/GE

**Comment by farooqkz** [comment]
I run mumble server on my ARM SBCs. I install murmur from Debian repos and it works fine. And also no need for XFCE or any other graphical environment.

**Comment by lexterror** [comment]
@farooqkz what deb packages are required to run mumble server without GE?
