### ISSUE TITLE
Hi, I have been getting an error LibSndFile_Dir and SndFile_Dir are not found. 

### ISSUE THREAD

**Issue by Ajith-Chandran-K** [mumble-voip/mumble#6208]
### The issue

I use cmake-gui and try to build mumble. It is throwing this error. Windows 10; x64. I used vcpkg to install libsndfile and I have also tried manually refering the libraries. Am I doing something wrong here? Thanks

CMake Error at cmake/pkg-utils.cmake:124 (message):
  sndfile not found
Call Stack (most recent call first):
  src/mumble/CMakeLists.txt:513 (find_pkg)

### Mumble version

The Master Branch

### Mumble component

Client

### OS

Windows

**Comment by davidebeatrici** [comment]
Are you using a matching triplet for the package?

**Comment by Ajith-Chandran-K** [comment]
@davidebeatrici Hi, I tried matching the package but it said there is no x64 for libsndfile. I am kinda really new to this. vcpkg install libsndfile add --triples x64 is correct right?

**Comment by Krzmbrzl** [comment]
You need the `x64-windows-static-md` triplet

**Comment by Ajith-Chandran-K** [comment]
@Krzmbrzl hi I downloaded that and I made 
LibSndFile_DIR C:\Users\myuser\Desktop\VCPKG\vcpkg\packages\libsndfile_x64-windows-static-md as this but when i hit configure it removes the directory and tells me sndfile not found. Is there anything else I am doing wrong?

**Comment by Krzmbrzl** [comment]
You shouldn't be downloading anything manually. Please follow the instructions as laid out in this repository (see the main README)

**Comment by Ajith-Chandran-K** [comment]
@Krzmbrzl hi I followed the ps1 script and installed , it was still throwing an error on the MDNSresponder actually.error: building mdnsresponder:x64-windows-static-md failed with: BUILD_FAILED
Elapsed time to handle mdnsresponder:x64-windows-static-md: 13 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+mdnsresponder
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[mdnsresponder]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Ftheotech%2FDesktop%2FVCPKG%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
    
    I am a bit stuck here 
    
    thank you :)

**Comment by davidebeatrici** [comment]
The console output should also tell you where to find the build logs, very important for figuring out what the actual failure is.

**Comment by Ajith-Chandran-K** [comment]
@davidebeatrici thanks alot I think all the dependencies are found now. I am having one final error that says 
CMake Error at cmake/pkg-utils.cmake:87 (message):
  Ice component not found: Ice
Call Stack (most recent call first):
  src/murmur/CMakeLists.txt:200 (find_pkg)


-- Configuring incomplete, errors occurred!

and I read through the documentation and tried my best to understand the part. I installed zero-ice as well but is there something i am missing?

**Comment by davidebeatrici** [comment]
We use our own port file, that is provided in this repository.

**Comment by Ajith-Chandran-K** [comment]
@davidebeatrici i tried that but the hyper link that shows the package says no link found, so what zeroc-ice mumble directory am i supposed to copy? thank you :)

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/tree/master/helpers/vcpkg/ports/zeroc-ice-mumble

**Comment by Ajith-Chandran-K** [comment]
@davidebeatrici got it thanks alot. I think we can close the issue. Thanks alot for the help <3

**Comment by davidebeatrici** [comment]
No problem.
