### ISSUE TITLE
Make more functions available in the list of global shortcuts

### ISSUE THREAD

**Issue by Globostofo** [mumble-voip/mumble#6229]
### Context

I've noticed that some basic functions could be made available in the list of global shortcuts.

![image](https://github.com/mumble-voip/mumble/assets/71722881/c8882cb0-81b2-4dca-8f54-c34fff6cdb7a)

I'd like to know if you're interested if I work on implementing these functions.

### Description

I would like to add the functions available in the client top menu (e.g. `Server>Connect`, `Server>Disconnect`, `Server>Information`, `Self>Recording`, `Configure>Settings`...)

![image](https://github.com/mumble-voip/mumble/assets/71722881/6127417b-4bfa-426c-a2c9-d97bc086e32e) ![image](https://github.com/mumble-voip/mumble/assets/71722881/d119e5c3-c552-4a49-ad3f-2c06b0af48e1) ![image](https://github.com/mumble-voip/mumble/assets/71722881/58ba7345-3b0e-4fd8-baef-8f7d78ce880e)

### Mumble component

Client

### OS-specific?

No

### Additional information

I'd like to have the opinion of the maintainers before I start coding
Thanks in advance :^)

**Comment by Krzmbrzl** [comment]
> I'd like to know if you're interested if I work on implementing these functions.

Sure! Having more options is always good :)

If you're feeling like it, there are also a couple more open issues about shortcut actions that would be nice to have. E.g. https://github.com/mumble-voip/mumble/issues/6133
