### ISSUE TITLE
Using the mysql backend, murmur exits with "Failed to get character encoding"

### ISSUE THREAD

**Issue by TheZeldakatze** [mumble-voip/mumble#6232]
### Description

I tried setting up the mysql backend of murmur because I'd like to use it on a potentially bigger server, but after changing the .ini file and restarting the server, the server exits, only showing `Failed to get character encoding`

I'm using Debian 12.1 with mariadb 10.11.4 and murmur 1.3.4-4
I also tried a custom build of murmur 1.5.517, the error is the same

### Steps to reproduce

Create a user and database

1. Change the config file to use QMYSQL, comment out the `database=` line:
```
dbDriver=QMYSQL
dbUsername=mumble
dbPassword=PASSWORD
dbHost=localhost
dbPort=3306
dbPrefix=murmur_
dbOpts="UNIX_SOCKET=/var/run/mysqld/mysqld.sock"
```

2. Restart the server with `service mumble-server restart`
or manually run `murmurd`

### Mumble version

1.3.4-4 / 1.5.517

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Relevant log output

```shell
mumble-server[7181]: Failed to get character encoding:
```

**Comment by Hartmnt** [comment]
I think it is failing in this line: https://github.com/mumble-voip/mumble/blob/master/src/murmur/ServerDB.cpp#L251
But, I find it strange that no additional text is printed after the ``:`` :thinking:

**Comment by TheZeldakatze** [comment]
I somehow managed to mess up the database name (don't know how I just managed to do that) and set `database=`, setting `database=mumble` makes it work, sorry for messing that up and wasting time

**Comment by Hartmnt** [comment]
> I somehow managed to mess up the database name (don't know how I just managed to do that) and set `database=`, setting `database=mumble` makes it work, sorry for messing that up and wasting time

Alright, thanks for coming back to tell us. If there is still something wrong with the encoding here, feel free to reopen.
