### ISSUE TITLE
Bluetooth issues

### ISSUE THREAD

**Issue by CobraClarkB** [mumble-voip/mumble#6233]
### Description

Mumble on Android using bluetooth does not work with Mic from Phones paired device. Receive PTT Audio come to the Bluetooth headset but when you key ptt the mic stay using the device. Not good this is a bug i discovered. Most don't realize it because they hold phone near their mouth when keying ptt button to speak. 

### Steps to reproduce

Pair your bluetooh device with your android Phone
Launch mumble PTT
Hold phone far away and key PTT and talk 
You will notice that the Android MIC is not coming from bluetooth mic.
AUDIO PTT follows the Devices default mic. 

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
This repository does not deal with the Android app. In fact, there is no official Mumble app for Android (and the one for iOS is ancient and unmaintained).
You are probably using Mumla, in which case you should open an issue at https://gitlab.com/quite/mumla
