### ISSUE TITLE
Time of transmission on screen and TOT preference

### ISSUE THREAD

**Issue by Sthrenor** [mumble-voip/mumble#6242]
### Context

Ham Radio opertation

### Description

Hi,
we use this app for clients of a network of radio links. We are Ham radios amateurs and we need to know how long is lasting our transmission on screen. Would be nice to have a Time of Transmission preference that can cut transmissions passed that time as well.
Thanks a lot in advance.

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
Wouldn't it be enough to simply release the PTT key every so often?
And a timer such as this seems like a perfect candiate for a plugin :thinking:

**Comment by Sthrenor** [comment]
Releasing the PTT manually is enough, but I will explain the need for the TOT and timer. When you have multiple systems connected, as FRN, Zello, TeamSpeak, Mumla, radio links, the main system (FRN) cut your comunication with a TOT of 3 minutes. What happens is that you continue talking using Mumla and only people on Mumla listen to you. That's why I request this feature.
