### ISSUE TITLE
wiki.mumble.info is down?

### ISSUE THREAD

**Issue by NagaseYami** [mumble-voip/mumble#6244]
### Description

Can't access to any wiki page for now.

### Steps to reproduce

https://wiki.mumble.info/

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

### Screenshots

![image](https://github.com/mumble-voip/mumble/assets/23649435/d44d6bfb-055e-40b3-b722-756c0115dc2e)

**Comment by Krzmbrzl** [comment]
@davidebeatrici

**Comment by davidebeatrici** [comment]
MySQL/MariaDB crashed, as usual. Restarted.

**Comment by WROIATE** [comment]
It seems crash again
