### ISSUE TITLE
References Mumble-compatible Bluetooth PTT microphone

### ISSUE THREAD

**Issue by f4gqk** [mumble-voip/mumble#6253]
### The issue

Hello, 

I am looking for a bluetooth PTT microphone reference(s) that would work properly with Mumble Android.

Thanks

Sebastien 

### Mumble version

3.6.3

### Mumble component

Client

### OS

Linux, Other

**Comment by Krzmbrzl** [comment]
The android Mumble app is not maintained by us and is therefore unrelated to this repository. Please contact the actual maintainer.
