### ISSUE TITLE
In Firefox, clicking mumble:// links do not open the Mumble application

### ISSUE THREAD

**Issue by GenericUser1000** [mumble-voip/mumble#6257]
### The issue

I clicked on mumble:// link in Firefox browser that is supposed to open Mumble with server information. It is supposed to open the Mumble application but instead it does nothing

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
Do these links work outside of Firefox?

**Comment by GenericUser1000** [comment]
Hi, issue is resolved by installing latest version of Mumble.

**Comment by Krzmbrzl** [comment]
Great! :+1:
