### ISSUE TITLE
No microphone input with ASUS STRIX RAID DLX (7.1) selected as output

### ISSUE THREAD

**Issue by mypantsfelldown** [mumble-voip/mumble#6262]
### The issue

My friend has the aforementioned soundcard selected as their output, but this disables all input signals (despite their microphone being listed and selectable). However, with this output device selected they can still hear others speaking.

If they select a different output device, Mumble receives an input signal again.

### Mumble version

1.5.517

### Mumble component

Client

### OS

Windows

### Additional information

Also tested on 1.4.287, exact same issue.

**Comment by Krzmbrzl** [comment]
Perhaps there is some kind of exclusivity setting on the OS/driver level? Is the audio card also selectable as input? In that case, it might be necessary to use it for audio input and output.

**Comment by mypantsfelldown** [comment]
We are still investigating this issue. We're going to test whether the microphone works via the input on the soundcard as soon as possible.

**Comment by mypantsfelldown** [comment]
Hello, so we've tried lining into the soundcard but Mumble still isn't receiving any signal (there is signal in Windows). Any other ideas?

**Comment by Krzmbrzl** [comment]
Hm, unfortunately I don't have any further ideas... I take it that you have already tried other programs to see wither the problem is reproducible there as well?
