### ISSUE TITLE
Linux (debian) package update

### ISSUE THREAD

**Issue by mstjr** [mumble-voip/mumble#6276]
### Description

Still on the 1.3.4-4 version on debian, could be great if you can update all that thing up to the 1.4.X <3

### Steps to reproduce

Just install on linux
apt-get update
apt-get upgrade -y
apt-get install mumble-server

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
The package is not maintained by us so there is not much we can do about it. You'll have to contact the Debian package maintainer about it.
