### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [mumble-voip/mumble#6278]
### Description

Dear @mumble-voip team,

It is possible to create a new stable build?

Latest is: 1.4.287 (2022-09-14), One year, three months:
- https://github.com/mumble-voip/mumble/releases/tag/v1.4.287

Unstable is: 1.5.517 (2023-01-21), soon one year:
- https://github.com/mumble-voip/mumble/releases/tag/v1.5.517

Thanks in advance.

### Steps to reproduce

Please read before.

### Mumble version

*

### Mumble component

Both

### OS

Other

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
It's WIP since like forever, but we currently lack the time to complete it. Release will come as soon as one of us has the necessary time 👀
