### ISSUE TITLE
Official mumble port at least for android 

### ISSUE THREAD

**Issue by DGMurdockIII** [mumble-voip/mumble#6281]
### Context

Official mumble port for android 

### Description

Yes I now this could be alot of work but there allready is a mobile port here https://gitlab.com/quite/mumla but it be nice if there a official one or if you guys just made a framework that the community can help maintain vlc has made I also know there are not too many people working on mumble at the moment but this could be a good thing to work towards or even maybe apply for Google summer of code and get this a goal maybe you guys could talk to the mumla dev to maybe work out something 

### Mumble component

Both

### OS-specific?

Yes

### Additional information

I have been using mumla     https://mumla-app.gitlab.io/ and before that plumble https://github.com/acomminos/Plumble witch is no longer maintained

**Comment by Krzmbrzl** [comment]
We don't have the resources to properly maintain the desktop application. Therefore, starting mobile development seems like a bad idea.

There is the libmumble project that could eventually be used as the basis for a future app (framework). But for the near future this will likely not happen.
