### ISSUE TITLE
Allow specifying installation folder

### ISSUE THREAD

**Issue by saelic** [mumble-voip/mumble#6301]
### Context

Program installation.

### Description

Please allow user to have the ability to select installation folder. Not everyone wants or have the ability to install to Program Files, there are circumstances where installation to different folder is desired.

### Mumble component

Both

### OS-specific?

Yes

### Additional information

This is probably Windows specific.

**Comment by Krzmbrzl** [comment]
Mumble do.esn't work properly when installed somewhere diese due to Windows restrictions. That's why the directory is fix.

**Comment by davidebeatrici** [comment]
More specifically, global shortcuts work in privileged applications only if our executables is in the Program Files folder.
