### ISSUE TITLE
Disabling notification method for message type will uncheck it for all message types, if "All messages" was enabled

### ISSUE THREAD

**Issue by Hartmnt** [mumble-voip/mumble#6302]
### Description

In the ``Messages`` settings, if you try to disable a single notification method e.g. ``Console`` for a single message type e.g. ``Critical``, all check-boxes will disappear when ``All messages`` had ``Console`` checked to begin with...

The expected and user-friendly behavior would be to disable the clicked check-box and also the ``All messages`` check-box, but not all the other check-boxes.

### Steps to reproduce

1) Open the ``Messages`` settings
2) Find or create a column where ``All messages`` is checked (and therefore all the check-boxes in that column)
3) Uncheck a single check-box for a single message type e.g. ``Critical``
4) Observer that all check-boxes in that column are now unchecked

### Mumble version

1.5.x (possibly more)

### Mumble component

Client

### OS

Probably all

### Reproducible?

Yes

### Additional information

My assumption is that the automatic unchecking of the ``All messages`` check-box is treated as if the user actually clicked on the ``All messages`` check-box and therefore triggering that event, too.

**Comment by shreya-shenoy** [comment]
Hello! This is my first time contributing to an open-source project. Can I try working on this task?

**Comment by Hartmnt** [comment]
> Hello! This is my first time contributing to an open-source project. Can I try working on this task?

Hi! Yes, sure. Feel free to ask for advice at any point :)

**Comment by roshan-orlando** [comment]
Hi! Could I contribute?

**Comment by Krzmbrzl** [comment]
You can, but if you look two posts upwards you'll find that this specific issue is already taken. Contributions elsewhere would be appreciated though :)

**Comment by shreya-shenoy** [comment]
Hi! Unfortunately, I cannot work on this issue. Please pass it on to the next person!
