### ISSUE TITLE
Multi entradas de áudio

### ISSUE THREAD

**Issue by MauroBonan** [mumble-voip/mumble#6317]
### Context

Comunicação TalkBack

### Description

Olá pessoal,  estou maravilhado com Mumble! 
Bom, teria como  fazer o sistema de áudio ler mais que uma entrada? 
Tipo... eu tenho uma placa de áudio com entradas para 3 microfones, tem possibilidade de o Munble reconhecer as 3 entradas,  ou reconhecer mais de uma placa de áudio? 

### Mumble component

Client

### OS-specific?

Yes

### Additional information

Um leitor de URL, como  um player de áudio streaming, para tocar áudio de um fonte qualquer via streaming com agendamento de horário para início e fim ( play e stop.

**Comment by Krzmbrzl** [comment]
English only, please.

**Comment by MauroBonan** [comment]
> Apenas Inglês por favor.

TalkBack Communication

 Description

 Hi everyone, I'm in awe of Mumble!
 Well, would there be a way to make the audio system read more than one input?
 Like... I have an audio card with inputs for 3 microphones, is it possible for Munble to register all 3 inputs, or consider more than one audio card?

 A URL reader, like a streaming audio player, to play audio from any source via streaming with start and stop scheduling (play and stop.

**Comment by Krzmbrzl** [comment]
#4112
