### ISSUE TITLE
translation error, Dutch

### ISSUE THREAD

**Issue by oehTie** [mumble-voip/mumble#6323]
### Description

translation is simply wrong. when i enter a channel, i get the notification: "Je neep <channelname> binnen." This is simply not Dutch. It should be "Je ging <channelname> binnen."

### Steps to reproduce

set mumble to dutch as language, change channel. The notification pops up in the message screen on the left.

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

i can help translating Dutch if you guys need, i'm a native speaker. Maybe more things exist, just saw this one. I'm not sure if it was there in previous versions.

### Screenshots

![image](https://github.com/mumble-voip/mumble/assets/35137992/bae6edfa-94e2-41ec-98c3-609e02e2dded)

**Comment by Hartmnt** [comment]
Hi, thank you for bringing this up. The Mumble translations are handled via the external service called "weblate". See this part of our README https://github.com/mumble-voip/mumble?tab=readme-ov-file#translating

Feel free to contribute any improvements to the dutch translation via that service. The changes from weblate are pulled in on a regular basis. This issue tracker here on GitHub only tracks issues for the other functional parts of Mumble. If you have any questions, feel free to ask in our official Matrix room, or in the GitHub discussions :)
