### ISSUE TITLE
server fails to create/write to log file (aka systemd sucks)

### ISSUE THREAD

**Issue by atomGit** [mumble-voip/mumble#6331]
### The issue

1.5.517 - server was installed from the Arch repo

one problem here is that -fg is used in the systemd unit file and if i remove it, the server won't start (systemctl start mumble-server)

```
mumble-server.service: Scheduled restart job, restart counter is at 5.
mumble-server.service: Start request repeated too quickly.
mumble-server.service: Failed with result 'start-limit-hit'.
Failed to start Mumble server.
```

```
[Unit]
Description=Mumble server
After=network.target
Wants=network-online.target

[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/mumble-server -ini /etc/mumble/mumble-server.ini -fg
Group=_mumble-server
LockPersonality=yes
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes
PrivateDevices=true
PrivateTmp=true
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=true
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectSystem=full
RestrictAddressFamilies=~AF_PACKET AF_NETLINK
RestrictNamespaces=yes
RestrictSUIDSGID=yes
RestrictRealtime=yes
Restart=always
SystemCallArchitectures=native
SystemCallFilter=@system-service
Type=simple
User=_mumble-server

[Install]
WantedBy=multi-user.target
```

### Mumble version

1.5.517

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
> one problem here is that -fg is used in the systemd unit file

Why is that a problem?

**Comment by davidebeatrici** [comment]
Right, the two logging methods should be independent from each other.

**Comment by atomGit** [comment]
maybe i'm not being as clear as i could

* i want the server to log 
* if -fg is used in the unit file, it won't log
* if i remove -fg, the server won't start

i don't understand why removing -fg results in the server failing to start

**Comment by davidebeatrici** [comment]
Oh, that's indeed not expected. What happens if you launch it manually?

**Comment by Krzmbrzl** [comment]
That is expected behavior. If you need a specific log file you can't use systemd. If you do, you should instead use the systemd log

**Comment by atomGit** [comment]
i commented out logfile in the ini, so now the server should be logging to the console, but i'm not sure everything is being logged

when i restart the server (systemctl) and connect to the server, the client connects fine, however the console output seems to indicate problems...

```
<W>2024-02-10 16:37:19.286 QSqlDatabasePrivate::removeDatabase: connection 'ServerHandler' is still in use, all queries will cease to work.
<W>2024-02-10 16:37:19.287 QSqlDatabasePrivate::addDatabase: duplicate connection name 'ServerHandler', old connection removed.
<W>2024-02-10 16:37:19.297 Database SQLite: "3.44.2"
<W>2024-02-10 16:37:19.298 OpenSSL Support: 1 (OpenSSL 3.2.0 23 Nov 2023)
<W>2024-02-10 16:37:19.339 ServerHandler: TLS cipher preference is "[blah blah]"
<W>2024-02-10 16:37:19.452 ServerHandler: connection attempt to [0::1]:57799 failed: Connection refused (0); trying next server....
```

**Comment by Krzmbrzl** [comment]
This is the server log, right? That's odd because ServerHandler is a class that is only used on in the client, if I'm not?mistaken 👀

**Comment by atomGit** [comment]
that was from the client console - is it the journald log you were referring to? if so, that looks ok

**Comment by Krzmbrzl** [comment]
yes I am referring to the journald logfile. Okay this being on the client side at least explains why we see references of ServerHandler there. It doesn't explain what's going on though :thinking:

**Comment by atomGit** [comment]
i think it's working as expected, no? server is logging to jounrnald which is apparently the only place it can log if it's started with systemd, correct?

**Comment by Krzmbrzl** [comment]
Yes - but the client is apparently having some weird issues. That should be completely unrelated to the server log though

**Comment by atomGit** [comment]
yeah, that is odd, but it appears to be working fine

maybe something to do with client and server running on the same box?

let me know if there's anything i can do provide more info and i can open a new issue

**Comment by Krzmbrzl** [comment]
Yeah, please open a separate issue as this is unrelated to the server logging issue. Would be nice if you could check whether this issue is reproducible and if so, add the steps to do so to the new issue.

**Comment by atomGit** [comment]
i've been hesitating on this because i don't exactly understand what the issue is with the client and so i don't know how to properly create a new issue

is it the last line here? ...

```
<W>2024-02-10 16:37:19.286 QSqlDatabasePrivate::removeDatabase: connection 'ServerHandler' is still in use, all queries will cease to work.
<W>2024-02-10 16:37:19.287 QSqlDatabasePrivate::addDatabase: duplicate connection name 'ServerHandler', old connection removed.
<W>2024-02-10 16:37:19.297 Database SQLite: "3.44.2"
<W>2024-02-10 16:37:19.298 OpenSSL Support: 1 (OpenSSL 3.2.0 23 Nov 2023)
<W>2024-02-10 16:37:19.339 ServerHandler: TLS cipher preference is "[blah blah]"
<W>2024-02-10 16:37:19.452 ServerHandler: connection attempt to [0::1]:57799 failed: Connection refused (0); trying next server....
```

**Comment by Krzmbrzl** [comment]
No it's about the first lines where it says that ServerManager is still in use.

**Comment by atomGit** [comment]
"'ServerHandler' is still in use" is no longer an issue - i moved the server and forgot to report this before doing so
