### ISSUE TITLE
new build for EPEL

### ISSUE THREAD

**Issue by atomGit** [mumble-voip/mumble#6340]
### Context

this is not a feature req., however that seemed like the best category

the EPEL version of the server is getting rather long in the tooth and i'm curious as to why that is

is this a pkg maintainer issue, or something else?

mumble is a _very_ valuable piece of software in my opinion and it's quite sad to see it being neglected in the server department

people shouldn't have to rely on snap/flatpak and all the (unwanted) overhead/garbage that comes with that in my opinion, yet the static builds are no longer available for RHEL/Alma systems any longer and so we're stuck with v1.3 which has serious problems when administered via a 1.5 client

please reconsider compiling static builds or finding some way of supporting the common RHEL-based VPS OS

### Description

as above

### Mumble component

Server

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
We don't manage the packages in individual repositories. You'll have to get in contact with the respective maintainers.

Alternatively, you can use the official Docker image for the server.

**Comment by atomGit** [comment]
why not static builds?

**Comment by Krzmbrzl** [comment]
Because we didn't manage to get a truly static build with the new vcpkg environment. And the old env was terribly outdated and even then it was terribly messy to get everything to play together to produce a static build. This kind of effort just doesn't seem to be worth it.
