### ISSUE TITLE
how to monitor connection/activity log?

### ISSUE THREAD

**Issue by atomGit** [mumble-voip/mumble#6342]
### The issue

on Alma, the EPEL package installs murmurd/mumble-server 1.3 and it's controlled via systemd - some of the server information is available via the client console and journalctl, however i'm wanting monitor server activity, such as user joins and exits and i'm not seeing where this is available

apparently this info used to be in the wiki but i couldn't find it 

### Mumble version

1.3.4

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
One possibility would be to write a bot that's connected to the server and which therefore gets notified about new connections etc on the server.
Alternatively, the systemd serverlog should indicate new connections and also disconnects.

**Comment by atomGit** [comment]
i tried `journalctl -u murmurd -f` and `journalctl -u murmurd.service -n 100 --no-pager` and there was no logging of connects/disconnects

**Comment by Krzmbrzl** [comment]
If I start a server locally, I get entries like
```
<W>2024-02-18 18:47:04.344 1 => <0:(-1)> New connection: ::ffff:191.268.168.24:48756
```
in the server log whenever a new client connects and
```
<W>2024-02-18 18:47:04.344 1 => <0:(-1)> New connection: ::ffff:191.268.168.24:48756
```
when a client disconnects.
