### ISSUE TITLE
Mumble bug with Minecraft

### ISSUE THREAD

**Issue by Namirauuh** [mumble-voip/mumble#6343]
### Description

Hello, 
I play with Mumble on the game "Minecraft" with the version 1.3.4 of Mumble (the most stable version for Minecraft) and for several weeks I have a very annoying bug: indeed, at completely random times, the sound cuts and I do not hear/ see anyone talking. On mumble, people talk and I don’t hear them for a few seconds, then it comes back. It’s very annoying when it happens every 2/3 minutes. When this problem happens, even the software tells me that no one speaks anymore. How to fix this problem? I checked all the parameters, it does not come from there because everything worked very well before.
Thank you in advance!

### Steps to reproduce

1. Lauch Mumble
2. Wait and see

### Mumble version

1.3.4

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by davidebeatrici** [comment]
Hello,

Does this only happen when Minecraft is running?

**Comment by Namirauuh** [comment]
yes !
