### ISSUE TITLE
Losing Voice Chat, Hotkeys after RDP

### ISSUE THREAD

**Issue by Mnior** [mumble-voip/mumble#6346]
### Description

Sound and hotkeys are guaranteed to stop working after connecting via RDP (Remote Desktop).
It does not disconnect from the server.
You can fix the problem by simply opening the settings and clicking OK.

### Steps to reproduce

1. Start
2. Connect via RDP from another machine
3. Login to OS (locked after RDP)
4. No sound, no voice, hotkey not work
5. Open Settings & "Save" (click Ok)
6. Sound, Voice, Hotkey work perfect

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows 10

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
So you have a machine A on which you are running Mumble and then you use a machine B to connect to A via RDP which causes the described issues?

**Comment by Mnior** [comment]
> So you have a machine A on which you are running Mumble and then you use a machine B to connect to A via RDP which causes the described issues?

Conversations can no longer be heard and hotkeys no longer work.

Because audio output is configured.

And when connecting RDP, the list of input and output devices changes. Perhaps the client does not restore, or rather, does not respond to changes in the list of devices.

**Comment by Krzmbrzl** [comment]
This sounds like a duplicate of #4992 then, no?

**Comment by Mnior** [comment]
> This sounds like a duplicate of #4992 then, no?

And perhaps as in #4300
