### ISSUE TITLE
Connecting murmur server rom/chanal to another murmur rom/chanal

### ISSUE THREAD

**Issue by FilipStadler** [mumble-voip/mumble#6353]
### Context

It would be usefull to make simular room/chanals available on another server - would that be a way to scale the setup?

### Description

mumble is cool 

### Mumble component

Server

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
That would massively complicate the implementation. I don't see how this would really be worth the cost. If you have channels that shall be completely separated from other channels (e.g. can't be linked to, can't be listened to, etc.) then simply host a second server 🤷‍♂️
