### ISSUE TITLE
The 1.5.X version of Mumble has no effect after turning on "In-Game Display" in the game "EVE Online".

### ISSUE THREAD

**Issue by WJun9a** [mumble-voip/mumble#6360]
### Description

In version 1.4.X, EVE Online can be displayed normally in the game, but in version 1.5.X, it cannot be displayed. I've tried various adjustments, but nothing works.
(I prefer the new and dislike the old, so it feels very awkward to use the 1.4.X version of Mumble now.)

### Steps to reproduce

None.

### Mumble version

1.5.X

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
Hi,

I am sorry, but I am afraid I can not follow your description. With "In-Game Display" do you mean the Mumble overlay?
What exactly do you mean with "EVE Online can be displayed normally in the game"

The Mumble Overlay does not support DirectX 12 at the moment. See #5760 but this is independent of the Mumble version used
