### ISSUE TITLE
Mumble wont start on Raspian bookworm

### ISSUE THREAD

**Issue by sbodese** [mumble-voip/mumble#6362]
### The issue

Hi folks, 
the mumble raspian bookworm version wont start.

systemctl status mumble-server says:

```
mumble-server.service - LSB: Mumble VoIP Server
     Loaded: loaded (/etc/init.d/mumble-server; generated)
     Active: active (exited) since Sun 2024-03-17 19:43:25 UTC; 2min 11s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 16666 ExecStart=/etc/init.d/mumble-server start (code=exited, status=0/SUCCESS)
        CPU: 185ms

Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: QSslSocket: cannot resolve X509_getm_notBefore
Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: QSslSocket: cannot resolve X509_getm_notAfter
Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: QSslSocket: cannot resolve X509_get_version
Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: QSslSocket: cannot resolve X509_STORE_set_ex_data
Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: QSslSocket: cannot resolve X509_STORE_get_ex_data
Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version_num
Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version
Mar 17 19:43:24 raspi.local mumble-server[16693]: qt.network.ssl: Incompatible version of OpenSSL
Mar 17 19:43:24 raspi.local mumble-server[16693]: <F>2024-03-17 19:43:24.897 SSL: this version of Murmur is built against Qt without SSL Support. Aborting.
Mar 17 19:43:25 raspi.local systemd[1]: Started mumble-server.service - LSB: Mumble VoIP Server.
```

Have anyone a idea please?

Greetings Steve

### Mumble version

1.3.4-4

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
This seems like an OpenSSL issue. Is your version of Mumble perhaps compiled for OpenSSL 1.1.x but you have v3 installed or vice versa?

**Comment by Krzmbrzl** [comment]
> What can i do pls ?

Report it to the package maintainer. Seems like the package needs to be fixed

**Comment by sbodese** [comment]
oh yeah, this qt support is a "special" on armv7? no docker image, no easy build 
... or have you an make script for me :-) ? 

PS: mumble is a great work, thanks

**Comment by Krzmbrzl** [comment]
> or have you an make script for me

Check the build documentation

**Comment by crknadle** [comment]
> > What can i do pls ?
> 
> Report it to the package maintainer. Seems like the package needs to be fixed

I'm the package maintainer in Debian, and that's why I'm listed as the package maintainer for Mumble in Raspian. Based on the version numbers I see in the repository, it doesn't look like Mumble has been patched specifically for Raspian.
Is anyone else seeing this bug in mumble-server in Raspian?

**Comment by davidebeatrici** [comment]
Oh, do they have a specific package in Raspbian's repository?

**Comment by sbodese** [comment]
@crknadle well, which version is the right and specifically patched for raspian please ? I got this version from the official raspian bookwork repository with the regular apt install routine.
But if i take a lool with aptitude i got this informations:

![grafik](https://github.com/mumble-voip/mumble/assets/7249354/a4988ee3-862c-4502-9d13-235807f48346)

Greetings

**Comment by sbodese** [comment]
@crknadle well, which version is the right and specifically patched for raspian please ? I got this version from the official raspian bookwork repository with the regular apt install routine.

`deb http://archive.raspbian.org/raspbian bookworm main contrib non-free
deb-src http://archive.raspbian.org/raspbian bookworm main contrib non-free`


Greetings

**Comment by davidebeatrici** [comment]
Well, I would try the one from upstream Debian.

`arm64`: https://deb.debian.org/debian/pool/main/m/mumble/mumble-server_1.3.4-4+b1_arm64.deb
`armhf`: https://deb.debian.org/debian/pool/main/m/mumble/mumble-server_1.3.4-4+b1_armhf.deb
