### ISSUE TITLE
[Request] Support unicode usernames

### ISSUE THREAD

**Issue by shleeable** [mumble-voip/mumble#6368]
### Context

unicode usernames seem to be rejected by default.

### Description

People on a REDM server cannot connect when using unicode usernames.

### Mumble component

Server (Murmur 1.6.304)

### OS-specific?

No? Running on linux ubunutu 20.04

### Additional information

```
<91:[107] 𝕮𝕯(-1)> Rejected connection from 101.98.39.137:2925: Invalid username
<91:[107] 𝕮𝕯(-1)> Connection closed:  [-1]
```

**Comment by Krzmbrzl** [comment]
They are rejected b default because there is lots of ways to play weird tricks with Unicode characters. But they are supported and can be enabled by the server admin.

**Comment by shleeable** [comment]
Hi @Krzmbrzl I am the admin. I cannot find any documention to enable this. Can you help?

https://wiki.mumble.info/wiki/Murmur.ini doesn't have any reference to unicode

**Comment by shleeable** [comment]
`^[\p{L}\p{M}]+$` maybe?

**Comment by Krzmbrzl** [comment]
If you are not concerned that users start doing funny tricks with their usernames, you can simply do `username=.+`, which should match any non-empty name.
If you are concerned about tricky names, using Unicode will name your life extremely hard as there are essentially endless possibilities to do funny things with it.
