### ISSUE TITLE
Text to Speech not working on Mumble 1.5 Ubuntu Snap

### ISSUE THREAD

**Issue by cedarmax** [mumble-voip/mumble#6375]
### Description

I am on Ubuntu 22.04 LTS

1. snap install mumble

2. Enable Text to Speech.

No text to speech audio can be heard.  Other audio works fine.

This only occurs with the snap package, Mumble 1.5.0.  Mumble 1.3.4 from Ubuntu's repository has no issue with Text to Speech.

### Steps to reproduce

1. Install Ubuntu 22.04 LTS
2. snap install mumble
3. Enable Text to Speech.

### Mumble version

1.5.0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by cedarmax** [comment]
> * Does the problem also exist with the native (non snap) package?
> 
>     * Do you have `speechd` installed on your system?

- No, as stated, the problem does not exist with the non-snap package.
- There is no package titled "speechd" in the official repositories.

**Comment by Krzmbrzl** [comment]
Okay, then please report this to the snap package maintainers: https://github.com/snapcrafters/mumble/issues
