### ISSUE TITLE
Mumble reacts slow when simracing pedals are connected

### ISSUE THREAD

**Issue by ReFerox** [mumble-voip/mumble#6388]
### Description

There is an issue where Mumble is reacting slow when there are sim racing pedals connected. While these pedals are connected a window opens after i drag that window around. I.E i click on the settings button, the settings screen stays white, i drag the window and the settings are apearing. Same is valid for closing mumble, the 'are you sure you want to close mumble' screen pops up all blank, but when i drag it a little bit around the buttons to close are showing. When the pedals are disconnected this issue dissapears.

The pedals we are using are the Heusinkveld Ultimate + Pedals. 

### Steps to reproduce

Connect the Heusinkveld Ultimate + pedals
Open mumble
Try to open settings
Settings do open, but it's a blank window
After dragging the window around the settings do apear

Happens on version 1.4.287 and 1.5.163

### Mumble version

1.5.163 x64

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
Is #5631 or #6054 what you are experiencing? Could you try to disable "Global Shortcuts" and see if this makes it any better?

**Comment by ReFerox** [comment]
Yes #6054 is what we are experiencing.
I couldn’t find the Global Shortcuts option, so I disabled the options in the shortcut menu. But this didn’t help.

Van: Hartmnt ***@***.***>
Verzonden: dinsdag 9 april 2024 09:21
Aan: mumble-voip/mumble ***@***.***>
CC: Bram | ReFerox ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mumble-voip/mumble] Mumble reacts slow when simracing pedals are connected (Issue #6388)


Is #5631<https://github.com/mumble-voip/mumble/issues/5631> or #6054<https://github.com/mumble-voip/mumble/issues/6054> what you are experiencing? Could you try to disable "Global Shortcuts" and see if this makes it any better?
