### ISSUE TITLE
un-mute and un-deafen only un-deafens after restart

### ISSUE THREAD

**Issue by atomGit** [mumble-voip/mumble#6393]
### Description

if exiting mumble while mute and deafen are enabled, and then using a hotkey to disable mute and deafen the next time it's run, the mic remains muted

### Steps to reproduce

1. assign a hotkey to deafen self (Control_L + Super_L)
2. deafen self
3. restart mumble
4. use assigned hotkey to un-mute and un-deafen self
5. observe that the mic remains muted

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Manjaro Linux, KDE, Mumble installed from Arch repo

**Comment by Krzmbrzl** [comment]
Is the hotkey still registered after restarting? And does it work immediately after configuring it?

Do other shortcuts remain working after restarting?

**Comment by Hartmnt** [comment]
Can confirm this. This has nothing to do with shortcuts. The information that your state is "deafened (muted implied)" is lost and you will be "muted and then deafened". That means you will have to undeafen and then also unmute.

This is essentially the same as if you
1) mute yourself
2) deafen yourself
3) undeafen yourself

**Comment by Krzmbrzl** [comment]
This might be related to the switch of storing settings in a JSON file and the associated restructuring of setting load and save

**Comment by atomGit** [comment]
> Is the hotkey still registered after restarting? And does it work immediately after configuring it?
>
> Do other shortcuts remain working after restarting?

yes and yes
