### ISSUE TITLE
crashing when (hidetray=true & using -c aka --config)

### ISSUE THREAD

**Issue by gulk1** [mumble-voip/mumble#6396]
### Description

mumble is crashing on startup when

simultaneously using command line: -c aka --config
 AND
hidetray=true in mumble.ini

setting it to false allows mumble to start.

### Steps to reproduce

use both settings

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
What is the exact command line invocation?

**Comment by gulk1** [comment]
`E:\Portable\Mumble\client\mumble.exe -c E:\Portable\Mumble\client\mumble.ini`

**Comment by gulk1** [comment]
Somehow it fixed itself. Dunno what I changed.
