### ISSUE TITLE
Clarify OCB patents are lapse, license of OCB to be public domain

### ISSUE THREAD

**Issue by andreasstieger** [mumble-voip/mumble#6403]
### Description

[src/crypto/CryptStateOCB2.cpp](https://github.com/mumble-voip/mumble/blob/fd0a73ab9a4ef07b87cfaff245c5d0dfc3e075d7/src/crypto/CryptStateOCB2.cpp#L7C1-L14C1) mentions:

````
/*
 * This code implements OCB-AES128.
 * In the US, OCB is covered by patents. The inventor has given a license
 * to all programs distributed under the GPL.
 * Mumble is BSD (revised) licensed, meaning you can use the code in a
 * closed-source program. If you do, you'll have to either replace
 * OCB with something else or get yourself a license.
 */
````

However the patents are lapsed and OCB is now in the public domain. 

### Steps to reproduce

Source code only. Distribution level keyword based license check.

### Mumble version

1.5.0

### Mumble component

Both

### OS

Linux

### Reproducible?

Yes

### Additional information

From https://www.cs.ucdavis.edu/~rogaway/ocb/license.htm

>  OCB is Free
> All OCB-related IP of mine is in the public domain: as far as I am concerned, you may use it, without restrictions, with my blessing. Correspondingly, I long ago stopped paying my patent-renewal fees. This wasn’t an accident; it was a decision. 

From https://mailarchive.ietf.org/arch/msg/cfrg/qLTveWOdTJcLn4HP3ev-vrj05Vg/

> I can confirm that I have abandoned all OCB patents and placed into the public domain all OCB-related IP of mine.

From https://www.cs.ucdavis.edu/~rogaway/ocb/ocb-faq.htm#patent:phil

Well see yourself.

**Comment by Krzmbrzl** [comment]
Would you like to create a PR that removes the comments?
