### ISSUE TITLE
Linux mint repository

### ISSUE THREAD

**Issue by Dispatch3376** [mumble-voip/mumble#6408]
### The issue

The mumble package in the Linux mint repository is version 1.3.4-1
https://community.linuxmint.com/software/view/mumble

### Mumble version

1.3.4

### Mumble component

Client

### OS

Linux

**Comment by Krzmbrzl** [comment]
The Debian package (which also ends up in Linux Mint) is maintained by an external package maintainer and not by us.
However, in the most recent Debian version Mumble has been updated to 1.5
