### ISSUE TITLE
mumble is out of order since 2 days

### ISSUE THREAD

**Issue by dokarukera** [mumble-voip/mumble#6416]
### Description

mumble is out of order since 2 days - 

### Steps to reproduce

impossible to go to : [mumble.puma-network.net](http://mumble.puma-network.net/)

### Mumble component

Client

### OS

Linux

### Reproducible?

No

**Comment by Krzmbrzl** [comment]
With the information given, there is no way we can help you. This sounds like a server-side problem. Are you the server admin? If so, what do the server logs have to say?

**Comment by dokarukera** [comment]
i m admin , but we cannot connect, and all my team cannot use mumble.  i ve try to open [mumble.puma-network.net](http://mumble.puma-network.net/), but also this one is not working. i don t understand what s happen.
this is the answer : 
[22:14:35] Connexion au serveur srv01.serveurmumble.com.
[22:15:05] La connexion au serveur a échoué : Délai de connexion dépassé.

**Comment by davidebeatrici** [comment]
Make sure that the server is running.

**Comment by Krzmbrzl** [comment]
And with server we mean the underlying hardware. Once you have ensured that the server itself is running and reachable (e.g. via SSH), check whether the Mumble server application is running.

**Comment by andreasstieger** [comment]
Thank you for documenting your challenges. 

Two thinks that may explain your observation. First it looks like the domain lapsed:

https://twitter.com/pumanetwork
> Need a free unlimited Mumble server ? Go here : https://puma-network.net/index.php/mumble…

From https://web.archive.org/web/20240210122734/https://wiki.mumble.info/wiki/Hosters

> Free Mumble server with UNLIMITED slots  and high voice quality : 128 Kbits/s. Renewable each month. Instant  setup and full control with our administration panel : stop, start,  change the server name, edit the welcome message, manage users, Mumble  Viewer... Located in France.> 

* 2021-06-13 "free unlimited mumble server" https://web.archive.org/web/20210613071601/https://www.puma-network.net/index.php/mumble
* 2022-12-23 "mumble VPS hosting"... https://web.archive.org/web/20221223214722/https://puma-network.net/ 
* 2023-09-29 "domain has expired" ... https://web.archive.org/web/20230929053008/https://puma-network.net/
* `puma-network.net` registered `2023-11-05T19:30:35Z`
* 2024-02-02 "Welcome to PG electronics" ... https://web.archive.org/web/20240222121527/http://www.puma-network.net/

And secondly this seems to have just resold service from another hoster..

> [mumble.puma-network.net](http://mumble.puma-network.net/),
> `[22:14:35] Connexion au serveur srv01.serveurmumble.com.`

And that service just happened to have [announced closing of service](https://web.archive.org/web/20240515140926/http://www.serveurmumble.com/) on 2024-05-13.

I am not sure how you could not find this out as an "admin", but thank you for documenting. In any case the mumble project cannot help you with that.
