### ISSUE TITLE
Mumble not migrate conf file after user rename 

### ISSUE THREAD

**Issue by HumanG33k** [mumble-voip/mumble#6419]
### Description

I rename my user on my windows device.

In order to keep things order i also rename the home directory. oldname => newname

But when i try to start mumble it is not able to detect curent newname is diferent from C:/Users/oldname/AppData/Roaming/Mumble/mumble.sqlite.

As the path contain C:/Users/aUsername/  and current username is not aUsername we can safely deduce username has change. Instead of asking for a creation of a new database file at old path an option to migrate the configuration path to the new auto detect one if available should be better. 

### Steps to reproduce

1. change OS (windows in my case) username 
2. change user home directory name (change user home dir in regedit, create new admin user, log with it, change dir name, relog with old user, check everything is ok)
3. with modify login user start mumble 

### Mumble version

last one

### Mumble component

Client

### OS

Windows

### Reproducible?

Haven't tried

**Comment by Hartmnt** [comment]
Hi, what happens when you enter ``%AppData%`` into the Windows Explorer path field? Does it lead you to ``C:/Users/oldname/AppData`` or ``C:/Users/newname/AppData``?

**Comment by HumanG33k** [comment]
@Hartmnt  newname

**Comment by HumanG33k** [comment]
i just try to choose to create the path (containing the old user name) and the app start well and the path / database are not create, and mumble start with existing server and stuff so I guess it fallback to the new user. I think message nor behavior had to be modify to not be so scary (where are my data, will i loose something, will it mess up with my directories)
