### ISSUE TITLE
No audio output and no push to talk possible in 1.5.634 on Windows

### ISSUE THREAD

**Issue by Hartmnt** [mumble-voip/mumble#6420]
### Discussed in https://github.com/mumble-voip/mumble/discussions/6418

<div type='discussions-op-text'>

<sup>Originally posted by **smakibbfb** May 20, 2024</sup>
After updating to the new version this morning I get no audio at all and the push to talk function is completely broken, even deleting the config and resetting the audio devices to default does nothing at all to help, if i revert back to the previous version though everything works perfectly again, is anyone able to point me in a direction as to why this might be happening?

<br>
Hi, Windows 11 Pro 23H2 Build 22631.3593 with a Soundblaster AE-5 Plus soundcard, no sound from the new version at all

</div>

**Comment by Hartmnt** [comment]
@smakibbfb

Could you please send us the contents of the [developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) when using the new version?

It may contain a clue as to what the problem is.

**Comment by smakibbfb** [comment]
<X>2024-05-21 11:33:01.787 Loading settings from "C:/Users/****/AppData/Local/Mumble/Mumble/mumble_settings.json"
<W>2024-05-21 11:33:01.844 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<W>2024-05-21 11:33:01.847 Theme: "Mumble"
<W>2024-05-21 11:33:01.847 Style: "Dark"
<W>2024-05-21 11:33:01.847 --> qss: ":themes/Default/Dark.qss"
<W>2024-05-21 11:33:01.848 Locale is "en_GB" (System: "en_GB")
<W>2024-05-21 11:33:02.034 Database SQLite: "3.43.2"
<W>2024-05-21 11:33:02.337 Updating application palette
<W>2024-05-21 11:33:02.628 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2024-05-21 11:33:02.628 QMetaObject::connectSlotsByName: No matching signal for on_muteCuePopup_triggered()
<W>2024-05-21 11:33:03.109 AudioInput: Opus encoder set for low delay
<W>2024-05-21 11:33:03.109 AudioInput: 72000 bits/s, 48000 hz, 480 sample
<W>2024-05-21 11:33:03.110 Public list disabled
<W>2024-05-21 11:33:02.344 XboxInput: using XInput DLL 'XInput1_4.dll'
<W>2024-05-21 11:33:02.344 XboxInput: using XInputGetStateEx() as querying function.
<W>2024-05-21 11:33:03.119 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:33:03.120 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:33:03.123 WASAPIOutput: IsFormatSupported failed: hr=0x88890008
<W>2024-05-21 11:33:03.128 WASAPIOutput: Initialize failed: hr=0x88890008
<W>2024-05-21 11:33:03.130 WASAPIInput: Mic Stream format 1
<W>2024-05-21 11:33:03.130 WASAPIInput: Stream Latency 0 (1056)
<X>2024-05-21 11:33:03.142 GlobalShortcutWin: "[0738:2221] Mad Catz" added
<W>2024-05-21 11:33:03.201 Database SQLite: "3.43.2"
<W>2024-05-21 11:33:03.201 OpenSSL Support: 1 (OpenSSL 3.2.0 23 Nov 2023)
<W>2024-05-21 11:33:03.207 SSL: CA certificate filter applied. Filtered size: 138, original size: 138
<W>2024-05-21 11:33:03.208 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2024-05-21 11:33:03.208 ServerHandler: Failed to load qWave.dll, no QoS available
<W>2024-05-21 11:33:03.195 WASAPIInput: Echo Stream format 1
<W>2024-05-21 11:33:03.195 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 6 channel 48000 hz echo
<X>2024-05-21 11:33:03.603 GlobalShortcutWin: "[0738:A221] Mad Catz" added
<W>2024-05-21 11:33:39.051   OpenType support missing for "MS Shell Dlg 2", script 11
<W>2024-05-21 11:33:39.051   OpenType support missing for "Arial", script 11
<W>2024-05-21 11:33:39.052   OpenType support missing for "MS UI Gothic", script 11
<W>2024-05-21 11:33:39.053   OpenType support missing for "SimSun", script 11
<W>2024-05-21 11:33:39.067   OpenType support missing for "MS Shell Dlg 2", script 20
<W>2024-05-21 11:33:39.068   OpenType support missing for "Arial", script 20
<W>2024-05-21 11:33:39.069   OpenType support missing for "MS UI Gothic", script 20
<W>2024-05-21 11:33:39.070   OpenType support missing for "SimSun", script 20
<W>2024-05-21 11:33:39.071   OpenType support missing for "MS Shell Dlg 2", script 17
<W>2024-05-21 11:33:39.071   OpenType support missing for "Arial", script 17
<W>2024-05-21 11:33:39.071   OpenType support missing for "MS UI Gothic", script 17
<W>2024-05-21 11:33:39.071   OpenType support missing for "SimSun", script 17
<W>2024-05-21 11:33:39.254   OpenType support missing for "Segoe UI", script 20
<W>2024-05-21 11:33:39.254   OpenType support missing for "Microsoft YaHei UI", script 20
<W>2024-05-21 11:33:39.254   OpenType support missing for "Arial", script 20
<W>2024-05-21 11:33:39.255   OpenType support missing for "MS Shell Dlg 2", script 20
<W>2024-05-21 11:33:39.255   OpenType support missing for "MS UI Gothic", script 20
<W>2024-05-21 11:33:39.255   OpenType support missing for "SimSun", script 20
<W>2024-05-21 11:34:11.613 AudioInput: Opus encoder set for low quality speech
<W>2024-05-21 11:34:11.613 AudioInput: 27000 bits/s, 48000 hz, 480 sample
<W>2024-05-21 11:34:11.618 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:34:11.619 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:34:11.619 WASAPIOutput: IsFormatSupported failed: hr=0x88890008
<W>2024-05-21 11:34:11.622 WASAPIOutput: Initialize failed: hr=0x88890008
<W>2024-05-21 11:34:11.623 WASAPIInput: Mic Stream format 1
<W>2024-05-21 11:34:11.623 WASAPIInput: Stream Latency 0 (1056)
<W>2024-05-21 11:34:11.673 WASAPIInput: Echo Stream format 1
<W>2024-05-21 11:34:11.673 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 6 channel 48000 hz echo
<W>2024-05-21 11:34:12.765 AudioInput: Opus encoder set for low quality speech
<W>2024-05-21 11:34:12.765 AudioInput: 27000 bits/s, 48000 hz, 480 sample
<W>2024-05-21 11:34:12.769 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:34:12.770 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:34:12.770 WASAPIOutput: IsFormatSupported failed: hr=0x88890008
<W>2024-05-21 11:34:12.773 WASAPIOutput: Initialize failed: hr=0x88890008
<W>2024-05-21 11:34:12.773 WASAPIInput: Mic Stream format 1
<W>2024-05-21 11:34:12.774 WASAPIInput: Stream Latency 0 (1056)
<W>2024-05-21 11:34:12.822 WASAPIInput: Echo Stream format 1
<W>2024-05-21 11:34:12.822 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 6 channel 48000 hz echo
<W>2024-05-21 11:34:13.757 AudioInput: Opus encoder set for low quality speech
<W>2024-05-21 11:34:13.757 AudioInput: 27000 bits/s, 48000 hz, 480 sample
<W>2024-05-21 11:34:13.761 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:34:13.762 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-05-21 11:34:13.762 WASAPIOutput: IsFormatSupported failed: hr=0x88890008
<W>2024-05-21 11:34:13.765 WASAPIOutput: Initialize failed: hr=0x88890008
<W>2024-05-21 11:34:13.766 WASAPIInput: Mic Stream format 1
<W>2024-05-21 11:34:13.766 WASAPIInput: Stream Latency 0 (1056)
<W>2024-05-21 11:34:13.813 WASAPIInput: Echo Stream format 1
<W>2024-05-21 11:34:13.814 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 6 channel 48000 hz echo

**Comment by Hartmnt** [comment]
@davidebeatrici

**Comment by Krzmbrzl** [comment]
This part seems to be the juicy bit:
> 2024-05-21 11:34:11.619 WASAPIOutput: IsFormatSupported failed: hr=0x88890008
2024-05-21 11:34:11.622 WASAPIOutput: Initialize failed: hr=0x88890008

**Comment by davidebeatrici** [comment]
Precisely: `IsFormatSupported()` returns `AUDCLNT_E_UNSUPPORTED_FORMAT` when the format is not supported in exclusive mode.

**Comment by Krzmbrzl** [comment]
So the solution would be to turn off exclusive mode?

**Comment by davidebeatrici** [comment]
Yes.

**Comment by smakibbfb** [comment]
Only problem there is I have never had exclusive mode set.

**Comment by davidebeatrici** [comment]
Interesting... could you provide brand and model of your sound card, please?

**Comment by smakibbfb** [comment]
It's a Sound BlasterX AE-5 Plus, https://uk.creative.com/p/sound-blaster/sound-blasterx-ae-5-plus
Running the latest drivers and software

**Comment by davidebeatrici** [comment]
Well... in that case the format we are requesting is not supported and the driver does not suggest a close one.

Could you provide a screenshot of the audio output device properties? Specifically, I'm interested in the format that is set.

**Comment by smakibbfb** [comment]
![image](https://github.com/mumble-voip/mumble/assets/149095470/d33471b8-4006-4115-af33-bb7d1c5db0d7)

Default is the above but I have tried a few others too, just want to be clear this has worked perfectly and still works perfectly on the previous version of Mumble

**Comment by davidebeatrici** [comment]
Without any changes at all to the audio driver and/or settings?

**Comment by smakibbfb** [comment]
Yep, previous version has worked fine since it was released with no changes between the two.

**Comment by Fuchs** [comment]
Same effect here, and while I also do have a Sound BlasterX AE-5 in my machine, it's actually not used and not the default, in use and the default is a Sennheiser GSX 1200. Downgrading mumble to 1.4.287 resolves the issue, upgrading to 1.5.634 it doesn't work, with the exact same settings between the two versions.

**Comment by Krzmbrzl** [comment]
@smakibbfb @Fuchs is anyone of you able to compile Mumble yourself in order to do a bisect to identify the root of this issue?
