### ISSUE TITLE
1.5 Flatpak crashes when opening up the settings

### ISSUE THREAD

**Issue by gianmarcogg03** [mumble-voip/mumble#6421]
### Description

In the latest Mumble update when I open the settings the application freezes with some sound glitches (audible only when some audio is playing) for a few seconds and then closes. Also my custom sounds didn't play for some reason.

### Steps to reproduce

1. Click on the options button

### Mumble version

1.5.634

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Flatpak on EndeavourOS.
Screen recording (the sound glitch isn't audible though): 

https://github.com/mumble-voip/mumble/assets/28053717/0fa74922-1256-40bb-898e-b4d1b9201e94

**Comment by Krzmbrzl** [comment]
Please report that to the Flatpak maintainers (they have a separate github repo)

**Comment by Hartmnt** [comment]
@gianmarcogg03 Are you using Wayland? If so, try to remove any keyboard shortcuts by editing the config files by hand.

**Comment by mryamac** [comment]
OS:
Linux user-VirtualBox 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
QT:
QMake version 3.1
Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu

Debug Log:
F>2024-05-22 16:43:50.701 ASSERT: "!isEmpty()" in file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 364

Call stack :
![image](https://github.com/mumble-voip/mumble/assets/45417780/d3a44de7-673e-4b17-bcd0-a147367931b9)
