### ISSUE TITLE
Positional Audio not working for GoldSRC Games (Counter-Strike)

### ISSUE THREAD

**Issue by einfacharthur** [mumble-voip/mumble#6423]
### Description

Mumble is not showing that positional audio plugin is connected.
for Source based games it is working tho:
[22:21:15] Source Engine hat eine Verbindung hergestellt

trying the steam_legacy	Pre-25th Anniversary Build:
hl.exe
] version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:53:27 Aug  3 2020 (8684)

not working!

### Steps to reproduce

![image](https://github.com/mumble-voip/mumble/assets/12992757/145fd12f-06b4-4793-8a94-f81792f84ef2)

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
I assume the version you are trying to use is not >= 1.6 from Steam? 🤔

**Comment by davidebeatrici** [comment]
We rely on memory offsets, which are most likely changed as the build appears to be from 2020.

**Comment by Nekto89** [comment]
> We rely on memory offsets, which are most likely changed as the build appears to be from 2020.

question: what tools can be used to find new memory offsets? I would like to try that with Rocket League but I don't know where to start
