### ISSUE TITLE
Support for Specifying Certificate Files via Command Line or Config File

### ISSUE THREAD

**Issue by awatchar** [mumble-voip/mumble#6424]
### The issue

Hello,

I am looking for a way to specify certificate files in the Mumble client for Windows. While I know it’s possible to set these in the mumble.ini configuration file, I am interested in knowing if there is a way to specify these files directly via command line arguments.

Is there a way to achieve this via command line options or another method for easier automation and script integration?

Thank you!

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
Have a look at the output when running Mumble with the `--help` option. If there is nothing listed there (which I think is the case) then it is currently not supported.
