### ISSUE TITLE
Problem today with Version 1.5.634 on both Linux and windows

### ISSUE THREAD

**Issue by FilipStadler** [mumble-voip/mumble#6430]
### Description

Suddenly the connection gets adjusted and it says

[09:32:16] Server instructed us to use an audio codec different from Opus, which is no longer supported. Disconnecting...

[09:32:16] (Private) server: WARNING: Your client doesn't support the CELT codec, you won't be able to talk to or hear most clients. Please make sure your client was built with CELT support.

[09:32:16] Velkomstbesked: 
Velkommen til Danske Digital Radio NetMurmur. 
Nyd at sludre med de andre!
Se https://ddrnet.dk
Husk evt. PTT Transmit mode

[09:32:16] Forbindelse til server afbrudt.

[09:32:16] Serverens maksimale netværksbåndbredde er kun 72 kbit/s. Lydkvaliteten blev automatisk justeret til 56 kbit/s (20 ms)

If I downgrade to normal mumbla from ubunto repository I can connect again but normal and I have simular problem with the current version on Linux from flatpak repository - I have been using the 1.5 for some days with no problem but now I have problems because I did upgrade to lates on some computers running the lates from flatpak repository,

Anyway this bug is on both my windows client computer with windows 10 and the Linux computers.

### Steps to reproduce

I can do it both windows and Linux

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

The android mumla connects as normal and also downgrade to mumble in ubuntu repository  with apt install mumble works fine but then it lack the nice stuff.

**Comment by Krzmbrzl** [comment]
The Mumble client bo longer support anything but the Opus codec. You have to enforce Opus on the server to prevent individual ancient clients not using Opus to downgrade all clients to older codecs. 
1.5 servers enforce Opus by default.

**Comment by FilipStadler** [comment]
I am not really sure and find it strange that 1.5.634 was working finde but for some reason it did change.

Swiching to mumble to Mumble (1.3.4-1ubuntu1)  I have not changed the server only upgraded the clients, it used celt CELT 0.7.0 on the older client before but can it be that the mumble server does not provide opus but I can enfoce it ?

**Comment by Krzmbrzl** [comment]
You have to use the `opusthreshold` config option

**Comment by FilipStadler** [comment]
Ok it was not set in the ini file so if understand it correctly so will be in percent that maybe treshold 95 would say 5% is allowed to use something else ?

**Comment by Krzmbrzl** [comment]
See https://wiki.mumble.info/wiki/Murmur.ini#opusthreshold

In order to enforce Opus usage (aka: never switch to an older codec), set this option to `0`
