### ISSUE TITLE
Host does not match any of the list in the certificate

### ISSUE THREAD

**Issue by Hountez** [mumble-voip/mumble#6432]
### Description

Upon connecting to my server the client complains about the Certificate i use (letsencrypt), i registered multiple domains in the certificate including the one Mumble uses but I get as error that the hostname does not match any of the list of valid hosts on the certificate.

The domain used is listed as "DNS" under certificate details, this is how letsencrypt creates the certificate if multiple domains are used in one certificate and does not pose a problem in any other application i use the certificate.

The domain i use is "deutschritter.eu" if you want to test it.

Let me know if you need further information.

### Steps to reproduce

Connect to the server and get greeted with an error message

### Mumble version

1.3.4-1

### Mumble component

Both

### OS

Linux

### Reproducible?

Yes

### Additional information

OS: Debian 11
Mumble server installed with APT

**Comment by Krzmbrzl** [comment]
To narrow things down, could you create a certificate exclusively for the domain Mumble uses to see if that works as expected?

**Comment by Krzmbrzl** [comment]
Hm. No idea either. If it is no longer an issue for you, I'll close this issue though as there is no way we can figure things out without a way to reproduce the issue.
