### ISSUE TITLE
Mumble crashing chaning from default white to dark theme

### ISSUE THREAD

**Issue by makedir** [mumble-voip/mumble#6434]
### Description

Mumble crashing with no feedback turning on dark mode, then nothing happening anymore opening Mumble, have to force close process in task manager.

If you reopening Mumble it takes a log time again and a send crash report gui, after this it seems to work fine even with dark theme.

### Steps to reproduce

Opening mumble change to dark mode. Restarting Mumble.

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
This seems to be the same as #6114. Could you follow the instructions in that issue to create and upload a dump of this crash?

**Comment by iwa** [comment]
i'm having the exact same issue :/

@Krzmbrzl sorry to bother you but how can i find that userdump.exe app? i don't have any `C:\kktools` on my win 11 pc

**Comment by Krzmbrzl** [comment]
With the info provided, we can't really act on this. From the steps described to get the issue fixed, this might have something to do with the known-to-be-buggy tray icon implementation. If that is the case, the underlying issue should be resolved once #6466 gets merged.
