### ISSUE TITLE
All GUI elements not good readable on Windows client, too big fonts and scaling

### ISSUE THREAD

**Issue by makedir** [mumble-voip/mumble#6435]
### Description

No GUI elements reable with latest Mumble 1.5. Everything too big, no way to change GUI font size or any scaling.

### Steps to reproduce

Using Mumble 1.5.x

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Do you have global scaling enabled in Windows? What is your screen resolution?

This seems to be a duplicate of #1850
