### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by makedir** [mumble-voip/mumble#6436]
### Description

No way to get the Overlay working with Mumble. After all the years, still not fixed with 1.5.

### Steps to reproduce

Opening Mumble, turning on Overlay. Nothing is working. Adding allowed exe, nothing is working. No Overlay shown in anyway.

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Alright. This report does not provide any meaningful information to us. Closing this.
