### ISSUE TITLE
After uninstall mumble 1.5.634 and install 1.4.x, all the server links are gone

### ISSUE THREAD

**Issue by huapage** [mumble-voip/mumble#6437]
### The issue

I install mumble 1.5.634, then add some servers. Then I find some servers don't support 1.5.634 (e.g. Some servers which support Mumble 1.2.3 still use CELT codec), then I install back 1.4.x so that I can connect to these servers. But all the servers added in 1.5.634 cannot be found in 1.4.x . Need to add them back manually.

If I install 1.4.x first then 1.5.634, the servers are migrated properly.

I found 1.5.634 will use %appdata%\Mumble\Mumble as data folder but 1.4.x will use %appdata%\Mumble as data folder. Why there is such a change?

Workaround: Manually copy the data in %appdata%\Mumble\Mumble to %appdata%\Mumble, then launch 1.4.x, the servers will appear ( not sure if it will cause any side effect by doing this ).

Suggestion 1: Can we keep same data folder in 1.5.x ? e.g. Still use %appdata%\Mumble as data folder?  Especially if there is no database format change.

Suggestion 2: Can we keep the CELT codec support in 1.5.x (or at least as a installer option)? Since one client may need to connect to many servers, we cannot control all the servers are upgraded. Then we have to use Mumble 1.4.x rather than 1.5.x  if 1.5.x doesn't support CELT codec.

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
> Can we keep same data folder in 1.5.x ? e.g. Still use %appdata%\Mumble as data folder? Especially if there is no database format change.

The paths come from Qt and the change results from fixing another issue in which Qt wasn't configured correctly. Keeping the old path would essentially mess with the cross platform compatibility that we get by getting the paths from Qt in the first place.

> Can we keep the CELT codec support in 1.5.x (or at least as a installer option)? Since one client may need to connect to many servers, we cannot control all the servers are upgraded. Then we have to use Mumble 1.4.x rather than 1.5.x if 1.5.x doesn't support CELT codec.

No. Opus should be supported by 99% of all clients out there. If servers are still configured to use CELT, then they are misconfigured. Mumble 1.2 has been EOL for years now. Removing CELT support allowed significant cleanup of the code base.

Side-node: Server admins should either upgrade to the latest server version or set the `opusthreshold` option in the INI to 0.

**Comment by huapage** [comment]
For this Side-node: Server admins should either upgrade to the latest server version or set the opusthreshold option in the INI to 0.  This will make server switch codec from CELT codec to Opus codec.

From server side of view, which codec is more lightweight?

Assume a server previous uses CELT codec, now use Opus. What is the impact to the server. ( Bandwidth, CPU etc. )

e.g. Assume a server can support 500 concurrent users  with CELT codec ( some of them are talking, most of them are listening ), after switching to Opus codec, the concurrent users supported by server will increase or decrease?

**Comment by Krzmbrzl** [comment]
> From server side of view, which codec is more lightweight?

For the server there is no difference as the server doesn't en- or decode any audio packets. They are only passed-through between clients.

In terms of size I don't know, but I don't expect huge differences. If anything, Opus is the one I would expect to yield smaller package sizes but that's just a guess.

Either way, CELT is a legacy codec in Mumble and therefore deprecated by definition and from 1.5 is officially no longer supported. That means that every server that insists on using CELT will become incompatible with all future Mumble versions.
