### ISSUE TITLE
is there any possible to change registerPassword

### ISSUE THREAD

**Issue by bonjour-py** [mumble-voip/mumble#6438]
### The issue

i used to configured a insecure registerPassword to register server on public list 
i think i should change it , but i got errors when i did :
```
<W>2024-05-28 08:45:09.511 1 => Registration failed: Host requires authentication
<W>2024-05-28 08:45:10.481 1 => <0:(-1)> Connection closed: The TLS/SSL connection has been closed [1]
```

how to change it 
plz help

### Mumble version

Murmur 1.5.634 running on Linux: Ubuntu 22.04.4 LTS [x64]

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
@davidebeatrici ^

**Comment by davidebeatrici** [comment]
You should wait until the server disappears from the public list. Alternatively, you can send us (either here or in private) your server's info so that we can delete it manually.

**Comment by bonjour-py** [comment]
thank you very much
I believe everyone should wait for automatic deletion.


some questions (could make it as doc)

how long will it takes
should I shut my server down to let it disappears from the public list

**Comment by davidebeatrici** [comment]
> how long will automatic-deletion takes

7 days.

> should I shut my server down to let it disappears from the public list

No, as long as registration fails the timeout period is not reset.

**Comment by bonjour-py** [comment]
thanks again

**Comment by bonjour-py** [comment]
I changed REGISTER_PASSWORD a week ago, but still got “Registration failed: Host requires authentication”. 
After turning off registration (deleting REGISTER_PASSWORD), it has been 2 weeks, and I still get “Registration failed: Host requires authentication”.

please help 

my server : 

Environment = MUMBLE_CONFIG_REGISTER_NAME=班泽的窝
Environment = MUMBLE_CONFIG_REGISTER_PASSWORD=**********
Environment = MUMBLE_CONFIG_REGISTER_HOSTNAME=voice.bonjour.zone
Environment = MUMBLE_CONFIG_REGISTER_URL=https://space.bilibili.com/42442654
Environment = MUMBLE_CONFIG_REGISTER_LOCATION=CN

**Comment by davidebeatrici** [comment]
Please note that I deleted the original revision of your message as otherwise the censored info could still be read.

I Just checked our records: your server is actually listed twice:

```
home of Bonjour | 2024-05-27 11:27:08 | voice.bonjour.zone
班泽的窝 | 2024-05-28 23:59:56 | voice.bonjour.zone
```

The timestamp represents the last time communication with the server took place.

Looks like the trigger that took care of automatically deleting old records has been missing for a while:

```sql
DELETE FROM servers WHERE seen < (NOW() - INTERVAL 1 WEEK);
Query OK, 1110 rows affected (0.034 sec)
```

I restored it now.

**Comment by bonjour-py** [comment]
thank you very much

**Comment by davidebeatrici** [comment]
You're welcome, thank you for reporting the issue.
