### ISSUE TITLE
i want pymumble

### ISSUE THREAD

**Issue by KGLongWang** [mumble-voip/mumble#6439]
### Context

I am looking for a voice library that can be integrated into program. I tried Mumble, and the voice quality is quite good; all the noise around me is blocked out. I found a PyMumble library that can connect to Murmur, but this library has not been maintained for two years. I really hope there can be a new PyMumble library available for use.

### Description

 can be integrated into program

### Mumble component

Client

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
There is github.com/mumble-voip/libmumble but it is not yet production ready.
