### ISSUE TITLE
How can I update the libopus version from 1.3.1 (which is currently being used) to 1.5.2 ?

### ISSUE THREAD

**Issue by developer-swetabh** [mumble-voip/mumble#6453]
### The issue

The current opus version which is being used in mumble server is 1.3.1. I want to upgrade it to 1.5.2 which is the latest version of libopus library. 
According to the official website of opus, the latest version includes several improvements to the encoder and decoder.
Opus 1.5 also includes improved packet loss robustness using DRED. Opus 1.5 also includes other improvements, such as better AVX2 and ARM NEON optimizations, low-bitrate speech quality enhancements, and support for 4th and 5th order ambisonics.

So, I want to upgrade the opus version.

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

**Comment by Hartmnt** [comment]
The Mumble server does not decode or encode audio packets. It merely forwards audio packets from client to client. That means that the server is not built against libopus at all. If you want to use a newer version of libopus, you would have to recompile the client with that version. AFAIK opus 1.5 is API backwards compatible, so this should not be much of a problem in theory.
