### ISSUE TITLE
Remove deprecated QStandardPaths from config fallback chain

### ISSUE THREAD

**Issue by Hartmnt** [mumble-voip/mumble#6459]
### Description

Mumble uses fallback chains for possible configuration paths. If configuration/database is found in a legacy location, that will be used and/or migrated to the new location.

Unfortunately, ``QStandardPath::DataLocation`` is deprecated in Qt5 https://doc.qt.io/qt-5/qstandardpaths.html and removed in Qt6

These need to be removed, ideally without breaking the fallback chain.

https://github.com/mumble-voip/mumble/blob/f73db9da7ac81eda2c6eeacad6c97d97481a5e65/src/mumble/Database.cpp#L47-L57

https://github.com/mumble-voip/mumble/blob/a32229f88c9b6cbf8f33a2baa3e4373b27d54d80/src/mumble/Settings.cpp#L1279-L1284

https://github.com/mumble-voip/mumble/blob/a32229f88c9b6cbf8f33a2baa3e4373b27d54d80/src/murmur/Meta.cpp#L168

### Mumble version

1.5.634

### Mumble component

Both

**Comment by yapa-ymtl** [comment]
Hi Can fix this issue, I was trying to build the project on my mac. As mentioned in the doc I installed all the packages but getting this error  
![Screenshot 2024-08-10 at 11 06 16](https://github.com/user-attachments/assets/76ce9ef1-13b6-466e-b524-696bdc7cf23a)

**Comment by Krzmbrzl** [comment]
You need to do `git submodule update --init --recursive`

**Comment by davidebeatrici** [comment]
Please note that this is already fixed in #6516.

**Comment by Krzmbrzl** [comment]
@davidebeatrici you should link this issue to your PR to make GitHub aware of that.

**Comment by yapa-ymtl** [comment]
> You need to do `git submodule update --init --recursive`

Thank you

**Comment by yapa-ymtl** [comment]
> @davidebeatrici you should link this issue to your PR to make GitHub aware of that.

Noted.
