### ISSUE TITLE
Add AppImage for server

### ISSUE THREAD

**Issue by Greelan** [mumble-voip/mumble#6463]
### Context

Setting up a new server on Linux 

### Description

I'd like to see AppImages for the server binaries. This would allow flexibility to run the server on any distro without having to rely on outdated packages in distro repos (Debian 12's version is over 3 years old) or build from source just to get an up to date version. I realise there is a docker image but not every use case is suited to using docker. 

### Mumble component

Server

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment]
We have a Docker image for the server: https://github.com/mumble-voip/mumble-docker

As for the AppImage, we already have this ticket for them: https://github.com/mumble-voip/mumble/issues/4659

**Comment by Greelan** [comment]
Thanks. I'm aware of the docker image as mentioned in my original post. I'm talking about circumstances where using that image is not possible or desired. 

Sounds like the AppImage won't happen based on the other ticket.

**Comment by Deojuvente** [comment]
+1 on circumstances where using that image is not possible or desired.

**Comment by Krzmbrzl** [comment]
> Sounds like the AppImage won't happen based on the other ticket.

At least not anytime soon
