### ISSUE TITLE
Authentik

### ISSUE THREAD

**Issue by mrbreil** [mumble-voip/mumble#6470]
### The issue

I would like to use mumble with Authentik.
I know that mumble can do ldap authentication. But I can't do it because my users can log in. Can someone help me or has a tip for me? Many thanks

### Mumble version

1.4

### Mumble component

Server

### OS

Other

**Comment by Krzmbrzl** [comment]
> But I can't do it because my users can log in.

This sentence I find rather confusing 🤔
