### ISSUE TITLE
Doesn't load blank mumble.ini or save setting to file

### ISSUE THREAD

**Issue by Cruentus-Tigris** [mumble-voip/mumble#6471]
### Description

Mumble does not recognize blank mumble.ini file when in program files or in folder on desktop and only uses settings in app data, when hardcoded to use mumble.ini with "-c mumble.ini" loads default settings but does not save settings. both don't override settings in ini to use them next time. Works perfely in 1.4.287 loads and save using ini.

### Steps to reproduce

1. copy mumble folder to desktop
2. create mumble.ini client folder
3. run problem
4. notice it uses setting already made on installed version not defaults as it should with a blank file

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
The Mumble 1.5 Client migrates settings to a ``.json`` file. Please take a look in ``AppData`` folder and search for a ``mumble_settings.json`` and try to use that as a reference for the ``mumble -c`` command.
