### ISSUE TITLE
Mumble client 1.5.634 would not launch on Windows 7 (x64)

### ISSUE THREAD

**Issue by MrZomka** [mumble-voip/mumble#6473]
### Description

Hey everyone. I recently reinstalled Windows 7 (x64) on an old computer of mine and I tried installing the latest release of the Mumble client for Windows x64. However, it would launch and would only output an error message box, a screenshot of which is attached below.
I could not reproduce this on the latest stable release (1.4.287), so I assume something in the latest stable release is causing this.

### Steps to reproduce

1. Install the Mumble client on Windows 7
2. Open it
3. The error will appear

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll.](https://github.com/mumble-voip/mumble/assets/25344028/3ff04137-6877-4f09-94b5-6f480e634d35)

**Comment by MrZomka** [comment]
Update: Tried to get one of the RCs to work and I found out that the latest version I was able to get to work is [1.5.517](https://github.com/mumble-voip/mumble/releases/tag/v1.5.517).
![Mumble 1.5.517's About page running on Windows 7](https://github.com/mumble-voip/mumble/assets/25344028/fab54ddf-7318-4fc0-b994-f7648305c3e5)
So, I guess something that was introduced in RC2 broke it...

**Comment by MrZomka** [comment]
Huh... I couldn't find any references to `GetSystemTimePreciseAsFileTime` in the source code for the Mumble client... Perhaps it's in one of the libraries?... I honestly don't know... I hope someone could help me with this :(

**Comment by davidebeatrici** [comment]
Please note that we officially support only Windows 10 and newer.

I would try https://github.com/vxiiduu/VxKex, if that symbol is the only one to be missing there's a strong chance the solution will work.

**Comment by Krzmbrzl** [comment]
It's almost certainly Qt that has the dependence to the referenced function. Officially, Qt hasn't supported Windows 7 for quire a while now, so if 1.5.517 has worked, that's just coincidence. 
As Davide said: we only support Windows 10 and newer (due to Qt, mostly)

**Comment by MrZomka** [comment]
> Please note that we officially support only Windows 10 and newer.

The README says otherwise though...
> Please note that with "Windows" we mean 7 and newer.

Oh well… I guess I’ll try recompiling Mumble with an older version of Qt or just stay on 1.5.517.

Thanks for the help :)

**Comment by Krzmbrzl** [comment]
> The README says otherwise though...

Fixed, thanks!

**Comment by davidebeatrici** [comment]
@MrZomka Keep in mind that Windows 7 has been out of support since January 2020.

If you're not willing to use third-party patches, I strongly recommend to switch to a Linux distribution.

**Comment by MrZomka** [comment]
> @MrZomka Keep in mind that Windows 7 has been out of support since January 2020.
> 
> If you're not willing to use third-party patches, I strongly recommend to switch to a Linux distribution.

It’s fine. It’s not my main computer anyway, it’s just for messing around in old software. I daily drive Arch Linux on my main computer.

**Comment by davidebeatrici** [comment]
I see.
