### ISSUE TITLE
Compiling 1.6.0 on  OS: Debian GNU/Linux 12 (bookworm) aarch64  Kernel: 6.6.31+rpt-rpi-v8   

### ISSUE THREAD

**Issue by FilipStadler** [mumble-voip/mumble#6476]
### Description

OS: Debian GNU/Linux 12 (bookworm) aarch64  Kernel: 6.6.31+rpt-rpi-v8 
 
cmake ..
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python interpreter version 3.11.2
-- Performing Test COMPILER_HAS_MBIG_OBJ
-- Performing Test COMPILER_HAS_MBIG_OBJ - Failed
-- Using (among others) the following compiler flags: -Werror;-Wall;-Wpedantic;-Wextra;-Wconversion;-Wsign-conversion;-fsigned-char;-O3
-- ##################################################
-- Mumble version:              1.6.0
-- Architecture:                arm64
-- Build type:                  Release
-- Using LTO in release builds: ON
-- ##################################################
CMake Error at cmake/pkg-utils.cmake:87 (message):
  Qt5 component not found: Core
Call Stack (most recent call first):
  src/CMakeLists.txt:20 (find_pkg)

### Steps to reproduce

Use clean  OS: Debian GNU/Linux 12 (bookworm) aarch64  Kernel: 6.6.31+rpt-rpi-v8 
follow guide on how to compile on Debian 

Also did sudo apt install \
  build-essential \
  cmake \
  pkg-config \
  qtbase5-dev \
  qtchooser \
  qt5-qmake \
  qtbase5-dev-tools \
  qttools5-dev \
  qttools5-dev-tools \
  libqt5svg5-dev \
  libboost-dev \
  libssl-dev \
  libprotobuf-dev \
  protobuf-compiler \
  libprotoc-dev \
  libcap-dev \
  libxi-dev \
  libasound2-dev \
  libogg-dev \
  libsndfile1-dev \
  libspeechd-dev \
  libavahi-compat-libdnssd-dev \
  libxcb-xinerama0 \
  libzeroc-ice-dev \
  libpoco-dev \
  g++-multilib
  
  But   g++-multilib was not avaible - I am not sure if this has anything to say.

### Mumble version

1.6.0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
It seems like you don't have a proper Qt5 installation. I would have expected `qtbase5-dev` to be what you need but apparently it's not. These are the packages we install on our CI in order to make it work:
https://github.com/mumble-voip/mumble/blob/2ad73f6e0d2a1818e804a8a8348063615693d9ee/.github/actions/install-dependencies/install_ubuntu_shared_64bit.sh#L5-L32

**Comment by FilipStadler** [comment]
It can't add and libasound2-plugins-extra

E: Kunne ikke lokalisere pakken g++-multilib
E: Kunne ikke lokalisere pakken libasound2-plugins-extra

So I tried without them (dont know how important they are) 

The only warning I get is this

-- Configuring done
CMake Warning (dev) at 3rdparty/renamenoise/CMakeLists.txt:48 (add_library):
  Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
  enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  INTERPROCEDURAL_OPTIMIZATION property will be ignored for target
  'renamenoise'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
 I am have ignord it
 
 So its compile slowly :)  but done...  Thanks

**Comment by Krzmbrzl** [comment]
Alright - so I take it the issue is resolved?
Glad to have helped you then :)
