### ISSUE TITLE
Calling a PTT/GPIO function doing from TalkingUI bedst way - recommendations ?

### ISSUE THREAD

**Issue by FilipStadler** [mumble-voip/mumble#6482]
### Context

Controlling GPIO pins on from the TalkingUI

Need to call a function that can do some setup of GPIO pins when other speak not it self speak/transmit on in a rum.

### Description

I would like to add a function the TalkingUI  event can execute.

TalkingUI is set to active at set to remove silent user after 0 seconds

So when somebody is speaking it shows the user and call a PTT-on if the user speaking is NOT our self.

When the remove silent user after 0 seconds is called it calls
a PTT-off to turn off active transmitter and the Talking UI is emty again.

This would alow mumble connect/control a cbradio to raspberrypi - where mumble operate in voice activated mode
but here is a small problem it also have to avoid calling ptt-on if the "radio" our self is already speaking on mumble but when somebody else on the mumble chanal is speaking change talkingUI it should execute the ptt-on until talking-ui goes to emty it shuld call the ptt-off.

In a bash the ptt-on would do:

#!/bin/bash
# ptt-on
gpio mode 24 out
gpio write 24 1

And ptt-off woulde look like this 
#!/bin/bash
# ptt-off
gpio mode 24 out
gpio write 24 0

OK I am not sure on how to make a plugin and if a plugin and understanding the api is not easy for me.

### Mumble component

Client

### OS-specific?

No

### Additional information

Zello and teamspeak have plugin but option to call a script depening on the above change in Takling mode would be make mumble more powerfull to that usage also.

Any recommendation to this ?

**Comment by Green-Sky** [comment]
This sounds like something that you can do with plugins. https://github.com/mumble-voip/mumble/tree/master/docs/dev/plugins

specifically https://github.com/mumble-voip/mumble/blob/7fd66b5c36a9c55efceb8a82484d635cf3bb67ec/plugins/MumblePlugin.h#L989-L997

**Comment by FilipStadler** [comment]
> This sounds like something that you can do with plugins. https://github.com/mumble-voip/mumble/tree/master/docs/dev/plugins
> 
> specifically
> 
> https://github.com/mumble-voip/mumble/blob/7fd66b5c36a9c55efceb8a82484d635cf3bb67ec/plugins/MumblePlugin.h#L989-L997

I agree with you it looks like possible via the plugin solution but I must admit my programming skills are very limited  today it maybe 30 years since I did any C programming so even if I look on the examples its hard for me to avoid some confussion.

The on the air plugin would be very useful in a lot of cases beside radio push to talk even if plugin can be made universel to call other programs but I am not sure how to understand the information - it looks like i provide both information about server like if we where connected to more than one server and is mumble_userid_t a string with the name so I have alot to lean  again  but this maybe very natual for the developers.

**Comment by Krzmbrzl** [comment]
Yep, this is definitely something that should be implemented as a plugin.

> it looks like i provide both information about server like if we where connected to more than one server and is mumble_userid_t a string with the name

The user ID is numeric and for the rest I refer you to the plugin docs linked above.
