### ISSUE TITLE
Server sporadically disappears from the public server list

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#6490]
### Description

```txt
mumble.zova.io
```

Restarting the container does not seem to have any effect

### Steps to reproduce

1. Run a Mumble server

### Mumble version

1.5.634 official Docker image

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

Last I submitted the issue I ended up closing it as the server reappeared in the public server list shortly afterwards

### Relevant log output

```shell
Sadly nothing beyond the ordinary
```

**Comment by Krzmbrzl** [comment]
@davidebeatrici ^

**Comment by davidebeatrici** [comment]
Right now the server is present in the list. Please let me know if and when it disappears and I can check why.

**Comment by StrangePeanut** [comment]
@davidebeatrici just noticed that the server `mumble.zova.io` is not being listed again

**Comment by StrangePeanut** [comment]
@davidebeatrici server still hasn't reappeared in the public list which is unusual. I also haven't restarted it at all. Hope you can find the cause of the issue as it must surely affect more servers. Please let me know if there's anything I can do to assist.

**Comment by Scar1943** [comment]
> @davidebeatrici server still hasn't reappeared in the public list which is unusual. I also haven't restarted it at all. Hope you can find the cause of the issue as it must surely affect more servers. Please let me know if there's anything I can do to assist.

I've noticed a similar problem with the windows version of the server. I open the server log when first starting the server and watch for the registration entry. If you don't see in in like the first hand full of mins or so, I shut down, and restart the server. Once you finally see the successful message in the first hand full of mins, it will then continue to update ok. No idea why it happens, it was just the nature of the beast for me, and have learned to deal with it.

**Comment by StrangePeanut** [comment]
> > @davidebeatrici server still hasn't reappeared in the public list which is unusual. I also haven't restarted it at all. Hope you can find the cause of the issue as it must surely affect more servers. Please let me know if there's anything I can do to assist.
> 
> I've noticed a similar problem with the windows version of the server. I open the server log when first starting the server and watch for the registration entry. If you don't see in in like the first hand full of mins or so, I shut down, and restart the server. Once you finally see the successful message in the first hand full of mins, it will then continue to update ok. No idea why it happens, it was just the nature of the beast for me, and have learned to deal with it.

@Scar1943 you seem to be onto something! Yesterday I ran `grep` on the log and there were no occurrences. I restarted the server earlier. It now pops up in the list again, and sure enough, there is a 'Registration updated!' line in the log.

**Comment by Krzmbrzl** [comment]
In cases where you don't see the registration message, do you instead see the `Not registering server as public` log entry? Or is there simply no registration-related message in the logs at all?

I'm currently trying to find a code path that leads to the server starting normally, but the registration not happening...

The most likely scenario that I see is that the server correctly sends the registration update to the public server list, but never receives a reply and therefore never logs anything about the registration :eyes:

**Comment by Hartmnt** [comment]
> The most likely scenario that I see is that the server correctly sends the registration update to the public server list, but never receives a reply and therefore never logs anything about the registration 👀

In that case we should, in addition to fixing the backend stuff, implement a mechanism for a mumble-server to retry public registration

**Comment by Krzmbrzl** [comment]
> In that case we should, in addition to fixing the backend stuff, implement a mechanism for a mumble-server to retry public registration

If I understand the code correctly, it does send a registration message every hour (plus some random jiggle).

**Comment by davidebeatrici** [comment]
Correct, that's why I suspect there is something blocking the mechanism in the server's code.

**Comment by Krzmbrzl** [comment]
I don't see a code path that would do this though (unless we think that the Qt call for sensing the message might not do what it is supposes to)

**Comment by davidebeatrici** [comment]
The public registration system runs in a dedicated thread, right? Could the TCP connection perhaps get stuck indefinitely?

**Comment by Krzmbrzl** [comment]
> The public registration system runs in a dedicated thread, right?

No, it is doing its work asynchronously by means of Qt's event system. It uses a timer to schedule its run in the future and then also does the networking in an event based, asynchronous fashion.

**Comment by davidebeatrici** [comment]
I believe we should switch to a dedicated thread (which would also handle the timer), regardless of this problem.

The event system is useful, but I would avoid interacting with it unless strictly necessary. Especially because we're eventually going to only keep Qt for the UI.

**Comment by StrangePeanut** [comment]
> In cases where you don't see the registration message, do you instead see the `Not registering server as public` log entry? Or is there simply no registration-related message in the logs at all?

The latter as far as I know. `grep -i registr` yielded no results when I ran it. It seems that the issue either occurs or doesn't on server start-up. We run weekly scheduled reboots which might have been triggering the issue on and off.

**Comment by Hartmnt** [comment]
See #6956
