### ISSUE TITLE
Switching to mysql from sqlite

### ISSUE THREAD

**Issue by RinPromise** [mumble-voip/mumble#6492]
### Description

I want to switch to mysql database from sqlite. I have edited the mumble_server.ini file and uncommented these lines with appropriate values:
dbDriver=QMYSQL
database=mumble
dbHost=ip
dbPort=3306
dbUsername=username
dbPassword=password
dbPrefix=mumble-server_

### Steps to reproduce

services:
  mumble-server:
    image: mumblevoip/mumble-server:latest
    container_name: mumble-server
    restart: unless-stopped
    ports:
        - 64738:64738
        - 64738:64738/udp
    environment:
      - MUMBLE_CUSTOM_CONFIG_FILE=/data/mumble_server_config.ini
    volumes:
      - ./mumble_data:/data

### Mumble version

docker:latest

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

With Navicat, can successfully connect to the database.

### Relevant log output

```shell
ServerDB: Failed initialization: Can't connect to MySQL server on 'ip:3306' (110) QMYSQL: Unable to connect
```

**Comment by Krzmbrzl** [comment]
Do you have the qt MySQL driver installed?

**Comment by RinPromise** [comment]
> 您是否安装了qt MySQL驱动程序？

I am using a Docker image, and I am not sure if there is a MySQL driver installed in the image

**Comment by Krzmbrzl** [comment]
I don't think there is. If the driver is not installed, you can't use anything other than SQLite. Note that this will change with #6263 as this removes Qt from the equation (as far as the database is concerned)

**Comment by RinPromise** [comment]
> I don't think there is. If the driver is not installed, you can't use anything other than SQLite. Note that this will change with #6263 as this removes Qt from the equation (as far as the database is concerned)

Great changes! When can we try them out?

**Comment by Krzmbrzl** [comment]
If you feel like compiling yourself, you can try it immediately. The PR should be pretty stable already (at least on Linux). Otherwise, you'll have to wait for Mumble 1.6 for which there is no ETA yet.

**Comment by RinPromise** [comment]
> 如果您想自己编译，可以立即尝试。PR 应该已经非常稳定了（至少在 Linux 上）。否则，您将不得不等待尚未预计到达的 Mumble 1.6。

To compile it myself, which branch should I pull? The master branch?

**Comment by RinPromise** [comment]
> If you feel like compiling yourself, you can try it immediately. The PR should be pretty stable already (at least on Linux). Otherwise, you'll have to wait for Mumble 1.6 for which there is no ETA yet.

To compile it myself, which branch should I pull? The master branch?

**Comment by Hartmnt** [comment]
> To compile it myself, which branch should I pull? The master branch?

https://github.com/Krzmbrzl/mumble/tree/refac-database

**Comment by RinPromise** [comment]
> > To compile it myself, which branch should I pull? The master branch?
> 
> https://github.com/Krzmbrzl/mumble/tree/refac-database

Thanks! What configuration steps are needed to use MySQL after compiling?

**Comment by Krzmbrzl** [comment]
> Thanks! What configuration steps are needed to use MySQL after compiling?

Set the `dbDriver` config option to `MYSQL` and then populate `database`, `dbUsername`, `dbPassword`, `dbHost` and `dbPort` as appropriate for your local DB setup.

Furthermore, beware of
https://github.com/Krzmbrzl/mumble/blob/815bd0661b03bec1131d8d1873dc69775c9539ef/src/tests/TestDatabase/README.md?plain=1#L34-L42

**Comment by RinPromise** [comment]
> > Thanks! What configuration steps are needed to use MySQL after compiling?
> 
> Set the config option to and then populate , , , and as appropriate for your local DB setup.`dbDriver``MYSQL``database``dbUsername``dbPassword``dbHost``dbPort`
> 
> Furthermore, beware of https://github.com/Krzmbrzl/mumble/blob/815bd0661b03bec1131d8d1873dc69775c9539ef/src/tests/TestDatabase/README.md?plain=1#L34-L42

The dbPort parameter seems ineffective; no matter what value it is set to, it still defaults to 3306.

**Comment by RinPromise** [comment]
> > Thanks! What configuration steps are needed to use MySQL after compiling?
> 
> Set the `dbDriver` config option to `MYSQL` and then populate `database`, `dbUsername`, `dbPassword`, `dbHost` and `dbPort` as appropriate for your local DB setup.
> 
> Furthermore, beware of https://github.com/Krzmbrzl/mumble/blob/815bd0661b03bec1131d8d1873dc69775c9539ef/src/tests/TestDatabase/README.md?plain=1#L34-L42

[ERROR]: Can't connect to MySQL server on 'ip:3306' (110)
No matter how I change the dbPort, the error persists unchanged.

**Comment by Krzmbrzl** [comment]
@RinPromise good catch! That's indeed a bug in the current implementation. My most recent commit should address this (you might have to force-pull as I have been doing some force pushing to my branch).
