### ISSUE TITLE
No recent stable version (1.5.x) available for Linux Servers!

### ISSUE THREAD

**Issue by Fraggersmash** [mumble-voip/mumble#6493]
### Description

Please fix this asap. I have been waiting ages for you to fix the 1.5.x built to a point it is a stable version. There are features in it we don't get from other voip software. So please fix this asap!

### Steps to reproduce

Try to install mumble-server on a linux server and see that it is 1.3.x

### Mumble version

1.5

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
If you are installing from a package repository, then you get the version that the respective maintainer put into it. We don't control any of that.
However, you could also use our official Docker image: https://github.com/mumble-voip/mumble-docker

**Comment by hbeni** [comment]
Debian sid has 1.5.517: https://packages.debian.org/sid/mumble-server
