### ISSUE TITLE
If the program name is changed to Chinese, the program cannot be run.

### ISSUE THREAD

**Issue by rainbowsource** [mumble-voip/mumble#6505]
### Description

There is no error message and double clicking the program does not respond.

### Steps to reproduce

Change the file name of mumble.exe to "啊.exe". ("啊" means ah, just a test).

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

My operating system is Windows 11 23H2 version. But I tested it on a virtual machine and Windows 10 did not have this problem.

### Relevant log output

```shell
There is no error output.
```

### Screenshots

No.

**Comment by rainbowsource** [comment]
Very interesting question, even version 1.4 released in 2022 has the same problem. The same as my local Qt compilation environment is that we all use static compilation.

**Comment by Krzmbrzl** [comment]
> I'm beginning to suspect this is a Windows OS issue.

Yeah, that's my initial suspicion as well. Does this kind of renaming work for other programs on your PC?

**Comment by rainbowsource** [comment]
@Krzmbrzl Hello, thanks for your reply. I looked into it carefully and found that this problem can be traced back to 2015, when I used some programs statically compiled with Qt 4. My programs include Qt 4, 5, 6 and VS 2010 ~ VS 2022. So I am almost sure that this is a problem with Windows 11.

But... what's interesting is that MFC programs and Sciter programs do not have these problems; console programs compiled with Qt do not have this problem either.

Interesting Microsoft... :( or interesting Qt... :)

**Comment by davidebeatrici** [comment]
What happens if you enable UTF-8 support in Windows?

![](https://github.com/mumble-voip/mumble/assets/5897523/4b22a99d-6fa6-43e7-bb7e-7e00a8a2eb20)

**Comment by Krzmbrzl** [comment]
Alright, thanks for digging into this. I'll close this issue then as there is nothing we can do about this, as far as I am aware.

**Comment by rainbowsource** [comment]
@Krzmbrzl Holy Shift, the problem is solved using your method. Modifying the Region settings can perfectly solve this problem. Thank you very much, you solved a problem that has been bothering me for a long time.
