### ISSUE TITLE
Plugin interface: Updater not called?

### ISSUE THREAD

**Issue by hbeni** [mumble-voip/mumble#6506]
### The issue

Hi,
just a question. I currently try to enhance my plugins update procedure but cannot test it.
It seems, the plugins `mumble_hasUpdate()` is never called. I see this because I miss even basic log messages from my code, that should in any case be printed.

Is there any conditions or constraints when mumble looks if there are plugin updates available?

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Additional information

Plugin updater code is here: https://github.com/hbeni/fgcom-mumble/blob/master/client/mumble-plugin/lib/updater.cpp

I can verify the symbol is compiled into the binary:
```
mumble-plugin$ nm -gDC fgcom-mumble.so |grep mumble_
00000000000a96e3 T mumble_deactivateFeatures
00000000000a9529 T mumble_getAPIVersion
00000000000a95aa T mumble_getAuthor
00000000000a95ca T mumble_getDescription
00000000000a95c4 T mumble_getFeatures
00000000000a950f T mumble_getName
00000000000aaafc T mumble_getUpdateDownloadURL
00000000000a9587 T mumble_getVersion
00000000000b72a7 T mumble_hasUpdate
00000000000b538e T mumble_init
00000000000aed2c T mumble_onAudioSourceFetched
00000000000b1a08 T mumble_onChannelEntered
00000000000b1d63 T mumble_onChannelExited
00000000000a9c89 T mumble_onReceiveData
00000000000b5420 T mumble_onServerConnected
00000000000b1987 T mumble_onServerDisconnected
00000000000b549c T mumble_onServerSynchronized
00000000000ae105 T mumble_onUserTalkingStateChanged
00000000000a9560 T mumble_registerAPIFunctions
00000000000a954c T mumble_releaseResource
00000000000aa009 T mumble_setMumbleInfo
00000000000b1818 T mumble_shutdown
00000000000aaae9 T mumble_onAudioInput(short*, unsigned int, unsigned short, bool)
``

**Comment by hbeni** [comment]
Its the official debian binary, so I assume a regular build.

**Comment by hbeni** [comment]
Is there a way to trigger the call?

**Comment by hbeni** [comment]
@Krzmbrzl Is there any way I can make the client call the update function?

**Comment by Krzmbrzl** [comment]
> Its the official debian binary, so I assume a regular build.

Okay. Do you have update checking enabled in the settings? Do you even have a checkbox for that? There is an option for distributors to disable the update checks which historically is done on distros such as Debian.

> Is there a way to trigger the call?

No

**Comment by hbeni** [comment]
Thank you very much!!!
That was indeed the case:

![grafik](https://github.com/user-attachments/assets/3be6c23e-1c85-466b-bcd7-eec4c2857395)

After activating, i do see expected log messages!
```
FGCom [2024-07-17 16:03:43.072]: [DBG] Version check: latest='1.0.3'; newer=0
FGCom [2024-07-17 16:03:43.072]: [UPDATER] Version is up to date.
```

Thank you very much!

**Comment by hbeni** [comment]
(made a bug report at debian, asking to enable plugin updating by default)
