### ISSUE TITLE
Server no longer responds to USR1 signal to reload certificates

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#6513]
### Description

Recently noticed that the server kept using the old certificate. I manually issued `pkill -USR1 -xn mumble-server` but to no avail.

Relevant: https://github.com/mumble-voip/mumble/pull/2850

### Steps to reproduce

1. Run mumble-server with certificate
2. Update the certificate
3. Send USR1 signal to mumble-server
4. mumble-server ignores the signal, no events are logged, certificate remains unchanged

### Mumble version

1.5.634 official Docker image

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
Mh ``kill -n 10 <pid>`` works fine for me, but ``pkill -USR1 -xn mumble-server`` does not...

**Comment by Hartmnt** [comment]
The code that handles this has also not been touched since its introduction. I assume this is some behavior change of ``pkill``

**Comment by StrangePeanut** [comment]
@Hartmnt oh that's interesting. I will make the necessary changes. Thanks so much!
