### ISSUE TITLE
Echo Cancellation

### ISSUE THREAD

**Issue by FutabaWasuke** [mumble-voip/mumble#6514]
### Context

Occasionally, we encounter users in voice channels who utilize speakers and microphones instead of headsets. Even when they employ push-to-talk, their setups can inadvertently rebroadcast other users' voices back into Mumble. This situation can be quite disruptive to communication within the channel.

### Description

I would like to propose the implementation of an echo cancellation feature. Ideally, this feature would effectively eliminate echo in audio input, preventing users from hearing their own voices reflected through other participants' audio streams. As an additional consideration, if environmental noise reduction could be incorporated, it would be a wonderful bonus.

### Mumble component

Client

### OS-specific?

No

### Additional information

Mumble's greatest strength lies in its excellent audio quality. However, I've noticed that its noise reduction and echo prevention capabilities seem to lag behind those of Discord, WeChat, and QQ voice calls. While I'm not familiar with the technical aspects of how these platforms achieve their results, as a user, I can discern a noticeable difference.

**Comment by Krzmbrzl** [comment]
We already implement echo cancellation and noise cancellation. As far as echo cancellation goes, I am not aware of another library that implements this functionality that we could use and without a concrete suggestion I don't think the issue at hand is actionable. 

As far as noise cancellation goes, there is #6299

**Comment by Hartmnt** [comment]
In case here is something lost in translation: You can enable both echo cancellation as well as noise suppression in the Mumble Audio Output settings. The person which utilizes speakers would need to activate echo cancellation on their end.

**Comment by FutabaWasuke** [comment]
> In case here is something lost in translation: You can enable both echo cancellation as well as noise suppression in the Mumble Audio Output settings. The person which utilizes speakers would need to activate echo cancellation on their end.

Thanks for the replies. I did see that the Mumble has echo cancellation, but unfortunately I don't think there really is "echo cancellation".

The user with the audio they had both Speex+RNNoise on, but I could still clearly hear any word I said in his audio.

**Comment by Hartmnt** [comment]
RNNoise does not cancel echo. Has the user enabled echo cancellation via this combobo?
![mumble](https://github.com/user-attachments/assets/d01524dd-c2dd-4c00-be30-91614b289802)

**Comment by FutabaWasuke** [comment]
> RNNoise does not cancel echo. Has the user enabled echo cancellation via this combobo? ![mumble](https://private-user-images.githubusercontent.com/1348773/350873527-d01524dd-c2dd-4c00-be30-91614b289802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzM5MjEsIm5iZiI6MTcyMTYzMzYyMSwicGF0aCI6Ii8xMzQ4NzczLzM1MDg3MzUyNy1kMDE1MjRkZC1jMmRkLTRjMDAtYmUzMC05MTYxNGIyODk4MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDczMzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJjM2E5MWU1OWUyNjkzY2UwNTIwYzA0NDdkOTZjMmE0NmRiYjg2MWU4MWRiMGU0ZWM5ODRiMDdlMzA0Njc2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SEFPHc5KO5LHdZyvREKWLF8GYOSRvz-DT8_G32zxRoY)

Yes, speex is on. this user and I have tried various combinations of settings, but nothing works. I recorded a video and you can check this out if you want (dark mode Mumble is my local): [youtube](https://youtu.be/v9YZtVH_vKQ )

**Comment by Hartmnt** [comment]
@FutabaWasuke Alright, would you be able to open the [developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) on the system of the affected user and post the log. That way we can see whether any errors occur when setting up the echo cancellation.

**Comment by Hartmnt** [comment]
Another question: Does the affected user have an USB microphone or a 3.5mm audio jack microphone?

**Comment by Krzmbrzl** [comment]
@Hartmnt I don't think there is a need to reopen this. There are certain configurations in which echo cancellation just doesn't work. On my machine for instance it never worked. I guess OP is seeing a similar issue.

What we would really need is a different library that implements this but the only other one that I know of is WebRTC from which we would have to tear the echo cancellation part which is not future proof at all. So I think my original comment still applies: without concrete suggestions to alternatives that we could implement, there is nothing we can do about this.

**Comment by Hartmnt** [comment]
@Krzmbrzl I feel like it is worth a try to see if there is anything technically wrong. If there is nothing we can do, I agree.

I have had an as of yet unreproducible bug with the echo cancellation where the echo audio stream would randomly switch to my microphone resulting in my voice being cancelled. This was only visible in ``pavucontrol``. I think even though echo cancellation might be flaky as is, it would be nice to sanity check these kinds of bugs to make it a little more usable.

**Comment by FutabaWasuke** [comment]
> @FutabaWasuke Alright, would you be able to open the [developer console](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) on the system of the affected user and post the log. That way we can see whether any errors occur when setting up the echo cancellation.

`<X>2024-07-24 13:13:52.161 Loading settings from "C:/Users/diwen/AppData/Local/Mumble/Mumble/mumble_settings.json"
<W>2024-07-24 13:13:52.181 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<W>2024-07-24 13:13:52.182 Theme: "Mumble"
<W>2024-07-24 13:13:52.182 Style: "Lite"
<W>2024-07-24 13:13:52.182 --> qss: ":themes/Default/Lite.qss"
<W>2024-07-24 13:13:52.182 Locale is "zh_CN" (System: "zh_CN")
<W>2024-07-24 13:13:52.367 Database SQLite: "3.43.2"
<W>2024-07-24 13:13:52.396 Updating application palette
<W>2024-07-24 13:13:52.775 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2024-07-24 13:13:52.775 QMetaObject::connectSlotsByName: No matching signal for on_muteCuePopup_triggered()
<W>2024-07-24 13:13:53.489 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:13:53.489 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:13:52.405 XboxInput: using XInput DLL 'XInput1_4.dll'
<W>2024-07-24 13:13:52.405 XboxInput: using XInputGetStateEx() as querying function.
<W>2024-07-24 13:13:53.491 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:13:53.491 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:13:53.496 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:13:53.496 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:13:53.496 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:13:53.496 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:13:53.498 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:13:53.500 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:13:53.500 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:13:53.504 WASAPIInput: Echo Stream format 1
<W>2024-07-24 13:13:53.504 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2024-07-24 13:13:53.527 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:13:53.527 AudioInput: ECHO CANCELLER ACTIVE
<W>2024-07-24 13:13:54.457 Database SQLite: "3.43.2"
<W>2024-07-24 13:13:54.457 OpenSSL Support: 1 (OpenSSL 3.2.0 23 Nov 2023)
<W>2024-07-24 13:13:54.462 SSL: CA certificate filter applied. Filtered size: 92, original size: 92
<W>2024-07-24 13:13:54.462 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2024-07-24 13:13:54.462 ServerHandler: Failed to load qWave.dll, no QoS available
<W>2024-07-24 13:16:52.059   OpenType support missing for "SimSun", script 11
<W>2024-07-24 13:16:52.059   OpenType support missing for "Arial", script 11
<W>2024-07-24 13:16:52.061   OpenType support missing for "MS UI Gothic", script 11
<W>2024-07-24 13:16:52.069   OpenType support missing for "SimSun", script 20
<W>2024-07-24 13:16:52.069   OpenType support missing for "Arial", script 20
<W>2024-07-24 13:16:52.069   OpenType support missing for "MS UI Gothic", script 20
<W>2024-07-24 13:16:52.070   OpenType support missing for "SimSun", script 17
<W>2024-07-24 13:16:52.070   OpenType support missing for "Arial", script 17
<W>2024-07-24 13:16:52.070   OpenType support missing for "MS UI Gothic", script 17
<W>2024-07-24 13:16:52.100   OpenType support missing for "Segoe UI", script 20
<W>2024-07-24 13:16:52.100   OpenType support missing for "Microsoft YaHei UI", script 20
<W>2024-07-24 13:16:52.100   OpenType support missing for "Arial", script 20
<W>2024-07-24 13:16:52.100   OpenType support missing for "SimSun", script 20
<W>2024-07-24 13:16:52.100   OpenType support missing for "MS UI Gothic", script 20
<W>2024-07-24 13:17:56.839 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:17:56.839 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:17:56.840 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:17:56.840 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:17:56.842 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:17:56.842 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:17:56.844 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:17:56.844 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:17:56.844 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:17:56.844 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:17:56.845 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:17:56.847 WASAPIInput: Echo Stream format 1
<W>2024-07-24 13:17:56.847 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2024-07-24 13:17:56.868 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:17:56.868 AudioInput: ECHO CANCELLER ACTIVE
<W>2024-07-24 13:18:04.208 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:18:04.208 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:18:04.210 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:18:04.210 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:18:04.213 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:18:04.213 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:18:04.215 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:18:04.215 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:18:04.215 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:18:04.215 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:18:04.215 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:18:04.217 WASAPIInput: Echo Stream format 1
<W>2024-07-24 13:18:04.217 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2024-07-24 13:18:04.238 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:18:04.238 AudioInput: ECHO CANCELLER ACTIVE
<W>2024-07-24 13:18:09.228 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:18:09.229 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:18:09.230 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:18:09.230 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:18:09.232 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:18:09.233 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:18:09.236 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:18:09.236 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:18:09.236 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:18:09.236 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:18:09.236 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:18:09.238 WASAPIInput: Echo Stream format 1
<W>2024-07-24 13:18:09.238 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2024-07-24 13:18:09.257 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:18:09.257 AudioInput: ECHO CANCELLER ACTIVE
<W>2024-07-24 13:18:25.548 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:18:25.548 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:18:25.549 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:18:25.550 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:18:25.552 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:18:25.552 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:18:25.552 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2024-07-24 13:18:25.557 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:18:25.557 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:18:25.557 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:18:25.557 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:18:25.558 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:18:25.562 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:18:29.698 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:18:29.698 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:18:29.699 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:18:29.699 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:18:29.701 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:18:29.701 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:18:29.702 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:18:29.702 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:18:29.702 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:18:29.702 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:18:29.703 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:18:29.704 WASAPIInput: Echo Stream format 1
<W>2024-07-24 13:18:29.704 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2024-07-24 13:18:29.727 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:18:29.727 AudioInput: ECHO CANCELLER ACTIVE
<W>2024-07-24 13:18:41.728 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:18:41.729 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:18:41.730 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:18:41.730 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:18:41.732 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:18:41.732 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:18:41.735 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:18:41.735 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:18:41.735 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:18:41.735 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:18:41.735 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:18:41.736 WASAPIInput: Echo Stream format 1
<W>2024-07-24 13:18:41.736 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2024-07-24 13:18:41.757 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:18:41.757 AudioInput: ECHO CANCELLER ACTIVE
<W>2024-07-24 13:18:43.919 AudioInput: Opus encoder set for high quality speech
<W>2024-07-24 13:18:43.919 AudioInput: 46181 bits/s, 48000 hz, 480 sample
<W>2024-07-24 13:18:43.921 WASAPIInput: Latencies 100000 30000 => 100000
<W>2024-07-24 13:18:43.921 WASAPIOutput: Latencies 100000 26667 => 100000
<W>2024-07-24 13:18:43.923 WASAPIInput: Mic Stream format 1
<W>2024-07-24 13:18:43.923 WASAPIInput: Stream Latency 0 (1056)
<W>2024-07-24 13:18:43.925 WASAPIOutput: Output stream format 1
<W>2024-07-24 13:18:43.925 WASAPIOutput: Stream Latency 0 (2880)
<W>2024-07-24 13:18:43.925 WASAPIOutput: Periods 10000us 2666us (latency 0us)
<W>2024-07-24 13:18:43.925 WASAPIOutput: Buffer is 60000us (5)
<W>2024-07-24 13:18:43.925 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2024-07-24 13:18:43.926 WASAPIInput: Echo Stream format 1
<W>2024-07-24 13:18:43.926 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 2 channel 48000 hz echo
<W>2024-07-24 13:18:43.947 AudioInput: Using ReNameNoise and Speex as noise canceller
<W>2024-07-24 13:18:43.947 AudioInput: ECHO CANCELLER ACTIVE`

**Comment by FutabaWasuke** [comment]
> Another question: Does the affected user have an USB microphone or a 3.5mm audio jack microphone?

He's using a USB microphone.

Addendum: Although SteelSeries Sonar is installed, there is the same echo when using the physical microphone input and the physical speaker output directly

**Comment by Hartmnt** [comment]
@FutabaWasuke Well, from the log it looks like everything is initializing fine. And using an USB microphone means the audio signal is not leaking in electrically.

That sadly means there is no way to really improve this right now. There are open issues for using the Windows native echo cancellation #4697 and for audio output being picked up as input in general #5577
But I would not expect any work or improvements on this until Mumble is switching to its own cross-platform audio abstraction layer (#5408)

**Comment by FutabaWasuke** [comment]
> @FutabaWasuke Well, from the log it looks like everything is initializing fine. And using an USB microphone means the audio signal is not leaking in electrically.
> 
> That sadly means there is no way to really improve this right now. There are open issues for using the Windows native echo cancellation #4697 and for audio output being picked up as input in general #5577 But I would not expect any work or improvements on this until Mumble is switching to its own cross-platform audio abstraction layer (#5408)

Thank you for your willingness to help take a look at this issue, unfortunately it can't be solved for the time being.

We still appreciate your dedication to this project and look forward to Mumble working on it one day. 🙇‍♂️
