### ISSUE TITLE
Server install issue

### ISSUE THREAD

**Issue by mrattray1315** [mumble-voip/mumble#6519]
### The issue

Get an error on install.  Haven't figured away around it despite reboot, re-install, etc.  Any ideas

![Screenshot 2024-07-25 094839](https://github.com/user-attachments/assets/174c99cc-e4f5-47d8-be9f-dce72ceed823)
![Screenshot 2024-07-25 094839](https://github.com/user-attachments/assets/58e53922-c674-4341-9cdb-121b58afb3f0)

### Mumble version

1.5.634

### Mumble component

Server

### OS

Windows

**Comment by Krzmbrzl** [comment]
How exactly did you do the installation and where did you get the installer from?

And where did you install Mumble to?

**Comment by mrattray1315** [comment]
Opened the server link below into downloads on Windows 10.



Got server setup wizard below.  Click finish at end of wizard


Then had to go to program files to open server


Run the EXE as administrator, nothing seems to happen and then I get this

Find murmur icon on secondary task bar.  Right click and says it is running.  Left click and get below


Can't figure out where it is running or how to configure anything


Went to client computer and setup but even though it shows connected to server I can find no server box to open and configure anything.  I need the server to draw from usb audio codec.  Attachment is from the client computer.  Everything else is on server pc






I can see indication of notifications but no way to access anything on server pc.  Not sure if that is impacted by error message





That's about it.  Would love to get it working.



    On Thursday, July 25, 2024 at 12:04:58 PM PDT, Robert Adam ***@***.***> wrote:  
 
 


How exactly did you do the installation and where did you get the installer from?

And where did you install Mumble to?

**Comment by mrattray1315** [comment]
every time I try to open server app that error pops up

    On Thursday, July 25, 2024 at 08:06:59 PM PDT, maurice rattray ***@***.***> wrote:  
 
  
Opened the server link below into downloads on Windows 10.



Got server setup wizard below.  Click finish at end of wizard


Then had to go to program files to open server


Run the EXE as administrator, nothing seems to happen and then I get this

Find murmur icon on secondary task bar.  Right click and says it is running.  Left click and get below


Can't figure out where it is running or how to configure anything


Went to client computer and setup but even though it shows connected to server I can find no server box to open and configure anything.  I need the server to draw from usb audio codec.  Attachment is from the client computer.  Everything else is on server pc






I can see indication of notifications but no way to access anything on server pc.  Not sure if that is impacted by error message





That's about it.  Would love to get it working.



    On Thursday, July 25, 2024 at 12:04:58 PM PDT, Robert Adam ***@***.***> wrote:  
 
 


How exactly did you do the installation and where did you get the installer from?

And where did you install Mumble to?

**Comment by Krzmbrzl** [comment]
Where did you get the installer from and into which directory did you install the server?

**Comment by mrattray1315** [comment]
If the info provided doesn't answer your questions, can we do a screen share?

    On Friday, July 26, 2024 at 07:29:17 AM PDT, maurice rattray ***@***.***> wrote:  
 
  
Did you not get this?Message ID: ***@***.***>

**Comment by Krzmbrzl** [comment]
The info I am asking about has not been provided. So if you could please just explicitly provide the requested information (maybe directly on GitHub to not depend on that Email feature) I might be able to help you.

**Comment by mrattray1315** [comment]
Thu, Jul 25 at 8:06 PM

Opened the server link below into downloads on Windows 10.

see image1
![image1](https://github.com/user-attachments/assets/080e39bc-d318-4f70-bcf2-9a2e12915e38)


Got server setup wizard below.  Click finish at end of wizard

see image 2
![image2](https://github.com/user-attachments/assets/bb57e4b9-0152-4be1-846b-7b21799f8aeb)


Then had to go to program files to open server

see image 3
![image3](https://github.com/user-attachments/assets/3fde1a8d-c102-4ad9-a984-fd01d891d06b)


Run the EXE as administrator, nothing seems to happen and then I get this

see image4
![image4](https://github.com/user-attachments/assets/fac3fdf5-a3be-4a9c-ba2b-f31ad226b108)


Find murmur icon on secondary task bar.  Right click and says it is running.  Left click and get below
see image 5
![image5](https://github.com/user-attachments/assets/6005fa7c-79c5-46f1-9ed8-08f4fd349dc2)



Can't figure out where it is running or how to configure anything



Went to client computer and setup but even though it shows connected to server I can find no server box to open and configure anything.  I need the server to draw from usb audio codec.  Attachment is from the client computer.  Everything else is on server pc

see attached murmur.docx
[mumble.docx](https://github.com/user-attachments/files/16395641/mumble.docx)




I can see indication of notifications but no way to access anything on server pc.  Not sure if that is impacted by error message


see image 6
![image6](https://github.com/user-attachments/assets/a06f733d-1a0c-4842-9f2a-0b4bfe650a55)




That's about it.  Would love to get it working.


Hope these images get thru.

**Comment by Krzmbrzl** [comment]
Thanks. Now I have a good idea of what is going on. My guess is that due to the database being located under the program files directory, the server process lacks permission to write to it (hence "read-only").

In the server console you can see that the server reports that it didn't find an INI file in the appdata directory. If you create the INI file at that location, you can explicitly configure a path at which the server shall create the database. In fact, I believe simply having that file is enough to make the server create the database next to it. That should resolve the read-only issue.

As for configuring the server, there is some stuff that has to be done via the INI but things like creating channels are done from a client with admin privileges (for a new server login with the SuperUser account). The server executable itself doesn't have any support for configuration. It is only a daemon that runs in the background.

**Comment by mrattray1315** [comment]
So this is the program directory with the server.  Not sure where to find ini file or appdata directory though and then how to configure path.  The default download put this in the program directory.  Should I just reinstall and  put elsewhere?

![Screenshot 2024-07-27 012010](https://github.com/user-attachments/assets/5e6f88fd-abea-4d11-bdd4-4eb2cec78975)

On the client side I can find the server drop down but don't know how to access my superuser account info.  How would I find this account info or establish it anew.  Watched a couple youtube video but the didn't help.  Under the mumble file there is a server folder the following in it.
![Screenshot 2024-07-27 015356](https://github.com/user-attachments/assets/77f73f00-d0c2-4f0c-b9d2-1b04389e03d4)


So I could use some additional assistance to get this resolved.  I am not that skilled in what appears to be needed

**Comment by mrattray1315** [comment]
Reinstalled server to desktop and don't get error at moment.  Can't figure out how to get Super-user on client.  Likely don't have a copy of the original credentials if that is needed.  I removed, rebooted and re-installed on client pc and everything seemed the same.  Not sure how to establish the superuser at this time

**Comment by mrattray1315** [comment]
Latest log file

![Screenshot 2024-07-27 095801](https://github.com/user-attachments/assets/353a454a-4b82-458b-aa4b-b4828a787c67)

**Comment by Krzmbrzl** [comment]
No, don't install to a different location. Certain things might not work anymore in that case. You should only create an INI file at the location  that th server log has stated (see your screenshot).

**Comment by mrattray1315** [comment]
At the moment it is already done   My problem is figuring out how to set up super user account. I tried password from server log that said for super user but it didn’t work. How do I get a new password Sent from my iPhoneOn Jul 27, 2024, at 11:57 PM, Robert Adam ***@***.***> wrote:﻿
No, don't install to a different location. Certain things might not work anymore in that case. You should only create an INI file at the location  that th server log has stated (see your screenshot).

**Comment by mrattray1315** [comment]
Also I have no idea where to find ini file and open it.  If I try to look in program app "mumble" it just runs app.  

    On Sunday, July 28, 2024 at 07:00:36 AM PDT, maurice rattray ***@***.***> wrote:  
 
 At the moment it is already done   My problem is figuring out how to set up super user account. I tried password from server log that said for super user but it didn’t work. How do I get a new password 

Sent from my iPhone

On Jul 27, 2024, at 11:57 PM, Robert Adam ***@***.***> wrote:



﻿


No, don't install to a different location. Certain things might not work anymore in that case. You should only create an INI file at the location that th server log has stated (see your screenshot).

**Comment by mrattray1315** [comment]
This is what i get when trying to find  appdata location. 

![Screenshot 2024-07-28 071856](https://github.com/user-attachments/assets/6e971e76-1bd2-4810-bd21-ee5a3327e2b5)

**Comment by Krzmbrzl** [comment]
> How do I get a new password

You can set one via the server's CLI

**Comment by Krzmbrzl** [comment]
> Also I have no idea where to find ini file and open it.

Just use the path the server log prints. You can edit INI files with any text editor.

**Comment by mrattray1315** [comment]
Found appdata with hidden view.  Now just need help finding ini file and resetting superuser password.  Followed the instructions found on the following and think I got ini installed.  Now to figure out how to access superuser

https://meshnet.nordvpn.com/how-to/joint-projects/mumble-voice-chat-server

**Comment by mrattray1315** [comment]
lost on how to use server's CLI to setup superuser password.  Further assistance appreciated

**Comment by Krzmbrzl** [comment]
Start the serve via the command line and inspect the output of the `--help` command. What you want to use is the `-supw` option

**Comment by mrattray1315** [comment]
I keep getting directory invalid.  Have tried several options but the C:\Users\mratt> starting point may be problem.  Since it is in the C: it seems like I need to get rid of the :\Users\mratt but not sure how or if this is what I want

C:\Users\mratt>cd C:\Program Files\Mumble\server\mumble-server.exe

**Comment by mrattray1315** [comment]
got to the correct location C:\Program Files\Mumble\server>  .  Working on next steps to start and inspect output.  Not within my scope of knowledge but slowly proceeding.

**Comment by mrattray1315** [comment]
Started server with cmd line.  Need further assistance on the next step "inspect the output of the --help command. What you want to use is the -supw option" as entering help in cmd doesn't do anything.  Getting closer but not here yet.  Want to establish the server to draw from USB codec and informed that I had to do so with superruse account.

Start the serve via the command line and inspect the output of the --help command. What you want to use is the -supw option

**Comment by Krzmbrzl** [comment]
> Started server with cmd line. Need further assistance on the next step "inspect the output of the --help command. What you want to use is the -supw option" as entering help in cmd doesn't do anything.

Yes - you shouldn't simply run the server from the command line, you should pass it the `--help` argument to print the help text. Then check the description of the `-supw` option and use accordingly.

**Comment by mrattray1315** [comment]
Thanks,  here is what I am inputting but see no results or output.  Just takes me back to original prompt.  Sorry but not my bailiwick

C:\Program Files\Mumble\server>mumble-server.exe --help

C:\Program Files\Mumble\server>

**Comment by mrattray1315** [comment]
Also I can't get into wiki guide.  Keep getting this message  "Sorry! This site is experiencing technical difficulties."  Is this everywhere?

**Comment by Krzmbrzl** [comment]
On Windows the server may actually create a popup with the help message.

The wiki seems to be down (again) - @davidebeatrici

**Comment by mrattray1315** [comment]
Unfortunately I can find nothing after entering anywhere.  Don't see any pop up.  I do have access to a mumble server properties that started appearing.  It poped up on an icon on the taskbar.  The icon has now dissappeared and I can't get it back.  Only the other icon attached whickh doesn't do anything
![Screenshot 2024-07-28 133839](https://github.com/user-attachments/assets/36603a8c-4eca-4788-9645-86cd4140bbd4)
![image](https://github.com/user-attachments/assets/0514cd08-06e3-4dd4-b943-cc972681a2e3)
![Screenshot 2024-07-28 140657](https://github.com/user-attachments/assets/5417e2d0-1472-4504-980a-7781819bde61)

Nothing with this is easy. Darn

**Comment by Krzmbrzl** [comment]
> mumble-server.exe -supw MyPassword
