### ISSUE TITLE
vcpkg ice build failed

### ISSUE THREAD

**Issue by zhiyan114** [mumble-voip/mumble#6520]
### Description

When attempting to build ice file for mumble, the following error occured:
```
error: File does not have the expected hash:
url: https://github.com/mumble-voip/ice/archive/3.7.tar.gz
File: F:\_toolchain\vcpkg\downloads\mumble-voip-ice-3-d91d8845.7.tar.gz.33168.part
Expected hash: d91d88459b4bca14cf4a8addf642246a0cdd5b7bf740f916d3eead2f7d7e0b52bc3a2b8af2f024e63d05baa0b258f5a5676bc205f379387fb233dd6b9bb81228
Actual hash: 205b3ce0fa0ecc157944dd4dae5d9c68c54f07e7b0b8012beea83d83870bb7df8c21f930b6239b6c0dd49fb758ce9a58b1e2670d0de14349a582c58f73a2fafa
```

Attempting to override the checksum will result in `F:\_toolchain\vcpkg\buildtrees\zeroc-ice-mumble\x64-windows-static-md-dbg\generated\Ice/Version.h(39): fatal error C1189: #error:  Ice patch level mismatch!`

### Steps to reproduce

1. Go to mumble dir
2. Copy `zeroc-ice-mumble`  dir from the port dir to vcpkg's port dir
3.  Run `vcpkg install zeroc-ice-mumble --triplet x64-windows-static-md`

### Mumble version

b75fe546ab6e5f32204e20df7ee3ceb8ce70262c

### Mumble component

Both

### OS

Windows

### Reproducible?

Yes

**Comment by ppfeufer** [comment]
> File: F:\_toolchain\vcpkg\downloads\mumble-voip-ice-3-d91d8845.7.tar.gz.33168.part

That looks like an unfinished download …

**Comment by zhiyan114** [comment]
> > File: F:_toolchain\vcpkg\downloads\mumble-voip-ice-3-d91d8845.7.tar.gz.33168.part
> 
> That looks like an unfinished download …

Welp, it sounds like a vcpkg issue then. Is there a way to supply the source `tar.gz` manually?

**Comment by ppfeufer** [comment]
I don't know what `vcpkg` is or does, but I'd say, wait until the file download is completed and run the whole show then …

**Comment by zhiyan114** [comment]
> I don't know what `vcpkg` is or does, but I'd say, wait until the file download is completed and run the whole show then …

Unfortunately, the download process is automated, so `vcpkg` essentially just stops the download there. I'm not very familiar with vcpkg, so I wouldn't know if there any flag that can be used to fix this.

**Comment by zhiyan114** [comment]
> I recommend using our vcpkg fork: https://github.com/mumble-voip/vcpkg

Hi, using the forked version, I'm still getting a similar error:
```
DEBUG] Trying to hash F:\_toolchain\mumble_vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.33068.part
[DEBUG] F:\_toolchain\mumble_vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.33068.part has hash a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
error: Missing boostorg-core-boost-1.85.0.tar.gz and downloads are blocked by x-block-origin.
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: F:\_toolchain\mumble_vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.33068.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
```

**Comment by ppfeufer** [comment]
> error: Missing boostorg-core-boost-1.85.0.tar.gz and downloads are blocked by x-block-origin.

Look like something in your network is blocking the downloads, which would explain the `.part` files. If I had a guess, these files are 0 bytes?

**Comment by zhiyan114** [comment]
> > error: Missing boostorg-core-boost-1.85.0.tar.gz and downloads are blocked by x-block-origin.
> 
> Looks like something in your network is blocking the downloads, which would explain the `.part` files. If I had to guess, these files are 0 bytes?

 I ran the checksum on the supposing "corrupted" file and confirm that the checksum matches the "actual hash". So it looks like either vcpkg somehow failed to compute the hash correctly or there's some kind of issue with boost library that prevented the download to be completed correctly (see https://github.com/microsoft/vcpkg/issues/40033).

**Comment by Krzmbrzl** [comment]
Remove all previously downloaded files and get rid if whatever is blocking downloads in your network

**Comment by ppfeufer** [comment]
> I ran the checksum on the supposing "corrupted" file and confirm that the checksum matches the "actual hash".

It needs to match the "Expected hash".

**Comment by zhiyan114** [comment]
> Remove all previously downloaded files and get rid if whatever is blocking downloads in your network

Turns out, Some of the packages had out-of-date checksum values, and replacing it fixes the issue.

**Comment by Sardonyxtechsupport** [comment]
how to solve this issue ,,same issue i got..kindly help me to resolve this issue..
i upgrade HASH SHA512 by below script

$directory = "C:\Users\Administrator\vcpkg"
$outputFile = "C:\Users\Administrator\Desktop\hashes_sha512.txt"

Get-ChildItem -Path $directory -Recurse -File | ForEach-Object {
    $hash = Get-FileHash -Path $_.FullName -Algorithm SHA512
    "$($hash.Hash)  $($_.FullName)"
} | Out-File -FilePath $outputFile


all files updated

but while i execute .\get_mumble_dependencies.ps1
Same error coming
![ERR 1](https://github.com/user-attachments/assets/10fb66e3-93e7-416d-9a67-139da34a424b)
![ERR 2](https://github.com/user-attachments/assets/2616ff4b-1aec-41d5-8a41-3b9deb38c568)

**Comment by davidebeatrici** [comment]
@Sardonyxtechsupport Please continue in the issue you created (#6546).
