### ISSUE TITLE
No plugins in plugins tab

### ISSUE THREAD

**Issue by Artex154** [mumble-voip/mumble#6523]
### Description

I have no plugins in my plugins tab, reload doesn't work

### Steps to reproduce

1. Install Mumble 1.4.287;
2. Go in Settings -> Plugins Tab;

### Mumble version

1.4.287

### Mumble component

Client

### OS

Linux

### Reproducible?

Haven't tried

### Additional information

I'm on Fedora 40 flatpak and RPM doesn't work.

### Screenshots

![image](https://github.com/user-attachments/assets/225f4985-58db-4c8d-8ad9-87de424fa564)

**Comment by Hartmnt** [comment]
The Flatpak sandbox prohibits all of the fun shared memory stuff. Because of that you pretty much can not use any plugins (for positional audio) anyway.

**Comment by Artex154** [comment]
> The Flatpak sandbox prohibits all of the fun shared memory stuff. Because of that you pretty much can not use any plugins (for positional audio) anyway.

So plugins are just unusable ?

**Comment by Krzmbrzl** [comment]
When using the Flatpak version in its current state, yes

**Comment by Artex154** [comment]
> When using the Flatpak version in its current state, yes

Any other ways ? In the fedora shop there's only flatpak and RPM. Both doesn't work.

**Comment by Hartmnt** [comment]
If you want to use positional audio, RPM is the way to go. What does not work  using RPM?

**Comment by Krzmbrzl** [comment]
If plugins don't show up with the RPM version then they are simply not packaged by your distribution. Maybe there is a separate package for the plugins that you can install.

**Comment by Artex154** [comment]
> If you want to use positional audio, RPM is the way to go. What does not work using RPM?

RPM has no plugins like flatpak.

**Comment by Artex154** [comment]
> If plugins don't show up with the RPM version then they are simply not packaged by your distribution. Maybe there is a separate package for the plugins that you can install.

I don't see one?

**Comment by davidebeatrici** [comment]
It's a separate package called `mumble-plugins`.

**Comment by Artex154** [comment]
> It's a separate package called `mumble-plugins`.

![image](https://github.com/user-attachments/assets/3688ca6e-6d47-45eb-9073-006cf0c6ffc2)

Found it, thank you very much, it wasn't in the store so i didn't go that far to look it up.
