### ISSUE TITLE
mumble client issues

### ISSUE THREAD

**Issue by YogruTi** [mumble-voip/mumble#6524]
### Description

Won't the ios client for mumble be updated, the current version is too hard to use, is there an alternative client in the ios store please?

### Mumble component

Client

### OS-specific?

Yes

**Comment by YogruTi** [comment]
Due to ts client charges and verification, resulting in the use of cell phone client experience is very poor, and mumble this is done very well, the whole end are in addition to the ios client is very good to use, please ask the ios client is given up?

**Comment by Krzmbrzl** [comment]
Yes the iOS app is unmaintained
