### ISSUE TITLE
Probleme Racine sur version 1.3.4 et 1.3.3

### ISSUE THREAD

**Issue by UnDragonTaPeur** [mumble-voip/mumble#6527]
### Description

je suis sur mumble entrain de discuter et la tout mes salon se coupe et ça marque racine je suis obliger de redemarer mon pc 

### Steps to reproduce

je join un serve 
sa me quitte tout les salon 
et me marque racine  

### Mumble version

1.3.4 / 1.3.3

### Mumble component

Client

### OS

Other

### Reproducible?

Haven't tried

### Additional information

racine est marqué directement quand ej join le serve te apres ça montre les salons

**Comment by UnDragonTaPeur** [comment]
svp aidez moi

**Comment by Krzmbrzl** [comment]
Please stick to English. 

My French is too rusty to understand your description but what I can already say is that the Mumble 1.3 series has been EOL for quite a while now. Therefore, I would suggest upgrading your Mumble version to see whether the issue persists.

**Comment by UnDragonTaPeur** [comment]
okay excuse me

**Comment by Krzmbrzl** [comment]
So, what is the problem you have encountered?

**Comment by UnDragonTaPeur** [comment]
I'm on mumble chatting and all my living room cuts out and it racine root I have to restart my pc

**Comment by Krzmbrzl** [comment]
Your living room cuts out? I think there is an issue with your translation here 👀
"Racine root" also seems wrong. 

I still don't get what your problem is.

**Comment by davidebeatrici** [comment]
@UnDragonTaPeur With "living room cuts out" do you perhaps mean that you cannot hear anyone in the Mumble room anymore?

**Comment by UnDragonTaPeur** [comment]
yes is good
