### ISSUE TITLE
Large messages wreak havoc upon window layout

### ISSUE THREAD

**Issue by mataha** [mumble-voip/mumble#6528]
### Description

Writing a sufficiently large message into the *Type message to channel ... here* textbox causes Mumble to behave in unexpected ways - the textbox starts to occupy more and more space with channel tree and message log eventually shrinking to their minimum dimensions. Removing said message causes the message log to cover the remaining area, making the textbox inaccessible without resetting window boundaries or restarting the program.

The message doesn't even need to be sent - just it being present is enough.

### Steps to reproduce

1. Connect to a server.
2. Join a channel.
3. Compose a large message (I've used https://www.lipsum.com/feed/html for that).
4. Observe the mess.

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

The message doesn't have to be initially large - pasting the same line over and over will lead to the same end result.

### Screenshots

Before:

![mumble_tsVrT9jqRy](https://github.com/user-attachments/assets/2db364f5-70f0-4e55-b943-202bab618efe)

After:

![mumble_yJl1hkaMA5](https://github.com/user-attachments/assets/32478e8e-9c1f-4c18-a7fc-78c47e223243)

**Comment by Krzmbrzl** [comment]
Does this happen with any window layout (as can be selected from the settings) or only with a specific one?

**Comment by mataha** [comment]
Happens with any window layout.

**Comment by Hartmnt** [comment]
This is probably #1320

**Comment by mataha** [comment]
It certainly looks similar; that said, judging by that issue's screenshots the input textbox stays in its original position, while here it gets dragged way below the viewport.

Is that addressable, then? Having to reset the client after pasting a lengthy build log or stacktrace certainly feels irritating.

**Comment by Hartmnt** [comment]
> Is that addressable, then?

Probably yes. However, there is currently no estimated time frame I can give you for a new Mumble release, yet. But I plan to look into this...
