### ISSUE TITLE
Audio jitter/cutting out in Mumble while downloading, only happens on Linux.

### ISSUE THREAD

**Issue by jyetcv** [mumble-voip/mumble#6533]
### Description

In the Linux version of Mumble, when someone is speaking while I am downloading a file in the background, their voice will often been robotic sounding, cut out a bit and be hard understand. I have tried enabling and disabling TCP, QoS and increasing the jitter buffer, but nothing works. In the Windows version this doesn't happen to me. I'm not sure if it's something I have to set in Linux itself or it's something to do with Mumble's implementation of Opus.

### Steps to reproduce

Download a file in the background while someone else speaks.

### Mumble version

1.5.0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by davidebeatrici** [comment]
How's the latency and jitter (ping variation) to the server when you're downloading?

**Comment by jyetcv** [comment]
Ping goes up by about 50 and packet loss about 12%, but when I'm connected to a locally hosted server it still happens. But on Windows it sounds normal. I wonder if Linux is too aggressive or something with my bandwidth.

**Comment by davidebeatrici** [comment]
Our client's networking code is identical between platforms, however we currently rely on Qt for that and thus have no low level control.

With "locally hosted server" you mean on the same machine (i.e. `localhost`)?

**Comment by jyetcv** [comment]
Yes, the same machine.

**Comment by Krzmbrzl** [comment]
My guess here is that this is something outside of Mumble's control. What you are describing sounds like a bandwidth/networking problem.
It surely is weird that this also happens?when using a locally hosted server but even in that case there is the OS networking code between the server and the client.

**Comment by davidebeatrici** [comment]
As first step, I would check the CPU usage.

**Comment by davidebeatrici** [comment]
@jyetcv Were you able to find the cause?
