### ISSUE TITLE
Audio processing

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6539]
### The issue

Could someone direct me to the section of the source code that handles audio. I would like to know how the server gets the audio from the client and also how it sends audio back to the client.

### Mumble version

1.5

### Mumble component

Server

### OS

Linux

**Comment by davidebeatrici** [comment]
TCP: https://github.com/mumble-voip/mumble/blob/4610353838df4eba648209b8fac60afe0bcc8ee0/src/murmur/Server.cpp#L1702-L1737

UDP: https://github.com/mumble-voip/mumble/blob/4610353838df4eba648209b8fac60afe0bcc8ee0/src/murmur/Server.cpp#L963-L1001

Message processing: https://github.com/mumble-voip/mumble/blob/4610353838df4eba648209b8fac60afe0bcc8ee0/src/murmur/Server.cpp#L1147-L1344
