### ISSUE TITLE
Wiki HTTPS certificate is expired

### ISSUE THREAD

**Issue by nico9889** [mumble-voip/mumble#6540]
### The issue

The certificate used on https://wiki.mumble.info expired on Sat, 17 Aug 2024 20:53:01 GMT.

### Mumble version

doesn't apply

### Mumble component

I don't know

### OS

Linux, Windows, macOS, FreeBSD, OpenBSD, Other

**Comment by davidebeatrici** [comment]
Fixed, thank you.
