### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6541]
### The issue

I need to change the data that is sent by the server when a callback is triggered. How might I do this?

### Mumble version

1.5.0

### Mumble component

Server

### OS

Linux

**Comment by davidebeatrici** [comment]
What do you mean with "callback"?

**Comment by Krzmbrzl** [comment]
Generally speaking this kind of thing is likely only possible by modifying the source code itself.

**Comment by Neloy262** [comment]
@Krzmbrzl what files or folders should I look into?

**Comment by Krzmbrzl** [comment]
Given that I have no idea what you are actually trying to do, all I can say is that the server files live in `src/murmur`. If you tell me more about what exactly you want, I can be more specific.

**Comment by Neloy262** [comment]
I am using a client pymumble. There we can register callback functions when certain events occur(user state updated,channel created etc.). The server sends data back through these callbacks. I want to modify the data sent by the server.

**Comment by Krzmbrzl** [comment]
Depending on the message, the corresponding code lives somewhere else. But all end up going through `Server::sendMessage` eventually. You can go through the code backwards.
