### ISSUE TITLE
Mumble no public server showing

### ISSUE THREAD

**Issue by Beelzebub9966** [mumble-voip/mumble#6542]
### The issue

Im having trouble using mumble i just install the app and no public server is showing
![1](https://github.com/user-attachments/assets/c3acbdf4-3594-4f2f-a22e-254d3dd7965c)

### Mumble version

Mumble Client 1.4.230

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
Did you perhaps reject that Mumble can ping servers? You can also change this setting from the settings (probably in the network category)
