### ISSUE TITLE
Cannot disable Echo Cancellation through Audio Wizard unless explicitly ticked and unticked

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#6544]
### Description

Discovered a bug whilst helping my mate set up Mumble last night.

The Echo Cancellation option in the Audio Wizard does not take effect when left unticked with the intention to disable the feature. To disable Echo Cancellation through the Audio Wizard, one needs to explicitly tick and untick the option. Enabling Echo Cancellation does work as intended.

### Steps to reproduce

Reproducible on fresh and existing installs.

Scenario 1 (fresh install)

1. Complete Audio Wizard leaving Echo Cancellation unticked
2. Echo Cancellation is enabled

Scenario 2

1. Complete Audio Wizard ticking and unticking Echo Cancellation
2. Echo Cancellation is disabled

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
Can confirm. Reproducible when having an established client configuration with echo cancellation enabled. The audio wizard will not take the active echo cancellation setting into account and show an unchecked checkbox.

Offending code is probably in here:
https://github.com/mumble-voip/mumble/blob/4610353838df4eba648209b8fac60afe0bcc8ee0/src/mumble/AudioWizard.cpp#L47-L60
