### ISSUE TITLE
While install zeroc-ice-mumble:x64-windows ,got error

### ISSUE THREAD

**Issue by Sardonyxtechsupport** [mumble-voip/mumble#6546]
### Description

I have downloaded mumble-VoIP application. And I am following the steps for windows build
while running commands ,some of the packages were not downloading.
Error coming  ,
![VCPKG-1](https://github.com/user-attachments/assets/4ee08c2e-b5be-4a4c-a9b9-7c50138a5c1e)
Command  : vcpkg install zeroc-ice-mumble:x64-windows
![VCPKG-2](https://github.com/user-attachments/assets/3f9cd0e1-99cd-47f3-ac63-1b14b4549494)

### Steps to reproduce

1.Download mumble from github
2.execute ”.\get_mumble_dependencies.ps1
3.after long time running the commands ,issue show like attached screens shots

### Mumble version

1.5.634 

### Mumble component

Both

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Use https://github.com/mumble-voip/vcpkg and the scripts contained in that repo

**Comment by Sardonyxtechsupport** [comment]
Actually I have downloaded vcpkg though  .\get_mumble_dependencies.ps1.
it creates vcpkg in my pc C:\Users\Administrator\vcpkg.
shall i delete this folder and download vcpkg from here https://github.com/mumble-voip/vcpkg 
and 
Shall I use this command after vcpkg    Command : .\get_mumble_dependencies.ps1

**Comment by Sardonyxtechsupport** [comment]
i have replaced VCPKG URL in 
C:\Users\Administrator\mumble\scripts\vcpkg\get_mumble_dependencies.ps1 
C:\Users\Administrator\mumble\scripts\vcpkg\get_mumble_dependencies.sh 
like below 
![image](https://github.com/user-attachments/assets/33efc591-594c-467a-8eb3-d783b4b90f73)

after that i have executed .\get_mumble_dependencies.ps1 
faced another error
![ERR 1](https://github.com/user-attachments/assets/2cd16103-29ca-4e82-8c7a-0376990efca3)
![ERR 2](https://github.com/user-attachments/assets/50989872-fcbb-4ffe-acfa-0a08b60f4534)

what to do for this?

**Comment by Sardonyxtechsupport** [comment]
after clone and  run build_mumble_dependencies.ps1  i got result like below screen.

![Err 3](https://github.com/user-attachments/assets/0fb9f063-90c0-408d-8111-7aa008beeb40)

in this scenario ,if i execute cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Administrator/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DIce_HOME=C:/Users/Administrator/vcpkg/installed/x64-windows-static-md" "-DCMAKE_BUILD_TYPE=Release" ..

got error like below screen 
![Err 4](https://github.com/user-attachments/assets/57b1eb4a-44d6-4ee1-9a5f-c818a42bafd5)

what is next?

**Comment by Krzmbrzl** [comment]
Did you really do a fresh clone of vcpkg, removing  remnants of the previous installation?

**Comment by Krzmbrzl** [comment]
Did you really do a fresh clone of vcpkg, removing  remnants of the previous installation?

**Comment by Sardonyxtechsupport** [comment]
i just rename existing vcpkg folder to vcpkg1 and cloned.

**Comment by davidebeatrici** [comment]
The correct triplet is actually `x64-windows-static-md-release`.

**Comment by Krzmbrzl** [comment]
The script will use that automatically, if you execute it

**Comment by Krzmbrzl** [comment]
Can you download the linked tar from the vcpkg output manually?

**Comment by Sardonyxtechsupport** [comment]
link please

**Comment by Sardonyxtechsupport** [comment]
it has downloaded by manually. Why didn't work this by script?

**Comment by Sardonyxtechsupport** [comment]
i have completely delete and clone both Mumble and Vcpkg
When i am try to build, some of the packages missed .
i have downloaded that packages by below method.
![image](https://github.com/user-attachments/assets/ec4e792c-0416-4613-abc2-9775238bc0e4)

and when i enter below command 
cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Administrator/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DIce_HOME=C:/Users/Administrator/vcpkg/installed/x64-windows-static-md-release" "-DCMAKE_BUILD_TYPE=Release" ..

with triplet x64-windows-static-md-release zeroc-ice-mumble downloaded .but when i am execute with  triplet x64-windows-static-md got message like ICE not found.

Even  run with triplet x64-windows-static-md-release got error like below screen

![image](https://github.com/user-attachments/assets/fe420e0d-d562-4219-8e2c-4bc7b1237181)

**Comment by Sardonyxtechsupport** [comment]
hi, still I didn't get the solution. 
I have followed procedure of static build for windows. specified in document. but faced error for Boost.
FYI: I have downloaded all the latest dependence and app like cmake 3.30, Visual Studio 2022 
But no solution works.
any log need from my side. ? if so ,I will attach here.

**Comment by Krzmbrzl** [comment]
> with triplet x64-windows-static-md-release zeroc-ice-mumble downloaded .but when i am execute with triplet x64-windows-static-md got message like ICE not found.

you have to stick to a single triplet. If you use a different triplet in one of the steps, things can't work.

> Even run with triplet x64-windows-static-md-release got error like below screen

that is a different error. Now it finds Ice as expected but is failing for the Boost libraries. Which version of vcpkg are you using? And did you install all required Boost libraries, i.e. did you run the install script from our fork?
