### ISSUE TITLE
continuous source-output on pa/pw

### ISSUE THREAD

**Issue by metasystem** [mumble-voip/mumble#6547]
### Description

continuous input/output source on pw instead of close when no audio exist (muted, speak on touch, etc...)
playback and record always exist.
Block clock rates adaptation on pw because always present.
lock alsa direct flow on output.
block on sway-audio-idle-inhibit. So, no standby is avaible...

### Steps to reproduce

just use on pw...

### Mumble version

1.5.634

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

OS: Gentoo 2.15 x86_64
Kernel: Linux 6.9.10-zen1-x86_64
Uptime: 1 hour, 31 mins
Packages: 1727 (emerge), 10 (flatpak-user)
Shell: zsh 5.9
Display (Q3279WG5B): 2560x1440 @ 75 Hz in 33″ [External]
WM: Hyprland (Wayland)
Theme: Fusion [Qt], Material-Black-Cherry-3.36 [GTK2/3]
Icons: Laferte-Matrix [GTK2/3]
Font: qt5ct [Qt], Source Code Pro (12pt, Semibold) [GTK2/3]
Cursor: Adwaita
Terminal: alacritty 0.14.0-dev
Terminal Font: Input (20.0pt)
CPU: AMD Ryzen 7 7700 (16) @ 5.39 GHz
GPU 1: AMD Radeon RX 6800
GPU 2: AMD Raphael [Integrated]
Memory: 5.05 GiB / 29.03 GiB (17%)
Swap: Disabled
Disk (/): 649.18 GiB / 904.67 GiB (72%) - btrfs
Local IP (br0): 
Locale: fr_FR.UTF-8

### Screenshots

![image](https://github.com/user-attachments/assets/0cbc6036-607d-4d40-8af3-114303d26bce)
![image](https://github.com/user-attachments/assets/e3261e8c-6655-43a2-b101-dab09425dcc9)

**Comment by davidebeatrici** [comment]
#5408 will fix this.

Basically, we never pause the stream right now.

**Comment by Hartmnt** [comment]
I think since #6366 we pause the input stream when the user is muted. This was not backported to 1.5 though

**Comment by davidebeatrici** [comment]
Right.

**Comment by Krzmbrzl** [comment]
In other words, this is already implemented for 1.6
