### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by CCansler20** [mumble-voip/mumble#6550]
### The issue

On startup I get an immediate crash message. After I submit a report the application will open momentarily but be frozen, then close fully a few seconds later. I have tried reinstalling the app multiple times.

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

**Comment by davidebeatrici** [comment]
Possibly the issue that was fixed in #6510.

As a workaround you can set a stereo audio output device as default in Windows, launch Mumble and disable positional audio. Then you can use your mono audio output device without causing Mumble to crash.

**Comment by CCansler20** [comment]
Changing the audio devices then disabling positional seems to have solved it. Thanks!

**Comment by davidebeatrici** [comment]
Thank you for confirming!
