### ISSUE TITLE
Mumble server process name is "Main"

### ISSUE THREAD

**Issue by sorcix** [mumble-voip/mumble#6552]
### Description

On my server, `pstree` and `top` identify the mumble-server process as `Main` instead of `mumble-server`.

```
# pstree -p
systemd(1)─┬─Main(506)─┬─{Main}(607)
           │           ├─{Main}(665)
           │           ├─{Main}(666)
           │           └─{Main}(667)
```

```
# ps -p 506
    PID TTY          TIME CMD
    506 ?        00:00:00 Main
```

This PID 506 is actually Mumble server:

```
# ps aux | grep ' 506 '
_mumble+     506  0.0  2.2 460908 44804 ?        Ssl  13:27   0:00 /usr/bin/mumble-server -ini /etc/mumble/mumble-server.ini -fg
```

Looks like the thread name is being set [in `Server.cpp` on line 81](https://github.com/mumble-voip/mumble/blob/4610353838df4eba648209b8fac60afe0bcc8ee0/src/murmur/Server.cpp#L81).

Is it an option to change this to something that indicates it's a Mumble process?

### Steps to reproduce

1. Start a mumble-server instance
2. Search for the process in `pstree`/`ps`/`top`.

### Mumble version

1.5.634

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
Yup, I have also noticed this and got annoyed. It seems like this is set by tracy, which is interesting. The easiest fix would indeed be to change the thread name to "mumble-server". I am all for that, but would this break anything @Krzmbrzl ?

**Comment by Hartmnt** [comment]
@sorcix Would you be able to submit a PR for this?

**Comment by sorcix** [comment]
Oh no, I missed a super easy opportunity to become a contributor! :laughing:

Missed the notification, sorry about that. Thanks for the fix!
