### ISSUE TITLE
On CELT codec negotiation 1.5.xx clients are removed from the server

### ISSUE THREAD

**Issue by saori-yuko** [mumble-voip/mumble#6560]
### Description

When a client connects to a server that supports CELT and Opus the server will switch to CELT and drop all clients that no longer support CELT 

### Steps to reproduce

1. Start server that is 1.4.xx or lower
2. Connect with 1.5.xx client
3. Connect with client that prefers CELT or only supports CELT eg. Mumla (For Android)
4. Client that is 1.5.xx gets dropped 

To fix set opusthreshold=0 in your server config

### Mumble version

1.5.0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
> When a client connects to a server that supports CELT and Opus the server will switch to CELT and drop all clients that no longer support CELT

yes - 1.5 no longer supports CELT so that is working as intended.

> To fix set opusthreshold=0 in your server config

which is also the default starting from Mumble server 1.5

**Comment by saori-yuko** [comment]
> > When a client connects to a server that supports CELT and Opus the server will switch to CELT and drop all clients that no longer support CELT
> 
> yes - 1.5 no longer supports CELT so that is working as intended.
> 
> > To fix set opusthreshold=0 in your server config
> 
> which is also the default starting from Mumble server 1.5

I understand that, but this is a bug affecting users currently I've observed it multiple times

**Comment by Krzmbrzl** [comment]
>  but this is a bug affecting users currently I've observed it multiple times.

It's not a bug. That''s my point

> Maybe add a remediation message when the users are forced off the server and are unable to join?

That should already be the case:
https://github.com/mumble-voip/mumble/blob/71010603d8663da7c1d762e1783f55aa44029ec8/src/mumble/Messages.cpp#L1231-L1236

**Comment by Hartmnt** [comment]
> Only supports CELT eg. Mumla

The latest version of Mumla supports Opus and can flawlessly connect to a 1.5 server with 1.5 desktop clients on it

**Comment by saori-yuko** [comment]
> > but this is a bug affecting users currently I've observed it multiple times.
> 
> It's not a bug. That''s my point
> 
> > Maybe add a remediation message when the users are forced off the server and are unable to join?
> 
> That should already be the case:
> 
> https://github.com/mumble-voip/mumble/blob/71010603d8663da7c1d762e1783f55aa44029ec8/src/mumble/Messages.cpp#L1231-L1236

so it's not a bug if I'm able to drop users from a server under 1.5 got it

**Comment by Hartmnt** [comment]
> so it's not a bug if I'm able to drop users from a default server under 1.5 got it

Just set ``opusthreshold`` to ``0`` as you suggested. This has been the default for literally years:

https://github.com/mumble-voip/mumble/blob/36fc37c9c9f2905e09e9dc78fcdfd52693b0f270/auxiliary_files/mumble-server.ini#L167-L169

**Comment by saori-yuko** [comment]
> > so it's not a bug if I'm able to drop users from a default server under 1.5 got it
> 
> Just set `opusthreshold` to `0` as you suggested. This has been the default for literally years:
> 
> https://github.com/mumble-voip/mumble/blob/36fc37c9c9f2905e09e9dc78fcdfd52693b0f270/auxiliary_files/mumble-server.ini#L167-L169

Okay thank you I guess it's only Debian stable that's affected by it

**Comment by saori-yuko** [comment]
https://github.com/mumble-voip/mumble/commit/1017dab5c2f514841cba173c48092b2a01bf002c

>Just set opusthreshold to 0 as you suggested. This has been the default for literally years

The code was merged with the stable this year though

**Comment by Krzmbrzl** [comment]
Maybe the Debian package provides a custom INI file that uses different values. In that case, this would be a Debian package bug though.
