### ISSUE TITLE
Any settings are not saved. Every time a clean start

### ISSUE THREAD

**Issue by Mihail-Lazarev** [mumble-voip/mumble#6567]
### The issue

Please help me fix the problem. After installing the mumble program as usual I set the settings in Auto Tuning Wizard. 
 However, when I restart the program, no settings are saved and the program opens with Auto Tuning Wizard as if I were launching it for the first time. 
 If I change any setting and restart the program, the set setting disappears.
 I run the program in administrator mode but it doesn't change anything.

### Mumble version

v1.5.634

### Mumble component

Client

### OS

Windows

### Additional information

I got Windows 11

**Comment by Krzmbrzl** [comment]
Do you get a message upon startup saying something about improper exit of Mumble?

**Comment by Mihail-Lazarev** [comment]
> Do you get a message upon startup saying something about improper exit of Mumble?
No, I didn't receive any messages. 

 I have this problem only in the program versions v1.5.634 and v1.5.629 (all 1.5. ...). Versions of the program  1.4. ... work fine. I installed and used 1.4.287.
Also, I tried to add an exe file to an exception to Windows Defender but it didn't help.

**Comment by Hartmnt** [comment]
This sounds to me like a file/folder permission error. You could try to backup your settings, delete the configuration folder(s) and start Mumble as a normal user. Maybe this will fix your problem.

**Comment by markusmueller73** [comment]
Same here. Same OS, same Mumble version. The client didn't save the config. If I start it with the --config parameter, created an empty mumble.ini in a path with full access, the client didn't save the config too. After configuring and exiting, the client start clean the next time, with the above parameter. The mumble.ini file didn't touched at all.

**Comment by Krzmbrzl** [comment]
This version of Mumble is no longer using an INI file for configs. It uses JSON instead. What does the developer console contain when you run Mumble and configure it?
(See the docs folder for how to access the dev console)

**Comment by pateus** [comment]
Similar problem, settings are not saved, have to configure again each time you log in. Running as administrator does not help.
