### ISSUE TITLE
Push to talk button works only once.

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#6569]
### Description

If I push to talk, it works -- other side can hear. Once I let go and push again, it won't work. I have to restart mumble.

### Steps to reproduce

1. Build from github today
2. Using debian-stable murmerd (1.3.4-4)
3. Enable push to talk mode
4. Push to talk, and release
5. Push to talk again

I also tested this with the dbus startTalking and stopTalking. Once stopTalking is done, I no longer am heard by the other side. My side Does show blue (talking enabled), but the other side does not [not after the first time].

### Mumble version

1.6.0 github build

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

I've not yet tried building and installing an updated murmerd.  1.3.4-4 is the latest the comes with debian though.

**Comment by jaggzh** [comment]
Okay, it looks like mumble-server is built along with mumble. I ran it from within the mumble directory.
1. I did not install it, I just ran it. So there might be lib issues. I don't yet know how to make it into a debian package.
2. It's giving me an error so I'm not yet able to test if this bug is with the client or the old server:
```sh
$ ./mumble-server
qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter
```

**Comment by Krzmbrzl** [comment]
When you say "push to talk" do you mean PTT transmission activation (contrary to e.g. voice activation) or do you mean whispering/shouting?

**Comment by Hartmnt** [comment]
Please also check if there is any info logged in the DeveloperConsole https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md

**Comment by jaggzh** [comment]
(Okay, the new server runs (the QT error was not a fatal one).)
I'm using the actual Push to Talk transmit mode, but the same happens with Continuous and Voice Activated).

In testing and looking at dev console, it seems the issue arises on any Receiving Client (the client playing the audio transmitted from a "Transmitting Client").

Either client can only receive audio from the transmitter one time. When the transmission is done this dev console message appears on the Receiving Client:
```
<W>2024-09-26 12:37:42.843 QObject::connect: Cannot queue arguments of type 'AudioOutputBuffer*'
(Make sure 'AudioOutputBuffer*' is registered using qRegisterMetaType().)
```

ie. With Push to Talk, when the talk button is released, the receiving client will show that message.
With Voice Activity, when the activity is done and audio stops, the client will show that message.
Once it shows it, the audio system needs to be restarted (Okaying in settings or restarting mumble), and it's reset for that one-time-listener use :)

**Comment by jaggzh** [comment]
(Oh, like right now, a transmitting client is in continuous mode. On my listening-end (receiving client) I can hear them for now.  But if they stop transmitting (like if they switch modes or for any reason stop), my receiver won't ever show them as Blue again (and won't play audio) until I restart its audio system (the receiver's).

**Comment by jaggzh** [comment]
https://github.com/mumble-voip/mumble/pull/6571

Okay, I tested this on two Debian stable systems, and so far it seems to have fixed the problem without introducing any issues.

**Comment by Hartmnt** [comment]
I can confirm this bug in a VM. No transmission possible after the first. Must be happening since the upgrade to Qt6.
