### ISSUE TITLE
Mumble Freezing/crashing

### ISSUE THREAD

**Issue by Nachiqq** [mumble-voip/mumble#6605]
### The issue

My mumble will perma freeze/crash constantly, sometimes i may get past the part where i select a server but always ends up just being completely frozen, if i am in the server when it crashes/ becomes unresponsive i cannot hear nor speak. I have tried updating windows 10, i have tried completely uninstalling and deleting any files i can find and re installed mumble. I have also tried giving mumble higher priority using project lasso. The problem of freezing occured on the older ( i dont know which verison i was using previously) and the latest verison of mumble. I have to close mumble using task manager.

My windows verison: version 22h2 (os build 19045. 5011)

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment]
So you start Mumble and it freezes more or less?instantly?

**Comment by Nachiqq** [comment]
Correct

**Comment by Krzmbrzl** [comment]
Do you have any peripherals (e.g. controller, joystick) connected to your PC other than mouse and keyboard? If so, try disconnecting these and see whether the issue persists.

**Comment by Nachiqq** [comment]
This seems to have fixed my problem, i had quite a few things plugged in such as speakers, joystick and throttle, track IR, i unplugged everything apart from my keyboard mouse and wireless headset and mumble seems to be running smooth. 

I cant thank you enough this has been a total headache for me.

Thank you! :D

**Comment by Krzmbrzl** [comment]
Could you check which of the devices exactly causes the issue? My bet would be on the throttle 👀

But glad to head that this solved your issue (kinda at least) :+1:

**Comment by Krzmbrzl** [comment]
That'd be very odd though 👀

**Comment by Krzmbrzl** [comment]
@davidebeatrici seems like the shortcut system is still overloaded with event processing when analogue-ish input devices are connected that (presumably) send more or less a continuous stream of input events.

**Comment by volodin-victor** [comment]
Really piece of glitching sh*t.
