### ISSUE TITLE
Error during SSL handshake unsupported protocol  Android 4.4.2

### ISSUE THREAD

**Issue by itsfelipe-dev** [mumble-voip/mumble#6606]
### Server:  
Murmur 1.5.634 running on Windows: Windows 10 Pro 2009 22631.286
Client: Mumla 3.6.10 running on Android 4.4.2 

### Error:
0:(-1)> Connection closed: Error during SSL handshake: error:0A000102:SSL routines::unsupported protocol [13]`

### Log:
`<X>2024-10-12 20:27:05.330 SSL: OpenSSL version is 'OpenSSL 3.2.0 23 Nov 2023'

<W>2024-10-12 20:27:05.340 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2024-10-12 20:27:05.347 SSL: CA certificate filter applied. Filtered size: 78, original size: 78

<W>2024-10-12 20:27:06.752 Murmur 1.5.634 running on Windows: Windows 10 Pro 2009 22631.2861 [x64]: Booting servers

<W>2024-10-12 20:27:26.587 1 => <0:(-1)> New connection: 192.168.1.247:34600
<W>2024-10-12 20:27:26.588 Connection: Failed to add flow to QOS
<W>2024-10-12 20:27:26.612 1 => <0:(-1)> Connection closed: Error during SSL handshake: error:0A000102:SSL routines::unsupported protocol [13]`

### Config:
i tried using this settings, but it still doesn't work

murmur.ini
`sslCiphers=EECDH+AESGCM:EDH+aRSA+AESGCM:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS`

Any help will be appreciated, thank you

**Comment by Krzmbrzl** [comment]
Can you connect with a regular Mumble client? If so, this is a Mumla issue which is a software we do not maintain 👀
