### ISSUE TITLE
Registering Plugin Callbacks

### ISSUE THREAD

**Issue by Kaegos** [mumble-voip/mumble#6608]
### The issue

I'm probably being really dumb, but I am trying to make a small custom plugin that makes use of some eventhandler / callback functions, e.g. mumble_onUserTalkingStateChanged. I'm including the MumblePlugin.h header and that's fine, but I'm not sure how to actually make use of the function. I thought I would need to register the callback in the plugin Init function, but I can't find any callback registration definitions anywhere in the repo. Could someone point me in the right direction? 

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

**Comment by Kaegos** [comment]
I knew I'd find the answer as soon as I posted. It seems that the registration is automatic, simply having it in the code will register the callback.

**Comment by Krzmbrzl** [comment]
Indeed. You only have to take care to use the exact function signature as provided in the respective header file. Then the mere presence of an implementation of the given function is enough for Mumble to pick them up :)
