### ISSUE TITLE
Multiple authentication methods

### ISSUE THREAD

**Issue by UndeRus** [mumble-voip/mumble#6610]
### Context

Login to server

### Description

Now we have 2 variants to check user:

- User certificate
- Password

Transfering user certificate to other device is too hard for common user, password auth is too uncomfortable, especially if you have dynamic password(like one time password)

I want have some other auth variants like oauth2 or something. 

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
You can implement custom authenticators using Ice.

Furthermore, the issue of transferring certificates between devices will be mediated when we introduce multi device support.

**Comment by UndeRus** [comment]
You can implement custom authenticator(I made some), but problem doesnt' disappear:

Authenticator work through method ServerAuthenticator#authenticate which checks certificate or password, but if you want implement something asynchronous like oauth - you need to keep waiting authenticate function(what is incorrect and block server) or create session before password dialog confirm to proceed correctly.

Like this:
```mermaid
sequenceDiagram
    Client->>Server: Connect
    Server->>Client: Show password dialog
    Client->>External auth: Confirm Auth
    External auth-->>Server: Update sessions info
    Client->>Server: Confirm password dialog
    Server->>External auth: Check is session for current cert valid
    External auth->>Server: Return auth result
    Server->>Client: Auth succeed
```

But with this scenario:
- You need to register user cert before
- Password dialog doesn't give any information where user need to go to proceed auth

Is it ok?

**Comment by Krzmbrzl** [comment]
I believe that having some sort of asynchronous authentication is currently not really possible with the way the server is written. The best way I could come up with would be to reject the authentication request on the first try, do the asynchronous request in the background and then buffer its result. If the client tries to authenticate again, we can use the buffered result of the async operation.
But that's certainly not pretty.
