### ISSUE TITLE
error: 'bswap_16' was not declared in this scope

### ISSUE THREAD

**Issue by ridhoswasta** [mumble-voip/mumble#6612]
### Description

When building Mumble server only on Debian 12 it shows "error: 'bswap_64' was not declared in this scope" , seems like not compatible with latest protobuf on debian 12. 
protoc --version
libprotoc 3.21.12

### Steps to reproduce

1. Cloning mumble dir to mumble 
git clone --depth 1 --recursive https://github.com/mumble-voip/mumble.git
2. cMake with flag -Dclient=OFF and -Dbundled-opus=OFF
cmake -B build -Dclient=OFF -Dbundled-opus=OFF
`-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python interpreter version 3.11.2
^F-- Performing Test COMPILER_HAS_MBIG_OBJ
-- Performing Test COMPILER_HAS_MBIG_OBJ - Failed
-- Using (among others) the following compiler flags: -Werror;-Wall;-Wpedantic;-Wextra;-Wconversion;-Wsign-conversion;-fsigned-char;-O3
-- ##################################################
-- Mumble version:              1.6.0
-- Architecture:                x64
-- Build type:                  Release
-- Using LTO in release builds: ON
-- ##################################################
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Qt6 component found: Core | Version: 6.4.2
-- Qt6 component found: Network | Version: 6.4.2
-- Qt6 component found: Xml | Version: 6.4.2
-- OpenSSL component found: Crypto | Version: 3.0.14
-- OpenSSL component found: SSL | Version: 3.0.14
-- Protobuf found | Version: 3.21.12
-- Found Threads: TRUE
-- TRACY_ENABLE: OFF
-- TRACY_ON_DEMAND: ON
-- TRACY_CALLSTACK: OFF
-- TRACY_NO_CALLSTACK: OFF
-- TRACY_NO_CALLSTACK_INLINES: OFF
-- TRACY_ONLY_LOCALHOST: OFF
-- TRACY_NO_BROADCAST: OFF
-- TRACY_ONLY_IPV4: OFF
-- TRACY_NO_CODE_TRANSFER: OFF
-- TRACY_NO_CONTEXT_SWITCH: OFF
-- TRACY_NO_EXIT: OFF
-- TRACY_NO_SAMPLING: OFF
-- TRACY_NO_VERIFY: OFF
-- TRACY_NO_VSYNC_CAPTURE: OFF
-- TRACY_NO_FRAME_IMAGE: OFF
-- TRACY_NO_SYSTEM_TRACING: OFF
-- TRACY_DELAYED_INIT: OFF
-- TRACY_MANUAL_LIFETIME: OFF
-- TRACY_FIBERS: OFF
-- TRACY_NO_CRASH_HANDLER: OFF
-- TRACY_TIMER_FALLBACK: OFF
-- Disabling warnings for targets: TracyClient
-- Tracy: OFF
-- Found Git: /usr/bin/git (found version "2.39.5")
-- Qt6 component found: Sql | Version: 6.4.2
-- File: /mnt/d/swasta/mumble/build/src/murmur/murmur_autogen
-- Ice component found: Ice | Version: 3.7.8
-- Ice component found: IceSSL | Version: 3.7.8
-- Ice optional component found: IceDiscovery | Version: 3.7.8
-- Ice optional component found: IceLocatorDiscovery | Version: 3.7.8
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    bundled-opus

-- Build files have been written to: /mnt/d/swasta/mumble/build`

3. Build Mumble Server
make -j $(nproc)
`[  1%] Generating licenses.h
[  2%] Generating Ice files
[  4%] Building CXX object src/tracy/CMakeFiles/TracyClient.dir/public/TracyClient.cpp.o
[  4%] Built target generate_license_header
[  5%] Linking CXX static library libTracyClient.a
[  5%] Built target TracyClient
[  9%] Generating FFDHETable.h
[  9%] Running cpp protocol buffer compiler on /mnt/d/swasta/mumble/src/MumbleUDP.proto
[  9%] Running cpp protocol buffer compiler on /mnt/d/swasta/mumble/src/Mumble.proto
[ 11%] Automatic MOC for target shared
[ 11%] Built target shared_autogen
[ 13%] Building CXX object src/CMakeFiles/shared.dir/shared_autogen/mocs_compilation.cpp.o
[ 13%] Building CXX object src/CMakeFiles/shared.dir/Mumble.pb.cc.o
[ 16%] Building CXX object src/CMakeFiles/shared.dir/MumbleUDP.pb.cc.o
[ 16%] Building CXX object src/CMakeFiles/shared.dir/Ban.cpp.o
[ 19%] Building CXX object src/CMakeFiles/shared.dir/EnvUtils.cpp.o
[ 20%] Building CXX object src/CMakeFiles/shared.dir/FFDHE.cpp.o
[ 20%] Building CXX object src/CMakeFiles/shared.dir/HostAddress.cpp.o
[ 22%] Building CXX object src/CMakeFiles/shared.dir/HTMLFilter.cpp.o
[ 23%] Building CXX object src/CMakeFiles/shared.dir/License.cpp.o
In file included from /usr/include/google/protobuf/stubs/common.h:48,
                 from /usr/include/google/protobuf/io/coded_stream.h:131,
                 from /mnt/d/swasta/mumble/build/src/MumbleUDP.pb.h:23,
                 from /mnt/d/swasta/mumble/build/src/MumbleUDP.pb.cc:4:
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint16_t google::protobuf::BigEndian::FromHost16(uint16_t)':
/usr/include/google/protobuf/stubs/port.h:356:51: error: 'bswap_16' was not declared in this scope
  356 |   static uint16_t FromHost16(uint16_t x) { return bswap_16(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint16_t google::protobuf::BigEndian::ToHost16(uint16_t)':
/usr/include/google/protobuf/stubs/port.h:357:49: error: 'bswap_16' was not declared in this scope
  357 |   static uint16_t ToHost16(uint16_t x) { return bswap_16(x); }
      |                                                 ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint32_t google::protobuf::BigEndian::FromHost32(uint32_t)':
/usr/include/google/protobuf/stubs/port.h:359:51: error: 'bswap_32' was not declared in this scope
  359 |   static uint32_t FromHost32(uint32_t x) { return bswap_32(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint32_t google::protobuf::BigEndian::ToHost32(uint32_t)':
/usr/include/google/protobuf/stubs/port.h:360:49: error: 'bswap_32' was not declared in this scope
  360 |   static uint32_t ToHost32(uint32_t x) { return bswap_32(x); }
      |                                                 ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint64_t google::protobuf::BigEndian::FromHost64(uint64_t)':
/usr/include/google/protobuf/stubs/port.h:362:51: error: 'bswap_64' was not declared in this scope
  362 |   static uint64_t FromHost64(uint64_t x) { return bswap_64(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint64_t google::protobuf::BigEndian::ToHost64(uint64_t)':
/usr/include/google/protobuf/stubs/port.h:363:49: error: 'bswap_64' was not declared in this scope
  363 |   static uint64_t ToHost64(uint64_t x) { return bswap_64(x); }
      |                                                 ^~~~~~~~
In file included from /usr/include/google/protobuf/stubs/common.h:48,
                 from /usr/include/google/protobuf/io/coded_stream.h:131,
                 from /mnt/d/swasta/mumble/build/src/Mumble.pb.h:23,
                 from /mnt/d/swasta/mumble/build/src/Mumble.pb.cc:4:
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint16_t google::protobuf::BigEndian::FromHost16(uint16_t)':
/usr/include/google/protobuf/stubs/port.h:356:51: error: 'bswap_16' was not declared in this scope
  356 |   static uint16_t FromHost16(uint16_t x) { return bswap_16(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint16_t google::protobuf::BigEndian::ToHost16(uint16_t)':
/usr/include/google/protobuf/stubs/port.h:357:49: error: 'bswap_16' was not declared in this scope
  357 |   static uint16_t ToHost16(uint16_t x) { return bswap_16(x); }
      |                                                 ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint32_t google::protobuf::BigEndian::FromHost32(uint32_t)':
/usr/include/google/protobuf/stubs/port.h:359:51: error: 'bswap_32' was not declared in this scope
  359 |   static uint32_t FromHost32(uint32_t x) { return bswap_32(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint32_t google::protobuf::BigEndian::ToHost32(uint32_t)':
/usr/include/google/protobuf/stubs/port.h:360:49: error: 'bswap_32' was not declared in this scope
  360 |   static uint32_t ToHost32(uint32_t x) { return bswap_32(x); }
      |                                                 ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint64_t google::protobuf::BigEndian::FromHost64(uint64_t)':
/usr/include/google/protobuf/stubs/port.h:362:51: error: 'bswap_64' was not declared in this scope
  362 |   static uint64_t FromHost64(uint64_t x) { return bswap_64(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint64_t google::protobuf::BigEndian::ToHost64(uint64_t)':
/usr/include/google/protobuf/stubs/port.h:363:49: error: 'bswap_64' was not declared in this scope
  363 |   static uint64_t ToHost64(uint64_t x) { return bswap_64(x); }
      |                                                 ^~~~~~~~
[ 25%] Building CXX object src/CMakeFiles/shared.dir/LogEmitter.cpp.o
[ 26%] Building CXX object src/CMakeFiles/shared.dir/MumbleProtocol.cpp.o
[ 27%] Building CXX object src/CMakeFiles/shared.dir/OSInfo.cpp.o
make[2]: *** [src/CMakeFiles/shared.dir/build.make:124: src/CMakeFiles/shared.dir/MumbleUDP.pb.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 29%] Generating MumbleServerIceWrapper
[ 29%] Built target generate_murmur_ice_wrapper
make[2]: *** [src/CMakeFiles/shared.dir/build.make:110: src/CMakeFiles/shared.dir/Mumble.pb.cc.o] Error 1
In file included from /usr/include/google/protobuf/stubs/common.h:48,
                 from /usr/include/google/protobuf/io/coded_stream.h:131,
                 from /mnt/d/swasta/mumble/build/src/MumbleUDP.pb.h:23,
                 from /mnt/d/swasta/mumble/src/MumbleProtocol.h:9,
                 from /mnt/d/swasta/mumble/src/MumbleProtocol.cpp:6:
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint16_t google::protobuf::BigEndian::FromHost16(uint16_t)':
/usr/include/google/protobuf/stubs/port.h:356:51: error: 'bswap_16' was not declared in this scope
  356 |   static uint16_t FromHost16(uint16_t x) { return bswap_16(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint16_t google::protobuf::BigEndian::ToHost16(uint16_t)':
/usr/include/google/protobuf/stubs/port.h:357:49: error: 'bswap_16' was not declared in this scope
  357 |   static uint16_t ToHost16(uint16_t x) { return bswap_16(x); }
      |                                                 ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint32_t google::protobuf::BigEndian::FromHost32(uint32_t)':
/usr/include/google/protobuf/stubs/port.h:359:51: error: 'bswap_32' was not declared in this scope
  359 |   static uint32_t FromHost32(uint32_t x) { return bswap_32(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint32_t google::protobuf::BigEndian::ToHost32(uint32_t)':
/usr/include/google/protobuf/stubs/port.h:360:49: error: 'bswap_32' was not declared in this scope
  360 |   static uint32_t ToHost32(uint32_t x) { return bswap_32(x); }
      |                                                 ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint64_t google::protobuf::BigEndian::FromHost64(uint64_t)':
/usr/include/google/protobuf/stubs/port.h:362:51: error: 'bswap_64' was not declared in this scope
  362 |   static uint64_t FromHost64(uint64_t x) { return bswap_64(x); }
      |                                                   ^~~~~~~~
/usr/include/google/protobuf/stubs/port.h: In static member function 'static uint64_t google::protobuf::BigEndian::ToHost64(uint64_t)':
/usr/include/google/protobuf/stubs/port.h:363:49: error: 'bswap_64' was not declared in this scope
  363 |   static uint64_t ToHost64(uint64_t x) { return bswap_64(x); }
      |                                                 ^~~~~~~~
make[2]: *** [src/CMakeFiles/shared.dir/build.make:236: src/CMakeFiles/shared.dir/MumbleProtocol.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: src/CMakeFiles/shared.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

### Mumble version

1.6.0

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

root@DESKTOP-VLCQSJO:/mnt/d/swasta/mumble/build# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
root@DESKTOP-VLCQSJO:/mnt/d/swasta/mumble/build#

**Comment by Krzmbrzl** [comment]
#6297

**Comment by Krzmbrzl** [comment]
The compile error is likely due to you using a version of Mumble that is a couple of weeks old which doesn't yet use C++17, which Protobuf requires in recent versions (implicitly)

**Comment by ridhoswasta** [comment]
it's WSL issue. I am not sure why but it's built perfectly on non-wsl instance.

**Comment by Krzmbrzl** [comment]
Okay that's definitely odd. No idea what the cause might be.
Thanks for letting us know though!
