### ISSUE TITLE
ERROR ON BUILDING MUMBLE

### ISSUE THREAD

**Issue by ejaysaya** [mumble-voip/mumble#6626]
### The issue

now i only got this problem. 

C:\dev\mumble\build>cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DIce_HOME=C:/dev/vcpkg/installed/x64-windows-static-md" "-DCMAKE_BUILD_TYPE=Release" ..
-- Found Python interpreter version 3.9.13
-- Using Win7 as the oldest supported Windows version
-- Using (among others) the following compiler flags: /WX;/W4;/O2;/bigobj;/options:strict
-- ##################################################
-- Mumble version: 1.6.0
-- Architecture: x86
-- Build type: Release
-- Using LTO in release builds: ON
-- ##################################################
CMake Error at cmake/pkg-utils.cmake:87 (message):
Qt6 component not found: Core 6.2
Call Stack (most recent call first):
src/CMakeLists.txt:20 (find_pkg)

### Mumble version

1.5.634

### Mumble component

Both

### OS

Windows

### Additional information

i am not sure if i am doing it right but i installed Qt6 itself but still it looks for Qt6 component not found: Core 6.2

**Comment by Krzmbrzl** [comment]
You need to have the relevant Qt version to be installed via vcpkg.

**Comment by ejaysaya** [comment]
i already have installed it. and followed the instructions i just don't understand why is it looking for Qt6 component : Core 6.2

![image](https://github.com/user-attachments/assets/4d0558f9-d676-42f7-a8b8-99b43ad7448f)

**Comment by davidebeatrici** [comment]
We're looking for a minimum Qt version of 6.2 since ab7285fbe3748f251cca8d0a769292561e0782a2.

**Comment by ejaysaya** [comment]
> We're looking for a minimum Qt version of 6.2 since [ab7285f](https://github.com/mumble-voip/mumble/commit/ab7285fbe3748f251cca8d0a769292561e0782a2).

THANKS so it means i have to manually install. even if i used the prebuilt files

**Comment by Krzmbrzl** [comment]
No. The prebuilt env is working. That's what we are using on our CI to build Mumble. Just make sure you have the latest version of the build env.

**Comment by JobberRT** [comment]
@Krzmbrzl  Hi Krzmbrzl, Do you have any plan updating the `mumble-docker` repo?
I see a PR here, but it seems this PR make too many changes: https://github.com/mumble-voip/mumble-docker/pull/49

**Comment by Krzmbrzl** [comment]
Yes, the Docker image is still maintained

**Comment by JobberRT** [comment]
> Yes, the Docker image is still maintained

Thanks, I will wait for it!
