### ISSUE TITLE
the PA on left 4 dead 2 using source engine plugins does not work

### ISSUE THREAD

**Issue by salimshady12** [mumble-voip/mumble#6632]
### Description

the PA on left 4 dead 2 using source engine plugins does not work. is it because the new version or else ? 

### Steps to reproduce

-

### Mumble version

1.5.634

### Mumble component

Both

### OS

Windows

### Reproducible?

Yes

### Additional information

the mic only working when the round starts which is a goodthing . but the PA is not working.

### Relevant log output

```shell
-
```

### Screenshots

-

**Comment by Krzmbrzl** [comment]
What exactly do you mean by `PA` is not working? Apparently, it is somewhat working given that you stated that the mic only works when in-game. So I take it that what you mean is that you don't hear the direction from which a given voice is coming, correct?

**Comment by salimshady12** [comment]
exactly, is there something that i need to do ?

**Comment by Krzmbrzl** [comment]
Okay, could you [enable the developer menu](https://github.com/mumble-voip/mumble/blob/master/docs/DeveloperConsole.md) and then open the positional data viewer?

Then open L4D2 and walk around in-game. Now what does the positional data viewer of Mumble show?

**Comment by Hartmnt** [comment]
Please check again with the lastest version of Mumble
