### ISSUE TITLE
Proto msg being called more than once

### ISSUE THREAD

**Issue by Neloy262** [mumble-voip/mumble#6636]
### The issue

I have a custom proto msg. When my mumble client invokes that msg the server is sending multiple response msg. What could be the reason?

### Mumble version

1.4.0

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
So? With the information you provide, I can't see any issue. If you have multiple users on the server, you get multiple UserAdd messages (one per user). So I would say that everything is likely working as intended. 👀

Do you have a specific indication that makes you think something is wrong?

**Comment by Neloy262** [comment]
For testing purpose there is only one user on the server.

**Comment by Krzmbrzl** [comment]
You'll have to inspect the contents of the messages. Just because you receive a message of the same type doesn't mean it's the same message.
Generally speaking, I can only say that we are not aware of any redundant messages that are sent by our official server implementation 🤔

**Comment by Neloy262** [comment]
The content of the redundant messages are the same.
![Screenshot 2024-11-27 at 3 41 31 PM (1)](https://github.com/user-attachments/assets/434ab421-9a14-406f-a9ed-fa65af3367bd)

**Comment by Krzmbrzl** [comment]
There is no way for me to make sense of this. If you think you found a bug, please try to provide a minimal example that reproduces the behavior (using only the official server and client). If you find something that looks odd in this way, let me know and I cam see whether I can reproduce it on my machine. Everything else will just be remote debugging via text and that is extremely time consuming and error prone 👀
