### ISSUE TITLE
Freezing with Simracing Pedals

### ISSUE THREAD

**Issue by AlexFleurant** [mumble-voip/mumble#6642]
### Description

Mumble freeze when I plug my Conspit CPP lite Pedals

### Steps to reproduce

start with the device attached
Freeze and blank screen
start without the device attached
work fine

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
This is sadly a known issue. Closing in favor of #5631 and #6054
If you have any additional useful information for us feel free to post it in the linked issues.

**Comment by Krzmbrzl** [comment]
New issue for tracking this bug: https://github.com/mumble-voip/mumble/issues/6696
