### ISSUE TITLE
(Debian) Build Dependencies: Missing libspeexdsp-dev and libpipewire-0.3-dev?

### ISSUE THREAD

**Issue by diederikdehaas** [mumble-voip/mumble#6644]
### The issue

The [cmake_options.md](https://github.com/mumble-voip/mumble/blame/master/docs/dev/build-instructions/cmake_options.md) file has these options:
1) bundled-speex
2) pipewire

ad 1) If you want to turn bundled-speex OFF, thus use the system libraries, shouldn't ``libspeexdsp-dev`` be added as Build-Dependency? It's not listed in [build_linux.md](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md), so I wonder if that's deliberate (and if so why?) or a B-D that should be added?
ad 2) If you want to have pipewire support, which ofc I want, shouldn't ``libpipewire-0.3-dev`` be installed then as Build-Dependency (and thus added to the build instructions)?

### Mumble version

1.5.517

### Mumble component

Both

### OS

Linux

**Comment by Krzmbrzl** [comment]
The intended way is to just use the bundled libs. The no-bundled options are mainly there for distributors under the assumption that they'll know what packages to use as well.

As for the PipeWire support, adding it to the recommended build deps seems like a good idea. Mind creating a PR?

**Comment by diederikdehaas** [comment]
Distribution packagers often rely on the information given by the upstream project ;-)

> As for the PipeWire support, adding it to the recommended build deps seems like a good idea. Mind creating a PR?

Not at all :-) Can I also sort the list of dependencies *while I'm at it* and should that be in its own commit?

**Comment by Krzmbrzl** [comment]
> Distribution packagers often rely on the information given by the upstream project ;-)

I see :)

I mean, I don't have anything against adding the speexdsp package to the dependencies. So feel free to add that as well.

> Can I also sort the list of dependencies while I'm at it and should that be in its own commit?

For cleanliness sake a separate commit would be appreciated. 

Please note that both of these commits would be `DOCS` type commit as per our [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

**Comment by diederikdehaas** [comment]
Excellent, see here: https://github.com/mumble-voip/mumble/pull/6646

**Comment by diederikdehaas** [comment]
I had already theorized that ``libpipewire-0.3-dev`` would NOT be needed/useful as there isn't a config option to use the system library for that.
But I've just made 2 builds, with and without, and it made no relevant changes to the build output or the build log ... AFAICT.

I did notice the following:
- ``icons/hicolor/256x256/apps/mumble.png`` are binary different between the builds (different SHA256 value)
- ``mumble`` binaries are also different ... but that's also binary

The only differences between those builds are version: 1.5.634-0.2 vs 1.5.634-0.3 and the declaration of the Build-Dependency of ``libpipewire-0.3-dev`` but as stated above, that didn't result in relevant differences in the build log.

Just put one of those png files through ``xxd`` and then I saw ``Creation Time.2024-12-03T09:10:10-00:00`` and that matches the date of my 1.5.634-0.3 changelog entry (so that wouldn't be a problem for Reproducible Builds :-D)

Currently trying to kdiff3 the outputs of ``xxd mumble`` of the 2 versions, but I'm doubtful if that will be meaningful to me ...

While I don't understand what it means, it does seem that the difference is the same in 99% of cases!
I just copy-pasta-ed one example of it below:

```
0094bd70: 0193 8302 2098 0000 0012 0000 0000 0001  .... ...........
0094bd80: 0000 10d3 0000 0193 8302 2098 0000 00b0  .......... .....
0094bd90: 0000 0000 0001 0001 158b 0000 0193 8302  ................
0094bda0: 2098 0000 0188 0000 0000 0001 0006 703e   .............p>
0094bdb0: 0000 0193 8302 2098 0000 013c 0000 0000  ...... ....<....
0094bdc0: 0001 0001 869a 0000 0193 8302 2098 0000  ............ ...
```
(in my diff-view the blanks above are represented as a bit elevated dots)
vs
```
0094bd70: 0193 8bc8 c150 0000 0012 0000 0000 0001  .....P..........
0094bd80: 0000 10d3 0000 0193 8bc8 c150 0000 00b0  ...........P....
0094bd90: 0000 0000 0001 0001 158b 0000 0193 8bc8  ................
0094bda0: c150 0000 0188 0000 0000 0001 0006 703e  .P............p>
0094bdb0: 0000 0193 8bc8 c150 0000 013c 0000 0000  .......P...<....
0094bdc0: 0001 0001 869a 0000 0193 8bc8 c150 0000  .............P..
```

But it's consistently ``8302 2098`` vs ``8bc8 c150``

Any idea what that could be?

**Comment by davidebeatrici** [comment]
PipeWire and other backends are loaded at runtime and their development headers are bundled in this repository, meaning that there is no need for the development package to be installed.

> Any idea what that could be?

The build may be using the system-wide headers instead of the ones in this repository.

**Comment by diederikdehaas** [comment]
Yeah, my initial research already made it quite unlikely that ``libpipewire-0.3-dev`` would or could be used and AFAIC the different builds confirmed that.

I'm quite sure the difference isn't related to ``libpipewire-0.3-dev`` being installed or not and was mostly wondering for intellectual curiosity why there still was a binary difference, even though they're the same size in bytes.
With the PNG file I could track it down to difference in timestamp of my changelog entry and it could also be the case for the ``mumble`` binary, although I couldn't see it in the binary output.
But on Debian's Salsa CI ``reprotest`` job (reproducible build), it showed no issues, so probably not worth investing more time in :-)
