### ISSUE TITLE
Priority team chat (muting / attenuating main chat)

### ISSUE THREAD

**Issue by jaxankey** [mumble-voip/mumble#6647]
### Context

Managing audio with a main room and team/sub-rooms.

### Description

My understanding is it is possible to create a "main" room with many "team" rooms, simultaneously connect to the main and a team room, then hear everything from both. If I want to talk to just my team, I can bind a key to this. However, the team will then hear my voice plus whoever else is shouting in the main room. 

I'd like to have the option to push a button that prioritizes my voice to all those in my team by reducing / muting the noise from the main room, so they can actually hear me. 

### Mumble component

Both

### OS-specific?

No

**Comment by Hartmnt** [comment]
> I'd like to have the option to push a button that prioritizes my voice to all those in my team by reducing / muting the noise from the main room, so they can actually hear me.

Have you tried applying the "Priority Speaker" to yourself? If so, how would your feature request differ from that?

**Comment by jaxankey** [comment]
Are you able to bind a single button to simultaneously do "priority speaker" in the team and disable broadcasting to the main room?

**Comment by Hartmnt** [comment]
Ok, I seem to not quite understand what you mean. So when you are saying ``simultaneously connect to the main and a team room`` do you mean using channel listener, linked channels or literally 2 Mumble clients connected from your client?

What should be possible is: Have a main channel linked to one or multiple team channel(s). Configure them such that only clients in the main channel can hear the team channels by default. Then bind a key to whisper to a team channel. If you (or preferably all clients in main) have priority speaker set, you will then be speaking "over" the clients in the team channel when whispering.

But I am not sure if this is what you want.

**Comment by Hartmnt** [comment]
Mhh I guess you can *not* whisper to a channel (?) So that would be the thing you need right?

**Comment by jaxankey** [comment]
Close? I'd like everyone to join the noisy main discussion by default (talk and hear), but then be able to hold a button to only talk to their team as priority speaker.

**Comment by Hartmnt** [comment]
> Close? I'd like everyone to join the noisy main discussion by default (talk and hear), but then be able to hold a button to only talk to their team as priority speaker.

Ah ok. Well you could whisper to a group of users. Or alternatively an actual Mumble ACL group, I guess (using the "restrict to group" option) in the channel shout configuration.

**Comment by jaxankey** [comment]
Interesting. Okay so here's the full story:

We are playing a game involving 20 teams of 4 players. There are 50 people in the voice chat having great conversations and laughing the whole time. However, every few minutes, people need to communicate critical, time-sensitive information their team other above the noise, and it's basically impossible to get everyone to shut up.
________________________________
