### ISSUE TITLE
Documentation to build current release

### ISSUE THREAD

**Issue by roughnecks** [mumble-voip/mumble#6658]
### The issue

Hello,
after a chat on matrix room I was asked to file a report about an issue.

When following the documentation path from git master, to build mumble-server on debian, you are taken to:

https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md

But this doc is for Qt6, while Mumble 1.5.735 links against Qt5, so for current release the correct doc is at:

https://github.com/mumble-voip/mumble/blob/1.5.x/docs/dev/build-instructions/build_linux.md

### Mumble version

1.5.735

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
Not sure what such an explicit documentation would look like. The docs you get is always for the code you have checked out. If you want to build 1.5 but have checked out the master branch, you are on the wrong track already. 

And given that this applies to all docs, we would have to add such a note to every single file (as nobody ever only links to the docs root folder) which I don't think is a reasonable solution 🤔

@Hartmnt what did you have in mind?

**Comment by Hartmnt** [comment]
An additional sentence in the README to instruct users to use the docs on the branch you want to compile and maybe a warning on the building page itself to double check.

**Comment by Hartmnt** [comment]
> Wouldn't it be more sane to have releases from master and a dedicated `dev` branch for.. "development"?

Not really. Both are valid approaches and you need to remember that we are working on the next major release while back-porting to stable.

**Comment by Krzmbrzl** [comment]
> An additional sentence in the README

Which one? The one at the root of the build instructions? I think most folks will immediately click on the OS specific instructions, ignoring the README.

That being said, I don't have anything against adding a statement there.
