### ISSUE TITLE
Windows client crash 1.5.735

### ISSUE THREAD

**Issue by Scar1943** [mumble-voip/mumble#6659]
### Description

A hand full of my client installs that worked fine on 1.5.634 crash after 1.5.735 upgrade. It's NOT on every machine, only a hand full of windows 10 and windows 11 desktops. A removal and reinstall of 1.5.634 resolves the crash. Crash consists of just a flash of the dialog box, and vanish of the app. An occasional "crash report dialog" which I have filled out and sent in. Machines are both windows 11 pro and windows 10 pro machines. Are there newer windows libraries that are needed with the update? 

### Steps to reproduce

Use the update server stated in the start of the client.
Download the update.
Install the update.
Attempt to start mumble.

### Mumble version

1.5.735

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

I get the impression it is a library update that some of my older machines may not have? Can we get some info (if that is what it is) and perhaps a library download link.

**Comment by Tekwizz** [comment]
Hahaha, I was just going to login last night to report this exact same thing, but was delayed due to 2FA. Thanks for beating me to it, and that's exactly what happened to me, on a recently fully updated (last week) Win10 machine.

**Comment by Krzmbrzl** [comment]
Are all affected machines using the same Windows version? And do all machines have the same Visual C++ redistributable libraries installed?

**Comment by Hartmnt** [comment]
This is 99.9% caused by #6648

At this point we need a stack trace and probably @davidebeatrici :smiling_face_with_tear:

**Comment by Krzmbrzl** [comment]
I found https://github.com/conan-io/conan-center-index/issues/9546 but I would hope this is not the case in our case...

We should check whether the crash also happens with 1.6 snapshots. I would hope not.
If this is indeed the case, we could instead refactor the 1.5 code to go all-Qt for the filesystem handling instead of using boost filesystem.

**Comment by Krzmbrzl** [comment]
Error code `0xc0000005` means `Access violation` so my best guess would be that we are referencing an invalid (null?) pointer somewhere.

**Comment by Hartmnt** [comment]
@Tekwizz @Scar1943 Hi, here is an experimental build without our Unicode changes. Could you please check, if this experimental build also crashes? Note: I would not recommend using this as a daily driver. https://dev.azure.com/Mumble-VoIP/c819eb06-7b22-4ef3-bbcd-860094454eb3/_apis/build/builds/8981/artifacts?artifactName=Windows%20%28x64%29%20installer&api-version=7.1&%24format=zip

**Comment by Tekwizz** [comment]
Hi Harmnt, I just tried installing this 1.6.277 client on the same machine, and same situation, it disappears after two windows come up white for a moment, just like as with the 1.5.735 build.

**Comment by Scar1943** [comment]
I did try obvious things like running the client as admin, reinstall, etc. It does seem to be related to "older" windows 11 and 10. All my up to day windows 11 machines run fine. Windows 10, even current, won't run it. "FEELS LIKE" a windows library that isn't updated in 10, and odd windows 11 installs. Just a gut feeling.

**Comment by Scar1943** [comment]
> @Tekwizz @Scar1943 Hi, here is an experimental build without our Unicode changes. Could you please check, if this experimental build also crashes? Note: I would not recommend using this as a daily driver. https://dev.azure.com/Mumble-VoIP/c819eb06-7b22-4ef3-bbcd-860094454eb3/_apis/build/builds/8981/artifacts?artifactName=Windows%20%28x64%29%20installer&api-version=7.1&%24format=zip
> 
> Edit: For completeness and future reference, this is [56d44cc](https://github.com/mumble-voip/mumble/commit/56d44cc7b655d7a998b056a6740fc3b8a7356823)

Sorry, no difference. Thankfully, a windows uninstall, and reinstall of 634 is pretty easy to correct it. Did the new release require a newer version of some windows library that microsoft has dropped except in up to date 11 machines?

**Comment by Tekwizz** [comment]
The machine it's crashing on here, is an AMD A8 PRO-7600B Windows 10 22H2 build 19045.5011, yeah removing and reinstalling 634 is the fix so far. Well, yeah, I agree it does sound like dependency that's not being updated in Win 10.

**Comment by Scar1943** [comment]
Ok folks, looks like its the C++ 2022 Redistributable [x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)

Once I install that with the dowload page link, it seems to have resolved the problem with all my windows 10 machines.

https://aka.ms/vs/17/release/vc_redist.x64.exe

All my machine clients are now working.

**Comment by Krzmbrzl** [comment]
> nor is verifying it's installed.
 
#5549

**Comment by Hartmnt** [comment]
Damn in previous versions, the problem would manifest itself with a message box saying something like "MSVCP.dll not found" which was pretty easy to link towards missing dependencies.

I guess its very unfortunate that it now silently crashes... I guess we really have to somehow fix the installer for the next version.

**Comment by Krzmbrzl** [comment]
I don't think pinning an issue would really help...

**Comment by Krzmbrzl** [comment]
Well, if you are having a crash, you won't think by yourself that `Installer doesn't install VC++ redistributable` is the issue you are seeing. However, the issue title is correct in that it properly describes what the issue is, albeit not the exact symptom that can be caused by it. That is to say that I don't think renaming the issue would be the correct solution here.

**Comment by Krzmbrzl** [comment]
Oh. Okay now I get it :bulb: 
Yes indeed, that seems to make sense :+1:

**Comment by davidebeatrici** [comment]
This could potentially be related to appveyor/ci#3937.

I suspect ABI breakage in @microsoft's Visual C++.

**Comment by Tekwizz** [comment]
I'll confirm that as soon as I updated the Visual C++ library, without even a reboot, 1.5.735 runs fine!

The update:
14.32.31326 (5/8/2023)
14.42.34433

Funny that Windows update doesn't bother to update this...

**Comment by davidebeatrici** [comment]
Ideally the Visual C++ Runtime should be updated automatically, indeed, especially for security reasons.

In this specific case the lack of updates is even worse because the crash appears to be caused by a null pointer dereference.

**Comment by Hunweibyn** [comment]
Had same problem and reinstalling Visual C++ Runtime helped me too.
