### ISSUE TITLE
Windows preferences and settings location isn't unified

### ISSUE THREAD

**Issue by Porkepix** [mumble-voip/mumble#6662]
### Description

I was confirmed on Matrix the json settings files, the SQLite DBs and the other (empty for me) directories about plugins, overlays and so on are supposed to be located in the same place.

It appears that while almost everything is located into `%APPDATA%/Roaming/Mumble`, the newest `Json` settings files are located into `%APPDATA%/Local/Mumble`

### Steps to reproduce

N/A

### Mumble version

1.5.735

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
This is intentional. We use ``Qt::ConfigLocation`` for config files, and ``Qt::AppDataLocation`` for data files such as the database. This follows best practices and is not limited to Windows. In Linux the respective paths would be ``~/.config`` and ``~/.local/share``.
