### ISSUE TITLE
Sound delay when using Pulseaudio

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#978]
Distro: Debian Squeeze
Kernel version: 3.5.3
Sound card: CS5535 Audio

When I launched Mumble for the very first time, "Audio Tuning Wizard" opened to allow me to configure audio settings. I selected PulseAudio as the Input and Output device and advanced to the "Volume Tuning" screen. When testing the audio in this screen, I either did not hear any output or heard output with significant delay of more than 10 s, often garbled. 

When I stopped pulseaudio on the system and chose ALSA in the wizard instead, I did not experience these problems in the wizard and was able to get immediate audio output without any delay. 

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/978/ ._

**Comment by mkrautz** [comment]
I'll close this due to age. If this is still a problem, please re-open a new ticket. Thanks!
