### ISSUE TITLE
Overlay doesn't working with FOnline (OpenGL) under linux

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#979]
Hello guys, I've tried to use mumble-overlay in game called FOnline and it seems, that it doesn't working.
Under windows both FOnline.exe (ogl) and FOnlineD3D.exe (dx) are working with overlay, under Linux (Debian Wheezy) native FOnline, FOnline.exe with wine doesn't display overlay and FOnlineD3D.exe shows it.
If it helps, here's sdk repository for that game (giving link to sdk, because it's faster to download than downloading any game made with it)
https://xp-dev.com/svn/fonline_sdk/

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/979/ ._

**Comment by Krzmbrzl** [comment]
Does this issue persist in v1.3?
