### ISSUE TITLE
timeout flooding in murmur logs

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#981]
Server:
Murmur 1.2.3
WinXP Pro SP3
3GHz Pentium 4 with 2GB RAM

Constant flooding like this in my logs:

```
<W>2013-04-21 01:45:09.292 1 => <68:(-1)> Timeout
<W>2013-04-21 01:45:09.371 1 => <86:(-1)> Timeout
<W>2013-04-21 01:45:09.449 1 => <72:(-1)> Timeout
<W>2013-04-21 01:45:09.527 1 => <78:(-1)> Timeout
<W>2013-04-21 01:45:09.589 1 => <84:(-1)> Timeout
<W>2013-04-21 01:45:24.824 1 => <68:(-1)> Timeout
<W>2013-04-21 01:45:24.871 1 => <86:(-1)> Timeout
<W>2013-04-21 01:45:24.917 1 => <72:(-1)> Timeout
<W>2013-04-21 01:45:24.980 1 => <78:(-1)> Timeout
<W>2013-04-21 01:45:25.042 1 => <84:(-1)> Timeout
<W>2013-04-21 01:45:40.308 1 => <68:(-1)> Timeout
<W>2013-04-21 01:45:40.386 1 => <86:(-1)> Timeout
<W>2013-04-21 01:45:40.464 1 => <72:(-1)> Timeout
<W>2013-04-21 01:45:40.511 1 => <78:(-1)> Timeout
<W>2013-04-21 01:45:40.574 1 => <84:(-1)> Timeout
<W>2013-04-21 01:45:55.792 1 => <68:(-1)> Timeout
<W>2013-04-21 01:45:55.855 1 => <86:(-1)> Timeout
<W>2013-04-21 01:45:55.917 1 => <72:(-1)> Timeout
<W>2013-04-21 01:45:55.980 1 => <78:(-1)> Timeout
<W>2013-04-21 01:45:56.042 1 => <84:(-1)> Timeout
```

I saw this posted as a bug and closed [5 years ago](bugs:#111), but saw no reasonable solution in the thread.  I've been experiencing this problem for at least a year-- just never got around to reporting it.

We have no connection issues.  Things seem okay except for the flooding.

Restarting the server stops the flooding, but when left unattended the logs grow unnecessarily huge.  Has this issue been addressed in 1.2.4-RC?  I'm hesitant to upgrade at this point as the server is essential for raiding on a weekly basis.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/981/ ._

**Comment by Krzmbrzl** [comment]
Is this (still) reproducible in v1.3?
