### ISSUE TITLE
Strong certificate fails if user's stored cert hash is empty

### ISSUE THREAD

**Issue by fwaggle** [mumble-voip/mumble#982]
I think this qualifies as a bug.

Expected Behavior:
- Register a user via Ice, set email address and password
- User attempts to log in with strong certificate matching stored email address, and bypasses password auth.

Actual behavior:
- User attempts to log in and is prompted for a password, despite the strong certificate matching

Workaround:

Populate certHash in the DB via Ice, or use password auth to bootstrap the user, at which point strong certificates work as normal.

Cause:

In Server::authenticate(), "if (bStrongCert)" [1] is inside the block for "if (!certhash.isEmpty())" [2]. I'm not sure how to restructure it and I don't know if I'll have time to fix it, but I wanted it on my todo list for later.

1) https://github.com/fwaggle/mumble/blob/814ae5e129de4add9345f1a6084a8432d7c831df/src/murmur/ServerDB.cpp#L853
2) https://github.com/fwaggle/mumble/blob/814ae5e129de4add9345f1a6084a8432d7c831df/src/murmur/ServerDB.cpp#L845

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/982/ ._

**Comment by mkrautz** [comment]
@fwaggle 

From reading the current code, certhash wouldn't be empty even if you are not registered with the server yet.

All we need to do is to add something like this:

	QList<QSslCertificate> certs = uSource->peerCertificateChain();
	if (!certs.isEmpty()) {
		const QSslCertificate &cert = certs.last();
                // verify against emails in cert
        }

to the standard authenticate() path.

**Comment by Krzmbrzl** [comment]
Has this been fixed in 1.3?
