### ISSUE TITLE
Cryptic Studios games crash in some circumstances when Mumble overlay is enabled

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#983]
I'm sorry that at this time I don't have better details, as the crash reports frequently do not contain a mumble_ol DLL version numbers. Also, forum reports I've seen from customers are not incredibly detailed. I can inquire on the forums about the Mumble versions being used.

I have one crash dump with a mumble_ol.dll (not directly implicated in this particular crash)  with a timestamp of "2-19-2011 2:44 PM" but I'm not sure if that's just a Windows file modification timestamp. MSVC reports the module info as follows:

```
mumble_ol.dll   *C:\Program Files (x86)\Mumble\mumble_ol.dll    N/A N/A No matching binary found.       63  0.00.0.0    2/19/2011 2:44 PM   6A430000-6A453000   CrashDump.mdmp: Native  
```

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/983/ ._

**Comment by Krzmbrzl** [comment]
I kind of assume that this has been fixed in the meantime?
