### ISSUE TITLE
Proxy auth not working

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#985]
It happens in 1.2.3 and 1.2.4.

Here we only get the message "The connection requires authentication", despite typing user/pwd in the proxy config.

Look at this Question & Solution page, which directly suggests how to fix the current NetworkConfig.cpp code:
http://qt-project.org/forums/viewthread/20539

Can anyone fix this?

*This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/985/ .*

**Comment by hacst** [comment]
Read the forum thread linked. Sounds like a Qt bug to me. Someone should try whether this is still valid.

**Comment by mkrautz** [comment]
SOCKS5 auth works for me in the latest snapshot on Windows: 1.3.0~905~gda8a95e~snapshot

Tested using CCProxy 0.8 on Windows.
