### ISSUE TITLE
Importing Certifcate causes "Server Connection Failed" on OS X

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#993]
(Originally reported at https://sourceforge.net/apps/phpbb/mumble/viewtopic.php?f=4&t=1102 by wowsavvy).

Sorry to pester you, I'm on Mac OSX 10.8. Mumble and Murmur work well (newest releases), but I have an odd issue. I tried using the certificate wizard to import a certificate created by StartCom and Comodo, but upon switching to either of them, my server disconnects and says " Server connection failed: The remote host closed the connection." If Terminal is open, it says:
<W>2013-06-02 14:38:31.296 1 => <1:(-1)> SSL Error: The root CA certificate is not trusted for this purpose
<W>2013-06-02 14:38:31.297 1 => <1:(-1)> SSL Error: No certificates could be verified
<W>2013-06-02 14:38:31.298 1 => <1:(-1)> Connection closed: [-1]

As soon as I switch back to the self-made Certificate auto-created by Mumble on first use, the server comes back online. It's not a big glitch as I can still use both services fine, but as it was recommended to create a secure Certificate, I wanted to try one. Both certificates end in .p12 and were exported with Keychain access. Both say they were signed by an unknown authority, but I tried telling the Comodo one to be trusted and it still doesn't work. I have also reinstalled both Mumble and Murmur. 

No rush to reply! Thank you very much,
-Savvy

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/993/ ._

**Comment by mkrautz** [comment]
The problem here seems to be that Mumble doesn't handle incomplete certificate chains very well.

**Comment by mkrautz** [comment]
Fix is here: https://github.com/mumble-voip/mumble/pull/2336

**Comment by Krzmbrzl** [comment]
Merged via #3943
