### ISSUE TITLE
Mac os x text glitch in shortcuts setting page

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#995]
Just a small text glitch on the shortcuts preferences page, i have a shortcut as ctrl+`, but it shows the wrong character. see screenshot.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/995/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/995/attachment/mumble.png*

**Comment by Krzmbrzl** [comment]
This should be tested in 1.3

**Comment by ZeroAbility** [comment]
This will need tested in 1.4

**Comment by Krzmbrzl** [comment]
Given that nobody even tested it with 1.3 and there hasn't been any other activity here, let's just close this.
