### ISSUE TITLE
Mumble doesn't reconnect after sleep mode

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#996]
So, the title says itself. If you put your OS into a sleep mode and then go back, mumble never reconnects. Of course I have all these "reconnect automatically" option enabled. I guess that bug started with 1.2.3 beta, because I remember times when mumble always reconnected after sleep/suspend mode.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/996/ ._

**Comment by edo44** [comment]
It's 2016 and this wasn't fixed yet.

**Comment by mkrautz** [comment]
This has a high chance of being fixed by https://github.com/mumble-voip/mumble/pull/2622

I'll do a test on the various OSes once we're done massaging that PR.

**Comment by sztanpet** [comment]
not fixed, mumble also keeps the PC from auto-suspending

**Comment by mkrautz** [comment]
FWIW, @sztanpet, the potential fix was merged into master, which is 1.3.0.
It should be available in developer snapshot builds from https://www.mumble.info.

**Comment by sztanpet** [comment]
Yup, just noticed (and edited my earlier comment) thank you.
I have now tested with 1.3.0~1937~g289d0d4 and it does not reconnect after sleeping, the auto-suspend blocking I cannot test right now.

**Comment by sztanpet** [comment]
updated my comment with actual information :)

**Comment by sztanpet** [comment]
In case it helps, the `Disconnect` option in the  Server menu is not greyed out after coming back from sleep, it still thinks it's connected.
The connection error reported by mumble was:

    [09:54:42] Server connection failed: Server is not responding to TCP pings.

**Comment by mkrautz** [comment]
Thanks -- it should reconnect after receiving that error. I'm assuming it does not?

**Comment by sztanpet** [comment]
It does not, neither when the error was `[14:47:02] Server connection failed: The remote host closed the connection.`

**Comment by ZeroAbility** [comment]
Does this still happen, and is it happening on more than just Windows? An internet search is littered with issues with sound after sleep/suspend/hibernate which may require restarting the sound service, updating the audio drivers, or disabling power plans/settings entirely to resolve the issue. Are other sounds affected by this?
