### ISSUE TITLE
Audio in and out stops working after X amount of time.

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#997]
I've had this issue start anywhere from 20 minutes after logging in to a few hours after.  I've always had the audio disconnect happen during a lull in conversation, never cut anyone off mid stream.

The issue occurred on Win7 and Win8. And the beta versions of 1.2.4 had this issue as well.

From my end I see the mouth go red when I hit push to talk, no one sees my mouth go red though.  No one else seems to have an issue when it happens to me, they continue talking thinking I'm there listening (as do I)

I have been resolving the problem by restarting the program.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/997/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/997/attachment/DxDiag.txt*

**Comment by Krzmbrzl** [comment]
Does this issue still exist in 1.3?
